### ISSUE TITLE
Folder deleted after post processing failed

### ISSUE THREAD

**Issue by card78** [pymedusa/Medusa#10018]
**Describe the bug**
As per the title. My post processing directory does not only contain TV shows. It will delete folders that are not in the list of TV shows.

**To Reproduce**
1. Go to Settings -> Post-Processing, make sure that "Don't delete empty folders" is disabled, and that "Processing Method" is set to Move.
2. Copy a folder that is not in the list of TV shows.

Perhaps I'm not using medusa properly. In which case, feel free to close this ticket.
Thanks for this wonderful software.

**Comment by medariox** [comment]
You should enabled Don't delete empty folders if you don't want the folders to be removed.

**Comment by card78** [comment]
Thank you. I'll close this now.
