### ISSUE TITLE
Tv show video files disappeared after updating to the latest version.

### ISSUE THREAD

**Issue by jameejay** [pymedusa/Medusa#10023]
I'm running TrueNAS 12u6 with Medusa in a jail. 

After I updated to the latest Medusa version, I noticed my shows disappeared from my server. 

I since rolled Medusa back to an earlier version (below), and now shows reappeared. 

Branch: master
Commit: 21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6
Version: 0.5.18
Database: 44.18
Python Version: | 3.7.9 (default, Oct 3 2020, 01:26:44) [Clang 10.0.0 (git@github.com:llvm/llvm-project.git llvmorg-10.0.0-0-gd32170dbd
SSL Version: | OpenSSL 1.0.2s-freebsd 28 May 2019
OS: | FreeBSD-12.2-RELEASE-p10-amd64-64bit-ELF

**Comment by p0psicles** [comment]
In which version you noticed this? 
We're now on version 0.5.20.

Do you have any logs (debug) from this happening?

**Comment by p0psicles** [comment]
Did this started with 0.5.19? 
Maybe related to postprocessing? 
What do you mean with, shows now reappeared?

**Comment by jameejay** [comment]
It was yesterday that I updated Medusa and noticed the issue. I'm assuming it was  0.5.20.

> In which version you noticed this? We're now on version 0.5.20.
> 
> Do you have any logs (debug) from this happening?

**Comment by jameejay** [comment]
I'm using Medusa > Sabnzb. I believe the processing happens in Sab. 

![image](https://user-images.githubusercontent.com/30181160/139927026-367be0e1-20fb-4caa-bbfe-081821057e5a.png)

**Comment by jameejay** [comment]
I used TrueNas snapshots from a couple of days ago. I used that to roll back the jail Medusa is in, and the dataset connected to it which has the videos. After rolling back those items the videos reappeared and the Medusa version was from a couple of days ago.

**Comment by p0psicles** [comment]
Okay. We re-released today to 0.5.20.
A change related to postprocessing has been reverted in it. So you should be okay upgrading to 0.5.20

**Comment by jameejay** [comment]
> Okay. We re-released today to 0.5.20. A change related to postprocessing has been reverted in it. So you should be okay upgrading to 0.5.20

I'll update and check back in.

**Comment by p0psicles** [comment]
You have /media/Shows. That is a temporary folder right? Where do you store your shows?

**Comment by jameejay** [comment]
It's a mounting point that connects/points to my TrueNas dataset. 

Medusa/media >>>> PlexMedia/Movies
Medusa/media >>>> PlexMedia/Shows

**Comment by p0psicles** [comment]
Do you use root folders? Set up in config -> general?

**Comment by jameejay** [comment]
![image](https://user-images.githubusercontent.com/30181160/139929050-0a8745e6-696a-47d0-87f0-6028d85b0eae.png)


> Do you use root folders? Set up in config -> general?

**Comment by jameejay** [comment]
![image](https://user-images.githubusercontent.com/30181160/139929529-49e13a4d-08c3-428d-9160-1d9469f1c365.png)

**Comment by p0psicles** [comment]
That's the same folder?! You should really not do that. I now understand what went wrong. And I know this worked in the past. But thats really not how it should have been set up. Postprocess folder is like a scratch dir. It processes and cleans up. And the show root dir is the final destination.
