### ISSUE TITLE
Latest verison 5.20 is doing some strange things

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#10028]
**Describe the bug**
I have noticed that some episodes that it processes seem to vanish.  I have recycle bins and they don't always end up there.

Now I just found this;
![image](https://user-images.githubusercontent.com/14140816/140063279-92bac237-015f-42f8-889d-c44a62a2c4d2.png)

This show does not exist, down-loader never downloaded this (not with that name)

If I click on one of the episodes I get This;
![image](https://user-images.githubusercontent.com/14140816/140063695-9c2686e3-82a4-4d3f-b8fe-119600122a65.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
 Medusa Info:	Branch: master
Commit: 729ab4f066034709137edb43440dba7c84959626
Version: 0.5.20
Database: 44.18
 Python Version:	3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
 SSL Version:	OpenSSL 1.1.0j 20 Nov 2018
 OS:	Windows-7-6.1.7601-SP1
 Locale:	en_US.cp1252
 Timezone:	Eastern Daylight Time

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**
I went through the logs, no errors that point to the post processing operation.
And of course that Missing Show is missing....   I am looking through all the media folders to see where it may have been placed.
I will add updates as I find things.

**Comment by walterhpdx** [comment]
I opened a ticket a few days ago when I discovered this ([here](https://github.com/pymedusa/Medusa/issues/10019)). It's a defect, and you should have an update available. Once you update, the behavior should go back to normal.

Alternatively, you can change "Move" to "Copy" in post-processing to stop this behavior until you get the updated code.  Unfortunately, you will have to go through and find what was deleted and re-download it manually.

Good luck!

**Comment by nydave69** [comment]
> I opened a ticket a few days ago when I discovered this ([here](https://github.com/pymedusa/Medusa/issues/10019)). It's a defect, and you should have an update available. Once you update, the behavior should go back to normal.
> 
> Alternatively, you can change "Move" to "Copy" in post-processing to stop this behavior until you get the updated code. Unfortunately, you will have to go through and find what was deleted and re-download it manually.
> 
> Good luck!

I am on the latest...  This is since the update 5.20 two days ago....

**Comment by walterhpdx** [comment]
There was new code yesterday.

Regardless, change post-processing "Move" to "Copy" to get rid of the issue. You'll have cleanup to do after, but it's worth not losing data.

**Comment by nydave69** [comment]
UPDATE:
Missing Show = The Love Boat        A better quality was downloaded with a Show year of 1976
Looks like over time the show year has changed between 1976 and 1977  (episodes have both dates mainly 1977)
But it looks like when an episode is found with a scene exception year of 1976 it add it to the correct show folder with that year but may not remove the other episode.
That folder had episodes with different show years, quality, and the supporting files for all ie NFO, jpg, srt

I have checked other shows and found the same mess in some seasons.
in the process of cleaning that up...

I think this may have been the result of Medusa trying to figure out that folder, and went the best way it could and named them using the year 1976,  The Love Boat (1976) doesn't exist but (1977) does and it shows it updated correctly with the episodes having a (1976) show date.   (I think that theTVDB returns a 1976 show date  rather than the correct one 1977, that would have to be tested) 

I'll keep a closer watch and see if it happens again....

**Comment by nydave69** [comment]
> There was new code yesterday.
> 
> Regardless, change post-processing "Move" to "Copy" to get rid of the issue. You'll have cleanup to do after, but it's worth not losing data.

I don't remember seeing      change post-processing "Move" to "Copy"       that change posted by anyone from Medusa.
I know they said they reverted the code back to previous version in the newer 5.20 update that I did update to.

For me to change "Move to Copy" will create a new set of issues for me..

**Comment by p0psicles** [comment]
Do you use the same folder as the postprocessing folder as the root folder for your shows?

**Comment by nydave69** [comment]
> Do you use the same folder as the postprocessing folder as the root folder for your shows?

NO

Downloader has a working folder for all downloads      O:\utorrent\newDownload75
It moves completed downloads by type to O:\utorrent\completedDownload\MU in this case
Medusa finds completed in O:\utorrent\completedDownload\MU and move it based on the show to one of the following;
O:\series\
N:\series\Battlestar Galactica (1978)
M:\series\

This has worked for me for years....  10+

**Comment by p0psicles** [comment]
That's how it should be. Then your issue is not related to the recent changes.

**Comment by nydave69** [comment]
> That's how it should be. Then your issue is not related to the recent changes.

I agree,
I posted another thread  about the show's year changing in the online databases. 

Think that's what happen here, didn't discover that right off since I didn't know that "Missing Show" was not a show title but it was a reference that it  couldn't find that show in my database.
I think that caused the issue in this case.

that other thread took a look at a different show, and at the end I added a so called feature request..

**Comment by neo-neo1** [comment]
By any chance do you have Trakt.tv enabled? I also came across a strange scenario of already downloaded shows being delete, however I'm not sure if it's related to your issue or just a coincidence.

**Comment by nydave69** [comment]
I found some episodes in places they should not be.  But still within the normal path where things get placed.
I cannot confirm if that was due to Medusa or not since I cleaned things up before they were discovered.
I'm tracking this, will update then I know more..
