### ISSUE TITLE
[APP SUBMITTED]: FileNotFoundError: [Errno 2] No such file or directory: 'I:\\Downloads\\Bull (2016) - 6x05 - King Bull.mkv'

### ISSUE THREAD

**Issue by WarEagleUS21** [pymedusa/Medusa#10035]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@729ab4f066034709137edb43440dba7c84959626
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-11-06 14:46:02 ERROR    POSTPROCESSQUEUE-POST-PROCESS :: [729ab4f] OSError: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "C:\Medusa\Python\lib\shutil.py", line 563, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'I:\\Downloads\\Bull (2016) - 6x05 - King Bull.mkv' -> 'J:\\TV Shows\\Bull (2016)\\Season 6\\Bull - 6x05 - King Bull.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/729ab4f066034709137edb43440dba7c84959626/medusa/helpers/__init__.py#L320">medusa\helpers\__init__.py</a>", line 320, in move_file
    shutil.move(src_file, dest_file)
  File "C:\Medusa\Python\lib\shutil.py", line 578, in move
    os.unlink(src)
PermissionError: [WinError 5] Access is denied: 'I:\\Downloads\\Bull (2016) - 6x05 - King Bull.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/729ab4f066034709137edb43440dba7c84959626/medusa/helpers/__init__.py#L293">medusa\helpers\__init__.py</a>", line 293, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "C:\Medusa\Python\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'I:\\Downloads\\Bull (2016) - 6x05 - King Bull.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment]
It looks like Medusa doesn't access to the path you specified.
Is this a mapped network drive? If so, make sure the account under which Medusa runs can access it.
It is better to work with a symlink as those are machine wide and not per user.
See https://github.com/pymedusa/Medusa/issues/6418#issuecomment-484594878

**Comment by WarEagleUS21** [comment]
Ok I can do that. It's not a network drive, it's actually plugged in via
USB 3.0. I can try changing to Symlink

**Comment by Rouzax** [comment]
That is weird, USB should be visible machine wide.
Can you browse to the location via `Manual Post-Processing`
![image](https://user-images.githubusercontent.com/4103090/141117739-2307f4bf-4a03-4488-b858-b88c053aad0d.png)

![image](https://user-images.githubusercontent.com/4103090/141117653-321f6d9b-48b9-4cc9-89fc-e10b5b120f5e.png)

**Comment by WarEagleUS21** [comment]
Yes. I send it to my internal Drive and then Move it over to my External USB Drives. It shows my I:\Downloads folder so I guess it was just a hiccup. I wouldn’t worry too much about it because for the most part 98% of this works.

**Comment by Rouzax** [comment]
The only thing I can think of then is that the usb drive was powered down / sleep mode

**Comment by WarEagleUS21** [comment]
Probably right. Go ahead and close this. Thanks for your help.
