### ISSUE TITLE
Recent Change Broke My Internal Automation

### ISSUE THREAD

**Issue by LeeThompson** [pymedusa/Medusa#10031]
**Describe the bug**
I've been using my own automation to trigger daily searches in the evenings (and have it be light on them during the day).
(Basically I have medusa set to do daily search twice a day; but I have a Windows scheduled task on another machine that issues a forceSearch every 45 minutes from 6pm to 1am.)

Recently Medusa made changes so now it no longer works.

Basically, my task works real simply:
`curl "http://medusa_ip:medusa_port/manage/manageSearches/forceSearch"`

(I'm not using the API because the API doesn't support this.)

I noticed this evening, that this isn't working any longer.

**Medusa (please complete the following information):**
 - OS: Debian (host) (docker container)
 - Branch: master
 - Commit: e094759640ca61c5c033bf1ff9d33bc7fc1ba857
 - Python version: 3.8.10
 - Database version: 44.18

**Debug logs (at least 50 lines):**
Not applicable.

**Additional context**

**Comment by p0psicles** [comment]
ForceSearch is available through the apiv2 now. 
I'll cook up a curl command when I have time.

**Comment by LeeThompson** [comment]
I tried it but it's not working, maybe this isn't the right command?  (I poked in the js files to find this)

```
@echo off
setlocal

set medusa_host=http://medusa.sgc.logh.net:8001
set apikey=your_api_key
call :get_token
call :send_api_command "search/daily"
goto :eof

:send_api_command
set api_command=%~1
if not defined apitoken echo No API Token&&goto :eof
curl -H "Authorization: Bearer %apitoken%" -X POST "%medusa_host%/api/v2/%api_command%" 2>nul
goto :eof

:get_token
set "apitoken="
for /f "tokens=2" %%a in ('curl -d "x-api-key=%apikey%" -X POST "%medusa_host%/api/v2/authenticate"') do set temp=%%a
set temp=%temp:"=%
set "temp=%temp:~0,-1%"
set apitoken=%temp%
goto :eof
```

**Comment by LeeThompson** [comment]
Think I found it, it looks like it needs to be -X PUT not POST.
