### ISSUE TITLE
[BUG] Trakt Duplicates Shows Not Matching Default Indexer

### ISSUE THREAD

**Issue by neo-neo1** [pymedusa/Medusa#10073]
**Describe the bug**
Enabling Trakt with a preexisting Medusa library duplicates Medusa's shows not matching Trakt `Default indexer` option.
Example: If your Medusa library has 5 shows added via TVDB and 10 shows added via TVmaze and you enable Trakt all 10 TVmaze shows will be duplicated and added via TVDB. Trakt defaults `Default indexer` to `tvdb` and does not cross reference.

**To Reproduce**
Add various shows to Medusa as you normally would but ensure you choose TVDB, TVmaze, and TMDB from indexer column. Goal here is to ensure your Medusa library has shows added using different indexers.

Then authenticate and configure Trakt with the following options: 
-  Enable -> `On`.
- API Timeout `30`
- Default indexer -> `tvdb`
- Sync libraries -> `Off`
- Sync watchlist -> `On`
- Watchlist add method -> `Get whole show`
- Remove episode -> `On`
- Remove series -> `On`
- Remove watched show -> `Off`
- Start paused -> `Off`

Then either wait for sync or press `Force Sync` to avoid waiting. Now Trakt will start syncing and duplicating Medusa's shows not added via Trakt's `Default indexer` option (default is TVDB).

**Problem Theory:**
Medusa adds it's existing library of shows to your Trakt list account. Then Medusa starts pulling said shows from Trakt to itself. It doesn't cross reference shows not using tvdb (Default Indexer option) and duplicates all shows not using tvdb. It's not always perfect either at duplicating and sometimes will pick another show with a similar name (e.g. I had `The Haunting of Hill House` in Medusa's library but it duplicate added `The Haunting` instead).

**Suggestion:**
Add option to disable Medusa pushing it's library to Trakt. If option existed to disable 2-way syncing this issue wouldn't occur in the first place. Most users only need Medusa to add shows from Trakt lists. We only need Medusa to pull from Trakt and not Medusa to push to Trakt.

**Medusa**
 - Branch: Master
 - Version: 0.5.20
 - Python version: 3.8.10
 - Database version: 44.18

**Comment by p0psicles** [comment]
So you saying that:
1. show x is manually added in medusa using tmdb
2. show x is pushed to trakt and added to the trakt watchlist
3. show x is pulled from trakt and again added using tvdb?

**Comment by neo-neo1** [comment]
> So you saying that:
> 
> 1. show x is manually added in medusa using tmdb
> 2. show x is pushed to trakt and added to the trakt watchlist
> 3. show x is pulled from trakt and again added using tvdb?
> 
> Do you have an example show where this happened for you? So I can reproduce?

Correct

**Comment by neo-neo1** [comment]
> So you saying that:
> 
>     1. show x is manually added in medusa using tmdb
> 
>     2. show x is pushed to trakt and added to the trakt watchlist
> 
>     3. show x is pulled from trakt and again added using tvdb?
> 
> 
> Do you have an example show where this happened for you? So I can reproduce?

Correct. It happens literally to any show not added via `tvdb`. 
No example needed, but [Vikings](https://www.imdb.com/title/tt2306299/) was one of many which was duplicated.

**Comment by netty0** [comment]
This issue has existed for eternity and was a major driver I adopted Sonarr. There's zero need nor demand for Medusa to push it's library to Trakt.tv. This needless feature needs cross indexer de-duplication (Xem perhaps) to function properly. I suggest removing this worthless "feature" all together as simply doing so would fix it. Instead use your valuable time to implement multiple lists -  which is practically required by Trakt users. This is my only Medusa holdout as I do wish to switch back.

**Comment by p0psicles** [comment]
Yes I'll fix this when I get time for it.
