### ISSUE TITLE
Update MoreThanTV

### ISSUE THREAD

**Issue by Kosmatik** [pymedusa/Medusa#10090]
**Describe the bug**
MoreThanTV is up on a new URL.

**To Reproduce**
1. Go to https://www.morethantv.me

**Expected behavior**
Updated URL in medusa and taken out of broken providers.

**Medusa (please complete the following information):**
 - OS: Linux-5.10.28-Unraid-x86_64-with
 - Branch: master
 - Commit:  918cfe7ce01808499585ffe6c1356fd5ed369f76
 - Python version: 3.8.10 (default, May 6 2021, 06:30:44) [GCC 9.3.0]
 - Database version: 44.18

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

2021-11-13 17:18:36 INFO	MAIN :: [918cfe7] Broken providers found: ['danishbits', 'morethantv']
</details>

**Comment by p0psicles** [comment]
if you can hop on to discord, I could give it a shot

**Comment by p0psicles** [comment]
Alternative could be checking in with the guys at prowlarr. And use prowlarr when they have it added.
https://github.com/Prowlarr/Indexers/pull/27#issuecomment-909363587

**Comment by Kosmatik** [comment]
@p0psicles check general channel on discord

**Comment by p0psicles** [comment]
@Kosmatik are you able to test the linked PR/branch?
