### ISSUE TITLE
Kodi NFO Metadata Missing Trailer Field and others

### ISSUE THREAD

**Issue by neo-neo1** [pymedusa/Medusa#10097]
Kodi (Kodi 12+) NFO metadata lacks a few fields. Comparing Kodi metadata NFO files generated by Sonarr (and Jellyfin/Emby) this becomes evident. 

[Several fields missing](https://kodi.wiki/view/NFO_files/TV_shows) such as `trailer`, `status`, and etc...

Omiting `trailer` field disables ability for Kodi (and others) to provide clip previews. If indexer provides it please include it.

Kodi Trailer Field Syntax: `<trailer>plugin://plugin.video.youtube/play/?video_id=IDHERE</trailer>` The rest are straight forward.

Thank You

**Comment by p0psicles** [comment]
We can only place data in the nfo that we also keep stored in the db for the show.
We don't store the trailer url. We do have info on the status. So I could take a look at that if we don't send it already.

**Comment by netty0** [comment]
> We can only place data in the nfo that we also keep stored in the db for the show.
>
> We don't store the trailer url. 

It’s unfeasible to scrape trailers? Disappointing.


> We do have info on the status. So I could take a look at that if we don't send it already.
>

Please also cross reference other missing fields with the link. I didn’t check the code for completeness. 

A family member noticed TV show information is less detailed when compared to (Radarr generated) movie information. They make use of trailers in Kodi often. 

Thank you

**Comment by p0psicles** [comment]
yeah well it's not impossible to send additional data. Just have to go back to the indexer's api to get more data. But this is not an issue, but more a feature request.
