### ISSUE TITLE
 [729ab4f] Unhashable type encountered. Please report this warning to the developers.

### ISSUE THREAD

**Issue by roil13** [pymedusa/Medusa#10101]
```
2021-11-17 07:02:55 WARNING  SEARCHQUEUE-BACKLOG-72073 :: [729ab4f] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
```

Running Medusa on RPi 4.

**Comment by p0psicles** [comment]
Just this warning is pretty useless. Well need a surrounding debug log. 

Please also fill in the issue template

**Comment by roil13** [comment]
> 
> 
> Just this warning is pretty useless. Well need a surrounding debug log.
> 
> Please also fill in the issue template

Medusa works well, I just saw this warning and did as instructed. I've enabled logging in debug level and I will add it to here when the warning will pop up again. Should I fill the issue template anyway?

(asking because I'm new here and don't know the proper way to report things)

**Comment by roil13** [comment]
[medusalog.txt](https://github.com/pymedusa/Medusa/files/7553288/medusalog.txt)

**Comment by medariox** [comment]
Enable debug logs > restart > post new debug logs.

**Comment by roil13** [comment]
[medusalog.txt](https://github.com/pymedusa/Medusa/files/7649839/medusalog.txt)

**Comment by medariox** [comment]
```
2021-12-03 13:04:16 WARNING  SEARCHQUEUE-BACKLOG-72073 :: [f35a19d] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
```
That's the interesting part.

**Comment by medariox** [comment]
The next version will have a more detailed error. Please report again if it still happens.
