### ISSUE TITLE
Force Full Update not Updating .nfo Files

### ISSUE THREAD

**Issue by neo-neo1** [pymedusa/Medusa#10109]
Currently `Force Full Update` button does not update .nfo metadata files.

**Why this matters**
When users add shows before season is released episode names are often added as `TBA` in Medusa. When season is finally released and episode names are known Medusa will still rename all episode names to `TBA` upon post processing. But main problem is episode names are also added as `<title>TBA</title>` within .nfo metadata files. By default Kodi, Plex, etc... display episode names parsed from .nfo files and thus all episode names are `TBA` when displayed to user. The `Force Full Update` button only updates episode names within Medusa itself. You're forced to manually delete .nfo files and then run `Force Full Update` so Medusa will generate .nfo files with proper episode names. This also applies to updating episode plot in .nfo files.

**Comment by p0psicles** [comment]
@medariox do you know why the decision ever was made to only write the nfo files once?
I'm thinking of drawbacks for overwriting on each show/episode update?

**Comment by neo-neo1** [comment]
Also it would be ideal for `Force Full Update` to also pull all new photo metadata files (e.g poster, banner, etc...). Currently you must delete respective files for Medusa to pull new updated photo metadata files.

**Comment by fexofenadine** [comment]
IIRC Radarr and Sonarr handle this by generating a new .nfo file, comparing the hash of it to the existing .nfo file and then replacing it if the hashes are different.

Not sure if there's a benefit to doing it this way but it seems pretty elegant

**Comment by neo-neo1** [comment]
> IIRC Radarr and Sonarr handle this by generating a new .nfo file, comparing the hash of it to the existing .nfo file and then replacing it if the hashes are different.
> 
> Not sure if there's a benefit to doing it this way but it seems pretty elegant

Radarr/Sonarr actually does something more fancy if a file gets downloaded with `TBA` metadata. It will hold off importing the file up to 24hrs while it auto checks (TVDB I believe) indexer for new metadata every 6 hours (limit is 24hrs).

This works for episodes which are released without known metadata as usually TVDB... will update respective information with 24hrs. Since it holds off importing it will also hold off renaming episode filenames to `TBA`. Though there are obvious drawbacks for those users who expect to instantly watch downloaded episodes.

**Comment by p0psicles** [comment]
I've introduced a new option, named overwrite_nfo.
It's in the attached PR.

**Comment by neo-neo1** [comment]
> I've introduced a new option, named overwrite_nfo.
> It's in the attached PR.

> I've introduced a new option, named overwrite_nfo.
> It's in the attached PR.

Thanks! Perhaps in a future version there can be a scheduled task to check for missing metadata and update it automatically similarly to Sonarr
