### ISSUE TITLE
[BUG] Update Show in Kodi - Broken

### ISSUE THREAD

**Issue by neo-neo1** [pymedusa/Medusa#10111]
**Describe the bug**
Clicking `Update show in KODI` button is broken.

**Screenshots**

<img width="221" alt="ScreenShot 2021-11-21 at 12 21 53 PM" src="https://user-images.githubusercontent.com/6996362/142772443-4d5b00eb-ad61-49d8-88a3-816dc0ec0565.png">

**Logs:**

```
DEBUG	TORNADO :: Failed doing web ui get request 'updateKODI': Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 218, in get
    method = getattr(self, route)
AttributeError: 'Home' object has no attribute 'updateKODI'
```
</details>

**Additional context**
Medusa's Kodi notifications work properly upon episode downloads but this specific button and it's function does nothing.

**Medusa:**
- Version: 0.5.20 
- Branch: master
- Python version: 3.8.10
 - Database version: 44.18

**Comment by p0psicles** [comment]
Yeah I know. I'm just struggling with finding the time to fix all the issues

**Comment by neo-neo1** [comment]
No worries. Just cataloguing the issue. Thanks for all you do.
