### ISSUE TITLE
timestamp out of range for platform time_t

### ISSUE THREAD

**Issue by sterlingphoenix** [pymedusa/Medusa#10127]
This started happening a few days ago with no updates taking place anywhere. 

This happens on a Raspberry PI running Raspberry PI OS -- I was running Buster but I upgraded to Bullseye and the issue is still there. These are both 32-bit operating systems, and I assume timestamp crossed the threshold that 32-bit can support. 

Right now it makes the schedule not display -- I'm not sure if it also prevents shows from being downloaded and without a schedule I can't really confirm.

**To Reproduce**
Run Medusa on a Raspberry PI with Raspberry PI OS

**Expected behavior**
Schedule should display.

**Medusa (please complete the following information):**
 - OS: Raspberry PI OS Buster and Bullseye
 - Branch: master
 - Commit: 2f6a13036d9871a9abaec84421f279fe9e906427
 - Python version: 3.7.3 and 3.9.
 - Database version: 44.18

**Debug logs (at least 50 lines):**
<details>

```
2021-11-23 21:08:09 ERROR    TORNADO :: [2f6a130] Uncaught exception in APIv2: OverflowError('timestamp out of range for platform time_t')
Request: GET /api/v2/schedule?category[]=later&category[]=missed&category[]=soon&category[]=today&paused=true (192.168.0.99)
Traceback (most recent call last):
  File "/opt/**********/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/**********/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/**********/**********/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/opt/**********/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/**********/**********/server/api/v2/schedule.py", line 46, in get
    'localAirTime': show_air_time.replace(microsecond=0).isoformat(),
  File "/opt/**********/ext/dateutil/tz/tz.py", line 222, in utcoffset
    if self._isdst(dt):
  File "/opt/**********/ext/dateutil/tz/tz.py", line 291, in _isdst
    dstval = self._naive_is_dst(dt)
  File "/opt/**********/ext/dateutil/tz/tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OverflowError: timestamp out of range for platform time_t```

```
</details>

**Additional context**
N/A

**Comment by BenjV** [comment]
Timestamp problems using 32 bits are becoming a problem for dates after 19 januari 1938, so I doubt that is the problem here.
Also the Linux kernel was patched in 2018 to fix this problem and it has little to do with 32 bit versions, the old 64 bit Linux had the same problem because it also stored the timestamp in 4 bytes

So most OS versions have already fixed this issue and it is most certainly not  a Python issue, because python timestamps are stored as floats.

And without posting the log files it is impossible to investigate this problem.

**Comment by sterlingphoenix** [comment]
> And without posting the log files it is impossible to investigate this problem.

I did include the full error from the log, with debug enabled. That is the only error/exception/warning.

**Comment by BenjV** [comment]
Sorry I forgot to open the details to see you log.

All Linux system cannot handle time stamps before 1 januari 1970 and some old systems (and so maybe a raspberrypi OS) no dates after 1 januari 2038.
So most likely there is some strange date used somewhere.

**Comment by sterlingphoenix** [comment]
I know about the 32-bit Y2K38 problem. But the date on the system is correct, the locale is correct, the timezone is correct... I don't know where to go from here to debug this.

**Comment by BenjV** [comment]
Maybe the timestamp from some file?

**Comment by sterlingphoenix** [comment]
Good suggestion, but I checked and no files that Medusa touches have a modification time in the future ):

**Comment by BenjV** [comment]
You should look at the creation time not the modification time and a date before 1970 is more likely.
A nd browsing the database can be done with this Windows application.
https://sqlitebrowser.org/dl/

**Comment by sterlingphoenix** [comment]
I checked both creation and modification time, both in the future and well in the past, and found nothing, so that's not it. 

I don't have a Windows machine, but what I was really asking was what kind of database and where it lives, but I can figure that out and get a sqlite client. 


With that said, the error is when this line happens: 

``return time.localtime(timestamp + time.timezone).tm_isdst``

So I don't think it really is a file/database thing...

**Comment by BenjV** [comment]
The function time.localtime() converts the number of seconds since the epoch (1 januari 1970) to localtime.
The variable timestamp is so big that the result is past 1 jan 2038.
So you have received a schedule of a show with a completely wrong date which the your OS cannot handle.

**Comment by sterlingphoenix** [comment]
Ah. So it's something that's currently displayed on the schedule... that makes sense. 

I wonder if I can go show-by-show and see if any individual show has bad timestamps or also crashes the display...

**Comment by p0psicles** [comment]
You should check out the main.db file. And look in  tv_episodes table

**Comment by sterlingphoenix** [comment]
@p0psicles @BenjV Thank you both -- there was indeed a show in the database with an airdate of 11/25/2921... I've nuked that record from the database and all is OK now.

Thanks again!
