### ISSUE TITLE
Downloadhandler not working for Downloadstation NAS?

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#10153]
![image](https://user-images.githubusercontent.com/15545810/145014601-f470c5c1-0cb7-44e6-8e94-77f9f0c4ec78.png)

![image](https://user-images.githubusercontent.com/15545810/145014531-65d158e1-4eab-4243-aa29-a369bcf98a29.png)

<html>
<body>

Medusa Info: | Branch: masterCommit: f35a19da6bc4efcafff8facca6a4d5b9e3f3f501Version: 0.5.20Database: 44.18
-- | --
Python Version: | 3.8.12 (default, Oct 22 2021, 21:05:38) [GCC 7.5.0]
SSL Version: | OpenSSL 1.1.1l 24 Aug 2021
OS: | Linux-4.4.180+-x86_64-with-glibc2.2.5
Locale: | en_US.UTF-8
Timezone: | CET

</body>
</html>

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-12-07 11:34:41 ERROR    DOWNLOADHANDLER :: [f35a19d] Exception while checking torrent status. with error: 'DownloadStationAPI' object has no attribute 'get_status'
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/medusa/schedulers/download_handler.py", line 389, in run
    self._update_status(torrent_client)
  File "/volume1/@appstore/medusa/src/medusa/schedulers/download_handler.py", line 176, in _update_status
    status = client.get_status(history_result['info_hash'])
AttributeError: 'DownloadStationAPI' object has no attribute 'get_status
```
</details>

**Comment by p0psicles** [comment]
Download handler doesn't work with download station. I don't have a Synology myself. So I couldn't add that integration. I'll make sure do add some error / configuration handling for this

**Comment by ward0** [comment]
@p0psicles Thank you for your information, I will go back to scheduled Post-Processing for now.
The reason that I swichted between the 2 was because my downloads stay in snatched and don't go into downloaded state :(

**Comment by p0psicles** [comment]
You should share screenshots for your postprocessing config. Like where does the client keep it's incomplete / complete data. Where you pp from. Etc. 

Maybe a debug log of a scheduled pp, when it should process a download

**Comment by ward0** [comment]
@p0psicles I switched back and suddenly my snatched went into downloaded state for some reason. Problem solved for now.
Would be nice to be able download handler in combination with DownloadStation in the future.
