### ISSUE TITLE
BUG: When source drive unavailable: everything marked as Archived

### ISSUE THREAD

**Issue by eddywitkamp** [pymedusa/Medusa#10158]
**Describe the bug**
When my network drive that holds my shows was unavailable, and opening a show in Medusa, every "Downloaded" episode is now set to "Archived" 

**To Reproduce**
1. Download episode, Medusa sets it to "Downloaded"
2. Disconnect network drive
3. Open show, Location is now "missing" - expected
4. Downloaded episode is now set to "Archived" - not expected

**Expected behavior**
Download state does not change if the download location cannot be checked.

**Screenshots**
![image](https://user-images.githubusercontent.com/6422683/145249168-daf3a423-cfa5-45f1-9246-713d76520964.png)

**Medusa (please complete the following information):**
Branch: master
Commit: f35a19da6bc4efcafff8facca6a4d5b9e3f3f501
Version: 0.5.20
Database: 44.18
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-10-10.0.19041-SP0
Locale: | nl_NL.cp1252
Timezone: | West-Europa (standaardtijd)

**Comment by eddywitkamp** [comment]
It happend again....every episode marked as Downloaded is now marked as Archived again

**Comment by p0psicles** [comment]
@medariox could this be fixed when we do a short test, to see if the containing folder is accessable before deciding that the episode was removed?

**Comment by p0psicles** [comment]
Mm thinking about it. A user could of course also decide to remove an entire folder.

**Comment by p0psicles** [comment]
Alternative could be adding an opt-out option for the setting to archived on file removal

**Comment by eddywitkamp** [comment]
Yeah I would like that opt-out.

I don't know if there is a way for you to differentiate between a folder missing or the complete drive unavailable...

**Comment by p0psicles** [comment]
You can already disable this behavior.
![image](https://user-images.githubusercontent.com/1331394/150177610-8008336e-0a83-42c8-bbca-1fd27b7c56c5.png)

Enable the skip remove detection
