### ISSUE TITLE
Episode Management appears to be broken

### ISSUE THREAD

**Issue by siconic** [pymedusa/Medusa#10160]
When trying to mass change the status of episodes, it appears that there is nothing occurring.

Manage -> Episode Status Management -> Manage Episodes with Status "Snatched" - > Set Checked Shows/Episodes to "Failed"

After following that process, the screen goes blank, and no episodes are marked as failed. It appears to do nothing, and the logs do not reveal anything either. The shows never get added to the "Failed Episodes" list and do not trigger a search.

System Info:
Branch:  master
Commit:  f35a19da6bc4efcafff8facca6a4d5b9e3f3f501
Version: 0.5.20
Database: 44.18
Python Version: 3.7.8 (default, Aug  8 2020, 01:18:05)  [Clang 8.0.0 (tags/RELEASE_800/final 356365)]
SSL Version:  OpenSSL 1.0.2o-freebsd  27 Mar 2018
OS: FreeBSD-12.2-RELEASE-p10-amd64-64bit-ELF
Timezone:  EST

**Comment by siconic** [comment]
Do you need more information, I have not seen any status update or comments. I will be applying the latest update today and will report if there is a change.

**Comment by siconic** [comment]
Update did not resolve. 

Manage -> Failed downloads, shows no results. 

Setting checked episodes to failed does not add them to the failed list.

**Comment by p0psicles** [comment]
Only the failed download handling process is allowed to change a status to failed. As at that time more is done then just changing the status. It's also logging the last failed/attempted snatch. Something that it can't do when just changing the status.

You could try switching the status to wanted.

**Comment by p0psicles** [comment]
i'll remove the option to change to failed.

**Comment by siconic** [comment]
> Only the failed download handling process is allowed to change a status to failed. As at that time more is done then just changing the status. It's also logging the last failed/attempted snatch. Something that it can't do when just changing the status.
> 
> I can create a PR and allow for it to change to Failed. I'm just not sure if that won't cause other issues.

It used to work about 6 weeks ago. Maybe we are talking about different things?

Clicking here takes you to failed snatched episode management:
![image](https://user-images.githubusercontent.com/11541484/147782652-87d13db9-cba1-4a21-a64c-bb82dc7f72ea.png)

Setting "Set Check shows/episodes to Failed" would mark them as failed and trigger a backlog search. 
![image](https://user-images.githubusercontent.com/11541484/147782639-b1d48dab-19f2-4560-99f7-a4fe68adbb20.png)

I used to see immediate results and those episodes would end up in the failed downloads DB, but now they do not get added, and a backlog search is not triggered.
![image](https://user-images.githubusercontent.com/11541484/147782958-f4d5835b-3ae9-4e07-9b76-6531373b1c3f.png)

So I guess I dont follow what you are trying to tell me, since this WAS something that was fully functional, and somehow stopped working. It would certainly have to suck to go into each Show and find all the "Snatched" episodes, and manually mark them all as failed.

**Comment by p0psicles** [comment]
If this is a regression I'll make sure to fix it. I'll check it out

**Comment by p0psicles** [comment]
> So I guess I don't follow what you are trying to tell me, since this WAS something that was fully functional, and somehow stopped working. It would certainly have to suck to go into each Show and find all the "Snatched" episodes, and manually mark them all as failed.

are you saying that when you go into a show and mark a specific episode as failed, it does start a new snatch?

**Comment by p0psicles** [comment]
should be fixed in develop branch

**Comment by siconic** [comment]
While this does now change them to "Failed" they do not trigger a search. Again, there was a whole process that worked and is now broken. Several weeks ago, if you set the status to failed, a popup would ask "Would you like to search" or maybe it was "Would you like to trigger a backlog search". I cant remember the exact verbiage, but this feature would then run a search for failed episodes.

The current changes you made to episode.py does not seem to trigger the search.

**Comment by siconic** [comment]
Additional Info:

I directly modified the episode.py file. It could be there were other edits you had made, that have not been committed yet. Let me know, I didnt want to change my branch, just wanted to get this working.

**Comment by p0psicles** [comment]
The changes should als result in a new search.
https://github.com/pymedusa/Medusa/pull/10213/files#diff-dd7627247c6227f23470fd39af077f13f85d839c7366aa1c27c6ad5b09806d91R2156

**Comment by siconic** [comment]
OK, I will wait until it is merged, I may have something improper in my formatting.
