### ISSUE TITLE
Upgrading to Python 3.10 breaks Medusa

### ISSUE THREAD

**Issue by xenogenick** [pymedusa/Medusa#10169]
**Describe the bug**
Python 3.10 moved Collections Abstract Base Classes to the collections.abc module, creating log errors like "ImportError: cannot import name 'MutableMapping' from 'collections'" referencing various files, preventing Medusa from starting.

**To Reproduce**
1. Update Python to 3.10

**Expected behavior**
Medusa to continue working after the Python update.

**Medusa (please complete the following information):**
 - OS: Arch 2021.11.01
 - Branch: master
 - Commit: 0.5.20
 - Python version: 3.10
 - Database version: ?

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
Medusa does not start to enable debug
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Should already be fixed in develop branch
