### ISSUE TITLE
Torrentday limited on specific categories

### ISSUE THREAD

**Issue by dirkronsmans** [pymedusa/Medusa#10174]
Perhaps more of a request for clarification than a bug report.

I have the Netflix show "Arcane" added to my Medusa but on Torrentday they have it as category "Anime" as it is an animated series. (https://www.tvmaze.com/shows/55138/arcane)
With the current categories the search returns no result (it's missing category 29)

Is there a specific reason why we are limiting the search to specific categories only and perhaps why Anime is not included?

**Comment by p0psicles** [comment]
Yeah, we want to exclude results that don't make sense. To prevent the daily search response having to much results. Which could potentially result in skipped releases. 

But I can add the category.

**Comment by medariox** [comment]
Added.
