### ISSUE TITLE
Cannot Update Medusa

### ISSUE THREAD

**Issue by LyntonBrown** [pymedusa/Medusa#10187]
**Describe the bug**
Mesua Update Fails

**To Reproduce**
1. Go to top right menu button
2. Click on 'Check for Update'
3. When asked to update to new version select "Yes"
4. Medusa will automatically create a backup before you update. Are you sure you want to update? Select "Yes"
5. Update fails on the "Waiting for Medusa to update" step.

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Windows 11 Pro
 - Branch: master
 - Commit: f35a19da6bc4efcafff8facca6a4d5b9e3f3f501
 - Python version: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
 - Database version: 44.18

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>
2021-12-22 11:22:42 WARNING	APIv2-Thread-74 :: [f35a19d] git pull -f origin master returned : From https://github.com/pymedusa/Medusa
 * branch                master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	.github/workflows/python-backend.yml
	CHANGELOG.md
	ext/babelfish/__init__.py
	ext/babelfish/converters/__init__.py
	ext/babelfish/converters/opensubtitles.py
	ext/diskcache/__init__.py
	ext/diskcache/core.py
	ext/diskcache/djangocache.py
	ext/diskcache/fanout.py
	ext/diskcache/persistent.py
	ext/guessit/__main__.py
	ext/guessit/__version__.py
	ext/guessit/api.py
	ext/guessit/config/options.json
	ext/guessit/options.py
	ext/guessit/reutils.py
	ext/guessit/rules/__init__.py
	ext/guessit/rules/common/__init__.py
	ext/guessit/rules/common/date.py
	ext/guessit/rules/common/numeral.py
	ext/guessit/rules/common/quantity.py
	ext/guessit/rules/properties/audio_codec.py
	ext/guessit/rules/properties/bit_rate.py
	ext/guessit/rules/properties/bonus.py
	ext/guessit/rules/properties/country.py
	ext/guessit/rules/properties/edition.py
	ext/guessit/rules/properties/film.py
	ext/guessit/rules/properties/language.py
2021-12-22 11:22:33 WARNING	APIv2-Thread-74 :: [f35a19d] git reset --hard origin/master returned (128) : Checking out files:  15% (1130/7365)
Checking out files:  16% (1179/7365)
Checking out files:  17% (1253/7365)
Checking out files:  18% (1326/7365)
Checking out files:  19% (1400/7365)
Checking out files:  20% (1473/7365)
Checking out files:  21% (1547/7365)
Checking out files:  22% (1621/7365)
Checking out files:  23% (1694/7365)
Checking out files:  24% (1768/7365)
Checking out files:  25% (1842/7365)
Checking out files:  26% (1915/7365)
Checking out files:  27% (1989/7365)
Checking out files:  28% (2063/7365)
Checking out files:  29% (2136/7365)
Checking out files:  30% (2210/7365)
Checking out files:  30% (2245/7365)
error: unable to unlink old 'lib/native/windows/x86_64/MediaInfo.dll': Invalid argument
Checking out files:  31% (2284/7365)
Checking out files:  32% (2357/7365)
Checking out files:  33% (2431/7365)
Checking out files:  34% (2505/7365)
Checking out files:  35% (2578/7365)
Checking out files:  36% (2652/7365)
Checking out files:  37% (2726/7365)
Checking out files:  38% (2799/7365)
Checking out files:  39% (2873/7365)
Checking out files:  40% (2946/7365)
Checking out files:  41% (3020/7365)
Checking out files:  42% (3094/7365)
Checking out files:  43% (3167/7365)
Checking out files:  43% (3238/7365)
Checking out files:  44% (3241/7365)
Checking out files:  45% (3315/7365)
Checking out files:  46% (3388/7365)
Checking out files:  47% (3462/7365)
Checking out files:  48% (3536/7365)
Checking out files:  49% (3609/7365)
Checking out files:  50% (3683/7365)
Checking out files:  51% (3757/7365)
Checking out files:  52% (3830/7365)
Checking out files:  53% (3904/7365)
Checking out files:  54% (3978/7365)
Checking out files:  55% (4051/7365)
Checking out files:  56% (4125/7365)
Checking out files:  57% (4199/7365)
Checking out files:  58% (4272/7365)
Checking out files:  59% (4346/7365)
Checking out files:  60% (4419/7365)
Checking out files:  60% (4442/7365)
Checking out files:  61% (4493/7365)
Checking out files:  62% (4567/7365)
Checking out files:  63% (4640/7365)
Checking out files:  64% (4714/7365)
Checking out files:  65% (4788/7365)
Checking out files:  66% (4861/7365)
Checking out files:  67% (4935/7365)
Checking out files:  68% (5009/7365)
Checking out files:  69% (5082/7365)
Checking out files:  70% (5156/7365)
Checking out files:  71% (5230/7365)
Checking out files:  72% (5303/7365)
Checking out files:  73% (5377/7365)
Checking out files:  74% (5451/7365)
Checking out files:  75% (5524/7365)
Checking out files:  76% (5598/7365)
Checking out files:  76% (5658/7365)
Checking out files:  77% (5672/7365)
Checking out files:  78% (5745/7365)
Checking out files:  79% (5819/7365)
Checking out files:  80% (5892/7365)
Checking out files:  81% (5966/7365)
Checking out files:  82% (6040/7365)
Checking out files:  83% (6113/7365)
Checking out files:  84% (6187/7365)
Checking out files:  85% (6261/7365)
Checking out files:  86% (6334/7365)
Checking out files:  87% (6408/7365)
Checking out files:  88% (6482/7365)
Checking out files:  89% (6555/7365)
Checking out files:  90% (6629/7365)
Checking out files:  91% (6703/7365)
Checking out files:  92% (6776/7365)
Checking out files:  92% (6811/7365)
Checking out files:  93% (6850/7365)
Checking out files:  94% (6924/7365)
Checking out files:  95% (6997/7365)
Checking out files:  96% (7071/7365)
Checking out files:  97% (7145/7365)
Checking out files:  98% (7218/7365)
Checking out files:  99% (7292/7365)
Checking out files: 100% (7365/7365)
Checking out files: 100% (7365/7365), done.
fatal: Could not reset index file to revision 'origin/master'.
2021-12-22 11:22:26 INFO	APIv2-Thread-72 :: [f35a19d] Config backup successful
2021-12-22 11:22:16 INFO	APIv2-Thread-72 :: [f35a19d] Config backup in progress...
2021-12-22 11:21:20 WARNING	APIv2-Thread-50 :: [f35a19d] git pull -f origin master returned : From https://github.com/pymedusa/Medusa
 * branch                master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	.github/workflows/python-backend.yml
	CHANGELOG.md
	ext/babelfish/__init__.py
	ext/babelfish/converters/__init__.py
	ext/babelfish/converters/opensubtitles.py
	ext/diskcache/__init__.py
	ext/diskcache/core.py
	ext/diskcache/djangocache.py
	ext/diskcache/fanout.py
	ext/diskcache/persistent.py
	ext/guessit/__main__.py
	ext/guessit/__version__.py
	ext/guessit/api.py
	ext/guessit/config/options.json
	ext/guessit/options.py
	ext/guessit/reutils.py
	ext/guessit/rules/__init__.py
	ext/guessit/rules/common/__init__.py
	ext/guessit/rules/common/date.py
	ext/guessit/rules/common/numeral.py
	ext/guessit/rules/common/quantity.py
	ext/guessit/rules/properties/audio_codec.py
	ext/guessit/rules/properties/bit_rate.py
	ext/guessit/rules/properties/bonus.py
	ext/guessit/rules/properties/country.py
	ext/guessit/rules/properties/edition.py
	ext/guessit/rules/properties/film.py
	ext/guessit/rules/properties/language.py
2021-12-22 11:20:42 WARNING	APIv2-Thread-50 :: [f35a19d] git reset --hard origin/master returned (128) : Checking out files:  15% (1131/7365)
Checking out files:  16% (1179/7365)
Checking out files:  17% (1253/7365)
Checking out files:  18% (1326/7365)
Checking out files:  19% (1400/7365)
Checking out files:  20% (1473/7365)
Checking out files:  21% (1547/7365)
Checking out files:  22% (1621/7365)
Checking out files:  23% (1694/7365)
Checking out files:  24% (1768/7365)
Checking out files:  25% (1842/7365)
Checking out files:  26% (1915/7365)
Checking out files:  27% (1989/7365)
Checking out files:  28% (2063/7365)
Checking out files:  29% (2136/7365)
Checking out files:  30% (2210/7365)
error: unable to unlink old 'lib/native/windows/x86_64/MediaInfo.dll': Invalid argument
Checking out files:  30% (2250/7365)
Checking out files:  31% (2284/7365)
Checking out files:  32% (2357/7365)
Checking out files:  33% (2431/7365)
Checking out files:  34% (2505/7365)
Checking out files:  35% (2578/7365)
Checking out files:  36% (2652/7365)
Checking out files:  37% (2726/7365)
Checking out files:  38% (2799/7365)
Checking out files:  39% (2873/7365)
Checking out files:  40% (2946/7365)
Checking out files:  41% (3020/7365)
Checking out files:  42% (3094/7365)
Checking out files:  43% (3167/7365)
Checking out files:  44% (3241/7365)
Checking out files:  45% (3315/7365)
Checking out files:  45% (3330/7365)
Checking out files:  46% (3388/7365)
Checking out files:  47% (3462/7365)
Checking out files:  48% (3536/7365)
Checking out files:  49% (3609/7365)
Checking out files:  50% (3683/7365)
Checking out files:  51% (3757/7365)
Checking out files:  52% (3830/7365)
Checking out files:  53% (3904/7365)
Checking out files:  54% (3978/7365)
Checking out files:  55% (4051/7365)
Checking out files:  56% (4125/7365)
Checking out files:  57% (4199/7365)
Checking out files:  58% (4272/7365)
Checking out files:  59% (4346/7365)
Checking out files:  60% (4419/7365)
Checking out files:  61% (4493/7365)
Checking out files:  61% (4502/7365)
Checking out files:  62% (4567/7365)
Checking out files:  63% (4640/7365)
Checking out files:  64% (4714/7365)
Checking out files:  65% (4788/7365)
Checking out files:  66% (4861/7365)
Checking out files:  67% (4935/7365)
Checking out files:  68% (5009/7365)
Checking out files:  69% (5082/7365)
Checking out files:  70% (5156/7365)
Checking out files:  71% (5230/7365)
Checking out files:  72% (5303/7365)
Checking out files:  73% (5377/7365)
Checking out files:  74% (5451/7365)
Checking out files:  75% (5524/7365)
Checking out files:  76% (5598/7365)
Checking out files:  77% (5672/7365)
Checking out files:  78% (5745/7365)
Checking out files:  78% (5776/7365)
Checking out files:  79% (5819/7365)
Checking out files:  80% (5892/7365)
Checking out files:  81% (5966/7365)
Checking out files:  82% (6040/7365)
Checking out files:  83% (6113/7365)
Checking out files:  84% (6187/7365)
Checking out files:  85% (6261/7365)
Checking out files:  86% (6334/7365)
Checking out files:  87% (6408/7365)
Checking out files:  88% (6482/7365)
Checking out files:  89% (6555/7365)
Checking out files:  90% (6629/7365)
Checking out files:  91% (6703/7365)
Checking out files:  92% (6776/7365)
Checking out files:  93% (6850/7365)
Checking out files:  94% (6924/7365)
Checking out files:  94% (6959/7365)
Checking out files:  95% (6997/7365)
Checking out files:  96% (7071/7365)
Checking out files:  97% (7145/7365)
Checking out files:  98% (7218/7365)
Checking out files:  99% (7292/7365)
Checking out files: 100% (7365/7365)
Checking out files: 100% (7365/7365), done.
fatal: Could not reset index file to revision 'origin/master'.
2021-12-22 11:20:34 INFO	APIv2-Thread-69 :: [f35a19d] Config backup successful
2021-12-22 11:20:24 INFO	APIv2-Thread-69 :: [f35a19d] Config backup in progress...
2021-12-22 11:20:00 WARNING	APIv2-Thread-41 :: [f35a19d] Config patch ignored {'subtitles': {'enabled': None}, 'subtitlesMulti': None}
2021-12-22 11:18:53 INFO	POSTPROCESSOR :: [f35a19d] Post-processing completed.
2021-12-22 11:18:53 INFO	POSTPROCESSOR :: [f35a19d] Processing path: H:\Downloads\SB Temp
2021-12-22 11:16:49 WARNING	APIv2-Thread-59 :: [f35a19d] git pull -f origin master returned : From https://github.com/pymedusa/Medusa
 * branch                master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	.github/workflows/python-backend.yml
	CHANGELOG.md
	ext/babelfish/__init__.py
	ext/babelfish/converters/__init__.py
	ext/babelfish/converters/opensubtitles.py
	ext/diskcache/__init__.py
	ext/diskcache/core.py
	ext/diskcache/djangocache.py
	ext/diskcache/fanout.py
	ext/diskcache/persistent.py
	ext/guessit/__main__.py
	ext/guessit/__version__.py
	ext/guessit/api.py
	ext/guessit/config/options.json
	ext/guessit/options.py
	ext/guessit/reutils.py
	ext/guessit/rules/__init__.py
	ext/guessit/rules/common/__init__.py
	ext/guessit/rules/common/date.py
	ext/guessit/rules/common/numeral.py
	ext/guessit/rules/common/quantity.py
	ext/guessit/rules/properties/audio_codec.py
	ext/guessit/rules/properties/bit_rate.py
	ext/guessit/rules/properties/bonus.py
	ext/guessit/rules/properties/country.py
	ext/guessit/rules/properties/edition.py
	ext/guessit/rules/properties/film.py
	ext/guessit/rules/properties/language.py
2021-12-22 11:16:39 WARNING	APIv2-Thread-59 :: [f35a19d] git reset --hard origin/master returned (128) : Checking out files:  15% (1118/7365)
Checking out files:  16% (1179/7365)
Checking out files:  17% (1253/7365)
Checking out files:  18% (1326/7365)
Checking out files:  19% (1400/7365)
Checking out files:  20% (1473/7365)
Checking out files:  21% (1547/7365)
Checking out files:  22% (1621/7365)
Checking out files:  23% (1694/7365)
Checking out files:  24% (1768/7365)
Checking out files:  25% (1842/7365)
Checking out files:  26% (1915/7365)
Checking out files:  27% (1989/7365)
Checking out files:  28% (2063/7365)
Checking out files:  29% (2136/7365)
Checking out files:  30% (2210/7365)
Checking out files:  30% (2249/7365)
error: unable to unlink old 'lib/native/windows/x86_64/MediaInfo.dll': Invalid argument
Checking out files:  31% (2284/7365)
Checking out files:  32% (2357/7365)
Checking out files:  33% (2431/7365)
Checking out files:  34% (2505/7365)
Checking out files:  35% (2578/7365)
Checking out files:  36% (2652/7365)
Checking out files:  37% (2726/7365)
Checking out files:  38% (2799/7365)
Checking out files:  39% (2873/7365)
Checking out files:  40% (2946/7365)
Checking out files:  41% (3020/7365)
Checking out files:  42% (3094/7365)
Checking out files:  43% (3167/7365)
Checking out files:  44% (3241/7365)
Checking out files:  44% (3243/7365)
Checking out files:  45% (3315/7365)
Checking out files:  46% (3388/7365)
Checking out files:  47% (3462/7365)
Checking out files:  48% (3536/7365)
Checking out files:  49% (3609/7365)
Checking out files:  50% (3683/7365)
Checking out files:  51% (3757/7365)
Checking out files:  52% (3830/7365)
Checking out files:  53% (3904/7365)
Checking out files:  54% (3978/7365)
Checking out files:  55% (4051/7365)
Checking out files:  56% (4125/7365)
Checking out files:  57% (4199/7365)
Checking out files:  58% (4272/7365)
Checking out files:  59% (4346/7365)
Checking out files:  60% (4419/7365)
Checking out files:  60% (4440/7365)
Checking out files:  61% (4493/7365)
Checking out files:  62% (4567/7365)
Checking out files:  63% (4640/7365)
Checking out files:  64% (4714/7365)
Checking out files:  65% (4788/7365)
Checking out files:  66% (4861/7365)
Checking out files:  67% (4935/7365)
Checking out files:  68% (5009/7365)
Checking out files:  69% (5082/7365)
Checking out files:  70% (5156/7365)
Checking out files:  71% (5230/7365)
Checking out files:  72% (5303/7365)
Checking out files:  73% (5377/7365)
Checking out files:  74% (5451/7365)
Checking out files:  75% (5524/7365)
Checking out files:  75% (5570/7365)
Checking out files:  76% (5598/7365)
Checking out files:  77% (5672/7365)
Checking out files:  78% (5745/7365)
Checking out files:  79% (5819/7365)
Checking out files:  80% (5892/7365)
Checking out files:  81% (5966/7365)
Checking out files:  82% (6040/7365)
Checking out files:  83% (6113/7365)
Checking out files:  84% (6187/7365)
Checking out files:  85% (6261/7365)
Checking out files:  86% (6334/7365)
Checking out files:  87% (6408/7365)
Checking out files:  88% (6482/7365)
Checking out files:  89% (6555/7365)
Checking out files:  90% (6629/7365)
Checking out files:  91% (6703/7365)
Checking out files:  91% (6723/7365)
Checking out files:  92% (6776/7365)
Checking out files:  93% (6850/7365)
Checking out files:  94% (6924/7365)
Checking out files:  95% (6997/7365)
Checking out files:  96% (7071/7365)
Checking out files:  97% (7145/7365)
Checking out files:  98% (7218/7365)
Checking out files:  99% (7292/7365)
Checking out files: 100% (7365/7365)
Checking out files: 100% (7365/7365), done.
fatal: Could not reset index file to revision 'origin/master'.
2021-12-22 11:16:32 INFO	APIv2-Thread-56 :: [f35a19d] Config backup successful
2021-12-22 11:16:22 INFO	APIv2-Thread-56 :: [f35a19d] Config backup in progress...
2021-12-22 11:14:29 WARNING	APIv2-Thread-24 :: [f35a19d] git pull -f origin master returned : From https://github.com/pymedusa/Medusa
 * branch                master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	.github/workflows/python-backend.yml
	CHANGELOG.md
	ext/babelfish/__init__.py
	ext/babelfish/converters/__init__.py
	ext/babelfish/converters/opensubtitles.py
	ext/diskcache/__init__.py
	ext/diskcache/core.py
	ext/diskcache/djangocache.py
	ext/diskcache/fanout.py
	ext/diskcache/persistent.py
	ext/guessit/__main__.py
	ext/guessit/__version__.py
	ext/guessit/api.py
	ext/guessit/config/options.json
	ext/guessit/options.py
	ext/guessit/reutils.py
	ext/guessit/rules/__init__.py
	ext/guessit/rules/common/__init__.py
	ext/guessit/rules/common/date.py
	ext/guessit/rules/common/numeral.py
	ext/guessit/rules/common/quantity.py
	ext/guessit/rules/properties/audio_codec.py
	ext/guessit/rules/properties/bit_rate.py
	ext/guessit/rules/properties/bonus.py
	ext/guessit/rules/properties/country.py
	ext/guessit/rules/properties/edition.py
	ext/guessit/rules/properties/film.py
	ext/guessit/rules/properties/language.py
2021-12-22 11:14:20 WARNING	APIv2-Thread-24 :: [f35a19d] git reset --hard origin/master returned (128) : Checking out files:  14% (1093/7365)
Checking out files:  15% (1105/7365)
Checking out files:  16% (1179/7365)
Checking out files:  17% (1253/7365)
Checking out files:  18% (1326/7365)
Checking out files:  19% (1400/7365)
Checking out files:  20% (1473/7365)
Checking out files:  21% (1547/7365)
Checking out files:  22% (1621/7365)
Checking out files:  23% (1694/7365)
Checking out files:  24% (1768/7365)
Checking out files:  25% (1842/7365)
Checking out files:  26% (1915/7365)
Checking out files:  27% (1989/7365)
Checking out files:  28% (2063/7365)
Checking out files:  29% (2136/7365)
Checking out files:  30% (2210/7365)
Checking out files:  30% (2245/7365)
error: unable to unlink old 'lib/native/windows/x86_64/MediaInfo.dll': Invalid argument
Checking out files:  31% (2284/7365)
Checking out files:  32% (2357/7365)
Checking out files:  33% (2431/7365)
Checking out files:  34% (2505/7365)
Checking out files:  35% (2578/7365)
Checking out files:  36% (2652/7365)
Checking out files:  37% (2726/7365)
Checking out files:  38% (2799/7365)
Checking out files:  39% (2873/7365)
Checking out files:  40% (2946/7365)
Checking out files:  41% (3020/7365)
Checking out files:  42% (3094/7365)
Checking out files:  42% (3164/7365)
Checking out files:  43% (3167/7365)
Checking out files:  44% (3241/7365)
Checking out files:  45% (3315/7365)
Checking out files:  46% (3388/7365)
Checking out files:  47% (3462/7365)
Checking out files:  48% (3536/7365)
Checking out files:  49% (3609/7365)
Checking out files:  50% (3683/7365)
Checking out files:  51% (3757/7365)
Checking out files:  52% (3830/7365)
Checking out files:  53% (3904/7365)
Checking out files:  54% (3978/7365)
Checking out files:  55% (4051/7365)
Checking out files:  56% (4125/7365)
Checking out files:  57% (4199/7365)
Checking out files:  58% (4272/7365)
Checking out files:  59% (4346/7365)
Checking out files:  59% (4361/7365)
Checking out files:  60% (4419/7365)
Checking out files:  61% (4493/7365)
Checking out files:  62% (4567/7365)
Checking out files:  63% (4640/7365)
Checking out files:  64% (4714/7365)
Checking out files:  65% (4788/7365)
Checking out files:  66% (4861/7365)
Checking out files:  67% (4935/7365)
Checking out files:  68% (5009/7365)
Checking out files:  69% (5082/7365)
Checking out files:  70% (5156/7365)
Checking out files:  71% (5230/7365)
Checking out files:  72% (5303/7365)
Checking out files:  73% (5377/7365)
Checking out files:  74% (5451/7365)
Checking out files:  75% (5524/7365)
Checking out files:  75% (5527/7365)
Checking out files:  76% (5598/7365)
Checking out files:  77% (5672/7365)
Checking out files:  78% (5745/7365)
Checking out files:  79% (5819/7365)
Checking out files:  80% (5892/7365)
Checking out files:  81% (5966/7365)
Checking out files:  82% (6040/7365)
Checking out files:  83% (6113/7365)
Checking out files:  84% (6187/7365)
Checking out files:  85% (6261/7365)
Checking out files:  86% (6334/7365)
Checking out files:  87% (6408/7365)
Checking out files:  88% (6482/7365)
Checking out files:  89% (6555/7365)
Checking out files:  89% (6574/7365)
Checking out files:  90% (6629/7365)
Checking out files:  91% (6703/7365)
Checking out files:  92% (6776/7365)
Checking out files:  93% (6850/7365)
Checking out files:  94% (6924/7365)
Checking out files:  95% (6997/7365)
Checking out files:  96% (7071/7365)
Checking out files:  97% (7145/7365)
Checking out files:  98% (7218/7365)
Checking out files:  99% (7292/7365)
Checking out files: 100% (7365/7365)
Checking out files: 100% (7365/7365), done.
fatal: Could not reset index file to revision 'origin/master'.
2021-12-22 11:14:12 INFO	APIv2-Thread-30 :: [f35a19d] Config backup successful
2021-12-22 11:14:02 INFO	APIv2-Thread-30 :: [f35a19d] Config backup in progress...
2021-12-22 11:13:44 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] No needed episodes found
2021-12-22 11:13:43 INFO	SEARCHQUEUE-DAILY-SEARCH :: Eztv :: [f35a19d] Consider adding 'Hawkeye' in scene exceptions for series 'Hawkeye (2021)'
2021-12-22 11:13:43 INFO	SEARCHQUEUE-DAILY-SEARCH :: Eztv :: [f35a19d] Consider adding 'Hawkeye' in scene exceptions for series 'Hawkeye (2021)'
2021-12-22 11:13:37 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Using daily search providers
2021-12-22 11:13:37 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Beginning daily search for new episodes
2021-12-22 11:13:00 WARNING	APIv2-Thread-3 :: [f35a19d] Config patch ignored {'subtitles': {'enabled': None}, 'subtitlesMulti': None}
2021-12-22 11:12:22 INFO	APIv2-Thread-16 :: [f35a19d] Broken providers found: ['danishbits']
2021-12-22 11:12:22 WARNING	APIv2-Thread-16 :: [f35a19d] Config patch ignored {'subtitles': {'enabled': None}, 'subtitlesMulti': None}
2021-12-22 11:08:52 INFO	POSTPROCESSOR :: [f35a19d] Post-processing completed.
2021-12-22 11:08:52 INFO	POSTPROCESSOR :: [f35a19d] Processing path: H:\Downloads\SB Temp
2021-12-22 11:05:53 WARNING	APIv2-Thread-51 :: [f35a19d] git pull -f origin master returned : From https://github.com/pymedusa/Medusa
</details>

**Additional context**

**Comment by p0psicles** [comment]
looks like something went wrong in a git pull somewhere.
You'll have to repair the damage using manual git commands.
In you medusa root folder run:
stop medusa
`git fetch origin`
`get reset --hard origin/master`
start medusa

**Comment by roil13** [comment]
Have the same problem, running on raspberry pi 4 OS.
Got this errors:
[warninglog.txt](https://github.com/pymedusa/Medusa/files/7763761/warninglog.txt)

@p0psicles tried your solution got this:
```
git reset --hard orign/master
fatal: ambiguous argument 'orign/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by p0psicles** [comment]
You miss spelled

**Comment by LyntonBrown** [comment]
> just had to correct get to git and all is working.
