### ISSUE TITLE
Use ABC not found on synology nas, running Medusa in Docker

### ISSUE THREAD

**Issue by Dr-know** [pymedusa/Medusa#10191]
Hello,
first time user of Medusa. (previous using sickbeard-custom)
I run Medusa in a docker container on Synology.
I bind the already populated folder /tv with a folder on the Synology volume.
when i want to add existing shows and choose the /tv folder i get in de logs permission denied ...
At the Medusa configuration i see the User: abc
I want to trey to give the user abc read/write access to the /tv folder (bind to folder on synology nas) but this user abc does not exist as a Synology user .. how to fix this , ... even trey giving the /tv folder read/write access to "all users" ..

i use the image Version: 0.5.20 (pulled form linuxserver/medusa:latest )

**Comment by p0psicles** [comment]
It's recommended to run @BenjV Synology Medusa package. Less hassle with user/folder rights

**Comment by Dr-know** [comment]
> @Dr-know they likely need to be owned by nobody:nobody and not the abc user.

Ho do you Change that, so that the docker image runs as nobady:nobady?

**Comment by OmgImAlexis** [comment]
The container doesn't need to, if nobody:nobody owns them and the permissions are setup to effect new files then everything should just work.

**Comment by BenjV** [comment]
https://flaviocopes.com/docker-access-files-outside-container/

**Comment by JasonHears** [comment]
Old thread, but ran into this issue myself. What i found was the volume mounted by docker had no permissions. Performing an "ls -l" in terminal on the docker instance, the folders showed: "d--------". I ran "chmod 755 ./tv" and "chmod 755 ./downloads". This fixed the issue for me.
