### ISSUE TITLE
Manual Post-Processing unable to change "Process Method to be used".

### ISSUE THREAD

**Issue by consenti** [pymedusa/Medusa#10196]
**Describe the bug**
When I select an option other than the one set in my regular post-processing settings, it will revert to default as soon as I click **any** other button on the screen.

**To Reproduce**
1. Go to 'Shows and Click Manual Post-Processing'
2. Click on 'pull down menu of Process Method to be used'
3. Scroll down to 'any non-default method, in my case I chose Move'
4. Click any of the buttons below, or even process and the selection reverts to system default.  It will not allow me to actually use any alternate method.

**Expected behavior**
Select an alternate post processing method.  In my case change from Copy to Move, and process with my new selection.  
**Screenshots**

**Medusa (please complete the following information):**
 - OS: Linux-3.10.108-x86_64-with
 - Branch: master 
 - Commit: f3f501
 - Python version: 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
 - Database version: 44.18
 - Version: 0.5.22 
 - Docker Container: pymedusa/medusa:master
**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
None available since its more of a gui loss of focus issue
```

**Additional context**
Have tried on various installs using both docker and synology installation via benjv package.  Same problem occurs either way.

**Comment by p0psicles** [comment]
Should be fixed in develop branch. Tnx for reporting

**Comment by consenti** [comment]
> 

**Thank YOU p0psicles!  I appreciate your rapid response time.**  

I haven't figured out how to "easily" switch docker image to develop branchg, so I'll look forward the future update of master.

**Comment by p0psicles** [comment]
If you use the Medusa/pymedusa image, you can easily switch to the develop tag
