### ISSUE TITLE
Show names that start with numbers aren't being postprocessed - eg 1883

### ISSUE THREAD

**Issue by bonshates** [pymedusa/Medusa#10195]
**Describe the bug**
The post-processing function does not find episodes of shows that start with numbers. The best example is the show 1883. In my download folder I have two files: 1. 1883.s01e01.repack.1080p..... 2. 1883.s01e02.repack.1080p..... Post-processing does not discover these files and process them. I believe that this issue exists for all shows that start with a number but I could be wrong.

**To Reproduce**
1. Add the show "1883". The search function will find at least one episode of the show. (2021/12/23)
2. Download the show...
3. Search application.log for "1883" and I don't find any hits for that string.

**Expected behavior**
Medusa should find the downloaded file and process it.

**Screenshots**
I don't think any are needed but let me know if I am wrong.

**Medusa (please complete the following information):**
 - OS: dietpi (Linux-5.10.63-v7+-armv7l-with-glibc2.31)
 - Branch: master
 - Commit: f35a19da6bc4efcafff8facca6a4d5b9e3f3f501
 - Python version: 3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110]
 - Database version: 44.18

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
[1883.log](https://github.com/pymedusa/Medusa/files/7770752/1883.log)

```
</details>

**Additional context**

**Comment by Yellow1144** [comment]
I noticed the same thing with 1883.

The show was added properly to the database when I added it some time ago. The first episode was snatched and automatically post-processed just fine. The second episode I had to find manually but It won't post despite having the same name.

**Comment by bonshates** [comment]
Yes, I noticed this too exactly.

**Comment by p0psicles** [comment]
Should be fixed in develop branch
