### ISSUE TITLE
Medusa doesn't download show season poster & banners

### ISSUE THREAD

**Issue by h3llrais3r** [pymedusa/Medusa#10236]
**Describe the bug**
Force full update of the show.

**Expected behavior**
Download missing artwork: seasonxx-poster.jpg and seasonxx-banner.jpg
Expected to download season08-poster.jpg and season08-banner.jpg (images seems to be available in the list of images available in debug log: f.e. https://www.thetvdb.com/banners/series/257655/seasons/815984/posters/5ffa63f5c20eb_t.jpg)

**Medusa (please complete the following information):**
 - OS: Windows
 - Branch: master
 - Commit: 1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
 - Python version:  3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
 - Database version:  44.18

**Debug logs (at least 50 lines):**

[debug.log](https://github.com/pymedusa/Medusa/files/7825193/debug.log)

**Comment by p0psicles** [comment]
I can check for the season posters.
But I didn't get any seasonwide's (banners) for arrow from the api.

**Comment by h3llrais3r** [comment]
Posters were not coming either...

**Comment by h3llrais3r** [comment]
👍
