### ISSUE TITLE
Potential Bug With .nfo Files

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#10247]
**Describe the bug**
After looking at the forms of kodi and how the scrapers work. It seems that there is an issue with .nfo files on how it creates files and data is missing. It seems the Ratings are missing from the .nfo files. 

**To Reproduce**
1. Shows Downloads
2. Medusa creates .nfo for Episode

**Expected behavior**
Correct - Just missing info (Ratings )

**Medusa (please complete the following information):**
 - OS: Synology
 - Branch: master
 - Commit: 1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
 - Python version: 3.8.12
 - Database version: 44.18

**Additional context**
See - [https://forum.kodi.tv/showthread.php?tid=164652&page=31](https://forum.kodi.tv/showthread.php?tid=164652&page=31)

**Comment by p0psicles** [comment]
What do you mean with ratings are missing?
If I create an episode nfo. ratig is there. Like for ex. `<rating>7.0</rating>`
can you elaborate?

On the kodi forum, they say rating is not supported by kodi?

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

I see that the Kodi Team has responded to you about what is going on.

Thanks for picking this up :)

**Comment by p0psicles** [comment]
Yeah the rating thing is already resolved.
I'm looking at his review of our nfo. But it looks like our nfo is in pretty good shape.

**Comment by HPMSGEN8** [comment]
great thanks a lot this will be good news for all :)

Everyone will just need to delete old .nfo files and do an force update to get the new info if they want to use Kodi etc..... it seems correctly based on the comments from the dev's.

**Comment by p0psicles** [comment]
In the same PR i've added the feature to allow always overwriting of the nfo.
![image](https://user-images.githubusercontent.com/1331394/149136312-33793ee6-abf3-4041-a26f-da5951041737.png)

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

Is this ready for me to test on DEV at all as i see you have merged this. Also when do you think this will move to PROD.

Thanks a lot for your time to get this fixed. 

Thanks

**Comment by p0psicles** [comment]
Yeah you can of course test on develop.
Don't know when we'll release .

**Comment by HPMSGEN8** [comment]
Thanks :)
