### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by Anandkumarindel** [pymedusa/Medusa#10253]
**Describe the bug**
I have upgraded to python v3.10.2 from python v3.8, and below is list in installed modules on v3.10.2. when I execute my script, I get error "AttributeError: module 'collections' has no attribute 'MutableMapping'" 

**> python --version**
Python 3.10.2

**> pip list**
Package    Version
---------- -------
pip        21.3.1
setuptools 60.5.0
urllib3    1.26.8
wheel      0.36.2

**Expected behavior**
It should execute the without error.

**Screenshots**
NA

**Medusa (please complete the following information):**
 - OS: Windows 10 Pro
 - Branch: Windows OS version : 10.0.19042 Build 19042
 - Commit: NA
 - Python version: 3.10.2
 - Database version: NA

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
...
...
...
...
...
File "path\to\my\libdir\Resources\Functionalities\GeneralFunctionality\WEB\WEBCommunication.py", line 11, in <module>
    from Lib.Resources.ThirdPartyModules import requests
  File "path\to\my\libdir\Resources\ThirdPartyModules\requests\__init__.py", line 58, in <module>
    from . import utils
  File "path\to\my\libdir\Resources\ThirdPartyModules\requests\utils.py", line 30, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "path\to\my\libdir\Resources\ThirdPartyModules\requests\cookies.py", line 164, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```
</details>

**Additional context**
NA

**Comment by BenjV** [comment]
In python 10 the module MutableMapping has moved from:
`collections.MutableMapping`
to
`collections.abc.MutableMapping`

This code could fix this:
```
import collections
from collections import abc
collections.MutableMapping = abc.MutableMapping
```

**Comment by medariox** [comment]
Problem is that an old `requests` version is being used.

**Comment by Anandkumarindel** [comment]
Thanks All, for valuable comments. Yes, request module was old and when I replaced request module directory with its newer version, and installed few more modules (listed below), My script is working fine. 
Thanks a lot for immediate help.

Package            Version
------------------ ---------
**certifi            2021.10.8
charset-normalizer 2.0.10
idna               3.3**
pip                21.3.1
setuptools         60.5.0
urllib3            1.26.8
wheel              0.37.1

**Comment by junhaz4** [comment]
Hi, I have the same problem, but it seems that I need to change the import in namedict.py to make it work manually. Does anyone have the same situation? I tried all previous solutions but none of them worked.
<img width="1061" alt="Screen Shot 2022-07-29 at 10 31 10 PM" src="https://user-images.githubusercontent.com/49204487/181866862-dad486bf-ad8f-4207-b103-1e90b8b8a87f.png">

**Comment by otl1** [comment]
> Hi, I have the same problem. To make it work, I have to change the import in namedict.py by changing **collections.MutableMapping** to **collections.abc.MutableMapping**. Does anyone have the same situation? I tried all previous solutions but none of them worked. <img alt="Screen Shot 2022-07-29 at 10 31 10 PM" width="1061" src="https://user-images.githubusercontent.com/49204487/181866862-dad486bf-ad8f-4207-b103-1e90b8b8a87f.png">

Hi, Did you solve this issue?
