### ISSUE TITLE
This package requires DSM version 0.0-0000 or onward.

### ISSUE THREAD

**Issue by AhmedOsama** [pymedusa/Medusa#10277]
**Describe the bug**
Unable to update from DSM package center 

Installed version 1.3
newest online 2.3

**To Reproduce**
1. Go to 'Package center'
2. Click on 'update'
3. See error "This package requires DSM version 0.0-0000 or onward."

**Expected behavior**
Update Medusa

**Medusa (please complete the following information):**
DSM : DSM 6.2.4-25556 Update 3
Medusa Info: | Branch: masterCommit: 1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38Version: 0.5.22Database: 44.18
Python Version: | 3.8.12 (default, Oct 22 2021, 20:39:34) [GCC 4.9.3 20150311 (prerelease)]
SSL Version: | OpenSSL 1.1.1l 24 Aug 2021
OS: | Linux-3.2.40-armv7l-with-glibc2.4
Locale: | en_US.UTF-8
Timezone: | EET

**Comment by BenjV** [comment]
There is no Medusa Package in any Synology package center, so updating that way is impossible.

My packages can only be downloaden and installed manual from the package center.
The latest version for DSM 6 is 1.7 and for DSM 7 2.3
If you want to update the package, please make a backup from within Medusa first and restore it after the update.

But it is unnecessary to update the Synology package, that package is only needed for the first install.
Medusa itself can be updated from within Medusa.

**Comment by mvveelen** [comment]
I actually have the same message. If Medusa 1.7 is the latest, how can we get rid of this annoying message that there is an update to 2.3 ?

**Comment by BenjV** [comment]
DSM only checks the sites that are configured in your package center as "package source".
So one of those must have put that package on that site.

I have Medusa also on my Nas with DSM 6 and  I do not get that message but the only site I have configured as "package source " is the SynoCommunity.

**Comment by mvveelen** [comment]
Ah, good to know. I'll check the package sources and remove the one that gives me this message. Thanks!

**Comment by AhmedOsama** [comment]
Aha good to know thank you all
