### ISSUE TITLE
Medusa connect to trakt issue

### ISSUE THREAD

**Issue by McEnnes** [pymedusa/Medusa#10276]
When i want to connect to trakt in medusa with my trakt account i get a strange message:
Allow SiCKRAGE to use your account?

I remember sickrage to be an untrustworthy programmer in sickchill and sick rage, so i wonder if it is safe to give this permission in Medusa. 
Is it a harmless leftover from the Sickbeard programm or something?

**Comment by p0psicles** [comment]
It's trustworthy. We're still using the same api key.
We're just to lazy to request a new one.

**Comment by McEnnes** [comment]
Thanks for the quick answer!
