### ISSUE TITLE
Pymedusa fails to start - solution: add simplejson to requirements.txt

### ISSUE THREAD

**Issue by Wieter** [pymedusa/Medusa#10280]
**Describe the bug**
Pymedusa fails to start - solution: add simplejson to requirements.txt

**To Reproduce**
Install Pymedusa from git using below python version, any OS:
```
git clone https://github.com/pymedusa/Medusa.git
python -m venv env
. env/bin/activate
python -m pip install -U -r Medusa/requirements.txt
```

Run on command line in non-daemon mode to get *any* information (NO info is written to ANY log)
```sudo -H -u sc-sickbeard-custom env LANG=en_US.UTF-8 /volume1/\@appstore/sickbeard-custom/env/bin/python /volume1/\@appstore/sickbeard-custom/var/SickBeard/start.py --pidfile /volume1/\@appstore/sickbeard-custom/var/sickbeard-custom.pid --config /volume1/\@appstore/sickbeard-custom/var/config.ini --datadir /volume1/\@appstore/sickbeard-custom/var/ --port 8083```

**Expected behavior**
Pymedusa should start

**Screenshots**
N/A

**Medusa (please complete the following information):**
 - OS: DSM 6.2.4-25556 Update 2
 - Branch: master
 - Commit: 1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
 - Python version: 3.8.6
 - Database version: N/A

**Debug logs (at least 50 lines):**
```
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/start.py", line 9, in <module>
    main()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/__main__.py", line 2367, in main
    application.start(sys.argv[1:])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/__main__.py", line 350, in start
    self.initialize(console_logging=self.console_logging)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/__main__.py", line 668, in initialize
    helpers.get_broken_providers() or app.BROKEN_PROVIDERS)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/helpers/__init__.py", line 1665, in get_broken_providers
    response = MedusaSafeSession().get_json(url)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/session/core.py", line 141, in get_json
    return resp.json() if resp else resp
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
AttributeError: module 'simplejson' has no attribute 'loads'
```
</details>

**Additional context**
Seems related to #598, removal of simplejson needs to be reverted, then Pymedusa starts properly.
I've used the sickbeard-custom wrapper from synocommunity. But any git-installation would end up with the same.

**Comment by p0psicles** [comment]
For synology you should use the package provided by BenJv. See our wiki.
All our dependencies are pre packaged in /ext, /ext3 and /lib.

We have a lot of users all installing directly from a git clone. And nobody had to require dependencies.

**Comment by Wieter** [comment]
Some of us are oldschool and prefer the manual method for full control. I still had a start-stop wrapper lying around to recycle, created a fresh env and proceed from there. I've updated the description to contain this information. 

Just here to inform, nothing more :)
