### ISSUE TITLE
Network RaiPlay has incorrect capitalisation.

### ISSUE THREAD

**Issue by Sap1ent** [pymedusa/Medusa#10306]
**Describe the bug**
Network RaiPlay has incorrect capitalisation. It is looking for Raiplay rather than RaiPlay - note the capital P.

**To Reproduce**
1. Add a show with RaiPlay as the network
2. Wait for it to poll the server
3.  Returns error as it can't find network

**Expected behavior**
RaiPlay network is found

**Screenshots**
![image](https://user-images.githubusercontent.com/20213712/152051932-cc47d683-95bd-4379-88f2-10aaa5ec5822.png)

**Comment by p0psicles** [comment]
Could be that it differs per Indexer. Tvdb, tvmaze and tmdb.

**Comment by p0psicles** [comment]
Doing some searches. I see that tvdb and tvmaze return `RaiPlay`, so your correct.

**Comment by p0psicles** [comment]
Updated the network file.
