### ISSUE TITLE
Medusa 0.5.22 will no longer move torrents or set torrent location properly with deluge <2.0

### ISSUE THREAD

**Issue by mglaske** [pymedusa/Medusa#10311]
After upgrading to 0.5.22 docker medusa, I noticed that all my downloads were now going into the default deluge download location, instead of the one specified in medusa.

Medusa v0.5.22 (docker)
Deluge v1.3.15-2
OS Ubuntu 18.04.5 LTS

**Comment by mglaske** [comment]
Some reference from my system:
```
>>> c = DelugeRPCClient("127.0.0.1", 58846, "mglaske", password, decode_utf8=True, automatic_reconnect=False)
>>> c.deluge_version = 1
>>> c.connect()
>>> x = c.call("daemon.info")
>>> print x
1.3.15
>>> sv = x.split(".")[0:2]
>>> print sv
[u'1', u'3']
>>> tuple(int(x) for x in sv)
(1, 3)
```

**Comment by p0psicles** [comment]
Medusa never changed the default download location. But it sets a download location on completed.
For example check this:
![image](https://user-images.githubusercontent.com/1331394/152677932-3a5d72ac-0e68-4e74-93ec-9863f5f17e00.png)

That's still working as it should.

**Comment by mglaske** [comment]
That's odd. For some reason, just after I updated to v0.5.22, it stopped setting that.
