### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Now

### ISSUE THREAD

**Issue by mariajopinchunga** [pymedusa/Medusa#10334]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.4.0-96-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/a3e25edce9537148227906f8a656891f
### ERROR
<pre>
2022-02-11 17:16:37 ERROR    MAIN :: [] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
There is several networks with this name:
https://www.themoviedb.org/search/network?query=Now
What timezone should be added?

**Comment by mariajopinchunga** [comment]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.4.0-105-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-03-29 20:30:50 ERROR    MAIN :: [] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@b618bb953204dfa1c13e8ede883b6be6ffde662a
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-04-09 11:29:40 ERROR    MAIN :: [b618bb9] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mariajopinchunga** [comment]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.4.0-107-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-04-12 03:02:04 ERROR    MAIN :: [] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mariajopinchunga** [comment]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.4.0-107-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/19a914e9b4b10326dad4ccc08b29bc33
### ERROR
<pre>
2022-04-17 09:20:45 ERROR    MAIN :: [] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mariajopinchunga** [comment]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.4.0-107-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/a466921a290e72952f3cf38c35342b82
### ERROR
<pre>
2022-04-17 10:42:30 ERROR    MAIN :: [] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mariajopinchunga** [comment]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.4.0-107-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-04-20 19:46:27 ERROR    MAIN :: [] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mariajopinchunga** [comment]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.4.0-109-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/bd1ca9bed3e0b8f7eb3fa0fe2e040465
### ERROR
<pre>
2022-04-24 08:02:39 ERROR    MAIN :: [] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mariajopinchunga** [comment]
### INFO
**Python Version**: `3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]`
**Operating System**: `Linux-5.4.0-109-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: https://gist.github.com/37f9dbb1c97e7de49a641809e84a7f4d
### ERROR
<pre>
2022-04-24 09:49:10 ERROR    MAIN :: [e4870f8] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mariajopinchunga** [comment]
### INFO
**Python Version**: `3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]`
**Operating System**: `Linux-5.4.0-110-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-05-17 22:19:01 ERROR    MAIN :: [e4870f8] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-05-26 08:06:40 ERROR    MAIN :: [e4870f8] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-05-28 09:09:38 ERROR    MAIN :: [e4870f8] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mariajopinchunga** [comment]
### INFO
**Python Version**: `3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]`
**Operating System**: `Linux-5.4.0-117-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6313f26ca6a940885c0282c3a704dd522b73ec1e
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-06-22 04:13:43 ERROR    MAIN :: [6313f26] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mews-se** [comment]
### INFO
**Python Version**: `3.6.9 (default, Mar 15 2022, 13:55:28) [GCC 8.4.0]`
**Operating System**: `Linux-5.4.101-1-pve-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
**Link to Log**: https://gist.github.com/98e919680a5070acbc0946938e94e195
### ERROR
<pre>
2022-06-23 12:11:27 ERROR    SHOWQUEUE-ADD :: [1405fbb] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fexofenadine** [comment]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/1ceb2601304adfc1e8f06e34666052ed
### ERROR
<pre>
2022-07-12 13:52:42 ERROR    MAIN :: [baad1e5] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fexofenadine** [comment]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/c233b42ff8d11c441d1c20c2782dde56
### ERROR
<pre>
2022-07-16 03:05:18 ERROR    MAIN :: [baad1e5] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fexofenadine** [comment]
### INFO
**Python Version**: `3.9.13 (main, Jul 26 2022, 13:12:30) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-07-31 21:05:55 ERROR    MAIN :: [baad1e5] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp65001`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@400903a534414868f6fcf74ea2a5adc71505645d
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-08-07 04:36:09 ERROR    SHOWQUEUE-UPDATE :: [400903a] Missing time zone for network: Now
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fexofenadine** [comment]
this issue seems to have fallen through the cracks somehow despite being reported a lot

**Comment by YogSottot** [comment]
> There is several networks with this name:
> https://www.themoviedb.org/search/network?query=Now
> What timezone should be added?

**Comment by fexofenadine** [comment]
https://www.themoviedb.org/network/1596 is the one affecting me. UK subsidiary of Sky. Used to be called *Now UK*
