### ISSUE TITLE
Mass update refresh doesn't do anything

### ISSUE THREAD

**Issue by h3llrais3r** [pymedusa/Medusa#10376]
**Describe the bug**
Mass update refresh doesn't do anything when action is triggered on 1 or more shows

**Expected behavior**
All selected shows are refreshed/rescanned

**Medusa (please complete the following information):**
- Branch: [master](https://github.com/pymedusa/Medusa/tree/master)
- Commit: [4908f30db4fb3d9d6e59c51ca07deab95fb03a91]
- Version: [0.5.24](https://github.com/pymedusa/Medusa/releases/tag/v0.5.24)
- Database: 44.19

**Debug logs (at least 50 lines):**
No logs as nothing is executed

**Comment by p0psicles** [comment]
Fixed in linked PR
