### ISSUE TITLE
Deluge warning and error ...

### ISSUE THREAD

**Issue by papampi** [pymedusa/Medusa#10385]
Getting these two warning and error after updated deluge container to latest version:
deluge version: 2.0.5
https://hub.docker.com/r/linuxserver/deluge

```
2022-03-02 18:52:00 WARNING  SNATCHQUEUE-SNATCH-401513 :: [9387e16] Error while trying to get the deluge daemon version. Error: 
2022-03-02 18:52:00 ERROR    SNATCHQUEUE-SNATCH-401513 :: [9387e16] DelugeD: Unable to set the ratio for Torrent
```

Medusa Info:	
Branch: develop
Commit: 9387e16f1c188985c2632565e2ebd907ca6b5191
Version: 0.5.24
Database: 44.19
 Python Version:	3.10.0 (default, Dec 10 2021, 08:29:27) [GCC 8.4.0]
 SSL Version:	OpenSSL 1.1.1l 24 Aug 2021
 OS:	Linux-5.10.60-qnap-x86_64-with-glibc2.27
 Locale:	en_US.UTF-8

**Comment by p0psicles** [comment]
I'll check it out

**Comment by papampi** [comment]
Seems like it was the docker problem, reinstalled and errors are gone

**Comment by fuxxociety** [comment]
Commenting for completeness. Found via google search.

Also experiencing this set of errors, but I'm running Debian 10, Deluge 1.3.15, and Medusa commit [5de42f0]. Nothing containerized, no dockers. Using a direct daemon connection, not the deluge-webui.

**Comment by p0psicles** [comment]
Did you get the exact same error? Any debug logs maybe?

**Comment by fuxxociety** [comment]
It was those two exact error messages. Debug logs were already flushed so no luck there, sorry. 
Now that I've updated to Deluge 2.0.3 those errors are gone as well.
