### ISSUE TITLE
[APP SUBMITTED]: DelugeD: Unable to set the path for Torrent

### ISSUE THREAD

**Issue by vadorrey** [pymedusa/Medusa#10417]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@5de42f0b40aefdecd3613b045391c691c3cedf87
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-03-18 12:24:06 ERROR    SNATCHQUEUE-SNATCH-364093 :: [5de42f0] DelugeD: Unable to set the path for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Need more info.
Like what deluge version.
Debug logs surrounding the error.
Are you always getting this error. Or occasionally?

**Comment by medariox** [comment]
Can't help without more info.
