### ISSUE TITLE
Can't add scene exceptions for seasons higher than tvdb highest season

### ISSUE THREAD

**Issue by 499926** [pymedusa/Medusa#10434]
**Describe the bug**
Can't add scene exceptions for seasons highest than tvdb highest season, if a show has 6 scene seasons that are mapped to 3 tvdb seasons you can't set scene exceptions for seasons 4+ because the web ui only allows you to set them for seasons 1-3(aka tvdb seasons). An example would be this show https://thexem.info/xem/show/5322 , tvdb has 9 seasons and scene has 13 yet you can't set up scene exceptions for seasons 10-13.  

**To Reproduce**
1. Go to a show whose scene mapping has more seasons than its tvdb mapping
2. Go to that show advanced settings(aka where you add scene exceptions)
3. Try to add a scene exception for a season whose number is higher than tvdb highest season
4. You can't, the web ui limits you to the highest tvdb season

**Expected behavior**
That you can add scene exceptions for any season number(this would be great for custom scene mappings) or at least it is limited by the highest scene season instead of the tvdb one. 

**Medusa (please complete the following information):**
 - OS: Windows 11 x64
 - Branch: master
 - Commit: [4908f30db4fb3d9d6e59c51ca07deab95fb03a91](https://github.com/pymedusa/Medusa/commit/4908f30db4fb3d9d6e59c51ca07deab95fb03a91)
 - Python version: 3.10.2
 - Database version: 44.19

**Comment by 499926** [comment]
Forgot to mention that the ability to remove default scene exceptions would be amazing(aka the ones medusa get from thexem)

**Comment by p0psicles** [comment]
You can already do that. Through search templates. At least you can disable them

**Comment by 499926** [comment]
You can disable the search template but medusa will use the scene exception to match the file right?

**Comment by p0psicles** [comment]
Yes that's correct

**Comment by p0psicles** [comment]
If you don't need episode mapping from xem. You can use tvmaze. Then you don't get xem mappings

**Comment by 499926** [comment]
Yeah I do need xem mapping but I'd like to decide which xem names I want to use
