### ISSUE TITLE
Server responds with: Unable to Connect

### ISSUE THREAD

**Issue by crypticraven** [pymedusa/Medusa#10450]
**Describe the bug**
Since the update that posted yesterday, I've been receivig a message from my docker-based container that the page states Unable to Connect. I've reset the configuration multiple times with no success. I've rebuilt my container with no success. I deleted my configuration and rebuilt the container with no success.

**To Reproduce**
1. Download the docker repo
2.  Configure or Reset the docker configuration
3.  If Configure: Map /config to configuration and logging directory. Map /tv to the Plex TV directory. Map /downloads to the directory to save the .torrent files.
4.  Start Docker Container
5.  Browse to site on port 8081 and receive error.

**Expected behavior**
Load the application and allow further configuration and mapping of the series in the Plex Television folder.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64] - Docker Container
 - Branch: [e.g. master, develop] Latest
 - Commit: [e.g. c65ca2] 15f4e8f
 - Python version: [e.g. 3.6.8] - What ever is required for Docker
 - Database version: [e.g. 44.12] - What ever is required for Docker

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug

Unable to get these as the app will not let me get to the page.

**Additional context**
No other issues; just unable to use the application that was functioning before the update.

**Comment by crypticraven** [comment]
For kicks and giggles; I can attempted the same configuration with the develop branch. The develop branch allows the connection to the web app with no issues.

**Comment by p0psicles** [comment]
Which docker image are you using?

But yeah this is weird. Because master and develop branch images are practically the same right now. Maybe something went wrong while building the docker image for the master branch.

**Comment by crypticraven** [comment]
The Docker app doesn't tell me what specific image is being used. The download from the library comes from https://hub.docker.com/r/pymedusa/medusa/. The download is 178 meg. There's a 20 meg difference between Master/Latest and Dev.

**Comment by p0psicles** [comment]
Can you wait a couple of days. Run develop in the mean time. I'm going to release in a couple of days anyways

**Comment by crypticraven** [comment]
Can do; the dev branch doesn't seem as unpredictable as I was originally anticipating!

**Comment by jaxjexjox** [comment]
I am also getting this, not sure what's going on?

**Comment by p0psicles** [comment]
Probably the creation of the latest docker (master/latest) image failed. So for now you can use the `develop` tag. That should work.

**Comment by jaxjexjox** [comment]
:develop tag has not fixed this issue :/ 

Anyone else nailed it?

**Comment by p0psicles** [comment]
Could you try pulling the latest master image. I released yesterday, should be fine now.

**Comment by jaxjexjox** [comment]
tag :develop  tag :master

No dice here.

**Comment by medariox** [comment]
Make sure you are using a supported browser.

**Comment by jaxjexjox** [comment]
I'm using Chrome.

**Comment by p0psicles** [comment]
What OS are you running on.
Try to recreate the container from scratch. Use an empty config folders, so your Starlet with a fresh config and shows.

**Comment by jaxjexjox** [comment]
Windows 10 Pro 64.


I'll make a new container, but this isn't fun. I've generally found Medusa to be particularly reliable.   I've tailored a lot of simple settings to ensure it grabs the right files. Specifically filters per show for custom naming so it doesn't snatch the wrong version.

**Comment by p0psicles** [comment]
I'm. It saying to ditch your existing config. You can keep that for backup of course. But you have to start somewhere debugging this.

**Comment by jaxjexjox** [comment]
I apologise. I do understand the standard process in diagnosing this.  I'll do some more thorough work tomorrow.  I was hoping many people were getting the issue and it might be an easy one.


Hook you up with a lot more info tomorrow.

**Comment by p0psicles** [comment]
If the image was really broken then a. It would also be broken when I tested it. And b. Yeah a lot of users would flood GitHub and discord with complaints

**Comment by jaxjexjox** [comment]
Have any releases been made since this post?
https://github.com/pymedusa/Medusa/issues/10450#issuecomment-1086614459

My system auto updates containers, it's all good now! So thanks for the help, appreciate it.
If it pops up again I'll delve in a lot deeper to take a peek.
