### ISSUE TITLE
Recent API Change - Manually Queuing Searches Not Working

### ISSUE THREAD

**Issue by LeeThompson** [pymedusa/Medusa#10463]
I have scheduled tasks that trigger medusa daily searches more often in the evenings, recently medusa appears to have had a change and now medusa is ignoring the search command.

If medusa's API support for the /search commands has been intentionally removed, please, please put it back in.   If there's some security reason, default it to disabled but put an option to enable it.

**To Reproduce**
`curl -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNZWR1c2EgTm9uZSIsImlhdCI6MTY0ODY3NDA2NywianRpIjoiUVNhb2tuV0tpMGFvQTdDU1RpU0oiLCJleHAiOjE2NDg3NjA0NjcsInVzZXJuYW1lIjoiIiwiYXBpS2V5IjoiNjc2MzM4MmNmOGY0Zjk1ZTdlZmJlNTRiZTdmMzRmNDcifQ.qIkDmNfLGOPjCUEa_Gwj04Kh92R1wt4w9soc-VCAY6I" -X PUT "http://[redacted]/api/v2/search/daily" --silent`

(Obviously the token changes each time.)

In Medusa's log, I can see it's successfully logging into the API (`APIv2-Thread-2 :: [e094759] logged into the API v2`) but it just does nothing.

**Expected behavior**
I expect it to act the same as if I pressed 'force' under Manage Searches/Daily Search.

**Medusa (please complete the following information):**
 - Docker Image: linuxserver/medusa
 - OS: Linux-3.10.105-x86_64-with (on Docker, Synology DS1817)
 - Branch: master
 - Commit: [e094759640ca61c5c033bf1ff9d33bc7fc1ba857](https://github.com/pymedusa/Medusa/commit/e094759640ca61c5c033bf1ff9d33bc7fc1ba857)
 - Python version: 3.9.7
 - Database version: 44.19

**Debug logs:**
Not relevant, no errors are being shown.
<details>

```
2022-03-30 14:03:07 INFO	APIv2-Thread-1 :: [e094759] logged into the API v2
2022-03-30 14:02:15 INFO	APIv2-Thread-2 :: [e094759] logged into the API v2
2022-03-30 14:01:07 INFO	APIv2-Thread-2 :: [e094759] logged into the API v2
```
</details>

**Updates**
The problem seems to be that the token is invalid when passed in, I'm at a loss as to why because this script has worked for quite some time.

The token should be accepted but isn't. 
I turned on curl's tracing and the results are attached, I've redacted the intranet dns entry, medusa's ip address and my apikey.

Traces:
* [medusa_trace_1_auth.log](https://github.com/pymedusa/Medusa/files/8384499/medusa_trace_1_auth.log)
* [medusa_trace_2_command.log](https://github.com/pymedusa/Medusa/files/8384500/medusa_trace_2_command.log)

Update:
I looked through the source code and I tried using "x-auth" instead of "Authorization" for the header entry and now it's working.    

```
0069: x-auth: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJN
00a9: ZWR1c2EgTm9uZSIsImlhdCI6MTY0ODY3ODg3NSwianRpIjoiODZoNzdWM3czYzlY
00e9: alYwWkVzOXYiLCJleHAiOjE2NDg3NjUyNzUsInVzZXJuYW1lIjoiIiwiYXBpS2V5
0129: IjoiNjc2MzM4MmNmOGY0Zjk1ZTdlZmJlNTRiZTdmMzRmNDcifQ.d2abBEFJuTBH3
0169: dYnQ_4Yb9_AVnwQliqsx47cRhUHagQ
```

**Comment by LeeThompson** [comment]
I looked through the source on the repo and as far as I can tell it should be working... if there were API changes, are they documented anywhere?

**Comment by p0psicles** [comment]
Jip that is it. We had to change to x-auth as the authentication header is also used for basic authentication.
