### ISSUE TITLE
Auto Post Process is not running

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#10484]
**Describe the bug**
Auto Post Process is not running

**To Reproduce**

**Expected behavior**
That downloads be moved to their correct locations, in stead they are backing up in the download folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/14140816/162580400-78f60091-298f-4bca-b9ae-d85d0c230546.png)

from the log;
![image](https://user-images.githubusercontent.com/14140816/162580496-e08f56c8-c2be-4346-ad1b-88bc02dab4c8.png)

**Medusa (please complete the following information):**
![image](https://user-images.githubusercontent.com/14140816/162580533-709ddd3b-dd1e-4db7-b70a-ed81e06970fc.png)

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>
see above nothing listed in log past 7 days for post processing
```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Can you create screenshots of your pp settings?
Also enable debug logs.
Then restart and wait until pp starts running.
Post your application.log

**Comment by xplayman** [comment]
@p0psicles Seems to be the same problem as I have.
I just noticed it 2 days ago or so, also Medusa UI has been really slow and even sometimes
unresponsive for the past week or so, or since the latest update. 
I'm running Medusa in FreeNas Jail (Not plugin) with SSD, 32 threads and 32gb RAM
so the machine shouldn't be the problem
The post process starts, does some work and then fails/crashes, I have to restart the jail to get it started again.
This is the last thing posted in the log file.

```
2022-04-10 13:25:14 ERROR	POSTPROCESSOR :: [b618bb9] Exception generated: sequence item 0: expected str instance, int found
Traceback (most recent call last):
  File "/usr/local/medusa/medusa/schedulers/scheduler.py", line 78, in run
    self.action.run(self.force)
  File "/usr/local/medusa/medusa/process_tv.py", line 232, in run
    process_results.process(force=force, **kwargs)
  File "/usr/local/medusa/medusa/process_tv.py", line 386, in process
    ignore_subs=ignore_subs)
  File "/usr/local/medusa/medusa/process_tv.py", line 651, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/usr/local/medusa/medusa/process_tv.py", line 895, in process_media
    self.process_failed(path, resource_name=video)
  File "/usr/local/medusa/medusa/process_tv.py", line 937, in process_failed
    self.result = processor.process()
  File "/usr/local/medusa/medusa/failed_processor.py", line 86, in process
    segment = self._process_release_name()
  File "/usr/local/medusa/medusa/failed_processor.py", line 66, in _process_release_name
    segment=','.join(ep.episode for ep in segment),
TypeError: sequence item 0: expected str instance, int found
```

Do you need anything else than this error?

**Comment by p0psicles** [comment]
That error has been fixed in the develop branch

**Comment by xplayman** [comment]
Allright thanks, any idea when it might end in master branch?

**Comment by p0psicles** [comment]
Today or tomorrow. Ill release

**Comment by p0psicles** [comment]
it's released
