### ISSUE TITLE
'Subtitled' disappearing from History when filtering

### ISSUE THREAD

**Issue by Frank071** [pymedusa/Medusa#10512]
**Preamble**
Lately I am having issues with subtitles that seem to be off-sync with (removed) commercial breaks. It happens quite a lot that I need to offset the subtitles a few seconds each time the episode was interrupted for commercials. That probably has nothing to do with Medusa, but it got me looking in the history tab. And there I saw something strange...

**Describe the bug**
Items marked 'subtitled' disappear when you filter "too much" the resource. See below

**To Reproduce**
Go to History
![afbeelding](https://user-images.githubusercontent.com/807403/164042325-f60193c5-972c-485e-87ef-6bab9f9950c8.png)
Type something in the filter field for episode, in this case 'n'
![afbeelding](https://user-images.githubusercontent.com/807403/164042714-e6a5ce8a-56fb-4ddd-abf8-2056516d4398.png)
Add an extra character, in this case 'c'
![afbeelding](https://user-images.githubusercontent.com/807403/164042834-bf6d3850-fa65-4a08-8b5a-1d786ac59d9b.png)
That is unexpected. 

**Expected behavior**
History list should be filtered so that all episodes with (in this case) 'nc' in the title are shown

**Medusa (please complete the following information):**
 - OS: Linux-4.4.180+-x86_64-with
 - Branch: master
 - Commit: b34f1df336e52cf0a690acbc393440ac9f8b3581
 - Python version: 3.9.7
 - Database version: 44.19

**Additional context**
Nothing found in the debug log. Call to backend does not seem suspicious. Filtering does strange things, as it also filters out items that need not be filtered out.

**Comment by Frank071** [comment]
OK... found it... the filter textbox is in the episode column, but in fact filters on the resource field. Which, for subtitles, is the language. Seems a bit odd. If no good reason, then I suggest to change the code so it filters 'episode'. Any opinions?

**Comment by p0psicles** [comment]
There is no really proper solution to this. In the database we use a field named `resource` to store the data for that specific type of resource. So language for subtitles and release name for a snatch/download.

So what I could do is add a column named `resource` to it because more clear what you filter on?

**Comment by p0psicles** [comment]
you would get something like this:
![image](https://user-images.githubusercontent.com/1331394/164224015-2a82bbcb-540b-4f6c-8f77-400b78a75c9c.png)

**Comment by Frank071** [comment]
Well... I am not sure if (and why) one wants to filter on resource (especially since it isn't (wasn't) shown in the list)... I stumbled across this because I wanted to search for specific episodes and thought that would filter those out. Never thought it would filter on a different field. So I personally would welcome the option to filter on episode title)...

**Comment by p0psicles** [comment]
We don't store episode title in the db. It's a computed value.
So we store separate values to specific an episode. show id + season number + episode number. And when the history table is build, we "create" and episode title.

But i'll see what I can do.

**Comment by Frank071** [comment]
Ah yes... now I see in the code. episodeTitle is a constructed value. Sorry, my bad. In that case I think it will in any case be more clear if that textbox is not in the same column as the title and leave the functionality as it is.

**Comment by p0psicles** [comment]
So should I add the column resource. Cause I need `a` column to put the textbox in?

**Comment by Frank071** [comment]
Well, to be honest: I have no idea what the purpose for searching the resource field would be. If there is no purpose then there is no real reason to have the textbox and thus neither for an extra column.

**Comment by p0psicles** [comment]
Yeah so that's the easiest to implement solution. A client side filter input field. But yeah that would only filter what's currently pulled from backend.

**Comment by p0psicles** [comment]
Another solution could be.
Filter by showid. And season + episode. So that would mean adding three columns. And you would need to know the show id.
I could add a small function in the frontend that would translate a show name to an id. So you could do some filtering by show name.

**Comment by Frank071** [comment]
I stumbled upon this just recently and I don't think it should take up much of your time. The main thing is that the user is aware they are not searching episode titles...

**Comment by p0psicles** [comment]
Yeah. Well the search input has a placeholder named `resource`. So I thought I had it covered. But apparently its not clear enough
