### ISSUE TITLE
Passwords gets scrubbed

### ISSUE THREAD

**Issue by Dohnerd** [pymedusa/Medusa#10519]
Medusa Info: | Branch: masterCommit: e4870f8f4a322e67c77434597ccc09aa6524aa05Version: 0.5.29Database: 44.19
-- | --
Python Version: | 3.10.0 (default, Dec 10 2021, 08:29:27) [GCC 8.4.0]
SSL Version: | OpenSSL 1.1.1l 24 Aug 2021
OS: | Linux-3.4.6-x86_64-with-glibc2.27
Locale: | en_US.UTF-8
Timezone: | CEST

Everytime i do a correction or use the GUI config, it scrubs my passwords, so I thought "hey I will just manually put them in config.ini" but same effect it scrubs passwords, even the ones i manually entered in config.ini, so I constantly have to set in my passwords, maybe 5-6 times a day.

**Comment by Dohnerd** [comment]
Well everytime i do something in the config it clears the passwords in config.ini, I don't know if that is by design (guess so?)

But after a while i starts giving errors in log (if i dont replace config.ini with clear text):
2022-04-20 05:08:31 ERROR    SNATCHQUEUE-SNATCH-62286 :: [e4870f8] Transmission: Invalid Username or Password, check your config
2022-04-20 05:08:31 WARNING  SNATCHQUEUE-SNATCH-62286 :: [e4870f8] Transmission: Unable to send Torrent

This also occurs for Opensubtitle and Addic7ed ...

Also while we are at it, because theres no place to put the user/pass for podnapisi it gives me:

2022-04-21 03:44:35 WARNING  POSTPROCESSOR :: [e4870f8] SSL error MaxRetryError("HTTPSConnectionPool(host='www.podnapisi.net', port=443): Max retries exceeded with url: /subtitles/search/old?sXML=1&sL=da&sK=Manifest&sTS=3&sTE=1&sY=2018 (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)')))"). Provider podnapisi

**Comment by p0psicles** [comment]
No that's not by design. When you change something in UI it should be saved in config.ini. 

But does it save other values correct in config.ini. like usernames, enabled providers, enabled subtitle providers?

**Comment by Dohnerd** [comment]
Yes it seems to save everything else just fine, just not the password, it defaults all passwords settings to "" after any thing done in the GUI (set pass, add show, add provider etc etc).

**Comment by p0psicles** [comment]
Do you have password encryption enabled?

**Comment by p0psicles** [comment]
I think something is going wrong there. I would try with encryption disabled

**Comment by Dohnerd** [comment]
ok just discovered there was a Medua update in sherpa, I will try that first and then try to remove the encryption

**Comment by Dohnerd** [comment]
I removed the encryption and that seems to help, the update didnt.....

**Comment by p0psicles** [comment]
Okay so it seems there is an issue with the credentials encryption.

**Comment by p0psicles** [comment]
In your config.ini
what is your encryption_version? Also does it show an encryption_secret?
Something like: zXYjPp6BQXOkImrF+7bZakkpFXes3EGgl6J6HkaQ2ma=

**Comment by Dohnerd** [comment]
encryption_version = 0
encryption_secret = ""

**Comment by p0psicles** [comment]
stop medusa.
remove both lines from config.ini
and start.
It should now have re-created both keys. But now with proper values.

**Comment by Dohnerd** [comment]
yes, now it'l be exciting to see if the error still occurs :)
I'll give a feedback in a couple of days :)
