### ISSUE TITLE
Question: how to I setup existing Medusa to use another [updated] python vesion?

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#10539]
Just a support question: I have installed a new python version 3.10.4 on Windows. How do I set medusa to use it  ? I think it is now using the release located right beside it. The path to new python version is defined the system $PATH . 
Will using that new py version be possible also with an older version of medusa? 

Thanks
Rafi

**Comment by BenjV** [comment]
Python 3 is backward compatible, so yes you can use all versions of medusa for python 3 with python 3.10.4

If you use the python command to start medusa it will search for python.exe in the current directory and if not found via the PATH environment variable.
So if you want to use a specific python version just specify the full path (for example "C:\Program Files\Python3\Python medusa.py") instead of just "python medusa.py".

**Comment by p0psicles** [comment]
But I think the issue is that he's using the windows installer. Which installs a service. And that service might run the application with a direct location to a python.exe.

So I'm not sure how to change it. I think you'd have to change a registry key somewhere

**Comment by rafi-d** [comment]
Right. I did change the registry key defining python ( Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Medusa\Parameters\Application )  . Still having errors. Since the latest Medusa version *IS* running good, I'll need to find the time to upgrade to it, instead of try finding old bugs...

**Comment by p0psicles** [comment]
I'll try to update the installer this week. Pack it with the 3.10 version

**Comment by rafi-d** [comment]
Great, let me know when you are done..

**Comment by BenjV** [comment]
My suggestion would be not to include a python installation in the installer and use the python3 installed on Windows that can be found via the PATH environment variable.
Just give a warning if python3 cannot be found via that environment variable.

That way everybody can upgrade to a newer version of python3 without the need to reinstall medusa.

**Comment by rafi-d** [comment]
> ... not to include a python installation in the installer and use the python3 installed on Windows that can be found via the PATH environment variable. Just give a warning if python3 cannot be found via that environment variable.
> 

+1 , or provide an option if to install also python or not

**Comment by p0psicles** [comment]
There are a lot of users who don't want to figure out how to install python. If I change that now I'm definitely getting a lot of support requests. And I'd like to prevent that.

Making it optional would be preferred. But I'm not motivated enough to spend a lot of time fixing the installer for that. So maybe I'll take a quick look at that. But I'll probably just include a new py version

**Comment by rafi-d** [comment]
> ... I'm not motivated enough ...

I don't know why adding y/n before installing python is a lot of work, but possibly consider something simpler - check if it is already in the %PATH%  and use just "python.exe" (no absolute path) in the provisioning of the service. You can keep copying python (if you must), it will just not be used... :)

**Comment by BenjV** [comment]
@rafi-d 
Make a little batch file in the Windows startup folder like this:

> C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\start_medusa.bat


Put a line like this in that bat file (change the path where python and medusa are to be found to your situation).:

> C:\Program Files\Python3\pythonw.exe C:\Program Files\Python3\medusa.py

pytonw.exe is a wrapper for python to start python applications as a Windows service.

**Comment by rafi-d** [comment]
[BenjV](https://github.com/BenjV)
It does work, but eventually it is a regular Windows task (but in the background) , not a real service... But it was a good test to confirm it is possible to use the latest python for an older version...

**Comment by BenjV** [comment]
What do you think is the difference between a task and a service?

A service can be used by other task, but that is not usefull in this case!

**Comment by rafi-d** [comment]
If they are similar, why not stick to what is already installed, and change it? 
One (minor) difference that I see - is the already available medusa UI control over the service (restart, shutdown etc). 
But as you said, there is not much of a difference otherwise, except maybe more integrated "recovery" options.

**Comment by BenjV** [comment]
As I said, security is an issue.
And why thing are done or not I don't know, I am just a user of medusa, not a developer.

**Comment by rafi-d** [comment]
https://www.ccleaner.com/recuva + restore into folders + force recheck after + download the rest...

**Comment by p0psicles** [comment]
Might take a while before I can take a look at this. I have an old windows laptop. But that's barely working

**Comment by rafi-d** [comment]
So, I changing the registry key defining python ( Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Medusa\Parameters\Application ) to just python.exe  (instead of including the full path to medusa python install)  - did the trick. 
Of cause one needs to make sure he has his python's path in the %PATH% variable, which should be done by the python installer.
Medusa installer can also add it's own python path to the %PATH%, so both native and medusa pythons  will be accessible.
