### ISSUE TITLE
Rate Limit calls to rarbg.to

### ISSUE THREAD

**Issue by flick1999** [pymedusa/Medusa#10538]
Not a bug, per se, so opening as a feature request. I noticed I was missing some sporadic episodes across all of my shows, so I did some digging and discovered that Medusa is getting my IP temporary banned from rarbg.to. They cite this as the cause:

You are making more than 10 requests per second to the site

I request that an option be added to specify a request per second rate for this (any?) provider.

Thank you.

**Comment by p0psicles** [comment]
I could take a look at that.
In the mean time. I suggest disabling the backlog searches for that provider.

**Comment by p0psicles** [comment]
You can try prowlarr. They have rate limiting build in btw.

**Comment by flick1999** [comment]
> I could take a look at that. In the mean time. I suggest disabling the backlog searches for that provider.

Good thought, thank you.

**Comment by flick1999** [comment]
> You can try prowlarr. They have rate limiting build in btw.

I'll take a poke at this, thank you.

**Comment by p0psicles** [comment]
So what I hear on the prowlarr discord. Is that rarbg gives random bans. Like some can be prevented. But apparently there are users that got banned despite following the rate limiting rules.
