### ISSUE TITLE
Git issue

### ISSUE THREAD

**Issue by Dohnerd** [pymedusa/Medusa#10543]
I know this is highly likeliy a git error, but I'm guessing you guys already know how to remove this issue:

WARNING  CHECKVERSION :: [e4870f8] "/opt/bin/git" branch master --set-upstream-to origin/master returned : error: could not lock config file .git/config: File exists
error: Unable to write upstream branch configuration

**Comment by BenjV** [comment]
Most likely a permission problem on that file.
Or another process is locking that file.
