### ISSUE TITLE
couldn't switch to develop branch

### ISSUE THREAD

**Issue by Orion83** [pymedusa/Medusa#10568]
**Describe the bug**
couldn't switch to develop branch, the checkout branch seems to be on a loop.

**Medusa (please complete the following information):**
 - OS: DSM 7.1 Linux-4.4.180+-x86_64-with-glibc2.2.5
 - Branch: master
 - Commit: [e4870f8f4a322e67c77434597ccc09aa6524aa05]
 - Python version: 3.8.12 (default, Oct 22 2021, 21:05:38) [GCC 7.5.0]
 - Database version: 44.19

**Comment by BenjV** [comment]
On a Synology it is not possible to switch to another branch.
The package is build for production, so only the master branch is available.

**Comment by p0psicles** [comment]
Maybe we should add a check to detect if medusa is running on synology, and disable the checkout functionality. Or add some comments about it?

**Comment by Orion83** [comment]
thx for the info.
any idea when will come the next merge to master?
Waiting the change info language in mass update option.
