### ISSUE TITLE
whence 0.5.29 reference on .../releases page?

### ISSUE THREAD

**Issue by mmhere** [pymedusa/Medusa#10562]
I see that this no longer mentions release version 0.5.29:
https://github.com/pymedusa/Medusa/releases

Yet I upgraded to 0.5.29 yesterday, which still exists here but isn't mentioned on the releases page:
https://github.com/pymedusa/Medusa/releases/tag/v0.5.29

Is there a reason 0.5.29 went away from the .../releases page?

Are there significant problems?

Apologies for creating an issue ticket for this, but I thought I'd inquire if 0.5.29 has some problems that mean it should be avoided.

Should I roll back?

**Comment by p0psicles** [comment]
Shouldn't impact that

**Comment by p0psicles** [comment]
I was able to restore the release.
