### ISSUE TITLE
Shows shown as backlogged 2 days before airdate

### ISSUE THREAD

**Issue by Kvothe1970** [pymedusa/Medusa#10573]
**Describe the bug**
Episodes are shown as wanted / in the backlog two days before the airdate. 

Airdate offset in show advanced setting is 0:

**Expected behavior**
Shows are listed as wanted and in backlog if airdate has passed current date. 

**Screenshots**
![AD3F827F-2D86-4D2F-BA9D-059FC9F4232E](https://user-images.githubusercontent.com/24984994/168869821-d50b45d3-d143-47b1-9b90-11cd60eaf0a9.jpeg)
![B6F3C414-6FF6-48A3-9917-0023CAFB0541](https://user-images.githubusercontent.com/24984994/168869798-584c9af1-84fb-47c9-9571-e45c3f327e13.png).

**Medusa (please complete the following information):**

Medusa Info: | Branch: master Commit: e4870f8f4a322e67c77434597ccc09aa6524aa05 Version: 0.5.29 Database: 44.19
-- | --
Python Version: | 3.10.4 (main, Apr 12 2022, 17:17:33) [GCC 8.4.0]
SSL Version: | OpenSSL 1.1.1n 15 Mar 2022
OS: | Linux-4.2.8-armv7l-with-glibc2.27
Locale: | Unknown.Unknown
Timezone: | CEST

Medusa Info:	Branch: [master](https://github.com/pymedusa/Medusa/tree/master) 
Commit: [e4870f8f4a322e67c77434597ccc09aa6524aa05](https://github.com/pymedusa/Medusa/commit/e4870f8f4a322e67c77434597ccc09aa6524aa05) 
Version: [0.5.29](https://github.com/pymedusa/Medusa/releases/tag/v0.5.29) 
Database: 44.19
 Python Version:	3.10.4 (main, Apr 12 2022, 17:17:33) [GCC 8.4.0]
 SSL Version:	OpenSSL 1.1.1n 15 Mar 2022
 OS:	Linux-4.2.8-armv7l-with-glibc2.27
 Locale:	Unknown.Unknown
Timezone:	CEST

**Comment by p0psicles** [comment]
Is this something that reproduces each week / episode for this show?
Could you enable debug log, restart. and try reproduce the issue. I'd need to check your logs.

**Comment by Kvothe1970** [comment]
Will do, there are not too many shows airing atm so I’ll try to reproduce it later because it’s def happening for ST SNW

**Comment by Kvothe1970** [comment]
pw: RP4S9KxYX2
https://pastebin.com/dR9PLUQ7

I performed a restart with DEBUG enabled. Show backlog was empty. 
After a while it was populated again with the incorrect entries: 
![image](https://user-images.githubusercontent.com/24984994/169005781-6443437e-f34b-478a-8599-9a8f46efd333.png)

**Comment by p0psicles** [comment]
They have already been changed to wanted before you enabled debug. So you'll want to catch the moment itll change a new ep to wanted pre maturely

**Comment by Kvothe1970** [comment]
I just performed a full force update on one of the shows, it reverts to unaired. Debug is till on. I expect this to change to wanted in a bit.

**Comment by Kvothe1970** [comment]
can confirm: 
![image](https://user-images.githubusercontent.com/24984994/169013976-2f9694b6-74ad-45ee-8eb2-b57bb9cd4954.png)
I updated the pastebin with the latest update starting with the time I pushed the force update on the show

**Comment by Kvothe1970** [comment]
Let me know if I should provide additional log entries for the next event. I’ve just kept Debug log level on for now.

**Comment by Kvothe1970** [comment]
With two new EPs coming up, issue reoccurs reliably.

**Comment by p0psicles** [comment]
I can't access your pastebin. Can you PM me on discord?

**Comment by Kvothe1970** [comment]
Sure, can you five me your discord ID?
