### ISSUE TITLE
Post-Processing - Custom airs by date, reset to default OFF 

### ISSUE THREAD

**Issue by crxed9** [pymedusa/Medusa#10572]
**Describe the bug**
Post-Processing - Custom airs by date reset to default OFF after medusa update

Whenever there is an update to Medusa, everything works as expected, BUT the "Custom airs by date" setting is turned OFF, resulting in different filenames than before the update/reboot.

**Expected behavior**
Setting to not be changed after update

**Screenshots**
Before update:
![image](https://user-images.githubusercontent.com/6422683/168666811-2a6ebd9a-1fa0-476b-9775-de11f76e3d67.png)

After Update
![image](https://user-images.githubusercontent.com/6422683/168666835-f591dd80-635a-4ecb-b6c5-209a7c246ae5.png)

**Medusa (please complete the following information):**
<html>
<body>

Medusa Info: | Branch: master
Commit: e4870f8f4a322e67c77434597ccc09aa6524aa05
Version: 0.5.29
Database: 44.19
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-10-10.0.19041-SP0
Locale: | nl_NL.cp1252
Timezone: | West-Europa (zomertijd)

</body>
</html>

**Comment by p0psicles** [comment]
Can you also reproduce with a Medusa restart?

**Comment by eddywitkamp** [comment]
Wow, I can even reproduce it by closing the browser and by opening Medusa again!

**Comment by p0psicles** [comment]
For me it's saving fine.
After saving, can you check your config.ini.
There should be a value like: `naming_custom_abd = 1`

Can you check for any errors/warnings in your application.log.
As well as any errors in the browsers console. (F12)

**Comment by p0psicles** [comment]
Do you get any errors in your browsers log?

**Comment by crxed9** [comment]
I am on Chrome stable V 102.0.5005.63 (Official build) (64-bits)

I enabled debug logging and the chrome log stayed empty
Nothing in the Medusa debug logging either

It happens in normal and in incognito mode
It also happens in Edge

Looks like it is just not reading that set property.


FOUND THIS:

If I go to 
http://localhost:8082/home
and then to Post Processing options and then to Episode Naming tab
the toggle is OFF

But if I go directly to
http://localhost:8082/config/postProcessing/
and then to Episode Naming tab
the toggle is ON

**Comment by p0psicles** [comment]
Good find. I can reproduce that. I can pick it up from there.

**Comment by p0psicles** [comment]
Fixed in develop branch
