### ISSUE TITLE
"NetworkError when attempting to fetch resource" error in Firefox

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#10584]
This popup box appears out of the blue:
![image](https://user-images.githubusercontent.com/2458280/169637274-76a31074-57d5-44ca-8036-9c1862a1d841.png)

No idea how to reproduce, but I found many references , which can hint . Couple of them are:
https://javascript.tutorialink.com/networkerror-when-attempting-to-fetch-resource-only-on-firefox/
https://javascript.tutorialink.com/networkerror-when-attempting-to-fetch-resource-only-on-firefox/
And maybe a hint here:
https://stackoverflow.com/questions/66853081/firefox-error-networkerror-when-attempting-to-fetch-resource-only-from-extensio

TBH, I am not 100% sure it is from medusa, but I do not have any other suspect... 

<html><body>

Medusa Info: | Branch:                 master                  Commit:                 e4870f8f4a322e67c77434597ccc09aa6524aa05                  Version:                 0.5.29                  Database:                 44.19
-- | --
Python Version: | 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.1n  15 Mar 2022
OS: | Windows-10-10.0.19044-SP0
Locale: | en_IL.cp1255
Timezone: | Jerusalem Daylight Time

</body>
</html>Medusa Info: 	Branch: [master](https://github.com/pymedusa/Medusa/tree/master)
Commit: [e4870f8f4a322e67c77434597ccc09aa6524aa05](https://github.com/pymedusa/Medusa/commit/e4870f8f4a322e67c77434597ccc09aa6524aa05)
Version: [0.5.29](https://github.com/pymedusa/Medusa/releases/tag/v0.5.29)
Database: 44.19
Python Version:	3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
SSL Version:	OpenSSL 1.1.1n 15 Mar 2022
OS:	Windows-10-10.0.19044-SP0
Locale:	en_IL.cp1255
Timezone:	Jerusalem Daylight Time

**Comment by p0psicles** [comment]
I can't reproduce this. So I can't do much about it.
So first thing you need to do, is try to reproduce this with some actions performed in medusa.

**Comment by p0psicles** [comment]
Okay, then I'd have to time the shutdown with a fetch of a resource through the apiv2.
But on the other hand, it's not that bad to get an error from the UI when the backend drops out.

**Comment by rafi-d** [comment]
It's a timing related issue. The browser is just faster to auto-start than
the  service ...

**Comment by rafi-d** [comment]
Ps: so, it is not dropping out, it never fully started...
