### ISSUE TITLE
Since 1.0 automatic upgrade it doesnt run, service on pause in windows 

### ISSUE THREAD

**Issue by hawkeye73** [pymedusa/Medusa#10689]
**Describe the bug**
I saw a mention of releasing 1.0 and thought I check which version I am running. No medusa anymore. I checked my Windows 2019 server where it runs and saw the service was on paused. Tried to stop/restart it, message Windows could not start the Medusa service on local computer. 

**To Reproduce**
I rebooted, same error

**Expected behavior**
Before it just ran fine, several updates for several years.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Windows Server 2019 latest updates
 - Branch: master
 - Commit: cannot check
 - Python version: 3.7.3
 - Database version: cannot check

**Additional context**
remove the service, reinstalled medusa using windows installer, no go.

**Comment by p0psicles** [comment]
Well shortly release version 1.0.1. that should fix it

**Comment by ac3nl** [comment]
> Well shortly release version 1.0.1. that should fix it

Any way to update that without total re-install?

**Comment by hawkeye73** [comment]
> Well shortly release version 1.0.1. that should fix it

What should I do now? I removed everything so I can restore a backup. Thanks for the fast reply!

**Comment by medariox** [comment]
Update to version 1.0.1 and restore the backup.
