### ISSUE TITLE
[request] how to fix an install of 1.0.0 with crash

### ISSUE THREAD

**Issue by ac3nl** [pymedusa/Medusa#10692]
I installed 1.0.0 with the python bug

how do i get to 1.0.1 without a total reinstall?
Which files do i need to update?

**Comment by steve-work** [comment]
Running a git pull worked for me:

 C:\Medusa\medusa> C:\Medusa\Git\cmd\git.exe pull

**Comment by p0psicles** [comment]
Yes you will need to run git commands.
git fetch origin
git reset --hard origin/master

**Comment by ac3nl** [comment]
i allready uninstalled my old synology package
now i used :medusa_noarch-all_20190826-2.spk

but it doesn't install it says: wrong fork

GIT_BRANCH="master"
GIT_URL="git://github.com/pymedusa/Medusa.git"

what is the right fork??

**Comment by p0psicles** [comment]
There is only one package you should use. https://github.com/BenjV/SYNO-packages/blob/master/Medusa%201.7%20Python%203%20noarch.spk from @BenjV

**Comment by ac3nl** [comment]
> There is only one package you should use. https://github.com/BenjV/SYNO-packages/blob/master/Medusa%201.7%20Python%203%20noarch.spk from @BenjV

gives invalid file format when tries to install

the old file was working fine before 1.0.0

**Comment by medariox** [comment]
You need to go on the GitHub page and press the Download button (top right).

**Comment by p0psicles** [comment]
@BenjV what is the recommended SPK for dsm5.2?

**Comment by BenjV** [comment]
The version fir Dsm 6 should work fine for Dsm 5.2
https://github.com/BenjV/SYNO-packages/blob/master/Medusa%201.7%20Python%203%20noarch.spk

**Comment by medariox** [comment]
For anyone having issues, please try with Medusa version 1.0.2. That should definitely solve the remaining boot issues.

**Comment by ac3nl** [comment]
> The version for Dsm 6 should work fine for Dsm 5.2 But I don't have a Dsm 5 around so I cannot test it It does a git pull during installation, so you willl get the latest version of Medusa.
> 
> https://github.com/BenjV/SYNO-packages/blob/master/Medusa%201.7%20Python%203%20noarch.spk

it doesn't "invalid file format"
can you fix the file you created medusa_noarch-all_20190826-2.spk
with the right repo?

regards, and many thanks

**Comment by p0psicles** [comment]
I think your not correctly downloading the file. Use the "Download" option in GitHub for that file.

**Comment by BenjV** [comment]
Aha I think I remember something from the old days.
DSM 5 packages had some strange requirement that inside the .spk the application (Medusa in this case) itself had to be packaged in a tar file.
Tomorrow I will look ito this and try to create a DSM 5 package for you, it may cost you some try an retry because I cannot test it myself by lack of DSM 5.

**Comment by BenjV** [comment]
For any change in a .spk a new package has to be created.
I don't know if I have that old package somewhere, but I rather adapt the current package because the old package included Medusa and the new package just does a git pull.

Are you using the Python3 from the SynoCommunity or the one from Synology?

**Comment by ac3nl** [comment]
> For any change in a .spk a new package has to be created. I don't know if I have that old package somewhere, but I rather adapt the current package because the old package included Medusa and the new package just does a git pull.
> 
> Are you using the Python3 from the SynoCommunity or the one from Synology? Welk model Nas gebruik je?

i use a DS1010+. the old package also did a git pull, thats why it says incorrect fork
i am on the syno community python 3

i used the old package before, and it worked for years and years.
i was able to update within medusa, all the time.
just this one, it broke because of the errors in 1.0.,0

**Comment by BenjV** [comment]
As far as I remember the old package had a fixed version of Medusa on board and after the installation you had to update it from within Medusa to get the latest.

The new package does not have Medusa on board but does a git pull during installation.

**Comment by ac3nl** [comment]
failed to install

**Comment by BenjV** [comment]
Ok I have to put more time into this tomorrow.

**Comment by ac3nl** [comment]
thanks for trying, really appreciate it!

**Comment by BenjV** [comment]
Ok one more try, in the hast I forgot a quote in the git_url
I pushed a new version to my github

**Comment by ac3nl** [comment]
WOW, up and running!!!

**Comment by ac3nl** [comment]
backup restored, and on version 1,.02

**Comment by BenjV** [comment]
Glad it worked out for you.

**Comment by ac3nl** [comment]
Maybe update the wiki with the new file?
