### ISSUE TITLE
error parsing media quality

### ISSUE THREAD

**Issue by mikeh143** [pymedusa/Medusa#10705]
**Describe the bug**
since updating to v 1, I am getting the following error on occasion when doing a re-scan files. After running the re-scan, new files have the quality set as "Unknown". I encoded the files myself to convert them to HEVC, but it used to show 720p with no errors. 

**To Reproduce**
Click Re-scan files on show page

**Expected behavior**
Files refresh with current file quality

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Windows
 - Branch: master
 - Commit: ad2c7adcde31a423ecd3195c1c76f39f67800451
 - Python version: 3.10.2
 - Database version: 44.19

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>
`2022-06-01 14:59:21 INFO	SHOWQUEUE-REFRESH :: [ad2c7ad] Cache check completed
2022-06-01 14:59:21 INFO	SHOWQUEUE-REFRESH :: [ad2c7ad] 409708: Updating NFOs for show with new indexer info
2022-06-01 14:59:21 INFO	SHOWQUEUE-REFRESH :: [ad2c7ad] Trying to clean any empty folder under T:\TV Shows\Storm Rising
2022-06-01 14:59:21 WARNING	SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: T:\TV Shows\Storm Rising\Storm.Rising.S01E05.Surging.Threat.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Plex\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Plex\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Plex\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Plex\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
</details>
![ss+(2022-06-01+at+02 58 20)](https://user-images.githubusercontent.com/52714265/171512230-a998156d-36b7-460d-a326-51a336da640e.png)

**Comment by mastafrooper** [comment]
Same error here.


`2022-06-02 02:51:10 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: \\ABYSS-SVR\Data\TV Series\American Dad!\Season 16\American Dad! - S16E24 - Yule. Tide. Repeat.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|       C:\ProgramData\chocolatey\bin\ffprobe.exe       |
|         v5.0.1-essentials_build-www.gyan.dev          |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Data\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Data\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Data\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Data\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+`

**Comment by medariox** [comment]
@mikeh143 
Can you please share one of your encoded files (just encode some short copyright free video)? That would allow us to reproduce the issue.

**Comment by p0psicles** [comment]
I can cook up a small python script that you can use to have MediaInfo scan the specific media file.

**Comment by p0psicles** [comment]
[test_mediainfo.zip](https://github.com/pymedusa/Medusa/files/8825262/test_mediainfo.zip)
Can you download the zip.
Then using pip install knowit.
`pip install knowit`
extract the test_mediainfo.zip.
Now run:
`python test_mediainfo.py "\ABYSS-SVR\Data\TV Series\American Dad!\Season 16\American Dad! - S16E24 - Yule. Tide. Repeat.mkv"`

or
`python test_mediainfo.py "T:\\TV Shows\\Storm Rising\\Storm.Rising.S01E05.Surging.Threat.mkv"

Then capture the output.

**Comment by p0psicles** [comment]
after your done uninstall knowit. `pip uninstall knowit`

**Comment by mikeh143** [comment]
Attached a couple outputs that have the issue

[output1.txt](https://github.com/pymedusa/Medusa/files/8825852/output1.txt)
[output2.txt](https://github.com/pymedusa/Medusa/files/8825853/output2.txt)

**Comment by mikeh143** [comment]
Note: If I manually change the quality in Medusa to 720p (using the dropdown on the show listing page), then re-scan again, there is no error. If I set it back to Unknown, and then re-scan, then the error appears again. Not sure if that is helpful at all

**Comment by mikeh143** [comment]
@p0psicles will do

**Comment by medariox** [comment]
The MediaInfo.dll version bundled with Medusa is quite old - that might be the issue.

**Comment by mikeh143** [comment]
@medariox you may be right. I replaced it with version 22.3.0.0, restarted Medusa and the error is gone
[MediaInfo.22.3.0.0.zip](https://github.com/pymedusa/Medusa/files/8826561/MediaInfo.22.3.0.0.zip)

**Comment by p0psicles** [comment]
I also was thinking in this direction. Cause I tried your re-encode. And it parsed just fine on my machine. (ubuntu 22.04)

**Comment by p0psicles** [comment]
@medariox shouldn't we add that version?

**Comment by medariox** [comment]
@p0psicles `pymediainfo` supports up to version v21.03 so I think that's the version we should include in the next release. I can open a PR to add it later.

**Comment by mikeh143** [comment]
I'll downgrade mine to 21.03, and will let you know if I see any issues with it

**Comment by mikeh143** [comment]
All good so far with 21.03. Attaching it here so you don't have to hunt for it
[MediaInfo.v21.03.0.0.zip](https://github.com/pymedusa/Medusa/files/8826699/MediaInfo.v21.03.0.0.zip)

**Comment by medariox** [comment]
Thanks a lot @mikeh143 
This PR also updates for Win32 and MacOSX: https://github.com/pymedusa/Medusa/pull/10711
