### ISSUE TITLE
rtorrent is not connecting

### ISSUE THREAD

**Issue by rosavanwinkle** [pymedusa/Medusa#10712]
**Describe the bug**
Rtorrent does not want to connect anymore since latest update... these have always being my default settings that worked
"2022-06-04 07:07:28 WARNING  Thread_0 :: [1c62acd] Error while testing rtorrent connection: Unable to authenticate with rtorrent client: [Errno 111] Connection refused"

**To Reproduce**
1. Go to search settings,torrent search
set to rtorrent
![image](https://user-images.githubusercontent.com/5783693/171985906-27423f53-3010-41cd-bb80-f3b765150fdd.png)

**Expected behavior**
succesfull connection to rtorrent

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Xubuntu (seedbox "seedhost.eu")
 - Branch: Master
 - Commit: [1c62acdc4e034951f00db31847bd00479e1db47c](https://github.com/pymedusa/Medusa/commit/1c62acdc4e034951f00db31847bd00479e1db47c)
 - Python version: [3.9.7
 - Database version: 44.19

**Debug logs (at least 50 lines):**
the logger even with debugs on... was not showing the errors so this is directly from the warning log screeen
2022-06-04 07:25:26 WARNING  DOWNLOADHANDLER :: [1c62acd] Unable to connect to rtorrent. Error: Unable to authenticate with rtorrent client: [Errno 111] Connection refused
2022-06-04 07:24:20 WARNING  Thread_0 :: [1c62acd] Error while testing rtorrent connection: Unable to authenticate with rtorrent client: [Errno 111] Connection refused
2022-06-04 07:07:09 WARNING  Thread_0 :: [1c62acd] Error while testing rtorrent connection: Unable to authenticate with rtorrent client: Supported authentication are: basic and digest
2022-06-04 07:06:40 WARNING  Thread_0 :: [1c62acd] Error while testing rtorrent connection: Unable to authenticate with rtorrent client: [Errno 99] Address not available
```

it used to work always perfectly fine,upon testing other clients those work rtorrent is the only not working...

**Comment by p0psicles** [comment]
Then something changes on your end. We haven't touched rtorrent client code in months

**Comment by rosavanwinkle** [comment]
Strange,well ive opend up a ticket with my seedbox provider and they set it to the right configuration...but upon pressing test it still gives me the error(i doubt they pressed test)... so lets see what the customer support replies to that.

ive made a backup just in case just now, if anything ill try reinstalling and see what it does then.

thank you for your information

**Comment by rosavanwinkle** [comment]
a reinstall did not fix medusa...so im fairly sure its something on rtorrents end...

**Comment by thompatry** [comment]
Have you tried RPC?

**Comment by rosavanwinkle** [comment]
> Have you tried RPC?

im sorry im not sure i follow what do you mean?  or suggest i try?

**Comment by thompatry** [comment]
Is the httprpc plugin install and enabled on rutorrent? If so, use the `https://localhost/rutorrent/plugins/httprpc/action.php` line in the connection box.

**Comment by rosavanwinkle** [comment]
![image](https://user-images.githubusercontent.com/5783693/172020395-50242214-afdc-4a9d-9ad2-a791464099b7.png)
i see it in this location... and iu have tried your url with all the diffrent variants 
of authentication and made sure the password is correct etc.

**Comment by thompatry** [comment]
Please set it up like this. I know the image is older.

![image](https://user-images.githubusercontent.com/1422320/172021103-93d8900a-fd74-4ba3-911e-12e45815eef6.png)

**Comment by rosavanwinkle** [comment]
diffrent error this time
`2022-06-04 20:37:00 WARNING  Thread_0 :: [1c62acd] Error while testing rtorrent connection: Unable to authenticate with rtorrent client: local variable 'response' referenced before assignment`

for reference this is what i enterd:
localhost/shuriken200/rutorrent/plugins/httprpc/action.php

image reference aswell:
![image](https://user-images.githubusercontent.com/5783693/172021220-ef58601c-c279-400b-ab43-37c2f4d5b1ba.png)

possible it has to do with something here? 
![image](https://user-images.githubusercontent.com/5783693/172021260-e442c7b2-b1b6-4eb9-b3fc-7a4be5288f57.png)

**Comment by rosavanwinkle** [comment]
PS: just want to say ty to all of you for the help and info so far...the customer support of seedhost is atm very horrible...might share the whole ticket sometime just to show how disapointing it is

**Comment by thompatry** [comment]
Did you put http in the front like the error states?

**Comment by rosavanwinkle** [comment]
> Did you put http in the front like the error states?
tried both https and http
http://localhost/shuriken200/rutorrent/plugins/httprpc/action.php
https://localhost/shuriken200/rutorrent/plugins/httprpc/action.php

same error
`2022-06-04 20:47:05 WARNING  Thread_0 :: [1c62acd] Error while testing rtorrent connection: Unable to authenticate with rtorrent client: local variable 'response' referenced before assignment`

**Comment by BenjV** [comment]
Did you check if the correct port is configured on you rutorrent installation
The config file (rtorrent.rc )should have this:


scgi_port = 127.0.0.1:5000

**Comment by rosavanwinkle** [comment]
hello sorry for the late reply,yup its in the rtorrent rc folder i checked.

**Comment by rosavanwinkle** [comment]
problem is solved,the people from seedhost fixed it once more and showed screenshots it succesfully connected
i checked the error logs they seemed to have some issues themselves...

the adress for me was this one

 https://server511.seedhost.eu/shuriken200/rutorrent/plugins/httprpc/action.php
![image](https://user-images.githubusercontent.com/5783693/172235881-e24f74d4-c3ce-4970-8e9e-65fbd2ac0e46.png)

i hope this can provide some help for others idk if they changed anything in the files of rtorrent but im glad its fixed hope the screenshot can provide some info
