### ISSUE TITLE
Update won't complete

### ISSUE THREAD

**Issue by steveschow** [pymedusa/Medusa#10759]
Trying to run update and just keep getting this error.

![Screen Shot 2022-06-12 at 9 20 06 AM](https://user-images.githubusercontent.com/9116800/173240195-18227f79-5d28-43be-9373-8fa633312100.jpg)

**Comment by p0psicles** [comment]
Same issue as this? https://github.com/pymedusa/Medusa/issues/10753#issuecomment-1153187642

**Comment by steveschow** [comment]
yes thanks.  Have to stop Medusa, manually delete the mediainfo.dll files and then start it and update right away.  Seemed to go through this time.
