### ISSUE TITLE
Unable to update 1.0.2 to 1.0.3 on Windows system

### ISSUE THREAD

**Issue by hawkeye73** [pymedusa/Medusa#10753]
**Describe the bug**
I wanted to update from 1.0.2 to 1.0.3 but I get an error. 

**To Reproduce**
Click update see:
Checking if medusa needs update: v
Waiting for medusa to create backup: v
Waiting for medusa to update: x

**Expected behavior**
Update it.

**Medusa (please complete the following information):**
 - OS: Windows Server 2019
 - Branch: master
 - Commit: [ad2c7adcde31a423ecd3195c1c76f39f67800451]
 - Python version: [3.7.3]
 - Database version: [44.19]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2022-06-10 21:47:27 WARNING	APIv2-Thread-36 :: [ad2c7ad] Enable 'git reset' in settings or stash your changes in local files
2022-06-10 21:47:22 WARNING	APIv2-Thread-36 :: [ad2c7ad] git reset --hard origin/master returned (128) : error: unable to unlink old 'lib/native/windows/x86_64/MediaInfo.dll': Invalid argument
fatal: Could not reset index file to revision 'origin/master'.
2022-06-10 21:47:22 INFO	APIv2-Thread-23 :: [ad2c7ad] Config backup successful
2022-06-10 21:46:37 INFO	APIv2-Thread-23 :: [ad2c7ad] Config backup in progress...
2022-06-10 21:46:21 WARNING	APIv2-Thread-10 :: [ad2c7ad] Config patch ignored {'git': {'resetBranches': 'master'}}
2022-06-10 21:41:18 WARNING	APIv2-Thread-23 :: [ad2c7ad] Enable 'git reset' in settings or stash your changes in local files
2022-06-10 21:41:17 WARNING	APIv2-Thread-23 :: [ad2c7ad] git reset --hard origin/master returned (128) : error: unable to unlink old 'lib/native/windows/x86_64/MediaInfo.dll': Invalid argument
fatal: Could not reset index file to revision 'origin/master'.
2022-06-10 21:41:16 INFO	APIv2-Thread-22 :: [ad2c7ad] Config backup successful
2022-06-10 21:40:31 INFO	APIv2-Thread-22 :: [ad2c7ad] Config backup in progress...
```
</details>

**Additional context**

**Comment by medariox** [comment]
Some files are still in use when Medusa tries to update. Try to restart and update again.

**Comment by hawkeye73** [comment]
I did that. Stopped and restarting the service. Same behavior. I will reboot the machine tomorrow. Thanks. Let you know more.

**Comment by adix** [comment]
I have the exact same issue with MediaInfo.dll.  Still exists after a reboot.

**Comment by adix** [comment]
Shutdown Medusa and was able to delete the dll restarted and was able to update.

**Comment by WarEagleUS21** [comment]
I too have the issue of trying to update (I am 14 commits behind) and when I let it do it I get this in my logs:

2022-06-11 04:49:05 WARNING  APIv2-Thread_53 :: [ad2c7ad] "C:\Medusa\Git\cmd\git.exe" reset --hard origin/master returned (128) : error: unable to unlink old 'lib/native/windows/x86_64/MediaInfo.dll': Invalid argument
fatal: Could not reset index file to revision 'origin/master'.
2022-06-11 04:49:05 WARNING  APIv2-Thread_53 :: [ad2c7ad] Enable 'git reset' in settings or stash your changes in local files

**Comment by WarEagleUS21** [comment]
I followed what adix did and now I am on 1.0.3

**Comment by hawkeye73** [comment]
> Shutdown Medusa and was able to delete the dll restarted and was able to update.

Thanks! I was able to delete the DLL, restart Medusa and able to update also. Now running 1.0.3. without rebooting the machine.

**Comment by nydave69** [comment]
error: unable to unlink old 'lib/native/windows/x86_64/MediaInfo.dll': Invalid argument
Did a search of the windows folder and subfolders that file doesn't exist. 
also no /x86_64/ folder

rebooted etc..  still cant update..

**Comment by adix** [comment]
The dll will be in a sub folder of your Medusa folder

**Comment by nydave69** [comment]
OK found the file deleted it..   `Update still fails

`2022-06-12 08:15:04 WARNING	APIv2-Thread-8 :: [ad2c7ad] Enable 'git reset' in settings or stash your changes in local files
2022-06-12 08:15:00 WARNING	APIv2-Thread-8 :: [ad2c7ad] git reset --hard origin/master returned (128) : Checking out files:   4% (315/7300)   
Checking out files:   5% (365/7300)   
Checking out files:   6% (438/7300)   
Checking out files:   7% (511/7300)   
Checking out files:   8% (584/7300)   
Checking out files:   8% (601/7300)   
Checking out files:   9% (657/7300)   
Checking out files:  10% (730/7300)   
Checking out files:  11% (803/7300)   
Checking out files:  12% (876/7300)   
Checking out files:  12% (895/7300)   
Checking out files:  13% (949/7300)   
Checking out files:  14% (1022/7300)   
Checking out files:  15% (1095/7300)   
Checking out files:  16% (1168/7300)   
Checking out files:  16% (1216/7300)   
Checking out files:  17% (1241/7300)   
Checking out files:  18% (1314/7300)   
Checking out files:  19% (1387/7300)   
Checking out files:  20% (1460/7300)   
Checking out files:  20% (1484/7300)   
Checking out files:  21% (1533/7300)   
Checking out files:  22% (1606/7300)   
Checking out files:  23% (1679/7300)   
Checking out files:  24% (1752/7300)   
Checking out files:  24% (1797/7300)   
Checking out files:  25% (1825/7300)   
Checking out files:  26% (1898/7300)   
Checking out files:  27% (1971/7300)   
Checking out files:  28% (2044/7300)   
Checking out files:  28% (2114/7300)   
Checking out files:  29% (2117/7300)   
Checking out files:  30% (2190/7300)   
error: unable to unlink old 'lib/native/windows/x86_64/MediaInfo.dll': Invalid argument

Checking out files:  31% (2263/7300)   
Checking out files:  31% (2296/7300)   
Checking out files:  32% (2336/7300)   
Checking out files:  33% (2409/7300)   
Checking out files:  34% (2482/7300)   
Checking out files:  35% (2555/7300)   
Checking out files:  35% (2578/7300)   
Checking out files:  36% (2628/7300)   
Checking out files:  37% (2701/7300)   
Checking out files:  38% (2774/7300)   
Checking out files:  39% (2847/7300)   
Checking out files:  39% (2870/7300)   
Checking out files:  40% (2920/7300)   
Checking out files:  41% (2993/7300)   
Checking out files:  42% (3066/7300)   
Checking out files:  43% (3139/7300)   
Checking out files:  43% (3149/7300)   
Checking out files:  44% (3212/7300)   
Checking out files:  45% (3285/7300)   
Checking out files:  46% (3358/7300)   
Checking out files:  47% (3431/7300)   
Checking out files:  47% (3439/7300)   
Checking out files:  48% (3504/7300)   
Checking out files:  49% (3577/7300)   
Checking out files:  50% (3650/7300)   
Checking out files:  50% (3720/7300)   
Checking out files:  51% (3723/7300)   
Checking out files:  52% (3796/7300)   
Checking out files:  53% (3869/7300)   
Checking out files:  54% (3942/7300)   
Checking out files:  54% (4001/7300)   
Checking out files:  55% (4015/7300)   
Checking out files:  56% (4088/7300)   
Checking out files:  57% (4161/7300)   
Checking out files:  58% (4234/7300)   
Checking out files:  58% (4291/7300)   
Checking out files:  59% (4307/7300)   
Checking out files:  60% (4380/7300)   
Checking out files:  61% (4453/7300)   
Checking out files:  62% (4526/7300)   
Checking out files:  62% (4571/7300)   
Checking out files:  63% (4599/7300)   
Checking out files:  64% (4672/7300)   
Checking out files:  65% (4745/7300)   
Checking out files:  66% (4818/7300)   
Checking out files:  66% (4853/7300)   
Checking out files:  67% (4891/7300)   
Checking out files:  68% (4964/7300)   
Checking out files:  69% (5037/7300)   
Checking out files:  70% (5110/7300)   
Checking out files:  70% (5127/7300)   
Checking out files:  71% (5183/7300)   
Checking out files:  72% (5256/7300)   
Checking out files:  73% (5329/7300)   
Checking out files:  73% (5391/7300)   
Checking out files:  74% (5402/7300)   
Checking out files:  75% (5475/7300)   
Checking out files:  76% (5548/7300)   
Checking out files:  77% (5621/7300)   
Checking out files:  77% (5666/7300)   
Checking out files:  78% (5694/7300)   
Checking out files:  79% (5767/7300)   
Checking out files:  80% (5840/7300)   
Checking out files:  80% (5905/7300)   
Checking out files:  81% (5913/7300)   
Checking out files:  82% (5986/7300)   
Checking out files:  83% (6059/7300)   
Checking out files:  84% (6132/7300)   
Checking out files:  84% (6187/7300)   
Checking out files:  85% (6205/7300)   
Checking out files:  86% (6278/7300)   
Checking out files:  87% (6351/7300)   
Checking out files:  88% (6424/7300)   
Checking out files:  88% (6461/7300)   
Checking out files:  89% (6497/7300)   
Checking out files:  90% (6570/7300)   
Checking out files:  91% (6643/7300)   
Checking out files:  92% (6716/7300)   
Checking out files:  92% (6731/7300)   
Checking out files:  93% (6789/7300)   
Checking out files:  94% (6862/7300)   
Checking out files:  95% (6935/7300)   
Checking out files:  95% (7001/7300)   
Checking out files:  96% (7008/7300)   
Checking out files:  97% (7081/7300)   
Checking out files:  98% (7154/7300)   
Checking out files:  99% (7227/7300)   
Checking out files:  99% (7279/7300)   
Checking out files: 100% (7300/7300)   
Checking out files: 100% (7300/7300), done.

fatal: Could not reset index file to revision 'origin/master'.
2022-06-12 08:14:32 INFO	APIv2-Thread-3 :: [ad2c7ad] Config backup successful
2022-06-12 08:12:05 INFO	APIv2-Thread-3 :: [ad2c7ad] Config backup in progress...
2022-06-12 08:11:53 INFO	APIv2-Thread-1 :: [ad2c7ad] Checking for updates using GitHub Updater
`

**Comment by p0psicles** [comment]
Can you try running the git reset manually when Medusa is stopped?

**Comment by adix** [comment]
There are 2 versions of the dll…did you delete the right one?

**Comment by nydave69** [comment]
> There are 2 versions of the dll…did you delete the right one?

only one file in that folder...
even with that error above, info show Version: [1.0.2]
and no update showing anymore..

**Comment by p0psicles** [comment]
Have you tried running the git commands manually?

**Comment by nydave69** [comment]
spoke tooo soon, took a couple of hours but the update is back.

**Comment by nydave69** [comment]
What version of python is required for 1.0.3
The version of Medusa I have installed has 3.7  within the Medusa package..
I noticed that 1.0.3 doesn't have python in the package, 

Should I install python 3.8.  ?

**Comment by p0psicles** [comment]
The Windows installer has python in it's package.

**Comment by nydave69** [comment]
Is there an installer for 1.0.3 somewhere

**Comment by hawkeye73** [comment]
Can somebody close this ticket ? I see a lot of off topic questions. Please make a ticket for your questions. So the questions and answers stay as clean as possible.
