### ISSUE TITLE
Having difficulty importing a file with "Processing failed: This show isn't in your list"

### ISSUE THREAD

**Issue by jaxjexjox** [pymedusa/Medusa#10756]
**Describe the bug**

**To Reproduce**

Added following TV show:
Love in Paradise: The Caribbean, A 90 Day Story.

Configured a scene exception, so that files will import from my provider.
Scene exceptions (x3 in an attempt to fix this?)

"Love.in.Paradise.The.Caribbean"
"love in paradise the caribbean"
"Love.in.Paradise.The.Caribbean."

Filename in the import (download) directory:
Love.in.Paradise.The.Caribbean.S01E01.(etc etc etc).mkv

Resulting fail, even on a manual post process:

Post-processing files: ['Love.in.Paradise.The.Caribbean.S01E01.Tropic.Like.Its.Hot.480p.x264-mSD.mkv']
Post-processing video files: ['Love.in.Paradise.The.Caribbean.S01E01.Tropic.Like.Its.Hot.480p.x264-mSD.mkv']
Processing failed for /downloads/Love.in.Paradise.The.Caribbean.S01E01.Tropic.Like.Its.Hot.480p.x264-mSD.mkv: This show isn't in your list, you need to add it before post-processing an episode
Problem(s) during processing, failed for the following files/folders: 
Missed file: /downloads/Love.in.Paradise.The.Caribbean.S01E01.Tropic.Like.Its.Hot.480p.x264-mSD.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode

**Expected behavior**

(I thought scene exception, tricks the program into accepting a filename as something else?)
Working file import

**Screenshots**
N/A

**Medusa (please complete the following information):**
Medusa Info:	Branch: master
Commit: 6313f26ca6a940885c0282c3a704dd522b73ec1e
Version: 1.0.3
Database: 44.19
 Python Version:	3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]
 SSL Version:	OpenSSL 1.1.1n 15 Mar 2022
 OS:	Linux-5.15.0-33-generic-x86_64-with
 Locale:	en_US.UTF-8
 Timezone:	AEST

Unsure what else I can do?  I am confused, coudl've sworn scene exception gets along mess with imports and search?

**Comment by p0psicles** [comment]
In config - postprocessing ( guessit tab ). You can test out release names.
