### ISSUE TITLE
medusa backlog not finding 4k on Dognzb

### ISSUE THREAD

**Issue by McEnnes** [pymedusa/Medusa#10769]
**Describe the bug**
I have in my custom search settings 1080p Web-DL, 1080p HDTV and 1080p Bluray in my allowed list.
In the preferred list i have 4k UHD TV, 4k UHD Web-DL and 4k UHD Bluray.

![Settings](https://user-images.githubusercontent.com/13847206/174436251-0ba861d3-2184-4337-adde-54ef6ff87ff5.png)

The 1080p video`s are downloaded and ok.
When i go to the Backlog overview i see some TV series who are downloaded in the 1080p format and waiting to find a 4k replacement.
**To Reproduce**
I do a backlog search for a 4k episode, in this case Prehistoric Planet S01e04
![Backlog](https://user-images.githubusercontent.com/13847206/174436111-f8506a4c-096f-4b48-92ab-4d4cbe3091ec.png)

In the search results i see that there are no 4k files found 
[New Text Document (2).txt](https://github.com/pymedusa/Medusa/files/8933459/New.Text.Document.2.txt)

**Expected behavior**
Finding a 4k version of this episode, because as you can see on the next screenshot, it is there to find.
![Dog](https://user-images.githubusercontent.com/13847206/174436329-fd96208e-8c46-4962-8757-1b1c07d98f3e.png)

I do not know if this is a bug, or a wrong setting on my side or something to do with dognzb
When i do a manual push from the dognzb website to my server with a 4k episode, everything works just fine.

**Medusa (please complete the following information):**
 - OS: [DSM 4.1-42661  Linux-4.4.180+-x86_64-with-glibc2.2.5
 - Branch: master
 - Commit: [[6313f26ca6a940885c0282c3a704dd522b73ec1e]
 - Python version: 3.8.12
 - Database version: 44.19

**Comment by p0psicles** [comment]
What's your provider config?

**Comment by McEnnes** [comment]
Is this what you mean?
![DogConf](https://user-images.githubusercontent.com/13847206/174488127-58f58ddb-b120-42f5-bb0d-dd37ac6f8602.png)

**Comment by McEnnes** [comment]
And/Or..
![IndexOpt](https://user-images.githubusercontent.com/13847206/174488409-c0678819-2bf0-456a-9be2-d14c978fe904.png)

**Comment by p0psicles** [comment]
Dognzb is a newznab based provider. Check your newznab tab. And check for the categories selected. You might need to add categories for 4k

**Comment by McEnnes** [comment]
That solved it indeed. Thank you very much, again!!
