### ISSUE TITLE
Could not get a downloaded release name from the history table

### ISSUE THREAD

**Issue by Amit86** [pymedusa/Medusa#10781]
Whenever I try to manually download a subtitle, it throws this error: "Could not get a downloaded release name from the history table".

The log doesn't provide any additional information:

> 2022-06-28 08:43:59 INFO	Thread-2 :: [ee1b898] Manual searching subtitles for: xxx
> 2022-06-28 08:43:59 INFO	Thread-2 :: [ee1b898] Starting to manual searching subtitles

I have subtitle providers available, and I can see that the subtitle is available on their site.

What can I do to fix this? it happens to all shows, all episodes.
(Auto downloading subtitles doesn't work either)

Thanks!

**Comment by p0psicles** [comment]
Did you download the episode through medusa, for which you are trying to get a sub?
Which subtitle provider did you have configured?
Enable debug logs, search for subtitle and post logs.

**Comment by Amit86** [comment]
Thank you for the quick reply!

Medusa auto-downloaded it, I only had to move it to the post-processing folder manually because I've been having some issues with auto-tools (it doesn't auto-move to the completed download folder).
This also happens with manual downloads

I have debug logs enabled, here's the log:

> 2022-06-28 09:00:22 WARNING	Thread :: [ee1b898] Unexpected error. Provider opensubtitles
> Traceback (most recent call last):
>   File "/app/medusa/ext/subliminal/core.py", line 115, in list_subtitles_provider
>     return self[provider].list_subtitles(video, provider_languages)
>   File "/app/medusa/ext/subliminal/core.py", line 67, in __getitem__
>     provider.initialize()
>   File "/app/medusa/ext/subliminal/providers/opensubtitles.py", line 129, in initialize
>     response = checked(self.server.LogIn(self.username, self.password, 'eng', self.user_agent))
>   File "/app/medusa/ext/subliminal/providers/opensubtitles.py", line 278, in checked
>     raise Unauthorized
> subliminal.providers.opensubtitles.Unauthorized
> 2022-06-28 09:00:22 WARNING	Thread :: [ee1b898] Unexpected error. Provider wizdom
> Traceback (most recent call last):
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 597, in urlopen
>     httplib_response = self._make_request(conn, method, url,
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
>     response.begin()
>   File "/usr/lib/python3.9/http/client.py", line 319, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.9/socket.py", line 704, in readinto
>     return self._sock.recv_into(b)
> ConnectionResetError: [Errno 104] Connection reset by peer
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/app/medusa/ext/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 637, in urlopen
>     retries = retries.increment(method, url, error=e, _pool=self,
>   File "/app/medusa/ext/urllib3/util/retry.py", line 367, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/app/medusa/ext/urllib3/packages/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 597, in urlopen
>     httplib_response = self._make_request(conn, method, url,
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
>     response.begin()
>   File "/usr/lib/python3.9/http/client.py", line 319, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.9/socket.py", line 704, in readinto
>     return self._sock.recv_into(b)
> urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/app/medusa/ext/subliminal/core.py", line 115, in list_subtitles_provider
>     return self[provider].list_subtitles(video, provider_languages)
>   File "/app/medusa/medusa/subtitle_providers/wizdom.py", line 193, in list_subtitles
>     return [s for s in self.query(title, season, episode, year, filename, imdb_id) if s.language in languages]
>   File "/app/medusa/medusa/subtitle_providers/wizdom.py", line 144, in query
>     r = self.session.get(url)
>   File "/app/medusa/ext/requests/sessions.py", line 555, in get
>     return self.request('GET', url, **kwargs)
>   File "/app/medusa/ext/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/app/medusa/ext/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/app/medusa/ext/requests/adapters.py", line 498, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> 2022-06-28 09:00:22 INFO	Thread :: [ee1b898] Manual searching subtitles for: xxx
> 2022-06-28 09:00:22 INFO	Thread :: [ee1b898] Starting to manual searching subtitles
> 2022-06-28 08:59:18 WARNING	Thread :: [ee1b898] Unexpected error. Provider opensubtitles

**Comment by Amit86** [comment]
Another log specific for Wizdom

> 2022-06-28 09:09:47 WARNING	Thread :: [ee1b898] Unexpected error. Provider wizdom
> Traceback (most recent call last):
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 597, in urlopen
>     httplib_response = self._make_request(conn, method, url,
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
>     response.begin()
>   File "/usr/lib/python3.9/http/client.py", line 319, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.9/socket.py", line 704, in readinto
>     return self._sock.recv_into(b)
> ConnectionResetError: [Errno 104] Connection reset by peer
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/app/medusa/ext/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 637, in urlopen
>     retries = retries.increment(method, url, error=e, _pool=self,
>   File "/app/medusa/ext/urllib3/util/retry.py", line 367, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/app/medusa/ext/urllib3/packages/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 597, in urlopen
>     httplib_response = self._make_request(conn, method, url,
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
>     response.begin()
>   File "/usr/lib/python3.9/http/client.py", line 319, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.9/socket.py", line 704, in readinto
>     return self._sock.recv_into(b)
> urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/app/medusa/ext/subliminal/core.py", line 115, in list_subtitles_provider
>     return self[provider].list_subtitles(video, provider_languages)
>   File "/app/medusa/medusa/subtitle_providers/wizdom.py", line 193, in list_subtitles
>     return [s for s in self.query(title, season, episode, year, filename, imdb_id) if s.language in languages]
>   File "/app/medusa/medusa/subtitle_providers/wizdom.py", line 144, in query
>     r = self.session.get(url)
>   File "/app/medusa/ext/requests/sessions.py", line 555, in get
>     return self.request('GET', url, **kwargs)
>   File "/app/medusa/ext/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/app/medusa/ext/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/app/medusa/ext/requests/adapters.py", line 498, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> 2022-06-28 09:09:47 INFO	Thread :: [ee1b898] Manual searching subtitles for: xxx
> 2022-06-28 09:09:47 INFO	Thread :: [ee1b898] Starting to manual searching subtitles

**Comment by p0psicles** [comment]
So opensubtitles seems your not authenticated. but could also be that the provider is broken in subliminal (which is the package we use for the subtitle searching).

Wizdom is having connection issues. Also a subliminal error. Better report there.
https://github.com/Diaoul/subliminal

**Comment by p0psicles** [comment]
the warning your getting `"Could not get a downloaded release name from the history table"` could be caused because your postprocessing loop isn't complete.

**Comment by Amit86** [comment]
I'll open up a report there as well. Thank you. 
For the post processing loop - I think it does get completed given I transfer manually and get a notification from medusa that it got added correctly, but subtitles are not added (I have a telegram notification set up)

**Comment by p0psicles** [comment]
Maybe you'll need to enable failed download handling. You could try that.

**Comment by p0psicles** [comment]
Wizdom is a medusa added custom subtitle provider. So this is a medusa bug.
I'll see if its an easy fix.

**Comment by Amit86** [comment]
Thank you so much, I appreciate your help!

**Comment by p0psicles** [comment]
Also the kodi addon is having the same issues.

**Comment by Amit86** [comment]
Thank you for the update, 
I've sent them a message via the contact me page, hope to get an answer soon.

**Comment by Amit86** [comment]
Hello @p0psicles 
I got a response that their API has been updated and all addons need to comply with the new updates
I've also asked for samples/demo/documentation but have yet to receive anything

**Comment by p0psicles** [comment]
That's good news. As soon as I have the specs I'll fix it

**Comment by Amit86** [comment]
As far as I can see there was a new addon released two months ago for Wizdom:
https://github.com/repoil/club/blob/master/service.subtitles.wizdom/service.subtitles.wizdom-2.0.6.zip

As part of it I can see some changes to how they pull subtitles:
```
def searchByIMDB(imdb, season=0, episode=0, version=0):
	filename = 'wizdom.imdb.%s.%s.%s.json' % (imdb, season, episode)
	url = "http://%s/search?action=by_id&imdb=%s&season=%s&episode=%s&version=%s" % (
		myDomain, imdb, season, episode, version)

	wlog("searchByIMDB:%s" % url)
	json = cachingJSON(filename,url)
	subs_rate = []  # TODO remove not in used
	if json != 0:
		for item_data in json:
			listitem = ListItem(label="Hebrew", label2=item_data["versioname"],
								thumbnailImage="he", iconImage="%s" % (item_data["score"]/2))
			if int(item_data["score"]) > 8:
				listitem.setProperty("sync", "true")
			url = "plugin://%s/?action=download&versioname=%s&id=%s&imdb=%s&season=%s&episode=%s" % (
					myScriptID, item_data["versioname"], item_data["id"],imdb, season, episode)
			addDirectoryItem(handle=int(sys.argv[1]), url=url, listitem=listitem, isFolder=False)
```

I'm not a coder, and there might be something that I am missing, hope that helps?

**Comment by Amit86** [comment]
Okay, they got back to me with this:
The changes in the paths are:
For Download:
[[https://wizdom.xyz/files/sub/](https://deref-mail.com/mail/client/8DIQrmLahVI/dereferrer/?redirectUrl=https%3A%2F%2Fwizdom.xyz%2Ffiles%2Fsub%2F){WIZDUM_SUB_ID}](https://wizdom.xyz/files/sub/{WIZDUM_SUB_ID})

For Search:
[https://wizdom.xyz/search](https://deref-mail.com/mail/client/RuL4XqcxLYI/dereferrer/?redirectUrl=https%3A%2F%2Fwizdom.xyz%2Fsearch) and then the query parameters are the same
 
Sorry for over-responding here, but as I get new information I share, as this is important to me :)

**Comment by p0psicles** [comment]
OKay so a valid search api call is `https://wizdom.xyz/api/search?action=by_id&imdb=tt10945036&season=1&episode=10`

**Comment by p0psicles** [comment]
Should be fixed in the develop branch. Can you test this for me?
