### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: TVING

### ISSUE THREAD

**Issue by fuxxociety** [pymedusa/Medusa#10789]
### INFO
**Python Version**: `3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]`
**Operating System**: `Linux-5.10.0-10-amd64-x86_64-with-glibc2.31`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6313f26ca6a940885c0282c3a704dd522b73ec1e
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-06-27 13:54:27 ERROR    MAIN :: [6313f26] Missing time zone for network: TVING
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mmhere** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-22-amd64-x86_64-with-debian-10.13`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4b480c924d0dbb01417333a5669b3cfcf19f9fe
**Link to Log**: https://gist.github.com/7c69676cb8b0275a7d5534a3238415f2
### ERROR
<pre>
2022-10-15 08:25:34 ERROR    SHOWQUEUE-ADD :: [e4b480c] Missing time zone for network: TVING
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mmhere** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-22-amd64-x86_64-with-debian-10.13`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4b480c924d0dbb01417333a5669b3cfcf19f9fe
**Link to Log**: https://gist.github.com/911cf0358bae23168b23fdadd6eb0dab
### ERROR
<pre>
2022-10-22 07:11:52 ERROR    MAIN :: [e4b480c] Missing time zone for network: TVING
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by taochern** [comment]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/f513a7a027a87d225abcd6276ddb7f51
### ERROR
<pre>
2022-12-31 06:32:16 ERROR    SHOWQUEUE-ADD :: [d9c31da] Missing time zone for network: TVING
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by taochern** [comment]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/8c08e16e7216faa1c8301e7a88fc7f2c
### ERROR
<pre>
2023-01-15 11:11:08 ERROR    MAIN :: [d9c31da] Missing time zone for network: TVING
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp65001`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@b9292f9d786e90a3aa0ba9a9ebdfebe4e0c5297e
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-01-27 09:19:42 ERROR    MAIN :: [b9292f9] Missing time zone for network: TVING
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by taochern** [comment]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/531dc2a4377b685b425d487e7992254b
### ERROR
<pre>
2023-02-07 21:22:00 ERROR    MAIN :: [d9c31da] Missing time zone for network: TVING
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by taochern** [comment]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/1f50f22c23782003604e362a9b97d3fe
### ERROR
<pre>
2023-02-16 16:46:46 ERROR    MAIN :: [d9c31da] Missing time zone for network: TVING
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
