### ISSUE TITLE
APIv2 docs are out of date

### ISSUE THREAD

**Issue by aidan-** [pymedusa/Medusa#10794]
**Describe the bug**
#10418 changed the auth header used for the Bearer token from `authorization` to `x-auth` which broke some consumers (Flexget/Flexget#3490).  The [documentation](https://github.com/pymedusa/Medusa/wiki/API-v2#intro) on how to authenticate to medusa needs to be updated to reference the correct header (`x-auth`).

**Expected behavior**
Docs correctly describe the header consumers should use for authenticating to medusa.

**Comment by p0psicles** [comment]
I'll change it
