### ISSUE TITLE
Waiting for Medusa to update: X

### ISSUE THREAD

**Issue by GoodBear1** [pymedusa/Medusa#10824]
Hi. Medusa failed to Update. I even manually copied over the new files after shutdown of Medusa (and stopping the service) but it still fails to update, "Waiting for Medusa to update: X".
![2022-07-15 Failed to Update Medusa](https://user-images.githubusercontent.com/85022380/179219854-3be95d0f-5764-46fa-b61d-f275709a5481.png)

Any advise on how to successfully update?

**Comment by p0psicles** [comment]
Check your logs for errors
