### ISSUE TITLE
Object of type Episode is not JSON serializable

### ISSUE THREAD

**Issue by adix** [pymedusa/Medusa#10889]
**INFO**
Medusa Info:
Branch: master
Commit: 400903a534414868f6fcf74ea2a5adc71505645d
Version: 1.0.6
Database: 44.19
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-7-6.1.7601-SP1

**WARNING**
2022-08-20 15:08:02 WARNING  SHOWQUEUE-UPDATE :: [400903a] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')

**Comment by medariox** [comment]
The next version will have a more detailed error. Please report again if it still happens.
