### ISSUE TITLE
Purge shows that have been added more then 180 ago

### ISSUE THREAD

**Issue by crxed9** [pymedusa/Medusa#10891]
**Describe the bug**
Log says "2022-08-21 00:18:02 INFO	GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-IMDB :: [400903a] Purge shows that have been added more then 180 ago"

But what does it mean....180 what?

Please correct with proper;
- VALUE.
- change THEN to THAN

-----------------

Medusa Info: | Branch: master
Commit: 400903a534414868f6fcf74ea2a5adc71505645dVersion: 1.0.6
Database: 44.19
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-10-10.0.19041-SP0
Locale: | nl_NL.cp1252
Timezone: | West-Europa (zomertijd)

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/10894
