### ISSUE TITLE
BUG OR DESIGN

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#10922]
Hi All,

I have noticed that when you use Recommend Shows it is not giving you a full list of what is in your Library etc...

So Example: TVDB shows a show called "Some Show Name" and you have it from TVMAZE it does not show it as Selected and shows you that you can add it again. 

There seems to be an disconnect based on provider etc...

Please let me know if you need any more info.

Thanks

**Comment by p0psicles** [comment]
It needs to have a mapping of tvmaze -> tvdb, to know if you already added it to your library. So maybe for some combinations it can't deduct that.

**Comment by p0psicles** [comment]
Do you have an example of shows that don't show as added in the recommended shows list?

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

So on Add Recommend Shows it selects the IMDB and then there is an long long list of shows that do not show as added. Here is some of them

ER
The X-Files
Halo

Thanks

**Comment by p0psicles** [comment]
and you've added these through tvdb?

**Comment by HPMSGEN8** [comment]
I checked Halo and it has an star next to tvmaze so i take it that is the primary source

**Comment by p0psicles** [comment]
Found the bug.

**Comment by HPMSGEN8** [comment]
Thanks for looking into this :)
