### ISSUE TITLE
Backlog / Daily Search Issue

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#10935]
Hi @p0psicles 

I might have found another issue. So i have 2 Providers setup for NZB but only 1 of them is showing when i do an Manual Search.

Also it is not finding the Version, Quality etc... that i am looking for but if i search the Site i see it. 

So i am not sure what is going on. I have even selected Randomize Providers. 

Thanks

**Comment by p0psicles** [comment]
maybe one provider is broken? And needs maintenance.

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

Issue Found & Closing :) 

Thanks
