### ISSUE TITLE
Files seem to be copied instead of moved by post-processor

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#10939]
When Medusa post-processes a file using the medusa included post-processor I can see the file size slowly growing over time in the tv-folder instead of instantly appearing. This leads me to believe that medusa copies the file instead of moving as is configured in the settings.

Env setup: Docker based images for SABnzb and medusa.
Medusa versions:
```
Branch: [master](https://github.com/pymedusa/Medusa/tree/master) 
Commit: [f690170c2cbd9f2804c38a6047059cb1ace8afe3](https://github.com/pymedusa/Medusa/commit/f690170c2cbd9f2804c38a6047059cb1ace8afe3) 
Version: [1.0.8](https://github.com/pymedusa/Medusa/releases/tag/v1.0.8) 
Database: 44.19
```

My whole setup is running using docker-compose and all paths are on a external USB drive.
SAB:
```
    volumes:
      - /Volumes/Docker/Containers/sabnzbd:/config
      - /Volumes/Docker/Download/downloads:/downloads
      - /Volumes/Docker/Download/incomplete:/incomplete-downloads
```
Medusa:
```
    volumes:
      - /Volumes/Docker/Containers/medusa:/config
      - /Volumes/Docker/Download/downloads/tv:/downloads
      - /Volumes/Docker/Media/TV:/tv
```

SAB will place d/l ed eps in the tv subfolder of the /downloads folder due to the category folder assignment. There they are picked up by Medusa w/o any issues and copied to the /tv folder. Looking at the folder /Volumes/Docker/Media/TV from the command line the file under processing is growing slowly over time hence it seems to be copied. As its an USB connection and rather slow the I/O is really limiting the post-processing here...

Medusa processing setup is:

![Screenshot 2022-09-23 at 09 42 22](https://user-images.githubusercontent.com/869637/191913400-0d1ea447-335c-4b8b-bb91-2b06918e79fb.png)

![Screenshot 2022-09-23 at 09 42 41](https://user-images.githubusercontent.com/869637/191913424-f9d48a02-7663-4ee6-b83f-4e0b76fce268.png)

Sorry if this has been asked before but I could not find this in any closed issue or other forum posts.

**Comment by BenjV** [comment]
If it is copied you should be able to see every file in two places.

But you are probably using a Synology with Btfrs as filesystem.
Btfrs is a COW( Copy On Write) filesystem so it cannot give an accurate prediction of the size in use, so looking at the size of a folder is 'None' information.

**Comment by udochrist** [comment]
Maybe this is just a misunderstanding of the word "copy" vs. "move" at my end.
In any case I want to have the file removed from my download folder after is has been transferred to the library.

so let me clarify what I mean; my assumption is:

 - move := file is moved from dl-folder to library-folder (unix analogy: mv <dl-file> <lib-file>)
 - copy := file is copied from dl-folder to library-folder  (unix analogy: cp <dl-file> <lib-file>)
 
after the move/copy operation has finished the d/l folder processed will get removed so I never have the file in two places.
from what is see I use "move" in the configuration but the operation used to transfer the file from the dl-folder to the library is "cp" instead of "mv".

hardware-wise we are talking about MacOS using a USB mounted APFS drive under docker.

**Comment by BenjV** [comment]
That is precisely what is does.
So instead of looking at size of folders you should check is you actually have two versions of the video on two places.

Also you must look in the logging.
A move is actually a copy followed by a delete of the original file.
So if for some reason the copy succeeded but the delete failed then you have to find out why it failed.
Could be a permission issue or the file is still open by another application like for example SabNzbd.

**Comment by udochrist** [comment]
understood.
I'm looking at file size in the library folder while the transfer is running and I could clearly see that the file is slowly growing in size. when the storage-medium is only usb-2 a copy of a large file takes a considerable amount of time as it needs to be read and written via the same link.

but its understood now: I/o-wise there is no difference between move and copy as move := copy + delete_orig.

**Comment by udochrist** [comment]
Just for the record: 
the "move" operation will try to move (i.e os.rename) and only if that fails it will do a copy&delete from download to library. 

I've changed my folder/volume setup so that the SAB TV downloads folder is mounted with the same volume in the medusa docker container.

so tv-download folder and library are on the same filesystem (and volume mount inside medusa) and the transfer of files from download-dir to library is instantaneous via the os.rename and therefore will save a lot of time spent in I/O esp. for slow connected drives

**Comment by BenjV** [comment]
Move does **not** exists, it is always a copy followed by a delete.
It would half the speed of the process if every buffer that was copied first had to be remove from the source and is the whole process is interrupted the net result would be two corrupted files.

Only if the source and the destination are on the same filesystem then it is as simply as changing the filepointer to a new location.

**Comment by udochrist** [comment]
Sorry. You’re wrong: The python code says that for “move” it’s doing a shutil.move( sec, dest). This internally is clever enough to do the copy/delete if a move is not possible due to crossing filesystems. Tested and working.

**Comment by BenjV** [comment]
That is exactly what I am saying.
If both on the same Filesystem is just changes the filepointer(called move) , if on a different filesystem it does copy and delete. 
That is what shutil.move() does
