### ISSUE TITLE
Processing Failed: File Is Locked For Reading

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#11079]
Good Day

I just installed DSM 7.1.1 and used the latest packing. I am having issues with post processing. the rights are still the same as in DSM 5

sc-download , sc-medusa has read write. So i am not sure what is going on. 

`Processing failed: File is locked for reading`

Thanks

**Comment by BenjV** [comment]
On DSM 7 all packages are running as a "system internal user" in this case sc-medusa.
That is not the same user as the sc-medusa that was used on the older DSM versions

So you have to give the system internal user 'sc-medusa"  permissions on the share where the files are located.
This can only be done on share level in DSM.
Go to control panel, shared folders, select the correct folder, click edit, choose permissions, select in de pulldown the "system internal uses" and give sc-medusa the correct permissions

**Comment by HPMSGEN8** [comment]
Thanks alot
