### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: KBS 2

### ISSUE THREAD

**Issue by taochern** [pymedusa/Medusa#11103]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-01-17 04:53:37 ERROR    SHOWQUEUE-SEASON-UPDATE :: [d9c31da] Missing time zone for network: KBS 2
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/pull/438
