### ISSUE TITLE
GuessitException('An internal error has occured in guessit - "IndexError: list index out of range"

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#11102]
**Describe the bug**
logs get spammed with Guessit errors
Getting: IndexError: list index out of range

To Reproduce, Just trigger a manual search of an EP with many Scene names.
not sure what the exact scene name triggers this.

**Screenshots**
<img width="2960" alt="Screen Shot 2023-01-16 at 4 16 32 pm" src="https://user-images.githubusercontent.com/2242880/212604603-548e355b-dc7e-408f-aac6-fe8ad73956c3.png">

<img width="2965" alt="Screen Shot 2023-01-16 at 10 46 33 pm" src="https://user-images.githubusercontent.com/2242880/212671362-f5795dac-768f-4b9a-9437-fe2f8f3b3038.png">

**Medusa (please complete the following information):**
 - OS: macOS 11.7.2
 - Branch: develop
 - Commit: 1064d7b9345170c4862d59951666b379f529ccea
 - Python version: 3.9.16 (main, Dec 7 2022, 10:15:13) [Clang 13.0.0 (clang-1300.0.29.30)]
 - Database version: 44.19

**Debug logs (at least 50 lines):**
[Guessit_Error2.log](https://github.com/pymedusa/Medusa/files/10425476/Guessit_Error2.log)
[Guessit_Error.log](https://github.com/pymedusa/Medusa/files/10425480/Guessit_Error.log)
[pyMedusa Logs.zip](https://github.com/pymedusa/Medusa/files/10425495/pyMedusa.Logs.zip)
_too big to post as raw text, hits max character limit on github_

**Additional context**
I've mentioned the issue on the Guessit Repo: https://github.com/guessit-io/guessit/issues/738#issue-1534322703
however, they said to report here instead.

this is getting beyond frustrating I get like 15-20 of these a day.

@pymedusa/support @pymedusa/moderators

Feel free to DM/ping me on your discord server for more info
XxUnkn0wnxX#0001

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/11105
