### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by psmoros** [pymedusa/Medusa#11134]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@brackishio) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by pizza-power** [comment]
The brackish account was converted into an organizational account, and access to huntr lost, so they will no longer be present on huntr. I'm the one that submitted the issue on huntr under the brackish account.

**Comment by medariox** [comment]
Hey! Thanks for your interest in reporting security issues in a responsible manner. You can report your finding privately through GitHub (see: https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability) and join our Discord server (https://discord.gg/zMdAdUK) for direct contact.
