### ISSUE TITLE
WARNING    CHECKVERSION :: [671a443] c:\program files (x86)\medusa\git\cmd\git.exe version returned : 'c:\program' is not recognized

### ISSUE THREAD

**Issue by heloid** [pymedusa/Medusa#11179]
Windows 10 PC, latest version.  671a443 /  1.0.12 (03-03-2023)

_"2023-03-19 10:10:46 WARNING    CHECKVERSION :: [671a443] c:\program files (x86)\medusa\git\cmd\git.exe version returned : 'c:\program' is not recognized as an internal or external command, operable program or batch file."_

This error is also causing warning messages presumably because Medusa can't find GIT:
_"You're using the branch. Please use 'master' unless specifically asked
Unable to find your git executable. Set git executable path in Advanced Settings OR shutdown application and delete your .git folder and run from source to enable updates."_

No issues with GIT  if manually run, so looks like the code isn't handling spaces in the Advanced Setting git path field:

_C:\Program Files (x86)\Medusa\Medusa>"C:\Program Files (x86)\Medusa\Git\cmd\git.exe" checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
C:\Program Files (x86)\Medusa\Medusa>"C:\Program Files (x86)\Medusa\Git\cmd\git.exe" pull
Already up to date._

**Comment by heloid** [comment]
```
        if platform.system().lower() == 'windows':
                cmd = '"' + git_path  + '"' + ' ' + args
        else: cmd = git_path + ' ' + args
```

This will fix the first issue. The OS File check still fails when the git_path has double quotes and without.

**Comment by medariox** [comment]
Thanks for the report. This should fix it: https://github.com/pymedusa/Medusa/pull/11182

**Comment by medariox** [comment]
Nvm, needs more work to do it properly.
