### ISSUE TITLE
Wrong show match

### ISSUE THREAD

**Issue by Willy0611** [pymedusa/Medusa#11196]
I have the following two shows:

1. 9-1-1
2. 9-1-1: Lone Star

Medusa is unable to find any downloads for "9-1-1: Lone Star". When I download an episode manually Medusa matches it with "9-1-1". When I then copy it to the "9-1-1: Lone Star" directory, rename it properly and do a "Re-scan files" then it is recognized as the correct episode in the correct show.

I migrated from SickChill which didn't have this issue.

**Comment by medariox** [comment]
Add `9-1-1 Lone Star` as scene exception for the entire show.

![img](https://i.imgur.com/WSl80f3.png)
