### ISSUE TITLE
PyPI dependency `imdbpie` causes failure for other modules

### ISSUE THREAD

**Issue by OneCDOnly** [pymedusa/Medusa#11204]
Hi all, 

I'm using Medusa installed from the `master` branch here on GitHub. Running on a QNAP NAS via Entware and inside a `virtualenv`. 

I'm seeing a dependency version issue when installing modules as per this project's `requirements.txt`:

It appears to be related to `imdbpie` (the following info was found with the excellent [pipdeptree](https://pypi.org/project/pipdeptree/) utility)
```
imdbpie==5.6.4
  - attrs [required: >=18.1.0,<19.0.0, installed: 21.4.0]
```
So, installing `imdbpie==5.6.4` then installs:
```
Collecting attrs<19.0.0,>=18.1.0
  Downloading attrs-18.2.0-py2.py3-none-any.whl (34 kB)
```
which then tries to uninstall the existing valid `attrs`:
```
  Attempting uninstall: attrs
    Found existing installation: attrs 21.4.0
    Not uninstalling attrs at /share/CACHEDEV2_DATA/.qpkg/Entware/lib/python3.10/site-packages, outside environment /share/CACHEDEV2_DATA/.qpkg/OMedusa/venv
    Can't uninstall 'attrs'. No files were found to uninstall.
```

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
twisted 22.4.0 requires attrs>=19.2.0, but you have attrs 18.2.0 which is incompatible.
automat 20.2.0 requires attrs>=19.2.0, but you have attrs 18.2.0 which is incompatible.
```
... but despite the message stating it couldn't uninstall the existing `attrs`, it seems to have installed the downgraded version fine:
```
Successfully installed ... attrs-18.2.0 ...
```
I then need to manually uninstall and reinstall `attrs` to get back to version 21.4.0

Can anyone please advise? Thank you. :)

**Comment by BenjV** [comment]
Medusa only uses attrs version 18.2.0

So you have created a virtual environment for more then Medusa only and that created this conflict.
Virtual environments are ment to be use by only one application in this case Medusa

As you can see pip complains about modules "twisted" and "automat" which are not part of Medusa.
Create for the application of those module their own virtual environment.

**Comment by OneCDOnly** [comment]
Thanks @BenjV  👍🏽 

Briefly: Medusa does run in its own virtualenv. However, this virtualenv also has access to system Python packages. 

I'll see if I can trace-back and work-out what's causing the `twisted` and `automat` modules to be installed.

Investigating this now...

**Comment by OneCDOnly** [comment]
As a test, I recreated a virtualenv for Medusa _without_ access to the system Python packages, and it worked fine. So, that makes this an easy fix. 😄 

As it's not related to the Medusa application, I'll close this issue.
