### ISSUE TITLE
Python issue when windows vm restarts

### ISSUE THREAD

**Issue by jsirota554** [pymedusa/Medusa#11215]
**Describe the bug**
Whenever our windows server restarts I receive issues starting medusa.

Traceback (most recent call last):
  File "C:\Medusa\Medusa\start.py", line 6, in <module>
    from medusa.__main__ import main
  File "C:\Medusa\Medusa\medusa\__main__.py", line 67, in <module>
    from medusa import (
  File "C:\Medusa\Medusa\medusa\helpers\__init__.py", line 49, in <module>
    from medusa.session.core import MedusaSafeSession
  File "C:\Medusa\Medusa\medusa\session\core.py", line 14, in <module>
    from medusa.session import factory, handlers, hooks
  File "C:\Medusa\Medusa\medusa\session\handlers.py", line 9, in <module>
    from cloudscraper import CloudScraper
  File "C:\Medusa\Medusa\ext\cloudscraper\__init__.py", line 36, in <module>
    from .cloudflare import Cloudflare
ModuleNotFoundError: No module named 'cloudscraper.cloudflare'

I have tried --force-reinstalling the requirements. This usually can be resolved by switching to different python versions or switching between cmd and powershell. But not always.

**To Reproduce**
1. Run the following in a command window "C:\Python311\python.exe "C:\Medusa\Medusa\start.py" --nolaunch --datadir="C:\Medusa\Data""

**Expected behavior**
Generally medusa starts.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Windows 10 Pro
 - Branch: tried master and develop
 - Commit: [7559c50]
 - Python version: 3.7.3, 3.8.10, 3.9.13, 3.10.4, 3.10.10, and 3.11.3,
 - Database version: 44.18

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
Cannot run medusa to receive these
```
</details>

**Additional context**
Started happening a few months ago, it may be a localized issue but any advice would also be appreciated.

**Comment by medariox** [comment]
This is usually a sign that you are running an old Medusa version with old dependencies or vice versa.

**Comment by jsirota554** [comment]
Fresh install of medusa, and restored backup seems to have resolved. Thanks
