### ISSUE TITLE
Postprocessing scripts cannot write to destination

### ISSUE THREAD

**Issue by fexofenadine** [pymedusa/Medusa#11240]
**Describe the bug**
Using a docker container, running postprocessing scripts results in "Permission denied" errors when I attempt to write to files in the destination directory. In this case, writing a metadata tag using ffmpeg. The rest of Medusa seems to be able to write to that directory and file, but not python postprocessing scripts. It's like these scripts are either not running as root, or the script is running with unexpected permissions.  The script works locally inside the container during testing, just not when medusa calls it.

**To Reproduce**
1. setup medusa to run a postprocessing script that writes to files with external processes (like ffmpeg or even touch).
2. trigger a manual postprocess on a file
3. check manual postprocessing's output

**Expected behavior**
Should be able to write to files, especially files that Medusa itself created.

**Medusa (please complete the following information):**
 - OS: Linux-4.4.180+-x86_64-with
 - Branch: master
 - Commit: baad1e5
 - Python version: 3.10.11 (main, Apr 6 2023, 01:16:54) [GCC 12.2.1 20220924]
 - Database version: 44.19

**Additional context**
If I'm doing something stupid here please let me know, I've tried many things and Googling hasn't been useful for this.

**Comment by fexofenadine** [comment]
ok, this may be just a workaround, or the actual intended behaviour - I was able to write to /tmp/ directory and then use shutil to move the new file to the correct place.  ffmpeg could not write directly to files in the tv_shows directory, but shutil can.

if this is intended behaviour, please close this as complete :) sorry if i've wasted your time

**Comment by ac3nl** [comment]
Latest version does respect UMASK

**Comment by ac3nl** [comment]
1.0.16 fixed this issue for me,

**Comment by fexofenadine** [comment]
yep working for me too, thanks!
