### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Cartoon Network Latin America

### ISSUE THREAD

**Issue by marcoaraujojunior** [pymedusa/Medusa#11252]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.15.0-72-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d45f98c9356f9cc6b819028c2fb52fae709c21dd
**Link to Log**: https://gist.github.com/marcoaraujojunior/c440f3b5225da39c12f2ea60cf52f1dc
### ERROR
<pre>
2023-05-21 12:30:51 ERROR    MAIN :: [d45f98c] Missing time zone for network: Cartoon Network Latin America
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
Time zones of LA: UTC−02:00 to UTC−08:00
I don't know what time zone should be used for this.

https://en.wikipedia.org/wiki/Cartoon_Network_(Latin_American_TV_channel)

**Comment by 88keyz** [comment]
Maybe this one.

https://www.tvmaze.com/networks/1753/cartoon-network

Timezone: America/Monterrey (GMT -6)
