### ISSUE TITLE
Sort by date on history not sorting

### ISSUE THREAD

**Issue by LethalCorpse** [pymedusa/Medusa#11302]
![image](https://github.com/pymedusa/Medusa/assets/351549/41ec4f77-aacf-48ff-9530-3bdab93c068d)
Not sure what this is sorting by, but it isn't date/time

**Comment by medariox** [comment]
It works for me. What browser and browser version are you using?

**Comment by LethalCorpse** [comment]
Firefox but confirmed on Chrome. I think I've figured out what it is, though. History list is updated when episodes are snatched, downloaded, or subtitled, not just when they're downloaded. The Time column lists the time when the episode was downloaded or snatched (I'm not sure which), but it sorts by the time of the most recent event (download or subtitle). I dunno why I'm getting subs weeks after the episode, but that's a lesser concern right now.

**Comment by LethalCorpse** [comment]
It's like sorting files by Date Modified, but only displaying Date Created, and labeling the column "Date".

**Comment by medariox** [comment]
Fixed with v1.0.17 https://github.com/pymedusa/Medusa/releases/tag/v1.0.17
