### ISSUE TITLE
History says no data for table

### ISSUE THREAD

**Issue by MotleyC** [pymedusa/Medusa#11371]
**Describe the bug**
After the most recent update the history no longer works. It just says No Data For table"
I have tried shutting down Medusa and restarting it.

**Medusa (please complete the following information):**
 - OS: Windows 10 x64
 - Branch: Master
 - Commit: 3d656652ab277e47689483912ed7fc443e7023e8
 - Python version: [e.g. 3.7.3]
 - Database version: [e.g. 44.19]

**Debug logs (at least 50 lines):**
Says nothing about history

**Comment by medariox** [comment]
Clear the cookies for Medusa. Here is an extensive guide on how to do it: https://www.lifewire.com/clear-cookies-for-one-site-4587347

**Comment by MotleyC** [comment]
That did the trick. Thank You!
