### ISSUE TITLE
[ FEATURE ] Remove Torrent Once Completed.

### ISSUE THREAD

**Issue by JonathanGorbutt** [pymedusa/Medusa#1139]
Hi,

I wanted to know if you would consider adding a remove torrent feature similar to how Sonarr does this?

For example once the episode is snatched and download then seeded to your desired ratio/time Medusa would check every so often and remove the torrent onces its finished seeding?

Many thanks again for creating an awesome piece of software and features.

**Comment by NicoLeOca** [comment]
I'd love that one too!

**Comment by fernandog** [comment]
@jonathanendersby we added an alpha feature for Transmission:

It only logs the removal so users can feedback if is removing something that it shouldn't

**Comment by NicoLeOca** [comment]
@fernandog 
I use Deluge; let me know when you want me to try out with this software

**Comment by fernandog** [comment]
@NicoLeOca i need some dev that uses deluge to code for it

**Comment by fernandog** [comment]
@NicoLeOca added to Deluge (develop)

**Comment by fernandog** [comment]
@JonathanGorbutt are you still using Medusa?  which client do you use?

**Comment by labrys** [comment]
Added to master feature request list - discussion for feature will continue here even though issue is closed.

**Comment by N1k0o8** [comment]
Still not working on Transmission and nothing and the logs.

It is still a feature ?

**Comment by p0psicles** [comment]
@fernandog this was working right?

**Comment by fernandog** [comment]
There is some users using it and no issues. Need logs with debug enabled otherwise can't help

**Comment by N1k0o8** [comment]
OK I've activated debug and change the frequency to 30min (minimum), keeping you posted.

**Comment by N1k0o8** [comment]
Hi all, good since the lastest update : 

2017-12-01 03:08:56 INFO     TORRENTCHECKER :: [b96b3ee] Torrent completed and reached minimum ratio: [1.001/1.000] or seed idle limit: [10080 min]. Removing it: [_CENSORED_]

**Comment by Rouzax** [comment]
I'm looking for this feature in the settings but can't seem to find it.
Is it also available for qBittorrent?

**Comment by fernandog** [comment]
No. Only transmission and deluge. Others don't have API to support

**Comment by Rouzax** [comment]
😄 that is the reason I can't find it.
