### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: National Geographic: Wild

### ISSUE THREAD

**Issue by gtlfilms** [pymedusa/Medusa#11410]
### INFO
**Python Version**: `3.11.4 (main, Jun  9 2023, 02:29:05) [GCC 12.2.1 20220924]`
**Operating System**: `Linux-5.10.0-21-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: https://gist.github.com/gtlfilms/bf1f8c6de31c30df3613e8f924d09c4e
### ERROR
<pre>
2023-07-18 16:49:04 ERROR    SHOWQUEUE-CHANGE-INDEXER :: [e4870f8] Missing time zone for network: National Geographic: Wild
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by gtlfilms** [comment]
### INFO
**Python Version**: `3.11.4 (main, Jun  9 2023, 02:29:05) [GCC 12.2.1 20220924]`
**Operating System**: `Linux-5.10.0-21-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: https://gist.github.com/gtlfilms/3133093546fac307edf02754ce9a438e
### ERROR
<pre>
2023-07-21 15:08:43 ERROR    MAIN :: [e4870f8] Missing time zone for network: National Geographic: Wild
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by DrakeJones** [comment]
Still an issue... ERROR    MAIN :: [34a67cf] Missing time zone for network: National Geographic Wild.  Nat Geo Wild as well.
