### ISSUE TITLE
Problem with the history section

### ISSUE THREAD

**Issue by bpivk** [pymedusa/Medusa#11430]
**Describe the bug**
I get an error while navigating to the history page. The error repeats whenever I restore my backup. A clean install works fine.

**To Reproduce**
I just use my backup and the error pops up.

**Expected behavior**
The page should open.

**Error**
`2023-07-30 19:32:54 ERROR    TORNADO :: [918cfe7] Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /api/v2/history?page=1&limit=50&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D&compact=true (192.168.0.55)
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
            ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'`

**Medusa (please complete the following information):**
 - OS: unraid
 - Branch: master

I suspect cleaning the database folder for my history would work.
Cleaning with clean and trim do nothing.

**Comment by narimanshariat** [comment]
Try to clear your cookies and refreshing the page.

**Comment by bpivk** [comment]
I did that. It happens in all my browsers on all my machines.

**Comment by medariox** [comment]
This is a known issue with old cookies, you need to clear Medusa's cookies. If you open the page while in incognito mode, it works fine, doesn't it?
