### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Freeform.com

### ISSUE THREAD

**Issue by pyrodex** [pymedusa/Medusa#11437]
### INFO
**Python Version**: `3.11.4 (main, Jun  9 2023, 02:29:05) [GCC 12.2.1 20220924]`
**Operating System**: `Linux-6.1.0-10-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@9b23c72f7e24bf638819e32d72f33e433f9649c4
**Link to Log**: https://gist.github.com/pyrodex/5151ea65da93853c9d0536f1b2e92969
### ERROR
<pre>
2023-08-04 07:00:28 ERROR    MAIN :: [9b23c72] Missing time zone for network: Freeform.com
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ComplexIOd** [comment]
### INFO
**Python Version**: `3.11.4 (main, Jun  9 2023, 02:29:05) [GCC 12.2.1 20220924]`
**Operating System**: `Linux-5.15.0-78-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/ComplexIOd/69a9fdad223710f33204ae634cee609d
### ERROR
<pre>
2023-08-05 10:23:06 ERROR    MAIN :: [] Missing time zone for network: Freeform.com
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
