### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Warhammer TV

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#11492]
### INFO
**Python Version**: `3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]`
**Operating System**: `Linux-6.2.0-34-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@3d656652ab277e47689483912ed7fc443e7023e8
**Link to Log**: https://gist.github.com/nydave69/a50087f5124176afa43771f9f6760e0c
### ERROR
<pre>
2023-10-11 10:44:50 ERROR    MAIN :: [3d65665] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]`
**Operating System**: `Linux-6.2.0-34-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@b8bec48d5036a4d9084d762e2d2ffca9c711f2f3
**Link to Log**: https://gist.github.com/nydave69/e3bc5e56bffca4f15bfc3d02d1281200
### ERROR
<pre>
2023-10-30 16:31:36 ERROR    MAIN :: [b8bec48] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]`
**Operating System**: `Linux-6.2.0-36-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@b8bec48d5036a4d9084d762e2d2ffca9c711f2f3
**Link to Log**: https://gist.github.com/nydave69/b55941f0708a64c1fe80030a089a8791
### ERROR
<pre>
2023-12-05 13:36:59 ERROR    MAIN :: [b8bec48] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]`
**Operating System**: `Linux-6.5.0-26-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6a0becf85d07b0b6919d94ed8a9f502faad17df8
**Link to Log**: https://gist.github.com/nydave69/ef91b27d67c57f447edb33bac9dba434
### ERROR
<pre>
2024-03-29 18:19:52 ERROR    MAIN :: [6a0becf] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-40-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@34a67cf159acab69017dd5b95e0233ecde0de28a
**Link to Log**: https://gist.github.com/nydave69/95121563289ee35124ab44de20d8a48f
### ERROR
<pre>
2024-08-29 08:12:58 ERROR    MAIN :: [34a67cf] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-40-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@34a67cf159acab69017dd5b95e0233ecde0de28a
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-09-10 18:02:32 ERROR    MAIN :: [34a67cf] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by taochern** [comment]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/taochern/6c9dc65bd79f98614584ac02f2c72d38
### ERROR
<pre>
2025-02-12 12:51:50 ERROR    MAIN :: [d9c31da] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by taochern** [comment]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/taochern/5742dd5dfe1938fef334e738d360edb2
### ERROR
<pre>
2025-02-25 18:08:06 ERROR    MAIN :: [d9c31da] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by taochern** [comment]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/taochern/f74291a9fe01fc765e7084421e24b2d1
### ERROR
<pre>
2025-03-12 18:23:42 ERROR    MAIN :: [d9c31da] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by taochern** [comment]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/taochern/8aaa53dac2f8fa516b7256d7a923eeb4
### ERROR
<pre>
2025-03-15 05:03:24 ERROR    MAIN :: [d9c31da] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by taochern** [comment]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: **No Log available**
### ERROR
<pre>
2025-03-15 22:50:21 ERROR    MAIN :: [d9c31da] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-51-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d99638720355ef047857735876ec37adcb6a94a5
**Link to Log**: https://gist.github.com/nydave69/2475fd51681b9c7c47f7f209b81d4085
### ERROR
<pre>
2025-03-18 08:22:43 ERROR    MAIN :: [d996387] Missing time zone for network: Warhammer TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
