### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: PLANÈTE+

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#11502]
### INFO
**Python Version**: `3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]`
**Operating System**: `Linux-6.2.0-34-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@3d656652ab277e47689483912ed7fc443e7023e8
**Link to Log**: https://gist.github.com/nydave69/e5b40fbfbba8563932076fdb25d235f6
### ERROR
<pre>
2023-10-11 10:45:04 ERROR    MAIN :: [3d65665] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]`
**Operating System**: `Linux-6.2.0-34-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@b8bec48d5036a4d9084d762e2d2ffca9c711f2f3
**Link to Log**: https://gist.github.com/nydave69/b70f9b28a454389d3cfc64d02e25902a
### ERROR
<pre>
2023-10-30 16:50:48 ERROR    MAIN :: [b8bec48] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]`
**Operating System**: `Linux-6.2.0-34-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@b8bec48d5036a4d9084d762e2d2ffca9c711f2f3
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-10-30 17:30:57 ERROR    MAIN :: [b8bec48] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]`
**Operating System**: `Linux-6.2.0-39-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-12-19 07:25:43 ERROR    MAIN :: [c5a1e37] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]`
**Operating System**: `Linux-6.5.0-26-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6a0becf85d07b0b6919d94ed8a9f502faad17df8
**Link to Log**: https://gist.github.com/nydave69/8bd27e306b16a37c292321311f0d8c8d
### ERROR
<pre>
2024-03-29 18:15:40 ERROR    MAIN :: [6a0becf] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]`
**Operating System**: `Linux-6.5.0-28-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@34a67cf159acab69017dd5b95e0233ecde0de28a
**Link to Log**: https://gist.github.com/nydave69/84bb81ed1374d2426b8bd8652b709abe
### ERROR
<pre>
2024-07-12 16:05:14 ERROR    MAIN :: [34a67cf] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Mika3578** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@4f79d3f1a5e74c4a9857f28e14ee7e3a11886d0b
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-12-21 22:13:11 ERROR    MAIN :: [4f79d3f] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Mika3578** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@4f79d3f1a5e74c4a9857f28e14ee7e3a11886d0b
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-12-25 00:47:37 ERROR    MAIN :: [4f79d3f] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-52-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d99638720355ef047857735876ec37adcb6a94a5
**Link to Log**: https://gist.github.com/nydave69/b2d4531f8e99dd5d2d2a5291461f63b6
### ERROR
<pre>
2025-04-02 19:28:07 ERROR    MAIN :: [d996387] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Mika3578** [comment]
### INFO
**Python Version**: `3.12.9 (main, Feb  7 2025, 17:39:29) [GCC 14.2.0]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/Mika3578/1e27a9bb6f75c9ce3f545fe412135045
### ERROR
<pre>
2025-04-08 13:30:48 ERROR    MAIN :: [] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Mika3578** [comment]
### INFO
**Python Version**: `3.11.13 (main, Jun  9 2025, 08:59:37) [GCC 13.2.1 20231014]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/Mika3578/2643400b28ff0307685622a8b90f3e42
### ERROR
<pre>
2025-08-01 14:14:30 ERROR    MAIN :: [] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Aug 15 2025, 14:32:43) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-87-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@59bb4eca2791b1605a84b498a5d53382f5b82d82
**Link to Log**: https://gist.github.com/nydave69/0722705193086e2137376617b00615d9
### ERROR
<pre>
2025-11-12 10:36:14 ERROR    MAIN :: [59bb4ec] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Aug 15 2025, 14:32:43) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-87-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@27e13769e83197d8e4ba7145f964384058592d4a
**Link to Log**: https://gist.github.com/nydave69/2f2c683393bc5f6e36932682fb9d003d
### ERROR
<pre>
2025-11-15 12:09:06 ERROR    MAIN :: [27e1376] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Aug 15 2025, 14:32:43) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-87-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@27e13769e83197d8e4ba7145f964384058592d4a
**Link to Log**: https://gist.github.com/nydave69/3ee1660b68f0190fd8343e101267e203
### ERROR
<pre>
2025-11-15 15:12:50 ERROR    MAIN :: [27e1376] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Aug 15 2025, 14:32:43) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-87-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@27e13769e83197d8e4ba7145f964384058592d4a
**Link to Log**: **No Log available**
### ERROR
<pre>
2025-11-18 09:21:16 ERROR    MAIN :: [27e1376] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Aug 15 2025, 14:32:43) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-87-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@27e13769e83197d8e4ba7145f964384058592d4a
**Link to Log**: https://gist.github.com/nydave69/c0744dd039abffc9fc5f0536b4df615c
### ERROR
<pre>
2025-11-22 09:20:00 ERROR    MAIN :: [27e1376] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Aug 15 2025, 14:32:43) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-87-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@27e13769e83197d8e4ba7145f964384058592d4a
**Link to Log**: https://gist.github.com/nydave69/70908c0a5b92209d1b9505521679d053
### ERROR
<pre>
2025-11-26 14:28:22 ERROR    MAIN :: [27e1376] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Nov  4 2025, 08:48:33) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-87-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@27e13769e83197d8e4ba7145f964384058592d4a
**Link to Log**: https://gist.github.com/nydave69/2cc56f9d180603ea76bbf3d870fadfec
### ERROR
<pre>
2025-12-31 09:02:47 ERROR    MAIN :: [27e1376] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Nov  4 2025, 08:48:33) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-87-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@27e13769e83197d8e4ba7145f964384058592d4a
**Link to Log**: **No Log available**
### ERROR
<pre>
2026-01-07 12:34:24 ERROR    MAIN :: [27e1376] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Mar  3 2026, 11:56:32) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-100-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@27e13769e83197d8e4ba7145f964384058592d4a
**Link to Log**: https://gist.github.com/nydave69/95c394b709dd50b63752afa7d2966890
### ERROR
<pre>
2026-04-16 07:55:10 ERROR    MAIN :: [27e1376] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Mar  3 2026, 11:56:32) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-100-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@2bc1eb2b0ea53305639c2e2a076c0dfb8914916f
**Link to Log**: https://gist.github.com/nydave69/cad296f434ea811908c08f9e1f512192
### ERROR
<pre>
2026-05-24 14:48:05 ERROR    MAIN :: [2bc1eb2] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Mar  3 2026, 11:56:32) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-100-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@2bc1eb2b0ea53305639c2e2a076c0dfb8914916f
**Link to Log**: https://gist.github.com/nydave69/b19200daf03ed35db00b47ca36e3c5ee
### ERROR
<pre>
2026-07-06 07:46:04 ERROR    MAIN :: [2bc1eb2] Missing time zone for network: PLANÈTE+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
