### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Zues

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#11572]
### INFO
**Python Version**: `3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]`
**Operating System**: `Linux-6.2.0-36-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@b8bec48d5036a4d9084d762e2d2ffca9c711f2f3
**Link to Log**: https://gist.github.com/nydave69/6e1f50a49e7c5f79ff70110ca833514a
### ERROR
<pre>
2023-12-05 13:37:07 ERROR    MAIN :: [b8bec48] Missing time zone for network: Zues
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
It's Zeus, not Zues
There's an error in themoviedb
https://www.themoviedb.org/tv/218537-baddies-west

The imdb has the correct information
https://www.imdb.com/title/tt26442901/

Need to fix an error in moviedb, not medusa

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]`
**Operating System**: `Linux-6.5.0-26-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6a0becf85d07b0b6919d94ed8a9f502faad17df8
**Link to Log**: https://gist.github.com/nydave69/fc45c92081f9a88f0259efb741b8f9a3
### ERROR
<pre>
2024-03-29 18:20:02 ERROR    MAIN :: [6a0becf] Missing time zone for network: Zues
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-40-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@34a67cf159acab69017dd5b95e0233ecde0de28a
**Link to Log**: https://gist.github.com/nydave69/4962350bcf8c69780389ab4862438937
### ERROR
<pre>
2024-08-29 08:13:10 ERROR    MAIN :: [34a67cf] Missing time zone for network: Zues
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]`
**Operating System**: `Linux-6.8.0-40-generic-x86_64-with-glibc2.35`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@34a67cf159acab69017dd5b95e0233ecde0de28a
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-09-10 18:02:45 ERROR    MAIN :: [34a67cf] Missing time zone for network: Zues
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
