### ISSUE TITLE
History page fails parsing sort parameter

### ISSUE THREAD

**Issue by bitchkat** [pymedusa/Medusa#11637]
**Describe the bug**
Accessing the history page generates an error and the log contains:
2024-02-27 18:27:43 ERROR    TORNADO :: [c5a1e37] Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")

This is occurring in history,py at this location:

`                field = sort[0].get('field').lower()
`
I added debug and it looks like its getting called twice.  One time it appears that sort is
[ { "field": "date" ....} ] and the other time its wrapper in another array [ [ { "field": "date", .. } ] ]

So I made this change 

```
$ git diff medusa/server/api/v2/history.py 
diff --git a/medusa/server/api/v2/history.py b/medusa/server/api/v2/history.py
index 707930e20..975e17045 100644
--- a/medusa/server/api/v2/history.py
+++ b/medusa/server/api/v2/history.py
@@ -136,8 +136,13 @@ class HistoryHandler(BaseRequestHandler):
             sql_base += ' AND '.join(where_with_ops)
 
         if sort is not None and len(sort) == 1:  # Only support one sort column right now.
-            field = sort[0].get('field').lower()
-            order = sort[0].get('type')
+            if isinstance(sort[0], list):
+                field = sort[0][0].get('field').lower()
+                order = sort[0][0].get('type')
+            else:
+                field = sort[0].get('field').lower()
+                order = sort[0].get('type')
+ 
             if field_map.get(field):
                 sql_base += f' ORDER BY {field_map[field]} {order} '
```

Check the type of sort[0] and handle accordingly if its list or dict.

**To Reproduce**
1. Go to History page
2. Notice there is an error logged
3. View errors

**Expected behavior**
Viewing the history should not log errors every time we view.

[history.py.txt](https://github.com/pymedusa/Medusa/files/14428762/history.py.txt)

**Medusa (please complete the following information):**
 - OS: fedora 39 x86_64
 - Branch: master
 - Commit: [e.g. c65ca2]
 - Python version: 3.11
 - Database version: 

**Debug logs (at least 50 lines):**
Accidentally cleared my logs and with my fix above, its no longer logging errors  If you absolutely need one, I ca

```
```
</details>

**Additional context**
Attached patch file.

**Comment by medariox** [comment]
No need to change the Python code. It's fixed once you clear the browser cookies for Medusa. See https://github.com/pymedusa/Medusa/issues/11434
