### ISSUE TITLE
This show isn't in your list, you need to add it before post-processing an episode

### ISSUE THREAD

**Issue by jaytonic** [pymedusa/Medusa#11641]
Hi,

I added Shogun to my medusa, but it was not able to find episode. I went to my usual torrent provider(yggtorrent), downloaded the torrent and tried to do a manual processing.

It fails because the show is not in my list:

 `Processing failed for /downloads/complete/[ Torrent911.bz ] Shogun.2024.S01E01.VOSTFR.WEBRip.x264.mp4: This show isn't in your list, you need to add it before post-processing an episodeProcessing failed for /downloads/complete/[ Torrent911.bz ] Shogun.2024.S01E02.VOSTFR.WEBRip.x264.mp4: This show isn't in your list, you need to add it before post-processing an episode` 

How can I influence medusa for those files to be recognized properly??
I tried to add "[ Torrent911.bz ]" as scene exception, but I still get the same error

**Comment by Frank071** [comment]
Add a scene exception for "Shogun 2024" and it will probably work.
