### ISSUE TITLE
History Page still broken since security patch. [dev branch]

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#11654]
**Describe the bug**
history page elements refuse to function since commit 14a78453083d5dc08feb781bbbbc630c7f501dcf
commit 1b0a21c4443786b9db9b555561dacd0306c2137d broke it even further, history page won't even render now.

**To Reproduce**
Go to history page to marvel at its non-functionality 

**Expected behavior**
to work like to work exactly as it did on commit: 70f9e902fc7dc4fac7b324df51206dda8f46021d before it broke.

**Screenshots**
<img width="2728" alt="Screen Shot 2024-03-18 at 3 49 33 am" src="https://github.com/pymedusa/Medusa/assets/2242880/a3561867-0c52-4b7d-96e6-faef7084240d">
<img width="2811" alt="Screen Shot 2024-03-18 at 3 49 26 am" src="https://github.com/pymedusa/Medusa/assets/2242880/13f7353b-cdfb-446a-ad7b-dbb6704174a4">

**Medusa (please complete the following information):**
 - OS: macOS 11.7.10
 - Branch: develop
 - Commit: 1b0a21c4443786b9db9b555561dacd0306c2137d
 - Python version: 3.11.6
 - Database version: 44.19

**Debug logs (at least 50 lines):**
<details>

```
2024-03-18 03:49:23 ERROR    TORNADO :: [1b0a21c] Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /api/v2/history?page=1&limit=50&sort=[%7B%22field%22:%22actionDate%22,%22type%22:%22desc%22%7D] (127.0.0.1)
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/ovidijus/Apps/Medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ovidijus/Apps/Medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ovidijus/Apps/Medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ovidijus/Apps/Medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
            ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
```
</details>

**Additional context**
Full Logs:
[Logs.zip](https://github.com/pymedusa/Medusa/files/14628174/Logs.zip)

**Comment by XxUnkn0wnxX** [comment]
Commit: 98246101e446bc84f6031a95540c2981c1bebba9 partial Fixed, page renders, however most filters are still dead

**Comment by medariox** [comment]
Fixed, please update.
