### ISSUE TITLE
Manual post processing does not allow folder selection as it did before recent update details below

### ISSUE THREAD

**Issue by johnvick** [pymedusa/Medusa#11676]
<html>
<body>

Branch: masterCommit: e4870f8f4a322e67c77434597ccc09aa6524aa05Version: 1.0.20Database: 44.19
--
Python Version: | 3.11.8 (main, Feb 19 2024, 17:01:17) [GCC 13.2.1 20231014]
SSL Version: | OpenSSL 3.1.4 24 Oct 2023
OS: | Linux-6.5.13-3-pve-x86_64-with
Locale: | en_US.UTF-8
Timezone: | NZDT
  |  
  |  
User: | abc
Program Folder: | /app/medusa
Config File: | /config/config.ini
Database File: | /config/main.db
Cache Folder: | /config/cache
Log Folder: | /config/Logs
Arguments: | --nolaunch --datadir /config
Runs in Docker: | Yes

</body>
</html>Branch: [master](https://github.com/pymedusa/Medusa/tree/master)
Commit: [e4870f8f4a322e67c77434597ccc09aa6524aa05](https://github.com/pymedusa/Medusa/commit/e4870f8f4a322e67c77434597ccc09aa6524aa05)
Version: [1.0.20](https://github.com/pymedusa/Medusa/releases/tag/v1.0.20)
Database: 44.19
 Python Version:	3.11.8 (main, Feb 19 2024, 17:01:17) [GCC 13.2.1 20231014]
 SSL Version:	OpenSSL 3.1.4 24 Oct 2023
 OS:	Linux-6.5.13-3-pve-x86_64-with
 Locale:	en_US.UTF-8
 Timezone:	NZDT
 	 
 	 
 User:	abc
 Program Folder:	/app/medusa
 Config File:	/config/config.ini
 Database File:	/config/main.db
 Cache Folder:	/config/cache
 Log Folder:	/config/Logs
 Arguments:	
--nolaunch --datadir /config
 Runs in Docker:	Yes

**Comment by TBoneStaek** [comment]
Just updated, I'm having the same issue.

Branch: master
Commit: a1d899bc882da047b3d6ff936e8b78b62b169b05
Version: 1.0.20
Database: 44.19
Python Version:	3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]
SSL Version:	OpenSSL 3.2.1 30 Jan 2024
OS:	Linux-6.1.74-Unraid-x86_64-with-glibc2.39

**Comment by medariox** [comment]
What does not work as before? Can you post a screenshot?

**Comment by johnvick** [comment]
![medusa](https://github.com/pymedusa/Medusa/assets/10369590/be06d854-4145-4dce-9823-c961c721b62f)

Before it was a drop down menu to select location of file you wanted to post process, now you cannot.

**Comment by TBoneStaek** [comment]
That's exactly what I get.

**Comment by R0d3er** [comment]
Hi, I just did a new installation and I have the same problem, unable to define several directories : "Black hole folder location", "Post-Processing Dir". "TV Download Directory " is N/A in the Server Status menu.
I tried to force the "tv_download_dir" in config.ini file but it doesn't keeps it once restarted.

**Comment by medariox** [comment]
Fixed with the new release. Please update

**Comment by R0d3er** [comment]
> Fixed with the new release. Please update

Thank you, it works perfectly now.
