### ISSUE TITLE
nzbToSickbeard.py results in KeyError: (3, 11) (from eol.py)

### ISSUE THREAD

**Issue by scronkey** [pymedusa/Medusa#11734]
**Describe the bug**
Running nzbToSickbeard.py causes a `KeyError: (3, 11)`
This comes from a call within eol.py
Specifically `time_left = PYTHON_EOL[(major, minor)] - now`

**To Reproduce**
1. Have unprocessed media in Post=Processing Dir
2. Run nzbToSickbeard.py
3. See error
```
Traceback (most recent call last):
  File "/opt/medusa/contrib/nzbToMedia/./nzbToSickBeard.py", line 270, in <module>
    import nzbToMedia
  File "/opt/medusa/contrib/nzbToMedia/nzbToMedia.py", line 727, in <module>
    eol.check()
  File "/opt/medusa/contrib/nzbToMedia/eol.py", line 100, in check
    warn_for_status(version, grace_period)
  File "/opt/medusa/contrib/nzbToMedia/eol.py", line 141, in warn_for_status
    days_left = lifetime(version)
                ^^^^^^^^^^^^^^^^^
  File "/opt/medusa/contrib/nzbToMedia/eol.py", line 71, in lifetime
    time_left = PYTHON_EOL[(major, minor)] - now
                ~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: (3, 11)
```

**Expected behavior**
Expected behaviour is successful processing of the media to library

**Medusa (please complete the following information):**
 - OS: ubuntu 23.10 x64
 - Branch: master
 - Commit: 34a67cf159acab69017dd5b95e0233ecde0de28a
 - Python version: 3.11.6
 - Database version: 44.18
 - Medusa version: 1.0.21

**Debug logs (at least 50 lines):**
No debug logs in Medusa, as this is nzbToMedia issue

**Additional context**
autoProcessMedia.cfg is configured

**Comment by p0psicles** [comment]
if this is an nzbToMedia issue, why report it here?

**Comment by scronkey** [comment]
Ah, because it was in this repo and I've wrongly assumed it was amintained here - I didn't quite connect it is in the contrib directory until now.

I'll see if I can contact the original author or try to work it out myself.
