### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Oxygen True Crime

### ISSUE THREAD

**Issue by gtlfilms** [pymedusa/Medusa#11813]
### INFO
**Python Version**: `3.11.9 (main, Aug 22 2024, 22:17:24) [GCC 13.2.1 20231014]`
**Operating System**: `Linux-5.10.0-31-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: https://gist.github.com/gtlfilms/ab7fd057e2fa190884fefb361c126172
### ERROR
<pre>
2024-09-02 02:06:48 ERROR    SHOWQUEUE-UPDATE :: [e4870f8] Missing time zone for network: Oxygen True Crime
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by gtlfilms** [comment]
### INFO
**Python Version**: `3.11.9 (main, Aug 22 2024, 22:17:24) [GCC 13.2.1 20231014]`
**Operating System**: `Linux-6.1.0-23-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: https://gist.github.com/gtlfilms/56c100e9c08a403425fc4e4cec4493cd
### ERROR
<pre>
2024-09-05 13:27:14 ERROR    MAIN :: [e4870f8] Missing time zone for network: Oxygen True Crime
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19045-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@34a67cf159acab69017dd5b95e0233ecde0de28a
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-09-13 04:25:49 ERROR    MAIN :: [34a67cf] Missing time zone for network: Oxygen True Crime
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by adix** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@34a67cf159acab69017dd5b95e0233ecde0de28a
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-09-17 05:34:19 ERROR    SHOWQUEUE-UPDATE :: [34a67cf] Missing time zone for network: Oxygen True Crime
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
