### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Seven

### ISSUE THREAD

**Issue by fexofenadine** [pymedusa/Medusa#11825]
### INFO
**Python Version**: `3.11.9 (main, Aug 22 2024, 22:17:24) [GCC 13.2.1 20231014]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-09-08 02:52:25 ERROR    SHOWQUEUE-SEASON-UPDATE :: [baad1e5] Missing time zone for network: Seven
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19045-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@34a67cf159acab69017dd5b95e0233ecde0de28a
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-09-13 04:25:46 ERROR    MAIN :: [34a67cf] Missing time zone for network: Seven
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
