### ISSUE TITLE
How do I change an index source for a specific TV show? 

### ISSUE THREAD

**Issue by OneCDOnly** [pymedusa/Medusa#11858]
Hi guys, 

If I want to change the index source for a specific TV show, I presently remove the show, then add it again with the different index source. Is there a better way to do this?

Cheers. 🤓

**Comment by nydave69** [comment]
Not sure it's a better way,
Under Managed
Change show indexer

**Comment by OneCDOnly** [comment]
Cheers @nydave69 , that's just what I was looking-for. 🤓
