### ISSUE TITLE
Has anyone figured out how to set the TV show The Diplomat

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#11869]
**Describe the bug**
Has anyone figured out how to set the TV show The Diplomat, so that it doesn't keep 
getting mixed up with other shows of the same name. There doesn't seem to be any pattern 
as to what show it does match to.

Its a current;y running 2023 US show.

Oh and Guess-it just is no help...

**To Reproduce**

**Expected behavior**
Medusa would match the correct show.

**Screenshots**

`Medusa Info:	Branch: master
Commit: 34a67cf159acab69017dd5b95e0233ecde0de28a
Version: 1.0.21
Database: 44.19
 Python Version:	3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
 SSL Version:	OpenSSL 3.0.2 15 Mar 2022
 OS:	Linux-6.8.0-47-generic-x86_64-with-glibc2.35
 Locale:	en_US.UTF-8
 Timezone:	EST
 	 `

**Debug logs (at least 50 lines):**
Nothing in the log to show..     it matches just the wrong series
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by skalvaro** [comment]
What worked for me was following:
Go to the show page
Click Edit
Click the Advanced tab
Add "The Diplomat US" to Scene Exception
Click on the plus sign
Click on Save Changes

**Comment by medariox** [comment]
That is the way, thanks.
