### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: TV Tokyo

### ISSUE THREAD

**Issue by MariusEvotel** [pymedusa/Medusa#11877]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-6.8.4-3-pve-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@34a67cf159acab69017dd5b95e0233ecde0de28a
**Link to Log**: https://gist.github.com/MariusEvotel/538f9f587f24c6423277091917c5f1fe
### ERROR
<pre>
2024-12-05 22:27:21 ERROR    MAIN :: [34a67cf] Missing time zone for network: TV Tokyo
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
it's on the list.
https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L2522

**Comment by MariusEvotel** [comment]
Then what is causing the error?
