### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: CBS

### ISSUE THREAD

**Issue by MariusFttx** [pymedusa/Medusa#11876]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-6.8.4-3-pve-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@34a67cf159acab69017dd5b95e0233ecde0de28a
**Link to Log**: https://gist.github.com/MariusEvotel/c444200c91cb8c2a0ac4995ce17b61f1
### ERROR
<pre>
2024-12-05 22:30:31 ERROR    MAIN :: [34a67cf] Missing time zone for network: CBS
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
it's on the list.
https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L447
