### ISSUE TITLE
Join notifications have stopped including Medusa Icon

### ISSUE THREAD

**Issue by fexofenadine** [pymedusa/Medusa#11881]
**Describe the bug**
When Medusa sends a notification to the Join API, it used to include the green squares Medusa icon. the most recent build does not include one, so Join just shows its default icon on the message

**To Reproduce**
1. Set a Join API key and device
2. send a test notification

**Expected behavior**
Notification arrives on specified device(s) with the application icon for Medusa embedded

**Screenshots**
Notifications with default Join icon at top left
![Notifications with default Join icon](https://i.ibb.co/NtDDhbx/Screenshot-20241209-173916.png)
**Medusa (please complete the following information):**
 - OS: docker
 - Branch: master
 - Commit: https://github.com/pymedusa/Medusa/commit/baad1e5af59d7f29606c1fed1c110af1424bb117
 - Python version: 3.11.10 (main, Sep 11 2024, 09:58:40) [GCC 13.2.1 20231014]
 - Database version: 44.19

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
Join notification does not show up on debug logs in my instance
```
</details>

**Additional context**
Used to work, very recently. Must have changed behaviour in the last release or two

**Comment by medariox** [comment]
Fixed in develop.
