### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: U&Alibi

### ISSUE THREAD

**Issue by taochern** [pymedusa/Medusa#11880]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/taochern/7caef085590eb9de81c6f49d3f35245a
### ERROR
<pre>
2024-12-08 05:35:03 ERROR    TORNADO :: [d9c31da] Missing time zone for network: U&Alibi
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by taochern** [comment]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-12-14 12:25:14 ERROR    MAIN :: [d9c31da] Missing time zone for network: U&Alibi
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ledderi** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.26100-SP0`
**Locale**: `cp1255`
**Branch**: [](../tree/)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@729ab4f066034709137edb43440dba7c84959626
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-12-24 16:44:58 ERROR    MAIN :: [729ab4f] Missing time zone for network: U&Alibi
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ledderi** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.26100-SP0`
**Locale**: `cp1255`
**Branch**: [](../tree/)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@729ab4f066034709137edb43440dba7c84959626
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-12-25 17:26:02 ERROR    MAIN :: [729ab4f] Missing time zone for network: U&Alibi
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ledderi** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.26100-SP0`
**Locale**: `cp1255`
**Branch**: [](../tree/)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@729ab4f066034709137edb43440dba7c84959626
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-12-26 13:32:47 ERROR    MAIN :: [729ab4f] Missing time zone for network: U&Alibi
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ledderi** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.26100-SP0`
**Locale**: `cp1255`
**Branch**: [](../tree/)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@729ab4f066034709137edb43440dba7c84959626
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-12-28 07:12:31 ERROR    MAIN :: [729ab4f] Missing time zone for network: U&Alibi
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ledderi** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.26100-SP0`
**Locale**: `cp1255`
**Branch**: [](../tree/)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@729ab4f066034709137edb43440dba7c84959626
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-12-31 15:50:46 ERROR    MAIN :: [729ab4f] Missing time zone for network: U&Alibi
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
