### ISSUE TITLE
Pre-Built Synology Package Still Avail?

### ISSUE THREAD

**Issue by marlowe310** [pymedusa/Medusa#1227]
Is there still a pre-built package available for Synology NAS? Or is the correct way to install to use SickBeard Custom, and then give this path as the custom build? Thanks much!

**Comment by fernandog** [comment]
afaik custom. @ratoaq2 can confirm

**Comment by ratoaq2** [comment]
I only use the custom one

**Comment by medariox** [comment]
Please use SickBeard Custom for now.
