### ISSUE TITLE
Config seems to reset or at least ignore old values

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#1247]
Branch/Commit: 0854fcc995f4dde4f2e96c5a05354b318c7886e3
OS: Happening to all OSs
What you did: `git checkout develop && git pull`
What happened: All my config settings seem to using the default settings
What you expected: My actual config settings to be used
Logs: Nothing in the logs is shown

@pymedusa/administrators @pymedusa/contributors @pymedusa/developers @pymedusa/moderators @pymedusa/owners

**Comment by duramato** [comment]
I think I can confirm this, I thought it was something on my system..

**Comment by fernandog** [comment]
i don't have this issue. Can someone debug it?

**Comment by ratoaq2** [comment]
Closing this one. No one reported this issue anymore. And if that's still happening, it would be a blocker one.
