### ISSUE TITLE
Best quality not being search

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#1248]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: last develop
OS: DSM last version

![image](https://cloud.githubusercontent.com/assets/9487685/19259165/5b1af8fe-8f7f-11e6-96b3-ca182f9e0944.png)

Bluray quality was available for 2 months through different providers but Medusa didn't look for it apparently.
I had to make a manual search and snatch.

logs:
https://gist.github.com/NicoLeOca/d06197180fb9003fd7edcdfdff3e1fb2

**Comment by fernandog** [comment]
Send a full screen shot of the page of results while manual sesrching

**Comment by NicoLeOca** [comment]
@fernandog 
![image](https://cloud.githubusercontent.com/assets/9487685/19281200/5b3ec738-8fe9-11e6-9ae4-9e7bec0653dc.png)

having a look at my logs
there are thousands of lines about another show for backlog
I guess the show keeps it busy and it doesn't look for another..
I'll mark it as archive and see if it gets better for shameless

**Comment by NicoLeOca** [comment]
@fernandog 
I found the issue; the show was paused.
that's strange, cause I am pretty sure I didn't pause it.
I close the issue
thanks for trying to help as usual ;-)
