### ISSUE TITLE
Function _format_pattern not using scene numbering (when apply)

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#1258]
So notifications, logs and etc are wrong.

Example:

![image](https://cloud.githubusercontent.com/assets/2620870/19332711/0c67f9cc-90c5-11e6-833d-eb3e1b47d79c.png)

"The Battles Premiere" is episode 8 (scene)

but I got a notification saying that ep 7 that got downloaded
![image](https://cloud.githubusercontent.com/assets/2620870/19332767/a93f57d6-90c5-11e6-99a1-241c1a9b6703.png)

So how do we handle this? What is correct here?
@duramato @medariox @ratoaq2 @OmgImAlexis @p0psicles

**Comment by OmgImAlexis** [comment]
Notifications are done in Python so it's not anything on the front-end, same goes for the page layout at the moment. So I have no clue.

**Comment by fernandog** [comment]
Im asking about if we should use index number or scene number.

**Comment by duramato** [comment]
Everything but displayShow should be using scene numbering if enabled imo
DisplayShow shouldn't becouse it is a 1:1 representation of the indexer map, beeing tvdb or soon to be tvmaze etc

**Comment by fernandog** [comment]
first change needs to be here:
`return self._format_pattern('%SN - S%0SE%0E - %EN')`
https://github.com/pymedusa/Medusa/blob/develop/medusa/tv.py#L2487

we need to check if show has xem mapping
and use this in the format_pattern:
`return self._format_pattern('%SN - S%0XSE%0XE - %EN')`

from tv.py
```
'%0XS': '%02d' % self.scene_season,
'%0XE': '%02d' % self.scene_episode,
```

**Comment by duramato** [comment]
you should check if the scene numbering option is enabled.. not if it has xem mapping.
