### ISSUE TITLE
[ FEATURE ] Add a property "have_xem_map" in TV Show object

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#1262]
Add a property "have_xem_map" in TV Show object so we can avoid to do this check in displayShow to know if that show have xem map or not

`get_xem_numbering_for_show` returns ALL mappings. But we only need to know if has map or not (True|False)

``` python
xem_numbering=get_xem_numbering_for_show(indexerid, indexer),
xem_absolute_numbering=get_xem_absolute_numbering_for_show(indexerid, indexer),
```

https://github.com/pymedusa/Medusa/blob/develop/medusa/server/web/home/handler.py#L893

in displayShow we add a XEM icon when show has xem map

``` html
% if xem_numbering or xem_absolute_numbering:
                <a href="${anon_url('http://thexem.de/search?q=', show.name)}" rel="noreferrer" onclick="window.open(this.href, '_blank'); return false;" title="http://thexem.de/search?q-${show.name}">
                    <img alt="[xem]" height="16" width="16" src="images/xem.png" style="margin-top: -1px; vertical-align:middle;"/>
                </a>
% endif
```

@medariox @ratoaq2

**Comment by fernandog** [comment]
i think this may help with subtitle issue so we can use tv_show object to check if has xem map or not

**Comment by fernandog** [comment]
@p0psicles what do you think?

**Comment by p0psicles** [comment]
I'm for moving all mako code out of the templates. So if this helps. Why not.

**Comment by fernandog** [comment]
@xo how did you do with displayShow in vue?

**Comment by p0psicles** [comment]
@fernandog finished right

**Comment by fernandog** [comment]
No. I didnt add yet. Will do

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
