### ISSUE TITLE
[ FEATURE ] Mark certain file extensions as a failed download

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1277]
Sometimes a sneaky fake file gets past , and Medusa snatches. It's normally named like a normal Scene release so i can't add it to ignored words ex: `Show.S01E01.HDTV.x264-KILLERS`
After it's downloaded Medusa PPs it and then i find it's fake file in .wmv format.

So my idea is to have an option to set up certain file extensions that when Auto Post Processor runs, and if it finds said extension it will mark it as a failed download.

**Comment by fernandog** [comment]
afaik we check that.  wmv is in our `media_extensions` list
maybe need list to ignore 
@medariox

**Comment by OmgImAlexis** [comment]
I'd be nice to have this list user editable. For me I'd add .wmv, .flv, etc. to it or maybe allow the "accepted list" to be editable so people can just add .mp4 and .mkv to it for example.

**Comment by duramato** [comment]
Exclusion would be better than inclusion.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
