### ISSUE TITLE
Error with T411 search

### ISSUE THREAD

**Issue by FireBladeNooT** [pymedusa/Medusa#1278]
Hi,
I've this issue about search on T411 provider:
```
2016-10-17 19:22:19 DEBUG    SEARCHQUEUE-MANUAL-296762 :: [T411] :: [2697d37] Data returned from provider does not contain any torrents
2016-10-17 19:22:19 DEBUG    SEARCHQUEUE-MANUAL-296762 :: [T411] :: [2697d37] GET URL: https://api.t411.ch/torrents/search/Westworld%20S01E03*?cid=639&limit=100 [Status: 200]
2016-10-17 19:22:18 DEBUG    SEARCHQUEUE-MANUAL-296762 :: [T411] :: [2697d37] Data returned from provider does not contain any torrents
2016-10-17 19:22:18 DEBUG    SEARCHQUEUE-MANUAL-296762 :: [T411] :: [2697d37] GET URL: https://api.t411.ch/torrents/search/Westworld%20S01E03*?cid=455&limit=100 [Status: 200]
2016-10-17 19:22:18 DEBUG    SEARCHQUEUE-MANUAL-296762 :: [T411] :: [2697d37] Data returned from provider does not contain any torrents
2016-10-17 19:22:18 DEBUG    SEARCHQUEUE-MANUAL-296762 :: [T411] :: [2697d37] GET URL: https://api.t411.ch/torrents/search/Westworld%20S01E03*?cid=637&limit=100 [Status: 200]
2016-10-17 19:22:17 DEBUG    SEARCHQUEUE-MANUAL-296762 :: [T411] :: [2697d37] Data returned from provider does not contain any torrents
2016-10-17 19:22:17 DEBUG    SEARCHQUEUE-MANUAL-296762 :: [T411] :: [2697d37] GET URL: https://api.t411.ch/torrents/search/Westworld%20S01E03*?cid=433&limit=100 [Status: 200]
2016-10-17 19:22:10 DEBUG    SEARCHQUEUE-MANUAL-296762 :: [T411] :: [2697d37] Search string: Westworld S01E03
2016-10-17 19:22:10 DEBUG    SEARCHQUEUE-MANUAL-296762 :: [T411] :: [2697d37] Search mode: Episode
2016-10-17 19:22:10 INFO     SEARCHQUEUE-MANUAL-296762 :: [T411] :: [2697d37] Performing episode search for Westworld
```
I don't know if the problem come from me, but I've verified my account, it's fine.

**Comment by duramato** [comment]
No issue there, just no results

**Comment by FireBladeNooT** [comment]
ok so it's not returned not validated torrent?

**Comment by duramato** [comment]
Mm taking a look at the site there are results, but they aren't parsed..

**Comment by FireBladeNooT** [comment]
I search an older episode but it doesn't find anything, and when I search manually on the website I found some torrents :(

**Comment by FireBladeNooT** [comment]
It does it for any search.

**Comment by FireBladeNooT** [comment]
I've remove all required and undesired words, nothing change.

**Comment by FireBladeNooT** [comment]
Error is "_{"error":"Invalid token","code":202}_"

**Comment by FireBladeNooT** [comment]
It seems code have an issue because when I search on this URL [https://api.t411.ch/](url)
with this query : https://api.t411.ch/torrents/search/Westworld%20S01E03*?cid=433&limit=100
I've got this result:

'''
{"query":"Westworld S01E03*","offset":0,"limit":"100","total":"5","torrents":[{"id":"5585944","name":"Westworld.S01E03.VOSTFR.HDTV.x264-otm","category":"433","rewritename":"westworld-s01e03-vostfr-hdtv-x264-otm","seeders":"982","leechers":"27","comments":"6","isVerified":"1","added":"2016-10-17 09:35:07","size":"385337677","times_completed":"1589","owner":"105916399","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"onlythemusic","privacy":"normal"},{"id":"5586030","name":"Westworld.S01E03.1080p.VOSTFR.HDTV.x264-BATV","category":"433","rewritename":"westworld-s01e03-1080p-vostfr-hdtv-x264-batv","seeders":"330","leechers":"29","comments":"1","isVerified":"0","added":"2016-10-17 13:15:00","size":"4524972675","times_completed":"498","owner":"5597133","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"mohagunner","privacy":"normal"},{"id":"5585933","name":"Westworld.S01E03.PROPER.VOSTFR.720p.HDTV.x264-exPM5","category":"433","rewritename":"westworld-s01e03-proper-vostfr-720p-hdtv-x264-expm5","seeders":"2922","leechers":"153","comments":"8","isVerified":"1","added":"2016-10-17 09:09:53","size":"1268503102","times_completed":"4880","owner":"336059","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"JP60","privacy":"strong"},{"id":"5585945","name":"Westworld.S01E03.PROPER.VOSTFR.1080p.HDTV.x264-exPM5","category":"433","rewritename":"westworld-s01e03-proper-vostfr-1080p-hdtv-x264-expm5","seeders":"924","leechers":"57","comments":"5","isVerified":"1","added":"2016-10-17 09:45:41","size":"4525004351","times_completed":"1438","owner":"336059","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"JP60","privacy":"strong"},{"id":"5586026","name":"Westworld.S01E03.PROPER.VOSTFR.HDTV.XviD-exPM5","category":"433","rewritename":"westworld-s01e03-proper-vostfr-hdtv-xvid-expm5","seeders":"628","leechers":"30","comments":"1","isVerified":"1","added":"2016-10-17 13:11:49","size":"522455040","times_completed":"917","owner":"336059","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"JP60","privacy":"strong"}]}

**Comment by FireBladeNooT** [comment]
Maybe the problem come from this code:
````
2016-10-17 22:34:04 DEBUG    SEARCHQUEUE-MANUAL-81797 :: [T411] :: [2697d37] With post data: username=**********&password=**********
2016-10-17 22:34:04 DEBUG    SEARCHQUEUE-MANUAL-81797 :: [T411] :: [2697d37] POST URL: https://api.t411.ch/auth [Status: 200]
````
And the token get is not correct?

**Comment by fernandog** [comment]
@FireBladeNooT check if have "only download torrents from trusted or verified uploaders ?" enabled

and check if those results are trusted or not

**Comment by fernandog** [comment]
@FireBladeNooT so?

**Comment by fernandog** [comment]
no response

**Comment by labrys** [comment]
Error 202 happens if you changed your password, since the stored token would no longer be valid.  Make sure you have updated your password in Medusa.

**Comment by duramato** [comment]
That error happen becouse he direct accessed the URL without a token set, not in Medusa

**Comment by labrys** [comment]
That's another way you can get that error. :)

**Comment by FireBladeNooT** [comment]
Hi thanks for your answers.
I'll try to connect and check my Id/password

**Comment by FireBladeNooT** [comment]
This is the result I've got with this URL:
_https://api.t411.ch/torrents/search/Gotham%20S03E06*?cid=433&limit=100_

''''
{"query":"Gotham S03E06*","offset":0,"limit":"100","total":"8","torrents":[{"id":"5590405","name":"Gotham.S03E06.FASTSUB.VOSTFR.HDTV.x264-otm","category":"433","rewritename":"gotham-s03e06-fastsub-vostfr-hdtv-x264-otm","seeders":"89","leechers":"0","comments":"0","isVerified":"0","added":"2016-10-25 19:27:11","size":"193309758","times_completed":"157","owner":"105916399","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"onlythemusic","privacy":"normal"},{"id":"5590341","name":"Gotham.S03E06.SUBFRENCH.WEB-DL.x264-ARK01","category":"433","rewritename":"gotham-s03e06-subfrench-web-dl-x264-ark01","seeders":"304","leechers":"3","comments":"0","isVerified":"1","added":"2016-10-25 17:48:55","size":"268678104","times_completed":"619","owner":"94925822","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"Arkhos01","privacy":"normal"},{"id":"5590399","name":"Gotham.S03E06.SUBFRENCH.720p.WEB-DL.DD5.1.x264-ARK01","category":"433","rewritename":"gotham-s03e06-subfrench-720p-web-dl-dd5-1-x264-ark01","seeders":"314","leechers":"10","comments":"0","isVerified":"1","added":"2016-10-25 19:00:04","size":"811922627","times_completed":"522","owner":"94925822","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"Arkhos01","privacy":"normal"},{"id":"5590244","name":"Gotham.S03E06.SUBFRENCH.1080p.WEB-DL.H264.Yn1D","category":"433","rewritename":"gotham-s03e06-subfrench-1080p-web-dl-h264-yn1d","seeders":"470","leechers":"5","comments":"6","isVerified":"1","added":"2016-10-25 14:38:49","size":"1768310292","times_completed":"954","owner":"738539","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"killerdu13","privacy":"strong"},{"id":"5590403","name":"Gotham.S03E06.SUBFRENCH.WEB-DL.XviD-ZT","category":"433","rewritename":"gotham-s03e06-subfrench-web-dl-xvid-zt","seeders":"110","leechers":"2","comments":"0","isVerified":"0","added":"2016-10-25 19:12:13","size":"362909636","times_completed":"188","owner":"4809046","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"kingspace","privacy":"normal"},{"id":"5590058","name":"Gotham.S03E06.720p.HDTV.AAC2.0.x264-GOBO2S","category":"433","rewritename":"gotham-s03e06-720p-hdtv-aac2-0-x264-gobo2s","seeders":"188","leechers":"0","comments":"4","isVerified":"1","added":"2016-10-25 05:18:39","size":"341614270","times_completed":"510","owner":"98845842","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"GoBosS","privacy":"normal"},{"id":"5590528","name":"Gotham.S03E06.FASTSUB.VOSTFR.720p.HDTV.AAC2.0.x264-GOBO2S","category":"433","rewritename":"gotham-s03e06-fastsub-vostfr-720p-hdtv-aac2-0-x264-gobo2s","seeders":"331","leechers":"17","comments":"1","isVerified":"0","added":"2016-10-26 01:05:36","size":"341665505","times_completed":"492","owner":"98845842","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"GoBosS","privacy":"normal"},{"id":"5590530","name":"Gotham.S03E06.FASTSUB.VOSTFR.1080p.HDTV.x264.AC3-GOBO2S","category":"433","rewritename":"gotham-s03e06-fastsub-vostfr-1080p-hdtv-x264-ac3-gobo2s","seeders":"131","leechers":"5","comments":"1","isVerified":"0","added":"2016-10-26 01:37:42","size":"1432139666","times_completed":"200","owner":"98845842","categoryname":"S\u00e9rie TV","categoryimage":"video-tv-series","username":"GoBosS","privacy":"normal"}]}
{"query":"Gotham S03E06*","offset":0,"limit":"100","total":0,"torrents":[]}

**Comment by FireBladeNooT** [comment]
Others URL return nothing:
````
{"query":"Gotham S03E06*","offset":0,"limit":"100","total":0,"torrents":[]}

**Comment by FireBladeNooT** [comment]
I've try to change my password but it doesn't works.
Box "only download torrents from trusted or verified uploaders ?" is not check.
Maybe if my ID finish with numbers is a problem?

By the way, the log reveal my password now.
