### ISSUE TITLE
HDSpace wrongfully parsed

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1284]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop
OS: Ubuntu 14.04
What you did: Ran a manual search
What happened: A torrent got wrongfully parsed as `HBO.Vice.News.Tonight.2016.10.10.720p.HDTV.x264-%5BeSc%5D` instead of `HBO.Vice.News.Tonight.2016.10.10.720p.HDTV.x264-[eSc]`
What you expected: For it to be parsed correctly
As seen in Medusa:
https://lol.doyou.bid/Yz8tD.png
As seen in the site:
https://lol.doyou.bid/KFLY2.png

**Comment by fernandog** [comment]
i have no idea
@medariox idea?

**Comment by labrys** [comment]
The title is URL Encoded.   %5B is `[` and %5D is `%`.  Either the title can be URL decoded or we can see about parsing the title a different way.  Hard to say without seeing the html directly and I don't have HDSpace access.

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/1296
