### ISSUE TITLE
Release names beeing cropped on ExtraTorrent

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1318]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Develop
OS: Ubuntu 14.04
What you did: Medusa ran the daily search and cached an item from ExtraTorrent
What happened: The release name got cropped

![image](https://cloud.githubusercontent.com/assets/10121067/19665600/aef674da-9a3d-11e6-8144-2442ca0c0133.png)

![image](https://cloud.githubusercontent.com/assets/10121067/19665616/c6b6b5d0-9a3d-11e6-88f3-f4e4ded6df09.png)

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/1319
