### ISSUE TITLE
Proper not being downloaded over non-proper

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#1323]
Branch/Commit: last develop
OS: windows
What you did: I added an existing folder of Black Mirror containing S03E04 released by SKGTV
![image](https://cloud.githubusercontent.com/assets/9487685/19699718/b92b7a42-9af4-11e6-8410-57939497ca01.png)
file is properly recognized and Medusa search as quality is only allowed

here is the search:
![image](https://cloud.githubusercontent.com/assets/9487685/19699816/14b05f2c-9af5-11e6-881e-e68b01ce673c.png)

there is a proper release which isn't downloaded, why?

FYI: a backlog search was forced on the date/time you see above.
and logs are from that time, as I don't have previous ones anymore.

Logs:
https://gist.github.com/NicoLeOca/65beb24b9efe05b2d7bcce1991132cc5

**Comment by medariox** [comment]
That log doesn't help much. Force "Find Propers Search:" instead and post the logs right after it has finished.

**Comment by NicoLeOca** [comment]
@medariox 
here you are:
https://gist.github.com/NicoLeOca/56dbd746c0d0d65e5eafa528e9f86740

**Comment by medariox** [comment]
The proper search is not searching for Black Mirror at all. Propers are only being searched for 3(?) days after non-proper download or something similar. @fernandog can be more precise here. Your only way to get those propers would be manual download.

**Comment by fernandog** [comment]
2 days after airdate

**Comment by NicoLeOca** [comment]
why only 2 days after air-date? that seems very short to me.

HDTV are regularly available less than 24h after air date
webdl, about 3 days
Bluray a couple of months

**Comment by fernandog** [comment]
@NicoLeOca proper search keep searching for propers for 2 days after airdate

so if ep airs today at 21:00, it will keep searching for propers until (today + 2 days) at 21:00

**Comment by NicoLeOca** [comment]
@fernandog 
that's what I understood.
and I keep thinking it should be longer than 2 days, maybe a week
at least because sometimes even  initial HDTV release are not posted within 2 days following air.
and by definition a proper can't appear before an initial release.

as for myself, I don't download HDTV, only web-dl or bluray.
it is very rare that the initial web-dl release appear within 2 days after airdate; it's usually 3 to 4.
and web-dl can have propers as well.
Black Mirror above is a good example.
SKGTV released 4 days after the airdate and Deflate posted a proper 6-7 days after airdate.

**Comment by duramato** [comment]
Maybe it should be changed for 2 days after donwload/snatch

**Comment by NicoLeOca** [comment]
if we can use download/snatch date, that would be great, maybe with longer than 2 days still, 3 to 4 I'd say.

does search for proper bring a huge amout of load on Medusa?

**Comment by fernandog** [comment]
@NicoLeOca I already have a possible solution

**Comment by NicoLeOca** [comment]
@fernandog 
great!
though can you please answer for the load it brings?
also can we change the reference date as @duramato suggested

**Comment by fernandog** [comment]
@NicoLeOca proper search is the same as backlog search. it searches for custom search string. depending how many aired episodes you have in last 2 days, it can search a lot. 

if providers doesn't support AND search. it will search:
Show S01E01 PROPER
Show S01E01 REAL
Show S01E01 REPACK

so if you have 10 recently aired episodes, it will do 30 searches for this provider
if you have 3 providers enabled it will do 90 searches.

**Comment by medariox** [comment]
This has been implemented in develop. Closing
