### ISSUE TITLE
Guessit issue when both SxxExx and Episode xx is in filename

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1327]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Last Week Tonight with John Oliver - S02E31 - Episode 55 (720p.HDTV).mkv
is guessit'ed to Episode 55 in S02.. is it possible to fix that somehow?

Branch/Commit: develop
OS: windows
What you did: rescanned files
What happened: medusa generated episodes using "Episode xx" instead of "SxxExx"
What you expected: for medusa to use "SxxExx" to match file to episode
Logs:

```
PASTE LOGS HERE
```

**Comment by medariox** [comment]
What is "Episode 55" supposed to be? The episode title? Anyway, Guessit related issues should be reported here: https://github.com/pymedusa/Medusa/issues/810

**Comment by wimpyrbx** [comment]
Episode 55 is the title from thetvdb yes. so this was a case of having PP renaming the files.. then re-adding the show at a later stage where the filename was Last Week Tonight with John Oliver - S02E31 - Episode 55 (720p.HDTV).mkv

when rescanning it linked the file to episode 55 instead of 31

**Comment by ratoaq2** [comment]
Fixed by #1474
