### ISSUE TITLE
[ FEATURE ] allow error submission from Medusa even if not up-to-date

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#1342]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: right before the commit where @fernandog remove mandatory approval for new pull
What you did: there was an error with PP
What happened: I had to submit it manually because Medusa wasn't up-to-date...
What you expected: could we have an option to force it or have a tolerance of a few commits?
Logs:

```
PASTE LOGS HERE
```

**Comment by OmgImAlexis** [comment]
I'd be nice to have the last commit be allowed with submit after showing another warning saying that they should check Github and the change-log before submitting it.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.

**Comment by labrys** [comment]
@NicoLeOca if you enable developer mode you can submit issues for versions that are not up to date, however be prepared to re-test any issues with an up-to-date version if required by a dev.

**Comment by NicoLeOca** [comment]
@labrys 
duly noted, thanks!
