### ISSUE TITLE
Rename page issue

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1347]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Just noticed something has happened to the rename page. it shows this is wrongly named.. the only difference is "season" vs "Season" in the path. Never seen that before.

Branch/Commit: develop
OS: windows
What you did: wanted to rename some episodes
What happened: rename itself works but it shows correctly named episodes as wrongly named due to case sensitivity differences..
What you expected: for correctly named episodes to not show as incorrectly named.
Logs:

```
PASTE LOGS HERE
```

season 02\Gilmore Girls - S02E03 - Red Light on the Wedding Night (720p.WEB-DL).mkv    => Season 02\Gilmore Girls - S02E03 - Red Light on the Wedding Night (720p.WEB-DL).mkv

**Comment by wimpyrbx** [comment]
not sure why case sensitivity kicks in on windows. i know it's a thing in linux, but in windows it does not as far as i know.

**Comment by duramato** [comment]
What is your renaming pattern?

**Comment by wimpyrbx** [comment]
Season %0S/%SN - S%0SE%0E - %EN (%Q.N)
but the issue is that it's "season" vs "Season" as the files are already named 100% to naming pattern.

**Comment by OmgImAlexis** [comment]
If this is a Windows issue then I can't help at the moment, only have my Mac accessible.

![screen shot 2016-11-09 at 8 47 55 am](https://cloud.githubusercontent.com/assets/6525926/20119634/3f307a56-a659-11e6-9132-bd7813fc3499.png)

**Comment by wimpyrbx** [comment]
works after renaming "season 02" to "Season 02" on windows. case sensitivity issue for sure.

**Comment by fernandog** [comment]
@wimpyrbx as we talked:

this is the code. It does a string check. doesn't matter the OS.
`'good' if curLoc == newLoc else 'wanted'`

I could reproduce your case. Folder "season" and pattern "Season". It marked as "red" to rename
IMO this is not an issue
