### ISSUE TITLE
Invalid Timeformat on DisplayShow

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1352]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop
OS: windows
What you did: added new show
What happened: it shows invalid timeformat
What you expected: to not see invalid timeformat
Logs:

```
PASTE LOGS HERE
```

![image](https://cloud.githubusercontent.com/assets/13415240/19813885/03516af2-9d3c-11e6-90b5-96527669794e.png)

not sure if this can be handled on medusa side somehow.

**Comment by fernandog** [comment]
@Thraxis @p0psicles related to timeago library that got added or tvdb api v2 issue?

**Comment by medariox** [comment]
TVDB2, show has no air date, needs to be handled.

**Comment by p0psicles** [comment]
It's an old show. But searching for it does show a date.

**Comment by medariox** [comment]
First aired, but not air date, right?
![tvdb](https://snapr.pw/i/21029d7931.png)

**Comment by p0psicles** [comment]
I'm going to make some small changes. And test it with this show. Would be nice if I had a list with 'problematic' shows.
