### ISSUE TITLE
Lost all shows in show list after updat to v0.17

### ISSUE THREAD

**Issue by themixer2000** [pymedusa/Medusa#1364]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 0.17
OS: Centos 7
What you did: updated to 0.17
What happened: lost all show under show list
What you expected: shows to still be there. 
Logs:
```
PASTE LOGS HERE
I have tried doing a restore and all my settings come back but show list is still blank.

**Comment by fernandog** [comment]
@themixer2000 master branch?

can you confirm you have a main.db file inside Medusa folder? What is the size of this file?

**Comment by themixer2000** [comment]
yes there is and it 24 KB I do have some main.db.bak up files as well that size.

**Comment by fernandog** [comment]
@themixer2000 what about sickbeard.db ?

**Comment by themixer2000** [comment]
yes with file size of 3698 KB but with some bak files of 24

**Comment by fernandog** [comment]
ok. stop medusa. move all .bak files to outside medusa
make a backup of sickbeard.db and keep only .db files (sickbeard.db, failed.db and cache.db) in medusa's folder
try again

**Comment by fernandog** [comment]
@themixer2000 worked?

**Comment by themixer2000** [comment]
yes thank you thank you
