### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: A&amp;E

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#1373]
### INFO

**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@20111914a8633e29b51e035a9e6d1618b908e389
**Link to Log**: https://gist.github.com/b1a5a01e1510033daf3ffa9d799ffba9
### ERROR

<pre>
2016-10-29 09:01:32 ERROR    Thread-22 :: [2011191] Missing time zone for network: A&amp;E
</pre>
---

_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by wimpyrbx** [comment]
2016-10-30 22:54:56 ERROR    Thread-32 :: [a9b215a] Missing time zone for network: A&E
2016-10-30 22:54:56 ERROR    Thread-32 :: [a9b215a] Missing time zone for network: Discovery Channel (Canada)

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@a9b215a0250d860b8cd851dc026e5361672f4d1c
**Link to Log**: https://gist.github.com/4ee30d5acdc84920ca8e4009eb38d3e8
### ERROR
<pre>
2016-10-31 10:36:39 ERROR    Thread-32 :: [a9b215a] Missing time zone for network: A&amp;E
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
A&E exists, might be windows encoding related...

**Comment by ripper1967** [comment]
Not sure but there is no network icon showing,
![a e](https://cloud.githubusercontent.com/assets/7034303/19859898/3af419c8-9f5d-11e6-9683-5915f09eb4b5.png)

**Comment by ripper1967** [comment]
there is an ? for network icon wonder if that is the problem?
![a e](https://cloud.githubusercontent.com/assets/7034303/19860040/bbaec86a-9f5d-11e6-9249-63c271e35a55.png)

**Comment by duramato** [comment]
![image](https://cloud.githubusercontent.com/assets/10121067/19860516/dab2c82e-9f80-11e6-82c2-8db4f8553ce2.png)

**Comment by ripper1967** [comment]
hmmmmm  weird

**Comment by fernandog** [comment]
### INFO
**Python Version**: `2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.27-1-osmc-armv7l-with-debian-8.6`
**Locale**: `UTF-8`
**Branch**: [optimized2](../tree/optimized2)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@58ed90dee2e6de8be0484c68b34b7bf590d869df
**Link to Log**: https://gist.github.com/520b92b40537ae37faf2ff97cc3b3747
### ERROR
<pre>
2016-10-31 18:59:00 ERROR    Thread-15 :: [58ed90d] Missing time zone for network: A&amp;E
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato not fixed. ^

any idea?

**Comment by fernandog** [comment]
@p0psicles confirm?

**Comment by p0psicles** [comment]
Yes, tvdb apiv2 is storing it urlencoded.

**Comment by fernandog** [comment]
@p00chie so what needs to be done?

check if isinstance is 'unicode' in the clean?

**Comment by medariox** [comment]
What's the state here? Fixed? @fernandog @p0psicles

**Comment by fernandog** [comment]
There is an open PR by pops. Need to tests more shows updates to make sure its ok

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/57e5dd8bf1155e626c433ac050f237b2
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: A&E
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/835bb5d074564d78f766ff28320e55f7
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: E!
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/c17151c28737272b6654b2fd86b4b7f2
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: E4
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
