### ISSUE TITLE
Many thanks

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#1381]
You all guys are doing an amazing job at improving and maintaining Medusa!
we owe you a lot for that.
and seeing you acting as a team brings somethings special to this project

(I'am writing here as not everyone is on IRC)

**Comment by OmgImAlexis** [comment]
PING: @pymedusa/administrators @pymedusa/contributors @pymedusa/developers @pymedusa/moderators @pymedusa/owners

**Comment by medariox** [comment]
Thanks, we try our best :) closing this now
