### ISSUE TITLE
[APP SUBMITTED]: Show in /media/extssd/Shows/The Young Pope has no name on TVDBv2, probably searched with the wrong language.

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1392]
### INFO

**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@8223edb745999763875b45f1adacb430bdf49027
**Link to Log**: https://gist.github.com/cf0cbb8b2dde55a23069a2b419ca7883
### ERROR

<pre>
2016-10-30 15:03:27 ERROR    SHOWQUEUE-ADD :: [8223edb] Show in /media/extssd/Shows/The Young Pope has no name on TVDBv2, probably searched with the wrong language.
</pre>
---

_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Related https://github.com/pymedusa/Medusa/issues/1393
