### ISSUE TITLE
[ FEATURE ] FFMpeg (or similar?) implementation + DisplayEpisode page

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1407]
For episodes that do not have online thumbnails it would be nice to have a FFMpeg (or similar) fallback solution that creates thumb(s) from the video file.

another aspect of having ffmpeg is the ability to let user create (or live view) screenshot for an episode at 100% size. like "view x frames for video"-type button that will open a modal displaying screenshots. this can help users to quickly identify image quality..

we can also generate more thumbnails/screenshots for each episode so that we could have a "click on episode" and a new DisplayEpisode page that will display plot, screenshots and other episode information. This page could also host manual search solution below the information panel about the episode perhaps. consolidate the two into a "episode info and management page".

way off or ok thoughts?

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
