### ISSUE TITLE
DB logs using "DEBUG" level instead of "DB"

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#1409]
Enable db debug logs in advanced settings.
Force any thread in medusa.
Open logs:

`2016-10-25 09:28:16 DEBUG    MAIN :: [1ea10b0] main.db: SELECT * FROM tv_shows WHERE indexer_id = ? with args `

as requested @ratoaq2

**Comment by ratoaq2** [comment]
Fixed by #1475
