### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: TNT (US)

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1411]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@a9b215a0250d860b8cd851dc026e5361672f4d1c
**Link to Log**: https://gist.github.com/79de88bcb06c019021b9b24743bd4525
### ERROR
<pre>
2016-10-31 15:15:03 ERROR    Thread-15 :: [a9b215a] Missing time zone for network: TNT (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by wimpyrbx** [comment]
2016-10-31 18:42:33 ERROR    Thread-32 :: [462e776] Missing time zone for network: 13th Street Germany

**Comment by fernandog** [comment]
### INFO
**Python Version**: `2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.27-1-osmc-armv7l-with-debian-8.6`
**Locale**: `UTF-8`
**Branch**: [optimized2](../tree/optimized2)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@58ed90dee2e6de8be0484c68b34b7bf590d869df
**Link to Log**: https://gist.github.com/d17b166a2de3e35551868ff9b07e803c
### ERROR
<pre>
2016-10-31 18:59:01 ERROR    Thread-15 :: [58ed90d] Missing time zone for network: TNT (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
https://github.com/pymedusa/medusa.github.io/pull/13

**Comment by theystillcallmemister** [comment]
### INFO
**Python Version**: `2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]`
**Operating System**: `Linux-4.8.12-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@677b47ac1f6a75abc71c4472f3fb9c4eecb6413f
**Link to Log**: https://gist.github.com/5d261b1062e54c3776a85aeae1199d8f
### ERROR
<pre>
2017-01-10 09:06:55 ERROR    Thread-16 :: [677b47a] Missing time zone for network: ABC (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by theystillcallmemister** [comment]
### INFO
**Python Version**: `2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]`
**Operating System**: `Linux-4.8.12-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@677b47ac1f6a75abc71c4472f3fb9c4eecb6413f
**Link to Log**: https://gist.github.com/e2016438924b8af6eb2b4240ba9a3198
### ERROR
<pre>
2017-01-10 09:06:55 ERROR    Thread-16 :: [677b47a] Missing time zone for network: FOX (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by theystillcallmemister** [comment]
### INFO
**Python Version**: `2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]`
**Operating System**: `Linux-4.8.12-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@677b47ac1f6a75abc71c4472f3fb9c4eecb6413f
**Link to Log**: https://gist.github.com/cf07f3aa95cddc8f1ab5d8007b2cfe74
### ERROR
<pre>
2017-01-10 09:06:55 ERROR    Thread-16 :: [677b47a] Missing time zone for network: FX (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.8-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@772930a97a94280d76a355f29706ee6b64035b5f
**Link to Log**: https://gist.github.com/28503481ae032a26e586634fb1be0e1d
### ERROR
<pre>
2017-02-21 04:36:31 ERROR    Thread-428 :: [772930a] Missing time zone for network: ABC (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.8-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@772930a97a94280d76a355f29706ee6b64035b5f
**Link to Log**: https://gist.github.com/a48cc136fcf717b1e238026b7c45d4b0
### ERROR
<pre>
2017-02-21 04:36:31 ERROR    Thread-428 :: [772930a] Missing time zone for network: TNT (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.8-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@772930a97a94280d76a355f29706ee6b64035b5f
**Link to Log**: https://gist.github.com/b4f094e2acc9c8a840d904caa383308c
### ERROR
<pre>
2017-02-21 04:36:31 ERROR    Thread-428 :: [772930a] Missing time zone for network: MTV (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.8-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@772930a97a94280d76a355f29706ee6b64035b5f
**Link to Log**: https://gist.github.com/75e9e3fceee47fb6a88c13118fdc7154
### ERROR
<pre>
2017-02-21 04:36:31 ERROR    Thread-428 :: [772930a] Missing time zone for network: FX (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.8-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@772930a97a94280d76a355f29706ee6b64035b5f
**Link to Log**: https://gist.github.com/3ac1e6b147714b3da0e6fec60431e6a5
### ERROR
<pre>
2017-02-21 04:36:31 ERROR    Thread-428 :: [772930a] Missing time zone for network: FOX (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.10-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/fcf0ee9d6b182986131bf99f410d429a
### ERROR
<pre>
2017-03-16 04:42:00 ERROR    Thread-23 :: [a011615] Missing time zone for network: MTV (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.10-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/2afedc35acc16c596c8dc24bfb31dc79
### ERROR
<pre>
2017-03-16 04:41:59 ERROR    Thread-20 :: [a011615] Missing time zone for network: ABC (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/28a18715d845be561391d397d5c5a02f
### ERROR
<pre>
2017-04-01 17:32:29 ERROR    Thread-16 :: [a011615] Missing time zone for network: ABC (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/035f65017d454ee1574367cde1d9f131
### ERROR
<pre>
2017-04-01 17:32:29 ERROR    Thread-16 :: [a011615] Missing time zone for network: TNT (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/c8f6ef9fc6dcf02c6e5d9a9f8638e2fb
### ERROR
<pre>
2017-04-01 17:32:29 ERROR    Thread-16 :: [a011615] Missing time zone for network: MTV (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/71ea94530097314cafc4fbaf6242dcf8
### ERROR
<pre>
2017-04-01 17:32:29 ERROR    Thread-16 :: [a011615] Missing time zone for network: FX (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/e4d631e490cc6556d839a072f1296334
### ERROR
<pre>
2017-04-01 17:32:29 ERROR    Thread-16 :: [a011615] Missing time zone for network: FOX (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/6f7b6ea9330a77f765c5e827004751dc
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: TBS
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/95e4d6dba2588548ff36e93ba8158c04
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: ABC (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/83fccc9afc789d00a66aa353619f9942
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: MTV (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/3fad522f3cf00f5b184278403351d743
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: TNT (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/38a69a84f7ed9b9442b2a63210661af5
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: MTV (UK)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/88196df14b6c8570b5a29e293049c9c0
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: NTV (JP)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/992338f70beab3741ffcaadc728f66d1
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: TV One (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/175674b5140100fd1b6597f1e2cc37bf
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: FX (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/dffa8f7dd28bf1f675dcf6680d93cc3f
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: Bravo (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
