### ISSUE TITLE
Preview for manual search subtitle

### ISSUE THREAD

**Issue by FireBladeNooT** [pymedusa/Medusa#1417]
For provider Addict7d, the name/version of subtitle is not show, so it's difficult to choose ^^

![image](https://cloud.githubusercontent.com/assets/16977862/19873582/1dc1cc16-9fc0-11e6-986f-39722550df06.png)

**Comment by fernandog** [comment]
@FireBladeNooT you have "perfect match" disabled right?

green mark is "perfect match"

as in your case as you have perfect match disabled, any subtitle that matches show + season + episode will be a "perfect" match

**Comment by fernandog** [comment]
@ratoaq2 seems he renamed file, but shouldn't we get the original "release_name" ? Look at the modal title.

**Comment by fernandog** [comment]
@FireBladeNooT the original filaname was like that (in the modal title) or you renamed using medusa or other tool?

**Comment by FireBladeNooT** [comment]
Hi,
so yes perfect match is disabled, and yes medusa renamed the file.
But why it seems to works with opensubtitle?

**Comment by fernandog** [comment]
@FireBladeNooT opensubtitle uses hash match most of times

**Comment by FireBladeNooT** [comment]
@fernandog 
Yes but with openssubtitle the name of file appears and with addict7d it just said "updated..."

**Comment by fernandog** [comment]
@ratoaq2  need to update Addi7ed code right?

**Comment by FireBladeNooT** [comment]
@fernandog I think yes

**Comment by fernandog** [comment]
@FireBladeNooT that code is not ours. is from another repository.

**Comment by FireBladeNooT** [comment]
@fernandog 
Ok, so I've to create an issue in this other repo?

**Comment by fernandog** [comment]
no

**Comment by medariox** [comment]
Those names are what we get from subliminal. This is definitely an upstream issue.

**Comment by fernandog** [comment]
@ratoaq2 for addi7ed can we get the `version` and show as the description of the subtitle?

https://github.com/pymedusa/Medusa/blob/master/lib/subliminal/providers/addic7ed.py#L265-L266

**Comment by ratoaq2** [comment]
Fixed by #1442
