### ISSUE TITLE
Parent Folder is not being saved, when clicked "set as default"

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#1424]
### Before submitting your issue:

Start fresh, and you don't have a rootDit set.

Add a new show.
In the process you need to configure a "Parent folder".
Select one, and click on "set as default*".
It won't save.

Same applies to configuring it through settings - general.

**Comment by p0psicles** [comment]
#1353

**Comment by fernandog** [comment]
confirmed

**Comment by ratoaq2** [comment]
Fixed by #1438
