### ISSUE TITLE
2016-11-04 03:00:09 ERROR    SHOWUPDATER :: [f430875] Exception generated: 'NoneType' object has no attribute 'paused'

### ISSUE THREAD

**Issue by medariox** [pymedusa/Medusa#1461]
```
2016-11-04 03:00:09 ERROR    SHOWUPDATER :: [f430875] Exception generated: 'NoneType' object has no attribute 'paused'
Traceback (most recent call last):
  File "/home/orangepi/.sickrage/medusa/scheduler.py", line 103, in run
    self.action.run(self.force)
  File "/home/orangepi/.sickrage/medusa/show_updater.py", line 112, in run
    if not show[0].paused:
AttributeError: 'NoneType' object has no attribute 'paused'
```

**Comment by medariox** [comment]
Also: https://github.com/pymedusa/Medusa/issues/1043#issuecomment-258348681
Got posted in the wrong ticket for some reason.

**Comment by p0psicles** [comment]
I think this is current develop. As we've already made changes to this code in a feature branch. I'd like to wait until we merge that, and then try to reproduce it.

**Comment by wimpyrbx** [comment]
i can confirm this issue as well

**Comment by ripper1967** [comment]
I found that i could do a manual mass update and refresh without the error, it only seems to produce the error when the hour i picked to have it auto update starts

**Comment by ripper1967** [comment]
current dev this is fixed for me no more error.
