### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Viceland (US)

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1473]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@2c3afd6ec8485029aa9a093f3484081303aed91f
**Link to Log**: https://gist.github.com/d98ec2194356af4b1812fcb41e9552bd
### ERROR
<pre>
2016-11-05 00:53:48 ERROR    DAILYSEARCHER :: [2c3afd6] Missing time zone for network: Viceland (US)
</pre>

---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
@duramato 
Can you add this one?

**Comment by medariox** [comment]
[Busy supergonkas is too busy.](https://github.com/pymedusa/medusa.github.io/commit/fe8cd69fd633397add32d8d0b734433149e6febd)

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/b4b236622d044f77783675c57bdc42ce
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: Viceland (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
