### ISSUE TITLE
[APP SUBMITTED]: EpisodeDeletedException

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#1481]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@146eefe7ab5bb9811b5233b19544876224b37592
**Link to Log**: https://gist.github.com/5409778db5fa1c21901f81bee171a5b1
### ERROR
<pre>
2016-11-05 17:04:55 ERROR    SHOWQUEUE-SEASON-UPDATE :: [146eefe] 294417: Couldn't delete episode Scream: The TV Series S00E04 from the database
Traceback (most recent call last):
  File "C:\pymedusaSickRage\medusa\show_queue.py", line 853, in run
    ep_obj.delete_episode()
  File "C:\pymedusaSickRage\medusa\tv.py", line 2541, in delete_episode
    raise EpisodeDeletedException()
EpisodeDeletedException
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
I dont even have that episode on my computer?

**Comment by medariox** [comment]
@ripper1967 
That's okay, it's just being deleted from the DB.

@p0psicles 
Apparently EpisodeDeletedException is being raised on successful episode deletion. 😆 
https://github.com/pymedusa/Medusa/blob/9f544d40b1cda69b792bd4aded3b963fca366c6e/medusa/tv.py#L2292

**Comment by ripper1967** [comment]
ok ty,  you can close it then

**Comment by medariox** [comment]
Changed here: https://github.com/pymedusa/Medusa/pull/1482
