### ISSUE TITLE
Episode shows as unaired even though it is aired

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1490]
Commit: 4b392abf8a7ddf8a66d9039f03db4260cd3d471c

Medusa's server time: `Sun Nov  6 23:42:27 UTC 2016`

![image](https://cloud.githubusercontent.com/assets/10121067/20042965/672bb668-a47b-11e6-8059-2d568738681b.png)

Network's timezone https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L937
it is `ITV:Europe/London` london which is in the **same time zone** as me , has the **Same time** as i have currently, the show is _definitly aired_. But as can be seen by the screenie it shows as unaired.

**Comment by duramato** [comment]
Another case:
https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L235

![image](https://cloud.githubusercontent.com/assets/10121067/20043063/3584363c-a47e-11e6-9b22-d5f1c2cab7dd.png)

**Comment by duramato** [comment]
Also a london timezone:
![image](https://lol.doyou.bid/tCHWK.png)

**Comment by fernandog** [comment]
@duramato still have this issue?

look in your logs for: 
"....airs in the future or has no airdate, marking it..."

or 
"...has already aired..."

**Comment by fernandog** [comment]
no response. reopen if happens again

**Comment by YogSottot** [comment]
Branch: master
Commit: a0116154f262786d6f5274459cb8f9cdb23012cc
Version: v0.1.11
Database: 44.5 
```
DEBUG SHOWQUEUE-UPDATE :: [a011615] 2175: Marvel's Iron Fist S01E01 airs in the future or has no airdate, marking it 'UNAIRED'
```
Show is aired.
![aired](https://i.imgur.com/6oa4dZx.png)
