### ISSUE TITLE
[question] PP scripts

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#1510]
Hi,
I got a question about usage of these scripts down this page below.
Will a  script start after Medusa has finished post processing?
Will Medusa wait for the script to finish before PP anything else?

![image](https://cloud.githubusercontent.com/assets/9487685/20077125/60d30148-a53b-11e6-884c-c4cd7c120962.png)

Cheers

**Comment by Thraxis** [comment]
Yes Medusa will wait for the script to finish and return a result code

**Comment by NicoLeOca** [comment]
thanks @Thraxis 

@fernandog @ratoaq2 
can you add it to wiki please?

**Comment by fernandog** [comment]
@NicoLeOca really? just look your SS with attention

**Comment by NicoLeOca** [comment]
@fernandog 
yes really!
because I have never used it before, I never coded any script in my life.
I wanted to know what I could expect before getting started
All users are not as experienced as you are

I am not surprised you asked though; the many features we add, the less user friendly it becomes.
that's why Sonarr is so popular vs SB/SR/Medusa.

I love Medusa but UX could really be better
they are so many settings here and there; when you start, you need to get ready to have headaches.

what do you think @p0psicles @ratoaq2 ?

**Comment by fernandog** [comment]
@NicoLeOca just click red **WIKI** on the page.

**Comment by NicoLeOca** [comment]
@fernandog 
I modified the page and added that:

Medusa will then wait for a feedback from your script before post-processing anything else. 

here:
https://github.com/pymedusa/Medusa/wiki/Post-Processing
