### ISSUE TITLE
Using a unicode show title (ja), breaks url to xem

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#1530]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop/6ce71405b4b31479577b9339fa3fcc7867aa29f5
OS: Windows7
What you did: Used show Food wars. Changed language to japanese.
What happened: The new (unicode/japanese) showtitle is used in the link towards xem.
What you expected: The link to xem not to break. Possibly not use the japanese title. And rather use an id.
Logs: Not needed

Some history in PR: #1528 

![image](https://cloud.githubusercontent.com/assets/1331394/20191617/91de766c-a786-11e6-9393-038eb3e0de5e.png)

**Comment by medariox** [comment]
Fixed, right? Can be closed? @p0psicles

**Comment by p0psicles** [comment]
No. This is a separate issue.

**Comment by duramato** [comment]
This also happens with a title with apostrophes

**Comment by fernandog** [comment]
@zoggy is it possible for you to add a new key in `http://thexem.de/map/all?id=78857&origin=tvdb` result with the xem_id so we can create the xem url like `http://thexem.de/xem/show/26` and add in our show page so user can click it?
