### ISSUE TITLE
/config page (Vue.js) doesn't load completely sometimes

### ISSUE THREAD

**Issue by medariox** [pymedusa/Medusa#1531]
Most noticeable on remote installs.

**Comment by fernandog** [comment]
this fix was supposed to be in 0.1.8. 

why we release without it ?

@OmgImAlexis too complicated to fix?

**Comment by OmgImAlexis** [comment]
If someone can give me a known setup that has the issue and that I can log into I can have a look otherwise it'll just have to wait until that happens.

**Comment by ratoaq2** [comment]
Fixed by #1566
