### ISSUE TITLE
Loading /config page, throuws warning in console.

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#1532]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop
OS: debian8
What you did: Loaded the /config page allot of times.
What happened: Most of the times it loaded. Once it didn't
What you expected: No warnings in chrome console.
Logs:
```
Vue warn]: Property or method "release" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. (found in root instance)warn @ vue.js:2574
vue.js:2574 [Vue warn]: Property or method "pythonVersion" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. (found in root instance)warn @ vue.js:2574
```

**Comment by fernandog** [comment]
@OmgImAlexis what about this one ?

**Comment by OmgImAlexis** [comment]
I'll fix this for 0.1.9 should be easy enough.

**Comment by medariox** [comment]
This should be fixed. @p0psicles ?

**Comment by OmgImAlexis** [comment]
@medariox If it's still not fixed then ping me on slack.

**Comment by medariox** [comment]
Should be fixed.
