### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Discovery Channel|Smithsonian Networks

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1536]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [feature/indexer/tmdb](../tree/feature/indexer/tmdb)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3
**Link to Log**: https://gist.github.com/b5b3f85b5eb9497bd11fcde3c403ffe9
### ERROR
<pre>
2016-11-13 16:38:20 ERROR    Thread-15 :: [d4746ea] Missing time zone for network: Discovery Channel|Smithsonian Networks
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Fixed in #1511.
