### ISSUE TITLE
[APP SUBMITTED]: TypeError: showPoster() got an unexpected keyword argument 'h'

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#1540]
### INFO
**Python Version**: `2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]`
**Operating System**: `Linux-4.4.30-unRAID-x86_64-with-Ubuntu-14.04-trusty`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@b6a8bc7cabd9c42a38ac7b993a841cc0cfc6d1cb
**Link to Log**: https://gist.github.com/cdf59e0f19ae2514f4fa7b261f322635
### ERROR
<pre>
2016-11-14 02:32:41 ERROR    Thread-21 :: [b6a8bc7] Failed doing web ui callback: Traceback (most recent call last):
  File "/app/sickrage/medusa/server/web/core/base.py", line 273, in async_call
    result = function(**kwargs)
TypeError: showPoster() got an unexpected keyword argument 'h'
Traceback (most recent call last):
  File "/app/sickrage/medusa/server/web/core/base.py", line 273, in async_call
    result = function(**kwargs)
TypeError: showPoster() got an unexpected keyword argument 'h'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
@OmgImAlexis can you reproduce this?

**Comment by OmgImAlexis** [comment]
Yes, should I close? Most routes have this issue, if you happen to add any extra params tornado flips out since we don't catch them with kwargs.

**Comment by p0psicles** [comment]
Aah Ok reproduce like that. Yeah I Agee a webserver should handle that. What's the downside of adding the Kearns?
