### ISSUE TITLE
Can't change episode status from ignored to wanted

### ISSUE THREAD

**Issue by Jaimar** [pymedusa/Medusa#1574]
**Branch/Commit: master version 0.1.8**
**OS: Synology 6.0.2-8451 Update 4** 
**What you did: added new series. Previous episodes are marked as ignored. Tried to put them as Wanted.**
**What happened: Got an error page saying "Oops
You have reached this page by accident, please check the url. "**
**What you expected: That the status of the episodes changed...**
**Logs:**
```
2016-11-17 16:24:27 DEBUG    TORNADO :: [b3a16be] Failed doing web ui request u'home/setStatus': Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/base.py", line 251, in get
    method = getattr(self, route)
AttributeError: 'Home' object has no attribute 'home/setStatus'
```

**Comment by medariox** [comment]
I've added a show as ignored and switched to wanted without issues on the same branch. 
Can you tell us how to reproduce this error? Are you trying to switch from within the show's page or where from? Try to be more specific please.

**Comment by Jaimar** [comment]
Hi,

I'm trying to switch from with the shows page. I select the episodes and then choose the different status. I get to "http://privateurl/home/home/setStatus?show=313999&eps=1x10|1x9|1x8|1x7|1x6|1x5|1x4|1x3|1x2|1x1&status=3" and then I get the error message. I restarted the package again but no resolution atm..

**Comment by Jaimar** [comment]
hmm.. I just noticed something else. When I change to another show from a showpage through the list I also get to the same errorpage.. maybe reinstall?

**Comment by fernandog** [comment]
@Jaimar i noticed in your url: `/home/home/`

did you changed `web_root`?

open you config.ini and check value for `web_root`

**Comment by Jaimar** [comment]
I haven't changed the webroot. But how can I check that config.ini file on a Synology NAS?

**Comment by fernandog** [comment]
Just open config.ini inside medusa folder.

**Comment by ratoaq2** [comment]
That file should be in `/usr/local/sickbeard-custom/var`

**Comment by Jaimar** [comment]
the file isn't there..


admin@ancalagon:/usr/local/sickbeard-custom$ cd /var
admin@ancalagon:/var$ dir
total 72
drwxr-xr-x 18 root root 4096 Nov 17 13:51 .
drwxr-xr-x 22 root root 4096 Nov 17 13:49 ..
drwxr-xr-x  4 root root 4096 Aug 24 16:05 cache
drwxrwx---  2 root root 4096 Mar 23  2016 crash
drwxr-xr-x  2 root root 4096 Mar  3  2014 db
drwxr-xr-x  3 root root 4096 Aug 24 16:04 dynlib
drwxr-xr-x  2 root root 4096 May 30  2014 empty
drwxr-xr-x 11 root root 4096 Nov 18 08:53 lib
lrwxrwxrwx  1 root root   11 Nov  7  2014 lock -> ../run/lock
drwxr-xr-x  9 root root 4096 Nov 18 09:28 log
drwx------  3 root root 4096 Nov  7  2014 net-snmp
drwxr-xr-x 17 root root 4096 Nov  2 14:48 packages
drwxr-xr-x  3 root root 4096 Sep 30  2014 quarantine
lrwxrwxrwx  1 root root    6 Aug 24 16:04 run -> ../run
drwxr-xr-x  3 root root 4096 Nov 17 13:49 services
drwxr-xr-x  4 root root 4096 Mar 24  2016 spool
drwxr-xr-x  3 root root 4096 Aug 24 16:04 state
drwxr-xr-x  5 root root 4096 Mar 24  2016 synobackup
drwx------  4 root root 4096 Mar 24  2016 target
drwxrwxrwt  5 root root 4096 Nov 18 00:11 tmp

**Comment by p0psicles** [comment]
I got a similar error yesterday. At the time I didn't have time to look into it. But I suspect that it has something to do with timing. Maybe the url hasn't yet been properly setup, before clicking it or something.

**Comment by Jaimar** [comment]
I just checked the conifg.ini

`webroot = ""`

I guess that's normal..

**Comment by fernandog** [comment]
@Jaimar do you use reverse proxy?

**Comment by Jaimar** [comment]
No I'm not

**Comment by medariox** [comment]
@Jaimar 
You should be using 
```
"http://privateurl/home/setStatus?show=313999&eps=1x10|1x9|1x8|1x7|1x6|1x5|1x4|1x3|1x2|1x1&status=3"
```
then.

Not **/home/home**

**Comment by Jaimar** [comment]
@medariox  I know this now and change the url manual now but this should be not the url I get from the program..

**Comment by medariox** [comment]
@Jaimar 
This really strange.
The last thing I can suggest is:
1) Shut down Medusa (make sure it really is shut!)
2) Make sure ```web_root = ""``` looks exactly like this, no spaces or anything else.
3) Save and start Medusa again

You aren't even using a reverse proxy. If this doesn't work, I don't know what to suggest anymore.

**Comment by Jaimar** [comment]
I have uninstalled the package on my synology and then I've added it again. I added one show and I have the same problem.. This is very strange..

**Comment by Jaimar** [comment]
Hi, just to let you guys know. I found the issue... it was Edge and IE11 (using windows 10)
With the opera and Chrome browsers no issues, haven't tested other browsers yet.

Thanks for the help.

**Comment by medariox** [comment]
Thanks for the bug report @Jaimar. Issue is added to the [Edge browser issues](https://github.com/pymedusa/Medusa/issues/1652).

**Comment by fernandog** [comment]
@Jaimar justed tested now and it works
