### ISSUE TITLE
[APP SUBMITTED]: Guessed more than one 'format' for 'Chicago.Fire.S05E01.HDTV.WEB-MiXED': HDTV,WEB-DL

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1581]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [feature/indexer/tvmaze](../tree/feature/indexer/tvmaze)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@921b9c75730a3a73c0155ecb51832b0494db7946
**Link to Log**: https://gist.github.com/af32963b0ff571d4a69d16d7423e365e
### ERROR
<pre>
2016-11-17 23:29:01 ERROR    FINDSUBTITLES :: [921b9c7] Guessed more than one 'format' for 'Chicago.Fire.S05E01.HDTV.WEB-MiXED': HDTV,WEB-DL
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ratoaq2** [comment]
HDTV + WEB-DL?

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [feature/indexer/tvmaze](../tree/feature/indexer/tvmaze)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@921b9c75730a3a73c0155ecb51832b0494db7946
**Link to Log**: https://gist.github.com/23cda61a51f8959918a9062dea5a61cc
### ERROR
<pre>
2016-11-18 06:24:21 ERROR    FINDSUBTITLES :: [921b9c7] Guessed more than one 'format' for 'Chicago.Fire.S05E01.HDTV.WEB-MiXED': HDTV,WEB-DL
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ratoaq2** [comment]
Same as #1587

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [feature/indexer/tvmaze](../tree/feature/indexer/tvmaze)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@921b9c75730a3a73c0155ecb51832b0494db7946
**Link to Log**: https://gist.github.com/0c271fec47da5a98eb06064d8bd9e5e0
### ERROR
<pre>
2016-11-19 14:45:39 ERROR    FINDSUBTITLES :: [921b9c7] Guessed more than one 'format' for 'Chicago.Fire.S05E01.HDTV.WEB-MiXED': HDTV,WEB-DL
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
