### ISSUE TITLE
[APP SUBMITTED]: Guessed more than one 'format' for 'I'm.a.Celebrity....Extra.Camp.S16E05.(17.November.2016).Web.mp4.hdtv.x264': HDTV,WEB-DL

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1583]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [feature/indexer/tvmaze](../tree/feature/indexer/tvmaze)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@921b9c75730a3a73c0155ecb51832b0494db7946
**Link to Log**: https://gist.github.com/4a17ad485d0c364d543cf3712dbbc6b5
### ERROR
<pre>
2016-11-18 01:40:10 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TvChaosUK] :: [921b9c7] Guessed more than one 'format' for 'I'm.a.Celebrity....Extra.Camp.S16E05.(17.November.2016).Web.mp4.hdtv.x264': HDTV,WEB-DL
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ratoaq2** [comment]
Fixed by #1597

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [feature/indexer/tvmaze](../tree/feature/indexer/tvmaze)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@921b9c75730a3a73c0155ecb51832b0494db7946
**Link to Log**: https://gist.github.com/52c3044e7884807457d60fe2bf1a2205
### ERROR
<pre>
2016-11-19 05:19:16 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TvChaosUK] :: [921b9c7] Guessed more than one 'format' for 'I'm.a.Celebrity....Extra.Camp.S16E06.(18.November.2016).Web.mp4.hdtv.x264': HDTV,WEB-DL
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
