### ISSUE TITLE
[APP SUBMITTED]: Guessed more than one 'format' for 'Salem.S03E03.HDTV.WEB-DL-KILLERS-FUM-RARBG': HDTV,WEB-DL

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#1587]
### INFO
**Python Version**: `2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.27-4-osmc-armv7l-with-debian-8.6`
**Locale**: `UTF-8`
**Branch**: [optimized](../tree/optimized)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@898e46c5f7a7966718f2f75e7f3ebad941b158f1
**Link to Log**: https://gist.github.com/d07f3ac5b547d4ee94d0dc22bca1424d
### ERROR
<pre>
2016-11-17 23:18:53 ERROR    FINDSUBTITLES :: [898e46c] Guessed more than one 'format' for 'Salem.S03E03.HDTV.WEB-DL-KILLERS-FUM-RARBG': HDTV,WEB-DL
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 why guessit was used in archive name? I thought we remove it

the subtitle files are normal

![image](https://cloud.githubusercontent.com/assets/2620870/20427511/77dd9488-ad6b-11e6-8a9b-b0d81239d4dd.png)

**Comment by fernandog** [comment]
https://github.com/pymedusa/Medusa/issues/1585

**Comment by fernandog** [comment]
is related to this code:

https://github.com/pymedusa/Medusa/blob/develop/lib/subliminal/providers/legendastv.py#L378-L384 

its guessing the archive name. but we don't need `format` there. we only need the "episode" guess

**Comment by fernandog** [comment]
@ratoaq2 can't we pass the `-P` argument and pass only `episode`?

```
$ guessit "Salem.S03E03.HDTV.WEB-DL-KILLERS-FUM-RARBG" -P episode
3
```

**Comment by fernandog** [comment]
I tried: `guess = guessit(clean_name, {'type': t['type'], 'show_property': 'episode'})` but still got the error.

can't understand why it doesn't work

**Comment by ratoaq2** [comment]
Release name in subtitle "archives" contains multiple release groups, formats and/or sources. There's nothing to be done here and we're not reporting these cases as errors anymore.
