### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Fox Broadcasting Company

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1591]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [feature/indexer/tvmaze](../tree/feature/indexer/tvmaze)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@921b9c75730a3a73c0155ecb51832b0494db7946
**Link to Log**: https://gist.github.com/7f251869d97f3c701adaa2439667689b
### ERROR
<pre>
2016-11-18 15:45:39 ERROR    Thread-15 :: [921b9c7] Missing time zone for network: Fox Broadcasting Company
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@b4a7e16f50ee2ced0e21ecb00c62fe3788bf063d
**Link to Log**: https://gist.github.com/2d65e6a59523acb0f764e60ac37d9ad2
### ERROR
<pre>
2016-12-28 22:43:53 ERROR    Thread-15 :: [b4a7e16] Missing time zone for network: American Broadcasting Company
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
