### ISSUE TITLE
wrong subtitles naming

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#1619]
Hi,

the whole was PPed and renamed by Medusa.
it dowloaded subs as well

here is what I got at the end in my folder:
![image](https://cloud.githubusercontent.com/assets/9487685/20465632/af47458e-af61-11e6-93d5-482839c4e29b.png)
there is one file with no extension

my naming partern is as such:
%S.N.S%0SE%0E.%RT.%SQ.N-%CRG

my logs:
https://gist.github.com/NicoLeOca/61893901a005ed34f4281c08ca27e686

**Comment by fernandog** [comment]
@medariox can you check?

**Comment by medariox** [comment]
The issue here is that replace_extension() doesn't work properly.

**Comment by fernandog** [comment]
@NicoLeOca please update and report if issue is fixed

**Comment by NicoLeOca** [comment]
@medariox @fernandog 
thanks for fixing it up quickly.

Medusa is up to date and I'll report if I see wrong behaviour
I close this one and I'll open it back if necessary
