### ISSUE TITLE
Trakt token is not properly refreshed, and needs manually refresh after a period of time.

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#1624]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**develop/tvmaze**
**OS:Debian**
**What you did:**
**What happened:**
**What you expected:**
**Logs:**
```
2016-11-21 06:22:42 WARNING  Thread-15 :: [7c8496e] Could not connect to Trakt service: You must get a Trakt TOKEN. Check your Trakt settings
```

**Comment by p0psicles** [comment]
@fernandog you experienced the same? Maybe it's because of me messing with my environment allot.

**Comment by ratoaq2** [comment]
I had the same issue some weeks ago

**Comment by fernandog** [comment]
I havent. Trakt restored darabase last week. Maybe related
