### ISSUE TITLE
Daily search scene exception lookup

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1633]
**Branch/Commit:** develop
**OS:** Ubuntu 14.04
**What you did:** Let daily run
**What happened:** It does an unecessary number of "Scene exception lookups" for show's i don't even have. For each show that it found and needed to do a "Scene exception lookups" it did it 6 times!
**What you expected:** For it to do only the number of necessary "Scene exception lookups"
**Logs:** https://gist.github.com/duramato/c0aa3d6d324e8e4f3d5b1a5134a045a0

**Comment by fernandog** [comment]
when can't match to a show in the database it does:

```python
        # try scene exceptions
        if not show:
            show_id = scene_exceptions.get_scene_exception_by_name(name)[0]
            if show_id:
                show = Show.find(app.showList, int(show_id))
```

btw i don't have this logs:
```
DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [a737de1] Hit the old cached items, not parsing any more for: rarbg
DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [a737de1] Unable to match Keeping.Up.with.the.Kardashians.S12E21.No.Good.Deeds.1080p.ETV.WEBRip.AAC2.0.x264-BTW[rartv] to a show in your database. Parser result: title: Keeping Up with the Kardashians, season: 12, episode: [21], episode_title: No Good Deeds, screen_size: 1080p, format: WEBRip, audio_codec: AAC, audio_channels: 2.0, video_codec: h264, video_encoder: x264, release_group: BTW, type: episode, absolute_episode: [], quality: 1080p WEB-DL
DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [a737de1] Unable to match Cops.S29E21.1080p.WEB.x264-HEAT[rartv] to a show in your database. Parser result: title: Cops, season: 29, episode: [21], screen_size: 1080p, format: WEB-DL, video_codec: h264, video_encoder: x264, release_group: HEAT, type: episode, absolute_episode: [], quality: 1080p WEB-DL
INFO     SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [a737de1] Removing cache entries older than 3 days from rarbg
```

**Comment by fernandog** [comment]
Looks like it try that when can't find show in the indexer

see if you can find `Unable to match Keijo.S01` this show in your indexers

**Comment by duramato** [comment]
The show exists? it even has the tvdbid in the lookup. I just don't have it in my library.
With another show and provider: https://gist.github.com/duramato/248fceb6de522b9daed8c321e6e05ed5
Seems to happen with animes/cartoons?

**Comment by fernandog** [comment]
As discussed here: https://github.com/pymedusa/Medusa/pull/1634#issuecomment-262076449
