### ISSUE TITLE
Edge browser issues

### ISSUE THREAD

**Issue by medariox** [pymedusa/Medusa#1652]
All issues are confirmed on current develop branch.
@OmgImAlexis It would be great if you could take a look.

1) Trying to add an existing show:
![image](https://cloud.githubusercontent.com/assets/2893509/20581457/46c8c2b0-b1d9-11e6-8e6d-172c1b4d1a04.png)

2) Using hide/show episodes button:
![image](https://cloud.githubusercontent.com/assets/2893509/20581495/85bc095a-b1d9-11e6-80b5-83ead4403706.png)

3) [Can't change episode status from ignored to wanted](https://github.com/pymedusa/Medusa/issues/1574)

**Comment by OmgImAlexis** [comment]
I'll have to fire up a Windows VM to test these. @p0psicles any chance you have access to a Windows machine to look into this?

**Comment by p0psicles** [comment]
Don't have w10

**Comment by ripper1967** [comment]
I have windows machine  if u need to look into this,  but it does the same thing  on my machine

**Comment by OmgImAlexis** [comment]
1. It seems to ignore the base href in Edge for some stupid reason and the js needs to be changed to add that before it.
We should probably do that for all `window.location.href` changes.
For example `window.location.href = $('base').attr('href') + 'addShows/existingShows'`

2. I can't confirm this with my setup.

**Comment by ripper1967** [comment]
want to try on my system? i will give u the info to log in if u want

**Comment by ripper1967** [comment]
or create a commit with it fixed and i will test it

**Comment by OmgImAlexis** [comment]
I've got a windows 10 vm booted so that's fine. I'm looking into anything else that may have broken in IE and Edge because of Microsoft being stupid... 😞

**Comment by ripper1967** [comment]
ok

**Comment by OmgImAlexis** [comment]
Issue 2 which hide/show episodes I can't check at the moment as I'm waiting for a few PRs to be merged which may affect it.

**Comment by labrys** [comment]
Good to know that Edge is so much better than IE :/

**Comment by fernandog** [comment]
Changing status in EDGE now works. Just tested

**Comment by fernandog** [comment]
Adding show also works

Except i saw this: `C:\Users\Fernando\Documents\SÃ©ries\Foreign Legion`

notice the "Séries" is showing as SÃ©ries. 

But it added ok

In display show is SÃ©ries too
