### ISSUE TITLE
[ FEATURE ] Different notification for episode being replaced with higher quality

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#168]
At the moment we send out the same notification for new episodes being added and for episodes being replaced with a higher quality. It'd be nice to have the notification state that the episode is being replaced and/or even a separate notification toggle for the two different events.

**Comment by OmgImAlexis** [comment]
This would also include things like when a version gets nuked and a proper gets snatched/downloaded as currently they send the same notification as the base file downloading.

@doucheymcdoucherson

**Comment by fernandog** [comment]
https://github.com/pymedusa/SickRage/pull/734

**Comment by p0psicles** [comment]
@fernandog can this be closed?

**Comment by fernandog** [comment]
Higher quality not implemented.
Need some rewrite in notifiers.

**Comment by labrys** [comment]
Added to master feature request list - discussion for feature will continue here even though issue is closed.
