### ISSUE TITLE
pp and backlog search not working as intended

### ISSUE THREAD

**Issue by poplolnman** [pymedusa/Medusa#1693]
Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit develop**
**OS:widows 10**
**What you did:**
**What happened:**
**What you expected:**
**Logs: below is a link to the log...
https://gist.github.com/poplolnman/10c4118d9403d312e580d681718ee886

**Comment by fernandog** [comment]
you need to point a release that is no PP

i see a lot of `skipping already processed`

**Comment by fernandog** [comment]
no response
