### ISSUE TITLE
[FEATURE] guessing matching subs based on filename

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#1710]
could we avoid this?
![image](https://cloud.githubusercontent.com/assets/9487685/20766505/07715f38-b737-11e6-84eb-ebeb9deef28b.png)
subs were downloaded manually somewhere else as you may guess
somehow VLC recognized them

**Comment by fernandog** [comment]
I didnt understood. Where subs are being downloaded? My are in the same folder as the video

**Comment by NicoLeOca** [comment]
sorry, it wasn't clearly
subs were not downloaded by Medusa, but by me somewhere else
I manually put them in the temperary folder where the video were
then manual PP

**Comment by fernandog** [comment]
no. they must have exact same name.
its not only medusa that does this way.

**Comment by NicoLeOca** [comment]
@fernandog 
that's why It's a feature request ;-)

but I understand as it may not worth it
