### ISSUE TITLE
[ FEATURE ] Summarize manual PP results

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#1712]
when we PP manually, Medusa tells us what it did exactly in details, pretty much the full logs.

![image](https://cloud.githubusercontent.com/assets/9487685/20783115/f275a3cc-b791-11e6-80d6-1433a808cec1.png)

Couldn't we have just a summary, easy to read?
like:
8 files found
5 were PPed
_and the list of Episodes is displayed_
3 were not PP
_and the list of Episodes is displayed and a reason is given_

we could leave the full details down the page

**Comment by labrys** [comment]
I have a cleanup in my local branch for the manual PP, it breaks it up a little bit more. I'll push it to dev.  I agree that the summary first would be nice.  I haven't made that change in mine yet.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
