### ISSUE TITLE
TVDBv2

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#1775]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Medusa Info:	Branch: develop
Commit: a1c30b8f69f232c2f16abb28c10af64c799a185c
Version: v0.1.8.1
Database: 44.3
 Python Version:	2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
 SSL Version:	OpenSSL 1.0.2d 9 Jul 2015
 OS:	Windows-10-10.0.14393
 Locale:	en_US.cp1252

**What you did:**SHOWQUEUE-SEASON-UPDATE
**What happened:** show wouldn`t update (show is The Shannara Chronicles)
**What you expected:** Update the show
**Logs:**
```
016-12-11 17:04:54 WARNING  SHOWQUEUE-SEASON-UPDATE :: [a1c30b8] 289096: No data returned from TVDBv2 during season show update. Unable to update this show
2016-12-11 17:04:54 WARNING  SHOWQUEUE-SEASON-UPDATE :: [a1c30b8] 289096: Unable to get info from TVDBv2. The show info will not be refreshed. Error: Show episode search exception, could not get any episodes. Did a season [2] search. Exception: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '77', 'X-Powered-By': 'Thundar!', 'Set-Cookie': '__cfduid=d10e5367570803ff14c849b515d5181ba1481493894; expires=Mon, 11-Dec-17 22:04:54 GMT; path=/; domain=.thetvdb.com; HttpOnly', 'Vary': 'Accept-Language', 'X-Thetvdb-Api-Version': '2.1.2', 'Connection': 'keep-alive', 'Cache-Control': 'private, max-age=600', 'Date': 'Sun, 11 Dec 2016 22:04:54 GMT', 'CF-RAY': '30fc3c299dc5189a-EWR', 'Server': 'cloudflare-nginx', 'Content-Type': 'application/json; charset=utf-8'})
HTTP response body: {
  "Error": "No results for your query: map[Season:2 tve.seriesId:289096]"
}
```

**Comment by ripper1967** [comment]
have moved a few of these shows like this over to tvmaze  it fixes the problem, just wondering if it is something i could fix on my end

**Comment by medariox** [comment]
Does this happen for other TVDBv2 shows too?

**Comment by p0psicles** [comment]
Think it's because tvdb added a season, and then removed it again. And it tried to update for that season. I havent' come around to it. But I suspect the issue went away by itself. @ripper1967 can you confirm that? Did you see the issue after that?

**Comment by ripper1967** [comment]
yes it went away no more errror. tvdb
