### ISSUE TITLE
WARNING  SHOWQUEUE-REFRESH :: [a1c30b8] 309893: No episode number found in.... for shows that have a word that starts with the letter C

### ISSUE THREAD

**Issue by Thraxis** [pymedusa/Medusa#1776]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch:**  develop
**Commit:** a1c30b8f69f232c2f16abb28c10af64c799a185c
**Version:** v0.1.8.1
**Database:** 44.3
**Python Version:** 2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]
**SSL Version:** OpenSSL 1.0.2j 26 Sep 2016
**OS:** Linux-4.4.30-unRAID-x86_64-with
**Locale:** Unknown.Unknown
**What you did:**
Showque Refresh ran on schedule
**What happened:**
Shows with a word that began with the letter C in the title threw the warning:  'No episode number found in'
**What you expected:**
All shows with downloaded episodes to process correctly/

This has been an ongoing issue since Guessit was introduced as the system for parsing files.  

Shows that had this issue last night:
Con Man
Marvel's Luke Cage
Comic Book Men
Class

Other shows in the past few days that have had this issue:
The Frankenstein Chronicles
Colony
Channel Zero
+My Wife is the Student Council President!

Other Shows tested with a manual Refresh that have this issue:
The Shannara Chronicles
The Cape
+The Asterisk War: The Academy City on the Water

_Shows with a + are Anime_

The only commonality for all of these shows is that they all have a word that starts with the letter C.

**Comment by medariox** [comment]
No issue here
https://gist.github.com/medariox/cbf79b88127dbeda5a31c7dd79864b67
Download, refresh, all good.

What are your show settings? Other relevant settings?

**Comment by Thraxis** [comment]
I didn't say it was an issue with Post Processing.

Open a show that has a word with the letter C at the start in the title in displayShow, one that you have episodes for.  Click on "Force Full Update".

https://gist.github.com/Thraxis/e67336426300fbd5e2d50b94ba5b36a9

**Comment by ratoaq2** [comment]
Are you able to create a fresh install in a separate place/folder and reproduce the issue with only one show in your library?

**Comment by Thraxis** [comment]
This issue is now.... fixed.

Latest Guessit updates have fixed this issue
