### ISSUE TITLE
[APP SUBMITTED]: WindowsError: [Error 5] Access is denied: 'G:\\completed  tv\\White.Rabbit.Project.S01E05.720p.WEBRip.X264-DEFLATE[rarbg]\\White.Rabbit.Project.S01E05.720p.WEBRip.X264-DEFLATE.mkv'

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#1779]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@a1c30b8f69f232c2f16abb28c10af64c799a185c
**Link to Log**: https://gist.github.com/889ea3c7bf89a8efd739d524d4cc9bd6
### ERROR
<pre>
2016-12-13 07:22:25 ERROR    Thread-33 :: [a1c30b8] Unable to move file G:\completed  tv\White.Rabbit.Project.S01E05.720p.WEBRip.X264-DEFLATE[rarbg]\White.Rabbit.Project.S01E05.720p.WEBRip.X264-DEFLATE.mkv to H:\tv\White Rabbit Project\Season 01\White.Rabbit.Project.S01E05.720p.WEB-DL-DEFLATE.mkv: WindowsError(5, 'Access is denied')
Traceback (most recent call last):
  File "C:\pymedusaSickRage\medusa\post_processor.py", line 399, in _int_move
    helpers.moveFile(cur_file_path, new_file_path)
  File "C:\pymedusaSickRage\medusa\helpers.py", line 320, in moveFile
    os.unlink(src_file)
  File "C:\pymedusaSickRage\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
WindowsError: [Error 5] Access is denied: 'G:\\completed  tv\\White.Rabbit.Project.S01E05.720p.WEBRip.X264-DEFLATE[rarbg]\\White.Rabbit.Project.S01E05.720p.WEBRip.X264-DEFLATE.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Do you have admin rights for that folder? Any other similar errors or did it happen this one time only?

**Comment by ripper1967** [comment]
i am not sure why this even submitted, i wasnt aware  it did .  i had to fix the read only on that folder

**Comment by ripper1967** [comment]
is this on our end or is it torrentings
[G:\completed tv\From [ WWW.TORRENTING.COM ] - Humans.S02E07.720p.HEVC.x265-MeGusta\Humans.S02E07.720p.mkv : Processing failed: Not enough information to determine what episode this is]
[G:\completed tv\From [ WWW.TORRENTING.COM ] - Kevin.Can.Wait.S01E12.720p.HEVC.x265-MeGusta\Kevin.Can.Wait.S01E12.720p.mkv : Processing failed: Not enough information to determine what episode this is]
[G:\completed tv\From [ WWW.TORRENTING.COM ] - Man.with.a.Plan.S01E07.720p.HEVC.x265-MeGusta\Man.with.a.Plan.S01E07.720p.mkv : Processing failed: Not enough information to determine what episode this is]
[G:\completed tv\From [ WWW.TORRENTING.COM ] - People.of.Earth.S01E08.720p.HEVC.x265-MeGusta\People.of.Earth.S01E08.720p.mkv : Processing failed: Not enough information to determine what episode this is]

**Comment by duramato** [comment]
@ratoaq2 
it's a guessit issue:
```
? G:\completed tv\From [ WWW.TORRENTING.COM ] - Man.with.a.Plan.S01E07.720p.HEVC.x265-MeGusta\Man.with.a.Plan.S01E07.720p.mkv
: title: From
  website: WWW.TORRENTING.COM
  season: 1
  episode: 7
  screen_size: 720p
  video_codec: h265
  video_encoder: x265
  release_group: MeGusta
  container: MKV
  type: episode
  parsing_time: 0.554311037064
```

**Comment by ratoaq2** [comment]
That name format is not supported:
`From [ website ] - Title...`
Removing the word `From` will fix it.

**Comment by ripper1967** [comment]
2016-12-14 08:27:28 WARNING  POSTPROCESSOR :: [aa2e8f5] Problem(s) during processing, failed the following files/folders: 
2016-12-14 08:27:28 WARNING  POSTPROCESSOR :: [aa2e8f5] Processing failed for G:\completed  tv\The.Curse.of.Oak.Island.S04E05.HQ360p.310mb.hdtv.x264-][ Bullseye ][ 14-Dec-2016 ].mp4: Not enough information to determine what episode this is
2016-12-14 08:27:28 WARNING  POSTPROCESSOR :: [aa2e8f5] [G:\completed  tv\The.Curse.of.Oak.Island.S04E05.HQ360p.310mb.hdtv.x264-][ Bullseye ][ 14-Dec-2016 ].mp4 : Processing failed: Not enough information to determine what episode this is]

**Comment by duramato** [comment]
```
# guessit: 2.1.1.dev0  rebulk: 0.8.3.dev0
? G:\completed tv\The.Curse.of.Oak.Island.S04E05.HQ360p.310mb.hdtv.x264-][ Bullseye ][ 14-Dec-2016 ].mp4
: title: The Curse of Oak Island
  season: 4
  episode: 5
  episode_title: HQ360p
  size: 310MB
  format: HDTV
  video_codec: h264
  video_encoder: x264
  date: 2016-12-14
  container: mp4
  mimetype: video/mp4
  type: episode
  parsing_time: 0.52229809761
```

What are the preceeding, debug, logs to those ones?

**Comment by ripper1967** [comment]
here is debug https://gist.github.com/ripper1967/e26142309a414de78cbc644c24e234f3
and here is the db log https://gist.github.com/ripper1967/c47b36d438c0dab918c1c45706c44978

**Comment by duramato** [comment]
Mm weird it's considering as air by date for you, guess because of the date @ratoaq2
