### ISSUE TITLE
name_cache beeing generated with wrong id

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1785]
@p0psicles, Follow up from irc 
logged info in the format `" Internal name cache for Quarry with id (show.indexerid) set is: [name_cache]" `
https://gist.github.com/duramato/4d5adc46ed173e79e29b9a2409edddfd

The issue is the show is saving to name cache with the imdb id `u'quarry': 269110`,and not the indexer id `Quarry with id (4158)`

Indexer used: tvmaze

**Comment by p0psicles** [comment]
Do you have a full log?

**Comment by duramato** [comment]
There are no other logs with info pertaining to the issue. The only other time I see it is an empty name cache is when performing a search, that it shows the name cache items,but it is the same as above.

**Comment by p0psicles** [comment]
Or just remove one of the shows.
