### ISSUE TITLE
[ FEATURE ] Allow UI theme customisation 

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1786]
Would be excellent if Archived could be different color green. darker perhaps. or even a completely new color. To easier distinguish between Download and Archive

**Comment by wimpyrbx** [comment]
looking towards a new UI it would perhaps also be possible for users to edit these colors themselves.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
