### ISSUE TITLE
Missing time zone for network: CBS All Access (US)

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1815]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:**
**What you did:**
**What happened:**
**What you expected:**
**Logs:**
```
2016-12-21 15:09:09 ERROR    Thread-35 :: [71fbe13] Missing time zone for network: CBS All Access (US)
```

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@18da54101053c83e0d23a4a260bf74183c3a5aab
**Link to Log**: https://gist.github.com/a7cc8f8784d8df106ce81ed5bd878eb2
### ERROR
<pre>
2016-12-24 07:55:26 ERROR    Thread-29 :: [18da541] Missing time zone for network: CBS All Access (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@9aeefe726e55597b5bf6d653c8793faf77e35cac
**Link to Log**: https://gist.github.com/a8373bb6c60911a697a7f0aeb0b72dc7
### ERROR
<pre>
2017-03-15 09:45:32 ERROR    Thread-33 :: [9aeefe7] Missing time zone for network: CBS All Access
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
Pull request sent to fix it for tvmaze

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/c0e739e379ea0d34e6e6cce425fe1939
### ERROR
<pre>
2017-04-20 08:57:34 ERROR    Thread-20 :: [a011615] Missing time zone for network: CBS All Access
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
