### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Sundance Channel

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1816]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@4be744925acba1993d643dcad22475fb24cc0318
**Link to Log**: https://gist.github.com/53c617ffac7c16948dbaaa461efd2e64
### ERROR
<pre>
2016-12-21 18:38:33 ERROR    Thread-16 :: [4be7449] Missing time zone for network: Sundance Channel
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@153b8ba884dd285a6f0458027015550478d85dfd
**Link to Log**: https://gist.github.com/6524fa87d96dd1d57e674531ed7cbba5
### ERROR
<pre>
2016-12-22 22:50:43 ERROR    Thread-16 :: [153b8ba] Missing time zone for network: Sundance Channel
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@b4a7e16f50ee2ced0e21ecb00c62fe3788bf063d
**Link to Log**: https://gist.github.com/6df8bf35d605caad2dfa2f0afe43c021
### ERROR
<pre>
2016-12-28 22:43:52 ERROR    Thread-15 :: [b4a7e16] Missing time zone for network: Sundance Channel
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/302765f0e968e27c3007f2c6c6955642
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: Super Channel
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/6a6bcee8358692689a54d7f099c549f4
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: Science Channel
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
