### ISSUE TITLE
[ FEATURE ] Omit certain directories from search

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1819]
for tvshow extras that never aired..
it would be nice to be able to put specials/extras in a folder called for example "Extras" which medusa would not scan/touch at all.

for example Game of Thrones i have all the bluray extras, but they never aired. that is 100+ files being scanned/checked each scan.

being able to put them in an omitted folder like "Extras" it would lessen the work medusa does.

**Comment by wimpyrbx** [comment]
just an update. implementing this would at least in my case mean a lot of episodes not being searched on scans/parses. Lots of non-aired extras available for shows that i like to keep in the same folder as the rest of the show.

So in short.
* Skip folders that are named <Whatever_We_Decide_To_Call_It>

**Comment by fernandog** [comment]
@wimpyrbx 

there is something in the code that is related to extras but is seems its a bug:

```python
def list_media_files(path):
    """Get a list of files possibly containing media in a path.

.....
    for cur_file in os.listdir(path):
        full_cur_file = os.path.join(path, cur_file)

        # if it's a folder do it recursively
        if os.path.isdir(full_cur_file) and not cur_file.startswith('.') and not cur_file == 'Extras':
            files += list_media_files(full_cur_file)
```

noticed the `and not cur_file == 'Extras' ` 

i think that is intended to be a Extra folder and not a file

@medariox confirm the issue?

**Comment by labrys** [comment]
@fernandog just because its a variable called `cur_file` doesn't mean its actually a file.

**Comment by fernandog** [comment]
@labrys that's why i asked to confirm or not. as afaik we ignored Extras folder.

i will check sickbeard/sickrage code

**Comment by labrys** [comment]
Unless it broke, it used to ignore them.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
