### ISSUE TITLE
[ FEATURE ] Rename files after metadata is updated

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#183]
Since files are only processed once if the show is missing the meta data such as the title the files may not be named correctly when they're processed. I'd love if when data gets updated we'd loop over the show's episodes and rename them according to the new data.

For example Daredevil only had episode 1 of season 2 named when the files processed so even though the show is now updated my files are still missing their names.

```
S01E01 - Into the Ring.mkv
S01E02 - Cut Man.mkv
S01E03 - Rabbit in a Snow Storm.mkv
S01E04 - In the Blood.mkv
S01E05 - World on Fire.mkv
S01E06 - Condemned.mkv
S01E07 - Stick.mkv
S01E08 - Shadows in the Glass.mkv
S01E09 - Speak of the Devil.mkv
S01E10 - Nelson v. Murdock.mkv
S01E11 - The Path of the Righteous.mkv
S01E12 - The Ones We Leave Behind.mkv
S01E13 - Daredevil.mkv
S02E01 - Bang.mkv
S02E02 -.mkv
S02E03 -.mkv
S02E04 -.mkv
S02E05 -.mkv
S02E06 -.mkv
S02E07 -.mkv
S02E08 -.mkv
S02E09 -.mkv
S02E10 -.mkv
S02E11 -.mkv
S02E12 -.mkv
S02E13 -.mkv
```

**Comment by labrys** [comment]
just have to be careful to avoid issues with scene numbering and per season scene exceptions.

**Comment by OmgImAlexis** [comment]
@fernandog can we add a field to the DB on whether the file has been named or not and if it hasn't once we update and get the name for the episode we can then rename the file.

**Comment by OmgImAlexis** [comment]
@fernandog was this fixed by the PR you merged recently?

**Comment by labrys** [comment]
Added to master feature request list - discussion for feature will continue here even though issue is closed.
