### ISSUE TITLE
Issues missed in wave 3

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#1840]
- [x] On home page the fuzzy dates are now all double lines.
- [x] The show page still has the massive dropdown.
- [x] The manual pp page isn't centered anymore.
- [x] The navbar needs padding added to the sides since the scrollbar now overlaps the most right dropdown.
- [ ] Show title wraps on small poster
- [x] 'Release' column in manual search results is too small. (Chrome 55)
- [ ] ~~Poster is not alligned with the info "box" (see image nº7)~~
- [ ] ~~On mobile all "tables" aren't the same size as everything else, which has the screen size when the page is first loaded (can be reproduced with chrome's dev tools) (see images nº8)~~

The ones that i've crossed now, are "won't fix". We should discuss these offline.

1.
![screen shot 2016-12-26 at 12 52 07 pm](https://cloud.githubusercontent.com/assets/6525926/21474044/2dcebbca-cb6a-11e6-81da-e8f1f0b5c40a.png)
2.
![screen shot 2016-12-26 at 12 51 26 pm](https://cloud.githubusercontent.com/assets/6525926/21474045/2dcec89a-cb6a-11e6-80fc-374c80278177.png)
3.
![screen shot 2016-12-26 at 12 52 26 pm](https://cloud.githubusercontent.com/assets/6525926/21474046/2dd0166e-cb6a-11e6-8ef5-6e68376cd1dc.png)
4.
![screen shot 2016-12-26 at 12 55 00 pm](https://cloud.githubusercontent.com/assets/6525926/21474073/89845664-cb6a-11e6-8e33-99142576fc86.png)
5.
![screen shot 2016-12-26 at 3 37 27 pm](https://cloud.githubusercontent.com/assets/6525926/21475853/4cea2668-cb81-11e6-802f-87f644425d55.png)
6.
![screen shot](https://snapr.pw/i/d134369c71.png)

7. 
![image](https://cloud.githubusercontent.com/assets/10121067/21486864/f0817790-cbb3-11e6-8c6a-62f5411e0f75.png)

8. 
![image](https://lol.doyou.bid/M3Qus.png)
![image](https://lol.doyou.bid/jv3yi.png)
![image](https://lol.doyou.bid/vzhbc.png)

and on desktop

![image](https://lol.doyou.bid/kOJpQ.png)

**Comment by OmgImAlexis** [comment]
For some reason it looks like the nowrap class was removed even though it's still used on td elements. Adding this back seems to fix the fuzzy date issue.

```
.nowrap {
    white-space: nowrap;
}
```

**Comment by OmgImAlexis** [comment]
Can you check if adding the nowrap in Chrome's devtools fixes it? I think that may be the issue.

**Comment by p0psicles** [comment]
@duramato https://cloud.githubusercontent.com/assets/10121067/21486864/f0817790-cbb3-11e6-8c6a-62f5411e0f75.png
How do you want me to fix this? Because I don't know. I tried shifting the image to the bottom. But then the imdb ratings row, will shift to the left. 
Plus, It's not that easy to align it to the bottom, and make it cross-browser supported. So unless someone knows a way to properly do this, it's a "won't fix".
