### ISSUE TITLE
[ FEATURE ] More options in renamer

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1875]
it would be nice, once KNOWIT is implemented into the database.. to be able to use CODEC information to tag files with renamer in PP.

for example to be able to be 100% sure (KNOWIT) when renaming files:
"SHOWNAME - SxxExx - TITLE (1080p WEB-DL AC3 5.1 X264).mkv"

WEB-DL would have to be from episodestatus like before, but "AC3 5.1" and "X264" would be 100% correct values from the file itself.

Lots of shows I download are not SCENE so alot are named just "s01e01.mkv" etc. This would help me alot in the renaming.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
