### ISSUE TITLE
[ FEATURE ] Move showselect and change behavior

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1876]
this is a feature request basically to move the show searchbox to the main header and have it work something like this:
http://jsfiddle.net/tumkxjdb/

i just repeated 5-6 shows in the list to show how it would look with more shows.
also the prev/next would obviously be the same icons we have at the moment.

**Comment by wimpyrbx** [comment]
![image](https://cloud.githubusercontent.com/assets/13415240/22292013/99b7a516-e309-11e6-972a-95b1f0588701.png)

this illustrates why this is wanted on my part. there is too much of DisplayShow taking up space below the menu and above the showheader-area imo.

it also illustrates additionally the message about updates (or running in another branch etc)

**Comment by wimpyrbx** [comment]
yellow area/arrows; move these elements
red area; area not really utilized well.

**Comment by OmgImAlexis** [comment]
@wimpyrbx I'm thinking we move the update banner to a notification on the bottom right like how Plexpy has it.

**Comment by duramato** [comment]
It would be better off beeing here:
![image](https://pls.gtfo.accountant/L9n9I.png)

in the bottom of the page it doesn't catch the user's eye as most pages are more than a screen's height, i personally i'm almost never on the bottom of the page while on the top the update notification is the first that catches my eye when opening medusa.

**Comment by OmgImAlexis** [comment]
@duramato I'm talking about a floating notification like plexpy has in the bottom right. Not moving it to the bottom of the page.

**Comment by labrys** [comment]
Floating UI elements are imo ugly and tacky.  It screams "look at what I learned how to do" not "This is a well thought out placement that serves a good function".  The only place I think they work well is in a fixed frame type element where it presents a fixed title-bar and nav-menu while the content of the page remains scrollable (e.g. the Plex Web App). 

That said, I think the current placement of those elements is absolutely horrible.  

Personally I think putting them in the bar as @wimpyrbx suggests is better, but I personally think that it would clutter the title bar too much, particularly for mobile UIs or lower screen resolutions which have enough screen real-estate issues.  

I think the best bet would be to replace the show changing element with a breadcrumb-style bar and to do away with the update message altogether.  The updates can either appear as a (small) pill-style indicator in the menu (similar to errors/warnings) or similar non-intrusive indicator.  

As for the other type of notification that can be present here (the occasional important notifications)  those should appear as a notification window that appears over the page upon first load that can be dismissed (either with or without further reminders).

**Comment by wimpyrbx** [comment]
happy to see some discussion around this. i agree that my initial example to move items to header might clutter it up. another approach would be to add a second menuline to hold sub menu to the right like it is at the moment and put, like labrys wrote, a breadcrumb solution.. åerhaås hen at the left of the submenu line.. how this would translate into responsive UI for mobile platforms etc i have no idea as i am not and most likely will not use medusa in mobile resolutions.

at least it seems to be an agreement that current setup clutters the main pages.

**Comment by fernandog** [comment]
@wimpyrbx are you good with new layout?

**Comment by wimpyrbx** [comment]
yes i am.
i still would like to see the notification boxes about updates and running on branch <> master move away from the "body" of the page, but all other aspects i wanted solved are done.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
