### ISSUE TITLE
[ FEATURE ]  History box for main page

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1877]
it would be cool to have a "widget" that would display above the show table on \home\

something like this
http://jsfiddle.net/vqzeqzyd/
(missing here is ofcourse the code to build x similar that would be possible to either jump next/prev or auto-rotate like a div-carousel

displaying for example up to 5 shows that were last affected by changes either by user or scheduled jobs.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
