### ISSUE TITLE
[ FEATURE ] Alternative episode table layout

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1878]
http://jsfiddle.net/z1fwnpfz/

it would be nice to be able to have something like this. crude example, but the point is multiline pr episode to avoid too much line breakage in the layout.

also it would be a good step towards making room for more information once KNOWIT is in the database and we can display codec information like "AC3 5.1", "x264" etc etc..

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
