### ISSUE TITLE
[ FEATURE ] Allow size limits for episodes

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#1883]
I'd really like some way to limit file sizes per quality. I keep getting 6GB+ 1080p WEB-DL files selected over 1GB - 2GB ones. Personally I don't see the difference between them and it just means my storage is filling up quicker.

**Comment by IDerr** [comment]
That means that all providers have to give filesize in their api ? I don't know if it's the case...

**Comment by p0psicles** [comment]
The thing here is.. we have global options, show option, searchprovider options (nzb and torrent), provider options. Where do you want to store this setting.

Maybe apparent place is show option. But then it won't take long for people to request different sizes for WEB-DL and BluRay and 4k, 8k,.. etc.

Our current architecture doesn't provide for this. So we need to redesign our quality system, to properly implement this.

We already have several issues reported which are related to this one. Just need to find someone who can work on it.

https://github.com/pymedusa/Medusa/issues/661
https://github.com/pymedusa/Medusa/issues/1266

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
