### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Amazon Prime

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#1900]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@ab588dc8cd0bff86d6a5ed3d4b99276763a42bbf
**Link to Log**: https://gist.github.com/584a26810b9af42dc9230bbb83be7a9e
### ERROR
<pre>
2017-01-04 14:26:09 ERROR    Thread-22 :: [ab588dc] Missing time zone for network: Amazon Prime
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
Added .

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.8-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@772930a97a94280d76a355f29706ee6b64035b5f
**Link to Log**: https://gist.github.com/ba1467c05d4ec2f68fe98410847a875f
### ERROR
<pre>
2017-02-21 04:36:31 ERROR    Thread-428 :: [772930a] Missing time zone for network: Amazon
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.10-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/7e08632d896d30f3cd902f544097a9cf
### ERROR
<pre>
2017-03-16 04:42:00 ERROR    Thread-20 :: [a011615] Missing time zone for network: Amazon
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
