### ISSUE TITLE
Empty column selector in Schedule

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#1942]
@p0psicles 

no JS errors in F12

![image](https://cloud.githubusercontent.com/assets/2620870/21682190/00dce7c0-d332-11e6-9af5-cf53d74e40ee.png)

**Comment by p0psicles** [comment]
@OmgImAlexis can you take a look at this?
![image](https://cloud.githubusercontent.com/assets/1331394/21691036/3279fa4e-d377-11e6-94cd-99dbc0c2976b.png)

**Comment by OmgImAlexis** [comment]
I moved this to the layout config var. Must have forgotten to update the js.

Look at `MEDUSA.config.layout.schedule`.
https://github.com/pymedusa/Medusa/blob/develop/medusa/server/api/v2/config.py#L125

**Comment by p0psicles** [comment]
I've seen one more like this one. Will also fix that
