### ISSUE TITLE
[ FEATURE ] quicksearch button on /home/

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1947]
it would be nice to have a search button right on the \home\ for shows that are missing the episode that just aired (or aired last 24h for example)

perhaps put it beside the progressbar or something.

it would have the same functionality as going into the show and clicking search for latest episode.

**Comment by wimpyrbx** [comment]
or even also add the manual search button which brings you to the manual search page for the last episode aired which is missing.

**Comment by fernandog** [comment]
@wimpyrbx that's why backlog Overview exists

**Comment by wimpyrbx** [comment]
yes, but backlog is often much longer than "aired previous 24h" shows. just thought it would be handy to be able to initiate a search for latest episode for a show directly in /home/

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
