### ISSUE TITLE
[ FEATURE ] Manual search by quality

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1948]
just a small request for a different table layout of hits.

instead of a full list by quality like it is at the moment i believe it could be nice to be able to box them into collapsable/expandable lists.

like this fiddle: http://jsfiddle.net/btx714wq/

with 10+ providers and so many different releases the list is very big..

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
