### ISSUE TITLE
Enzyme should not be used to parse .mp4 files

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#1949]
Trying to use enzyme on an mp4 raises the following error

```
2017-01-09 22:48:08 WARNING  SHOWQUEUE-REFRESH :: [ce6db48] Failed to refine video
Traceback (most recent call last):
  File "H:\usr\local\medusa\lib\subliminal\core.py", line 543, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "H:\usr\local\medusa\lib\subliminal\refiners\metadata.py", line 32, in refine
    mkv = MKV(f)
  File "H:\usr\local\medusa\lib\enzyme\mkv.py", line 56, in __init__
    raise MalformedMKVError('Parsing error: %s' % e)
MalformedMKVError: Parsing error: Less than 1 bytes read (0)
```

**Comment by ratoaq2** [comment]
I wonder how? 
https://github.com/Diaoul/subliminal/blob/master/subliminal/refiners/metadata.py#L30


It only runs in a mkv file

**Comment by ratoaq2** [comment]
Less than 1 bytr read is an empty mkv file, not mp4

**Comment by OmgImAlexis** [comment]
@ratoaq2 should that not be checking the file header instead of extension?

**Comment by ratoaq2** [comment]
This is what enzyme does.

**Comment by labrys** [comment]
@ratoaq2 The file referred to by that issue is a valid mp4 file and I have watched it.  It is not an mkv.  I'll see if I still have the log for this and if i do ill post the additional lines referencing the actual file.

**Comment by labrys** [comment]
Ofc it could be logging that its scanning one file, but its actually scanning another (similar to the issues with the `KeyError`s)
