### ISSUE TITLE
TVDB vandalism

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#1951]
Many series have been vandalized lately on TVDB.  We may need to look at some method of handling vandalized series locally if it continues to be a problem.  This is not related to #1950.

**Comment by p0psicles** [comment]
What are you thinking about? Maybe create UI controls to manually change db, and flag them as "fixed", that will prevent these episodes to be updated in future from indexer. Then you can unflag them when tvdb has been sanitized?

**Comment by labrys** [comment]
I'm not really certain yet, thus why I wanted to discuss it.  For example we could implement a delay on when an episode is updated, for example don't update information until X time after the last update.  This would give the advantage of allowing vandalized series to get corrected, however this could be an issue for frequently updated series that haven't been vandalized.  

The idea is to try to get them intercepted before they ever enter the database.  The reason its important to do it before is that more than just the database is affected.  For example an episode may get processed as the wrong number, wrong filename, wrong nfo data, etc.  

A manual correction would only work if the user notices it in a timely manner.   If it wasn't noticed initially, then eventually when its fixed and medusa updated the data, the file would now be vandalized in the users library but would not show as incorrect in Medusa.  Also with invalid numberings, this could lead to extra searches for episodes/seasons that don't exist, items potentially listed under the wrong episode number, etc.

**Comment by phraymond** [comment]
From a clueless end user point of view, could you somehow leverage the other two indexers as a "check" against TVDB vandalism?

**Comment by OmgImAlexis** [comment]
A main thing we can do for now is to strip all links from content coming from tvdb, etc. as well as all tags.

**Comment by phraymond** [comment]
Another question came to mind on this - which indexer is the "best" one? I mean, if TVDB has vandalism issues but the other's done, why not use another one? I note Medusa has "TVDBv2" as the default option, so I assume it's the preferred one? I've been looking around the internet for indexer discussions since having this thought but there's nothing out there particularly enlightening.

**Comment by OmgImAlexis** [comment]
There's no "best one" and the reason tvdb is targeted is because so many people use it and things like KODI and Plex default to using them as a source.

**Comment by phraymond** [comment]
That does make sense and lines up with the snippets I've seen elsewhere. I
guess the right question to ask is: what deciding factor would make me want
to choose a different one for any given show or overall? Simply personal
"gut" preference?

**Comment by duramato** [comment]
My choosing factors are usually artwork, amount of info and indexer. My general ordered being TheMovieDB the first because of its uptime and relatively rich content ( and better than tvmaze, because it's easy to add content, and has more artwork than tvdb) , secondly tvdb dispute it's poor infastruscture it's downtime vandalism bla bla, and lastly tvmaze because it generally lacks artwork only having posters and even those are poor.
But, this is my personal preference

**Comment by phraymond** [comment]
That is very helpful to me, thank you. I was leaning towards TheMovieDB as
well, after my reading. I don't see a way to bulk change indexers, though,
on existing shows, so this will have to be a "moving forward" type of thing.

**Comment by labrys** [comment]
From a technical standpoint, my preference is tvmaze first, tmdb second, and tvdb last.  

tvdb has had a horrible track record for availability.

tmdb has good content and good availability and the api rate-limit is fairly generous at 40 requests per 10 seconds.

tvmaze is still a newcomer so its content is still developing, but adding content is fairly easy and their guidelines for allowable content is much better than tvdb.  so far they have had a really good track record for availability.  The api rate limit, while appearing less generous than tmdb at 20 requests per 10 seconds, is actually fairly generous because any hits to cached content don't count against your limit.  Lastly the api doesn't require authentication, so using it as a reference (in .nfo files for example) is easy.

**Comment by labrys** [comment]
To address cross referencing to avoid vandalism, the problem lies in that the episodes dont necessarily map 1 to 1 across indexers (sometimes the same seasons or series dont even map) which makes using another indexer for validation is impractical.   For similar reasons, its not trivial to change indexers on a series once one has been selected.
