### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Netflix

### ISSUE THREAD

**Issue by theystillcallmemister** [pymedusa/Medusa#1956]
### INFO
**Python Version**: `2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]`
**Operating System**: `Linux-4.8.12-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@677b47ac1f6a75abc71c4472f3fb9c4eecb6413f
**Link to Log**: https://gist.github.com/fac3e3d88f45f4f9514c97b12d1d5ece
### ERROR
<pre>
2017-01-10 09:06:55 ERROR    Thread-16 :: [677b47a] Missing time zone for network: Netflix
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
All these network time zones are already there. Please let us know if it happens again.

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.8-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@772930a97a94280d76a355f29706ee6b64035b5f
**Link to Log**: https://gist.github.com/182ed4348006bfa0ad612b7bc5ddbb0f
### ERROR
<pre>
2017-02-21 04:36:31 ERROR    Thread-428 :: [772930a] Missing time zone for network: Netflix
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/cb421ef228191c18faa86ec3253c19d3
### ERROR
<pre>
2017-04-01 17:32:29 ERROR    Thread-16 :: [a011615] Missing time zone for network: Netflix
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/9583d1603b34754f1723761c90d00007
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: HDNet
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
