### ISSUE TITLE
Show refresh (and update?) taking way too long

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#1959]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**  Dev ce6db4851335b61a000f425f31ae195723671da9
**OS:**  Windows 7
**What you did:**  Nothing - auto show refresh was triggered
**What happened:**  Refresh still in progress from yesterday
**What you expected:**  Refreshes and updates to complete in a reasonable time

Checked server status and noticed every show was listed in the queue multiple times (once for each season) and a complete show refresh was being done for each season.  So if a series had 10 seasons the entire show would be updated 10 times.  Confirmed this by watching console.  An instance of the show in the queue would not drop off the server status page until after the entire series completed.  When the show started over at season 1 again, one instance would clear from the server status page, and the next would begin all over again.

**Comment by p0psicles** [comment]
Was it refreshed for a specific indexer? Did you maybe not update for a while? Like a new installation? Can you upload full debug? Tnx.

**Comment by p0psicles** [comment]
Haven't heard allot about this. And we've been using the indexers for a couple of months already. @supergonkas did you notice this?

**Comment by labrys** [comment]
TVDB is the only indexer i have been using.  Regardless of time period of last update, it should not be refreshing repeatedly.  Either a single season should be done per refresh or the entire show;  currently its refreshing every season every time its in the queue and being added to the queue once per season.  So a  series with one season is added to the queue once, but a show with 10 seasons is added to the queue 10 times, each time refreshing all 10 seasons.

**Comment by labrys** [comment]
To duplicate, make sure no items are in queue on server status page - trigger a manual refresh on all items from the mass update page - review queue on server status page, and watch logs or console to see the series repeat during the refresh.

**Comment by duramato** [comment]
Yes confirmed, it's each season.
@OmgImAlexis also has seen this

**Comment by p0psicles** [comment]
I know that it now looks weird. As it's updating on a per season basis. But I don't understand the issue.
Is it now incorrectly refreshing shole shows season by season at night, while no changes have been reported by tvdb.

or.. Does it update season by season when you force a refresh on the show?

If it's the first one, then show_updater is not functioning well.
If it's the second one, then I recognize the issue. Al tough I still don't understand how it taking so much more time. As now it's doing 20 season updates for a show with 20 seasons. But before that, it did 1 update of 20 seasons. There shouldn't be the difference there like your reported it. There isn't that much overhead.

**Comment by p0psicles** [comment]
Just tried to reproduce. Forcing update on all my shows, will only queue QueueItemUpdate() queuitems, and not QueueItemSeasonUpdate() items. After each update a QueueItemRefresh() is scheduled for that show. Nothing more than that.

**Comment by labrys** [comment]
The problem is that it doesn't just do one refresh per season it refreshes every single season for a show times the number of seasons that show has.  If a show has 10 seasons, it queues the entire series for refresh 10 times.  So it updates s01e01, s01e02.... s01eXX, s02e01...s02eXX, .... s10eXX.  At this point it should stop, but it doesnt, it starts over at s01e01 and loops through the whole series again ... and again and again until it has done the entire series 10 times.

**Comment by p0psicles** [comment]
aah okay, i think I know what the issue is. It's because of the refresh that tails the show_update. Already wasn't really a fan of this solution, and now I know why. I'll see if I can come up with a solution.

**Comment by labrys** [comment]
I had run both a forced show update and a forced show refresh to reproduce - as the queue was named showqueue-refresh in the console when i watched it loop through a series repeatedly I assumed it was the refresh triggering the multiple season calls, not the update, if you confirmed that its only the update, then I defer to your test as I killed the program after I saw that it was repeating as expected..

**Comment by labrys** [comment]
This should be high priority not medium as its a massive increase in number of requests for unchanged data.  It heavily affects UI responsiveness and it negatively impacts the service providers.

**Comment by fernandog** [comment]
fixed right? now we update seasons right @p0psicles
