### ISSUE TITLE
Fails for special number s00e00

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#1961]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:**  Windows 10
**What you did:**  Nothing - auto refresh of shows
**What happened:**  Showqueue-refresh raised EpisodeNotFoundException for special numbered s00e00.  Numbering is correct per TVDB.
**What you expected:**  Get data from TVDB and properly refresh and parse episodes.
**Logs:**
```
2017-01-10 08:13:40 ERROR    SHOWQUEUE-REFRESH :: [ce6db48] 83090: Unable to figure out what this file is, skipping D:\- Series\Goong [2006]\Season 00\Goong [2006] - S00E00 - Special.mp4
Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\tv.py", line 1062, in make_ep_from_file
    raise EpisodeNotFoundException
EpisodeNotFoundException
```

**Comment by duramato** [comment]
Maybe caused by this? https://github.com/pymedusa/Medusa/pull/1880/commits/7b353fe475ddd5eaf3fc728f43457d540d29a803

**Comment by p0psicles** [comment]
I doubt it @duramato as that prevents loading the s00e00 episodes from db.
And the only way to get it in the db, is through manually downloading a s00e00 ep. And then pp it. It's curious though that the exception gets thrown here. Need to do some digging here. As I don't know allot about the PP.

So this exceptions is thrown when it has an ep on disk, which it tries to pp into an episode object.

At this time medusa doesn't support episodes with number 0. Season 0 is okay.

**Comment by p0psicles** [comment]
imo we should do 2 things.
1. Properly handle the exception.
2. Implement S00E00 support.

It shouldn't be allot of work to implement. The work would be in the tests.

**Comment by labrys** [comment]
The big thing would be looking for all the places where an episode number was assumed to be required.  For example any logic that said `if not ep_num` would need to be changed to `if ep_num is not None`.

**Comment by p0psicles** [comment]
I'm going to experiment some with removing the show refresh from the QueueItemSeasonUpdate.
https://github.com/pymedusa/Medusa/blob/master/medusa/show_queue.py#L898

And force these for shows that have had the season update.
downside of this is, that it will always do the refresh. While running it from the queueitem, only did a refresh if it came to the end of the queueItem run.

**Comment by labrys** [comment]
I assume that last comment was more in regards to the show refresh and not specifically this issue.

**Comment by p0psicles** [comment]
Yeah.  Oops.  Don't know how it got here.
