### ISSUE TITLE
Postprocesser going backwards in time?

### ISSUE THREAD

**Issue by tagemu** [pymedusa/Medusa#1962]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** develop
**OS:** windows
**What you did:** looked at http://localhost:8082/home/status/
**What happened:** PP not running
**What you expected:** PP running each x minutes
**Logs:**
```
nothing in the logs that i can see relate to why it would do this..
```

this is what happens:
http://www.fshare.it/image.jpeg?i=tk1484137tg

**Comment by tagemu** [comment]
Post Process	True	True	True		10m	- 8h 6m 53s	2017-01-11 13:08:35	False

Continues to do it.

**Comment by labrys** [comment]
This usually means it has crashed, check and see if you have any invalid items in your post processing directory (such as an invalid rar file, etc).  Also, since you're on Windows, check and see if you have "Con Man" as a series.

**Comment by fernandog** [comment]
no response
