### ISSUE TITLE
[Improvements] Little fix for scene-exceptions

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#1971]
Hi again,

I think there's a little problem with scenes exception,
A commit have been made here : https://github.com/pymedusa/medusa.github.io/pull/21
to add some exceptions for example : 
Ao no exorcist S2 => Ao no Exorcist: Kyoto Fujouou-hen
The change is also made on thetvdb : http://thetvdb.com/?tab=series&id=248035&lid=7

When a manual search is done on the second episode for the S2, episodes will be referenced as season 1

2017-01-13 23:36:47 INFO     SEARCHQUEUE-MANUAL-248035 :: [677b47a] Beginning manual search for: [Blue Exorcist - S02E02 - Episode 2]
2017-01-13 23:36:47 DEBUG    SEARCHQUEUE-MANUAL-248035 :: [677b47a] 248035: Formatting pattern: %SN - S%0SE%0E - %EN -> Blue Exorcist - S02E02 - Episode 2

![Screen](http://i.imgur.com/pHQOrIg.png)

Medusa thinks that this episode number  is the absolute number, because I think, there is no check with scene_exceptions and the filename to determine season...

Same for the post-process by the way, it'll consider the number as absolute because there's an alias on thetvdb

I don't think if my explication was clear, but I hope it was...

Thanks a lot for your work

Belderak

**Comment by p0psicles** [comment]
hi @IDerr.
We made some changes to the way we search for anime using season scene exception names. Together with this fix, it will return the correct results, and show them at least for season 2.

![image](https://cloud.githubusercontent.com/assets/1331394/21954719/f67c5516-da59-11e6-9aef-59433e92e3ee.png)

It's true that the manual search, sometimes misplaces episodes, in the wrong season, when using season scene exception. That's a known error, and a little but harder to fix now.

We're using the scene exceptions for searching and parsing of titles. Searching is a little bit easier to do, then the parsing. We're using guessit for that. And this will improve over time.

**Comment by IDerr** [comment]
Yeah sure, thanks for your fix

Really awesome 👍

**Comment by IDerr** [comment]
Think we can close here no ?
