### ISSUE TITLE
Changing scene episode numbers after a show refresh, will keep reusing "wrong" guessit cached name parsing

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#1975]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:**
**What you did:**
* Refreshed a show dir with the show Ultimate Spider-Man season 3.
* noticed that xem is wrong and is mapping the episode 18 -> indexer ep 15.
* fixed the scene column episode numbers, changing 18 back to 3x15.
* did a rescan
**What happened:**
My downloaded episode 18 is still mapped to episode 15.
**What you expected:**
It to be put in the row of episode 18.
**Logs:**
Not really needed as I've already found the issue. Which we just need to discuss and find a possible solution for.
**Workaround:**
Restart medusa, and refresh.

The reason why it keeps parsing the ep 18 to ep 15, is because the parse result is cached. It was cached when the scene column was incorrectly configured by xem. Rebooting empties the cache, and makes it parse the episode using the new manually configured episode mapping.

A possible solution could be:
1. Keeping track of the timestamp parse cached results.
2. Then check keeping track of changes made to the episode in tv_episodes table. As when you override the scene episode column, changes are made to that table. We would need to add a column to track the timestamp.
3. When a cached parse is older then the newest change of one of the episodes for that season, re-parse it. It needs to be a little complex, as we don't know if we can trust the episode of the cached parse. Season would most likely be ok.

Other solution:
1. Empty parse cache every 24 hours.

**Comment by fernandog** [comment]
forcing show update doesn't invalidate cache?

**Comment by p0psicles** [comment]
No it doesn't. Show updater, doesn't do anything with the name cache.

**Comment by fernandog** [comment]
@ratoaq2 can we call something like this to remove cached parsed results  when user changes scene numbering?

```python
    def remove(self, indexer, indexerid):
        for cached_name, cached_parsed_result in self.cache.items():
            if cached_parsed_result.show.indexer == indexer and cached_parsed_result.show.indexerid == indexerid:
                self.cache.pop(cached_name)
                logger.debug("Removing cached parse result for show ID: '{id}'", id=indexerid)
```

**Comment by ratoaq2** [comment]
That can be a bit inefficient, right? How many items usually there are in the cache?

**Comment by fernandog** [comment]
no idea. how to make it efficient?
the main goal here is to invalidate/remove "outdated" cached itesm

**Comment by labrys** [comment]
maybe invalidate cache only for the episode when the numbering changes (would need to be invalidated for both the original and new episode)

**Comment by fernandog** [comment]
read code again
