### ISSUE TITLE
Medusa not working on reverse proxy

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#1984]
I use nginx to make a reverse proxy for all my services but it doesn't work with medusa but works with sickrage.
When it wants to download js and css, a lot of 404 errors because the link isn't good :
Link medusa : http://hostname.com/js/...
Real Link : http://hostname.com/medusa/js/...
There's some changes to do in the html I think.
![url](http://i.imgur.com/IukN4aR.png)

**Comment by p0psicles** [comment]
We have nginx users as well as apache users, with configured reverse proxy.
@OmgImAlexis, can you take on this one?

**Comment by OmgImAlexis** [comment]
@p0psicles for ref next time just mark as dupe and close. 👍 

Ref: https://github.com/pymedusa/Medusa/issues/1868
