### ISSUE TITLE
Error while searching on T411

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#1985]
I was searching ChäoS;Child and I saw on my debug log this error because of the ";"

This should url-encoded, but it doesn't seems so..

![img](http://i.imgur.com/m00RH06.png)

Thanks a lot,

**Comment by labrys** [comment]
@IDerr Can you confirm that this search works when it is url-encoded?  I'm posting a fix for this now if you wouldn't mind testing it.

**Comment by labrys** [comment]
Looks like `ChäoS;Child` isn't on t411, (searched using `ChäoS;Child`, `Chaos;Child`, `Chaos Child`, and `Kaosu Chairudo`).  However the URL-encoding should be fixed so you should no longer get those errors.

**Comment by IDerr** [comment]
Happening while connecting to provider too : 
![img](http://i.imgur.com/e9uTc0w.png)

**Comment by labrys** [comment]
@IDerr what branch are you on?

**Comment by IDerr** [comment]
master 
![](http://i.imgur.com/LoCiZog.png)

**Comment by labrys** [comment]
Ok.  I have a fix for it already that's awaiting merger to dev.

**Comment by IDerr** [comment]
Thanks a lot :D I think I'll switch to dev

**Comment by labrys** [comment]
It's not merged yet, its #1988.

**Comment by medariox** [comment]
Fixed in develop.
