### ISSUE TITLE
Cached results vs Forced manual search

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1998]
scenario:
when clicking "search" on an episode on DisplayShow it finds no suitable release.
however when going into manual search and forcing a new search it finds more releases and one or more suitable releases.

is there a way to force the search when clicking search on DisplayShow? right now it seems to use a cache results-list?

**Comment by fernandog** [comment]
If no cached results, it will auto run a search

By design existing cached results are only for DAILY providers
When you do a forced search it will use "MANUAL SEARCH" providers

Check your providers list. see which have the blue icon "M"

**Comment by wimpyrbx** [comment]
yeah i just don't understand the design. if i click search (DisplayShow) for an episode why would it not force and search all providers instead of looking at cache?

from a user perspective; clicking search on DisplayShow i would want to look beyond cache and look for the episode on all active providers?

i mean it can be solved by going into manual search and forcing search there and then once refreshed choose a release, but essentially that is what i thought clicking search on DisplayShow would do for me.

**Comment by fernandog** [comment]
why hit providers it you may already have a cached (good) result in the DB?
Also showing first cached it opens page faster

**Comment by wimpyrbx** [comment]
well i guess i'll have to stick with having to do force search in manual search if this is done by design.
not really a huge problem, but irritating as i notice it happens too often that cache is not updated with new releases hence nothing is being downloaded for that specific episode before i use the manual force search to update the cache

**Comment by fernandog** [comment]
@wimpyrbx you shouldn't. as daily updates the cache every x minutes.

Unless you have a provider that is not set as DAILY
please send a screenshot of your providers list.

**Comment by wimpyrbx** [comment]
![image](https://cloud.githubusercontent.com/assets/13415240/22103278/d0d83aca-de3a-11e6-9042-792896d304fe.png)

**Comment by fernandog** [comment]
why Extra doesn't have backlog enabled?

**Comment by wimpyrbx** [comment]
an overlook on my end. fixed now.
