### ISSUE TITLE
Scene numbering updated on Home page load

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#2002]
Scene numbering is updated on the Home page load, causing it to be unresponsive for a long time when there is a large number of shows.
```
622 Shows (347 Active) | 6273 +114 Snatched  / 37048 Episodes Downloaded (16.9%) | Daily Search: 0:07:10 | Backlog Search: 6:05:42
Memory used: 241.91 KB | Load time: 88.7180s / Mako: 87.5844s | Branch: develop | Now: Sex, 20. Janeiro 17 15:59
```

Log Snippet: https://gist.github.com/duramato/f6baf314cfff3fe0391d717dc221fda6

For comparision a "normal load":
```
622 Shows (347 Active) | 6273 +114 Snatched  / 37048 Episodes Downloaded (16.9%) | Daily Search: 0:04:45 | Backlog Search: 6:03:18
Memory used: 241.91 KB | Load time: 5.5397s / Mako: 4.5538s | Branch: develop | Now: Sex, 20. Janeiro 17 16:01
```

**Comment by fernandog** [comment]
bad luck. xem refresh happens once a day. you opened home and needed to be updated

**Comment by duramato** [comment]
This isn't the first time it occurued to me, and 80+s doesn't make much sense...
