### ISSUE TITLE
Absolute number 0 => fail search

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2003]
Absolute number of anime indexed with tmdb and tvmaze are all set to 0
![](http://i.imgur.com/Z4TgPnD.png)
so, when it is searching for episodes : 
![](http://i.imgur.com/9nNFNUb.png)
He searches with 00 and can't find any results

Thanks a lot

**Comment by p0psicles** [comment]
For anime it's better to use tvdb currently. I'll make sure to add a warning somewhere
