### ISSUE TITLE
Subscene as subtitle provider?

### ISSUE THREAD

**Issue by ZataH** [pymedusa/Medusa#2019]
Is it possible to get Subscene implemented as provider?
I often see alot of my shows, not getting subtitles from the current providers (Only chosen English and Danish subs)

**Comment by p0psicles** [comment]
We use subliminal as a library for the subtitles.
https://subliminal.readthedocs.io/en/latest/api/providers.html

If you would want to have that added, you should request that at subliminal.
https://github.com/Diaoul/subliminal/issues
