### ISSUE TITLE
Suggestion: Manual search should include "group" column for nzb results

### ISSUE THREAD

**Issue by Antioch18** [pymedusa/Medusa#2021]
Please consider adding a "group" column to the manual search results for nzb searches, e.g. "alt.binaries.multimedia.x264". If the name is too long to fit in the column, it is suggested to begin truncation from the left, or abbreviate by using the first character of the subgroup, i.e. "...multimedia.x264" or "a.b.multimedia.x264".

When searching for nzbs directly through my providers I occasionally encounter posts with identical names. In this instance it is useful to be able to differentiate the posts by group as posts in certain groups are more likely than others to be fake.

**Comment by fernandog** [comment]
@duramato do we have this info ?

**Comment by duramato** [comment]
I don't think newznab returns it
