### ISSUE TITLE
[APP SUBMITTED]: TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#2022]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@872d7bf3428ca7ec4314c583518d4bfca0bcf34e
**Link to Log**: https://gist.github.com/678ea5b7f5b82a5a76ad3769d240778a
### ERROR
<pre>
2017-01-24 04:03:14 ERROR    SHOWUPDATER :: [872d7bf] Exception generated: string indices must be integers, not str
Traceback (most recent call last):
  File "C:\pymedusaSickRage\medusa\scheduler.py", line 103, in run
    self.action.run(self.force)
  File "C:\pymedusaSickRage\medusa\show_updater.py", line 72, in run
    updated_seasons = t.get_last_updated_seasons([show.indexerid], last_update, update_max_weeks)
  File "C:\pymedusaSickRage\medusa\indexers\tvdbv2\tvdbv2_api.py", line 595, in get_last_updated_seasons
    if int(episode['lastupdated']) > from_time:
TypeError: string indices must be integers, not str
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by wimpyrbx** [comment]
can confirm this happens here as well for me on develop

**Comment by p0psicles** [comment]
I looked at it yesterday. But couldn't get it to reproduce.
Looks like somehow episode is a string and not a dict, like expected. Maybe something goes wrong when it tries to get the episodes for the show.

I have a PR ready, that will fix tvmaze updating. Maybe that also helps here. but honestly i doubt that.

**Comment by ripper1967** [comment]
I get this on a 3am  auto update  not  mass update  and update all shows. if that helps.

**Comment by fernandog** [comment]
@ripper1967 can you access your cache.db and send a screenshot of tje lastupdated table?

**Comment by p0psicles** [comment]
I don't think it has anything to do with that. The 'lastupdated' in the exception is an episode attribute returned by the indexer, which we use to check against our own lastUpdated in db. As the exception is referring the lastupdated and not the from_time var.

**Comment by p0psicles** [comment]
I'd like to merge the PR. Then see if it happens again. And if so, add some specific logging in develop, to see whats causing this.

**Comment by ripper1967** [comment]
after all the updates have updated twice now and no error will close this for now
