### ISSUE TITLE
feature request UI: change in DisplayShow top header

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2023]
Just a suggestion to the background "div"

![image](https://cloud.githubusercontent.com/assets/13415240/22253373/ac639a66-e251-11e6-9037-66a75ee24d9d.png)

fill it out on left and right side.

**Comment by p0psicles** [comment]
That's actually pretty cool @wimpyrbx!

**Comment by wimpyrbx** [comment]
yeah i think it looks quite good if it fills out the page. content in and below is boxed anyways, but i think it looks quite good :)

i also have ideas around the showselector above the title and the select solution below the div (wanted, allowed etc), but that's in another issue/feature request already.

**Comment by wimpyrbx** [comment]
unable to get sourcetree to work.. and at the same time it seems i'm having a hard time actually doing the changes in the css/mako files to get it like this ..

**Comment by p0psicles** [comment]
I also have been playing around. You really need to redesign it. I've tried with some css rules. But then you only can get the banner that wide when using position: absolute. And that's usually not that responsive ;-)

**Comment by wimpyrbx** [comment]
yeah i also played around with position:absolute etc. reason it doens't work afaik is that any div created also inherits a parent divs width if not using absolute.. so it's locked to the current width of some div somewhere hehe.. well it was a nice idea. perhaps something to think about if there is ever a new UI designed from scratch.

**Comment by wimpyrbx** [comment]
![image](https://cloud.githubusercontent.com/assets/13415240/22396587/8186ab58-e55d-11e6-9377-f9be17f9d57f.png)

just leaving this here. i look at the selection/quality setting. can be moved below the new <div> and free up space between header and season list

**Comment by Thraxis** [comment]
@wimpyrbx complete?

**Comment by wimpyrbx** [comment]
already in dev, so complete.
