### ISSUE TITLE
[ FEATURE ] SD WEB-DL quality level

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2031]
Example:
No.Activity.2015.S02E04E05E06.Webrip.x264-MFO.mp4

it would be nice to be able to have both SD TV, SD DVD and (a new one) SD WEB-DL as quality.
seen more and more of WEBRIP/WEB-DL of SD content popping up lately and I for one would like to differenciate between them just like we do on 720p, 1080p etc.

**Comment by wimpyrbx** [comment]
could this be related changes proposed in #1266 ?

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
