### ISSUE TITLE
ui feature request: double the menu bar

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2048]
double the menu bar. make submenus a part of menubar 2.
make both bars fixed like the top is at the moment.

![image](https://cloud.githubusercontent.com/assets/13415240/22371392/3db05c92-e497-11e6-966a-b94b8642f183.png)

**Comment by fernandog** [comment]
i liked it

**Comment by wimpyrbx** [comment]
this is of course a crude example, but show selector should be menu-fied i think. also some breadcrumb could be put somewhere if you'd want it. (like "Home / Shows / <Show Name>")

i'm also not 100% sure if i'd keep the buttons EDIT, PAUSE etc and perhaps do text menu like on the top bar.

so yeah, just throwing out ideas here since.
also the grey color is just to illustrate as i believe a color change could be a good move away from sickbeard/sickrage until there is a completely new UI being worked on.

**Comment by p0psicles** [comment]
I would hide the show selector in fullscreen, like your design. But still show it in mobile bar. And make this menu bar <> mobile.

**Comment by fernandog** [comment]
i don't like the idea of hiding the show selector...

**Comment by p0psicles** [comment]
I dont think you understand. I'll use different media queries. And show the select as is on mobile. And like @wimpbyrx designed for full width.

**Comment by labrys** [comment]
The medusa logo is a little antiseptic but the current logo should definitely go.

**Comment by wimpyrbx** [comment]
yeah don't take the logo in the image above as a serious replacement idea. i just wanted to see how it would look if i changed the colors and logo. to get a "new look"

**Comment by Thraxis** [comment]
@wimpyrbx Complete?

**Comment by wimpyrbx** [comment]
already in dev, so complete.
