### ISSUE TITLE
[APP SUBMITTED]: UnboundLocalError: local variable 'do_update' referenced before assignment

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#2058]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@e0e6acf52478ac0317c7c017ab7e342274919a1f
**Link to Log**: https://gist.github.com/1018bbce05692e5fc51591bb08f5596f
### ERROR
<pre>
2017-01-29 07:17:53 ERROR    Thread-28 :: [e0e6acf] Exception generated: local variable 'do_update' referenced before assignment
Traceback (most recent call last):
  File "C:\pymedusaSickRage\medusa\server\web\core\base.py", line 259, in async_call
    result = function(**kwargs)
  File "C:\pymedusaSickRage\medusa\server\web\home\handler.py", line 1513, in editShow
    if do_update:
UnboundLocalError: local variable 'do_update' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
Tried adding Taboo.UK  to scene exceptions, when clicking save changed web page went to white page and this error happened.

**Comment by fernandog** [comment]
@p0psicles 

1)
![image](https://cloud.githubusercontent.com/assets/2620870/22404036/3ab960e6-e60f-11e6-8521-bcd9f1d8ac85.png)


2)
![image](https://cloud.githubusercontent.com/assets/2620870/22404042/4e534932-e60f-11e6-9571-fbca26b647ee.png)
![image](https://cloud.githubusercontent.com/assets/2620870/22404046/6f328e56-e60f-11e6-8baa-89e075579819.png)

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/2061
