### ISSUE TITLE
[ FEATURE ] Add timeout to Plex, etc. to prevent excessive scanning

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#206]
If you add a lot of files to process all at once Sickrage tells Plex, etc. to rescan the library after every single file this can in some cases cause Plex to be completely unusable. I'd suggest we add a 20 second timeout and if there's another file processed within that time it resets it, after the timeout hits 0 only then do we send the refresh command. This would cause Plex to only scan the library once instead of in my case 500 times in 60 seconds.

**Comment by labrys** [comment]
I think either the timeout should be configurable, or better yet only call it once at the end of postprocessing if results were found.

**Comment by fernandog** [comment]
@OmgImAlexis its calls plex to refresh ONLY that show. To avoid scan full library

**Comment by OmgImAlexis** [comment]
@fernandog it may but Plex seems to rescan every single show. You sure it's not a quick scan of the show's library? Every single file that was processed when I was running it I had the whole "TV Show" library rescan.

**Comment by labrys** [comment]
@OmgImAlexis as far as i'm aware it refreshes the entire library.

**Comment by labrys** [comment]
@p0psicles another candidate for the Throttle class ... limit calls to refresh plex to, for example, once an hour

**Comment by OmgImAlexis** [comment]
Once an hour doesn't really help at all since Plex itself can have an option to do it once an hour. Doing it per show would be a lot better.

**Comment by ripper1967** [comment]
Plex also has an option to auto scan with any change to folders.

**Comment by OmgImAlexis** [comment]
@ripper1967 I know that and that's why I'd like to have something that just updates a single show. There's no point in Plex rescanning 10k+ episodes just to see that a single show with for example 2 episodes has a new one.

**Comment by ripper1967** [comment]
Oh i agree with you my plex is scaning all the time, was just pointing out
that there was an option for it that might be hooked into just to add a
show at a time without a full scan

**Comment by OmgImAlexis** [comment]
That auto scan just watches the file system and then updates. That doesn't work if you're using a network drive, if you're using docker and some OSs don't allow it either.

**Comment by Thraxis** [comment]
Unfortunately Plex doesn't have any method to say "update that show" You can either tell it "Look for any new items and add those"  or "Refresh the Metadata for every item in library 'X'"

My system runs a complete library update check of the TV section of my Plex library in 1 minute 20 seconds.  Which contains 286 different shows, spanning 733 seasons with 10749 episodes.

An update check on the Anime section of my Plex library takes about 40 seconds.  That is for 215 shows, spanning 317 seasons and 5025 episodes.

To scan both libraries would take about 2 minutes, I'd say a buffered call to plex where it would send one request every 5 minutes, consuming any duplicate requests between calls would be about the best you could do.

**Comment by labrys** [comment]
@OmgImAlexis Plex doesnt allow update of just a single series, only a single library.  And as for the update once per hour in plex, that will trigger every hour regardless of changes.  Using the example I mentioned it would only trigger a refresh once per hour *if* you had new shows during that time.  If you go 3 hours without a new episode added, it wouldnt trigger a scan.  It would be great if Plex supported scanning for just a single series/path.

**Comment by OmgImAlexis** [comment]
@Thraxis there is a update only this show but it needs to be done from the cli. Maybe we could look into adding a simple plex channel that just exposes the refresh function that we can then call?
On my setup a refresh to my show library with over 13k episodes takes well over 5 minutes and when multiple refreshes are done it can actually end up taking over half an hour for new episodes to appear as it seems to queue the refreshes one after each other or something like that.

@labrys that would help a little but still the single show would be ideal.

Maybe we can see if Plex would be willing to add another API endpoint for single show refreshes? I've had them respond quite nicely to other requests for bugs and such.

**Comment by labrys** [comment]
Added to master feature request list - discussion for feature will continue here even though issue is closed.
