### ISSUE TITLE
Posters home page not showing on chromebook / chrome

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#2070]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:**
**What you did:**
**What happened:**
**What you expected:**
**Logs:**
```
PASTE LOGS HERE
```

**Comment by fernandog** [comment]
@p0psicles still an issue?

**Comment by p0psicles** [comment]
Don't know. I don't have a chrome book.

**Comment by fernandog** [comment]
in chrome everything works
so how did you opened an issue with chromebook?

**Comment by fernandog** [comment]
re-open if happens again. all good here
