### ISSUE TITLE
TVShow.is_recently_deleted does not support multi-indexers.

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#2073]
```python
    @property
    def is_recently_deleted(self):
        return self.indexerid in app.RECENTLY_DELETED
```
This doesn't check which indexer the indexerid comes from so if you have the same ID number from two different and one of the shows is deleted, this would incorrectly flag the remaining show as recently deleted.

**Comment by p0psicles** [comment]
There are currently probably a hundred bugs, where we assume indexerid is always unique over all indexers. Until we seriously going to handle them all, we'll have to park this one.

Best you can do, is PR and add a ```# TODO: multiindexer fix needed```
Or something like that.

**Comment by labrys** [comment]
Which is why I opened the issue.  TODO's alone tend to just get forgotten.

**Comment by p0psicles** [comment]
Well just as easily as GitHub issues. But then it's in code, and flagged. Adding todos is how everyone can contribute. We should do that more often to mark tech debt imo.

**Comment by labrys** [comment]
Key phrase "TODO's alone..".  I documented it in my edits to tv.py with a todo already.
