### ISSUE TITLE
[APP SUBMITTED]: Errors: [u'Changing language to None for TVDBv2 show 248741']

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#2079]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@51ff22a919f4f27223c4bc958c74c6e91f627c56
**Link to Log**: https://gist.github.com/970ddf4a8ed5e2ca9e95eedf97364924
### ERROR
<pre>
2017-02-01 12:41:30 ERROR    Thread-25 :: [51ff22a] Errors: [u'Changing language to None for TVDBv2 show 248741']
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
I tried to edit a show under mass update to change the Preferred Quality  and got the same error  on all indexers .

**Comment by medariox** [comment]
@ripper1967 
Although there is an error, the quality should update correctly.

@p0psicles 
This is the relevant code: https://github.com/pymedusa/Medusa/blob/master/medusa/server/web/home/handler.py#L1384-L1415
If you want to look into it, I had a quick look and didn't really understand what you wanted to achieve.

**Comment by p0psicles** [comment]
Well it's not all my code anymore. But I'll look into it.

**Comment by ripper1967** [comment]
Its fine  it does change quality, it just pops a big red error that it wants to submit, maybe turn the error into a warning  or off?  it wanted to submit 327 errors. when  I updated all my shows quality.

**Comment by labrys** [comment]
@ripper1967 no its actually a bug, simple fix though

**Comment by ripper1967** [comment]
ty fixed by #2103

**Comment by fernandog** [comment]
@ripper1967 this PR above that really fixed your issue

As you can see in your error/log, show language was set to None because while mass edit several shows, you can't change language. Only in single show edition. I fixed that by ignoring if passed show lang in mass edit

**Comment by fernandog** [comment]
btw this doesn't make sense to me `Fix error message when changing show language to None` as we CAN'T change language to None

**Comment by labrys** [comment]
@fernandog your PR is not what fixed the issue.  It was logging as an error if the language was not set. The previous code refactor was faulty (it was adding everything as an error even if successful) and PR #2103 corrected that mistake.
