### ISSUE TITLE
DisplayShow Scene Name display

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2080]
![image](https://cloud.githubusercontent.com/assets/13415240/22519470/a8b482d0-e8b0-11e6-9173-2bee211a99f9.png)

should it display [u' etc here?

**Comment by fernandog** [comment]
Imo no.

**Comment by ripper1967** [comment]
I would have to agree with fernandog,  no to this one.

**Comment by duramato** [comment]
That's an issue with the snatchSelection, should be "human readable"

**Comment by labrys** [comment]
It's because the list is being printed directly.  Instead it should print `separator.join(aliases)`.  Also imo this should be a printed with one alias per line, limit 3 lines, and a + on the div to expand it to show all.

**Comment by fernandog** [comment]
![image](https://cloud.githubusercontent.com/assets/2620870/23072937/c6f05924-f51a-11e6-95a2-e1aa8e376793.png)
