### ISSUE TITLE
Fanart doesn't work properly on Mobile

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#2084]
The image is self explanatory, the fanart doesn't cover the full screen. Same goes for the show details.
While the screenshoots are from the UI PR, this affects all versions of Medusa.

![captura de ecra de 2017-02-02 20 45 11](https://cloud.githubusercontent.com/assets/10121067/22567652/c2739b10-e988-11e6-963c-1bf27461ff8a.png)

![captura de ecra de 2017-02-02 20 46 09](https://cloud.githubusercontent.com/assets/10121067/22567654/c2764752-e988-11e6-9dce-90636ca199e0.png)

![captura de ecra de 2017-02-02 20 46 22](https://cloud.githubusercontent.com/assets/10121067/22567653/c274d2aa-e988-11e6-84b0-71fc272aa225.png)

**Comment by fernandog** [comment]
at least to me is fixed
