### ISSUE TITLE
Backlog Concerns and potential options

### ISSUE THREAD

**Issue by jxer** [pymedusa/Medusa#2091]
Guys after having medusa add 300 torrents to my client and no way to clear it after simply changing quality i think some changes need to be made if possible.

a warning and an option needs to be added to indicate a quality change will re download all existing files . also if possible an option to only download future episodes in the new quality.

limit global backlog. not everyone holds on to everything, if i have 5 seasons of a show, and suddenly i want to change from sd to hd for season 6, most people are not going to want to redownload all 5 seasons now in hd, since we have prolly already watched them. I am asking for a "how far back do you want to go option" for those who want it all, they can leave it on unlimited, for me 2 weeks is prolly all i would use. "You have this option for forced backlog" which in my mind is pointless since it goes farther back in 12 hours anyway

finally archive on first download was removed. this needs to be put back, this needs to be a per show option.

people have to realize if private trackers are in play, then medusa can really really use alot of bandwidth and ratio constantly redownloading files that generally will prolly not be watched again.

these options need to be added for users who have small storage system limited bandwidth or simply don't keep multiple seasons of shows ( i delete everything after the season is over)  

also after the 300 hundred downloads started i tried to revert back to the original quality, that did not stop backlog from trying to keep downloading the new quality i tried to pick. i actually had to restore the entire server from a backup to get the original quality to stick without backlog killing me. something needs to be done here. either a clear backlog db or something

**Comment by jxer** [comment]
also where is my delete options in medusa already without removing the show, a per show or per season option needs to be added!

**Comment by fernandog** [comment]
My proposed solutions:
1) Add back the `Archive first match`
2) Add a WARNING while editing show quality that it could let to a lot of re-downloads if existing episodes doesn't have this new quality
3) Ask users with a modal while editing show quality if he wants to change status of all existing episodes to ARCHIVED

others?

**Comment by p0psicles** [comment]
Personally Im for option 3. As archiving is actually for these kind of use cases. Only I understand if users are not aware of this. Providing a user with a warning, if the user chooses for it, we could automatically archive existing DOWNLOADED episodes?

**Comment by fernandog** [comment]
yes, option 3 is to only archive episodes with `downloaded` status. don't know if too hard to do it
or just warn use and he picks the ones he wants to archive

**Comment by p0psicles** [comment]
I think its the easiest to implement and most user friendly. Will not be hard to code.

**Comment by jxer** [comment]
how about other issues p0psicles is it possible to code those as well?

**Comment by fernandog** [comment]
it need to be changed BEFORE user saves quality, otherwise backlog will start as soon you save it
Guess need to be done via JS?

**Comment by jxer** [comment]
option should simply be do you want quality change for only future epsiodes if yes, then automatically archive everything, remember automation is better!!!

**Comment by fernandog** [comment]
problem is: depending how you change you quality, you don't need to archive

If you have preferred set, and only **ADD** a new preferred, it won't be backlogged
If you have preferred set and remove like 720p HDTV and add 1080p HDTV, it will be backlogged

If you have only allowed set and only ADD a new allowed it won't be backlogged
If you have only allowed set and remove like 720p HDTV and add 1080p HDTV, it will be backlogged

**Comment by jxer** [comment]
when changing quality most would only be using 1 quality type for preferred, not sure why anyone would be setting 2 quality types, fine give me a checkbox to archive all episodes then :-)

**Comment by fernandog** [comment]
check this user quality setting: lol
![image](https://cloud.githubusercontent.com/assets/1867464/22587000/b6c33d12-e9cd-11e6-969f-f661d492bb8e.png)

**Comment by jxer** [comment]
stupidity should not be tolerated, that user prolly has no idea what he is doing

**Comment by labrys** [comment]
@jxer No need for that kind of comment.  Same could have been said for you.  You changed a setting and were surprised when it did what it was supposed to.

**Comment by labrys** [comment]
Personally, I think the modal warning is a good idea, but I also think the backlog logic should be improved.  I think there should be a smarter set of rules to govern which episodes are backlogged.  

Some examples of rules: 
* Only search for items that haven't been searched for in the last X days
* Limit total number of searches performed during a backlog run
* Limit total number of snatches during a backlog run
* Search for missed episodes of current seasons only
* More frequent backlog searches for series starred as favorites
...etc

**Comment by OmgImAlexis** [comment]
Like I was saying to @fernandog I think his idea of archiving stuff will help but not as much as he thinks it will. For example I still have 170/350 shows that backlog episodes every single day. Most of them are older shows that are only downloading missing episodes and/or replacing season packs with HD episodes. I have setup archived on a lot of episodes but that only brought my backlog from 6k+ down to around 1k and there's more getting added to that every time a new show comes out.

If there could be a way for Medusa to only search for example shows with no new episodes once every 3 days and then shows that are continuing every day that right there would reduce a lot of the strain and still get the same outcome.

**Comment by fernandog** [comment]
@OmgImAlexis i think is very usefull . You reduced your backlog in 83% (6k > 1k). isn't that expressive?

**Comment by fernandog** [comment]
@jxer need anything else? =)

**Comment by jxer** [comment]
@fernandog when i see the changes in master i will let you know

still would like ability to delete a episode straight out of medusa, not just when delete the show

**Comment by p0psicles** [comment]
You should create a new feature request for that.

**Comment by fernandog** [comment]
everything in master
