### ISSUE TITLE
[ FEATURE ] Add page for PP results

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#2099]
I'd be nice to have a page where we could see the results of all PPs in a table or something instead of just relying on the logs. This would help see what's not PPing, which episodes didn't match, etc.

**Comment by NicoLeOca** [comment]
@OmgImAlexis 
this wouldn't be enough?
https://github.com/pymedusa/Medusa/issues/1712

**Comment by labrys** [comment]
@NicoLeOca I think @OmgImAlexis is talking about a page for results for the auto PP not just the manual.

**Comment by OmgImAlexis** [comment]
Yeah I'm talking less of summarising the massive text on manual PP and more of adding a page like history but for PP results. Currently both manual and auto PP just make a bunch of logs if there's something wrong and don't give the user any way to fix anything.

I'd rather have a page where I can see what broke, see that a certain episode is named incorrectly, a scene exception is missing, a duplicate was found from a season pack, etc. and actually have buttons to fix it all.

**Comment by NicoLeOca** [comment]
@OmgImAlexis @labrys 
That would be nice indeed but it requires more dev

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
