### ISSUE TITLE
Add Italian support for season/episode 

### ISSUE THREAD

**Issue by medariox** [pymedusa/Medusa#2110]
Examples:
```
 python report_guessit.py 'Mastercook Italia - Stagione 6 (2016) 720p ep13 spyro.mkv'
# guessit: 2.1.2.dev0  rebulk: 0.8.3.dev0
? Mastercook Italia - Stagione 6 (2016) 720p ep13 spyro.mkv
: title: Mastercook Italia
  alias: Mastercook Italia - Stagione
  alternative_title: Stagione
  episode: [6, 13]
  year: 2016
  screen_size: 720p
  episode_title: spyro
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 0.333541870117
```

```
python report_guessit.py 'Mastercook Italia - Stagione 6 (2016) 720p Episodio 13 spyro.mkv'
# guessit: 2.1.2.dev0  rebulk: 0.8.3.dev0
? Mastercook Italia - Stagione 6 (2016) 720p Episodio 13 spyro.mkv
: title: Mastercook Italia
  alias: Mastercook Italia - Stagione 6
  alternative_title: Stagione 6
  year: 2016
  screen_size: 720p
  episode: 13
  absolute_episode: 13
  episode_title: spyro
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 0.32994389534
```

Stagione = Season
Episodio = Episode

Episodio seems to be fine, guessit is a bit confused by Stagione.

@ratoaq2 If you want I can open this in the guessit repo instead. 🙏

**Comment by ratoaq2** [comment]
`spyro` should be `episode_title` since it's just after episode. Is that correct?

**Comment by medariox** [comment]
```spyro``` is the group in this case.

**Comment by ratoaq2** [comment]
It's not possible to guess it properly then. Only the release group is an issue, since changing it will break a lot of scenarios where episode title is properly guessed

**Comment by medariox** [comment]
What about
```Mastercook Italia - Stagione 6 (2016) 720p Episodio 13 Pizza & Pasta.mkv```
? 😋 

Just joking, I understand if you don't want to support it without the entire correct guess.

**Comment by medariox** [comment]
Just FYI, most Italian releases don't have ```-``` before the group and they still get processed. For example:
```
python report_guessit.py "Mastercook Italia S06E03 corey91.mp4"
# guessit: 2.1.2.dev0  rebulk: 0.8.3.dev0
? Mastercook Italia S06E03 corey91.mp4
: title: Mastercook Italia
  season: 6
  episode: 3
  episode_title: corey91
  container: mp4
  mimetype: video/mp4
  type: episode
  parsing_time: 0.308223962784
```
The guess is only partially correct, of course.

**Comment by ratoaq2** [comment]
It can be supported, but the release group will be guessed as episode title. There's not much to do about it. The episode file is clear and well defined: the next unmatched part after episode numbers : https://github.com/guessit-io/guessit/blob/develop/guessit/test/episodes.yml#L240

**Comment by medariox** [comment]
That's understandable and completely acceptable - it would be great to have season + episode working so that the episodes can be processed.

**Comment by medariox** [comment]
Fixed some time ago with the guessit update.
