### ISSUE TITLE
[ FEATURE ] Remove items from sab history upon successful completion.

### ISSUE THREAD

**Issue by sparklyballs** [pymedusa/Medusa#2112]
Would it be possible in a future release for medusa to be able to remove an item from the history section of sabnzbd or that other nzb downloader ;) , much the same way that couchpotato does when a download has finished processing.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
