### ISSUE TITLE
Missing many posters/banners

### ISSUE THREAD

**Issue by BenoitMartin2** [pymedusa/Medusa#2115]
Hello,

Medusa Info:	Branch: master
Commit: b8f309af2893e06fc9cf91eb98da5164122c2046
Version: v0.1.10
Database: 44.4
Python Version:	2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
SSL Version:	OpenSSL 1.0.1t 3 May 2016
OS:	Linux-4.4.21-1-pve-x86_64-with-debian-9.0

**What you did:**
Added shows
**What happened:**
Many poster/banners not provided

http://i.imgur.com/TwoXoiA.png
http://i.imgur.com/xrz1WnL.png

**Comment by OmgImAlexis** [comment]
Can you try running a refresh on a show that's missing images and report back.

**Comment by p0psicles** [comment]
You'll have to be allot more specific than that.
Like which show? Which indexer. If you noticed it with multiple shows, please tell me which ones.
You could also check yourself on the indexer, if the posters/banners are available there.

**Comment by BenoitMartin2** [comment]
I use "all" indexers to search for a show and then I only select the first (good) result in the list.
I swtiched from SR to Medusa because I couldn't find some shows using SR. Using "your" indexers I can, but that's all I'm concerned bout indexers.

Despite refreshes I still miss banners for:
 - The Walking Dead
 - The Son
 - Iron First,
 - 3%,
 - Six.

And posters for:
 - The Young Pope,
 - The Crown,
 - Westworld,
 - Vikings,
 - Stranger Things,
 - Peaky Blinders,
 - The OA,
 - Luke Cage,
 - Greys Anatomy,
 - Outsiders.

Where can I see which indexer is used for a show or another? Where can I change it?
Thanks for your support

**Comment by p0psicles** [comment]
You can find which indexer through using the banner or simple layout, on the show overview page.
![image](https://cloud.githubusercontent.com/assets/1331394/22689449/63a61d18-ed31-11e6-9358-8214a4baced2.png)

To also show banners, your best bet, is to use tvdb. The others don't provide wide banners.

To switch indexers, you'll have to "remove" the show from library. Note! when it asks you to remove files, choose no, obviously. Then you should be able to readd it as an existing show, but select a different indexer.

**Comment by medariox** [comment]
About the missing posters: if you are using theTVDB, try to add them with English (eg. instead of French) language. Sadly resources are language bound, this is a known limitation of the new theTVDB API and it is being worked on their side: https://trello.com/c/dyEhtfky/15-handle-multiple-languages-in-the-accept-language-header

**Comment by fernandog** [comment]
can we make a small table while adding shows so user know which feature provider misses?
so before use picks a indexer, he knows what he will miss?

**Comment by BenoitMartin2** [comment]
Thank you all. I guess my prob is using the French language as all my missing visuals are from TVDB. I'll use English then.
