### ISSUE TITLE
[APP SUBMITTED]: TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#2121]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@63f66cdd827c391aa500986cd2b1e3b8276f858e
**Link to Log**: https://gist.github.com/3ac6567533f759fba5d4d3288d93eb69
### ERROR
<pre>
2017-02-07 15:57:36 ERROR    Thread-37 :: [63f66cd] Exception generated: unhashable type: 'list'
Traceback (most recent call last):
  File "C:\Medusa\medusa\server\web\core\base.py", line 259, in async_call
    result = function(**kwargs)
  File "C:\Medusa\medusa\server\web\home\handler.py", line 1431, in editShow
    exceptions = {exceptions}
TypeError: unhashable type: 'list'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
fixed as of current commit

**Comment by labrys** [comment]
As always, @ripper1967, thanks for the prompt issue reports and the feedback on when the issue is resolved.
