### ISSUE TITLE
adding existing show

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#2130]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: develop
Commit: 5df71dd80ebea7264e8b7cbcb2d146f68bd57f68
Version: v0.1.10
Database: 44.4
Python Version:	2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
**What you did: I added a existing show,set old episodes to skipped
**What happened: Got this in my log
**What you expected:**
**Logs:**
```
PASTE LOGS HERE  
 Here debug log:  https://gist.github.com/ripper1967/40de204a4e3553bd7e4e34e34c59223f
Here is info log:  https://gist.github.com/ripper1967/39de34e32f38ab8d7d8f256fd3b3c790
 the info log shows the invalid stuff

**Comment by fernandog** [comment]
Needde debug logs

**Comment by ripper1967** [comment]
ok will enable logs

**Comment by fernandog** [comment]
@ripper1967 i don't see any errors. what's wrong?
