### ISSUE TITLE
Episodes appear in backlogOverview but are snatched according to displayShow

### ISSUE THREAD

**Issue by Antioch18** [pymedusa/Medusa#2150]
**Branch/Commit:**
master / b8f309af2893e06fc9cf91eb98da5164122c2046

**OS:**
FreeBSD-10.3-RELEASE-amd64-64bit-ELF

**What you did:**
Opened up the backlogOverview page

**What happened:**
Found a lot of old episodes for various shows in the backlogOverview page even though the listed episodes were downloaded and marked as such in the displayShow page

**What you expected:**
Expected that recently aired but not yet downloaded episodes will be shown

**Logs:**
Unnecessary according to fernandog

![displayshow_wolfhall](https://cloud.githubusercontent.com/assets/2858806/22883776/207e2d24-f235-11e6-8f01-e8b7a419f3e3.PNG)
![backlogoverview_wolfhall](https://cloud.githubusercontent.com/assets/2858806/22883775/207e53f8-f235-11e6-87bc-8467f95e36c6.PNG)

**Comment by fernandog** [comment]
Your current episode quality is not in your wanted qualities. So it backlogged to try to find 720|1080p version
