### ISSUE TITLE
Unable to change episode status

### ISSUE THREAD

**Issue by Antioch18** [pymedusa/Medusa#2151]
**Branch/Commit:**
Branch: master
Commit: b8f309af2893e06fc9cf91eb98da5164122c2046

**OS:**
FreeBSD-10.3-RELEASE-amd64-64bit-ELF

**What you did:**
Ticked the box next to an episode whose status is "unknown" on the displayShow page, selected "Downloaded (1080p BluRay)" from the "change selected episodes to" menu at the top of the page and pressed the "go" button.

**What happened:**
The page reloaded as expected by the episode status didn't change.

**What you expected:**
The episode status changed to "Downloaded (1080p BluRay)"

**Logs:**
```
2017-02-13 21:48:07 WARNING  Thread-19 :: [b8f309a] Refusing to change status of 0x9 to DOWNLOADED because it's not SNATCHED/DOWNLOADED
2017-02-13 21:48:07 DEBUG    Thread-19 :: [b8f309a] Attempting to set status on episode 0x9 to 25604
```

**Comment by fernandog** [comment]
its a rule. you can't change it

File still exists? If so, just click "re-scan files"

**Comment by Antioch18** [comment]
I delete old episodes for shows I don't want to archive. Some of them I've downloaded manually and don't want to have appear in my backlog. Is the suggestion behavior in this case to set the episode as "skipped" instead?

**Comment by fernandog** [comment]
if medusa didn't snatched, yes. if recommend skipped

btw medusa detects you deleted a episode and chage status to ARCHIVED
this status is the same as DOWNLOADED, except it doesn't create backlog. Its like "don't touch it"
