### ISSUE TITLE
Phone UI scaling wrong in Schedule and History tab

### ISSUE THREAD

**Issue by llonca13** [pymedusa/Medusa#2159]
When in phone web browset UI gets messed up scaling when going to Schedule and History tab(like selecting "Request desktop site" in browser).I didnt have this problem in Sickrage/sickrage branch.Please fix if you can

**Comment by fernandog** [comment]
@llonca13 can you send some screen shots please?

**Comment by llonca13** [comment]
Good UI scaling in homepage tab
![screenshot_20170214-004657](https://cloud.githubusercontent.com/assets/17835147/22908611/be9d3e2c-f24f-11e6-9ff8-727aa152b52d.png)
Messed up in History and Schedule
![screenshot_20170214-004718](https://cloud.githubusercontent.com/assets/17835147/22908640/e4a5d002-f24f-11e6-92a0-ec8d9b0a611c.png)

**Comment by llonca13** [comment]
Thank you in advance

**Comment by duramato** [comment]
It's an issue with all tables, it's the same issue as the fanart https://github.com/pymedusa/Medusa/issues/2084

**Comment by llonca13** [comment]
Its true..i didnt notice it until now :(

**Comment by llonca13** [comment]
Good scaling in sickrage/sickrage
