### ISSUE TITLE
Improve T411 Torrent Search

### ISSUE THREAD

**Issue by Marbellasaad** [pymedusa/Medusa#2160]
Hello.

I don't understand why Medusa don't find some shows seasons/episodes like South Park Seasons or Arrow Episode.

What Medusa found for South Park S19 (i used the show all config) :
http://prntscr.com/e8i93g

But they are in T411 :
http://prntscr.com/e8i9ad

What i have in logs :
17-02-14 08:39:47 INFO     SEARCHQUEUE-MANUAL-75897 :: [T411] :: [b8f309a] Performing season pack search for South Park
2017-02-14 08:39:47 INFO     SEARCHQUEUE-MANUAL-75897 :: [b8f309a] Using manual search providers
2017-02-14 08:39:47 INFO     SEARCHQUEUE-MANUAL-75897 :: [b8f309a] Beginning manual season pack search for: [South Park - S19E01 - ]

It's strange Medusa search for "South Park - S9E01 -" even if i enabled the season search mode :
http://prntscr.com/e8i9pm

For Arrow it's a little bit different,Medusa find two result for the episode 1 :
http://prntscr.com/e8ib0g

But i have to enable the "&show_all_results=1" to see them. And he purpose me only two result for this episode when they are alot of others torrent for this episode : 
http://prntscr.com/e8ibe4

Thanks in advance !

**Comment by p0psicles** [comment]
If you know how to check out branches. Could you give this one a try? ```feature/fix-first-time-search```

**Comment by Marbellasaad** [comment]
I don't know how to. :'(

**Comment by p0psicles** [comment]
Then it's better to wait I think. That branch will introduce some fixes and improvements the searches. Won't take long before it's merged to develop. So by that time you might want to look into how to switch to develop.

**Comment by Marbellasaad** [comment]
Thanks alot. Hope it will fixes these issue !

**Comment by p0psicles** [comment]
Too much to answer in a short amount of time here.
https://github.com/pymedusa/Medusa/compare/master...develop

**Comment by medariox** [comment]
@Marbellasaad 
How do you search on T411? If I search the things you mention on the site, I get the same results as Medusa. Do you have some way to make the search more precise?

**Comment by Marbellasaad** [comment]
@medariox On T411 you can search like this : http://prntscr.com/e8yraw
Like if i search Arrow with these settings : http://prntscr.com/e8yrge
You got this : http://prntscr.com/e8yrlk

**Comment by IDerr** [comment]
In fact, you can also search episode with this ![img](http://i.imgur.com/FS3xyIG.png) (S3E06)

**Comment by IDerr** [comment]
In fact t411 really need this.

When Searching with "Arrow S05E10", no good results 
![](http://i.imgur.com/Hob25er.png)
but, when adding the season and the episode, only good results
![](http://i.imgur.com/Y2Ql4fM.png)

**Comment by IDerr** [comment]
If you need some info for T411, just mention me 👍

**Comment by fernandog** [comment]
maybe @duramato can improve it. he has T411

**Comment by fernandog** [comment]
@IDerr @Marbellasaad can you test T411 search?

I'm getting `[T411] :: [b4a8a54] POST URL: https://api.t411.ai/auth [Status: 404]`

seems that page opens a forum now

**Comment by IDerr** [comment]
Yes, seems to be a bug. I will send them a message :(

**Comment by IDerr** [comment]
![](http://i.imgur.com/MhP6D5L.png)
Seems to be on maintenance. 
We just have to wait.
:D

**Comment by fernandog** [comment]
@IDerr i still can't connect to t411 using api. what about you?

**Comment by IDerr** [comment]
Yep, still down....
We have to wait...

**Comment by fernandog** [comment]
@FireBladeNooT

**Comment by IDerr** [comment]
You can check the api status here:
http://irc.t411.ai/screens/ms/tutoriels/Nathann83/ip_t411.php

**Comment by fernandog** [comment]
Nice! Thanks

**Comment by IDerr** [comment]
Api is back @fernandog

**Comment by IDerr** [comment]
@fernandog I think you can close this ?
