### ISSUE TITLE
logo suggestion

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2161]
![image](https://cloud.githubusercontent.com/assets/13415240/22926105/8d7fa15c-f2ab-11e6-85c9-1007df61ff4a.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22926112/9541f21e-f2ab-11e6-83d1-457311b0bec0.png)

**Comment by wimpyrbx** [comment]
http://www113.zippyshare.com/v/Vl82J5DW/file.html

**Comment by wimpyrbx** [comment]
transparent PNG files uploaded just in case team wants this logo

**Comment by medariox** [comment]
I like this a lot, think it's much better than the current logo. It looks clean and modern. Thank you @wimpyrbx. Any other opinions? Should we think about replacing the current logo with this one?

**Comment by labrys** [comment]
Can you post a copy of the second logo on a dark background?  Also I think maybe try something other than a stark-white... But I really like the logo a lot.

**Comment by wimpyrbx** [comment]
well the ones i posted are transparent PNG files so should work on whatever background. or what do you mean?

also i'll make one that is not ultra-white in a bit.

**Comment by wimpyrbx** [comment]
![image](https://cloud.githubusercontent.com/assets/13415240/22951318/06cef9ec-f309-11e6-9f95-addded717d9c.png)

Photoshop file with multiple colors and stuff in link below.
(also includes white, grey, black text with green boxes ready PNG files at max resolution. could be webified to minimize file size later on)
* choose text color
* choose box color
* option to turn white, black or header background on/off to view how it looks on different backgrounds.
  (remove background when saving as PNG of course)

http://www53.zippyshare.com/v/L7LEBoCb/file.html

**Comment by wimpyrbx** [comment]
i would also either;
1) move logo to align with show select dropdown box
or
2) move show select dropdown box further to the left to align with logo

**Comment by labrys** [comment]
@wimpyrbx I meant just so we had a visual of it in the issue showing it without white on white.  And thanks for the tweaked image and quick response :)

**Comment by labrys** [comment]
Also, just a few other suggestions (just tossing ideas out) how about either a gradient version, or one with a pinstripe or something through it.

**Comment by wimpyrbx** [comment]
![image](https://cloud.githubusercontent.com/assets/13415240/22964989/9b492ed8-f35b-11e6-8adc-03b440fdb2ef.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22964995/9e4c1eba-f35b-11e6-8c34-2ab4e25c2775.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22965093/1db62998-f35c-11e6-9da1-1310a67459e9.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22965100/27e3193a-f35c-11e6-94cf-6cc7f6f068a2.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22965118/4cc6896c-f35c-11e6-8272-ea748b8218d5.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22965141/638a6164-f35c-11e6-8a0d-b4aaa0c92402.png)

just some examples.

**Comment by wimpyrbx** [comment]
![image](https://cloud.githubusercontent.com/assets/13415240/22965269/1472b4fe-f35d-11e6-93ef-470bad1e8377.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22965305/3d494e74-f35d-11e6-9ede-c1a66bb104dc.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22965353/7b31020e-f35d-11e6-9c83-769f423026b8.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22965370/978bfc74-f35d-11e6-919a-2ad6d1618d29.png)

**Comment by wimpyrbx** [comment]
personally i like the simplicity of the logo in the Photoshop post above. meddling too much with other letters etc might make the logo "scream" too much. the boxes to represent the E i thought at least took the focus away from the USA part hehe

**Comment by wimpyrbx** [comment]
same concept other fonts. still a fan of the last one (from above)

![image](https://cloud.githubusercontent.com/assets/13415240/22971318/8e81392e-f375-11e6-8e31-4885e17800e3.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22971362/b445eeca-f375-11e6-9b04-fc889ba029e9.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22971491/1f103d46-f376-11e6-80f8-a1686dd6e900.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22971614/8e7f4032-f376-11e6-9070-9405514ca361.png)

![image](https://cloud.githubusercontent.com/assets/13415240/22971635/a35b7a52-f376-11e6-82f3-5ca81a54b07e.png)

**Comment by wimpyrbx** [comment]
another option is to make the boxes a bit smaller
![image](https://cloud.githubusercontent.com/assets/13415240/22971836/5c9c3ae2-f377-11e6-9d82-53e9acd2d421.png)

**Comment by wimpyrbx** [comment]
last example and how it would look in the UI

![image](https://cloud.githubusercontent.com/assets/13415240/22972004/17bb5506-f378-11e6-806d-43a91390b8dd.png)

**Comment by p0psicles** [comment]
I'd like to also use the 6 squares as the ellipses at the top right on mobile.

**Comment by wimpyrbx** [comment]
that would be very possible of course. could also build up to a 9 square icon instead of 6.

**Comment by Antioch18** [comment]
On a related note, I do like that the mockup/screenshot above has modified the header from blue to gray. I think the whole UI could use some refreshes in this regard to make it look more "modern." (I much like the design of nzbhydra)

**Comment by wimpyrbx** [comment]
Antioch. The UI displayed in the mockup above is from develop branch so that will land in master release on next update i believe.

**Comment by wimpyrbx** [comment]
closed due to new logo PR.
