### ISSUE TITLE
Error in /home if no shows

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2169]
Mako Error
A mako error has occured.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.
Show/Hide Error

File C:\Python27\lib\random.py:275, in choice:
return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range

**Comment by fernandog** [comment]
confirmed
