### ISSUE TITLE
Scheduled episodes are being skipped and returned to status:unknown

### ISSUE THREAD

**Issue by Antioch18** [pymedusa/Medusa#2180]
**Branch/Commit:**
Branch: master
Commit: b8f309af2893e06fc9cf91eb98da5164122c2046

**OS:**
FreeBSD-10.3-RELEASE-amd64-64bit-ELF

**What you did:**
I didn't really do anything. I setup a season with episodes to automatically download as per usual medusa usage.

**What happened:**
The next episode (S8E13 in this case) of a show called "Modern Family" (which I only allow 720p WebDL quality) appeared in the schedule, as expected, but sometime around the airdate it disappeared from the schedule. Looking at the episode in the displayShow page shows status "unknown."

**What you expected:**
I expected the episode to stay in the schedule for 1~2 days past broadcast time until an nzb was found, after which it would be removed from the queue and it's status would be changed to "snatched."

**Logs:**
[application.log.txt](https://github.com/pymedusa/Medusa/files/780170/application.log.txt)

**Comment by fernandog** [comment]
@Antioch18 what is the default episode status? see in the show page summary

**Comment by Antioch18** [comment]
@fernandog Default EP Status: 	Wanted

**Comment by fernandog** [comment]
@Antioch18 i can't find useful log lines in that files

I need logs like : 
`status changed from `
`has already aired, marking it`

do you have local file for that show?

**Comment by Antioch18** [comment]
What log files do you need?

**Comment by fernandog** [comment]
@Antioch18 in viewlog with level DEBUG, use the input to search for that sentences i wrote

you didn't answer: do you have local file for that show?

**Comment by Antioch18** [comment]
@fernandog It's happened to another episode from a different show again, sometime in the last 12 hours.

I searched the debug logs for the past 7 days with both strings and there are no matches which leads me to believe that I'm hitting some very strange bug...

What is the "local file for the show?" I haven't downloaded the missing episode manually, if that's what you mean.

Searching the debug logs for the show/episode in question, I see that it found a parsed a result that matched the quality settings, but it seems that some processing after this failed.

`2017-02-17 04:05:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [6box] :: [b8f309a] Parsed 'Modern.Family.S08E13.Do.It.Yourself.720p.AMZN.WEBRip.DD5.1.x264-NTb' into title: Modern Family, season: 8, episode: [13], episode_title: Do It Yourself, screen_size: 720p, streaming_service: Amazon Prime, format: WEBRip, audio_codec: AC3, audio_channels: 5.1, video_codec: h264, video_encoder: x264, release_group: NTb, type: episode, parsing_time: 0.336925983429, total_time: 0.337833881378, absolute_episode: [], quality: 720p WEB-DL
2017-02-17 04:05:12 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [b8f309a] Seeing if we need anything from Modern Family`

**Comment by Antioch18** [comment]
Here are all of the logs from the medusa\logs\ folder.

[application.log.txt](https://github.com/pymedusa/Medusa/files/784771/application.log.txt)
[application.log.1.txt](https://github.com/pymedusa/Medusa/files/784773/application.log.1.txt)
[application.log.2.txt](https://github.com/pymedusa/Medusa/files/784772/application.log.2.txt)

The other show that it happened to recently is "The Big Bang Theory" s10e16 (accepted quality setting: 1080p hdtv, 1080p webdl).

No, there are no files in the local folder as the local folder doesn't exist: when I first setup sickrage, I had the default folder location set to "mnt1" and had sabnzbd configured to dump TV-tagged files there as well. However, "mnt1" has since gotten full so I've configured sabnzbd to dump TV-tagged files to "mnt2". So, in this case medusa is pointed to "mnt1" and shows "folder missing" alert.

If this usage is unexpected and is the cause of this behavior, I will go through my settings and change the folder locations, however, I still think that there is a bug related to this as there seem to be no errors or warnings in the log associated with the episode status change.

**Comment by fernandog** [comment]
I will check logs
Just add mnt1 as another root folder in general config

**Comment by fernandog** [comment]
@Antioch18 logs look ok, no issues there. so this shows that are having this issue are shows with the target folder is missing  ?

**Comment by fernandog** [comment]
Others shows are ok. It set as SKIPPED because is your default ep status for shows shows are: SKIPPED

Frontier (2016) S01E06 has already aired, marking it 'SKIPPED'
The New Edition Story S01E03 has already aired, marking it 'SKIPPED'
Da Vinci's Demons S01E02 has already aired, marking it 'SKIPPED'
Vikings S04E20 has already aired, marking it 'SKIPPED'

**Comment by fernandog** [comment]
In MASS UPDATE you can see all shows "Default Ep Status".

If is wrong, select all shows , click "edit selected", and change setting

**Comment by Antioch18** [comment]
Those and several other shows I've set to "paused" as I don't want to download them now, but want them in medusa for tracking purposes. What's interesting is that all of the episodes in those shows have already been set to "skipped" so I'm not sure why medusa is checking for them and updating the status to "skipped." That's odd...

Now that I think about it, yes, it does seem that the only shows with problems are those that have a missing folder, however I can't be sure without more observation.

In mass update, almost every show's default ep status is "wanted," including the paused shows, and the ones I mentioned as getting skipped.

**Comment by fernandog** [comment]
@Antioch18 when that happens do you get this warning?

`logger.warning("{id}: Show {show} location '{location}' is missing. Keeping current episode statuses` ?

**Comment by fernandog** [comment]
no response
