### ISSUE TITLE
Quality pills too cramped with the "Wanted/Quality" pill

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#2187]
It even goes as far as beeing hidden by the [low] `Quality` pill
![captura de ecra de 2017-02-16 23 22 17](https://cloud.githubusercontent.com/assets/10121067/23045969/ea032a26-f49e-11e6-9367-3a8a31474503.png)
![captura de ecra de 2017-02-16 23 22 29](https://cloud.githubusercontent.com/assets/10121067/23045968/ea020178-f49e-11e6-910f-e249f461a562.png)

**Comment by medariox** [comment]
Fixed, right?
