### ISSUE TITLE
[BUG] Search Ignores Valid results if episode does not have XEM mapping

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2216]
Can't find links for the season 3
![](http://i.imgur.com/SN5vMI0.jpg)

In fact, they are detected as Season 1

![](http://i.imgur.com/EzlDswy.png)

The alias name is set on the scene_exceptions

![](http://i.imgur.com/ov0VCC1.png)

But episodes were detected in the 0.1.10

![](http://i.imgur.com/qR3Aowf.png)

Thanks a lot and good luck for the 0.1.11

**Comment by Thraxis** [comment]
The Xem mapping for episodes currently only goes up to episode 4, there is a draft change pending to go up to episode 8.

@fernandog @p0psicles the system searches for the correct episode name, gets results and rejects them as not being wanted.  I believe this is because of the lack of XEM mapping as you can manually search and get results for S03E04 of Yowamushi Pedal, but not S03E05 or S03E06.

**Comment by p0psicles** [comment]
I'll have to dive in. Can look at it tomorrow. Let me know if you want to give it a go @thraxis

**Comment by IDerr** [comment]
![](http://i.imgur.com/DY6b2Yo.jpg)
I don't know if it's the same for this show

**Comment by IDerr** [comment]
![](http://i.imgur.com/UJnon9l.png)
I don't know if it's the same for this show... (Should be S8 instead of S1)

**Comment by fernandog** [comment]
@IDerr send a full print of the show page, with columns enabled in the column selector

**Comment by IDerr** [comment]
I don't know if I understood what you mean, but I think It's that ?

![](http://i.imgur.com/IHNtryE.jpg)

**Comment by fernandog** [comment]
@Thraxis 
does it search using scene absolute?
so if I understood correctly - based on this new SS -  S08E11 and S08E12 has scene absolute 0 so it will be discarded?

**Comment by Thraxis** [comment]
@fernandog There are two Bugs happening for both of these anime.

Bug #1 If there is not a XEM mapping for an episode Search / Manual Search will not find the episode
IE for Yowamushi Pedal

XEM mapping only goes up to episode 4 of season 3
![image](https://cloud.githubusercontent.com/assets/1131905/23137931/ada22344-f759-11e6-9601-a3221b3ee506.png)

Searching for S03E05 will find but not return results as the correct season
Searching for S03E04 will find and return results barring issues with Bug #2 below

Bug #2 Search does not differentiate returns if it could match multiple seasons.  Gintama vs Gintama S4 when scene numbering is per season not per series.

IE for Gintama:
English:
Gintama - 323 (1280x720 HEVC2 AAC).mkv
[HorribleSubs] Gintama - 323 [720p].mkv
[DeadFish] Gintama. (2017) - 07 [720p][AAC].mp4
Non-English:
[DefinitelyNotMe] Gintama S4 - 07 VOSTFR [720p].mkv
[PuyaSubs!] Gintama S4 - 07 [720p][D8108FA6].mkv

If that episode has a XEM mapping the first 2 will be detected
![image](https://cloud.githubusercontent.com/assets/1131905/23137607/bfb2c7f2-f757-11e6-9777-9c2bf3ac6e98.png)

Note:  Gintama doesn't have season name mappings on XEM, only season / scene mappings which may be part of the issue

**Comment by fernandog** [comment]
i think i will pass this to someone that understand this stuff better. @p0psicles ? =)

**Comment by IDerr** [comment]
Same here for 303867
![](http://i.imgur.com/SCNf7oa.jpg)
![](http://i.imgur.com/n5bk7Tv.png)

But weird, it detect episode S02E1 S02E02 and S02E3 in the S01E02 
Because of the 2 in the title for the season (Kono Subarashii Sekai ni Shukufuku wo! 2 ) I think
Perhaps an another issue ?
![](http://i.imgur.com/gFAhTIy.jpg)

**Comment by p0psicles** [comment]
Regarding the first, I can't reproduce it anymore. I guess xem is up2date now.

Regarding KonoSuba, it seems that guessit is parsing some titles wrong.
Like:
```[HorribleSubs].Kono.Subarashii.Sekai.ni.Shukufuku.wo!.2.-.01.[1080p].mkv```
```
# guessit: 2.1.2.dev0  rebulk: 0.8.3.dev0
? '[HorribleSubs].Kono.Subarashii.Sekai.ni.Shukufuku.wo!.2.-.01.[1080p].mkv'
: title: '
  episode_title: Kono Subarashii Sekai ni Shukufuku wo!
  episode: [2, 1]
  absolute_episode: [2, 1]
  screen_size: 1080p
  release_group: mkv
  type: episode
  parsing_time: 0.0479998588562
```
@ratoaq2, can you check this?
There is a scene name for:
```Kono Subarashii Sekai ni Shukufuku wo! 2```-> season 2.

**Comment by fernandog** [comment]
@p0psicles can't you change DB about xem numberring and block xem_update to reproduce again?

**Comment by p0psicles** [comment]
Well the only thing we do with the xem numbering syncing, is (for anime) filling the scene_absolute_number in tv_episodes table. Changing that manually (which should be possible) when there is no xem mapping available, should also resolve the issue.

@IDerr did you try that, at the time?

**Comment by IDerr** [comment]
Yeap, tried. But not changes...

**Comment by p0psicles** [comment]
Any other show you can reproduce it now?

**Comment by IDerr** [comment]
Nope, I think we can drop this for the moment if we can't reproduce...

**Comment by fernandog** [comment]
You cant reproduce because xem is updated.
It will happen again when some update is pending

**Comment by IDerr** [comment]
Yep. Just wait the answer of @ratoaq2 for the "possible" guessit bug. And I'll reopen a issue when xem will not be updated :)

Thanks for the work :P

**Comment by ratoaq2** [comment]
since the old legacy parser, animes are considered animes because it doesn't have season, only episode number. The animes that followed this pattern were and are still parsed having this number in the title:

https://github.com/pymedusa/Medusa/blob/develop/tests/test_guessit.yml#L1245

**Comment by IDerr** [comment]
So, it's not really something related to medusa...
But, we can add the show in the scene exceptions, to make it detected, right ?
But I think it doesn't work like the show above.

Thanks

**Comment by IDerr** [comment]
Having still the same issue for 303867. 
Do you want to close this issue since it resolved (XEM)

@ratoaq2 Even if there's no season in anime, It should be considered as season 2 because the show is in the scene_exceptions, no ?

**Comment by ratoaq2** [comment]
I'm not the expert in xem and anime. 
@p0psicles, could you help me to  understand what's expected from guessit in this situation? 

Probably there should be a fix  in the guessit side and on the  name parser as well.

**Comment by IDerr** [comment]
I think we can close this one.

Not having any XEM problems. Will reopen one if happens again.

Thanks
