### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Bravo (CA)

### ISSUE THREAD

**Issue by mykroft** [pymedusa/Medusa#2246]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.8-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@772930a97a94280d76a355f29706ee6b64035b5f
**Link to Log**: https://gist.github.com/a18e72e42336ee95ee517cc643b7fd95
### ERROR
<pre>
2017-02-21 04:36:31 ERROR    Thread-428 :: [772930a] Missing time zone for network: Bravo (CA)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/pymedusa/Medusa/issues/2276

**Comment by jlesage** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.10-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/15640251460d6e21f5c87471af2cd086
### ERROR
<pre>
2017-03-22 05:51:59 ERROR    Thread-16 :: [a011615] Missing time zone for network: TV5 (CA)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@YogSottot

**Comment by YogSottot** [comment]
@fernandog added

Also, all timezones mentioned in this issue pymedusa/Medusa#2276 already added.

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/59ea19a51714caf576362a81c667ef04
### ERROR
<pre>
2017-04-20 08:57:34 ERROR    Thread-20 :: [a011615] Missing time zone for network: SBS (AU)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/a5b636c6abcdcd8fdb28770bda713cf4
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: ABC (AU)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/5ef61fdb2413f0dccc800ac7252dbca1
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: CBC (CA)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
> SBS (AU)

https://github.com/pymedusa/medusa.github.io/blob/master/static/sb_network_timezones/network_timezones.txt#L1585

> ABC (AU)

https://github.com/pymedusa/medusa.github.io/blob/master/static/sb_network_timezones/network_timezones.txt#L78

> CBC (CA)

https://github.com/pymedusa/medusa.github.io/blob/master/static/sb_network_timezones/network_timezones.txt#L358
