### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: PlayStation Network

### ISSUE THREAD

**Issue by mykroft** [pymedusa/Medusa#2247]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.8-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@772930a97a94280d76a355f29706ee6b64035b5f
**Link to Log**: https://gist.github.com/cdf7aa7c04ac0853c7120d6549148f49
### ERROR
<pre>
2017-02-21 04:36:31 ERROR    Thread-428 :: [772930a] Missing time zone for network: PlayStation Network
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/pymedusa/Medusa/issues/2276

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.10-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/dc22a3ba87bf38214c0d1a455c81b374
### ERROR
<pre>
2017-03-16 04:42:00 ERROR    Thread-18 :: [a011615] Missing time zone for network: PlayStation Network
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mykroft** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/63a97821a37acfeded01499a10e1d748
### ERROR
<pre>
2017-04-01 17:32:29 ERROR    Thread-16 :: [a011615] Missing time zone for network: PlayStation Network
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
