### ISSUE TITLE
[OSMC] Add hidden setting in config to disable auto updates

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2267]
So all updates comes from app store

@samnazarko Medusa is pretty stable and if all @pymedusa/developers agree we can add to OSMC app store

we are mainly adding new features and improving code.
We currently don't have any major issue.

**Comment by fernandog** [comment]
btw our user base will increase a lot,  so I ask you: are we prepared?

**Comment by samnazarko** [comment]
see slack

**Comment by labrys** [comment]
I don't mind all updates coming from the app store, but it would require the app store to track reasonably close to upstream in order to provide effective support.  We do tend to push a lot of commits and make quite a few fixes/improvements even between minor releases.

**Comment by labrys** [comment]
If it's not possible for OSMC app store to track fairly closely to upstream, we would need to decide on and implement an LTS release scheme.

**Comment by fernandog** [comment]
I will handle this directly with Sam
