### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: National Geographic (AU)

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2293]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@d2f0f4f5bf70d0ca8220528c297852f9f631b22f
**Link to Log**: https://gist.github.com/aaecf0c5aa504a3fcea40fef618d3751
### ERROR
<pre>
2017-02-25 16:08:50 ERROR    Thread-33 :: [d2f0f4f] Missing time zone for network: National Geographic (AU)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by wimpyrbx** [comment]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@f52a0bbf06a0ef550a173a663df948fea73a659c
**Link to Log**: https://gist.github.com/9bdb0307aaf213905b9c8b86df5f4765
### ERROR
<pre>
2017-02-26 04:05:17 ERROR    Thread-25 :: [f52a0bb] Missing time zone for network: National Geographic (AU)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/pymedusa/Medusa/issues/2276
