### ISSUE TITLE
Add Open Search support

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#2320]
This will rely on the API's search. @ratoaq2 not sure if we should use `GET /api/v2/show?q=` for this or if we should have a search page that internally calls that.

Also not sure how we can handle internal domain/ip vs external since this will add it to browsers for whatever we provide and we can't provide two different URLs. 

Ref: https://stackoverflow.com/questions/7630144/how-to-add-google-chrome-omnibox-search-support-for-your-site

**Comment by labrys** [comment]
Added to master feature request list - discussion for feature will continue here even though issue is closed.
