### ISSUE TITLE
[ FEATURE ] Add Slack notification

### ISSUE THREAD

**Issue by Ic3Nine** [pymedusa/Medusa#2345]
This is a feature request through and through.

The ability to use slack notifications for snatches/downloads/updates.

**Comment by Ic3Nine** [comment]
any chance of getting any info on the time frame for this to be added?  It's literally the only caveat to making the switch to medusa from the other fork. :)

**Comment by labrys** [comment]
Added to master feature request list #282 - discussion for feature will continue here even though issue is closed.

**Comment by p0psicles** [comment]
Currently in develop.
