### ISSUE TITLE
Convert "scene" exceptions to name exceptions

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#2353]
Ref: https://github.com/pymedusa/Medusa/pull/2288#discussion_r104553867

**Comment by phraymond** [comment]
Not sure where to ask but this appears to be relevant - where do I report a show that is numbered differently across all of the indexers but is not set up on XEM? http://thexem.de/xem/show/1257 is the specific show and this thing is all over the board. Thanks.

**Comment by OmgImAlexis** [comment]
You'll need to get the show added to xem. Join #xem on irc.freenode.net and they should be able to get it added if you don't have an account.
