### ISSUE TITLE
Warning log keeps refreshing all the time

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2363]
When I'm going into logs : 
The UI keeps refreshing all the time...
![](http://i.imgur.com/pob2NsV.png)
![](http://i.imgur.com/56dNwfx.png)
![](http://i.imgur.com/MHVi3Hk.png)

**Comment by IDerr** [comment]
The UI keeps refreshing but I managed to cancel loading at the right time 👍 
![](http://i.imgur.com/hAv4oiW.png)

**Comment by fernandog** [comment]
@IDerr master right?

**Comment by IDerr** [comment]
yes, sure 
![](http://i.imgur.com/aZjMiyp.png)

**Comment by fernandog** [comment]
Duplicate: https://github.com/pymedusa/Medusa/issues/2336

**Comment by fernandog** [comment]
Fixed
