### ISSUE TITLE
view warnings

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#2379]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** current dev branch
**OS:** windows 10
**What you did:** clicked on view warnings
**What happened:**
**What you expected:** not wrap the bottom
**Logs:**
```
PASTE LOGS HERE
```
![view warnings](https://cloud.githubusercontent.com/assets/7034303/23800514/a92da250-057a-11e7-8c87-b66d4f9fbf12.png)
  when under view logs it is  fine.
![log file ok](https://cloud.githubusercontent.com/assets/7034303/23800600/06160584-057b-11e7-9430-9ccd0c5edce5.png)

**Comment by fernandog** [comment]
No idea what causes this

@Thraxis would you please check this?

**Comment by ripper1967** [comment]
@ fernandog  I think you may have fixed this i was one commit behind  when i updated it seem to fix it but i accidently hit clear warnings so i cant click on it anymore  but i need it to create an warning first

**Comment by ripper1967** [comment]
nope its stilll there

**Comment by OmgImAlexis** [comment]
@fernandog I'm guessing it may be something like the js refreshing bug but with an unescaped/unclosed `<div>` or `<pre>` tag.

**Comment by fernandog** [comment]
can't figure out the reason

**Comment by fernandog** [comment]
@p0psicles @Thraxis 
I think i know why this is happening:

Because of this: ` (read timeout=<object object at 0x76dbf4a8>)'`

```
2017-03-13 18:02:49 WARNING  SHOWUPDATER :: [b0ccb37] Problem running show_updater, Indexer TVDBv2 seems to be having connectivity issues while trying to look for show updates on show: American Horror Story
2017-03-13 18:04:52 WARNING  SHOWUPDATER :: [b0ccb37] could not authenticate to the indexer TheTvdb.com, with reason 'HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=<object object at 0x76dbf4a8>)'.
```

**Comment by fernandog** [comment]
@ripper1967 please update
