### ISSUE TITLE
add recomended shows imdbs popular

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#2427]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**  current dev
**OS:**Windows 10
**What you did:**
**What happened:**
**What you expected:**
**Logs:**
```
PASTE LOGS HERE
```
![add recomebded shows](https://cloud.githubusercontent.com/assets/7034303/24073979/fdbfe9ec-0bd6-11e7-93dc-ba15cc7e71d7.png)

**Comment by fernandog** [comment]
@duramato can you help here?

recommendations\imdb.py:
```python
        soup = BeautifulSoup(response.text, 'html5lib')
        results = soup.find('div', class_='lister-list')
        rows = results.find_all('div', class_='lister-item mode-advanced')
```

results is None causing the issue. Maybe class got renamed or else

https://gist.github.com/fernandog/6e5a9dc901d23464dd4e5478986449ce

**Comment by duramato** [comment]
I can try and make this use  imdbpie

**Comment by fernandog** [comment]
@ripper1967 please update
