### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#2431]
This is a partial list of issues to make Medusa Python 3 compatible

#### Incompatible libs:
1. `adba` resolved with #2439
1. `bencode`
1. `feedparser`
1. `github`
1. `jsonrpclib`
1. `libgrowl`
1. `pythontwitter`
1. `unrar2`
1. `shutil_custom` -> `copyfile_custom() got an unexpected keyword argument 'follow_symlinks'`

#### Medusa Issues:
1. `__main__.py` in py 3.0-3.3 `reload` is `imp.reload` in py3.4+ its `importlib.reload`
1. `__main__.py` no `sys.setdefaultencoding` in py3
1. `common.split_composite_status` sorts `Quality.qualityStrings.keys()` but `None` can not compare < to `int`
1. `databases.main_db` can't compare equality of tuple and int
1. `helpers.__init__.py` import `itertools.izip` is `zip` in py3
1. `helpers.__init__.py` import `contextlib2` is `contextlib` in py3
1. `history.py` invalid relative import `import db`
1. `indexers.indexer_ui` print statements without parentheses
1. `indexers.indexer_ui` invalid relative import `from indexer_exceptions import IndexerUserAbort`
1. `init.filesystem.make_closure` breaks `ntpath.dirname` with `TypeError: 'map' object is not subscriptable`
1. `init.logconfig.StyleAdapter` uses deprecated `getargparse` 
1. `network_timezones.py` invalid relative import `from app import BASE_PYMEDUSA_URL`
1. `show_updater.py` invalid relative import `import app`
1. `torrent_checker.py` invalid relative import `import app`
1. `version_checker.GitUpdateManager._run_git` returns bytes instead of unicode for first arg
1. `ex` returns bytes in py3
1. SQL keys should not be bytes in py3 so all the` b''` need to be replaced

**Comment by ratoaq2** [comment]
From the top of my head:

Medusa issues:
1. It shouldn't be called when in  py3
2. As above
10. Init  filesystem should only happen in  py2

About the libs, let's start replacing them?

**Comment by labrys** [comment]
Most libs should be fairly quick compatibility fixes that could be pushed upstream.  As for most of the others they are quick fixes too, although Im sure thats not the end of the issues.  #16 is probably going to be the biggest pain so far, but this list is far from complete.

**Comment by medariox** [comment]
```PyGithub``` should actually be compatible with Python 3: https://github.com/PyGithub/PyGithub#pygithub

I will replace ```unrar2``` with ```rarfile``` (py3 compatible) _soon_.
