### ISSUE TITLE
[ FEATURE ] Better layout in dropdown(select) box on displayShow

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2436]
it would be nice to change current dropdown for changing selected episodes to a more readable list since it's quite a long list.

![image](https://cloud.githubusercontent.com/assets/13415240/24090926/cf3b784c-0d44-11e7-8582-49800395daab.png)

into something like:
https://jsfiddle.net/whk5f5gx/

using bootstrap-ish solutions in the future will also allow us to use icons in dropdown select boxes as well.

**Comment by labrys** [comment]
This would make the list more readable, but if we split it into two drop-downs, one for status and one for quality it would improve it even more imo.

**Comment by OmgImAlexis** [comment]
That'd help a lot as we could allow users to change from snatched to downloaded or downloaded to archived without selecting the quality. We'd take the quality(WEB-DL, etc.) of the last status and add it to the new one.

This would help with archiving whole seasons that have different qualities.

**Comment by labrys** [comment]
Added to master feature request list #282 - discussion for feature will continue here even though issue is closed.
