### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: ITV Encore

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2441]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.6`
**Commit**: pymedusa/Medusa@cd1033afc5a6486fe41534d230150899df9d3062
**Link to Log**: https://gist.github.com/256e4f25b856ffb4fb71a9e3c41da52e
### ERROR
<pre>
2017-03-21 13:42:22 ERROR    Thread-33 :: [cd1033a] Missing time zone for network: ITV Encore
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@YogSottot can you add it please?

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/f0032ca6fab4816651a6f959040dec0b
### ERROR
<pre>
2017-04-20 08:57:33 ERROR    Thread-20 :: [a011615] Missing time zone for network: ITV Encore
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
> Missing time zone for network: ITV Encore

Already present in the https://github.com/pymedusa/medusa.github.io/blob/master/static/sb_network_timezones/network_timezones.txt
