### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: VICELAND

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2442]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.6`
**Commit**: pymedusa/Medusa@cd1033afc5a6486fe41534d230150899df9d3062
**Link to Log**: https://gist.github.com/b1aa47c2281fcadd73ed8c5b76b36cbf
### ERROR
<pre>
2017-03-21 13:42:22 ERROR    Thread-33 :: [cd1033a] Missing time zone for network: VICELAND
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@YogSottot can you add it please?
