### ISSUE TITLE
Make Medusa clean again! 

### ISSUE THREAD

**Issue by hagabla** [pymedusa/Medusa#2454]
I would kindly request an option to disable the random TVshow artwork on almost every page for several reasons:

* colours of the background, due to randomness, often clash with foreground colours
* it is distracting
* often looks bad
* colours are unevenly spread out over the page which draws attention to the background instead of to the foreground
* when scrolling through the page differently coloured background shines through the gaps between the items, for example on the schedule page with banner format, when scrolling different background colours, depending on randomness, shines through and irritate me
* it just looks unclean
* too much noise on the page
* fonts are sometimes, depending on randomness, very hard to read. (black font, black background ...)

A simple checkbox to disable loading of the artwork would go along way, or drop it all together since it goes against every design guideline ever invented in the whole multiverse :/

**Comment by Thraxis** [comment]
There is already an option to disable fanart in the config

**Comment by hagabla** [comment]
Thats embarrassing, i totally missed that.
So much better now!
