### ISSUE TITLE
T411 change url

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2482]
The url for the T411 api changed : 

https://api.t411.li/ => https://api.t411.ai/

Thanks

**Comment by fernandog** [comment]
@duramato ok?

**Comment by sebastientinel** [comment]
I confirm the change of TLD, it seems they won't go back to the previous one.

**Comment by fernandog** [comment]
@sebastientinel is there any announce about it?

**Comment by sebastientinel** [comment]
Yes, they announce it on the home page of the site here is a screenshot http://imgur.com/a/zhuIG

Let me know if you need a translation.

Thanks
