### ISSUE TITLE
[APP SUBMITTED]: KeyError: 12

### ISSUE THREAD

**Issue by Ic3Nine** [pymedusa/Medusa#2483]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.8.0-41-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.6`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/0ba8ca60bc37184499b5e3e32d4c46ec
### ERROR
<pre>
2017-03-27 20:29:47 ERROR    MAIN :: [a011615] There was an error creating the show in /tv/TV/The Zoo (2017): Exception generated: 12
Traceback (most recent call last):
  File "/app/medusa/medusa/__main__.py", line 1991, in load_shows_from_db
    cur_show = Series(sql_show[b'indexer'], sql_show[b'indexer_id'])
  File "/app/medusa/medusa/tv/series.py", line 154, in __init__
    self._load_from_db()
  File "/app/medusa/medusa/tv/series.py", line 1174, in _load_from_db
    self._load_externals_from_db()
  File "/app/medusa/medusa/tv/series.py", line 909, in _load_externals_from_db
    self.externals[mappings[result[2]]] = result[3]
KeyError: 12
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
Did you switched to develop then back to master?

**Comment by Ic3Nine** [comment]
hi fernando, i was on develop due to thraxis' docker
i just switched over to linuxserver docker (which is master).  Kept the settings,  should i do a fresh install?  i did delete the cache.db and cache dir

**Comment by fernandog** [comment]
@Ic3Nine 
do you have sqlite3 installed?

~$ sqlite3
SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open main.db
sqlite> DELETE FROM indexer_mapping where mindexer=12;
sqlite> .quit

**Comment by Ic3Nine** [comment]
thanks fernando, 
i ended up just deleting everything but the config.ini.  I was getting some error trying to open the main.db file. i was able to add the show.
