### ISSUE TITLE
Scheduled episodes going straight from Unaired to Skipped status

### ISSUE THREAD

**Issue by Arathen** [pymedusa/Medusa#2489]
The title pretty much says it all. I have a bunch of shows queued up in Medusa with future episodes automagically set to "Unaired". At some point (i'm not sure when, because even after the episode airtime passes, shows still seem to be in an Unaired status, and this may be a related or unrelated issue) those shows update in the schedule and instead of becoming "Wanted", they become "Skipped" instead. As such, they don't download as they're supposed to.

Manually setting them to "Wanted" results in a normal snatch.

Branch: master
Commit: a0116154f262786d6f5274459cb8f9cdb23012cc
OS: Linux armhf

**Comment by fernandog** [comment]
@Arathen open show page, what is in "Default episode status" ?

**Comment by labrys** [comment]
Go to `Manage -> Mass Edit` and check your default episode status for all series

**Comment by Arathen** [comment]
Ok... Default Episode Status was set to Skipped for everything, so i've fixed that. Is that the default setting?

Thanks heaps for the help :)

**Comment by fernandog** [comment]
Its set when you add shows. Maybe you missed the setting
