### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Watch Disney Channel

### ISSUE THREAD

**Issue by Ic3Nine** [pymedusa/Medusa#2490]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.8.0-41-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/3f3e42fb4d609d274795e5d5d9cf8be1
### ERROR
<pre>
2017-03-28 23:52:28 ERROR    Thread-21 :: [a011615] Missing time zone for network: Watch Disney Channel
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@YogSottot

**Comment by YogSottot** [comment]
@fernandog fixed

**Comment by fernandog** [comment]
@YogSottot thanks again!
