### ISSUE TITLE
Guide for installing when having SSL errors incorrect url to ez_setup.py

### ISSUE THREAD

**Issue by ArmandH** [pymedusa/Medusa#2565]
Hi,

I was following your guide to upgrade python but the provided url is not correct anymore to get the ez_setup.py please update.

I used https://bootstrap.pypa.io/ez_setup.py to get the ez_setup.py which worked fine.

Thanks

**Comment by fernandog** [comment]
@Thraxis @OmgImAlexis any idea?

**Comment by OmgImAlexis** [comment]
[Updated the wiki](https://github.com/pymedusa/Medusa/wiki/SSL-Errors/_compare/2010cbcf52c587adb7b6364a68f4a30efed5df4a...0a990b11a33d53509dc078e81218bbf692a27bf1) with the new URL, they just moved from Bitbucket to Github so the new link is `https://raw.githubusercontent.com/pypa/setuptools/bootstrap/ez_setup.py`.
