### ISSUE TITLE
T411 url

### ISSUE THREAD

**Issue by FireBladeNooT** [pymedusa/Medusa#2575]
Hello,
Just a change request for url of T411 which change from www.t411.li to www.t411.ai

Thks

**Comment by NicoLeOca** [comment]
@FireBladeNooT 
It is fixed in the develop branch.
You can safely switch to this branch, most of us use it everyday

@fernandog 
Any plan to merge dev into master?
Or at least this commit:
https://github.com/pymedusa/Medusa/commit/3ab8c86fec6c9f3ba3ae642ecbe62464ba88de26

**Comment by labrys** [comment]
@NicoLeOca yes we're finalizing some commits before releasing.

**Comment by fernandog** [comment]
t411 api is down

More info here: https://github.com/pymedusa/Medusa/issues/2160#issuecomment-291990971
