### ISSUE TITLE
Tablesort filtering not working

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2587]
If i add `!SDTV and !Unknown` it becomes `!SDTV%20and%20!Unknown` after reload

![image](https://cloud.githubusercontent.com/assets/2620870/24974978/6f618b74-1f9a-11e7-9526-5940121c49cd.png)

ping @Thraxis @OmgImAlexis

**Comment by fernandog** [comment]
@Thraxis please? no idea how to fix this

**Comment by OmgImAlexis** [comment]
I've looked into it and I think it's where tablesorter saves the input into local storage. When the page loads again and it pulls the string back out it doesn't url decode it.

@motti

**Comment by Mottie** [comment]
Hi everyone!

This was a known bug that was [fixed in v2.27.3](https://github.com/Mottie/tablesorter/issues/1237). It looks like [Medusa is still using v2.24.5](https://github.com/pymedusa/Medusa/blob/master/.build/bower.json#L22).

The current version is 2.28.7, but I plan to release 2.28.8 soon.

**Comment by fernandog** [comment]
@Mottie hey, thanks. soon like next month or next few days?

We are about to release a new version in the next days that's why I'm asking

**Comment by Mottie** [comment]
Well, I *could* push a new release today, but I was waiting to see if I could fix https://github.com/Mottie/tablesorter/issues/1384 first.... it's been a while, so maybe I'll just release and not wait for a response.

**Comment by fernandog** [comment]
@Mottie don't rush. We plan to release on sunday.

**Comment by Mottie** [comment]
Hehe, I released 2.28.8 yesterday 😋
