### ISSUE TITLE
Duplication episodes 

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2590]
I saw on one piece that there's a duplication on episodes
![](http://i.imgur.com/8KFFswX.jpg)

![](http://i.imgur.com/8m6DvzL.png)

Only 33 episodes on season 18 but 37 on medusa.
I think, they moved 4 episodes on the season 19.
The db was not updated on medusa

Thanks for all :)

**Comment by fernandog** [comment]
Force full update on this show

**Comment by IDerr** [comment]
Still not good.
![](http://i.imgur.com/DGPzUvc.png)

I'll delete them and redownload them, I think

**Comment by fernandog** [comment]
Full update should fix it

**Comment by IDerr** [comment]
I have done a full update before posting the screen, you can see the absolute value has changed.

It's still on the screen because the files are on the wrong folder :D
