### ISSUE TITLE
Reverse-proxying on Apache 2.4 not working (urlbase issue)

### ISSUE THREAD

**Issue by absinthewww** [pymedusa/Medusa#2595]
**Branch/Commit:**
master/`9503765`
**OS:**
Debian 8 'jessie' 
**What you did:**
Setup a reverse proxy on **Apache 2.4**, to access **Medusa** via HTTP on port `http://localhost:8082` on `https://my_domain.com/medusa`
**What happened:**
The URL changes from `https://my_domain.com/medusa` to `https://my_domain.com/login...`
**What you expected:**
The URL should change to `https://my_domain.com/medusa/login...`
**Logs:**
NA

**Comments**
I assume this is because there is no option to specify a `urlbase` in **Medusa**'s config - I have the same setup on **CouchPotato**, where the same issue happened until I specified `/couchpotato` in the `urlbase` section of the **CouchPotato** config.

I tried to see if anyone else has the same issue while reverse-proxying, but it seems like everyone just uses **nginx** and does not run into this problem - I would like to use **Apache 2.4** for this.

**Comment by p0psicles** [comment]
You'll find this option in the config.ini settings file.

For ex:
![image](https://cloud.githubusercontent.com/assets/1331394/25062745/9f0e6344-21d2-11e7-88df-71d4a6db42b6.png)

**Comment by absinthewww** [comment]
Should I put in a feature request instead to allow this to be configured
from the Web UI?

On 15 Apr. 2017 19:57, "p0ps" <notifications@github.com> wrote:

You'll find this option in the config.ini settings file.

For ex:
[image: image]
<https://cloud.githubusercontent.com/assets/1331394/25062745/9f0e6344-21d2-11e7-88df-71d4a6db42b6.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pymedusa/Medusa/issues/2595#issuecomment-294283665>,
or mute
the thread

**Comment by medariox** [comment]
The option is there, but it's not configurable from the UI (for some mysterious reason). Make sure Medusa is shut down, open config.ini and set the ```web_root``` to e.g. ```"medusa"```.

**Comment by p0psicles** [comment]
I'm also not sure why it's not in the ui. Maybe it's because users who configure reverse proxy, need to dive in their command line any way. You can request for it as a feature request.

**Comment by OmgImAlexis** [comment]
It's not in the UI as it'll most likely fuck things up without a restart so it was never added. It's also likely to be changed by people that don't know what they're doing meaning we end up with users saying "Medusa broke and it totally wasn't out fault, now fix it" so it's best to just leave it as is.

**Comment by absinthewww** [comment]
Why don't you take the approach CouchPotato does and have it in an advanced
section that must be toggled on explicitly to access it, with a warning of
possible breakage?

**Comment by OmgImAlexis** [comment]
We don't have anything in the UI like what CouchPotato does and adding something like that wouldn't be quick, for now the config file is fine. We may look into adding it in later on once we redo the UI.
