### ISSUE TITLE
Plot information not showing (API v2)

### ISSUE THREAD

**Issue by medariox** [pymedusa/Medusa#2600]
![404](https://snapr.pw/i/c734f6177e.png)

![log](https://snapr.pw/i/3a7a146873.png)

![req](https://snapr.pw/i/da51d75987.png)

![err](https://snapr.pw/i/7c6b735b1c.png)

- Restarting does nothing.
- After a "Force Full Update" it works again (temporarily) for the updated show.
- Restarting Medusa causes the "updated" shows (see above) to lose the plot information again.
- Using "Re-scan files" makes it work again only for shows that are "Downloaded" (also lost on reboot).

**Comment by fernandog** [comment]
tested with several episodes of some shows, all good
Looks a issue in show and not in api v2

**Comment by medariox** [comment]
Happens to all shows and it was also confirmed by @OmgImAlexis

**Comment by fernandog** [comment]
Show 1:
![image](https://cloud.githubusercontent.com/assets/2620870/25088693/9615b670-234e-11e7-8d54-d252a10bd272.png)

Show 2:
![image](https://cloud.githubusercontent.com/assets/2620870/25088712/abf17862-234e-11e7-8441-1ab508e09f98.png)

Show 3:
![image](https://cloud.githubusercontent.com/assets/2620870/25088723/c3854594-234e-11e7-9bf5-dc9cd9226d20.png)

**Comment by fernandog** [comment]
btw all my shows are normal shows. not anime or sports or air-by-date

**Comment by OmgImAlexis** [comment]
@fernandog it only happens with an old DB after updating to the latest dev. Happened with both my local and remote installs.

**Comment by fernandog** [comment]
@OmgImAlexis what do you mean by old DB? the api didn't upgrade the DB

**Comment by OmgImAlexis** [comment]
A DB that was setup before the latest update. I'm guessing it's a cache issue somewhere along the lines. I have a feeling on first `GET` for the endpoint Medusa is still downloading TVDB info and after a few minutes Medusa then has it and all if fine. That's how @medariox and I saw it as we checked right when we first booted Medusa.

**Comment by fernandog** [comment]
that errors points to "episode not found" as it can't create the episode object using database. That's why i said its related to the show, not the api v2 call.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/2601
