### ISSUE TITLE
[APP SUBMITTED]: WindowsError: [Error 2] Le fichier spécifié est introuvable: 'C:\\Users\\**********\\Downloads\\AutoDL\\Deluge Seedbox\\Taboo.UK.S01.1080p.BluRay.x264-SHORTBREHD[rartv]\\Taboo.UK.S01E02.1080p.BluRay.x264-SHORTBREHD.en.srt'

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#2606]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@33c3a5a735663342a33c6b5f04d665c34aa5006f
**Link to Log**: https://gist.github.com/1f13d72302c18f1021aec36f0c27e9d6
### ERROR
<pre>
2017-04-18 22:28:34 ERROR    Thread-36 :: [33c3a5a] Unable to move file C:\Users\**********\Downloads\AutoDL\Deluge Seedbox\Taboo.UK.S01.1080p.BluRay.x264-SHORTBREHD[rartv]\Taboo.UK.S01E02.1080p.BluRay.x264-SHORTBREHD.en.srt to Z:\Series\Taboo (2017)\Season 01\Taboo.2017.S01E02.1080p.BluRay.x264-SHORTBREHD.en.srt: WindowsError(2, 'Le fichier sp\xe9cifi\xe9 est introuvable')
Traceback (most recent call last):
  File "C:\Medusa\medusa\post_processor.py", line 454, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "C:\Medusa\medusa\helpers\__init__.py", line 313, in move_file
    os.unlink(src_file)
  File "C:\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
WindowsError: [Error 2] Le fichier spécifié est introuvable: 'C:\\Users\\**********\\Downloads\\AutoDL\\Deluge Seedbox\\Taboo.UK.S01.1080p.BluRay.x264-SHORTBREHD[rartv]\\Taboo.UK.S01E02.1080p.BluRay.x264-SHORTBREHD.en.srt'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by NicoLeOca** [comment]
"Le fichier spécifié est introuvable" means that the file can't be found.
Though I wonder why, can you help me to clarify please?

**Comment by fernandog** [comment]
maybe i was already processed. can you confirm?

**Comment by fernandog** [comment]
@medariox as we are raising a PP exception, it shouldn't show the traceback. any idea why this is happening?

**Comment by NicoLeOca** [comment]
@fernandog that's most likely the reason.
why does it occur though?
Medusa PP a file and just 2 seconds later tells that it can't as the file is not available.
that's not really accurate

**Comment by medariox** [comment]
@NicoLeOca 
Did it happen again? It seems to be a very rare situation. If you have any hints on how to reproduce this, it would be a first step.

**Comment by NicoLeOca** [comment]
it is rare indeed
I wonder if it happens when a manual PP is launched and an automatic PP starts at nearly the same time

Le 8 mai 2017 à 14:08, Dario <notifications@github.com<mailto:notifications@github.com>> a écrit :


@NicoLeOca<https://github.com/NicoLeOca>
Did it happen again? It seems to be a very rare situation. If you have any hints on how to reproduce this, it would be a first step.

**Comment by medariox** [comment]
@NicoLeOca 
Yes, that can indeed be the case. We need shouldn't allow manual post-processing while the auto is running.
