### ISSUE TITLE
Created tvshow.nfo has wrong episode guide url

### ISSUE THREAD

**Issue by bnevets27** [pymedusa/Medusa#2608]
Example of url medusa produces in the tvshow.nfo:
https://api.thetvdb.com271546/all/en.zip

Working url:
http://thetvdb.com/api/F9C450E78D99172E/series/271546/all/en.zip

Expected outcome: Have kodi read the tvshow.nfo properly

**Comment by fernandog** [comment]
@p0psicles missing slash after `.com` and `271546` ?

**Comment by bnevets27** [comment]
It's more then that. You can just copy paste into browser address bar. 
This does not work:
https://api.thetvdb.com/271546/all/en.zip

Looks like a JWT token is needed
https://api.thetvdb.com/swagger#/

Not that I have any idea what I'm talking about

**Comment by p0psicles** [comment]
I'm not even sure if the new api provides this endpoint. It would not be a first that tvdb would remove a feature in the new api.

**Comment by p0psicles** [comment]
Apparently others have also faced this issue.
https://www.filebot.net/forums/viewtopic.php?t=3964

The <episodeguide> element, requires the link https://api.thetvdb.com/271546/all/en.zip, to be able to lookup the detailed episode information.

Kodi documentation is also still refering to tvdb api v1.
http://kodi.wiki/view/Add-on:The_TVDB
