### ISSUE TITLE
Privacy setting note doesn't match the options in the listbox

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2612]
Also afaik we could change it without restart just like enabling subliminal/tornado logs:
```python
# Reconfigure the logger
logger.reconfigure()
```

![image](https://cloud.githubusercontent.com/assets/2620870/25197823/c3f0c28c-251b-11e7-8370-b96d6ab53b1d.png)

**Comment by fernandog** [comment]
in common we have a lot more levels (and no docs about what they mean)

```python
privacy_levels = {
    'absurd': 9002,
    'stupid': 9001,  # it's over 9000!
    'max': 9000,
    'high': 30,
    'normal': 20,
    'low': 10,
    'disabled': 0
}
```

in mako we have only: 
```mako
% for privacy_level in ['high', 'normal', 'low', ]:
```

and somehow even we reconfigure log in save_general, changing levels doesn't apply to logs
I tested doing manual searches and checking if user and password appear in the provider URLS

**Comment by fernandog** [comment]
https://github.com/pymedusa/Medusa/pull/494#issuecomment-220771599

**Comment by labrys** [comment]
The other levels were undocumented for a reason.  `disabled` is for dev usage only.  `stupid` was a test for excessive censoring, and `absurd` was a joke level that censored absolutely everything, so I'm not surprised that that breaks the logger.

**Comment by fernandog** [comment]
_`disabled` is for dev usage only._

![image](https://cloud.githubusercontent.com/assets/2620870/25206269/48235b66-253d-11e7-9b1c-025ebc01ad2e.png)

**Comment by labrys** [comment]
Yes it was discussed in IRC to make it unavailable.  After the feature was coded, the UI was then updated with commit f98245b.  The note should never have been in the UI.

**Comment by labrys** [comment]
No need to assign him, just remove the warning.  The decision in IRC to not enable it in the UI was that if a user wants to make a dangerous change like that then they can manually edit the config.  If the teams wants to allow users to disable censoring, my recommendation is to then prevent auto-reporting of issues while disabled.
