### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: HBO Nordic

### ISSUE THREAD

**Issue by phraymond** [pymedusa/Medusa#2620]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/85d59394a28cb4e661dd0926705844fa
### ERROR
<pre>
2017-04-20 08:57:34 ERROR    Thread-20 :: [a011615] Missing time zone for network: HBO Nordic
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@190e9e9412662518822cbe696734cb67bd9ab6a2
**Link to Log**: https://gist.github.com/19a5ea52e21283e8edd33953fbfaee09
### ERROR
<pre>
2017-04-20 20:56:47 ERROR    Thread-23 :: [190e9e9] Missing time zone for network: HBO Go
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
> HBO Nordic

https://github.com/pymedusa/medusa.github.io/blob/master/static/sb_network_timezones/network_timezones.txt#L894
