### ISSUE TITLE
[ FEATURE ] Update episode nfo and maintain Kodi watched status.

### ISSUE THREAD

**Issue by bnevets27** [pymedusa/Medusa#2646]
Update episode nfo/kodi and maintain watched status.
This would use the info from the Kodi watched status feature when it's completed.

Problem this solves:
When episodes are scanned into kodi or the nfo's are created by medusa sometimes the episode overview doesn't exist yet on thetvdb and therefore the episode overview is blank in the nfo and in kodi.

The episode overview eventually gets added to thetvdb but the nfo and kodi doesn't get updated with the new episode overview.

If medusa could periodically update the nfo then tell kodi to update the show it should then update the episode with the episode overview. With the addition of the watched status feature, medusa can write the nfo to include the watch status.

Without adding the watched status to the nfo, the episode will get marked as unwatched if its refreshed in kodi.

So quick review of what medusa will do.
-nfo/kodi has missing episode overview
-Medusa overwrites the nfo with new episode overview and kodi watched status
-Medusa tells kodi to update the show forcing it to read the updated nfo
-nfo/kodi now has episode overview and watched status

Will require this feature to be completed first.
Kodi Watched Status (bi-directionnal)
http://feathub.com/SickRage/SickRage/+45

**Comment by fernandog** [comment]
Why dont you let Kodi handle the nfo?
Use are using medusa only to automate nfo update.
Makes no sense to me

Check kodi addons that updates .nfo

**Comment by bnevets27** [comment]
I thought that might come up. Thing is there is nothing for kodi that actually does that.

I've asked this on the kodi forums in previous years and again recently, there is no way mentioned to do what I asked in the feature request.
http://forum.kodi.tv/showthread.php?tid=312747

Been using kodi/xbmc since v1 and this wasn't really an issue until automation came along due to the fact that episodes are now released quicker then the episode summary is being created on thetvdb.

Kodi only reads the nfo the first time it sees a new file. Changing the nfo after that has no effect on the kodi db unless a refresh is done on that (or all) episodes which results in the watch status being lost.

I definitely won't be using medusa to just automate nfo updating. I use all of the many great features it has. (Manual search and preferred words are a great addition) 

Additionally this also keeps the nfo's useful/valid. Example:
You use the feature of medusa to create episode nfo's, over time nfo's get created with empty episode summaries. Now when you start a fresh install of kodi and kodi reads all the nfo's medusa created and kodi fills its db full of empty episode summaries.

So there is kind of two parts to this request. 
1) keep the nfo's up to date (or at least insure no blank episode summery, but I'm sure its easier to just replace the whole nfo)
2)keep the watched state in the nfo in synced with the kodi db (which will be possible with the kodi watched status feature request)

Once both of those are done fire off refresh for the episode and kodi will now load the episode summary and read the watched status from the nfo.

Of course like I mentioned in the request this will only be possible once the "Kodi Watched Status (bi-directionnal)" feature is implemented.

Make more sense? If there is something out there that can do this I would be more then happy to use it but I the 9 years of using kodi I haven't found anything to do so.

**Comment by OmgImAlexis** [comment]
This would also effect Plex and anything else that reads the nfo files. Maybe we should split this up into two requests and make it less directed at kodi and more about keeping nfo files up to date as well as updating media services like plex, emby, kodi, etc. when they're changed by Medusa.

**Comment by bnevets27** [comment]
Plex can't read nfo's by default. 
Plex can read nfo's if you install a third party agent. 

Emby looks like it reads nfo's and actually will reread them if the modified date changes. (from a quick Google search) which is a nice feature I didn't know about. 

Again from a quick search it looks like modifying the watch status (more correctly, the play count),  in the nfo file, will have no effect on the emby db unless the user has "sync user watched status" on. Which from what I can tell is syncing between kodi and emby and therefore I think would be compatible with what this feature would do. 

So it would seem it would be safe to implement without effecting other media centers.

**Comment by OmgImAlexis** [comment]
Plex definitely can and does read NFOs even by default as "local media" is by default set as the first media agent.

**Comment by bnevets27** [comment]
https://support.plex.tv/hc/en-us/articles/200220717-Local-Media-Assets-TV-Shows?

I don't see any reference to nfo files there. And there is a third party media agents called "XBMCnfoMoviesImporter" which is needed if you want plex to read nfo's.

**Comment by OmgImAlexis** [comment]
The docs are 100% out of date. Plex has had nfo support built into it since about a year ago. I've asked on the forums over and over to have the docs updated to reflect that and I always get "we'll pass the feedback onto someone and have to updated soon".

**Comment by bnevets27** [comment]
That sounds typical. Well I learned something new. Thanks. Could you post so info on it though. After googling for a while I get little info on that it's actually supported. Within the last year (some discussion within the last few months) I see most people still are using the xbmcnfo agent (which is still being developed which is confusing if the support is built in) to read nfo and only one or two references to plex being to read it by itself. Is there a changelog for plex with that added or something? 

I didn't realize plex was that bad with its documentation. 

Back on topic

**Comment by bnevets27** [comment]
Must of hit close by mistake

**Comment by OmgImAlexis** [comment]
Nope no issues just the feature when added to the change log will need to reflect the changes incase Plex does decide to start using more of the nfo info. For the moment it looks like it just reads the description, episode title, show title, etc. from it. Play count doesn't seem to be read in Plex.

The only documentation I can find is the fact that I know this is how it works on my server without changing anything from a default install.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
