### ISSUE TITLE
[ FEATURE ] Full show name in folder name (or option to customize)

### ISSUE THREAD

**Issue by phraymond** [pymedusa/Medusa#2659]
There are several shows, an example of one below, in which multiple shows have the same name but are differentiated by year and listed as such on the indexers. I would like to be able to customize the folder name, just like I can with episode names, so that they're in the format I prefer.

Admittedly, this wouldn't have been as big of an issue as it ended up being, had Medusa for some reason not read the tvshow.nfo files in over half of my library folders. Sigh. Thank you.

![2017-04-22 19_42_31-medusa - new show](https://cloud.githubusercontent.com/assets/1957542/25310201/fe576294-2793-11e7-9af6-30277f0c4a20.png)

**Comment by OmgImAlexis** [comment]
For now you can just edit the show's location and change the directory name.

**Comment by medariox** [comment]
If I understood this correctly, what you are looking for already exists - at least to some extent.

For instance, that's what I use:
![naming](https://snapr.pw/i/de45d62964.png)

What do you need and what do you feel is missing?

**Comment by phraymond** [comment]
Yes, which is what I did. Gets rather tedious when one is doing it for over 100 folders, though. Sigh. When I get back from my business trip I'll open a bug for it missing a whole slew of NFO files. I left quite a few in place for testing/reporting purposes. Thanks.

**Comment by labrys** [comment]
Odd I just rebuilt my library last week and out of >500 shows I only had 4 missed (2 were because I had duplicate folders for the same show).  What do you use for your `.nfo`s, medusa or an external program?

**Comment by phraymond** [comment]
SickRage for the last couple of years. I have almost 1500 shows and a
significant portion of them, over half, did not have the nfo files properly
read. I spent about two hours straight just clicking "add show" on the easy
ones. I deferred the harder ones (multiple options, such as the years
mentioned in this thread) for next weekend.

via Handheld, excuse typos

On Sun, Apr 23, 2017 at 7:31 AM, Labrys of Knossos <notifications@github.com

**Comment by labrys** [comment]
I have about the same number, I split mine into several diff libraries for convenience though.  If you could provide us some of the failed NFOs it would be appreciated :).

**Comment by phraymond** [comment]
Relatedly, when it started refreshing shows, it started trying to download
a whole slew of episodes - in the 100s, and it was only through a couple
dozen shows. I disabled the torrent provider on my way out the door,
figured I'd deal with it when I get back. I'm not sure if it's a bug or a
feature, but I had previous aired episodes set to "Skipped" so I was quite
surprised when it tried to update existing SD episodes to HD and to look
for missing episodes! My assumption was that setting everything in the past
to skip would make it ignore all prior and just look forward, as future
episodes are set to wanted. I certainly don't want to download literally
1000s of episodes at once, especially when I'm away!


via Handheld, excuse typos

**Comment by phraymond** [comment]
I thought you might ask that so I tossed some into my dropbox just in case
you asked. Hopefully they'll come through this email response. And yeah,
all of mine are in one root called "tv".

via Handheld, excuse typos

**Comment by phraymond** [comment]
[showsampls.zip](https://github.com/pymedusa/Medusa/files/949807/showsampls.zip)

**Comment by labrys** [comment]
Could you also provide the folder names for those shows?  It should prefer nfo contents over folder name, but just in case.

**Comment by phraymond** [comment]
Folder names match show titles exactly.

via Handheld, excuse typos

**Comment by phraymond** [comment]
I'm back home and able to move forward with this. I have about 130 shows with unrecognized NFO files left at this point. Thanks.

**Comment by phraymond** [comment]
See if this is helpful in troubleshooting, please. Here's what I've done:

1. Set Medusa to debug logging at approximately "2017-04-29 09:51:46"
2. Ran Add Shows, Add Existing Shows
3. Selected three shows that have "?" for Show Name (Sidenote - why aren't these alphabetized? See screenshot)
4. Pulled all supporting files from the three shows ("before" folder in attached sample.zip)
5. Added each show "by hand" from the list (screenshots)
6. Checked status page to ensure processing was done
7. Checked show pages to ensure it was properly showing my downloaded files
8. Checked folders to verify that Medusa had created/updated the tvshow.nfo files
9. Noted that Medusa was once again trying to pull backlog files I was pretty sure I didn't want it to (Baby Daddy in the logs), cursed, and disabled search
10. Went and looked at settings for show. It's trying to find HD versions of SD downloads even though I had set status for previous episodes as "Skipped" when adding it as an existing show.
11. Turned off debug logging.
12. Grabbed a copy of config.ini, scrubbed it for username/passwords, added to zip file.
13. Pulled an "after" snapshot of the supporting files ("after" folder)
14. Uploaded sample.zip to this thread, in multiple files, after multiple attempts, cursing over github's limitations.
15. Profit. No, that's not quite it - wait patiently. That's it. :-)

Password is in your email, @labrys.

Thank you.

[sample001.zip](https://github.com/pymedusa/Medusa/files/966302/sample001.zip)
[sample002.zip](https://github.com/pymedusa/Medusa/files/966303/sample002.zip)
[sample003.zip](https://github.com/pymedusa/Medusa/files/966304/sample003.zip)
[sample004.zip](https://github.com/pymedusa/Medusa/files/966305/sample004.zip)

**Comment by phraymond** [comment]
Alternatively, with the same password: https://www.dropbox.com/s/dk8rn149237bl5d/sample.7z?dl=0

**Comment by labrys** [comment]
Sorry been busy lately and havent had a chance to look into this.

**Comment by phraymond** [comment]
No worries. Most of them are not currently airing and I'll just add the ones that are as new are available. I can let this sit until you're ready to do some testing.

**Comment by labrys** [comment]
Added to master feature request list #282 - discussion for feature will continue here even though issue is closed.

**Comment by phraymond** [comment]
Thank you on that one. As for medusa not recognizing a whole slew of tvshow.nfo files, are we continuing that here or should I open a separate bug report? Thanks.

**Comment by labrys** [comment]
I'll open it as a new issue with a reference to this thread.
