### ISSUE TITLE
[T411] :: [9c19b10] Unknown exception in url https://api.t411.ai/torrents/search/Homeland%20S06E03. Error: data must be a byte string

### ISSUE THREAD

**Issue by rdpdo** [pymedusa/Medusa#2661]
Hello,

I've got the same issue of : https://github.com/pymedusa/Medusa/issues/2117

But I cannot uninstal open-ssl because it will uninstall deluged ....

So I tried to upgrade to pyhton 2.7.13 but Medusa still display that I use python 2.7.9...

But when in type "python --version" i got 2.7.13... ?

Can someone can help me ?

Thanks !

**Comment by labrys** [comment]
What version of open-ssl do you have?  Maybe try updating it?

**Comment by medariox** [comment]
Make sure you are starting Medusa with the correct python version. You can check the version Medusa is using from Gear > Help & Info

**Comment by fernandog** [comment]
T411 is done
