### ISSUE TITLE
WEB.DL in file name gets Bluray flag

### ISSUE THREAD

**Issue by bnevets27** [pymedusa/Medusa#2679]
If %Q.N is used in post-processing or renaming and medusa reads the file name WEB.DL it will get flagged as Bluray.

%QN
which results in WEB-DL is correctly flagged as WEB-DL

Didn't experiment with:
%Q_N
%SQN
 %SQ.N
 %SQ_N

**Comment by OmgImAlexis** [comment]
Can you provide some examples of the actual file names there may be an issue with Guessit which we use to parse the filenames.

**Comment by bnevets27** [comment]
http://i.imgur.com/yrbR1Xj.jpg

I Removed the period from WED.DL and it gets flagged as WEB-DL.

**Comment by bnevets27** [comment]
Sorry, disregard I made a mistake
