### ISSUE TITLE
Missing time zone for network: Go90

### ISSUE THREAD

**Issue by phraymond** [pymedusa/Medusa#2680]
2017-04-29 11:34:41 ERROR    Thread-17 :: [9c19b10] Missing time zone for network: Go90

Show: http://thetvdb.com/?tab=series&id=322944

**Comment by medariox** [comment]
Added here: https://github.com/pymedusa/medusa.github.io/commit/e1603c783f793f825ca1991edd3492fbfb4a56a0

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@4ab1a97e5c7af0d79b11a660414c86676668a15c
**Link to Log**: https://gist.github.com/ddfe18b5662abf4cb8e09cb4ade9a8dd
### ERROR
<pre>
2017-09-26 09:51:49 ERROR    Thread-185 :: [4ab1a97] Missing time zone for network: Sky Go
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
