### ISSUE TITLE
Manual search on danishbits fails

### ISSUE THREAD

**Issue by OBenned** [pymedusa/Medusa#2682]
Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** Master
**OS:** DSM 6.1 Synology
**What you did:** I tried doing a manual search on the DanishBits tracker
**What happened:** It returned no results
**What you expected:** I expected it to return results, as i know there are hits on that tracker
**Logs:**
```
2017-04-30 10:33:37 ERROR    SEARCHQUEUE-MANUAL-247897 :: [Danishbits] :: [9c19b10] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/app/medusa/medusa/providers/torrent/html/danishbits.py", line 171, in parse\n    torrent_size = cells[labels.index(\'St\xc3\xb8rrelse\')].contents[0]\nValueError: u\'St\\xf8rrelse\' is not in list\n'
Traceback (most recent call last):
  File "/app/medusa/medusa/providers/torrent/html/danishbits.py", line 171, in parse
    torrent_size = cells[labels.index('Størrelse')].contents[0]
ValueError: u'St\xf8rrelse' is not in list
```

**Comment by duramato** [comment]
What is your​ locale set to? That's likely to be he problem

**Comment by OBenned** [comment]
Sorry i wasnt being very clear, been a long weekend :)

im running it in docker on a synology, ive just tried another cotainer, it has the same problem.

The first one i tried was alpine based and doesent have locale settings afaik.
The second one is arch based and here is the locale for that container:

LANG=en_GB.UTF-8                                                                                                                                                                                            
LC_CTYPE="en_GB.UTF-8"                                                                                                                                                                                      
LC_NUMERIC="en_GB.UTF-8"                                                                                                                                                                                    
LC_TIME="en_GB.UTF-8"                                                                                                                                                                                       
LC_COLLATE="en_GB.UTF-8"                                                                                                                                                                                    
LC_MONETARY="en_GB.UTF-8"                                                                                                                                                                                   
LC_MESSAGES="en_GB.UTF-8"                                                                                                                                                                                   
LC_PAPER="en_GB.UTF-8"                                                                                                                                                                                      
LC_NAME="en_GB.UTF-8"                                                                                                                                                                                       
LC_ADDRESS="en_GB.UTF-8"                                                                                                                                                                                    
LC_TELEPHONE="en_GB.UTF-8"                                                                                                                                                                                  
LC_MEASUREMENT="en_GB.UTF-8"                                                                                                                                                                                
LC_IDENTIFICATION="en_GB.UTF-8"                                                                                                                                                                             
LC_ALL=

I know that tracker has changed things in recent times as i were using sickrage before and they had to update the serach sickrage, after some column changes, but i dont know if thats the problem here

**Comment by duramato** [comment]
Can you try and set the LC_ALL? The parsing is working correctly.

**Comment by OBenned** [comment]
I added the LC_ALL as a variable to the container, but i still get the same error.

locale now outputs:

LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8

**Comment by medariox** [comment]
What's your locale in Medusa?

Gear > Help & Info
![config](https://snapr.pw/i/f3b604767b.png)

**Comment by OBenned** [comment]
@medariox 

This is what i get in medusa

![medusa](https://cloud.githubusercontent.com/assets/1587311/25584198/5daa2a3a-2e95-11e7-8fe6-1d86748b457c.PNG)

**Comment by medariox** [comment]
@OBenned Thank you. I opened a pull request that should fix your issue here: https://github.com/pymedusa/Medusa/pull/2684
It would be great if you could try it and report back.

**Comment by OBenned** [comment]
@medariox 

Unfortunately the container im using has no git installed so i manually edited the danishbits.py file.
Im still getting the same error:

```
2017-05-01 18:09:54 ERROR    SEARCHQUEUE-MANUAL-247897 :: [Danishbits] :: [9c19b10] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/opt/medusa/medusa/providers/torrent/html/danishbits.py", line 172, in parse\n    torrent_size = cells[labels.index(\'St\\xc3\\xb8rrelse\')].contents[0]\nValueError: u\'St\\xc3\\xb8rrelse\' is not in list\n'
Traceback (most recent call last):
  File "/opt/medusa/medusa/providers/torrent/html/danishbits.py", line 172, in parse
    torrent_size = cells[labels.index('St\xc3\xb8rrelse')].contents[0]
ValueError: u'St\xc3\xb8rrelse' is not in list
```

**Comment by medariox** [comment]
Oh, you changed the site language to English, right? That's the issue. Set it back to Danish and it will work again. Will try to have it working for both languages ASAP. Thanks for the bug report.

**Comment by OBenned** [comment]
I always had it at english, and you mean the the tracker site right? :)
Just tried switching it to danish, and the same issue is there

**Comment by medariox** [comment]
Yes. Please use the original code and try again with Danish. It should work.

**Comment by OBenned** [comment]
Ahhh, i see :)

**Comment by OBenned** [comment]
Confirmed working when switching to danish.

And thanks to all for nice job 👍
