### ISSUE TITLE
Support Horriblesubs

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2689]
Support HorribleSubs for Anime
http://horriblesubs.info/
RSS link :
http://horriblesubs.info/rss.php?res=all

**Comment by medariox** [comment]
Waiting approval: https://github.com/pymedusa/Medusa/pull/2693

**Comment by IDerr** [comment]
Thanks sir :D

**Comment by medariox** [comment]
Merged in develop.

**Comment by IDerr** [comment]
Thanks a lot
