### ISSUE TITLE
Not all NFOs recognized when adding existing series

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#2692]
Continuation from discussion in #2659

**Comment by phraymond** [comment]
Any progress on this? I still have quite a few left to add. Thank you.

**Comment by phraymond** [comment]
I noticed that my show updates had duplicates and the like in them. Theorizing that it was due to corruption thanks to the disk full/corrupt file system I had, I decided to rebuild it from scratch. That brought me back to this issue, of tvshow.nfo and series.xml not being properly read.

I did some digging and I think I found it. The ones that *aren't* recognized have this:
  <episodeguideurl>http://thetvdb.com/api/redacted/series/75805/all/en.zip</episodeguideurl>
  <id moviedb="imdb">75805</id>
  <tvdbid>75805</tvdbid>

The shows that *are* recognized have this:
  <episodeguide>
    <url cache="auth.json" post="yes">https://api.thetvdb.com/login?{"apikey":"redacted","id":75805}|Content-Type=application/json</url>
  </episodeguide>
  <mpaa>TV-MA</mpaa>
  <id>75805</id>

Perhaps this helps in troubleshooting this issue? 

Thanks.


Full files attached
[NOTWORKINGtvshow.nfo.txt](https://github.com/pymedusa/Medusa/files/1605038/NOTWORKINGtvshow.nfo.txt)
[WORKINGtvshow.nfo.txt](https://github.com/pymedusa/Medusa/files/1605044/WORKINGtvshow.nfo.txt)

**Comment by Santiagodraco** [comment]
This is an old one!   I was searching for a resolution to my issue and found this thread/issue.   I'm in the same boat as others in ths thread were back in 2017/18.   Tons of nfo files not being read in spite of them being complete and accurate.  Having to manually add/confirm hundreds of shows.

Is there a resolution to this?   It's been 2 years so I'm hopeful!

Thanks.

**Comment by p0psicles** [comment]
Can you share like ten of the nfo? I can take a look

**Comment by Santiagodraco** [comment]
Sure thing.  Just saw this.  Let me put some together and upload them.  Next day or so.

**Comment by Santiagodraco** [comment]
Here are 10 nfo files from shows that Medusa could not recognize but Sickchill did.  There are a few hundred like this.   

[tvshow.txt](https://github.com/pymedusa/Medusa/files/4285562/tvshow.txt)
[tvshow.txt](https://github.com/pymedusa/Medusa/files/4285565/tvshow.txt)
[tvshow.txt](https://github.com/pymedusa/Medusa/files/4285567/tvshow.txt)
[tvshow.txt](https://github.com/pymedusa/Medusa/files/4285571/tvshow.txt)
[tvshow.txt](https://github.com/pymedusa/Medusa/files/4285572/tvshow.txt)
[tvshow.txt](https://github.com/pymedusa/Medusa/files/4285573/tvshow.txt)
[tvshow.txt](https://github.com/pymedusa/Medusa/files/4285575/tvshow.txt)
[tvshow.txt](https://github.com/pymedusa/Medusa/files/4285577/tvshow.txt)
[tvshow.txt](https://github.com/pymedusa/Medusa/files/4285579/tvshow.txt)
[tvshow.txt](https://github.com/pymedusa/Medusa/files/4285581/tvshow.txt)

**Comment by p0psicles** [comment]
Ok the issue is, there are no episode detail URL. The url was the only thing we could use to know if it is tvdb, tvmaze or tmdb.

**Comment by Santiagodraco** [comment]
Ok.   Does that mean the issue is on my side or is this something you'll change/fix?   I'm confused why Sickchill picked all of them up but Medusa did not.   Thanks.

**Comment by p0psicles** [comment]
You could try to enable the creation of episode nfo / episode details.

It's very simple. Sickchill only has one indexer ( tvdb) we have three. So we need to know which indexer the show was added with.

**Comment by p0psicles** [comment]
We could do a workaround. Like if we can't detect an indexer, assume tvdb

**Comment by Santiagodraco** [comment]
Thanks for the response.  That explains the issue, makes sense.  A work around would be great.  I can look into how I can address it on my side but for sure it would be difficult ;)

**Comment by medariox** [comment]
Where are these nfo files coming from?<episodeguide> is actually a requirement if you want to use scrapers to update the information, the ID is not enough to identify the indexer. See: https://kodi.wiki/view/NFO_files/TV_shows

**Comment by Santiagodraco** [comment]
I'm using Media Center Master and SickChill (for now).   Any recommendations on a better alternative than MCM?  Thanks.

**Comment by Santiagodraco** [comment]
Giving tinyMediaManager a try.  I think it will create proper nfo files and hopefully that will resolve the issue.   

Still it may not be a bad idea to default to tvdb though if that info is missing.   But I'll see if this resolves my issue in the short term.  Thanks!

**Comment by Santiagodraco** [comment]
I reprocessed my entire TV library using tinyMediaManager and this helped considerably.   Thanks for the feedback in the issue.   I still ended up with about 70 shows unmatched but that was more an issue of them being obscure shows that needed direct matching.  Thanks again!
