### ISSUE TITLE
Support anidex.info

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2695]
Perhaps the next nyaa :D 

https://anidex.info/
RSS:
https://anidex.info/rss/cat/0

**Comment by medariox** [comment]
Waiting for approval: https://github.com/pymedusa/Medusa/pull/2700

**Comment by IDerr** [comment]
Thanks, for that, pretty reactive :D

**Comment by medariox** [comment]
Merged to develop, enjoy!

**Comment by IDerr** [comment]
Thanks for that :D

**Comment by IDerr** [comment]
I saw that Anidex has a working RSS, but in your commit I saw that you parse HTML.
Is it because of missing informations @medariox ?

It's just for curiosity.

Thanks a lot
