### ISSUE TITLE
"File exists and the new file has the same size, aborting post-processing"

### ISSUE THREAD

**Issue by phraymond** [pymedusa/Medusa#2697]
This happens to me from time to time, It'd be handy if I could set it so that when this happens, it deletes the new file, rather than aborting. Thank you.

**Comment by fernandog** [comment]
manual PP and use option:

`Mark Dir/Files as priority download`
(Check this to replace the file even if it exists at higher quality)

**Comment by phraymond** [comment]
I disagree that that's a solution to the issue at hand. Sure, it's a
workaround, but it's still more work on my part - I'd have to make sure
there are no lower quality files in the queue that would overwrite higher
quality ones already in the library.

**Comment by medariox** [comment]
Duplicate https://github.com/pymedusa/Medusa/issues/3252
