### ISSUE TITLE
delete nyaatorrents

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2702]
Nyaa is down forever

https://torrentfreak.com/anime-torrent-site-nyaa-goes-down-after-domain-name-deactivation-170502/
https://www.reddit.com/r/trackers/comments/68zyj4/update_nyaa_is_most_likely_gone_for_good/

**Comment by fernandog** [comment]
@p0psicles can we remove it?

**Comment by IDerr** [comment]
Never mind : 

https://nyaa.si/
