### ISSUE TITLE
Missing time zone for network: Starz

### ISSUE THREAD

**Issue by phraymond** [pymedusa/Medusa#2706]
2017-05-05 15:20:35 ERROR    DAILYSEARCHER :: [9c19b10] Missing time zone for network: Starz

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/c312a7b0ff3b673856a6de609d59a68dd1838136

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@2a21fd430ad688cd633f8929d2fb90cd78362e9e
**Link to Log**: https://gist.github.com/1c4e185b7309fd9c01fb7568d81c2c7c
### ERROR
<pre>
2017-06-01 16:26:11 ERROR    Thread-39 :: [2a21fd4] Missing time zone for network: ten
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
added https://github.com/pymedusa/medusa.github.io/pull/55

**Comment by jrozelle** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
**Link to Log**: https://gist.github.com/621def28ca6c647894076651300f4c9a
### ERROR
<pre>
2017-11-09 17:39:42 ERROR    Thread-16 :: [b16e0e5] Missing time zone for network: Starz!
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bentux** [comment]
### INFO
**Python Version**: `2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]`
**Operating System**: `Linux-3.13.0-141-generic-x86_64-with-Ubuntu-14.04-trusty`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `43.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/917b0a69fb4b4327d4bfdb81f637f962
### ERROR
<pre>
2018-02-20 23:51:56 ERROR    Thread-17 :: [ccbc0ce] Missing time zone for network: CBS
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
CBS:US/Eastern  Already there
