### ISSUE TITLE
Localtimezone translation fails for Late Night with Seth Meyers

### ISSUE THREAD

**Issue by hagabla** [pymedusa/Medusa#2754]
**Branch/Commit: 9c19b10731765197136e042f30ebca793414cac1/master**
**OS:Debian**
**What you did:Add mentioned show**
**What happened:gets the day wrong**
**What you expected:gets the day right**
**Logs:**

It seems timezone translation fails for Late show with Seth Meyers. It gets the time right but not the day. For example today is Monday(8. May), Mondays show will Air on 00:37(Tuesday) in the US, which translates to 06:37AM 9. May Tuesday here (Europe). But Medusa shows the Airdate as Monday 8. May 06:35, which is wrong. I think Medusa gets confused because Mondays show actually airs after midnight but in thetvdb is listed as 8. May. 

The result is way to early searches, show getting into backlog and showing as missed, is there any way medusa could correct that?

**Comment by fernandog** [comment]
@duramato any idea? 

afaik it should show as "Daily" and not "Monday" in show page

**Comment by hagabla** [comment]
It does show as daily on the show page.
It says: Daily 12:35 AM om NBC

The problem is that it airs after midnight, so medusa does not interpret it as Monday night after midnight (technically Tuesday, since after midnight) but as Monday morning 00:35 (Sunday night after midnight).

**Comment by medariox** [comment]
One could argue that this is an indexer issue. Is the "wrong" air-date consistent at least? Is there some kind of threshold where we can say it's definitely airing the next day? E.g. what if a show airs at 2AM.. is it still going to have as air-date the previous day?

**Comment by fernandog** [comment]
@hagabla  ^^

**Comment by hagabla** [comment]
What kind of more info do you need from me?

**Comment by medariox** [comment]
@hagabla 
> Is the "wrong" air-date consistent at least? Is there some kind of threshold where we can say it's definitely airing the next day? E.g. what if a show airs at 2AM.. is it still going to have as air-date the previous day?

**Comment by hagabla** [comment]
Yes the wrong date is consistent  for Late Night with Seth Meyers, seems I did not make myself clear enough as why this happens and whats the cause of this.

About the threshold? How would I know :O When you look at programming guides, or magazines they usually go until ~4 AM ish.
Basically right before the breakfast tv shows start. Are there any shows that run after 2AM but reruns? I don't know.

Medusa is not acting wrong, nor are the indexers wrong. It is just how the TV stations act. Monday 00:30 does not mean Sunday to Monday 00:30 but Monday to Tuesday 00:30 since it still counts to Monday's programming.

**Comment by hagabla** [comment]
Did you guys agree on anything?

**Comment by hagabla** [comment]
Bump

**Comment by p0psicles** [comment]
Maybe we can implement a manual offset for these edge case scenarios. What you guys think?

**Comment by labrys** [comment]
In my opinion this is an error with the Indexer data.  Logically it is not the same day.  If they are using Broadcast Days, then the indexer needs to make that clear and then we can adjust all shows for that indexer to use Broadcast Days.  If the indexer itself is inconsistent, then the data should be corrected on the indexer.   For example `tvmaze` has some shows (mostly japanese) that have airtimes such as 26:30 to show 2:30 AM as part of the previous Broadcast Day.

**Comment by hagabla** [comment]
I don't care about Japanese shows. Indexer data, in this case at least, is perfectly clear and correct, shows the correct day and time. It's clearly a logical flaw/edge case in medusa. Anyhow, I am out. Deleted that show. Good luck guys.

**Comment by labrys** [comment]
@hagabla the Japanese show was just an example of how another indexer handles BroadCast days.  I understand why this would be irritating, I would like to make the indexers follow a defined standard to avoid these types of issues.  We could add an individual offset for a show, but the small number of edge-cases would be better solved by having the indexers be consistent.

**Comment by labrys** [comment]
I have opened an issue on thetvdb forums about support for broadcast days.

**Comment by sasha-** [comment]
Both tvmaze.com and thetvdb.com  track this show's air date incorrectly - this will never change. It would be nice if offset can be added to show settings on medusa side of things.  Even if "search offset"  would apply toward schedule and backlog would do the trick.
