### ISSUE TITLE
Unable to view showlist after adding First show

### ISSUE THREAD

**Issue by izenn** [pymedusa/Medusa#2791]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
9c19b10731765197136e042f30ebca793414cac1
**OS:**
Linux-4.10.13-1-ARCH-x86_64-with-glibc2.2.5
**What you did:**
add show
**What happened:**
show seemed to get info, but mako keeps throwing an error after the show info is downloaded for about 10 minutes

**What you expected:**
to view the show list at /home/
**Logs:**
[output.txt](https://github.com/pymedusa/Medusa/files/998745/output.txt)

**Comment by Wonderfall** [comment]
Hi, are you talking about this one? I'm trying to use Medusa instead of Sickrage, but once I add my first show Medusa keep throwing me this error.
![screen shot 2017-05-13 at 17 42 14](https://cloud.githubusercontent.com/assets/5507232/26027010/c775d14c-3806-11e7-856c-19330fe4b04e.jpg)

**Comment by medariox** [comment]
Thanks for the bug report. This is already [fixed in develop](https://github.com/pymedusa/Medusa/pull/2761) and will be included in the next release. The error should be gone as soon as the first show is added and you force refresh the page:
```
Windows: ctrl + F5
Mac/Apple: Apple + R or command + R
Linux: F5
```

**Comment by Wonderfall** [comment]
@medariox Thanks for the information. But it's been running for minutes and I still have no improvements. I'll try a fresh install again.

**Comment by medariox** [comment]
@Wonderfall 
Did you try force refreshing (CTRL + F5) or restarting Medusa first? A fresh install shouldn't be required.

**Comment by Wonderfall** [comment]
@medariox Yep, I tried refreshing the page several times. 

Unfortunately it seems Medusa couldn't be restarted : 

```
2017-05-13 15:57:04 INFO     MAIN :: [9c19b10] Broken providers found: [u'sdbits', u'binsearch', u'sceneaccess']
/usr/lib/python2.7/urllib.py:1299: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Traceback (most recent call last):
  File "/Medusa/SickBeard.py", line 7, in <module>
    main()
  File "/Medusa/medusa/__main__.py", line 2069, in main
    application.start(sys.argv[1:])
  File "/Medusa/medusa/__main__.py", line 297, in start
    self.initialize(console_logging=self.console_logging)
  File "/Medusa/medusa/__main__.py", line 986, in initialize
    load_provider_setting(app.CFG, provider, 'string', 'password', '', censor_log='low')
  File "/Medusa/medusa/config.py", line 688, in load_provider_setting
    value = check_provider_setting(config, provider, attr_type, attr, default, silent, **kwargs)
  File "/Medusa/medusa/config.py", line 680, in check_provider_setting
    return check_setting(config, section, attr_type, attr, default, silent, **kwargs)
  File "/Medusa/medusa/config.py", line 667, in check_setting
    return func[attr_type](config, section, attr, default, silent, **kwargs)
  File "/Medusa/medusa/config.py", line 643, in check_setting_str
    logger.rebuild_censored_list()
  File "/Medusa/medusa/logger/__init__.py", line 74, in rebuild_censored_list
    results |= {quote(item) for item in results}
  File "/Medusa/medusa/logger/__init__.py", line 74, in <setcomp>
    results |= {quote(item) for item in results}
  File "/usr/lib/python2.7/urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xbe'
WARNING:knowit.providers.mediainfo:Unable to load native mediainfo library
```

That being said I'm using Docker containers so perhaps I did something wrong with my image (using [this one](https://github.com/xataz/dockerfiles/tree/master/sickrage)). So maybe the fault is mine, although Sickrage was working fine.

**Comment by izenn** [comment]
thanks for the pointer about it being fixed in develop -- i'll switch my branch.  apparently my google-fu failed me. :)

**Comment by medariox** [comment]
@Wonderfall 
Please try to use our official docker images if possible:
* X86 - [Dockerhub](https://hub.docker.com/r/linuxserver/medusa/), [Github](https://github.com/linuxserver/docker-medusa)
* armhf - [Dockerhub](https://hub.docker.com/r/lsioarmhf/medusa/), [Github](https://github.com/linuxserver/docker-medusa-armhf)
* aarch64 - [Dockerhub](https://hub.docker.com/r/lsioarmhf/medusa-aarch64/), [Github](https://github.com/linuxserver/docker-medusa-arm64)

Do you [have a locale set](https://github.com/pymedusa/Medusa/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)? 
If you are still having issues, open a new issue with the relevant information.

**Comment by Wonderfall** [comment]
I prefer the way our image is organised, thanks though! I didn't have time to look at it but I'll open an issue if needed.
