### ISSUE TITLE
Jackett in Medusa 

### ISSUE THREAD

**Issue by toshi24** [pymedusa/Medusa#2794]
Hello,
I try to add Jackett to Medusa but i only find a way to add an rss adress. 
It seem working with torznab before, do you have a trick ?
Thanks,
Sébastien

**Comment by labrys** [comment]
I don't use Jackett but basically you set it as a newznab indexer.

**Comment by toshi24** [comment]
Thanks, @labrys. Here the way :
- Search settings / NZB search -> activate Search NZBs
- Search Providers / Cnfigure Custom Newznab Provider ->add jackett here
