### ISSUE TITLE
[APP SUBMITTED]: InterfaceError: Error binding parameter 0 - probably unsupported type.

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#2800]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@fffcab6b58c3ff22a20a4540e0df10f9e8591d0f
**Link to Log**: https://gist.github.com/0b3ba9af888ed43e7a6a219b68e24af2
### ERROR
<pre>
2017-05-16 14:32:52 ERROR    Thread-18 :: [fffcab6] DB error: InterfaceError('Error binding parameter 0 - probably unsupported type.',)
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/fffcab6b58c3ff22a20a4540e0df10f9e8591d0f/medusa/db.py#L107">medusa/db.py</a>", line 107, in _execute
    sql_results = cursor.execute(query, args)
InterfaceError: Error binding parameter 0 - probably unsupported type.
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

Error:
Couldn't read latest episode status. Error: long() argument must be a string or a number, not 'NoneType'

**Comment by fernandog** [comment]
@duramato 
Issue is here as in your history table the `action` column is None:

This error: `Couldn't read latest episode status. Error: long() argument must be a string or a number, not 'NoneType'` happens here:
https://github.com/pymedusa/Medusa/blob/develop/medusa/common.py#L475

Called from here: 
https://github.com/pymedusa/Medusa/blob/develop/medusa/server/web/home/handler.py#L1263

**Comment by fernandog** [comment]
no reply
