### ISSUE TITLE
[ FEATURE ] Support seedpeer.eu

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2818]
Hi can you add this provider :D 
http://www.seedpeer.eu/

Thanks a lot :D

**Comment by p0psicles** [comment]
@supergonkas will this bring much value? I have my doubts.

**Comment by IDerr** [comment]
Yeah true, in fact, not as much as nyaa. I prefer not to waste your time, and let you focus on more valuable things.

Thanks for your work.

**Comment by duramato** [comment]
I think this would bring benefit to out users, as can be seen by @phraymond :P who gave a thumbs up to the issue.
I don't think it can be even conpared to nyaa, ones focused on anime while this is a general indexer.

**Comment by p0psicles** [comment]
Well Im more hinting to the amount and quality off offered content. As also the amount of effort it requires to implement.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
