### ISSUE TITLE
Medusa not finding season packs

### ISSUE THREAD

**Issue by famulor** [pymedusa/Medusa#2830]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** Master/9c19b10731765197136e042f30ebca793414cac1
**OS:** Windows
**What you did:** Searched for season packs
**What happened:** Nothing. Skips to episode search
**What you expected:** Finding season packs :D 
**Logs:**

Btw im not sure thats the log you want but its the only one in /data/logs

Logs: [application2.txt](https://github.com/pymedusa/Medusa/files/1033528/application2.txt)

**Comment by medariox** [comment]
Issue: Backlog search for series (Show S02) ignores results which should be kept.

**Comment by fernandog** [comment]
@medariox are you going to debug this?

**Comment by p0psicles** [comment]
Is this for a specific search. Or every season pack search?

**Comment by medariox** [comment]
@fernandog 
No, I was only adding more information to the issue.

@p0psicles 
It's for every season pack search.

**Comment by famulor** [comment]
https://gist.github.com/famulor/36ebee8705c1ee5e330e333d8075b0c5 @fernandog
