### ISSUE TITLE
Postprocess subtitles

### ISSUE THREAD

**Issue by Stonedestroyer** [pymedusa/Medusa#2857]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:**
**What you did:**
**What happened:**
**What you expected:**
**Logs:**
```
PASTE LOGS HERE
```
How do I make it postprocess subtitles as currently in develop branch it doesn't seem to rename and pick them up.

**Comment by medariox** [comment]
Do you have "Delete associated files" checked and the extensions you want to keep set?

![pic](https://snapr.pw/i/ee9f20254d.png)

Also you can't process subtitles alone, you must have also the associated video files.

**Comment by Stonedestroyer** [comment]
I don't have "delete associated files" I only have keep associated files with the names inside, do I have to keep delete ticked as well?

**Comment by medariox** [comment]
Yes, you have to check the box "Delete associated files" as well. The text should probably say something like "Handle/Include associated files" instead, the wording is a bit confusing.

**Comment by fernandog** [comment]
You dont need to enable that to PP subtitles

What is your wanted subtitle language?
Check debug logs (must enable it)
Send a full print of your subs settings please

**Comment by medariox** [comment]
@fernandog 
Please try it at least before writing.

**Comment by Stonedestroyer** [comment]
Thank you, it works when that is enabled. 
![chrome_2017-06-04_20-17-15](https://cloud.githubusercontent.com/assets/1307729/26764196/d663fd88-4962-11e7-9a21-a3495dabaf65.png)

Without the checkbox it does not work.

**Comment by medariox** [comment]
@Stonedestroyer 
What's your Medusa version?

**Comment by Stonedestroyer** [comment]
Latest develop version, "You're using the develop branch. Please use 'master' unless specifically asked" latest commit.
