### ISSUE TITLE
Requesting for files when series page loads

### ISSUE THREAD

**Issue by burzka** [pymedusa/Medusa#2865]
I posted this issue on SickRage before, but same issue here in Medusa.

I set up series location on mounted GoogleDrive. Mounted drive has many limitations (for example checking if file exists takes much longer than on local drive). Now, even when series is fully cached in Medusa database, files are requested everytime I load episodes list. There is no info on DEBUG log. I see it on GoogleDrive mounting software log. It causing EXTREMELY lag. Waiting time strictly depends of number of episodes inside series.

Is there any reason for requesting files from disc, when specific episodes list page is loading?

**Comment by p0psicles** [comment]
It's checking for locale nfo files. And maybe some other files like subtitles.
