### ISSUE TITLE
Can't configure/search subtitles

### ISSUE THREAD

**Issue by Wonderfall** [pymedusa/Medusa#2867]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: master 2a21fd430ad688cd633f8929d2fb90cd78362e9e**
**OS: Alpine Linux 3.6**
**What you did: Tried to access subtitles settings.**
**What happened: Medusa throws a 500 error.**
**Logs:**
```
File /usr/lib/python2.7/encodings/utf_8.py:16, in decode:
return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 5: invalid continuation byte
```

It seems the search feature is also broken. But the strangest thing : it used to work before, I could for instance set up my opensubtitles account and add some languages.

**Comment by p0psicles** [comment]
Can you enable debugging, and post the log? Easiest is to use https://gist.github.com/

**Comment by Wonderfall** [comment]
I enabled debugging, I'm afraid I didn't get more entries than this one.

**Comment by p0psicles** [comment]
after enabling debugging, restart medusa. Then reproduce the issue. And go the `view log`. Change logging level from info to debug. In the right top of the logging window, there is a small notebook. you can use that to view the log in plain text.

**Comment by fernandog** [comment]
@Wonderfall do you have a locale set ? is it UTF-8?

open medusa page: http//ip:port/config/ and send a screenshot please

**Comment by fernandog** [comment]
no reply

**Comment by Wonderfall** [comment]
Yes but that doesn't mean the bug disappeared. I just didn't have time to look into this (yet).

**Comment by fernandog** [comment]
We sure can continue discuss.

**Comment by fernandog** [comment]
I will waiting your reply
