### ISSUE TITLE
[ FEATURE ] Add tv-vault.me support

### ISSUE THREAD

**Issue by smoresmores** [pymedusa/Medusa#2873]
Would be great if you could add support for the torrent tracker https://tv-vault.me 
Really appreciate your work on this!
Thanks!

**Comment by p0psicles** [comment]
We would love to. But it's not that easy without access to it.
Best is if you could come on IRC, and we can try to get one of the devs an account.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
