### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: ABC Spark

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#2875]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@21ec574d66160255f9de95a78ad5742ac256cad5
**Link to Log**: https://gist.github.com/49c98b95b343c786bab562e269529b18
### ERROR
<pre>
2017-06-12 10:49:42 ERROR    Thread-41 :: [21ec574] Missing time zone for network: ABC Spark
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
Added

**Comment by jrozelle** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
**Link to Log**: https://gist.github.com/a1934f9955b3dbfed48b14bb7b37e3f5
### ERROR
<pre>
2017-11-09 17:39:42 ERROR    Thread-16 :: [b16e0e5] Missing time zone for network: ABC (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
