### ISSUE TITLE
Year is before 1900

### ISSUE THREAD

**Issue by bnevets27** [pymedusa/Medusa#2892]
The show had an air date of something like 0201-04-28 on one of the episodes on thetvdb. Which causes medusa to post the following error on screen when going to the show page:

```
Mako Error
A mako error has occured.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.
```

Show/Hide reveals the following:

```
File /app/medusa/medusa/sbdatetime.py:235, in sbfdatetime:
strd = dt.strftime(app.DATE_PRESET)
ValueError: year=201 is before 1900; the datetime strftime() methods require year >= 1900
```

Fixed the episode on thetvdb and the issue is gone. Maybe just deal with this error more gracefully?

**Comment by OmgImAlexis** [comment]
@p0psicles we shouldn't have this issue once we're vue only right?

**Comment by sharkykh** [comment]
@OmgImAlexis Incorrect data from indexers will always be a thing IMO, since it's powered by the community. Vue might not fix that specific issue since it would probably be in the backend.
Dealing with it would mean changing any dates below 1900 to a null date (AKA an Unaired episode)
