### ISSUE TITLE
Bug? Location dropdown /home/ not working

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2893]
latest develop.

![image](https://user-images.githubusercontent.com/13415240/27241166-f298811c-52d7-11e7-91f5-52fbba3f23b9.png)

this solution that was added not long ago is not working. it always resets to "All Folders"

**Comment by fernandog** [comment]
@OmgImAlexis 

since when this started?

`2017-06-20 17:23:41 WARNING  TORNADO :: [97e2852] Config patch ignored {u'selectedRootIndex': u'0'}`

**Comment by fernandog** [comment]
@OmgImAlexis why this is not working anymore?

![image](https://user-images.githubusercontent.com/2620870/27357599-32cb25fa-55e9-11e7-9b12-9232f7bcc09d.png)
