### ISSUE TITLE
Calculate absolute number for tmdb

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2894]
Hi medusa team,
first of all, thanks for your work, I have reached 99.8% of episodes downloaded thanks to your work. 👍 

For the moment, anime users have to use tvdb as providers , because of absolute number (episodes).
But sometimes, tmdb has better naming, so if it's possible to calculate in Medusa the absolute number of episodes, it'll be great !

Thanks a lot :)

**Comment by p0psicles** [comment]
We make use of the xem for that. They don't support tmdb unfortunately.

**Comment by IDerr** [comment]
Ok, thanks for the answer

**Comment by labrys** [comment]
There are possibilities for episode matching between tvdb and tmdb, but an automated system would likely be error-prone.  For example names, air-dates, and order can all differ making matching problematic.
