### ISSUE TITLE
Trying to create an episode object, without the proper ingredients.

### ISSUE THREAD

**Issue by medariox** [pymedusa/Medusa#2896]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@4b24c3d74ad1e9cf278304f9eb954df7c1fcebd6
**Link to Log**: https://gist.github.com/9d1f6523bc8b367cea83f1148e208b26
### ERROR
<pre>
2017-06-17 20:27:00 ERROR    SEARCHQUEUE-BACKLOG-296762 :: [Nzb.su] :: [4b24c3d] Trying to create an episode object, without the proper ingredients. Missing season: 1, episodes: [] or the show object: indexerid: 296762
indexer: 1
name: Westworld
location: Z:\Series\Westworld
network: HBO
airs: Sunday 9:00 PM
status: Continuing
start_year: 2016
genre: Drama|Science-Fiction|Western
classification: Scripted
runtime: 60
quality: 16777280
scene: False
sports: False
anime: False

</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Aah I might have caused this. But not sure.

**Comment by medariox** [comment]
Looks like it was added in the proper fix https://github.com/pymedusa/Medusa/pull/2883/files#diff-90b4db298132f61ff3ce451582cd4a63R192

**Comment by p0psicles** [comment]
Aah. Yeah Im failing it now if the method was passed without any actual_episodes. As before it would just not generate episode objects.

But it's odd to go into the method if we don't have any episode numbers to convert to episode objects.

**Comment by p0psicles** [comment]
So we could resolve it by changing the changing the log exception to log info. And try to make more sense of it afterwards.

**Comment by p0psicles** [comment]
@fernandog, just remove the log
