### ISSUE TITLE
Bug? Multiple notification popups

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2897]
![image](https://user-images.githubusercontent.com/13415240/27271548-b52ae348-54c5-11e7-8c54-485e89a2e47c.png)

this happens since a few updates ago on develop

**Comment by medariox** [comment]
Multiple tabs open when it happens? That's because of WebSockets.

**Comment by IDerr** [comment]
Happens too. Like @medariox said, it's because of multiple tabs

**Comment by sharkykh** [comment]
@medariox Try setting `PNotify.desktop.tag` option for each message to a unique id (in JS).
I used a `hash()` on the Notification object in Python and then transferred that to Javascript along with the other params.

**Comment by wimpyrbx** [comment]
i'm pretty sure experienced it with only one tab as well. will update if i see it again.

**Comment by labrys** [comment]
@wimpyrbx I'm pretty sure I've had it with a single tab as well.

**Comment by labrys** [comment]
Actually it appears the double pop-ups I had with a single tab open appear to be duplicate snatches, not duplicate notifications.

**Comment by fernandog** [comment]
@OmgImAlexis when you have time can you try that fix please?

**Comment by fernandog** [comment]
@wimpyrbx confirm fixed?
