### ISSUE TITLE
Feature Request: Add Next Episode tracking system

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#2900]
Would be so nice if you guys integrate this 'tracker': http://next-episode.net/

**Comment by labrys** [comment]
@p0psicles it appears to be a tv-guide type site

**Comment by p0psicles** [comment]
Well yes. That's also what I noticed. So I was wondering the user would envision using this in Medusa.

**Comment by ward0** [comment]
I follow-up my shows there, when i watched a episode i put it as archived in next-episode.

When i have a new show that i want to follow, i add it first in that site

**Comment by OmgImAlexis** [comment]
I think they're wanting a way for Medusa to auto import new shows from the sounds of it.

**Comment by p0psicles** [comment]
Well it has similar functionality as trakt. But it doesnt offer a public api. It only offers an rss feed for the watch list.

If you really want to use a service like this. I'd recommend looking into trakt.

**Comment by labrys** [comment]
@ward0 If you want to talk to them to see if they are willing to provide an API (preferably json) then we can add it, however the RSS feed alone isn't particularly useful for us.

**Comment by ward0** [comment]
@labrys I asked the question.
