### ISSUE TITLE
Proper search on newznab+ does not work

### ISSUE THREAD

**Issue by hagabla** [pymedusa/Medusa#2903]
### Before submitting your issue:

**Branch/Commit:latest master**
**OS:debian jessie**

```
DEBUG    FINDPROPERS :: [xxx] :: [2a21fd4] No results returned from provider. Check chosen Newznab search categories in provider settings and/or usenet retention
2017-06-22 11:39:49 DEBUG    FINDPROPERS :: [xxx] :: [2a21fd4] GET URL: https://some.newsnab/api?apikey=**********&maxage=1500&cat=5030%2C5040&q=iZombie+S03E12+PROPER%7CREPACK%7CREAL%7CRERIP&limit=100&t=search&offset=0 [Status: 200]
2017-06-22 11:39:44 DEBUG    FINDPROPERS :: [xxx] :: [2a21fd4] Search show using search string: iZombie S03E12 PROPER|REPACK|REAL|RERIP
2017-06-22 11:39:44 DEBUG    FINDPROPERS :: [xxx] :: [2a21fd4] Search mode: Episode
```

Logs show the output from manual proper search.
Pasting the url into chrome with the correct api key shows an xml file with 0 hits.
5040 is the correct category.

After testing around a little it seems the PROPER|REPACK|REAL|RERIP search string is the issue, just searching with PROPER finds the release.

**Comment by fernandog** [comment]
@hagabla which that PROPER|REPACK is a "OR" search. Can you make sure it doesn't work in your newznab indexer?

**Comment by hagabla** [comment]
@fernandog I know what it is ;)

I can confirm it does not work that why, I tried via the web interface with PROPER OR REPACK, (PROPER OR REPACK), (PROPER|REPACK) in addition, but always got something like "Your search - iZombie S03E12 PROPER|REPACK - did not match any releases."

**Comment by fernandog** [comment]
maybe we will need to add this indexer as an exception.
can you tell us the name?

**Comment by hagabla** [comment]
@fernandog newznab

**Comment by p0psicles** [comment]
What interests me is that it didn't snatch it from a daily search. You say the release was in you cache/manual search list?

**Comment by hagabla** [comment]
It snatched the normal release, sure. But pymedusa does not find the proper.
Not sure what you mean with cache/manual search list.

This is only about the proper search.

**Comment by fernandog** [comment]
@p0psicles the PROPER isn't snatched in DAILY as a PROPER.

Daily only snatch a PROPER if is the first snatch

**Comment by p0psicles** [comment]
So proper search isn't checking the cache?

**Comment by fernandog** [comment]
it is. but it won't replace.

**Comment by hagabla** [comment]
Is this something that can be fixed?

**Comment by p0psicles** [comment]
I'm doing a rewrite of the entire search logic. So i'll also handle, replacing non-propers with a proper release during regular daily "and maybe backlog" searches, there. At least it should pick up proper results, that have been stored in the db (cache). You can at least check if the proper results you where aiming for, where visible in manual search.

Having fixed downloading propers from cache, will at least make the proper search (as how we use it now) superfluous to some degree.

Then there is the issue that your newznab+ provider is not working conform the newznab specs. Or at least not like what where accustomed to. We can take a look at that, but then we would need to have access to such a provider. I've setup nZEDb once, and that's not something i'd really like to do again. So if you could come to irc, and request for a dev, then maybe we can take a look at that.

**Comment by p0psicles** [comment]
I did some checks, but it seems something is wrong with your configuration of newznab+. Comparing this for ex. to usenet-crawler, that indexer is also a newznab+ site, and it is able to accept search strings like: "show name PROPER|REPACK|REAL". You should be able to get support on your installation.

Else I would recommend to look into nZEDb. That's an open source fork. Which should also support the pipes.

**Comment by hagabla** [comment]
Worked with sickbeard sickrage for years. I'll ask on the newznab forums or whatever kind of support they have.

**Comment by p0psicles** [comment]
Yeah problem is, that it's closed source. So I can't look into that. The piped operator search is working for all newznab providers we encountered. So we used that to search for PROPER, REPACK, REAL releases in one api search, which limits the amount of hits we do. 

What I could do, is make the list with searchable proper key values configurable for newznab providers. If you would limit it to one keyword (PROPER) it would work for you.

**Comment by p0psicles** [comment]
But in that solution it would only recognize one type of proper

**Comment by hagabla** [comment]
Well I doubt there is an option in newznab to disable OR search, but obviously I don't know. My guess is that sites based on newznab+ implement OR search themselves on top of the software.

It works with sickrageTV and with sickbeard, do you know how those apps do it?

**Comment by p0psicles** [comment]
sickrageTV i don't know, but SickRage runs one search per proper. So when a provider is configured to search for PROPER + REPACK + REAL, it will run 3 searches.

This is something we try to prevent whenever possible. As we don't want to hammer providers. For example when a show has three scene exceptions besides it's primary show name. For example: DC legends of tomorrow + "legends of tomorrow" + "legend of tommorrow" + ..? It will run 4 x 3 searches (12) with sickrage, and (4) with medusa.
