### ISSUE TITLE
[ FEATURE ] More options in Dropdown on /Home/

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2919]
would it be possible to add some more functionality to this dropdown box?
currently it gives option to show all or a certain location.
it would be cool to be able to have a list like this as option as well imo:

```
All folders
Folder1
Folder2
---------
Last added shows (for example last 10 added)
Shows with recent downloads
Shows missing episodes
```

The three below the ------ being the new ones i'm proposing. Hopefully it's just a switch and SQL change for the select to fix this?

![image](https://user-images.githubusercontent.com/13415240/27595865-24a1c50e-5b5e-11e7-9fea-f75d88667cbd.png)

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
