### ISSUE TITLE
In manual search when you sort by size it sorts MB above GB

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2931]
Issue from IRC:
<DeadlyBytes> BTW theres a small bug I just noticed, In manual search when you sort by size it sorts MB above GB. so 200MB iis "bigger" than 2GB

I don't know how to fix this @p0psicles @OmgImAlexis 
snatchSelection has some table sort stuff that I don't know
In mako we show pretty_size. Maybe need to add the size and make JS read it in text extraction
I prefer other to fix this to avoid break other stuff

**Comment by p0psicles** [comment]
Not that hard to fix. Just need to point it at the raw size for sorting.

**Comment by fernandog** [comment]
L136:

 `<td class="col-size triggerhighlight">${hItem["pretty_size"]}</td>`

Raw:
hItem["size"]

**Comment by sharkykh** [comment]
If this uses tablesorter, you can add the attribute: `data-text="${hItem["size"]}"`

**Comment by p0psicles** [comment]
Exactly sharkykh
