### ISSUE TITLE
Searching for manual subtitles when mobile does not work.

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#2943]
Hey,

When going into a serie > episode without subtitles > cc > manual > you get results but you can click on one to download.

I only have this problem when browsing on my phone using chrome.

I tried 'desktop version' in Chrome but didn't help either.

**Comment by fernandog** [comment]
mine works

@duramato yours still works too?

**Comment by ward0** [comment]
I found out that i have to click on the file name, not select the one i want and click ok or something.
I should have double checked, my bad.
