### ISSUE TITLE
Guessit 'format' match issue: folder vs filename

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2950]
File: WEB-DL
Folder: WEBRIP

This is becoming quite common for me. @ratoaq2 Can we use the format from file instead of folder?
The subtitles won't match because of this

ping @duramato 

```
python report_guessit.py "/series/Fear.the.Walking.Dead.S03E07.1080p.AMZN.WEBRip.DD5.1.x264-VLAD[rarbg]/Fear.the.Walking.Dead.S03E07.1080p.AMZN.WEB-DL.DD+5.1.H.264-VLAD.mkv"
# guessit: 2.1.3.dev0  rebulk: 0.8.3.dev0
? /series/Fear.the.Walking.Dead.S03E07.1080p.AMZN.WEBRip.DD5.1.x264-VLAD[rarbg]/Fear.the.Walking.Dead.S03E07.1080p.AMZN.WEB-DL.DD+5.1.H.264-VLAD.mkv
: title: Fear the Walking Dead
  season: 3
  episode: 7
  screen_size: 1080p
  streaming_service: Amazon Prime
  format: WEBRip
  audio_codec: AC3
  audio_channels: 5.1
  video_codec: h264
  video_encoder: x264
  release_group: VLAD
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 0.915619850159
```

**Comment by fernandog** [comment]
@rarbg quick question: is the uploaders or you that create the folder name in the RARBG releases?

noticed that the folder is "webrip" and file name is "web-dl".

**Comment by fernandog** [comment]
just noticed now that code is different too: x264 vs H.264

**Comment by rarbg** [comment]
We have a strict naming convention
How guessit treats it is up to guessit

**Comment by fernandog** [comment]
@rarbg i know but I'm asking about the torrent itself, not the guessit result

Check it out: https://rarbg.is/torrent/hnvu3w7#expand

Torrent name: Fear.the.Walking.Dead.S03E07.1080p.AMZN.WEBRip.DD5.1.x264-VLAD
Filename: Fear.the.Walking.Dead.S03E07.1080p.AMZN.WEB-DL.DD+5.1.H.264-VLAD.mkv

**Comment by duramato** [comment]
In this case file name is the correct release name.

**Comment by rarbg** [comment]
There is nothing to check. There are thousands of torrents like that

**Comment by rarbg** [comment]
@duramato 

whats right for us doesnt mean its right for guessit

thats why guessit should choose how to implement those results

**Comment by ratoaq2** [comment]
We would like at least to understand the logic/idea behind it. 
Should I understand that it's a webrip? Or a webdl?

**Comment by ratoaq2** [comment]
Is it Ac3 or EAC3?

**Comment by rarbg** [comment]
@ratoaq2
web-dl vs webrip - whats a web-dl and whats a webrip for you ?
AC3 vs EAC3 we dont have EAC3 tags and we never did its always DD5.1

**Comment by ratoaq2** [comment]
`/Fear.the.Walking.Dead.S03E07.1080p.AMZN.WEBRip.DD5.1.x264-VLAD[rarbg]/Fear.the.Walking.Dead.S03E07.1080p.AMZN.WEB-DL.DD+5.1.H.264-VLAD.mkv`

From where DD+ come from? that's Dolby Digital Plus (EAC3)

**Comment by rarbg** [comment]
From VLAD source

**Comment by ratoaq2** [comment]
someone inspected the file and it's indeed EAC3. So the VLAD source is correct and if I understood correctly, rarbg is labelling as AC3.

EAC3 is not backwards compatible with AC3.

https://en.wikipedia.org/wiki/Dolby_Digital_Plus#Relation_to_Dolby_Digital
> Dolby Digital Plus bitstreams are not directly backward compatible with legacy Dolby Digital decoders. 

I'm not challenging rarbg naming rules since it has a lot of reasoning behind it, but EAC3 labelled as AC3 is misleading since an AC3 device cannot decode EAC3.

**Comment by fernandog** [comment]
yes, vlad source is DD+, but what I don't get (bear with me please) is from where the webrip came from and the "DD" (not DD+) in the torrent name

![image](https://user-images.githubusercontent.com/2620870/28130688-f084864c-670d-11e7-9676-4fc805361b46.png)

**Comment by fernandog** [comment]
Replying the webrip vs web-dl:

web-dl is a file that was downloaded from the streaming service
webrip is from an **encode** from a stream. 

So webrip is a encode from a web-dl file

**Comment by rarbg** [comment]
VLAD labels it as DD 5.1+
Im not being rude , but understand that thats how its being labeled on rarbg for years and its not going to change. About device compatibility - thats a user issue , not ours. There are people that cant play DTS but still noone labels it for example.

**Comment by rarbg** [comment]
@fernandog 
Then Fear.the.Walking.Dead.S03E07.1080p.AMZN.WEB-DL.DD+5.1.H.264-VLAD is a WEB-DL for you. Not for us. For us a web-dl is itunes only.
Until all groups start tagging their releases properly , we are not going to change our naming convention and confuse hundreds of thousands of users!

Example why we cant't do that right now :
**Fear.the.Walking.Dead.S03E07.1080p.AMZN.WEB-DL.DD+5.1.H.264-VLAD** is a **WEB-DL** labeled as **AMZN WEB-DL** from VLAD and uploaded on RARBG as **Fear.the.Walking.Dead.S03E07.1080p.AMZN.WEBRip.DD5.1.x264-VLAD**

**The.Jim.Jefferies.Show.S01E05.720p.AMZN.WEBRip.DD2.0.x264-NTb** is a **WEB-DL** labeled as **AMZN WEBRip** from NTb and uploaded on RARBG as **The.Jim.Jefferies.Show.S01E05.720p.AMZN.WEBRip.DD2.0.x264-NTb**

**Comment by fernandog** [comment]
No problem. Thanks. I know you weren't being rude

**Comment by rarbg** [comment]
Just to make things clear.
11 days ago some groups accepted the AMZN.WEB-DL thing ( also NF.WEB-DL , HULU.WEB-DL and etc ) It will take time before everyone accepts it and then we will change our naming convention

**Comment by duramato** [comment]
>The.Jim.Jefferies.Show.S01E05.720p.AMZN.WEBRip.DD2.0.x264-NTb is a WEB-DL labeled as AMZN WEBRip from NTb and uploaded on RARBG as The.Jim.Jefferies.Show.S01E05.720p.AMZN.WEBRip.DD2.0.x264-NTb

@rarbg , `The.Jim.Jefferies.Show.S01E05.720p.AMZN.WEBRip.DD2.0.x264-NTb` is not a **web-dl**, but rather it is correctly tagged as **webrip** as it wasn't downloaded directly from AMZN, it's an encode from the web-dl per it's release notes: `This release is sourced from Amazon and was re-encoded.`

**Comment by rarbg** [comment]
@duramato 
That was a bad example , i wont go back on each release to check notes on which releases they fucked up

**Comment by rarbg** [comment]
Starting from today we preserve the DDP tag

**Comment by fernandog** [comment]
thanks!

**Comment by fernandog** [comment]
Fixed upstream: https://github.com/guessit-io/guessit/pull/488
