### ISSUE TITLE
Subtitle with Plex

### ISSUE THREAD

**Issue by lilp69** [pymedusa/Medusa#2952]
Hi, I use Medusa and Plex together. When I take some TV Shows in VO and after use Medusa to search subtitle, Plex doens't see my srt. In Medusa, I use Hardlink to move download from /Series/Download to /Series/TvShowName/
Subtitle options are : empty subtitle directory.
It's download well a subtitle and place it in /Series/TvShowName/, but Plex doens't see him.

Medusa Info:
Branch: master
Commit: 6b7e935af14dc51e213d7c3449048bc40126292d
Version: v0.1.14
Database: 44.8
Python Version: | 2.7.6 (default, Oct 26 2016, 20:32:47) 
OS: | Linux-4.4.0-72-generic-i686-with-Ubuntu-14.04-trusty

**Logs:**
2017-07-12 07:00:22 INFO     Thread-17 :: [6b7e935] Found subtitle for Fear the Walking Dead - S03E08 - Children of Wrath.mkv in podnapisi provider with language fre
2017-07-12 07:00:21 INFO     Thread-17 :: [6b7e935] Manual downloading subtitles for: Fear.the.Walking.Dead.S03E08.1080p.WEB-DL.DD5.1.H264-RARBG
2017-07-12 07:00:21 INFO     Thread-17 :: [6b7e935] Starting to manual downloading subtitles
2017-07-12 06:59:30 INFO     Thread-16 :: [6b7e935] Manual searching subtitles for: Fear.the.Walking.Dead.S03E08.1080p.WEB-DL.DD5.1.H264-RARBG
2017-07-12 06:59:30 INFO     Thread-16 :: [6b7e935] Starting to manual searching subtitles

**Comment by fernandog** [comment]
What is the full path and filename of subtitle?

**Comment by lilp69** [comment]
Full path is : Series/TvShowName/
Filename is : TvShowName - Title - SXXEXX.fr.srt

**Comment by fernandog** [comment]
Removing the "fr" works?

**Comment by lilp69** [comment]
Yes, I remove "fr" and it's works, but manually isn't so good :)

**Comment by fernandog** [comment]
In medusa there is an option to not append language if you only download one language

You should ask Plex why it doesn't recognize 'fr' (ping @pannal)

Subtitles Multi-Language:
Append language codes to subtitle filenames?

**Comment by pannal** [comment]
It should. For me (and all of my users) it does.

You're violating the Plex naming convention btw, by not using Season folders: https://support.plex.tv/hc/en-us/articles/200220687-Naming-Series-Season-Based-TV-Shows

**Comment by OmgImAlexis** [comment]
@pannal I've spoken to the Plex devs and you don't need season folders if you have SXX or Season XX in the file name.

**Comment by pannal** [comment]
OK. I'm just stating the official documentation :)

**Comment by lilp69** [comment]
Ok, I forget sorry but my correct path folder is ; /Series/TvShowName/SeasonXX/

**Comment by lilp69** [comment]
I check with Disable this setting:
    Subtitles Multi-Language
for a new episode who just comes out ;), and it's ok, thanks a lot.
