### ISSUE TITLE
Where did the user/password login page went to?

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#2954]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:

Medusa Info: | Branch: masterCommit: 6b7e935af14dc51e213d7c3449048bc40126292dVersion: v0.1.12Database: 44.8
-- | --
Python Version: | 2.7.13 (default, Dec 18 2016, 21:23:50) [GCC 4.6.4]
SSL Version: | OpenSSL 1.0.2j 26 Sep 2016
OS: | Linux-3.2.40-armv7l-with-glibc2.4
Locale: | en_US.UTF-8

**OS: synology
**What you did: wondering where my login page went to
**What happened: its gone after switch from Sickrage to Medusa
**What you expected: having to type my username and password.

I open the Medusa port to the internet.. I would like to have a login page where i have to type a username and password before i can login to Medusa.

**Comment by p0psicles** [comment]
General configuration -> interface -> scroll down.
Btw I wouldn't make medusa publicly available. I would look into the usage of a reverse proxy, like nginx.
