### ISSUE TITLE
summaryBackground div is not correct 

### ISSUE THREAD

**Issue by audi4life** [pymedusa/Medusa#2995]
### Before submitting your issue:

First off I like this port of Sickrage and thanks for the hard work. Mostly because of the preferred words which allow me to download HEVC episodes.
Now this is not so much an issue with operation as more a UI correction

When displaying the Show Summary the summaryBackground is as wide as the page, is not high enough to contain the cover art pic.  Or perhaps the cover art pic sits to low.

The code below would fix it `<div id="summaryBackground" class="shadow" style="height: 315px; top: 251px; left: 330px;width: 780px"></div>` would move the summary box over and shrink it to fit only the summary and the show status, quality settings etc... 

Again having not gone over the code there may be more to it or some css styling I am missing. But I just think it would give the UI a more polished look..

As well the cover art picture should be centred to the summary area. 
**Branch/Commit: Master
**OS: Linux
**What you did: N/A
**What happened:N/A
**What you expected:N/A
**Logs:**
```
PASTE LOGS HERE
```

**Comment by p0psicles** [comment]
We've disconnected the wide banner from the art pic on purpose. As the banner purpose is to wrap the show summary information. That div can be very dynamic in height. Depending on the overal widht of the screen, the number of wanted qualities, preferred words, etc.

So you'll have to take all these variables into account. But if you can come up with a better look, then please create a pull request, and we'll take a look.
