### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: SFR Play

### ISSUE THREAD

**Issue by phraymond** [pymedusa/Medusa#2997]
### INFO
**Python Version**: `2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]`
**Operating System**: `Linux-4.9.30-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/30984fc30497ddff8883fda71f610c1f
### ERROR
<pre>
2017-08-08 14:15:47 ERROR    Thread-34 :: [49e9fc3] Missing time zone for network: SFR Play
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by DcR-NL** [comment]
Created a pull for these timezones: https://github.com/pymedusa/medusa.github.io/pull/62

**Comment by p0psicles** [comment]
Tnx!
