### ISSUE TITLE
WebSockets not compatible with reverse proxy + web_root

### ISSUE THREAD

**Issue by adaur** [pymedusa/Medusa#3007]
When I try to access Medusa, I'm getting a Web proxy error despite my Nginx configuration being correct as per the wiki:

```
		location ^~ /medusa {
			proxy_pass http://localhost:8081;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Host $host:443;
			proxy_set_header X-Forwarded-Server $host;
			proxy_set_header X-Forwarded-Port 443;
			proxy_set_header X-Forwarded-Proto $scheme;

			# Websocket
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_read_timeout 86400;
		}
```

Problem is, I'm using medusa behind a reverse proxy + a custom folder:

https://mydomain.com/medusa

wsCheckNotifications tries to ping the following:

https://mydomain.com/ws/ui

this is obviously not working since it should be

https://mydomain.com/medusa/ws/ui

Problem is coming from https://github.com/pymedusa/Medusa/blob/develop/static/js/ajax-notifications.js#L34

The following seems to work, but you'll probably want to do something cleaner

`var ws = new WebSocket(proto + '//' + window.location.hostname + ':' + window.location.port + window.location.pathname.split('/')[1] + '/ws' + WSMessageUrl);`

**Comment by OmgImAlexis** [comment]
@p0psicles I thought we were using srRoot in the websocket url?

**Comment by p0psicles** [comment]
Yeah me too, i'll look into this next.

**Comment by p0psicles** [comment]
I'm reopening this issue. As I noticed that MEDUSA.config.webRoot is only available on config pages. All other pages, like displayShow, massEdit, manualSearch, don't hvae the webRoot attribute.

this will mean for now, that the notification only work in the config pages.

@OmgImAlexis can you look into this?

**Comment by p0psicles** [comment]
Hmm I just checked again, and now it's available like it should. Maybe I was confused, when testing with webroot disabled. As when retrieving the config from apiv2, when the value is empty, the key is also not added in the json.

I am still having some issues with getting the notifications for the other pages then config. So i'll do some more testing.

@adaur is this solved for you now?

**Comment by adaur** [comment]
Yes, it is working great, thanks. I'll be able to switch soon :)

**Comment by OmgImAlexis** [comment]
@p0psicles the key is most likely set to undefined that's probably why you didn't think it was there as a missing key is also returns undefined.
