### ISSUE TITLE
Absolute number ?

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#3029]
Hi, I have trouble with Medusa to detect absolute numbering. Absolute naming is automatically considered as Season 1 : 

```
Found release name Saint.Seiya.E76.1080p.BluRay-Yomi
Destination folder for this episode: /home/**/downloads/animes/Saint Seiya/Season 01
Moving file from /home/**/complete/Saint.Seiya.E76.1080p.BluRay-Yomi.mkv to /home/**/downloads/animes/Saint Seiya/Season 01/Saint.Seiya.S01E76.1080p.BluRay-Yomi.mkv 
Processing succeeded for /home/**/complete/Saint.Seiya.E76.1080p.BluRay-Yomi.mkv
```

An idea on this ?

**Comment by p0psicles** [comment]
@ratoaq2 do you have any idea why guessit, didn't parse this as an absolute episode number? Is that because of the `E` in front of 76?


python report_guessit.py "Saint.Seiya.E76.1080p.BluRay-Yomi.mkv"
```# guessit: 2.1.3.dev0  rebulk: 0.8.3.dev0
? Saint.Seiya.E76.1080p.BluRay-Yomi.mkv
: title: Saint Seiya
  episode: 76
  screen_size: 1080p
  format: BluRay
  release_group: Yomi
  container: mkv
  type: episode
  parsing_time: 0.0260000228882
```

**Comment by p0psicles** [comment]
@IDerr we're working on this. Might take some time for us to continue on this. For now I would just move the episodes to the appropriate folder, and manually fix the naming. Like: `Saint.Seiya.s02e03.1080p.BluRay-Yomi.mkv`.

**Comment by p0psicles** [comment]
@IDerr, can you test this again using the develop branch? Should be fixed.

**Comment by IDerr** [comment]
Yep, trying this right now :D

**Comment by IDerr** [comment]
Yep it is working :D 

Thanks :D
