### ISSUE TITLE
Error connecting to websocket

### ISSUE THREAD

**Issue by stanthewizzard** [pymedusa/Medusa#3041]
Medusa Info: | Branch: masterCommit: 49e9fc38856200768d41a74139807886acefa054Version: v0.1.14Database: 44.8
-- | --
Debian 8.9
Python Version: | 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: | fr_FR.UTF-8

Hello
I get this notification error 
Error connecting to webscoket
Behind Nginx and with direct IP access

Someone got this issue too ?

Thanks

**Comment by OmgImAlexis** [comment]
[You need to enable websockets in your nginx config](https://stackoverflow.com/questions/12102110/nginx-to-reverse-proxy-websockets-and-enable-ssl-wss).

**Comment by p0psicles** [comment]
With a correct configured nginx reversed proxy this should be fixed in current develop.
Won't be long until that's merged to master.

**Comment by stanthewizzard** [comment]
I got the issue through IP direct
bypassing nginx totaly
:/

**Comment by OmgImAlexis** [comment]
The websocket is likely trying to use wss which requires ssl. It will work fine with nginx if you add the websocket details on the page I linked.

**Comment by p0psicles** [comment]
Are u using a webroot?

**Comment by stanthewizzard** [comment]
sorry I don't understand what it is ? :)

**Comment by p0psicles** [comment]
are you running default using a root like this: http://localhost:8082/home/... or did you have a base configured like: http://localhost:8082/medusa/home/...

**Comment by p0psicles** [comment]
I suspect you have the webroot configured, and then you'll need to wait for our next release to have this fixed. Or checkout develop branch.

**Comment by stanthewizzard** [comment]
OK I understand (thanks)
No it's a root web dir.
Configured like that
http://localhost:8082/medusa/home/...
