### ISSUE TITLE
Add existing series triggers search prematurely

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#3054]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** Develop
**OS:** Windows 10
**What you did:** Added existing series
**What happened:**  While series was being processed a daily search triggered and episodes were found and added to queue even though preferred quality already existed on drive.
**What you expected:**  All searches to be deferred until existing series has been fully processed
**Logs:**
```
N/A
```

**Comment by p0psicles** [comment]
I'd like to refine this a little. I think we should not include a show in a search, when it has not yet fully processed.
