### ISSUE TITLE
[APP SUBMITTED]: UnboundLocalError: local variable 'countries' referenced before assignment

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#3055]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `43.8`
**Commit**: pymedusa/Medusa@44d7bb04b0b2b446009612321466c754976c3a0d
**Link to Log**: https://gist.github.com/e8f78e371b0671bf92fb8a46d6151c7e
### ERROR
<pre>
2017-08-23 19:37:09 ERROR    SHOWQUEUE-ADD :: [44d7bb0] Error loading IMDb info: local variable 'countries' referenced before assignment
Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\show_queue.py", line 533, in run
    self.show.load_imdb_info()
  File "H:\usr\local\medusa\medusa\tv\series.py", line 1569, in load_imdb_info
    'countries': '|'.join(countries),  # Obtained from TMDB's api, as imdbpie doesn't have it. Not IMDb info.
UnboundLocalError: local variable 'countries' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
#3048

**Comment by medariox** [comment]
Fixed in develop.
