### ISSUE TITLE
[ FEATURE ] Add release name to email notification

### ISSUE THREAD

**Issue by doopsuiker** [pymedusa/Medusa#3061]
Hi,

Is it possible to add the full release name of an episode to the email notification?
In this way, we would exactly know what we downloaded instead of only "1080p WEB-DL"

**Comment by fernandog** [comment]
@doopsuiker if you want to try, just stop Medusa and change that file like this:
https://github.com/pymedusa/Medusa/pull/3062/files

**Comment by doopsuiker** [comment]
@fernandog 
I meant adding an extra line with the full release name like this:
Release name: Game.of.Thrones.S07E06.Beyond.the.Wall.1080p.AMZN.WEB-DL.DDP5.1.H.264-GoT.mkv

**Comment by fernandog** [comment]
so you want both the "1080p WEB-DL" and the full release name ? Cause this change will show full release name instead of "1080p WEB-DL"

**Comment by doopsuiker** [comment]
@fernandog 
I want an extra line with the full release name.
Your change only changes this:

Episode: Suits - 7x07 - Full Disclosure - 1080p WEB-DL
 instead of
Episode: 7x07 - Full Disclosure

I want an extra line like this:
Release name: Show.S07E06.1080p.AMZN.WEB-DL.DDP5.1.H.264-RG.mkv

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
