### ISSUE TITLE
Unable to get info to move torrent later as no info hash available for

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#3065]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** Develop
**OS:** Windows
**What you did:**  Observed warnings
**What happened:** Got lots of warnings for "Unable to get info to move torrent later as no info hash available for"
**What you expected:**  I don't torrent so I shouldn't be getting these errors.  Also the errors should only occur if you're using the move torrent feature.
**Logs:**
```
2017-08-26 04:51:48 WARNING  Thread-34 :: [c3a7a22] Unable to get info to move torrent later as no info hash available for: <FILE>
```

**Comment by medariox** [comment]
This should be fixed.
