### ISSUE TITLE
[ FEATURE ] Option to use banners instead of posters in schedule (calendar layout)

### ISSUE THREAD

**Issue by leo06** [pymedusa/Medusa#3068]
In schedule (calendar layout) use banners instead of posters and color tags would be nice, for example, under the banner the episode's name background blue for unaired episode,red for missing, green for downloaded,light blue for unaired premiere

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
