### ISSUE TITLE
[APP SUBMITTED]: Prowl auth failed: Unauthorized

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#3074]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-3.16.0-4-amd64-x86_64-with-debian-8.8`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@f0cc6bc750b647546b99905b31df981ab45c0b0a
**Link to Log**: https://gist.github.com/ebdabda8b61e940eedb931e3218352dd
### ERROR
<pre>
2017-08-29 00:12:26 ERROR    FINDSUBTITLES :: [f0cc6bc] Prowl auth failed: Unauthorized
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
Shouldn't be error but warning

**Comment by labrys** [comment]
IMO should be error... I define error as something that should be investigated by a sysadmin to resolve the issue.

**Comment by fernandog** [comment]
User/Pass is wrong @p0psicles or else?

**Comment by p0psicles** [comment]
sorry yes that's it. Didn't intent to upload this error. But I agree that it should be a warning. @labrys with sysadmin, you mean the user? Then when do you justify using warnings?
