### ISSUE TITLE
Keeps downloading stuff i dont want

### ISSUE THREAD

**Issue by Hellowlol** [pymedusa/Medusa#3077]
Im having issues with medusa keeps downloading stuff i ready have. 

My first though just just to add everything has skipped in hope that medusa just ignored everything and focused on future episodes. But it seems to be picked up anyway since i already have the files.

Then i tried to to setup a custom setting where any thing is permitted, and i set prefered to 720. The same happens again.

How can i get medusa to just ignore any aired episodes and just focus on the new ones?

**Comment by fernandog** [comment]
Open manage backlog. How many episodes you have with atatus "quality" ?

If none Medusa it's not doing any search/replace

If you archive all episodes it won't be replaced no matter what.

**Comment by Hellowlol** [comment]
quality is 5835 wanted is 8.
Where can i archive all the episodes?

**Comment by fernandog** [comment]
If quality is that much then your custom qualities are wrong. Edit one show with custom qualities and you can see on the fly if backlog increases/decreases

**Comment by fernandog** [comment]
As soon you change custom qualities a red label will show the backlog account

**Comment by Hellowlol** [comment]
Well thats pr show. I have no intention doing this one by one. Ill see if cant fix this via medusa api. Imo medusa should handle this better, i cant be the only one in this situation.

Anyway thanks for the help, it cleared up something for me. Thanks alot :)

**Comment by fernandog** [comment]
First you need to understand what's wrong with your custom qualities. Now you can mass edit shows and fix then

To archive open display show, select EPs and change episode status to ARCHIVED

**Comment by fernandog** [comment]
BTW what was wrong with the show you tested?

**Comment by Hellowlol** [comment]
There isnt anything wrong with atleast not that i know of. They just dont do what i want. The quality seems to referee to all the media. I want to split on how i handle existing content vs new. Medusa should ignore all old stuff and just handle new. Archive seems to solve this issue.

**Comment by Hellowlol** [comment]
I didn't test just one show. I just don't have time to manually go thru all my shows and change to archive for all the episodes.

**Comment by fernandog** [comment]
In backlog overview you can archive too. It's last icon. Looks like a box

**Comment by Hellowlol** [comment]
Yeah i was it but i couldnt find any button for archive all. I don't want to push the same button 5889 times so I'll use the API.

**Comment by Hellowlol** [comment]
Incase anybodys wants a "fix" for this issue they can use this gist. https://gist.github.com/Hellowlol/85f2748889b23a5709066481bff27c2c
