### ISSUE TITLE
Error connecting to websocket pop up?

### ISSUE THREAD

**Issue by whipcracker** [pymedusa/Medusa#3079]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
Master - 3f23fd272652b10cf781e3058fee50daf79f11b6
**OS:**
Linux-4.12.3-feral-x86_64-with-debian-8.8
**What you did:**
Nothing (that I'm aware of anyway)
**What happened:**
I have this error msg pop up each time the page refreshes or changes page. This issue started right after the last major update before Medusa received the DCMA issue. It doesn't appear to show anything in the logs, it doesn't appear to affect anything when using Medusa either. I'm running Medusa off my feralhosting slot and have been using this fine for months, if not years, yet never had this message before. I don't have any proxy or reverse proxy manually configured at all. I've noticed that the page doesn't even load on Internet Exlorer at all (just hangs). I'm using Chrome on Win 10 to view the page. I don't appear to see the issue when using Chrome on my Android phone, though (either not able to see it at all, or might not be affected? I don't know). I've tried this using HTTPS and HTTP and the msg still pops up.
![image](https://user-images.githubusercontent.com/15645911/30004699-0c9afd74-90cc-11e7-8b8a-09d432551640.png)
![image](https://user-images.githubusercontent.com/15645911/30004761-20a5c23a-90cd-11e7-833e-5ddcd9a094b0.png)

**What you expected:**
I don't expect the little window to pop up each time the page loads.
**Logs:**
```
2017-09-03 16:10:39 DEBUG    CHECKVERSION :: [3f23fd2] User-Agent: Medusa/0.0.1(Linux; 4.12.3-feral; 670aa200-90c2-11e7-b4d6-0090fa70a3bc)
2017-09-03 16:10:39 DEBUG    CHECKVERSION :: [3f23fd2] GET URL: https://cdn.pymedusa.com/news/news.md [Status: 200]
2017-09-03 16:10:38 DEBUG    CHECKVERSION :: [3f23fd2] check_for_new_news: Checking GitHub for latest news.
2017-09-03 16:10:38 DEBUG    CHECKVERSION :: [3f23fd2] cur_commit = 3f23fd272652b10cf781e3058fee50daf79f11b6, newest_commit = 3f23fd272652b10cf781e3058fee50daf79f11b6, num_commits_behind = 0, num_commits_ahead = 0
2017-09-03 16:10:38 DEBUG    CHECKVERSION :: [3f23fd2] git rev-list --left-right "@{upstream}"...HEAD : returned successful
2017-09-03 16:10:38 DEBUG    CHECKVERSION :: [3f23fd2] Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /media/sdq1/home/**********/.sickrage
2017-09-03 16:10:38 DEBUG    CHECKVERSION :: [3f23fd2] git rev-parse --verify --quiet "@{upstream}" : returned successful
2017-09-03 16:10:38 DEBUG    CHECKVERSION :: [3f23fd2] Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /media/sdq1/home/**********/.sickrage
2017-09-03 16:10:38 DEBUG    CHECKVERSION :: [3f23fd2] git fetch origin : returned successful
2017-09-03 16:10:36 DEBUG    CHECKVERSION :: [3f23fd2] Executing git fetch origin with your shell in /media/sdq1/home/**********/.sickrage
2017-09-03 16:10:36 DEBUG    CHECKVERSION :: [3f23fd2] git config remote.origin.pushurl https://github.com/**********/Medusa.git : returned successful
2017-09-03 16:10:36 DEBUG    CHECKVERSION :: [3f23fd2] Executing git config remote.origin.pushurl https://github.com/**********/Medusa.git with your shell in /media/sdq1/home/**********/.sickrage
2017-09-03 16:10:36 DEBUG    CHECKVERSION :: [3f23fd2] git config remote.origin.url https://github.com/pymedusa/Medusa.git : returned successful
2017-09-03 16:10:36 DEBUG    CHECKVERSION :: [3f23fd2] Executing git config remote.origin.url https://github.com/pymedusa/Medusa.git with your shell in /media/sdq1/home/**********/.sickrage
2017-09-03 16:10:36 DEBUG    CHECKVERSION :: [3f23fd2] git rev-parse HEAD : returned successful
2017-09-03 16:10:36 DEBUG    CHECKVERSION :: [3f23fd2] Executing git rev-parse HEAD with your shell in /media/sdq1/home/**********/.sickrage
2017-09-03 16:10:36 DEBUG    CHECKVERSION :: [3f23fd2] git symbolic-ref -q HEAD : returned successful
2017-09-03 16:10:36 DEBUG    CHECKVERSION :: [3f23fd2] Executing git symbolic-ref -q HEAD with your shell in /media/sdq1/home/**********/.sickrage
2017-09-03 16:10:36 INFO     CHECKVERSION :: [3f23fd2] Checking for updates using GIT
2017-09-03 16:10:36 DEBUG    CHECKVERSION :: [3f23fd2] git ls-remote --heads origin : returned successful
```

**Comment by p0psicles** [comment]
Can you try this for me? Open the dev tools (F12) in chrome when you have the medusa home screen open. Check if there are any warnings or errors in the console? Maybe do a refresh when you have medusa and the Console open.

Also to be sure. You'r opening medusa using the following url: `http://your_machine_ip_address:port/whipcracker/sickrage/` ?

**Comment by ward0** [comment]
Have you done a IE reset already? Looks like a proxy problem to me.
![image](https://user-images.githubusercontent.com/15545810/30018074-d0a5870e-915b-11e7-9f8d-4522e441f1cc.png)

**Comment by whipcracker** [comment]
I'll have a look at both of these later tonight lads. Just thought I'd mention that I don't have this problem at all with my Medusa install on my Windows PC with very much the same settings. Once I've had a go at both of your suggestions, I'll post back. Cheers!

**Comment by whipcracker** [comment]
https://server.feralhosting.com/whipcracker/sickrage/home/ is what I use to access the Medusa install on my seedbox. There is an install script that they have to install SickRage, which sets up ssl and probably other stuff. I just change the branch over and do a pull on the new branch and she updates over to Medusa and its been doing that fine for at least 18 months.

I opened up Chrome and clicked the console tab and did a refresh, however nothing appeared in the main window there at all. Is that where you're wanting me to look?

Advanced settings restore in IE havent done anything either. To be honest, I havent really opened up IE since I installed Windows on it?

Please let me know where you want me to look from here. Cheers!

**Comment by medariox** [comment]
Is there any way for you to modify the "automated setup" feral hosting has in place for SR? Medusa requires some additions to support websockets now, that differ from the "default" SR ones. Probably they are using nginx, have a look here for a config example: https://github.com/pymedusa/Medusa/wiki/Reverse-Proxy-setup 
Maybe you can ask feral hosting to edit that for you (or even add an automated setup for Medusa)?

**Comment by whipcracker** [comment]
I'm using nginx definitely. I had to move from Apache over to Nginx originally, probably to get SickRage or something else to work properly. I'm going to assume that the last major update before the DCMA debacle had some changes made where Medusa needs further info on websockets?

We have SSH access to our slots (minus any sudo elevated commands of course) but just wondering where I'd place that nginx reverse proxy script, exactly?

**Comment by medariox** [comment]
The nginx config files are usually located in ```/etc/nginx/sites-enabled/```.

You should have something like:
```
location /medusa {
        ......(you current config)....
        Add the following:
        # Websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }
```

**Comment by medariox** [comment]
About Chrome and the console window, make sure you keep the console open and refresh the page the page until the websocket error pops up. You should eventually get an error in the chrome console.

**Comment by whipcracker** [comment]
Hi Dario,

Uncertain as to which directory you're wanting me to edit? Are you talking
about the config.ini in the Medusa main folder, or are you referring to the
nginx directory located in my main directory of the seedbox? If it's the
latter, then the directories you suggest unfortunately aren't the same.

Any suggestions? Thanks in advance!

**Comment by ward0** [comment]
Can you do as @medariox asked you to do? in chrome > press F12 until you see an error.

**Comment by whipcracker** [comment]
Just found the error msg now!

VM42:161 WebSocket connection to 'wss://hestia.feralhosting.com/whipcracker/sickrage/ws/ui' failed: Error during WebSocket handshake: Unexpected response code: 400
WrappedWebSocket @ VM42:161
ajax-notifications.js?2242:53 Error connecting to websocket. Please check your network connection. If you are using a reverse proxy, please take a look at our wiki for config examples.
ws.onerror @ ajax-notifications.js?2242:53

**Comment by whipcracker** [comment]
@medariox and @ward0 unsure if you saw the latest comment on what I got from F12 in Chrome? Cheers in advance :)

**Comment by medariox** [comment]
@whipcracker 
> Uncertain as to which directory you're wanting me to edit? Are you talking
about the config.ini in the Medusa main folder, or are you referring to the
nginx directory located in my main directory of the seedbox? If it's the
latter, then the directories you suggest unfortunately aren't the same.

I was referring to the nginx directory. Do you know where it's located? Can you edit the nginx config?
I have the feeling that the config file is missing the necessary bits to make WebSockets work properly (see my answer above for what to add to the config).

**Comment by whipcracker** [comment]
Hi @medariox I have a nginx folder in the home directory on the seedbox,
which has a few folders? Any suggestions on where you'd want me to look?
Hopefully the attachment has loaded of what's in the nginx directory.

Cheers :)

On 14 Sep 2017 7:45 PM, "Dario" <notifications@github.com> wrote:

@whipcracker <https://github.com/whipcracker>

Uncertain as to which directory you're wanting me to edit? Are you talking
about the config.ini in the Medusa main folder, or are you referring to the
nginx directory located in my main directory of the seedbox? If it's the
latter, then the directories you suggest unfortunately aren't the same.

I was referring to the nginx directory. Do you know where it's located? Can
you edit the nginx config?
I have the feeling that the config file is missing the necessary bits to
make WebSockets work properly (see my answer above for what to add to the
config).

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pymedusa/Medusa/issues/3079#issuecomment-329573982>,
or mute
the thread

**Comment by medariox** [comment]
Which folders do you have? I don't see any attachments.

> The way nginx and its modules work is determined in the configuration file. By default, the configuration file is named nginx.conf and placed in the directory /usr/local/nginx/conf, /etc/nginx, or /usr/local/etc/nginx.

You should be looking for a file ending with ```.conf```, but I can't say for sure which one, as I don't know how your configuration is structured.

**Comment by whipcracker** [comment]
![screenshot_20170914-203923](https://user-images.githubusercontent.com/15645911/30452315-24763e30-998d-11e7-8aac-2eb8703d8d10.png)

**Comment by whipcracker** [comment]
I have a nginx.conf file there, so looks like I'll need to have a look at that file.

**Comment by whipcracker** [comment]
My config file contains this:

"pid       /media/sdq1/home/whipcracker/.nginx/pid;
error_log /media/sdq1/home/whipcracker/.nginx/error.log;

worker_processes     1;
worker_rlimit_nofile 65535;
events {
    worker_connections 8192;
}

http {
    include          /etc/nginx/mime.types;
    default_type     application/octet-stream;
    access_log       off;
    sendfile         on;
    tcp_nopush       on;
    real_ip_header   X-Forwarded-For;
    port_in_redirect off;

    client_max_body_size  1g;
    client_body_temp_path /media/sdq1/home/whipcracker/.nginx/client;
    fastcgi_temp_path     /media/sdq1/home/whipcracker/.nginx/fastcgi;
    uwsgi_temp_path       /media/sdq1/home/whipcracker/.nginx/uwscgi;
    scgi_temp_path        /media/sdq1/home/whipcracker/.nginx/scgi;
    proxy_temp_path       /media/sdq1/home/whipcracker/.nginx/proxy;

    include conf.d/*.conf;
}"

**Comment by medariox** [comment]
What's in the ```conf.d``` folder?

**Comment by whipcracker** [comment]
![screenshot_20170914-205214](https://user-images.githubusercontent.com/15645911/30452758-abfa206e-998e-11e7-968f-deb617a8e26c.png)

That's what's in the conf.d folder..

**Comment by whipcracker** [comment]
![screenshot_20170914-205225](https://user-images.githubusercontent.com/15645911/30452793-c9d31596-998e-11e7-9808-b0b44d789452.png)

That's what's in the 000-default-server.d folder has.

**Comment by medariox** [comment]
That's it. You need to add what I posted above to the sickrage.conf.

**Comment by whipcracker** [comment]
I originally used the install script from the seedbox provider to install Sickrage, then I moved over to Medusa... I'm wondering if I should be looking in the sickrage.conf file?

**Comment by whipcracker** [comment]
Roger that. I'll have a look and add it in if it needs it.

**Comment by whipcracker** [comment]
Stupid question, what goes in the area that you've said "your current config"?

**Comment by medariox** [comment]
It depends how your current config is setup right now.. I can't really know. What you need to look for is the ```location /sickrage``` part and put what I wrote above at the bottom of it within the curly brackets.

**Comment by whipcracker** [comment]
This is what I currently have..

location /sickrage {
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $http_x_host;
proxy_set_header X-NginX-Proxy true;

rewrite /(.*) /whipcracker/$1 break;
proxy_pass http://10.0.0.1:30334/;
proxy_redirect off;
}

**Comment by whipcracker** [comment]
Am I able to add to the same conf file, or do I need to edit it instead?

**Comment by medariox** [comment]
Just try adding this...
```
proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
```
Don't forget to reboot/reload nginx.

**Comment by whipcracker** [comment]
Like this?

location /sickrage {
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $http_x_host;
proxy_set_header X-NginX-Proxy true;

rewrite /(.*) /whipcracker/$1 break;
proxy_pass http://10.0.0.1:30334/;
proxy_redirect off;

proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
}

**Comment by medariox** [comment]
Yeah, give that a try.

**Comment by whipcracker** [comment]
Added the extra bit and reloaded nginx, however the problem is still happening :(

I'll remove that last piece from the conf file and take it back to its original file. Any further suggestions or help you might have would be epic.

**Comment by jalim** [comment]
Was there any resolution found to this issue?

**Comment by whipcracker** [comment]
Unsure if it's an isolated incident or not. Can probably close the case
unless it plays up again?

**Comment by OmgImAlexis** [comment]
These should all help https://github.com/pymedusa/Medusa/wiki/Reverse-Proxy-setup

**Comment by whipcracker** [comment]
Hey Alexis,

Cheers for the link. I'm wondering what has changed in recent updates
that's caused this problem? It's running on a Debian Linux seedbox
(FeralHosting) in Europe for the past couple of years without any hitches.

Happy to look into it, just thought it was something worth mentioning.

**Comment by OmgImAlexis** [comment]
Well we added websocket support so that's what caused this.

Most people will just need to add the section for websockets as listed by that wiki page.

**Comment by whipcracker** [comment]
Sounds fair.

Which config file am I adding this to, please? Also seeing I'm running
Nginx, I assume it just wants me to replace the example with the full
domain name of the server I use to connect to, externally and the IP is the
public IP, not a local IP?

**Comment by OmgImAlexis** [comment]
If you're already using a config similar to that then yes otherwise just copy the websocket part for nginx and add it to your current nginx config in the correct place.

Keep in mind I think websockets only work on a HTTPS connection now so you'll at least have to use a self signed cert if not an actual valid one.

**Comment by whipcracker** [comment]
Thanks for the reply. I'll have a look into it tomorrow and go from there.
It's a SS cert and yeah, SSL all the way!

**Comment by jalim** [comment]
I'm having issues getting this to work with Jwilder's Nginx Proxy Docker.  Has anyone got a working setup for this?  I've tried using the wiki config but this makes the whole site fail as the page tries to load insecure http resources.

**Comment by OmgImAlexis** [comment]
@jalim I use Jwilder's Nginx Proxy Docker on my test box without issue.

Make sure you have reverse proxy enabled in the settings. The default config that the nginx proxy ships with should work fine with websockets.

**Comment by jalim** [comment]
It may be my use of Basic Auth that's breaking it.  I'll just have to stick to the Medusa HTTP Auth.

**Comment by OmgImAlexis** [comment]
Ah, if you're using basic auth you'll need to use the same user/pass from memory.

**Comment by whipcracker** [comment]
For the record I'm still having the websocket issue and can replicate the problem on another seedbox with the same issue. Is this a nginx problem, basically?

**Comment by OmgImAlexis** [comment]
@whipcracker yep.

**Comment by whipcracker** [comment]
Is there an actual fix at all? Reading the prior comments sorta leads me to nowhere to be honest.

**Comment by p0psicles** [comment]
What's your current nginx config and overal setup?
