### ISSUE TITLE
Post processing as the wrong show

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#3085]
Log: https://gist.github.com/duramato/4796a37a64578468f367599883f8688f
For `Abandoned.2016.S01.1080p.VICE.WEBRip.AAC2.0.x264-RTN/Abandoned.2016.S01E06.Route.66.1080p.VICE.WEBRip.AAC2.0.x264-RTN.mkv`, it gets wrongfully processed as another show, `Route 66`.
```
report_guessit.py "Abandoned.2016.S01.1080p.VICE.WEBRip.AAC2.0.x264-RTN/Abandoned.2016.S01E06.Route.66.1080p.VICE.WEBRip.AAC2.0.x264-RTN.mkv"
# guessit: 2.1.3.dev0  rebulk: 0.8.3.dev0
? Abandoned.2016.S01.1080p.VICE.WEBRip.AAC2.0.x264-RTN/Abandoned.2016.S01E06.Route.66.1080p.VICE.WEBRip.AAC2.0.x264-RTN.mkv
: title: Abandoned
  year: 2016
  season: 1
  screen_size: 1080p
  format: WEBRip
  audio_codec: AAC
  audio_channels: 2.0
  video_codec: h264
  video_encoder: x264
  release_group: RTN
  alias: Abandoned 2016
  episode: 6
  episode_title: Route 66
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 0.85474896431
```

**Comment by medariox** [comment]
Doesn't look like a guessit issue. Do you have more debug logs?

**Comment by duramato** [comment]
Those are all the logs for that file. All other files in the season "pack" processed fine.
I have both an ` Abandoned 2016` a `Route 66` in my shows, and what I _**think**_ is happening is Medusa passes the show's titles as expected titles for guessit and guessit uses the episode title as the valid show title eventough the show title in the release name was also in the expected titles passed.

**Comment by medariox** [comment]
That shouldn't be the case, guessit either uses the alias (first) or the title. Never the episode_title.

**Comment by OmgImAlexis** [comment]
PING: @medariox @duramato

**Comment by thompatry** [comment]
I just had this issue with Criminal Minds Beyond Borders. GuessIt shows the show correctly. The debugs logs tries to put it in Criminal Minds Suspect Behavior. What occurs after guessit runs?

**Comment by medariox** [comment]
@thompatry 
The show parses correctly for me. You need to post the relevant debug logs, otherwise we can't help you.
