### ISSUE TITLE
[ FEATURE ] Add xspeeds.eu torrent provider

### ISSUE THREAD

**Issue by jtwill** [pymedusa/Medusa#3093]
Xspeeds.eu is one of the largest private general trackers, it has great pre-times, and it has all unRARed content. I'm actually surprised that it is not already supported by the various Sick- forks.

It currently has open signups, so if any developers are lacking accounts, now is the time to get one:

https://www.reddit.com/r/OpenSignups/comments/6zkj8y/open_xspeeds_general/

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
