### ISSUE TITLE
[ FEATURE ] add x[BiT] as a provider (have rss and api)

### ISSUE THREAD

**Issue by scriptzteam** [pymedusa/Medusa#3095]
**https://xbit.pw/readme**

```Base-page search:
https://xbit.pw/?search=ubuntu

Base-RSS:
https://xbit.pw/rss

Base-RSS search:
https://xbit.pw/rss?search=ubuntu

Base-RSS search with limits number of output:
https://xbit.pw/rss?search=ubuntu&limit=5

Basic magnet view:
https://xbit.pw/?id=1

Basic magnet files view:
https://xbit.pw/?files=1&id=1

Recently discovered files:
https://xbit.pw/files

Stats page:
https://xbit.pw/stats

---------------------------------------------------------------

Json-API with search and limit output (limit can be max. 100):
https://xbit.pw/api?search=ubuntu&limit=3

Json-API latest 1000:
https://xbit.pw/api

---------------------------------------------------------------

:)

```

**Comment by medariox** [comment]
Looks like a nice addition! Any way to limit the results to TV only?

**Comment by scriptzteam** [comment]
Sure, testing RSS first then api and main index will have these too :)

You can test it meanwhile -->> https://xbit.pw/rss_cat?cat=TV-HD-X264&search=-DIMENSION

**Comment by scriptzteam** [comment]
Any luck on this ? :)

**Comment by medariox** [comment]
@scriptzteam 
This is next on my list. The API is awesome!

Just 2 requests if possible:
- Category search for the API
- Multiple category search (we want all TV) for RSS and/or API

Any chance to have this implemented?

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
