### ISSUE TITLE
Cookie required when configuring custom provider

### ISSUE THREAD

**Issue by DazzFX** [pymedusa/Medusa#3096]
Branch: master
Commit: 3f23fd272652b10cf781e3058fee50daf79f11b6Version: v0.1.15
Database: 44.8
Python Version: | 2.7.13 (default, Dec 18 2016, 22:44:40) [GCC 4.9.3 20150311 (prerelease)]
SSL Version: | OpenSSL 1.0.2j 26 Sep 2016
OS: | Linux-3.10.102-armv7l-with-glibc2.4
Locale: | en_US.UTF-8

Trying to add custom provider, EZTV.  I don't use a login, just linking to the RSS feed.  When I try to add the site, it's requiring a cookie, something I don't recall having to do w/SR.   When I put all of the details in except the cookie and hit add, I get an error box stating "No Cookies added from ui for provider: EZTV".  Shouldn't this be optional or has something changed requiring cookies to be set?

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/3097

**Comment by p0psicles** [comment]
Tnx @DazzFX

**Comment by medariox** [comment]
Fixed in develop, thanks again!
