### ISSUE TITLE
Fail detection of episode number

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#3105]
Hi, 
is it normal that Medusa can't snatch an episode because the episode number is interpreted as episode_title ?
A lot of teams uses S02 - 23 instead of  S02E23.

Thanks for your work !

You can find below, guess it reports for both filenames :D 

Used by teams 
```
For: [DefinitelyNotMe] Boku no Hero Academia S02 - 23 VOSTFR [1080p].mkv
GuessIt found: {
    "release_group": "DefinitelyNotMe",
    "title": "Boku no Hero Academia",
    "season": 2,
    "episode_title": "23",
    "subtitle_language": "French",
    "screen_size": "1080p",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```
Detected by medusa
```
For: [DefinitelyNotMe] Boku no Hero Academia S02E23 VOSTFR [1080p].mkv
GuessIt found: {
    "release_group": "DefinitelyNotMe",
    "title": "Boku no Hero Academia",
    "season": 2,
    "episode": 23,
    "subtitle_language": "French",
    "screen_size": "1080p",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

**Comment by medariox** [comment]
Is this a common pattern? If that's the case, you should report it to guessit as well.

**Comment by IDerr** [comment]
Yes it is. 
All big teams in anime are using this (I don't know why...)
ex: Horriblesubs, PuyaSubs
I'll report it to guessit :)

Thanks for your answer

**Comment by OmgImAlexis** [comment]
@IDerr was this ever submitted to guessit? If so can you please provide us with PR link so we can close since after it's fixed.

**Comment by IDerr** [comment]
In fact, it has been fixed, I just forgot to close this issue.

Sorry about that :(
