### ISSUE TITLE
Custom torrent providers information lost after restart

### ISSUE THREAD

**Issue by medariox** [pymedusa/Medusa#3130]
After restart **RSS URL** and **Cookies (optional)** are missing from the custom provider. Latest develop.

**Comment by medariox** [comment]
This issue is not caused by the config migration.

To reproduce:
- Add a custom torrent provider
- Restart

RSS URL and Cookies (optional) information will be lost.

**Comment by p0psicles** [comment]
Can you explain which issues still remain?

**Comment by p0psicles** [comment]
Oh ok

**Comment by medariox** [comment]
Yeah, this is probably an older bug... custom NZB providers could be affected as well (didn't try yet).

**Comment by p0psicles** [comment]
Can you check if the information is correctly stored in your config.ini?

**Comment by medariox** [comment]
Yes, they are correctly stored before the restart. Just get back to default it seems. I think something triggers a save in custom providers (probably some JS code). Add the provider -> restart -> go to custom providers and switch providers around a bit -> restart. After that all information should be gone besides the provider name. I hope you can reproduce it this way.

**Comment by p0psicles** [comment]
Yeah I see where it's going wrong. During loading of the config and recreating the providers. Don't think there's anything wrong with the frond end. But not sure. tnx

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/3148
