### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Disney Channel (DE)

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#3132]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@40a598ca96b1c849723132cc1d0b0778c73cbf3b
**Link to Log**: https://gist.github.com/ba1390b38eff45da42304178c128b97c
### ERROR
<pre>
2017-09-23 14:41:59 ERROR    Thread-18 :: [40a598c] Missing time zone for network: Disney Channel (DE)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by andersjohansson3** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]`
**Operating System**: `Linux-3.2.40-i686-with-glibc2.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@75951e66ac8af38bad7f545095bf61c34c9e65d3
**Link to Log**: https://gist.github.com/7819af5e2432c91bc9f5c29a624ff5af
### ERROR
<pre>
2017-10-20 09:14:21 ERROR    Thread-16 :: [75951e6] Missing time zone for network: Discovery Channel (UK)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
