### ISSUE TITLE
Multiple download error

### ISSUE THREAD

**Issue by lilp69** [pymedusa/Medusa#3137]
Hello, sometimes Medusa snatch 2 episodes and not only one. So I download two file and not only one.
For exemple : 
/Series/American Horror Story/Season 07/American Horror Story - S07E04 - 11-9 - 720p HDTV.mkv
/Series/American Horror Story/Season 07/American Horror Story - S07E04 - 11-9.mkv

Master/v0.1.15
Ubuntu 14

**Comment by medariox** [comment]
Are you sure that the first download wasn't replaced by the seconde one because of your quality settings?

**Comment by lilp69** [comment]
In my download folder, I have only one file, but after renaming process and link, in /Series/American.../ I have two files.

**Comment by medariox** [comment]
Are you using Symbolic Link as post-process method? What are your quality settings? You need to tell us a bit more about your setup, otherwise we aren't able to reproduce your issue.

**Comment by lilp69** [comment]
I use HardLink for keep sharing file after moving and renaming.
My quality settings are on Preferred quality : HD
