### ISSUE TITLE
Sizes display N/A in manual search for all NZB providers

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#3140]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** #dc8382b
**OS:** Windows
**What you did:**  Manual search an episode
**What happened:**  No sizes listed for any results.  All come up N/A
**What you expected:**  Sizes to be displayed
**Logs:**
```
N/A
```
![image](https://user-images.githubusercontent.com/1867464/31046001-b30d5952-a5be-11e7-85d9-a148dc2930f2.png)

**Comment by medariox** [comment]
Which provider are we talking about here?

**Comment by labrys** [comment]
All providers for me (all nzb ofc).
