### ISSUE TITLE
Medusa with jackett

### ISSUE THREAD

**Issue by lilp69** [pymedusa/Medusa#3154]
Hi,
How add a custom torrent's proviers in Medusa with Jacket?

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/3081

**Comment by lilp69** [comment]
Ok thanks. I think it's only for NZB search and not torrent

**Comment by medariox** [comment]
You're welcome! Jackett supports both, NZB and torrent providers.
