### ISSUE TITLE
Episode thumbnails are not being created

### ISSUE THREAD

**Issue by komerdoor** [pymedusa/Medusa#3155]
**Branch/Commit:** 3f23fd2

**OS:** Debian Stretch (4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64)

**What you did:** Added new episodes. Tried "Force Full Update".

**What happened:** Does not retrieve episode thumbnails. Log reports: "No thumb is available for this episode, not creating a thumb"

**What you expected:** The episode thumbnails to be created. They do exists on tvdb as can be seen at: https://www.thetvdb.com/?tab=season&seriesid=327109&seasonid=708372&lid=7

**Logs:**

> 2017-10-11 22:19:52 DEBUG    SHOWQUEUE-REFRESH :: [3f23fd2] 327109: Formatting pattern: %SN - S%0SE%0E - %EN -> Mr. Mercedes - S01E07 - 007 - Willow Lake
> 2017-10-11 22:19:52 DEBUG    SHOWQUEUE-REFRESH :: [3f23fd2] Metadata provider KODI 12+ creating episode thumbnail for Mr. Mercedes - S01E07 - 007 - Willow Lake
> 2017-10-11 22:19:52 DEBUG    SHOWQUEUE-REFRESH :: [3f23fd2] **No thumb is available for this episode, not creating a thumb**

More at: https://pastebin.com/mJf2uDtU

**Comment by medariox** [comment]
Fixed in develop with https://github.com/pymedusa/Medusa/pull/3156. Thanks for the bug report!
