### ISSUE TITLE
Medusa fails to delete .srt .nfo -thumb.jpg files when replacing an episode with preferred quality

### ISSUE THREAD

**Issue by jtwill** [pymedusa/Medusa#3157]
**Branch/Commit:**
Medusa Info:  Branch: master
Commit: 3f23fd272652b10cf781e3058fee50daf79f11b6

**OS:**
OS: Linux-4.13.4-1-ARCH-x86_64-with-glibc2.2.5

**What you did:**
Medusa replaced an allowed quality episode with a preferred quality episode

This issue has happened with many different series and episodes on my computer (all of them,
in fact). But I have just included one specific example in this report.

**What happened:**
Medusa deleted the .mkv file associated with the old quality episode being replaced,
but did NOT delete associated .srt .nfo -thumb.jpg files

**What you expected:**
Medusa should have deleted all the files associated with the old quality episode that
is being replaced. I switched to Medusa from an older version of Sickrage and SR
used to delete those files.

Note that I have PostProcessing / Rename episode using the Episode Naming settings? unchecked
(disabled) so the original filenames are kept, but there is a custom renaming pattern defined. Medusa
should respect the unchecked rename setting despite having a custom renaming pattern defined, but
I thought I should mention this in case there is a bug in Medusa under those conditions.

**Logs:**
```
Medusa Configuration
Medusa Info:  Branch: master
Commit: 3f23fd272652b10cf781e3058fee50daf79f11b6
Version: v0.1.15
Database: 44.8
Python Version: 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
SSL Version:  OpenSSL 1.1.0f 25 May 2017
OS: Linux-4.13.4-1-ARCH-x86_64-with-glibc2.2.5
Locale: en_US.UTF-8
   
   
User: sysop
Program Folder: /opt/Medusa
Config File:  /home/sysop/.medusa/config.ini
Database File:  /home/sysop/.medusa/main.db
Cache Folder: /home/sysop/.medusa/cache
Log Folder: /home/sysop/.medusa/Logs
Arguments:  

[
    "--quiet",
    "--nolaunch",
    "--daemon",
    "--datadir",
    "/home/sysop/.medusa"
]

[medusa-issue.log](https://github.com/pymedusa/Medusa/files/1382968/medusa-issue.log)

```

**Comment by medariox** [comment]
Thanks for the report, this is indeed a bug. It should be fixed with https://github.com/pymedusa/Medusa/pull/3158

**Comment by medariox** [comment]
Added to develop, will be available with the next release.
