### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by lilp69** [pymedusa/Medusa#3161]
### Before submitting your issue:
Hi,
My Medusa process use 86% of my CPU all times.

**Branch/Commit:Mako: 0.1043s | Branch: master
**OS:Ubuntu 14.04.5

https://pastebin.com/y0XdLT4s

**Comment by ratoaq2** [comment]
Do you have a lot of missing subtitles? Which subtitle providers you're using? 

The subtitle search using subliminal + guessit can be cpu intensive depending the number of missing subs and the subtitle providers you're using.

**Comment by lilp69** [comment]
Yes, I think I have a lot of missing subtitles. I use addic7ed, opensubtitles for providers.

**Comment by OmgImAlexis** [comment]
Closing as this is normal behaviour when background tasks are running.
