### ISSUE TITLE
[ FEATURE ] add snatched as option in Schedule to see recent (failed) snatches

### ISSUE THREAD

**Issue by bobbysteel** [pymedusa/Medusa#3170]
This is one of the things I miss from Sickrage. Would be nice to have this back.
https://github.com/SickRage/SickRage/blob/72f937b3667166801ff595ea674a7877dd8b67cd/gui/slick/views/schedule.mako

**Comment by medariox** [comment]
@sharkykh Is it ok with you if we just use your code?

**Comment by sharkykh** [comment]
@medariox Sure, but I only did the UI option.
[This is the commit](https://github.com/SickRage/SickRage/commit/8c9475c3ac1c82ebe49ea114007dd9ce4eaea81c) that added the actual feature.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
