### ISSUE TITLE
[APP SUBMITTED]: Unable to create the folder /media/ssd/Shows/The End of the F---ing World, can't add the show

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#3177]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@58cdc48628ee8c5a98d220e0e3a2b97f25377afa
**Link to Log**: https://gist.github.com/a1b3e6fa750b2b7a714c5b4c80676598
### ERROR
<pre>
2017-10-25 15:03:23 ERROR    Thread-18 :: [58cdc48] Unable to create the folder /media/ssd/Shows/The End of the F---ing World, can't add the show
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
Log was already changed to info level.
