### ISSUE TITLE
[ FEATURE ] Discord notification

### ISSUE THREAD

**Issue by asock** [pymedusa/Medusa#3181]
Could this be added? I currently use this in Sickrage and would like to migrate. Or is it already possible and I'm just missing something? Thanks!

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.

**Comment by UNiXMIT** [comment]
A workaround to have this working now is to create a private twitter account and have Medusa post notifications as new tweets to that account. Then setup IFTTT to send a JSON formatted POST to a Discord Webhook everytime a new tweet is posted on that account. Works a treat for now.

**Comment by p0psicles** [comment]
Aah yes, I forgot about this

**Comment by medariox** [comment]
Added with https://github.com/pymedusa/Medusa/pull/7189. Will be available with the next release.

**Comment by wallopthecat** [comment]
This feature is awesome. Just wondering about where to start digging into `requests via discord bot`.

There is already https://github.com/physk/MediaButler with radarr/sonarr/Tautulli support, and https://github.com/v0idp/Mellow/ with all of the aforementioned plus Ombi support. 

Would my efforts be best served adding pymedusa support to one of those projects or is this something you want to keep in-house for the local bot @p0psicles?

**Comment by p0psicles** [comment]
We have an api. And anyone can use it as he/she wishes. Np

**Comment by wallopthecat** [comment]
Turns out sickchill integration in ombi works with the mellow bot for anyone else interested in this feature 
![image](https://user-images.githubusercontent.com/28909747/69257506-ca8a4480-0b80-11ea-9393-a15705a00a54.png)
![image](https://user-images.githubusercontent.com/28909747/69257532-d413ac80-0b80-11ea-8c16-873de060c1e2.png)
