### ISSUE TITLE
[ BUG ] Medusa fails to start after update

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#3186]
The auto updater may sometimes leave Medusa in an unclean state preventing Medusa from starting or causing user interface (UI) errors.  This usually happens after changes to the UI or when a filename has changed.

**Comment by fexofenadine** [comment]
[issue 3183](https://github.com/pymedusa/Medusa/issues/3183) has some fixes/workarounds, but doesn't address the auto updater bug itself

**Comment by fexofenadine** [comment]
actually @medariox mentions a commit that might fix it?

**Comment by p0psicles** [comment]
I think labrys issue, is more about the general fault tolerance of the auto updater.

Another example. My disk was full. Running auto updater left me with a 0kb config.ini.

**Comment by fexofenadine** [comment]
yeah you're absolutely right, thanks
