### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: WATCH Disney XD

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#3187]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@42b1e5f92de75f692099a53e0f61856c15e9e206
**Link to Log**: https://gist.github.com/d6d94da97dceefd9acda094153442a17
### ERROR
<pre>
2017-10-28 05:56:51 ERROR    Thread-40 :: [42b1e5f] Missing time zone for network: WATCH Disney XD
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b22a20200cba226481fdd1f67013d2e16c333285
**Link to Log**: https://gist.github.com/0e63a4ecd89fb5ab658e92435d7d951b
### ERROR
<pre>
2017-10-29 17:06:57 ERROR    Thread-28 :: [b22a202] Missing time zone for network: WATCH Disney XD
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
Added

**Comment by jrozelle** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
**Link to Log**: https://gist.github.com/8b95f80784459f7db6519a635ac8f8ce
### ERROR
<pre>
2017-11-09 17:39:42 ERROR    Thread-16 :: [b16e0e5] Missing time zone for network: Disney XD
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
