### ISSUE TITLE
Anime status goes off after editing existing Anime show whitelist

### ISSUE THREAD

**Issue by hergonoway** [pymedusa/Medusa#3192]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
Master : Latest (21/10)

**OS:**
Docker (Linuxserver.io)

**What you did:**
Clicked "EDIT" button on an existing Anime show page (Kino no Tabi (2017)) and change settings.

**What happened:**
I've added a release group manually "Horriblesubs" then clicked "add to whitelist" , everything seems fine, the whitelist was visually updated, then I've clicked on save button, got the correctly saved notification, then being redirect to the Anime show page, but the show wasn't considered as an anime anymore (red cross next to anime)

**Workaround ?**

Unfortunatly no, only removing the show, adding it again did the job.

When I try to set the show as an Anime again with whitelisted release group, I go to the edit page of the show and check the box of "is an anime ?", but, unlike the same menu while adding a new show, the whitelist menu doesn't appear. So I have to save the parameters, go back to the show page, then click "EDIT" again, but from there the problem explained above do the same thing. If I add a whitelisted release groupe the show is not an Anime anymore.

**Comment by p0psicles** [comment]
I can't reproduce this issue at all. Did the same only different SHOW. Added horriblesubs and saved. The anime flag stayed enabled.

Any logs maybe at the time? Debug if possible.

**Comment by p0psicles** [comment]
I can't reproduce this issue at all. Did the same only different SHOW. Added horriblesubs and saved. The anime flag stayed enabled.

Any logs maybe at the time? Debug if possible.

**Comment by hergonoway** [comment]
damn I've encountered again this issue, but there's no obvious repeatability. I'll catch the log when it'll happen again.
