### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Movistar+

### ISSUE THREAD

**Issue by juayhi** [pymedusa/Medusa#3194]
### INFO
**Python Version**: `2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-97-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
**Link to Log**: https://gist.github.com/0a0e74d5ae748070e405862707a4507e
### ERROR
<pre>
2017-10-29 11:54:46 ERROR    Thread-16 :: [b16e0e5] Missing time zone for network: Movistar+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by juayhi** [comment]
### INFO
**Python Version**: `2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-97-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
**Link to Log**: https://gist.github.com/b8037835be80251b8bb4eb602331d7d0
### ERROR
<pre>
2017-10-30 19:47:00 ERROR    Thread-16 :: [b16e0e5] Missing time zone for network: Movistar+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
Added
