### ISSUE TITLE
[ FEATURE ] Possible new providers 

### ISSUE THREAD

**Issue by adaur** [pymedusa/Medusa#3197]
List of possible new providers to add:

- [ ] http://www.nextorrent.tv/
- [x] https://archetorrent.com/ (need an invite)
- [ ] https://ethor.net (need an invite)
- [ ] https://www.spacetorrent.pw

**Comment by bobbysteel** [comment]
Jackett is a good interim fix for handling providers not yet supported.

**Comment by hergonoway** [comment]
Hi, 

+1 bobbysteel, Jackett should be integrated more directly to medusa as Jackett, currently it's a bit tricky and not really user friendly, more like a workaround.

I don't know if you could list configured indexer from Jackett through API, that would be so awesome. Like picking up available indexer from Jackett

**Comment by adaur** [comment]
Please create a separate issue (feature request) for this. I'm not denying Jackett is useful, but I prefer having only Medusa running.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
