### ISSUE TITLE
Error: Help to refine video

### ISSUE THREAD

**Issue by Olivier6767** [pymedusa/Medusa#3201]
Branch: master
Commit: b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
Version: v0.1.17
OS: Debian

I get the error below once or twice a day.
Is this an indication of an issue with a specific video file?
If yes, how can I find out which one?

Is there anything else I can check?

Thanks.

2017-10-31 03:06:47 WARNING  SHOWQUEUE-REFRESH :: [b16e0e5] Failed to refine video
Traceback (most recent call last):
  File "/home/Services/cinema/medusa/Medusa/ext/subliminal/core.py", line 546, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/home/Services/cinema/medusa/Medusa/ext/subliminal/refiners/metadata.py", line 32, in refine
    mkv = MKV(f)
  File "/home/Services/cinema/medusa/Medusa/ext/enzyme/mkv.py", line 56, in __init__
    raise MalformedMKVError('Parsing error: %s' % e)
MalformedMKVError: Parsing error: Less than 1 bytes read (0)

**Comment by medariox** [comment]
Yes, one of your .mkv video files is malformed. Sadly there isn't a way to determine which one is faulty, but it is an episode that still needs subtitles. We should definitely improve the error message (possibly upstream).

**Comment by fernandog** [comment]
Diaoul/subliminal/pull/779/files

**Comment by Olivier6767** [comment]
I reviewed teh latest downloads and found 1 file where I cannot fast forward... So I suspect this is the faulty file.
I will re-download it.

Thanks for the hints.

**Comment by fernandog** [comment]
It recently started to complain about a lot of files. But they all are playing ok.
