### ISSUE TITLE
tvdb Scene exceptions used for tmdb shows

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#3205]
The tvdb Scene exceptions are being used for tmdb shows, becouse of id colisions.

https://github.com/pymedusa/medusa.github.io/blob/master/scene_exceptions/scene_exceptions_tvdb.json#L269-L274
My show has an id in TMDb of `73178` which matches `Two Guys a Girl and a Pizza Place` on tvdb, but it should only use exceptions for their respective indexer
![image](https://user-images.githubusercontent.com/10121067/32221308-f0efca12-be2c-11e7-9d88-0b239e05b8b5.png)

**Comment by OmgImAlexis** [comment]
@p0psicles was this fixed? If so please close.

**Comment by p0psicles** [comment]
I think its fixed. But havent verified myself. Super can you verify?

**Comment by sharkykh** [comment]
![image](https://user-images.githubusercontent.com/10238474/40203664-9b65d872-5a2e-11e8-888b-2ded231384b6.png)
