### ISSUE TITLE
Cannot push error on github automatically

### ISSUE THREAD

**Issue by zaggash** [pymedusa/Medusa#3209]
**Branch/Commit:**
```
branch: master
Commit: b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
Version: v0.1.17
Database: 44.8
--
Python Version: | 2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
SSL Version: | LibreSSL 2.5.5
OS: | Linux-3.16.0-4-amd64-x86_64-with
Locale: | Unknown.Unknown
```
**OS:**
`Using the linuxserver.io docker image.`
**What you did:**
```
I configured the github setting in the config.
I am using the "Personal access token" because I have 2FA on github.
Then, in the error message page on Medusa, I pushed the submit errors button.
```
**What happened:**
`
The notification tell me I have to setup my username and password first
`

**Logs:**
```
2017-10-31 21:50:05 WARNING  Thread-16 :: [b16e0e5] Please set your GitHub username and password in the config and enable debug. Unable to submit issue ticket to GitHub.
```

**Comment by adaur** [comment]
Same here, I'm unable to report an issue using the "Submit errors" button

**Comment by salfter** [comment]
At the risk of AOLing, it's giving me the same error, even though a username and password are set.  (I don't use 2FA with GitHub.)

**Comment by labrys** [comment]
This isn't so much a bug as a vague error message.  You need to enable Debug logging before you are able to report errors.  Really it should be two separate warning messages, one for debug logging and one for username/password.  I'll push a change to develop this weekend.
