### ISSUE TITLE
qbittorrent: Unable to set the label for Torrent

### ISSUE THREAD

**Issue by PinaColonic** [pymedusa/Medusa#3211]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
MASTER branch
commit b16e0e5eb4ded727eebd2ab2cd9683ab597662f5

**OS:** 
Linux-4.10.0-37-generic-x86_64-with-LinuxMint-18.2-sonya
running Qbittorrent 3.3.16

**What you did:**
Snatch an episode manually

**What happened:**
It worked fine successfully added torrent to qbittorrent, downloaded it, post procssed it, etc.... but threw this error about Qbittorrent and a label issue

**What you expected:**
Not an error - note in Search Settings -> Torrent Search -> Add Label to Torrent it is blank (with no spaces) - a friend of mine is seeing this same error, we both went from SickRage to pyMedusa today and are both qBittorrent users

**Logs:**
```
2017-11-01 12:55:35 ERROR    SNATCHQUEUE-MANUALSNATCH-250487 :: [b16e0e5] qbittorrent: Unable to set priority for Torrent
2017-11-01 12:55:35 INFO     SNATCHQUEUE-MANUALSNATCH-250487 :: [b16e0e5] qbittorrent: Forbidden
2017-11-01 12:55:35 ERROR    SNATCHQUEUE-MANUALSNATCH-250487 :: [b16e0e5] qbittorrent: Unable to set the label for Torrent
2017-11-01 12:55:33 INFO     SNATCHQUEUE-MANUALSNATCH-250487 :: [b16e0e5] Downloading xxxxxxx.mkv with 8 seeders and 0 leechers and size 1.91 GB from xxxx
2017-11-01 12:55:33 INFO     SNATCHQUEUE-MANUALSNATCH-250487 :: [b16e0e5] Beginning to manual snatch release: xxxxxx

I changed the torrent name and provider to xxxx for privacy.

**Comment by medariox** [comment]
Thanks for the bug report! It will be fixed with: https://github.com/pymedusa/Medusa/pull/3212

In the meanwhile, you can set any label to avoid the error.

**Comment by ripper1967** [comment]
### INFO
        **Python Version**: `2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
        **Operating System**: `Linux-4.10.0-42-generic-x86_64-with-LinuxMint-18.3-sylvia`
        **Locale**: `UTF-8`
        **Branch**: [develop](../tree/develop)
        **Database**: `44.8`
        **Commit**: pymedusa/Medusa@7813c7956c2efb350f2589cc783064575dbf801e
        **Link to Log**: https://gist.github.com/43deb47deedebc108d07b6a4f4f313cc
        ### ERROR
        <pre>
2017-12-09 18:28:51 ERROR    SNATCHQUEUE-MANUALSNATCH-164541 :: [7813c79] qbittorrent: Unable to set the pause for Torrent
</pre>
        ---
        _STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MotleyC** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/f066807d3a338906250c0cd9c9bf6715
### ERROR
<pre>
2018-05-09 07:14:19 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [77b2091] qbittorrent: Unable to set the pause for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
@MotleyC Fixed in #4169.

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/e6758eed80bcf750910ed229426d1999
### ERROR
<pre>
2018-05-12 11:47:28 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [77b2091] qbittorrent: Unable to set the pause for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MotleyC** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/5d0bd85dc3133a6c296ef65b74dbe75c
### ERROR
<pre>
2018-05-13 06:50:01 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [77b2091] qbittorrent: Unable to set the pause for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bergonzzi** [comment]
### INFO
**Python Version**: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/ba725103b441770751ae87e8e3ed7eaf
### ERROR
<pre>
2018-05-13 15:29:25 ERROR    SEARCHQUEUE-BACKLOG-289108 :: [77b2091] qbittorrent: Unable to set the pause for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
