### ISSUE TITLE
Storage of Custom Newznab provider media categories

### ISSUE THREAD

**Issue by bobbysteel** [pymedusa/Medusa#3215]
[Using latest docker image of master from linuxserver/medusa]

Editing Custom Newznab providers pulls their categories properly and "update categories" works as expected in the UI to store the correct categories for each provider.

This persists until restart, at which point these are lost. While running and after shut down, I have grep'ped for a particular sample category and cannot find that string anywhere in any config, so it seems it's not being written properly into a config for the custom Newznab provider itself.

**Comment by medariox** [comment]
Fixed since ages
