### ISSUE TITLE
Should FINDPROPERs only snatch proper releases from same streaming service ?

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#3227]
A AMZN release can't be propered by a p2p release right (don't have streaming service)?

Should it check the `stream services` from guessit and compare it ?
So maybe only proper ifs AMZN (torrent/nzb) == AMZN (snatched history)
In case there is no streaming services available, don't proper it and the comparison will be false

@duramato

**Comment by medariox** [comment]
Added to develop.
