### ISSUE TITLE
Missing Network Icons for rtejr and VRV (low priority)

### ISSUE THREAD

**Issue by PinaColonic** [pymedusa/Medusa#3231]
I have some shows that are under the RTÉjr network (Puffin Rock) and also the VRV network (Harmonquest).   

They currently show the question mark for provider in shows list.   Obviously this is super low priority but figured I'd open an issue for it so it is "out there".   Thanks!

edit: changed the word provider to network, since these are networks.

**Comment by fernandog** [comment]
@duramato can you add this ones please?
