### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Anime OAV

### ISSUE THREAD

**Issue by mhertel** [pymedusa/Medusa#3236]
### INFO
**Python Version**: `2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]`
**Operating System**: `Linux-4.9.30-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
**Link to Log**: https://gist.github.com/dd2993868c6ff0d3c15909b4739fd8a9
### ERROR
<pre>
2017-11-06 10:23:12 ERROR    Thread-285 :: [b16e0e5] Missing time zone for network: Anime OAV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
added
