### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Pay-Per-View

### ISSUE THREAD

**Issue by ITOpsMgr** [pymedusa/Medusa#3238]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.8-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
**Link to Log**: https://gist.github.com/c8a5479d775ee163ead05f88820e19b3
### ERROR
<pre>
2017-11-06 19:23:39 ERROR    Thread-16 :: [b16e0e5] Missing time zone for network: Pay-Per-View
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
added
