### ISSUE TITLE
KODI Metadata NFO has TVDB v1 URL

### ISSUE THREAD

**Issue by Fietspomp86** [pymedusa/Medusa#3242]
Switched from Sickrage to Medusa few days ago, must say I love it!
Just saw this when adding a new show, the NFO created by Medusa has the old TVDB v1 url inside, which makes KODI fall into error. (401 not authorized is what the TVDB v1 URL returns)

I know Medusa uses the new API to search shows etc but the metadata is not correct.
Example show Lucifer:
NFO contains this URL:
`<url>https://api.thetvdb.com/295685/all/en.zip</url>`
But it should be:
`<url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:295685}|Content-Type=application/json</url>`

Running the stable/master version by the way, from git.

[More info on the Kodi forum (ofc already known here)](https://forum.kodi.tv/showthread.php?tid=323588)

**Comment by p0psicles** [comment]
There wasn't an alternative up until recently. We'll make the update. Tnx for sharing.

**Comment by h3llrais3r** [comment]
Tried to make the changes but I can't seem to get the escaped quotes the nfo file.
Result for now is as follows:
![image](https://user-images.githubusercontent.com/1945295/33220332-a81d10aa-d147-11e7-8c86-470f8404a233.png)

Any idea if this is also ok? Or does it really need to be with escaped quotes?

**Comment by p0psicles** [comment]
You can use requests URL encode for the json string.

**Comment by p0psicles** [comment]
Just create Pr. I'll help out

**Comment by h3llrais3r** [comment]
Done, but I'm not sure the url encode will work, since all `&` are replaced by `&amp;`.
Even when I'm adding the escaped quotes myself, it stil translates the `&` from `&quot;` to `&amp;quot;` in the nfo file.
