### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: USA Network

### ISSUE THREAD

**Issue by jrozelle** [pymedusa/Medusa#3249]
### INFO
**Python Version**: `2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
**Link to Log**: https://gist.github.com/d5c842ec51d347f55a3279d9f329fdc0
### ERROR
<pre>
2017-11-09 17:39:42 ERROR    Thread-16 :: [b16e0e5] Missing time zone for network: USA Network
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
Already in the list USA Network:US/Eastern

**Comment by OmgImAlexis** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.14.13-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
**Link to Log**: https://gist.github.com/617edfb1ba048686cc5434ba56356d42
### ERROR
<pre>
2018-04-22 00:24:50 ERROR    Thread_0 :: [1a8dc66] Missing time zone for network: Hub Network
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rtrevino70** [comment]
### INFO
**Python Version**: `2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`
**Operating System**: `Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/16c9318d320225e0f71cde39e470bda8
### ERROR
<pre>
2018-09-20 21:37:58 ERROR    Thread_9 :: [4614efc] Missing time zone for network: USA Network
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rtrevino70** [comment]
### INFO
**Python Version**: `2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`
**Operating System**: `Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/d5e5c66359c64f796d6075beff0d843a
### ERROR
<pre>
2018-09-20 22:25:22 ERROR    Thread_0 :: [4614efc] Missing time zone for network: USA Network
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Dale-J** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/c631df856b3979e416ffdabe43ddf3c7
### ERROR
<pre>
2018-10-24 23:02:46 ERROR    Thread_1 :: [4614efc] Missing time zone for network: USA Network
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
