### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: FOX (US)

### ISSUE THREAD

**Issue by jrozelle** [pymedusa/Medusa#3251]
### INFO
**Python Version**: `2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
**Link to Log**: https://gist.github.com/b96491c5c5ff3222b878a30f18c9ef3d
### ERROR
<pre>
2017-11-09 17:39:42 ERROR    Thread-16 :: [b16e0e5] Missing time zone for network: FOX (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
Already in the list FOX (US):US/Eastern
