### ISSUE TITLE
Cant start after install on Synology DSM 6

### ISSUE THREAD

**Issue by Diablobait** [pymedusa/Medusa#3254]
Hello, after i installed on sickbeard-custom and put the correct url of the git, install correct but after cant start the service, im running DSM 6.

**Comment by NicoLeOca** [comment]
Hi,

I just tried on mine.
I faced the same issue and fixed it by restarting the NAS right after the installation and before launching the app for the first time (uncheck the appropriate box during installation).

I don't know which branch you instend to install but it is safe to use develop and it usually has new features in advance.

Welcome on board!

**Comment by bobbysteel** [comment]
What do you mean by it doesn't start? Are you using docker? If so can you ssh in and show the container logs?

**Comment by ward0** [comment]
running DS213J with DSM6.X(latest) and having no problems running sickbeard-custom.

Do you have some linux skills? Things have changed since DSM5...

**Comment by MGaetan89** [comment]
I had the same issue, and @NicoLeOca helped me.
But I didn't see anything in the Log Center application :/

**Comment by ward0** [comment]
@MGaetan89 seems normal that you don't see anything in the log center because the user running Medusa doesn't have rights to write anything into a log...
