### ISSUE TITLE
Any plans for making the ui faster?

### ISSUE THREAD

**Issue by Hellowlol** [pymedusa/Medusa#3258]
For some reason i couldnt download the report so here is some images of it.
![image](https://user-images.githubusercontent.com/1214134/32682885-c6773e20-c677-11e7-924b-34177ebc0633.png)

![image](https://user-images.githubusercontent.com/1214134/32682896-d1b5bf00-c677-11e7-81f0-a310e7a4396e.png)

![image](https://user-images.githubusercontent.com/1214134/32682910-df732c9a-c677-11e7-9ad5-14c0c5a317ad.png)

Medusa Info: | Branch: masterCommit: b16e0e5eb4ded727eebd2ab2cd9683ab597662f5Version: v0.1.17Database: 44.8
-- | --
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
SSL Version: | OpenSSL 1.0.2j 26 Sep 2016
OS: | Windows-7-6.1.7601-SP1
Locale: | nb_NO.cp1252

```
PASTE LOGS HERE
```

**Comment by p0psicles** [comment]
Yes, and those plans have been there for a long time already.

We've even already started on a new restful backend (apiv2) that could be used for a faster new frontend. We just lack the resources.

**Comment by OmgImAlexis** [comment]
Closing this as the Vue changes will likely fix most of this.
