### ISSUE TITLE
Error while postprocess

### ISSUE THREAD

**Issue by lilp69** [pymedusa/Medusa#3259]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Mako: 0.0240s | Branch: master
OS : Debian (CT on Proxmox with ZFS)
```
PASTE LOGS HERE

Processing succeeded for /Downloads/torrents/The.Walking.Dead.S08E02.VOSTFR.1080p.WEB-DL.DD5.1.H264-ARK01.mkv
2017-11-11 10:21:55 INFO     Thread-17 :: [b16e0e5] Exception caught in subliminal.scan_video, subtitles couldn't be refreshed for /TvShows/The Walking Dead/Season 08/The Walking Dead - S08E02 - The Damned.mkv
2017-11-11 10:21:55 WARNING  Thread-17 :: [b16e0e5] Unable to scan video: /TvShows/The Walking Dead/Season 08/The Walking Dead - S08E02 - The Damned.mkv. Error: Path does not exist
2017-11-11 10:21:55 INFO     Thread-17 :: [b16e0e5] Trying to clean any empty folder under /TvShows/The Walking Dead/Season 08
2017-11-11 10:21:55 INFO     Thread-17 :: [b16e0e5] This download is marked a priority download so I'm going to replace an existing file if I find one
2017-11-11 10:21:55 INFO     Thread-17 :: [b16e0e5] New size: 1.65 GB
2017-11-11 10:21:55 INFO     Thread-17 :: [b16e0e5] New file: /Downloads/torrents/The.Walking.Dead.S08E02.VOSTFR.1080p.WEB-DL.DD5.1.H264-ARK01.mkv
2017-11-11 10:21:55 INFO     Thread-17 :: [b16e0e5] Processing /Downloads/torrents/The.Walking.Dead.S08E02.VOSTFR.1080p.WEB-DL.DD5.1.H264-ARK01.mkv
```

**Comment by medariox** [comment]
Is it only happening with this file? Does this path exist? `/TvShows/The Walking Dead/Season 08/The Walking Dead - S08E02 - The Damned.mkv`
What are your settings? More information, please.

**Comment by lilp69** [comment]
No, it's happening for all terminate files.
Which settings do you need ?
I'm on a container on proxmox with HDD data on Zfs.

**Comment by medariox** [comment]
Please enable debug logs and post the full log.

**Comment by lilp69** [comment]
Here it's de debug log : https://pastebin.com/Rsb1UhM2

**Comment by medariox** [comment]
`Processing failed for /mnt/Downloads/torrents/Bla.Bla.S09E06.VOSTFR.720p.HDTV.x264-FDS.mkv: Unable to create the show directory`

It seems that you don't have the correct permissions set.

**Comment by lilp69** [comment]
it's my permissions : drwxrwxr-x  6 root root  7 nov.  10 17:02 Downloads
drwxrwxr-x 72 1000 1000 76 nov.  11 10:35 TvShows

I put medusa user into root group.

**Comment by medariox** [comment]
Please switch to [this branch](https://github.com/pymedusa/Medusa/tree/imp-log-pp) and reproduce the error, then post the full debug logs.

**Comment by lilp69** [comment]
https://pastebin.com/eU3xk6vQ

**Comment by medariox** [comment]
That's not the correct branch...

**Comment by lilp69** [comment]
git checkout imp-log-pp
Alreary on  'imp-log-pp'
Update to date 'origin/imp-log-pp'.

**Comment by medariox** [comment]
At the beginning of your logs is `[commit number]`. It should be `[a2f15e0]`.

**Comment by lilp69** [comment]
It's not git checkout imp-log-pp for switch to it?

**Comment by medariox** [comment]
It is, but somehow you are not on that branch it seems...

**Comment by lilp69** [comment]
:( and log is not good enough in this branch

**Comment by medariox** [comment]
The current log doesn't contain the reason why it's failing. Maybe you can manually copy the modified files over if you are unable to switch branch?

**Comment by lilp69** [comment]
I haven't any log now

**Comment by lilp69** [comment]
Here we go : https://pastebin.com/cXQvefhk

**Comment by medariox** [comment]
Okay, now you need to add the show... It needs to produce the same error as the first logs.

**Comment by lilp69** [comment]
https://pastebin.com/ajDQ4f58

**Comment by medariox** [comment]
Like I initially thought, you don't have the correct permissions. `Error: [Errno 13] Permission non accordée`. Try to run as root?

**Comment by lilp69** [comment]
I don't understand I create a SMB share and mount it : 
smb.conf : [TvShows]
comment = TvShows
browsable = yes
path = /tank/TvShows
guest ok = yes
read only = no
writeable = yes

Mount cifs on CT  :mount.cifs //192.168.0.11/TvSHows /mnt/TvShows/ -o guest

**Comment by lilp69** [comment]
Manually I can create, delete file into each folder, but postprocess still doens't work : https://pastebin.com/h84YQLRg

**Comment by lilp69** [comment]
I've this error : 

2017-11-12 10:01:37 ERROR    Thread-17 :: [a2f15e0] Failed creating /mnt/TvShows/The Big Bang Theory/Season 10/ : OSError(13, 'Permission non accord\xc3\xa9e')
Traceback (most recent call last):
  File "/opt/medusa/medusa/helpers/__init__.py", line 459, in make_dirs
    os.mkdir(sofar)
  File "/opt/medusa/medusa/init/filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
OSError: [Errno 13] Permission non accordée: '/mnt/TvShows/The Big Bang Theory/Season 10/'

**Comment by fernandog** [comment]
Which user runs Medusa? Check the startup script you set up

**Comment by lilp69** [comment]
It's user medusa. 
It's how I install Medusa : 
addgroup --system medusa && adduser --disabled-password --system --home /var/lib/medusa --gecos "Medusa" --ingroup medusa medusa
mkdir /opt/medusa && git clone https://github.com/pymedusa/Medusa.git /opt/medusa
 chown -R medusa:medusa /opt/medusa
cp -v /opt/medusa/runscripts/init.systemd /etc/systemd/system/medusa.service
chown root:root /etc/systemd/system/medusa.service && chmod 644 /etc/systemd/system/medusa.service

**Comment by lilp69** [comment]
Postprocess don't make a symlink, but copy and delete original file.
My config is like : symlink.
The log :https://pastebin.com/gvVUNt3w

**Comment by medariox** [comment]
That means that Medusa failed to create the symlink. There are multiple reasons for that: wrong permissions, no rights, OS doesn't support it and so on. You should have gotten a warning with the reason why the symlink failed.

**Comment by lilp69** [comment]
It seems post process works because I have : mr.robot.s03e06.internal.720p.web.h264-strife.mkv -> /mnt/TvShows/Mr. Robot/Season 03/Mr. Robot - S03E06 - eps3.5_kill-process.inc.mkv
But file in /mnt/TvShows/Mr.... can't be read.

**Comment by lilp69** [comment]
I've this issue : 
 Unable to move file /mnt/Downloads/torrents/The.Last.Man.on.Earth.S04E07.FASTSUB.VOSTFR.720p.HDTV.x264-FDS.mkv to /mnt/TvShows/The Last Man On Earth/Season 04: IOError(2, 'Aucun fichier ou dossier de ce type')
Traceback (most recent call last):
  File "/opt/medusa/medusa/post_processor.py", line 1202, in process
    app.MOVE_ASSOCIATED_FILES, app.USE_SUBTITLES and ep_obj.series.subtitles)
  File "/opt/medusa/medusa/post_processor.py", line 491, in post_process_action
    action=action, subtitle_action=subtitle_action, subtitles=subtitles)
  File "/opt/medusa/medusa/post_processor.py", line 418, in _combined_file_operation
    file_list += self.list_associated_files(file_path, subtitles_only=True, refine=True)
  File "/opt/medusa/medusa/post_processor.py", line 190, in list_associated_files
    processed_names += filter(None, (self._rar_basename(file_path, files),))
  File "/opt/medusa/medusa/post_processor.py", line 300, in _rar_basename
    for rar in rars:
  File "/opt/medusa/medusa/post_processor.py", line 298, in <genexpr>
    rars = (x for x in files if rarfile.is_rarfile(x))
  File "/opt/medusa/ext/rarfile.py", line 404, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/opt/medusa/ext/rarfile.py", line 389, in _get_rar_version
    with XFile(xfile) as fd:
  File "/opt/medusa/ext/rarfile.py", line 2401, in __init__
    self._fd = open(xfile, 'rb', bufsize)

**Comment by lilp69** [comment]
I see sometimes (a lot of) Medusa don't wait download finished for post-process, so I've corrupted files : https://pastebin.com/KKmYq5dA

**Comment by medariox** [comment]
Medusa can't know when the files are finished downloading unless there is a sync file that acts as a marker. You need to have 2 separate folders, one for incomplete download and one for the finished download (which should also be the post-processing folder).

**Comment by lilp69** [comment]
My download are in /tank/Downloads/torrents and when it's finished medusa post-process them to /tank/TvShows/.
I use Rtorrents. Need to configure something else? Maybe different?

**Comment by medariox** [comment]
Hardlink the files to another folder once they are complete with rTorrent. That folder should be your post-processing folder and use move as processing method.
![img](https://snapr.pw/i/59de6ac04c.png)

**Comment by lilp69** [comment]
This config don't want to save, each time I put path to finished download I've : Autotools direcotry to finished downloads not set.
Directory exist and have 777 right.
