### ISSUE TITLE
Medusa sends Jackett TORRENT result to SABNZBD

### ISSUE THREAD

**Issue by Olivier6767** [pymedusa/Medusa#3261]
Branch: master
Commit: b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
Version: v0.1.17

Hello,
When Jackett returns results from a **Torrent** provider, the download link is sent to the NZB Download tool (**SABnzbd**) instead of being sent to the Torrent download tool (**uTorrent**).

The link sent to SABnzbd in that case points a **.torrent** file, and SABnzbd does not know how to handle this. Therefore the **job is in error in SABnzbd and the episode is never fetched.**
This happens in Automatic search but also in Manual search.

I thought this was the same issue as https://github.com/pymedusa/Medusa/issues/3149, but this issue was solved in https://github.com/pymedusa/Medusa/commit/f91e7a366cc140c97abf81aaed9269d54e1b85e3.

However I'm still having the issue today (I'm on latest release on Master branch).

**Comment by medariox** [comment]
Should be fixed with: https://github.com/pymedusa/Medusa/pull/3214 (not yet on `master` branch)

**Comment by Olivier6767** [comment]
ok thanks, will wait until it's merged into the master branch.
