### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: BBC First

### ISSUE THREAD

**Issue by phraymond** [pymedusa/Medusa#3270]
### INFO
**Python Version**: `2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]`
**Operating System**: `Linux-4.9.30-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
**Link to Log**: https://gist.github.com/bbf3f4108897d578b68b8cbb75b9f6ae
### ERROR
<pre>
2017-11-14 16:45:13 ERROR    Thread-22 :: [b16e0e5] Missing time zone for network: BBC First
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.13.0-26-generic-x86_64-with-LinuxMint-18.3-sylvia`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@c25e86ae79fc50db3cfc8b63c9126be16fadf64a
**Link to Log**: https://gist.github.com/d5b1093b480c4b6c785b7844e054dc90
### ERROR
<pre>
2018-01-21 14:04:59 ERROR    Thread-23 :: [c25e86a] Missing time zone for network: BBC Three
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
