### ISSUE TITLE
Jackett .torrent results sent to SAB instead of Transmission

### ISSUE THREAD

**Issue by bobbysteel** [pymedusa/Medusa#3272]
[Using latest docker image of master from linuxserver/medusa]

I guess I'm not quite sure what to expect here, but it seems this worked in SickRage/SickBeard but is now not working? 

I've setup a new Jackett provider that returns actual torrent files (vs my earlier bug which only returns magnet links which is being dealt with separately). 

When a result is found, Medusa is sending the .torrent file to SABNzbd and SAB is hanging on "trying to fetch" the torrent. Medusa should presumably route any torrent directly to my torrent client? I understand this is counterintuitive as a Newsnab provider should only return NZB files, but I suppose this was default behavior on earlier ancestor forks.

Feel free to close if I'm misinterpreting how Jackett should be working in this case... Thanks

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/3261 ?

**Comment by bobbysteel** [comment]
Oops didn't see that! Thanks
