### ISSUE TITLE
[ FEATURE ] Delay snatching new episodes

### ISSUE THREAD

**Issue by BlackestDawn** [pymedusa/Medusa#3287]
Personally  I think that having the option to delay snatching of episodes so that it has time to wait for preferred quality version to become available over "just" allowed quality would be a very good thing, since it would at least minimize fetching redundant/"duplicate" episodes.

**Comment by fernandog** [comment]
@BlackestDawn change daily search frequency. set to be less frequent.

**Comment by labrys** [comment]
@fernandog that's a useful workaround for now, but I think @BlackestDawn's feature request is valid.  It should be easy to implement as we already delay for the show's duration, we would just have to add a configurable delay to that.  It would be better than increasing the daily search frequency since results can be missed that way.

**Comment by BlackestDawn** [comment]
@fernandog 
It won't really resolve the issue just reduce it, though more likely only reduce the number of shows "affected" by it since some will be within the search interval while others will cross them.

The main issue is having an allowed quality "published" before a search and a preferred one after that search. Regardless of how seldom you search that will always be an issue. Delaying the snatch once an allowed (but not preferred) quality is first seen since it won't depend on when nor how often the searches are done.

Sure, waiting a fixed time after the show has concluded would be good enough but I was more thinking of the [Timeframe](https://flexget.com/Plugins/series/timeframe) option in FlexGet. It waits the given timeframe after it was initially seen for preferred quality, otherwise goes with best seen.

**Comment by labrys** [comment]
@BlackestDawn I agree a timeframe-like option would be better, but it would require a significant backend change to implement, one that isn't likely to happen soon while the fixed time after show conclusion could be implemented relatively quickly.

**Comment by BlackestDawn** [comment]
@labrys Of course of course, that's why I said fixed time was good enough.

**Comment by p0psicles** [comment]
#3360

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
