### ISSUE TITLE
yggtorrent provider : [b16e0e5] Failed parsing provider.

### ISSUE THREAD

**Issue by Jakhe** [pymedusa/Medusa#3291]
Hi,

 /opt/medusa/medusa/providers/torrent/html/yggtorrent.py", line 125, in parse
    download_url = urljoin(self.url, cells[0].find('a', target='_blank')['href'])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by adaur** [comment]
Already fixed on dev. A new version will be released soon, hopefully.
