### ISSUE TITLE
Post processing issue : bad scene match on Anime

### ISSUE THREAD

**Issue by hergonoway** [pymedusa/Medusa#3294]
Hi, 

currently using the last stable version through docker.

I precise that each of my anime series is set up correctly with anime tag and scene numbered, etc.

On some Anime there's bad post processing behavior where files from a specific season (with non absolute number but a scene name on the season) are processed like the files from the first season, even if the XEM scene name for this specific season is currently known from medusa (little Xem logo next to the season number with the right name showing when I put my mouse over). Which result in overwriting an episode from the first season with another one (often from backlog search when upgrading quality form 720 to 1080)

[EXAMPLE]
It happens on many Anime but in order to pick a good one for you to test I'll take : "Himouto! Umaru-chan" with HorribleSubs set as whitelisted release group. 
- Scene name for the show is automatically gathered by Medusa and set to "My Two-Faced Little Sister | Himouto!.Umaru-chan.R | Himouto! Umaru-chan R | Umaru-chan R" 
- the Xem logo next to Season 2 show "Himouto! Umaru-chan S2 | **Himouto! Umaru-chan R**"

the file in the post process folder is : "[HorribleSubs] **Himouto! Umaru-chan R** - 07 [1080p].mkv" which match the Xem scene name for season 2 but it's systematicaly post processed as Episode 7 from season 1.

:(

**Comment by p0psicles** [comment]
When you do a manual search for that episode 7, are you getting proper results? As that should indicate if it's being parsed correctly.

Here is a test I did for the episode you mentioned:
![image](https://user-images.githubusercontent.com/1331394/33234989-290d395e-d230-11e7-8d9b-df533dc65a8b.png)

No issues here.

**Comment by hergonoway** [comment]
![medusa - himouto umaru-chan 2017-11-26 01-22-31](https://user-images.githubusercontent.com/8405448/33236061-6538c976-d248-11e7-9401-0ab6f82056b9.png)

hello, yes I've got proper result. My issue is when medusa post process the downloaded file, I search and snatched correctly, file name is not modified, but it's processed like the episode 7 of the first season.

**Comment by hergonoway** [comment]
In my case, I saw 2 behavior : 
#1 I moved the first season once watched for every anime, so episodes where tagged as "Archive 720 HDTV", but there's no file anymore. in this case it replace the "Archive 720 HDTV" by "Downloaded 1080 HDTV"
#2 it simply post-process files as Special

**Comment by p0psicles** [comment]
Wait your throwing in two more potential bugs. Can you reproduce it and post the debug logs? Let's try to isolate one issue at a time.

**Comment by hergonoway** [comment]
Ok, so I kind of reproduced the problem

I took the Anime Blood Blockade Battlefront, here's my files : 
![recherche dans blood blockade battlefront 2017-11-27 23-02-15](https://user-images.githubusercontent.com/8405448/33291748-30f556e0-d3c7-11e7-8772-849680da626a.png)

As you can see, episode 17 and 19 are missing, which corresponding to episode 5 and 7 from second season.

Beforehand, I cleared scene names, full updated the show, rescan files, waited for the scene to be automatically updated, and let Medusa works. This show is known as "Kekkai Sensen" for season 1 and "Kekkai Sensen & Beyond" for season 2. These 2 scene names were correctly set to the right season automatically by medusa (little XEM logo next to season title). Then Medusa automaticaly snatched and download the 2 missing episode in 1080  of season 2, episode 5 and 7. 

![medusa - blood blockade battlefront 2017-11-27 23-07-40](https://user-images.githubusercontent.com/8405448/33291925-cdc8c6be-d3c7-11e7-91ed-9e20d3e15d58.png)

Once in post process, files are not processed : [https://pastebin.com/10SQ8dWU](url)

**Comment by medariox** [comment]
And what's the issue?

The log message is clear:
```2017-11-27 22:38:05 DEBUG    POSTPROCESSOR :: [b96b3ee] Skipping already processed file: [HorribleSubs] Kekkai Sensen & Beyond - 07 [1080p].mkv
2017-11-27 22:38:05 DEBUG    POSTPROCESSOR :: [b96b3ee] You're trying to post-process a file that has already been processed, skipping: [HorribleSubs] Kekkai Sensen & Beyond - 07 [1080p].mkv
2017-11-27 22:38:05 DEBUG    POSTPROCESSOR :: [b96b3ee] Skipping already processed file: [HorribleSubs] Kekkai Sensen & Beyond - 05 [1080p].mkv
2017-11-27 22:38:05 DEBUG    POSTPROCESSOR :: [b96b3ee] You're trying to post-process a file that has already been processed, skipping: [HorribleSubs] Kekkai Sensen & Beyond - 05 [1080p].mkv
```

Meaning that you already processed the files once. What you need to do is manual process the files with the option checked:
![img](https://snapr.pw/i/6ae24938f3.png)

**Comment by hergonoway** [comment]
yeah correct my bad 😞 

definitely difficult to reproduce

**Comment by hergonoway** [comment]
Well, I tried but impossible to reproduce, so I'm closing the issue, next time I encounter this issue (I hope not) I look at the debug directly.

The only common point I found to every Anime where first season of special episodes were replaced by episodes from further season were anime that I once set manually scene exception (before scene name was available on Xem) 

well thanks for your time anyway, keep the good job

**Comment by p0psicles** [comment]
Keep in mind there is a big difference between scene exceptions and season scene exceptions. Both of them can be added through xem. But you can only add the first. 

Season scene exceptions can be added in other ways though.
