### ISSUE TITLE
Post-Processed seeding torrents location don't work with remote torrent client

### ISSUE THREAD

**Issue by darkbroodzed** [pymedusa/Medusa#3295]
**Branch/Commit:** Any
**OS:** Any
**What you did:**  set Post-Processed seeding torrents location 
**What happened:** error in log
**What you expected:** moving torrent to new location after post process
**Logs:**
```
PASTE LOGS HERE
```
2017-11-23 15:30:19 WARNING  POSTPROCESSOR :: [b16e0e5] Not possible to move torrent after post-processing because seed location is invalid

its fail because of wrong logic in file process_tv.py

def move_torrent(info_hash, release_names):
        """Move torrent to a given seeding folder after PP."""
        if not os.path.isdir(app.TORRENT_SEED_LOCATION):
            logger.log('Not possible to move torrent after post-processing because seed location is invalid',
                       logger.WARNING)
return False

always "false" for any non local path, but torrent client can be on different device

**Comment by lilp69** [comment]
Check if your user have right to write in both location.

**Comment by darkbroodzed** [comment]
yep i have it
pi@raspberrypi:/mnt/dlink_a2/Transmission $ ls -la
total 40
drwxrwxrwx  8  501  501  4096 Nov 22 17:38 .
drwxrwxrwx 16 root root  4096 Nov 23 14:58 ..
drwxrwxrwx 72  501  501 12288 Nov 23 14:23 complete
drwxrwxrwx  2 1002  501  4096 Nov 19 12:19 couchpotato
drwxrwxrwx  2  501  501  4096 Nov 23 15:22 incomplete
drwxrwxrwx  5 pi   pi    4096 Nov 23 15:22 medusa
drwxrwxrwx  4 pi   pi    4096 Nov 23 00:30 seed
drwxrwxrwx  2  501  501  4096 Oct  2  2014 torrent

**Comment by fernandog** [comment]
@darkbroodzed not sure if transmission allows move to non local folder. Did you try using the Transmission UI to do that? I think it will complain because path is not mapped

**Comment by darkbroodzed** [comment]
guys i showed you code where logic fail.
In my installation i comment code
if not os.path.isdir(app.TORRENT_SEED_LOCATION):
logger.log('Not possible to move torrent after post-processing because seed location is invalid',
logger.WARNING)
return False
restart and all start work as expected.

Ok. Mb my English isn't perfect so i try explain it again:
I have sever with Medusa (Machine number one)
I have nas sever with Transmission torrent client and obliviously all video store on this server (Machine number two)
![image](https://user-images.githubusercontent.com/16042551/33185547-890b54d2-d094-11e7-804b-c578ad4a7e14.png)
path at screenshot local for machine number two (Transmission), but remote for Medusa's machine.

What wrong in current code? it check path entered in "Post-Processed seeding torrents location"
if not os.path.isdir(app.TORRENT_SEED_LOCATION):
and of course it false for any path from Transmission machine, but this path send to transmission machine, not local Medusa machine, so i kindly ask you - please remove this check from code.
PS. Transmission definitely support changing torrent location.

**Comment by fernandog** [comment]
It checks if user set a real folder and not a invalid or that doesn't exist.

This feature uses the transmission moving feature.

So you must pass a valid folder.

I really didn't understood what you explained.

@p0psicles helpe here?

**Comment by darkbroodzed** [comment]
> It checks if user set a real folder and not a invalid or that doesn't exist.
And path do not exits on machine where it is checked.
it exist only on machine where transmission installed, and it's different machine from where Medusa installed.

ok i try to be more creative :)
Medusa:
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
pi@raspberrypi:~ $ df -h
Filesystem                   Size  Used Avail Use% Mounted on
/dev/root                    5.6G  4.6G  673M  88% /
devtmpfs                     458M     0  458M   0% /dev
tmpfs                        462M     0  462M   0% /dev/shm
tmpfs                        462M   42M  421M   9% /run
tmpfs                        5.0M  4.0K  5.0M   1% /run/lock
tmpfs                        462M     0  462M   0% /sys/fs/cgroup
/dev/mmcblk0p6                68M   21M   48M  31% /boot
tmpfs                         93M     0   93M   0% /run/user/1000
192.168.100.3:/mnt/HD/HD_a2  3.6T  3.4T  219G  95% /mnt/dlink_a2

Machine with transmission:
[root@dlink-67E30D HD_a2]# uname -a
Linux dlink-67E30D 3.2.40 #1 Wed Apr 22 14:57:45 CST 2015 armv7l GNU/Linux
[root@dlink-67E30D HD_a2]# df -h
Filesystem                Size      Used Available Use% Mounted on
%root%                    8.7M      8.7M         0 100% /
/dev/ram0                 8.7M      8.7M         0 100% /
mdev                    248.0M         0    248.0M   0% /dev
/dev/loop0               37.9M     37.9M         0 100% /usr/local/modules
ubi0:config               4.8M    120.0K      4.4M   3% /usr/local/config
none                      2.0M    380.0K      1.6M  19% /mydlink
/dev/sda4               959.9M     34.1M    925.8M   4% /mnt/HD_a4
/dev/sdb4               959.9M     49.8M    910.1M   5% /mnt/HD_b4
/dev/sdb2                 3.6T      3.4T    218.8G  94% /mnt/HD/HD_a2
/dev/sda2               914.4G    269.7G    644.7G  29% /mnt/HD/HD_b2
/mnt/HD/HD_a2/Nas_Prog/sshd/etc
                          3.6T      3.4T    218.8G  94% /home/root/.ssh

So path from 
![image](https://user-images.githubusercontent.com/16042551/33186185-af839af8-d098-11e7-9400-bdd90a4590e3.png)
/mnt/HD/HD_a2/Transmission/medusa valid for Transmission machine but not valid for Medusa machine
When code starts it send path string to transmission and ask it move torrent, so path string MUST BE LOCAL PATH for Transmission, not for Medusa.

**Comment by fernandog** [comment]
Ok. I got it.
But either way I need to do any kind of check here. I can blindly send it

I will evaluate

**Comment by darkbroodzed** [comment]
you already blindly send any path from 
![image](https://user-images.githubusercontent.com/16042551/33186551-6065fc92-d09b-11e7-986c-1495bd7f2264.png)
so no big deal it will be checked from transmission side and you get error code if something goes wrong.

**Comment by fernandog** [comment]
Fixed in develop
