### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: HBO Asia

### ISSUE THREAD

**Issue by OoGuru** [pymedusa/Medusa#3303]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-3.16.0-4-amd64-x86_64-with-debian-8.6`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
**Link to Log**: https://gist.github.com/a0c1dbc7e93a414f45dfba9e6f9277c5
### ERROR
<pre>
2017-11-24 19:35:01 ERROR    Thread-27 :: [b16e0e5] Missing time zone for network: HBO Asia
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/e0cb1f3f7bf65a0e5028583f58cbbba730311c0f

**Comment by bentux** [comment]
### INFO
**Python Version**: `2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]`
**Operating System**: `Linux-3.13.0-141-generic-x86_64-with-Ubuntu-14.04-trusty`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `43.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/254d809141b3c9cf69a91fb622bbfd8a
### ERROR
<pre>
2018-02-20 23:52:39 ERROR    Thread-17 :: [ccbc0ce] Missing time zone for network: HBO
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
HBO already in list
