### ISSUE TITLE
[ FEATURE ] Tabbed home page

### ISSUE THREAD

**Issue by h3llrais3r** [pymedusa/Medusa#3306]
Is there any interest in having a tabbed home page?
If you choose to split the anime from the shows, you can configure to use tabs instead of putting the anime below the shows.
I've implemented this some time ago in SickRage but if you also find this interesting, I can make a PR for that. 

Example: 
![image](https://user-images.githubusercontent.com/1945295/33223955-286d2b88-d165-11e7-9e05-e17b5c822de8.png)

![image](https://user-images.githubusercontent.com/1945295/33223932-e5cd48c6-d164-11e7-89c4-08cc4685c9e7.png)

**Comment by h3llrais3r** [comment]
Will see if I find some time this week to implement it. 😉

**Comment by p0psicles** [comment]
Wait. There is already a Pr out there. Where I've made the order anime/Series changeable.

 https://github.com/pymedusa/Medusa/pull/3260

Not that I don't think its not a nice feature. Just want to align here.

**Comment by h3llrais3r** [comment]
@p0psicles can you finish your PR so I can make this PR? I already started with it yesterday...

**Comment by p0psicles** [comment]
Yeah sure. I'm waiting also on some other PR's.

**Comment by h3llrais3r** [comment]
@p0psicles any progress on the other PR's so I can get started with this one?

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
