### ISSUE TITLE
Medusa seems to be ignoring provider priority/quality when selecting a download

### ISSUE THREAD

**Issue by r1142** [pymedusa/Medusa#3307]
**Branch/Commit:** Master
**OS:** Windows
**What you did:** Added TV show with the preferred quality of SDTV/SD DVD and with the allow quality of all. Added providers in order: TPB, Torrentz2, Rarbg, TorrentDay. Randomize order is unchecked. Min seeders set to 4 for all providers.
**What happened:** I clicked the magnifying glass icon to do a forced search. It searched through all providers, but ultimately downloaded a torrent from TorrentDay with a quality of 'Unknown'
**What you expected:** I expected a torrent from TPB (First on provider list, matching preferred quality).
**Logs:**
https://pastebin.com/GHQg3kPU

I am not understanding how Medusa is selecting the file that it does to download. Image `#1` below shows the provider priority list, Image `#2` shows the options found by Medusa (by using the manual search on the same 4 providers) and image `#3` shows the TV show's configured qualities.

- Provider `#1` had 1 result that met the all requirements (seeders min:4, Quality SD)
- Provider `#2` had 1 result that met the same requirements.
- Provider `#3` had 2 results that met the same requirements.
- Provider `#4` had 4 results that met the same requirements, but the file was selected was not one of these four.

My questions are:

- Why was provider `#4` selected even though it was the lowest priority?
- Why was the quality selected an 'Allowed' quality when there were several 'Preferred' qualities available?
- Hypothetically, if no results matched the 'Preferred' quality from any providers, but all providers had 'Allowed' quality results, would the downloaded file from come Provider `#1` or from some other provider?

![image](https://user-images.githubusercontent.com/33968361/33224333-712f1e28-d136-11e7-8294-694432853e7e.png)
![image](https://user-images.githubusercontent.com/33968361/33224364-c73d3980-d136-11e7-9d3b-b2a5338c93c7.png)
![image](https://user-images.githubusercontent.com/33968361/33224375-ea2e6b1c-d136-11e7-88ad-1943fa299794.png)

**Comment by fernandog** [comment]
@r1142 you need to check the logs to proper read "history" of the found results. You can't look at the manual search page because you may see a results that was found later than the other.

get all your logs for `Adding item from search to cache` and check releases and timestamps

**Comment by sharkykh** [comment]
@r1142 
Since you haven't responded in over 6 months, I am closing this issue.
If you're still experiencing the issue let us know and we'll reopen.
