### ISSUE TITLE
Newpct issues

### ISSUE THREAD

**Issue by snamds** [pymedusa/Medusa#3314]
I'm not using medusa but I'd like to help here.

1) This replace is not enough:
https://github.com/pymedusa/Medusa/blob/cb73fce7e722df41297ff9e17dc10759347d68e9/medusa/providers/torrent/html/newpct.py#L86
Check what I had to do here:
https://github.com/snamds/SickRage/blob/newpct-web-restructure/sickbeard/providers/newpct.py#L108

2) Sometimes newpct releases some episodes together.
Like this:
http://www.newpct.com/series-hd/bates-motel
Episodes from 3 to 10 are in the same torrent.
Exists: http://www.newpct.com/descargar-seriehd/bates-motel/capitulo-53/hdtv-720p-ac3-5-1/
But not exists: http://www.newpct.com/descargar-seriehd/bates-motel/capitulo-54/hdtv-720p-ac3-5-1/

**Comment by medariox** [comment]
Thanks for the feedback! I've addressed 1. here: https://github.com/pymedusa/Medusa/pull/3322
About 2. there isn't much we can do about. Newpct is just too inconsistent and the search is useless.
