### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Tokyo Broadcasting System Television

### ISSUE THREAD

**Issue by Lynwex** [pymedusa/Medusa#3316]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@76e0401eabf7abc7392897f478c4d090a65b3e2c
**Link to Log**: https://gist.github.com/c0b7822b5cd073c79d6d7ed9781de171
### ERROR
<pre>
2017-11-26 11:42:44 ERROR    Thread-47 :: [76e0401] Missing time zone for network: Tokyo Broadcasting System Television
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/e0cb1f3f7bf65a0e5028583f58cbbba730311c0f
