### ISSUE TITLE
Missing time zone for network: Sky Italia

### ISSUE THREAD

**Issue by tomzic59** [pymedusa/Medusa#3318]
### INFO:

**Branch:** master
**Commit:** 76e0401eabf7abc7392897f478c4d090a65b3e2c
**Version:** v0.1.18
**Database:** 44.8
**Python Version:** 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
**SSL Version:** OpenSSL 1.0.1t 3 May 2016
**OS:** Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8
**Locale:** fr_FR.UTF-8

### ERROR:
```
2017-11-26 11:54:48 ERROR    Thread-16 :: [76e0401] Missing time zone for network: Sky Italia
```

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/e0cb1f3f7bf65a0e5028583f58cbbba730311c0f
