### ISSUE TITLE
Medusa crashes after adding a show // TVDBv2 Indexer won't work properly

### ISSUE THREAD

**Issue by tomzic59** [pymedusa/Medusa#3319]
### INFO:

**Branch:** master
**Commit:** 76e0401eabf7abc7392897f478c4d090a65b3e2c
**Version:** v0.1.18
**Database:** 44.8
**Python Version:** 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
**SSL Version:** OpenSSL 1.0.1t 3 May 2016
**OS:** Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8
**Locale:** fr_FR.UTF-8

### LOGS:

**Link:** [https://pastebin.com/FfzkPvg5](https://pastebin.com/FfzkPvg5)

### PROBLEM:

Every time I add a show with the TMDB indexer, Medusa checks the pre-existing files, gets the metadatas and crashes. So I need to restart the service manually. 

I don't want to use the TVDBv2 indexer because it seems very buggy. Some shows get the wrong poster or background picture but the metadatas are correct. For example : I wanted to add the show "Sherlock", the poster and background pic were from the movie "Sherlock" with Downey Jr. but the banner pic and the metas were from the original TV show. I really can't explain this...
I did not get that from Sickrage and the original TVDB indexer (not the v2).

**Comment by medariox** [comment]
Tried to add the show "Sherlock" with TVDB and TMDB both add the show correctly and the information is perfectly fine (posters, background, etc.). I suggest you delete any metadata you have for that show and try again.

**Comment by tomzic59** [comment]
What is the best way to delete all the metadata ?

**Comment by medariox** [comment]
Remove the show and delete the show's images from `medusa/cache/images/{show_id}`.

**Comment by tomzic59** [comment]
Ok, i deleted the show, the folder `images/{show_id}`, restarted medusa and finally added the show "Sherlock".
Now the show poster and fanart are not from the movie "Sherlock" but from an older collection...

![image](https://user-images.githubusercontent.com/33957088/33240564-f3d809fc-d2b7-11e7-9e34-db2388085b82.png)


How can I factory reset Medusa ?

**Comment by medariox** [comment]
Delete everything in `medusa/cache`.

**Comment by tomzic59** [comment]
Few days ago, I tried to restore my Sickrage backup. But when Medusa restarted (as requested), the restore process did nothing. 

Do you think this could be related to my problem ?

**Comment by fernandog** [comment]
@tomzic59 maybe you added the wrong Sherlock show. Mind the year of the show before adding it

![image](https://user-images.githubusercontent.com/2620870/33240689-32e043a6-d2a1-11e7-91d0-26d4096bb234.png)

**Comment by tomzic59** [comment]
At the beginning, I though it was that.
But I added the right tv show (like the checked littlebox in your picture).

**Comment by fernandog** [comment]
TVDB has the corrects ones?

**Comment by tomzic59** [comment]
Yes it has. I think i will hard reset medusa by a full re-install. If this works I will post again.

**Comment by fernandog** [comment]
@tomzic59 just full update show and see if fixes. See the full address of the image in Medusa UI and try to delete it in the folder

**Comment by tomzic59** [comment]
So I full updated the show, I found the full address of the image but it do not correspond to any folder in `/medusa`.

![image](https://user-images.githubusercontent.com/33957088/33241200-5affdd80-d2c2-11e7-85a7-40e9180b94c9.png)

**Comment by fernandog** [comment]
can you send the full address from the `src` ?
Seems the image is wrong in tvdb

**Comment by fernandog** [comment]
@tomzic59 try erase your browser cache please

**Comment by tomzic59** [comment]
I erased the cache but i always see the wrong picture. (Even after a full update)

I made few tests : 
- Factory reset Medusa by deleting the folder et re-clone the .git
- Try to catch the show in english
- Try to catch the show in french (my mother tongue)

Now i have a clean install i found that the indexer works well in English : 
![image](https://user-images.githubusercontent.com/33957088/33241416-30fe9ce4-d2c5-11e7-9986-9aa04c1829cc.png)

But with the "Français" language, i still have the same wrong meta pictures...

Maybe there is a problem in the code itself, i don't know.

**Comment by fernandog** [comment]
@tomzic59 waiting the `src` link address from the english version. I think the issue is in tvdb

**Comment by tomzic59** [comment]
`src` from the english version : `api/v2/series/tvdb176941/asset/posterThumb?api_key=2db1efdfa8f410ba89addb50a2b31e25`

**Comment by medariox** [comment]
Added `Sherlock` with French language and no issue at all - poster, banner, background all there and correct.

**Comment by bibi32** [comment]
Can we have the poster by site rating please ??

**Comment by p0psicles** [comment]
I believe I already did that. Which indexer?

**Comment by bibi32** [comment]
with TVDBv2 for blindspot i have this poster https://www.thetvdb.com/banners/posters/295647-15.jpg.
On master or develop and lots of series in english.
