### ISSUE TITLE
H264-20-40 is wrongly parsed as episodes 20-40

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#3320]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** develop
**OS:** windows/linux
**What you did:** Parsing the title `The.Good.Wife.Season.6.480p.HDTV.H264-20-40.WEB-DL`, results in the parsing the 20-40 describes the episodes, but it actually describes the h264 encoding settings.
**What happened:**
**What you expected:**
**Logs:**
```
D:\Development\Medusa2 - Copy\tests>python report_guessit.py The.Good.Wife.Season.6.480p.HDTV.H264-20-40.WEB-DL
# guessit: 2.1.4  rebulk: 0.9.0
? The.Good.Wife.Season.6.480p.HDTV.H264-20-40.WEB-DL
: title: The Good Wife
  season: 6
  screen_size: 480p
  video_codec: h264
  episode: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
  format: WEB-DL
  type: episode
  parsing_time: 0.0469999313354
```

One more example, `Arrow.Season.2.480p.HDTV.H264-20-40`.

Reported upstream: https://github.com/guessit-io/guessit/issues/507

**Comment by fernandog** [comment]
Never saw this before. @duramato did you?

**Comment by p0psicles** [comment]
I've noticed as I was making improvements to the season pack searching. As I was getting a really limited amount of season packs found. I was looking at geek.

**Comment by fernandog** [comment]
I suggest open an issue in guessit

**Comment by p0psicles** [comment]
Thought first check it's not because of our refiners.

**Comment by fernandog** [comment]
Its guessit issue:

```
guessit "The.Good.Wife.Season.6.480p.HDTV.H264-20-40.WEB-D                                                                             L"
For: The.Good.Wife.Season.6.480p.HDTV.H264-20-40.WEB-DL
GuessIt found: {
    "title": "The Good Wife",
    "season": 6,
    "screen_size": "480p",
    "format": [
        "HDTV",
        "WEB-DL"
    ],
    "video_codec": "h264",
    "episode": [
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40
    ],
    "type": "episode"
}
```
