### ISSUE TITLE
Allow schedulers to run on demand?

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#3329]
Medusa Info: | Branch: masterCommit: b96b3ee10760ffa03a15a207841a1a2bc65798ddVersion: v0.1.19Database: 44.8
-- | --
Python Version: | 2.7.13 (default, Dec 18 2016, 21:23:50) [GCC 4.6.4]
SSL Version: | OpenSSL 1.0.2j 26 Sep 2016
OS: | Linux-3.2.40-armv7l-with-glibc2.4
Locale: | en_US.UTF-8

would be handy for people like me who don't leave their NAS on for more then 5 hours...

**Comment by labrys** [comment]
@ward0 Are you aware you can run searches on demand from `Manage -> Manage Searches`?

**Comment by ward0** [comment]
see it closed.. wasn't aware ... thx
