### ISSUE TITLE
TypeError: index() got an unexpected keyword argument 'proc_dir'

### ISSUE THREAD

**Issue by adaur** [pymedusa/Medusa#3337]
### 
I'm not sure why I get this since. I'm calling the post processor manually but proc_dir should work.

**Branch/Commit:** develop
**OS:**
**What you did:**
**What happened:**
**What you expected:**
**Logs:**
```
2017-11-28 13:53:48 ERROR    Thread-19 :: [66baad3] Exception generated: index() got an unexpected keyword argument 'proc_dir'
Traceback (most recent call last):
  File "/home/www/medusa/medusa/server/web/core/base.py", line 263, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'proc_dir'
```

**Comment by p0psicles** [comment]
I think the route you requested is wrong.

**Comment by adaur** [comment]
Here is my bash file:

```
#!/bin/bash
wget --user=myuser --password=mypassword --post-data "proc_dir=/path" -O /dev/null https://mywebsite.com/medusa/home/postprocess/
```

I don't really see what's wrong there.

**Comment by medariox** [comment]
Should be `.../Medusa/home/postprocess/processEpisode` IIRC.

**Comment by labrys** [comment]
I assume you use nzbtomedia... check and make sure you have an updated version.

**Comment by adaur** [comment]
You're right, of course. I looked at the actual URL, updated it and did not look at the <form> URL. Silly me...
