### ISSUE TITLE
Medusa 404 white page

### ISSUE THREAD

**Issue by lilp69** [pymedusa/Medusa#3342]
On Debian 9.0 with latest stable version of Medusa.
I try to configure reverse proxy.
When in Medusa I put URL base : /medusa
And check "X-Forwarded-For..." I lost webgui from WAN & LAN.
How I can backup?

**Comment by p0psicles** [comment]
Restart medusa through systemctl. Your webroot should be active after restart.

**Comment by lilp69** [comment]
After restart, I have : traceback (most recent call last):
File "/opt/medusa/et/tornado/web.py" line 1488 in_execute
result = self.prepare()
File "/opt/medusa/et/tornado/web.py" line 2223 in prepare raise HTTPError(self.status_code)
HTTPError: HTTP 404: Not Found

**Comment by lilp69** [comment]
I need to put /medusa after my address...
