### ISSUE TITLE
[APP SUBMITTED]: Could not send notification to NotifyMyAndroid

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#3343]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [js-2017](../tree/js-2017)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@827ff79e2b674fa8d34aec4820a4bfcb7297043c
**Link to Log**: https://gist.github.com/45795d5fc5b0de11a645196e2b7db4a6
### ERROR
<pre>
2017-11-29 02:42:22 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [827ff79] Could not send notification to NotifyMyAndroid
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
Already PRed this fix

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [js-2017](../tree/js-2017)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@827ff79e2b674fa8d34aec4820a4bfcb7297043c
**Link to Log**: https://gist.github.com/a5bac37433c455bfad60415574cfca19
### ERROR
<pre>
2017-12-04 20:25:04 ERROR    SEARCHQUEUE-BACKLOG-274431 :: [827ff79] Could not send notification to NotifyMyAndroid
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
