### ISSUE TITLE
Root dirs and disk page page

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#3346]
@p0psicles 

![image](https://user-images.githubusercontent.com/2620870/33390070-f9619396-d51b-11e7-8cec-8aad95865768.png)

![image](https://user-images.githubusercontent.com/2620870/33390125-263c87cc-d51c-11e7-904d-9ad89ca5bebf.png)

**Comment by fernandog** [comment]
Notice the show folder:

![image](https://user-images.githubusercontent.com/2620870/33390515-43e3882e-d51d-11e7-8b23-31065b338c77.png)

**Comment by p0psicles** [comment]
Pls create a proper bug report?

**Comment by fernandog** [comment]
using phone. i can next week
