### ISSUE TITLE
"&" In Episode name gets named "&amp;" when processing or renaming.

### ISSUE THREAD

**Issue by QuickSwitchLK** [pymedusa/Medusa#3350]
Medusa Info: | Branch: master
                       Commit: b96b3ee10760ffa03a15a207841a1a2bc65798dd
                       Version: v0.1.19
                       Database: 44.8
Python Version: | 2.7.13 (default, Dec 18 2016, 23:11:11)  [GCC 4.6.4]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Linux-3.2.40-armv7l-with-glibc2.4
Locale: | en_US.UTF-8

So I have moved from SickRage to Medusa and have a new problem that if a new episode has "&" in the title it gets named "&amp;" when processed.

so for example when...
Modern Family - S09E04 - Sex, Lies & Kickball - 1080p WEB-DL.mkv was processed it was renamed in my windows share as...

Modern Family - S09E04 - Sex, Lies &amp; Kickball - 1080p WEB-DL.mkv

If I show file names in Medusa is still shows as being named "Modern Family - S09E04 - Sex, Lies & Kickball - 1080p WEB-DL.mkv" but still exists as "Modern Family - S09E04 - Sex, Lies &amp; Kickball - 1080p WEB-DL.mkv" in the windows directory.

Preview Rename also wants to change any existing file that contains "&" from my existing collection.

If it makes any difference Medusa is running on my Synology.

**Comment by medariox** [comment]
Should be fixed with https://github.com/pymedusa/Medusa/pull/3396
Make sure to remove the show and add it again.

**Comment by fexofenadine** [comment]
Thanks for looking at this, it also appears to be using the HTML code for ampersand inside the filename.nfo metadata file. I've updated to the latest and this seems to still be happening

This is in the Kodi 12+ filename.nfo metadata <title> tag if it helps

Thanks again

**Comment by medariox** [comment]
@fexofenadine 
Are you running develop? Did you remove and readd the show?

**Comment by fexofenadine** [comment]
No not develop, I did remove and readd the show, deleted the nfo files to be sure the second time I tried it

**Comment by fexofenadine** [comment]
Oh it's only in develop branch. Apologies!

**Comment by medariox** [comment]
@fexofenadine 
No worries! Closing the issue as it should be solved with next release.
