### ISSUE TITLE
[ FEATURE ] Make use of a Post Processing queue

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#3351]
Would it be possible to implement a Post Process queue like SickRage is currently doing?
In Medusa currently when it is busy post processing in the background the web GUI does not respond anymore.
I mean this pull from SickRage https://github.com/SickRage/SickRage/pull/2839

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.

**Comment by Rouzax** [comment]
This also for fills https://github.com/pymedusa/Medusa/issues/3351
Does this mean that when I call the API it will give an acknowledge directly or will it still wait for the process to complete and it can just handle more "threads" at a time?
