### ISSUE TITLE
Reverse proxy and HTTPS

### ISSUE THREAD

**Issue by lilp69** [pymedusa/Medusa#3358]
Hi,
I use a VM for reverse proxy with Nginx.
I install https on it with my certificates.
Medusa is in their own VM.
Since I activate HTTPS I can access to Medusa.
How can use HTTPS and reverse proxy with Medusa?

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/wiki/Reverse-Proxy-setup

Open again if you still have issues.

**Comment by lilp69** [comment]
Same issue : here my conf on my nginx vm : https://pastebin.com/uLspiDzK

**Comment by medariox** [comment]
What issue? You will need to be much more specific if you want anyone to help you.

**Comment by lilp69** [comment]
502 bad gateway

**Comment by adaur** [comment]
It works just fine using Nginx+SSL for me:

```
		location ^~ /medusa {
			proxy_pass http://localhost:8081;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Host $host:443;
			proxy_set_header X-Forwarded-Server $host;
			proxy_set_header X-Forwarded-Port 443;
			proxy_set_header X-Forwarded-Proto $scheme;

		# Websocket
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_read_timeout 86400;
	}
```

**Comment by lilp69** [comment]
I've my reverse proxy on a container and medusa and another.This conf don't works.

**Comment by bobbysteel** [comment]
this is tricky to do but requires docker config so both containers are on the same network or both running on the host network. not trivial when you containerize stuff like this.

**Comment by lilp69** [comment]
Both are on the same network and before HTTPS, reverse proxy it's good.

**Comment by adaur** [comment]
Or you could consider adding Nginx to your Medusa's instance. Anyway, not related to Medusa directly

**Comment by lilp69** [comment]
But I haven't only medusa use reverse proxy...
