### ISSUE TITLE
Empty "Anonymous redirect" results in broken links in add show

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#3359]
Branch: master                
Commit: b96b3ee10760ffa03a15a207841a1a2bc65798dd                 
Version: v0.1.19                 
Database: 44.8
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

When no link is used in Anonymous redirect this will result in a broken link in the add show page all other pages seem to work fine.
![image](https://user-images.githubusercontent.com/4103090/33492260-cc062112-d6bc-11e7-82bd-78b90f54fcd4.png)

![image](https://user-images.githubusercontent.com/4103090/33492333-06354a70-d6bd-11e7-87c6-e9e4cae1845e.png)
The links point to:
- undefinedhttp://thetvdb.com/?tab=series&id=321239&lid=7
- undefinedhttp://www.tvmaze.com/shows/16579
- undefinedhttps://www.themoviedb.org/tv/69478

**Comment by OmgImAlexis** [comment]
If this is still an issue please let me know and I'll reopen it.

**Comment by Rouzax** [comment]
@OmgImAlexis Should this have been fixed in the latest release?
I still have it with the following version:

Medusa Info: | Branch: master                 Commit: 77b20916ab577b82112ebc624f816054788c63f2                 Version: v0.2.2                 Database: 44.9
-- | --
Python Version: | 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2k  26 Jan 2017
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

**Comment by sharkykh** [comment]
Sorry, my bad.
I don't know how I completely missed that.
https://github.com/pymedusa/Medusa/blob/46804b09b7e2ac2214f7a5bd5cee06341d611714/themes/light/assets/js/add-shows/new-show.js#L111-L116
Should be an easy fix.
The previous fix affected all other places, but this is using custom code.

**Comment by Rouzax** [comment]
No problem, you are all doing a great job.

**Comment by sharkykh** [comment]
@Rouzax Should finally be fixed on develop :+1:
