### ISSUE TITLE
[ FEATURE ] Fallback to secondary search provider group after a day

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#3361]
I have two private torrent sites that I get 99.9% of my content from. I want to have those 2 providers be used at random which I can do using this setting.
![image](https://user-images.githubusercontent.com/4103090/32983576-0f534740-cc97-11e7-831a-f6c5f01ada1b.png)
That way I spread out my ratio and bonus points.

Now sometimes I want to be able to use for instance RARBG as fallback but when I have the setting selected to randomize my search provides than sometimes RARBG is the first one used.
Would it be possible to create a main and secondary Search Provider Group?
That way the Primary ones can be used at random and for instance if a download is not found in a day then it can do a search using the Secondary Search Group.

**Comment by p0psicles** [comment]
Would it help if you could configure a delay per provider? Then you could delay RARBG by a day. It would not use include the rarbg result until 1 day counting from the first found release over all providers.

**Comment by fernandog** [comment]
@p0psicles keep in mind that we keep updating the `date` (and also seed/peers) in the cache.db so how you would know when the first result was added to cache?

**Comment by p0psicles** [comment]
#3360

**Comment by Rouzax** [comment]
This is awesome

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.

**Comment by Rouzax** [comment]
@p0psicles Thanks for implementing this.
Just to check, these two settings are directly related, if the first one is not enabled the second one does nothing?
![image](https://user-images.githubusercontent.com/4103090/34376055-217f0e7e-eaea-11e7-9dee-739d8264d669.png)

**Comment by p0psicles** [comment]
Yes

**Comment by Rouzax** [comment]
Thanks again.
