### ISSUE TITLE
Cleaning time zones gives error "too many SQL variables"

### ISSUE THREAD

**Issue by SunMar** [pymedusa/Medusa#3363]
Hi,

I am trying out Medusa and migrating my SickRage data to it and came across this problem.

**Branch/Commit:** master
**OS:** Windows
**What you did:** Copied my SickRage data folder to my new Medusa data folder
**What happened:** A SQL error when it was trying to clean the `cache.db` table `network_timezones`
**What you expected:** No error
**Logs:**
```
2017-12-01 22:26:24 INFO     MAIN :: [b96b3ee] Query: 'DELETE FROM network_timezones WHERE network_name IN (?, ...
2017-12-01 22:26:24 ERROR    MAIN :: [b96b3ee] DB error: OperationalError('too many SQL variables',)
```

**Comments:**

I fixed this by manually clearing the table before starting Medusa (it had 2633 records). I don't know if it tries to delete everything, in which case truncating the table is a better option (`DELETE FROM network_timezones` possibly followed by a `VACUUM`). If it doesn't delete everything, perhaps still do a truncate when the number of timezones it wants to clean up exceeds say 100. Nicest would be to check for the limit but for that I could only find a hack in the form of changing the limit through `sqlite3_limit` and checking the return value (jgallagher/rusqlite#220). Though truncating it if you want to clean a large amount doesn't seem like a bad solution to me since it appears to get repopulated anyways.

**Comment by fernandog** [comment]
@SunMar don't use sickrage's cache.db - erase it from medusa folder

**Comment by labrys** [comment]
@SunMar The max limit is usually 999.  The delete could function by deleting only 999 time zones a time, but the function that executes the statement handles all mass sql statements, for other statements it would be better to fail than to have possible race conditions.  I'll look into this when I get a chance.

**Comment by fernandog** [comment]
@SunMar erasing sickrages cache.db worked? Our cache.db is different from then, you shouldn't use it

**Comment by SunMar** [comment]
Yes, removing the cache.db didn't produce any problems, it appears to be recreated.
