### ISSUE TITLE
General / Advanced / No Restart mentions "SR"

### ISSUE THREAD

**Issue by SunMar** [pymedusa/Medusa#3365]
**Branch/Commit:** master
**OS:** Windows
**What you did:** Go to General Configuration > Advanced Settings > No Restart
**What happened:** Description says "SR"
**What you expected:** Description to say "Medusa"
**Logs:**
```
No Restart

Only shutdown when restarting SR. Only select this when you have external software restarting SR automatically when it stops (like FireDaemon)
```

**Comment by medariox** [comment]
Fixed in develop. Thanks for the report!
