### ISSUE TITLE
Label: "Help Wanted" Snatching existing files

### ISSUE THREAD

**Issue by johnvick** [pymedusa/Medusa#3398]
Branch: masterCommit: ca2c5c4c92888f2f588c74c6770cfa12c6db7f40Version: v0.1.19Database: 44.8
--
Python Version: | 2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]
SSL Version: | OpenSSL 1.0.1t 3 May 2016
OS: | Linux-4.9.61+-armv7l-with-debian-8.9
Locale: | en_GB.UTF-8

**What you did:** Imported existing series from local drive
**What happened:** Series were imported and appear as downloaded in the library but are snatched again
**What you expected:** I didn't want to get the episodes again

The existing episodes can be a mixture of SD 720 etc. Past episodes are set to be skipped by default and future as wanted. Can't work out why this is happening with some series and not others from the same folders that SickRage uses. The torrent files are being sent to a dead folder in the meantime. 

Any help appreciated.

**Comment by fernandog** [comment]
Set all old episodes as archived

**Comment by johnvick** [comment]
Thanks - is there a setting to automatically mark all imported episodes as archived or does this have to be done manually?

**Comment by fernandog** [comment]
If all episodes have the same quality, select all in the display show and in the listbox, pick the correct archive quality

**Comment by johnvick** [comment]
OK thanks all clear now.

**Comment by labrys** [comment]
@johnvick before importing if you can select default status, just make sure you change the series default to the desired default status after importing.  After files are imported, @fernandog's option is available of course.
