### ISSUE TITLE
ffprobe fails with exit status 6

### ISSUE THREAD

**Issue by rEes9P** [pymedusa/Medusa#3400]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: master/ca2c5c4c92888f2f588c74c6770cfa12c6db7f40**
**OS: macOS Sierra 10.12.6**
**What you did: Recently installed Medusa**
**What happened: The app works _very_ slowly. I think it might be because of the repeated error messages I get (see log). Also, under _Help & Info_ my Locale is shown as Unknown.Unknown**
**What you expected: The navigation to be much faster as it is almost unusable at the moment**
**Logs:**
```
2017-12-04 16:14:04 DEBUG Thread-19 :: [ca2c5c4] Broken providers already updated in the last hour
2017-12-04 16:13:54 DEBUG Thread-23 :: [ca2c5c4] Broken providers already updated in the last hour
2017-12-04 16:06:58 WARNING Thread-16 :: [ca2c5c4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2017-12-04 16:06:58 WARNING Thread-16 :: [ca2c5c4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2017-12-04 16:06:58 WARNING Thread-16 :: [ca2c5c4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2017-12-04 16:06:58 WARNING Thread-16 :: [ca2c5c4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2017-12-04 16:06:58 WARNING Thread-16 :: [ca2c5c4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt

AND

ERROR    Thread-16 :: [ca2c5c4] Missing time zone for network: BBC One
```

**Comment by p0psicles** [comment]
Can you use gist or pastebin to share a full debug log, from the moment you start medusa up?
Does the slow UI show itself directly after startup? Or is it always slow, or just on moments?

**Comment by rEes9P** [comment]
Thanks for getting back so promptly, @p0psicles 

It is extremely slow to start and starts crawling once I add a show.

Another thing that has me flummoxed is that I am unable to start Medusa simply by cd'ing into the Medusa folder and running the _python SickBeard.py_ command. If I do so then I get the following error message in Terminal:

> $ python SickBeard.py
> dyld: Library not loaded: /usr/local/opt/x265/lib/libx265.130.dylib
>   Referenced from: /usr/local/bin/ffprobe
>   Reason: image not found
> Traceback (most recent call last):
>   File "SickBeard.py", line 4, in <module>
>     from medusa.__main__ import main
>   File "/Applications/Medusa/medusa/__init__.py", line 23, in <module>
>     initialize()
>   File "/Applications/Medusa/medusa/init/__init__.py", line 29, in initialize
>     _configure_knowit()
>   File "/Applications/Medusa/medusa/init/__init__.py", line 161, in _configure_knowit
>     api.initialize({'mediainfo': suggested_path})
>   File "/Applications/Medusa/ext/knowit/api.py", line 27, in initialize
>     available_providers[name] = provider_cls(config, context.get(name) or config.general.get(name))
>   File "/Applications/Medusa/ext/knowit/providers/ffmpeg.py", line 202, in __init__
>     self.executor = FFmpegExecutor.get_executor_instance(suggested_path)
>   File "/Applications/Medusa/ext/knowit/providers/ffmpeg.py", line 88, in get_executor_instance
>     executor = exec_cls.create(os_family, suggested_path)
>   File "/Applications/Medusa/ext/knowit/providers/ffmpeg.py", line 117, in create
>     check_output([candidate, '-version'])
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command '[u'ffprobe', u'-version']' returned non-zero exit status -6

However, if I try and start Medusa from a simple Automator AppleScript app (It is literally one line _"do shell script "python /Applications/Medusa/SickBeard.py"_) then it does eventually start after a very long delay.

I have absolutely no idea why this is so as cd'ing into /Applications/Medusa and then running the command _python SickBeard.py_ should do the same exact thing but instead it gives me the above referenced error messages.

[Here](https://gist.github.com/rEes9P/d4c0afac48912098aff2277d48c2b5f3) is the full debug log, which is full of _Updating network timezones failed_ messages.

**Comment by labrys** [comment]
@rEes9P sounds like it's a permissions error.  Try cd'ing to the directory and run `ffprobe -version` from the shell and see if it gives an error.

**Comment by rEes9P** [comment]
@labrys Thanks for getting back. I ran `ffprobe -version` after cd'ing into Applications/Medusa and got this error message.

> $ ffprobe -version
> dyld: Library not loaded: /usr/local/opt/x265/lib/libx265.130.dylib
>   Referenced from: /usr/local/bin/ffprobe
>   Reason: image not found
> Abort trap: 6

Could you please explain, if possible, why Medusa does eventually start if I run it through the Automator script but not directly via the `python SickBeard.py` command in Terminal (as explained in my post above?) Thanks!

**Comment by labrys** [comment]
My guess is that when you run it manually, the shell user has no access to `/usr/local/opt/x265/lib/libx265.130.dylib` but when run by the script, it runs it as a different user that has correct permissions for that file.

As for why its slow, I would guess the Automater script user may not have network permissions.  Does it function correctly other than being slow?

**Comment by rEes9P** [comment]
It is so incredibly slow that I don't know if it functions correctly. I am able to add shows at times but have not been able to go to an actual page for the show given the speed. I think it might even be hanging.

**Comment by labrys** [comment]
I'd like to focus on troubleshooting the ffprobe issue first and foremost so we can compare performance with the Automater script.  From some googling it looks like you might have an incorrect version of the libx265 library installed.  Check `/usr/local/opt/x265/lib` to see what version you have.  It may be something like `libx265.142.dylib` instead of the expected `libx265.130.dylib`.  If that's the case, then re-installing `ffprobe` should work.

**Comment by rEes9P** [comment]
Yup, that seems to be it. I have `libx265.146.dylib`. Sorry to ask you a very basic question but could you please guide me about how to re-install/update `ffprobe`? I installed `ffmpeg` via Homebrew but I can't find `ffprobe` on Homebrew (neither independently or in the list of `ffmpeg` dependencies) nor could I come across easy to understand instructions on installing it. Thanks for your help!

**Comment by labrys** [comment]
Tagging @OmgImAlexis to see if you can assist with a user installing `ffprobe` on mac
@rEes9P since this issue has become more focused on the `ffprobe` issue, can you open a new issue for the Automator AppleScript causing Medusa to be too slow?

**Comment by sharkykh** [comment]
@rEes9P 
Were you able to figure it out or is this still an issue?

**Comment by rEes9P** [comment]
Sorry @sharkykh, I am no longer using Medusa.
