### ISSUE TITLE
[Yggtorrent] unable to connect

### ISSUE THREAD

**Issue by MrAurik** [pymedusa/Medusa#3401]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** MASTER / Commit: ca2c5c4c92888f2f588c74c6770cfa12c6db7f40
**OS:** 
**What you did:**
**What happened:** I tried to download a file from YGGTorrent but medusa was unable to login
**What you expected:**
**Logs:**
```
2017-12-04 12:39:23 WARNING  SEARCHQUEUE-FORCED-73762 :: [Yggtorrent] :: [ca2c5c4] Unable to login to provider
2017-12-04 12:39:22 INFO     SEARCHQUEUE-FORCED-73762 :: [Yggtorrent] :: [ca2c5c4] Performing episode search for XXX
```

It seems that YGGtorrent change his URL : https://ww1.yggtorrent.com

Thanks !

**Comment by p0psicles** [comment]
Already in develop branch.
Wait for our next release.
https://github.com/pymedusa/Medusa/blob/develop/medusa/providers/torrent/html/yggtorrent.py#L37
