### ISSUE TITLE
No published date for IPtorrent

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#3402]
Medusa Info: | Version
-- | --
Branch: | master                
Commit: | ca2c5c4c92888f2f588c74c6770cfa12c6db7f40                
Version: | v0.1.19                
Database: | 44.8
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

Not sure if this is a bug or working as designed.
When I do a manual search the Publish Dates for IPtorrents are not populated.
![image](https://user-images.githubusercontent.com/4103090/33559465-23f5266e-d90d-11e7-97a9-3c6b6e837070.png)

**Comment by p0psicles** [comment]
It has never been implemented, probably with a reason.
Is there are torrent publish data available?

**Comment by medariox** [comment]
The publish date is there (human time). I think the main reason was laziness 😃

**Comment by p0psicles** [comment]
Aah, ok.
Well @rouzax, i guess won't be long before that's added.

**Comment by sharkykh** [comment]
Looks like this was added.
