### ISSUE TITLE
Problem with root_dirs setting

### ISSUE THREAD

**Issue by Forceflow** [pymedusa/Medusa#3404]
**Branch/Commit:** master
**OS:** Ubuntu 17.10
**What you did:** Run Medusa start script
**What happened:** Error on loading of video root dirs
**What you expected:** Succesful loading
**Logs:**
```
me@dystopia2:~/dev/Medusa$ ./start.py
2017-12-04 14:06:29 INFO     MAIN :: [ca2c5c4] Starting Medusa [master] using '/home/**********/dev/Medusa/config.ini'
Traceback (most recent call last):
  File "./start.py", line 7, in <module>
    main()
  File "/home/me/dev/Medusa/medusa/__main__.py", line 2104, in main
    application.start(sys.argv[1:])
  File "/home/me/dev/Medusa/medusa/__main__.py", line 347, in start
    self.web_server = AppWebServer(self.web_options)
  File "/home/me/dev/Medusa/medusa/server/core.py", line 95, in __init__
    self.video_root = root_dirs[int(root_dirs[0]) + 1]
ValueError: invalid literal for int() with base 10: '/home/me/Downloads/Medusa'
```
There seems to be a problem with setting anything in the video_root variable in the config file. After I've erased the value there manually (it was set to /home/me/Downloads/Medusa, which is a valid path), Medusa starts up and continues to run. If I return to the config screen to set the value again and mark the folder as default, Medusa will crash somewhere in the next 2 or 3 days. No funny characters in the path or anything else I can think of.

**Comment by p0psicles** [comment]
I don't know how it got this way, but the format is not correct.
Medusa made a change recently to how lists are stored in the config.ini.
Meaning that if you have only one root dit, for you it would look like:
`root_dirs = 0, /home/me/Downloads/Medusa`

**Comment by Forceflow** [comment]
I will manually change it in my config.ini, and report if the crash still occurs. I can vaguely remember trying to fix it that way and failing, but I will verify. Thanks!

**Comment by p0psicles** [comment]
Are you using an android/ios app to control medusa?

**Comment by medariox** [comment]
@fernandog had a similar issue IIRC.

**Comment by Forceflow** [comment]
@p0psicles : In fact, I do! I use https://github.com/MGaetan89/ShowsRage, which was not especially designed for Medusa, but for Sickrage. It kept on working after I switched, so I didn't think much of it.

Would this be messing around with my config file, though?

**Comment by labrys** [comment]
@Forceflow it should be fixed in develop, but you may need to manually add the `0, ` to the beginning of the `root_dirs` setting in your `config.ini`.  Make sure you shutdown Medusa before manually editing the config or the changes will not persist.

**Comment by labrys** [comment]
Closing this as fixed in develop, if you have issues with develop or once its been merged to master, feel free to re-open this issue.
