### ISSUE TITLE
Unable to connect to provider yggtorrent

### ISSUE THREAD

**Issue by storn70** [pymedusa/Medusa#3408]
OS: Syno
**What you did: Try to change password
**What happened: No change
**What you expected: To logon on Yggtorrent with Medusa
**Logs:
2017-12-04 22:47:36 WARNING  SEARCHQUEUE-MANUAL-121361 :: [Yggtorrent] :: [ca2c5c4] Unable to login to provider

Hi, i've configured my provider yggtorrent in medusa with my ygg account but still unable to use it.

Could you please check ?

Thx.

**Comment by medariox** [comment]
This is already fixed and will be available with the next release.
