### ISSUE TITLE
[QUESTION] How switch branch in unraid for develop

### ISSUE THREAD

**Issue by maxcore** [pymedusa/Medusa#3414]
Hi ,

How switch branch in unraid for develop ?

thx

**Comment by fernandog** [comment]
Are you willing to have some issues from time to time?

**Comment by maxcore** [comment]
I take the risk :)

**Comment by fernandog** [comment]
Can you run git commands?

Stop medusa
Run inside Medusa folder:
git checkout develop
Start medusa

**Comment by maxcore** [comment]
@fernandog thx for your help

**Comment by fernandog** [comment]
@maxcore please add your github username/password in medusa settings so you can report issues/errors

**Comment by maxcore** [comment]
yes ! it done!
