### ISSUE TITLE
[ FEATURE ] Providers statistics

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#3420]
I would be interested in seing statistics of providers
my initial thought is about the providers which gave me a successful download

Also, with a more general overview, we could think about general statistics about providers which made available episodes matching my criteria, not only the ones which were snatched.
 After some time, that feature would definitely help to choose the providers and give priorities also.

**Comment by fernandog** [comment]
problem is you can't know (now) how long or when provider was enabled/disabled. We don't log it. So it can give false statistics.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
