### ISSUE TITLE
[APP SUBMITTED]: No translation mapping available for value: minutes

### ISSUE THREAD

**Issue by PxReaz** [pymedusa/Medusa#3427]
### INFO
        **Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
        **Operating System**: `Linux-3.16.0-4-amd64-x86_64-with-debian-8.9`
        **Locale**: `UTF-8`
        **Branch**: [master](../tree/master)
        **Database**: `44.8`
        **Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
        **Link to Log**: https://gist.github.com/ba8bb91c8f92d3cd18d74ce092a0b5f6
        ### ERROR
        <pre>
2017-12-07 07:55:51 ERROR    SEARCHQUEUE-FORCED-321285 :: [Yggtorrent] :: [1a8dc66] No translation mapping available for value: minutes
</pre>
        ---
        _STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by adaur** [comment]
Thanks for the report. I thought they were not needed since they are not to be translated but apparently they are.

**Comment by scott451** [comment]
### INFO
        **Python Version**: `2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]
        **Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
        **Locale**: `UTF-8`
        **Branch**: [master](../tree/master)
        **Database**: `44.8`
        **Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
        **Link to Log**: https://gist.github.com/855fd1b00e4a8dcca4b157fb471584eb
        ### ERROR
        <pre>
2017-12-09 18:13:08 ERROR    SEARCHQUEUE-MANUAL-80379 :: [Yggtorrent] :: [1a8dc66] No translation mapping available for value: minutes
</pre>
        ---
        _STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by scott451** [comment]
### INFO
        **Python Version**: `2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]
        **Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
        **Locale**: `UTF-8`
        **Branch**: [master](../tree/master)
        **Database**: `44.8`
        **Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
        **Link to Log**: https://gist.github.com/2033e76017d5af5db6df6f841302e4d2
        ### ERROR
        <pre>
2017-12-15 08:43:44 ERROR    SEARCHQUEUE-BACKLOG-289590 :: [Yggtorrent] :: [1a8dc66] No translation mapping available for value: minutes
</pre>
        ---
        _STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Fixed in develop. No big issue also. Release is not picked up in first minute. But will in next run.
