### ISSUE TITLE
Popup notification on save not showing

### ISSUE THREAD

**Issue by guim31** [pymedusa/Medusa#3428]
Hi everybody,

since I use Medusa on my Synology NAS in a docker container, all the popups notifications on change save won't show. Something like "Changes saved"

I'm also unable to see a list of choices when I want to download subtitles : I click the CC button, it asks me if I want to go manual or Auto, whatever I choose , nothing happens.

I think the two problems are related, like a general popup issue

Medusa Info: 
Branch: master
Commit: 1a8dc66c7ec9231be0d3444710e476437c9ae1c8
Version: v0.1.20
Database: 44.8

**Comment by p0psicles** [comment]
Python version?
Any errors in log? 
Debug log? 
Your browser? 
Use Chrome, hit f12, check for any errors in console.

**Comment by guim31** [comment]
Sorry for the lack of informations : 

On the Chrome console (I tried with Chrome and Chromium, running on Ubuntu Mate 17.10) I have those lines : 

```
permission @ vender.min.js?1341:20
(anonymous) @ ajax-notifications.js?1341:16
```
When I click on the 'ajax-notifications.js' link, it takes me to this line : 
`PNotify.desktop.permission();`

I can't see anaything related to my issue in the debug log... I can copy it if you want !

**Comment by guim31** [comment]
Just tested on Firefox and everything is working..

**Comment by p0psicles** [comment]
maybe you need to authorize the notification popup in chrome?

**Comment by guim31** [comment]
I allready tried that, but it didn't work

**Comment by ripper1967** [comment]
its a chrome issue, try localhost and port your medusa is on it will show notifications.
