### ISSUE TITLE
[ FEATURE ] Change the default option for change status on the backlog page

### ISSUE THREAD

**Issue by timdine** [pymedusa/Medusa#3431]
Bug / Enhancement?

The default option for changing the status of episodes on the show page is nothing, you are presented with "Choose an option"

The default option for changing the status of episodes on the backlog page is "Skipped"

Make the default option on the backlog page "Choose an option" to make it consistent and to prevent destroying a backlog with a missed click.

**Comment by labrys** [comment]
By `backlog page` do you mean the `Episode Status Management` page?

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.

**Comment by timdine** [comment]
You are correct, it is actually the Episode Status Management page.
