### ISSUE TITLE
Custom providers can't have double pipes (||) in the name

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#3436]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:**
**What you did:**
**What happened:**
**What you expected:**
**Logs:**
```
Any custom 'Configure Custom
Newznab Providers' and for the variable 'provider name' set || in the name and you will have a error. change column to something else?
```

**Comment by medariox** [comment]
I'm not sure if I understood this correctly. You set as provider name `II`?

**Comment by ward0** [comment]
example provider name: '1337x || Jackett'
a provider name that works: '1337x(space)Jackett'

I use '|| Jackett' in the name to get more information for myself.

**Comment by medariox** [comment]
How is `||` any better than `|` or anything else really? I've tagged it as a bug now, but this is something that we can't really change in the foreseeable future. That's how SR used to handle the providers separation in the config and we still want to support users coming from SR and older versions for now.

**Comment by ward0** [comment]
@medariox just wanted to let you guys know that its a small bug. I just changed the || to something else indeed.

**Comment by labrys** [comment]
I think this, at least for the foreseeable future is a won't fix.  We could maybe put a note though in the UI saying `||` is not valid.

**Comment by ward0** [comment]
@labrys I was more informing you guys... A note in the UI would be handy indeed.
