### ISSUE TITLE
Base_URL not correctly displaying changes.md

### ISSUE THREAD

**Issue by bobbysteel** [pymedusa/Medusa#3439]
In /medusa/app.py there's a reference to base_url being the cdn.pymedusa.com address. However in app when using the top-right menu to look at changelog, it seems to reference the news that's here: https://github.com/pymedusa/medusa.github.io/tree/master/news and the cdn.pymedusa.com address isn't correct. But I can't tell what's actually at cdn.pymedusa.com or why that was put there, so I don't want to check in code that breaks something else. Ideas?

```
Could not load changes from the repo. Click here for CHANGES.md
```
This points to https://cdn.pymedusa.com/news/CHANGES.md

**Comment by medariox** [comment]
The CDN seems to be down. Ping @OmgImAlexis

**Comment by medariox** [comment]
CDN is back up.

**Comment by OmgImAlexis** [comment]
Sorry about that, logs killed the server.

`cdn.pymedusa.com` is the right URL to use.
