### ISSUE TITLE
Post-Processsing Problem

### ISSUE THREAD

**Issue by pucelano7** [pymedusa/Medusa#3440]
**Branch/Commit:**
**OS:** DSM 6.1.4-15217 Update 2 (NAS Synology DS213)
**What you did:** I have installed Medusa recently and I am configuring it
**What happened: ** All works well: Medusa sends the .torrent file to Downoad Station and when the download finish Medusa move the downloaded file to the "TV Shows Folder"....the problem is that I would like move the file to the "season" folder and I have done a lot of tests and I cann't do it

As you can see I have ckecked _"Season Folder" option_
![captura1](https://user-images.githubusercontent.com/24883267/33799921-c79a282e-dd35-11e7-8b05-a7e299539f9a.PNG)

And I have checked the _"Create Missing Show Directories"_:
![captura4](https://user-images.githubusercontent.com/24883267/33799923-c7d3fd6a-dd35-11e7-9e1e-469c1fa6e687.PNG)

**An example:**
the Post-Processing moves the file from _"Downloader" folder_ to _"Alli Abajo" Folder_ (the TV Show's name) instead of move to _"Season 3" Folder_: 
![captura2](https://user-images.githubusercontent.com/24883267/33799922-c7b87216-dd35-11e7-9984-095296f15bae.PNG)

**Logs:**
![ejemplo log procesado manual](https://user-images.githubusercontent.com/24883267/33799924-c7f4bd7a-dd35-11e7-9274-debf6fab3371.PNG)

**Comment by labrys** [comment]
Do you have Season folders as part of your naming pattern?

For example `Season %0S/%SN - S%0SE%0E - %EN` would give results like `Season 02/Show Name - S02E03 - Ep Name.ext`.  Notice the `Season %0S/` at the beginning.

**Comment by pucelano7** [comment]
Ahhh! I don’t have it...I will test it now, I’m sure you give me the solution

Thanks a lot!!!!
