### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: CuriosityStream

### ISSUE THREAD

**Issue by nucshuco** [pymedusa/Medusa#3446]
### INFO
**Python Version**: `2.7.14 (default, Nov 30 2017, 01:13:54) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]
**Operating System**: `FreeBSD-10.3-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
**Link to Log**: https://gist.github.com/cc722ea37f437ff8d1d36c7318e8f964
### ERROR
<pre>
2017-12-09 18:28:53 ERROR    Thread-23 :: [1a8dc66] Missing time zone for network: CuriosityStream
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added
