### ISSUE TITLE
How to turn off the background on the show list screen?

### ISSUE THREAD

**Issue by Arendiel22** [pymedusa/Medusa#3468]
Is there a way to turn off the background image on the show list screen? It's currently cycling through the backgrounds of various shows in my list on refresh which is annoying. If there is no way to turn this off can this be added as a feature request? Thanks.

**Comment by fernandog** [comment]
advanced settings, interface.

**Comment by Arendiel22** [comment]
The only option there I see is to Show fanart in the background on the show summary page but I want to keep the artwork on the show summary page. I want to remove it from the show list page.

**Comment by fernandog** [comment]
You can't. All or nothing
