### ISSUE TITLE
Is there a way to set file size for download?

### ISSUE THREAD

**Issue by Arendiel22** [pymedusa/Medusa#3469]
I know we can set quality (720p vs 1080p, etc.) but is there a way to also define a max file size? So ask Medusa to download a 1080p version but only if it is below 1GB in file size? If not can this be added as a feature request? Thanks.

**Comment by labrys** [comment]
@Arendiel22 this feature has already been requested and is something that we will add in the future but there is no ETA.  Closing this issue as a duplicate of #1883.   A list of features requested can be found under issue #282 Master Feature List.
