### ISSUE TITLE
[APP SUBMITTED]: Deluge: Unable to set the label for Torrent

### ISSUE THREAD

**Issue by shadownetdev1** [pymedusa/Medusa#3474]
### INFO
        **Python Version**: `2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
        **Operating System**: `Linux-4.9.30-unRAID-x86_64-with`
        **Locale**: `None`
        **Branch**: [master](../tree/master)
        **Database**: `44.8`
        **Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
        **Link to Log**: https://gist.github.com/3470a4448cd3cc42be6b32a6cafb4645
        ### ERROR
        <pre>
2017-12-15 13:39:07 ERROR    SEARCHQUEUE-BACKLOG-94121 :: [1a8dc66] Deluge: Unable to set the label for Torrent
</pre>
        ---
        _STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@shadownetdev1 as error message: `Deluge: Invalid label. Label must not contain a space`

**Comment by rssfed23** [comment]
### INFO
**Python Version**: `2.7.14 (default, Jan 17 2018, 14:28:32) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]`
**Operating System**: `Linux-4.14.14-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/2a1e70be7330c70eae770713183c85e9
### ERROR
<pre>
2018-02-19 01:23:45 ERROR    SEARCHQUEUE-BACKLOG-263365 :: [ccbc0ce] DelugeD: Unable to set the pause for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rssfed23** [comment]
### INFO
**Python Version**: `2.7.14 (default, Jan 17 2018, 14:28:32) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]`
**Operating System**: `Linux-4.14.14-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/7643211fe8d8784f220213ba8c934a29
### ERROR
<pre>
2018-02-19 02:10:01 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [ccbc0ce] DelugeD: Unable to set the pause for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mrdeadlocked** [comment]
### INFO
**Python Version**: `2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]`
**Operating System**: `Linux-4.13.13-6-pve-x86_64-with-Ubuntu-17.10-artful`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/f5e674be07cb54b8d947b1a7c88a843d
### ERROR
<pre>
2018-03-24 20:34:42 ERROR    SEARCHQUEUE-FORCED-253323 :: [d6eb72d] DelugeD: Unable to set the pause for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mrdeadlocked** [comment]
### INFO
**Python Version**: `2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]`
**Operating System**: `Linux-4.13.13-6-pve-x86_64-with-Ubuntu-17.10-artful`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/fb05d5604f07e159955ce7544ea75b3f
### ERROR
<pre>
2018-03-25 22:13:56 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [d6eb72d] DelugeD: Unable to set the pause for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
