### ISSUE TITLE
[APP SUBMITTED]: Deluge: Invalid label. Label must not contain a space

### ISSUE THREAD

**Issue by shadownetdev1** [pymedusa/Medusa#3475]
### INFO
        **Python Version**: `2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
        **Operating System**: `Linux-4.9.30-unRAID-x86_64-with`
        **Locale**: `None`
        **Branch**: [master](../tree/master)
        **Database**: `44.8`
        **Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
        **Link to Log**: https://gist.github.com/b4167b811ece0c7b1adb56dcf10ca2b4
        ### ERROR
        <pre>
2017-12-15 13:39:07 ERROR    SEARCHQUEUE-BACKLOG-94121 :: [1a8dc66] Deluge: Invalid label. Label must not contain a space
</pre>
        ---
        _STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
as title. Label can't have space
