### ISSUE TITLE
Yggtorrent Unable to login to provider

### ISSUE THREAD

**Issue by minibombardo** [pymedusa/Medusa#3490]
**Branch/Commit: Master
**OS: Ubuntu 16.04 - Quickbox
**What you did: torrent search
**What happened: error message in the logs
**Logs: 2017-12-18 10:53:26 WARNING  SEARCHQUEUE-MANUAL-62710 :: [Yggtorrent] :: [1a8dc66] Unable to login to provider

since this weekend I can not find torrent anymore

when i go to the site with my login all works

**Comment by adaur** [comment]
Switch to dev

**Comment by minibombardo** [comment]
@adaur 
and comment on making the change?

I find nothing on the subject
