### ISSUE TITLE
Ignored Words

### ISSUE THREAD

**Issue by pucelano7** [pymedusa/Medusa#3493]
**OS:**DSM 6.2 (NAS Synology)
**What happened:** I'm trying to use the "Ignored Words" Options to avoid download version with subtitles of some TV Shows but I have a lot of doubts

I can see three types of name of the episode:
- Name of File (Nombre de archivo): 'Blindspot - Temporada 3 [HDTV 720p] [Cap.307] [V.O. Subt. Castellano]
- URL: 'Blindspot.Temporada.3.Capitulo.7.HDTV.720p.AC3.5.1
- Name of File Downloaded: 'Blindspot_307VOSE_720p.mkv'

![blindspot1](https://user-images.githubusercontent.com/24883267/34111841-24467aec-e40b-11e7-94c9-a73987a87104.PNG)
![blindspot2](https://user-images.githubusercontent.com/24883267/34111843-2467a8c0-e40b-11e7-8983-4f8dd4547899.PNG)

I would like don't downloaded this version and wait for the spanish version (Without subtitles) in 2-3 days...but I am testing with different words to avoid the download and I don't get it.
I tried with 'Subt', 'Subt.', [V.O. Subt. Castellano]...
![blindspot3](https://user-images.githubusercontent.com/24883267/34111884-46dc2138-e40b-11e7-8eca-549908e9aee5.jpg)

Can anyone give a clue, please

Thanks!!!!

**Comment by medariox** [comment]
Just add `V.O. Subt. Castellano` without additional dots.

**Comment by fernandog** [comment]
@pucelano7 ignored words is for torrent/nzb name only. It doesn't apply to filenames

**Comment by pucelano7** [comment]
@medariox @fernandog Thanks!!! It was so useful to get it :-)
