### ISSUE TITLE
Info about Scheduler?

### ISSUE THREAD

**Issue by pucelano7** [pymedusa/Medusa#3496]
I don't know if this is the correct place for my question...if I'm wrong change it to the correct place or delete it, please

My question:
Is there any place when I can read some little explanation about the Scheduler? Just to understand better how MEDUSA works

![scheduler](https://user-images.githubusercontent.com/24883267/34134232-bbc5ceec-e459-11e7-86f9-db734935a6cf.PNG)

Thanks!!!

**Comment by labrys** [comment]
Most of the columns explained:

Scheduler: Name of the scheduled task
Alive: If the task is working or has crashed
Enable: If the task is enabled or not
Active: If the task is currently running
Cycle time: Frequency the task repeats
Next run:  Time till task is run again
Last run:  Time the task last run

**Comment by pucelano7** [comment]
@labrys Thanks a lot!!!

And the tasks? I suppose the following:
- Show update: search information about the TV Shows. For example: airdate, name of the chapters...
- Post Process: Medusa search in the "Post Process Folder" if there are files. If it finds it process it as we have configured in "post-process options"
- Backlog: Medusa execute the actions that we can find in "Backlog Overview section".
- Subtitle finder: search the subtitles if we have activated this option in same TV Show.
- Trakt checker: analyze the status of the chapters???
- Show Queue: process the queue of shows pending
- Search Queue: process the queue of shows for search.
- Version Check: analyze the version of shows we have (prefered o allowed)
- Proper Finder: searching of the "proper version" (according to the values we have in "proper settings")
- Torrent checker: 
- Daily Search: 

Thanks!!!
