### ISSUE TITLE
Yggtorrent : Unable to login to provider

### ISSUE THREAD

**Issue by famelartBenoit** [pymedusa/Medusa#3505]
Medusa Info: Branch: master
Commit: 1a8dc66c7ec9231be0d3444710e476437c9ae1c8
Version: v0.1.20
Database: 44.8
-- | --
Python Version: | 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
SSL Version: | OpenSSL 1.0.1t 3 May 2016
OS: | Linux-4.9.0-0.bpo.4-amd64-x86_64-with-debian-8.9
Locale: | fr_FR.UTF-8

```
[Yggtorrent] :: [1a8dc66] Unable to login to provider
```

Hi,

Since this morning, i got this issue. Can't login on yggtorrent. It works with the regular website, with jackett, but not with medusa.

Is it from yggtorrent website or of medusa ?

thanks

**Comment by adaur** [comment]
Fixed in develop
