### ISSUE TITLE
[FEATURE]  Scheduled database backups

### ISSUE THREAD

**Issue by joelang1699** [pymedusa/Medusa#3508]
Is it possible to build in an automatic database backup function?

**Comment by p0psicles** [comment]
Just copy the .db files. It's sqlite.

**Comment by labrys** [comment]
@p0psicles we've actually had a lot of people ask for this in the past, might not be a bad idea to implement in the future

@joelang1699 are you aware that the databases are backed up every time Medusa updates through the UI?

One issue with this is the database is in active use so Medusa would need to restart to backup the database.  When Medusa restarts, the queue scheduling restarts too.  This can cause issues with scheduled tasks not triggering when expected or even not at all.  The scheduler would need to be revamped before this could be implemented.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature Request List** to track all feature requests.  Discussion specific to this feature can continue in this thread
