### ISSUE TITLE
Search Providers - Only download Freeleech - TRUE

### ISSUE THREAD

**Issue by GritGub** [pymedusa/Medusa#3524]
OS: DSM 6 (NAS Synology)
Where: Settings->Search Providers->Provider Options
What happened: On any search provider, option "Only download Freeleech torrents" is set to TRUE, after MEDUSA restart, the value is FALSE.

Setup: Migration from Sickrage

Logs & screens:

<img width="776" alt="skaermbillede 2017-12-26 kl 22 41 31" src="https://user-images.githubusercontent.com/25592744/34365205-fd0dae12-ea8d-11e7-8568-2421bdfbb869.png">

When setting is set to TRUE, I get this in debug log. 
<img width="861" alt="skaermbillede 2017-12-26 kl 22 42 47" src="https://user-images.githubusercontent.com/25592744/34365216-254eda36-ea8e-11e7-89d4-b49f51b4a9d2.png">

<img width="742" alt="skaermbillede 2017-12-26 kl 22 48 27" src="https://user-images.githubusercontent.com/25592744/34365290-f91a87f2-ea8e-11e7-9397-796a51ae01f3.png">

**Comment by medariox** [comment]
Thanks for the bug report! Fixed with https://github.com/pymedusa/Medusa/pull/3538

**Comment by GritGub** [comment]
Great job, thanks. When will this be released to Master? Or is there any way I can implement this commit to my current ver?

**Comment by p0psicles** [comment]
You can run develop. It's mostly stable. But where going to merge some bleeding edge changes soon. But it should always be fit for production
