### ISSUE TITLE
Not possible to select 'anime' when adding an existing anime series

### ISSUE THREAD

**Issue by h3llrais3r** [pymedusa/Medusa#3529]
I don't see the 'anime' checkbox when adding existing shows.
Do I need to import all my shows individually and check the anime option?

![image](https://user-images.githubusercontent.com/1945295/34379601-6e2f1df6-eafc-11e7-955b-83e1fe25ab69.png)

EDIT: even when I check the 'scene numbering' checkbox, the series is added without the flag...
I need to check it again after it's added.
In fact, it takes the default (saved) settings instead of the ones chosen when adding the show/anime.

When I check 'prompt me to set settings for each show', I'm not able to continue.
![image](https://user-images.githubusercontent.com/1945295/34380078-322d7552-eaff-11e7-8c04-4940d28e5e17.png)

Getting this dialog when trying to add the show.

![image](https://user-images.githubusercontent.com/1945295/34380104-5c68d4ce-eaff-11e7-83ba-004d740884bd.png)

**Comment by h3llrais3r** [comment]
I've checked the code, and when adding existing shows, the shows are added with the default (saved) settings. This means that the 'customized options' are not taken into account, unless they are saved as default. 
However, the flag anime is still missing. I'll make a PR to add it, so we can at least save it by default when adding existing shows.
If we want to take the options into account without saving, a refactoring will be needed.
For now I can live with the fact that I need to save it as default before adding anime series in bulk.
One more remark: I don't think we shoud enable the black/white list when anime is selected for adding existing shows... This because this fetches the groups from anidb (if enabled) and this is unusable when multiple series are selected.

**Comment by p0psicles** [comment]
We're going through a refactor of our frond end scaffolding. This will eventually implement the possibility of adding isolated themes. Can you wait until we've finished that?

**Comment by h3llrais3r** [comment]
Just did the quick fix ;)
Did not do big things.
