### ISSUE TITLE
Simple layout issue when splitting anime and shows

### ISSUE THREAD

**Issue by h3llrais3r** [pymedusa/Medusa#3532]
Shows should be listed on top.
Now the shows table is appended at the end of the anime list.

![image](https://user-images.githubusercontent.com/1945295/34382022-7d096286-eb0c-11e7-8e33-0d9d08034890.png)

**Comment by p0psicles** [comment]
Aah I see. It's a little messed up.
I'll see if I can improve it a little. Don't know if I want to split up the table. But maybe that's the best solution here.

**Comment by h3llrais3r** [comment]
It should be possible to split up the tables. (I think it was split up before)

**Comment by p0psicles** [comment]
You fixed it yourself. Nice PR!

**Comment by h3llrais3r** [comment]
Yes, just sorry for copy paste errors (double if statements) :rofl:
