### ISSUE TITLE
No access from outside localhost

### ISSUE THREAD

**Issue by ceeboonan** [pymedusa/Medusa#3535]
**Branch/Commit:**
Branch: master
Commit: 7b9111eef5836a6846499ef257ffff3f1f35df8f
Version: v0.1.22
Database: 44.8
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2j 26 Sep 2016
OS: | Windows-10-10.0.16299
Locale: | de_DE.cp1252

**What you did:**
I tried to connect with my android to medusa. Ports are forwarded.
**What happened:**
Can't connect due to time out.
**What you expected:**
I thought to browse medusa from the internet, at least from inside my network. SickGear is running fine in that case.
**Logs:**
Nothing interesting related to this case.

**Comment by fernandog** [comment]
Are you running medusa in the same port as SickGear?

**Comment by ceeboonan** [comment]
No, all services are running different ports. SickGear and Sickbeard/rage are installed but just for knowledge.

**Comment by fernandog** [comment]
can you access locally? do you use any web root?

**Comment by ceeboonan** [comment]
Yes, that's no problem. Do you mean web root at my local computer or at my android? Just the ones that are installed already.

**Comment by bobbysteel** [comment]
is windows 10 firewall getting in the way? try shutting down SickGear and using Medusa on that port.

**Comment by ceeboonan** [comment]
> is windows 10 firewall getting in the way?>
That's it! Made a exception and works like a charm now. Thanks alot!
