### ISSUE TITLE
[FEATURE] Post-Processor ignore folders beginning with #

### ISSUE THREAD

**Issue by tomhumphrey** [pymedusa/Medusa#3551]
I run Medusa on my dockerized on my Synology NAS. I can see from the Logs that folders beginning with a '.' or a '@' are ignored by the post-processor. Would it be possible to ignore folders starting with '#' as well. Synology uses the folder #recycle as a recycle bin for deleted files. It's a bit annoying that this then gets searched by the post-processor as well.

**Comment by tomhumphrey** [comment]
Thanks @fernandog 👍

**Comment by Mikii67** [comment]
Hi. This still fires up a warning on my Medusa Version: 0.5.22?:

`WARNING  POSTPROCESSOR :: [1405fbb] Missed file: /volume2/Downloads/medusadownload/@eaDir: Hidden or ignored folder
`
