### ISSUE TITLE
[Feature] separated themed frontend

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#3564]
I'd like to propose a new feature name "themed frontend"
Currently we're utilizing one 'mako' templated frontend, with a css for a light and dark theme.
I'd like to add a feature where it's possible to select a complete different frontend (html/mako, css and js) but reuse the existing endpoints. As discussed with @OmgImAlexis this could be realized by including the them in the routes.

### Routes
Currently we have one route buildup as follows:
`{optional_webroot}/{main_route}/`

In the new situation we would have a themed route:
`{optional_webroot}/{theme_id}/{main_route}/`

### Deliverables
As part of this project we will deliver:
* A default theme (let's pick the dark or light theme). This theme will be further developed.
* The alternative light/dark theme.
* A legacy theme, which will freeze and support all current features available to users using internet explorer 11.
* The ability for users to add their own theme, through copying one of the existing themes.

### Solution
I was thinking about using a folder structure that includes html+css. ~~But have the js in a separated `source` folder. And have the js bundled into the new folder structure.~~

Each theme folder will include:
* Full html/mako
* Full js build
* Full css
* All Images
* package.json including versions. This will be useful if we ever want to separate the theme from the subversion management. We've chosen to use npm for package distribution. More about this in the chapter Theme Packaging.

### Directory structure.
```.
themes/[theme name]
├── assets
│  ├── css
│  │ └── main.css
│  ├── img
│  │ └── logo.png
│  └── js
│     └── index.js
|── package.json
|── templates
│  └─ index.mako 
|── vue
│   ├── build.js
│   ├── build.js.map
│   ├── build.min.js
│   └── build.min.map
└─ index.html (SPA)

```
For the existing themes (dark, light, legacy) we will initially maintain it's source, in:
```.
themes_default/[theme name]
├── static
│   ├── css
│   │   └── main.css
│   ├── img
│   │   └── logo.png
│   └── fonts
│   └── js
│       └── index.js
├── package.json
└── views
│   └─ index.mako
└── vue
    ├── src
    ├── test
    ├── locales
    ├── .babelrc
    ├── index.html
    └── package.json
```

### Theme packaging
Themes will be packaged as npm packages, and will therefor have a package.json. The package.json can be used as metadata for the theme, like a version, name, and optionally other dependencies, and a minimum supported medusa version. Here is an example of a manifest. But additional keys can be added of course:
```json
{
	"version": "0.1.0",
	"name": "legacy",
	"author": "p0psicles"
}
```

**Comment by OmgImAlexis** [comment]
The js would have to be theme specific as we rely on DOM elements and if they're not there or have missing/extra classes the js won't work or will break in weird ways.

**Comment by p0psicles** [comment]
I was thinking about providing a shared library. And have each theme the ability of adding their own. But maybe that's only possible if we use a framework that really had components like vue.js.

**Comment by medariox** [comment]
I think this is a great idea. It will definitely improve users contributions and can bring some awesome work from external developers. 👍

**Comment by OmgImAlexis** [comment]
In regards to the directory structure this is what I propse.

If `templates` is included we render server-side as an old style theme. This will be what we use for the current theme until it's all moved to requesting data from the API instead of local render data. The `templates`dir will be depreciated and un-documented.

We'll serve `assets` at `/` and if they want to use an SPA then `templates` should be missing and instead a file called `index.html` added to `assets`. We then serve the `index.html` at `/` and all 404s like an SPA would. 
```.
├── assets
│   ├── css
│   │   └── main.css
│   ├── img
│   │   └── logo.png
│   └── js
│       └── index.js
├── meta.json
└── templates
    └── index.mako
```

**Comment by OmgImAlexis** [comment]
We still need to discuss how we'll ship our themes, I was thinking we could use travis to build our src dir and then post a `tar+gzip` file to Github's release API we'd then get Medusa to download the theme when it installs or updates.

Once we finally seperate our theme from mako files we could even move the theme to a new repo allowing it to be updated and changed without the backend changes interfering.

**Comment by OmgImAlexis** [comment]
For the future the last known working IE version was https://github.com/pymedusa/Medusa/commit/4f6f8e8362cd6e941ad70ae86c40df1a92e956bb

**Comment by p0psicles** [comment]
@OmgImAlexis I think it's maybe a good idea to make the dark/light configuration for the dark/light themes, part of the manifest.json. Then we only need to keep one dark/light them in the `themes-default` folder. And at build time we can generate two dist builds. One for light and one for dark. We'll have to make to make some addaptations to the mako and css. But that will be less work then maintaining two themes.

**Comment by p0psicles** [comment]
Also keep in mind, that we're always serving one theme! So if the `legacy` theme is configured. It's only able to serve mako files from `/themes/legacy/templates`.

**Comment by p0psicles** [comment]
Changed the packaging chapter to use a package.json in stead of the manifest.json.

**Comment by Tailslide** [comment]
Hi, just migrated to Medusa and noticed IE doesn't work for me.. is there a branch where this is working?  Or should I roll back to Dec 31 ?  

Thanks for all your hard work it's really impressive what you've accomplished in a short amount of time.

**Comment by p0psicles** [comment]
Your using ie11? You should switch to the legacy theme.
Or use a modern browser like chrome or firefox.

**Comment by Tailslide** [comment]
Thanks, I tried the legacy theme but it still does not display any page.
I also tried compatibility mode and clearing my cache with no success.

**Comment by OmgImAlexis** [comment]
@Tailslide please open a new issue instead of polluting this one.
If you're able to use another browser I'd highly recommend that.

**Comment by OmgImAlexis** [comment]
@p0psicles shall we close this now?
