### ISSUE TITLE
Error Connecting To Websocket

### ISSUE THREAD

**Issue by Miicker** [pymedusa/Medusa#3569]
Branch: master
Commit: 7b9111eef5836a6846499ef257ffff3f1f35df8f
Version: v0.1.22
Synology DSM 6.1.4-15217 Update 5 (Medusa runs in a Docker container)

I recently switched from SickRage to Medusa. Both running in a Docker container. Medusa runs fine, except for a annoying issue:
Every time I open Medusa, open a show, or go to the settings (basically every time when I load another webpage from Medusa) I get this annoying pop up telling met "Error connecting to websocket. Please check your network connection. If you are using a reverse proxy, please take a look at our wiki for config examples."

And I am using a reverse proxy, I am using Synology's build in service, and it worked just fine with SickRage. It still works fine with NZBGet, Radarr, Hydra and a lot of other applications that I run on my machine. Radarr is giving me this error, and I know an easy fix would be to turn off browser notifications, but I like them and wan't them to be turned on.

The error only is shown when I access Medusa trough my domain, so this is for example the url I use to access Medusa:
https://medusa.mydomain.com
When I do that, I receive the popup. When I access Medusa through the network (for example: 172.0.0.50:XXXX, XXXX being the port number) I do not receive any message.

Since I use Synology's build in reverse proxy, I cannot edit the configuration. I think editing the webroot could solve this problem, but since I use a subdomain and not for example "mydomain.com/medusa", I am not able to use this setting.

How can I fix this problem, or how can I change the base URL that Medusa uses to for example "medusa.mydomain.com" (if that fixes the problem).

Thanks in advance.

**Comment by OmgImAlexis** [comment]
What reverse proxy are you using? You'll need to enable websockets.

Those other programs you listed as well as an older version of Medusa doesn't use websockets and that's why you don't get any warnings from the others.

**Comment by labrys** [comment]
This may help you configuring your syno with websockets. https://forum.synology.com/enu/viewtopic.php?t=119672

**Comment by Miicker** [comment]
@labrys I've tried this and it works! No more annoying errors :)
Thank you!
