### ISSUE TITLE
WARNING  SHOWQUEUE-UPDATE

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#3570]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:   develop
**OS:       Linux-4.10.0-42-generic-x86_64-with-LinuxMint-18.3-sylvia
**What you did:   Updated the shows
**What happened:   Warning 
**What you expected: imdb info
**Logs:**
```
PASTE LOGS HERE
Debug log:https://gist.github.com/ripper1967/e942c4818ed0356197edb28c7130df58
Warning Log: https://gist.github.com/ripper1967/47efe8614ec49d88023d671cb409557d

**Comment by p0psicles** [comment]
More info here: https://github.com/richardasaurus/imdb-pie/issues/49
We need to wait for that to have been fixed.
