### ISSUE TITLE
IMDB API 404 error

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#3571]
Medusa Info: | Branch: master                 Commit: 7b9111eef5836a6846499ef257ffff3f1f35df8f                 Version: v0.1.22                 Database: 44.8
-- | --
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

It seems that IMDB have revoke the API key that Medusa is using, or they are having issues themselves
![image](https://user-images.githubusercontent.com/4103090/34567320-18344374-f162-11e7-9bfe-a972ce3473b9.png)

**Comment by p0psicles** [comment]
Yes already reported. Tnx.
