### ISSUE TITLE
[Feature] Stop searching for preferred qualities after initial search period

### ISSUE THREAD

**Issue by moryoav** [pymedusa/Medusa#3580]
There's an issue in Medusa with the current implementation of "qualities". 

As it is set up now, a user can have a list of "Allowed" qualities for a show (for example: 720p, 1080p, etc) and "Preferred" (for example: 4k qualities). This is a typical scenario I am sure many users with 4k TVs started using, what with a very limited amount of shows that have 4k qualities.

The rationale is for a show to download in HD quality but if there's a 4k quality then the user would prefer that over the HD. If HD was downloaded first, the 4k version should download later. The problem is that there is no definition for time expiration for searching for "Preferred" quality. A show can end, an episode can be watched a long time ago, and it'll still try to search and download a Preferred version for that show. Logically, I would say that if within a certain amount of days you can't find the Preferred quality, no point to continue looking. 

My feature request: Under Settings->Search Settings->Episode Search, under "proper search days" (which is a similar concept to this feature request, just with "Proper" versions), add an option for "Preferred search days". If that number of days passed since downloading the Allowed version, stop looking.

**Comment by labrys** [comment]
That's a logical request.  You can get this type of behaviour through manually changing episodes to an Archived status when you no longer want them to search for a preferred quality.  A question for your feature request though, would you still want a 4k search result downloaded if it was found during a daily search?

**Comment by moryoav** [comment]
It would make sense for episodes to automatically archive themselves after a certain amount of days and so they won't be searched at all during a normal daily search.

**Comment by labrys** [comment]
Just to make sure you understand what a daily search is vs a backlog search.  Daily search is a constant ongoing process that checks your provider for any recently added releases and downloads anything that's wanted.  Its a very efficient way of getting missing items.  Backlog search on the other hand does a search for a single missing item at a time on each provider and is significantly less efficient but is more likely to find results.  Archived status will not replace existing files with a preferred quality even if found later during a daily search, but an auto-archiving feature would likely be easier to implement than just preventing backlog searching.

**Comment by moryoav** [comment]
I think that this is exactly what should happen - meaning the files should auto-archive and therefore not downloaded ever again, not during a daily search and not in a backlog search. Is that not a similar implementation to what happens with "proper search days" option? After a certain amount of days, proper versions will not be downloaded no matter what, and that would be the correct behavior, assuming the user either ends up watching the episode a few days tops after it was downloaded, or the download was flagged and a proper was released soon after the original. A similar thing happens with qualities. If a 4K version is not available within a few days, it becomes irrelevant. The episode is either watched, or a 4K version is a lot less likely to be out there.

**Comment by labrys** [comment]
I wanted to confirm that's what you intended, but needed to clarify.  Also you have to keep in mind users use-cases and desired qualities.  For example, say someone allows 4K but prefers a lower resolution such as 720p for space savings.  If a show is initially acquired in 4K, there's a fairly high likelihood that a 720p resolution will be available in the future, but they don't want it doing an inefficient backlog search for it.  Personally I think the auto-archive feature as we've already described it is sufficient for most cases though.

**Comment by fernandog** [comment]
I don't think it should auto archive. But I agree it shouldn't search if time has expired.

**Comment by hannonq** [comment]
Has this issue been solved? If yes, how can I achieve what OP desired?
If no, is the only workaround manually setting the episodes to "Archived"?
