### ISSUE TITLE
Double listings in show updates

### ISSUE THREAD

**Issue by flick1999** [pymedusa/Medusa#3584]
Even after dumping my DB and starting from scratch, I'm still seeing some shows listed twice when the update jobs run. Screenshot shows a couple of examples. Any suggestions? Thank you.

![2018-01-07 13_04_51-medusa - status](https://user-images.githubusercontent.com/1957542/34653606-89ebcab4-f3ab-11e7-98b1-c1a3654ee863.png)

**Comment by p0psicles** [comment]
I suspect they're season updates. Meaning arrow could updated two seasons at the time. I'll see if I can add the updating season to the report.

**Comment by phraymond** [comment]
Ah, that would make sense. Thanks!
