### ISSUE TITLE
Recommended HEVC search settings ?

### ISSUE THREAD

**Issue by Trotter73** [pymedusa/Medusa#3586]
Hi,

Not a bug, but a request for clarification.

If I want to MEDUSA to grab 720P HEVC releases what is the optimum quality settings I should use.

Having migrated over from SickRage I currently use the following:-

Allowed Quality: Unknown
Preferred Quality: Unset
Ignored words: 1080P
Required words:- HEVC,720P

This does seem to work however I do seem to miss releases, is there a better way to search for a 720, HEVC release in MEDUSA ?

Thanks,

**Comment by fernandog** [comment]
You need to choose 720p in allowed too

**Comment by Trotter73** [comment]
Hi, thanks for getting back to me..

So if I add 720P into allowed, would I then remove 720P from Required Words & 1080P from Ignored words ?

**Comment by fernandog** [comment]
Keep everything else as you may have unknown with 720p in it

**Comment by bobbysteel** [comment]
if you ONLY want HEVC then you can put x264, h264 into ignored words. But that will miss many things that aren't available in HEVC of course.

**Comment by Trotter73** [comment]
HEVC is not that popular yet so I have kept my default setting as SD, but for shows that regularly have HEVC posts I've been moving them over. I have added 720P as fernandog suggested and will give that a whirl and see how it goes. 

I have read that qualities are a right house of cards and without a big re-write not much can be done, is it something you guys are going to look at ? I'm well impressed so far, but that would be the icing on the cake :)

Thanks again...
