### ISSUE TITLE
Post processing throws error

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#3597]
I was processing 2 shows in manual PP 2 of the shows were single episodes x 4 and the other show was the whole complete S01-S11. I think this come up between the large show processing and the other show's single episodes starting.

```
2018-01-10 19:49:05 ERROR    Thread-18 :: [1a8dc66] Exception generated: u'f73eb62919bef913bba4a4ec35a7f759e36060f7'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 263, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/post_process.py", line 50, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 174, in process
    app.RECENTLY_POSTPROCESSED.pop(info_hash)
KeyError: u'f73eb62919bef913bba4a4ec35a7f759e36060f7'
```

**Comment by fernandog** [comment]
Seems you PP same torrent twice. Right?
When it PP a given info hash it gets removed from the "queue". This happened because it tries to move same torrent again

**Comment by labrys** [comment]
From @OmgImAlexis description I'm wondering if it might be the two different downloads with same infohash, one as part of season pack and the other as an individual torrent.  Ofc this is dependant on how infohashes for multi-ep releases are calculated.

**Comment by OmgImAlexis** [comment]
@labrys I believe that's correct.

**Comment by fernandog** [comment]
@duramato can info hash for season pack be the same for single e

**Comment by duramato** [comment]
No. That would only be possible if there where hash colisions. We are talking about a single file vs a multiple files in a directory.

**Comment by labrys** [comment]
Ok.  I was wondering if the episodes within a season pack were hashed separately.  If so then you could have them hash the same for the contained episodes if the episode was a duplicate.  If the multieps hash the collection then there would be virtually no chance of this.

**Comment by medariox** [comment]
It's not possible to post-process the same episode twice unless it is manually forced.
