### ISSUE TITLE
Network timezones not found. (One mismatch and one missing)

### ISSUE THREAD

**Issue by EraYaN** [pymedusa/Medusa#3601]
This is for two Korean networks. (Asia/Seoul timezone)

MBC Every 1 -> MBC Every1 
Second one shouldbe correct, used like this on TVDB and the Korean text has one word `MBC 에브리원` or `MBC ebeuliwon`. And well "Everyone" is one word.

[Channel A](https://en.wikipedia.org/wiki/Channel_A_(TV_channel))

**Comment by medariox** [comment]
Can you submit a PR here please? -> https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt

**Comment by EraYaN** [comment]
Will do.
