### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: BBC Two

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#3642]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@c25e86ae79fc50db3cfc8b63c9126be16fadf64a
**Link to Log**: https://gist.github.com/c1b87c4115d207e4c91db0d9f0ede639
### ERROR
<pre>
2018-01-21 16:06:34 ERROR    DAILYSEARCHER :: [c25e86a] Missing time zone for network: BBC Two
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.13.0-26-generic-x86_64-with-LinuxMint-18.3-sylvia`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@c25e86ae79fc50db3cfc8b63c9126be16fadf64a
**Link to Log**: https://gist.github.com/9f502229cbf5d6c6cda01b17ed967b7a
### ERROR
<pre>
2018-01-21 14:04:59 ERROR    Thread-23 :: [c25e86a] Missing time zone for network: BBC One
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.13.0-26-generic-x86_64-with-LinuxMint-18.3-sylvia`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@c25e86ae79fc50db3cfc8b63c9126be16fadf64a
**Link to Log**: https://gist.github.com/c6323f6799e5192d2609c60879bad246
### ERROR
<pre>
2018-01-21 14:04:59 ERROR    Thread-23 :: [c25e86a] Missing time zone for network: BBC Two
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rtrevino70** [comment]
### INFO
**Python Version**: `2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`
**Operating System**: `Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/1cd47827a999d7b3abee347cd429efd7
### ERROR
<pre>
2018-09-20 22:25:22 ERROR    Thread_0 :: [4614efc] Missing time zone for network: BBC Two
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Dale-J** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/9df14f2524799e37abe366c8f96fbe82
### ERROR
<pre>
2018-10-24 23:02:46 ERROR    Thread_1 :: [4614efc] Missing time zone for network: BBC Two
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
