### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Victor Entertainment

### ISSUE THREAD

**Issue by shadownetdev1** [pymedusa/Medusa#3659]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.9.30-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@bd0832551d836713481dd0a93f4118372bb5d963
**Link to Log**: https://gist.github.com/3a84eaef4311d2abea10c8c662d85198
### ERROR
<pre>
2018-01-23 23:57:02 ERROR    Thread-267 :: [bd08325] Missing time zone for network: Victor Entertainment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added.
