### ISSUE TITLE
[Feature Request] - Add option to add show in paused state

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#3666]
Sometimes when I add a show I would like the ability to add the show in a paused state so I can do for instance a manual download of a season pack or something else.

I know I can sort of get this behavior by setting `Status for previously aired episodes` & `Status for all future episodes` to ignored or skipped.

**Comment by p0psicles** [comment]
You can pause the show after adding it?

**Comment by Rouzax** [comment]
Most of the time I will be to late. 😄 
It will already have started with snatching episodes.

**Comment by p0psicles** [comment]
aah okay. Yea can be done, but prio is rather low for me atm.

**Comment by Rouzax** [comment]
No problem, this is just a nice to have.

**Comment by p0psicles** [comment]
Closing as added to master feature list.
