### ISSUE TITLE
Post-processing Extra Scripts permission issue

### ISSUE THREAD

**Issue by noodle-** [pymedusa/Medusa#3669]
**Branch/Commit:** master/ https://github.com/pymedusa/Medusa/commit/bd0832551d836713481dd0a93f4118372bb5d963
**OS:** Linux / Bananian (old debian-like)
**What you did:** added `/usr/bin/python /root/Scripts/SickrageToSyncthing.py` to the `Extra Scripts` option to be run after postprocessing
**What happened:** running the extra script fails due to permissions. 
**What you expected:** the script to run succesfully
**Logs:** 
```
[13:34:40] [POSTPROCESS]::SICKBEARD: Executing command: [u'/usr/bin/python', '/root/Scripts/SickrageToSyncthing.py', '/media/usb0/SickRage/Lucifer/Nothing.Illegal.S03E12.1080p.WEB-DL.h264.Trust.Me.-NTb.mkv', '/media/usb0/SABnzbd/done/Nothing.Illegal.S03E12.Trust.Me.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb/Nothing.Illegal.S03E12.Trust.Me.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv', '295685', '3', '12', '2018-01-22']
[13:34:40] [POSTPROCESS]::SICKBEARD: Script result: /usr/bin/python: can't open file '/root/Scripts/SickrageToSyncthing.py': [Errno 13] Permission denied
```

Further info:
SABnzbd sends completed downloads back to Medusa through NZBtoMedia, that whole process works. It's just my extra postprocessing script which fails run due to the medusa user not having the right permissions or the `SickrageToSyncthing.py` file not having the proper file permissions set.

I followed [the recommended guide](https://github.com/pymedusa/Medusa/wiki/Medusa-installation-Ubuntu-15) so I'm running Medusa as medusa:medusa. And I think this user does not have the right permissions to be running python or to execute that python file. 

Executing the file as root manually works.
I've already set medusa:medusa to be the owner of the `SickrageToSyncthing.py` file but that doesn't seem to help.

Any ideas on how to solve this besides running Medusa as root?

**Comment by p0psicles** [comment]
Can't you just change the user:group of `/root/Scripts/SickrageToSyncthing.py` to medusa:medusa?

**Comment by noodle-** [comment]
@p0psicles I've already done that. I thought the reason of the failure might be because it's in the /root/Scripts/ directory to which the medusa user (probably?) does not have access. 

![asdf](https://user-images.githubusercontent.com/812565/35430096-158e6854-0277-11e8-82cc-7c283ac2c11f.PNG)

I'm guessing I could place the script in the medusa user's home directory `/var/lib/medusa` but I'd rather not.

Do you know a quick way of running commands as another user?
` su - medusa -c 'echo "hello"' ` doesn't work, so I'm just going through the whole download process by starting a download from medusa for a single test run..

**Comment by p0psicles** [comment]
You need to make sure that the Medusa user has read+execute access to the folder.

So you can also change the group of the folder. Like chown root:Medusa folder. And chmod it to 750.

**Comment by noodle-** [comment]
@p0psicles 

![asdf](https://user-images.githubusercontent.com/812565/35434447-7584c6ee-0287-11e8-9c94-efae4d8e30e8.PNG)

`Script result: /usr/bin/python: can't open file '/root/Scripts/temp/SickrageToSyncthing.py': [Errno 13] Permission denied`

That should have worked right? I'm not even sure it's possible anymore.

I gave up on trying to launch it from that directory. I copied it to `/var/lib/medusa` and didn't give it any special rights, AFAIK it doesn't even need executable rights because it's being run through python and not directly.

![asdf1](https://user-images.githubusercontent.com/812565/35434826-d217ea70-0288-11e8-8349-2987bb11abb9.PNG)

This somehow works. 

If it's really impossible to do it the way that I tried it before then it might be nice to add a hint to the wiki/guide to recommend adding post-processing scripts to the medusa home dir. 
Want me to do that?

**Comment by p0psicles** [comment]
No, because that doesn't have anything todo with medusa. It's just basic linux knowledge.
I often recommend to create a folder in /opt. Like `/opt/PPscripts`. Then create a group that you share with applications that need to access the same files. Like a group `media-user`.
Then make your `medusa` user, `rtorrent` user, `sabnzbd` user all member of this group. And run the following commands to set the appropriate rights:
```
chown -R medusa:media-user /opt/PPscripts
chmod -R 750 /opt/PPscripts
chmod -R 660 /opt/PPscripts/*
```

**Comment by noodle-** [comment]
Thanks for the advice.
