### ISSUE TITLE
Long log lines end with ellipsis instead of full data

### ISSUE THREAD

**Issue by bobbysteel** [pymedusa/Medusa#3673]
Trying to debug a Transmission issue. Logs truncate as follows 
```
SEARCHQUEUE-DAILY-SEARCH :: [bd08325] Transmission: Requested a POST connection to http://server/transmission/rpc with params: None Data: {"arguments": {"queuePosition": 0, "priority-high": [], "ids": ["813f52931e85f7b25bc8738c4a4d5627a7...
```
I'd like to see the full JSON. Any ideas?

**Comment by p0psicles** [comment]
This is by design. As sometimes torrents are send as post data. And the logger didn't like this.

**Comment by bobbysteel** [comment]
How do you suggest I debug these JSON requests though?

**Comment by fernandog** [comment]
@bobbysteal you can revert this in your local setup to debug the issue


https://github.com/pymedusa/Medusa/pull/3406/files

**Comment by p0psicles** [comment]
You can run Medusa together with fiddler on windows.

**Comment by bobbysteel** [comment]
I run dockerized on Ubuntu.

**Comment by p0psicles** [comment]
Then install fiddler on Ubuntu

**Comment by p0psicles** [comment]
Or install tcpdump
