### ISSUE TITLE
Postprocessing not dealing with files in main folder

### ISSUE THREAD

**Issue by Panaetius** [pymedusa/Medusa#3678]
**Branch/Commit:** Master  bd0832551d836713481dd0a93f4118372bb5d963
**OS:** Arch Linux
**Logs:**
```
Processing path: /media/tv_temp
Found temporary sync files in folder: /media/tv_temp
Skipping post-processing for folder: /media/tv_temp
```

I have medusa set up with transmission as a torrent client. Torrents get downloaded to /media/tv_temp and then get moved by post-processing to /media/tv in the correct show folders.

Most torrents define a subfolder to download to, like /media/tv_temp/<torrent name>/ and those work fine with post-processing.

But some torrents are a single file and don't get downloaded into a subfolder, so they're just in /media/tv_temp/

Post-processing fails for those files if some torrents aren't finished yet (since the folder contains .part files), even though others in the folder are finished. So you could have 50 finished .avi files in /media/tv_temp/ and one .avi.part file and post processing (manual and automated) won't work for those 50 finished files.

It would be great to either be able to specify manual post-processing to still process files in a folder best-effort even if there are .part, or to have an option to force torrents to always be downloaded to individual subfolders (probably the better/safer option).

**Comment by p0psicles** [comment]
Can't you specify a separate folder for incomplete and complete?

**Comment by Panaetius** [comment]
Oh that's a good idea, I'll give that a try. I didn't even think of that, thanks!
