### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Acorn TV

### ISSUE THREAD

**Issue by DDA78** [pymedusa/Medusa#3681]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 16:23:38) [GCC 6.4.0]`
**Operating System**: `Linux-4.4.71+-armv7l-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@bd0832551d836713481dd0a93f4118372bb5d963
**Link to Log**: https://gist.github.com/03f756ac7393225a2ac2c5b77ed86a5b
### ERROR
<pre>
2018-01-29 22:03:22 ERROR    Thread-18 :: [bd08325] Missing time zone for network: Acorn TV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/2522a38bf6cad634bf98f8a1e88c55f0370370d1
