### ISSUE TITLE
Add EZTV.ag tracker

### ISSUE THREAD

**Issue by TTLucian** [pymedusa/Medusa#3692]
https://eztv.ag/

**Comment by duramato** [comment]
https://torrentfreak.com/eztv-shuts-down-after-hostile-takeover-150518/

Seems the people running that .ag domain are also piggy backing on other deceased torrent sites.
Also the torrents on that site are already avaiable from the existing sites.

**Comment by TTLucian** [comment]
That's 3 years old news. The eztv.ag site seems fine to me. Good thing we have Jackett.

**Comment by adaur** [comment]
All you seem to do here is complain about the lack of providers offered in Medusa, as well as promoting Jackett. This is not very constructive. If you want more providers in Medusa, and fast, you are more than welcome to write the code for them by yourself. Also do not forget that nobody is getting paid here...

**Comment by medariox** [comment]
We are never going to include a site that has willingly stolen the reputation of a well known and trusted tracker just to make money out of it, no matter how "fine it may seem".
