### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 36] File name too long: '/media/bigdisk/Anime/The Disastrous Life of Saiki K/Season 01/The Disastrous Life of Saiki K - S01E01E02 - The Disastrous Life of a Psychic + The Worst of the Worst! Riki Nendou + Shun Kaidou, AKA The Jet-Black Wings + Intelligent and Beautiful! Kokomi Teruhashi & Hot-Blooded! Dodgeball! + Reach Him! Sign of Love + Saiki Family Home Renovation! Drastic Makeover!! + Deceive! Mind Control.mkv'

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#3699]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-4-amd64-x86_64-with-debian-9.2`
**Locale**: `UTF-8`
**Branch**: [feature/add-theming](../tree/feature/add-theming)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@4e0d16b55903c9dc2bb98d593b530c203be803ff
**Link to Log**: https://gist.github.com/0e86def32496f17e413975c3b4bfc4b4
### ERROR
<pre>
2018-02-03 10:00:27 ERROR    POSTPROCESSOR :: [4e0d16b] OSError: 
Traceback (most recent call last):
  File "/opt/medusa/medusa/helpers/__init__.py", line 285, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/opt/medusa/lib/shutil_custom/__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 36] File name too long: '/media/bigdisk/Anime/The Disastrous Life of Saiki K/Season 01/The Disastrous Life of Saiki K - S01E01E02 - The Disastrous Life of a Psychic + The Worst of the Worst! Riki Nendou + Shun Kaidou, AKA The Jet-Black Wings + Intelligent and Beautiful! Kokomi Teruhashi & Hot-Blooded! Dodgeball! + Reach Him! Sign of Love + Saiki Family Home Renovation! Drastic Makeover!! + Deceive! Mind Control.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed in develop.
