### ISSUE TITLE
How do I Stop Upgrading Shows?

### ISSUE THREAD

**Issue by rbhamilton** [pymedusa/Medusa#3703]
Hey sorry I know this isn't the right format but I can't find any other way to ask a question.  I just switched to Medusa from SickRage and imported all my shows.  Easy.  Thanks!  Wonderful program.

However this morning I woke up and found Medusa had re-downloaded about 850 shows.

I've set my "allowed" quality to "any" and my preferred to 720P.  Meaning (to me) if you can get it in 720P then that's great but if you can only find it in SD that's fine.  But I'm not fixated on it.  Please don't re-download everything in 720P!!

How do I turn off the "upgrading" of older shows?  Is there any way to just disable that feature?  If there is, I can't seem to find it but I'm guessing it's something obvious.

Many thanks in advance for your assistance.

**Comment by fernandog** [comment]
@rbhamilton don't select anything in preferred

**Comment by rbhamilton** [comment]
Thanks for the tip!  How do I delete my Preferred option now that I've made it?

**Comment by fernandog** [comment]
Edit show, Unselected it

**Comment by medariox** [comment]
In a show's page, first button on the right:
![img](https://snapr.pw/i/c8c6b646c5.png)

You might also want to read **[this](https://github.com/pymedusa/Medusa/wiki/Qualities-Changes)** if you haven't already done so.

**Comment by medariox** [comment]
Closing as solved.
