### ISSUE TITLE
Bug: Backlog Overview show name listing does not follow the "Sort with "The", "A", "An"" option.

### ISSUE THREAD

**Issue by heymoe** [pymedusa/Medusa#3715]
```
Branch: develop (also noticed this in master)
Commit: 941599ac357bcdb9f81532fac56d187539468a60
Version: v0.1.22
Database: 44.9
Python Version:  2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
SSL Version: LibreSSL 2.6.3
OS: Linux-4.14.13-1-ARCH-x86_64-with
```

When the `Sort with "The", "A", "An"` option is **not** checked under `Settings -> General -> Interface`,  the sorting of the shows names when viewing the Backlog Overview screen is still sorted using "The", "A" and "An".

Example:
```
The Daily Show
The Blacklist
The Flash
etc..
```
Are sorted by "The" instead of just "Daily Show", "Blacklist" and "Flash" etc...

**Comment by sharkykh** [comment]
Fixed on develop.
