### ISSUE TITLE
Searcing with danish characters

### ISSUE THREAD

**Issue by NickyM** [pymedusa/Medusa#3720]
Unable to perform searches with æ ø å. oe instead of ø does not work neither.

Branch/Commit: master/bd0832551d836713481dd0a93f4118372bb5d963
OS: Windows Server 2012
What you did: Searching for show: Børnelokkerne
What happened: No results
What you expected: Expected to find this show: https://www.thetvdb.com/?tab=series&id=316315&lid=10
Logs:
2018-02-06 23:48:04 INFO     Thread-37 :: [bd08325] Error searching for show: Show search failed in getting a result with reason: Show bÃƒÆ’Ã‚Â£Ãƒâ€šÃ‚Â¸rnelokkerne not found
2018-02-06 23:48:04 INFO     Thread-37 :: [bd08325] Error searching for show: Show search failed in getting a result with reason: HTTPError

**Comment by labrys** [comment]
This is a long-standing bug.  You can add it via the api using the tvdb id.  To do so visit the following URL in your browser after filling in the appropriate sections:

http://**{HOST}**/api/v1/**{API KEY}**/?cmd=show.addnew&indexerid=**{TVDB ID}**&lang=**{LANG}**

 **{HOST}** = Your Medusa host/port  (e.g. `localhost:8080`)
**{API KEY}** = Your Medusa api key.  You can find this by going to the Gear -> General -> Interface tab -> Web Interface -> API key
**{TVDB ID}** = The tvdb id (`316315` for Børnelokkerne)
**{LANG}** = The language for the information on TVDB as a 2-letter abbreviation (e.g. `da` for danish)

**Comment by NickyM** [comment]
Great, thanks

**Comment by NickyM** [comment]
+1 for quick response and a doable workaround! :)

**Comment by NickyM** [comment]
Ran into another issue with this.

Often, the danish characters are replaced in the release name, which results in the searchers wont be able to find it.

ø = oe, æ = ae, å = aa.

Ex: Børnelokkerne -> Boernelokkerne.

**Comment by labrys** [comment]
Add Boernelokkerne as a scene exception for the show.

**Comment by NickyM** [comment]
My god. You man, are the holy grail of Medusa support!
THANKS!

**Comment by sharkykh** [comment]
#4260 fixes this issue:
![image](https://user-images.githubusercontent.com/10238474/40594430-d5e88f38-6237-11e8-8a60-70350e14ff4f.png)
