### ISSUE TITLE
Request: Adding shows without being found on indexers

### ISSUE THREAD

**Issue by NickyM** [pymedusa/Medusa#3721]
I would be nice, to manually add a show to be downloaded with out it can be found on indexers.
Example, a new season of MasterChef has just started in our country, but it ain't present on any scrapers.
I should be possible to add a feature that downloads these shows from a RSS feed.

**Comment by labrys** [comment]
@NickyM Have you considered adding it to the indexer site yourself?  Then the work spent adding it can benefit more than just a single person.

**Comment by NickyM** [comment]
Didn't know that was possible. Of course that's the way to go. Thanks

**Comment by labrys** [comment]
TVDB can sometimes be rude if they feel the request doesn't meet their requirements (too few episodes for example).   If so don't be discouraged, TVMaze can be used as an indexer and they have a much less restrictive policy for new shows.
