### ISSUE TITLE
FFMpeg not found

### ISSUE THREAD

**Issue by snowybunting** [pymedusa/Medusa#3724]
**Master**
**Centos 7.3:**

When Medusa starts, I get an "FFmpeg not found" error in the logs. Everything starts up fine, everything seems to be working correctly, I'm wondering why it is needed and if I really need to install it. 

From the application.log:
```
FFmpeg (ffprobe) not found on your system or could not be loaded.
Visit https://ffmpeg.org/download.html to download it.
If you still have problems, please check if the downloaded version matches your system.
To load FFmpeg (ffprobe) from a specific location, please define the location as follow:
  knowit --ffmpeg /usr/local/ffmpeg/bin <video_path>
  knowit --ffmpeg /usr/local/ffmpeg/bin/ffprobe <video_path>
  knowit --ffmpeg "C:\Program Files\FFmpeg" <video_path>
  knowit --ffmpeg C:\Software\ffprobe.exe <video_path>

```

**Comment by p0psicles** [comment]
Ffmpeg is used as one of the methods for retrieving video metadata during post processing. It's recommended to install the binary.

**Comment by snowybunting** [comment]
Thanks for the reply. I tried installing a Centos version via Yum from the nux-desktop repository a few days ago when I first saw the error, that version caused Medusa to not start. The logs from that have been pruned, so I can't post those. Is cloning it from github the preferred method for installing ffmpeg?

**Comment by p0psicles** [comment]
No. Better to use the distribution repository. I would be interested in the output of ffmpeg --version
