### ISSUE TITLE
[Feature Request] - Create Medusa for Movies

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#3741]
This is probably not going to happen, but nevertheless I'm going to ask for it anyway 😃 
Could you guys and girls start an automatic video library manager for movies based on Medusa?

It seems that the development of Couchpotato is winding down and is not being maintained regular anymore so there is a gap to fill.

**Comment by p0psicles** [comment]
Well let me tell you, it's not that crazy. Allot has already been done in medusa behind the scenes, to make this possible.

**Comment by p0psicles** [comment]
Closed because added to master feature list.

**Comment by Rouzax** [comment]
I know this is probably still very far out but my CouchPotato is starting to die and it isn't maintained anymore.  I've tried Radarr but the whole flow of that doesn't really fit me and a lot of the things that worked great in Couchpotato are severely lacking or missing, automated addition of movies based on criteria for example. The other is Post Processing flexibility, if it is not in the download client folder you're pretty much screwed.

I know it is still early till Christmas but you spoke so hopeful in February that I'm hoping for an early Christmas present 😉

**Comment by p0psicles** [comment]
Dont want to crush your dreams. But before we have time to work on big luxurious requests like that, allot of other enhancements have to be done first.

We dont have the amount of dev time to implement those in a timely fashion. So dont count on it to have been added this year.

**Comment by Rouzax** [comment]
So Christmas next year 😄 

I completely understand, I just really love the way your are handling this project and I know that a Movie version of it would blow Radarr and CouchPotato away.

**Comment by wallopthecat** [comment]
Christmas next year is almost upon us :)

**Comment by p0psicles** [comment]
Well in that case, I'll have to disappoint you. Still a couple of enhancements / features that have higher prio.

**Comment by p0psicles** [comment]
If you guys can find me a good vue.js Dev. I promise you I'm on this.

**Comment by wallopthecat** [comment]
I can assist but am new to Vue

**Comment by dark-swordsman** [comment]
I am a react dev that was actually trying to create my own replacement for Sonarr/Radarr. However, based on what I hear, Medusa solves literally all my problems, *except for movies*.

Is there anything specific that would be needed to be done to get movies working? I would happily fork and work on a movie feature myself. 

In the mean time I do plan to setup medusa and use it for most of my current media.

**Comment by p0psicles** [comment]
Adding movies would be A lot of work on both the backend (python) and frontend (vue.js). I don't have time for any of these tbh

**Comment by dark-swordsman** [comment]
> Adding movies would be A lot of work on both the backend (python) and frontend (vue.js). I don't have time for any of these tbh

In that case, what do you use for movies? Because I'd prefer to stay as far away from the *arr ecosystem as possible.

**Comment by p0psicles** [comment]
Yeah sorry. I don't know. Don't think there are a lot of alternatives for movies

**Comment by Rouzax** [comment]
> > Adding movies would be A lot of work on both the backend (python) and frontend (vue.js). I don't have time for any of these tbh
> 
> In that case, what do you use for movies? Because I'd prefer to stay as far away from the *arr ecosystem as possible.

Did use couchpotato on the past but that is not maintained anymore, I have switched to Radarr for movies and Medusa for TV shows.
What is the reason you want to stay away from *arr?

**Comment by dark-swordsman** [comment]
> Did use couchpotato on the past but that is not maintained anymore, I have switched to Radarr for movies and Medusa for TV shows. What is the reason you want to stay away from *arr?

It mainly comes down to that I have a lot of problems with features, functionality, and user experience with Sonarr mainly. But also that I had a terrible experience when asking for help in their support channel. Granted, I was relatively a linux noob at the time, but they made it as difficult as possible to try to use their software and many others have had the same problem.

**Comment by Rouzax** [comment]
> > Did use couchpotato on the past but that is not maintained anymore, I have switched to Radarr for movies and Medusa for TV shows. What is the reason you want to stay away from *arr?
> 
> It mainly comes down to that I have a lot of problems with features, functionality, and user experience with Sonarr. But also that I had a terrible experience when asking for help in their support channel. Granted, I was relatively a linux noob at the time, but they made it as difficult as possible to try to use their software by being extremely rude and many others have had the same problem.
> 
> I can settle for Radarr for movies, especially since the volume of video files should be much smaller, and I planned to create multiple qbit instances anyways. Just was hoping I can have a better all-in-one solution.

Yeah I understand they can be a bit unforgiving when asking for support, but it had gotten a lot better.
Have asked quite a few outlandish questions since I wrote a script to import TV and Movies from Qbit and am not using the standard download import handling of Radarr since that does not work for my flow.
They have been very helpful.

**Comment by 7ore** [comment]
I'll revisit this old thread, as I just searched if there was a "medusa for movies". I moved from Couchpotato to Radarr and I do not like the flow and lack of control in Radarr (pretty much same reason I use Emby instead of Plex), so I started to search for another alternative and [Watcher3](https://github.com/barbequesauce/Watcher3), does what I want from this kind of tool.
It is not especially active, so Radarr might be a better choice for those who accept the way that tool works.
But I thought I would recommend Watcher for those who want to find an alternative to Radarr...

**Comment by Rouzax** [comment]
> I'll revisit this old thread, as I just searched if there was a "medusa for movies". I moved from Couchpotato to Radarr and I do not like the flow and lack of control in Radarr (pretty much same reason I use Emby instead of Plex), so I started to search for another alternative and [Watcher3](https://github.com/barbequesauce/Watcher3), does what I want from this kind of tool. It is not especially active, so Radarr might be a better choice for those who accept the way that tool works. But I thought I would recommend Watcher for those who want to find an alternative to Radarr...

I have the same love/hate relationship with Radarr, I have managed to work around their default behavior with my own script to call their API to do post processing.

Have looked at Watcher3 but it seems that the owner has archived his repo

**Comment by 7ore** [comment]
Yes, I saw that too now. He did it yesterday... 
oh well, Maybe I try to put a harness on Radarr to minimize the issues.
