### ISSUE TITLE
Add Recommended -> IMDB gives error

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#3749]
Hi,

adding recommended shows from IMDB doesn't work. there are no errors or else to be seen in logs. 
the gui shows an error relating to u'ratingCount' ?

![error](https://user-images.githubusercontent.com/869637/36075220-f263f4d4-0f4b-11e8-9831-36a036a17a7d.png)

Branch: master
Commit: ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
Version: v0.2.0
Database: 44.8

**Comment by udochrist** [comment]
trakt and anidb are working fine fwiw

**Comment by p0psicles** [comment]
Tnx look into it.

**Comment by medariox** [comment]
Fixed in develop with https://github.com/pymedusa/Medusa/pull/3768
