### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: ALT Balaji

### ISSUE THREAD

**Issue by DDA78** [pymedusa/Medusa#3750]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 16:23:38) [GCC 6.4.0]`
**Operating System**: `Linux-4.4.71+-armv7l-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/3216e75ba3c3471c7b81e738e5fb0d89
### ERROR
<pre>
2018-02-11 21:21:05 ERROR    Thread-19 :: [ccbc0ce] Missing time zone for network: ALT Balaji
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added: https://github.com/pymedusa/medusa.github.io/commit/b435d0b99de1e3ea5502cfe49f82d1a5541a10ea
