### ISSUE TITLE
Can't delete show with "é" in show name

### ISSUE THREAD

**Issue by doopsuiker** [pymedusa/Medusa#3759]
Hi, 

I'm on the master branch on Windows 10.
I'm trying to delete the show "90 day fiancé", but when i try to delete the show, nothing happens.
In the logs I see that the "é" is replaced by "Ã©"

Is there a way to manually delete the show from the database?

Here is the relevant log, nothing else is added
2018-02-12 12:22:02 INFO     SHOWQUEUE-REMOVE-SHOW :: [ccbc0ce] 3139: Removing 90 Day FiancÃ©

**Comment by p0psicles** [comment]
you could download an sqlite3 editor. And open the main.db file.
There is a table tv_shows. and remove the shows from there.
Also remove all episodes in tv_episodes.

Can you maybe share your locale settings?
the gear -> help & info.

I've tested it on win7, deleted fine.

**Comment by doopsuiker** [comment]
My locale was nl_BE, I changed it to en_US, but no avail.
Anyway, I'll just delete it manually from the database
