### ISSUE TITLE
Feature Request:  Update Quality for all shows

### ISSUE THREAD

**Issue by rbhamilton** [pymedusa/Medusa#3760]
My problem is with the mass update feature.  It has a field for PREFERRED but not one for ALLOWED.  Either that or I can't seem to find it.  How do I a mass-update of ALL shows and change just the ALLOWED quality of the show without touching the preferred quality setting?

Problem is changing the PREFERRED field triggers a massive backlog search and might swamp your hard drive with duplicates and kills your data cap.

I have something like 80 shows.  They were imported from another product.  The "allowed" quality is set to all available qualities (4K, 1080P, 720P, SD, etc).  Since 1080P are often released first, Medusa grabs a 1080P torrent and starts downloading.  Problem is these releases are large - sometimes up to 3GB in size and can take quite a while to finish.  Meanwhile a few minutes after the 1080P is released, somebody releases a 720P or SD about 300MB in size.

Waiting a few minutes for a lower quality release means you can watch the show faster and save your bandwidth.

Unless I edit the ALLOWED quality to 720P or SD, I end up waiting to watch the show and blowing through my data cap.  I can individually manually edit the show to set ALLOWED to be SD or 720P leaving PREFERRED blank and save bandwidth and get the show faster.  Except I have to do it manually show by show by show.

Any ideas?

**Comment by Artwebb1986** [comment]
Where it says preferred quality in the mass update edit list select Custom and then Allowed and Preferred are right beside each other, and pick whatever you want.

**Comment by sharkykh** [comment]
As explained above, the text on the page is outdated / incorrect.
You can choose allowed / preferred qualities as you wish:
![image](https://user-images.githubusercontent.com/10238474/41744779-7be881a8-75ad-11e8-95a3-4710cdf391b0.png)
