### ISSUE TITLE
[APP SUBMITTED]: Automatic post-processing attempted but directory is relative (and probably not what you really want to process): Download

### ISSUE THREAD

**Issue by iioodii** [pymedusa/Medusa#3766]
### INFO
**Python Version**: `2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/71d1c5f09adb0a0d0f56b7ba92a9fc0f
### ERROR
<pre>
2018-02-13 08:11:35 ERROR    POSTPROCESSOR :: [ccbc0ce] Automatic post-processing attempted but directory is relative (and probably not what you really want to process): Download
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
You can't use a relative directory for auto post-processing.

**Comment by iioodii** [comment]
What do you mean "can't use a relative directory"

This is the same location ware my torrent Clint put the completed download "/volume1/download"

**Comment by medariox** [comment]
Try to set it again because it seems to be currently set to `Download`.

**Comment by labrys** [comment]
@iioodii you need to set it to `/volume1/download` not `download`
