### ISSUE TITLE
x265, hevc as prefered words not working?

### ISSUE THREAD

**Issue by trohnjavolta** [pymedusa/Medusa#3767]
**Branch/Commit:**
master/latest
**OS:**
osmc (debian stretch)
**What you did:**
Set x265, hevc as prefered words in global search settings.
**What happened:**
Medusa is grabbing x264 releases, but no x265. Also the dls aren't moved in backlog search.
**What you expected:**
Medusa dl'ing x264 if no x265 is avaiable is fine, but the episode should go into some backlog search to be continuously searched until x265 is avaiable

**Comment by bobbysteel** [comment]
It would be neat to have x265 as a preferred quality option (or tickbox to upgrade to x265 in that manner)

**Comment by p0psicles** [comment]
We can't include x265 within our current quality system, as it can be combined with multiple resolutions.
But maybe we can do something like a global 'upgrade' option. We'll discuss it.

**Comment by trohnjavolta** [comment]
That would be awesome.
I know x265 isn't "there" yet but I gets more and more attention from different sides. I love the reduced file size and to be honest I don't really notice the quality worsening described sometimes.

**Comment by bobbysteel** [comment]
Probably a low priority, but I'd imagine would be nicer to refactor this
entire selector based on like 3 columns

Resolution (multi selector)
[ SD, 720, 1080, 4k, 8k]

Rip type (multi selector)
[ DVD, HDTV, BluRay, Webrip]

Compression type (multi-selector)
[ Raw, x265, x264/default ]

(obviously ignoring impossible combinations like SD Bluray or 4k DVD)

The current model is a bit out of hand - I don't really ever want 8K and
that's a nuisance to be on every list. Very rarely 4k. And never RAW.

Likewise, I don't care much about the various grades of 720p. For most junk
shows want to eventually have x265 for archival purposes, but for next-day
viewing want anything 720p or above.

**Comment by p0psicles** [comment]
That requires a big rewrite of code. And we don't have the resources in the team to do that. It has been on our agenda for a long time.

**Comment by MarioCaires** [comment]
+1
Would be amazing if somehow we could set something like "preferred word(s)" per show! This way we could choose which shows we would prefer to download x265, hevc!
The x265 offer out there is still very limited, however I have found at least one tv show available in x265 and the size reduction with it is very compelling!

**Comment by trohnjavolta** [comment]
Imo there's already a reasonably good amount of x265 content out there, mostly torrents.

**Comment by HPMSGEN8** [comment]
@p0psicles is there no way you can have an x265 option and it will only look for x265 and what is defined. so there is no need to rewrite just a new option and it will then ignore all others and use this ?

**Comment by p0psicles** [comment]
You can use required words for that?

**Comment by HPMSGEN8** [comment]
Well i have tried and still it gets 720p HDTV. Maybe i am doing something wrong.

**Comment by OmgImAlexis** [comment]
Adding `HEVC` seemed to fix it for me. `x265` was hit and miss.

**Comment by trohnjavolta** [comment]
I just noticed the prefered words option but setting shows to it lets episodes already downloaded in hevc be replaced with higher quality x264 downloads. Is this desired behaviour?
I think I set quality to best, like bluray. But there aren't that many bluray hevc releases.

Lowering quality settings would rule out bluray releases.

I'd like both the quickness of x264 and the small size of hevc.
What I mean is: I noticed that after a release, x264 files are found much faster than hevc.

So, initial download should be x264 and after set period of time only search for hevc. 
Is this possible somehow?

**Comment by p0psicles** [comment]
Hevc isnt a recognized quality in Medusa, so that cant be used for upgrading a quality.

**Comment by HPMSGEN8** [comment]
@p0psicles This is seeming to be working but now what happens with Proper's if the HEVC is Nuked and the SD is the correct one to get. How should the seeings be as i have this for Required Works now on some shows:

HEVC, MeGusta

Thanks

**Comment by p0psicles** [comment]
Of the hevc gets nuked. A proper is released with the same codec. So it should only replace the nuked hevc with a proper hevc.

@duramato am i correct?

**Comment by duramato** [comment]
It only upgrades with a proper of the same codec.

**Comment by HPMSGEN8** [comment]
Then i only need to have HEVC nothing else or if the release i want is Nuked it will not pick anything else am i correct in this.

**Comment by p0psicles** [comment]
Okay wait a minute. We search for proper versions of already downloaded results for a limited amount of time.

If a proper is released for your already downloaded hevc version, it will download that proper. Simple as that.

**Comment by medariox** [comment]
With required words Medusa will only download a result if HEVC or MeGusta are found in the title, otherwise the result will be discarded.

**Comment by HPMSGEN8** [comment]
@medariox If i select SD & 720P and have required words as HEVC, MeGusta and HEVC is not found i take it that it should look for SDTV or will it Ignore it 

If it Ignores it do i just add HDTV as well ?

Thanks again
