### ISSUE TITLE
Bug: Re-scanning files with scene numbering enabled on the show results in incorrectly identified episodes. 

### ISSUE THREAD

**Issue by heymoe** [pymedusa/Medusa#3772]
**Branch/Commit:** develop / e881e37de844f9b5ff221fb40ea71a40cee624cf
**OS:** Linux SVR 4.14.13-1-ARCH #1 SMP PREEMPT Wed Jan 10 11:14:50 UTC 2018 x86_64 GNU/Linux

**What you did:**
Renamed some files outside of Medusa in the show's folder and then clicked re-scan files in Medusa.

**What happened:**
It seems that when Medusa found the newly renamed files, it took the season and episode numbers from the filename and then processed it though the xem / scene numbering system which caused it to incorrectly identify the episode. The file was named using the correct TVDB season and episode numbers and was located in the show's directory under the correct season folder.  

For example, if "American Dad - s13e01 - SD.DVD.avi" (named correctly for TVDB) and placed in the show's directory in the "Season 13" folder, Medusa when re-scanning the show would identify this episode as being s14e01 because in XEM / scene numbering  s13e01 = s14e01 TVDB but the files in the show's directory are already in TVDB format.

Of course "Scene numbering" has to be enabled on the show in Medusa too. 

**What you expected:**
Re-scanning for new / renamed files in the show's directory should not have the XEM / scene numbering to indexer (TVDB) conversion process done on them since it should be assumed that files in the show's directory have already been converted.

It took me several tries to get American Dad fixed which evolved some combo of removing the whole show, disabling scene numbering, full refresh and re-scanning of files before Medusa re-added all the episodes correctly again at which point I was able to turn scene numbering back on and not have Medusa mess things up on re-scan since there are now "new" files in the show's directory for it to process.

**Comment by p0psicles** [comment]
Tnx for the bugreport. Very nice detailed report.
Your right, we need to re-evaluate this. Setting a show to scene (numbered) changes the way it parses the releases. As it expects to get scene named/numbered releases.

**Comment by heymoe** [comment]
Just as an update. It looks like that even though I was able to get Medusa to re-add the show correctly by not having scene numbering enabled on import and then enabling it afterwards. Eventually Medusa will perform a scheduled show update at which point it will apply the scene number translation to all the existing episodes and mis-identify all the existing episodes that were initially identified correctly when the show was imported.

So basically enabling scene numbering is a catch 22. If you don't enable it then Medusa won't correctly download new / missing episodes and if you do enable it Medusa will eventually mis-identify all the existing episodes to the point that it will likely not download anything new or download and replace correct episodes because after the episodes are mis-identified, Medus might think you're missing an episode that you really do have.

As a side note. SickRage had more or less this exact same issue that I reported back in Jan of 2016 and then forgotten so I re-posted the issue in Jan of 2017 and it got fixed shortly after that. Maybe you can look at the code changes they made and apply something similar to Medusa.

https://github.com/SickRage/old-sickrage-issues/issues/673

**Comment by medariox** [comment]
Why don't you simply name the existing episodes as they are numbered on XEM? There is a reason why XEM is used in these cases: you wouldn't be able to download the episodes at all if they were searched with TVDB numbering. Medusa is a download manager and thus has to rely on information about how the episodes are released and not how they are numbered on TVDB, TVMaze, etc.

**Comment by heymoe** [comment]
I know what XEM is and why it needs to be used. I personally don't see Medusa and the like as just a download manager. It does post processing, maintains a unified file naming schema, meta data generation (.nfo) as well as all of the other poster, banners, and other images, etc.. etc.. If it was just a download manager why do all of that other stuff?

Sure some people might just have Medusa trigger a download and then use something else (not Medusa) for post processing but that is not how everyone does it. 

Renaming all the episodes to support the XEM / scene numbering would be fine IF Medusa managed the episodes in scene numbering if enabled on a show, as in it converts TVDB/TVMaze to scene numbering in the Medusa web interface but it doesn't. It uses TVDB / TVMaze as the definitive episode ordering which typically is also the official ordering as in how the rest of the would knows them by which in my mind is the preferred ordering.

Either way you have to do a translation and the issue here is that once the translation is done it should NOT to be applied again to the already translated episodes.

**Comment by medariox** [comment]
What I mean is that you shouldn't be manually changing the episodes in the show folder at all. Name them like they are released and manual post-process them (that's the whole point of manual post-processing). Otherwise, you'll need to have scene numbering enabled and name the episodes like they are named on the indexer. Either way works perfectly fine for me with the same show. What you definitely shouldn't be doing is switching between scene and non-scene numbering, that's probably what's messing it up in the first place.

**Comment by heymoe** [comment]
I understand what you are saying and I'm well aware how the process works. In a perfect world where there is no possible reason / need to manually update / rename files in the shows directory then fine BUT we don't live in a perfect world and obviously at some point with this type of app, this functionally was added for a reason otherwise why even have a "re-scan files" option then?

You may not see a need to being able to make changes in the show's directory but that does not mean everyone does and a function to support this behavior has been provided. 

Bug wise, you have this function (re-scan files) that when used on a show that does not have scene numbering enabled has no issues looking for new / renamed files and updates the show without any problem BUT this same function if used on a show with scene numbering enabled will completely blow up the episodes for a show when a change is detected. Same function but different results. That's not to say a function can't have different results as long as the results are valid / correct. In this case though, one of the results is completely wrong / broken.

The fix as I see it is A) don't run the files that already exist in the show's directory though the XEM translation process  if scene numbering is enabled. or B) if scene numbering is enabled, disable re-scan file be it manually or otherwise of the show's directory to keep Medusa for blowing the show up there are any changes in the show's directory are detected for any reason.

SickRage saw this as a bug (see link I provide earlier) and they actually fixed it within a few days after I re-submitted the bug report and there were other users who chimed in claiming they were having the same problem. The code changes they made were not that drastic from what I saw over there so I would assume they would be very similar for Medusa (I could be wrong).

Also as I noted before, I imported the show with scene numbering disable so that it doesn't apply the translation to the existing files. Once the import is done, I turn scene numbering on. I'm not just flip flopping it willy nilly. Sure how I do things may not be how you would do them but that does not change the fact that the outcome of the expected functionally of a feature provide is broken.

**Comment by medariox** [comment]
> Bug wise, you have this function (re-scan files) that when used on a show that does not have scene numbering enabled has no issues looking for new / renamed files and updates the show without any problem BUT this same function if used on a show with scene numbering enabled will completely blow up the episodes for a show when a change is detected. Same function but different results. That's not to say a function can't have different results as long as the results are valid / correct. In this case though, one of the results is completely wrong / broken.

Like I said, I have no problem with scene numbering enabled and using TVDB naming for the exact same show. I name the episodes how they appear in the show overview and that's how they show up for me after a rescan. Can you please be detailed on how to reproduce your issue?

> SickRage saw this as a bug (see link I provide earlier) and they actually fixed it within a few days after I re-submitted the bug report and there were other users who chimed in claiming they were having the same problem. The code changes they made were not that drastic from what I saw over there so I would assume they would be very similar for Medusa (I could be wrong).

You mean someone (a random contributer) casually saw your issue after over a year and was kind enough to push a dirty fix. Yeah, that's not how we want to do things around here.

**Comment by heymoe** [comment]
I removed American Dad from Medusa today due to my files not getting matched to the correct episodes again (my post from 8 hours ago: https://github.com/pymedusa/Medusa/issues/3772#issuecomment-368020227)

The reason for that update was due to me finally getting American Dad added back in correctly 9 days ago (Feb 14th)  when I opened this bug and just letting Medusa run. I did not manually click the re-scan files button between then and now and when I looked at American Dad yesterday I noticed all my episodes were screwed up again. The only possible change I can think of was that the newest episode (s15e02 TVDB) was copied into the Show's directory from a different processes between the Feb 14th and now.

If my Medusa was working as you described as in you're not seeing the issues I'm seeing then I wouldn't have even opened this bug issue. Since SickRage had this issue and now that I've migrated to Medusa and I'm seeing similar behavior and that Medusa and SickRage share a similar code base (fork) if I'm not mistaken, I figured Medusa didn't get the fix thus reporting this bug.
 
So I'm going to repeat this process and document the steps and results as I go along. 

Here are the steps I've done so far.

All of the files in the show's directory are already named using TVDB's numbering and are in "Season XX" sub-folders

1) Shows -> Add Shows -> Add Existing Shows
2) Select the American Dad folder. Click Submit
3) Selected American Dad from the search results (TVDBv2), click Next
4) Click Next on page 2 (no changes)
5) Make sure "scene numbering" is not checked on page 3 and then clicked Add Show
6) After Medusa imported the show, everything looks good at this point.

Even though I didn't enable scene-numbering during the import process on page 3, it looks like Medusa knows it needs to be enabled so it was auto enabled post-import. So I didn't manually enable it.

At this point I'm not going to click on anything like re-scan files and just let Medusa run it's normal processes and scheduled tasks and I'll pull up the page every few days to see if the episodes are still assigned correctly.

I'll keep track of any changes going forward which the only thing I can think of happening is that the next new episode might get added to the show directory by a different process.

Now we wait....

**Comment by heymoe** [comment]
Iit happened again. Everything was looking fine 4 days ago and looked fine the last time I checked it sometime yesterday.

I didn't manually click on "re-scan files" or "force full update". All I did was pull up the show's page to make sure the episodes were associated with the correct files.

The only change was I named correctly (TVDB) the file for last Monday's episode and confirmed today while writing this update that it was named exactly as Medusa would have named it by clicking on "preview rename" and placed into the shows directory. That's it, I didn't click on anything in the Medusa interface. Just put the file into the folder.

![amdad](https://user-images.githubusercontent.com/1672877/36753167-63a3a2aa-1bd3-11e8-996d-df156fd8f8c5.jpg)

As you can see from the screenshot, a bunch of Season 14 (TVDB) files are now identified in Medusa as being Season 15 (TVDB) episodes. It's the same for all the other seasons too, files being associated with the wrong season and episode number.

So I seem to have done what you described: 

>  I name the episodes how they appear in the show overview and that's how they show up for me after a rescan.

Except I didn't click rescan myself. Medusa did it on its own and blew up the episode associations for all the files that were already associated correctly.

**Comment by medariox** [comment]
Thanks for the updated feedback @heymoe!

Looks like the real issue here is the automated periodic scan messing things up, probably wrongfully using the XEM numbering while it shouldn't. Do you think that what I'm describing is correct? If that's the case we can start narrowing it down to that specific code part.

**Comment by heymoe** [comment]
What you describe seems to be correct for the mass update of all the existing episodes. 

I want to say when I was playing around and renamed an existing episode (just one) say s13e01 by changing the title part of the filename. Example renamed: "`American Dad - s13e01 - Roots - SD.DVD.avi`" to "`American Dad - s13e01 - Roots (test) - SD.DVD.avi`" and then clicking on "re-scan files" that Medusa would associate the s13e01 file to the s14e01 episode and mark the s13e01 episode as ignored / missing. So still applying the XEM translation but only on that single file and not every file after the manual rescan.

I can re-run that test if you like too. Basically reset using the same 6 steps I describe 4 days ago and then do what I described above.

**Comment by medariox** [comment]
If you change one single episode name and trigger a re-scan, can you reproduce this issue? Because I tried and it works as expected here. Let's say I have `S15E03` - that's how it is called on my HDD and that's how it shows up in Medusa. I change the name, re-scan and it just changes the name of the episode in Medusa, the numbering doesn't change at all. If you can reproduce the issue, please also post the corresponding debug log.

**Comment by labrys** [comment]
@medariox this was in fact the same bug as SR and I had the same "discussion" with a certain dev then.  It did affect single episodes.  I dropped the issue since I had few scene numbered episodes and was using an external tool for pp

**Comment by medariox** [comment]
@labrys Interesting. I'd really like to look into this issue, but I'm currently unable to reproduce it.

**Comment by heymoe** [comment]
I re-did the same 6 steps to get the show re-added to Medusa. I rename just the video file for s13e01 as noted in my last post and deleted the other files (.nfo, poster, thumb jpgs, etc..) then then clicked on "Re-scan Files". I let it run and then refreshed the show's page. I was only expecting that single episode to be messed up but this time around ended up with the same outcome as what I posted 4 days ago. All the episodes were associated incorrectly instead of just the one I renamed being messed up.

**Comment by labrys** [comment]
@heymoe that's what I would have expected because that's what I've seen in the past.  I realize my previous post was unclear when I said it happened even with single episodes.

**Comment by udochrist** [comment]
Same issue happened today for Sense8. The show was marked scene numbered and i placed a "missing" file s02e01 into the season2 folder. Medusa did not add it to s02e01 but to s02e02 instead.
it's my understanding the the files (after postprocessing) are stored using the indexers (tvdb, tvmaze,..) episode numbering scheme despite the search possibly uses scene. If this is true then the "Rescan Files" must use the indexers numbering to pickup files from the show folder.
When rescanning the download folder the configured search numbering must be used.

to use the search numbering in the tv show folder is broken imho.

Can this be fixed? possibly this is also why madusa has completely messed up my American Dad show folder....

**Comment by heymoe** [comment]
Welcome to the party. It doesn't look like Sense8 has a XEM entry so you shouldn't have to enable "scene numbering" on it. American Dad on the other hand, this issue is indeed most likely causing the issue.

I've been hoping that they would fix this issue but it doesn't look like there has been any movement on it since March. I guess it's still on their todo list to fix since this issue is still open and has been tagged as a bug and confirmed so we just have to wait.

**Comment by udochrist** [comment]
yeah. funny thing is i didn't turn on Scene myself. Maybe some nightly show-refresh or else.
I could only disable it by completely removing the show from Medusa and then re-importing it using postprocessing after adding it again w/o Scene. I think the nfo file is/was the culprit there….
