### ISSUE TITLE
Medusa is not updating show summaries. Months behind.

### ISSUE THREAD

**Issue by d0ct0rd00m** [pymedusa/Medusa#3776]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Master**
**Windows 7 Ultimate x64:**
**I haven't done anything. Just let Medusa run naturally.**
**Medusa does not update show summaries correctly. I have shows months behind in "latest" episode aired. Because of this, I am not downloading shows shortly after they air.**
**I expect Medusa to update shows correctly. To have it correctly display the last episode aired and download.**
**Logs:**
```
https://pastebin.com/DSLckRRG
```

**Comment by medariox** [comment]
Your installation seems to be pretty broken. I'd suggest you start fresh with a new install.

**Comment by medariox** [comment]
Before doing that you could try deleting your `cache.db` and restart, see if that helps. Post the logs once you've done that.

**Comment by d0ct0rd00m** [comment]
Alright i will try. If i need to reinstall it will i be able to save the database or will i have to re-enter all the shows i want to download again?

**Comment by d0ct0rd00m** [comment]
Here is the pastebin
https://pastebin.com/bJwtZz93

seems the same even after delete of cache.

so what do i need to do? delete everything pertaining to medusa and install fresh?

**Comment by medariox** [comment]
Your database seems to have some major issues. You can try to keep your `config.ini` and delete all your databases `main.db`, `cache.db` and `failed.db`. You will have to re-add all your series, but you will keep your settings at least.

**Comment by d0ct0rd00m** [comment]
Thank you i will try that now.

**Comment by d0ct0rd00m** [comment]
I uninstalled and deleted everything. I reinstalled and added back all the shows and its working for now. All shows are updated correctly.

Thank you :D
