### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Stargate Command

### ISSUE THREAD

**Issue by laurentl1** [pymedusa/Medusa#3777]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.14.12-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/ff60aa4bd140b305baa687d67fb2afeb
### ERROR
<pre>
2018-02-15 10:14:39 ERROR    Thread-22 :: [ccbc0ce] Missing time zone for network: Stargate Command
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added: https://github.com/pymedusa/medusa.github.io/commit/c1d9b43239b09226787c613b77de984861f8ec80

**Comment by udochrist** [comment]
### INFO
**Python Version**: `2.7.14 (default, Jan 15 2018, 19:15:25) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/9c094ec590ef9225f7730ac98740bcd5
### ERROR
<pre>
2018-02-15 05:28:53 ERROR    Thread-16 :: [ccbc0ce] Missing time zone for network: Stargate Command
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
