### ISSUE TITLE
Development: Help needed to understand dev setup

### ISSUE THREAD

**Issue by abeloin** [pymedusa/Medusa#3778]
**Branch/Commit:** Develop/0e2338b8b49cd018671b7e95823c749070cf3b7e
**OS:** Linux
**What you did:** Run my own fork to fix a bug
**What happened:** Medusa rewrote the git remotes when debugging it
**What you expected:** Leave the git remote alone
**Logs:** N/A

Hello,

Could you help me understand how you guys setup Medusa for development? As you seem to have the weirdest triangular workflow I have ever seen.

In the past, I would have done:

1. Fork the repo
2. Clone the forked repo on my computer
3. Modified the following value in Config.ini
   - developer = 1
   - git_remote_url = https://github.com/abeloin/Medusa
4. Start working

But now this result in the origin remote to be overwritten to 'https://github.com/pymedusa/Medusa' !!!

So I looked at the code to see what I'm missing and I found this:

https://github.com/pymedusa/Medusa/blob/develop/medusa/__main__.py#L474
```
repo_url_re = re.compile(
    r'(?P<prefix>(?:git@github\.com:)|(?:https://github\.com/))(?P<org>\w+)/(?P<repo>\w+)\.git')
m = repo_url_re.match(app.GIT_REMOTE_URL)
if m:
    groups = m.groupdict()
    if groups['org'].lower() != app.GIT_ORG.lower() or groups['repo'].lower() != app.GIT_REPO.lower():
        app.GIT_REMOTE_URL = groups['prefix'] + app.GIT_ORG + '/' + app.GIT_REPO + '.git'
else:
    app.GIT_REMOTE_URL = app.APPLICATION_URL
```

At first, I thought that I need to change app.git_org but it is not available in Config.ini.

For now, I've commented out that code but isn't there a better way?

Thank you in advance for your help.

P.S. I tried to ask the question in the IRC channel first but it is eerily quiet over there. ;)

**Comment by p0psicles** [comment]
The way everyone develops is by getting contributor access to this repo. You will then get access to create `feature/` branches in pymedusa.

But your right this piece of code should be changed or maybe even just removed.

**Comment by p0psicles** [comment]
You've been added `contributor` now. You should get a message. If you accept the invitation you should be able to create branches in the github UI. Or push new branches from your local checkout.

**Comment by abeloin** [comment]
OK, so you're not using the triangular workflow. Good to know

I'll submit a PR that add an 'if not app.developer' around that code so that the check for regular user still apply.

Thanks for the info
