### ISSUE TITLE
Add Recomended Shows From IMDB`s

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#3784]
Branch: develop
Commit: 0e2338b8b49cd018671b7e95823c749070cf3b7eVersion: v0.1.22
Database: 44.9
Python Version: | 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
OS: | Linux-4.13.0-32-generic-x86_64-with-LinuxMint-18.3-sylvia
what you did: Tried Adding shows
What Happen:
![screenshot from 2018-02-18 09-04-58](https://user-images.githubusercontent.com/7034303/36352704-eeb62016-148a-11e8-8c17-fee18dee6a40.png)

**Comment by p0psicles** [comment]
Yeah fix already in the works

**Comment by ripper1967** [comment]
Ok will close it for now then.
