### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Discovery (US)

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#3795]
### INFO
**Python Version**: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/edd8f63457e4bd464d51bf991b738187
### ERROR
<pre>
2018-02-22 13:23:50 ERROR    Thread-633 :: [ccbc0ce] Missing time zone for network: Discovery (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
Added
