### ISSUE TITLE
[APP SUBMITTED]: TypeError: displayShow() got an unexpected keyword argument 'show'

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#3798]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.14.13-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
**Link to Log**: https://gist.github.com/bc6107cfa8d082b212a533a9b8ecb530
### ERROR
<pre>
2018-02-23 02:27:26 ERROR    Thread-16 :: [1a8dc66] Exception generated: displayShow() got an unexpected keyword argument 'show'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 280, in async_call
    result = function(**kwargs)
TypeError: displayShow() got an unexpected keyword argument 'show'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Just upgraded or maybe used an old bookmark?
