### ISSUE TITLE
simpleanidb cache directory wanting to be created in /root/.cache

### ISSUE THREAD

**Issue by Thraxis** [pymedusa/Medusa#3802]
I maintain a docker running the development branch of Medusa, last night I updated the docker and it would not start as it kept attempting to create a directory in the /root/.cache folder and did not have permissions.

I shelled into my docker image and changed permissions to allow it to discover it was creation a folder called simpleanidb and in the folder it downloaded the anime_list.xml file.

It appears to be an issue with the call occurring before app.CACHE_DIR has been set to a value from the config.ini

**Comment by p0psicles** [comment]
Tnx I'll try to fix and include it in the release tomorrow.
