### ISSUE TITLE
Purpose of connection to catbread.info

### ISSUE THREAD

**Issue by dkasak** [pymedusa/Medusa#3814]
I just noticed medusa making an outbound connection to 172.245.57.197:80 (which reverse resolves to catbread.info). I didn't find any references to this IP or this domain in a cursory search of the source code. What is the purpose of this connection and where is it established?

**Comment by p0psicles** [comment]
I don't know.
When is it opening the connection? Can you match it with some logs? Like during a search? a show update? Adding of new show? Getting fanart? Sending notifications? Can be allot?

**Comment by duramato** [comment]
That's thexem.de, used for scene numbering mappings.

**Comment by medariox** [comment]
http://www.viewdns.info/reverseip/?host=172.245.57.197&t=1

**Comment by dkasak** [comment]
Right, thanks!
