### ISSUE TITLE
Did the API changed in the past? - android apps do not show the medusa show list

### ISSUE THREAD

**Issue by Denqbar** [pymedusa/Medusa#3820]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:Master**
**OS:Linux-Debian 4.9.0.0bpo -> Docker Container (https://hub.docker.com/r/binhex/arch-medusa/)**
**What you did:nothing, but used the android app "nzb360" and "nzbmanager"**
**What happened: The API test of the apps is successful, but the show list is empty or incomplete**
**What you expected:the show list ist identical to the list in the webinterface**

Hey Guys,
as discribed before, I noticed that the android apps I use, do not show the show list of medusa. So I contacted the Dev of nzb360 and he promised to me, that he didi not change the code for a long time. So maybe you can tell me if the api or something related to it did change in te past month or so.

thanks in advance

Denqbar

**Comment by p0psicles** [comment]
We did make changes. Also added a new apiv2. So while adding allot of features like multi indexer support, we tried to freeze the api v1 at least. Your having tvdb shows in your lib?

Also make sure your running latest version. We did some fixes yesterday

**Comment by p0psicles** [comment]
I'll have to check the app

**Comment by p0psicles** [comment]
Found the issue. Installed the app.
have it fixed this weekend.
