### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: GMM One

### ISSUE THREAD

**Issue by Tuxie** [pymedusa/Medusa#3824]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/9ab64a6e1360403a426f26c9593fbf84
### ERROR
<pre>
2018-03-02 21:47:51 ERROR    Thread-16 :: [d6eb72d] Missing time zone for network: GMM One
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added with: https://github.com/pymedusa/medusa.github.io/commit/7402fd80e60832599ad4f6db96ccebb2718a58c6
