### ISSUE TITLE
How search a new series in code with api

### ISSUE THREAD

**Issue by nico6308** [pymedusa/Medusa#3834]
Hi, i developp iOS app for remote my medusa server, in the api v2 I can't search series by name but just by id. So how I can search series by name and get the series id for add a new show for example ? I see the api documentation on: [https://medusaapi.docs.apiary.io/#authentication/undefined](https://medusaapi.docs.apiary.io/#authentication/undefined)

**Comment by p0psicles** [comment]
apiv2 hasn't been finished yet. It's still in alpha.
This resource hasn't been implemented yet.

We'd suggest not to start building an app based on the current specs.
Or at least, we might do small changes to the current routes. And add to them coming months.

**Comment by nico6308** [comment]
Ok, thank i understand so how used the api v1 without api key or rather how get api key in code with id ?

**Comment by p0psicles** [comment]
Sorry I don't understand what your question is.

**Comment by nico6308** [comment]
So I can't use API V2 for search series, I want use the API v1 for that. I need the API key for use API like this: /api/v1/APIKEY/?cmd=sb.searchtvdb for example. But I want get my API with my credential ID it is possible ?

**Comment by sharkykh** [comment]
"Credential ID" - do you mean with a user and password?
Anyway I don't think APIv1 has a way to get the API key.
Currently you need to enter the API key in manually.

**Comment by p0psicles** [comment]
Its also used in our kodi addon. There we go from username -> jwt -> api key. Its in python though

**Comment by p0psicles** [comment]
The addon is using /authenticate. Which is the apiv2 variant of /token. So you have some options

**Comment by sharkykh** [comment]
Closed due to lack of response.
