### ISSUE TITLE
Problem with new CardCaptor Sakura series

### ISSUE THREAD

**Issue by saitoh183** [pymedusa/Medusa#3835]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

 Medusa Info: 	Branch: develop
Commit: f74f5afb4d31f2139d19f577ed5d5e5b27420033
Version: v0.1.22
Database: 44.9
Python Version:	2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
SSL Version:	OpenSSL 1.0.1t 3 May 2016
OS:	Linux-4.14.11-feral-x86_64-with-debian-8.10
Locale:	en_GB.UTF-8
```
Parsed [Erai-raws].Cardcaptor.Sakura.-.Clear.Card-hen.-.08.[1080p][Multiple.Subtitle].mkv into release_group: Erai-raws, title: Cardcaptor Sakura, alias: Cardcaptor Sakura - Clear Card-hen, alternative_title: Clear Card-hen, episode: [8], absolute_episode: [8], screen_size: 1080p, container: mkv, mimetype: video/x-matroska, type: episode, parsing_time: 0.0425989627838, total_time: 0.145897865295, quality: 1080p HDTV, season: 1
```
I think it is being parsed wrong because i get no results for season 4 eps 8 which is **[Erai-raws].Cardcaptor.Sakura.-.Clear.Card-hen.-.08.[1080p][Multiple.Subtitle].mkv** I tested the same episode in sonarr and it gets recognized fine

**Comment by abeloin** [comment]
Hello,
Can you try to upgrade to the latest commit and try it again?

**Comment by saitoh183** [comment]
2018-03-06 13:45:25 INFO     Thread-33 :: [f74f5af] No update needed
2018-03-06 13:45:23 INFO     Thread-33 :: [f74f5af] Checking for updates using GIT

**Comment by saitoh183** [comment]
Medusa Info: 	Branch: develop
Commit: 23a27c25447aaf2d0b1e53acfa17dfcac5983883
Version: v0.1.22
Database: 44.9
Python Version:	2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
SSL Version:	OpenSSL 1.0.1t 3 May 2016
OS:	Linux-4.14.11-feral-x86_64-with-debian-8.10
Locale:	en_GB.UTF-8

Seems to be working now :)

Thanks
