### ISSUE TITLE
Spartacus suddenly showing season 4

### ISSUE THREAD

**Issue by h3llrais3r** [pymedusa/Medusa#3841]
Suddenly the series Spartacus is having a Season 4 while it has been ended quite some time ago.
I see that the episodes are the same as the episodes of the specials...
Any idea what's happening?

**Branch/Commit:** d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**OS:** Windows
**What you did:**
**What happened:**
**What you expected:**
**Logs:**

![image](https://user-images.githubusercontent.com/1945295/37171282-a2f47196-230d-11e8-882d-c6c0c224d435.png)

**Comment by abeloin** [comment]
Hello,
I found a request to delete season 4 on the theTVDB forums:
https://forums.thetvdb.com/viewtopic.php?f=18&t=44981&p=126445&hilit=spartacus#p126445

Could you try a "Force Full Update"?

**Comment by h3llrais3r** [comment]
@abeloin Thanks for the tip, that did the trick.
I did check tvdb before opening this issue, and I didn't see the season 4, so I didn't look further on tvdb itself.
