### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by TTLucian** [pymedusa/Medusa#3844]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/5219e0d234f722829d6fa61c59542322
### ERROR
<pre>
2018-03-10 00:22:08 ERROR    POSTPROCESSOR :: [d6eb72d] OSError: 
Traceback (most recent call last):
  File "C:\Data\Medusa\Medusa\medusa\helpers\__init__.py", line 285, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "C:\Data\Medusa\Medusa\lib\shutil_custom\__init__.py", line 41, in copyfile_custom
    fin = os.open(src, READ_FLAGS)
OSError: [Errno 13] Permission denied
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by abeloin** [comment]
From the log, I would guess that the source file was still being transfered to the complete folder or that another process was locking the file.

`Unable to determine needed filespace as the source file is locked for access`
`Error: WindowsError(17, 'The system cannot move the file to a different disk drive.'). Copying instead`

**Comment by sharkykh** [comment]
No response.
