### ISSUE TITLE
episodes stay in snatched, where to start?

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#3848]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Medusa Info: | Branch: masterCommit: d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebeVersion: v0.2.1Database: 44.9
-- | --
Python Version: | 2.7.13 (default, Dec 18 2016, 21:23:50) [GCC 4.6.4]
SSL Version: | OpenSSL 1.0.2j 26 Sep 2016
OS: | Linux-3.2.40-armv7l-with-glibc2.4
Locale: | en_US.UTF-8

**What you did: downloaded some episodes
**What happened: they don't go into download, but stay in snatched
**What you expected: move to series folder
![image](https://user-images.githubusercontent.com/15545810/37242399-0cbe031a-2469-11e8-84c3-9f118c3e4f33.png)

![image](https://user-images.githubusercontent.com/15545810/37242404-2bc076e4-2469-11e8-8a16-ef278536e167.png)

permission issue? I can't think of anything else...

**Comment by abeloin** [comment]
If you think it's a permission issue, make sure the user running Medusa has the proper right to see the files.

Or if you can provide(via dir -l or getfacl(if you use acl)):
- the episode folder permissions(e.g.: 700 user:group)
- one of the file permissions inside that episode folder
- the user running Medusa

**Comment by ward0** [comment]
was indeed problem with security, since the new syno update i had to add sc-download to make it work again. I wonder why Medusa is not trowing errors?
