### ISSUE TITLE
Yggtorrent Date Translation

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#3865]
WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Yggtorrent] :: [d6eb72d] Could not translate publishing date with value: à l'instant

When a torrent is released, instead of having a real published date, they'll put "à l'instant" which means "just now" in french. Medusa should replace that with the current date :)

Thanks for your work,

**Comment by medariox** [comment]
Here you go: https://github.com/pymedusa/Medusa/pull/3868

**Comment by IDerr** [comment]
Thanks @medariox
