### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: National Geographic WILD

### ISSUE THREAD

**Issue by ztaale** [pymedusa/Medusa#3879]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-5-amd64-x86_64-with-debian-9.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/28486f738918aec5bf0828dc5cfe35f4
### ERROR
<pre>
2018-03-19 15:21:27 ERROR    Thread-19 :: [d6eb72d] Missing time zone for network: National Geographic WILD
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
Added
