### ISSUE TITLE
Add to whitelist no longer working on edit show

### ISSUE THREAD

**Issue by h3llrais3r** [pymedusa/Medusa#3887]
![image](https://user-images.githubusercontent.com/1945295/37730392-e1f353a8-2d3f-11e8-8449-971239d4fcdf.png)

**Branch/Commit:** develop: 1d62c9064c260d003cc825f069b980c85c5837ce
**OS:** Windows
**What you did:** Select horriblesubs as group and click on add to whitelist button
**What happened:** Nothing
**What you expected:** HorribleSubs added in whitelist

EDIT: on master it still works

**Comment by OmgImAlexis** [comment]
@h3llrais3r which "latest develop" is this? This is why we ask for a commit hash.

**Comment by h3llrais3r** [comment]
@OmgImAlexis updated issue with commit hash.

**Comment by OmgImAlexis** [comment]
Could you check if the issue is still there in the newest dev or https://github.com/pymedusa/Medusa/pull/3890

**Comment by medariox** [comment]
It's also happening when adding normal scene exceptions for me (newest develop).

**Comment by OmgImAlexis** [comment]
I'll look into this, I have a feeling it may be a HTML issue again.

**Comment by h3llrais3r** [comment]
Confirmed it's still an issue on latest develop (a928239b057d2c67340cfdbf94a9cee618b8ee71)

**Comment by h3llrais3r** [comment]
Found the issue. Need to wrap the jquery buttons with a$(document).ready():

```javascript
$(document).ready(() => {
    $('#removeW').on('click', () => {
        !$('#white option:selected').remove().appendTo('#pool');  // eslint-disable-line no-unused-expressions
    });

    $('#addW').on('click', () => {
        !$('#pool option:selected').remove().appendTo('#white');  // eslint-disable-line no-unused-expressions
    });

    $('#addB').on('click', () => {
        !$('#pool option:selected').remove().appendTo('#black');  // eslint-disable-line no-unused-expressions
    });

    $('#removeP').on('click', () => {
        !$('#pool option:selected').remove();  // eslint-disable-line no-unused-expressions
    });

    $('#removeB').on('click', () => {
        !$('#black option:selected').remove().appendTo('#pool');  // eslint-disable-line no-unused-expressions
    });

    $('#addToWhite').on('click', () => {
        const group = $('#addToPoolText').val();
        if (group !== '') {
            const option = $('<option>');
            option.prop('value', group);
            option.html(group);
            option.appendTo('#white');
            $('#addToPoolText').val('');
        }
    });

    $('#addToBlack').on('click', () => {
        const group = $('#addToPoolText').val();
        if (group !== '') {
            const option = $('<option>');
            option.prop('value', group);
            option.html(group);
            option.appendTo('#black');
            $('#addToPoolText').val('');
        }
    });
});
```

PS: I tried to setup the development environment for the themes, but I couldn't get it working...
yarn always seems to fail on windows when running it...

**Comment by p0psicles** [comment]
You can also just copy the file to, dark and light as well

**Comment by h3llrais3r** [comment]
That's it? Adding in themes-default and copying it to dark and light folder also?

**Comment by p0psicles** [comment]
Yeah we don't do any compiling of js for now.
But it should be able to install the deps using yarn.
What's the error your getting with that?

**Comment by h3llrais3r** [comment]
Will let you know this evening. 😉

**Comment by h3llrais3r** [comment]
Error running yarn:

![image](https://user-images.githubusercontent.com/1945295/37843367-fadf008e-2ec4-11e8-8c69-0061a548d215.png)

**Comment by p0psicles** [comment]
What's your node version?

**Comment by p0psicles** [comment]
If you have at least node 8, I recommend deleting your node_modules and try to install again.

**Comment by p0psicles** [comment]
Ooh I've also send you an invite, used your github email.

**Comment by h3llrais3r** [comment]
@p0psicles I have node 8.9.3 and already tried to reinstall 2 times...

**Comment by h3llrais3r** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/3902
