### ISSUE TITLE
Problems with Danish tv shop that contains ø

### ISSUE THREAD

**Issue by jbaun** [pymedusa/Medusa#3891]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
Branch: master
Commit: d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
Version: v0.2.1

**OS:**
Linux-2.6.32.12-armv5tel-with-glibc2.4
On Synology NAS

**What you did:**
When trying to post process the show "De Unge Mødre" (https://www.thetvdb.com/?tab=series&id=104951&lid=10) it fails

The name of the file is: De Unge Mødre S25E07.mkv

Seaching for the show is also not working with the use of Scene Exception de unge moedre, The name of the file is normally de.unge.moedre.mkv

It is working fine in SickRage, and of cause the show is added to Medusa.

**What happened:**
It fails.
**What you expected:**
To work.

**Logs:**
```
Processing path: /volume1/downloads/complete/tv
Processing folder: /volume1/downloads/complete/tv
Post-processing files: [u'De Unge M\xf8dre S25E07.mkv']
Post-processing video files: [u'De Unge M\xf8dre S25E07.mkv']
Processing failed for /volume1/downloads/complete/tv/De Unge Mødre S25E07.mkv: This show isn't in your list, you need to add it before post-processing an episode
Problem(s) during processing, failed for the following files/folders: 
/volume1/downloads/complete/tv/De Unge Mødre S25E07.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
```

**Comment by medariox** [comment]
The problem here is the guessit parsing. You should add `Unge Mødre` as scene exception, that should fix the post-processing and likely also the search.

**Comment by jbaun** [comment]
nice. that helped. thank you weary much.

**Comment by medariox** [comment]
You're welcome. I'm going to close this issue as we have a few other similar ones open, also related to guessit.
