### ISSUE TITLE
`git_token` is encrypted multiple times and becomes unusable

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#3895]
**Branch/Commit:** 527c2326aefb788a5359de0c06843dd8f68d4fcd
**OS:** Windows 7

`git_token` config entry gets re-encrypted and loses access to the raw, unencrypted value.

**Steps to reproduce:**
1. Enable the *Encrypt passwords* option in General -> Advanced
2. Put in a fresh Github Personal Access Token and save the General config.
3. Check `config.ini`, original token is now encrypted once - save that encrypted value
4. Restart Medusa
5. Go to General config and save the config.
6. Check `config.ini`, original token is now encrypted *twice* - notice that the length is a little longer than the first one.
7. **The token is now unusable.** At this point you will start getting the following warning:
    > Invalid Github credentials. Please check your Github credentials in Medusa settings.

Repeat steps 4 to 6. The token just keeps getting re-encrypted and becomes unusable.

![image](https://user-images.githubusercontent.com/10238474/37783649-b0f0bbaa-2dfe-11e8-9338-98574604d90e.png)

**Comment by OmgImAlexis** [comment]
@p0psicles there's a chance this is related to the vue stuff but I doubt it.

**Comment by p0psicles** [comment]
Think it's an old bug

**Comment by sharkykh** [comment]
Maybe it's because of this?
https://github.com/pymedusa/Medusa/blob/a928239b057d2c67340cfdbf94a9cee618b8ee71/medusa/config.py#L677-L679

That would make sense - because `check_setting_str` is called when Medusa is starting, and if it doesn't decrypt the value it would have the encrypted value in `app.GIT_TOKEN`.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/3896 👍
