### ISSUE TITLE
Sorting published date in manual search does not work

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#3917]
Medusa Info: | Branch: master                 Commit: d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe                 Version: v0.2.1                 Database: 44.9
-- | --
Python Version: | 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2k  26 Jan 2017
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

Sorting published date in manual search does not work like expected, it does work with Added date for instance.
![image](https://user-images.githubusercontent.com/4103090/37908333-3b844a3c-3108-11e8-9f87-44cdaaf1d7ed.png)

Example for added date
![image](https://user-images.githubusercontent.com/4103090/37908399-64581434-3108-11e8-8638-20a67c2b84b8.png)

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/3920
