### ISSUE TITLE
Edit Show button on Backlog Overview page does not work

### ISSUE THREAD

**Issue by MonkWho** [pymedusa/Medusa#3928]
**Branch/Commit:**
Branch: master
Commit: d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
Version: v0.2.1

**OS:**
Windows 7

**What you did:**
Click "Edit Show" button on "Backlog Overview" page

**What happened:**
Page loads with message "Unable to find the specified show ID: None"

**What you expected:**
"Edit Show" page to open for that particular show

**Logs:**
Nothing in logs. Incorrect link issue

Checked the link and can see that Edit Show button is redirecting to an incorrect link. Parameter "indexername" is being passed a show number instead of indexer name. Here is what link currently looks like:
http://SERVER_ADDRESS:PORT/manage/editShow?indexername=SHOW_ID&seriesid=SHOW_ID

Should be:
http://SERVER_ADDRESS:PORT/manage/editShow?indexername=tvdb&seriesid=SHOW_ID
or
http://SERVER_ADDRESS:PORT//home/editShow?indexername=tvdb&seriesid=SHOW_ID

Error is in "/templates/manage_backlogOverview.mako" for all themes.

Line 96 needs to change from:
`<a class="btn btn-inline editShow" href="manage/editShow?indexername=${cur_show.series_id}&seriesid=${cur_show.series_id}"><i class="icon-play-circle icon-white"></i> Edit Show</a>`
to
`<a class="btn btn-inline editShow" href="manage/editShow?indexername=${cur_show.indexer_name}&seriesid=${cur_show.series_id}"><i class="icon-play-circle icon-white"></i> Edit Show</a>`

**Comment by MonkWho** [comment]
It is in "/templates/manage_backlogOverview.mako" for all themes.

Line 96 needs to change from:
`                                    <a class="btn btn-inline editShow" href="manage/editShow?indexername=${cur_show.series_id}&seriesid=${cur_show.series_id}"><i class="icon-play-circle icon-white"></i> Edit Show</a>`
to
`                                    <a class="btn btn-inline editShow" href="manage/editShow?indexername=${cur_show.indexer_name}&seriesid=${cur_show.series_id}"><i class="icon-play-circle icon-white"></i> Edit Show</a>`

**Comment by sharkykh** [comment]
Thank you @MonkWho, you are correct.
I will open a PR to fix this.
