### ISSUE TITLE
addic7ed is raising exception TooManyRequests when searching for subtitles.

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#393]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop/f358c8be1995b6c91d0951809318c3ef212b7bcc
OS: debian 7
What you did: Start subtitle finder
What happened: Got an error with trackback
What you expected: no trackeback and preferably no error
Logs:

```
2016-04-15 10:54:23 10:54:23 ERROR::FINDSUBTITLES :: [1f87e70] Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/home/opt/Sickrage-*****/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/opt/Sickrage-*****/lib/subliminal/providers/addic7ed.py", line 265, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/home/opt/Sickrage-*****/lib/subliminal/providers/addic7ed.py", line 230, in query
    raise TooManyRequests()
TooManyRequests
```

Additional info: 
- I am logged in with a user account.
- It is finding subtitles from that provider.

**Comment by p0psicles** [comment]
Will need to be fixed upstream.
@ratoaq2 would you be willing to report this for us?

**Comment by labrys** [comment]
Actually this shouldn't be fixed upstream, they are raising the error for us to catch it so that we can stop querying the provider when it happens.

**Comment by p0psicles** [comment]
If it's possible we should throttle the amount of requests send.

**Comment by fernandog** [comment]
this should be addressed to subliminal @diaol

**Comment by ratoaq2** [comment]
IMO we should throttle our requests to subliminal. If in one iteration we have a queue of 30 episodes with missing subtitles, then we need to take it easy.

**Comment by labrys** [comment]
Agreed, @ratoaq2.  This is not an upstream issue.

**Comment by fernandog** [comment]
Subliminal should handle because user can have a script searching for a lot of subs using CLI/API and same error will happen

**Comment by Diaoul** [comment]
Subliminal cannot throttle requests without knowing the rate limiting rule. As a side effect, subliminal will be really slow with Addic7ed if you want to get subtitles for a large amount of videos. One way to reduce the number of requests to Addic7ed is to implement it another way so it only makes one query per season instead of one query per episode. Like with legendas with a 15 min cache for example.

If request throttling is implemented it will be disable by default in the high level API so it doesn't hurt performance on large searches with multiple providers.

**Comment by fernandog** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/2026/commits/7bb8017db880cc1e4cca07db3bb8a07330eba1ed
