### ISSUE TITLE
[Feature Request] Add private tracker fuzer.me

### ISSUE THREAD

**Issue by myakove** [pymedusa/Medusa#3936]
It would be nice to get https://www.fuzer.me , currently using Jackett and it's not working, Always no results from it.

**Comment by myakove** [comment]
I think sickrage have a fix for Jackett issue.
https://github.com/SickRage/SickRage/commit/dfcf25af4f21fa3d194e272d8cd3c1e487fbf4c8

**Comment by p0psicles** [comment]
Is jacket giving no results. Or Medusa icw jacket? There is a fix for jacket in our develop branch. We need to get develop stable before we can release it.

**Comment by medariox** [comment]
Yeah, there is no need for this fix as we have dedicated Jackett providers coming with the next release.

**Comment by myakove** [comment]
Great news, thanks.

**Comment by medariox** [comment]
This should be now working with Jackett. If you want this implemented as a stand-alone provider, we will need an invite.

**Comment by myakove** [comment]
Thanks, it's working with Jackett, if you need an invite I can send one.
