### ISSUE TITLE
[Feature Request] Post Processing using a temporary folder

### ISSUE THREAD

**Issue by nodupe** [pymedusa/Medusa#3939]
I'd like to have the option of post processing on a temporary folder. Ideally it would be great to point the unrar command to a folder determined, avoiding leftovers on the same folder where the rar files are present.

**Comment by medariox** [comment]
What do you mean by leftovers? Did you try this option?
![img](https://snapr.pw/i/87b0955d7e.png)

**Comment by nodupe** [comment]
Sorry for the late reply. The option you show is great, but not what I am looking for.

I mirror files between Server1 and Server2. Server1 downloads from internet and store files on folder1. Folder1 syncs (over one cloud service) with Folder2 on Server2.
Medusa is installed on Server2.
If I cannot "force" a temp folder where Medusa unpacks the files from Folder2, Server2 starts uploading the unpacked files directly to Folder1 in Server1, trying to keep both folders on sync.

I know it is an edge case, but it makes sense (at least to me) to have an option to set the temp folder, at least under an advanced tab.
