### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Audience

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#3944]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@384ccc6bdcd6a029060c68e35da7010f809122e7
**Link to Log**: https://gist.github.com/bb6c881266868c94fc31a66fbc1a4ce5
### ERROR
<pre>
2018-04-02 11:16:08 ERROR    ThreadPoolExecutor-0_0 :: [384ccc6] Missing time zone for network: Audience
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added
