### ISSUE TITLE
cannot connect with uTorrent client; missing torrent download path in WebUI command to utorrent

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#3963]
Hi,
Using latest uTorrent 3.5.3 (44390 beta) and latest Medisa (just installed, Windows 10 - latest), I am not able to communicate with uT webui/remote. It is working fine with remote,utorrent.com site.

I am getting the following error in uT log (localhost:32457):
[2018-04-05 20:19:03]  HTTP: IP ::1: Bad username/password
[2018-04-05 20:21:16]  HTTP: IP ::1: Bad username/password

Medusa log:
```
2018-04-05 20:21:16 DEBUG    Thread-24 :: [d6eb72d] User-Agent: Medusa/0.1.23 (Windows; 10; d5449161-38ef-11e8-918d-001b213c7449)
2018-04-05 20:21:16 DEBUG    Thread-24 :: [d6eb72d] GET URL: http://localhost:32457/gui/token.html [Status: 401]
2018-04-05 20:21:16 DEBUG    Thread-24 :: [d6eb72d] User-Agent: Medusa/0.1.23 (Windows; 10; d5449161-38ef-11e8-918d-001b213c7449)
2018-04-05 20:21:16 DEBUG    Thread-24 :: [d6eb72d] GET URL: http://localhost:32457/gui/ [Status: 400]
```
Can you please check if this is still working for you?

Thanks

Rafi

**Comment by sharkykh** [comment]
I glanced at the release notes for the latest uTorrent, and I think they changed the authentication system for the WebUI in 3.5.3. I'm reluctant to upgrade uTorrent because of its adware.

Could you upload the `webui.zip` file from `%APPDATA%\uTorrent` so that I could have a look? (It has no personal information - just some templates for the WebUI)

**Comment by rafi-d** [comment]
No problem (this one was created after the last beta), but the dates are all old, so   I don't think there is anything changed. 
I am not a user of utorrent "remote" , so maybe I am doing something wrong here either in uTorrent or Medusa.  The only was I checked was using remote.utorrent.com site.

Anyway, you are welcome to use my settings , so to avoid the ads (just rename it to settings.dat and put in the same folder as the exe to operate in "standalone" mode: http://goo.gl/V2eHo ).
[webui.zip](https://github.com/pymedusa/Medusa/files/1883080/webui.zip)

**Comment by sharkykh** [comment]
Hmm. Okay.
1. Your settings seem fine to me.
2. The image you provided has helped me the most.
I'll have to take a deeper look into the changes made to uTorrent's WebAPI (that's what Medusa uses).

**Comment by sharkykh** [comment]
Just so we're on the same page, I don't see that you set a username and password for the WebUI.
I'm only saying that because I could see those set in your settings file.


![image](https://user-images.githubusercontent.com/10238474/38408881-f627d1ec-3987-11e8-80a3-64e963ae2206.png)

**Comment by rafi-d** [comment]
Yes . The "remote" UI looks a bit different now  (attached), w/o an option for an alternate port. The fact that I am getting an error shows that some data are getting through., tho, I wouldn't rule out the possibility that uTorrent simply has some kind of a related bug now... 

![1](https://user-images.githubusercontent.com/2458280/38409983-1bc8f8aa-398c-11e8-950f-61ca4c046625.png)

**Comment by sharkykh** [comment]
@rafi-d You are confusing Remote with WebUI - click on the + next to "Advanced" and then, click "Web UI", that is where you need to enter your username and password.

**Comment by rafi-d** [comment]
Right, my mistake, thanks. I have reverted to using the correct dialog/setting, but had another issue, this time -  Medusa - no allowing my username. I have changed it to use only alfa characters , and it seems OK now, so you might want to fix that glitch...  

I'll try later on if it will now also download with the client... 

Thanks!

![1](https://user-images.githubusercontent.com/2458280/38410853-5de2735e-398e-11e8-8871-590240bee638.png)

![2](https://user-images.githubusercontent.com/2458280/38410872-67cb1808-398e-11e8-9748-61cb76d4ffb0.png)

**Comment by sharkykh** [comment]
> but had another issue, this time - Medusa - no allowing my username. I have changed it to use only alfa characters , and it seems OK now, so you might want to fix that glitch...

I can't seem to replicate this issue. Maybe the username / password were actually incorrect. I tried using the same username as you, but it worked just fine for me.
Although, if you used non-English characters in the password, that might not work as expected.

**Comment by rafi-d** [comment]
Done the "snatch" Ok via the webui. There is one issue that I can see - although you specify a location for every show in the UI, with webui in uTorrent  you cannot specify an action to download to a *specific* show location. It will always download to the root, so everything is messed up... This is a limitation of webui:
http://help.utorrent.com/customer/en/portal/articles/1573954-limitations---webapi

The "post-processing" can easily move the download to the proper folder, but if you do it this way, uTorrent is being "disconnected" from the torrent, and will show an error and cannot seed. 

I think this limitation, can be easily worked-around.  if you can add a  per-show label default - to the show name, it will override the global label) .  With such option, utorrent will be able to self-auto-move the data to the proper location, and still keep seeding it. Also, Medusa will be able to update the status properly to "downloaded".  You can also just give a checkbox to "auto-label" with the show name instead, but it is less flexible... 

Can you add this in one of the next releases? At this point, it is not very useful with utorrent   :(

Thanks

Rafi

![1](https://user-images.githubusercontent.com/2458280/38416853-d603a064-399e-11e8-84cc-47c36efc4cfe.png)

**Comment by sharkykh** [comment]
I'm not the one who ultimately decides, but as far as I know, this is not the way Medusa works.
Medusa doesn't download anything - it sends the search result to your client and your client downloads, and then Medusa post-processes downloaded files into your library. That workflow is probably going to stay as it is.
You're suggesting Medusa passes the final folder for the downloaded files to the client, even before it knows what files exactly are being downloaded. You have to keep in mind every user uses whatever client fits them best, and some don't even use torrents, let alone uTorrent.

In my opinion, the better solution for keeping torrents seeded while not having duplicates of the files on your system, is to somehow _"tell"_ the torrent client where Medusa put the file and let it seed it from that location.
Even if that's possible (via an API, a Web UI, etc.) with uTorrent, or any other torrent client for that matter, it would take a lot of work to actually do it.

**Comment by rafi-d** [comment]
>You're suggesting Medusa passes the final folder for the downloaded files to the client,
No, I am simply suggesting to fix a bug in your API calls you are now using  just for utorrent webUI, and add a path=<subfolder name> parameter.  It is on that *SAME* API-request  you use today with the new episode-file in it.   

I am pretty sure you are doing the same for qBittorrent and others, but have just missed it for uTorrent since it is not documented!... :) 

The client cannot "decide"/know where to put any file, except if you tell it, and I believe it is true for every client.

**Comment by rafi-d** [comment]
>I'm not the one who ultimately decides, but as far as I know, this is not the way Medusa works.
Hi,
I have done the required fixes here, locally, and this work fine with uTorrent.   Please inquire with whoever is deciding if they like to adopt these changes. I'll be happy to discuss with them.

Thanks

Rafi

**Comment by medariox** [comment]
@rafi-d 
This is an open source project and everybody is very welcome to contribute to it. Please open a pull request with the mentioned changes and we will discuss/review it ASAP.

**Comment by rafi-d** [comment]
OK. Is basing on latest stable/master branch (as I did here) ok?

**Comment by medariox** [comment]
Sure, we will rebase it to master if you can't do it.

**Comment by rafi-d** [comment]
Done:  https://github.com/pymedusa/Medusa/pull/4005

Some test-screenshots:
http://www.imagebam.com/image/bcf5bc814153593

**Comment by sharkykh** [comment]
#4056
