### ISSUE TITLE
problems sending downloads to transmission

### ISSUE THREAD

**Issue by poplolnman** [pymedusa/Medusa#3964]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: develop
**OS: windows 10
**What you did: sent season download to transmission
**What happened: season download was sent sabnzbd even though its a torrent client download
**What you expected: download to be sent to transmission and completed.
**Logs:**

[screenshot 33](https://user-images.githubusercontent.com/12866874/38381737-b8ae406a-38d5-11e8-8063-b316d0cd7340.jpg)

**Comment by sharkykh** [comment]
@poplolnman 
Jackett integration was recently changed (#3513).
I believe you should have gotten a warning in Medusa:
> Using Jackett providers as Newznab providers is deprecated! Switch them to Jackett providers as soon as possible.

What you need to do is remove the custom newznab provider you set up for Jackett in Medusa, and re-add it as a Jackett provider:
![image](https://user-images.githubusercontent.com/10238474/38408063-9cddae66-3984-11e8-9d3c-74b17a6a3f32.png)

**Comment by medariox** [comment]
Is this issue solved @poplolnman?

**Comment by sharkykh** [comment]
No response.
