### ISSUE TITLE
PostProcessing name parsing error (guessit)

### ISSUE THREAD

**Issue by snamds** [pymedusa/Medusa#3972]
**Branch/Commit: master / https://github.com/pymedusa/Medusa/commit/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**OS: Windows 10
**What you did: postprocess
**What happened: unable to match series

Title should be "cuerpo de elite"

Debug log:

`2018-04-06 19:56:10 DEBUG    Thread-25 :: [] Unable to match Cuerpo de Elite  - Temporada 1 [HDTV 720p][Cap.101][AC3 5.1 EspaÃ±ol Castellano]\CuerpoDeElite720p_101_NEWPCT.mkv to a series in your database. Parser result: title: Cuerpo, season: 1, format: HDTV, screen_size: 720p, episode: [1, 101], audio_codec: AC3, audio_channels: 5.1, release_group: EspaÃ±ol, language: ca, absolute_episode: [101], container: mkv, mimetype: video/x-matroska, type: episode, parsing_time: 0.124000072479, total_time: 724.878000021, quality: 720p HDTV
2018-04-06 19:44:04 DEBUG    Thread-25 :: [] Unable to match CuerpoDeElite720p_101_NEWPCT.mkv to a series in your database. Parser result: title: CuerpoDeElite720p, season: 1, episode: [1], episode_title: NEWPCT, container: mkv, mimetype: video/x-matroska, type: episode, parsing_time: 0.0460000038147, total_time: 5.05400013924, absolute_episode: [], quality: Unknown`

In pycharm I've install guessit (2.1.4) and the result is ok:

guessit.guessit('Cuerpo de Elite  - Temporada 1 [HDTV 720p][Cap.101][AC3 5.1 Español Castellano]\\CuerpoDeElite720p_101_NEWPCT.mkv', dict(show_type=None))
MatchesDict([('title', 'Cuerpo de Elite'), ('season', 1), ('format', 'HDTV'), ('screen_size', '720p'), ('episode', 1), ('audio_codec', 'AC3'), ('audio_channels', '5.1'), ('language', <Language [ca]>), ('episode_title', 'NEWPCT'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])

**Comment by snamds** [comment]
The problem has to do with the "de" of the title. It seems to be a conflicto with "de" as language.
Also even if "de" is removed from allowed language, it fails with the episode number. says [1, 101]

See the guessit results:

u'CuerpoDeElite720p_101_NEWPCT.mkv'

Options:
{
'allowed_languages': set(['ru', 'fr', 'en', 'nl', 'sv', 'pt', 'ca', 'de', 'jp', 'it', 'hu', 'und', 'pl', 'uk', 'mul', 'ro', 'es', 'he']), 
'expected_group': ['TV2LAX9', 'DHD', '20-40'], 
'expected_title': [], 
'allowed_countries': set(['gb', 'us']), 
'episode_prefer_number': False, 
'show_type': None, 'type': 
'episode', 
'implicit': True}

Result:
MatchesDict([
('title', u'CuerpoDeElite720p'), 
('season', 1), 
('episode', 1), 
('episode_title', u'NEWPCT'), 
('container', u'mkv'), 
('mimetype', u'video/x-matroska'), 
('type', u'episode')])

---

u'Cuerpo de Elite  - Temporada 1 [HDTV 720p][Cap.101][AC3 5.1 Español Castellano]\\CuerpoDeElite720p_101_NEWPCT.mkv'

Options:
{
'allowed_languages': set(['ru', 'fr', 'en', 'nl', 'sv', 'pt', 'ca', 'de', 'jp', 'it', 'hu', 'und', 'pl', 'uk', 'mul', 'ro', 'es', 'he']), 
'expected_group': ['TV2LAX9', 'DHD', '20-40'], 
'expected_title': [], 
'allowed_countries': set(['gb', 'us']), 
'episode_prefer_number': False, 
'show_type': None, 
'type': 'episode', 
'implicit': True}

Result:
MatchesDict([
('title', u'Cuerpo'), 
('season', 1), 
('format', u'HDTV'), 
('screen_size', u'720p'), 
('episode', [1, 101]), 
('audio_codec', u'AC3'), 
('audio_channels', u'5.1'), 
('release_group', u'Espa\xf1ol'), 
('language', <Language [ca]>), 
('absolute_episode', 101), 
('container', u'mkv'), 
('mimetype', u'video/x-matroska'), 
('type', u'episode')])

---

Without "de" in allowed languages

u'CuerpoDeElite720p_101_NEWPCT.mkv'

Options:
{
'allowed_languages': set(['ru', 'fr', 'en', 'nl', 'sv', 'pt', 'ca', 'jp', 'it', 'hu', 'und', 'pl', 'uk', 'mul', 'ro', 'es', 'he']), 
'expected_group': ['TV2LAX9', 'DHD', '20-40'], 
'expected_title': [], 
'allowed_countries': set(['gb', 'us']), 
'episode_prefer_number': False, 
'show_type': None, 
'type': 'episode', 
'implicit': True}

Result:
MatchesDict([
('title', u'CuerpoDeElite720p'), 
('season', 1), 
('episode', 1), 
('episode_title', u'NEWPCT'), 
('container', u'mkv'), 
('mimetype', u'video/x-matroska'), 
('type', u'episode')])

---

u'Cuerpo de Elite  - Temporada 1 [HDTV 720p][Cap.101][AC3 5.1 Español Castellano]\\CuerpoDeElite720p_101_NEWPCT.mkv'

Options:
{
'allowed_languages': set(['ru', 'fr', 'en', 'nl', 'sv', 'pt', 'ca', 'jp', 'it', 'hu', 'und', 'pl', 'uk', 'mul', 'ro', 'es', 'he']), 
'expected_group': ['TV2LAX9', 'DHD', '20-40'], 
'expected_title': [], 
'allowed_countries': set(['gb', 'us']), 
'episode_prefer_number': False, 
'show_type': None, 'type': 
'episode', 
'implicit': True}

Result:
MatchesDict([
('title', u'Cuerpo de Elite'), 
('season', 1), 
('format', u'HDTV'), 
('screen_size', u'720p'), 
('episode', [1, 101]), 
('audio_codec', u'AC3'), 
('audio_channels', u'5.1'), 
('release_group', u'Espa\xf1ol'), 
('language', <Language [ca]>), 
('absolute_episode', 101), 
('episode_title', u'NEWPCT'), 
('container', u'mkv'), 
('mimetype', u'video/x-matroska'), 
('type', u'episode')])

**Comment by duramato** [comment]
It's an issue with our version of guessit it seems, the correct test is:

```
$ python Medusa/tests/report_guessit.py "Cuerpo de Elite - Temporada 1 [HDTV 720p][Cap.101][AC3 5.1 EspaÃ±ol Castellano]\CuerpoDeElite720p_101_NEWPCT.mkv"
# guessit: 2.1.4  rebulk: 0.9.0
? Cuerpo de Elite - Temporada 1 [HDTV 720p][Cap.101][AC3 5.1 EspaÃ±ol Castellano]\CuerpoDeElite720p_101_NEWPCT.mkv
: title: Cuerpo
  season: 1
  format: HDTV
  screen_size: 720p
  episode: [1, 101]
  audio_codec: AC3
  audio_channels: 5.1
  release_group: EspaÃ±ol
  language: ca
  absolute_episode: 101
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 0.387345075607
```
vs vanilla guessit
```
$ guessit "Cuerpo de Elite - Temporada 1 [HDTV 720p][Cap.101][AC3 5.1 EspaÃ±ol Castellano]\CuerpoDeElite720p_101_NEWPCT.mkv"
For: Cuerpo de Elite - Temporada 1 [HDTV 720p][Cap.101][AC3 5.1 EspaÃ±ol Castellano]\CuerpoDeElite720p_101_NEWPCT.mkv
GuessIt found: {
    "title": "Cuerpo de Elite",
    "season": 1,
    "format": "HDTV",
    "screen_size": "720p",
    "episode": 1,
    "audio_codec": "AC3",
    "audio_channels": "5.1",
    "release_group": "EspaÃ±ol",
    "language": "Catalan",
    "episode_title": "NEWPCT",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}

 ```

@ratoaq2

**Comment by medariox** [comment]
Partially fixed with the guessit v3 update:
```
λ guessit -t episode "Cuerpo de Elite - Temporada 1 [HDTV 720p][Cap.101][AC3 5.1 EspaÃ±ol Castellano]\CuerpoDeElite720p_101_NEWPCT.mkv"
For: Cuerpo de Elite - Temporada 1 [HDTV 720p][Cap.101][AC3 5.1 EspaÃ±ol Castellano]\CuerpoDeElite720p_101_NEWPCT.mkv                  
GuessIt found: {                                                                                                                       
    "title": [                                                                                                                         
        "Cuerpo",                                                                                                                      
        "de Elite"                                                                                                                     
    ],                                                                                                                                 
    "season": 1,                                                                                                                       
    "source": "HDTV",                                                                                                                  
    "screen_size": "720p",                                                                                                             
    "episode": 1,                                                                                                                      
    "audio_codec": "Dolby Digital",                                                                                                    
    "audio_channels": "5.1",                                                                                                           
    "release_group": "EspaÃ±ol",                                                                                                       
    "language": "Catalan",                                                                                                             
    "container": "mkv",                                                                                                                
    "mimetype": "video/x-matroska",                                                                                                    
    "type": "episode"                                                                                                                  
}                                                                                                                                      
```

**Comment by medariox** [comment]
Fixed with the next release.
