### ISSUE TITLE
Missing time zone for network: OUTtv

### ISSUE THREAD

**Issue by 88keyz** [pymedusa/Medusa#3973]
Branch: master
Commit: d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
OS: Linux-4.4.0-119-generic-x86_64-with-Ubuntu-16.04-xenial

To Reproduce: Add "The Boulet Brothers' DRAGULA" (id=323152) via [TVDBv2]

```
2018-04-06 23:26:38 ERROR    Thread-16 :: [d6eb72d] Missing time zone for network: OUTtv
```

**Comment by droo88** [comment]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-6-amd64-x86_64-with-debian-9.4`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@989daabd0e28da796b3c2f3aae5f7ece2d2a06e9
**Link to Log**: https://gist.github.com/674896d27e50b74fbda7602d02cb2d47
### ERROR
<pre>
2018-05-12 22:27:52 ERROR    Thread_0 :: [989daab] Missing time zone for network: MCOT
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
