### ISSUE TITLE
MAKO Error clicking on a TV Show

### ISSUE THREAD

**Issue by mitchellkeley** [pymedusa/Medusa#3993]
Branch/Commit: master/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
OS: Ubuntu
What you did: Tried to view NCIS: Los Angeles
What happened: given a mako error
What you expected: To see the shows home page
Logs:

File /opt/medusa/medusa/init/filesystem.py:31, in decode:
return text_type(value, 'utf-8' if os.name != 'nt' else fs_encoding)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 29: invalid continuation byte

**Comment by medariox** [comment]
A lot of information is missing in this issue. If you want any valuable help you need to provide the following information:
```
Python Version,
Operating System,
Locale,
Branch,
Database,
Commit,
Full Debug Log,
Error.
```

**Comment by mitchellkeley** [comment]
Sorry,
Python Verison; Python 2.7.12
OS; Ubuntu 16.04
Locale; en_AU.UTF-8
Branch; Master
Database; 44.9
Commit; d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
Full Debug Log; https://pastebin.com/rJ8jgngX
Error; 

File /opt/medusa/medusa/init/filesystem.py:31, in decode:
return text_type(value, 'utf-8' if os.name != 'nt' else fs_encoding)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 29: invalid continuation byte

**Comment by medariox** [comment]
Where does `Locale; en_AU.UTF-8` come from? From Medusa's Help & Info page?

**Comment by mitchellkeley** [comment]
Yes, thats correct

**Comment by OmgImAlexis** [comment]
@medariox I'm using the same Locale with no issues.

**Comment by sharkykh** [comment]
```
2018-04-11 22:30:35 DEBUG Thread-36 :: [d6eb72d] File /usr/lib/python2.7/os.py, line 278, in walk
2018-04-11 22:30:35 DEBUG Thread-36 :: [d6eb72d] File /usr/lib/python2.7/os.py, line 296, in walk
2018-04-11 22:30:35 DEBUG Thread-36 :: [d6eb72d] File /opt/medusa/medusa/helpers/__init__.py, line 1401, in get_size
```
It's trying to get the size of the show's folder, so this has something to do with the files in that folder.

**Comment by labrys** [comment]
The problem is `NCIS: Los Angeles` episode `s09e13`.   The episode title is `Các Tù Nhân` which is Prisoners in Vietnamese.  The error message is saying its having trouble with `á` which as you can tell from [this chart](http://www.i18nqa.com/debug/utf8-debug.html) is what `0xe1` is trying to map to.

**Comment by mitchellkeley** [comment]
Ok, thank you. Renaming that file seemed to fixed the error. Cheers guys
