### ISSUE TITLE
Episodes are being marked as downloaded, although they are not aired.

### ISSUE THREAD

**Issue by Miicker** [pymedusa/Medusa#4019]
**Branch/Commit:**
Master / d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**OS:**
Docker Container (On Synology DSM 6.1.6-15266 update 1)

**What happened:**
So here is what happened, I have some shows in my library, and one of them is driving me nuts. I am talking about American Dad. It all has to do with the episode numbering, the showmakers decided a long time ago to change the numbering, but episodes on the internet are still being numbered the old fashion way. Over here you can see which episode number should be used, and which episode number is actually used:
http://thexem.de/xem/show/4189

For example, S15E08 in Medusa, is uploaded online as S14E09. Some uploaders use the correct naming though. I had lots of issues with this in the past, like episodes from S12 actually being episodes from S11 and so on. I was able to correct a lot of it by hand and I have the complete series now downloaded and named correctly. But I still have problems. New episodes aren't downloaded, or when Medusa tries to download S15E08 for example, it actually downloads the old episode S14E09, which is actually S13E09... So that is very frustrating, to fix this, I manually changed "Scene" to 15x8 so it searches for the name S15E08. I also turned off Scene Numbering to fix this. Now most of the problems where solved, but it takes a very long time to find new episodes, sometimes weeks. And the other problem I have, that every week or so, it puts almost all episodes to "Downloaded", even tough the Episodes are not even aired yet. I have to put the status for those episodes to wanted, and than restart Medusa in order to fix it.

A screenshot of that situation is attached below. Even tough I disabled Scene Numbering, and manually entered the field "Scene" for these Episodes, it picks up the size of the episodes for S14, so the size of episode S15E11 in the screenshot, is actually the size of episode S14E12.

After a long time struggling with this, I want it to be fixed, so hopefully anyone can help me.

**Logs:**
```
Tell me what logs are needed and I past them
```
![image](https://user-images.githubusercontent.com/17907646/38767103-8b225fa6-3fdc-11e8-9809-4d9b2f226235.png)

**Comment by medariox** [comment]
You need to enable `Scene Numbering`.

**Comment by Miicker** [comment]
@medariox before I switched scene numbering off I had the exact same problem, and I had a more annoying problem, which was that some times, Medusa decided to check all episodes again and renaming them, leading to all episodes being named and numbered wrong and the missing of an entire season. So I am afraid if I turn scene numbering on again it will mess it up again..

**Comment by labrys** [comment]
@Miicker same reason i dont use scene numbering

**Comment by Miicker** [comment]
@medariox so I followed your advice, and I turned on scene numbering, and well, it has gone wrong once again. Medusa now downloaded the new episode (so that is nice) but it also re-downloaded 5 other episodes (which already where downloaded) and it replaced some of the old episodes with the new ones, which are the wrong episodes. So S14E21 is downloaded again for example. Medusa downloaded S13E21 and named it to S14E21, but it's actually S13E21...

Most of the downloads failed luckily, but the download status for those episodes is still "Snatched",when I change it to downloaded, the file size is not filled. So its pretty annoying. Why does Medusa even snatch episodes which are already downloaded?

**Comment by medariox** [comment]
What quality were the old episodes and what are your quality settings? Just refresh the show and it will find the new files. If you want further help you need to post Debug logs of whatever search triggered the snatch of already downloaded episodes.

**Comment by Miicker** [comment]
The quality is 720p HDTV, the snatched quality is also 720p HDTV, but with a "PROPER" tag, maybe that has something to do with it (not sure what it means).

Preferred qualities:
720p HDTV, 720p WEB-DL, 720p BluRay

**Comment by medariox** [comment]
It has indeed a lot to do with why those episodes are being downloaded. Read about the meaning of _Proper_ here: https://scenelingo.wordpress.com/2008/07/16/what-does-proper-mean/

You can disable the download of Propers from Gear > Search Settings (not recommended):
![prop](https://snapr.pw/i/8b3b658ded.png)

**Comment by Miicker** [comment]
@medariox thanx for the information! Isn't it possible to turn this off for just the one tv show? That would be great.

**Comment by medariox** [comment]
No, but you can set the episode status to Archived, Skipped or Ignored. Either of these should prevent further downloads for the episode.

**Comment by medariox** [comment]
What status were they? Something tells me they were `DOWNLOADED`... Just enabled debug logging, let Medusa run for a few days and when it happens again post all the logs from your `Logs` folder.

**Comment by Miicker** [comment]
I have enabled debug logging, and I don't know what the status of the episode was, but why is Medusa even snatching episodes which are 190+ days old while the episode is released a few days ago?

**Comment by medariox** [comment]
Closing, let us know if yous till have this issue.
