### ISSUE TITLE
Search sub-folders for subtitles

### ISSUE THREAD

**Issue by flick1999** [pymedusa/Medusa#4034]
It appears that Medusa is not seeing subtitles when they're in a sub-folder from the folder containing the media files. Should be an easy solution, just have it search all sub-folders within the folder containing the media files.

**Comment by medariox** [comment]
You need to add a relative subtitles directory within your subtitle settings.

**Comment by phraymond** [comment]
I appreciate the assist, thank you. Sadly though, I don't see where to make that setting?

**Comment by medariox** [comment]
Gear > Subtitles Settings
![subs](https://snapr.pw/i/8e6ad6d4f5.png)

**Comment by medariox** [comment]
It will be the subfolder where you're supposed to keep the subtitles for X show.

**Comment by phraymond** [comment]
Ok, so I did understand it right. That's not going to rectify my issue, I'm
afraid. I need the post-processor to look in \queue\tvshowname\subs and
then move them along with the media to \tv\tvshowname\season1\. That's the
issue I'm having.

**Comment by phoenix83** [comment]
Why is this closed? A lot of releases put subtitles in subfolders. Sickrage handles this fine.

**Comment by p0psicles** [comment]
I closed all issues older then 6 months

**Comment by phoenix83** [comment]
Ok I'm not confident enough to submit it myself, but I believe I may have found where the issue is.

The functionality appears to be implemented in the _search_files() method of post_processor.py:
> 
        files = []
        for root, _, filenames in os.walk(directory):
            for filename in fnmatch.filter(filenames, pattern):
                files.append(os.path.join(root, filename))
            if not subfolders:
                break

however in the _combined_file_operation() method, the calls to list_associated_files() do not explicitly set the 'subfolders' argument (which then defaults to false):
> 
        file_list = [file_path]
        if associated_files:
            file_list += self.list_associated_files(file_path, refine=True)
        elif subtitles:
            file_list += self.list_associated_files(file_path, subtitles_only=True, refine=True)

Ideally it needs to be implemented as a user option though.

**Comment by phoenix83** [comment]
I'm surprised this issue isn't more popular, but perhaps the issue title is misleading. Something like "Post-processor not including sub-folders" would be better as it's more than just sub-titles.

**Comment by papampi** [comment]
+1 on this
So many full season shows put their subtitles inside a sub directory and medusa not process them

**Comment by medariox** [comment]
Added with: https://github.com/pymedusa/Medusa/pull/7889

**Comment by phoenix83** [comment]
This is listed as fixed in 0.3.14 on the release page, but I'm running 0.3.15 and it's still not working?

**Comment by papampi** [comment]
Not working for me either

**Comment by medariox** [comment]
Saying it's not working is useless. Open a proper bug report with all needed information and debug logs.
