### ISSUE TITLE
Wrong URL for yggtorrent

### ISSUE THREAD

**Issue by angarod** [pymedusa/Medusa#4039]
The URL for yggtorrent provider in torrent websites is changed since march : https://yggtorrent.is

**Comment by patricemeyer** [comment]
hello 
 https://github.com/pymedusa/Medusa/commit/f921b860e8a0769a17880652ed171120c5dbf278

**Comment by OmgImAlexis** [comment]
Closed in https://github.com/pymedusa/Medusa/commit/f921b860e8a0769a17880652ed171120c5dbf278

You'll need to wait for develop to be merged into master.

**Comment by angarod** [comment]
The URL for Yggtorrent has once again changed : https://ww1.yggtorrent.is
