### ISSUE TITLE
Medusa not creating metadata when post processing?

### ISSUE THREAD

**Issue by NathZ1** [pymedusa/Medusa#4062]
Hi guys, recent convert from SickRage here - Great app you have going here!

One problem i am finding however...

Medusa seems to be not able to write metadata when post processing, but when i do a manual refresh on a show after it has post processed an episode it does write it (so obviously not a permission problem)... Any ideas why this is happening? 

TIA.

**Branch/Commit: master
**OS: DSM 6.1.6

Post processor log:

https://pastebin.com/raw/KrKSZEnv

Edit (sharkykh): Moved log to pastebin.

**Comment by medariox** [comment]
Is it just happening with TMDB as indexer?

**Comment by sharkykh** [comment]
It should have logged a warning or an error, but there was a bug in the part that does that, see #4111 
I am pretty sure there was an actual error with saving the file, and I hope after that will will have an answer...

**Comment by Naffles** [comment]
thanks @sharkykh  for this information. I am now actually using Emby to post process. Once fix gets pushed into master i'll revert back to post process via Medusa to see if i can generate an error/warning. Should I close issue for now?

Cheers

**Comment by sharkykh** [comment]
@Naffles Let's keep it open, since release is a few days away at max.

**Comment by Naffles** [comment]
10-4

**Comment by sharkykh** [comment]
@Naffles No news mean good news? Can we close this?

**Comment by Naffles** [comment]
Sorry mate completely forgot about this one. I'm still using Emby to post process will flick back to Medusa and report back in a few minutes
