### ISSUE TITLE
Can't add scene exceptions on last stable

### ISSUE THREAD

**Issue by genimac** [pymedusa/Medusa#4068]
Hello after the update to the last version I can't add scene exceptions.
Branch: Master, v0.2.2
Commit: 77b20916ab577b82112ebc624f816054788c63f2
Database: 44.9
Python Version: | 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
SSL Version: | OpenSSL 1.1.0f 25 May 2017
OS: | Linux-4.14.0-0.bpo.3-amd64-x86_64-with-debian-9.4
Locale: | en_US.UTF-8

What you did: go to edit on an anime show and tried to add an scene exception
What happened: add button don't work, no way to add the exception
What you expected: new scene name added to the list

Connected from Safari 11.1 on macOS HighSierra 10.13.4

![captura de pantalla 2018-04-21 a las 17 57 29](https://user-images.githubusercontent.com/10963265/39086256-42d85116-458f-11e8-86ac-59d6337fa0d9.png)

**Comment by genimac** [comment]
Download Firefox and Chrome on macOS.
Both work, issue is Safari only seems.

**Comment by sharkykh** [comment]
This was fixed with the new editShow UI that will be available on the next release.
