### ISSUE TITLE
Loading editShow whows wrong location

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#4072]
Reminder for @OmgImAlexis 

When editing a show, it's using the location from the browsers localStorage.
Sometime it's using the wrong location, sometime (when starting clean) it's showing an empty input box.

Note!
I renamed the 'key' attribute of the file-browser component props, int `localStorageKey` because vue was complaining, as it's a reserved keyword. (that's also now in develop).

I'm not sure if that's the cause. I don't think so.

**Comment by sharkykh** [comment]
I haven't looked into it just yet, but I think [browser.js](https://github.com/pymedusa/Medusa/blob/develop/themes-default/slim/static/js/browser.js) is being loaded before `file-browser.mako` and taking precedent over the component.

Before removing that file, need to make sure `file-broswer` implements everything `browser.js` does.

**Comment by sharkykh** [comment]
Fixed in #4075
