### ISSUE TITLE
Invalid URL specified pop up on providers page

### ISSUE THREAD

**Issue by bobbysteel** [pymedusa/Medusa#4083]
With the newest push to master, whenever on the provider page I keep getting this error. Have deleted cache.db and cache folder on the server and cleared browser cookies, but to no avail. Any ideas how to further debug? Running with https enabled fwiw.

**Comment by sharkykh** [comment]
Try checking your Newznab, Torznab (Jackett) and Torrent RSS providers.
The pop-up seems to be coming from one of them.

**Comment by sharkykh** [comment]
You can also try checking the config file:
```ini
[Newznab]
newznab_providers = ,
[TorrentRss]
torrentrss_providers = ,
[Torznab]
torznab_providers = ,
```

**Comment by bobbysteel** [comment]
Cool that fixed it. Might be worth a fix for a clearer error message though?

**Comment by sharkykh** [comment]
Done! @bobbysteel
