### ISSUE TITLE
ImportError: No module named lib2to3.pgen2.parse

### ISSUE THREAD

**Issue by Sevyx** [pymedusa/Medusa#4087]
**Branch/Commit:** Master
**OS:** armv5tel - python 2.7.14
**What you did:** First had a different error then decided to update it with the following command:

```
git remote set-url origin https://github.com/SickRage/SickRage.git
git fetch origin
git checkout master
git branch -u origin/master
git reset --hard origin/master
git pull
```

Even tried python 3.5 but didnt fix it either so switch back to python 2.7.14

**What happened:** Cant start up pymedusa after the update 2 days ago. Tried trouble shooting myself but gave up since my knowledge of python is limited. 

**What you expected:** a working pymedusa

```
[/share/MD0_DATA/.qpkg/SickBeard-TVRage] # sh sickbeard-tvrage.sh start
armv5tel
SickBeard-TVRage prestartup checks...
 Checking for git...  Found!
Looking for /usr/bin/python2.7
Looking for /usr/local/bin/python2.7
Looking for /opt/bin/python2.7
Looking for /Apps/opt/bin/python2.7
Looking for /opt/QPython2/bin/python2.7
Found Python Version 2.7.14 at /opt/bin/python2.7
Updating SickBeard-TVRage
HEAD is now at a760263 Update translations (build 9390) [skip ci]
Already up-to-date.
Starting SickBeard-TVRage
Traceback (most recent call last):
  File "SickBeard.py", line 548, in <module>
    SickRage().start()
  File "SickBeard.py", line 250, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/__init__.py", line 1316, in initialize
    if x]
ValueError: invalid literal for int() with base 10: '[]'
```

**Comment by sharkykh** [comment]
You changed your repo to SickRage.
Do this: https://github.com/pymedusa/Medusa/wiki/FAQ's-and-Fixes#update-problems-try-this

**Comment by medariox** [comment]
Gone in Python 3 https://docs.python.org/3.0/whatsnew/3.0.html#ordering-comparisons

**Comment by twolaw** [comment]
Same happened on Libreelec distro.
Python 2.7 on Libreelec is missing the lib2to3 module.
So, last Medusa update can't start anymore on this system.

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/4089
