### ISSUE TITLE
More accurate search for french season

### ISSUE THREAD

**Issue by angarod** [pymedusa/Medusa#4091]
I am looking for sense8 season 1 on yggtorrent and medusa just show me the result with "season" or "S01" but i want to specifically tell medusa to search with "saison" (season in french). The option is not available in the search settings.

**Comment by Naworm** [comment]
I've reopened this here with more informations : https://github.com/pymedusa/Medusa/issues/7919
Maybe you can close this one and re-open the other one ;)
