### ISSUE TITLE
Jackett issue

### ISSUE THREAD

**Issue by Cylae** [pymedusa/Medusa#4099]
Hello,

I've the same issue : https://github.com/pymedusa/Medusa/issues/3964

I tried to delete custom newznab providers and add them again as Jackett providers but they are still displaying into newznab providers...

Thank you for your help ! :)

**Comment by OmgImAlexis** [comment]
@medariox or @sharkykh could you have a look at this?

**Comment by medariox** [comment]
It works correctly here.

**Comment by sharkykh** [comment]
@Cylae did you save after deleting, and saves after adding?

**Comment by medariox** [comment]
Closing this until the bug is confirmed.
