### ISSUE TITLE
[ Feature ] Force update scene exceptions button

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#410]
It'd be nice to have a button added to the config page where you could force the scene exceptions file to be updated.

**Comment by fernandog** [comment]
scene exceptions is updated before every dailysearch run

**Comment by OmgImAlexis** [comment]
If I add a show and then manually search it won't necessarily be updated or if I update the exceptions on Github it won't be updated right away so adding a manual update button would help.
