### ISSUE TITLE
Manual search dont work after last update

### ISSUE THREAD

**Issue by Diablobait** [pymedusa/Medusa#4102]
Since last update 50% of the time i try to manual search i get a white screen with no text or code, if a show get this error i cannot make manual search again always white screen

**Branch/Commit: Master
**OS: Ubuntu 16.04 Server
**What you did: Manual Search
**What happened: White screen, no code
**What you expected: Manual search of a show
**Logs: No debug logs, nothing happen i can record a movie if you want
```
PASTE LOGS HERE
```

**Comment by OmgImAlexis** [comment]
I need more info. Please use the form that we provide when opening the issue.

I have edited your post to add the form.

**Comment by medariox** [comment]
No debug logs = impossible to help.

**Comment by Diablobait** [comment]
updated

**Comment by medariox** [comment]
Still need debug logs.

**Comment by OmgImAlexis** [comment]
@Diablobait could you show a screenshot? I'm not sure what you mean by "50% of the time i try to manual search i get a white screen with no text or code". I have checked both master and develop and neither seem to have said issue.

@sharkykh I did notice the manual search event handler being removed after the div is reloaded though. We're going to have to add an API route for the results if we don't already have one.

**Comment by sharkykh** [comment]
What about the web browser's log console? If you use Chrome press F12 and click the console tab, **then**  try to reproduce the issue and see if you get any errors in that log.

**Comment by Diablobait** [comment]
no errors, and on the html code: no head no body and <style id="stylish-32" class="stylish" type="text/css">/* AGENT_SHEET */
@namespace url(http://www.w3.org/1999/xhtml);</style>

**Comment by Diablobait** [comment]
i tried on firefox and now i get this error code
2018-04-30 00:53:00 ERROR    Thread_9 :: [Newpct] :: [Newpct] :: [Newpct] :: [77b2091] Exception generated: astimezone() cannot be applied to a naive datetime
Traceback (most recent call last):
  File "/home/master/.medusa/medusa/server/web/core/base.py", line 285, in async_call
    result = function(**kwargs)
  File "/home/master/.medusa/medusa/server/web/home/handler.py", line 1174, in snatchSelection
    show_all_results=show_all_results, **search_show)
  File "/home/master/.medusa/medusa/search/manual.py", line 306, in get_provider_cache_results
    i['pubdate'] = parser.parse(i['pubdate']).astimezone(app_timezone) if i['pubdate'] else ''
ValueError: astimezone() cannot be applied to a naive datetime

**Comment by sharkykh** [comment]
@medariox could this be a remnant in the cache db?

**Comment by Diablobait** [comment]
i removed cache.db, restarted, enable newpct and its the same:

2018-04-30 19:04:13 ERROR    Thread_8 :: [Newpct] :: [77b2091] Exception generated: astimezone() cannot be applied to a naive datetime
Traceback (most recent call last):
  File "/home/master/.medusa/medusa/server/web/core/base.py", line 285, in async_call
    result = function(**kwargs)
  File "/home/master/.medusa/medusa/server/web/home/handler.py", line 1174, in snatchSelection
    show_all_results=show_all_results, **search_show)
  File "/home/master/.medusa/medusa/search/manual.py", line 306, in get_provider_cache_results
    i['pubdate'] = parser.parse(i['pubdate']).astimezone(app_timezone) if i['pubdate'] else ''
ValueError: astimezone() cannot be applied to a naive datetime

**Comment by medariox** [comment]
Looks like you manually modified the provider or something the like. We don't/can't support custom changes. Anyway, the provider is currently broken - just disable it until it is fixed.
