### ISSUE TITLE
Error post processing renaming

### ISSUE THREAD

**Issue by Diablobait** [pymedusa/Medusa#4103]
I have an error with caps with post processing, mesusa just rename for example Legion S01E05 cap with the name Legion S01E105 and plex go crazy because think season has 115.

**Comment by sharkykh** [comment]
What do you mean by 'caps'?
Please provide debug logs of that action.

**Comment by Diablobait** [comment]
i just activate debug log, the next time i have the error i will paste it

**Comment by sharkykh** [comment]
If you get the error again, post the logs here and I'll reopen the issue.
