### ISSUE TITLE
downloading torrents and nzbs of the same episodes

### ISSUE THREAD

**Issue by poplolnman** [pymedusa/Medusa#4105]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit**: master
**OS**: windows 10
**What you did**: added show to medusa
**What happened**: double downloaded individual downloads via nzb and whole seasons via torrent
**What you expected**: to download each episode singely
**Logs**: is there a setting i may have clicked that caused this? its just causing a lot of unnecessary downloading that uses up my data limit.
```
PASTE LOGS HERE
```

**Comment by sharkykh** [comment]
Please provide debug logs. Can't track down the issue without them.

**Comment by sharkykh** [comment]
Well, firstly...
Did you add `The Last Ship` and set the status of all the episodes to Wanted **by mistake** or **intentionally**?

**Comment by poplolnman** [comment]
intentionally

**Comment by poplolnman** [comment]
also not sure if this matters but when i first add a show it says that it is unable to add it, but then says it is added...

**Comment by David-EU** [comment]
There is not much need of more informations. I got this issue each time I add a show or add an existing show, just try.
Adding a show is asking double time the informations of the show, basicaly doing two time the same process for the same show/season.
BTW you can just bypass the second time or go trough the overall process with ignoring errors, you'll have your shows.

**Comment by sharkykh** [comment]
Possibly fixed with #4311.
