### ISSUE TITLE
Auto post processing or post processing by url does not work..

### ISSUE THREAD

**Issue by felipesalomao** [pymedusa/Medusa#4123]
Branch/Commit:  Master/77b20916ab577b82112ebc624f816054788c63f2
OS: Raspbian Raspberry PI3 

Auto Processing does not work. i set it to auto process each 10 minutes.. Folder is mnt/organizar.. I also have command line that i use after download something that worked on past to send command to post process especific folder..
When i try open it derectly on browser, it seems not work.. Just redirect to link without any suceess or fail message: 
http://192.168.1.158:7073/home/postprocess/

this is full link i tried test..
http://192.168.1.158:7073/home/postprocess/processEpisode?dir="/mnt/organizar/Westworld.S01E02.NORDiC.1080p.WEBRip.DD5.1.H.264-DBRETAiL"

Looking on logs, i wasnt able any post process log.. Tried look each 10 minutes and not found anything, also tried look after send http command..  

I only am able to post process, if do it manually on url http://192.168.1.158:7073/home/postprocess/, then selecting folder clicking on browse button and after clicking on process button..

Any tips?

**Comment by sharkykh** [comment]
I use the API for the very same purpose every day.
I made a script for it, maybe I'll upload it on Github when I have time.
Navigate to http://192.168.1.158:7073/apibuilder and read about the `postprocess` API command.

**Comment by felipesalomao** [comment]
Thank you.. I was able to make it auto post process each 10 minutes.. But not was able to run script.. I see your script, but i dont understand pyhton.. Just a little bit of simple bash.. I just want run simplier bash script as possible.. I can  get corect directory easly using transmission api.. Thats no problem for me.. The question is just command line itself.. tried 3 different ways:

`wget -qO /dev/null 192.168.1.158:7073/home/postprocess/processEpisode?dir="/mnt/organizar/Westworld.S01E02.NORDiC.1080p.WEBRip.DD5.1.H.264-DBRETAiL" & `

`/sbin/curl --data "dir=/mnt/organizar/Westworld.S01E02.NORDiC.1080p.WEBRip.DD5.1.H.264-DBRETAiL" http://192.168.1.158:7073/home/postprocess/processEpisode`

`curl -X POST -d http://192.168.1.158:7073/home/postprocess/processEpisode?dir="/mnt/organizar/Westworld.S01E02.NORDiC.1080p.WEBRip.DD5.1.H.264-DBRETAiL"`

when i run those commands.. i just receive this kind of information on putty:
```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    76    0     0  100    76      0   3037 --:--:-- --:--:-- --:--:--  3166

```
 i do not  get any error and viewing debug, i cant find anything.. but for example if i type command wrong like:
`/sbin/curl --data dir="/mnt/organizar/Westworld.S01E02.NORDiC.1080p.WEBRip.DD5.1.H.264-DBRETAiL" http://192.168.1.158:7073/home/postprocess/processEEEpisode`

i get on medusa log:
```
2018-04-27 02:04:29 DEBUG    TORNADO :: [77b2091] F**********iled doing web ui post request u'processEEEpisode': Tr**********ceb**********ck (most recent c**********ll l**********st):
  File "/opt/medus**********/medus**********/server/web/core/b**********se.py", line 267, in post
    method = get**********ttr(self, route)
AttributeError: 'HomePostProcess' object h**********s no **********ttribute 'processEEEpisode'
```

But when i trype correct, it dont show any log..

**Comment by felipesalomao** [comment]
I think i found solution looking api builder, on command line it worked.. Now i will test on script.. 
wget -qO /dev/null $NASADRESS:$PORT/api/v1/ea3ea1255177925d357da1b51060d5f7/?cmd=postprocess&path="${DIRETORIO}"

NASADRESS  is medusa ip, port then Diretorio is folder to scan.. Will test then talk here..

**Comment by OmgImAlexis** [comment]
If you're just trying to have it auto PP every 10 minutes then why not just enable auto PP?

What're you actually trying to achieve with this?

**Comment by OmgImAlexis** [comment]
Closing as this is more asking how to work with the API than it is an issue/bug report.

**Comment by sharkykh** [comment]
For the record, for POST requests you have to provider the arguments as form data. I don't see you doing that with `curl`.
This might have worked for you:
```
curl -X POST http://192.168.1.158:7073/home/postprocess/processEpisode -d "dir=/mnt/organizar/Westworld.S01E02.NORDiC.1080p.WEBRip.DD5.1.H.264-DBRETAiL"
```

But since you found a solution - nevermind.
