### ISSUE TITLE
Second click on some main-menu items - results with a wrong server-link

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#4127]
**Branch/Commit:**
v 0.22

**OS:**
Win 10

**What you did:**
second click on main menu items with listview: Shows, Manage, settings and the last one.

**What happened:**
"Oops
You have reached this page by accident, please check the url."

**What you expected:**
Either selecting a default(first? user-defined?)  menu item
or: close the drop-down list

**Logs:**
examples of  generated links:
http://localhost:8081/http://localhost:8081/manage/episodeStatuses/
http://localhost:8081/http://localhost:8081/config/

**Root cause:**
Links are being appended to the existing address-link, w/o clearing it first...

**Comment by OmgImAlexis** [comment]
Do you have your webroot set?

I have the same version installed without that issue.

**Comment by rafi-d** [comment]
No, it's blank (default). What should it be set to and why ? I've no issues w/o setting it till now...

**Comment by OmgImAlexis** [comment]
Blank is fine.

Could you please check the page source and see what the `<base>` element has the href field set to?

**Comment by OmgImAlexis** [comment]
@p0psicles any idea why his base has not ending slash?

Mine is like this `<base href="http://localhost:8081/">`.

**Comment by rafi-d** [comment]
Same as mine. Have you cleared this webroot settings from your config, restarted  and re-created? I'm using Chrome., BTW.

**Comment by OmgImAlexis** [comment]
I have no webroot set, I can't reproduce this issue at all.

**Comment by rafi-d** [comment]
See if you follow my use-case/clip-
https://drive.google.com/file/d/15i7GwIhoE2YKg122AGHorFpgCrDo8Kam/view?usp=sharing

**Comment by OmgImAlexis** [comment]
Okay I see what you're meaning now.

**Comment by rafi-d** [comment]
A clip is always best ... :)  
Do you plan for second click to maybe open the first (default?) drop-list item?
