### ISSUE TITLE
General Update Kodi button not working

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#4141]
Medusa Info: | Branch: master                 Commit: 77b20916ab577b82112ebc624f816054788c63f2                 Version: v0.2.2                 Database: 44.9
-- | --
Python Version: | 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2k  26 Jan 2017
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

The general `Update Kodi` menu item does not work any more.
Link goes to: `https://xxx.yyy/home/updateKODI/`
![image](https://user-images.githubusercontent.com/4103090/39408794-191728fe-4bdc-11e8-947c-fb8fe22ed239.png)

```
Error
Invalid show ID 
```

**Comment by Naffles** [comment]
Is this the same as the error i get when i try to update Emby for an individual show? Error is: 

WARNING  Thread_18 :: [77b2091] EMBY: Provider unknown

There is no corresponding Emby log at all so nothing is being sent to the emby server.

**Comment by sharkykh** [comment]
@Naffles No, that's a different issue.
It seems like EMBY only supports using TVDB ID to identify a show.
We'll have to do something else to fix that.

**Comment by Naffles** [comment]
That's interesting... I use TMDB as default anyway (option set in settings) ... so shouldn't it be sending that through?

**Comment by Naffles** [comment]
Sorry misread. TMDB vs TVDB... Is this going to be hard to fix? I'm surprised the issue hasn't come up previously - does no-one use Medusa/Emby is combo?

**Comment by sharkykh** [comment]
As I said, **EMBY** doesn't seem to support updating the TV library using indexers other than TVDB.
I'm working on a workaround for that.

**Comment by Naffles** [comment]
Can confirm that this is now working... however...

When updating a specific show there is no INFO level log that it has been done, only DEBUG. I initially thought it still wasn't working as there was nothing in the standard log - is it possible to log an additional INFO level notification that it has occurred? 

If not no biggie - like i said it looks to be working now... although it is also a bit strange that there is nothing after the for colons (i.e. no post data or HTTP response).

MEDUSA:
2018-05-21 17:42:34 DEBUG    Thread_16 :: [212cd1c] EMBY: HTTP response: 
2018-05-21 17:42:34 DEBUG    Thread_16 :: [212cd1c] With post data: 
2018-05-21 17:42:34 DEBUG    Thread_16 :: [212cd1c] User-Agent: Medusa/0.2.3 (Linux; 3.10.102; ac678421-5a83-11e8-86a4-0011325d9479)
2018-05-21 17:42:34 DEBUG    Thread_16 :: [212cd1c] POST URL: http://192.168.1.15:8096/emby/Library/Series/Updated?tvdbid=272644 [Status: 204]

EMBY:
2018-05-21 17:42:33.802 Info HttpServer: HTTP POST http://192.168.1.15:8096/emby/Library/Series/Updated?tvdbid=272644. UserAgent: Medusa/0.2.3 (Linux; 3.10.102; ac678421-5a83-11e8-86a4-0011325d9479)
2018-05-21 17:42:34.091 Info HttpServer: HTTP Response 204 to 192.168.1.15. Time: 290ms. http://192.168.1.15:8096/emby/Library/Series/Updated?tvdbid=272644 
2018-05-21 17:43:34.157 Info LibraryMonitor: 12 Monkeys (/volume1/ZipfData/TV Series/12 Monkeys) will be refreshed.

**Comment by sharkykh** [comment]
1. > When updating a specific show there is no INFO level log that it has been done, only DEBUG. I initially thought it still wasn't working as there was nothing in the standard log - is it possible to log an additional INFO level notification that it has occurred?

That's actually on-par with the other
2. `With post data: ` - This is correct. The EMBY API is weird. You need to pass the `tvdbid` in the url (like a GET request) rather in the request body (like a POST request).
3. `EMBY: HTTP response: ` - The response from EMBY is [204 - No Content](https://httpstatuses.com/204):
```
2018-05-21 17:42:34.091 Info HttpServer: HTTP Response 204 to 192.168.1.15. Time: 290ms. http://192.168.1.15:8096/emby/Library/Series/Updated?tvdbid=272644 
```
I can remove it, but maybe it's there for a reason, maybe if there's an issue, EMBY reports back.
(Plus, I can't find a good documentation source for the EMBY API and I don't really want to install it...)

**Comment by Naffles** [comment]
Yeah no worries mate. Cheers for all your work!
