### ISSUE TITLE
When setting status back to 'WANTED' quality of the existing file get's lost

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#4156]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:**
**What you did:**
1. Downloaded an episode, but it was a bad release.
2. Changed it's status to wanted
3. Started a backlog

**What happened:**
All results were ignored because the existing quality was 'UNKNOWN'.
**What you expected:**
That it would replace the existing file.
**Logs:**
```
2018-05-03 06:14:55 DEBUG    SEARCHQUEUE-BACKLOG-284131 :: [NZBGeek] :: [781bfd2] 284131: 'The Seven Deadly Sins' S02E08 status is: 'SNATCHED (UNKNOWN)'. Ignoring result with quality '720p HDTV'. Reason: Existing quality is UNKNOWN. Ignoring new quality (edited)
```

Imo there are three issues here:
1. When you reset the status of an ep to wanted, you overwrite the status to 3. With that, you lose the combined status info. And thus lose the original quality.
2. When it can't detect an existing quality, it won't replace. I still don't understand the reasoning behind this.
3. It's not using `knowit` to detect the quality. Where in my case, this would also have resolved the issue.

**Comment by p0psicles** [comment]
The immediate issue 1 I can fix myself. The others we should also address imo.

**Comment by p0psicles** [comment]
Ok so what your saying is that our users should know that they always need to move an episode status back to failed, when they want to research an episode.

And when they change it like I did, so from downloaded, directly back to wanted, the episode will stick at wanted indefinitely.

I'm just trying to summarize the issue.

**Comment by snamds** [comment]
Unkown quality is the highest value of the quality enum. Could be this the reason?
I had to do this https://github.com/pymedusa/Medusa/pull/4204 because unkown quality was picked over 720p in my case

**Comment by p0psicles** [comment]
Well were in the process of removing unknown status. So in the near future, this shouldnt be an issue anymore
