### ISSUE TITLE
Parsing in Notification Emails

### ISSUE THREAD

**Issue by synthetc82** [pymedusa/Medusa#4159]
**Branch/Commit:** 77b20916ab577b82112ebc624f816054788c63f2 / master
**OS:** Server 2012 R2
**What you did:** - Sent a notification email
**What happened:** Email body parsing incorrect
**What you expected:** Parsing to be correct 
**Logs:** NA - See screenshots below! 

Hey guys, my TV show notification emails are showing like below, they display the same on webmail / outlook / android mail app etc.

![image](https://user-images.githubusercontent.com/38138869/39642804-bc6b7c16-4fca-11e8-8376-d094f26882a7.png)

![image](https://user-images.githubusercontent.com/38138869/39642829-cc348336-4fca-11e8-8eaf-b0704107f0d6.png)
![image](https://user-images.githubusercontent.com/38138869/39642858-db2890ee-4fca-11e8-9fc3-19c80cf32c1b.png)
![image](https://user-images.githubusercontent.com/38138869/39642877-e943be06-4fca-11e8-9dc8-5359a479fc04.png)
![image](https://user-images.githubusercontent.com/38138869/39642894-f637f0c8-4fca-11e8-8c13-fa898e059fb7.png)

**Comment by sharkykh** [comment]
Fixed in develop.
We are working on a release so it will be in master by tomorrow, if not sooner :)
