### ISSUE TITLE
Cannot add all existing shows / mass update due to URL limitation

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#416]
issue from upstream that need to be fixed here

"I recently decided to redo my SickRage container and wanted to add my shows back using /addShows/existingShows/... and since I have a lot of content, the URL exceeded 32800 characters, and Chrome returns a ERR_CONNECTION_RESET. It's hard for me to determine exactly how many shows I can actually add before reaching this limitation since SickRage only allows me to select all shows, or pick and choose (and with a lot of shows, this is tedious and time consuming). I think I was able to add about around 430 shows by playing around with the URL. But until all of these 430 shows add, they will still appear in existingShows until they are added.

Branch/Commit: Develop SickRage/SickRage@a18ae55
OS: Debian 8
What you did: Tried to add all shows at once
What happened: /addShows/addExistingShows URL was too long and incomplete as it exceeded 32800 characters.
What you expected: Be able to add all shows without hacking up the URL."

https://github.com/SickRage/sickrage-issues/issues/1203

**Comment by OmgImAlexis** [comment]
The easiest fix for this is to use a post request and handle the added shows in the background instead of using get as post doesn't add anything to the URL.

For now as a work around people can use Firefox as it doesn't have this "issue".

**Comment by p0psicles** [comment]
I'll change it to a json send by post.

**Comment by p0psicles** [comment]
WIP: https://github.com/pymedusa/SickRage/pull/434

**Comment by p0psicles** [comment]
Ready for some testing.
@didyouexpectthat whe are looking for a tester for this. Willing to get involved?

**Comment by p0psicles** [comment]
Maybe we shouldn't merge this to our first release. Feels a little hacky. And I can't even resproduce the issue, as you would need to add alllottttt of shows. And who does that often? And possibly selecting not all shows to update/add at once, would be a pretty easy workaround.

**Comment by didyouexpectthat** [comment]
I wouldn't mind doing some testing.
I have >1400 shows.

**Comment by OmgImAlexis** [comment]
@p0psicles is this still in progress or did we end up merging the fix?

**Comment by p0psicles** [comment]
It's still in a Pr somewhere.

**Comment by sharkykh** [comment]
Should have been fixed with #4267.
