### ISSUE TITLE
Update qBittorrent client to use API v2

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#4161]
Added in qBittorrent version 4.1.0 which was released May 4th, 2018
https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#changes

- The older API still works, hence the low priority.
- API v2 requires logging in before you can query for the API and/or Application version, plus it uses SemVer, while the older API versioning system is a simple integer (last version was 18).

**Comment by fabiotp91** [comment]
I can't connect to my qBittorrent, is it because of this?

**Comment by sharkykh** [comment]
Probably not. I'm using version 4.1.4 and it works for me.

**Comment by fabiotp91** [comment]
Mine is giving an error with pymedusa, but I can use qBittorrent with Sonarr for example.

url of the error:
https://preview.redd.it/l59cjjq6ywz11.png?width=640&crop=smart&auto=webp&s=093a9278fb38dd5d7de80844028632e7b805f602

**Comment by sharkykh** [comment]
Well it says "Invalid Host" - check the `config.ini` file in your data folder for the value of `torrent_host`.
For example mine is:
```ini
torrent_host = http://192.168.1.1:12121/
```

**Comment by medariox** [comment]
The code says that `Invalid Host` is shown either if the schema is missing or the URL is invalid. https://github.com/pymedusa/Medusa/blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/clients/torrent/generic.py#L87
So it's either the one or the other and since you don't post the URL we obviously can't know.

**Comment by fabiotp91** [comment]
I'm going to be honest, I fixed my problem by changing the API name, now it's working normally

**Comment by sharkykh** [comment]
#6505
