### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Fox España

### ISSUE THREAD

**Issue by aferpa94** [pymedusa/Medusa#4164]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.13.0-39-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/ab52523c857ead17a7bd55e90ca50a20
### ERROR
<pre>
2018-05-05 18:44:02 ERROR    Thread_0 :: [77b2091] Missing time zone for network: Fox España
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added: https://github.com/pymedusa/medusa.github.io/commit/d7ab11ddc27beef1d9cc9750cab9195bb07c40d2
