### ISSUE TITLE
When editing series info language reverts to English

### ISSUE THREAD

**Issue by anonvoy** [pymedusa/Medusa#4166]
**Branch/Commit:** Commit 77b20916ab577b82112ebc624f816054788c63f2
**OS:** Linux 64-bit
**What you did:** I edit a series ("Edit show" screen)
**What happened:** The info language, which was set to French or German, reverts to English, and when I hit the "Save Changes" button, English gets saved as the new info language.
**What you expected:** The info language should stay at French, German or whatever I set it to.
**Logs:** This doesn't show up in the logs. Should be reproducible anyway.

**Comment by sharkykh** [comment]
That should be fixed on develop as `editShow` was converted to Vue.js.
I have a show with a metadata language different from English, I have no issues with it **on develop**.
