### ISSUE TITLE
double downloading episodes and whole seasons

### ISSUE THREAD

**Issue by poplolnman** [pymedusa/Medusa#4168]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: master
**OS: windows 10
**What you did: this is in reference to a continuance of this previous issue: https://github.com/pymedusa/Medusa/issues/4105 and i added several new shows.
**What happened: basically episodes are getting downloaded twice or more.
**What you expected: shows to only be downloaded once.
**Logs:**
```
[application2.log](https://github.com/pymedusa/Medusa/files/1978449/application2.log)
[application.log](https://github.com/pymedusa/Medusa/files/1978452/application.log)
```

**Comment by p0psicles** [comment]
I think I need logs that go further back.
Do you have any where a show update/refresh is in it?

**Comment by p0psicles** [comment]
also can you point out which show / episodes where redownload? And do you maybe know what the previous status was? downloaded or archived?

**Comment by p0psicles** [comment]
Btw, we're working on fixing `this` issue. But it would still be nice if we can confirm that our fix will also fix your issue.

**Comment by poplolnman** [comment]
Here are more logs over the last day when it kept on download videos over and over again:

[application.log](https://github.com/pymedusa/Medusa/files/1981914/application.log)
[application4.log](https://github.com/pymedusa/Medusa/files/1981924/application4.log)
[application5.log](https://github.com/pymedusa/Medusa/files/1981925/application5.log)
[application2.log](https://github.com/pymedusa/Medusa/files/1981926/application2.log)
[application3.log](https://github.com/pymedusa/Medusa/files/1981927/application3.log)

two examples of such shows are Spartacus and the handmaids tale. what happened was that i added them as new shows with all episodes as wanted and then they did their searches and double added. Im not sure if this matters but when i add the shows initially i get a notification stating that medusa is unable to add them , then a split second later it states that it has added.

your post doesnt link the fix and how would i go about downloading the required files to help test it?

I also have several other issues. one of which is that even though the default option is to separate by season folder and that everytime i check to make sure that option is used, it is; all of the video files stay in the same folder in instead of being divided. also at least once a week the medusa post processor stops working and i have to clear everthing out of the folder in order for it to start working again...

**Comment by medariox** [comment]
If you add the shows as WANTED Medusa will try to replace all the files with different/proper versions of the episodes. That's the whole point of WANTED. If you don't want to replace these episodes you need to choose IGNORED, SKIPPED or ARCHIVED as initial instead.

**Comment by p0psicles** [comment]
This will be fixed in master coming days. Little bit patience pls.

**Comment by poplolnman** [comment]
@medariox maybe im reading wrong(english isnt my native language), but i had no initial files and so it shouldnt have double downloaded or are you saying that it will basically do that even if i have no initial files and should just avoid the WANTED option anyways?

@p0psicles sorry wasnt trying to push, was just wondering what was happening.

**Comment by medariox** [comment]
@poplolnman Of course it will try to download the files... `WANTED` means you want Medusa to automatically download the files. That's all that `WANTED` does. You should NOT add the new shows as `WANTED` if you don't wish to download the episodes!

**Comment by poplolnman** [comment]
@medariox  but i do want to download previous episodes. the problem is that when it searches for those releases, it will download the episodes once from a provider and then a short while later it will download the same releases from another provider. the files are not upgrades either and i have a data cap and this repeated downloading really eats at my limit.

**Comment by medariox** [comment]
Should be fixed with: https://github.com/pymedusa/Medusa/pull/4311
