### ISSUE TITLE
When adding a new show into the Medusa database even if the option is checked to use Season folders after adding the show it becomes unchecked. 

### ISSUE THREAD

**Issue by 1sourCream** [pymedusa/Medusa#4170]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**master
**OS:**unRAID 6.5.1 using linuxserver/medusa
**What you did:** Added a new or existing show into Medusa's database
**What happened:**When adding a new show to the database even if the group season's folder option is checked after you add the show it becomes unchecked. Resulting in the show not using Season folders. Started a week or so ago just found out today.
**What you expected:**
**Logs:**
```
PASTE LOGS HERE
```

**Comment by p0psicles** [comment]
@sharkykh can you look into this. I can confirm, i experienced something similar

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/4172
