### ISSUE TITLE
Error for post processing Lost in Space

### ISSUE THREAD

**Issue by angarod** [pymedusa/Medusa#4180]
```
2018-05-10 16:01:18 WARNING  POSTPROCESSOR :: [77b2091] Processing failed for /home/**********/rtorrent/download/Lost.in.Space.2018.S01.MULTi.1080p.NF.WEB-DL.DDP5.1.x264-ARK01/Lost.in.Space.2018.S01E06.MULTi.1080p.NF.WEB-DL.DDP5.1.x264-ARK01.mkv: This show isn't in your list, you need to add it before post-processing an episode
```
However i do have the show in my list.
Downloaded on yggtorrent.

**Comment by p0psicles** [comment]
It provably sees the show found with the year in it. Youll have to add a scene exception where the year is included

**Comment by angarod** [comment]
Fixed with Lost.in.Space.2018 as an exception. Thank you !

**Comment by sharkykh** [comment]
@angarod 
You shouldn't need to add a scene exception. Did you add the new show? There's also the one from 1965, that has no year in the title.

**Comment by angarod** [comment]
I have already added the new show released this year.

**Comment by sharkykh** [comment]
Sorry, my mistake!

**Comment by angarod** [comment]
I'm french maybe Medusa is looking for "Perdus dans l'espace (2018)" for this show ?

**Comment by angarod** [comment]
tvdb

**Comment by angarod** [comment]
I have specific word for my entire collection for required, ignored and preferred name. May it impact post processing ?

**Comment by sharkykh** [comment]
Those should only affect selecting a search result to snatch.

**Comment by medariox** [comment]
If the show name is in french, it will use the french name to search and also post-process. Is that the case?

**Comment by angarod** [comment]
yes it is
