### ISSUE TITLE
Nebulance displays wrong file size in manual search

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#4181]
Medusa Info: | Branch: master                 Commit: 77b20916ab577b82112ebc624f816054788c63f2                 Version: v0.2.2                 Database: 44.9
-- | --
Python Version: | 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2k  26 Jan 2017
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

Nebulance displays wrong file size in manual search
![image](https://user-images.githubusercontent.com/4103090/39878424-9c91bbaa-5478-11e8-80cd-b2478d80e631.png)

Actual Nebulance result
![image](https://user-images.githubusercontent.com/4103090/39878505-d8b3ec7a-5478-11e8-86d3-cdde85f53cb7.png)

**Comment by duramato** [comment]
The parsing needs to be changed, I'll see if I can fix it.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/4203
