### ISSUE TITLE
TVDBv2 Unauthorized - bad api key

### ISSUE THREAD

**Issue by deadc0de6** [pymedusa/Medusa#4183]
**Branch/Commit:** Commit: 77b20916ab577b82112ebc624f816054788c63f2
**OS:** Linux

I'm getting plenty of warning logs similar to the line below. Not sure if/where I can add an API key, or if it's possible to use another provider. Any help would be appreciated.

**Logs:**
```
2018-05-11 03:03:26 WARNING  SHOWUPDATER :: [77b2091] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Room 104. Cause: Authentication failed, possible bad api key. reason: HTTPError
401 Client Error: Unauthorized for url: https://api.thetvdb.com/updated/query?fromTime=1525914179 (401)
```

**Comment by sharkykh** [comment]
1. You shoulsn't need to add an API key, it is built into Medusa.
2. Other indexers - Medusa supports TVDB, TMDB and TvMaze. You can add shows from any indexer, just keep in mind that if you want to switch indexers, you have to remove the show then re-add it.
3. The warning doesn't give us much info to work with. If you could provide debug logs of that issue that *might* be helpful.
Are you behind a proxy of some kind, maybe?

**Comment by deadc0de6** [comment]
ok, thanks for the info. I added it with TvMaze what seemed to have fixed the issue. I might be somehow blocked on TVDBv2 I guess.
