### ISSUE TITLE
Subtitle management only to some trackers

### ISSUE THREAD

**Issue by DarkSupremo** [pymedusa/Medusa#4184]
Is there an way to have the subtitle management only to some trackers?

I have configured some local trackers (Brazillian) that already include subtitle and so i don't need to look for subtitles there, but that trackers is really bad on searching for old episodes, so i would use an international tracker to do so.

But for that tracker i would need an way to gather subtitles or at least give it an different label on torrent or something like that, any idea how can i do that?

**Comment by sharkykh** [comment]
Subtitles are not related to the episode search. Subtitles are downloaded for each episode video file individually. There's no link between search providers and subtitles.
* If that Brazilian provider includes the subtitles as a file next to the video, you may be able to set up the post-processor to move the subtitle file with the episode video file.
Check the Post-Processing Settings - Enable `Delete associated files` and make sure to list the file extensions you want to move with the video file in `Keep associated file extensions`.
* If the subtitles are embedded in the video file (`.mkv` for example), the best thing you can do is tell Medusa to *not* ignore embedded subtitles.
Check the Subtitles Settings for the `Ignore Embedded Subtitles` option.
* If the subtitles are hard-coded into the video, there's nothing you can do.

I could be wrong, of course. If anyone has another idea, feel free to correct me.

**Comment by sharkykh** [comment]
You can try the `Run External Scripts` option in the Post Processing settings

**Comment by DarkSupremo** [comment]
I used nzbToMedia to call medusa post-process and so far working fine..
