### ISSUE TITLE
usenet-crawler search categories failing to save

### ISSUE THREAD

**Issue by kamiller42** [pymedusa/Medusa#4185]
1. Go to Configure Custom Newznab Providers
2. Update categories.
3. Select 5030, 5040, 5050.
4. Click Save.
5. Navigate back to Configure Custom Newznab Providers and select usenet-crawler.
6. Observe categories chosen were not saved.

I also created a new provider profile called "usenetcrawler" with exact same settings as usenet-crawler. Selecting same categories results in 5030 and 5040 saved but not 5050.

Add categories in config.ini is futile as they are erased when application shuts down or settings saved. Shutting down, editing, and starting retains settings. The categories even appear in the web interface.

No warnings or errors appear in log.

**Comment by p0psicles** [comment]
Can you try develop branch?

**Comment by medariox** [comment]
This has been reported so many times already. It is fixed in devlop and will be available with the next release. https://github.com/pymedusa/Medusa/pull/4073
