### ISSUE TITLE
Invalid season numbers

### ISSUE THREAD

**Issue by FangsMcWolf** [pymedusa/Medusa#4192]
Added show "Blindspot" which is currently in it's third season, yet I'm seeing various season numbers up to season 19.  Only seems to be happening with this one entry (others are fine),

**Comment by sharkykh** [comment]
On the show page, click Force Full Update.

**Comment by FangsMcWolf** [comment]
Still showing the invalid seasons.

**Comment by FangsMcWolf** [comment]
Ignore.  I just deleted and then re-added the show, it's cleared up now.
