### ISSUE TITLE
[Feature Request] Add tracker zooqle.com

### ISSUE THREAD

**Issue by egibar** [pymedusa/Medusa#4198]
since kickasstorrents and others are going down, I found this tracker, that is simmilar to it. It has millions of torrents, and I think that could be awesome to have it.
Also since newpct is down to, and rename as tvsinpagar.com, I was wondering if there is more in spanish.

I am a last year computer science student, and I know python, if you wish I will be charmed to try to help you.

**Comment by medariox** [comment]
Zooqle is already available as torrent provider. 😉 Regarding newpct/tvsinpagar/etc. it makes little sense to add a provider that actively tries to break our parser every time we release a new version. If there are any Spanish alternatives that are more suitable let us know, we will try to add them ASAP. If you want to help with development, you can either send an email to me or @p0psicles and we will add you to our Slack channel (make sure to include a valid email address).

**Comment by egibar** [comment]
there is one called elitetorrent.biz. For the slack channel, how can I know your email?

**Comment by medariox** [comment]
You can PM me on [reddit](https://www.reddit.com/user/dontdoit19/) or join `#pymedusa` on freenode.
