### ISSUE TITLE
Manual search : download button not clickable after a force search

### ISSUE THREAD

**Issue by Kilay** [pymedusa/Medusa#4207]
**Branch/Commit:** master / 77b20916ab577b82112ebc624f816054788c63f2
**OS:** Synology DSM 6
**What you did:** Force manual search for a show. 
**What happened:** The download button is not clickable, probably because of a "app-link" node instead of "a" node (see below screenshot.
If I refresh the page without force searching, the button is clickable.

![image](https://user-images.githubusercontent.com/314557/40114403-1d4b93fe-590d-11e8-8242-6d93a92a4b92.png)

**Comment by medariox** [comment]
This has been fixed in develop for some time now. It will be released with the upcoming release.

**Comment by Kilay** [comment]
Thank you ! And thank you for your hard work !
