### ISSUE TITLE
Cannot change episode status

### ISSUE THREAD

**Issue by johnvick** [pymedusa/Medusa#4209]
Branch: masterCommit: 4b9c599a461dae200a1cdd4d53ede28619c3151fVersion: v0.2.3Database: 44.9
--
Python Version: | 2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]
SSL Version: | OpenSSL 1.0.1t 3 May 2016
OS: | Linux-4.9.61+-armv7l-with-debian-8.10
Locale: | en_GB.UTF-8

Since the most recent update I can no longer change episode status to archived - I get "Error - invalid status". Nothing in the logs that looks relevant.

**Comment by p0psicles** [comment]
jip, hotfix incoming.
tnx for reporting

**Comment by medariox** [comment]
This is now fixed, please update.

**Comment by johnvick** [comment]
Thanks for sorting this out so quickly.

**Comment by p0psicles** [comment]
If you notice anything else bugging related to statussen or quality settings. Pls let us know
