### ISSUE TITLE
Jackett releases repeated

### ISSUE THREAD

**Issue by snamds** [pymedusa/Medusa#4212]
Jackett releases keep getting repeated when you go to the manual search results.

As far as I've seen, cache releases use url as "primary key" to detect repeats. As Jackett URLs are always different because of the crypt system, they get repeated.

https://github.com/Jackett/Jackett/issues/3118

**Comment by p0psicles** [comment]
@medariox I think we should do something about this.
And imo there are two directions for this.

1. Change the cache db, introduce a key field, and remove the constraint from url field.
2. Overwrite the max lifetime on cache items, per provider. And enforce this, when querying results from such a provider.

**Comment by duramato** [comment]
I'm more inclined to the 1st solution, this new field could be populated with said GUID for jackett and for normal torrents and usenet it can remain the download url which has been working fine.

**Comment by p0psicles** [comment]
Yeah I even think the 1ste solution is less work.
