### ISSUE TITLE
[APP SUBMITTED]: OperationalError: database or disk is full

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#4222]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.14.13-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
**Link to Log**: https://gist.github.com/64be6c09e2d5455793c33ad496d35a2f
### ERROR
<pre>
2018-05-20 03:10:47 ERROR    SHOWQUEUE-SEASON-UPDATE :: [1a8dc66] DB error: error b'database or disk is full'
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 274, in action
    self.connection.commit()
OperationalError: database or disk is full
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OmgImAlexis** [comment]
@p0psicles this type of message should really be converted to an actionable notification so the user knows there's an issue instead of needing to read logs.

**Comment by p0psicles** [comment]
But its already an error. Meaning something went wrong that directly obstructs the funtioning of the application.

And because its an error, its visible to the user.
