### ISSUE TITLE
Add Shows Button No Working

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/Medusa#4229]
Make that "Not Working"... Two different machines having this issue. 

Medusa Info: | Branch: master                     Commit: 212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f                     Version: 0.2.4                     Database: 44.9
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Windows-7-6.1.7601-SP1
Locale: | en_GB.cp1252

**What you did: Click on "ADD SHOW Or add existing shows
**What happened: Nothing!
**What you expected: Expected to add shows
**Logs: Debug enabled - No Errors Shown
```

**Comment by medariox** [comment]
What browser are you using? Try refreshing with Ctrl + F5

**Comment by DrakeJones** [comment]
Just noticed the problem yesterday, by the way.  Using Firefox ESR 52.5.3 (32-bit).  Flushing browser cache not doing it.  Two independent machines, same issue...  Even reinstalled and configured fresh from windows executable.

**Comment by sharkykh** [comment]
@DrakeJones 
1. We can't reliably support older versions of browsers. Any reason you can't update?
2. Try opening the developer console on the browser, maybe there are errors?

**Comment by p0psicles** [comment]
Just use latest versions of chrome, ff or edge. Problem solved

**Comment by DrakeJones** [comment]
Tail wags dog?  I really appreciate what you’ve done with the project, but I like my current bowser and Medusa worked fine until a few days ago.  Firefox ESR branch is supported by MIT ( Massachusetts Institute of Technology), is current, secure, and up-to-date.  If it’s good enough for them, it’s good enough for me. I hate to do it, but I’ll think put Sickrage back in my line-up.

**Comment by DrakeJones** [comment]
I was afraid you’d tell me to try a different browser…  Can I just stick with the Medusa version that worked?

 

 

Here is the dev console image of the issue/error: https://imgur.com/a/3CCFLUE

 

I like my browser and plan to stick with it.  The version of FF that I’m using is the long-term support version supported by MIT – not Mozilla.  It is secure and up-to-date.

**Comment by sharkykh** [comment]
@OmgImAlexis Any ideas why `vue-frisbee` isn't available?

**Comment by p0psicles** [comment]
You posted the error as screenshot. But its not readable

**Comment by sharkykh** [comment]
@p0psicles It is on desktop... here you go:
![image](https://user-images.githubusercontent.com/10238474/40315164-5021ff4c-5d23-11e8-96e3-c2c4b2c04cac.png)

> The version of FF that I’m using is the long-term support version supported by MIT – not Mozilla.  It is secure and up-to-date.

@DrakeJones It's not truly up-to-date. You're using version 52.5.3, while 52.8.0 is the latest.

**Comment by DrakeJones** [comment]
Thank you very, very much for revisiting the issue.

**Comment by DrakeJones** [comment]
Maybe related - trying editing preexisting shows via http://localhost:8081/home/editShow?indexername=tvdb&seriesid=XXXXX seems to be defaulting to global settings, not show-specific settings...  I hope the frisbee update does it.  This is really bumming me out.

**Comment by sharkykh** [comment]
@DrakeJones
Frisbee update won't affect `editShow`.
Can you check the dev console on that page too? (Already uninstalled FF...)

**Comment by sharkykh** [comment]
@DrakeJones 
1. `addShow`: Should now be fixed for you in develop (or you can wait for the next version).
2. `editShow`: I wasn't able to reproduce the issue.
It is possible your issue is related to #4248, if you get an empty allowed/preferred quality lists (for example) on some shows.
