### ISSUE TITLE
[API v1] sb.searchindexers does not return anything

### ISSUE THREAD

**Issue by MGaetan89** [pymedusa/Medusa#4246]
Hi guys,

I received a bug report for my Android app (https://github.com/MGaetan89/ShowsRage/issues/149) related to the search feature in the API v1.
When using this entry point, Medusa (version 0.2.4) does not return anything, while the web UI returns some shows for the same query.
Here is a sample request that returns nothing for me from the API (in the API builder), and a lot of shows on the web UI:
`/api/v1/{api_key}/?cmd=sb.searchindexers&name=how`

Could you have a look to see what is going on?
I know that you have an API v2 now, and I am planning to include it at some point. But until then, I will need v1 to work as expected ;)

**Comment by sharkykh** [comment]
@MGaetan89 We released v0.2.5, should be good now.

**Comment by MGaetan89** [comment]
It's working again on my side.
Thanks for your work :)
