### ISSUE TITLE
Not finding episodes that are available. 

### ISSUE THREAD

**Issue by chumleyex** [pymedusa/Medusa#4250]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS: Windows 10
**What you did: this is a continuation of Closed #4158.. I tried to search for a specific episode that is on a site that jacket is searching. Medusa doesn't download the file. 
[application.log.zip](https://github.com/pymedusa/Medusa/files/2040722/application.log.zip)

High Maintenance (2016)

S02E10	Wanted	Steve	3/23/2018, 10:00 PM

Jump into the daily routines of a diverse group of New Yorkers and how they light things up. "The Guy" is a nameless pot deliveryman whose client base includes an eccentric group of characters with neuroses as diverse as the city.
Quality:	HD1080p
Originally Airs:	Friday 11:00 PM on HBO
Show Status:	Continuing
Default EP Status:	Wanted
Location:	E:\Video\TV\High Maintenance (2016)
Required Words:	x265
Ignored Words:	german, french, core2hd, dutch, swedish, reenc, MrLss, dubbed
Undesired Words:	internal, xvid
Size:	2.17 GB

	Line 30918: 2018-05-25 14:41:25 INFO     SEARCHQUEUE-MANUAL-314324 :: [212cd1c] Beginning manual search for: High Maintenance (2016) - S02E10 - Steve
	Line 31015: 2018-05-25 14:41:37 INFO     SEARCHQUEUE-MANUAL-314324 :: [212cd1c] Unable to find manual results for: High Maintenance (2016) - S02E10 - Steve
	Line 31935: 2018-05-25 14:43:04 DEBUG    SEARCHQUEUE-MANUAL-314324 :: [212cd1c] 314324: Formatting pattern: %SN - S%0SE10 - %EN -> High Maintenance (2016) - S02E10 - Steve
	Line 31937: 2018-05-25 14:43:04 INFO     SEARCHQUEUE-MANUAL-314324 :: [212cd1c] Beginning manual search for: High Maintenance (2016) - S02E10 - Steve
	Line 33916: 2018-05-25 14:43:16 DEBUG    SEARCHQUEUE-MANUAL-314324 :: [212cd1c] 314324: Formatting pattern: %SN - S%0SE10 - %EN -> High Maintenance (2016) - S02E10 - Steve
	Line 33918: 2018-05-25 14:43:16 INFO     SEARCHQUEUE-MANUAL-314324 :: [212cd1c] Unable to find manual results for: High Maintenance (2016) - S02E10 - Steve
	Line 42078: 2018-05-25 14:48:16 DEBUG    SEARCHQUEUE-FORCED-314324 :: [212cd1c] 314324: Formatting pattern: %SN - S%0SE10 - %EN -> High Maintenance (2016) - S02E10 - Steve
	Line 42079: 2018-05-25 14:48:16 INFO     SEARCHQUEUE-FORCED-314324 :: [212cd1c] Beginning forced search for: High Maintenance (2016) - S02E10 - Steve
	Line 42197: 2018-05-25 14:48:27 DEBUG    SEARCHQUEUE-FORCED-314324 :: [212cd1c] 314324: Formatting pattern: %SN - S%0SE10 - %EN -> High Maintenance (2016) - S02E10 - Steve
	Line 42198: 2018-05-25 14:48:27 INFO     SEARCHQUEUE-FORCED-314324 :: [212cd1c] Unable to find forced results for: High Maintenance (2016) - S02E10 - Steve
	
	
Link to MagnetDL where it finds the episode. 
http://www.magnetdl.com/file/3366470/high.maintenance.s02e10.1080p.hevc.x265-megusta/
**Logs: are attached
```
PASTE LOGS HERE
```

**Comment by medariox** [comment]
Are you able to find the episode with a manual search? Also, post the corresponding debug logs of the manual search.
