### ISSUE TITLE
AttributeError: 'WebRoot' object has no attribute 'home' after adding existing show

### ISSUE THREAD

**Issue by Aerya** [pymedusa/Medusa#4256]
Hello,

Error while adding existing shows **only**.

**Branch/Commit:**
Medusa Info: | Branch: master                     Commit: 212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f                     Version: v0.2.4                     Database: 44.9
Python Version: | 2.7.14 (default, Dec 14 2017, 15:51:29)  [GCC 6.4.0]
SSL Version: | LibreSSL 2.6.3
OS: | Linux-4.15.0-20-generic-x86_64-with

**Configuration**
Docker Medusa : [Linuxserver.io](https://hub.docker.com/r/linuxserver/medusa/) 
Proxy : [jwlider](https://hub.docker.com/r/jwilder/nginx-proxy/)
SSL : [jrcs](https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/)

**Running Medusa :**
`docker run -d \
--name=medusa \
--restart always \
-p 8088:8081/tcp \
-v /home/pierre/docker/medusa:/config \
-v /mnt:/downloads \
-v /mnt:/tv \
-e TZ=Europe/Paris \
-e PGID=1001 -e PUID=1001  \
-e "VIRTUAL_HOST=medusa.yy.xx" \
-e "LETSENCRYPT_HOST=medusa.yy.xx" \
-e "LETSENCRYPT_EMAIL=ssl@yy.xx" \
  linuxserver/medusa`

**What you did:**
Adding some existing shows (or only one at a time), I got this error after choosing the show (clicking Add Show).
I'm using Linux at home, tried with Firefox, Vivaldi, Chromium, Brave, even TorBrowser... using domain.tld and/or direct IP.
`web_root = ""`

**What happened:**
![image](https://user-images.githubusercontent.com/26864765/40583581-20a5ad40-6192-11e8-8768-d971c59d2ff7.png)

**What you expected:**
Everythings ok while adding a new show. No problem using Sickrage.

**Logs:**
```
2018-05-27 09:28:28 DEBUG    TORNADO :: [212cd1c] Failed doing web ui get request u'home': Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 249, in get
    method = getattr(self, route)
AttributeError: 'WebRoot' object has no attribute 'home'
```

**Comment by OmgImAlexis** [comment]
You have a double slash. Remove the second slash in the URL.

@sharkykh seems the redirect is adding another `/` to the end even if it has one.

**Comment by Aerya** [comment]
Yeah, of course it works when I manually remove the /. But I still can't add existing shows.

**Comment by sharkykh** [comment]
@OmgImAlexis I think it was reported on Slack.

#4235 partially fixes the issue. As I said I'm already working on Vueify-ing newShow, but it's going to take a while. In the meantime maybe we should go back to using native form submission (and not `vue-submit-form`)?

**Comment by Aerya** [comment]
I posted it on IRC on yesterday, guess it was linked to your Slask?

**Comment by labrys** [comment]
IRC is linked to the Medusa Slack

**Comment by sharkykh** [comment]
Partially fixed on `develop`. #4267 will fix all the redirection issues.
