### ISSUE TITLE
Double "Save Changes" buttons - is a bit redundant (& confusing... )

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#4284]
All configuration screens have TWO "save changes" buttons at the bottom one right near the other. 
I don't see the point here, this is more confusing than helpful, one is good enough... 

 If you want to improve/easy UI, delete one, of better yet - move all  the copies to the top of each page. At lease this can save us scrolling to the bottom when some settings on the top part are being changed... :) 

Thanks

Rafi

**Comment by OmgImAlexis** [comment]
We're already planning on doing this.
