### ISSUE TITLE
Error loading IMDb info: Title not found. tt2661044 is a redirection imdb id

### ISSUE THREAD

**Issue by chrisric** [pymedusa/Medusa#4285]
**Branch/Commit: Master/0.23, latest version as of 20180517
**OS: QNAP (Linux-4.2.8-x86_64-with-glibc2.2.5)
**What you did: Nothing that I know of...
**What happened: The "Show Update" process is causing a warning for each show in the update list. The warnings have been happening for a fews weeks I think.
**What you expected: No warnings.
**Logs:
`2018-05-30 09:01:30 WARNING  SHOWQUEUE-SEASON-UPDATE :: [212cd1c] 268592: Error loading IMDb info: Title not found. tt2661044 is a redirection imdb id`

I have attached a debug log of one show, all the others are the same output but if you want the complete log just let me know.

Thanks.

[warning.log](https://github.com/pymedusa/Medusa/files/2051909/warning.log)

**Comment by OmgImAlexis** [comment]
Duplicate: https://github.com/pymedusa/Medusa/issues/4281
