### ISSUE TITLE
Per torrent Undesired words search setting

### ISSUE THREAD

**Issue by Anatharias** [pymedusa/Medusa#4286]
Hello,

I'd like to request a new feature where search terms can be fully overridden, per torrent.
There has been some improvement to the UI, but that still doesn't filter properly.

At the moment, If I have the word **French** in my **Undesired Words** list and **VOSTFR** in my **Preferred words** list, then a French dubbed TV show will be ignored, and a VOSTFR subbed version will be preferred over other releases.

But if for a given TV show, I would actually want the French dubbing or multi: I can't
The global **Undesired Words** setting cannot be overridden per torrent.

The **Required Words** setting doesn't properly override the **Undesired Words** from the global search settings.

I just had the unfortunate download of 35 useless GB because the filter didn't work properly.

This is the show's settings, it picked a VOSTFR over a FRENCH show (both were available, same quality).
Required Words:	french
Ignored Words:	german, ger, core2hd, dutch, swedish, renew, ita, italian, MrLss, ru, russian
Preferred Words:	VOSTFR, multi, fastsub
Undesired Words:	french

here is the log:

2018-05-29 18:33:53 INFO     SEARCHQUEUE-BACKLOG-263365 :: [xxxxxx] :: [212cd1c] Quality of xxxxxx.S02.FRENCH.1080p.WEB-DL.H264-LiBERTY is 1080p WEB-DL
2018-05-29 18:33:53 INFO     SEARCHQUEUE-BACKLOG-263365 :: [xxxxxx] :: [212cd1c] Preferring xxxxxx.S02.(VOSTFR.1080p.WEB-DL.DD5.1.H.264-Visual) (preferred words)
2018-05-29 18:33:53 INFO     SEARCHQUEUE-BACKLOG-263365 :: [xxxxxx] :: [212cd1c] Quality of xxxxxx.S02.(VOSTFR.1080p.WEB-DL.DD5.1.H.264-Visual) is 1080p WEB-DL

Thanks for your help

**Comment by Anatharias** [comment]
Hey,
No one has that kind of issue with their Medusa setup?
Or maybe I'm misinterpreting the way settings works.

Any idea on how to improve above behaviour?
thanks

**Comment by rafi-d** [comment]
+1 
I think all FOUR words' filters - Ignore, Undesired, Preferred, and Required should be available also per show (not just two of them). When/if this is so, every couple of lists (global+local) will be added together. There is still a question of how to deal with conflicting lists, but this is more of a user-problem, not Medusa...

**Comment by Danelem** [comment]
I agree, it's a problem when people want to have different profile: one in the original language, and one for the dubbed version.

Could we have the option in the show settings "overwrite the global required/ignored words"?

**Comment by MagicMicky** [comment]
Hi
I'd also like to see this feature happen.

I'm french, I watch a few french TV shows when they are actually french shows (ie: "Le Bureau des légendes"), but for most of the time I watch us shows and dislike French dubbing.
So what I'd like to do is to set as globally ignored "French,Truefrench", to avoid downloading french dubbed tv shows, but to be able to override this list of ignored word, for the few specific French TV shows. This is actually the way sickrage _(sickchill)_ propose you to do it (just made the move today), and they explained:

> Ignored Words - note: this option overrides the globally ignored words!

I think having the option to override the globally ignored word list would be great and allow me to keep enjoy my French TV Shows with Medusa! For now, I'm thinking to keep sickrage for my french tv shows only.

**Comment by p0psicles** [comment]
Has been implemented in current develop branch

**Comment by rafi-d** [comment]
@p0psicles : I hope this is backward compatible (I mean optional) , since I am using now combined list(s) - per show plus  global.

**Comment by p0psicles** [comment]
Yes it is
