### ISSUE TITLE
Enhancement suggestion for "Add New Show" - Option to create new folder

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#4289]
Hi,
I have noticed that there is no way to create a new folder/root-folder for new shows. I think that  adding "create new folder" button for new shows (mainly for first time users)  - will be helpful.

BTW, I've heard from a new user, that there are issue with detecting his NAS devices for the using his root folder. I don't have more details, though... 

Thanks

Rafi

**Comment by OmgImAlexis** [comment]
Not sure if this is really needed as we expect users should at least know how to create a directory if they're able to install and use Medusa.

**Comment by rafi-d** [comment]
The point is - ease of use, and not know-how. It is useful to have this ability internally, and not make the user go elsewhere to so the same, and then need to refresh Medusa displayed paths. I guess its a matter of opinion...
