### ISSUE TITLE
TVDBv2 connectivity issues connectivity issues

### ISSUE THREAD

**Issue by kantjer** [pymedusa/Medusa#4290]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** master/212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f
**OS:** DSM 6.1.7-15284
**What you did:** Medusa is running daily show updater
**What happened:** Log is showing TVDBv2 connectivity issues connectivity issues for all shows. This is happening daily since a few days now 
**What you expected:** No errors
**Logs:**

Below log is just an example of one show, I have similar errors for every show in my library
```
2018-05-31 10:04:03 WARNING  SHOWUPDATER :: [212cd1c] Problem running show_updater, Indexer TVDBv2 seems to be having connectivity issues while trying to look for show updates on show: Safe
2018-05-31 10:04:02 WARNING  SHOWUPDATER :: [212cd1c] could not connect to TheTvdb.com, with reason 'Error connecting to Tvdb api. Caused by: HTTPError
503 Server Error: Service Unavailable for url: https://tvdb2.plex.tv/updated/query?fromTime=1527494449'
```

**Comment by p0psicles** [comment]
Yeah and a while ago i noticed the plex fallback also isnt as reliable anymore.

**Comment by OmgImAlexis** [comment]
Waiting on https://gitlab.thetvdb.com/site/thetvdb_api/issues/35

**Comment by bobbysteel** [comment]
Can I suggest we demote the warning to INFO instead? It's super annoying to have hundreds of notifications in the top right of my screen...
