### ISSUE TITLE
Embedded preferred subtitles are shown as missed subtitels

### ISSUE THREAD

**Issue by BaukeZwart** [pymedusa/Medusa#4303]
[Edited by @sharkykh]

**Feature request:**
Add an option for "Episodes without **some** wanted subtitles" on `manage/subtitleMissed`.
Meaning - list all episodes that don't have at least one of the wanted subtitle languages (assuming more than one language is wanted). If at least one wanted subtitle is present, don't list the episode.

Original post follows...
-----

**Branch/Commit:** master/212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f
**OS:** DSM 6.1.7-15284
**What you did:** Open Missed subtitel Management
**What happened:** TV Episodes with embedded preferred subtitles are shown as missed subtitels
**What you expected:** Not to show episodes with embedded preferred subtitles
Logs: 

![image](https://i.imgur.com/zSWTBSV.jpg)

![image](https://i.imgur.com/rDWaijs.jpg)

**Comment by fernandog** [comment]
If embedded subtitles doesn't have language code, there is no way to know if is preferred

**Comment by kantjer** [comment]
Embedded subs in MKV files can have language code as my screenshot proves. subs are clearly English

**Comment by sharkykh** [comment]
Please make sure you **didn't** enable the following config option:
**Gear Icon > Subtitles Settings > Embedded Subtitles**
>  Ignore subtitles embedded inside video file?

**Comment by kantjer** [comment]
I have Ignore subtitles embedded inside video file disabled_

**Comment by sharkykh** [comment]
Wait, so the issue is, it detected the embedded subtitles (you see the correct flag on the show's page, but the Missed Subtitles page lists those episodes anyway?

**Comment by kantjer** [comment]
Correct, that's the issue

**Comment by sharkykh** [comment]
I can't even get Medusa to recognize the embedded subtitles.
Are you using the "postpone post-processing if no subs" option by any chance?

**Comment by fernandog** [comment]
From the SS it's weird: Missing subtitles: episodes without English (undefined). 

Undefined?!

**Comment by sharkykh** [comment]
> From the SS it's weird: Missing subtitles: episodes without English (undefined).

Undefined?!

I saw that, so JS may be related. But still, this issue might point to a bigger issue, because I tried to post-process an mkv with an English language track, and also tried to rescan the show with the same file in the show folder, neither of these methods updated the `subtitles` field for the episode to `eng`.

**Comment by medariox** [comment]
@sharkykh 
Are you sure the subtitle isn't actually tagged with language `und`?

@kantjer 
Just enable multi-subs in the subtitle settings to fix the issue.

**Comment by sharkykh** [comment]
@medariox 
I checked the database directly. It didn't change the value.
I also could only find code for extracting the embedded subtitle track information in the postponed feature:
https://github.com/pymedusa/Medusa/blob/212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f/medusa/process_tv.py#L554-L557

**Comment by kantjer** [comment]
@medariox Thanks for the explanation.

Enabling multi-subs only makes the issue much bigger in my case because most embedded subs don't have a language code are are added to the missing subs list when enabling it.

I will either remove the language code from the mkv files or just ignore them.

**Comment by sharkykh** [comment]
@kantjer Can you please check the browser developer console for errors on that page?

**Comment by kantjer** [comment]
@sharkykh not sure if this is what you are looking for:

```
Loading local Vue since we found a window.app
vue.js:8542 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.js:8553 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
core.js?13786:186 Notifications library loaded.
```

**Comment by kantjer** [comment]
I’m starting to get the feeling that when selecting multiple languages the “All” in Missed Subtitle Management is working opposite as to what I expect.

Even with the Download only one language option set missed Subs management with all filter shows all episode that don’t have Subs in all set Languages, In my case Eng and Und.

I would expect All with only DL one language setting active to show only episodes that don’t have subs in any of the two set languages.

**Comment by sharkykh** [comment]
@kantjer 
That, but I'm not seeing any errors.
Does the title still have `(undefined)` in it instead of the language code?
![image](https://user-images.githubusercontent.com/10238474/41021943-d80c0d86-6970-11e8-9c21-d510a697b2cd.png)

**Comment by kantjer** [comment]
@sharkykh I now have the following filter options in Subs Management

Episodes without all wanted subtitles.
Episodes without Undetermined (und) subtitles.
Episodes without English (en) subtitles.

That looks like it's working as intended (only for me no as expected)

I would like to see:
Episodes without any wanted subtitles.

That would give me the one page overview of missing subtitles I'm looking for

So this now turns into a feature request I guess.
