### ISSUE TITLE
No NZB/Torrent providers found or enabled

### ISSUE THREAD

**Issue by Thilas** [pymedusa/Medusa#4315]
**Branch/Commit:** Master
**OS:** Linux
**What you did:** I do not use search providers (NZB or Torrent). Instead I use an external way to get video and then call Medusa for post processing
**What happened:** Every hour/few hours, I get a warning message saying that "No NZB/Torrent providers found or enabled in the application config for daily searches"
**What you expected:** That no warnings are issued as the program is getting the releases via post processing. If they do need to have a warning, just do one. Don't have the warnings over & over.
**Logs:**
```
2018-06-07 22:28:43 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [212cd1c] No NZB/Torrent providers found or enabled in the application config for daily searches. Please check your settings
```

**Comment by sharkykh** [comment]
I don't think there's a simple option to disable daily/backlog searches,
but what you can do is increase the time between searches in Config - Search.
The two options are called: `Backlog search frequency` and `Daily search frequency`.
Setting the values to a year in minutes - `525600` - should work.

**Comment by Thilas** [comment]
I guess this is one way to go 😄
Thanks
