### ISSUE TITLE
Version 0.2.5 seems to have only minimal manual search results (vs 0.2.4)

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#4330]
Hi,
See attached two test. Same config, same providers, same shows, same episode.  Sadly - there is almost no results in 0.2.5  :(   Is there any new configuration parameter that is now related and should be set? Have you seen the same amount of results in your tests as in 0.2.4 ?  A regression?

0.2.4:
====
![024_100](https://user-images.githubusercontent.com/2458280/41204901-5cd1e5ec-6cf3-11e8-8e97-0461246712ab.png)
![024_billions](https://user-images.githubusercontent.com/2458280/41204902-5cf4249a-6cf3-11e8-9e21-f33a1f94d02a.png)

0.2.5:
====
![025_100](https://user-images.githubusercontent.com/2458280/41204903-5d1545bc-6cf3-11e8-8d3e-5f59ad6832f5.png)
![025_bilions](https://user-images.githubusercontent.com/2458280/41204904-5d35cd1e-6cf3-11e8-8daf-fa78c6bd7130.png)

![search_providers](https://user-images.githubusercontent.com/2458280/41204922-ac16271c-6cf3-11e8-86a3-b5cd63495a88.png)

**Comment by medariox** [comment]
You need to force a new search.

**Comment by sharkykh** [comment]
Yes. Provider cache was reset due to the changes in the quality system.
And as @medariox said, you need to force a new search for older results to show up.

**Comment by rafi-d** [comment]
OK, done the, and the full list is there. But... then, it now hangs in the overview  with this error:

2018-06-10 21:50:13 ERROR    Thread_3 :: [c65ca26] Could not parse episode status into a valid overview status: 3276806

Anything else need to be reseted/forced?  BTW, I think there might need to be some auto-refresh process when an upgrade requires it ...

![025_100_overview](https://user-images.githubusercontent.com/2458280/41205259-c758f392-6cf8-11e8-8fbd-656af8f1a1c3.png)

**Comment by rafi-d** [comment]
I did, but also replaced the DBs at the same time with my backups from 0.2.4. when I moved back to 0.2.5 - I did the same. It is possible tho, that the swaps were to 100% "clean"... 

The arrow points to the point where episodes 1-5 are not showing at all now . No problem to  revert back to 0.2.4 (I have full backup of)  and upgrade again if you think it's best, force check again, and see if that error appends again.

**Comment by medariox** [comment]
Try to `Force Full Update` on the show. And yes, you should use a clean, unmodified DB and let it upgrade automatically.

**Comment by rafi-d** [comment]
No change  with full update. I'll try re-upgrading tomorrow....

**Comment by rafi-d** [comment]
Sadly it fails to update. I believe this was the initial failure too, I was showing a blank page at http://localhost:8081/home/update/?pid=6092 ,  I've just ignored it then.... BTW, all the files seems to have been be updated correctly (compared to 0.2.5 zip).

https://pastebin.com/bUH2vHZP

**Comment by medariox** [comment]
There is currently no way to confirm that the upgrade went as planned. What indexer are you using? Just added that show with theTVDB and it looks fine here. If it's just that show try removing it and adding it again?

**Comment by rafi-d** [comment]
Maybe I wasn't clear. Actually I do not see any problem now, with any of the shows. All files look good, and the DB seems to be converted (size-wise). Just that the "help" page is not showing the wrong data, and there is this banner requesting to update...

**Comment by medariox** [comment]
You can't update if you have a modified Medusa version, that's normal.
Run:
```
git fetch origin
git reset --hard origin/master
```
This will reset your Medusa installation to the unmodified version. After that, you will be able to update normally (if required).

**Comment by rafi-d** [comment]
Done, thanks!
