### ISSUE TITLE
"No update needed", even when there's a new release

### ISSUE THREAD

**Issue by 3dsound** [pymedusa/Medusa#4334]
Windows 10
Branch: master
Commit: 212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f
Version: 0.2.4 (but this has been going on since forever).
I click on "Check for Updates", it redirects me to the list of shows and no message appears, I go to the log where I see "No update needed" (even when there's a needed update).
I'm on Master branch and it says "master" in General -> Advanced Settings -> GitHub. 
What I always end up doing 
https://github.com/pymedusa/Medusa/wiki/FAQ%27s-and-Fixes#i-have-problems-updating-or-my-installation-got-corrupt-what-now

These commands always update me to the next version
```
git remote add upstream https://github.com/pymedusa/Medusa.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull
```
Debug logs: https://pastebin.com/aiWtVEeN

**Comment by sharkykh** [comment]
Let's try to debug the issue in steps.
Can you please run the following commands in Medusa's directory, and post the results?

```
git status
git remote -v
git branch -a -vv
```

**Comment by 3dsound** [comment]
**git status**
```
On branch master
Your branch is up to date with 'upstream/master'.
```
**git remote -v**
```
origin	https://github.com/pymedusa/Medusa (fetch)
origin	https://github.com/pymedusa/Medusa (push)
upstream	https://github.com/pymedusa/Medusa.git (fetch)
upstream	https://github.com/pymedusa/Medusa.git (push)

```
**git branch -a -vv**
https://pastebin.com/93B9n5uB

**Comment by sharkykh** [comment]
I think the instructions on the Wiki were wrong. I'll update them.
**Make sure Medusa is shut down**, then please do the following:
```
git branch --set-upstream-to=origin/master
git remote rm upstream
git fetch --all --prune
git gc
```

Explanation, by command line number:
1. Your master branch is tracking master from remote 'upstream', which Medusa won't try to update, unless you tell it to use that remote (config option).
	This will fix it so it tracks master from remote 'origin', which is what Medusa updates by default.
2. This removes the duplicate remote that is unused (no need to two remotes with the same url)
3. This will make sure all the remote is updated, and removes old data
4. This is a simple garbage collection.

Now, run Medusa and try to update. It should work.
Please note that during the update process you will encounter a white page, this is a bug.
Don't refresh the page - just manually navigate back to the home page (`http://localhost:8081`)

**Comment by rafi-d** [comment]
>Please note that during the update process you will encounter a white page, this is a bug.
Sadly, I think I've encountered this as well, and did a refresh... :( 
https://github.com/pymedusa/Medusa/issues/4330#issuecomment-396147958

These two git commands, helped me recover, tho... 
https://github.com/pymedusa/Medusa/issues/4330#issuecomment-396221695

**Comment by 3dsound** [comment]
Solved, thank you!
