### ISSUE TITLE
comment deleted ?

### ISSUE THREAD

**Issue by David-EU** [pymedusa/Medusa#4354]
Why my comment was deleted ? I was polite, just telling you just need to have a try yourself to figure out. What is the way to not being deleted ? Can I only say things you like or so ?

**Comment by sharkykh** [comment]
To what comment are you referring? Where? On what issue?

**Comment by medariox** [comment]
Do you mean this comment? https://github.com/pymedusa/Medusa/issues/4105#issuecomment-396549946

**Comment by David-EU** [comment]
Around 1pm CET, I left a comment on a issue concerning shows added double times, sorry can't remember the exact thread... I couldn't find it back, even by searching with my name and by clearing every filters. So I expect it was deleted and I'm wondering what I did wrong ?

**Comment by medariox** [comment]
Be assured that we do not delete comments.
