### ISSUE TITLE
http://localhost:8081/config/search/ Test SABnzbd Button is dead

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/Medusa#4355]
Test NZBget and Black hole test ok, but Test SABnzbd Button is dead is dead.  Logs don't show an error. Nor does dev console view in Firefox 60.0.2 (64-bit).  Also, checked config.ini for SABnzb info...  Host and api key don't update the values in the file.  Related to windows file path issue or maybe I have a corrupted db?

**Comment by sharkykh** [comment]
Don't worry, nothing is corrupt on your end. The button isn't bound to the function that tests the connection. Will fix it in #4348

**Comment by OmgImAlexis** [comment]
Closed in https://github.com/pymedusa/Medusa/pull/4348
