### ISSUE TITLE
Update markdown2

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#4358]
Waiting on https://github.com/trentm/python-markdown2/issues/285

**Comment by OmgImAlexis** [comment]
@sharkykh thoughts on removing this lib and just switching everything to Vue for markdown? We can easily convert the `markdown.mako` file.

**Comment by sharkykh** [comment]
No objections

**Comment by OmgImAlexis** [comment]
Still an issue https://github.com/trentm/python-markdown2/issues/285#issuecomment-427651533

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/5834
