### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: V LIVE

### ISSUE THREAD

**Issue by droo88** [pymedusa/Medusa#4370]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-6-amd64-x86_64-with-debian-9.4`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@2809aa4781bdc3997d8dd4391b3635451b674501
**Link to Log**: https://gist.github.com/3b66f3dc7a704976c288ab05e24f55c5
### ERROR
<pre>
2018-06-14 12:23:39 ERROR    Thread_58 :: [2809aa4] Missing time zone for network: V LIVE
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added: https://github.com/pymedusa/medusa.github.io/commit/4a66ee0256577d3325aee6bd17871dd1faaecd44
