### ISSUE TITLE
invisible providers

### ISSUE THREAD

**Issue by poplolnman** [pymedusa/Medusa#4371]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** master/develop
**OS:** windows 10
**What you did:**updated medusa
**What happened:** the providers page now has no providers present on it
![screenshot_2](https://user-images.githubusercontent.com/12866874/41444009-2bf12adc-700e-11e8-8be0-fbf2884e8cfd.png)

**What you expected:** to have full access to my provder options
**Logs:**
```
i also updated to develop branch to see if there was a fix for it, but the problem remained the same...

**Comment by poplolnman** [comment]
@OmgImAlexis  its google chrome

Loading local Vue since we found a window.app
vue.js:8542 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.js:8553 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
(index):9638 This function need to be moved to config/providers.js but can't be as we've got scope issues currently.

https://ghostbin.com/paste/5srpp

is this what you needed?

**Comment by OmgImAlexis** [comment]
I've removed the ghost bin link since you included all your passwords for the providers in it.

**Comment by poplolnman** [comment]
thank you, big mistake on my part. was any of that helpful though?

**Comment by sharkykh** [comment]
Do you have any custom providers?

**Comment by poplolnman** [comment]
if you mean jackett, then yes.

**Comment by sharkykh** [comment]
Okay now did you, by any chance, use quotation marks `"'` in the name or something else?

**Comment by poplolnman** [comment]
no, these providers also worked fine before the latest update.

**Comment by medariox** [comment]
Check if your `config.ini` is messed up and try a different browser.

**Comment by poplolnman** [comment]
i tried opera and still had the same problem. also i checked the config.ini and everything was ok, all of the provider info was there as well.

**Comment by medariox** [comment]
Does it work with a fresh `config.ini`?

**Comment by poplolnman** [comment]
@medariox when i use a fresh config.ini, the providers show up.

**Comment by p0psicles** [comment]
Then you should manually move over the providers to see which one is causing the issue
