### ISSUE TITLE
service beated up

### ISSUE THREAD

**Issue by oasisck** [pymedusa/Medusa#4375]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: `master`
**OS: `FreeBSD 11.1-RELEASE (iocage jail)`
**What you did: `fresh install -> add series -> saw errors about KeyError -> debug mode -> sleep -> reboot host`
**What happened: `service failed`
**What you expected: `it works :)`
**Logs:

```
root@medusa:/ # service medusa start
Starting medusa.
Traceback (most recent call last):
  File "/usr/local/medusa/start.py", line 9, in <module>
    main()
  File "/usr/local/medusa/medusa/__main__.py", line 2157, in main
    application.start(sys.argv[1:])
  File "/usr/local/medusa/medusa/__main__.py", line 339, in start
    self.initialize(console_logging=self.console_logging)
  File "/usr/local/medusa/medusa/__main__.py", line 1093, in initialize
    app_logger.rebuild_censored_list()
  File "/usr/local/medusa/medusa/logger/__init__.py", line 90, in rebuild_censored_list
    results |= {quote(item) for item in results}
  File "/usr/local/medusa/medusa/logger/__init__.py", line 90, in <setcomp>
    results |= {quote(item) for item in results}
  File "/usr/local/lib/python2.7/urllib.py", line 1298, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u20ac'
/usr/local/etc/rc.d/medusa: WARNING: failed to start medusa

```
I was on SickRage and I saw your awesome medusa. It perfectly worked before I add my series.
This is my installation script : 
```
pkg update
pkg install git python py27-sqlite3 unrar ffmpeg
pw groupadd multimedia -g 1001
pw useradd clement -u 1000 -g 1001
cd /usr/local
git clone git://github.com/pymedusa/Medusa.git
cp /usr/local/Medusa/runscripts/init.freebsd /usr/local/etc/rc.d/medusa
echo 'medusa_enable="YES"' >> /etc/rc.conf
echo 'medusa_user="clement"' >> /etc/rc.conf
echo 'medusa_group="multimedia"' >> /etc/rc.conf
echo 'medusa_datadir="/var/db/medusa"' >> /etc/rc.conf
mkdir /var/db/medusa
chown -R clement:multimedia /var/db/medusa /usr/local/Medusa
cd ..
mv Medusa/ medusa/
```

**Comment by sharkykh** [comment]
Guessing here;
Did you copy over the `config.ini` file from SickRage?
Does one of your passwords contain the Euro sign?

**Comment by sharkykh** [comment]
Alright, for now set the git credentials to `""` in the config file, and medusa should run.
I'll look into fixing this. It needs to be tweaked to work with unicode characters.

For anyone interested, `urllib.quote` doesn't handle unicode strings, it needs to be a utf-8 encoded byte string.

**Comment by oasisck** [comment]
work like a charm
