### ISSUE TITLE
[ FEATURE ] Add support for processing and snatching multi-season releases

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#438]
Branch/Commit: develop
OS: Ubuntu 14.04
What you did:  Snatched a multi season pack ie `The.Magic.School.Bus.S01-S04.DVDRip.x264-DEiMOS`
What happened: Only marked the season the snatch was made from as snatched
What you expected: To mark all seasons as snatched from 1 to 4

**Comment by fernandog** [comment]
Not an issue. Its feature request: add regex for multi-season

**Comment by duramato** [comment]
It is if you snatch S01-S02 it should mark both as snatched since thats what happened

**Comment by fernandog** [comment]
@labrys guessit detects as S01 and S04

We should think using guessit soon

**Comment by duramato** [comment]
it isnt just season 1 and 4 , its 1,2,3 and 4

**Comment by fernandog** [comment]
So guessit is wrong. Is there a multi-season ? Any docs about it?

**Comment by duramato** [comment]
`S01-S04` or COMPLETE for the whole show's seasons
whats the output of guessit?

**Comment by fernandog** [comment]
```
guessit The.Magic.School.Bus.S01-S04.DVDRip.x264-DEiMOS
For: The.Magic.School.Bus.S01-S04.DVDRip.x264-DEiMOS
GuessIt found: {
    "title": "The Magic School Bus",
    "season": [
        1,
        4
    ],
    "format": "DVD",
    "video_codec": "h264",
    "release_group": "DEiMOS",
    "type": "episode"
}
```

**Comment by OmgImAlexis** [comment]
@fernandog the expected behaviour is that it matched all so I'm making it as a bug.

**Comment by fernandog** [comment]
@OmgImAlexis we never supported multi-season. Database doesnt support multi-season. We store season as INT and not LIST

**Comment by OmgImAlexis** [comment]
@fernandog can you not just loop through and set each season? E.g. if it's 1-4 then do a loop and do the same for each season?

**Comment by fernandog** [comment]
@OmgImAlexis we get information from database. not directly from file. So if database doesn't support and also regext doesnt support is not a issue as it was never designed to support

**Comment by OmgImAlexis** [comment]
Well we shouldn't allow snatching of them then.. either we fix the issue or disallow it to be caused in the first place.

I'd honestly go with fixing it instead of just trying to prevent this "feature" from working.

**Comment by labrys** [comment]
@fernandog you need an option enabled to guess multi-season or multi-episode, or really any multi-occurence of any tag.  otherwise it just grabs the first match for that tag.

**Comment by labrys** [comment]
```python
guessit(title, options={"implicit":True})
```

**Comment by p0psicles** [comment]
Yeah, if it requires DB model and regex changed. Create a FR. And we Look at it when time is due

**Comment by OmgImAlexis** [comment]
@p0psicles we need to block them being downloaded via manual search then otherwise this should be classed as a bug.

**Comment by labrys** [comment]
@OmgImAlexis I don't think they should be blocked.  Manual search is about user choice.  I do agree that the incorrect snatch tho is a bug, although in my opinion it would be a low priority one.  Also these kind of bugs should be given milestone tags as an indicator on when they might be fixed, e.g. when multi-season support goes live.

**Comment by OmgImAlexis** [comment]
Maybe add this to RC 2?

**Comment by p0psicles** [comment]
That depends on which changes will be required. If we need to make changes to db model, i vote not to include this. Remember we want to merge to master soon. I also expect that more issues similar to this one will rise to the surface, when we go live.

**Comment by ratoaq2** [comment]
As of today:
- Our parser can parse multi season correctly
- We discard multi season releases since our model (db, TVEpisode) doesn't support it.

I'm flagging this one as Feature Request since there's no bug to be fix.

**Comment by OmgImAlexis** [comment]
@ratoaq2 does guessit currently support multi season?

**Comment by fernandog** [comment]
DB doesnt support it.

**Comment by OmgImAlexis** [comment]
@fernandog well that'll have to be fixed then..

**Comment by fernandog** [comment]
We are waiting new DB since Nov/16.
And I bet we wont have it for 2017.
So, just wait.

**Comment by labrys** [comment]
New DB doesn't mean stop all development that relates to DB

**Comment by labrys** [comment]
Added to master feature request list - discussion for feature will continue here even though issue is closed.
