### ISSUE TITLE
"Add existing show" - returns/cycles to "Add new show" [v 0.2.5]

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#4385]
On Win10 / v 0.2.5 - when adding an existing show , instead of finishing in home screen (showing the new show, or related "sync" message" - Medusa returns to display the add-new-show, and with data of that new show that already been added.

Also, for some reason, the default quality is some strange custom one, I've probably used once couple of versions ago... It doesn't seem to remember the last quality/resolution set for the last added existing show.

Test clip:
https://drive.google.com/file/d/1EfWVxAd32eci5b9qSJ2kpbw45liQJSoO/view?usp=sharing

FYI

Rafi

**Comment by medariox** [comment]
Already fixed with: https://github.com/pymedusa/Medusa/pull/4336
