### ISSUE TITLE
When testing nzbget connections - useHttps is not defined

### ISSUE THREAD

**Issue by d0t1q** [pymedusa/Medusa#4386]
Branch/Commit: Current
OS:Ubuntu 18.04
What you did: Enabled nzbget 
What happened: medusa stalls while testing nzbget connection with or without https selected (note that the my nzbget system is not running on https)
What you expected: successful connection
Logs: Logs are useless as they do not capture the error, even with debugging enabled 

Error caught in chrome: 

Uncaught (in promise) ReferenceError: useHttps is not defined
    at Vue.testNzbget ((index):2031)
    at invoker (vue.js:2029)
    at HTMLInputElement.fn._withTask.fn._withTask (vue.js:1828)
testNzbget @ (index):2031
invoker @ vue.js:2029
fn._withTask.fn._withTask @ vue.js:1828

commenting out the useHttps line from the mako files fixes the issue.

I assume the main index file for the search settings is located here
https://github.com/pymedusa/Medusa/blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/themes-default/slim/views/config_search.mako

**Comment by OmgImAlexis** [comment]
Fixed in https://github.com/pymedusa/Medusa/commit/de4b5a1b4279ea4b109689ccd6aff308bd62ca4f
