### ISSUE TITLE
Edit Show page is broken, can't turn off check box

### ISSUE THREAD

**Issue by DarkSupremo** [pymedusa/Medusa#4387]
All checkboxes are not loading the current values, it's all turned off, and if i can't toggle something off, for example, scene numbering, anime, and so...

Here is an video that show it:
https://www.useloom.com/share/608d66aaf36c4a84a67f476b548acf40

### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** develop
**OS:** Window
**What you did:** Tried to toggle off scene numbering
**What happened:** It was already turned off in edit show page, and i can't really turn it off
**What you expected:** be able to turn it off in edit show page and show the real status of the check box

**Comment by p0psicles** [comment]
any errors in your developer tools console?

**Comment by DarkSupremo** [comment]
No error at developer tools or logs..

**Comment by OmgImAlexis** [comment]
@p0psicles might need to check those are updating their local state in vue's dev tools when you enable them.

**Comment by p0psicles** [comment]
Well its working fine for me. So i suspect its because of some specific config configuration. 

Your experiencing this with every show?

**Comment by p0psicles** [comment]
I correct. Have the same issue. Ill fix it

**Comment by sharkykh** [comment]
@p0psicles As I see it, we have two options:
[Fix the wrapper, but it requires another watch](https://github.com/pymedusa/Medusa/commit/f87bc7a1fc0db15eb9fab3c849a3aed2b804bff3)
or
[Remove the wrapper and go back to manually setting the values](https://github.com/pymedusa/Medusa/commit/0ec2c1bac399eaff2f55ce701d22fe81a1906129)

**Comment by sharkykh** [comment]
Fixed with #4401
