### ISSUE TITLE
Add Anidb.net as indexer

### ISSUE THREAD

**Issue by Nekotje** [pymedusa/Medusa#4390]
When i add a new show i only see 3 indexs.

Is it possible to add Anidb.net on there?

**Comment by medariox** [comment]
Everything is possible, it just requires someone to code it - it's not automated. Why would you like to have it added? Are the other 3 not enough?

**Comment by Nekotje** [comment]
i cant add certain showsbecause the others dont find it. And i only use it for Anime so the other 3 arnt useful for me.

**Comment by p0psicles** [comment]
Why dont you just add the anime on thetvdb or tvmaze? Issue with anidb is that they dont have an open api and are not open to implement sonething like it.

If we would implement anidb with the api's available, your ip would get banned within a day. And then everyone comes complaining here.

**Comment by Nekotje** [comment]
it already works with recommend anime. that shows a few. So i dont see the problem.  But i guess i will remove it the. Not going to add the titles to other sites to get it on this.  That is a worthless Workaround

**Comment by Nekotje** [comment]
this hasnt a general  Filter atleast i could not find it. Where i can add my own filters.

and that searches the rss feeds for new stuff.  i dont really need al the info of it. just a filter/template where i can add my filters and that filter searches the rss feeds.

**Comment by p0psicles** [comment]
Filter? What are you talking about? Where duscussing about getting anime shows visible in medusa, which are currently not on our used indexers like tvdb right?

**Comment by Nekotje** [comment]
that is correct. what i mean is. Instead of using anidb's api.

have a general page or so where you can add entries. like search for *.naruto*. or something like that with the options that the show page also has when you click on edit. 
it wont show any episode entries or info about anything. It would just fetch the rss feed from lets say Nyaa.si and if it finds a match it will download the torrent.

**Comment by damonmensch** [comment]
I know this is a tad late to the discussion, but just thought you should know this.



> Why dont you just add the anime on thetvdb or tvmaze?

The problem with thetvdb is they have a nasty habit of treating anime like American shows and combining multiple series of the same project group as one series, when it is in fact separate. they've done this with ".hack//SIGN", ".hack//ROOTS", ".hack//QUANTUM"; merged together as one entry ".hack//". They also did this with "Sword Art Online", merging all the spin-offs and sequels as one entry. Same goes for "Food Wars! Shokugeki no Souma". When you try to explain it to them that no, this isn't accurate and they should be separate,  they climb on their high horse and essentially shout that it's the way they are doing it and they don't care what others say and that if you don't like it stick to anidb.

Newer anime, where it's only a year or a couple moths apart is tolerable and understandable. But oldr ones, such as the case with ".hack//", where there is several years between these "seasons". The same is true for "Zoids"

I understand the concern for getting users banned by doing the API hits. There is a plugin for Plex that actually pulls this data from anidb, HTTP AniDB Metadata Agent [https://forums.plex.tv/t/rel-http-anidb-metadata-agent-hama/40470](url)

If I understand what it's doing correctly, it makes a local cache, once a week, of the series XML file on anidb and references that when doing searches.

This is just a suggestion on why this feature would be wanted and a possible way to implement it.

**Comment by p0psicles** [comment]
I know, tvdb is not ideal. That's the entire reason thexem.de got introduced. Which we utilize and works fine. Im also an anime user and using season scene exceptions and occasionally xem episode mapping it can find almost anything, with the rare exception.

We also use the anidb xml's. Mostly the one with tvdb mappings. But the other one can be used for searching shows. Only downside is, it's missing release year and network info. But I could live with that.

But then if we want to implement it as an indexer, we would need to have a way of getting detailed show info Inc episodes. And that api is very sensitive. I have ideas how to work around that using rare limmiting and local (dog pile) caching, but still. Allot of work. And only few devs.
