### ISSUE TITLE
Missing time zone for network Sky Go and Starz Play

### ISSUE THREAD

**Issue by deadc0de6** [pymedusa/Medusa#4391]
**Branch/Commit:** master Commit: c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**OS:** Linux-4.9.0-6-amd64-x86_64-with
**Logs:**
```
ERROR    Thread_0 :: [c65ca26] Missing time zone for network: Sky Go
ERROR    Thread_0 :: [c65ca26] Missing time zone for network: Starz Play
```

Thanks!

**Comment by sharkykh** [comment]
Can you give examples of shows that use these networks?

Looks like Starz Play is broadcast in the "Middle-East and Africa" region, which spans over multiple time zones from `UTC-1` to `UTC+3`/`UTC+4`

And Sky Go is a streaming app owned by Sky.com, which probably means it should be a network.

**Comment by deadc0de6** [comment]
For example britannia (https://www.imdb.com/title/tt5932548) is on sky and power (https://www.imdb.com/title/tt3281796) on starz.

**Comment by sharkykh** [comment]
Thank you for the information.

**Britannia**
https://www.thetvdb.com/series/britannia
https://www.themoviedb.org/tv/70484-britannia
http://www.tvmaze.com/shows/19685/britannia

I'd say the info on TVmaze is incorrect, and the network should be [Sky Atlantic](http://www.tvmaze.com/networks/113/sky-atlantic).
I don't have an account on that site.

**Power**
https://www.thetvdb.com/series/power
https://www.themoviedb.org/tv/54650-power
http://www.tvmaze.com/shows/299/power

I can't seem to find this network, so I'm someone already fixed it.
Make sure to click the "Force Full Update" for this show to fix the error.

====

Any other shows in your library that have these networks?
(you should be able to filter on the home page - try the list layout)

**Comment by deadc0de6** [comment]
nope, that's the two I tested.
Thanks for your help!
