### ISSUE TITLE
[APP SUBMITTED]: Could not parse episode status into a valid overview status: 3276806

### ISSUE THREAD

**Issue by droo88** [pymedusa/Medusa#4399]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-6-amd64-x86_64-with-debian-9.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/0879bc0c888b2ffb2e9621b2c136e176
### ERROR
<pre>
2018-06-17 20:02:17 ERROR    Thread_1 :: [c65ca26] Could not parse episode status into a valid overview status: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Did this happen just after the update, or?

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/0c0f086f4b41e0fd1f1b96cc09d3e1b0
### ERROR
<pre>
2018-06-19 16:00:59 ERROR    Thread_16 :: [c65ca26] Could not parse episode status into a valid overview status: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/5d7a9ac3806ed7b82c135dccdfa47717
### ERROR
<pre>
2018-06-19 16:26:25 ERROR    Thread_17 :: [c65ca26] Could not parse episode status into a valid overview status: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
@Magnus010 
Something went wrong with your upgrade. Are you using the `linuxserver.io` docker by chance? There seems to be a bug that causes the Medusa to start twice, causing the upgrade process to execute multiple times - this messes up the database. Follow these steps to fix it: https://github.com/pymedusa/Medusa/issues/4335#issuecomment-396208650

**Comment by Magnus010** [comment]
I am using the linuxserver.io docker image. I'll give that fix a shot. Thanks!

**Comment by Magnus010** [comment]
Looks like that took care of the issue. Thank you very much!

**Comment by doul59** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7
**Link to Log**: https://gist.github.com/704d7136a06a5f6df0aa406fadac6d04
### ERROR
<pre>
2018-06-24 12:48:39 ERROR    Thread_5 :: [32f7a7c] Could not parse episode status into a valid overview status: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
