### ISSUE TITLE
Absolute number now append to season number

### ISSUE THREAD

**Issue by hergonoway** [pymedusa/Medusa#4402]
#Version 0.2.5

Hi, 
while refreshing files from an anime I saw that naming scheme changed. I usually rename only with absolute number, so I've checked my settings and something odd showed-up : 

<img width="366" alt="image" src="https://user-images.githubusercontent.com/8405448/41512033-d2f9d1d2-7282-11e8-969f-b2e3fcd72863.png">

Season number isn't replace by absolute number. At first I assumed that something went wrong because I use a custom pattern : "%SN - S%0SE%0E - [%QN] [%RG]". So I've tried with pre-selected pattern but still the same.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/8405448/41512085-9660be10-7283-11e8-920f-631361e64bc8.png">

finally I've tried to check what would be the behaviour if I "preview rename" bad renamed files and it seems to be worst : 
<img width="496" alt="image" src="https://user-images.githubusercontent.com/8405448/41512128-471a47c6-7284-11e8-9a7f-619619befa12.png">

**Comment by sharkykh** [comment]
For now you can drop the `S%0S` from your custom naming format and it should work as expected.
`%SN - %0E - [%QN] [%RG]`

I'll look into fixing this.

**Comment by sharkykh** [comment]
Just note that because of this bug you may have to manually rename the files back to the names you used to have, if Medusa changed them to one that isn't correct, like in the screenshots above.
Sorry about that.

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/4403
