### ISSUE TITLE
Episodes stuck in snatched status after nzbget list items as failed 

### ISSUE THREAD

**Issue by d0t1q** [pymedusa/Medusa#4407]
**Branch/Commit:** master
**OS:** Ubuntu 18.04
**What you did:** Searched for old episodes 
**What happened:** medusa sent the nzb file to nzbget, nzbget failed to download the file as the file was unhealthy, nzbget listed the file as failed but medusa did not update its status
**What you expected:** Medusa should catch the failed status and blacklist the release 
**Logs:** https://pastebin.com/MswMH0aH -- Look at line 177 or ctrl+f "3x13" - nzbget failed notice - https://i.imgur.com/ssSFQt0.png

Medusa can catch shows that compelte succesfully from nzbget, its only failed shows that aren't updated, is there a setting I have misconfigured maybe?

**Comment by sharkykh** [comment]
> nzbget listed the file as failed but medusa did not update its status

> its only failed shows that aren't updated

I don't think that is something that's built into NZBget or Medusa.
You may have to use something like [nzbToMedia](https://github.com/clinton-hall/nzbToMedia).
But I barely know anything about it.
There's this guide, but it may be outdated: https://github.com/pymedusa/Medusa/wiki/NZBtoMedia#how-to-setup-nzbtomedia-with-nzbget

**Comment by d0t1q** [comment]
I'm not sure about that, on a previous install medusa would catch failed downloads and change the status from snatched to wanted and then try another release, I believe that is the point of the "use Failed downloads / Delete failed" (Lets you enable failed downloads. This will also allow adding bad/failed torrents/nzb to the failed.db so that they aren't downloaded again.)

**Comment by duramato** [comment]
Medusa doesn't have any auto failed downloads by iteself, currently for that you need to use a 3rd party script like nzbToMedia.
