### ISSUE TITLE
Search delay not saving for .5 hours in search Provider Options

### ISSUE THREAD

**Issue by PinaColonic** [pymedusa/Medusa#4408]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
c65ca26
**OS:**
Linux Mint 18.3 Cinnamon 64 bit
**What you did:**
Went to Search Providers ->  Provider Options -> checked Enable Search Delay -> Put .5 in for search delay (hours), hit save changes, came back 
**What happened:**
It showed 0.0 for search delay instead of .5, even though hovering over that field it says it can be a value .5 or greater - "Value must be greater than or equal to 0.5".  It seems to only save if I put at least "1" in for the hours.   I don't know if it is a display issue and it really saved .5 but shows 0.0 or if it is treating it as 0 delay in which case won't work as actual delay.
**What you expected:**
0.5 to show after saving and going back in to look at search delay (hours).
**Logs:**
N/A

**Comment by sharkykh** [comment]
@PinaColonic 
This is just a visual bug.
The correct value is saved (as long as you don't save it again when the value shows 0.0`.
The issue will be fixed with #4453.
