### ISSUE TITLE
Ignore possible malware either through post-processing or viewing torrent content

### ISSUE THREAD

**Issue by Samillion** [pymedusa/Medusa#4412]
Occasionally the odd fake and malicious file would be downloaded, I've experienced this on LimeTorrents a couple of times.

It's the typical `.exe` made to appear as a video file by using a VLC icon and TV show file name.

A similar feature has been requested here #1277, however it only covers unwanted extensions such as `wmv` and `flv` for quality reasons or potentially being fake content.

In the comments I saw that the Medusa team prefers exclusion rather than inclusion. Maybe add an "ignore completely" option if `exe` was found within torrent content as an opt-in option? I realize this could slow the process of searching, that's why I suggest it would be opt-in.

Or include it as an option for post-processing. Though I'd prefer an action before downloading to be honest. Either solution would be great though, if possible, of course.

**Comment by medariox** [comment]
We can't know what the torrent contains in advance. So that's a bit tricky to do. Post-processing only processes video files anyway, the rest should get deleted. Make sure to only search for verified torrents with Limetorrents and you should be fine.

**Comment by Samillion** [comment]
I never changed that setting and it's enabled by default. It doesn't happen often, just occasionally. It has stopped me from using LimeTorrents to be honest. I'm currently testing Zoogle. The ones with best results for me so far are TPB and RARBG.

Thank you very much for your input. Closing.
