### ISSUE TITLE
Feature request - File size restrictions 

### ISSUE THREAD

**Issue by Steve6030** [pymedusa/Medusa#4447]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** master
**OS:** MacOS
**What you did:** Nothing
**What happened:** Nothing
**What you expected:** Nothing
**Logs:** n/a
```
PASTE LOGS HERE
```
As a user I would like to be able to specify minimum and maximum file sizes for each quality.
eg: if I only want to download media larger than 700MB but smaller than 4.8GB.

**Comment by OmgImAlexis** [comment]
Closing as duplicate.

https://github.com/pymedusa/Medusa/issues/282
http://feathub.com/SickRage/SickRage/+77
