### ISSUE TITLE
Re-enable todo bot once issue is addressed

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#4468]
Please see https://github.com/pymedusa/Medusa/pull/4462#issuecomment-400254372 and https://twitter.com/OmgImAlexis/status/1011552577228435456

**Comment by sharkykh** [comment]
IMO it seems like that bot is going to be even more "spammy" than the code coverage bot... :thinking:

**Comment by OmgImAlexis** [comment]
It'll comment on each PR with the `@TODO` comments that the dev adds and once it's merged will move them to issues. It's worth it even if it feels a tad spammy as it cleans up after itself.
