### ISSUE TITLE
Manual Quality/Status has been Removed

### ISSUE THREAD

**Issue by bnevets27** [pymedusa/Medusa#4474]
I'm sure removing the ability to manually set the quality/status per episode was removed for a good reason but I know I'm not the only one missing that feature. Sure it's not a huge issue but it was helpful nonetheless.

First use case I've come across since it being removed.  I know there are more, some brought up in irc.
Medusa falsely is identifying a file as 720p web-dl. I would like to set it correctly to sdtv and archive it.
I think the above situation came about when medusa snatched a prefered quality (720p web-dl) to replace the existing sdtv. The snatched file failed and left the state in snatch 720p web-dl. I didn't want medusa to try an contine snatching that episode, so set it as archive. As archive sdtv now does not exist. Now the file is falsely labeled as 720p web-dl archived.

**Comment by medariox** [comment]
Will be back with the next release: https://github.com/pymedusa/Medusa/pull/4658
