### ISSUE TITLE
Rescan doesn't really Rescan

### ISSUE THREAD

**Issue by bnevets27** [pymedusa/Medusa#4475]
This has been a bug since I started using medusa over a year ago.

After a show is scanned in, changing filenames/moving files etc doesn't reflect in medusa. The expected result would be that the rescan button would freshly look at all the files and re-add them.

Removing the show, rebooting medusa and readding the show functions the way the rescan button should.

Example here:
https://lime-technology.com/forums/topic/53499-support-linuxserverio-medusa/?page=5&tab=comments#comment-664399

**Comment by medariox** [comment]
Re-scan only triggers a refresh of the episode if its name or size has changed. What did you actually do to the files? I couldn't understand it.

**Comment by bnevets27** [comment]
That's exactly what happens. Renamed files don't get picked up. This is from memory as I know that's happened in the past when trying to fix shows the have episode order messed up.

Not sure exactly what happened in that users case. But the idea is, Rescan seem to me like it should be about the same as removing the show and re-adding it, without having to go through all of that.

A current example would be that medusa incorrectly marked an episode as web-dl when I set it to downloaded/archived, when it had snatched a web-dl which had failed. In reality its was a hdtv file as indicated in the file name. One solution would be a rescan and it should pick up the hdtv in the filename. But it won't change the quality unless the entire show is removed then re-added.  

This is a bug which has been reported already.

**Comment by medariox** [comment]
These are completely different things. The issue here is: rescan doesn't really rescan. Where are the debug logs to prove that a changed file is not re-scanned? It rescans perfectly fine for me.

**Comment by bnevets27** [comment]
Admittedly, this is definitely a terrible bug report. Sorry about that. I can't reproduce right now. I know I had trouble when I was re-ordering episodes of some shows but don't have any messed up shows at the moment.

The example/issue I linked to was to make a point though. Why does removing a show completely, then re-adding it fix issues that users would expect the re-scan button to fix?

**Comment by medariox** [comment]
Because rescanning a show is obviously different than adding a show as new. I'll reopen the issue once you post the debug logs.
