### ISSUE TITLE
Error Getting Caps XML

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#4483]
Hi Team

I have install MedUSA on master and i am trying to add shows back. I keep on getting this. on SickRage i have no issues. 

Branch: master
Commit: c65ca2607fae74405dcceaaf8c02f3d29d0313ea
Version: v0.2.5
Database: 44.11
OS: Synology
What you did: Scan For Show
What happened: Error In Log
What you expected: No Error in Log
Logs:
```
2018-06-27 19:49:56 WARNING  SEARCHQUEUE-FORCED-321239 :: [NZBs.org] :: [c65ca26] Error getting caps xml for: NZBs.org
2018-06-27 19:46:29 WARNING  Thread_31 :: [c65ca26] Error getting caps xml for: NZBs.org
```

Thanks

**Comment by duramato** [comment]
Did you set your nzbs.org API key in the settings?

**Comment by HPMSGEN8** [comment]
Yes i did. same as all the others but  i only get this error on medusa

**Comment by medariox** [comment]
How do you expect getting results if the provider is offline? Some kind of dark magic?

**Comment by medariox** [comment]
Please put at least the same amount of effort in the issue reports that we put in trying to fix them.

**Comment by HPMSGEN8** [comment]
@medariox Sure will do :)
