### ISSUE TITLE
Single proper snatched multiple times

### ISSUE THREAD

**Issue by Tailslide** [pymedusa/Medusa#4495]
There seems to be some issue that started the last month or so where medusa will download multiple copies of the same proper from different search provider within seconds of each other.  Once I got two from the same search provider only 7 seconds apart as well.  The worst was last night where it snatched the same episode 10 times.

**Comment by sharkykh** [comment]
Already reported.
Probably a duplicate of the issues #4311 fixed.
This will probably be fixed in the next version.

**Comment by medariox** [comment]
@sharkykh 
I didn't have a look at the "proper search" code at all, so it is possible that this is still an issue.

**Comment by medariox** [comment]
@Tailslide 
What Medusa version are you using? Any debug logs to share?

**Comment by medariox** [comment]
Will be fixed with: https://github.com/pymedusa/Medusa/pull/4509

**Comment by Tailslide** [comment]
Thanks so much !! You guys are awesome.
