### ISSUE TITLE
[APP SUBMITTED]: Error loading IMDb info: Indexer TMDB is unavailable at this time. Cause: 502 Server Error: Bad Gateway for url: https://api.themoviedb.org/3/configuration?api_key=**********

### ISSUE THREAD

**Issue by shadownetdev1** [pymedusa/Medusa#4518]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/14d19864bde545816f2d2e865c0f88a4
### ERROR
<pre>
2018-07-01 22:15:23 ERROR    SHOWQUEUE-ADD :: [c65ca26] Error loading IMDb info: Indexer TMDB is unavailable at this time. Cause: 502 Server Error: Bad Gateway for url: https://api.themoviedb.org/3/configuration?api_key=**********
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
Fixed with #4524.
