### ISSUE TITLE
Black/White lists on Add New Show don't work

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#4525]
develop / e37859f7a3cadac6c72df8511fe754360f4e350b

Release groups black / white lists on the Add New Show page don't work (the buttons).
It used to not be visible due to a bug (I think), but now it is, and it needs to be fixed.

![2018-07-02_19-07-43](https://user-images.githubusercontent.com/10238474/42174491-392ae7f8-7e2b-11e8-9f32-191bf98b70a7.gif)

**Comment by p0psicles** [comment]
Needs to be replaces with the component

**Comment by sharkykh** [comment]
@p0psicles Right. This is here so we don't forget about it.

**Comment by OmgImAlexis** [comment]
@sharkykh any chance this could be fixed before release or shall we change milestones?

**Comment by sharkykh** [comment]
Probably not. `addShowOptions` needs to get converted to a Vue first. I've started but it's not going so smoothly.
