### ISSUE TITLE
Medusa updated - then downloaded over 1000 files

### ISSUE THREAD

**Issue by juliemars** [pymedusa/Medusa#4562]
Hi

I got a notification this morning that Medusa had updated to 

Branch: master 
Commit: a09681038a8f1fab0f4234ff2ae91784cc3d473d 
Version: v0.2.6 
Database: 44.11

a couple of hours later I noticed that my download queue had over 1000 files queued for download, and more was being added all the time. Basically ever file I had was being queued up for download again. 

All my files are stored in the following format:

Season %0S/%SN - S%0SE%0E.%EN (%QN)

the majority of my shows are set with the following quality:
SD TV, SD DVD, 720p HDTV, 720p web-dl
preferred is SD DVD (some are set to 720p web-dl as well)

Ignored Words: | german, french, core2hd, dutch, swedish, reenc, MrLss, Italian
Preferred Words: | x265, h265
Undesired Words: | internal, xvid, iNTERNAL

any ideas what I have done wrong and how to reset my library to the correct format's instead of snatched, setting the files to download sets them to 720p web-dl no matter the quality that was downloaded. 

Ideally I want to have DVD or x265 web-dl as my final copy.

Appreciate the help

**Comment by sharkykh** [comment]
> setting the files to download sets them to 720p web-dl no matter the quality that was downloaded.

Regarding that, we are working on restoring the function to change the episode quality manually [#4474].

> any ideas [...] how to reset my library to the correct format's instead of snatched

You can get the backup from before the update from the `Data/backup` folder.
I suggest you wait until we figure out a solution to your situation, so you it won't repeat the same thing when you load Medusa with that backup.

**Comment by medariox** [comment]
![img](https://snapr.pw/i/c9443a4ecc.png)

Isn't this the exect behaviour described in the quality description? Maybe it is confusing, but that's how it's originally suppused to work. There was a bug that was preventing this to work as expected and has now been fixed, hence the sudden snatches. You shouldn't have any issues for future episodes, the rest you can solve by keeping just one quality in the allowed list.

**Comment by juliemars** [comment]
thanks both, so the grabs is because of the way I have it set.

Guess I will need to work out a better settings now to stop this happening again, I had added the 720p quality last year to help with x265 grabs which is what I prefer

**Comment by medariox** [comment]
Yeah, it really was supposed to be like that from the beginning. You can read more about it [here](https://github.com/pymedusa/Medusa/pull/4514) and [here](https://github.com/pymedusa/Medusa/issues/2572). Btw we improved the preferred/undesired word filters a lot in version 0.2.6, just in case you were having issues in the past. If you need help with the settings profile visit us on IRC, there are usually a bunch of people happy to help out.

**Comment by jxer** [comment]
As discuss in chat.

please find a way to mass update all shows to archive to deal with this. some library's are huge and will require hours of going through and individually editing them.

**Comment by medariox** [comment]
This will be possible with: https://github.com/pymedusa/Medusa/pull/4647
Episodes that are currently `Snatched` -> set to `Ignored`
Episodes that are still `Downloaded` -> set to `Archived`

Thanks for the feedback!
