### ISSUE TITLE
schedule/periodic  “Re-scan files”

### ISSUE THREAD

**Issue by kantjer** [pymedusa/Medusa#4566]
**Is your feature request related to a problem? Please describe.**
I have to regular do a manual “Re-scan files” op have the library updated with removed (set to Archived) episodes.

**Describe the solution you'd like**
Would it be possible to schedule such a scan so the library is automatically updated? 

**Describe alternatives you've considered**
cron job if this could be triggered via the com,mand line

**Additional context**
none

**Comment by sharkykh** [comment]
This is one of the purposes of the Show Update[r] scheduler.
On the Server Status page you can see when it last ran, and when it's going to run next.

Or, perhaps you set this setting to disabled?
![image](https://user-images.githubusercontent.com/10238474/42315508-4e6aae56-8050-11e8-9548-98ec737f24b1.png)

**Comment by kantjer** [comment]
I see Show Update running daily at 6AM, and I haven't ticked the "skip Remove Detection" option but still my (by Kodi) deleted shows aren't removed from the library until I do a manual "Re-scan files"

Perhaps things work differently than I expect.

**Comment by sharkykh** [comment]
Oh you were talking about the Kodi library?

**Comment by kantjer** [comment]
No sorry, Kodi removes the file from my NAS
I'm talking about updating the Medusa library to reflect that

**Comment by kantjer** [comment]
@sharkykh I can confirm that both a manual "Re-scan files" and "Force Full Update" on the show with deleted episodes sets the removed episodes as "Archived". The scheduled show updater doesn't do anything with the removed episode(s)

I have enabled debug logging and will upload a debug log after the next run.

**Comment by kantjer** [comment]
@sharkykh 

debug log of the scheduled show updater
Hawaii Five-0 has a few episodes deleted, those are not picked up by the updater

If you want I can also run a "Re-scan files" that will set them to archived and post a log of that

https://hastebin.com/wavuvoqaki.sql

**Comment by sharkykh** [comment]
Ah, from the logs it looks like it didn't even run an update because the show didn't update on the indexer.
This is part of a feature to reduce the amount of information downloaded every day by the show updater.

I don't know how we should handle situations like these.
@p0psicles @medariox 
What do you think? Should we always refresh the folders?
That's a big change...

**Comment by medariox** [comment]
IMO we shouldn't always refresh the folders, it's like that for a reason and it works pretty well that way. This looks like a feature request to me.

**Comment by crazyasyou** [comment]
Moving from Sickrage to MedUSA I notice that as I watch and remove files they are not removing from MedUSA like they did in SickRage - I don't have "skip detection of removed files" checked, I have to perform a manual refresh of the show(s) to see them removed from MedUSA can this be corrected please?

**Comment by scambra** [comment]
I'm interested in this feature too. I think when file is removed, updated timestamp for parent directory changes.

Stat output before deletion:
  Size: 0               Blocks: 0          IO Block: 16384  directory
Device: 35h/53d Inode: 1345589516  Links: 2
Access: (0775/drwxrwxr-x)  Uid: ( 1000/  sergio)   Gid: (   90/ network)
Access: 2019-02-20 22:39:26.689910300 +0100
Modify: 2019-02-20 22:39:26.689910300 +0100
Change: 2019-02-20 22:39:26.689910300 +0100


Stat output after deletion:
  Size: 0               Blocks: 0          IO Block: 16384  directory
Device: 35h/53d Inode: 1345589516  Links: 2
Access: (0775/drwxrwxr-x)  Uid: ( 1000/  sergio)   Gid: (   90/ network)
Access: 2019-02-21 13:38:38.621086200 +0100
Modify: 2019-02-21 13:38:38.621086200 +0100
Change: 2019-02-21 13:38:38.621086200 +0100


Should it possible to have some scheduler which re-scan files for shows if show directory, or any season directory has newer modify timestamp than last run. It could be an optional scheduler, having a setting to define periodic time for this scheduler.

**Comment by rouggy** [comment]
Hi all, also having an issue with this, in the past while a new show was downloaded i could trigger this command: curl 'http://localhost:8081/api/*************?cmd=show.refresh&tvdbid={info.id}' with Sickrage and that would re scan the files of the specified show, but now this does not work anymore and i need to manually re-scan all the tv shows to make sure Medusa is updated properly whether a new show is downloaded or removed. Any other option to perform the same behavior ?

Thanks a lot

**Comment by p0psicles** [comment]
That api should work. You added the show with tvdb?

**Comment by rouggy** [comment]
Yes changed to tvdb and now working perfectly, awesome !
THanks a lot

**Comment by syp1975** [comment]
why is this issue closed? @rouggy message is a different topic. I still think this feature request should be open. In my case I use my own scripts to copy/rename files after being downloaded by deluge, but medusa keeps episode status at snatched until I manually press rescan files or force full update.

**Comment by medariox** [comment]
@syp1975 
You can trigger a re-scan with the API. We have no intention to add a periodic re-scan of the files atm.

**Comment by p0psicles** [comment]
There are 5 different issues /requests in this topic. I'm not sure what the issue is.

The api could be used. Maybe it doesn't work when used with tvmaze / tmdb shows. But it should with tvdb like sick*

**Comment by syp1975** [comment]
Issue title is the topic, that is why I did not had opened a new duplicated issue.
And yes, having no intention at all to add this feature request is a cause to close it.
Now that I know this, could you reconsider?
- For me this is not a feature request, is a design flaw: episode status is not updated with local changes, but only after an indexer change?
- Is the average user able to program and execute an scheduled script?

**Comment by p0psicles** [comment]
We dont scan periodic for changes as then other users start complain that where accessing the disk too much, which is bringing their Nas out of hibernation.

We maybe should however also start a scan when we do partial (season) indexer update. As @sharkykh mentioned this is not happening now? Or I'm not understanding.

The api v1 should be usable by our average users, considering most of our users know some scripting.

**Comment by p0psicles** [comment]
I'm also willing to help you out with a script. Then just hit me up on discord

**Comment by medariox** [comment]
@p0psicles 
IIrc the scan is only performed if there are any changes on the indexer.
