### ISSUE TITLE
Select dropdown for SubMenu navigation

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#458]
I was getting tired of all the small buttons wrapping on a mobile device.
That's why i've added a select for this. I'm a css expert, so this can be improved.

What do you guys think?
![image](https://cloud.githubusercontent.com/assets/1331394/14760541/1364d53e-0947-11e6-9ad9-08b9daae4737.png)
![image](https://cloud.githubusercontent.com/assets/1331394/14760542/16c1bc38-0947-11e6-9450-8edd4f7b72a2.png)
![image](https://cloud.githubusercontent.com/assets/1331394/14760544/1e13f8ca-0947-11e6-97d0-d659630f84ce.png)

If there's a need for it, i'll PR.

**Comment by p0psicles** [comment]
If there is no interest, i'm going to ditch it

**Comment by fernandog** [comment]
i liked for mobile!

**Comment by medariox** [comment]
I really like it for mobile devices as well. I think it would much easier to use compared to the small buttons we have right now.

**Comment by p0psicles** [comment]
It's triggered on a resize event, when the width of the screen goes below 979 pixels.

**Comment by fernandog** [comment]
@p0psicles after mobile view we can close it right?
