### ISSUE TITLE
History flashes an unsorted list for a second before showing sorted list

### ISSUE THREAD

**Issue by jtwill** [pymedusa/Medusa#4618]
**Describe the bug**
Whenever I click on "History", Medusa briefly shows a blank page then for about 1 second it flashes an unsorted history list, and then it shows the sorted history list (I have it sorted by date/time).

**To Reproduce**
Click on history and watch the screen carefully.

**Expected behavior**
The unsorted history list should not be shown. It is disorienting. Medusa should show the blank page until it can display the sorted history list.

**Medusa (please complete the following information):**

Medusa Info: | Branch:                     master                      
Commit:                     e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64                      
Version:                     v0.2.6                      
Database:                     44.11
Python Version: | 2.7.15 (default, May  1 2018, 20:16:04)  [GCC 7.3.1 20180406]
SSL Version: | OpenSSL 1.1.0h  27 Mar 2018
OS: | Linux-4.17.2-1-ARCH-x86_64-with-glibc2.2.5
Locale: | en_US.UTF-8

**Additional context**
I have my initial page set to "History" but I do not think it is relevant to this bug because
it happens even when I am already in Medusa and specifically click on "History".

I think this behavior only started with the latest release (v0.2.6). I did not notice it with previous versions.

**Comment by OmgImAlexis** [comment]
@sharkykh maybe we should add `loading` to data and have it set to false until the nextTick happens and tablesorter kicks in.

**Comment by sharkykh** [comment]
@OmgImAlexis 
I have something that looks like it's working, I'll open a PR for it.
I decided to go global with it, since it's already happening on other pages.
Had to make it use `opacity: 0` and not `display: none`, because `display` breaks a lot.

**Comment by medariox** [comment]
Fixed in develop with: https://github.com/pymedusa/Medusa/pull/4629
