### ISSUE TITLE
Unable to Send Email Notifications via Mailgun

### ISSUE THREAD

**Issue by synthetc82** [pymedusa/Medusa#4644]
**Describe the bug**
When using mailgun as the email provider, the following error is reported if the "SMTP from" isn't an actual email address. Other apps work fine with mailgun + a "Display name" as the "SMTP from". 

**To Reproduce**
Set the email notify to use mailgun's smtp server and try and send an email using an "SMTP from" value of anything but an email address.

**Expected behavior**
The email to be sent without issue

**Screenshots**
![image](https://user-images.githubusercontent.com/38138869/42524756-5197cc7c-8469-11e8-853e-dfe5e32689fd.png)

**Medusa (please complete the following information):**
 - OS:  Windows Server 2016 x64
 - Branch:  master
 - Commit: e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64

**Logs:**
<details>

```
2018-07-10 17:41:39 DEBUG    Thread_35 :: [e7c4ff3] Sending LOGIN command!
2018-07-10 17:41:38 DEBUG    Thread_35 :: [e7c4ff3] Sending STARTTLS command!
2018-07-10 17:41:38 DEBUG    Thread_35 :: [e7c4ff3] Sending initial EHLO command!
2018-07-10 17:41:38 DEBUG    Thread_35 :: [e7c4ff3] HOST: smtp.mailgun.org; PORT: 587; FROM: Plex Alerts, TLS: 1, USER: **********, PWD: ********, TO: [u'*******@sky.com']
```
</details>

**Additional context**
Suspect this is due to the way Medusa connects to the SMTP host to send emails, other applications (Tautulli for example) work fine using the same "SMTP from" display name and host settings.

**Comment by sharkykh** [comment]
We don't do anything special, it's the standard Python library.
Those "other apps" you speak of, they are probably written in a different programming language.

Try `Plex Alerts <>`?
