### ISSUE TITLE
Customized options not respected when mass importing shows.

### ISSUE THREAD

**Issue by calmcacil** [pymedusa/Medusa#4652]
**Describe the bug**
Adding large folders of show with show names from tvshow.nfo, adding custom settings in the customized tab and then clicking add, it still uses the defaults rather than the selected ones. Had it happen with my toons where I selected to ignore old episodes. As well as my anime folder it did not respect the anime checkbox.

**To Reproduce**
Add shows.
Add Existing Shows.
Add Folder, it will load a list of series as well as show the name and what to match it against.
Go to Customized options, Make changes.
Click submit

**Expected behavior**
I expected when making changes in Customized options that said options would be used when adding the large list of shows instead of falling back to defaults.

**Medusa (please complete the following information):**
 - OS: Unraid (Docker)
 - Branch: master
 - Commit: 0.2.6

**Comment by sharkykh** [comment]
Yep, I think I missed that.

**Comment by sharkykh** [comment]
Correction, looks like it was never a thing.
I agree it's a bit confusing, but currently you have to click "Save Defaults" before submitting the folders.

**Comment by medariox** [comment]
Just save defaults before importing.

**Comment by p0psicles** [comment]
I think this is now fixed in addExistingshows
