### ISSUE TITLE
Error loading IMDb info: file is encrypted or is not a database

### ISSUE THREAD

**Issue by trillex** [pymedusa/Medusa#4689]
**Describe the bug**
When Medusa attempts to refresh data from IMDB or I try to access the IMDB recommended show, I am greeted with: 

Error loading IMDb info: file is encrypted or is not a database

This also occurs on a fresh start, during the start phase, which gives the error shown under logs. 

I have tried to delete cache, both the content of the cache directory as well as cache.db. 

Checking through sqlite and a pragma check_integrity query, the normal sqlite databases seem to be OK. 

**To Reproduce**
1. Start Medusa

1. Go to Shows -> Add Recommended Shows
2. Click Add from IMDB's Popular Shows
3. An exception is made: Fetching of Recommender Data failed. Exception: file is encrypted or is not a database

**Expected behavior**
IMDB information should be gathered and put into the shows. 

IMDB recommended shows should appear

**Medusa (please complete the following information):**
 - OS: Windows 10
 - Branch: master
 - Commit: e7c4ff3

**Logs:**
<details>

```
Traceback (most recent call last):
  File "C:\Git\Medusa\medusa\show_queue.py", line 587, in run
    self.show.load_imdb_info()
  File "C:\Git\Medusa\medusa\tv\series.py", line 1543, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "C:\Git\Medusa\ext\imdbpie\imdbpie.py", line 80, in get_title
    '/title/{0}/auxiliary'.format(imdb_id)
  File "C:\Git\Medusa\ext\imdbpie\imdbpie.py", line 265, in _get_resource
    return self._get(url=url)['resource']
  File "C:\Git\Medusa\ext\imdbpie\imdbpie.py", line 272, in _get
    headers.update(self.get_auth_headers(path))
  File "C:\Git\Medusa\ext\imdbpie\auth.py", line 112, in get_auth_headers
    creds, soon_expires = self._creds_soon_expiring()
  File "C:\Git\Medusa\ext\imdbpie\auth.py", line 97, in _creds_soon_expiring
    creds = self._get_creds()
  File "C:\Git\Medusa\ext\imdbpie\auth.py", line 84, in _get_creds
    with diskcache.Cache(directory=self._cachedir) as cache:
  File "C:\Git\Medusa\ext\diskcache\core.py", line 380, in __init__
    sql('CREATE TABLE IF NOT EXISTS Settings ('
DatabaseError: file is encrypted or is not a database
```
</details>

**Additional context**
I have been noticing more and more errors regarding not being able to look up various shows in IMDB, it was first today that I decided to look further into it, with debug enabled. 

I was sure it was an issue with the Medusa Windows Installer, so I reinstalled from scratch with old data and new release from git. 

It is most likely a simple issue, I am just not finding the solution.

**Comment by medariox** [comment]
Works fine for me. Tested with Debian 8 and Windows 10.

**Comment by p0psicles** [comment]
Maybe its specific show related. You tried recommended list?

**Comment by medariox** [comment]
Yeah, that's what I tried.

**Comment by sharkykh** [comment]
@p0psicles If you still have this issue, can you run:
```
python -c "import tempfile, os.path; print os.path.join(tempfile.gettempdir(), 'cache.db')"
```
That's where DiskCache (the library imdbpie is using) stores the database.
Maybe it's invalid...

**Comment by trillex** [comment]
@sharkykh Deleting this worked for me, it's currently rebuilding it after I went to Shows -> Add Recommended Shows -> Add from IMDB's Popular Shows. 

If @p0psicles sees the same, I say that this issue can be closed.

**Comment by sharkykh** [comment]
@trillex 
Thank you for confirming :)

> If @p0psicles sees the same, I say that this issue can be closed.

It's only a temporary solution. I think a better solution would be [to move that file to the `Data/cache` folder](https://github.com/pymedusa/Medusa/issues/4743#issuecomment-407364945).

**Comment by medariox** [comment]
Fixed in develop with: https://github.com/pymedusa/Medusa/pull/4745
