### ISSUE TITLE
Does 'Post-Processed seeding torrents location' work with 'copy' processing method?

### ISSUE THREAD

**Issue by Makeshift** [pymedusa/Medusa#4693]
**Describe the bug**
When the processing method 'copy' is used in conjunction with the 'post-processed seeding torrents location' with Transmission, Medusa doesn't seem to move the torrent after processing, causing it to get stuck attempting to process repeatedly. I'm wondering if this is intended behaviour or a bug?

**To Reproduce**
1. Use Transmission with an incomplete-dir set (not sure if required), and download-dir set.
2. Have Medusa copy the files during processing.
3. Set Medusa to move the torrent after processing using 'post-processing seeding torrents location'
4. Nothing seems to happen - After post-processing completes, the files do not move and no log is produced regarding it.

**Expected behavior**
After download completes, it is moved into the processing folder for Medusa to process. Medusa should copy the content to the correct location, and after processing should use the Transmission RPC to move the seeding item to the specified folder.

**Medusa (please complete the following information):**
 - OS: Ubuntu 18.04
 - Branch: Master
 - Commit: e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64 (https://hub.docker.com/r/linuxserver/medusa/ latest version)

**Logs:**
No relevant logs

**Additional context**
This may be related to my absolutely ridiculous setup which I haven't gone into detail here - If somebody else can confirm it's working fine for them I'm happy to concede that it might be my configuration and handle it myself.

**Comment by fernandog** [comment]
@Makeshift as feature description says: "Note: **If your Post-Processor method is set to hard/soft link** this will move your torrent to another location after Post-Processor to prevent reprocessing the same file over and over. "

**Comment by OmgImAlexis** [comment]
@fernandog would we be able to add this for copy as well? It should still be able to run in the torrent client and be moved.

Maybe the user has a larger drive being used for their SEEDING directory which is the case for myself.

**Comment by Makeshift** [comment]
Ah - Thanks Fernandog. The note seemed a little ambiguous since I wasn't sure if it applied to others or JUST hard/soft links.

In that case I'd like to swap this to a feature request to allow for moves if copy is enabled. Would you like me to update the original ticket?

**Comment by fernandog** [comment]
If all other devs think this could be changed then just need to change this line of code:

https://github.com/pymedusa/Medusa/blob/develop/medusa/process_tv.py#L169
