### ISSUE TITLE
Add show : Step 3 screen by default and image broken

### ISSUE THREAD

**Issue by Naokor** [pymedusa/Medusa#4736]
**Describe the bug**
When clicking on "add shows" from topbar menu then "add new show" with the TV logo (https://domain.xxx/medusa/addShows/newShow/) the stage 3 is displayed as landing page instead of the step 1. It is just a very light annoyance and not really a bug. Occurs on Chrome and Safari. Not tested with other browsers. 

In addition, when searching a TV Show (see screenshots), an image link seems to be broken. It is very quick but visible! 
 
**To Reproduce**
1. Go to 'Shows (topbar) / Add shows / Add a new show'
1. See error

Second bug : On the step 1 screen, search fo a show. While searching, an image link is broken. 

**Expected behavior**
Land on the step 1 screen instead of the step's 3 

**Screenshots**

![image broken](https://user-images.githubusercontent.com/26311252/43105214-64f31e46-8ed4-11e8-893d-4a8b29ede677.png)

![screen 3](https://user-images.githubusercontent.com/26311252/43105083-e991770c-8ed3-11e8-8deb-f8155935a399.png)

**Medusa (please complete the following information):**

Branch: develop Commit: c304860c5360b2e9fa118717a639c28578e5a27e 
Version: v0.2.6 Database: 44.11
Python Version: | 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.12.14-041214-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: | en_US.UTF-8

**Additional context**
After a clean install of Medusa with quickbox.

**Comment by sharkykh** [comment]
Will be fixed with #4719.

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/4719
