### ISSUE TITLE
{"result": "success"} page on manual search (magnifier icon)

### ISSUE THREAD

**Issue by Naokor** [pymedusa/Medusa#4737]
**Describe the bug**
When clicking the magnifier icon on a show page to launch a forced search of the episode, the result is a blank white page with {"result": "success"}

**To Reproduce**
1. Go to a show detail page
2. Click on 'the magnifier icon at the end of an episode's line'

**Expected behavior**
A "success" message on the episode's line

**Screenshots**
![success](https://user-images.githubusercontent.com/26311252/43105435-2fe4576e-8ed5-11e8-9657-6d1a7bf562a6.png)

**Medusa (please complete the following information):**
Branch: develop Commit: c304860c5360b2e9fa118717a639c28578e5a27e 
Version: v0.2.6 Database: 44.11
Python Version: | 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.12.14-041214-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: | en_US.UTF-8

**Additional context**
Only on develop branch. Master works fine.

**Comment by sharkykh** [comment]
@OmgImAlexis 
I'm not having much luck with this bug...

**Comment by p0psicles** [comment]
This is probably happening because of some other js failure. He should check chrome dev tools console.

**Comment by sharkykh** [comment]
@p0psicles 
The click event handler is missing. That's not a JS error, it's all related to Vue.
It's taking over the DOM too early, I think.

![chrome_2018-07-24_21-01-45](https://user-images.githubusercontent.com/10238474/43157205-f35dc9b4-8f84-11e8-96ef-5175b35e4718.png)

**Comment by p0psicles** [comment]
Ive had the issue before. And i think it was a race condition. I dont think its vue related.

We could make sure its not following the link, when the click event hasnt been overeritten yet.

**Comment by p0psicles** [comment]
Hmm these are generated now by the app-link.
Still remember to have seen this issue before they where changed to app-link.

**Comment by sharkykh** [comment]
You're talking about the links in the snatchSelection. Because it was loading part of the page using jQuery, and Vue can't render new components on the fly.
It's a different issue.

**Comment by p0psicles** [comment]
I think we could easily fix this, by adding a property to the app-link component, to remove the click handler.

**Comment by p0psicles** [comment]
No, i'm talking about the links in displayShow. The app-link is generating an <a> with an href. Then ajax-ep-search.js goes over all the .epSearch and .epManualSearch classes, and binds new click handlers.

If you click the icon before the new events have been bind, your just following the <a> link. Which is returning the json.

**Comment by OmgImAlexis** [comment]
`ajax-ep-search.js` there is your issue. Move the button to a new component that handles manual search instead of using an `app-link` since it's not a link.

**Comment by sharkykh** [comment]
Fixes with #4751.
