### ISSUE TITLE
Abnormal provider : doesn't find anything

### ISSUE THREAD

**Issue by Naokor** [pymedusa/Medusa#4747]
**Describe the bug**
The provider Abnormal _(him again, yes)_ can not find anything in manual and automatic search. I tested with a very specific episode and others (both available on the tracker). Is it a langage related issue? I do not really know! According to my settings it should find it and DL it, but nothing happened. Thank you!

**Expected behavior**
An episode snatch!

**Screenshots**
Available on the tracker 
![abn 204](https://user-images.githubusercontent.com/26311252/43150317-e75db2e8-8f69-11e8-93fa-379fef188415.JPG)

My settings _(I don't know if the required words are case sensitive so... I put two versions of vostfr...)_
![settings](https://user-images.githubusercontent.com/26311252/43150330-ee0978b6-8f69-11e8-9669-cd480b8ff7cc.JPG)

**Medusa (please complete the following information):**
Branch: develop 
Commit: 998f309861beaf0631fda4005d6ec1b395226995 
Version: v0.2.6 Database: 44.11
Python Version: | 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.12.14-041214-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: | en_US.UTF-8

**Logs:**
<details>

2018-07-24 17:42:58 INFO     SEARCHQUEUE-MANUAL-325517 :: [998f309] Unable to find manual results for: Salvation - S02E04 - Indivisible
2018-07-24 17:42:56 INFO     SEARCHQUEUE-MANUAL-325517 :: [ABNormal] :: [998f309] Performing episode search for Salvation
2018-07-24 17:42:56 INFO     SEARCHQUEUE-MANUAL-325517 :: [998f309] Using manual search providers
2018-07-24 17:42:56 INFO     SEARCHQUEUE-MANUAL-325517 :: [998f309] Building internal name cache for Salvation
2018-07-24 17:42:56 INFO     SEARCHQUEUE-MANUAL-325517 :: [998f309] Finished processing 2832 scene exceptions.
2018-07-24 17:42:56 INFO     SEARCHQUEUE-MANUAL-325517 :: [998f309] Updating exception_cache and exception_season_cache
2018-07-24 17:42:56 INFO     SEARCHQUEUE-MANUAL-325517 :: [998f309] Beginning manual search for: Salvation - S02E04 - Indivisible

</details>

**Additional context**
Medusa clean install with Quickbox.

**Comment by medariox** [comment]
I don't think any of the devs have access to this provider and the code might be outdated. Would you be able to provide us with (temporary) access?

PS: Required/Ignored/Undesired/Preferred words are all case insensitive.

**Comment by Naokor** [comment]
@medariox I think this is mandatory if we want this issue fixed. How can I reach you to give you some ID ?

**Comment by p0psicles** [comment]
Through irc. Get on irc and ping one of the devs. From there you can get in a PM.

**Comment by Naokor** [comment]
Hello! I asked the team to open a temporary access. While I am waiting, here is the link to the Jackett file currently in use with abnormal (and it works). Maybe it is useless for you (don't know).

[Jackett/src/Jackett.Common/Indexers/Abnormal.cs](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Abnormal.cs)

**Comment by Naokor** [comment]
This issue can be closed! I am ashamed to tell you that the IP adress of my test server was accidentely banned! This was the explanation...

 I discovered this with Jackett's logs... This provider works fine with Medusa and give some results on manual and auto search. 

Thank you guys!
