### ISSUE TITLE
New torrent provider : ShowRSS

### ISSUE THREAD

**Issue by Ofboir** [pymedusa/Medusa#4753]
Hi !

Would it be possible to add ShowRSS to the supported torrent providers ?

It seems that it was supported by TvTumbler, a Sickbeard fork from a few years ago. Maybe this could help :
https://github.com/bricky/xbmc-addon-tvtumbler/blob/master/tvtumbler/feeders/showrss.py

Thank you

**Comment by p0psicles** [comment]
You can add its rss feeds

**Comment by sharkykh** [comment]
@Ofboir 
Try this configuration.
**Provider name:** `ShowRSS`
**RSS URL:** `https://showrss.info/other/all.rss`
**Search element:** `tv_raw_title`

This should work best.
