### ISSUE TITLE
WebUI not loading in develop branch (black screen)

### ISSUE THREAD

**Issue by JustARandomGuyHere** [pymedusa/Medusa#4754]
**Describe the bug**
WebUI is not loading (black screen occurs)

**To Reproduce**
1) clone the repo
2) checkout to develop branch
3) start medusa
4) go to webui

**Expected behavior**
The webui should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/38226681/43219181-e431c770-9046-11e8-8b90-7f7b2a51cbf5.png)

**Medusa (please complete the following information):**
 - OS: debian 9
 - Branch: develop
 - latest commit but it's like that for a few days now.

**Logs:**
Logs are ok there is no error check the screenshot for browser logs

**Comment by sharkykh** [comment]
Try doing a hard reload of the page to clear your cache (CTRL + F5).

**Comment by JustARandomGuyHere** [comment]
Oh ok Cloudflare cached my website and I completely forgot to clear that cache too 😅 
Everything is working fine now.

Keep up the good work !
