### ISSUE TITLE
Add pagination to  "Schedule" tab calendar view

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#4760]
>A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I am always frustrated when I cannot see *all* of my shows' future episodes  on the Schedule tab (supposes to be weekly).  
The problem is that the shows that has been aired TODAY (US night show, early AM in my timezone) and snatched - are NOT visible on a 1-week calendar, since the next episode is due in 8 days, and the 8th day is not shown.

>A clear and concise description of what you want to happen.

I like to see all future shows for the next coming week.

>A clear and concise description of any alternative solutions or features you've considered.

A simple solution should be - show an 8-day schedule, not 7 days.
One more option is to have an option to define the "length" of the calendar in days or even weeks/months. At least - up to two weeks. 

>Add any other context or screenshots about the feature request here.

I think the above is clear enough. Come to think of it, one can consider it a bug, and not a feature request. Your call... :)

**Comment by OmgImAlexis** [comment]
We already planned on adding pagination to most pages so there's no point in adding a half assed feature when we can just do it properly.

**Comment by rafi-d** [comment]
Surly, I am not for half baked solutions... 

What I meant was that "pagination" is simply not relevant to lists-views. They can be as long as you want.
So my thought was that instead of waiting for a low priority feature to get done, just quick-fix/change the dates-range  by +1 for now for the lists view in Schedule, which might be in 0.2.7 already, and provide a quick solution...

**Comment by rafi-d** [comment]
The proposed 1-character-change in schedule.py and the result - 

```
@route('/schedule(/?.*)')
class Schedule(WebRoot):
    def __init__(self, *args, **kwargs):
        super(Schedule, self).__init__(*args, **kwargs)

    def index(self):
        next_week = datetime.date.today() + datetime.timedelta(days=8)   \\ <--- change 7->8 
        next_week1 = datetime.datetime.combine(next_week, datetime.time(tzinfo=network_timezones.app_timezone))

```
![medusa-8-days-schedule-lists_2018-07-27_081400](https://user-images.githubusercontent.com/2458280/43303618-3201b180-9179-11e8-8017-ec7db113b067.jpg)
