### ISSUE TITLE
0.2.7 : Empty Screens on Safari / OSX

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#4771]
**Describe the bug**
The latest version 0.2.7 only shows the blank background and no app. safari ans osx are latest version. Chrome does not suffer from this issue.

**To Reproduce**
i've upgraded, the app restarted and i was looking at a blank page for 10 mins until i understood what happened. regardless what page i'm opening from the url i only get a blank rsponse. View Page-Source seems to be fine FWIW and looks like a proper page...

**Expected behavior**
Obvious. :-)

**Screenshots**
![screen](https://user-images.githubusercontent.com/869637/43330517-b6d8b788-91c3-11e8-8bb4-7833a95f6246.png)

**Medusa (please complete the following information):**
Branch: master 
Commit: b7333559c9a747cd3e8b4022c4073757a62b32ed 
Version: v0.2.7 
Database: 44.11

OS: OSX High Sierra

**Logs:**
No Errors

**Additional context**
N/A

**Comment by sharkykh** [comment]
Duplicate of #4767.
Do a hard page reload. (Should be CMD + F5)

**Comment by udochrist** [comment]
Works. thx...
