### ISSUE TITLE
Dark, blank page after update

### ISSUE THREAD

**Issue by trohnjavolta** [pymedusa/Medusa#4772]
Hi, after todays update I get a dark, blank page. Clearing website cache and cookies does not help.
Systemctl status medusa shows no errors. Any chance to roll back the update?

Trying this from faq didn't help, says I'm already up to date
https://github.com/pymedusa/Medusa/wiki/FAQ's-and-Fixes#update-problems-try-this

**Comment by PinaColonic** [comment]
A friend of mine is saying the same thing, I haven't tried myself due to his warning and just found yours

**Comment by p0psicles** [comment]
Any errors? Debug log? Chrome console logs?

**Comment by PinaColonic** [comment]
"<thisaintgonnahappen> tho, it appears to be an issue with the hostname
<thisaintgonnahappen> I changed from localhost to 127.0.0.1
<thisaintgonnahappen> and is workin"

Apparently that is what he had to do to fix it....

**Comment by trohnjavolta** [comment]
Yes, thats it thx.
That's unfortunate that via hostname it's not workin anymore. Why could that be?

**Comment by sharkykh** [comment]
Have any of you tried a hard page reload? (CTRL+F5)
This is a cache issue.

**Comment by PinaColonic** [comment]
My friend confirms the CTRL-F5 worked...had trusted the first update above that cache was cleared but I guess that wasn't done the right way.

**Comment by PinaColonic** [comment]
His success gave me a better feeling so I just updated myself, got same black/blank page, and did CTRL-F5 to fix it, and looks good.  Might spook a lot of users who won't know how to look this up on github or do this, though...

**Comment by sharkykh** [comment]
I agree, we'll fix it by next version.

**Comment by trohnjavolta** [comment]
Lol, yes. I deleted website cookies and reseted website settings.
Now Ctrl + F5 works.
