### ISSUE TITLE
Anime/series tab separation broken after last update

### ISSUE THREAD

**Issue by rodrizapico** [pymedusa/Medusa#4773]
**Describe the bug**
Hi! After updating last night and fixing the issue described in  #4772, the tabs separating anime from series are broken, instead showing as two separated lists.

 - OS: FreeBSD 11.1 running on FreeNAS jail
 - Branch: master

**Comment by p0psicles** [comment]
We noticed. Fixed in current develop. Not a big enough issue to create a hotfix for. But we noticed another issue, that we might hotfix.

**Comment by rodrizapico** [comment]
Great, thanks for the quick answer!
