### ISSUE TITLE
Make certain Text fields a Text Area in config

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#4780]
**Is your feature request related to a problem? Please describe.**
The number of ignore words I have are getting quite long and the current text field needs a lot of scrolling

**Describe the solution you'd like**
Would be easy if it was converted to a textarea

![image](https://user-images.githubusercontent.com/4103090/43355653-3b23040c-9260-11e8-8d14-410bae14cce5.png)

**Comment by p0psicles** [comment]
haha tnx :heart_eyes:

**Comment by p0psicles** [comment]
Closing the issue, as the text area is not going to happen. And vueifying Search Filters isn't going to take that long.
