### ISSUE TITLE
Show pages: Episode column not shown on mobile

### ISSUE THREAD

**Issue by benfishbus** [pymedusa/Medusa#4815]
When I view any show page from iOS Safari or Chrome, the ‘Name’ column containing episode title is not shown. It is selected in the ‘Columns’ dropdown, and toggling and reloading doesn’t help.

**Comment by p0psicles** [comment]
It was a choice to hide it at some time. Ill revert it.

**Comment by medariox** [comment]
Fixed long time ago.
