### ISSUE TITLE
Question: SickRage To Medusa Migration 

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#4816]
Hi Team.

What is recommend, Upgrade SickRage to Medusa using some guides to keep all the settings and stuff or an clean install and import from the ground up.

Or is there an easier way.

Thanks

**Comment by alzeric** [comment]
Clean Install, Then go to Shows/Add Show/Add Existing Shows (then point it
to all your TV Show folders)

This is the best and easiest way, avoiding all the pitfalls of trying to
use the old sickrage DB.

**Comment by HPMSGEN8** [comment]
Thanks @alzeric. I take it that adding them works 100% now and it picks up all the show quality if SD and HD ?

I take it that all custom settings per show needs to get added manually or is there easier way for that,

Thanks

**Comment by alzeric** [comment]
Yeh I believe a patch or two back took care of the duplicate show bug (where adding from existing made you have to go through each show twice). I'm actually running the development version (which I know 100% for sure it's fixed in)

Yes if you have specific settings per show you'll have to manually set those, if all them are to be the same you can set your "Default Settings" before progressing through the import.

**Comment by HPMSGEN8** [comment]
Thanks. Tomorrow is going to be a Migration Day :)

**Comment by HPMSGEN8** [comment]
Migration is starting but for some odd reason Chrome keeps on timing out and i am using almost 400MB of RAM which i think is a bit odd since SickRage only used a very small amount. Will see after a few hours what happens. 

I might move this to Docker to see if i get better performance.

**Comment by OmgImAlexis** [comment]
It's expected that it'll use more RAM on first load, keep in mind it'll be filling all it's caches, etc. since you didn't copy your database files over.

**Comment by HPMSGEN8** [comment]
Yes i get that but i mean at normal running mode it is still way higher.

**Comment by p0psicles** [comment]
Well you can't compare medusa with sickrage. It's really a different app. There is allot more caching going on. Which will result in higher memory usage. But is essential to limit the amount of outside connections.

Also the virtual memory usage doesn't say much about the real usage. As 1. often the swapped out reserved memory is included and 2. the application uses what's available.

**Comment by HPMSGEN8** [comment]
@p0psicles I have added 1GB of RAM to Docker so this way i do not have to worry about the RAM Again :)

**Comment by p0psicles** [comment]
Yeah see it like this. Memory is the cheapest resource to spare. Youd rather have it use more memory then cpu cycles, network or disk io.

But still, well try to bring it back a little, through some profiling.

**Comment by HPMSGEN8** [comment]
Thanks
