### ISSUE TITLE
Add Arrows To Search Shows

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#4817]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
If possible to have the left and right arrows on the show page. So once you are in an show you do not have to use the drop down to select the next you and can move left or right to search as well. 

This is what SickRage. 

**Describe alternatives you've considered**
What is in place already

**Additional context**
N / A

Thanks Alot

**Comment by medariox** [comment]
They look really outdated. Won't be coming back.
