### ISSUE TITLE
[Feature Request] Add Auto Refresh For Logs Display 

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#4818]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The Logs page does not auto refresh so i cannot see what is happening in real time. is it possible to have an rolling log ever 2 or 5 seconds so all updates and change etc.. can be seen instead of pressing F5 to see what is going on. 

**Describe alternatives you've considered**
N / A

**Additional context**
N / A

Thanks Again.

**Comment by OmgImAlexis** [comment]
We should be adding live logs within the next few months.

**Comment by HPMSGEN8** [comment]
@OmgImAlexis  Thanks :)
