### ISSUE TITLE
Three-Digit Episode / Seasonnumber

### ISSUE THREAD

**Issue by annomatik** [pymedusa/Medusa#4823]
**Is your feature request related to a problem? Please describe.**

Not a problem, but ... Currently, Medusa / SickRage / SickBeard only either provide no or one leading zero for Episode- and Seasonnumbers, e.g. 1x1 or 01x01 or any mix thereof. But as there are some TV Shows that have more than 99 episodes, this can in these cases mess up alphabetic sorting in a file explorer, so I have started my collection with three digits each (for symmetry)

**Describe the solution you'd like**

In Post Processing --> Episode Naming, it is currently possible to use %0S and %0E for one leading zero, it would be great, if there also was a %00S and a %00E for two leading zeroes.

**Describe alternatives you've considered**

Currently, I'm using this naming string:

Season 0%0S/0%0Sx0%0E - %EN %qn-%rg

Obviously, if there are e.g. year-seasons, like 2018, this results in problems like 02018x001 as episode number.

**Additional context**

Thanks for your consideration!

**Comment by p0psicles** [comment]
Honestly i would recommend to not do this. As the one leading zero is a much used standard by most media parsing software.

But ill consider the feature request as im currently working on the name patterns anyway.

**Comment by annomatik** [comment]
Thank you! Well, in Kodi, this scheme works great.

**Comment by p0psicles** [comment]
So you currently using this:
Currently, I'm using this naming string:
Season 0%0S/0%0Sx0%0E - %EN %qn-%rg

But for a season 1, ep 123 that would result in: `Season 001/001x0123 - Ep Name 720p hdtv-rlsgroup.ext` right?

**Comment by annomatik** [comment]
Hi, yes, that's what I used (except for the dash between %0E and %EN) and that's what came out.

Currently, I'm using Season 0%0S/S%0SE%0E %EN %qn-%rg, because of parser issues. Medusa doesn't seem to understand SeasonXEpisode for filenames, so I changed to SSeasonEEpisode.
