### ISSUE TITLE
Backlog showing "Downloaded" episodes

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#4832]
Hi,
A question: should the backlog show downloaded episodes? I thought the expected behavior is- it was  intended for "wanted" ones that are pending to be snatched (air-dates have passed) ? 

**Screenshots**
attached - showing "the 100" - that was downloaded/

**Medusa (please complete the following information):**
 - OS: Win 10 x86
Medusa 0.25
![1](https://user-images.githubusercontent.com/2458280/43563965-235837ea-962d-11e8-8ca2-3852d118a5ff.png)

In my case, it seems to show also "allowed" qualities. Is Medusa going to re-download those if the "preferred" qualities be available and delete the previous downloads  ?  If not, maybe a "backlog" is not the place to show them, or at least make a note to the fact that those are NOT candidates for download now?

**Comment by rafi-d** [comment]
Will it re-download bluray, so it will end up with two downloaded files?

**Comment by OmgImAlexis** [comment]
It should download it and replace the file.

**Comment by rafi-d** [comment]
Not sure I understand the process in this use case: 
Is the previous file being physically deleted plus the associated .torrent file? If so, since it has been on the uTorrent client list (in my case) will Medusa  also remove it from that uTorrent client list (using webui API) ? Otherwise it will show as "red" (missing file error).
