### ISSUE TITLE
HTTPS issues

### ISSUE THREAD

**Issue by oasisck** [pymedusa/Medusa#4840]
Hi all, I'm trying HTTPS but I'm stuck loading webpage when enable_https = 1
Medusa in iocage jail (FreeBSD 11.1)
pkg installation script : 
`pkg install git python py27-sqlite3 unrar ffmpeg mediainfo`
Like couchpotato and headphones
```
pkg install py27-pip
pip install --upgrade pip
pip install pyopenssl
```
but I didn't read that before : https://github.com/pymedusa/Medusa/wiki/SSL-Errors (btw, URL for ez_setup.py changed to https://raw.githubusercontent.com/pypa/setuptools/bootstrap/ez_setup.py)
So I try to downgrade pyopenssl and install Python cryptography module but both won't work

**Comment by medariox** [comment]
Shut down Medusa. Try enabling tornado logging in `config.ini` and look for logs in the `Logs` folder. It should give you more information about what's going on.

**Comment by oasisck** [comment]
thanks !
`SSLError: [X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:2798)`
I screwed up when managing crt and key for my subdomains
