### ISSUE TITLE
Yggtorrent provider : needs an url update again

### ISSUE THREAD

**Issue by Naokor** [pymedusa/Medusa#4842]
**Describe the bug**
The URL of yggtorrent just changed from ww2 to https://ww3.yggtorrent.is/
An update is needed for this provider. 

**Medusa (please complete the following information):**

Medusa Info: | Branch: develop Commit: 92f33c0a1f1fb65c94d6334a104167177d864407 
Version: v0.2.8 
Database: 44.11
Python Version: | 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.12.14-041214-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: | en_US.UTF-8

**Logs:**
<details>

```
2018-08-04 16:19:46 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Yggtorrent] :: [92f33c0] Invalid username or password. Check your settings
```
</details>

**Additional context**
The user/pass are correct in this case.

**Comment by medariox** [comment]
Fixed in develop.
