### ISSUE TITLE
Support Request: Change Scheduler Cycle-Times

### ISSUE THREAD

**Issue by annomatik** [pymedusa/Medusa#4846]
Hi!

Not a bug, but a support request.

Can you please tell me, how I can change the Cycle Time of the Backlog Search? (Screwdriver -> Server Status -> Scheduler). Currently, my Backlog Search takes around 11:30h, the cycle time is set to 12h, so if I add some more shows, I'm probably... screwed :-) I'd like to change it to 24h.

OS: Raspbian Stretch on a Raspberry PI 3B+
Branch: master / v0.2.8
Commit: f5973b28465246e67465d7d86bdc8aa74d13e659

Thanks!

**Comment by p0psicles** [comment]
Config - search settings -> Backlog search frequency
