### ISSUE TITLE
How Specials works ?

### ISSUE THREAD

**Issue by oasisck** [pymedusa/Medusa#4862]
For example, I have Escaflowne The Movie but Medusa doesn't detect it. I try to create a folder Specials or place the movie at the root of the series. Nothing works

**Comment by sharkykh** [comment]
For specials I usually have to add `Show Name S00Exx` where `xx` is the episode number on the specials season (on Medusa).
In any case Medusa will never download specials, but that way you can add the special episodes you already have.

**Comment by oasisck** [comment]
OK thanks it works
