### ISSUE TITLE
API Builder gives error "Unable to connect to Medusa"

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#4875]
**Describe the bug**
When I open the API builder from the link in the settings it will open it up but also generate a popup.
Everything seems to work as expected

**To Reproduce**
1. Goto General settings
2. Open the API builder: http://IP/apibuilder/
![image](https://user-images.githubusercontent.com/4103090/43779003-85455112-9a57-11e8-9a7f-2f1f771e450c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/4103090/43779054-a2b3dbec-9a57-11e8-9dbb-ecc13ec323a9.png)

**Medusa (please complete the following information):**

Medusa Info: | Branch:                     master                      Commit:                     f5973b28465246e67465d7d86bdc8aa74d13e659                      Version:                     v0.2.8                      Database:                     44.11
-- | --
Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2o  27 Mar 2018
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

**Logs:**

Firefox Developer tools
![image](https://user-images.githubusercontent.com/4103090/43779584-05ec7088-9a59-11e8-8b43-8121805c17a0.png)

**Comment by sharkykh** [comment]
The apibuilder was neglected a bit, but I noticed that and I believe it's already fixed on develop. If not, #4781 definitely fixes it.

**Comment by sharkykh** [comment]
Fixed on develop.
