### ISSUE TITLE
[Support] Docker, MedUSA, nzbToMedia

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#4882]
Hi Team,

Does anyone have an guide on how to get this to work. I have it working to a point but still i get this:

[13:08:24] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
[13:08:24] [INFO]::MAIN: No update needed
[13:08:24] [INFO]::MAIN: nzbToMedia Version:11.05 Branch:master (Linux 3.10.102)
[13:08:24] [WARNING]::MAIN: Failed to locate ffmpeg. Transcoding disabled!
[13:08:24] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
[13:08:24] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[13:08:24] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...

I have tried to mount folders, change path locations etc.. and still nothing. 

Any help please.

Thanks

**Comment by HPMSGEN8** [comment]
@medariox i am using this one - https://hub.docker.com/r/linuxserver/medusa/

**Comment by OmgImAlexis** [comment]
@HPMSGEN8 can we have the command you ran to create the container? Please remove any sensitive details though.

You can also try https://hub.docker.com/r/pymedusa/medusa/

**Comment by HPMSGEN8** [comment]
I used Docker on Synology. So it was an Download, Launch and setup. I did not run anything. to create it via commands.

Sure will give that one a go.

**Comment by OmgImAlexis** [comment]
Did you do something like this?

https://github.com/pymedusa/Medusa/wiki/Switching-your-Synology's-Medusa-to-the-new-repository

**Comment by HPMSGEN8** [comment]
Nope. i Installed Docker from Synology, Download the IMG then Set it up.

**Comment by OmgImAlexis** [comment]
@HPMSGEN8 that screenshot looks correct?

**Comment by HPMSGEN8** [comment]
Version is showing unknown is that correct ?

**Comment by HPMSGEN8** [comment]
All Solved Now :)

**Comment by HPMSGEN8** [comment]
@OmgImAlexis any luck on this at all on how i can fix this. if it is not a big deal and MedUSA will still update then i think we can maybe close this

**Comment by sharkykh** [comment]
@HPMSGEN8 
You mean the "Version: Unknown" issue?
It's happening because the Docker images don't have git installed and the version checker doesn't keep track of the version on source installs (non-git installs)

Related code:
https://github.com/pymedusa/Medusa/blob/27673758a541d8dd254698a8782fb347b6a8de2a/medusa/version_checker.py#L780-L782

Vs.

https://github.com/pymedusa/Medusa/blob/27673758a541d8dd254698a8782fb347b6a8de2a/medusa/version_checker.py#L401-L404

**Comment by HPMSGEN8** [comment]
@sharkykh Ok thanks. So even thou i have added GIT as an environment variable is there no way to solve this issue.

If it is not an issue and MedUSA will still update then i am happy and we can close this.

Thakns

**Comment by sharkykh** [comment]
>  So even thou i have added GIT as an environment variable is there no way to solve this issue.

Yes, because (I left this part out, apparently) you not only need git installed inside the docker container, but you also need the Medusa app folder to be a git repository, just like it would be if you were to clone it from github using git.

**Comment by HPMSGEN8** [comment]
Thanks

Will close this as well then :)
