### ISSUE TITLE
Medusa adds incorrect Season 01 folder for absolute numbered show.

### ISSUE THREAD

**Issue by EraYaN** [pymedusa/Medusa#4884]
**Describe the bug**
Take this show: https://www.thetvdb.com/series/knowing-bros
Like many of these shows these shows do not have defined seasons and release as E100 for example (maps to S2017E44). All items have the correct absolute numbers. Even though Medusa will refrain from actually taking the list of known episodes to match an absolute number to it and insists on making some season 1. This goes for many more long running shows aired in Asia.

**To Reproduce**
1. Add show knowing bros.
2. Have episode `Knowing Bros - E100.mp4`
3. Try to post process, fail because "not enough info"
4. Set "Anime" to true
4. Post-process, fail because now it's renamed as S01E100 instead of the correct S2017E44

**Expected behavior**
The absolute episode number should be used to look in the existsing episodes first and only if that does not exist may it be added to some random season.

**Screenshots**
Example of correct episodes. Second number is Absolute number as given by TheTVDB.
![Screenshot of correct episode](https://i.imgur.com/tLsnkPb.png)
And where they end up.
![Screenshot of where they end up](https://i.imgur.com/6mQxeBQ.png)

**Medusa (please complete the following information):**
 - OS: Windows Server 2016 64-bit
 - Branch: master
 - Commit: f5973b28465246e67465d7d86bdc8aa74d13e659

**Logs:**
```
2018-08-09 11:02:09 INFO     Thread_3 :: [f5973b2] Could not create/update meta files. Continuing with post-processing...
2018-08-09 11:02:09 INFO     Thread_3 :: [f5973b2] Unable to find episode S01E100 on TVDBv2... has it been removed? Should I delete from db?
2018-08-09 11:01:16 INFO     Thread_3 :: [f5973b2] New size: 3.64 GB
2018-08-09 11:01:16 INFO     Thread_3 :: [f5973b2] New file: D:\public\qBittorrent\Downloads Finished\Knowing Bros\Knowing Bros - E100.mp4
2018-08-09 11:01:16 WARNING  Thread_3 :: [f5973b2] Unable to parse season number for anime Knowing Bros, assuming absolute numbered anime with season 1
2018-08-09 11:01:15 INFO     Thread_3 :: [f5973b2] Processing D:\public\qBittorrent\Downloads Finished\Knowing Bros\Knowing Bros - E100.mp4
```
(in reverse)
</details>

And to answer the question asked by the log there, yes you should remove it. It does not exist...

**Additional context**
Some way to parse absolute numbered shows without the anime S01 behavior or entering all hundred+ episodes scene absolute values, would be sweet. It might still be useful as a fall back, but i the current state there is no easy way to quickly import all episodes without manually renaming them first, which make the whole medusa thing basically superfluous.

An example of a full release name is: `Knowing.Bros.E134.180630.1080p-NEXT`

EDIT: Adding the Scene Absolute number and turning on scene numbering also does not work, still season 1...

**Comment by dirkr07** [comment]
Same issue here!
Have it on an anime show.

- Absolute numbering is turned on
- Show is marked as anime
- All episodes are thrown under Season 1

![image](https://user-images.githubusercontent.com/10185229/61468202-2ea3be80-a97d-11e9-9f93-9d7683ea6ffa.png)

Other seasons are present and have the correct Absolute numbering

![image](https://user-images.githubusercontent.com/10185229/61468254-42e7bb80-a97d-11e9-9233-b492149dd43d.png)

**Comment by medariox** [comment]
This is expected. You can disable the folder creation for the show if don't want it.

**Comment by medariox** [comment]
The show has only one season. If you enable season folder creation it will be season 1 obviously.

**Comment by EraYaN** [comment]
@medariox This is not in fact "expected" (at least I hope not) and the previous comment is a different issue.

This show has since switched to the fairly popular "year" season of TheTVDB, but this does not fix the issue and just puts files in the non-existent S1 when it encounters any non-seasoned filenames. This defeats the purpose of the absolute numbering tickbox.

**Comment by medariox** [comment]
@EraYaN
The show is absolute numbered and you have season folders activated. It will put them in the season folder, because you have that option enabled. What did you expect instead? Why don't you just disable the option?
If it's a different issue it needs to be opened in a separate issue.
