### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: AMC Premiere

### ISSUE THREAD

**Issue by ictinc** [pymedusa/Medusa#4885]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.14.52-v7+-armv7l-with-debian-9.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/e39a577c92fae3bc41b827c1690b2261
### ERROR
<pre>
2018-08-10 03:36:01 ERROR    Thread_8 :: [f5973b2] Missing time zone for network: AMC Premiere
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added
