### ISSUE TITLE
[Feature Request] Please add subdivx.com as a subtitle source

### ISSUE THREAD

**Issue by SBI-boy** [pymedusa/Medusa#4899]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated because I always have to download subtitles in Spanish manually.

**Describe the solution you'd like**
Please Add subdivx.com as a subtitle source for spanish.

**Describe alternatives you've considered**
subtitulamos.tv & tusubtitulo.com could be good alternatives, but subdivx is better because it collects all the subtitles released on both portals and many others more and the pretimes are the best too.

**Additional context**
The only downside of subdivx is that all the subtitles files are compressed in .rar and the only way to distinguish between the release versions is by reading the description. 

Thank you
Regards

**Comment by p0psicles** [comment]
Thats something you should request with subliminal, not with us.
Maybe @fernandog can help.

**Comment by gticomunica** [comment]
Isn't subliminal an abandoned project?
