### ISSUE TITLE
Problem with YGGTORRENT because of url change : ww[3].yggtorrent.is

### ISSUE THREAD

**Issue by neo62248** [pymedusa/Medusa#4901]
**Describe the bug**
Problem when trying to download episodes with YGGTORRENT provider. 
I see that the URL of yggtorrent has changed since the last version of Medusa, from "ww2.yggtorrent.is" to "ww3.yggtorrent.is". 

**To Reproduce**
1. Snatch episode with YGGTORRENT provider.
2. The torrent file won't be downloaded, just downloading an empty file
3. Warning in Medusa and no file downloaded by the torrent client.

**Expected behavior**
Dev : Find a way please to configure the provider URL with the Medusa interface... please, to avoid multiples problems like this because many providers change their url frequently.

**Medusa (please complete the following information):**
 - OS: Windows 10, Medusa is installed in DSM 6 on Synology
 - Branch: master (up to date)

**Comment by p0psicles** [comment]
@medariox @supergonkas what you guys think? Is this a case "piratebay"?

**Comment by medariox** [comment]
Yeah, if they keep changing the URL every few weeks... It's getting really annoying.

**Comment by thib3113** [comment]
On my side, I use jackett, and configure yggTorrent in jackett . So I can "easily" change the url in jackett, whithout updating the configuration in medusa . ( I put `easily` in quote, because in fact, here is a bug, and we need to manually update the json file )

**Comment by p0psicles** [comment]
Dont sweat it. Well make the url field configurable. Its not much work. Just have to wait until someone gets to it.

**Comment by neo62248** [comment]
During this charming conversation, url of yggtorrent became ww4.yggtorrent.is.

**Comment by p0psicles** [comment]
Why are they changing it?

**Comment by neo62248** [comment]
It's to prevent dereferencing by Google.

**Comment by medariox** [comment]
The download works fine from the browser, even with the old domains. So it should also work for us. There must be an issue with our code somewhere.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/4925 
This will also make it work if they decide to change URL once again.

**Comment by medariox** [comment]
Fixed in develop.
