### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Cartoon Hangover

### ISSUE THREAD

**Issue by fexofenadine** [pymedusa/Medusa#4903]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.105-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/5266f6daf466f497d12685e98280e8b4
### ERROR
<pre>
2018-08-16 20:27:04 ERROR    Thread_0 :: [f5973b2] Missing time zone for network: Cartoon Hangover
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added
