### ISSUE TITLE
"Missing episodes range" - setting seems to have no effect

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#4918]
When you modify the above parameter (say form 7 to 14) , nothing seems to change in the Schedule page .

**To Reproduce**
1. change 7 to 14 days in general->interface configuration & save
2. View the Schedule page

**Expected behavior**
Schedule should show two weeks, but it does not

 - OS: x86
 - Branch: master 0.25

**Comment by medariox** [comment]
We don't provide support for old versions.

**Comment by rafi-d** [comment]
Can you do me a favor, and just look see if that setting works well in 0.28?
