### ISSUE TITLE
Box cover

### ISSUE THREAD

**Issue by ashman70** [pymedusa/Medusa#4931]
For the show Black Mirror, when I view my shows with small box covers this box cover for this show appears to be in a foreign language, instead of the desired language English. When I edit the show, it appears the same, when I click on it however it opens large and is in English. Is there a way to change box covers? See attachments.
![black mirror l](https://user-images.githubusercontent.com/27771421/44370151-f4991680-a4a6-11e8-8077-53de7f94a69b.jpeg)
![black mirror s](https://user-images.githubusercontent.com/27771421/44370152-f4991680-a4a6-11e8-87b9-55dcc4865a8d.jpeg)

**Comment by medariox** [comment]
Which indexer? Looks fine here with TheTVDB.

**Comment by p0psicles** [comment]
Also remove any poster in your shows folder. Might have been saved there as metadata. Then do full update

**Comment by ashman70** [comment]
So here is the weird thing, that poster with what looks like Russian writing is not in my actual show folder.....I don't know where it's coming from or where it resides.
