### ISSUE TITLE
Copy templates (mako) using Webpack

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#4953]
Instead of:
```
yarn dev
yarn gulp sync
```
Just use:
```
yarn dev
```

I have the code in a branch with other changes, just need to isolate it and open a PR.

**Comment by p0psicles** [comment]
That would be awesome. Still much work? Because you added milestone 0.2.10?

**Comment by sharkykh** [comment]
Not much work, no.
I just added 0.2.10 for now to try to finish 0.2.9 first.
I will look at PRing it later today.
