### ISSUE TITLE
You are running Vue in development mode

### ISSUE THREAD

**Issue by ngosang** [pymedusa/Medusa#4955]
**Describe the bug**
I can see the following message in the browser console (Firefox):
```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

**To Reproduce**
1. Press F12
2. Open Medusa home page

**Expected behavior**
By default, Vue should be in production mode

**Medusa (please complete the following information):**
 - Branch: master

**Comment by p0psicles** [comment]
Yes your right. I think @sharkykh already has a branch. Or at least a check its not in dev mode when creating the release.

**Comment by sharkykh** [comment]
Will be fixed by next version, as we moved to Webpack since last version.
It will build Vue in production mode for the master branch.

**Comment by OmgImAlexis** [comment]
@sharkykh let's make sure we're properly using sourcemaps when we do the production build otherwise it's going to be a pain to try and debug client errors.

**Comment by sharkykh** [comment]
@OmgImAlexis 
We can set `devtool: 'source-map'` when it's a production built. Is this what you mean?
