### ISSUE TITLE
Implement multi-threading in the API v2 handler

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#4963]
For reference, the current WebHandler:
https://github.com/pymedusa/Medusa/blob/1b62217a9ea7dbceae924d8f3dd2bcb46caaecda/medusa/server/web/core/base.py#L211-L262

**Comment by p0psicles** [comment]
As long as we support python2.7 well just have to mimic the WebHandler implementation.

**Comment by sharkykh** [comment]
@p0psicles 
Yes well I tried that a few months ago and couldn't figure out a way to make it work. :disappointed:

**Comment by sharkykh** [comment]
This is based on what I tried to do back then, I made some changes and it seems to work now, although I'm not really sure how to stress test the API v2 handler.
https://github.com/pymedusa/Medusa/tree/feature/apiv2-multithread

I also don't like the changes I had to make to the `get`, `post`, etc. methods' names.

**Comment by p0psicles** [comment]
I tested it. And indeed it works fine.
I used postman and configured multiple api calls: `/api/v2/series/tvdb281662`
Then I put a breakpoint in the `Series.to_json()` method.
And now it's at least not blocking anymore after the first call.

**Comment by medariox** [comment]
Implemented: https://github.com/pymedusa/Medusa/pull/4970
