### ISSUE TITLE
Sorting, Filtering and Column Selection Broken on Home Page

### ISSUE THREAD

**Issue by Thraxis** [pymedusa/Medusa#4965]
**Describe the bug**
In the current Development Version Sorting, Filtering and Column Selection is Broken on Home Page

**To Reproduce**
Open the Home page of Medusa...  attempt to sort on a column, Attempt to Filter Show List, Attempt to Select columns displayed

**Expected behavior**
Expected behavior is for those items to work

**Screenshots**

**Medusa (please complete the following information):**
 - OS: [developmet docker based off of linuxserver.io docker]
 - Branch: [develop]
 - Commit: 565fa304819b38ae8de1ecb11c35ac0cdf748d32

**Comment by sharkykh** [comment]
Ah, scratch that, confirmed:
Home page is broken when the split home in tabs option is enabled.
Thank you for reporting!

**Comment by sharkykh** [comment]
Should be fixed now.
