### ISSUE TITLE
No module named _bsddb

### ISSUE THREAD

**Issue by eximo84** [pymedusa/Medusa#4971]
**Describe the bug**
Adding recommended shows using Trakt or IMDB list i get an exception No module named _bsddb

**To Reproduce**
1. Go to 'Shows"
2. Click on '.Add Recommended Shows'
3. Click on 'Add from Trakt List'

**Expected behavior**
Trakt or IMDB list to show a list of shows

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Docker
 - Branch: Master
 - Commit: f5973b28465246e67465d7d86bdc8aa74d13e659 

**Logs:**
<details>

```
<-- Please replace this whole line with your logs -->
```
</details>

**Additional context**

**Comment by medariox** [comment]
Which Docker image are you using?

**Comment by eximo84** [comment]
This one https://hub.docker.com/r/linuxserver/medusa/

**Comment by p0psicles** [comment]
#5131

**Comment by sharkykh** [comment]
Which version of the docker image are you using? Is it a version prior to 29.11.17 (not included)?

**Comment by medariox** [comment]
I'd like to see a full debug with the error if possible.

**Comment by sharkykh** [comment]
@medariox Take a look at either of the issues @p0psicles linked as duplicates, they all share the same error.

----

Python issue report:
https://bugs.python.org/issue2329

*I think* what this means is,
the availability of `bsddb` (which is, by-the-way, **removed** in Python 3) is directly affected by the availability of the Berkeley DB linux library when Python is compiled from source (when installing Python)...

**Comment by p0psicles** [comment]
@sharkykh where did you see it's removed in python 3?
Also it's used by dogpile. So that would mean that dogpile would not work with python 3?

**Comment by sharkykh** [comment]
1. https://docs.python.org/2/library/bsddb.html
2. Might have to remove cache when upgrading existing installations to py3, but it should still work.

**Comment by p0psicles** [comment]
https://www.jcea.es/programacion/pybsddb.htm

'Python 3.x doesn't include native Berkeley DB support, you need to install this library by your own.`

**Comment by sharkykh** [comment]
Correct. That refers to https://pypi.org/project/bsddb3/. I haven't tested that though.

@medariox It's possible your right about that then, because `bsddb3` includes the C files.
![image](https://user-images.githubusercontent.com/10238474/45215560-7f02b800-b2a6-11e8-89c2-f7d8fca9eb2c.png)

**Comment by p0psicles** [comment]
hmm, I don't get this. It's allot of work to add bsddb3 your self. You'll have to add all kinds of whl links, for the compiled libraries.

I also think we even are not using bsddb. It's just imported.

**Comment by p0psicles** [comment]
Python3 uses: https://pymotw.com/3/dbm/
As apposed to python2: anydbm

```` 
        # TODO: make this configurable
        if compat.py3k:
            import dbm
        else:
            import anydbm as dbm
```

**Comment by sharkykh** [comment]
> I also think we even are not using bsddb. It's just imported.

Dogpile does. We're using the file backend which is where you took the code in the comment above from.
So we are:
```
C:\Medusa\Data\cache>  python -c "import whichdb; print whichdb.whichdb('application.dbm')"
dbhash
```

[`dbhash`](https://docs.python.org/2/library/dbhash.html) imports and uses `bsddb`

**Comment by p0psicles** [comment]
dogpile uses dumbdbm on python3. As on python3 dbm falls back to dumbdbm. I read there are allot of issues whith that.

**Comment by sharkykh** [comment]
@eximo84 
Can you please try shutting down Medusa and simply removing the files in `/config/cache`?
(Then start Medusa and try to list recommended shows)

**Comment by udochrist** [comment]
Tested that. Seems to do the trick.

**Comment by udochrist** [comment]
Dont know if its related:

when i now click on a show to see the eps medusa freezes. theres nothing in the application log. The docker log however shows
```
2018-09-07 18:16:29 | stderr | UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 3: invalid start byte
2018-09-07 18:16:29 | stderr | return codecs.utf_8_decode(input, errors, True)
2018-09-07 18:16:29 | stderr | File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
2018-09-07 18:16:29 | stderr | data = self.sock.recv(8192).decode('UTF-8')
2018-09-07 18:16:29 | stderr | File "/app/medusa/ext/adba/aniDBlink.py", line 95, in run
2018-09-07 18:16:29 | stderr | Traceback (most recent call last):
2018-09-07 18:16:29 | stderr | ERROR:root:Bad response from server: 'utf8' codec can't decode byte 0x9c in position 3: invalid start byte
2018-09-07 18:16:20 | stderr | 2018-09-07 20:16:20 DEBUG    Thread_6 :: [db3d9d7] No XEM data for show ID 305719 on tvdb
2018-09-07 18:16:20 | stderr | 2018-09-07 20:16:20 DEBUG    Thread_6 :: [db3d9d7] User-Agent: Medusa/0.2.9 (Linux; 3.10.105; 4fbdf640-b2c9-11e8-9863-0242ac130004)
```

ideas greatly appreciated as i need to shutdown and restart

**Comment by sharkykh** [comment]
I think @p0psicles is working on a fix for that in #5125

**Comment by udochrist** [comment]
i can reproduce that each time i open the show. i'll check if #5125 fixes this once i can get my hands on it. Thanks for the fast response!!

**Comment by eximo84** [comment]
Can confirm deleting cache has fixed my issue. I’ve also updated for good measure. Thanks for the help.
