### ISSUE TITLE
Scan File Quality on Bulk Import

### ISSUE THREAD

**Issue by Phillips57** [pymedusa/Medusa#4977]
When I "Add Existing Shows" they are always added as Unknown Quality, and episodes that where perfectly good are re-downloaded.

I'd like Medusa to either Scan the Quality on Adding/or have the ability to Scan existing files after, to set the quality.

This way If I need to re-Install Medusa or Rebuild my Shows list I will only download shows that are below my preferred Quality setting or missing

**Comment by medariox** [comment]
How are your files named like?

**Comment by Phillips57** [comment]
Thier named "%SN - S%0SE%0E - %EN"
Show Name - S02E03 - Ep Name.ext

**Comment by medariox** [comment]
Medusa can't de
