### ISSUE TITLE
Update feedparser

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#4991]
Update the `feedparser` library:
https://github.com/kurtmckee/feedparser/tree/develop

Diff from current vendored commit ([`f1dd1bb923ebfe6482fc2521c1f150b4032289ec`](https://github.com/pymedusa/Medusa/blob/0e800bfd9e9b89f2c529dcb9b7a677b5e4d7c6e7/requirements.txt#L15)):
https://github.com/kurtmckee/feedparser/compare/f1dd1bb923ebfe6482fc2521c1f150b4032289ec...develop

**Comment by ngosang** [comment]
Related to #4980 I added sgmllib for python3 compatibility but I didn't change feedparser. This should work too.
> [Python3] Add lib3/sgmllib package

**Comment by sharkykh** [comment]
@ngosang `sgmllib` would still be needed for Python 3 IMO.

BTW I don't know if you realized the difference between `lib/` and `ext/` - `ext` is for packages using official versions that can be installed using `pip` and unmodified packages.
`lib` is for custom or modified packages (that cannot be installed using pip, so git commits of repos with `setup.py` are okay to go into `ext/`.

Hopefully this makes sense. So `sgmllib` should be in `ext3`.

**Comment by ngosang** [comment]
@sharkykh yes, I will keep it.
I didn't know about lib/ext. I'm going to rework the PR to follow that guidelines.
