### ISSUE TITLE
Not finding subtitles for MAoS

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#505]
@ratoaq2 
Also in sublimal cli

it should also search for: u"marvels agents of s.h.i.e.l.d." but its not

```
Downloading subtitles  [####################################]  100%  Marvels.Agents.of.S.H.I.E.L.D.S03E18.The.Singularity.1080p.WEB-DL.DD5.1.H.264-MAoS.mkv
INFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages set([<Language [pt-BR]>])
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.providers.legendastv:Logging in
DEBUG:subliminal.providers.legendastv:Logged in
INFO:subliminal.providers.legendastv:Searching title u'marvels agents of s h i e l d'
DEBUG:subliminal.providers.legendastv:Found 0 titles
INFO:subliminal.providers.legendastv:Searching title u"marvel's agents of s.h.i.e.l.d."
DEBUG:subliminal.providers.legendastv:Found 0 titles

```

**Comment by p0psicles** [comment]
Shouldn't this be reported upstream?

**Comment by fernandog** [comment]
Its a medusa refiners issue. Rato developed that.

**Comment by p0psicles** [comment]
Ok, @ratoaq2 can we assign this to you?

**Comment by ratoaq2** [comment]
It's not a medusa issue. Legendas.tv site registered this series without marvel's in the name. We could at least start a discussion about it at subliminal repo.

**Comment by fernandog** [comment]
@ratoaq2 problem is when searching using "marvels", it uses "s h i e l d" instead of "s.h.i.e.l.d.", so it doesn't find.

**Comment by ratoaq2** [comment]
Sorry, I  clicked the close button by mistake.

**Comment by ratoaq2** [comment]
If you see the logs, it searches without ' and . And it also searches with them.

marvels agents of s.h.i.e.l.d
http://legendas.tv/legenda/sugestao/marvels%20agents%20of%20s.h.i.e.l.d

marvel's agents of s.h.i.e.l.d
http://legendas.tv/legenda/sugestao/marvel's%20agents%20of%20s.h.i.e.l.d

marvels agents of s h i e l d
http://legendas.tv/legenda/sugestao/marvels%20agents%20of%20s%20h%20i%20e%20l%20d

marvel's agents of s h i e l d
http://legendas.tv/legenda/sugestao/marvel's%20agents%20of%20s%20h%20i%20e%20l%20d

Doesn't matter. All searches return 0 results.
Only agents of s.h.i.e.l.d returns results:
http://legendas.tv/legenda/sugestao/agents%20of%20s.h.i.e.l.d
