### ISSUE TITLE
Add BTDB.to search engine

### ISSUE THREAD

**Issue by ngosang** [pymedusa/Medusa#5084]
Add https://btdb.to/
It has millions of torrents, stable domain, clean api, https...

Jackett implementation => https://github.com/Jackett/Jackett/blob/060972475f13ffe59fcc09c51ffe91a547a29029/src/Jackett.Common/Definitions/btdb.yml

qBittorrent implementation => https://github.com/qbittorrent/search-plugins/blob/master/nova3/engines/btdb.py

**Comment by medariox** [comment]
Added with https://github.com/pymedusa/Medusa/pull/5129 🎉
