### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: DC Universe

### ISSUE THREAD

**Issue by jasimancas** [pymedusa/Medusa#5093]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.16.0-0.bpo.2-amd64-x86_64-with`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@929d3c8c1b21cd679d0833f4dd52541ceb8d38bc
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-08-31 10:53:19 ERROR    Thread_0 :: [929d3c8] Missing time zone for network: DC Universe
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/5756a85ca5e7904179479d40a57d4184e20a5ad7
