### ISSUE TITLE
[Feature request] Add a button to launch postprocessing manually

### ISSUE THREAD

**Issue by ngosang** [pymedusa/Medusa#5094]
I have been looking the whole UI but I didn't found it.
Maybe in Mass Update?
Maybe in the server status to manually trigger scheduled tasks?

**Comment by medariox** [comment]
This?

![manualpp1](https://snapr.pw/i/949d576bcd.png)

![manualpp2](https://snapr.pw/i/b15fc5eead.png)

**Comment by ngosang** [comment]
Yes. I didn't see...
Shouldn't this option be in Manage tab?

**Comment by ngosang** [comment]
Closed in favor of #5133
