### ISSUE TITLE
Replace 'synchronousdeluge' with 'deluge-client'

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#5097]
### Replace `synchronousdeluge` with `deluge-client`

Related to #4980

- [`synchronousdeluge`](https://github.com/pymedusa/Medusa/tree/f5973b28465246e67465d7d86bdc8aa74d13e659/lib/synchronousdeluge) (custom lib)
- [`deluge-client`](https://pypi.org/project/deluge-client) ([github](https://github.com/JohnDoee/deluge-client))

**Comment by sharkykh** [comment]
On the subject of the `deluge` torrent client, we have two clients:
- `deluge` - uses the web ui
- `deluged` - uses `scgi://` protocol and the `RPC` client interface via `synchronousdeluge`

### Is there a reason to keep both?
Related to point no. 5 of https://github.com/pymedusa/Medusa/pull/5091#issuecomment-419630187:
> 5. We support `deluge` (deluge web ui) and `deluged` (deluge daemon) as different bittorrent clients. IMHO we should support only the deluge web ui and remove `synchronousdeluge` package. I mean, the user is already using an UI to manage the downloads. Maybe he uses the GUI instead of the webui, but I don't think installing the web ui is a too hard... Related #5097

**Comment by medariox** [comment]
Replaced synchronousdeluge with deluge-client, see https://github.com/pymedusa/Medusa/pull/6279
