### ISSUE TITLE
API: Change `show.seasons` structure

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#5121]
Related to [this discussion](https://github.com/pymedusa/Medusa/pull/5087#discussion_r215536755).

### Option 1:
An object where the keys are the season numbers (as strings because JSON doesn't support key indices)
```js
"show": {
    "seasons": {
        "0": [
            { episode1 (object) },
            // ...
            { episodeN (object) }
        ],
        "1": {
            { episodeN (object) }
        },
        // ...
    }
}
```

### Option 2:
An array of objects
```js
"show": {
    "seasons": [
        {
            "season": 0,
            "episodes": [
                { episode1 (object) },
                // ...
                { episodeN (object) }
            ]
        },
        { season1 (object) },
        // ...
    ]
}
```

**Comment by p0psicles** [comment]
I would go with option 1. As its a little unlogic to get a specific season having to loop over them.

**Comment by p0psicles** [comment]
I had to search a little. But it seems we share an opinion.

**Comment by sharkykh** [comment]
@p0psicles Yeah the first option was actually my second suggestion, so I like do it better than the other option.

**Comment by sharkykh** [comment]
Ughh...
`patternProperties` isn't supported by OpenAPI (both 2.0 and 3.0).
If it isn't supported, we can't really use in the API definition, which is a problem...
