### ISSUE TITLE
[Feature request] Improve history layout in webui

### ISSUE THREAD

**Issue by ngosang** [pymedusa/Medusa#5158]
Ok, it's a minor thing this time but I'm perfectionist.
Improve history layout in webui, looks ugly to me.

![imagen](https://user-images.githubusercontent.com/10577978/45251941-f9871280-b34e-11e8-8440-bb5b9e985650.png)

**Comment by OmgImAlexis** [comment]
@ngosang please don't open feature requests unless you actually have a feature "it's ugly" doesn't really help anyone and just wastes our time closing the issue.
