### ISSUE TITLE
Torrentleech Broken since 0.2.9 update. 

### ISSUE THREAD

**Issue by maticks81** [pymedusa/Medusa#5171]
After updating to 0.2.9 from 0.2.8.
Torrentleech now responds back with [TorrentLeech] :: [db3d9d7] Invalid username or **********. Check your settings.

Tried reapplying the password and relogging in the website seems to be fine something must have changed in the provider plugin.

**Comment by sharkykh** [comment]
I don't use torrentleech but have an account, I checked, and the code I wrote had a bug in the search code.
I will fix it.

However I was able to login successfully.
Can you please:
1. Enable debug logs in the general config page
2. Try searching TorrentLeech again,
3. Get the debug logs from View Logs page (you need to change the level to DEBUG before you copy them)

**Comment by medariox** [comment]
All good here with Torrentleech. Does your username/password contain non-ASCII chars?

**Comment by maticks81** [comment]
uppercase and lowercase with numbers only but i have a long password.
it was working pre the release of 0.2.9

**Comment by maticks81** [comment]
Just rolled back to 0.2.8 and its working, thought i had to reapply my password in medusa for the torrentleech search provider page.
i did try reapplying the password in 0.2.9 but that didnt work.
Is there a password length difference?

2018-09-10 10:06:03 INFO     SEARCHQUEUE-FORCED-74768 :: [4614efc] Downloading The.Block.AU.S14E21.720p.HDTV.x264-ORENJI with 24 seeders and 1 leechers and size 1.12 GB from TorrentLeech
2018-09-10 10:06:03 INFO     SEARCHQUEUE-FORCED-74768 :: [TorrentLeech] :: [4614efc] Picked The.Block.AU.S14E21.720p.HDTV.x264-ORENJI as the best result.
2018-09-10 10:06:03 INFO     SEARCHQUEUE-FORCED-74768 :: [TorrentLeech] :: [4614efc] Quality of The.Block.AU.S14E21.HDTV.x264-FQM is SDTV
2018-09-10 10:06:03 INFO     SEARCHQUEUE-FORCED-74768 :: [TorrentLeech] :: [4614efc] Quality of The.Block.AU.S14E21.720p.HDTV.x264-ORENJI is 720p HDTV
2018-09-10 10:05:58 INFO     SEARCHQUEUE-FORCED-74768 :: [TorrentLeech] :: [4614efc] Performing episode search for The Block

**Comment by sharkykh** [comment]
> Is there a password length difference between 0.2.9 and 0.2.8?

I don't think so.

> i did try reapplying the password in 0.2.9 but that didnt work, i tried a few times.

Hmm. Can you try:
1. Switch back to 0.2.9
2. Disable the [password encryption option](https://user-images.githubusercontent.com/10238474/45271676-61ee0500-b4b1-11e8-8ab4-5e168e599bb9.png) (General config -> Advanced)
3. Re-enter your username and password and save the config
4. Verify [the values are correct in `config.ini`](https://user-images.githubusercontent.com/10238474/45271785-0708dd80-b4b2-11e8-8176-b68b1f851e62.png) (in your Medusa's data dir)
5. If they are correct, try TorrentLeech again. If they are not, tell us.
6. If TorrentLeech works, re-enable the password encryption option and save.
7. Try TorrentLeech again, let us know if it works at this point or not.

**Comment by maticks81** [comment]
with password encryption off and reapplying it seems to be working on 0.2.9.

**Comment by sharkykh** [comment]
Does it still work after you restart Medusa?

**Comment by jefferymcjefferson** [comment]
I am encountering the same problem with v0.2.10. I tried changing my password a few times, and had no luck.

**Comment by maticks81** [comment]
@jefferymcjefferson what i tried seem to work.
Downgrade to v0.2.9, untick encryption option in general config, restart medusa
go into the Torrentleech password section type in something else that isn't your password save it.
then type in your real password and save it again.
check the config.ini file you should see the correct password.
upgrade to v0.2.10 now it works properly.

**Comment by jefferymcjefferson** [comment]
Hhmmm, this is interesting. So my 0.2.10 install was a clean install (minus the sickbeard.db). After doing at least one service reboot (pretty sure I did several), this search seems to be working. I made no changes and no rollbacks.
