### ISSUE TITLE
Infinite loading / can't access any anime or tv show web page since 0.2.9

### ISSUE THREAD

**Issue by tomzic59** [pymedusa/Medusa#5174]
**Describe the bug**
Infinite loading / can't access any anime or tv show web page since 0.2.9

**Expected behavior**
Access to these pages like before :)

**Medusa (please complete the following information):**
 - OS: Debian Jessie
 - Branch: master 
 - Commit: db3d9d767bbf3fe7c365df20d92099b0cbbd91b4

**Comment by OmgImAlexis** [comment]
Duplicate: https://github.com/pymedusa/Medusa/issues/5170
