### ISSUE TITLE
Infinite loading / can't access any anime or tv show web page since 0.2.9 [EDIT]

### ISSUE THREAD

**Issue by tomzic59** [pymedusa/Medusa#5182]
Describe the bug
Infinite loading / can't access any anime or tv show web page since 0.2.9
When I click on a show, the page is loading again and again...
EDIT : The 0.2.10 hotfix did not resolve the issue !

Expected behavior
Access to these pages like before :)

Medusa (please complete the following information):
OS: Debian Jessie
Branch: master
Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6

**Comment by p0psicles** [comment]
Going into displayShow?
And each show. Or only anime?

**Comment by p0psicles** [comment]
Ow fixed?

**Comment by tomzic59** [comment]
I think i found the reason why ... (certainly my bad ftm)
I will tell you tonight !

**Comment by tomzic59** [comment]
Indeed, the network folder on which the shows are stored was unavailable ...
When I restarted it, everything is back to normal.

Sorry for the double post

Suggestion: It may be necessary to warn the user with a notification message.
