### ISSUE TITLE
Telegram notification broken since 28-08-2018

### ISSUE THREAD

**Issue by zflash** [pymedusa/Medusa#5189]
Branch/Commit: Master 4614efc77151ded92ef458a09dec39f8bd5acfc6 
OS: Windows 10
Browser: Chrome
What you did: Nothing
What happened: Telegram suddenly stopped working
What you expected: Notifications

```
Error sending Telegram notification: Unknown IO error: HTTP Error 403: Forbidden
```
This is what happend when testing. Same error also appears on my current Sickrage install. everything was fine until August 28th.

**Comment by p0psicles** [comment]
Works fine here

**Comment by p0psicles** [comment]
Maybe its blocked in your country?

**Comment by zflash** [comment]
That's weird. I'm in the Netherlands. Nothing is blocked here (Well, except TPD). Any way on how to check this? I can adjust the bot just fine

**Comment by zflash** [comment]
Checked it with an custom API; My provider is being blocked by Telegram. Will use an VPN in the future. Thanks for the direction p0psicles!
