### ISSUE TITLE
Mass Redownload with Duplicates

### ISSUE THREAD

**Issue by jefferymcjefferson** [pymedusa/Medusa#5225]
**Describe the bug**
Even though I've got all of my TV shows set as Skipped, Medusa just did a *massive* redownload of a ton of stuff. I chewed through terabytes last night. Even worse, it started grabbing duplicates of the exact same seasons. This is going to hurt my ratio pretty bad.

**To Reproduce**
???

**Expected behavior**
Medusa not to download anything while set to Skipped.

**Screenshots**
Here's an example of it grabbing three of the same season (I'm aware of the fourth not being the same).

![image](https://user-images.githubusercontent.com/28831302/45597799-6cffd400-b98e-11e8-8a45-e1d09c688fe0.png)

**Medusa (please complete the following information):**
 - OS: CentOS 7
 - Docker Image: docker.io/linuxserver/medusa de6454b8f283
 - Branch: master
 - Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6
 - Version: v0.2.10

**Logs:**
I apologize for not selecting the right snippet of logs, but I don't know where the issue is. I believe it started around line 102.

[medusa.log](https://github.com/pymedusa/Medusa/files/2386690/medusa.log)

**Additional context**
These were previously downloaded shows. If my storage had dropped off temporarily (which I expect may have occurred), I would expect that a show that changed from present to absent would revert back to the Skipped behavior.

**Comment by medariox** [comment]
Any chance you had the whole first season of `The Walking Dead` as `Wanted`?

**Comment by jefferymcjefferson** [comment]
I had 0 items marked as Wanted in my library. I'm afraid that, if a previously found item is suddenly gone, it shows up as Wanted, instead of skipped.

**Comment by medariox** [comment]
That seems unlikely, I wouldn't worry about that. Please enable debug logging and make sure to keep an eye on your downloads. If it happens again it would be really helpful if you could post the debug logs.

**Comment by jefferymcjefferson** [comment]
I'll enable debugging and see if I can't replicate this behavior. Thank you.
