### ISSUE TITLE
Set snatched to Failed after X hours

### ISSUE THREAD

**Issue by sufd4** [pymedusa/Medusa#5226]
Sometimes with certain failures it's not reported back to Medusa correctly and an episode is forever stuck as 'Snatched'. Can you have a setting to allow it to automatically change that to failed and search again if it doesn't complete after a certain number of hours?

Similar to this option on SickRageTV 'the feature/option can be found under search clients called '**Enable failed snatch handling** '

Thanks

**Comment by a10kiloham** [comment]
I'd find this useful

**Comment by sunnyd71** [comment]
Thanks. Is there any timeline for implementing active checking in sab? (or where it falls within your priorities)

**Comment by p0psicles** [comment]
With the currently activity. Maybe early 2019. Or we get some new contributors.
