### ISSUE TITLE
Support Request: Update

### ISSUE THREAD

**Issue by annomatik** [pymedusa/Medusa#5238]
**Describe the bug**
Hi! Just found this message in my log:

"2018-09-20 00:35:32 WARNING  CHECKVERSION :: [f5973b2] We can't proceed with the update. New update has a new DB version. Please manually update"

So... how do I manually update?

Thanks!

**Comment by medariox** [comment]
You can update manually with git.
`cd` to Medusa's main folder (it's the one that contains `start.py`) and run a `git pull`. Restart Medusa and you should be up to date.

**Comment by medariox** [comment]
I'm going to assume you solved this. If not just post again.

**Comment by annomatik** [comment]
Thanks, that worked! Sorry for not replying earlier, I've been offline a couple of weeks...
