### ISSUE TITLE
ERROR:root:Bad response from server: 'utf8' codec can't decode byte 0x9c in position 3: invalid start byte

### ISSUE THREAD

**Issue by GrumpyM0nk** [pymedusa/Medusa#5242]
**Describe the bug**
When i try to edit a show within my anime section medusa hangs and i have to restart the docker.

**To Reproduce**
1. Go to '..anime.'
2. Click on 'any anime show.'
3. Click on edit and medusa hangs until i restart the docker'

Platform: Docker running on top of Unraid
Branch: master
Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6
Version: v0.2.10
Database: 44.1
Python Version: | 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
SSL Version: | LibreSSL 2.7.4
OS: | Linux-4.14.49-unRAID-x86_64-with
Locale: | Unknown.Unknown

**Logs:**
```
ERROR:root:Bad response from server: 'utf8' codec can't decode byte 0x9c in position 3: invalid start byte

Traceback (most recent call last):
File "/app/medusa/ext/adba/aniDBlink.py", line 95, in run
data = self.sock.recv(8192).decode('UTF-8')
File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 3: invalid start byte
```

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5125
