### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: CBS All Access

### ISSUE THREAD

**Issue by rtrevino70** [pymedusa/Medusa#5247]
### INFO
**Python Version**: `2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`
**Operating System**: `Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/f83d92cd06ee0c1b1dddaeeabf8c6d25
### ERROR
<pre>
2018-09-20 22:25:22 ERROR    Thread_0 :: [4614efc] Missing time zone for network: CBS All Access
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
> CBS All Access

Already in the list https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L356

**Comment by Dale-J** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/05b10e39960362e01209f02c4807de77
### ERROR
<pre>
2018-10-24 23:02:46 ERROR    Thread_1 :: [4614efc] Missing time zone for network: CBS All Access
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
