### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: HBO

### ISSUE THREAD

**Issue by rtrevino70** [pymedusa/Medusa#5259]
### INFO
**Python Version**: `2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`
**Operating System**: `Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/316668e6521fa56c8b3ffa96a5c79d5b
### ERROR
<pre>
2018-09-20 22:25:21 ERROR    Thread_0 :: [4614efc] Missing time zone for network: HBO
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
> HBO

Already in the list https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L915

**Comment by taktlos79** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.8-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/10d304769ba0d3a48e65611eee2eef3f
### ERROR
<pre>
2018-10-19 21:14:51 ERROR    Thread_1 :: [4614efc] Missing time zone for network: HBO
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Dale-J** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/28f57d10a8004a5ce7cef5fe0242fbac
### ERROR
<pre>
2018-10-24 23:02:45 ERROR    Thread_1 :: [4614efc] Missing time zone for network: HBO
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
