### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Discovery Channel

### ISSUE THREAD

**Issue by rtrevino70** [pymedusa/Medusa#5263]
### INFO
**Python Version**: `2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`
**Operating System**: `Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/42e9a0e258d85d5a27ede5b22c36ab8f
### ERROR
<pre>
2018-09-20 22:25:21 ERROR    Thread_0 :: [4614efc] Missing time zone for network: Discovery Channel
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
> Discovery Channel

Already in the list https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L610
