### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: ABC (US)

### ISSUE THREAD

**Issue by rtrevino70** [pymedusa/Medusa#5267]
### INFO
**Python Version**: `2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`
**Operating System**: `Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/dbd9400362e1f85e7d339df3689c84f3
### ERROR
<pre>
2018-09-20 22:25:21 ERROR    Thread_0 :: [4614efc] Missing time zone for network: ABC (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
> ABC (US)

Already in the list https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L52

**Comment by Dale-J** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/3f97a20e48df8e0048caba106979745e
### ERROR
<pre>
2018-10-24 23:02:45 ERROR    Thread_1 :: [4614efc] Missing time zone for network: ABC (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
