### ISSUE TITLE
NFO and TBN all greyed out

### ISSUE THREAD

**Issue by bluelavalamp** [pymedusa/Medusa#5282]
**Describe the bug**
I noticed on my Shows Overview page that the column for NFO and TBN are all greyed out even though there is an .nfo file and covers, banner, posters, thumbnails, or fanart in the folder.  I then went to the wiki to read about what each column is for and I noticed that the screenshot in the wiki also the entire column for NFO and TBN are greyed out (Wiki "Show settings explained" page)

**To Reproduce**
Click on a show to see it's Show Overview page.

**Expected behavior**
I would have expected some of the icons to not be greyed out since the folder contains the information that the wiki says the icon indicates is present.

**Medusa (please complete the following information):**
 - OS: Slackware -current
 - Branch: master
 - Commit: not how to find this info

**Comment by medariox** [comment]
The NFO and TBN must have the same name as the episode they are for.

**Comment by bluelavalamp** [comment]
Ok, so I've confirmed from the file system that the show and the nfo are named exactly the same but the NFO icon is still greyed out.

**Comment by medariox** [comment]
Do you have the setting enabled in `Post Processing > Metadata`?
