### ISSUE TITLE
Search Specific Languages?

### ISSUE THREAD

**Issue by gelsas** [pymedusa/Medusa#5283]
Hello, 

is it possible to let Medusa search for episodes of Shows in specific languages. 

For example I would like to get the show "The Example Show" in English (most important), Spanish (less important) and German (less important). 

How could I make sure that it check for other languages besides English?

**Comment by medariox** [comment]
Add the name of the show in various languages as scene exception.

**Comment by medariox** [comment]
Go to the desired show page > Edit > Advanced > Scene Exception

If the names are the same in both languages you don't need to add the scene exception.

**Comment by gelsas** [comment]
I added German for example as required word but it still lists english versions (the required word is not even in it)

**Comment by p0psicles** [comment]
Manual search you pick your self. So then you pick the ferman result
