### ISSUE TITLE
This show isn't in your list, you need to add it before post-processing an episode

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#5284]
**Describe the bug**
Unable to import Maniac episode stating that it is not in my show list, while other episodes have been imported with the same naming schema.

**Screenshots**
The one selected does want to go in while the rest processed okay
![image](https://user-images.githubusercontent.com/4103090/45916415-20246d80-be66-11e8-9150-ff322ce714b0.png)

**Medusa (please complete the following information):**

Medusa Info: | Branch:                 master                  Commit:                 4614efc77151ded92ef458a09dec39f8bd5acfc6                  Version:                 v0.2.10                  Database:                 44.12
-- | --
Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2o  27 Mar 2018
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

**Logs:**
<details>

```
Processing path: C:\DATA\Private\Torrent\PROCD\TV\Maniac.2018.S01E03.INTERNAL.1080p.WEBRip.X264-DEFLATE[rarbg]
Processing folder: C:\DATA\Private\Torrent\PROCD\TV\Maniac.2018.S01E03.INTERNAL.1080p.WEBRip.X264-DEFLATE[rarbg]
Post-processing files: [u'Maniac.2018.S01E03.INTERNAL.1080p.WEBRip.X264-DEFLATE.3.eng.srt', u'Maniac.2018.S01E03.INTERNAL.1080p.WEBRip.X264-DEFLATE.4.eng.srt', u'Maniac.2018.S01E03.INTERNAL.1080p.WEBRip.X264-DEFLATE.mkv', u'maniac.2018.s01e03.internal.1080p.webrip.x264-deflate.nfo', u'RARBG.txt']
Post-processing video files: [u'Maniac.2018.S01E03.INTERNAL.1080p.WEBRip.X264-DEFLATE.mkv']
Found unwanted files: [u'maniac.2018.s01e03.internal.1080p.webrip.x264-deflate.nfo', u'RARBG.txt']
Processing failed for C:\DATA\Private\Torrent\PROCD\TV\Maniac.2018.S01E03.INTERNAL.1080p.WEBRip.X264-DEFLATE[rarbg]\Maniac.2018.S01E03.INTERNAL.1080p.WEBRip.X264-DEFLATE.mkv: This show isn't in your list, you need to add it before post-processing an episode
Problem(s) during processing, failed for the following files/folders:
C:\DATA\Private\Torrent\PROCD\TV\Maniac.2018.S01E03.INTERNAL.1080p.WEBRip.X264-DEFLATE[rarbg]\Maniac.2018.S01E03.INTERNAL.1080p.WEBRip.X264-DEFLATE.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode 
```
</details>

**Additional context**

**Comment by Rouzax** [comment]
You're on top of it :)

In addition I do have a scene exception 
![image](https://user-images.githubusercontent.com/4103090/45916657-e35a7580-be69-11e8-9652-74a91b0b0f7b.png)

**Comment by p0psicles** [comment]
Add scene exception Maniac 2018

**Comment by Rouzax** [comment]
@p0psicles I already had 'Maniac' as exception and tried to add 'Maniac (2018)' but that wouldn't save.

**Comment by p0psicles** [comment]
That shouldn't be an issue. Ill verify later. Any debug logs?

**Comment by Rouzax** [comment]
Hmm, Just tried to add `Maniac (2018)` again and it did save now.
Not sure why it didn't go through the first time.

**Comment by p0psicles** [comment]
No from adding the exception. Should work now.

**Comment by Rouzax** [comment]
Let's call this a `PEBCAK`
