### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: MAX

### ISSUE THREAD

**Issue by ztaale** [pymedusa/Medusa#5288]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with-debian-9.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/102a91c14b410873af0ced587c22d024
### ERROR
<pre>
2018-09-22 19:53:29 ERROR    Thread_9 :: [4614efc] Missing time zone for network: MAX
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Which `MAX` channel is it?

**Comment by ztaale** [comment]
Norwegian "tv Norge Max"
