### ISSUE TITLE
Hovering rows in anime tab results in javascript errors in console

### ISSUE THREAD

**Issue by h3llrais3r** [pymedusa/Medusa#5313]
**Describe the bug**
When using the home page with split in tabs, I'm getting a lot of javascript errors when hovering the rows in the anime tab. Hovering in the normal show tab doesn't result in javascript errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/1945295/46130679-2c2f7700-c23a-11e8-865b-5d5cdf3e9b8a.png)

**Medusa (please complete the following information):**
- OS: Windows-8-6.2.9200
- Branch: master 
- Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6 
- Version: v0.2.10 
- Database: 44.12

**Comment by medariox** [comment]
Fixed.
