### ISSUE TITLE
WindowsError: [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by wsb12203** [pymedusa/Medusa#5319]
I'm using Python 2.7.14 |Anaconda, Inc.| (default, Nov  8 2017, 13:40:45) [MSC v.1500 64 bit (AMD64)]

I have following error: 

`self._handle = _dlopen(str(self._name), mode)
WindowsError: [Error 193] %1 is not a valid Win32 application`

I have already replaced   
`self._handle = _dlopen(self._name, mode)`
 to:
`self._handle = _dlopen(str(self._name), mode)`
as suggested in [here](https://github.com/pymedusa/Medusa/issues/1843#issuecomment-310126049)

**Comment by medariox** [comment]
This issue doesn't seem to be specifically related to Medusa. Please post your issue [here](https://github.com/pymedusa/Medusa/issues/1843) instead.
