### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: TBS.com

### ISSUE THREAD

**Issue by Zer0Velocity** [pymedusa/Medusa#5327]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-135-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/c70e8ef2725543109a6a0d7a25c319ab
### ERROR
<pre>
2018-09-29 17:14:25 ERROR    Thread_0 :: [4614efc] Missing time zone for network: TBS.com
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/b8208da35bc579b6600aef60bfb5f56ab5a99f77
