### ISSUE TITLE
 Error: OSError(18, 'Cross-device link'). Copying instead

### ISSUE THREAD

**Issue by bibi32** [pymedusa/Medusa#5341]
**Describe the bug**
2018-09-30 20:40:28 WARNING  POSTPROCESSOR :: [4614efc] Failed to create hardlink of /downloads/completed/[ www.T9.pe ] Young.Sheldon.S01E01.FRENCH.HDTV.XviD-ZT.avi at /data/series/Young Sheldon/Saison 01/Young Sheldon.S01E01.Sheldon, le surdoué.avi. Error: OSError(18, 'Cross-device link'). Copying instead

**To Reproduce**
deluge and medusa on docker from LinuxServer.io
medusa have a Post-Processed seeding torrents location.

 - OS: docker on raspberry pi
 - Branch: master
 - Commit: 4614efc

Everything work fine but I have this error, can I disable the Warning Logs or something else, thanks.

**Comment by medariox** [comment]
As the error says you can't hard-link across separate devices. Why don't you use copy or soft-link instead?

**Comment by bibi32** [comment]
For copy that dosen't move to Post-Processed seeding torrents location and for soft link that dosen't work for me and don't move to Post-Processed seeding torrents.

**Comment by p0psicles** [comment]
Then copy. And remove the torrent when seeding is complete?

**Comment by bibi32** [comment]
for post processing that dosen't recreate the file every 10 minutes ??

**Comment by OmgImAlexis** [comment]
@p0psicles could we not just allow moving the torrent to the seeding dir even if we copy? I don't see the harm.

**Comment by p0psicles** [comment]
Ooh ignore my last comment. Regarding torrents i dont know what im talking about. @medariox or @duramato are more fit to handle this.

**Comment by bibi32** [comment]
I continue with hardlink, I'm just delete the warning logs each days. Thanks.

**Comment by medariox** [comment]
Even if you use hardlink it will keep copying as the error message says. I suggest you just switch to copying so you don't get the error message.
