### ISSUE TITLE
Cannot change Auto Post-Processing Frequency

### ISSUE THREAD

**Issue by NickMolloy** [pymedusa/Medusa#5346]
The value for "Auto Post-Processing Frequency" cannot be changed in the Post Processing settings.

**To Reproduce**
1. Set post processor frequency to some value
2. Save settings
3. Value doe not change
4. See in log: ```WARNING  APIv2-Thread_4 :: [a1b5c87] Config patch ignored {u'postProcessing': {u'autoPostprocessorFrequency': u'15'}}```

I believe this is due to the fact that the value is sent as a string in the JSON patch request, rather than an integer, and so the validation [here](https://github.com/pymedusa/Medusa/blob/master/medusa/server/api/v2/base.py#L421) fails.

```
{"postProcessing":{  
      ...
      "postponeIfSyncFiles":true,
      "autoPostprocessorFrequency":"15",
      "airdateEpisodes":false,
      ...
   }
}
```

**Medusa:**
 - OS: [Debian 9.5 x64]
 - Branch: [develop]
 - Commit: [a1b5c87]

**Comment by p0psicles** [comment]
Tnx for reporting. And yes your assessment is correct.

**Comment by kezek** [comment]
+1

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5482
