### ISSUE TITLE
Shows not refreshing as expected 

### ISSUE THREAD

**Issue by a10kiloham** [pymedusa/Medusa#5348]
I'm having a hard time showing logs for this as I'm not quite sure what to search.
I'm seeing regular situations where my shows aren't updating from thetvdb and thus now downloading. A manual full refresh fixes but this is sometimes going a month or more before I realize I've missed weeks of a show. I've tried a manual refresh in the bulk editor but the problem persists with future updates.

**Comment by a10kiloham** [comment]
anyone else seeing this? i've tried clearing the cache and using a new docker image  but can't really figure out why this is happening. manually triggering full refresh fixes as expected.

**Comment by p0psicles** [comment]
There is a smart mechanism in place that checks periodically if there have been changes since a specific checked date. So next time we dont check after that date.

I suspect that your show updater ran and there where some connectivity issues at the time. Then it marked as "checked".

You could help by trying to collect some logs when the updater ran for a show that should have updated. Or check for any connection errors or warnings in the ShowUpdater thread.

When i have time ill see if i can build in some error margins.

**Comment by a10kiloham** [comment]
Here's an example. I can see for the past few days it's done daily checks on a show. SHOWUPDATER is returning status 200 so it seems to be checking (as of Oct 14). However there are a bunch of shows that exist on theTVDB that aren't pickedup.

Using the bulk edit tool, when i tick off the "UPDATE" box on this show nothing happens. When I tick "EDIT" "UPDATE" and download cover art, it performs as expected and detects properly
```
application.log:20600:2018-10-15 13:11:08 DEBUG    SHOWQUEUE-UPDATE :: [4614efc] 295777: Queueing show refresh for Crazy Ex-Girlfriend
application.log:20601:2018-10-15 13:11:10 INFO     SHOWQUEUE-REFRESH :: [4614efc] 295777: Performing refresh on Crazy Ex-Girlfriend
```
The past 3 days SHOWUPDATER had performed a refresh w/o actually updating. So either it's reporting a 200 status w/ no data or otherwise something else is interfering?

**Comment by p0psicles** [comment]
You have to check earlier. First its checking what needs to be updated. Then it queus the shows and gets the changes. Then it queus the shows and refresh.

**Comment by a10kiloham** [comment]
What shall I grep? Here's a fuller log of yesterday
```
application.log.3:71206:2018-10-13 04:02:35 DEBUG    Thread_15 :: [4614efc] 295777: Setter sets location to /mnt/Resources/TV/Crazy Ex-Girlfriend/Season.04/Crazy.Ex-Girlfriend.S04E01.Episode 1.720p HDTV.mkv
application.log.3:71213:2018-10-13 04:02:35 DEBUG    Thread_15 :: [4614efc] 295777: Formatting pattern: %SN - S%0SE01 - %EN -> Crazy Ex-Girlfriend - S04E01 - Episode 1
application.log.3:71215:2018-10-13 04:02:35 DEBUG    Thread_15 :: [4614efc] 295777: Using language from show settings: en
application.log.3:71216:2018-10-13 04:02:35 DEBUG    Thread_15 :: [4614efc] 295777: Using language from show settings: en
application.log.3:71218:2018-10-13 04:02:35 DEBUG    Thread_15 :: [4614efc] Getting all series data for 295777
application.log.3:71219:2018-10-13 04:02:35 DEBUG    Thread_15 :: [4614efc] Getting all show data for 295777
application.log.3:71220:2018-10-13 04:02:36 DEBUG    Thread_15 :: [4614efc] GET URL: https://api.thetvdb.com/series/295777 [Status: 200]
application.log.3:71222:2018-10-13 04:02:36 DEBUG    Thread_15 :: [4614efc] Getting all episodes of 295777
application.log.3:71223:2018-10-13 04:02:36 DEBUG    Thread_15 :: [4614efc] GET URL: https://api.thetvdb.com/series/295777/episodes/query?page=1 [Status: 200]
```

application.log.2:58508:2018-10-14 03:12:41 DEBUG    FINDPROPERS :: <cut> [Status: 200]
application.log.2:84618:2018-10-14 07:00:27 DEBUG    SHOWUPDATER :: [4614efc] Getting episodes for 295777
application.log.2:84619:2018-10-14 07:00:27 DEBUG    SHOWUPDATER :: [4614efc] Getting all episodes of 295777
application.log.2:84620:2018-10-14 07:00:27 DEBUG    SHOWUPDATER :: [4614efc] GET URL: https://api.thetvdb.com/series/295777/episodes/query?page=1 [Status: 200]
application.log.2:84999:2018-10-14 07:00:41 DEBUG    SHOWUPDATER :: [4614efc] 295777: Queueing show refresh for Crazy Ex-Girlfriend
application.log.2:86114:2018-10-14 07:00:54 DEBUG    MAIN :: [4614efc] 295777: Loading show info from database
application.log.2:86116:2018-10-14 07:00:54 DEBUG    MAIN :: [4614efc] 295777: Finding the episode which airs next
application.log.2:86117:2018-10-14 07:00:54 DEBUG    MAIN :: [4614efc] 295777: No episode found... need to implement a show status
application.log.2:94015:2018-10-14 11:00:55 DEBUG    FINDPROPERS ......clipped

**Comment by a10kiloham** [comment]
before and after this are just a bunch of normal FINDPROPERS but the show itself doesn't update for the unaired and un-downloaded shows which ought to be shown. There should have been at least one missing show found on this date which wasn't.

**Comment by a10kiloham** [comment]
Moved machines and this bug has disappeared it seems, so closing for now.

**Comment by p0psicles** [comment]
Most often this is explained by connectivity issues. Or at your end or that of tvdb.

**Comment by a10kiloham** [comment]
it was definitely more consistent than just connectivity I think. it runs on a VPS so quite stable that end and the 2+ months of failures meant it was repeatedly failing yet instantly fixed with manual refresh.
