### ISSUE TITLE
Metadata settings not getting saved

### ISSUE THREAD

**Issue by Generator** [pymedusa/Medusa#5352]
**Describe the bug**
After changing the metadata setting on Post Processing the metadata remains default on config.ini resulting on reverting to default on restart

**To Reproduce**
1. Go to Post Processing -> Metadata
2. Change settings
3. Save changes
4. Check config.ini for changes on metadata_*

**Expected behavior**
Metadata settings persist after restart

**Screenshots**
![screenshot_2018-10-05 organizr v2](https://user-images.githubusercontent.com/44146/46532743-15bc9780-c89a-11e8-8ee5-6c6f1e9637d7.png)

config.ini

```
metadata_kodi = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_kodi_12plus = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_mediabrowser = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_ps3 = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_wdtv = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_tivo = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_mede8er = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
```

**Medusa:**
 - OS: Raspbian 9.4 arm
 - Python: 2.7.13
 - Branch: master
 - Commit:  4614efc77

**Additional context**
Medusa have permissions to r/w config.ini, other settings gets saved on config.ini. 
No errors found on logs

**Comment by p0psicles** [comment]
Im pretty sure i tested this when vueified.

**Comment by medariox** [comment]
@p0psicles I reproduced it on latest develop. After a restart the selections are gone.

**Comment by Generator** [comment]
Also tested with [docker image](https://hub.docker.com/r/linuxserver/medusa/) with same result, the "Saved Post-Processing config" is shown but no changes on config.ini

**Comment by p0psicles** [comment]
https://github.com/pymedusa/Medusa/blob/develop/medusa/server/api/v2/config.py#L233 this should do it?

**Comment by medariox** [comment]
@p0psicles What do you mean?

**Comment by p0psicles** [comment]
I mean i dont understand how this is not working?

**Comment by desepticon** [comment]
can confirm I am seeing this exact same issue.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5400
