### ISSUE TITLE
scene number handling is broken

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#5354]
**Describe the bug**
1/ Episodes on Disc are always handled as scene numbered when tvdb/medusa knows scene numbers for eps.
2/ cannot add a show as non-scene when the indexer has it stored as scene

**To Reproduce**
1/ set a scene numbered show to be non-scene and refresh and reload everything. the eps will still be sorted by their scene number following the file name. Scene should only be used when searching indexers or adding eps from postprocessing. Never on stored eps in the show folder.

2/ when adding a show the last page has a checkbox. adding a scene numbered show does not add it as non scene when the tickmark is not set.

**Expected behavior**
scene numbers should not get enabled and used by default if they  are not enabled for a show. eps internally are never processed using scene. scene is only for searching and importing.
the eps need to be associated to the db as they are numbered.  Instead you can see the chaos of mixed content..

**Screenshots**
non scene and refreshed fully and files multiple times 
![show setting](https://user-images.githubusercontent.com/869637/46572231-69a2ab80-c982-11e8-9a60-8e9b1e5ba1e8.png)

the chaos that is a mixed season...
![season](https://user-images.githubusercontent.com/869637/46572237-935bd280-c982-11e8-94f6-da716fad04ea.png)

**Medusa (please complete the following information):**

Branch: master Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6 Version: Unknown Database: 44.12
Python Version: | 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
SSL Version: | LibreSSL 2.6.5
OS: | Linux-3.10.105-x86_64-with

**Logs:**
**Additional context**
removing/re-adding does not help either.

**Comment by medariox** [comment]
Scene numbering is not forced anymore.
