### ISSUE TITLE
Showing the N/A quality when failed download

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#536]
We know the quality, why is showing as N/A ?

![image](https://cloud.githubusercontent.com/assets/2620870/12089112/80acf598-b2c8-11e5-95b0-f532283421b4.png)

**Comment by p0psicles** [comment]
Isn't it that we know the quality for sure, after it has been post processed? Because the release name, should by default not be the same as the downloaded and PP file?

**Comment by fernandog** [comment]
Sometimes it works. Sometimes not (showing failed quality)

**Comment by duramato** [comment]
Can comfirm but its some thing intermitent, and i still dont know the exact variables/cause for this to happen. It may be related to why some downloads on manual search only appear the inclued same quality in search and doesnt show the failed modal too.

**Comment by OmgImAlexis** [comment]
Any updates on this?

**Comment by fernandog** [comment]
I cant figure it out. Need someone with more debugging experience

**Comment by fernandog** [comment]
as we change PP to use guessit will close this. if happens again will open

ping @duramato
