### ISSUE TITLE
Bug when adding a series with a special character (ø)

### ISSUE THREAD

**Issue by Roedy86** [pymedusa/Medusa#5360]
When I add the Danish show Ørkenens Sønner, which i have on disk, Medusa creates a new folder with the name Ãrkenens SÃ¸nner. - This is also shown when adding the show, as the path changes in the process.

1. Click Shows > Add Shows > Add Existing Shows
2. Choose the show from the list by selecting the folder. (The folder is shown correctly here as "Ørkenens Sønner")
3. Click Submit
4. Now the issue can be seen as the show has now changed name to Ãrkenens SÃ¸nner on both the path and the "Find a show on selected indexer(s)"
5. Finish adding the show and go to the series area.
6. The series path can now be seen as <PATH>/Ãrkenens SÃ¸nner and medusa has actually created a folder by that name.

**Medusa (please complete the following information):**
 - OS: Debian stretch
 - Branch: master
 - Commit: https://github.com/pymedusa/Medusa/commit/4614efc77151ded92ef458a09dec39f8bd5acfc6

The bug can be worked around by just editing the show and changing the path to the correct one after adding the show.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5635
