### ISSUE TITLE
Time Zone error for Sun Television

### ISSUE THREAD

**Issue by hergonoway** [pymedusa/Medusa#5367]
**Describe the bug**
got systematically that error : 
2018-10-09 14:37:49 ERROR    Thread_0 :: [4614efc] Missing time zone for network: Sun Television

**Medusa (please complete the following information):**
 - OS: linux (through docker)
 - Branch: ster
 - Vers : 0.2.10

Got this error for a long time (not from the last commit) which makes my top right menu always RED :)

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/550e045e2f68cfbde8f9226b8fee00e601de5b6e
