### ISSUE TITLE
Translation ?

### ISSUE THREAD

**Issue by Surfoo** [pymedusa/Medusa#5376]
Hello,

Will you plan to add the translation, like sickrage/sickchill/whatever the name? 

I'd like to switch from Sickchill to Medusa, but I'am not alone to use this app and they don't speak english...

**Comment by OmgImAlexis** [comment]
Yes this is planned. I might open a PR soon to add this.

@miigotu any chance we could share translation strings for common phrases? It'd help us get off the ground a lot quicker with this.

**Comment by ciltocruz** [comment]
Hello, how is this topic going? Is there an open process for putting translations?

**Comment by OmgImAlexis** [comment]
No the whole ui still needs to have all the text replaced with i18n functions and such.

**Comment by ciltocruz** [comment]
Oh ...!

When is it planned then?

**Comment by medariox** [comment]
Waiting for contributions.
