### ISSUE TITLE
map'ed drive suport

### ISSUE THREAD

**Issue by ragga64** [pymedusa/Medusa#5378]
just installed medusa and can not get it to find or will except maped drive link address \\Plex-pc\plex-media\TV  to list all tv videos, address works fine on sickrage but will not let me save the address in Show root directories
if needed an update would be great
many thanks 
john

**Comment by medariox** [comment]
You mean you can't browser to the directory?

**Comment by ragga64** [comment]
that is corect, i use a second server to run plex and store the media files on so map the network drive to sickrage, but in sickrage you can put the map drive address in the Show root directories as a new drive but in medusa you can put it in but will not save location only local drives!.
not sure if bug or not writen into the code as yet but a pain in the but :)

**Comment by ragga64** [comment]
Just one more thing, i tryed to edit the config.ini with the root dir, it will save but when reboot it resets back to defualt.
cheers O7

**Comment by ragga64** [comment]
![screenshot_2018-10-12 sickrage - config - general](https://user-images.githubusercontent.com/22989284/46897190-3461f600-ce79-11e8-8ef7-a3546dd7e554.png)

This is in sickrage
---------------------------------------------------------------------------------------------------------

**Comment by p0psicles** [comment]
Mount the unc to a local drive.

**Comment by p0psicles** [comment]
https://www.dummies.com/computers/pcs/mapping-a-network-drive-on-your-windows-10-pc/

**Comment by labrys** [comment]
@ragga64 are you using the windows installer?  If so then mapped drives won't work.  I've used uncs in medusa in the past and while you can't add them in the UI, you can add them in the config.ini
Make sure medusa is stopped before you change the config.ini

**Comment by ragga64** [comment]
backlog_days = 7
cache_dir = cache
root_dirs = 0|\\Plex-pc\plex-media\TV
tv_download_dir = E:\compleat
keep_processed_dir = 1
process_method = copy
---------------------------------------------------------------------------------------------
ok managed to get it to stay after reboot but now this !!
![screenshot_2018-10-13 status medusa](https://user-images.githubusercontent.com/22989284/46909628-5ddc5980-cf2d-11e8-8984-68c2b3aa5c1a.png)

**Comment by medariox** [comment]
It should be `0, E:\Videos\TV Shows` instead.

**Comment by ragga64** [comment]
cache_dir = cache
root_dirs = 0, \\Plex-pc\plex-media\TV
tv_download_dir = E:\compleat
keep_processed_dir = 1
process_method = copy


yep just found that out :)  cheers for all the help every one O/

**Comment by WarEagleUS21** [comment]
What if you want to keep the local directories but also add the QNAP\NAS Network drive that is mapped on Win 11? Can I go under root_dirs = 3, XXX and add network_dirs = 0, \IP OF QNAP\Z folder?

**Comment by p0psicles** [comment]
You just add the second path with a comma to the end of that line.
Like:
`0, /my/first/path, \\server\share`
The first value is the index to determin you default folder. Like in that example 0 will point to `/my/first/path`. If I'd change that to 1. It would point to `\\server\share`

**Comment by WarEagleUS21** [comment]
Thank you
