### ISSUE TITLE
SabNZBd "Direct Unpack" feature causes post processing failures.

### ISSUE THREAD

**Issue by desepticon** [pymedusa/Medusa#5379]
**Describe the bug**
SabNZBd has a (relatively) new feature that will unrar the file as it downloads if it has enough chunks and the disk speed is sufficient.

However, Medusa keeps trying to post-process this even though I have added "\_UNPACK\_" to the sync file extensions (which prepends the folder name of downloads using this feature) and "Wait to process a folder if sync files are present" is enabled.

I have recently migrated from Sickrage, and this didn't used to happen on that platform. 

**To Reproduce**
1. Download a file in SABnzbd with "Direct Unpacking" option enabled.
2. Wait for medusa's post-processor to fire as the download is ongoing.
3. See error

**Expected behavior**
Medusa should recognize this as an incomplete download and decline to Post-process

**Medusa (please complete the following information):**
 - OS: [Mac OS 10.13.6]
 - Branch: [master]
 - Commit: [?]

**Logs:**
<details>
```
2018-10-10 23:05:35 WARNING  POSTPROCESSOR :: [4614efc] Processing failed for /Volumes/dvorak.8tb/SABnzbd/tv/_UNPACK_Firefly.S01E12.Objects.in.Space.720p.BluRay.DD5.1.x264-CHOTAB/AmFbpPF7yUvpZsU4zn9FpnffknKitQiqs.mkv: This show isn't in your list, you need to add it before post-processing an episode
```
</details>

**Additional context**
none

**Comment by medariox** [comment]
Thanks for the report!

The option is only for files, not for folders. That's why it doesn't work as you expect it to.
Support for SABnzbd's Direct Unpack feature will be added with: https://github.com/pymedusa/Medusa/pull/5385

**Comment by desepticon** [comment]
Gotta love that fast turnaround!
