### ISSUE TITLE
[Feature Request] Episode gaps screen

### ISSUE THREAD

**Issue by psylenced** [pymedusa/Medusa#5383]
Cross posting my request from sickrage:

------

Sometimes for some reason episodes get missed and lost when managing large collections and there are a few seasons that have episodes that have been gaps of un-downloaded episodes with future episodes downloading after it.

What I suggest is a new screen called "episode gaps" which shows any show/season that has a gap in one of the episode downloads.

I wrote the following query:
```
select distinct t1.*
from tv_episodes t1
inner join tv_episodes t2 on t1.showid = t2.showid and t1.season = t2.season and t1.episode < t2.episode and t1.location = '' and t2.location <> '' 
where t1.season <> 0
order by t1.showid, t1.season desc, t1.episode desc 
```

What this does is finds any season that has a location (ie. filename) that has an earlier episode that is missing a location. This then returns "gaps" of missing downloads.

It works on a season basis, so wont return gaps for earlier seasons, unless an episode has been downloaded in that season.

Not sure what the screen layout should be, whether it models off schedule screen or backlog overview. If it was backlog, it'd need clicks through to the show and possibly a search column, so the schedule screen is probably the best fit.

**Comment by medariox** [comment]
Wouldn't it be a better approach to actually find out the reason why some episodes are being skipped?

**Comment by psylenced** [comment]
Of course finding out why is important, but the issue is easily identifying them first.

A single screen showing all of them helps you start that process. 

Could be failed download, could be really old season, could be deleted off disk.

The only way to work it out currently, is to click individual shows that are not 100% compete 1 by 1.

**Comment by medariox** [comment]
Manage > Backlog Overview
