### ISSUE TITLE
Post Process Not enabling even though sliders enabled in post processing settings

### ISSUE THREAD

**Issue by LoRNiKoN** [pymedusa/Medusa#5384]
Post Process Not enabling even though sliders enabled in post processing settings (manual work around via config.ini) If you set this feature and review the server Status the post processing enable flag is set to FALSE.

Please note this is on a fresh install of Medusa and think is related tot eh change from the tickbox to the slider and so the value isnt updating the config.ini

The manual fix for the auto processing for X time is to manually edit the confi.ini and update process_automatically to a value of 0

**To Reproduce**
1. Go to 'Manage > Post Processing'
2. Enable Scheduled Post Prosecessor slider (has replaced tick box)
3. Set an Auto Post-Processing Frequency
4. Save Changes
5. Go to Server Status page and see that post process is set to FALSE

**Expected behavior**
These two value should enable Medusa to auto scan the download folder for changes (which it does not) and also auto process the folder every X minuties.

**Medusa (please complete the following information):**
 - OS: Windows 10 (1803 - 17134.345)
 - Branch: Master
 - Commit: 4614efc7715ded92ef458a09dec39f8bd5acfc6

**Comment by medariox** [comment]
Hey! The False doesn't mean it's not working, it just means it _currently_ isn't running. Maybe you have set a lower post-processing frequency? You will need to wait 10 min for it to start in that case, see https://github.com/pymedusa/Medusa/issues/5346

**Comment by LoRNiKoN** [comment]
Hey there, I had this set to 10 mins which should be fine... its just that after enabling the process was marked as disabled even though all my values were set as to run this process. the only way i could get it to run with the 10 min intival was to manually adjust the config.ini value and then the timed process would run.

Even doing this its not running on a change to the folder but i can live with an intival scan. 

I just wanted to raise this for awareness as i litterally installed Medusa yesterday as i only found out about this fork yesterday so was just trying to work out why it wasnt running as it should as i never had this issue with Sickrage which i was using prior to this.

**Comment by Tearow** [comment]
I had this aswell if you check server status it will say post process enable = False. you can restart medusa and it will be on True

**Comment by polyneux** [comment]
I was having a similar issue. As @Tearow said once I restarted the server it connected the post-processor. Not sure why I didn't think of this before.
