### ISSUE TITLE
Scanning doesn't find episodes with alternate name

### ISSUE THREAD

**Issue by MrTimscampi** [pymedusa/Medusa#5390]
**Describe the bug**
Trying to scan episodes for the anime "Attack Number One", which shows up as "Attack No. 1" from the indexer.
The scan doesn't find any episodes despite them being named like this: `Attack Number One - 01 - The New One.mkv`

**To Reproduce**
1. Scan a show with multiple names
2. Medusa fails to find it

**Expected behavior**
Medusa should also use alternate titles to scan local files and perform searches (It currently doesn't return torrents on Nyaa which I know exist for that show).

**Screenshots**
n/a

**Medusa (please complete the following information):**
 - OS: CentOS 7, Docker 18.06.1-ce, build e68fc7a
 - Branch: master
 - Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6

**Logs:**
<details>
n/a
</details>

**Additional context**
Medusa doesn't seem to take alternate names into account while scanning or searching ?

**Comment by p0psicles** [comment]
You will have to add a scene name exception for the alternative title

**Comment by MrTimscampi** [comment]
It doesn't seem to help it find either the torrents or the local files, unfortunately. I added these as scene exceptions: "Attack no. 1" and "Attack Number One".

**Comment by medariox** [comment]
https://nyaa.si/?f=0&c=0_0&q=Attack+Number+One

It's very likely getting skipped because of the 0 seeders.

**Comment by medariox** [comment]
Closing because no debug logs were posted.
