### ISSUE TITLE
Scene Exceptions

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#5394]
Hi Team

Just out of interest do you update scene names and then it updates MedUSA or must the user do this per show like the below is stating ?

Consider adding 'Scandal' in scene exceptions for series 'Scandal (2012)'
Consider adding 'The Flash' in scene exceptions for series 'The Flash (2014)'
Consider adding 'Empire' in scene exceptions for series 'Empire (2015)'
Consider adding 'Beauty and the Beast' in scene exceptions for series 'Beauty and the Beast (2012)'

Thanks

**Comment by desepticon** [comment]
You have to do this yourself, I believe. However, be careful. If the alternate name is a different show that releases can be found for, you will get the wrong show. ie: MacGyver (2016) and MacGyver would cause all kinds of confusion for Medusa.

**Comment by labrys** [comment]
@HPMSGEN8 sometimes they can be helpful to identify some series, but the majority should be ignored.

**Comment by HPMSGEN8** [comment]
Thanks all :)

**Comment by git-hub-nub** [comment]
How do I suppress these warnings for particular series? My OCD plays havoc when I see warnings on the front screen.

Consider adding 'Bodyguard' in scene exceptions for series 'Bodyguard (2018)'

The series I have added is indeed "Bodyguard (2018)".
