### ISSUE TITLE
Disable post processor warnings for certain issues

### ISSUE THREAD

**Issue by DrSpaldo** [pymedusa/Medusa#5399]
Hi, I have recently switched from SickRage to Medusa. So far it feels nicer. However, I have noticed that in the way I have my Medusa set up that I am getting a lot more warnings than before.

I have Medusa installed on Synology with a mounted folder that has all the TV from the seedbox. This is needed as it is shared and the only way I could get it to connect properly. So the mounted folder is listed in the post processing section. Unfortunately, as there are other shows I do not have in Medusa that other users use, it is picking them up and giving me the following error/warning:

This show isn't in your list, you need to add it before post-processing an episode

Is there is way I can turn this off as a warning?

Hope this makes sense. Thanks.,

**Comment by desepticon** [comment]
You might be able to write a script that symlinks all the files processed by Medusa and puts them in a folder outside the PP folder.

**Comment by kezek** [comment]
+1

**Comment by neo62248** [comment]
+1

My Transmission client is seeding many downloads in the complete directory. This directory is already used by MEDUSA to postprocessing. Films that don't have to deal with MEDUSA are in this directory. I need to move them to avoid warnings. But i loose the capacity of seeding my files moved.

**Comment by sspencer10** [comment]
So if anyone is looking for a workaround, I changed the log level from warning to info in this file:

https://github.com/pymedusa/Medusa/blob/master/medusa/process_tv.py

Look at lines 208 and 210

**Comment by p0psicles** [comment]
I'll make some logs, level adjustable. 
Almost finished

**Comment by p0psicles** [comment]
As i've nearly completed this feature in branch: feature/customize-logging
Can I get some early testers? @sspencer10 @neo62248 @kezek?

YOu'll need to checkout the branch.

**Comment by sspencer10** [comment]
@p0psicles I will, but am away for the weekend. Will report back sometime next week

**Comment by p0psicles** [comment]
Added to develop
