### ISSUE TITLE
Rar Permission Issues

### ISSUE THREAD

**Issue by bmbermn** [pymedusa/Medusa#5403]
**Describe the bug**
I am running medusa on my qnap nas through container station. I have everything configured but it is having a permission issue when trying to unrar during post processing. The downloads directory itself is 777 but the files/folders within are 775. The error is 
```2018-10-13 18:46:37 WARNING  Thread_17 :: [4614efc] /downloads/I.Feel.Bad.S01E04.1080p.WEB.x264-TBS/i.feel.bad.s01e04.1080p.web.x264-tbs.mkv: Processing failed: File /downloads/I.Feel.Bad.S01E04.1080p.WEB.x264-TBS/i.feel.bad.s01e04.1080p.web.x264-tbs.mkv doesn't exist, did unrar fail?```
I set the files within to 777 manually and it was able to process. Can you advise how I could tell medusa to either set these to 777 on creation or fix the issue. 

**Medusa (please complete the following information):**
 - OS: QNAP Nas
 - Branch: Master
 - Commit: Latest

**Comment by desepticon** [comment]
Why would unrar need write permissions on the file?

**Comment by bmbermn** [comment]
It needs write permissions to be able to create the new combined file.

**Comment by desepticon** [comment]
I think the easy fix would just be to set your downloader to set your permissions before post-post-proecessing even occurs.

**Comment by solipsist01** [comment]
run your container with these parameters included: -e PUID=0 -e PGID=0
the container will run as root

**Comment by donbrew1** [comment]
Who owns unrar?  The same owner or group that owns the folder?

**Comment by medariox** [comment]
There is nothing we can do. You need to use the correct permissions.
