### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: DisneyNOW

### ISSUE THREAD

**Issue by dirkr07** [pymedusa/Medusa#5408]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 15:26:34) [GCC 4.3.2]`
**Operating System**: `Linux-2.6.32.12-ppc-with-glibc2.0`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-10-14 09:36:07 ERROR    Thread_2 :: [4614efc] Missing time zone for network: DisneyNOW
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/d6b9d2aea0b6c5a917ce11697faedba9003f276e
