### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: 7mate

### ISSUE THREAD

**Issue by ragga64** [pymedusa/Medusa#5409]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-10-14 08:59:13 ERROR    Thread_34 :: [4614efc] Missing time zone for network: 7mate
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/d6b9d2aea0b6c5a917ce11697faedba9003f276e
