### ISSUE TITLE
[Feature Request] Cross-Seeding the same file

### ISSUE THREAD

**Issue by doopeldedoo** [pymedusa/Medusa#5410]
Medusa only downloads one torrent of a specific episode. 
If the episode is available on multiple trackers, can Medusa download them all to cross-seed?
Cross-seeding is when the same torrent is on two different trackers, you can download it from one, then seed to both.
This makes it possible to get a better ratio at multiple trackers.

**Comment by doopeldedoo** [comment]
> That doesnt have anything to do with medusa. Medusa doesnt download or seed. Thats for your download client, deluge, rtorrent, trsansmission.

Oh it does. Medusa searches for the torrents and advises the torrent client to download the torrent files. The torrent client just stupidly downloads the file. But it downloads it only ones since the files are identical.

**Comment by doopeldedoo** [comment]
A cross-seeding feature would
-download multiple identical torrents of the same file from different trackers

**Comment by p0psicles** [comment]
Ok i understand now

**Comment by plato79** [comment]
I don't have enough knowledge but can you guess if the torrents are same when they're from different trackers? It seems hashes on magnet links are like that.

**Comment by doopeldedoo** [comment]
> I don't have enough knowledge but can you guess if the torrents are same when they're from different trackers? It seems hashes on magnet links are like that.

Yes you can guess. Torrents from different trackers will have the same name and file count and overall torrent size.

**Comment by plato79** [comment]
Well, the thing is it's not always like that.. I saw the same torrent with different file name with the same content.. When I add to the client though, torrent client recognizes that it's the same torrent and add trackers automatically.. Torrent file size could be also different because when you think about it the torrent files could have different tracker information in them..

Of course the files in the torrent and the sizes of the files in the torrent should match.

**Comment by p0psicles** [comment]
So then youd need to analyze each torrent before sending it to the client?

**Comment by plato79** [comment]
Ok, I checked the file structure but it seems comparing [piece list](https://en.wikipedia.org/wiki/Torrent_file#File_structure) would work.. Though I think some sources have only magnet links, sending these to the torrent client is enough to download (assuming there are seeders/leechers) but Medusa wouldn't be able to check the contents without an actual torrent file.

I don't think it's feasible to work on this. Just enable DHT on your client and hope it would get more seeders than what the tracker contains...

**Comment by doopeldedoo** [comment]
> Ok, I checked the file structure but it seems comparing [piece list](https://en.wikipedia.org/wiki/Torrent_file#File_structure) would work.. Though I think some sources have only magnet links, sending these to the torrent client is enough to download (assuming there are seeders/leechers) but Medusa wouldn't be able to check the contents without an actual torrent file.
> 
> I don't think it's feasible to work on this. Just enable DHT on your client and hope it would get more seeders than what the tracker contains...

Enabling DHT does not work with private trackers. They prohibit DHT so that the swarm cannot be seen from outside (legal reasons).

The piece list would also not work since the hash is different from torrent file to torrent file. Most trackers release SCENE releases though. They are strict about them so that there should not be any missing files or changed files.

**Comment by plato79** [comment]
I know private trackers doesn't work with DHT.. You could always put private trackers at the bottom in the search provider list.

The piece list should match for the same torrent file with different tracker though... We are talking about the same torrent file with different file name and tracker..

**Comment by medariox** [comment]
This is out of scope for Medusa.
