### ISSUE TITLE
Can't access Medusa over the network

### ISSUE THREAD

**Issue by ragga64** [pymedusa/Medusa#5414]
**Read the wiki, been looking on github but cant fined any info on how to get access  to Medusa over the network, unlike sickrage wich was just there, no probs 

config.ini
=====================================
download_url = ""
localhost_ip = 192.168.0.23
cpu_preset = NORMAL
anon_redirect = http://dereferer.org/?
=====================================
192.168.0.23:8081
this should work but nothing!!

any help would be great
many thanks
J

**Comment by medariox** [comment]
This is not a Medusa issue and there is no way we can help you. Check your router settings or something.
