### ISSUE TITLE
Post processing error with episode number

### ISSUE THREAD

**Issue by aykot** [pymedusa/Medusa#5415]
**Describe the bug**
When I use the %E (for episode number) in the following form "Season %0S/%SN %Sx%0E - %EN/%RN" the preview and the renaming are "Season 02/Show Name 003 - Ep Name/Show.Name.003.HDTV.x264-RLSGROUP.ext" where the 003 in episode number if wrong both in the folder part and in the file part. if I change it to %XE, it works only in the folder part, but the release name is still wrong.

**To Reproduce**
1. Go to 'Configs - Post processing'
2. Click on 'Episode naming'
3. Fill custom folder with previously stated format.

**Expected behavior**
Final output should read:
Season 02/Show Name 2x03 - Ep Name/Show.Name.2x03.HDTV.x264-RLSGROUP.ext

**Screenshots**
https://imgur.com/a/uoG8FWV

**Medusa (please complete the following information):**
 - OS: Mac El Capitan
 - Branch: master
 - Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6
 - Version: Unknown
 - Database: 44.12
 - Python Version:  2.7.12 (default, Jul 21 2016, 12:04:57) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
 - SSL Version: | OpenSSL 1.0.2n 7 Dec 2017
 - OS: | Darwin-15.6.0-x86_64-i386-64bit
 - Locale: | es_ES.UTF-8

**Comment by medariox** [comment]
Not sure what you are doing differently, but it seems to work just fine for me: https://snapr.pw/i/99fe171137.png

**Comment by medariox** [comment]
Oh, that's what you mean. `Season %0S/%SN %Sx%0E - %EN/%RN` should be fine `%RN` is just an "example preview" (e.g. it can be absolute for anime, but doesn't have to), it should actually work as you expect (`Show.Name.2x03.HDTV.x264-RLSGROUP.ext`).

**Comment by aykot** [comment]
You are absolutely right, it’s only a matter of the preview. Thanks for the help!
