### ISSUE TITLE
IPTorrents configure the required cookies for this provider.

### ISSUE THREAD

**Issue by redbriar** [pymedusa/Medusa#5422]
**Describe the bug**
Using IPTorrents for my torrents, although the provider is setup with the cookie values i get the error below. My sickrage/ sickchill still works with the cookie. I have generated a new cookie and tested first in medusa where i had the same warning. Sickchill worked first time.

If i play around with the cookie values i get different messages included below.

**To Reproduce**
1. Use IPTorrents as provider
2. Enter cookie info
3. Search for show
4. Warning appear in settings

**Expected behavior**
Search for and find torrents

**Screenshots**
![Imgur Link to settings](https://i.imgur.com/NkXjvcP.jpg)

**Medusa (please complete the following information):**
 - OS: Unraid
 - Branch: master
 - Commit: 4614efc

**Logs:**
<details>

```
2018-10-15 17:58:00 INFO     SEARCHQUEUE-BACKLOG-148581 :: [4614efc] No needed episodes found during backlog search for: Strike Back
2018-10-15 17:58:00 INFO     SEARCHQUEUE-BACKLOG-148581 :: [IPTorrents] :: [4614efc] Performing season pack search for Strike Back
2018-10-15 17:58:00 WARNING  SEARCHQUEUE-BACKLOG-148581 :: [IPTorrents] :: [4614efc] Please configure the required cookies for this provider. Check your provider settings
2018-10-15 17:57:59 INFO     SEARCHQUEUE-BACKLOG-148581 :: [IPTorrents] :: [4614efc] Performing episode search for Strike Back
2018-10-15 17:57:59 INFO     SEARCHQUEUE-BACKLOG-148581 :: [4614efc] Using backlog search providers
2018-10-15 17:57:59 INFO     SEARCHQUEUE-BACKLOG-148581 :: [4614efc] Building internal name cache for Strike Back
2018-10-15 17:57:59 INFO     SEARCHQUEUE-BACKLOG-148581 :: [4614efc] Finished processing 2904 scene exceptions.
2018-10-15 17:57:59 INFO     SEARCHQUEUE-BACKLOG-148581 :: [4614efc] Updating exception_cache and exception_season_cache
2018-10-15 17:57:59 INFO     SEARCHQUEUE-BACKLOG-148581 :: [4614efc] Beginning backlog search for: Strike Back
```

```
Added extra ; at end of cookie
2018-10-15 18:11:12 WARNING  SEARCHQUEUE-BACKLOG-148581 :: [IPTorrents] :: [4614efc] Cookie is not correctly formatted: uid=xxxxxxx;pass=xxxxxxxx2;

No pass value
2018-10-15 18:12:39 WARNING  SEARCHQUEUE-BACKLOG-148581 :: [IPTorrents] :: [4614efc] Cookie is not correctly formatted: uid=xxxxxxx;
```
</details>

**Additional context**

**Comment by redbriar** [comment]
Thats how i have it set currently if you look at the imgur screenshot, i have just done a re install before posting the issue as thought maybe i had done something

**Comment by DanGarion** [comment]
I just setup medusa today and I'm unable to replicate your issue. I followed the steps in the provider config and it worked for me. As you sure you are not using the passkey that IPTorrents has? They are not the same...

**Comment by redbriar** [comment]
100% using the pass value obtained from the cookies (same place as the uid) I have the exact same cookie values working in sickrage and then a brand new config in sickchill. Another user has the same issue on reddit aswell, similiar setup to mine

**Comment by medariox** [comment]
I just tried it out on a new install and it works as expected. Are you sure you don't have spaces between `uid=xx;` and `pass=xx`? Try to log out from IPT, log in again and use the new uid and pass. If that still doesn't work check your `config.ini` and see if the values are saved correctly.

**Comment by redbriar** [comment]
[imgur link](https://imgur.com/NbaA0E2) From my config, no spaces and no new line at the end of the line / random hidden characters. I have tried logging out and clearing cookies, same from different computer and browser and still have the same issue. Due to using ipt and my isp i do have to proxy the connection out, are you able to test that

**Comment by DanGarion** [comment]
Have to tried a restart? I only ask this because that fixed a completely different issue I was having with postprocessing not turning on for me...

**Comment by DanGarion** [comment]
That is strange, I just compared it to mine and as long as the ID and Pass are correct you have it set right (from what I can tell).

**Comment by redbriar** [comment]
Just cloned the repo onto ubuntu 18 and everything is working, using system vpn or proxy in the app (ISP block). Something is going wrong with when its coming down onto unraid/docker. Ill clear out the docker image and configs tomorrow and give it another go. Although the clean windows version did have the same issue.

**Comment by DanGarion** [comment]
Good luck, that is how I loaded up Medusa today was with Docker using linuxserver/medusa. This whole SickRage thing was frustrating once I realized what was happening.

**Comment by redbriar** [comment]
This is something to do with unraid i feel, ran it in Docker on ubuntu and works fine, ran the same command just on unraid and same issue, it can connect out to indexers through the proxy but still having issues with cookies, tried both pymedusa and linuxserver repos and same issue.

**Comment by p0psicles** [comment]
@omgimalexis you run unraid right? Can you reproduce.

**Comment by ccsliinc** [comment]
@p0psicles Running latest on unraid with IPT and it is working as expected.

**Comment by redbriar** [comment]
So the issue is with my proxy or how medusa speaks to my proxy. Indexer is working fine and can grab content through the proxy. I use Privoxy and PIA connection to get access to IPT past my ISP. Unfortunatly HTTPS stops me from looking at what is being passed to my proxy, any ideas where i can look to troubleshoot??

**Comment by redbriar** [comment]
The only connection coming through the proxy from medusa is going out to cdn.pymedusa.com:443, is this expected? using either chill or pre-chill rage i see the request for ipt

**Comment by redbriar** [comment]
Just tried with a different proxy (tinyproxy) still have the same issue, does anyone have a working proxy set?

**Comment by ccsliinc** [comment]
@redbriar it appears as though the problem is with the proxy or the conversation between and not actually medusa.  Unfortunately my setup is only using vpn but no proxy.

**Comment by redbriar** [comment]
@ccsliinc its an odd issue as this is the first time ive had this issue with the proxy in 5 years across mutlple containers, hosts and devices. There is another guy on reddit who also has the same issue but it using binhex's docker proxy. If no one else can help ill just close the issue as it seems very isolated and support will be hard to come by.

**Comment by MWatter** [comment]
I realize this is an old ticket, but It's now happening to me as well. I don't use a proxy or VPN. This was working as of 2019-02-15. At that point I shut down my unread server and moved to a new house. Today I started my system back up again and it didn't work with the message "lease configure the required cookies for this provider". No worries. I logged back into ipt and pulled down the cookies. They were the same as before, but to be safe I re-pasted the values into the form field in Medusa. Same error. 

I'm using the linuxserver/medusa image. I did do an update of the image before restarting the app. perhaps that had something to do with it, however, if the same issue is being reported from back in October, then maybe not. 

Anyway, I was just hoping that posting here might prompt someone who had seen the issue and solved it to post the answer.

**Comment by redbriar** [comment]
Hey @MWatter the site changed something to do with how their cloudflare front end handles incoming traffic. If you do not hold a cookie when sending the headers you are hit by the "wait while we check your browser". This is breaking a lot of automation which used to use the login pages. Unsure how this project is currently handling the logins now as I moved back to sickchill unfortunately.

**Comment by medariox** [comment]
@MWatter 
Try to generate new cookies by logging out and logging in again. Restart Medusa once you are done. It is likely that CF is targeting your IP specifically tho, this can be temporary. Anyway, the provider works fine here and there is nothing we can do to help in such cases.
