### ISSUE TITLE
Fresh install does not "name" episodes

### ISSUE THREAD

**Issue by Tankyspanky** [pymedusa/Medusa#5423]
** Not Sure its a bugg** more a out of the box thingy i found and cant resolve 

Fresh install does not "name" episodes  example in row below .
![image](https://user-images.githubusercontent.com/16389747/46967759-b9cfeb00-d0b1-11e8-86d8-d602de6d6ffb.png)

I have no clue where to search it i have tried "all indexers" and also a single one.
(I cant backup my disk now because all files are "nameless" and on the backup external are the same files but then with a name ( from before)

Season 01 is with filenames - Season 2 does rename them to S02E01 - .***
And not the "show name" i have that with a lot of "old" added shows.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Debian 9
 - Branch: [master]
 - Commit: latest master release (sorry kinda new to this all)

I come from Sickrage, then tried Sickchill but that had a lot of errors while trying to add my series
Then people recommended Medusa because that was better and had more options.

**Comment by medariox** [comment]
The episode names come from the indexers (e.g. TheTVDB). You will need to add them on the indexers yourself, we can't do anything about it.

**Comment by Tankyspanky** [comment]
hmm, i try to understand.
I need to add the episode names to the indexer?

crap now i fell dumb :) 

Ty in advance

**Comment by plato79** [comment]
There may be some misunderstanding.. The show you added should already have episode names on TVDB (there are a lot of maintainers) or if not, you should add it yourself.. Normally you don't have to do anything about it.
