### ISSUE TITLE
Existing TV Show folder names with accented characters or apostrophes cause exception

### ISSUE THREAD

**Issue by bartolomesoriano** [pymedusa/Medusa#5426]
When adding existing shows, if the tv show folder name has accented characters or apostrophes ('), Medusa does not add the show and an exception is shown in the log.

Branch: master 
Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6 
Version: v0.2.10 
Database: 44.12
--
Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
OS: | Windows-10-10.0.18252
Locale: | en_US.cp1252

Fresh installation of Medusa under Windows 10 1809.  I have lots of shows with accented characters in the name (I have a lot of Spanish and Latin American shows), as well as shows with ' in the folder name.

When trying to add "Dirk Gently's Holistic Detective Agency", the following appears in the log and the show is not added:
```
2018-10-16 10:58:19 INFO     SHOWQUEUE-ADD :: [4614efc] Starting to add show by ShowDir: U:\Dirk Gentlyâ€™s Holistic Detective Agency
2018-10-16 10:58:19 INFO     SHOWQUEUE-ADD :: [4614efc] TVDBv2: {u'session': <medusa.session.core.MedusaSession object at 0x00000000086AFF98>, u'cache': u'C:\\pyMedusa\\cache\\indexers\\TVDBv2', u'language': u'en', u'use_zip': True}
2018-10-16 10:58:22 INFO     SHOWQUEUE-ADD :: [4614efc] 312505: Unable to find the show in the database
Traceback (most recent call last):
  File "C:\pyMedusa\medusa\show_queue.py", line 521, in run
    self.show.location = self.showDir
  File "C:\pyMedusa\medusa\tv\base.py", line 57, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "C:\pyMedusa\medusa\tv\series.py", line 398, in location
    raise ShowDirectoryNotFoundException(u'Invalid show folder!')
ShowDirectoryNotFoundException: Invalid show folder!
2018-10-16 10:58:24 ERROR    SHOWQUEUE-ADD :: [4614efc] Error trying to add show: Invalid show folder!
2018-10-16 10:58:25 INFO     SHOWQUEUE-REMOVE-SHOW :: [4614efc] 312505: Removing Dirk Gently's Holistic Detective Agency
```

The same happens when trying to add tv shows with accented characters in the name, such as "Diablo Guardián".

EDIT: Medusa added correctly the show "James Cameron's Story of Science Fiction", so I am not sure what is going on with '  in the folder name.

**Comment by p0psicles** [comment]
@medariox im pretty sure this has worked in the past. Maybe issue with locale?

**Comment by bartolomesoriano** [comment]
How would I go about checking that?

**Comment by p0psicles** [comment]
First see if someone can reproduce on win10

**Comment by p0psicles** [comment]
I can test in a few days. Maybe ill need a reminder

**Comment by bartolomesoriano** [comment]
@p0psicles, I can remind you next week.  In the meantime, I will leave out the shows with accented characters.  Does it matter for folder names what language you search with in the tvdb? I ask since I will remove the nfos for all my Spanish shows and add them again using Spanish as language.

**Comment by p0psicles** [comment]
Oow im not sure. @duramato knows

**Comment by bartolomesoriano** [comment]
@medariox So far only with NFOs. Since I am in the middle of adding all of my shows to a fresh install, I have not tried without NFOs yet.  I will be doing that for all my Spanish shows after the others finish (i have over 500 shows), and I can try that as well for the ones that did not get added.

**Comment by bartolomesoriano** [comment]
@medariox @p0psicles I deleted the NFOs of my Spanish shows and added them to Medusa, selecting Spanish as the indexer language.  All of my shows were added fine, except that Medusa did not create an NFO for any of the shows.  Is this by design or a bug? Should I open another issue? This creates a problem for me, with my media managers (Kodi, for instance, I don't do online scraping and rely always on NFOs).  Please advise.  Thanks.

**Comment by bartolomesoriano** [comment]
@medariox Thanks, I thought I had selected all of the relevant metadata for KODI 12+, I guess I did not save them correctly.

In terms of the initial issue, I found that even though for some shows with accented characters Medusa was creating a folder with garbled characters in the name, I could edit the show and select the correct folder, so in the end I was able to add all of my shows correctly.  From that perspective, this issue can be closed.  I have not tried adding a new show with accented characters, so I don't know if in that scenario Medusa performs correctly.

**Comment by p0psicles** [comment]
Do you still have one of the nfo with accent.

**Comment by duramato** [comment]
> Does it matter for folder names what language you search with in the tvdb?

The folder name is the show name in the selected language. (If it's avaiable in that language)

**Comment by bartolomesoriano** [comment]
@medariox I guess I did save the metadata settings correctly, but Medusa reverts them after a restart.  I saw that this is fixed in the develop branch, but I am not sure if this is enough for me to switch to it.  Do you recommend switching at this time?

**Comment by medariox** [comment]
If it is not urgent I advise to wait a few days until the next release.

**Comment by bartolomesoriano** [comment]
@medariox I will wait, thanks.

**Comment by p0psicles** [comment]
Could anyone checkout this branch: `feature/fix-adding-existing-unicode` and try the import with that?

**Comment by bartolomesoriano** [comment]
@p0psicles, I will test and let you know how it goes.

**Comment by bartolomesoriano** [comment]
@p0psicles, just tested the branch.  Removed some of my shows with apostrophes and accented characters, removed the NFOs, and re-imported them.  All 4 shows I tried imported without any issues, folder names were read correctly and no errors appear in the log.  

The only issue I saw with the import is that the shows did not keep some of the options I set during import, in particular Download Subtitles and Group by Season Folders.  I had to set these options again for each show.  I guess this is a different issue and not related to unicode characters.

Can I stay in this branch or should I go back to master?

**Comment by p0psicles** [comment]
The nfo looks fine here.
Didn't change language. But don't think that matters much.
![image](https://user-images.githubusercontent.com/1331394/48061560-abac5080-e1bf-11e8-9731-0ec8bf00418f.png)

**Comment by p0psicles** [comment]
I've made some changes to the branch `feature/fix-adding-existing-unicode`
Wanna do a pull, and test your shows import from folder again?

**Comment by p0psicles** [comment]
number 3. is a known error.  I'll do a quick bug report on that myself.

**Comment by bartolomesoriano** [comment]
@p0psicles I will be able to test tonight, I will report back my findings.

**Comment by bartolomesoriano** [comment]
@p0psicles Just tested, did not see any changes.  The issues I reported before are still present.

**Comment by p0psicles** [comment]
See my response to the nfo issue

**Comment by p0psicles** [comment]
What do you use to view it?

**Comment by bartolomesoriano** [comment]
Notepad++

If I have Emby server re-generate the NFO (same machine, same version of Windows 10, same Windows language) I get the below, which has the correct accented characters:

![annotation 2018-11-07 113112](https://user-images.githubusercontent.com/7786357/48141239-d8746c80-e280-11e8-818a-30a238c7177c.png)

**Comment by p0psicles** [comment]
Do you set encoding in np++ to utf-8?

**Comment by bartolomesoriano** [comment]
@p0psicles, no I did not.  I just tried that and the accented characters look fine in Notepad++.  Sorry about that and thanks for pointing that out.

**Comment by p0psicles** [comment]
Yeah don't know why it's not doing that automatically
