### ISSUE TITLE
Sickrage DB doesn't work with Medusa?

### ISSUE THREAD

**Issue by copekyle** [pymedusa/Medusa#5427]
Hoping for a quick and easy answer on Windows.  Trying to move over to Medusa but have about 90 shows in SickRage that I don't want to manually set up.  Things I have tried:
1. Back up in SickChill and restore in Medusa (FAIL)
2. Move just the Sickbeard.db file into the data folder (FAIL)
3. Manually move the Restore folder into the data folder (FAIL)

Looking at the logs, it gives an error message about there being too many SQL arguments.  Is this not something that's possible?

**Comment by p0psicles** [comment]
If its 90 shows. Better just spend the time to reimport them. Wont take you more then half an hour.

Option 2 works for most people. But if not, there arent many other options.

We dont keep track of other forks changes, to make them all migrate nicely.

**Comment by medariox** [comment]
Try to move sickbeard.db and rename it to main.db. It should work that way.

**Comment by plato79** [comment]
Maybe you didn't wait when you first launched medusa.. it takes time to convert sickbeard.db to main.db file.. When I first upgraded I thought it hung up, so I killed the process, and rerun again. But then I got SQL errors regarding missing fields etc.. After deleting main.db.* config.ini.* restoring sickbeard.db and config.ini and then running again and waiting for a while fixed the problem.
