### ISSUE TITLE
Add Join to Device Notfications

### ISSUE THREAD

**Issue by DanGarion** [pymedusa/Medusa#5428]
I would like to see Join added to device notifications. Allows consistent notifications on Desktop, Browser, and Android via push notifications.
http://joaoapps.com/join

**Comment by p0psicles** [comment]
Keep an eye out for this
https://github.com/pymedusa/Medusa/pull/5241

**Comment by DanGarion** [comment]
Doh, I'm a slacker. I know I should have searched first... Thanks! :)
