### ISSUE TITLE
Medusa doesn't recognize .STRM files

### ISSUE THREAD

**Issue by bnichs5** [pymedusa/Medusa#5434]
A lot of my tv show library files are .STRM and it doesn't seem that Medusa can see them. Is this something that can easily be implemented into the next update? I dont need medusa to download them in that format. I just want for medusa to recognize that I already have that episode. Thanks!

**Comment by p0psicles** [comment]
As in text files that have a link to the actual video file?

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5438
