### ISSUE TITLE
After importing from SickRage, some options are broken

### ISSUE THREAD

**Issue by plato79** [pymedusa/Medusa#5436]
After upgrading from Sickrage's config.ini and sickrage.db there are some settings broken in configuration:
- Sync File Extensions: !, s, y, n, c, ,, l, f, t, p, -, p, g, e, t, -, s, t, a, t, u, s, ,, b, t, s, ,, !, q, b, ,, !, q, B
- Keep associated file extensions: a, s, s, ,, s, u, b, ,, i, d, x, ,, n, f, o, ,, s, r, r, ,, s, f, v, ,, s, r, t 

**To Reproduce**
clone the Medusa repository.
put Sickrage's config.ini and sickbeard.db to the root directory of Medusa
run and wait until it parses db and ini file.
check config.

**Expected behavior**
it should be like this:
- Sync File Extensions: !sync, lftp-pget-status, !qb, !qB (not very sure about that but something like this) 
- Keep associated file extensions: ass, sub, idx, nfo, srr, sfv, srt

Medusa Info: | Branch: master Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6 Version: v0.2.10 Database: 44.12
Python Version: | 2.7.14 (default, Oct 19 2017, 01:17:20) [GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)]
SSL Version: | OpenSSL 1.0.2j-freebsd 26 Sep 2016
OS: | FreeBSD-11.1-STABLE-amd64-64bit-ELF
Locale: | Unknown.Unknown

**Comment by ward0** [comment]
what happens when you take a backup in sickrage and import in medusa trough config?

**Comment by plato79** [comment]
don't really know, because after last problems with who owns what part of sickrage I think they broke it completely :D

**Comment by p0psicles** [comment]
Cant you just manually correct these?

**Comment by plato79** [comment]
I already did.. Just wanted to inform you there's something wrong with importing config.ini from sickrage..

**Comment by p0psicles** [comment]
Okay thanks, but i dont think anyone is going to "fix" that. Good you have it working
