### ISSUE TITLE
Put a custom url for other blocked providers

### ISSUE THREAD

**Issue by plato79** [pymedusa/Medusa#5437]
**Is your feature request related to a problem? Please describe.**
Well, in Turkey rarbg is blocked so it'd be good if we could provide custom urls for it like piratebay

**Describe the solution you'd like**
Put a custom url in every blocked or blockable providers..

**Describe alternatives you've considered**
I don't think there's any alternative for this.. Other than connecting the server to a VPN, but that doesn't solve the problem gracefully, and it could cause other problems..

**Comment by duramato** [comment]
Are you sure RARBG is blocked? We use a costum url. Can you access: https://torrentapi.org/apidocs_v2.txt ?

**Comment by plato79** [comment]
Yes, I can.. I live in Turkey and rarbg.to is blocked, though I can access it via rarbgmirror.com

**Comment by duramato** [comment]
> Yes, I can.. 

Then rarbg isn't blocked for you in Medusa, like I said it doesn't use rarbg.to to access the site, so a url mirror isn't needed and won't even work.
