### ISSUE TITLE
Allow a Default file quality for files of an unknown type

### ISSUE THREAD

**Issue by ServerGuyHK** [pymedusa/Medusa#5442]
When adding a show that is in an existing directory, there can be a mix of file types within the show directory and these could have different file qualities.

For example when adding a show I found that the .MKV files added OK but the .ISO files added to the show as "downloaded unknown".

This "downloaded unknown" status causes the search processes to then look for and update the .ISO files with downloaded and sometimes worse quality files.

So being able to specify that during an "add existing show" you can set the default file quality to be "xyz" when the file quality cannot be read when the directory is scanned. Thus .ISO files will be added to the show and won't be subjected to being deleted and replaced by new downloads.

**Comment by medariox** [comment]
Iso files are not supported.
