### ISSUE TITLE
Adding titles to anidb causes error

### ISSUE THREAD

**Issue by plato79** [pymedusa/Medusa#5448]
**Describe the bug**
When postprocess tries to add the title to anidb my list there is an error in the log

`anidb exception msg: TypeError(u'option values must be strings',)
`
**To Reproduce**
Post process any anime title

**Expected behavior**
The title should be added to anidb mylist.

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64]
 - Branch: [e.g. master, develop]
 - Commit: [e.g. c65ca2]

**Logs:**
`2018-10-18 10:06:33 WARNING  Thread_0 :: [4614efc] anidb exception msg: TypeError(u'option values must be strings',)`

**Comment by plato79** [comment]
I saw this error also:

`Exception message: TypeError("add_to_mylist() got an unexpected keyword argument 'status'",)`

**Comment by p0psicles** [comment]
Can you reproduce with a recent build?

**Comment by p0psicles** [comment]
my guess is, that if you run medusa with python3, issue is resolved.

**Comment by plato79** [comment]
I changed my init script to start medusa with python3.6 now... But even with python2.7 I didn't get that error for a while I think.
