### ISSUE TITLE
Faulty processing of multipart episodes

### ISSUE THREAD

**Issue by plato79** [pymedusa/Medusa#5449]
**Describe the bug**
There are some episodes which are more than one part..
Here is an example:

ripper.street.s04e01.1080p.bluray.x264-turmoil.mkv
ripper.street.s04e01.part.2.1080p.bluray.x264-turmoil.mkv

There were some more but they're lost when Medusa moved them over the other part.

Some files are like this..

Title.s01e01.part.1.1080p.....
Title.s01e01.part.2.1080p.....

So Medusa thinks but files are for S01 E01 and if the part processed after is a little bit longer than the other one, then it moves it over the first part it processed and causes one of the parts lost in process.

**To Reproduce**
Post process a title with multi-part episode.

**Expected behavior**
I'm not sure how to address this situation. There are some shows which are divided like this by scene. But I think the show is designed that way so I couldn't say that what scene doing is wrong.

After Medusa renames the file, I'm not sure if it remembers the original name, so it may need to check to see if there's another file with the same episode, it should check the processed file's original name, and if it has or the processing file's name has "part" somewhere in the file name it should name it accordingly.. Like:

Ripper Street - S01E01 - I Need Light [shortbrehd.1080p.BluRay].mkv
Ripper Street - S01E01 - I Need Light (II) [shortbrehd.1080p.BluRay].mkv

It would be a little more problem when the second part is processed first. Though after detecting correctly I don't think it'll be a big problem.

Medusa Info: 
Branch: master 
Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6 
Version: v0.2.10 
Database: 44.12
Python Version: | 2.7.14 (default, Oct 19 2017, 01:17:20) [GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)]
SSL Version: | OpenSSL 1.0.2j-freebsd 26 Sep 2016
OS: | FreeBSD-11.1-STABLE-amd64-64bit-ELF
Locale: | Unknown.Unknown

**Comment by desepticon** [comment]
Why are these being released in two parts? I have the same show in my database. I checked my S01E01 with mediainfo and it shows as a 59min episode. Other episodes show a similar length. Standard episode length.

I would suggest concatenating these weird eps with mkvtoolnix.

**Comment by medariox** [comment]
Medusa won't support silly namings.
