### ISSUE TITLE
How do I trun post processing on?

### ISSUE THREAD

**Issue by ausghostdog** [pymedusa/Medusa#5450]
**Describe the bug**
![image](https://user-images.githubusercontent.com/7588602/47138211-1e7e8600-d2fc-11e8-98c9-115776140f31.png)
Noticed my files were not processing, manual was working
![image](https://user-images.githubusercontent.com/7588602/47138307-5b4a7d00-d2fc-11e8-9c5c-caa355eb880b.png)

**To Reproduce**
No idea

**Expected behavior**
it to be turned on

**Screenshots**

**Medusa (please complete the following information):**
![image](https://user-images.githubusercontent.com/7588602/47138490-e88dd180-d2fc-11e8-8fb7-709a9b94cd21.png)

**Logs:**
No idea where to find them, I checked in logs for processing but no errors

```
<-- Please replace this whole line with your logs -->
```
</details>

**Additional context**
I just want it turned on

**Comment by plato79** [comment]
It looks like it's already active.

Scheduled Postprocessor is the option to turn on automatic post processing.

**Comment by ausghostdog** [comment]
@plato79 In server status post process is not alive, so not working

**Comment by plato79** [comment]
Did you try restarting Medusa? 

Though I think it's only alive when it's actively processing the folder... For example when I start processing the folder it becomes "Alive". I configured it for manual processing. So it's not a problem I think.
