### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: TNT (US)

### ISSUE THREAD

**Issue by taktlos79** [pymedusa/Medusa#5459]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.8-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/781f75c121c9290b45e34d9823940112
### ERROR
<pre>
2018-10-19 21:14:51 ERROR    Thread_1 :: [4614efc] Missing time zone for network: TNT (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
>  TNT (US)

Already in the list https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L1938

**Comment by Dale-J** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/873a5c215259cfed8411d86dc48156fa
### ERROR
<pre>
2018-10-24 23:02:45 ERROR    Thread_1 :: [4614efc] Missing time zone for network: TNT (US)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
