### ISSUE TITLE
how to add a sport show?

### ISSUE THREAD

**Issue by ashenkin** [pymedusa/Medusa#5462]
I've seen mention of configuring medusa to download sports, but i don't see any suitable indexers... wondering if someone can point me in the right direction?

**Comment by medariox** [comment]
TVmaze has sports shows.

**Comment by p0psicles** [comment]
Just a heads up. Downloading sports is not that functional right now. As the "episodes" are mostly not named in a standard way.

A new feature currently in development will improve on this. 

But then guessit will still need to be able to parse the title correctly.

**Comment by joeportela** [comment]
@p0psicles Is there any interest in adding support for https://www.thesportsdb.com indexing? I would be willing to make the contributions to get it done myself. If there is interest, I'd be happy to open a new issue to re-ignite a discussion.

**Comment by p0psicles** [comment]
Medusa is build around showid, season and episode. I don't think that site is build with these principles in mind. Don't think it's doable

**Comment by p0psicles** [comment]
It's not really about interest, it's more about if its possible without having to change the db structure

**Comment by joeportela** [comment]
Probably couldn't full support all the different data types they have (like Teams), but I think the mapping could work well with showid == League, season == Season (usually year), and episode == Event.

I think the biggest challenge would be that each League would likely need its own pattern matching formula for searching indexers, but since there aren't that many Leagues, and they don't change much at all, it might not be a huge burden after initial setup.

**Comment by joeportela** [comment]
I use BTN primarily and they support many of the Leagues on TheSportsDB using that data type mapping.

**Comment by p0psicles** [comment]
Next is an open documented api. We don't scrape sites. Then it should allow for searching the api by name (the league). And provide results with league + year started. And after api should return a minimum amount of info.

It's allot of work to get all this info. And I'm not going to start on such a big project for coming year. My advice is to make sure your sport shows get properly added to tvmaze or tmdb

**Comment by p0psicles** [comment]
Indication for the amount of work. I started on adding IMDb. https://github.com/pymedusa/Medusa/pull/3603
But that api is missing some info. So it's on halt. 

With this PR merged you'll be able to define your own search templates. So it will be able to find any show. https://github.com/pymedusa/Medusa/pull/3732

**Comment by p0psicles** [comment]
Added search templates, which should improve sport show support.
