### ISSUE TITLE
How to change Port from 8081 to another one?

### ISSUE THREAD

**Issue by digitalnaiveDE** [pymedusa/Medusa#5476]
hi there,

i am fairly new to Medusa and have formerly used sickrage. That was tricky for me but i was able to set it up and using it for a while.

Now i´ve downloaded and installed it on my Ubuntu Server following a guide because i have almost no experience using linux. On that machine i have another software running which is using port 8081. So i need to use another port like 8083.

How do i change that?

**Comment by digitalnaiveDE** [comment]
@p0psicles can you please so kind and tell me which line I have to change?

**Comment by p0psicles** [comment]
Just search for web_port

**Comment by digitalnaiveDE** [comment]
@p0psicles I have opened config.py in the medusa folder with sudo nano config.py and searched for web_port. "web_port not found"

What am i doing wrong?

**Comment by medariox** [comment]
Try with `config.ini` now. 😖

**Comment by digitalnaiveDE** [comment]
I have no config.ini at the moment?!

I followed this guide: https://github.com/pymedusa/Medusa/wiki/Ultimate-Medusa-Linux-Guide

But there is no config.ini in either /srv/media nor /srv/media/medusa

**Comment by bjwest** [comment]
This may be due to a three year gap in the versions, but there is no config.ini anywhere in the /opt/madusa tree.  Perhaps be a bit more specific than just the file name with an application that has hundreds of subdirectories in its tree.
