### ISSUE TITLE
Medusa fails to start on Ubuntu 18.10

### ISSUE THREAD

**Issue by bradmann** [pymedusa/Medusa#5477]
**Describe the bug**
Recently updated my Ubuntu version from 18.04 -> 18.10 and Medusa no longer starts.

**To Reproduce**
1. Attempt to start Medusa.
2. Receive the following error:
user@mediapc:~$ systemctl status medusa.service
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-10-22 08:18:43 EDT; 6min ago
  Process: 13799 ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa (code=exited, status=1/FAILURE)

Oct 22 08:18:43 mediapc python2.7[13799]:   File "/opt/medusa/medusa/scene_exceptions.py", line 13, in <module>
Oct 22 08:18:43 mediapc python2.7[13799]:     import adba
Oct 22 08:18:43 mediapc python2.7[13799]:   File "/opt/medusa/ext/adba/__init__.py", line 27, in <module>
Oct 22 08:18:43 mediapc python2.7[13799]:     from configparser import ConfigParser
Oct 22 08:18:43 mediapc python2.7[13799]:   File "/opt/medusa/ext/configparser.py", line 12, in <module>
Oct 22 08:18:43 mediapc python2.7[13799]:     from backports.configparser import (
Oct 22 08:18:43 mediapc python2.7[13799]: ImportError: cannot import name ConverterMapping
Oct 22 08:18:43 mediapc systemd[1]: medusa.service: Control process exited, code=exited status=1
Oct 22 08:18:43 mediapc systemd[1]: medusa.service: Failed with result 'exit-code'.
Oct 22 08:18:43 mediapc systemd[1]: Failed to start Medusa Daemon.

**Expected behavior**
Medusa should start

**Medusa (please complete the following information):**
 - OS: ubuntu 18.10 x64
 - Branch: master
 - Commit: 4614ef

**Comment by p0psicles** [comment]
Can you run: pip uninstall configparser?

**Comment by bradmann** [comment]
Was able to remedy by running:
# sudo pip uninstall configparser
# sudo pip install configparser
