### ISSUE TITLE
"Edit show" is broken for anime

### ISSUE THREAD

**Issue by rnd256** [pymedusa/Medusa#5479]
**Describe the bug**
When clicking the "edit" button on an anime, the server stops responding. No debug logs are produced.

**To Reproduce**
1. Go to any anime show page within Medusa.
2. Click on "Edit".
3. See that the server has stopped responding.
4. Try to open any other page.
5. See that the server now has stopped responding on all pages.

**Expected behavior**
Server displays the "edit show" page.

**Medusa (please complete the following information):**
 - OS: ubuntu, running linuxserver/medusa latest (https://hub.docker.com/r/linuxserver/medusa/tags/)
 - Branch: master

**Logs:**
Nothing is logged, even when debug logs are enabled. The server just freezes.

**Additional context**
Possible related to this issue:
https://github.com/pymedusa/Medusa/issues/4633

**Comment by rnd256** [comment]
Branch: master
Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6
Medusa Version: v0.2.10
Database: 44.12
Python Version: 2.7.15
SSL Version: LibreSSL 2.7.4
OS: Linux-4.4.0-103-generic-x86_64-with

**Comment by p0psicles** [comment]
Fixed in develop
