### ISSUE TITLE
Showlist empty after reboot

### ISSUE THREAD

**Issue by StijnDC** [pymedusa/Medusa#5485]
**Describe the bug**
After leaving sickrage for what it is i installed medusa using the HTPC guide and started adding my excisting shows to medusa.

after fixing some issues with Medusa not starting with booting the RPI. (permissions) i now get medusa to start with the RPI.
i first tried importing a back-up of sickrage (deleting de failed.db and cache.db) but that did not seem to work. i then added my excisting shows to medusa and configured everything as i wanted it.

Sadly after rebooting the RPI i noticed that the medusa showlist is completely empty.
i then added a single show, rebooted again, and again the list was empty.

thinking this might be a .DB error i removed all the .DB files from the /opt/medusa folder. 
restarted the RPI, added another show, rebooted and the showlist is again empty.

all the other settings are retained after reboot. and i'm kind of stumped.

**Medusa (please complete the following information):**

Medusa Info: | Branch: master 
Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6 
Version: v0.2.10
Database: .0
-- | --
Python Version: | 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
SSL Version: | OpenSSL 1.1.0f 25 May 2017
OS: | Linux-4.14.34-6-osmc-armv7l-with-debian-9.5
Locale: | Unknown.Unknown

**Comment by medariox** [comment]
Something is very wrong with your setup. Probably the user running Medusa doesn't have the correct rights/permissions to access the database.

**Comment by StijnDC** [comment]
i Created a user "medusa", that is also the user that has the rights to /opt/medusa.
using "sudo chown -R medusa:medusa /opt/medusa"

Could it be possible that it creates a temp db that cannot be read after a reboot?

**Comment by p0psicles** [comment]
You checked that the python process is started by the medusa user?

**Comment by StijnDC** [comment]
I will check later today (not at the location)
that should be with "ps -ef | grep medusa" right?

P.S. please note that i have limited knowledge of linux and i'm currently in the process of learning more about it and how it works ;)

**Comment by StijnDC** [comment]
![image](https://user-images.githubusercontent.com/5908942/47529353-dc2ee900-d8a7-11e8-8fa8-41d1a9a9aad6.png)

Please note the output of the command.

also note the output of the journalctl -xe command:

![image](https://user-images.githubusercontent.com/5908942/47529398-fe286b80-d8a7-11e8-82b9-707f1efa3850.png)

looks like when starting medusa it's trying to restore a database, which it cannot find thus leaving the .DB empty

**Comment by StijnDC** [comment]
Hi guys,

I completely wiped the /opt/medusa folder and started from scratch.
i think it's the sickrage restort the screwed everything over.

clean install is the best after all ;)
