### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: CNBC

### ISSUE THREAD

**Issue by Dale-J** [pymedusa/Medusa#5490]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/83a2f1bf484c3642e93aa6249783d7ce
### ERROR
<pre>
2018-10-24 10:30:24 ERROR    Thread_6 :: [4614efc] Missing time zone for network: CNBC
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Dale-J** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/817e492f99ec8134625d64ea097ffcf2
### ERROR
<pre>
2018-10-24 23:02:45 ERROR    Thread_1 :: [4614efc] Missing time zone for network: CNBC
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
> CNBC

Already in the list https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L394
