### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: RTÉ One

### ISSUE THREAD

**Issue by Dale-J** [pymedusa/Medusa#5492]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/89641319adb759a42696e30c8a04a85c
### ERROR
<pre>
2018-10-24 10:30:24 ERROR    Thread_5 :: [4614efc] Missing time zone for network: RTÉ One
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Dale-J** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/cd422cf3d4cdbf9b1b9c4807021e2e3c
### ERROR
<pre>
2018-10-24 23:02:46 ERROR    Thread_1 :: [4614efc] Missing time zone for network: RTÉ One
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
> RTÉ One

Already in the list https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L1604
