### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: BBC America

### ISSUE THREAD

**Issue by Dale-J** [pymedusa/Medusa#5494]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/aefb4541add28fda26bb26267a48da5c
### ERROR
<pre>
2018-10-24 10:30:24 ERROR    Thread_9 :: [4614efc] Missing time zone for network: BBC America
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Dale-J** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/dd9b768742605a3cf737b3129906fed9
### ERROR
<pre>
2018-10-24 23:02:46 ERROR    Thread_1 :: [4614efc] Missing time zone for network: BBC America
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
> BBC America

Already in the list https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L216
