### ISSUE TITLE
Installation on Asustor?

### ISSUE THREAD

**Issue by Aesculapius** [pymedusa/Medusa#5506]
Hi,

On one page it is described that installation candidates are available for NASes including Asustor. Running an Asustor AS-7008T with Sickrage currently and want to switch to Medusa, but can't find any guides or packages that allow me to do so...

What would be the best approach?

**Comment by Aesculapius** [comment]
Never mind, got it working by using the Sickrage package, which allowed me to enter a custom github URL.

Is it possible to import the exported sickrage config or should I start over?

**Comment by p0psicles** [comment]
Should be possible. You can give it a try. You can always start fresh.

**Comment by aiiDaH** [comment]
Hi

Im not allowed in any moment of the sickrage installation to write the custom github URL for medusa, can someone please help me out here, I'm on a Asustor NAS
