### ISSUE TITLE
Releases by HorribleSubs are detected as HDTV instead of WEB-DL

### ISSUE THREAD

**Issue by MrTimscampi** [pymedusa/Medusa#5527]
**Describe the bug**
Every release by the group HorribleSubs is detected as HDTV source instead of WEB-DL.  
HorribleSubs being a team that rips WEB-DLs, it doesn't really make sense.

This is likely a Guessit issue though ?

**To Reproduce**
1. Add a currently airing anime
2. Search for an episode
3. Releases by HorribleSubs show up as HDTV

**Expected behavior**
This group doesn't do TV rips, they only rip from streaming services like Crunchyroll, Amazon Prime, etc. So they should automatically be WEB-DL.

**Screenshots**
n/a

**Medusa (please complete the following information):**
 - OS: Fedora 28 x64
 - Branch: develop
 - Commit: lasted commit

**Logs:**
n/&

**Additional context**
Here's what their filenames looks like: [HorribleSubs].Grand.Blue.-.01.[1080p].mkv

**Comment by p0psicles** [comment]
Its more that they dont follow the scene rules. So they should add Webdl to their release names. We go from the release names. Alternative is to keep a cached lookup table. And enrich parsed releases from that. But then you need a source to sync table with. All allot of work, because the release group refuses to properly name?

**Comment by MrTimscampi** [comment]
They're following the anime "scene" naming conventions, which are unfortunately a goddamn mess (Ony of my many gripes with the anime community, along with 10-bit encoding and a whole bunch of other stuff).

I don't know if any other team falls into the same trap (Though honestly I'd guess that nowadays the majority of anime releases are WEB-DL, except for the odd show or group).

**Comment by p0psicles** [comment]
But still. This is not a bug. The release bames are parsed correctly.

This could be a feature request, to map certain release groups to a fixed source. I dont think we should want that.

**Comment by medariox** [comment]
Not a bug, no source in the title defaults to HDTV.
