### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: LivingTV

### ISSUE THREAD

**Issue by hackerjack42** [pymedusa/Medusa#5528]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.105-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-10-27 23:13:48 ERROR    Thread_16 :: [4614efc] Missing time zone for network: LivingTV
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/47fe8784853086453d4e1d0caa16a857c39b636b
