### ISSUE TITLE
Implement rate limiter/cool down period in TMDB API requests

### ISSUE THREAD

**Issue by hackerjack42** [pymedusa/Medusa#5529]
**Is your feature request related to a problem? Please describe.**
I frequently receive the following error when trying to update/scan shows.

`Error: Indexer TMDB is unavailable at this time. Cause: 429 Client Error:`

**Describe the solution you'd like**
Check "X-RateLimit" headers when making requests with the TMDB API.

**Describe alternatives you've considered**
I obtained my own API key and updated my local app.py file.  I then read that limits are by IP address, not API key, so my attempt was a failure.

**Additional context**
Per the TMDB API documentation, requests are limited to 40 every 10 seconds.

https://developers.themoviedb.org/3/getting-started/request-rate-limiting

**Comment by hackerjack42** [comment]
So...I couldn't let this go.  I'm no Python developer by any definition, but I decided to take a whack at it.

It seems that the issue is in the tmdbsimple library.  I think I found a simple solution whereas it watches for status code 429 and then waits for the number of seconds specified in the "Retry-After" response header.  I commented on an [existing issue](https://github.com/celiao/tmdbsimple/issues/55) on their GitHub page.  Hopefully someone over there will pick it up and make the modifications.

In the meantime, here's what I did to make it work.

```diff
diff --git a/lib/tmdbsimple/base.py b/lib/tmdbsimple/base.py
index d178f66b3..8c96ccfe1 100644
--- a/lib/tmdbsimple/base.py
+++ b/lib/tmdbsimple/base.py
@@ -13,6 +13,7 @@ Created by Celia Oakley on 2013-10-31.

 import json
 import requests
+import time


 class APIKeyError(Exception):
@@ -72,10 +73,16 @@ class TMDB(object):
         url = self._get_complete_url(path)
         params = self._get_params(params)

-        response = requests.request(
-            method, url, params=params,
-            data=json.dumps(payload) if payload else payload,
-            headers=self.headers)
+        retry = True
+        while retry:
+            retry = False
+            response = requests.request(
+                method, url, params=params,
+                data=json.dumps(payload) if payload else payload,
+                headers=self.headers)
+            if response.status_code == 429:
+                retry = True
+                time.sleep(int(response.headers['Retry-After']))

         response.raise_for_status()
         response.encoding = 'utf-8'
```

**Comment by medariox** [comment]
TMDB has disabled rate limits.
