### ISSUE TITLE
UnboundLocalError: local variable 'cur_ep_enddate' referenced before assignment

### ISSUE THREAD

**Issue by zodd721** [pymedusa/Medusa#5535]
**Describe the bug**
When navigating to the "Schedule" page I receive the following error message:

File /opt/medusa/themes/dark/templates/partials/schedule/list.mako:52, in render_body:
                <% ends = sbdatetime.sbdatetime.convert_to_setting(cur_ep_enddate) %>
UnboundLocalError: local variable 'cur_ep_enddate' referenced before assignment

**To Reproduce**
1. Go to home screen
2. Click on Schedule

**Expected behavior**
The Schedule page should open showing upcoming episodes

**Screenshots**
![image](https://user-images.githubusercontent.com/44557412/47623364-afb0e200-dade-11e8-92c6-0b2aa0fa9275.png)

**Medusa (please complete the following information):**
 - OS: Ubuntu 16.04
 - Branch: master
 - Commit:  4614efc77151ded92ef458a09dec39f8bd5acfc6
 - Python: 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]

**Logs:**
<details>

```
2018-10-28 17:15:51 DEBUG    Thread_1 :: [4614efc] File /opt/medusa/medusa/server/web/core/base.py, line 121, in render
2018-10-28 17:15:51 DEBUG    Thread_1 :: [4614efc] File /opt/medusa/ext/mako/template.py, line 471, in render_unicode
2018-10-28 17:15:51 DEBUG    Thread_1 :: [4614efc] File /opt/medusa/ext/mako/runtime.py, line 838, in _render
2018-10-28 17:15:51 DEBUG    Thread_1 :: [4614efc] File /opt/medusa/ext/mako/runtime.py, line 873, in _render_context
2018-10-28 17:15:51 DEBUG    Thread_1 :: [4614efc] File /opt/medusa/ext/mako/runtime.py, line 899, in _exec_template
2018-10-28 17:15:51 DEBUG    Thread_1 :: [4614efc] File /opt/medusa/themes/dark/templates/layouts/main.mako, line 79, in render_body
2018-10-28 17:15:51 DEBUG    Thread_1 :: [4614efc] File /opt/medusa/themes/dark/templates/schedule.mako, line 165, in render_content
2018-10-28 17:15:51 DEBUG    Thread_1 :: [4614efc] File /opt/medusa/ext/mako/runtime.py, line 761, in _include_file
2018-10-28 17:15:51 DEBUG    Thread_1 :: [4614efc] File /opt/medusa/themes/dark/templates/partials/schedule/list.mako, line 52, in render_body
2018-10-28 17:15:51 INFO     Thread_1 :: [4614efc] UnboundLocalError: local variable 'cur_ep_enddate' referenced before assignment
2018-10-28 17:15:51 INFO     TORNADO :: [4614efc] 200 GET /schedule/ (192.168.0.211) 749.75ms
```
</details>

**Additional context**

**Comment by zodd721** [comment]
Ok, this is weird. I was able to reproduce this issue consistently for over 12+ hours yesterday. This was after trying to reboot the Linux box and restart Medusa multiple times. Now, after checking it again this morning the issue has gone away. Obviously, there's some value that was missing then that now exists. I don't know if there's any interest in trying to figure out why or should I just close it?

**Comment by medariox** [comment]
One of your shows didn't have the `runtime` for some reason. It probably updated during the night with the scheduled show updater. Yes, please keep the issue open as it seems to be a bug.

**Comment by Thuid** [comment]
I am getting the same thing happening. Is there a way to find the show that is causing this or override/ignore the show/episode?

**Comment by p0psicles** [comment]
Do you know how to use an sqlite editor? Like sqlite3 on linux?

**Comment by Thuid** [comment]
Yes. But my installation is on a Synology NAS, so that complicates it a bit.

On Nov 7, 2018 4:31 AM, "p0ps" <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you know how to use an sqlite editor? Like sqlite3 on linux?

**Comment by zodd721** [comment]
I tried to figure this out. However, I know Python but I don't understand Mako and wasn't doing a very good job at tracking it back in the code. Is the runtime value equal to the airs column in the tv_shows table?

**Comment by p0psicles** [comment]
Can you try to open main.db with sqlite and run the query: `select * from tv_shows where runtime = '' or runtime is null;` ?

**Comment by medariox** [comment]
Adding something like `or 45` to this line should fix this: https://github.com/pymedusa/Medusa/blob/0c0a73583452f988c518adeafa75ee1f17987bdf/themes-default/slim/views/partials/schedule/list.mako#L29

But not a great solution hard-coding the show run time. It would be interesting to know which indexer/show is causing this.

**Comment by p0psicles** [comment]
@zodd721 Switching from list to some other schedule layout will also temporary fix it for you.

**Comment by zodd721** [comment]
I'm not currently experiencing the issue anymore but my curiosity got the best of me and I decided to look. Realized I had an oh duh moment. I couldn't find the "runtime" column because I was looking at the wrong table. tv_shows definitely has "runtime" my bad. Your select statement works fine for me but I currently lack any blank values.  @Thuid would need to verify? I'd like to know which show as well? Really appreciate the quick responses everyone..

**Comment by Thuid** [comment]
Or even if not found, code it to '0' instead of ' ' or null. Would that work, then at lease a '0' runtime would stand out when scanning the list as a problem show.

**Comment by Thuid** [comment]
Okay I don't think it is just the `runtime` field that is causing this. I am getting the error again today, but when I check the database there is no '' or NULL values this time. Is there anything else that may cause this?

**Comment by medariox** [comment]
Post the error please.

**Comment by Thuid** [comment]
File /volume1/@appstore/sickbeard-custom/var/SickBeard/themes/dark/templates/partials/schedule/list.mako:51, in render_body:
                <% ends = sbdatetime.sbdatetime.convert_to_setting(cur_ep_enddate) %>
UnboundLocalError: local variable 'cur_ep_enddate' referenced before assignment

**Comment by medariox** [comment]
What branch are you on? Please post the log, not just the copied error.

**Comment by Thuid** [comment]
Branch: master
Commit: 0c0a73583452f988c518adeafa75ee1f17987bdf
Version: v0.2.11
Database: 44.12
[application.log](https://github.com/pymedusa/Medusa/files/2568377/application.log)

**Comment by medariox** [comment]
The fix is not in master yet.

**Comment by p0psicles** [comment]
### INFO
**Python Version**: `3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-4-amd64-x86_64-with-debian-9.6`
**Locale**: `UTF-8`
**Branch**: [feature/py3_2](../tree/feature/py3_2)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@76c294edaca2d0070efb7b9fc04f688309796f0d
**Link to Log**: https://gist.github.com/6e13060cfdfe53bcf066cf083007f37a
### ERROR
<pre>
2018-12-10 21:14:12 ERROR    Thread-34 :: [76c294e] Exception generated: local variable 'e' referenced before assignment
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/76c294edaca2d0070efb7b9fc04f688309796f0d/medusa/server/web/core/base.py#L262">medusa/server/web/core/base.py</a>", line 262, in async_call
    result = function(**kwargs)
  File "/opt/medusa/<a href="../blob/76c294edaca2d0070efb7b9fc04f688309796f0d/medusa/server/web/home/add_shows.py#L207">medusa/server/web/home/add_shows.py</a>", line 207, in popularShows
    recommended_shows=recommended_shows, exception=e, groups=[],
UnboundLocalError: local variable 'e' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
