### ISSUE TITLE
Ios12 safari shows only loading page

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#5552]
**Describe the bug**
Opening the 0.2.11 Medusa on an iPad using safari only shows 
```
Loading…
If this is taking too long,
click here to show the page.
```

Clicking also does not show any success.

It is working perfectly fine using chrome on the same iPad or safari on a mac. 
Is there anything special (like clearing caches ) that needs to be / can be done?

**Comment by p0psicles** [comment]
I dont know what to do with this? Dont have any mac stuff.

**Comment by udochrist** [comment]
Cache issue. After cleaning the safari caches on the iPad Medusa is now working.
