### ISSUE TITLE
Torrent Client - Synology DS - Wrong file name

### ISSUE THREAD

**Issue by pathoz** [pymedusa/Medusa#5559]
**DESCRIPTION**:
Attempting to configure Synology DS as torrent client.  After entering correct details and clicking "test" an error is generated:

> WARNING  Thread_0 :: [0c0a735] Error while testing downloadstation connection: No module named downloadstation_client

**RESOLUTION**:
Rename /opt/medusa/medusa/clients/torrent/download_station_client.py to downloadstation_client.py

**Medusa (please complete the following information):**
 - OS: ubuntu 18.04 server
 - Branch: master
 - Commit: 0c0a73583452f988c518adeafa75ee1f17987bdf

**Comment by medariox** [comment]
Thanks for the bug report. This will be fixed with: https://github.com/pymedusa/Medusa/pull/5561
