### ISSUE TITLE
Torrent file content is empty

### ISSUE THREAD

**Issue by southeast123** [pymedusa/Medusa#5565]
Hi , after I updated to 0.2.11 (2018-10-29)b I'm getting warnings.  Medusa is not adding torrents to qBittorrent anymore on auto. 
If I go to the show, manual search, and select download then Medusa will drop it in qBittorrent 4.1.3 (tho).

2018-10-30 20:10:52 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [0c0a735] Torrent file content is empty: The.Real.Fat.Guy.Eating.Marshmellows.S13E15.WEB.x264-TBS[rartv]

**Comment by p0psicles** [comment]
Is this reproducable behavior? As in what does a forced search do?

**Comment by medariox** [comment]
Which provider? Please post full debug logs.

**Comment by southeast123** [comment]
Sorry I didn't come back sooner. 
It's working now. After a couple manual downloads and/or setting qBittorrent options back to "when it was working" settings. Then while sleeping it caught up to date.

I came from the SickRage and SickRageTV mess. Pretty sure I had the foul hooked one. Installed Medusa fresh and hopefully removed all the Sickrageblah

I'll be sure to show up with debug logs if there's a next time. TY!
