### ISSUE TITLE
Absolute scene numbering not working for anime

### ISSUE THREAD

**Issue by lewis269** [pymedusa/Medusa#5570]
There are two issues with scene numbering. 
1. Absolute scene numbering isn't being automatically updated from sources such as TVDB or anidb. All absolute scene numbers are set as 0. 

2. If you manually change a scene number on one episode. It will change the scene numbering for every episode to that same number. So all episodes end up with absolute scene number "57" for example. See screenshot below. 

Debug turned on but no logs when making a manual change to scene numbering. 
Some animes such as one piece have the correct scene numbering. (Too afraid to change it in case it messes it up) but unsure if this is because of reliable source information or a leftover piece of data when migrating from sickrage.  
I have scene numbering enabled in all anime shows. 
![screenshot_20181031-231649](https://user-images.githubusercontent.com/27728386/47787464-1fcf9a00-dd63-11e8-9f0b-19aefc4a1511.png)

**Comment by lewis269** [comment]
I think I may have possibly fixed this by removing the show. Removing all tbn and NFO files from the shows directory. And then re-adding the show with scene numbering and anime enabled. 
This has also seemed to have fixed the bug with it changing all episodes to a specific number. 
Even still, should not have to do this to get scene numbering to work. 

Not a high priority as a manual fix is available.

**Comment by p0psicles** [comment]
Yeah but it has to be somehow reproducable to be able to fix it.
