### ISSUE TITLE
Not finding torrent

### ISSUE THREAD

**Issue by Masterditto** [pymedusa/Medusa#5582]
**Describe the bug**
Taking example in the TV series "Arrow", medusa refuses to find "Arrow.S07E02.Custom.DKsubs.720p.WEB-DL.H.264-SUBSTANCE"
Where required word "Substance" is the only criteria for medusa. It easily find others (look below in log section)

This happends to all releases from "Substance" (Tracker: DanishBits) and "YesWeAre" (Tracker: NordicBits)

**To Reproduce**
Setup Medusa to do a search for "Arrow" with required word "Substance" on tracker DanishBits or "Supernatural" with required word "YesWeAre" on tracker NordicBits

I will gladly have you take a look from within my pc remotely, debug log says nothing else than normal log.

**Expected behavior**
Expected behavior is it should download and find this "Substance" and "YesWeAre" releases. Been trying to fix this for days now.
Please help :)

**Screenshots**
None that would help better.

**Medusa (please complete the following information):**
 - OS: Linux Synology running SickBeard with Medusa set as master Branch
 - Branch: master
 - Commit: Not sure what is needed here?

**Logs:**
Not finding "Substance" Arrow episode on DanishBits.

```
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [0c0a735] Unable to find forced results for: Arrow - S07E02 - The Longbow Hunters
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [Danishbits] :: [0c0a735] Ignoring Arrow.S07E02.1080p.HEVC.x265-MeGusta based on required words filter: [u'SUBSTANCE']
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [Danishbits] :: [0c0a735] Quality of Arrow.S07E02.1080p.HEVC.x265-MeGusta is 1080p HDTV
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [Danishbits] :: [0c0a735] Ignoring Arrow.S07E02.HDTV.x264-SVA based on required words filter: [u'SUBSTANCE']
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [Danishbits] :: [0c0a735] Quality of Arrow.S07E02.HDTV.x264-SVA is SDTV
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [Danishbits] :: [0c0a735] Ignoring Arrow.S07E02.iNTERNAL.720p.WEB.h264-BAMBOOZLE based on required words filter: [u'SUBSTANCE']
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [Danishbits] :: [0c0a735] Quality of Arrow.S07E02.iNTERNAL.720p.WEB.h264-BAMBOOZLE is 720p WEB-DL
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [Danishbits] :: [0c0a735] Ignoring Arrow.S07E02.1080p.WEB.h264-TBS based on required words filter: [u'SUBSTANCE']
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [Danishbits] :: [0c0a735] Quality of Arrow.S07E02.1080p.WEB.h264-TBS is 1080p WEB-DL
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [Danishbits] :: [0c0a735] Ignoring Arrow.S07E02.720p.HDTV.x264-SVA based on required words filter: [u'SUBSTANCE']
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [Danishbits] :: [0c0a735] Quality of Arrow.S07E02.720p.HDTV.x264-SVA is 720p HDTV
2018-11-01 12:27:07 INFO     SEARCHQUEUE-FORCED-257655 :: [Danishbits] :: [0c0a735] Performing episode search for Arrow
```
</details>

**Additional context**
Dont have more details.

**Comment by medariox** [comment]
Enable debug logs and post a full manual search.

**Comment by Masterditto** [comment]
I did enable debug, but "logs" dont show anything debug related. Been trying to find solution online too. What should I do ?

Even tried restarted Medusa after enable and try do manual search. Still shows no debug even tho I see the checkmark for "enabled"

**Comment by medariox** [comment]
You need to select debug from the drop down in view logs.

**Comment by Masterditto** [comment]
Better picture here:
![debug2](https://user-images.githubusercontent.com/18222939/47851837-1b929380-ddda-11e8-8e9b-5f36c00649c2.png)

**Comment by p0psicles** [comment]
Copy the logs to gist.github.com. Past gist link here

**Comment by Masterditto** [comment]
https://gist.github.com/Masterditto/218b55c0bfb002c623c4eee6985eb067

**Comment by medariox** [comment]
Now do the same with a manual search.

**Comment by Masterditto** [comment]
https://gist.github.com/Masterditto/8a6de8873c5ad86f151fba3a28cf19b1

**Comment by medariox** [comment]
That's still not a manual search. A manual search starts with `SEARCHQUEUE-MANUAL-`.

**Comment by Masterditto** [comment]
Sorry! got it.. but clicking it returns nothing in DEBUG log other than pushing me to this website:
![debug4](https://user-images.githubusercontent.com/18222939/47856234-fce6c980-dde6-11e8-9ac3-08b20ed8a996.jpg)

**Comment by Masterditto** [comment]
Ok that made it appear in the list!
![debug5](https://user-images.githubusercontent.com/18222939/47857856-02461300-ddeb-11e8-94de-2f7d51c50564.jpg)

Log here:
https://gist.github.com/Masterditto/aba12b56c96f90cf8fd8f3c858466526

I have required word "Substance" becuz its the only sub group I wanna download from in this paticular TV show. Could I do this smarter somehow?

**Comment by p0psicles** [comment]
Ok then it will only download those.
It should have that picked up in a backlog search

**Comment by Masterditto** [comment]
It downloaded the Episode 02, but how can I tell it to look for these Substance? without me requiring to do a manual search everytime.

**Comment by sharkykh** [comment]
Didn't read the whole thread but results with `dk` subs are ignored by default. Try removing `dk` from the list of ignored subtitled results on the **Search Settings** config page.
Option is titled **Ignore language names in subbed results**

**Comment by Masterditto** [comment]
I already did a full clear there:
![search filters](https://user-images.githubusercontent.com/18222939/47859164-fb6ccf80-dded-11e8-984b-d8ed9037a8e3.png)

**Comment by Masterditto** [comment]
Just wonder why i does not pick these up automaticly. Really dont wanna do a "Force manual search" every episode :(

**Comment by Masterditto** [comment]
So I've now did what u asked. And surely enough a "Forced manuel search" does find Episode 2 here. Look at first picture, but why should I do a manual search on ALL episodes?
Going into episode 3 (2. picture below) I again have to do manuel search ?

This is most likely a bug or?

![2](https://user-images.githubusercontent.com/18222939/47953602-3a328f00-df80-11e8-88a5-63eb56ea0849.jpg)

![1](https://user-images.githubusercontent.com/18222939/47953605-3ef74300-df80-11e8-94de-4e9d337a367b.jpg)

Please help me fix this! Love Medusa over old SickRage!

**Comment by medariox** [comment]
You most likely only want releases with danish subs, right? In that case you should just add `DKsubs` to required words. Regarding the issue you seem to have, without a full debug log (talking about at least 24h from when the episode was released) it is really hard to help you further.

**Comment by Masterditto** [comment]
Hi medaiox

Been trying having no required word for the show "Arrow" and it does not find the releases from "Substance" automaticly. I have to do a "Force manual search" before it shows up in the list - Like I talked about earlier. Take a look here:

![arrow](https://user-images.githubusercontent.com/18222939/48354815-ebc57480-e692-11e8-8511-ca92df803810.jpg)

My debug log didn't go further than this in the web-interface:
https://gist.github.com/Masterditto/51b78727b75c096f4ad5d79f8217e7bf

"Danishbits" search provider does work, because its grabbing 90% of the content I also have MEDUSA search for.
Recently this was taken without any problems:
Kidding.S01E10.NORDiC.720p.WEB-DL.DDP5.1.H.264-DBRETAiL (2 hours ago - required word: DBRETAiL)
DCs.Legends.of.Tomorrow.S04E03.NORDiC.720p.WEB-DL.DD5.1.H.264-DBRETAiL (19 hours ago - required word: DBRETAiL)
The.Big.Bang.Theory.S12E08.Custom.DKsubs.720p.WEB-DL.x264-ENiGMA (2 days ago - required word: ENiGMA)

**Comment by jbaun** [comment]
I have the same problem with Medusa and Danishbits. Any news on a solution?

**Comment by p0psicles** [comment]
@Masterditto still an issue?
Normally these episodes should be found 1. through daily (rss) search and then 2. backlog search. We'll need debug logs for these. A `force manual search` is the same as a backlog search but for one specific episode. All results from a backlog search, should also be added to cache.

**Comment by Masterditto** [comment]
Yes im still doing "Force manual search" on many episodes. Waiting for u guys for a fix (I hope)

**Comment by p0psicles** [comment]
If your missing a result. Manual start a backlog search. And share the debug log.

**Comment by Masterditto** [comment]
"Force Manual Search" is not a backlog search? Can u tell me where that is?

**Comment by p0psicles** [comment]
Manage - manage searches
You can trigger a backlog search there.

**Comment by Masterditto** [comment]
Hi p0psicles - Had to wait for a release to test :) here is one with full information.

The.Last.Ship.S05E10.Custom.DKsubs.720p.WEB-DL.H.264-SUBSTANCE
Was released 14 days ago (I missed it) so changed backlog search to 30 days for this.

![thelastship1](https://user-images.githubusercontent.com/18222939/49337629-76f0b500-f616-11e8-8b11-675b1d490874.jpg)

![thelastship2](https://user-images.githubusercontent.com/18222939/49337630-7c4dff80-f616-11e8-89fb-48372e9a5a5b.jpg)

![thelastship3](https://user-images.githubusercontent.com/18222939/49337631-7fe18680-f616-11e8-9f3e-faa258179321.jpg)

And debug log file:
https://gist.github.com/Masterditto/072a2d331182bbcd7d33f693c5a57f15

AFTER CLICKING "FORCE SEARCH":
![thelastship3](https://user-images.githubusercontent.com/18222939/49337649-c800a900-f616-11e8-9675-d239ceb25053.jpg)

**Comment by p0psicles** [comment]
@pymedusa/developers the backlog search works like this:
1. Check cache for a specific show/episode
2. if it finds results, it is satisfied with that, and moves to the next wanted ep.
3. if it doesn't find results, it will search the provider.

Meaning that we're pretty much depending heavily on the RSS search. As that makes sure that "all" eps are added to cache.

The issue here is that *for some reason* the DKsubs releases are not added through the RSS search.
But other releases are added. Then the backlog only finds the releases that were added and doesn't bother searching further.

So there are two issues here:
1. RSS search doesn't pick up all releases
2. Backlog doesn't search the provider if it has >= 1 release in cache.

**Comment by p0psicles** [comment]
@Masterditto For the two issues 2 is really hard to do something about short term. But we can focus for now on why the specific release is not added through the RSS. But for that, you need to keep an eye on the logs for when an episode is released. You can filter your logs with `SEARCHQUEUE-DAILY-SEARCH`.

**Comment by p0psicles** [comment]
@Masterditto it could also help if I get temporary access. But that's up to you.

**Comment by p0psicles** [comment]
@Masterditto can you checkout this branch, and run some tests for us?
`feature/check-cache-for-candidates`

**Comment by p0psicles** [comment]
Can you get on irc?

**Comment by Masterditto** [comment]
Yeah, what channel?

**Comment by p0psicles** [comment]
freenode pymedusa

**Comment by p0psicles** [comment]
yes for example open: https://webchat.freenode.net/
And join #pymedusa

**Comment by Masterditto** [comment]
im in that now

**Comment by p0psicles** [comment]
As discussed with @Masterditto, he had min seeders configured to 1 for danishbits. New results in the RSS can start with 0 seeders, and then will not be added. Advised to set set min seeders to 0.

**Comment by Masterditto** [comment]
I could recommend Medusa to set it to 0 as default ? (IF this solves the issue) I promise to return if its working now :)

**Comment by jbaun** [comment]
Hi. Mine was also set to 1. I have now set it to 0 and will also test this.

**Comment by Masterditto** [comment]
So far one problem.

Z.Nation.S05E09.Custom.DKsubs.720p.WEB-DL.H.264-SUBSTANCE
Released 2 hours ago.

![z1](https://user-images.githubusercontent.com/18222939/49455087-d3a2ca00-f7e6-11e8-81f4-40e513779bdc.jpg)

Forcing backlog search didnt find it either. (I know it WILL find it if I again do a "Force manual search")

**Comment by p0psicles** [comment]
Plesase zip you Logs folder

**Comment by Masterditto** [comment]
Can you please go on IRC for a moment to write?

**Comment by Masterditto** [comment]
[application.zip](https://github.com/pymedusa/Medusa/files/2644863/application.zip)

here is log file

**Comment by p0psicles** [comment]
Ok

**Comment by Masterditto** [comment]
[Logs.zip](https://github.com/pymedusa/Medusa/files/2647671/Logs.zip)

Here is logs after this Supergirl episode :)

**Comment by Masterditto** [comment]
UPDATE:

This was not found. Full screenshots and log file after I ran manage searches "Backlog" and "Daily".
![flash](https://user-images.githubusercontent.com/18222939/49629048-be48be00-f9e7-11e8-9a95-c1854e668ee3.png)

![flash1](https://user-images.githubusercontent.com/18222939/49629051-c1dc4500-f9e7-11e8-956b-f2e50dc7951e.png)

![flash2](https://user-images.githubusercontent.com/18222939/49629056-c4d73580-f9e7-11e8-8772-35b6f297f5cf.png)

![flash3](https://user-images.githubusercontent.com/18222939/49629058-c86abc80-f9e7-11e8-8239-6d60db5afd32.png)

[Logs.zip](https://github.com/pymedusa/Medusa/files/2655942/Logs.zip)

**Comment by XenoBIT78** [comment]
If you need more logs let me know im facing the same problem..  :)

**Comment by p0psicles** [comment]
Danishbits has a really fast paced RSS. It has 20 items. And on times they move through them within 15 minutes. We have a minimum interval of 10 minutes. But there is a check that makes sure that individual providers are not polled more often then what they are configured for (individually). There is a small issue, where sometimes the last search was (for example) 9 minutes and 58 seconds ago. Then it skips that provider for that "turn". And 10 minutes later, the provider is allowed to pull new results. So although the provider is supposed to pull every 10 min. In that case there will be a gap of 19 minutes and 58 seconds. Which can result in missing a few eps.

I'll discuss with the other devs, if we can do something about this.

**Comment by p0psicles** [comment]
Example of the actual RSS pulls:
```
application.log.1:2018-12-06 19:39:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Danishbits] :: [54da0c7] GET URL: https://danishbits.org/couchpotato.php?search=.&latest=true&user=**********&passkey=********** [Status: 200]
application.log.1:2018-12-06 19:49:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Danishbits] :: [54da0c7] GET URL: https://danishbits.org/couchpotato.php?search=.&latest=true&user=**********&passkey=********** [Status: 200]
application.log.1:2018-12-06 19:59:34 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Danishbits] :: [54da0c7] GET URL: https://danishbits.org/couchpotato.php?search=.&latest=true&user=**********&passkey=********** [Status: 200]
application.log.1:2018-12-06 20:19:34 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Danishbits] :: [54da0c7] GET URL: https://danishbits.org/couchpotato.php?search=.&latest=true&user=**********&passkey=********** [Status: 200]
application.log.1:2018-12-06 20:39:34 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Danishbits] :: [54da0c7] GET URL: https://danishbits.org/couchpotato.php?search=.&latest=true&user=**********&passkey=********** [Status: 200]
application.log.1:2018-12-06 20:49:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Danishbits] :: [54da0c7] GET URL: https://danishbits.org/couchpotato.php?search=.&latest=true&user=**********&passkey=********** [Status: 200]
application.log.1:2018-12-06 21:09:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Danishbits] :: [54da0c7] GET URL: https://danishbits.org/couchpotato.php?search=.&latest=true&user=**********&passkey=********** [Status: 200]
application.log.1:2018-12-06 21:19:38 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Danishbits] :: [54da0c7] GET URL: https://danishbits.org/couchpotato.php?search=.&latest=true&user=**********&passkey=********** [Status: 200]
application.log.1:2018-12-06 21:39:41 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Danishbits] :: [54da0c7] GET URL: https://danishbits.org/couchpotato.php?search=.&latest=true&user=**********&passkey=********** [Status: 200]
application.log.1:2018-12-06 21:59:41 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Danishbits] :: [54da0c7] GET URL: https://danishbits.org/couchpotato.php?search=.&latest=true&user=**********&passkey=********** [Status: 200]
application.log.1:2018-12-06 22:19:42 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Danishbits] :: [54da0c7] GET URL: https://danishbits.org/couchpotato.php?search=.&latest=true&user=**********&passkey=********** [Status: 200]
```

**Comment by p0psicles** [comment]
You can see it often skips 20 minutes, where it should skip 10 now.

**Comment by p0psicles** [comment]
You can tell them, that if they extend the number of results, users can also extend the interval. Lowering the amount of hits on their api.

**Comment by Masterditto** [comment]
Ok, told them that too. And references them to this page to look themself :) Thx as always p0psicles and others for a great product!

**Comment by Masterditto** [comment]
p0p can u meet me on IRC for a moment?

**Comment by p0psicles** [comment]
I can now

**Comment by p0psicles** [comment]
Yeah i think that should solve it.
Also the change I'm making to daily search will also improve reliability.

**Comment by Masterditto** [comment]
Awesome p0p!

So far the first needed snatch has worked. I'll keep monitering and report back here for some time before we close the issue :)

**Comment by p0psicles** [comment]
Well we've made a number of nice improvements because of your help. So tnx for the help.

**Comment by XenoBIT78** [comment]
any special build for testing this fix ?

**Comment by p0psicles** [comment]
Develop branch already has two of the three improvements

**Comment by p0psicles** [comment]
Last one will be merged soon

**Comment by XenoBIT78** [comment]
Thanks..

Gr8 work :D it's much apreciated :)
