### ISSUE TITLE
Set unrar path

### ISSUE THREAD

**Issue by madtempest** [pymedusa/Medusa#5587]
Can we please have an option similar to SickChill where you can specify your unrar binary?

It appears that Medusa is using bsdtar on FreeBSD jails. I am basing this on observations from SickChill, where unless I specified the path to my unrar binary, SickChill was unable to unrar files successfully. When the path to the unrar binary is specified, it all works. I am seeing the same behaviour with Medusa.

Thanks!

**Comment by medariox** [comment]
Do you have `unrar` installed? It should work without having to set the path.

**Comment by madtempest** [comment]
I sure do.

root@jail: # which unrar
/usr/local/bin/unrar
root@jail: #

The behaviour of allowing Medusa to unrar is that I get errors in my warning log that rar'd files cannot be processed.

**Comment by medariox** [comment]
Please post the exact error you are getting.

**Comment by madtempest** [comment]
Packed files detected: [u'somefile.rar']
Unpacking archive: somefile.rar
Failed unpacking archive somefile.rar: error b'No suitable RAR unpacker installed'
Extracted content: []
Post-processing files: [u'somefile.r04', u'somefile.r03', u'somefile.r00', u'somefile.r02', u'somefile.nfo', u'somefile.rar', u'somefile.r05', u'somefile.r01', u'somefile.sfv']
Post-processing video files: []
Found unwanted files: [u'somefile.r04', u'somefile.r03', u'somefile.r00', u'somefile.r02', u'somefile.rar', u'somefile.r05', u'somefile.r01', u'somefile.sfv']
Successfully processed.
I did encounter some unprocessable items: 
somefile.rar: Unpacking failed: Unpacking failed for an unknown reason

That's a manual post-process.

The Warning log fills with:

WARNING  POSTPROCESSOR :: [0c0a735] somefile.rar: Unpacking failed: Unpacking failed for an unknown reason

As mentioned, using SickChill I would see this kind of error when it was trying to use bsdtar.

I've just enabled debug logging - I'll see what that yields.

**Comment by madtempest** [comment]
Oh, if this is necessary:
```
 echo $path
/sbin /bin /usr/sbin /usr/bin /usr/local/sbin /usr/local/bin /root/bin
```

**Comment by medariox** [comment]
That's your choice, I'm no one to judge.

The thing is, all that the `py-unrar2` does is calling `unrar` as you would do from console. So if it works from console, it should also work from within Medusa.

**Comment by madtempest** [comment]
Okay sure, thats what the documentation says it should do, but I'm not seeing that effect. As mentioned though in my Feature Request, when I can manually set the path it works.

**Comment by madtempest** [comment]
Sorry for the long delay.
I've recently rebuilt the jail that I host medusa in.
I'm getting "Error: 'No suitable RAR unpacker installed'" throughout my logs however when I check the jail for a suitable unrar:

```
# pkg install unrar
Updating FreeBSD repository catalogue...
[cassandra] Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
[cassandra] Fetching packagesite.txz: 100%    6 MiB 845.8kB/s    00:08
Processing entries: 100%
FreeBSD repository update completed. 32579 packages processed.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent version of packages are already installed
```

So I am not sure what is going on here. I am also using the latest Medusa install.

**Comment by madtempest** [comment]
Hi. This is still ongoing and I was wondering what other information you need from me? 

FreeBSD 11.2-STABLE #0 r325575+fc3d65faae6(HEAD): Thu Dec 20 16:12:30 EST 2018     root@nemesis.tn.ixsystems.com:/freenas-releng-final/freenas/_BE/objs/freenas-releng-final/freenas/_BE/os/sys/FreeNAS.amd64

Python 2.7.16

UNRAR 5.71 (iconv) freeware      Copyright (c) 1993-2019 Alexander Roshal

Date Time WARNING  POSTPROCESSOR :: [6a21a60] something.rar: Unpacking failed: Unpacking failed for an unknown reason

Date Time WARNING  POSTPROCESSOR :: [6a21a60] Failed unpacking archive something.rar: Error: 'No suitable RAR unpacker installed'

**Comment by medariox** [comment]
Should be fixed.
