### ISSUE TITLE
Medusa doesn't use existing folder

### ISSUE THREAD

**Issue by shaavik** [pymedusa/Medusa#5589]
**Describe the bug**
All my series are named like : XXX (YYYY)
with XXX is the show name and YYYY the year of the show.
Since 2.11, Medusa create folder XXX for all my shows.

**To Reproduce**
1. Create a directory with show XXX (YYYY)
2. Click on 'Add existing shows'
3. Scroll back to shows location
4. See a new folder beeing creating : XXX

**Expected behavior**
The show folder should remains the one which exists on the show folders.

**Medusa (please complete the following information):**
 - OS: [Windows 10]
 - Branch: [master]
 - Commit: [0c0a73583452f988c518adeafa75ee1f17987bdf ]

**Logs:**

**Additional context**

**Comment by shaavik** [comment]
There is a problem too with accent
Serie name : La Trêve
Keep creating : La Treve

**Comment by p0psicles** [comment]
Can you try develop branch?

**Comment by shaavik** [comment]
I tried develop branch, and it's working. I tried with accent and with year in show name.

**Comment by p0psicles** [comment]
Okay, im closing this. As its fixed in develop

**Comment by p0psicles** [comment]
Okay, im closing this. As its fixed in develop
