### ISSUE TITLE
Prefer non-rar/non-archived torrents

### ISSUE THREAD

**Issue by Xanobia** [pymedusa/Medusa#5590]
Is there a way to prefer torrent where the files aren't archived (with rar or similar)

And also can this information be shown when doing manual search - perhaps a files view button or smoething?

As i prefer to share non archived torrent (having plex hardlinking files) i prefer torrent to have the mkv or whatever format over rar or similar torrents - to preserve storage space needed

**Comment by medariox** [comment]
This is not possible. We can't know the content of the files beforehand.
