### ISSUE TITLE
Search Settings dont save

### ISSUE THREAD

**Issue by LaBoss** [pymedusa/Medusa#5642]
**Describe the bug**
I'm here with a problem in Search Settings when I select Synology DS and save, everything works correctly until you restart the server or medusa. After restart the setting is reverted to Black Hole

In my config.ini the **torrent_method**  key is

torrent_method = downloadstation

even after rebooting

**To Reproduce**
1. Go to 'Search Settings'
2. Select 'Synology DS'
3. Save
4. Restart Medusa
5. Go to 'Search Settings'
6. Demo https://streamable.com/tgql1

**Expected behavior**
Search provider save

**Medusa (please complete the following information):**
 - OS: Linux-3.10.102-x86_64-with-glibc2.2.5 (SynologyOS)
 - Branch: master 
 - Commit: master

**Comment by p0psicles** [comment]
So its still changed after a page reload? But not app restart?

**Comment by LaBoss** [comment]
> So its still changed after a page reload? But not app restart?

Yes, only after restarting, it happens

**Comment by p0psicles** [comment]
Just confirmed it.
Thing is i'm already changing the code for the config - search page. And I think it's already fixed there.
https://github.com/pymedusa/Medusa/pull/5553

**Comment by LaBoss** [comment]
Ok thanks...

I'll wait for release

Thks

**Comment by p0psicles** [comment]
Ill make sure in my branch

**Comment by LaBoss** [comment]
Hello, update today and continue with the same problem, now the button to test a connection also does not work

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5761
