### ISSUE TITLE
Auto post-process not working

### ISSUE THREAD

**Issue by leo-123** [pymedusa/Medusa#5645]
**Describe the bug**
Auto postproccessor not working.

**To Reproduce**
Turn it on and wait...

**Expected behavior**
Should extract relevant downloads in frequency time.

**Screenshots**
![medusa_scheduler](https://user-images.githubusercontent.com/35333745/48013195-73a7fd80-e12c-11e8-9695-6fa784b7b38b.PNG)

**Medusa (please complete the following information):**
Medusa Info:	Branch: master 
Commit: 0c0a73583452f988c518adeafa75ee1f17987bdf 
Version: v0.2.11 
Database: 44.12
Python Version:	2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version:	OpenSSL 1.0.2j 26 Sep 2016
OS:	Windows-10-10.0.17134
Locale:	en_US.cp1252

**Logs:**
No relevant logs

**Additional context**
If I run the pot-process manually - it finishes successfuly.
If I restart the server, the Server status is displaying correctly the counter - 10 mins to post-proccess, but after those 10 minutes - the counter just keeps counting down (see attached screenshot) and nothing gets extracted, my downloads are still in snatched state.

**Comment by leo-123** [comment]
BTW this is a new installation. Had sickrage before, unsinstalled that, did a clean install of Medusa and imported all the folders manually, so this feature never worked before.

**Comment by medariox** [comment]
I would suggest you try with a new `config.ini` instead of importing the one from Sick*.

**Comment by leo-123** [comment]
Hi @medariox, This is a fresh install - nothing was imported from SickRage.

**Comment by p0psicles** [comment]
In the screenshot the post process thead is running. Maybe its blocked on something? Can you enable debug logs, restart, and wait for the pp to start.

**Comment by Tearow** [comment]
After turning it on do a restart of medusa it will work afterwards.

**Comment by leo-123** [comment]
So Here's what I did to solve it.
The debug logs were already turned on, there were no interesting errors there, but it does look like it got stuck on a loop with an irrelevant files and simply didn't do anything after that.
The download folder is shared for all downloads, so I assumed its confusing Medusa somehow and configured Medusa to add a "Medusa" label, and the uTorrent client to move each download to its relevant label, so now all Medusa downloads are in a dedicated folder. Configured that folder for the post-process, rebooted the server and it's working as expected now.
Thanks for the help.
