### ISSUE TITLE
Ignored words need to be changeable/setable on a show level

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#5648]
**Is your feature request related to a problem? Please describe.**
you cannot override "global" ignored words. when for 99% of the shows you don't want "language" in the title, but just for one you want to allow it you must add "language" to all 99% of the shows.

**Describe the solution you'd like**
When no ignored words are set at the show level use the global ones, otherwise the shows.

**Describe alternatives you've considered**
editing 99% of shows :-( which _really_ is a lot

**Comment by billotronic** [comment]
To add to this it would be also handy to be able to set Require at a show level too. Say for getting the Uncensored versions of a show or maybe a different resolution etc.

**Comment by p0psicles** [comment]
Ok I'll check this out

**Comment by p0psicles** [comment]
It's not that easy to change the behavior. As that will change how it now works for allot of users.

**Comment by udochrist** [comment]
Depends on the approach chosen to implement that. If you keep a delta list on the show level it should not change anything to current users.

**Comment by medariox** [comment]
Added.
