### ISSUE TITLE
Force Show Update Cycle

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#5655]
Hi Team

For some strange Reason Medusa and Docker i am having issues where it is not updating the shows or when it does it hangs.

Is there a command i can run to force the cycle as from what i have seen i have missed out on 2 weeks on some shows.

Thanks

**Comment by HPMSGEN8** [comment]
Anyone know the command i can run please ?

**Comment by p0psicles** [comment]
You can open crome dev tools and look at network tab, when you click the button

**Comment by HPMSGEN8** [comment]
So there is nothing i can run via SSH for this at all then

**Comment by p0psicles** [comment]
You can use curl and send the web command

**Comment by HPMSGEN8** [comment]
Thanks i have no clue where to start.  Do you have a command i can run please ? 

I do not know why this is still getting locked now and then on Docker. The rights are ok everything is ok just that this hangs for some strange reason.

**Comment by HPMSGEN8** [comment]
No Longer Required
