### ISSUE TITLE
Medusa Show Update (Re-Scan) Issue

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#5662]
Hi Team

I have just moved Medusa from Docker and i had to change the Show Locations. This has broken the show status of what i had set them to.

So Medusa has re-scanned and decided to set it what it thinks and this is 100% wrong. Is there anyway i can fix this as i do not feel like going over each one to fix this.

Thanks in Advanced

**Comment by p0psicles** [comment]
Is the root dir correct in medusa?
Are rights correct set on root dir?
Then try mass update.

**Comment by HPMSGEN8** [comment]
@p0psicles Yes this is correct. The issue is that it is not holding the status that i set this to.

**Comment by medariox** [comment]
You need to set the quality in the file name, there is no other way if you think the quality Medusa detected is incorrect.

**Comment by HPMSGEN8** [comment]
@medariox That is updating tons of files. 

If a user sets it to what they want in Medusa then it should never update unless it changes from SD to HD or something like that

Now i have to make tons or changes due to this bug

**Comment by HPMSGEN8** [comment]
OR how can i take 1 Medusa DB and move it to another instance. The only issue is the Volume Names where the shows are is different. Do you have an Easy fix for this at all.

**Comment by medariox** [comment]
You can edit the paths with SQLite Browser if you know what you are doing: https://sqlitebrowser.org/

**Comment by HPMSGEN8** [comment]
Thanks is there any way to set the status as i asked above at all.

**Comment by p0psicles** [comment]
Sorry i have truly no idea what the issue is.
Can you try to explain in more detail. Use some screenshots?

**Comment by HPMSGEN8** [comment]
The issue is that i backed up my setup from Docker. Then i installed it on a new NAS.

Then i had to change all the Locations from XYZ to ABC. This started a Mass Update as it should.

The issue then started when it started the Re-Scan on the Files it changed what i had setup to what it thought.

My Question is that if a user sets the Quality of a Show / File to SDTV or 720p WEB-DL etc... it will not overwrite based on an Force Update / Re-Scan, etc...

It should only update if it changes from SDTV to 720 or SD-DVD etc.... with a new version.

Is this possible to do ?

**Comment by HPMSGEN8** [comment]
@p0psicles Any luck on this at all plz. As i am having major issues on Docker and need to get this migrated correctly.
