### ISSUE TITLE
Proccessing failed: This show isn't in your list, you need to add it before post-processing an episode

### ISSUE THREAD

**Issue by Miicker** [pymedusa/Medusa#5667]
I run Medusa on Synology (in a Docker container).
Here some info:

Branch: master
Commit: 0c0a73583452f988c518adeafa75ee1f17987bdf
Version: v0.2.11
Database: 44.12
Python Version:  2.7.13

So for one show on my list processing stopped working. Medusa downloads the episode just fine, but then gives the error as shown in the title. I already tried to remove the show and add it again, but that didn't fix the problem. I searched for this issue, but only found old threats. Cay you please support me with this issue?

Also when I reboot my NAS, or restart Medusa, it gives some errors (which I think are not related), but might be good to mention. I've submitted these errors: https://github.com/pymedusa/Medusa/issues/5658

Thanks in advance!

**Comment by labrys** [comment]
You probably need to add a scene exception for the affected show.

For example if you have the show `Law And Order: Special Victims Unit' and it downloads files named 'Law Order SVU - S01E02.mkv'.  It doesn't know that `Law Order SVU` is the same show.  After adding `Law Order SVU` as a scene exception it will properly post-process the file.

**Comment by Miicker** [comment]
Thanks this approach did indeed solve it!
