### ISSUE TITLE
Manual Post-Processing nor Post-Processing Will Start

### ISSUE THREAD

**Issue by Kdabe** [pymedusa/Medusa#5668]
I am unable to get either forms of Post-Processing to trigger, and I am getting no errors or messages of any kind when attempting to do so. When I check the Server Status page, the timer for Post-Processing goes into the negatives, without any indication that its running. I tried updating to the current version, but it changed nothing. I am debating just starting from scratch with a new download of medusa, but I was wondering if there might be any other suggestions for what could be wrong.

**Comment by p0psicles** [comment]
Configure automatic postprocessing. Enable debug logging. Now restart medusa and wait for it to start. Post the debug log.

**Comment by Kdabe** [comment]
I walked away and came back, and it started about 20 minutes after initially being triggered, so something must have been holding it up. I don't want to mess with it now that its running, but once it completes I will download another show and see if the situation repeats itself, then post a log if I need to. If I don't need to post a log, I will still update you on the situation by the end of the day.

**Comment by medariox** [comment]
Closing as solved, please your reply if it happens again.
