### ISSUE TITLE
[APP SUBMITTED]: 331753: Multiple entries found in show: Black Clover 

### ISSUE THREAD

**Issue by pct00** [pymedusa/Medusa#5675]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/d434797421435f21229a028b02fd5ebd
### ERROR
<pre>
2018-11-07 19:06:42 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Nyaa] :: [0c0a735] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Aethrios** [comment]
### INFO
**Python Version**: `2.7.15 (default, May 26 2018, 01:11:09) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-01-27 14:00:37 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [AniDex] :: [918cfe7] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Aethrios** [comment]
### INFO
**Python Version**: `2.7.15 (default, May 26 2018, 01:11:09) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-01-27 10:51:37 ERROR    SEARCHQUEUE-BACKLOG-331753 :: [ShanaProject] :: [918cfe7] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Aethrios** [comment]
### INFO
**Python Version**: `2.7.15 (default, May 26 2018, 01:11:09) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-01-26 10:41:45 ERROR    SEARCHQUEUE-BACKLOG-331753 :: [TokyoToshokan] :: [918cfe7] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Aethrios** [comment]
### INFO
**Python Version**: `2.7.15 (default, May 26 2018, 01:11:09) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-01-24 15:34:05 ERROR    FINDPROPERS :: [918cfe7] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by thesugarat** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/5e4306e1cd7a798e83bb94ca9d009ba6
### ERROR
<pre>
2019-04-28 03:02:39 ERROR    SEARCHQUEUE-BACKLOG-331753 :: [NZBFinder.ws] :: [f46bfac] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Aethrios** [comment]
### INFO
**Python Version**: `2.7.15 (default, May 26 2018, 01:11:09) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/967963359ee5f0deb68190cfb1dac821
### ERROR
<pre>
2019-05-08 09:23:46 ERROR    SEARCHQUEUE-BACKLOG-331753 :: [TokyoToshokan] :: [f46bfac] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Aethrios** [comment]
### INFO
**Python Version**: `2.7.15 (default, May 26 2018, 01:11:09) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/b8382f73c72ca3b2ab69e8dd8a81bb24
### ERROR
<pre>
2019-05-08 09:21:50 ERROR    SEARCHQUEUE-BACKLOG-331753 :: [AniDex] :: [f46bfac] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Aethrios** [comment]
### INFO
**Python Version**: `2.7.15 (default, May 26 2018, 01:11:09) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/5d560c190c05fee4ef59af7b6c8ae6c0
### ERROR
<pre>
2019-05-08 09:17:51 ERROR    SEARCHQUEUE-BACKLOG-331753 :: [ShanaProject] :: [f46bfac] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by thesugarat** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-10-17 10:19:53 ERROR    SEARCHQUEUE-BACKLOG-331753 :: [NZBGeek] :: [baad1e5] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by thesugarat** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-10-17 10:19:43 ERROR    SEARCHQUEUE-BACKLOG-331753 :: [NZBFinder.ws] :: [baad1e5] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by cyan** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 26 2018, 05:58:52) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/c91564d740482363f67e5953979db974
### ERROR
<pre>
2019-10-29 06:10:51 ERROR    SEARCHQUEUE-BACKLOG-331753 :: [Nyaa] :: [baad1e5] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by thesugarat** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-11-02 07:00:57 ERROR    SEARCHQUEUE-BACKLOG-331753 :: [NZBGeek] :: [baad1e5] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by thesugarat** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-11-02 07:00:43 ERROR    SEARCHQUEUE-BACKLOG-331753 :: [NZBFinder.ws] :: [baad1e5] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
