### ISSUE TITLE
[APP SUBMITTED]: 331753: Multiple entries found in show: Black Clover 

### ISSUE THREAD

**Issue by pct00** [pymedusa/Medusa#5676]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/1f03081e894f2de7a23ea4574639cf0b
### ERROR
<pre>
2018-11-07 02:50:50 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] 331753: Multiple entries found in show: Black Clover 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Its because someone added a season 2 on tvdb. Those episodes need to be removed from your db

**Comment by p0psicles** [comment]
Only solution for now, readd show
