### ISSUE TITLE
Medusa unable to find anime

### ISSUE THREAD

**Issue by wfulcher** [pymedusa/Medusa#5693]
Branch/Commit: Master/0c0a73583452f988c518adeafa75ee1f17987bdf
OS:DSM 6.2.1 (though running in Docker Image pymedusa/medusa:Latest)
What I did: Tried finding an anime. The anime is toggled as anime, HorribleSubs is whitelisted. I have tried with Scene numbering on and off. I have also tried searching with anime toggled off with similar results. 

What happend: Gui said no results found.
What you expected: Results to be found. I can go on horriblesubs, nyaa, and shanaproject and search the name and it brings back results. 

Logs:
2018-11-11 15:58:22 INFO     SEARCHQUEUE-MANUAL-38782 :: [0c0a735] Unable to find manual results for: Zombieland Saga - 000 - Good Morning SAGA
2018-11-11 15:58:13 INFO     SEARCHQUEUE-MANUAL-38782 :: [ShanaProject] :: [0c0a735] Performing episode search for Zombieland Saga
2018-11-11 15:58:07 INFO     SEARCHQUEUE-MANUAL-38782 :: [Rarbg] :: [0c0a735] Performing episode search for Zombieland Saga
2018-11-11 15:58:07 INFO     SEARCHQUEUE-MANUAL-38782 :: [IPTorrents] :: [0c0a735] Performing season pack search for Zombieland Saga
2018-11-11 15:58:06 INFO     SEARCHQUEUE-MANUAL-38782 :: [IPTorrents] :: [0c0a735] Performing episode search for Zombieland Saga
2018-11-11 15:58:06 INFO     SEARCHQUEUE-MANUAL-38782 :: [HorribleSubs] :: [0c0a735] Performing season pack search for Zombieland Saga
2018-11-11 15:58:06 INFO     SEARCHQUEUE-MANUAL-38782 :: [HorribleSubs] :: [0c0a735] Performing episode search for Zombieland Saga
2018-11-11 15:58:06 INFO     SEARCHQUEUE-MANUAL-38782 :: [Nyaa] :: [0c0a735] Performing season pack search for Zombieland Saga
2018-11-11 15:58:05 INFO     SEARCHQUEUE-MANUAL-38782 :: [Nyaa] :: [0c0a735] Performing episode search for Zombieland Saga
2018-11-11 15:58:05 INFO     SEARCHQUEUE-MANUAL-38782 :: [0c0a735] Using manual search providers
2018-11-11 15:58:05 INFO     SEARCHQUEUE-MANUAL-38782 :: [0c0a735] Building internal name cache for Zombieland Saga
2018-11-11 15:58:05 INFO     SEARCHQUEUE-MANUAL-38782 :: [0c0a735] Finished processing 2936 scene exceptions.
2018-11-11 15:58:05 INFO     SEARCHQUEUE-MANUAL-38782 :: [0c0a735] Updating exception_cache and exception_season_cache
2018-11-11 15:58:05 INFO     SEARCHQUEUE-MANUAL-38782 :: [0c0a735] Beginning manual search for: Zombieland Saga - 000 - Good Morning SAGA

**Comment by p0psicles** [comment]
Enable debug logging.
Use gist.github.com to post logs

**Comment by p0psicles** [comment]
Also run manage - searches, force xem exceptions

**Comment by wfulcher** [comment]
https://gist.github.com/wfulcher/296490f99ca40aa925bfebe131357b3e#file-gistfile1-txt

**Comment by wfulcher** [comment]
Or do you want the complete log file. I just put in the part where I forced the exceptions and then ran a manual search

**Comment by p0psicles** [comment]
Thats fine

**Comment by p0psicles** [comment]
Can you force update the show?

**Comment by wfulcher** [comment]
https://gist.github.com/wfulcher/7cd697be4f6e4ef411899b772d5243a8#file-gistfile1-txt

**Comment by wfulcher** [comment]
Ran a forced update, then updated the Exceptions, then ran a manual search. No results returned.

**Comment by p0psicles** [comment]
Go to config - general, look up logging and set to debug. Then restart and repeat.

**Comment by p0psicles** [comment]
Well i suspect your tvepisode table is not updated with the absolute numbers. I think its also solved when you remove/add the show and nake sure you enable anime and scene numbering when adding. But would still like to see full debug logs. So from startup, full update show and manual search.

**Comment by wfulcher** [comment]
I am able to fix them, but it still doesnt see any results after fixing. Again at this point Im just going to use an RSS feed. The program otherwise works with "Normal" shows. Just anime isnt working. Thank you for your help!

**Comment by p0psicles** [comment]
All anime are working fine for me and allot of other users. If there is a bug here, id like to resolve it, to help other users who go through the same

**Comment by wfulcher** [comment]
It does seem to be hit and miss now. I added another show, didnt whitelist any groups and it pulled down. I then tried to replicate it and added another show and it didnt work.

**Comment by wfulcher** [comment]
https://gist.github.com/wfulcher/c1b42aee4c167e56fb185a520f470efb#file-gistfile1-txt

**Comment by wfulcher** [comment]
After jiggling the handle a bit it does seem to find some of that show. But only if I do the automated search. If I try to manually search it still says no results.

**Comment by wfulcher** [comment]
Ive also found, if I dont add anything to the white list and only add to the black list, it seems to increase the odds of success. So by just leaving the groups I want in the "release groups" section it ups the odds in favor of finding.

**Comment by p0psicles** [comment]
In the logs i see a forced search. But if you do a manual search you will see the results. Also if a forced or backlog seach would have not picked them.

**Comment by wfulcher** [comment]
I havent done any forced searches. I just click the little icon on the show episode next to the one that auto picks.

**Comment by p0psicles** [comment]
Hmm its still searching for 00 episode. Ill add the zombieland show, try to replicate. Can you make. Screenshot of your show options? The header on the displayShow should give enough info.

**Comment by p0psicles** [comment]
Did you use tmdb to add the show?

**Comment by wfulcher** [comment]
TVmaze

**Comment by wfulcher** [comment]
![config 1](https://user-images.githubusercontent.com/8878898/48318900-68415000-e5cc-11e8-8d07-009130a1d6b8.PNG)
![config 2](https://user-images.githubusercontent.com/8878898/48318901-68d9e680-e5cc-11e8-9193-26d90b75a9d9.PNG)
![config 3](https://user-images.githubusercontent.com/8878898/48318902-68d9e680-e5cc-11e8-9014-b028ce1a8e37.PNG)

**Comment by wfulcher** [comment]
As you can see in the 2nd picture it shows the whitelist as horriblesubs spelled vertically. I have changed this multiple times and it seems to keep reverting.

**Comment by wfulcher** [comment]
![yuuna 1](https://user-images.githubusercontent.com/8878898/48318925-c3734280-e5cc-11e8-84dd-07f8216fc7af.PNG)
![yuuna 2](https://user-images.githubusercontent.com/8878898/48318926-c3734280-e5cc-11e8-9932-0e555ee0d1c3.PNG)
![yuuna 3](https://user-images.githubusercontent.com/8878898/48318927-c3734280-e5cc-11e8-98b6-e6ec8bc77378.PNG)


This one worked, but only if I put everything I didnt want in the black list.

**Comment by p0psicles** [comment]
I think best is to add the show on tvdb. And then add it from tvdb in medusa.

**Comment by wfulcher** [comment]
![slime 1](https://user-images.githubusercontent.com/8878898/48318952-f9b0c200-e5cc-11e8-9dc4-3723146824a0.PNG)
![slime 2](https://user-images.githubusercontent.com/8878898/48318953-f9b0c200-e5cc-11e8-866c-02cfe021c4a7.PNG)
![slime 3](https://user-images.githubusercontent.com/8878898/48318954-f9b0c200-e5cc-11e8-81ba-f49bc259e2de.PNG)


This one the Whitelist function appears to be working as expected. I didnt have to use the black list or manually search.

**Comment by p0psicles** [comment]
Ill check out the release groups.

**Comment by wfulcher** [comment]
![gridman](https://user-images.githubusercontent.com/8878898/48318978-5f9d4980-e5cd-11e8-8d9e-3c4f2fe6ff31.PNG)
![gridman 2](https://user-images.githubusercontent.com/8878898/48318980-60ce7680-e5cd-11e8-954a-8b5d211a548f.PNG)
![gridman 3](https://user-images.githubusercontent.com/8878898/48318981-61ffa380-e5cd-11e8-9fa1-10c4102df17c.PNG)


And then this one does not work as well. Ive tried all of the same methods above that worked with no success.

**Comment by p0psicles** [comment]
Okay good. Remove and add through tvdb using 'zombie land saga', enable anime disable scene numbering, that should fix most of the issues

**Comment by wfulcher** [comment]
Looks like its working now. I apologize for the headache I caused. I didnt see anything about using tvdb when searching for anime. 

Thank you for all of your help sir/ma'am!

**Comment by p0psicles** [comment]
Yeah, its not well documented. Well add some warnings whem selecting tvmaze/tmdb with anime.

Also changing the release groups seems really broken. Ill dive into that.
