### ISSUE TITLE
qBittorrent set download location 

### ISSUE THREAD

**Issue by SuperKingZ** [pymedusa/Medusa#5695]
**Is your feature request related to a problem? Please describe.**
The save path is not implemented in qBittorrent. I'm busy transferring from deluge to qBittorrent and its one of the features that I miss.

**Describe the solution you'd like**
Add a "_set_torrent_path" function to the "qbittorrent_client.py" file.  I'm not a programmer but after looking at the qBittorrent web ui API and deluge implementation I think the function should look something like this.
```python
    def _set_torrent_path(self, result):
        if app.TORRENT_PATH:
            self.url = '{host}command/setLocation'.format(host=self.host)
            data = {
                'hashes': result.hash.lower(),
                'location' : app.TORRENT_PATH
            }
            return self._request(method='post', data=data, cookies=self.session.cookies)
        return True
```
After that enable save path in "config_search.mako" for qBittorrent

**Comment by sharkykh** [comment]
I use the labels in qBittorrent, it's much easier to manage. Create a label for the TV downloads and set the save path you want for them, then on Medusa set the same label on qBitorrent's client settings.
I've been using this method successfully for months now.

**Comment by SuperKingZ** [comment]
I was using qBittorrent without the GUI and the "Default Torrent Management Mode" is not available in the web options.  After enabling automatic download management in the qBittorrent.conf file everything is working and the torrents are now downloading to the correct location per category.

Thank you @sharkykh for your help!

```
[BitTorrent]
Session\DisableAutoTMMByDefault=false
Session\DisableAutoTMMTriggers\CategoryChanged=false
Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false
```
