### ISSUE TITLE
no adding shows either new or old

### ISSUE THREAD

**Issue by kevwiener** [pymedusa/Medusa#5697]
**Describe the bug**
Every time i add a show it tells me that is has added it and it shows as loading on the first refresh of the home page, but then it disappears and the show is not in my list, this is both for new and exisiting shows. 

**To Reproduce**
1. Go to add show
2. Click on the show title box and search
3. select show and then follow the options to add
4. show seems to be added but then nothing there in the list

**Expected behavior**
to add a new or existing show

**Medusa (please complete the following information):**
 - OS: Windows server 2012 R2
 - Branch: Master
 - Commit:0c0a73583452f988c518adeafa75ee1f17987bdf 

**Logs:**
[application.log](https://github.com/pymedusa/Medusa/files/2571504/application.log)

```
<-- Please replace this whole line with your logs -->
```
</details>

**Additional context**

**Comment by medariox** [comment]
You need to add a show and post the related DEBUG logs. Which browser are you using?

**Comment by kevwiener** [comment]
i have enabled debug log but not sure where it saves it too ?? i am running google chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by kevwiener** [comment]
i think i know what the problem is https://pastebin.com/t2eS49Bb but im not sure how to fix it haha its telling me it cant access the DB :( this is a new install too so not sure why

**Comment by medariox** [comment]
If it's not a permissions/rights issue (make sure the user running Medusa is able to read and write the file), it could be a hardware issue (HDD switching to read only mode for example). I'm afraid you'll need to figure that out yourself unfortunately.
