### ISSUE TITLE
Cannot find torrent on Nyaa.si - "Scene name" does not work?

### ISSUE THREAD

**Issue by Masterditto** [pymedusa/Medusa#5699]
**Describe the bug**
Added the Anime "That Time I Got Reincarnated as a Slime" in Medusa, and set "Required Word" to be Horriblesubs (works for other animes)
The show is called "Tensei Shitara Slime Datta Ken" on nyaa.si:
https://nyaa.si/?f=0&c=1_2&q=Tensei+Shitara+Slime+horrible+720
So I've added a "Scene name" as "Tensei Shitara Slime Datta Ken" but it does not find the episode, not even on "Force manual search"

**To Reproduce**
1. Setup Medusa for the Anime show "That Time I Got Reincarnated as a Slime"
2. Set scene name to "Tensei Shitara Slime Datta Ken" since thats it name on nyaa.si
3. Search the episode
4. See error?

**Expected behavior**
To find the torrent.

**Screenshots**
![nyaa](https://user-images.githubusercontent.com/18222939/48363801-128da600-e6a7-11e8-8113-c2b1bcbca816.jpg)
![medusa](https://user-images.githubusercontent.com/18222939/48363811-18838700-e6a7-11e8-8e89-0fc122772030.jpg)

**Medusa (please complete the following information):**
 - OS: Synology Linux
 - Branch: master
 - Commit: ?

**Logs:**
https://gist.github.com/Masterditto/971621bcbd10359f3c4b6756e0b836ad

```
<-- Please replace this whole line with your logs -->
```
</details>

**Additional context**

Expect the "Scene name" search to be broken?? seems like it does not search on that scene name I told it to. I may be wrong :)
Hope anyone can help.
Let me know if u need more details.

**Comment by p0psicles** [comment]
Add sing tvdb, not tmdb

**Comment by Masterditto** [comment]
![123](https://user-images.githubusercontent.com/18222939/48365306-dbb98f00-e6aa-11e8-98dc-62bbc06cdfae.jpg)

This ?

**Comment by medariox** [comment]
Yes.

**Comment by Masterditto** [comment]
Weird, pretty sure I already did that. Anyways.. Readded it and now it works. I got problems with another anime though - Should I add new issue or can we do it in this too ?
REALLY appreciate your help thx !

**Comment by p0psicles** [comment]
You can use this

**Comment by Masterditto** [comment]
Ok seems like it has been fixed.. Anime was called "Baki (2018)". It all works now. u can close this issue! thx alot for ur help!!
Hope one day we can fix this other issue of mine:
https://github.com/pymedusa/Medusa/issues/5582
