### ISSUE TITLE
[FEATURE REQUEST] Auto-update log page

### ISSUE THREAD

**Issue by Jabouty** [pymedusa/Medusa#5711]
**Is your feature request related to a problem? Please describe.**
No problems.

**Describe the solution you'd like**
Currently on the view log page (../errorlogs/viewlog/), the page and log lines are static and require a refresh to watch the logs.  As a transplant user from SickRage, I'm used to seeing the log-lines populate the top of the page as it's written to the log file, without having to manually refresh the page.  I believe having the log lines populate automatically without having to refresh the page would be a great help for everyone, especially when we're trying to watch for a specific info line to come up.

**Comment by medariox** [comment]
Added.
