### ISSUE TITLE
Add Release group column to show page

### ISSUE THREAD

**Issue by Kilay** [pymedusa/Medusa#5715]
Is it possible to add a new "Release Group" column to show page (page where all show episodes are listed) ?
It could be useful for user downloading subtitle in order to know which group was downloaded (without going to history page) and choose the right subtitle.

**Comment by p0psicles** [comment]
I have really no idea what your request is

**Comment by OmgImAlexis** [comment]
@p0psicles looks like they want the release group added to the episode row in `displayShow`.

**Comment by OmgImAlexis** [comment]
@Kilay not sure if you know but we do have automated downloading of subtitles already built into Medusa so you shouldn't need to manually grab them.

**Comment by Kilay** [comment]
You are right @OmgImAlexis, this is my request.
And yes, I know there is automated downloading. But for french language, fastest translation are usually from addic7ed site where there is no release group in subtitle name. So it pick wrong subtitle 80% of time.
Then, I have to manually search and download correct subtitle.

**Comment by p0psicles** [comment]
@Kilay we also have a manual select for the found subtitles right? You mean that? Or you navigate to the website yourself?

**Comment by Kilay** [comment]
@p0psicles I manually search and download  from Medusa

**Comment by p0psicles** [comment]
Yes the episodes, but also the subtitles?

**Comment by p0psicles** [comment]
Update #282

**Comment by medariox** [comment]
It's kind of already there if you hover over the episode number or if you select to show the file name column. Really low prio IMO.

![img](https://snapr.pw/i/a8a1a02ce4.png)

**Comment by Kilay** [comment]
If you don't rename file in post processing, this is true. But in my case, file are renamed using this pattern : "Saison 2/Show Name - S02E03 - Ep Name.ext".
But I agree with you, this is low priority as I have a workaround (by opening history page).
