### ISSUE TITLE
Medusa still try to DL torrent at yggtorrent.is url

### ISSUE THREAD

**Issue by Ameshas** [pymedusa/Medusa#5716]
Hi, 
Medusa refuse to DL torrent. The app still want to dl the torrent at the .is domain of yggtorrent

> 2018-11-14 23:57:07 INFO     SEARCHQUEUE-DAILY-SEARCH :: [0c0a735] Downloading Supernatural.S14E04.VOSTFR.720p.HDTV.x264-GOLD from Yggtorrent at https://ww2.yggtorrent.is/engine/download_torrent?id=341012
2018-11-14 23:57:07 INFO     SEARCHQUEUE-DAILY-SEARCH :: [0c0a735] Downloading Supernatural.S14E04.VOSTFR.720p.HDTV.x264-GOLD with 145 seeders and 10 leechers and size 939.45 MB from Yggtorrent

But adress is corrent on the yggtorrent.PY file : 

>         # URLs
        self.url = 'https://www.yggtorrent.to'
        self.urls = {
            'auth': urljoin(self.url, 'user/ajax_usermenu'),
            'login': urljoin(self.url, 'user/login'),
            'search': urljoin(self.url, 'engine/search'),
            'download': urljoin(self.url, 'engine/download_torrent?id={0}')

**Comment by medariox** [comment]
It still works because it follows the redirect.

**Comment by medariox** [comment]
Closing as solved, please reply if it's not the case.
