### ISSUE TITLE
Docker Update ?

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#5726]
Hi Team

Since i have updated to v2.12 I now have this showing on my main page;

There is an update available: please pull the latest docker image, and rebuild your container to update

How do i update this as there is no new Docker Versions

Thanks

**Comment by a10kiloham** [comment]
It seems the current commit hash isn't showing properly. The newest docker image dropped like an hour ago but my hash in app says Commit: 0c0a73583452f988c518adeafa75ee1f17987bdf

**Comment by p0psicles** [comment]
It shouldn't show. Not sure whats going on. On which commit are you running? Can you post debug logs on the startup?

Also watchtower is the way to go.

**Comment by a10kiloham** [comment]
@p0psicles watchtower updated to the absolute latest. 

```
2018-11-16 18:34:49 DEBUG    CHECKVERSION :: [0c0a735] User-Agent: Medusa/0.2.12 (Linux; 4.15.0-38-generic; 49e86161-e9ce-11e8-b926-0242ac110006)
2018-11-16 18:34:49 DEBUG    CHECKVERSION :: [0c0a735] GET URL: https://cdn.pymedusa.com/news/news.md [Status: 200]
2018-11-16 18:34:49 DEBUG    CHECKVERSION :: [0c0a735] Checking GitHub for latest news.
2018-11-16 18:34:49 DEBUG    CHECKVERSION :: [0c0a735] There is an update available, Medusa is running in a docker container, so auto updating is disabled.
2018-11-16 18:34:49 DEBUG    CHECKVERSION :: [0c0a735] cur_commit = 0c0a73583452f988c518adeafa75ee1f17987bdf, newest_commit = a1d899bc882da047b3d6ff936e8b78b62b169b05, num_commits_behind = 121
2018-11-16 18:34:48 INFO     CHECKVERSION :: [0c0a735] Checking for updates using SOURCE
```

**Comment by a10kiloham** [comment]
this was just freshly pulled and restarted again for good measure. the docker image isn't reflecting the hash for some reason.

**Comment by p0psicles** [comment]
I need to dive into this. In the mean time you can fix it by overwriting the commit hash in your config.ini.

**Comment by p0psicles** [comment]
`a1d899bc882da047b3d6ff936e8b78b62b169b05`

**Comment by a10kiloham** [comment]
cool thanks. no rush - doesn't bother me in the least but thought i'd chime in as someone else had seen it too :)

**Comment by p0psicles** [comment]
I had to disable some update stuff in docker containers, as it sometimes resulted in db corruption when we did db migrations.

So obviously i need to finetune this some more. Glad this issue is just in the category of annoying.

**Comment by udochrist** [comment]
i'm running pymedusa/medusa in docker using docker compose. i've pulled, stopped, force-recreated and tried build. still the app does not update..
how to i actually update the container now i cannot use the git update in docker?

**Comment by p0psicles** [comment]
Maybe remove container and image, then pull pymedusa/medusa@master and docker create + start

**Comment by udochrist** [comment]
no command i can issue with docker-compose updates medusa to 0.2.12
i have removed and updated / recreated images as well as containers.
medusa simply stays at 0.2.11. 

what docker commands did you use to test this new update mechanism?

**Comment by OmgImAlexis** [comment]
Pulling the :latest tag should give you the new version.

**Comment by OmgImAlexis** [comment]
For those having issues try and pull again as I just rebuilt the master, develop and latest tags.

**Comment by OmgImAlexis** [comment]
@p0psicles I seem to be on the latest yet in Medusa I'm seeing an old commit hash being shown, any ideas?

To verify which version you're all on check `/app/medusa/medusa/common.py`.
`VERSION` should be set to `0.2.12`.

**Comment by OmgImAlexis** [comment]
Yeah not sure why that's happening.

**Comment by p0psicles** [comment]
@OmgImAlexis yeah i have an idea. It has to do with the source -> commit translation that only applies to the pymedusa/medusa image. As a workaround you should be able to get rid of it, by putting the full commit in config.ini

**Comment by HPMSGEN8** [comment]
@p0psicles Thanks for taking a look at this and confirmed there is a bug. But what is watchtower and how is this meant to get used or setup .

**Comment by udochrist** [comment]
watchtower is a docker image monitoring docker containers and performing automatic updates of the docker image with restart of the container. its v2tec/watchtower on docker hub.

**Comment by a10kiloham** [comment]
I'm not sure what watchtower has to do w this. It simply automates the pull of a new image. This error is orthogonal. There is clearly a (low priority) bug where docker image rm/repull process with medusa does not handle/update the ini file.

**Comment by HPMSGEN8** [comment]
Thanks All for this :) i will then wait until fix.

**Comment by a10kiloham** [comment]
I've checked in two PRs to start the fix for this.
https://github.com/pymedusa/Medusa/pull/5830 and https://github.com/pymedusa/Medusa/pull/5829

These generate a file at the root of the Docker image called git-commit that contains the current hash of the build. Should be trivial to update the checker to read this and compare to latest online version.

**Comment by a10kiloham** [comment]
I submitted a PR that is probably too ugly for production but ought to fix this :) https://github.com/pymedusa/Medusa/pull/5831

**Comment by medariox** [comment]
Will be fixed with https://github.com/pymedusa/Medusa/pull/6018

**Comment by HPMSGEN8** [comment]
Hi All

I am getting this still - There is an update available: please pull the latest docker image, and rebuild your container to update

How do i fix this and what is the process / commands for this please. 

Thanks

**Comment by HPMSGEN8** [comment]
Thanks

**Comment by medariox** [comment]
Release is out.

**Comment by HPMSGEN8** [comment]
@medariox Thanks but how do i update this from Docker? It states to pull from docker. I have never done this is there a guide on how to get this done please.

Thanks

**Comment by medariox** [comment]
It depends on your setup... usually, depending on which image you are using:
`docker pull pymedusa/medusa`
or
`docker pull linuxserver/medusa`

**Comment by HPMSGEN8** [comment]
@medariox i am using - https://registry.hub.docker.com/u/pymedusa/medusa/

It is running on Synology So where do i go on my NAS to what folder or once logged on just run the command.

**Comment by medariox** [comment]
See https://www.reddit.com/r/synology/comments/6put9m/update_docker_containerimage/
Specifically https://www.reddit.com/r/synology/comments/6put9m/update_docker_containerimage/dkyigtu/

**Comment by HPMSGEN8** [comment]
Thanks :)
