### ISSUE TITLE
Updated to 0.2.12 and when trying to add a show or recommended shows and the page returns {{ $route.meta.header }} and stops loading

### ISSUE THREAD

**Issue by 1sourCream** [pymedusa/Medusa#5728]
**Describe the bug**
Updated to 0.2.12 and when trying to add a show or recommended shows and the page returns 
{{ $route.meta.header }} and stops loading
**To Reproduce**
Happens whenever i click on add shows or add recommended shows.

**Expected behavior**
Click on add show and have it let me add a show.
**Screenshots**
https://imgur.com/a/rjc3871

**Medusa (please complete the following information):**
 - OS: unRAID 6.6.5
 - Branch: master
 - Commit: a1d899bc882da047b3d6ff936e8b78b62b169b05 

**Logs:**
<details>

```
<-- Please replace this whole line with your logs -->
```
</details>

**Additional context**
Not one error is in the logs and i have another setup running the same setup and it does not have an issue adding shows.

**Comment by p0psicles** [comment]
Which docker image are you using?

**Comment by 1sourCream** [comment]
linuxserver

**Comment by medariox** [comment]
Next time you can try a hard cache refresh first: `Ctrl + F5`
