### ISSUE TITLE
Match release group for subtitles

### ISSUE THREAD

**Issue by Thilas** [pymedusa/Medusa#5729]
I have a problem with the automatic subtitle downloading. If I am not using "perfect match" option, subtitles are most of the time incorrect (mainly because of a wrong release group). And if I am using it, subtitles are almost never automatically downloaded (at least in my case for French language using only addic7ed source).

Looking at the code, I saw that:

- by default, Medusa tries to match: series + year + season + episode
- and with perfect match, it tries to match: hash - resolution - video_codec - audio_codec

While perfect match score is fine to me according to its definition ("perfect" match), I think the default match should also take the release group into account. I think this is a safe way to ensure that Medusa is downloading valid subtitles.

An other way we could see it is to allow to specify whatever score we want through Medusa configuration (with multiple checkboxes or a multiple select for instance) but I guess this would make the thing more complex to define.

Thank you!

**Comment by Thilas** [comment]
From what I saw in the code, yes.

**Comment by p0psicles** [comment]
Then youll have to report there.

**Comment by p0psicles** [comment]
https://github.com/Diaoul/subliminal

**Comment by medariox** [comment]
The perfect match is something we have implemented, will look into it when I have some time.

**Comment by Thilas** [comment]
@p0psicles, I misunderstood your question. The issue comes from how Medusa uses subliminal and not from subliminal itself.

If my proposition makes sense, I can provide a pull request (I mean match the release group even for non-perfect match).

**Comment by Thilas** [comment]
@medariox, what do you have in mind? Leave non-perfect match as is and change perfect match to: series + year + season + episode + release_group.

**Comment by Thilas** [comment]
Still waiting for #5784 to be released, but #5740 is ok to me. Closing this ticket.
