### ISSUE TITLE
don't save the password webui qbitorrent

### ISSUE THREAD

**Issue by Sirfrancis17** [pymedusa/Medusa#5732]
Hello
When entering the user data and password in the torrent client tab, it does not save my password. Every time I open the tab the password is empty.
Medusa gives the following error when connecting to the client torrent

2018-11-17 11:12:21 WARNING  SNATCHQUEUE-SNATCH-66 :: [a1d899b] qbittorrent: Authentication Failed
2018-11-17 11:07:49 WARNING  APIv2-Thread_3 :: [a1d899b] Config patch ignored {u'clients': {u'torrents': {u'testStatus': u'Success: Connected and Authenticated'}}}

**Comment by p0psicles** [comment]
If you check config.ini, is the password also empty there?
As it's a password field, it's not showing the password. It should show some stars actually.
```
[TORRENT]
torrent_username = Myuser
torrent_password = testpsss
torrent_host = http://localhost:9091
torrent_path = ""
torrent_seed_time = 0
torrent_paused = 0
torrent_high_bandwidth = 0
torrent_label = ""
torrent_label_anime = ""
torrent_verify_cert = 0
torrent_rpcurl = transmission
torrent_auth_type = none
torrent_seed_location = ""
```

**Comment by Sirfrancis17** [comment]
not. it's full. when i change user and password the file shows it correctly

**Comment by p0psicles** [comment]
okay, found the bug. I'll fix it.

**Comment by Sirfrancis17** [comment]
oh, thank you very much
