### ISSUE TITLE
Plex host setting not saved

### ISSUE THREAD

**Issue by Olivier6767** [pymedusa/Medusa#5737]
Hello,
In release 0.2.12, the host setting for plex was lost. 
When trying to set ti again, it gets lost during save and the following warning is logged : 
```
2018-11-18 10:27:26 WARNING  APIv2-Thread_16 :: [a1d899b] Config patch ignored {u'notifiers': {u'plex': {u'client': {u'host': u'10.1.1.83:32400', u'password': u''}}}}
```
Even when modifying the config file manually, the following error is logged when a plex notification is triggered : 
```
2018-11-18 10:25:43 WARNING  POSTPROCESSOR :: [a1d899b] PLEX: Error while trying to contact Plex Media Server: Error: MaxRetryError("HTTPConnectionPool(host='**********', port=80): Max retries exceeded with url: /library/sections (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa3084863d0>: Failed to establish a new connection: [Errno 22] Invalid argument',))",)
```

**Comment by OmgImAlexis** [comment]
@p0psicles this should be sent as an array since we have it set as a ListField in the API.

https://github.com/pymedusa/Medusa/blob/a1d899bc882da047b3d6ff936e8b78b62b169b05/medusa/server/api/v2/config.py#L218

**Comment by p0psicles** [comment]
The log states the client, not server
`{u'plex': {u'client': {u'host': u'10.1.1.83:32400', u'password': u''}}}}`

**Comment by p0psicles** [comment]
I'm having a real hard time reproducing this.
This is what it looks like in my config.ini, after chaging it:
```
plex_server_host = 192.168.1.2:32400, 192.168.1.3:32400
plex_server_token = ""
plex_client_host = ,
```

**Comment by Olivier6767** [comment]
I stopped Medusa, deleted all entries in the PLEX section off the config file and restarted.
I then entered the settings as shown below.
You can also see that mopst settings are not written to the config file, expect the password which is put into the field : plex_server_host....
This stopped working with the last upgrade.

`[Plex]
use_plex_server = 1
plex_notify_onsnatch = 0
plex_notify_ondownload = 0
plex_notify_onsubtitledownload = 0
plex_update_library = 1
plex_server_host = pass
plex_server_token = ""
plex_client_host = ,
plex_server_username = ""
plex_server_password = ""
use_plex_client = 0
plex_client_username = ""
plex_client_password = ""
plex_server_https = 0`

![image](https://user-images.githubusercontent.com/28684355/48711747-4cf9c480-ec0c-11e8-8cc0-5e88fa86033d.png)

As a side note, I just notices that the text on the Plex MEdia Server settings page mentions : Send KODI commands?   It should say PLEX commands.

**Comment by p0psicles** [comment]
Is the config.ini the result of the settings you changed in the gui? Or did you change them manually in config.ini.?

Also can you enable debug logging, restart. And save settings in gui. Send me debug logs since startup and the console logs from chrome?

I cant reproduce this at all. Maybe try doing a git reset --hard origin/master?

**Comment by Olivier6767** [comment]
Yes the config.ini was the result of the changes in the gui, no manual change in the file.

I just did a git reset --hard origin/master and a git pull. I then cleaned up the config file section before starting this trace. 

Here is the config file section before:

```
[Plex]
use_plex_server = 0
plex_notify_onsnatch = 0
plex_notify_ondownload = 0
plex_notify_onsubtitledownload = 0
plex_update_library = 0
plex_server_host = ,
plex_server_token = ""
plex_client_host = ,
plex_server_username = ""
plex_server_password = ""
use_plex_client = 0
plex_client_username = ""
plex_client_password = ""
plex_server_https = 0
```

Here are the settings:
![image](https://user-images.githubusercontent.com/28684355/48721739-c7cdda00-ec22-11e8-85d8-b6308a4de17e.png)


Here is the config file after:
```
[Plex]
use_plex_server = 1
plex_notify_onsnatch = 0
plex_notify_ondownload = 0
plex_notify_onsubtitledownload = 0
plex_update_library = 1
plex_server_host = pass
plex_server_token = ""
plex_client_host = ,
plex_server_username = ""
plex_server_password = ""
use_plex_client = 0
plex_client_username = ""
plex_client_password = ""
plex_server_https = 0
```


Here is the debug information:
[debug.log](https://github.com/pymedusa/Medusa/files/2596238/debug.log)

Here is the Chrome console log
[medusa.olisab.com-1542645675414.log](https://github.com/pymedusa/Medusa/files/2596224/medusa.olisab.com-1542645675414.log)

Thanks!

**Comment by p0psicles** [comment]
@OmgImAlexis can you reproduce this?

**Comment by OmgImAlexis** [comment]
I used the same before config.

I ended up with this.
```
[Plex]
use_plex_server = 1
plex_notify_onsnatch = 0
plex_notify_ondownload = 0
plex_notify_onsubtitledownload = 0
plex_update_library = 1
plex_server_host = pass
plex_server_token = ""
plex_client_host = ,
plex_server_username = ""
plex_server_password = ""
use_plex_client = 0
plex_client_username = ""
plex_client_password = ""
plex_server_https = 0
```

**Comment by OmgImAlexis** [comment]
Just rebuilding incase I was on another branch still.

**Comment by OmgImAlexis** [comment]
Okay, tried with a fresh install. This is what we're sending the server from that form. So it does look like it's an API issue.

```
{
  "updateLibrary": true,
  "host": [
    "10.1.1.83:32400"
  ],
  "enabled": true,
  "https": false,
  "token": "ABCDEFG",
  "username": "user",
  "password": "pass"
}
```
