### ISSUE TITLE
Anime default not respected

### ISSUE THREAD

**Issue by calmcacil** [pymedusa/Medusa#5739]
**Describe the bug**
Currently it seems the save defaults are not being recognized, especially not the anime one, i add shows and i have anime selected as my default. Interestingly enough i also noticed that if you go to add show, and on page 3 of 3 click save default without changing anything, it'll untick anime and season folders despite being checked from previous default.

**To Reproduce**
1. Enable anime as default.
2. Add any anime show
3. See that its not flagged as anime.

**Expected behavior**
Expected behavior that set default actually sets your defaults.

**Medusa (please complete the following information):**
 - OS: Docker, linuxserver.io container
 - Branch: master
 - Commit: a1d899bc882da047b3d6ff936e8b78b62b169b05

**Comment by p0psicles** [comment]
Could you try out the branch referenced here:
https://github.com/pymedusa/Medusa/pull/5749

**Comment by calmcacil** [comment]
can confirm that that branch fixes anime, however, season folder is not being respected in the same way still. so seems whatever fix is applied for anime also needs to be applied to the other toggles for saving defaults.

**Comment by p0psicles** [comment]
Can you check again?

**Comment by calmcacil** [comment]
That seems to have sorted it on my end, no issues with defaults.
