### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: RTL5

### ISSUE THREAD

**Issue by ginodesilva** [pymedusa/Medusa#5751]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.105-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@a1d899bc882da047b3d6ff936e8b78b62b169b05
**Link to Log**: https://gist.github.com/a6fb4b1d4334b19a33834f2a60296cb3
### ERROR
<pre>
2018-11-19 13:58:53 ERROR    Thread_0 :: [a1d899b] Missing time zone for network: RTL5
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/872f5249bdb5d946652e071f1d5543f3b0facba7
