### ISSUE TITLE
Android Compatibility

### ISSUE THREAD

**Issue by Dhop84** [pymedusa/Medusa#5754]
As the title says, I'd love to be able to install this on my Nvidia shield

**Comment by p0psicles** [comment]
It should be possible with android studio and Chaquopy.

**Comment by Dhop84** [comment]
I wouldn't have a clue how to do that, is it something you could do?

**Comment by p0psicles** [comment]
I guess i could do that. But ill probably wont.

**Comment by p0psicles** [comment]
This is probably never going to happen. Sorry
