### ISSUE TITLE
Medusa Not enough info to 

### ISSUE THREAD

**Issue by Tofu86** [pymedusa/Medusa#5766]
Hi there,
I'm currently trying to import the following show.
[https://imgur.com/a/arOC15v](url)

It just wont process the files no matter what I do. I've attached the debug log below.
[medusa.txt](https://github.com/pymedusa/Medusa/files/2607057/medusa.txt)

**Comment by medariox** [comment]
Guessit is unable to determine the episode number because `ED03` isn't a valid episode numbering.

**Comment by medariox** [comment]
For the episodes that have valid episode numbering, make sure you have the show selected as anime.

**Comment by Tofu86** [comment]
@medariox Thanks for your help. I have already set the show as [anime](https://imgur.com/a/zj41FZY) 

Naturally the OP and EDs would not be recognized but strangely the episodes themselves can't be post-processed. 

I have restarted medusa and attached the full log below
[application.log](https://github.com/pymedusa/Medusa/files/2608602/application.log)

**Comment by medariox** [comment]
I think it might be because you are using TVmaze. Can you try to add the show with TheTVDBv2 instead and see if that one works?

**Comment by Tofu86** [comment]
> I think it might be because you are using TVmaze. Can you try to add the show with TheTVDBv2 instead and see if that one works?

Same results
