### ISSUE TITLE
Button to test SABNZB settings not working

### ISSUE THREAD

**Issue by djiest** [pymedusa/Medusa#5767]
This is a follow up of #5735 

After the last update, settings are saved, but the 'Test settings' button does not respond

**To Reproduce**

- Go to 'Search Settings', tab 'NZB Search'
- Select 'SABnzbd'
- Enter SABnzbd username / password / api key
- Save
- Test SABnzbd settings > no response

**Expected behavior**
Feedback that settings are correct or not

**Comment by HPMSGEN8** [comment]
What browser you using. As on Chrome it takes some time and then it works

**Comment by medariox** [comment]
@OmgImAlexis @p0psicles @sharkykh 
Can someone take a look please?

**Comment by thestip** [comment]
Same issue here. The "Test SABnzbd" button does nothing in both Chrome and Edge.

**Comment by medariox** [comment]
Fixed with the new release.
