### ISSUE TITLE
Passwords reset on update

### ISSUE THREAD

**Issue by Pauwelz** [pymedusa/Medusa#5768]
Passwords for torrent client (e.g. Transmission) or Subtitle providers (e.g. Addic7ed and Opensubtitles) get reset everytime an update is performed. All other config settings get retained except for passwords.

**To Reproduce**
1. Enter password for torrent client or subtitle provider (Probably for Torrent providers the same issue)
2. Update Medusa using the built-in updater (Update now)
3. Check entered password fields, they will be cleared

**Expected behavior**
I'm not sure if this is intended, but it would be great if these passwords are kept during update.

**Medusa (please complete the following information):**
 - OS: QNAP QTS 4.3.5
 - Branch: master
 - Commit: 54da0c7

**Comment by p0psicles** [comment]
There also empty in the config.ini?
And there saved after restart but not update?

**Comment by Pauwelz** [comment]
Excellent remark, they are indeed not saved to the config.ini
Username gets stored, password doesn't.

**Comment by Pauwelz** [comment]
Turning off Encrypt passwords under General > Advanced Settings does save the passwords.
If I enable it again, passwords are removed from the config.ini again.

**Comment by Pauwelz** [comment]
I have found that enabling the Encryption does correctly set the encryption_version in the config, however the encryption_secret is set to "".
Because this is set to a blank string, the helpers.encrypt function returns a blank string as well.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/8823
