### ISSUE TITLE
Unable to add new show, sql error

### ISSUE THREAD

**Issue by anoriega211** [pymedusa/Medusa#5771]
**Describe the bug**
When adding 'The Good Doctor', I get a sql error stating the file is encrypted or is not a database. It doesn't seem to just be for this show, I tested adding a few other shows that aren't currently in my list and got the same result.

**To Reproduce**
1. Add new show - The Good Doctor
2. Click add show, taking me back to the home page
3. Watch the console window and it eventually errors out

**Expected behavior**
Should add the show as it's done with a bunch of others

**Medusa (please complete the following information):**
 - OS: Windows 10
 - Branch: master
 - Commit: 54da0c77d705a23f1ce67945ba4af3e1b978dcfc 

**Logs:**
Debug logs - https://gist.github.com/anoriega211/2dd597c9fa326067f44156112e273908
Snippet from console - https://gist.github.com/anoriega211/3ca4d21fabe43e6ba849a48e0d87ad31

Please let me know what else I can provide to help debug.

Thank you,
Andres

**Comment by medariox** [comment]
Check the permissions of the `cache` folder.

**Comment by anoriega211** [comment]
I checked Medusa\cache and my username has full control. I went back to the Medusa folder and forced all directories/files within to inherit the same permissions just to make sure my username has full control to everything within. Currently my username, system, and the administrators group all have full control.

Thanks,
Andres

**Comment by anoriega211** [comment]
Any suggestions on what I can do or try? I hope I don't have to start over and setup from scratch. I noticed that this location is empty, which is mentioned when trying to add a show:

`2018-11-29 09:07:29 INFO     SHOWQUEUE-ADD :: [54da0c7] TVDBv2: {u'session': <medusa.session.core.MedusaSession object at 0x0000000007BCF1D0>, u'cache': u'C:\\Users\\dre\\Desktop\\Medusa\\Medusa\\cache\\indexers\\TVDBv2', u'language': u'en', u'use_zip': True}`

I'm guessing TVDBv2 shouldn't be just an empty directory? Or does that not matter?

**Comment by anoriega211** [comment]
I ended up letting the cache directory be rebuilt... renamed the existing dir, started Medua, and forced a rescan for all shows. I'm able to add new shows again now.
