### ISSUE TITLE
Season Folders Missing On New Show Creation

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#5780]
**Describe the bug**
Folders not get created for newly added shows

**To Reproduce**
1. Add Show
2. Select Show To Add To Drive
3. Show Folder & Posters Added
4. Season Folders Missing On First Episode Post Process

**Expected behavior**
Season Folders To Get Created Once First Episode Is Post Processed

**Medusa (please complete the following information):**
DOCKER IMAGE - https://hub.docker.com/r/pymedusa/medusa/
Branch: master 
Commit: a1d899bc882da047b3d6ff936e8b78b62b169b05 
Version: Unknown 
Database: 44.12
Python Version:	2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
SSL Version:	LibreSSL 2.6.5
OS:	Linux-3.10.102-x86_64-with
Locale:	Unknown.Unknown

**Logs:**
N / A

Thanks

**Comment by medariox** [comment]
Is the `Season Folders` option enabled?
![img](https://snapr.pw/i/f765b15602.png)

**Comment by HPMSGEN8** [comment]
@medariox LOL I cannot believe this was missed i thought i saved all my Default. Options.

Thanks :)
