### ISSUE TITLE
Add Option On Edit Show Page To Change Search Time

### ISSUE THREAD

**Issue by desepticon** [pymedusa/Medusa#5783]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Some shows, like those on the Showtime and Starz network, are released at midnight on their streaming platforms on the same day before they officially air and are available to download early. It would be nice if there was an option on the edit show page to alter the time when a show gets searched so I could get the episode early without having to get it manually.

**Describe alternatives you've considered**
For now I've just been adding the shows to my downloader manually.

**Additional context**
none

**Comment by p0psicles** [comment]
Implemented in last release

**Comment by Bilbo** [comment]
Hi p0psicles,

Would you be so kind as to explain where this feature is on the Edit Show screens or is it found elsewhere. I am using version 0.2.14 (2018-12-19). Perhaps in yet to come in a future version not yet pushed out.

Cheers,

**Comment by p0psicles** [comment]
It's not in edit show  - advanced tab, airdate offset?

**Comment by p0psicles** [comment]
Ooh oops its still in develop
https://github.com/pymedusa/Medusa/blob/develop/CHANGELOG.md
