### ISSUE TITLE
Status of snatched episodes not changed to downloaded, while file has been post processed.

### ISSUE THREAD

**Issue by IanPHeitmans** [pymedusa/Medusa#5794]
**Describe the bug**
Often when Medusa snatches an episode, it's post processed (e.g. downloaded, moved, renamed and meta stuff downloaded) but the status remains at "Snatched". Even when I "Force full update" everything it remains "Snatched" even though the debug log indicates that it found the files (it even downloaded the thumbnails and all). I focused on episode s09e05 in this case. I don't know what, if anything, I'm doing wrong. Please help me.

**Expected behavior**
I expected the files to initially be marked as "Downloaded" as soon as Medusa post processes the files.

**Medusa (please complete the following information):**
 - OS: Debian Linux 8.11 x64
 - Branch: master
 - Commit: 54da0c77d705a23f1ce67945ba4af3e1b978dcfc

**Logs:**
<details>

```
[application.log](https://github.com/pymedusa/Medusa/files/2623984/application.log)

```
</details>

**Additional context**
Not sure if it's a bug or if I've done something wrong with the configuration. I really hope someone can help.

**Comment by p0psicles** [comment]
Need debug logs of a pp that goes wrong.

**Comment by IanPHeitmans** [comment]
Hope this will help. I changed episode s07e08 to "wanted" and Medusa downloaded snatched it automatically. Then it processed it, moved it to the correct folder and renamed the file. Yet the episode remains "snatched" in Medusa.

![image](https://user-images.githubusercontent.com/27200008/49287522-15a5d600-f49e-11e8-9f7e-694d67dbee7b.png)


![image](https://user-images.githubusercontent.com/27200008/49287471-e2fbdd80-f49d-11e8-84aa-ce09435f572b.png)


[application.log](https://github.com/pymedusa/Medusa/files/2633058/application.log)

**Comment by a10kiloham** [comment]
Are you doing some kind of post processing in SAB?
Your logs here don't actually show any postprocessing taking place in SAB unless you've omitted them. Is there maybe another app running like Radarr that's intercepting?

**Comment by GovPerm** [comment]
I get this issue as well. episode loads fine, but won't switch from snatched to downloaded. Sometimes the episodes will keep downloading because the status isn't changing.

**Comment by IanPHeitmans** [comment]
Thanks to **a10kiloham** I found out what the problem was. I moved from Sickrage to Medusa. And although I though I disabled Sickrage, apparently after a reboot if was started again, together with Medusa on startup. And obviously Sickrage was the one who seemed to always be quicker with the postprocessing and therefore Medusa never changed the status to "downloaded".

**Comment by GovPerm** [comment]
Logs attached. 
[Medusa Logs Snatched Downloaded Issue.pdf](https://github.com/pymedusa/Medusa/files/2658847/Medusa.Logs.Snatched.Downloaded.Issue.pdf)

**Comment by medariox** [comment]
@GovPerm 
All your logs show is snatching of episodes, there is nothing post-processing related.
