### ISSUE TITLE
[APP SUBMITTED]: 337020: Multiple entries found in show: BEATLESS 

### ISSUE THREAD

**Issue by pct00** [pymedusa/Medusa#5798]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@54da0c77d705a23f1ce67945ba4af3e1b978dcfc
**Link to Log**: https://gist.github.com/fd2472ff96ba9420f16f143bc8d0e0eb
### ERROR
<pre>
2018-11-28 20:14:38 ERROR    SEARCHQUEUE-MANUAL-337020 :: [Nyaa] :: [54da0c7] 337020: Multiple entries found in show: BEATLESS 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

edit @p0psicles: had the same issue with Tokyo Goul and Black Clover.

**Comment by p0psicles** [comment]
I have the same issue. So I'm sure its again a messup on tvdb or thexem.
I've copied my db. You can probably fix it by re-adding the show beatless. But i'm not 100% sure. I'll know more later.

**Comment by p0psicles** [comment]
@duramato @thezoggy any ideas?

**Comment by p0psicles** [comment]
connected: #5796 #5797

**Comment by p0psicles** [comment]
@pct00 you'll have to wait for my fix, and then re-add the show.

**Comment by pct00** [comment]
@p0psicles thanks for the feedback. it's no issue waiting and readding.
wasn't there a way to make a manual over ride on the absolute numbers locally to try to sort this kind of issues? i trid but couldn't find it,

also, maybe move this stuff from error to warning? not concerned about this specific case but if it the absolute numbering keeps getting messed up you guys will get spammed with these messages.

**Comment by p0psicles** [comment]
No should be an error. Because its a data integrity error.

The fix is in develop. It will prevent the issue for new episodes.

**Comment by thezoggy** [comment]
has it been reported to tvdb ? update tvdb data yourself ?

**Comment by p0psicles** [comment]
Its not that simple. Tvdb has ep 20 -> ab null and 24 -> ab 20. Then xem enrichment  has ep 20 set to ab 20. Leaving us with two ab 20.

**Comment by p0psicles** [comment]
I kinda fixed it for now by ignoring the xem enrichment for that ep. If that ab ep already exists.
