### ISSUE TITLE
DB Upgrade

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#580]
**TV_SHOWS**
- _size: store show size and only update with refresh and/or PP_
- ~~_description_~~ https://github.com/pymedusa/Medusa/pull/2147
- _actors_
- _search_method_

**TV_EPISODES**
- ~~_torrent hash: auto remove torrent from client_~~ (added to history)
- _torrent client: where hash was sent_ (fernandog: don't think is really needed)
- _torrent file link_
- _nzb guid_
- _nzb link_
- _actors_
- ~_watched_~ #4825 
- previous quality: if better quality stalls or fails, don't delete previous file and use previous quality
- previous status: same as above
- previous release file: if better quality stalls or fails, don't delete previous file and use previous quality. 
  Also use this if user rename file and don't put all needed info
## cache.db

**history**
- _size_
- ~~_hash_~~ https://github.com/pymedusa/Medusa/pull/1743
- _link_
- ~~_proper_~~ https://github.com/pymedusa/Medusa/pull/783

**provider cache tables**
Consolidate all provider tables to one table
## Failed.db
- _history.hash_
- _failed.hash_
  <br/>
  Include failed.db in sickbeard.db
  Add quality to failed.db

Subtitles: add to DB all subtitles downloaded and all languages of them.

**Comment by p0psicles** [comment]
Move scene_exceptions to sickbeard.db?

**Comment by labrys** [comment]
@p0psicles User entered scene exceptions should be in sickbeard.db, but ones cached from online sources (e.g. XEM) imo should remain in cache.db.

**Comment by duramato** [comment]
thing is @labrys you can't force a scene exceptions pull, only in the daily scheduled show update.

**Comment by p0psicles** [comment]
I've added consolidate provider cache tables to one. But I don't know the original reason to separate them, so maybe we shouldn't do that?

**Comment by duramato** [comment]
TV SHOWS, the english title
When you add a show with language as some other diferent than english the title most of the times is diferent, with the original , english, title in the db that one can also be used for searching

**Comment by fernandog** [comment]
pymedusa/Medusa/issues/1989
