### ISSUE TITLE
New Search settings GUI

### ISSUE THREAD

**Issue by bnevets27** [pymedusa/Medusa#5800]
The new layout of the search filters in the search settings don't allow pasting or copying of the ignored/undesired/preferred/required words. Being able to paste in or copy the comma separated list was a lot more efficient then having to type each word one by one.

Also the description of each of the sections should be at the top rather than the bottom as it looks to be describing the next section rather than the previous.

**Comment by p0psicles** [comment]
for that you click the two circular arrows.
![image](https://user-images.githubusercontent.com/1331394/49220678-20496800-f3d7-11e8-92fd-e8d373c43744.png)

![image](https://user-images.githubusercontent.com/1331394/49220686-293a3980-f3d7-11e8-99e1-432a7be542d6.png)

And yes the layout can be better. It has low prio now, as we don't have any active frontend (html/css) devs. If you wanna help. Be our guest.
