### ISSUE TITLE
1440p WEB-DL is identified as SDTV

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#5806]
1440p WEB-DL is identified as SDTV
should be included in 4K or another quality?

**Comment by wimpyrbx** [comment]
Example:
Showname (2018) - S01E08 - Episode Title (1440p WEB-DL).mkv

**Comment by medariox** [comment]
The problem is that `1440p` isn't a proper TV resolution by any means and we can't support all the weirdest resolutions out there.

**Comment by p0psicles** [comment]
Shouldn't it be registered as the highest supported resolution? Like 720p in this case?

**Comment by medariox** [comment]
Hmm, that would provide incorrect information tho?
