### ISSUE TITLE
Kodi notification settings - "always on" not saved

### ISSUE THREAD

**Issue by Inervo** [pymedusa/Medusa#5817]
**Describe the bug**
In Notification setting, regarding kodi : when switching off "always on", and saving, this specific setting is not saved!

**To Reproduce**
1. Go to Notification
2. Switch on Kodi
3. Switch off "Always on"
4. Save
5. Refresh page: the setting is still on

**Medusa (please complete the following information):**
 - OS: Synology DSM6
 - Branch: master
 - Commit: Last (54da0c7)

**Comment by medariox** [comment]
@p0psicles Can you look into this please?

**Comment by p0psicles** [comment]
Sure

**Comment by medariox** [comment]
Thanks for the bug report! Fixed with https://github.com/pymedusa/Medusa/pull/5871
