### ISSUE TITLE
Migrating from Windows SickChill to Synology Medusa

### ISSUE THREAD

**Issue by BenTotoro** [pymedusa/Medusa#5824]
Hello,

I have a question : Is there a way to transfer Sickrage running on Windows to Medusa running on a Synology NAS ?

Thanks a lot

**Comment by HPMSGEN8** [comment]
@BenTotoro the best way is to do a Clean Install on your Synology and then Import your Library.

**Comment by medariox** [comment]
Closing, please write if you still need support.
