### ISSUE TITLE
Can Not Get Custom search Providers To Work

### ISSUE THREAD

**Issue by salteran** [pymedusa/Medusa#5826]
I can not get Custom Providers for Torrents to Work.

I have followed what is in in the wiki done google searches and can not find any helpful information

I have put in the password and cookies and the URL and RSS feed information for multiple sites such as ettv and eztv but when I look in the logs after a search has been done there is nothing about these sites at all.  Not even a mention of incorrect setup

**To Reproduce**
Carry out manual search of an episode

Go into a show
Select an episode
carry out a manual search
check logs to see what sites were searched
No Custom providers listed

**Expected behavior**
I would expect to see custome providers listed in the manual search results for torrents they have
I would expext to see some search information in the logs, but there is nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/45611274/49482388-e8747180-f869-11e8-905e-4427179b152a.png)

![image](https://user-images.githubusercontent.com/45611274/49482487-528d1680-f86a-11e8-90e1-40a19d314005.png)

![image](https://user-images.githubusercontent.com/45611274/49482523-7ea89780-f86a-11e8-9548-7ffcab7215b8.png)

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64]
 - Branch: [e.g. master, develop]
 - Commit: [e.g. c65ca2]

**Logs:**
<details>

![image](https://user-images.githubusercontent.com/45611274/49482579-b9aacb00-f86a-11e8-9792-cd7ea6d637c3.png)

Any assistance would be greatly apreciated,  I am new to Medusa and github. Everything else is working perfectly. Just can not get this to work

Thanks

**Comment by medariox** [comment]
Why are you setting the cookies for ETTV? They shouldn't be needed. Enable debug logging and post the debug logs of the search (not a screenshot).

**Comment by salteran** [comment]
Hi

I had the cookies on attempting it just in case.  I have removed.  I have turned debug on and attached is the log. I moved ETTV to the top of the provider list. Thanks for your assistance

[application.log](https://github.com/pymedusa/Medusa/files/2649492/application.log)

**Comment by p0psicles** [comment]
Well jacket does pretty much the same as what medusa does. Periodic read a feed, and store the results for later search.

So you can use backlog search. But only search results you stored running the daily searches.

**Comment by salteran** [comment]
Hi Dario

 

Thank you for your assistance on this much appreciated

 

I believe I will log a feature request as suggested

 

This makes more sense now you have explained it.  

 

This would be fantastic if it was put into the documentation as the customer search providers section is a bit light on in explanation.  I did not realise you could not do manual searches or backlog searches using the custom provider

 

Lastly how do you get api keys and URLS for  Jackett for a site

 

Cheers

 

Thanks for your assistance

 

All the best

 

Alan

**Comment by salteran** [comment]
Thanks For responding

 

So how do you get api keys and URLS for  Jackett for a site

 

Thanks

 

Alan

**Comment by salteran** [comment]
Also where does the search results get stored?

**Comment by p0psicles** [comment]
In an sqlite table cache.db

**Comment by medariox** [comment]
Check Jackett on how to get the API key.
