### ISSUE TITLE
Single quote added as &#39; to filename

### ISSUE THREAD

**Issue by bolhaskutya** [pymedusa/Medusa#5833]
**Describe the bug**
I used preview rename to mass rename files. Instead of single quotes, its html escaped counterpart: `&#39; `was added to an episode's filename, but not to all. I don't know if this happens with regular post-processing renames.

**To Reproduce**
Mass rename files with preview rename tool.

**Preview of bugged filename and expected filename**
![quote-bug2](https://user-images.githubusercontent.com/34036534/49532550-0a4b1400-f8bd-11e8-98e9-e03d52eb4ce4.jpg)

**Screenshot of rename preview list**
![quote-bug](https://user-images.githubusercontent.com/34036534/49532561-12a34f00-f8bd-11e8-8871-4167493941fd.jpg)

**Medusa:**
 - OS: Synology DSM6
 - Branch: master
 - Commit: 54da0c77d705a23f1ce67945ba4af3e1b978dcfc

**More research:**
Strangely enough. American Horror Story.S05.E04 Devil's Night renames fine.
On tvdb.com both episodes seem to be fine.
https://www.thetvdb.com/series/american-horror-story/episodes/5309449
https://www.thetvdb.com/series/american-horror-story/episodes/6208554
- It could be an inconsistency on tvdb.com, perhaps the title is double escaped?

**Suggested solution:**
- Perhaps a safety check is needed for html escaped characters?
- Or an extra "unescape" method before applying filenames?

**Comment by medariox** [comment]
Sadly it's coming like that from TheTVDB's API. One time it's `Don&#39;t Be Afraid of the Dark` and one time it is `Devil's Night`. We could work around it, yes, but honestly they should rather have it consistent in their API.

**Comment by bolhaskutya** [comment]
Thanks for the fast reply :)
I posted the bug on tvdb's gitlab, we'll see how it goes over there.

**Comment by medariox** [comment]
Great, please let us know!

**Comment by bolhaskutya** [comment]
It seems `&#39;` was entered literally into the episode title. Developers at tvdb's gitlab have confirmed that the api itself isn't the cause. 
[https://gitlab.thetvdb.com/site/thetvdb_api/issues/55](https://gitlab.thetvdb.com/site/thetvdb_api/issues/55)
Closing issue.
