### ISSUE TITLE
Postprocesing not working so precise

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#5840]
Hello 

I am having some problems with the good doctor show: https://pastebin.com/yeZcu5VL 
This is how it is: http://prntscr.com/lrg2x0 and this is how it shows in medusa: http://prntscr.com/lrg375 
the funny thing is that those files are inside the show folder, not in postprocesing one, so it should be easier for medusa to find them correclty and seems it is not-
Also do not know why medusa do not have enough information to determine which is this episode: http://prntscr.com/lrgd9s 
is there any way for medusa to scan metadata to be more precise? 

Kind regards

**Comment by p0psicles** [comment]
Add thegooddoctor as scene exception.
Amd for the anime. This is one of the worst namings ive seen in a while. Really no wonder guessit cant get the episode from that.

**Comment by p0psicles** [comment]
The good doctor names are also not that good. After adding the scene exception. Also add dots between thegooddoctor and 720p as a minimum.

**Comment by elpedriyo** [comment]
well, you know, I am not the one uploading the episodes like that, it is just the people that rip them.
I think medusa should improve in the guessing of this things, if things were well done from the begining from the ripers side, then we should not need renaming service in medusa running.
I know that some other thrid party programs just guess this things better, but I wanted only to use medusa, one of them is called filebot, maybe you know it, and I think the code is also in github. Would it be so difficult to try and see how they do it to improve medusa guessing service?

**Comment by elpedriyo** [comment]
> Add thegooddoctor as scene exception.
> Amd for the anime. This is one of the worst namings ive seen in a while. Really no wonder guessit cant get the episode from that.

Doesn't work, medusa is confused with the 101, 102, 103 etc etc

**Comment by p0psicles** [comment]
We use guessit. Which already successfully guesses release way more releases then the regex rules in all the other sick* forks.

But if you want to improve guessit to parse your release names better, report it with them. https://github.com/guessit-io/guessit

**Comment by elpedriyo** [comment]
What a pitty, it seems they do not answer on their issue tracker.

**Comment by ratoaq2** [comment]
Well, if the issue was posted in guessit, it was fixed
