### ISSUE TITLE
Daily Shows don't load (Shows with lots of episodes)

### ISSUE THREAD

**Issue by GovPerm** [pymedusa/Medusa#5856]
***I posted this on a previous bug that seems to have solved that persons issue in October but the issue seems to have come back so I posted it as a new bug as well***

I'm having this issue with The Ellen Degeneres Show (Daily Episodes). When I add the show, it won't load the seasons and episodes, and I can't delete the show since it never loads. I'm on the latest master.

Using Medusa with Deluge on a Seedbox (Medusa is connected to PlexRequests as well, but I didn't enter the Ellen show via PlexRequests interface. I added directly via Medusa).

The place where it says
"Loading…
If this is taking too long,
click here to show the page."
When I "click here" nothing happens either.

Any help is appreciated. Thanks.

PS, this also happened with Pardon The Interruption (ESPN Show)

**Comment by GovPerm** [comment]
Just wanted to add the log. Looks like it's checking for new episodes of the show, but I can't get the seasons or episode list to load in the UI.
[Daily Show Not Loading Issue.pdf](https://github.com/pymedusa/Medusa/files/2658868/Daily.Show.Not.Loading.Issue.pdf)

**Comment by medariox** [comment]
It just takes a lot of time to load because we don't use pagination.
You can remove the shows from Manage > Mass Update

**Comment by GovPerm** [comment]
Any way to add an option when adding a show to say whether or not it's a daily show and if the user selects that it is a daily show, medusa will only grab episode information going back 30 days? So when the show is first added, medusa only grabs episode info for the last 30 days. If the user wants to add more episodes, it could be adjusted later as a user adjusted setting? Not sure how easy it would be to set it up like that. By limiting the episode lookback period, it would probably resolve the issue.

**Comment by rafi-d** [comment]
Here is an idea - there is already "pagination" for shows - page=season... So I suggest to always load only the last 1-2 seasons (active/last season and future season). Then add a "Load past seasons" button at the bottom, so to load the rest if the user likes to.

This will make it quick, since now - it takes unreasonably long!

**Comment by canadria** [comment]
I see this issue on the Daily Show. I had posted previously about it in IRC, and someone there directed me to install a dev build which fixed the problem, but it's seems to be a regression, and none of the recent dev builds resolve it.

**Comment by p0psicles** [comment]
@omgimalexis can you please take a look at this?

**Comment by canadria** [comment]
Any word in this? Even if it's a future version, I would love to know.

**Comment by rafi-d** [comment]
How about additional setting - # of seasons to load/show (default to "all"), and one new button - "load all seasons" if set to partial loads?

**Comment by p0psicles** [comment]
It's frontend / js work. Im working on it. It's just progressing slowly. We already have a paginated api for it. Now need to replace mako with vue. If any js / vue dev would help out it would go faster.

**Comment by canadria** [comment]
Thanks! I didn't personally mean to imply anything other than sincere hope this can be fixed. I know you guys are working hard, and this is not your day job.

**Comment by p0psicles** [comment]
I've been working on this issue here: https://github.com/pymedusa/Medusa/pull/6315. If you're able to checkout the branch and do some early testing with your show, that would be very helpful!

**Comment by p0psicles** [comment]
fixed
