### ISSUE TITLE
LimeTorrents address needs to be updated

### ISSUE THREAD

**Issue by Bilbo** [pymedusa/Medusa#5859]
**Describe the bug**
Not really a bug but an updated is required for the address.
I'm getting Status: 301 errors (meaning site has moved) as shown below:
SEARCHQUEUE-DAILY-SEARCH :: [LimeTorrents] :: [54da0c7] GET URL: https://www.limetorrents.cc/browse-torrents/TV-shows/ [Status: 301]

I believe the new address is https://www.limetorrents.info

Because it's a built-in provider I can't seem to change it.

Could this be updated in a future commit?

Thanks

**To Reproduce**
1. Go to 'http://localhost:8081/errorlogs/viewlog/?min_level=10&log_filter=None&log_period=one_day&log_search=status%3A%20301'

**Screenshots**
![image](https://user-images.githubusercontent.com/314932/49688479-7fdefc00-fad8-11e8-90c8-4d023965fcf4.png)

**Medusa (please complete the following information):**
 - OS: WIndows 10
 - Branch: master
 - Commit: 54da0c77d705a23f1ce67945ba4af3e1b978dcfc 

**Logs:**
<details>

```
<-- Please replace this whole line with your logs -->
```
</details>

**Additional context**

**Comment by medariox** [comment]
Thanks for the report! Fixed with https://github.com/pymedusa/Medusa/commit/14766592caeaa6be536abc1fb5b3bc2ba705bbf5
