### ISSUE TITLE
Can't open medusa

### ISSUE THREAD

**Issue by homegreewn** [pymedusa/Medusa#5880]
**Describe the bug**
After running systemctl start medusa I'm getting this error:

`pi@raspberrypi:~ $ sudo systemctl status medusa
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: e
   Active: failed (Result: exit-code) since Mon 2018-12-10 13:06:35 EST; 35s ago
  Process: 460 ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --daemon --n
 Main PID: 460 (code=exited, status=1/FAILURE)

Dec 10 13:06:34 raspberrypi python2.7[460]:   File "/opt/medusa/medusa/databases
Dec 10 13:06:34 raspberrypi python2.7[460]:     self.connection.action('ALTER TA
Dec 10 13:06:34 raspberrypi python2.7[460]:   File "/opt/medusa/medusa/db.py", l
Dec 10 13:06:34 raspberrypi python2.7[460]:     sql_results = self._execute(quer
Dec 10 13:06:34 raspberrypi python2.7[460]:   File "/opt/medusa/medusa/db.py", l
Dec 10 13:06:34 raspberrypi python2.7[460]:     sql_results = cursor.execute(que
Dec 10 13:06:34 raspberrypi python2.7[460]: sqlite3.OperationalError: attempt to
Dec 10 13:06:35 raspberrypi systemd[1]: medusa.service: Main process exited, cod
Dec 10 13:06:35 raspberrypi systemd[1]: medusa.service: Unit entered failed stat
Dec 10 13:06:35 raspberrypi systemd[1]: medusa.service: Failed with result 'exit
`

**To Reproduce**
sudo systemctl start medusa

**Expected behavior**
medusa to start

**Medusa (please complete the following information):**
 - OS: latest raspbian
 - Branch: [e.g. master, develop]
 - Commit: [e.g. c65ca2]

**Logs:**

```
OperationalError: attempt to write a readonly database
2018-12-10 13:06:34 ERROR    MAIN :: [54da0c7] DB error: Error: 'attempt to write a readonly database'
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: attempt to write a readonly database
2018-12-10 13:06:34 ERROR    MAIN :: [54da0c7] Error in AddE**********sodeWatchedField: Error: 'attempt to write a readonly $
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 466, in _processUpgrade
    instance.execute()
  File "/opt/medusa/medusa/databases/main_db.py", line 837, in execute
    self.connection.action('ALTER TABLE tv_e**********sodes RENAME TO tmp_tv_e**********sodes;')
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: attempt to write a readonly database

```
</details>

**Additional context**
Was working fine yesterday

**Comment by medariox** [comment]
You need read and write access to the database.

**Comment by homegreewn** [comment]
> You need read and write access to the database.

Sorry I didn't realize permissions resetted after all the troubleshooting I did. The original error was this:

`● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-12-10 20:12:56 EST; 23s ago
  Process: 8074 ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa (code=exited, s
 Main PID: 8074 (code=exited, status=1/FAILURE)

Dec 10 20:12:55 raspberrypi python2.7[8074]:   File "/opt/medusa/medusa/__main__.py", line 1097, in initialize
Dec 10 20:12:55 raspberrypi python2.7[8074]:     cache_db_con.action('VACUUM')
Dec 10 20:12:55 raspberrypi python2.7[8074]:   File "/opt/medusa/medusa/db.py", line 285, in action
Dec 10 20:12:55 raspberrypi python2.7[8074]:     sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone
Dec 10 20:12:55 raspberrypi python2.7[8074]:   File "/opt/medusa/medusa/db.py", line 113, in _execute
Dec 10 20:12:55 raspberrypi python2.7[8074]:     sql_results = cursor.execute(query)
Dec 10 20:12:55 raspberrypi python2.7[8074]: sqlite3.DatabaseError: database disk image is malformed
Dec 10 20:12:56 raspberrypi systemd[1]: medusa.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 20:12:56 raspberrypi systemd[1]: medusa.service: Unit entered failed state.
Dec 10 20:12:56 raspberrypi systemd[1]: medusa.service: Failed with result 'exit-code'.
`

**Comment by p0psicles** [comment]
Search the cache.db file. Remove it.

**Comment by homegreewn** [comment]
> Search the cache.db file. Remove it.

Will that delete my library and force me to readd all my shows?

**Comment by homegreewn** [comment]
> No, thats the main.db file

ty both for your help, problem solved

**Comment by p0psicles** [comment]
Check for a backup of your main.db? Maybe it created a new one because of your file access issues?

**Comment by homegreewn** [comment]
> Check for a backup of your main.db? Maybe it created a new one because of your file access issues?

![image](https://user-images.githubusercontent.com/11887610/49782002-ae302780-fce2-11e8-98cd-a7043d4cf208.png)
Any of these

**Comment by p0psicles** [comment]
Yes latest version

**Comment by homegreewn** [comment]
> Yes latest version

Ty for your help and sorry for my ignorance... so rm "main.db" and then copy "main.db.v44.11" and rename it to "main.db"?

**Comment by p0psicles** [comment]
Yeah or move your existing main.db to main.db.bak and then mv main.db.v44.11 main.db

**Comment by homegreewn** [comment]
> Yeah or move your existing main.db to main.db.bak and then mv main.db.v44.11 main.db

Tried all the way up until ...v44.8 with no success :(. Found a backup in the backup folder in a zipped file which worked but it is 20 days old so i lost a big chunk of my shows. Guess I'll just readd them. 

Thank you again for your help! :D
