### ISSUE TITLE
Settings -> Check propers: incorrect string in drop-selector

### ISSUE THREAD

**Issue by bolhaskutya** [pymedusa/Medusa#5890]
**Describe the bug:**
Just a minor typo :)
Under Settings -> Search Settings -> Episode Search -> **Check propers every**
The last option in the drop-down selector is incorrectly named **24 hours** instead of **15 minutes**.

```
<select id="check_propers_interval" name="check_propers_interval" class="form-control input-sm">
     <option value="daily">24 hours</option>
     <option value="4h">4 hours</option>
     <option value="90m">90 mins</option>
     <option value="45m">45 mins</option>
     <option value="15m">24 hours</option>
</select>
```

**Solution:**
I think the solutions are in config_search.mako files.

```
checkPropersIntervalLabels: [
     { text: '24 hours', value: 'daily' },
     { text: '4 hours', value: '4h' },
     { text: '90 mins', value: '90m' },
     { text: '45 mins', value: '45m' },
     { text: '24 hours', value: '15m' }
```

**Additional suggestion:**
I'd like to suggest adding the 30 minutes option as well, which seems a balanced choice to me.
`{ text: '30 mins', value: '30m' }`

**Medusa:**
- OS: Synology DSM 6.2.1-23824 Update 2, DS918+
- Branch: master
- Commit: 54da0c77d705a23f1ce67945ba4af3e1b978dcfc
- Version: v0.2.13

**Comment by bolhaskutya** [comment]
Nice. Thank you @medariox !

**Comment by medariox** [comment]
Closing as fixed.

**Comment by bolhaskutya** [comment]
Just updated. It working great. Thanks for the fix. Happy holidays.
