### ISSUE TITLE
Custom Anime Post Processing not working

### ISSUE THREAD

**Issue by Masterditto** [pymedusa/Medusa#5893]
**Describe the bug**
I have Post Processing "Custom Anime" set to enabled with this "code":
%SN - Season %0S/[%RG] %SN - S%0SE%0E - [A%AB] - %SQN
Show Name - Season 02/[RLSGROUP] Show Name - S02E03 - [A003] - 720p HDTV x264.ext

But the Post Processing names my anime like this:
[HorribleSubs] Fairy Tail Final Season - 288 [720p]
Which means it doesn't change the filename at all? - This fucks up Plex totally since it really needs the SxxExx.

**To Reproduce**
1. Add an anime to the show list
2. Set Post Processing, custom anime to enabled and change the "code"
3. Search an anime episode to download
4. Wait for Post Processing to happend
5. It does not change the filename at all with "custom anime" Post Processing

**Expected behavior**
To change the filename as being told in the "Post Processing" config/settings.

**Medusa (please complete the following information):**
 - OS: Linux (Synology)
 - Branch: master
 - Commit: ?

**Logs:**
[Logs.zip](https://github.com/pymedusa/Medusa/files/2683444/Logs.zip)

**Comment by medariox** [comment]
Do you have `Add Absolute Number` checked?

![img](https://snapr.pw/i/13d759734c.png)

**Comment by Masterditto** [comment]
Nope, but to be honest I don't remember if I changed that setting before creating this ticket. Let me double check next time "Post Processing" happends when it's set to "No"

![1](https://user-images.githubusercontent.com/18222939/50101927-1f606500-0224-11e9-99a9-49afe853fc0f.jpg)

**Comment by Masterditto** [comment]
Ok actually got an episode now. It was named: "[HorribleSubs] Tensei Shitara Slime Datta Ken - 12 [720p].mkv"

**Comment by medariox** [comment]
Is that with `Add Absolute Number` checked?

**Comment by Masterditto** [comment]
unchecked like the picture. figured I could add it myself with that code?

is that incorrect way of using it?

**Comment by medariox** [comment]
If you want both normal episode numbers and absolute episode numbers, you need to have `Add Absolute Number` checked.

**Comment by Masterditto** [comment]
Even with the custom code added? - Cuz when I do enable that (picture above) it adds it a place I dont want it too.
As stated it has to be inside a [ ] otherwise plex fucks it up?

And the hole custom code does nothing, it just copy > paste episode in the folder without changing the name at all (like stated in the issue)

Am I misunderstanding something? :O

**Comment by Alien003** [comment]
I have my animes working fine with plex without the SxxExx format.
I think It's because I have the metadata options enabled (had to turned them on because my previous media server had the same requirement to consider them a "serie")

These are my metadata settings:
![image](https://user-images.githubusercontent.com/17534730/50121595-26ea3300-0251-11e9-8bee-c1bd1604cbeb.png)

any my post processing for anime:
[%RG] %SN - %0E [%QN]

**Comment by Masterditto** [comment]
Regardless of it working like that Alien003, the "code" I told it to use does not work at all. Which I asume is a bug?

**Comment by Alien003** [comment]
I was only sharing the "workaround" that was working for me.
My setup was migrated from SickRage so I never tested the anime formats
here. That said, i had a lot of problems trying to tweak the formats there
as well since they mostly didn't work at all.

Didn't really try it here, but to me it is unacceptable to be forced use a
SxxExx format on shows where it does not make any sense.

On Dec 18, 2018 05:51, "Masterditto" <notifications@github.com> wrote:

Regardless of it working like that Alien003, the "code" I told it to use
does not work at all. Which I asume is a bug?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/pymedusa/Medusa/issues/5893#issuecomment-448105092>,
or mute
the thread

**Comment by medariox** [comment]
@Alien003 
You are not forced to use SxxExx at all. The issue here is that @Masterditto wants to have both normal **and** custom episode numbering added in a **custom** way to a single episode. It's something very specific and actually more like a feature request.

**Comment by Masterditto** [comment]
I thank you Alien003 for sharing!

@medariox How can it be Feature request? i'm using the build in legend code, but its not working? Am I missing something here?

**Comment by medariox** [comment]
`
Moving file from C:\[KaiDubs] Attack on Colossus S03E10 [1080p] [English Dub] [CC] [ASrip] [3591311C].mkv to E:\Videos\TV Shows\Attack on Colossus\Attack on Colossus - Season 03\[KaiDubs] Attack on Colossus - S03E10 - [A047] - 1080p HDTV.mkv
`

It works just fine for me with the settings you posted. Run the post-processing on the file and post only the relevant logs.

**Comment by Alien003** [comment]
Sorry, i understand that from medusa configurations point of view. I agree
that it is a bug/feature request.

I was talking about being forced on that format by he media servers when
there is no metadata files.

**Comment by Masterditto** [comment]
Ok I added a new Anime for testing purpose "Conception"
![1](https://user-images.githubusercontent.com/18222939/50201337-f215d300-0359-11e9-979e-246eaa7e5762.png)

Manually downloaded Episode 1, had rest set to SKIPPED, clicked to download episode 2 - Which was found and downloaded. But not renamed.

Here is my Logs:
[Logs.zip](https://github.com/pymedusa/Medusa/files/2693423/Logs.zip)

**Comment by medariox** [comment]
This is what I get with that naming pattern and `No Absolute Number` selected:
`
Copying file from C:\Users\sed\[HorribleSubs] Conception - 02 [1080p].mkv to E:\Videos\TV Shows\Conception\Conception - Season 01\[HorribleSubs] Conception - S01E02 - [A002] - 1080p HDTV.mkv
`

Don't know what you are doing wrong honestly, not sure how to help you.

These are my settings:
![img](https://snapr.pw/i/bd205c7946.png)

**Comment by Masterditto** [comment]
Could I somehow give you my Installation/data to look at? - Not sure what to do here :(
