### ISSUE TITLE
Why only 1 show with the api?

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#5898]
Hello,

I was wondering why I am having problems when displaying all shows in medusa through the api:

![image](https://user-images.githubusercontent.com/3207791/50233001-bce99f00-03b2-11e9-8fd4-2aa34819c851.png)

URL: /api/v1/*****/?cmd=shows&sort=name&paused=0

I was expecting all shows to appear, but only 1 is showing as you can see. Any idea?

Kind regards,

Pedro

**Comment by p0psicles** [comment]
You can use the apiv2 for that.
https://github.com/pymedusa/Medusa/blob/master/dredd/api-description.yml
https://github.com/pymedusa/Medusa/wiki/API-v2

**Comment by elpedriyo** [comment]
Hello,

Thanks for the information, the only thing I do not understand is why I am only able to have 1000 series in medusa?

![image](https://user-images.githubusercontent.com/3207791/50308270-0a413b80-049b-11e9-9e84-a9b69a0fbf1c.png)

Kind regards

**Comment by p0psicles** [comment]
I think thats where we needed to implement pagination. But the limit has already been bumped to 10000.
