### ISSUE TITLE
Pip install -r requirements.txt fails on subliminal

### ISSUE THREAD

**Issue by sammcj** [pymedusa/Medusa#5913]
Did a git pull last night and now medusa won’t start, I thought perhaps the python libs needed updating but it seems they’re broken:

```
fatal: reference is not a tree: 78687f45d23b1bc47fae0a5493be0198dc1fd5b5
Command "git checkout -q 78687f45d23b1bc47fae0a5493be0198dc1fd5b5" failed with error code 128 in /tmp/pip-install-j2oscnwc/subliminal
```

**Comment by sammcj** [comment]
Me being a cabbage - please ignore

**Comment by p0psicles** [comment]
The pip installation is also fixed BTW in develop. But you don't need it to run medusa
