### ISSUE TITLE
Can't change web_host setting in config.ini

### ISSUE THREAD

**Issue by mdnn** [pymedusa/Medusa#5916]
**Describe**
I would like change web_host value in config.ini to web_host = 127.0.0.1.
When I try it and restart medusa service, my change  is modified to web_host = 0.0.0.0

Thanks !

**Comment by medariox** [comment]
Medusa needs to be shut down before changing the `config.ini`.

**Comment by mdnn** [comment]
Thank you, It's worked.
Sorry, I thought I did.
