### ISSUE TITLE
'Improper' click behavior of the topright menu item 

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#5923]
This is a followup/regression to issue #4127 ... 
With the latest dev branch merged to /feature/add-daily-search-start-search-offset - 
Single/double click on the top rightmost menu (noname) - now strangely opens the 'Scheduler' page. 

I suggest to fix that and to:
1. Open the logger sub-menu with one click
2. Open the error logger sub-menu with double-click, or the warning log if only warnings, or the regular log if not warning or errors.

Thanks

**Comment by medariox** [comment]
It opens the Status page for me.

**Comment by rafi-d** [comment]
@medariox 
Sorry, my bad, you are right. Is it the intended behavior? If so, unless you think logs are more useful than status, I guess we can close this.

**Comment by medariox** [comment]
Yeah, it's supposed to be like that. Users shouldn't normally care too much about logs.
