### ISSUE TITLE
There is an update available: please pull the latest docker image, and rebuild your container to update

### ISSUE THREAD

**Issue by Miicker** [pymedusa/Medusa#5925]
Whenever I open Medusa I get the message:
There is an update available: please pull the latest docker image, and rebuild your container to update

A few weeks back I got the same message, back then I removed Medusa from Docker en rebuilt it (which is quit some work), now I get the same message. It's annoying that I have to do this, but I went along and did it, but I still got the same message, I tried three times, but still this message is showing, normally auto update just works fine.

I use Medusa on a Synology and run it within Docker (I use the image from linuxserver: https://hub.docker.com/r/linuxserver/medusa/ )

How can I solve this?
Branch: master 
Commit: 54da0c77d705a23f1ce67945ba4af3e1b978dcfc 
Version: v0.2.13 
Database: 44.12
Python Version: 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
OS: Linux-3.10.102-x86_64-with

**Comment by kimpenhaus** [comment]
I would recommend using [watchtower](https://github.com/v2tec/watchtower) for automatic container updates. I am using it with option [label-enable](https://hub.docker.com/r/v2tec/watchtower/#options) to flag only those containers which should be autoupdated.

**Comment by a10kiloham** [comment]
the container is being updated, the app is just currently not detecting that @kimpenhaus I can assure you many of us already use watchtower.

**Comment by pancho-villa** [comment]
Where do I find the current hash? I found the entry in config.ini, but I don't know what value to put there.

**Comment by medariox** [comment]
Go to https://github.com/pymedusa/Medusa/commits/master
![img](https://snapr.pw/i/a94d663533.png)
Click the button on the last (top) commit.

**Comment by ztaale** [comment]
Im also having this issue, is it a bug with docker?

**Comment by medariox** [comment]
Update to the new release and it should be fixed.
