### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: NPO 1

### ISSUE THREAD

**Issue by Miicker** [pymedusa/Medusa#5927]
### INFO
**Python Version**: `2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]`
**Operating System**: `Linux-3.10.102-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-12-28 23:53:55 ERROR    Thread_0 :: [918cfe7] Missing time zone for network: NPO 1
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/c5e89ecb1d9ad7d877ab1a316111bc89cbd645c4
