### ISSUE TITLE
Status page won't open

### ISSUE THREAD

**Issue by neojoe666** [pymedusa/Medusa#5930]
Click on the link to go to the server status
A blank page appears

**Medusa:**
OS: Synology - Linux-3.2.40-armv7l-with-glibc2.4
Branch: master
Commit: 918cfe7

**Logs:**
<details>

```
2018-12-29 15:56:19 ERROR    Thread_1 :: [918cfe7] Exception generated: 'ascii' codec can't encode character u'\xe9' in position 16: ordinal not in range(128)
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/base.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/home/handler.py", line 663, in status
    root_dir[subject] = helpers.get_disk_space_usage(subject)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/helpers/__init__.py", line 1451, in get_disk_space_usage
    st = os.statvfs(disk_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 16: ordinal not in range(128)
```
</details>

**Comment by medariox** [comment]
Gear > Help & Info
What's your locale?

**Comment by neojoe666** [comment]
Where can I see my locale ?

**Comment by medariox** [comment]
> Gear > Help & Info

**Comment by neojoe666** [comment]
Unknown.Unknown
--

**Comment by medariox** [comment]
You need to set your locale. Didn't you get a warning on startup about that?

**Comment by neojoe666** [comment]
No, I restart it everyday and haven't seen any warning.
Where can I set it ?

**Comment by neojoe666** [comment]
I ran locale -a on my synology and here is what it returns : 
C
cs_CZ.utf8
da_DK.utf8
de_DE.utf8
en_US.utf8
es_ES.utf8
fr_FR.utf8
hu_HU.utf8
it_IT.utf8
ja_JP.utf8
ko_KR.utf8
nb_NO.utf8
nl_NL.utf8
pl_PL.utf8
POSIX
pt_BR.utf8
pt_PT.utf8
ru_RU.utf8
sv_SE.utf8
tr_TR.utf8
zh_CN.utf8
zh_TW.utf8

**Comment by medariox** [comment]
What's your Python version?

**Comment by neojoe666** [comment]
2.7.14

**Comment by medariox** [comment]
Your Python install is unable to read your system locale. I don't know why, it could be a permission issue.

**Comment by labrys** [comment]
@neojoe666 what's the result of the following:
`python -c "import locale; print(locale.getdefaultlocale()); print(locale.setlocale(locale.LC_ALL, ''))"`

**Comment by neojoe666** [comment]
('en_US', 'UTF-8')
en_US.utf8

**Comment by neojoe666** [comment]
Any idea on what I should do?

**Comment by medariox** [comment]
```
vi /etc/profile
 # add:
 LANG=de_DE.UTF-8
 LC_ALL=de_DE.UTF-8
 export LANG LC_ALL
reboot
```
Did you do this?

**Comment by neojoe666** [comment]
I already have these in my /etc/profile:
export LC_ALL=en_US.utf8
export LANG=en_US.utf8

**Comment by medariox** [comment]
Please run:
`python -c "import locale; print(locale.CODESET); print(locale.nl_langinfo(locale.CODESET))"`

**Comment by neojoe666** [comment]
It returned this:
14
ANSI_X3.4-1968

**Comment by medariox** [comment]
What about `python -c "import sys; print(sys.getfilesystemencoding())"`?

**Comment by neojoe666** [comment]
UTF-8

**Comment by medariox** [comment]
How do you start Medusa? That means I need to know the exact script that is running `python start.py` or `python SickBeard.py` on your system.

**Comment by neojoe666** [comment]
It's installed on a Synology NAS so I don't know how it is executed. Where can I see it?

**Comment by medariox** [comment]
Not sure. How did you install it? Which package did you use? Which guide did you follow?

**Comment by neojoe666** [comment]
I installed the Sickbeard custom package by giving it the git adress of medusa : https://github.com/pymedusa/Medusa/wiki/Switching-your-Synology's-Medusa-to-the-new-repository

**Comment by medariox** [comment]
Please run `/usr/local/python -c "import sys; print(sys.getfilesystemencoding())"`

**Comment by neojoe666** [comment]
How can I execute the command you sent me?

**Comment by neojoe666** [comment]
I don't have python in /usr/local/bin
Yes, I have sudo

**Comment by p0psicles** [comment]
You could try to run the python commands with sudo -u "username" python...

**Comment by neojoe666** [comment]
I already ran this (see above):
python -c "import sys; print(sys.getfilesystemencoding())

and it returns:
UTF-8

I don't know what it changes to add the path in front of python but it doesn't work as I don't know where it is located

**Comment by neojoe666** [comment]
is it different to run python with the path?

**Comment by p0psicles** [comment]
Honestly I don't think so. But running it with the same user as you run Medusa could make a difference.

**Comment by neojoe666** [comment]
I found it:
sudo -u "sc-sickbeard-custom" /volume1/@appstore/sickbeard-custom/env/bin/python -c "import sys; print(sys.getfilesystemencoding())"

and it returns:
utf-8

**Comment by labrys** [comment]
@neojoe666 to be honest it looks to me like its set correctly...

**Comment by neojoe666** [comment]
@labrys but I still have this unknown.unknown in the locale info in Medusa...

**Comment by labrys** [comment]
@neojoe666 I'd be willing to bet its something in the medusa code...  I don't run medusa any more so I wouldn't be able to tell you if any changes are causing it.

**Comment by neojoe666** [comment]
it still worked in october or even beginning of november

**Comment by p0psicles** [comment]
Not much changed in that regard. Yeah maybe the python3 support

**Comment by neojoe666** [comment]
Any idea where this permission issue comes from?

**Comment by medariox** [comment]
It's definitely not a Medusa related issue, otherwise we would have many more reports by Synology users. The user you are running Medusa with is unable to access the locale information for some reason. Maybe you have updated your OS and some privileges were change/reset. I know nothing about Synology, you will probably have more luck asking on their forums.

**Comment by neojoe666** [comment]
which permissions are required? As when I execute the different command you told me above with the user sc-sickbeard-custom, it returns the right values

**Comment by neojoe666** [comment]
See ticket I opened on the synology community, it seems the problem comes from Medusa.
My user which runs Medusa retrieves all the locale information using the different command lines

**Comment by medariox** [comment]
Medusa knows nothing about the user. YOU need to start Medusa with the correct user.

**Comment by neojoe666** [comment]
I don't understand.
I run it with the right user and the command lines with this same user returns the right information.
Why did you close this issue? It's not solved... I'm asking for help....

**Comment by medariox** [comment]
You said running with root solves the issue so this is not a Medusa specific problem, but instead something you need to fix on your system. No matter what people think they know, this is not a problem caused by our code. As I already suggested, ask Synology for support, we can't help you.

**Comment by neojoe666** [comment]
but I need to know the permissions I need to set on the user and that depends on the code Medusa uses to get the locale information

**Comment by medariox** [comment]
No, not at all.

**Comment by neojoe666** [comment]
I really don't understand.
There are no permissions to set on the user I use to run Medusa?

**Comment by neojoe666** [comment]
@labrys you were saying it might be in the Medusa code. Do you see anything that could be wrong according to the tests I ran?

@p0psicles is it possible for you to take a look at it regarding the python3 support you mentioned? Do you have access to the code?

**Comment by labrys** [comment]
@neojoe666 Are you able to edit the code?  If so a couple of changes can provide more information to pinpoint where the issue is.

First stop Medusa.  Then inn `SickBeard.py` and/or `Start.py` (whichever is used to launch Medusa) add the following lines immediately after the `from __future__ import ...`
```python
import locale
with open('encoding.txt', 'w') as fout:
     fout.write(str(locale.getdefaultlocale()))
     fout.write(locale.setlocale(locale.LC_ALL, ''))
```
Then start medusa as you would normally.  This will write a file named 'encoding.txt' before Medusa does any initialization such as reloading the `sys` module and setting the default encoding.

If the contents are the same as when you run the test manually, then it is likely an issue with Medusa.  If it is not, then the issue is likely something with your environment (e.g. permissions, which python interpreter is running the code, etc.)

Depending on the results of this test, you can then try a post-initialization test as well.

**Comment by neojoe666** [comment]
@labrys thanks for your help but I'm getting an error:

Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py", line 7, in <module>
    with open('encoding.txt', 'w') as fout:
IOError: [Errno 13] Permission denied: u'encoding.txt'

**Comment by neojoe666** [comment]
@labrys I got the file and it returns (None, None)

So how can it be that it doesn't get the right values? Which permissions are needed?

**Comment by labrys** [comment]
@neojoe666 Replace the above for the following:
```python
import getpass
with open('encoding.txt', 'w') as fout:
     fout.write(sys.executable)
     fout.write(getpass.getuser())
```
This will tell you which python executable medusa is running and which user it is running as.

**Comment by neojoe666** [comment]
@labrys I had to write it below "import sys" as you used sys
it wrote this:
/volume1/@appstore/sickbeard-custom/env/bin/pythonsc-sickbeard-custom

**Comment by labrys** [comment]
Ok try the following:

```
sudo su sc-sickbeard-custom
/volume1/@appstore/sickbeard-custom/env/bin/python -c "import locale; print(locale.getdefaultlocale()); print(locale.setlocale(locale.LC_ALL, ''))"
```

**Comment by neojoe666** [comment]
I already did these tests above
sudo -u sc-sickbeard-custom /volume1/@appstore/sickbeard-custom/env/bin/python -c "import locale; print(locale.getdefaultlocale()); print(locale.setlocale(locale.LC_ALL, ''))"

and it returns
('en_US', 'UTF-8')
en_US.utf8

**Comment by neojoe666** [comment]
same error

**Comment by labrys** [comment]
Ok try `sudo -u sc-sickbeard-custom cat /etc/profile`

**Comment by neojoe666** [comment]
it opens the /etc/profile:


#/etc/profile: system-wide .profile file for ash.

umask 022

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
export PATH

PGDATA=/var/services/pgsql
export PGDATA

TERMINFO=/usr/share/terminfo
export TERMINFO

TERM=${TERM:-cons25}
export TERM

PAGER=more
export PAGER

export LC_ALL=en_US.utf8
export LANG=en_US.utf8

PS1="`hostname`> "

alias dir="ls -al"
alias ll="ls -la"

ulimit -c unlimited

if [ -f /etc.defaults/.bashrc_profile ]; then
        source /etc.defaults/.bashrc_profile

**Comment by labrys** [comment]
Hmmm... unfortunately I dont currently have access to my linux system to do any local tests, but it definitely points to an environment issue.  Possibly a /etc/profile.d or .bashrc_profile with conflicting/incorrect settings?

**Comment by neojoe666** [comment]
Thanls for your help. Let me know if you find anything or if you need me to run any other tests.

**Comment by labrys** [comment]
Try one last thing:

`sudo -u sc-sickbeard-custom echo $LC_ALL`

**Comment by neojoe666** [comment]
it returns:
en_US.utf8
