### ISSUE TITLE
Post Processing fails to run

### ISSUE THREAD

**Issue by rbhamilton** [pymedusa/Medusa#5942]
Post Processing doesn't run at all.  No errors or warnings in the log, no mention of any attempt to post-process at all.  It's set to run every 10 minutes.  Paths are fine.  It used to work just fine but this problem started after the last update.  Manual post-processing still works fine - no errors.  Any ideas?

**Comment by rbhamilton** [comment]
I have restarted multiple times.  Yesterday I uninstalled and reinstalled.  There are no relevant debug logs because as I said, nothing shows up in the log.  It does all the stuff it's supposed to do,  Snatches files, scans, etc.  But it never starts post-processing on it's own.

**Comment by medariox** [comment]
What's your OS? Python version? How are you running Medusa? Are you sure the auto post-processor is active?
Tools > Server Status:
![IMG](https://snapr.pw/i/968b352066.png)
Is Post Process alive?
Please understand that we need as much information as possible to help you out.

**Comment by rbhamilton** [comment]
Looks like the reinstall has solved it.  Post Processing shows in the logs now.  Thanks for the tip on the server status.  That's handy and I'll keep an eye on it.

**Comment by medariox** [comment]
Glad to hear!
