### ISSUE TITLE
Postprocessing full season

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#5943]
Hello,

I downloaded this full season:

![image](https://user-images.githubusercontent.com/3207791/50561349-1bdfda00-0d0a-11e9-850f-197bec00ab08.png)

With this files inside the folder:

![image](https://user-images.githubusercontent.com/3207791/50561355-2b5f2300-0d0a-11e9-8150-3203a2c3cdba.png)

As you can see they came inside a rar.

After the post processing took place, the were uncompressed as you can see on that image, but when being renamed and clasified into its show folder, it came into this:

![image](https://user-images.githubusercontent.com/3207791/50561373-5184c300-0d0a-11e9-917b-d5723b37f402.png)

Seems it took 1 chapter and renamed it like that.
Any workarround or fix for that kind of post processing?

Kind regards

**Comment by medariox** [comment]
Report it to https://github.com/guessit-io/guessit/issues to have it fixed.
