### ISSUE TITLE
Unable to remove a show

### ISSUE THREAD

**Issue by roaminglt** [pymedusa/Medusa#5955]
**Describe the bug**
I have a show I want to remove and I don't seem to be able to.

**To Reproduce**
1. Visit show page: home/displayShow?indexername=tmdb&seriesid=<showid number here>
2. Click on 'remove'
3. I do not tick the box to delete files (no eps downloaded, so don't need it to delete anything, and I am happy to delete folder by hand)
4. I click 'yes'
5. I wait while the page is loading.
6. Show listing loads, show not removed.

**Expected behavior**
I expect the show to be gone.

**Screenshots**
n/a

**Medusa (please complete the following information):**
Medusa Info: 
Branch:                  master
Commit:                918cfe7ce01808499585ffe6c1356fd5ed369f76
Version:                 Unknown
Database:              44.12
Python Version:     2.7.9 (default, Sep 26 2018, 00:05:48)  [GCC 4.9.2]
SSL Version:           OpenSSL 1.0.1t  3 May 2016
OS:                        Linux-4.4.140.armada.1-armv7l-with-debian-8.11
Locale:                   en_US.UTF-8

**Logs:**

Log data below corresponds to two attempts to delete the show.
<details>

```
2019-01-03 16:14:32 INFO     SHOWQUEUE-REMOVE-SHOW :: [918cfe7] 82491: Removing Star Trek: Short Treks
2019-01-03 15:41:33 INFO     SHOWQUEUE-REMOVE-SHOW :: [918cfe7] 82491: Removing Star Trek: Short Treks
```
</details>

**Additional context**
n/a

**Comment by medariox** [comment]
Does it work if you tick the box to remove the files?

**Comment by roaminglt** [comment]
Ticking the box to remove files also hasn't worked in the past. I've tried it again anyway as I hadn't tried this way on the version I'm currently running. I can confirm it doesn't work. It doesn't remove from medusa and also doesn't delete files.

Log just says:
2019-01-07 12:32:54 INFO     SHOWQUEUE-REMOVE-SHOW :: [918cfe7] 82491: Removing Star Trek: Short Treks

I should note that the show is paused, not sure if this affects it. So I have unpaused and re-attempted deletion. No change to behaviour, still won't delete.

**Comment by medariox** [comment]
What browser are you using? Tried with a different one?

**Comment by uoliaso** [comment]
I've tried (without success):

- Firefox - 64.0.2 (64-bit)
- Chrome - 73.0.3669.0 (Official Build) canary (64-bit)

I don't think it is a browser issue as the instruction goes through (as shown in the log) and the page works and loads back into the front page show list.

I've checked the /home/status/ page, just in case I could see a pending show delete in a queue (not sure if it would even show up here) but there's nothing that shows up.

Is there a way (I'll need a step-by-step) to manually check if the DB entry for the show is messed up?

many thanks

**Comment by Fietspomp86** [comment]
Same here, also trying to remove a show, exactly like same issue as above.
Log just says 
2019-05-08 19:58:37 INFO     SHOWQUEUE-REMOVE-SHOW :: [f46bfac] 77459: Removing The Passage
Nothing happening. Tried with different shows.

Tried Chrome and Edge browsers.

**Comment by sharkykh** [comment]
If any of you could enable the debug + DB debug options in the general config (advanced tab), then try to remove the shows, and get the [DB logs](https://user-images.githubusercontent.com/10238474/58944671-fe1c1280-878a-11e9-91f6-b3e7884dafaf.png), maybe it will help debug this.

**Comment by sharkykh** [comment]
In any case, the normal debug log should log:
`Transaction with X queries executed` where X is a number, and it does not do that, though I still don't understand why.

@roaminglt / @Fietspomp86 
Did you both enable debug logging?

**Comment by Fietspomp86** [comment]
Haven't had the time yet, will try later this afternoon.

**Comment by roaminglt** [comment]
I'm on a newer version than I was on, and at some point between now and then I successfully removed the show. I should have updated this ticket then so I could be more specific about the version - sorry!
