### ISSUE TITLE
Jackett is not working

### ISSUE THREAD

**Issue by ngosang** [pymedusa/Medusa#5965]
Jackett is not working.

1) I can't set up a new Jackett engine properly. I'm following => https://github.com/pymedusa/Medusa/wiki/Using-Jackett-with-Medusa
I can't configure the Categories. There is something weird in the categories buttons.
![imagen](https://user-images.githubusercontent.com/10577978/50744315-7acdb380-1222-11e9-9c06-8dd04eab1479.png)

2) When I perform a manual search I think Medusa is not calling Jackett. I can't see anything in Medusa logs, neither in Jackett logs. The Jackett URL and token is correct.

3) I added 2 Jackett engines. I select one and click delete, after that I select the other and click delete. I press Save. Only 1 is deleted, the other is still there...

**Medusa (please complete the following information):**
 - OS: Linux
 - Branch: master (updated)

**Comment by Yellow1144** [comment]
I had a similar problem. After you added the Jackett Provider in the Configure Jackett Provider tab, you then need to go back to the Provider Priority tab and enable them and set their priority. It is not clear from your post if you have done this.

Jacket is working perfectly for me.

**Comment by medariox** [comment]
Also make sure to enable all the search methods you want to use for the provider.

**Comment by ngosang** [comment]
I didn't know I have to enable the plugin in the priority list it's working. Please update the Wiki doc. 😄 

There are still some issues:
1) Manual search not using Jackett plugins. I checked the logs and nothing.
2) Configure "btbit" en Jackett and try to add in Medusa. There is something weid with the categories and categories buttons.
3) I added 2 Jackett engines. I select one and click delete, after that I select the other and click delete. I press Save. Only 1 is deleted, the other is still there...

**Comment by medariox** [comment]
1. You need to enable it in the individual provider settings:
![img](https://snapr.pw/i/30530fcbd7.png)

**Comment by ngosang** [comment]
@medariox I found the issue. Steps to replicate:
1. Configure `btbit` in Jackett
![imagen](https://user-images.githubusercontent.com/10577978/50995893-c3d28000-1520-11e9-9815-8ee5308387d5.png)

2. Add in Medusa. The categories don't appear, so the searches don't work.
![imagen](https://user-images.githubusercontent.com/10577978/50995879-b9b08180-1520-11e9-8282-4b54fb8c45d1.png)

In other trackers the Jackett plugin works well, maybe this tracker has too much categories or something like that...

**Comment by ngosang** [comment]
@medariox I understand now. Thank you for your help!
You can close this issue, but I think it's better to show all categories so the user is more capable. There are more trackers with only 1 generic category called video or movies. e.g. https://www.digbt.org/search/westworld%20s01e01/?c=video&s=time&u=y

**Comment by Whisper40** [comment]
Hello, i re open this issue because medusa is not using any of my jackett providers ( no problem with radarr & sonarr  with jackett too)
medusa is not able to find any series, same problem for all series.
No one filter is blocking the search ( no one has been configured to block )

Thanks for help
![image](https://user-images.githubusercontent.com/30440458/111701462-2d562380-883b-11eb-80aa-600d9dcdaf9a.png)
![image](https://user-images.githubusercontent.com/30440458/111701528-465ed480-883b-11eb-9b54-ef35df4e3ac8.png)

My debug logs : 
```
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Beginning backlog search for: Les 100
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Updating exception_cache and exception_season_cache
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Finished processing 3425 scene exceptions.
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Building internal name cache for Les 100
2021-03-18 21:39:58 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Internal name cache for les 100 set to: les 100
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Using backlog search providers
2021-03-18 21:39:58 WARNING  FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] No NZB/Torrent providers found or enabled in the application config for backlog searches. Please check your settings
2021-03-18 21:39:58 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Combining single and multi-episode results
2021-03-18 21:39:58 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] No results to sort.
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] No needed episodes found during backlog search for: Les 100
```
