### ISSUE TITLE
UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.

### ISSUE THREAD

**Issue by medariox** [pymedusa/Medusa#5968]
```
Medusa\ext2\bs4\element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
```

Only happening with Python 2.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5983

**Comment by amir1991115** [comment]
I want a solution to this Python 2.7 problem
/usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selector
