### ISSUE TITLE
[Docker] Re-scan files -> Quality = Unknown; knowit does not output video quality

### ISSUE THREAD

**Issue by GreenTeaBalls** [pymedusa/Medusa#5969]
**Describe the bug**
I moved the directory for a show to another file path. After updating the path in the show's settings and triggering a re-scan of files all existing files are shown as "Downloaded" but quality is "Unknown".

Further tinkering:
- start bash shell in the docker container
- `pip install knowit` to install knowit for current user
- running knowit on a media file in question does produce very limited output which does not include video quality
```
root@3ef9d444a2b7:/$ knowit some_video_file.mkv 
For: some_video_file.mkv
Knowit 0.2.4 found: 
{
    "path": "some_video_file.mkv", 
    "container": "mkv", 
    "size": 959003545, 
    "provider": "libmediainfo.so.0"
}
```
- running mediainfo cli application on the same file produces detailed output which includes video quality
```
root@3ef9d444a2b7:/$ mediainfo some_video_file.mkv
General
Unique ID                                : 251270548726810378748812581138875344681 (0xBD08F288625A65B0B2A7A09BC048E729)
Complete name                            : some_video_file.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 915 MiB
Duration                                 : 24 min 12 s
Overall bit rate                         : 5 281 kb/s
Encoded date                             : UTC 2014-01-15 04:28:01
Writing application                      : mkvmerge v5.8.0 ('No Sleep / Pillow') built on Sep  2 2012 15:37:04
Writing library                          : libebml v1.2.3 + libmatroska v1.3.0

Video
ID                                       : 2
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 24 min 12 s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 1
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : A_AAC-2
Duration                                 : 24 min 12 s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Language                                 : English
Default                                  : No
Forced                                   : No
```
**To Reproduce**
1. Rename folder of existing show
2. Change folder path in show settings to reflect new path
3. On show page trigger re-scan of files
4. Files show up as "Downloaded" with quality "Unknown"

**Expected behavior**
Display the actual quality of the existing files.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: [docker]
 - Branch: [master]
 - Commit: [918cfe7ce01808499585ffe6c1356fd5ed369f76]
 - libmediainfo: 18.05-r0
 - knowit: 0.2.4

**Possibly related**
https://github.com/ratoaq2/knowit/issues/16
https://github.com/pymedusa/Medusa/issues/5878

**Comment by iernie** [comment]
I am having the same problem. `knowit` was not installed in a fresh docker container using linuxserver/medusa and all files are getting marked as quality unknown when added.

**Comment by medariox** [comment]
Please try the latest knowit version from GitHub and see if that fixes it for you: https://github.com/ratoaq2/knowit

**Comment by iernie** [comment]
According to `knowit --version` the pip installed version is the latest version available on github
```
root@404a37d60d63:/# knowit --version
+-------------------------------------------------------+
|                     KnowIt 0.2.4                      |
+-------------------------------------------------------+
|                     mediainfo 3.1                     |
|                   libmediainfo.so.0                   |
|                                                       |
|                 ffmpeg not available                  |
|                                                       |
|                     enzyme 0.4.1                      |
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|     https://github.com/ratoaq2/knowit/issues.         |
+-------------------------------------------------------+
```

I've tried to run it on mp4, avi og mkv files, all results are the same

```
Knowit 0.2.4 found:
{
    "path": "/path/to/file.mp4|avi|mkv",
    "container": "mp4|avi|mkv",
    "size": xxxx,
    "provider": "libmediainfo.so.0"
}
```

**Comment by medariox** [comment]
@iernie 
I mean the master branch: https://github.com/ratoaq2/knowit/archive/master.zip

**Comment by iernie** [comment]
@medariox Ahh sorry. With the `0.3.0-dev` version, `knowit` is now giving me more information when I execute it manually inside the container now. Sadly, in Medusa everything still gets marked as quality Unknown. Even after a full refresh, delete and re-add and a restart of Medusa. Maybe `knowit` was not the real problem then?

**Comment by medariox** [comment]
Did you replace the inbuilt `knowit` version? It's located in `Medusa/ext/knowit`.

**Comment by iernie** [comment]
Yes, that seems to fix it! I had to remove the shows and re-add them, but now it picks up on quality. Any idea if this fix can find its way into the docker image?

**Comment by thelamer** [comment]
@medariox Hello from Linuxserver.io are there plans to fix this upstream? I am not super comfortable pulling this extension from knowit's git head to replace the embedded extensions in Medusa. 

Is this a case of you are waiting for them to push another release or can a working version be integrated into your codebase ?

**Comment by p0psicles** [comment]
Yes we waiting for that

**Comment by medariox** [comment]
Closing as fixed since a few versions.
