### ISSUE TITLE
Manual subtitle search is not working

### ISSUE THREAD

**Issue by ngosang** [pymedusa/Medusa#5979]
**To Reproduce**
I click in download subtitles. In the popup I click manual. The spinner spins forever...
![imagen](https://user-images.githubusercontent.com/10577978/50996344-e6b16400-1521-11e9-81f5-a67d13419043.png)

**Medusa (please complete the following information):**
 - OS: Linux / Python2.7
 - Branch: master
 - Commit: 918cfe7  v0.2.14

**Comment by medariox** [comment]
Closing as directly related to https://github.com/pymedusa/Medusa/issues/5980
