### ISSUE TITLE
Repeated post processing runs with hard linking mode generate warnings

### ISSUE THREAD

**Issue by JohnMaguire** [pymedusa/Medusa#6026]
**Describe the bug**
Every time the post-processor runs, it generates a ton of warnings due to the fact that files already exist in the TV Shows directory (the folder downloads are hardlinked into.)

**To Reproduce**
Set the mode to "Hard linking" and run the post-processor a couple times.

**Expected behavior**
Episodes are hard linked on the first run, and ignored on subsequent runs.

**Medusa (please complete the following information):**
 - OS: Arch Linux-4.19.14-1-lts-x86_64-with
 - Branch: master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76

**Logs:**
<details>

```
2019-01-16 18:30:19 WARNING  POSTPROCESSOR :: [918cfe7] /downloads/Downloads/completed/30.Rock.S04.1080p.AMZN.WEBRip.DD5.1.x264-NTb/30.Rock.S04E16.Floyd.1080p.AMZN.WEBRip.DD5.1.x264-NTb.mkv: Processing failed: File exists. Marking it unsafe to replace. Reason: New quality is equal than current Preferred. Ignoring quality
2019-01-16 18:30:19 WARNING  POSTPROCESSOR :: [918cfe7] /downloads/Downloads/completed/Portlandia.S03.1080p.WEB-DL.AAC2.0.H.264-BTN/Portlandia S03E11 Blackout 1080p WEB-DL AAC2.0 H.264 - HoodBag.mkv: Processing failed: File exists. Marking it unsafe to replace. Reason: New quality is lower than current Preferred. Ignoring quality
```
</details>

**Comment by medariox** [comment]
Why? That's not how Medusa works.

**Comment by JohnMaguire** [comment]
@medariox Why? Why not? Of course that's not how it works - that's why I filed the issue.

What is the value of creating a warning? The problem with creating a warning is that now every time the post-processor is run, I get thousands of warnings which fill up my logs and make it impossible to see real issues.

Why would I want a warning? Maybe to let me know that I'm trying to post-process a duplicate item? Certainly, this is sensible if my mode is set to "Move." But for hardlink, symlink, and copy, we'll see these files again and again and again.

**Comment by medariox** [comment]
The post-processing and download folders need to be different, no matter what processing method you choose.

**Comment by JohnMaguire** [comment]
They are.

**Comment by medariox** [comment]
The problem is that you are trying to process different files for an episode you already have, not the same file. Otherwise you would just get `File exists and the new file has the same size, aborting post-processing` which is just an INFO log.

**Comment by medariox** [comment]
I've added that log string to the custom logs, so you can decide what logging level you want to use. Gear > General > Advanced Settings > Logging
Will be available in the upcoming release.

**Comment by JohnMaguire** [comment]
Thanks for the clarification - can you tell me how the file comparison is
performed? Checksum?

**Comment by medariox** [comment]
It uses os.path.getsize(). Here the relevant code: https://github.com/pymedusa/Medusa/blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/post_processor.py#L161-L197
