### ISSUE TITLE
Downloads are not moved and folders are not created

### ISSUE THREAD

**Issue by digitalnaiveDE** [pymedusa/Medusa#6029]
hi there,

i am lost and hopefully you can help me. I followed the guide on htpcguides.com to setup medusa(formerly sickrage) to ensure that downloaded episodes will put into there season folders. unfortunately that is not happening and episodes just arrive in the folder /Media/Serien instead of /Media/Serien/xxx

In sabnzbd i created the category tv and the path i entered there is /Media/Serien, that should be correct?! The temp folder for downloads of sabnzbd is /Media/Downloads -> is that a problem?

additionally i gain an error in sabnzbd that it has not the rights to edit the folder /Media/Serien but this folder has chmod 755 for the same user as medusa and sabnzbd has.

Did i provide enough information that you can help me here? Thanks

**Comment by medariox** [comment]
DO you have `Season Folders` enabled?
![img](https://snapr.pw/i/71b5efeb37.png)

**Comment by digitalnaiveDE** [comment]
do you mean this setting? 

Create missing show directories

**Comment by medariox** [comment]
> Do you have Season Folders enabled?

Post a screenshot of the show path.

**Comment by digitalnaiveDE** [comment]
![image](https://user-images.githubusercontent.com/26203361/51329320-8c5e5900-1a75-11e9-9465-2eb1b3be7c9c.png)

**Comment by medariox** [comment]
Post the debug log with the error. A quick check if it's a permission issue would be to temporarily chmod the folder to 777. Does it work then?

**Comment by digitalnaiveDE** [comment]
Even i consider me a newbie it feels like i have done something wrong regarding permission:

![image](https://user-images.githubusercontent.com/26203361/51329716-65eced80-1a76-11e9-9d35-26225964d675.png)

so i added the user pi to the group medusa, the user pi is in my sabnzbd config file and so i thought it must be enough permission wise when i just give the ownership from /Media Recursiv to medusa:pi but as i am writting it and still learn, i assume i found my error. do i probably change my user in sabnzbd to medusa as well and then give ownership of /Media to medusa:medusa instead?

**Comment by medariox** [comment]
The log you posted above just shows that Medusa can't match the files to a show because the files are named as hashes. Medusa needs to know the name of the show to process them, either in the file or the folder.

**Comment by digitalnaiveDE** [comment]
Sorry if i ask back really stupid, but how do i achieve that?

**Comment by medariox** [comment]
These files don't have a folder? sabnzbd doesn't have an option to create a folder with the NZB name?

**Comment by digitalnaiveDE** [comment]
So that means that SABNZBD will initially create a folder and therefore needs the right permissions. Is this correct? (i am really sorry for those annoying questions)

**Comment by medariox** [comment]
That's probably the case, yes.
