### ISSUE TITLE
Backlog Search Sends Multiple Download Requests for Same Episode

### ISSUE THREAD

**Issue by gmusgrave** [pymedusa/Medusa#6031]
**Describe the bug**
I've noticed that sometimes when I start a backlog search, more than one version of the same episode will be sent to my download client(s). This seems similar to issue #5915 in that I've seen both an NZB and a torrent for the same episode, although not always. It also seems somewhat similar to issue #5991, but has noting to do with communicating with my bitorrent client.

Finally, I bagged a live specimen that really demonstrates this!

I set a backlog for the entire Season 2 of Marvel's Runaways. It appeared in my Backlog Overview as expected, and then I started to see pop-ups for the episodes being snatched. But... they kept coming and coming and coming!

Eventually SABnzbd had three sets of the 13 episodes queued for download, and qbittorrent had two more sets.

**To Reproduce**
Steps to reproduce the behaviour:

1. Select a show that has already aired, and has one or more skipped seasons (I believe this is important, because I have no problem with currently airing shows). I believe it also important to find a show that is popular so that there will be a selection of episodes that will match your download criteria.

2. Select an entire skipped season, and change the status to "Wanted."

3. Watch the chaos ensue...

**Expected behaviour**
Once Medusa finds a match for an episode and queues it for download, it should not queue additional duplicate episodes.

**Medusa (please complete the following information):**
 - OS: Windows 7 x64
 - Branch: Master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76

**Logs:**
Here is the log... WARNING: lengthy! This is because it snatched around five versions of each of 13 episodes.

```
[Medusa Log for Bug Report.txt](https://github.com/pymedusa/Medusa/files/2770061/Medusa.Log.for.Bug.Report.txt)
```
</details>

**Comment by gmusgrave** [comment]
Do you guys have a rough idea when this change will make it to the master branch?

**Comment by p0psicles** [comment]
Really hard to say. As we've also merged python3 compatibility into develop. And we still need to get that stable.

**Comment by p0psicles** [comment]
If your really bothered by it, better switch to develop until we release

**Comment by gmusgrave** [comment]
Thanks!

**Comment by djskippy50** [comment]
Have the same issue. Just recently switched to Medusa and the amount of duplicates that were getting sent to SAB were tremendous. Switching to the development branch fixed it for now, but I hope this makes it to the master branch soon, especially since this could be very confusing for new users.
