### ISSUE TITLE
[918cfe7] Unable to test TRAKT: MissingTokenException(u'You must get a Trakt TOKEN. Check your Trakt settings',)

### ISSUE THREAD

**Issue by raptor75** [pymedusa/Medusa#6059]
**Describe the bug**
Trakt authorisation seems not to be saved

**To Reproduce**
Go in notification settings, social, trakt. 
Get a PIN and authorize Medusa
Save
Do a test - succeeds.
Go on any other page (logs e.g.)
Go in notification settings, social, trakt. 
DO a test - fails with above error.

**Expected behavior**
Test should work.

**Medusa (please complete the following information):**
 - OS: Linux Mint 19.1 Tessa x64
 - Branch: master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76 

**Additional context**
I noticed this issue when my trakt was not being updated after adding episodes

**Comment by p0psicles** [comment]
Trakt is working fine for me.
I followed your exact steps. But no issues here.
When you save your settings, try opening config.ini. And check the [Trakt] section. It should have a trakt_access_token and trakt_refresh_token after saving.

**Comment by raptor75** [comment]
@a10kiloham what is your system?

**Comment by a10kiloham** [comment]
Just the master docker image on Linux

**Comment by raptor75** [comment]
bump

this is still an issue for me. trakt integration is not working. how can I be the only one?

**Comment by raptor75** [comment]
@p0psicles - I repeated the steps and checked the config.ini file. There are both entries, but trakt is still not working.

[Trakt]
use_trakt = 1
trakt_username = REDACTED
trakt_access_token = REDACTED
trakt_refresh_token = REDACTED
trakt_remove_watchlist = 0
trakt_remove_serieslist = 0
trakt_remove_show_from_application = 0
trakt_sync_watchlist = 0
trakt_method_add = 0
trakt_start_paused = 0
trakt_use_recommended = 0
trakt_sync = 0
trakt_sync_remove = 0
trakt_default_indexer = 1
trakt_timeout = 30
trakt_blacklist_name = ""

**Comment by p0psicles** [comment]
I don't know how to help you with this? Tried develop branch? Maybe some weird character in username? Can you try on different system?

**Comment by raptor75** [comment]
@p0psicles definitely not weird character, my username is simple letters and numbers.

Thing is, this was working and then suddenly stopped working, and I think when I updated to 19.1. Is there a log file I can check? Possibly a python update broke it.

**Comment by a10kiloham** [comment]
I had never tried it up until now and have the same error. Simple username, special characters in password only.

**Comment by p0psicles** [comment]
Any errors in the browser console?

**Comment by p0psicles** [comment]
Please both checkout the develop branch. And provide me some info on your browser. Also check you browser console for errors. I'm also trying to reproduce on develop.

**Comment by p0psicles** [comment]
This might be a fix. #6314

**Comment by a10kiloham** [comment]
from the chrome console the only error comes when getting a NEW pin. after the auth window Chrome throws ```Unchecked runtime.lastError: The message port closed before a response was received.```

**Comment by a10kiloham** [comment]
Argh, ok it just authorized and stayed authorized now. I can't reproduce either anymore. Thx

**Comment by p0psicles** [comment]
hmm could be a short timeout window? Maybe with users with a less then optimal internet connection?

**Comment by a10kiloham** [comment]
possible, or just a slow Trakt response. i had tried it originally and it didn't write to the config file, so perhaps those are separate bugs. in this case, maybe it was partially user error - the UI flow wasn't entirely clear and when it returned from the Trakt call, the PIN field was blank and disabled, but at the bottom the status said the authentication worked. perhaps it may also be more intuitive if the button changes to say the status like "AUTHENTICATED!" or otherwise some UI flourish to show it's good.

**Comment by p0psicles** [comment]
I was allready mid-way an other PR where I'm replacing our trakt lib with that of pytrakt. That also replaces the PIN auth as that's "deprecated" and should be replaced by OAUTH device auth. That's why i'm not looking too much into this now.

**Comment by pax0707** [comment]
Trakt PIN -> New
Allow SiCKRAGE to use your account? prompt
PIN -> Enter pin
Test Trakt -> Test notice sent successfully to Trakt
Save Changes
Test Trakt -> Test notice failed to Trakt: MissingTokenException('You must get a Trakt TOKEN. Check your Trakt settings')


```
[Trakt]
use_trakt = 1
trakt_username = XXXX
trakt_access_token = "" <- EMPTY
trakt_refresh_token = XXXXX
trakt_remove_watchlist = 0
trakt_remove_serieslist = 0
trakt_remove_show_from_application = 0
trakt_sync_watchlist = 0
trakt_method_add = 0
trakt_start_paused = 0
trakt_use_recommended = 0
trakt_sync = 0
trakt_sync_remove = 0
trakt_default_indexer = 1
trakt_timeout = 30
trakt_blacklist_name = medusa-blacklist
```


Medusa Info: | Branch: masterCommit: d0c136d7a528a471b51676140bd35d24d97f65c6Version: 0.3.9Database: 44.14
-- | --
Python Version: | 3.7.3 (default, Apr 3 2019, 05:39:12) [GCC 8.2.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-4.19.75-v7l+-armv7l-with-debian-10.2
Locale: | en_US.UTF-8

**Comment by Spoonikle** [comment]
pax0707, I was running Medusa as a container in UnRaid and having the same issue as you.

I went and installed sickchill - same problem - the I reinstalled the Medusa docker... bam - it worked.

**Comment by jeffski10** [comment]
I've started getting this issue in the last week: 
2020-01-22 20:04:45 INFO	TRAKTCHECKER :: Unable to retrieve episodes from Trakt watchlist. Error: MissingTokenException('You must get a Trakt TOKEN. Check your Trakt settings')
2020-01-22 20:04:40 INFO	TRAKTCHECKER :: Unable to retrieve shows from Trakt watchlist. Error: MissingTokenException('You must get a Trakt TOKEN. Check your Trakt settings')

I set the token, do the check it works then 5 mins later it fails. Running in docker.   When you did the set up again was it fresh i.e. clean ini file?

**Comment by Spoonikle** [comment]
> 
> 
> I've started getting this issue in the last week:
> 2020-01-22 20:04:45 INFO TRAKTCHECKER :: Unable to retrieve episodes from Trakt watchlist. Error: MissingTokenException('You must get a Trakt TOKEN. Check your Trakt settings')
> 2020-01-22 20:04:40 INFO TRAKTCHECKER :: Unable to retrieve shows from Trakt watchlist. Error: MissingTokenException('You must get a Trakt TOKEN. Check your Trakt settings')
> 
> I set the token, do the check it works then 5 mins later it fails. Running in docker. When you did the set up again was it fresh i.e. clean ini file?

I uninstalled the docker container, then reinstalled it. I did not delete any of its shares and I used the same config to reinstall as I did on my first install. I didn't set up trakt after reinstall, neither did I use the test button - it just started working on its own when I checked the logs. 

It was very weird behavior. 

While I expect the container to reinstall and run as if nothing changed, I didn't expect trakt to start working inexplicably.

**Comment by jeffski10** [comment]
Thanks for this.  Tried the same but still get the error and I notice in the config file I get trakt_access_token = ""   .  May need to build a clean version and see what happens.

**Comment by raptor75** [comment]
I know this was closed a long time ago, but I wanted to update on this. I still had issues with this but did not have time to look at it. Today I shifted to the develop branch which uses a different system for authentication on Trakt, and that stuck! Trakt integration is working again! Thanks @p0psicles

**Comment by raptor75** [comment]
adding to this, unfortunately it is not working again. it is losing the token.
