### ISSUE TITLE
[ FEATURE ] Display episode embedded tracks/subs

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#607]
if you ever got a media codec info extract solution in place it would be very cool if we could see the following:
- show embedded subtitles
- audio tracks count and names of tracks if possible

reason for this is to ensure better insight into what is accurate when it comes to the episode container file.

**Comment by wimpyrbx** [comment]
http://pastebin.com/ZCMG7etU

one way of reading the info is using ffmpeg's ffprobe which i believe should be available in most OS's.

* chapter info
* video streams count + info/name + codec info etc
* audio streams count + info/name + codec info etc

the supplied file is using title "Surround 5.1" as name for both streams. Usually this is where it would say ENG or English / NOR or Norway etc. So there would be a need for a lookup table translating different settings to language so we can use country flags.
IE:
EN => English
ENG => English
ENGLISH => English
and then if match is found we can use en.png to display language flag or something.

Also for audio it should be possible to find out how many different types we have.. like surround 5.1, 7.1, 2ch stereo etc and have icons for those as well.

**Comment by wimpyrbx** [comment]
This would also be nice since it would give instant info if a Commentary track is available etc.

**Comment by NicoLeOca** [comment]
Hi,

Could we have at least subs displayed wether they are activated or not?
at the moment, they are displayed only if you ask SR to get them.

Cheers

**Comment by NicoLeOca** [comment]
@ratoaq2 
why did you close this feature request?

**Comment by ratoaq2** [comment]
Sorry. I haven't realised. Probably while reading it on my mobile, I  pushed the close button  unintentionally. Reopening it

**Comment by NicoLeOca** [comment]
@fernandog 

what do you think about my comment above?

Could we have subs displayed wether they are activated or not?
at the moment, they are displayed only if you ask SR to get them.

**Comment by ratoaq2** [comment]
This might help for mkv files: https://github.com/Diaoul/enzyme

Subliminal uses it to get video info,  embedded subs,  etc

**Comment by NicoLeOca** [comment]
enzyme library is integrated into SR already.
it is used to parse files.
then it's mainly a matter of how to display information (if we want to show it)

**Comment by wimpyrbx** [comment]
i would love to be able to see how many, what languages and what is default subtitle track of those embedded in video container.

**Comment by labrys** [comment]
Added to master feature request list - discussion for feature will continue here even though issue is closed.
