### ISSUE TITLE
Failed parsing provider w/ newznab provider using Jackett

### ISSUE THREAD

**Issue by a10kiloham** [pymedusa/Medusa#6073]
```
2019-01-23 01:28:10 ERROR    SEARCHQUEUE-BACKLOG-333343 :: [Jackett Torrent] :: [918cfe7] Failed parsing provider.
Traceback (most recent call last):
  File "/app/medusa/medusa/providers/torrent/torznab/torznab.py", line 192, in parse
    torrent_size = item.size.get_text(strip=True)
AttributeError: 'NoneType' object has no attribute 'get_text'
```
Have gotten at least one error a day lately this way. Standard Docker build.

**Comment by p0psicles** [comment]
Provider that does not offer the torrent size?

**Comment by p0psicles** [comment]
@medariox we could check for the item.size? Don't know if we can have that optional?

**Comment by medariox** [comment]
Yes sure, size can be optional (-1, iirc), but it would be interesting to know which provider causes this.

**Comment by medariox** [comment]
In that case you might want to report it to Jackett and get it fixed over there as well, as the provider should provide the size. Obviously we should also avoid the exception.

**Comment by a10kiloham** [comment]
Yeah I'll open a ticket. V odd as there seem to be hundreds of requests yet only one is throwing this error. Ah well.
