### ISSUE TITLE
Redownloading episodes already downloaded

### ISSUE THREAD

**Issue by bluelavalamp** [pymedusa/Medusa#6078]
**Describe the bug**
I have one show where Medusa will keep downloading the episodes over and over again.  This issue has just started happening over the last couple of days.  The show is "Killing Eve".  Allowed quality is 720p and preferred is 1080p.  I had all 1080p versions of the episodes and suddenly Medusa decides to download the show again.  But it will not only download 1080p versions, but 720p versions as well.  I've tried setting the episodes to Ignore and Archive and it made no difference.  Eventually the shows will be snatched again and redownloaded.

**Expected behavior**
I expected that since the show was marked as Downloaded and being a 1080p quality it wouldn't snatch it again.  I also expected when setting status to Ignored or Archived that it wouldn't snatch the show again, but for both situations it re-snatched the show and started downloading.

**Medusa (please complete the following information):**
 - OS: Slackware64 -current
 - Branch: master
 - Commit: (not sure where to find this information)

**Logs:**
https://github.com/bluelavalamp/log

Thank you

**Comment by p0psicles** [comment]
Fixed in develop
