### ISSUE TITLE
Python Memory leak in Medusa

### ISSUE THREAD

**Issue by juliemars** [pymedusa/Medusa#6160]
Hi All

I am running Medusa on a Raspberrypi, I have tried the following Raspbian images, stretch and Buster, I know Buster is in beta but wanted to try it to see if it helped.

Medusa will over a couple of hours increase memory usage on the PI until it uses all the available memory and I have to log in and kill -9 the process, this will then restart the process and the cycle begins again. 

I have tried clean install of Medusa and the OS - same issue. I do have other python apps running, LazyLibrarian and mylar but I have ruled these out by disabling all apps and enabling them 1 at a time until the issue returned - in all cases it was only Medusa that caused the memory to spike, I could leave LazyLibrarian and mylar running for days without issue - Medusa on it's own exhibits the issue after a short time.. 

According to Monit, Medusa has been up for 17 hours and is currently using 0.2% CPU and 74.8% [730.4 MB] of memory checking Medusa status shows nothing running or updating the footer in Medusa shows Memory used: 745.11 KB. 

Medusa Configuration

`

Medusa Info: | Branch:                 master                  Commit:                 918cfe7ce01808499585ffe6c1356fd5ed369f76                  Version:                 v0.2.14                  Database:                 44.12
-- | --
Python Version: | 2.7.15+ (default, Nov 28 2018, 16:27:22)  [GCC 8.2.0]
SSL Version: | OpenSSL 1.1.1a  20 Nov 2018
OS: | Linux-4.14.79-v7+-armv7l-with-debian-buster-sid
Locale: | en_GB.UTF-8

`

Does anyone have any ideas as to why Medusa is using so much resources? I am sure it's a python issue but cannot locate what it is - especially as the other apps works fine. 

Thanks

**Comment by medariox** [comment]
How many shows do you have? Is it stable at around 750 MB or ist it still growing? What options do you have enabled? It's hard to help without any debug logs.

**Comment by juliemars** [comment]
Hi Medariox So in an hour since posting this Medusa is showing as 86.8% [847.4 MB] I have 54 Shows (47 Active).  

I should have said as part of an early test I did a fresh install and with no shows it did the same, it took slightly longer to get to a stage that was unusable but the memory leak was still present - I think it took around 50% longer but I am not 100% sure I have been trying various tests for a few months now.  

I will keep trying to get a debug log, but with the memory issues it's proving difficult. 

Thanks

**Comment by p0psicles** [comment]
How many providers? Does it go up after a scheduled daily search? Like every 10/20 minutes?

**Comment by medariox** [comment]
@p0psicles I don't think so.

**Comment by juliemars** [comment]
1 provider, nzbhydra.

I have the daily search set to 240 minutes, backlog to 1440 and proper's every 24 hours for 2 days.

It just seems to go up until it gets to around 95-98% of memory usage then it stays at that level but the PI is slow and unresponsive to anything so I log in and run a top command, it shows Medusa and I kill it.

**Comment by medariox** [comment]
It sounds a lot like a system specific issue. Can you try the same setup on a different system for one day? That would surely help.

**Comment by juliemars** [comment]
ah ok, makes sense. I just killed medusa as it was at 94% it's back to 2.7% at present and I have tried a manual daily search to see if that has an impact, once done if no impact I will try a backlog search.

2.7.15+ is what Medusa shows, I checked packages on Debian (https://packages.debian.org/buster/python) and it shows python as 2.7.15-4 I never built it, I just used apt-get install to get it from the repo. 

Will try and switch to Dev branch later today, is there anything I need to do to use Python3 with it? I am guessing just follow https://github.com/pymedusa/Medusa/pull/4982

**Comment by medariox** [comment]
Just pull the develop branch, install Python 3 and run Medusa with that Python version. It's probably going to be `python3 start.py`.

**Comment by medariox** [comment]
Yes, that looks right.

**Comment by lklock** [comment]
Hi,
I was running develop branch for the last two weeks and memory consumption seemed stable.
Switched to release to 0.3.0 yesterday and it is the same so it seems indeed that there is no more memory leak when running with Python 3 (3.5.3 on Debian stretch in my case)

**Comment by medariox** [comment]
Glad to hear that. Closing as fixed,
