### ISSUE TITLE
[minor] Wrong description for option on Search Settings

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#6161]
**Describe the bug**
On the search Settings page the description for _Forced backlog search day(s)_ seems to be wrong. it shows "how many days to keep searching for propers since episode airdate (default: 2 days)"

**Screenshots**
![settings](https://user-images.githubusercontent.com/869637/52165850-515f5500-2706-11e9-92ae-2f029542ab4d.png)

**Comment by medariox** [comment]
Thanks for the report! Fixed with https://github.com/pymedusa/Medusa/pull/6207
