### ISSUE TITLE
Quality Upgrade

### ISSUE THREAD

**Issue by salteran** [pymedusa/Medusa#6171]
Is there a Way to make Medusa keep or store the old video file rather than delete when it does a quality update of a preferred file

I have had 1 or two instances where the old file is much better in "actual recording quality" and would like to have reverted back to the old file

Thanks

Alan

**Comment by medariox** [comment]
That's not something we plan to add right now. If you know the groups you can exclude the ones that release low quality files by adding them to the ignored words filter.

**Comment by salteran** [comment]
Thanks for responding

 

Yeh I am aware of the filters.  

 

It’s more the fact that if I have watched the episode at a lower res, then a higher res comes along and Medusa downloads and deletes the lower res file. But then upon watching there is some issue with the higher res file.  It would be nice to restore the lower res file.  If Medusa could be told to move them to a Medusa “Recycle Bin”

 

Thanks

 

Alan
