### ISSUE TITLE
Cycle runs

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#6173]
Hello,

Can someone tell me why all the next run tasks are wrong on my scheduler?

http://prntscr.com/mh3qnu

Why if my postprocess cycle time is in 10m the next run will be in more than 1h?

Thanks,

Pedro

**Comment by medariox** [comment]
Well, that's something new. These kind of issues are usually on a lower level, maybe related to your system or your Python build. I'd suggest you to try a different system and/or Python version, as it is unlikely to be an issue directly related to Medusa and we are probably unable to help you.
