### ISSUE TITLE
Mako Error when adding existing shows

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#6185]
### INFO
**Python Version**: `3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134-SP0`
**Locale**: `cp1252`
**Branch**: [develop]
**Database**: `44.14`
**Commit**: [a0fe169]
 When trying to add more then two existing shows Medusa throws a Mako error
![addshows](https://user-images.githubusercontent.com/7034303/52365450-8379fb00-2a15-11e9-99e5-2db57ee588fa.png)
![makoerror](https://user-images.githubusercontent.com/7034303/52365475-97bdf800-2a15-11e9-900e-0a921979651d.png)

**Comment by medariox** [comment]
Thanks for the report. Fixed with https://github.com/pymedusa/Medusa/pull/6201
