### ISSUE TITLE
Default Episode Status Changes by Itself After Show Is Added

### ISSUE THREAD

**Issue by gmusgrave** [pymedusa/Medusa#6187]
**Describe the bug**
When I add a new show, it is set to my default of a "Default Episode Status" of "Wanted." I have verified this after the show was added.

Sometime later (maybe a day or so??) this changes by itself to "Skipped."

The result is that when the show air date comes along, the show is not downloaded. I then have to go back in and edit it to "Wanted," and manually download it. After that, this setting is remembered.

At the first of each month, I go online to see what new shows are debuting during the coming month. On Feb 1 I did this, and added 13 new shows. Each of them was initially set to "Wanted" (I checked!). A few days later, every one was changed to "Skipped."

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a new show, and during the Add dialogue make sure that the Default Episode Status is set to "Wanted."

2. After the show has been successfully added, visit the show's page and verify that the it is actually set to "Wanted."

3. A few days later, check again. In my case, it will have changed itself to "Skipped."

**Expected behaviour**
When I add a show with the Default Episode Status set to "Wanted," it should stay this way.

**Medusa (please complete the following information):**
 - OS:  Windows 7 SP 1
 - Branch:  master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76

Thanks

**Comment by gmusgrave** [comment]
OK... I attempted to bag a live specimen.

Yesterday at about 10:50AM I added a new show, "**_Larry Charles' Dangerous World of Comedy_**." It was added successfully, and I verified that the Default Episode Status was set to "**Wanted**."

I then checked it every 2 hours or so throughout the day to see whether it had changed. As of about 10PM it was still set to "**Wanted**."

**This morning about 7AM I checked again, and it had been changed to "_Skipped_**."

I reviewed the logs from about 10PM until just before 7AM:

From 21:54PM there were hourly SEARCHQUEUE searches for episodes up until about 3AM. Here is a typical example of one of these seemingly uneventful hourly searches:

 `2019-02-13 23:54:42 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [918cfe7] Seeing if we need anything from Larry Charles' Dangerous World of Comedy`

At about 2:53 AM there was a BACKLOG SEARCH:

`2019-02-14 02:53:51 DEBUG    BACKLOG :: [918cfe7] Seeing if we need anything from Larry Charles' Dangerous World of Comedy`

`2019-02-14 02:53:51 DEBUG    BACKLOG :: [918cfe7] Nothing needs to be downloaded for u"Larry Charles' Dangerous World of Comedy", skipping`

`2019-02-14 02:53:51 DEBUG    BACKLOG :: [918cfe7] Setting the last backlog in the DB to 737104`

Then at 2:55 AM there was another hourly SEARCHQUEUE search.

A few minutes later, there was a SHOWUPDATER event:

`2019-02-14 03:01:50 DEBUG    SHOWUPDATER :: [918cfe7] Skipping show update for Larry Charles' Dangerous World of Comedy. As the show is not in the indexers TVmaze list with updated shows within the last 12 weeks.`

At about 3:49AM there was this:

`2019-02-14 03:49:41 DEBUG    MAIN :: [918cfe7] Building black and white list for Larry Charles' Dangerous World of Comedy`

`2019-02-14 03:49:41 DEBUG    MAIN :: [918cfe7] 40909: Finding the episode which airs next`

`2019-02-14 03:49:41 DEBUG    MAIN :: [918cfe7] 40909: Found episode S01E01`

Then at 4:49 AM the hourly searches resumed up to the 7AM time when I noticed the switch in status, and started searching the logs.

Hopefully something in here can point you in the right direction, since this is an annoying bug. I have to reset the default episode status for every new show I add!

Thanks.

**Comment by medariox** [comment]
Are you sure you don't have the status for previously and future episodes switched up?
It sounds a lot like it TBH.

![img](https://snapr.pw/i/71c152e9d5.png)

**Comment by gmusgrave** [comment]
My default status settings look exactly like your example: **previously aired – "Skipped,"** and **future episodes – "Wanted."** 

Because of this problem, I always check page 3 of 3 during the Add show dialogue to make sure these are still the settings before I add the show. 

Once the show has been added, I check the "**Default EP Status:**" on the show page to be sure it also says **"Wanted."**

It is this latter that started out as **"Wanted"** when I first added the show, and stayed that way throughout the day (checked it every 2 hours or so), and then sometime during the night changed to **"Skipped."**

**Comment by gmusgrave** [comment]
**UPDATE**

OK... it's not so cut and dried.

On Sunday Feb 24, I added a new show. I checked it the next day, and the ensuing days. It remained set to "_Wanted_"! On Friday March 1, I added 9 new shows (debuting in March), and checked them on Saturday – no change in Default EP Status.

Then I checked this morning, and **all of these shows** had changed themselves to "_Skipped_"!

The only intervening event is that every Sunday morning, just before 3AM, my computer automatically reboots. I've learned the hard way over the years that this a good practice to help keep Windows from accumulating problems over time (in as much as that is possible). Anyway...

My first bug report was made for shows added at the start of the previous month, and there was an intervening re-boot Sunday between the addition of the shows and me noticing the switch in status. My second report of a bagged live specimen was a Wednesday/Thursday transition, but I checked and a Windows Update was installed Thursday in the wee hours, and it re-booted the computer.

There were two new shows I added **whose status did not change**, but they had episodes snatched before the re-boot.

So... I now believe that the problem can be restated: **if a new show is added, and no episodes have yet been snatched, and the computer is re-booted (or, more likely, Medusa is shut down and re-started), then the default episode status will change from "_Wanted_" to "_Skipped_."**

I looked at the Medusa logs, and could see no entries for any of these shows that explicitly explain why, or state that, the Default EP Status was changed.

Here is a summary of the logs:

```
At 2019-03-03 02:55:45 "Building black and white list for..." goes through shows by download folder, then the most recently added shows.

	Typical example:
		2019-03-03 02:55:46 DEBUG    MAIN :: [918cfe7] Building black and white list for After Life
		2019-03-03 02:55:46 DEBUG    MAIN :: [918cfe7] 36673: Finding the episode which airs next
		2019-03-03 02:55:46 DEBUG    MAIN :: [918cfe7] 36673: Found episode S01E01
		2019-03-03 02:55:46 DEBUG    MAIN :: [918cfe7] 40896: Loading show info from database

At 2019-03-03 02:55:46 the reboot occurred, and Medusa restarted.

At 2019-03-03 02:55:46 "Building internal name cache for all shows" started. Appeared to go in same order as black and white list. The most recently added shows were at end.

	Typical example:
		2019-03-03 02:55:46 DEBUG    MAIN :: [918cfe7] Internal name cache for after life set to: after life

At 2019-03-03 02:55:46 "Started updating network timezones" executed next, followed by checking github for an update.

At 2019-03-03 03:00:00 the SHOWUPDATER sequence started. Appeared to proceed in same order as black & white list and internal name cache. The most recently added shows were at the end.

	Typical example:
		2019-03-03 03:00:22 DEBUG    SHOWUPDATER :: [918cfe7] Skipping show update for After Life. As the show is not in the indexers TVmaze list with updated shows within the last 12 weeks.

At 2019-03-03 03:00:24 the SHOWQUEUE-UPDATE started. Appeared to proceed in same order as black & white list and internal name cache. The most recently added shows were at the end. Only one of the affected new shows was updated (MotherFatherSon).
 
At 2019-03-03 03:02:22 the SHOWQUEUE-SEASON-UPDATE started. Appeared to proceed in same order as SHOWQUEUE-UPDATE. The most recently added shows were not included.
 
At 2019-03-03 03:05:39 the SHOWQUEUE-REFRESH started.  Appeared to proceed in same order as SHOWQUEUE-UPDATE. The most recently added shows were not included except the one that appeared in the SHOWQUEUE-UPDATE (MotherFatherSon).
 
At 2019-03-03 03:10:46 POSTPROCESSOR started.

At 2019-03-03 03:40:46 FINDPROPERS started.
 
At 2019-03-03 03:55:46 DAILYSEARCHER started. Appeared to proceed in same order as black & white list and internal name cache. The most recently added shows were at the end.
 
	 Typical example:
		2019-03-03 03:55:50 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [918cfe7] Seeing if we need anything from After Life
	
The DAILYSEARCHER continued every hour, until I checked the episodes this morning.
```
If you need the complete log, I can upload it.

Thanks

**Comment by gmusgrave** [comment]
One more observation...

If the Default EP Status does change "by itself," and it is edited back to "Wanted," then it becomes sticky, and a re-start will not change it.

**Comment by gmusgrave** [comment]
OK... I added 8 new shows on Monday April 1. I confirmed that the Default EP Status on each was "Wanted."

Last night, I had to reboot for troubleshooting reasons (Windows).

Afterwards, five of these shows had been changed to "Skipped." Of the three that weren't changed, two had already had episodes downloaded, and the other had not, but was listed in the Backlog Overview.

**Comment by medariox** [comment]
@gmusgrave 
Sorry for the long wait. I've found the bug and it will be fixed in the next version.
Thank you so much for the detailed bug report and all the feedback.

**Comment by gmusgrave** [comment]
Thanks for this! It was a small issue, but annoying...

**Comment by strike84** [comment]
Has this bug been reintroduced? I've had this exact issue for years, but never got around to reporting it. I run medusa in a docker and on every restart the default episode status gets changed from wanted to skipped on newly added shows. After I manually change it back to wanted after the restart it will stick.

**Comment by p0psicles** [comment]
You can consistently reproduce this?

**Comment by strike84** [comment]
Yes, every time. And as the OP mentioned it doesn't happen if the show has snatched an episode before restart.

**Comment by strike84** [comment]
I should rephrase, it doesn't happen on every restart. But it happens if I restart after a day or 2. So I guess It could have something to do with show updater or something which runs every night. But I tested this yesterday. I added some shows a couple of days ago, then I restarted yesterday just to test. And all the shows were changed to skipped. And I confirmed they had wanted before I restarted.

**Comment by strike84** [comment]
@p0psicles Just curious if you have had the time to look into this?
