### ISSUE TITLE
Api post processing

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#6191]
Hello,

I just wanted to know how can I call the api of medusa to enable manually the post procesing of a folder. At the moment I had the post procesing scheduled with medusa to 10 min, but I wanted another service to execute it automatically on certain situations, for example, once a download has finished, the script is executed for medusa to run post procesing.
I looked here:
https://github.com/pymedusa/Medusa/wiki/Post-Processing
And saw the following:

> The third method is using a script to inform Medusa that a new episode was downloaded. This is the ideal/preferred way for NAS devices.

But I do not really know where to find that script, although I was thinking it was gonna be some sort of call to the api, but searched on the api and can not find either the call function. 

Can anyone help me with this?

Kind regards

**Comment by p0psicles** [comment]
Your looking for the nzbToMedia scripts. Search for it on github. It's a separate project. And you'll have to clone that separate.

**Comment by elpedriyo** [comment]
Hello,

I have searched for that but it seems that will activate postprocessing of nzbToMedia, and I am currently happy with the current postprocesing that medusa does.
So there is no way of just calling medusa api to execute postprocesing of it when I want?
If not, could you please create a call for it please?

Kind regards

**Comment by p0psicles** [comment]
No you can simply configure nzbToMedia to initiate the pp of Medusa. You make your download program use the nzbToMedia script.

**Comment by p0psicles** [comment]
You can still call the pp url directly of course. There was an issue with the url and params not to long ago. If I get time I'll look it up.

**Comment by elpedriyo** [comment]
Hello,

Yes, I have no problem on calling an script with transmission which is the one I am using currently for the downloads, but as far as I saw nzbToMedia does not initiate the pp of medusa.
But yes, if you could tell me the api url for the pp it would be great as I can not find it here:
https://medusaapi.docs.apiary.io/#

Kind regards

**Comment by p0psicles** [comment]
NzbToMedia does initiate Medusa pp.

**Comment by elpedriyo** [comment]
Let me check this code again:
https://github.com/clinton-hall/nzbToMedia/blob/master/TorrentToMedia.py

Although I would be more comfortable using the pp with an api call of medusa, instead of using NzbToMedia

**Comment by medariox** [comment]
That's what nzbToMedia does: https://github.com/clinton-hall/nzbToMedia/blob/4896848099298ee2914760c56a66d4ad0674d181/core/forks.py#L65-L70

https://github.com/pymedusa/Medusa/blob/master/medusa/server/api/v1/core.py#L1267-L1295

**Comment by elpedriyo** [comment]
Hello,

Yes, that api call was the one I was searching for :D didn't want to use the nzbmedia, was not looking for a third party tool just to activate a postprocesing.
Though seems v2 of the api is not completely updated with the old calls of api v1.

But thank you a lot :D 

Kind regards

**Comment by jaggeddragon** [comment]
For those who find this issue in the future and don't want to backtrack the direct API v1 URL is as follows:

curl 'http://{host}:{port}/api/{api_key}/?cmd=postprocess'

Where {api_key} can be found/managed within Medusa: Settings > General > Interface > Web Interface > API key
