### ISSUE TITLE
Does it reads from data disk?

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#6192]
Hello,

Just wanted to know if this scheduled jobs reads from the media directory where I have all my tv shows:

![image](https://user-images.githubusercontent.com/3207791/52528147-b7377800-2cd6-11e9-973a-e165b76660d1.png)

As I am currently want the disk to get into standby, and if it reads from disk, all the drives will start to spin for it

Kind regards

**Comment by p0psicles** [comment]
If you enable scheduled postprocessor, yes it will read from disk. If you don't want that, don't use it.

![image](https://user-images.githubusercontent.com/1331394/52533678-9eab7a00-2d37-11e9-984f-f876002c017a.png)

Alternative is to use nzbToMedia to trigger the PP when it needs to.
