### ISSUE TITLE
Episodes missed and not being grabbed, although it says 'snatched'

### ISSUE THREAD

**Issue by ashman70** [pymedusa/Medusa#6194]
**Describe the bug**
An episode for a show is missed, it's indicated that it was 'snatched' yet the episode has not been downloaded. When a manual search is conducted, plenty of available episodes in the requested quality are available.
_"From time to time I go through my shows in Medusa to make sure an episode has not been missed, and from time to time I find that a few have. Today is the first time in quite awhile that I have found over half a dozen episodes that have been missed for different shows, some episodes going back months. I am trying to understand why this is happening. When I click manual search for the missing episode, it finds plenty in the chosen resolution, in my case 720p, so I am not sure why they aren't being downloaded. I am very careful about scene names, take for example a show called Power, it is called Power.2014 so I have the edited into the show under scene exceptions, and I do this for most of my shows if they have more than one word in their name.  However this does not seem to have helped as an episode of Power got missed. Often I will find that in Medusa it says that an episode was 'snatched' but when I check I don't have it. I supposed it's possible there was an error downloading it but I wonder why if that was the case another attempt was not made, perhaps there is a setting I am missing? I have attached a few screen shots to illustrate what I am talking about. Even an episode of Vikings was missing, don't know why"_

**To Reproduce**

**Expected behavior**
It is expected that the episodes will be downloaded in the requested quality when available.

**Screenshots**

![image](https://user-images.githubusercontent.com/27771421/52535900-f0e1a080-2d21-11e9-873a-5fb2546aa084.png)

![image](https://user-images.githubusercontent.com/27771421/52535903-fb039f00-2d21-11e9-8ae8-2ec799dec705.png)

![image](https://user-images.githubusercontent.com/27771421/52535909-02c34380-2d22-11e9-8436-efacb7e0014a.png)

**Medusa (please complete the following information):**
 - OS: Linux-4.18.10-unRAID-x86_64-with
- Branch: Master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76 
**Logs:**
<details>

```
<-- Please replace this whole line with your logs -->
```
</details>

**Additional context**

**Comment by medariox** [comment]
Usually happens if the episode is deleted before the post-processing took place (e.g. auto deletion after X% upload). Check your settings.

**Comment by ashman70** [comment]
So what you are saying is the episode was downloaded but then deleted for some reason before post processing could process it? Why would that happen with only some episodes?

I don't see any such setting.
