### ISSUE TITLE
[ FEATURE ] Manual Search Collapse/Expand list

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#620]
possibility to group releases found in manual search into a collapsible/expandable table like this:

[+/-] Release 1 | Found x hits blabla bla
- Release 1 | provider1 | size etcetc..
- Release 1 | provider2 | size etcetc..
  [+/-] Release 2 | Found x hits blabla bla
- Release 2 | provider1 | size etcetc..
- Release 2 | provider2 | size etcetc..

https://www.packtpub.com/sites/default/files/Article-Images/jquery-article-27.png
poor example-image, but i'm sure you get my drift :P

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
