### ISSUE TITLE
[ FEATURE ] Manual metadata downloader

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#621]
it would be nice having a manual metadata (cover, fanart etc) downloader page, using fanart.tv or other sources.
- poster
- banner
- fanart
- clearart
- other available metadata

this would then replace cache images and place selected metadata files in the shows folder.

a page like this could be opened from a button on DisplayShow page.

**Comment by wimpyrbx** [comment]
This is an old, very crude, example to show what i mean.

http://www.fshare.it/i.php?i=4114604254o

In this example fanart selected would be saved in respective metadata locations inside show folder. Meaning if i have KODI metadata enabled it would save selected fanart to shows folder as fanart.jpg and at the same time update the cached version SR uses/displays in the theme.

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
