### ISSUE TITLE
Shows with a ton of episodes don't load

### ISSUE THREAD

**Issue by jandreaucodes** [pymedusa/Medusa#6216]
**Describe the bug**
If you add a show with a lot of episodes, the show won't load in Medusa.

**To Reproduce**
Add a show with a lot of episodes, for example Judge Judy.
When you load the show page, you don't see anything, just "loading". See: https://take.ms/o1xLR

**Expected behavior**
The show should load.

**Screenshots**
https://take.ms/o1xLR

**Medusa (please complete the following information):**
 - OS: Mac OS 10.14.3
 - Branch: master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76

**Comment by medariox** [comment]
This is already reported and we are working on it.
