### ISSUE TITLE
Transmission RPC URL not saving

### ISSUE THREAD

**Issue by henmad** [pymedusa/Medusa#6219]
**Describe the bug**
Updating Transmission RPC URL in search settings does not save and yields warning in logs. 
Googling yields results indicating this problem is fixed. However, I am still experiencing it.

**To Reproduce**
1. Go to Search settings -> Torrent search
2. type in "transmission" in Transmission RPC URL
3. Save changes

**Expected behavior**
Expected transmission settings to be updated with input data

**Medusa (please complete the following information):**
 - OS: Linux-2.6.32.12-armv5tel-with-glibc2.4
 - Branch: master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76 
 - Running Medusa on Synology NAS.

**Logs:**
<details>

```
2019-02-15 22:18:39 WARNING  APIv2-Thread_2 :: [918cfe7] Config patch ignored {u'clients': {u'torrents': {u'rpcUrl': u'transmission'}}}
```
</details>

**Comment by medariox** [comment]
Already fixed in develop.
