### ISSUE TITLE
[ FEATURE ] Theme to get access to more artwork

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#622]
Write a routine to be able to read artwork from folders show in mako.

At the moment we can only read out images from cache folder to use in the UI.
By opening this up we would be able to add more visually pleasing layout (GUI)

**Comment by wimpyrbx** [comment]
some old examples based on sickrage before i moved over to Medusa.

http://www.fshare.it/i.php?i=os1460911g4
http://www.fshare.it/i.php?i=d41460469r9

i know visual improvements are way behind other important stuff, but i'd like to get access to more artwork in the themes eventually to be able to do something like this.

**Comment by OmgImAlexis** [comment]
@wimpyrbx I'll be adding in an APIv2 route for this. @fernandog can we have a milestone for APIv2 please.

**Comment by fernandog** [comment]
milestone is whatever we decide

**Comment by OmgImAlexis** [comment]
This is being worked on as we speak. The new route will be as follows, `/api/v2/asset/{assetGroup}/{query}/?api_key=xxx&type={assetType}`.

For example to get a show's banner  `/api/v2/asset/show/12345/?api_key=xxx&type=banner`.

**Comment by wimpyrbx** [comment]
is there a list of what {assetType}'s there will be?

**Comment by OmgImAlexis** [comment]
For now it's poster, posterThumb and banner but this will most likely change. I'd like to have some kind of route that returns the assets for the resource you provide. For example with networks it'll only return icon as there's currently no other type of media for it.

@ratoaq2 should we start using http://swagger.io/ to list the acceptable routes, etc?

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
