### ISSUE TITLE
Debian users with ANY locale issue - Possible permanent FIX

### ISSUE THREAD

**Issue by Trans-IP** [pymedusa/Medusa#6220]
I have had a bunch of errors  with anime or shows that have non standard characters in the titles.

- nzbtosickbeard.py  failures
- renaming failures
- daily and backlog searches failing to run until the process is restarted

The root cause has always been how Python or the OS uses locales.   If the charset is missing the character that is needed for parsing, then failures occur.  So the idea is to use a widely used locale and deal with the one off issues.   I then went down the path of seeing if there was a way to enable all locales and not have the system pinned to any given one.

The solution seems to be to not pin the locale to any single locale but rather use the locales-all package which is pre-compiled with all locales enabled.   Once I installed this and rebooted the Locale on the Help and Info page is set to Unknown.Unknown but the /etc/local.gen file has every single locale listed in there.

Since then (last few hours) I have had zero errors with anything, renaming works, daily and backlog searches are working perfectly.

Some one should verify this and add it to the FAQ or install instructions for Debian (I'm using 9.7) and investigate how to do it on other distro's if possible.   I think it may be possible to just 'dpkg-reconfigure locales' and select all and set 'none' as default to get the same effect but I did not try this.  I have tried installing all with setting the default locale to one and had no success doing this.

Hope this helps someone!

**Comment by elrock** [comment]
I ran dpkg-reconfigure-locales with the options you suggested, and it seems to have fixed everything but subtitles search.
`2019-04-02 07:14:29 WARNING  FINDSUBTITLES :: [b34f1df] Unable to scan video: /media/lbrmedia/TV/Frontline/Frontline.S2019E04.The.Trial.of.Ratko.Mladić.720p.WEB-DL.mkv. Error: UnicodeEncodeError('ascii', u'/media/lbrmedia/TV/Frontline/Frontline.S2019E04.The.Trial.of.Ratko.Mladi\u0107.720p.WEB-DL.mkv', 72, 73, 'ordinal not in range(128)')
`
