### ISSUE TITLE
No metadata for tvmaze shows

### ISSUE THREAD

**Issue by Miicker** [pymedusa/Medusa#6223]
I have added two shows from tvmaze, banners for the tvmaze are not shown in Medusa. I tried fixing it by adding for example a banner to the following location:
\Medusa\cache\images\tvmaze\*show number*.banner.jpg

This works for a few hours/days, but after a certain time the banner is replaced again by the default medusa banner. How can this be fixed?

I guess it would be nice (and easy) to let Medusa check if there is a banner available at the indexer (for example tvmaze) and if there is not, check if there is one present in the folder. If there is, use that one and else use the default banner.

Another great future would be to upload custom art for each show, but I guess that would be a completely different kind of future request.

**Comment by p0psicles** [comment]
You should be able to choose your fanart using the Metadata generator kodi12+. Put the poster/banner/fanart in the shows folder.

**Comment by Miicker** [comment]
@p0psicles is that generator build into Medusa? And should I just put in in the folder main folder where the subfolders for each season are located?

**Comment by p0psicles** [comment]
Yes in config - postprocessed.
It think it's poster.jpg, banner.jpg fanart.jpg

In the shows main folder not season

**Comment by p0psicles** [comment]
It will create like the nfo and images if you click rescan files in the show

**Comment by Miicker** [comment]
Thanks @p0psicles it seems to work! :+1:
