### ISSUE TITLE
Scene Exceptions warning suppression

### ISSUE THREAD

**Issue by zaans2** [pymedusa/Medusa#6231]
I keep getting the warnings for scene exceptions where it says: 
`Consider adding '...' in scene exceptions for series '... (2018)'`

I rarely do actually add one of these exceptions. For the ones I do not add the exception it keeps giving the warning, which drives me crazy! 

I'd like to see some way of suppressing these warnings, maybe on a per show basis (as the warning is there with a purpose) or suggesting to add the scene exception when adding the show.

**Comment by duramato** [comment]
I think we can remove that log, what do you think @pymedusa/developers ? 
Most of the time it doens't offer any new info.

**Comment by medariox** [comment]
Yes, it should be made INFO for the next release.

**Comment by medariox** [comment]
Will be info in the next release.
