### ISSUE TITLE
Selecting first english release then foreign one

### ISSUE THREAD

**Issue by shaavik** [pymedusa/Medusa#6239]
**Is your feature request related to a problem? Please describe.**

I used : 
- Prefered words : french, vff
- Allowed words : french, vff, vostfr

I have already a show in 720p french, but medusa wants to download 1920 vostfr since the quality is superior.

**Describe the solution you'd like**
I want to keep shows in french in wathever quality, and if none exists in french, then in english.
My priority is language over quality.

**Describe alternatives you've considered**

**Additional context**

**Comment by medariox** [comment]
Already requested.
