### ISSUE TITLE
Question: missing  "numdict.pyc" ? Possibly re-instate it?

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#6241]
Hi,
Quick question - I have been  using NumDict from numdict.pyc file for my own filtering-code. I have noticed the file was removed in the latest releases. Can you put it back in ? There might be  ways to replace the functionality, but I am not an expert with python, and the code is already done here... 

Thanks!

Rafi

**Comment by medariox** [comment]
No chance, you can just add the[ numdict.py file](https://github.com/pymedusa/Medusa/blob/9d2568f2310f2a030f8bb02cecad234a39089f99/medusa/numdict.py) back yourself or replace whatever you are using NumDict for with a normal dict (as they are basically the same thing anyway).
