### ISSUE TITLE
rtorrent button to test connection not working

### ISSUE THREAD

**Issue by nygagest** [pymedusa/Medusa#6254]
**Describe the bug**
I've reinstalled medusa on my server, after that i've configured the rtorrent settings, i clicked on test connection and it does not work. I've checked with others like deluge and it works, but not for rtorrent.

**To Reproduce**
1. Go to Settings
2. Click on Torrent search
3. Configure your settings.
4. Scroll down to Test Connection
5. See error

**Expected behavior**
The result of test the connection, if it works or not.

**Medusa (please complete the following information):**
 - OS: Ubuntu Server 16.04 x64
 - Branch: master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76

**Comment by medariox** [comment]
Already fixed in develop.
