### ISSUE TITLE
backup/restore issue Shows all gone

### ISSUE THREAD

**Issue by povertypanda** [pymedusa/Medusa#6255]
Running the official docker image. 
Going from one docker instance to another. Both the same version level. 

Did the backup. Zip file was created. 
Restored on the new instance. No shows showing up. 

Figured okay lets play ball. Copied the entire config folder from the old one to the new one while the dockers were off. 
I have all of my settings however still none of the shows are coming up. 
I really do not want to add them all again.

Thoughts?

**Comment by p0psicles** [comment]
You need the main.db file

**Comment by povertypanda** [comment]
main.db is in the config folder and it was 100% copied when I copied the entire folder over to the new server. 
No go.

**Comment by p0psicles** [comment]
Must be in the main.db file. Sure you had that file copied? Access rights on the file okay?

**Comment by povertypanda** [comment]
So that file copied with my original transfer.. but didn't? the file was there but it was very much the wrong size. I have re-copied that file and all is well. 

Thanks for all of the input people. Very helpful!
