### ISSUE TITLE
[ FEATURE ] Direct link to torrent/nzb detail page in manual search

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#626]
Hi,

Would it be possible to have a direct hypertext link to the details of a release proposed by a manual search?

NicoLeOca

**Comment by medariox** [comment]
Which kind of details are we talking about here?

**Comment by duramato** [comment]
I think he means a link to the torrent or nzb page
But that's something that would/requires additional scrapping to get their details page as we only have the actual download links

**Comment by NicoLeOca** [comment]
yes, that's exactly what I meant

**Comment by p0psicles** [comment]
Yeah would be cool feature. Only it's not as standardized as scraping release name, torrent/nzb url's, seeders, etc. So it would 1. require db model change and 2. allot of configuration on a per provider base. Still not impossible, but those additional dependencies, will lower the prio of this of this request. Just so you now.

**Comment by NicoLeOca** [comment]
thanks for having had a look at it anyway, even if it' won't be on top of the priority list

**Comment by fernandog** [comment]
not possible for magnetl links so we can't support only a few items

**Comment by duramato** [comment]
It's possible.. just link to the provider it came from.

**Comment by fernandog** [comment]
we still can't make pubdate possible, imagine torrent details.

**Comment by duramato** [comment]
`example.com/id` no brainer.. just need to add a db table and many won't even need extra parsing.
pubdate is possible, just need to make the decision of string or object

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
