### ISSUE TITLE
Master vs Develop

### ISSUE THREAD

**Issue by rrd911** [pymedusa/Medusa#6260]
wasn't sure which option to choose (Feature or bug)

I noticed that there is a lot of great work being done on the Develop branch but the Master hasn't been updated in some time. Do most just live in the Develop branch these days? And is Develop stable enough to be almost considered master?

Just asking to see if I need to switch branches.

thanks for the great work

Ray

**Comment by p0psicles** [comment]
It's because we're working on python3 support in the develop branch.
And we discovered a major bug, which we haven't been able to fix yet.
We're also discovering new python3 related bugs on a weekly basis in develop branch. So we need to get it stable before we can merge it with master.

**Comment by p0psicles** [comment]
You can stay at master if everything works fine for you.

**Comment by rrd911** [comment]
Thanks for the update. Keep up the great work
