### ISSUE TITLE
problem with search season

### ISSUE THREAD

**Issue by Sirfrancis17** [pymedusa/Medusa#6261]
My problem is the medusa search season  this way
http://192.168.1.100:8081/home/snatchSelection?indexername=tvdb&seriesid=72218&season=6&episode=1&manual_search_type=season
Dont find anything because "episode=1"
without this argument i found the seasons packs
http://192.168.1.100:8081/home/snatchSelection?indexername=tvdb&seriesid=72218&season=6&manual_search_type=season
![1](https://user-images.githubusercontent.com/44566906/53679553-21d44600-3cce-11e9-9855-9f392b304858.png)
![2](https://user-images.githubusercontent.com/44566906/53679554-2436a000-3cce-11e9-8bf0-c36915603656.png)

**Comment by p0psicles** [comment]
Well need to refractor the code for this a little. Will look at it after next release

**Comment by p0psicles** [comment]
having a hard time reproducing it. My guess is, this is a jacket issue. Can you provide me with a recent example?
