### ISSUE TITLE
Problem with Postprocessing

### ISSUE THREAD

**Issue by Sparh4wk** [pymedusa/Medusa#6274]
Hello,

Im using develop version of medusa and I have problem with postprocessing.
When medusa found a new episode, it downloads it and marked as snatched.
But thats it.. even if I have post processing sheduled, it never runs out after it.
I waited several hours, but nothing.

My postprocessing setup:

![obrazek](https://user-images.githubusercontent.com/7014826/53786056-bdf28d00-3f1a-11e9-821a-13a5d6a06d14.png)

Im new so mb I did something bad when seting medusa up, but otherwise, everything is working so far.
When I run manual post processing on the same directory, it works fine.

**Comment by p0psicles** [comment]
Have you restarted Medusa after setting up?

**Comment by Sparh4wk** [comment]
yes like 3 times already

**Comment by medariox** [comment]
Does the auto post-processing even run? What Python version are you using? Please post a **debug** log of at least 1 hour.

**Comment by Sparh4wk** [comment]
dont know how, but its working after latest restart.. thanks for help and sry to bother :)
