### ISSUE TITLE
Failed to Start Medusa Daemon - code=killed

### ISSUE THREAD

**Issue by digitalnaiveDE** [pymedusa/Medusa#6276]
Hi folks,

i am currently receiving an Medusa Start Error.
```
medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Tue 2019-03-05 12:46:54 CET; 4min 22s ago
  Process: 14752 ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa (code=killed, signal=KILL)
```
```
Mär 05 12:45:35 raspberrypi systemd[1]: Starting Medusa Daemon...
Mär 05 12:46:54 raspberrypi systemd[1]: medusa.service: Control process exited, code=killed status=9
Mär 05 12:46:54 raspberrypi systemd[1]: Failed to start Medusa Daemon.
Mär 05 12:46:54 raspberrypi systemd[1]: medusa.service: Unit entered failed state.
Mär 05 12:46:54 raspberrypi systemd[1]: medusa.service: Failed with result 'signal'.
```
What can be the issue here?

**Comment by medariox** [comment]
Try to start Medusa with:
```/usr/bin/python2.7 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa```
You will see what's wrong.

**Comment by digitalnaiveDE** [comment]
I think it is an user error. I am connecting to my raspberry with another user than medusa. Unfortunately i haven´t understood the user structure in linux 100% yet. is it possible that executing those commands with another user is doing kind of nothing? do i need to login to ssh with the medusa user instead?

**Comment by medariox** [comment]
What kind of issues?

**Comment by digitalnaiveDE** [comment]
medusa.service: Failed to determine group credentials: No such process
Mar 05 14:54:23 asrock systemd[13844]: medusa.service: Failed at step GROUP spawning /usr/bin/python2.7: No such proces

**Comment by medariox** [comment]
Type `whereis python` and psot the result.

**Comment by medariox** [comment]
There was a small mistake in the setup guide. I suggest you start again from step 2. and it should be fine this time.

**Comment by medariox** [comment]
Closing as solved.
