### ISSUE TITLE
Add provider DigitalCore

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#6277]
Could the torrent site DigitalCore be added as a provider?
https://digitalcore.club/

They currently have open registration.

**Comment by p0psicles** [comment]
Don't think it's open. Or at least not anymore

**Comment by Rouzax** [comment]
It's still open
https://digitalcore.club/signup/open

**Comment by medariox** [comment]
Seems really new to me. What if it shuts down in 3 weeks? 😕

**Comment by Rouzax** [comment]
@medariox that is a valid concern that I don't have the answer to.

On their site they state:
We are a new site, build by ERR1R. Its a fork of the original rartracker source with modifications.

So it might be somewhat easy to implement.

**Comment by neo-neo1** [comment]
I'd love to see this get added to Medusa as a search provider

Sign-ups are currently open again: https://digitalcore.club/signup/
Great place for general 0day releases

**Comment by p0psicles** [comment]
I checked it out. But it's a bit meh. Like you need to open each page to get seeders, leeches and size

**Comment by Rouzax** [comment]
You could use Jackett to add it to Medusa.

**Comment by Rouzax** [comment]
I've added it using Jackett and it is indeed not such a top tier indexer
