### ISSUE TITLE
Deluge Client not working with python 3

### ISSUE THREAD

**Issue by dotsam** [pymedusa/Medusa#6278]
**Describe the bug**
When running the develop branch using Python 3.5.3, Medusa is unable to establish a connection to Deluge.

**To Reproduce**
1. Set up Torrent Search
2. Pick Deluge, either web or daemon
3. Configure with proper credentials
4. Attempt to test the connection

**Expected behaviour**
Medusa should be able to connect to Deluge. Works under Python 2.7.13.

**Screenshots**
N/A

**Medusa (please complete the following information):**
 - OS: Debian 9.7 x64
 - Branch: develop
 - Commit: f7cea251a

**Logs:**
Medusa shows no logs other than the tornado log for the test

```
2019-03-05 15:45:08 INFO     TORNADO :: [f7cea25] 304 GET /medusa/home/testTorrent?torrent_method=deluged&host=scgi:%2F%2Flocalhost:58846&username=**********&password=********** (::1) 7.36ms
```

Deluge shows a connection attempt and drop
```
Mar 05 15:45:08 pluvia deluged[25863]: [INFO    ] 15:45:08 rpcserver:206 Deluge Client connection made from: 127.0.0.1:51998
Mar 05 15:45:09 pluvia deluged[25863]: [INFO    ] 15:45:09 rpcserver:226 Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.                                                                                                                                                  
```

**Additional context**
It looks like there was some basic linting done on the deluge library to make it python 3 compatible in #4982, but the library is not functional. I see issue #5097 open to swap out the library used for Deluge, so it looks like that might need to be completed now.

**Comment by medariox** [comment]
Is just the test not working? Did you actually try to snatch something?

**Comment by dotsam** [comment]
Snatch is also not working. Again, no logs in Medusa, and just the timeout/connection close in the deluged logs.

**Comment by medariox** [comment]
Can you enable debug logging and post a full log please (of the failing snatch)? Also, deluge should work just fine, this is just about deluge**d**, correct?

**Comment by medariox** [comment]
Nvm, I've just replaced the lib. See https://github.com/pymedusa/Medusa/pull/6279

**Comment by medariox** [comment]
Merged to develop, please update.

**Comment by dotsam** [comment]
Confirmed working with the new library.

**Comment by Yellow1144** [comment]
Hmm. I have been using the develop branch for some time with python 3.5 (now 3.7) with Deluge 1.3.15 and all has been working properly.
