### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: CBC Gem

### ISSUE THREAD

**Issue by gmusgrave** [pymedusa/Medusa#6293]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-03-10 06:36:04 ERROR    Thread_1 :: [918cfe7] Missing time zone for network: CBC Gem
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt
