### ISSUE TITLE
v0.3.0 doesn't start: ensure_text invoked improperly?

### ISSUE THREAD

**Issue by salfter** [pymedusa/Medusa#6324]
I have the latest release of six (1.12.0) installed and Medusa 0.2.14 ran just fine with six 1.11.0, but when Medusa 0.3.0 tries to start, I get this:

```
Traceback (most recent call last):
  File "/usr/share/medusa/SickBeard.py", line 8, in <module>
    from medusa.__main__ import main
  File "/usr/share/medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/usr/share/medusa/medusa/helpers/__init__.py", line 51, in <module>
    from medusa.session.core import MedusaSafeSession
  File "/usr/share/medusa/medusa/session/core.py", line 14, in <module>
    from medusa.session import factory, handlers, hooks
  File "/usr/share/medusa/medusa/session/hooks.py", line 9, in <module>
    from six import ensure_text
ImportError: cannot import name ensure_text
```

**Comment by medariox** [comment]
How did you update? You probably have `.pyc` of the old six version lying around. If you updated manually you should remove the `.pyc` files first. You can do it with git by running `git clean -d -f -x lib ext ext2 ext3` from Medusa's main directory.

**Comment by salfter** [comment]
I maintain a Gentoo ebuild for Medusa (and those of its dependencies that aren't in Portage) and update that when new versions come along.  I started with v0.2.11 and upgraded through to 0.2.14 without issue.  I tried deleting *.pyc; it made no difference.

This shouldn't be necessary (it isn't for any other package I've run across), but I'm rebuilding all installed Python packages as I write this.

**Comment by salfter** [comment]
Rebuilding didn't work.  Deleting all .pyc files in /usr/lib64/python* and /usr/share/medusa yielded a different error:

```
Traceback (most recent call last):
  File "/usr/share/medusa/SickBeard.py", line 8, in <module>
    from medusa.__main__ import main
  File "/usr/share/medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/usr/share/medusa/medusa/naming.py", line 26, in <module>
    from medusa import app, common, logger, tv
  File "/usr/share/medusa/medusa/tv/__init__.py", line 6, in <module>
    from medusa.tv.cache import Cache
  File "/usr/share/medusa/medusa/tv/cache.py", line 31, in <module>
    from medusa.rss_feeds import getFeed
  File "/usr/share/medusa/medusa/rss_feeds.py", line 7, in <module>
    from feedparser.api import parse
ImportError: No module named api
```

**Comment by medariox** [comment]
@salfter 
You need to remove your locale `dev-python/feedparser-5.2.1` and all other external libraries you have installed for the matter. Medusa already includes all libraries it needs. All you should install is Python.

**Comment by salfter** [comment]
I figured it out, and it doesn't involve ignoring system packages and bringing in extra copies of everything.  Medusa is apparently using features not in the current version of feedparser.  I created an ebuild that installs a newer version of feedparser from GitHub (instead of pypi).  With that in place, Medusa fires right up.

**Comment by medariox** [comment]
You can see the exact libraries Medusa uses from the requirements.txt https://github.com/pymedusa/Medusa/blob/master/requirements.txt#L17

**Comment by salfter** [comment]
I'm going through that file right now...about three-fourths of the way through, making sure that all the necessary ebuilds are in place.  (It's running right now, but my approach to resolving dependencies previously was a bit hit-or-miss.  Currently have 23 new/updated ebuilds under dev-python staged for commit to my overlay.)

**Comment by salfter** [comment]
...and it's done.  Ended up with 32 new/updated Python ebuilds, and fixed the initscript so that Medusa runs under Python 3 instead of 2.

https://gitlab.com/salfter/portage
