### ISSUE TITLE
Some shows not appearing since upgrade to 0.3.0

### ISSUE THREAD

**Issue by canadria** [pymedusa/Medusa#6343]
INFO
Python Version: 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
Operating System: Linux-4.9.0-8-amd64-x86_64-with-debian-9.8
Locale: UTF-8
Branch: master
Database: 44.14
Commit: 94fae847b6e7e443d74c59cb11bdbd37c464b363 Version: 0.3.0 
OS: Windows-10-10.0.17763

Since my upgrade this afternoon to 0.3.0, several shows have disappeared from the show list, but they continue to appear on the schedule. If I click on the show in the schedule, it says "Error
Show not in show list". If I try to add the show manually, it won't add because it thinks the show is already present.

For each show, there is then a corresponding error in the logs that shows

2019-03-13 19:28:54 ERROR    MAIN :: [94fae84] There was an error creating the show in E:\TV Shows\Russian Doll: Exception generated: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\__main__.py", line 2122, in load_shows_from_db
    cur_show = Series(sql_show['indexer'], sql_show['indexer_id'])
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 245, in __init__
    self._load_from_db()
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 1493, in _load_from_db
    self.airdate_offset = int(sql_results[0]['airdate_offset'])
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by medariox** [comment]
Seems like the DB update didn't work as expected for you. You should replace your current `main.db` with the backup-ed one (should be called main.db.v44.13) and try again. 

**Steps:**
1. Shut down Medusa 
2. Rename your current main.db to main.db.old
3. Rename main.db.v44.13 to main.db
4. Start Medusa
5. Let it update (it can take some time!)
6. If all went well, delete main.db.old

**Comment by canadria** [comment]
Ack! I wish I had read that earlier. 

I wrote a SQL query to scan and remove the 47 broken shows, and manually re-added them and they seem to be working now.

**Comment by medariox** [comment]
Glad you got is solved anyway.
