### ISSUE TITLE
WARNING  Thread_27 :: [918cfe7] git rev-parse HEAD returned : fatal: bad config line 1 in file .git/config... and ....WARNING  Thread_27 :: [918cfe7] git symbolic-ref -q HEAD returned : fatal: bad config line 1 in file .git/config

### ISSUE THREAD

**Issue by fire222** [pymedusa/Medusa#6349]
keep getting errors every time it tries to install the update

**Comment by medariox** [comment]
Your `.git/config` file is damaged. Try removing it.

**Comment by fire222** [comment]
thanks for the info ..after deleting .git/config ....now the error is
 [918cfe7] git rev-parse --verify --quiet "@{upstream}" returned : fatal: no upstream configured for branch 'master'

**Comment by medariox** [comment]
Try setting the remote with:
```
git remote set-url origin https://github.com/pymedusa/Medusa.git
```

**Comment by fire222** [comment]
sorry no idea how to set that or were it is

**Comment by medariox** [comment]
Execute that command from within Medusa's main directory.

**Comment by fire222** [comment]
I'm using this on windows 10..were would I find it in medusa's main directory..don't see it anywhere

**Comment by medariox** [comment]
I assume you installed Medusa with the installer?

In the Medusa folder you should have a git folder, there should be a git.exe inside. 
Open `cmd` and run 
`cd <path to medusa>Medusa/Medusa`
now you should be in the Medusa folder.
now run
 `<path to medusa>git/git.exe remote set-url origin https://github.com/pymedusa/Medusa.git`

**Comment by fire222** [comment]
ok thanks for the help
