### ISSUE TITLE
0.3.0 nothing is downloading anymore

### ISSUE THREAD

**Issue by kikinjo** [pymedusa/Medusa#6350]
Error while sending torrent: UnicodeDecodeError('ascii', '</i8></value>\r\n<value><i8>2097152</i8></value>\r\n<value><i8>4</i8></value>\r\n<value><string>Black Sabbath - Black Box-The Complete Original Black Sabbath 1970\xe2\x80\x931978 (2004) [R2 73923 Anthology CD] - FLAC</string></value>\r\n<value><i8>1551916780</i8></value>\r\n<value><i8>0</i8></value>\r\n<value><string>/home/xbmc/downloads/zlong seed/Black Sabbath - Black Box-The Complete Original Black Sabbath 1970\xe2\x80\x931978 (2004) [R2 73923 Anthology CD] - FLAC</string></value>\r\n<value><i8>0</i8></value>\r\n<value><i8>1</i8></value>\r\n<value><i8>1</i8></value>\r\n<value><string>2D6C74304436302DA4C8D9CDB2E9A1670352168E</string></value>\r\n<value><i8>735</i8></value>\r\n<value><string>/home/xbmc/downloads/.session/83A81A565DD57EA843AB3169964B138776EDB9E6.torrent</string></value>\r\n<value><i8>137438953472</i8></value>\r\n<value><i8>1170</i8></value>\r\n<value><i8>0</i8></value>\r\n<value><i8>0</i8></value>\r\n<value><string>FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF', 156, 157, 'ordinal not in range(128)')

**Comment by medariox** [comment]
Open a proper issue report with debug logs https://github.com/pymedusa/Medusa/issues/new?template=bug_report.md
