### ISSUE TITLE
The soupsieve package is not installed. CSS selectors cannot be used.

### ISSUE THREAD

**Issue by Trotter73** [pymedusa/Medusa#6359]
Hi,

Windows 10 (64bit)
Python 2.7.15

Just blindly updated, to the 0.3.0, after the update I read the wiki, sorry..

When starting I now see the warning below in the console when Medusa starts.

C:\Utils\Medusa\ext2\bs4\element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
The soupsieve package is not installed. CSS selectors cannot be used

I have tried "pip install beautifulsoup4" & "pip install soupsieve" both appear to be installed OK.

It looks like the issue has been reported previously but reported as fixed (#5968).

Do I need to update my Python now or am I good for a bit ?

Ta.

**Comment by medariox** [comment]
Where are the debug logs? Open an issue with the proper template.

**Comment by AlexanderAmelkin** [comment]
@Trotter73, you may be missing some other module. Error reporting in Python is awful as usual.
Try running `python` interactively and run `import soupsieve` there.
For me in a similar situation it gave the following printout:

```
>>> import soupsieve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/soupsieve/__init__.py", line 30, in <module>
    from . import css_parser as cp
  File "/usr/local/lib/python2.7/dist-packages/soupsieve/css_parser.py", line 4, in <module>
    from . import util
  File "/usr/local/lib/python2.7/dist-packages/soupsieve/util.py", line 25, in <module>
    from backports.functools_lru_cache import lru_cache  # noqa F401
ImportError: No module named functools_lru_cache
```
So apparently it lacks the `functools_lru_cache` module in my setup, but wouldn't say that when imported from beautifulsoup4 because (I figure) they are doing try/catch there.

**Comment by Trotter73** [comment]
Hi,

Thanks for the reply, I never got a resolution using Python 2, even after posting using the PROPER template and gave up an ignored the error.

It went away when I updated to Python 3 for reference.
