### ISSUE TITLE
Medusa not working with pythonw on Windows

### ISSUE THREAD

**Issue by SunMar** [pymedusa/Medusa#6370]
Hi,

Today I upgraded to the new 0.3.0 and also upgraded to Python 3.7.2 (from 2.7), but now Meduse won't work using `pythonw` anymore. When I launch via pythonw I see the pythonw process appear and almost immedately shutdown again. Since it's pythonw there is no output, and nothing appears in the application log either. I've tried to debug a bit but I'm stuck. As soon I put in `start.py` the line:

```
sys.stderr = open('stderr.txt', 'a')
```

To try and catch any errors, Medusa actually magically starts working, but the log file remains empty (I've verified I am opening the correct file by actually writing something to it, when I do that my write appears in the log file but still nothing else).

My guess is something in the code tries to access `sys.stderr`, but since that's not available when running with `pythonw` the code breaks and the process exits. However because I'm not a Python developer I don't have any proper tools like step-debugging to find out exactly where it fails :(.

**Comment by medariox** [comment]
What happens if you try to start it with `python.exe`?

**Comment by SunMar** [comment]
@medariox Sorry looks like I forgot to explictly mention that, but starting with `python.exe` (without any adjustments ofc) works fine. It is specially when starting with `pythonw.exe` that it immediately exits unless I add that `syslog.stderr = ...` line.

**Comment by sharkykh** [comment]
@medariox 
AFAIK, Since `pythonw` doesn't provide a console window, methods like `print` / `sys.stdout.write` / etc. throw an exception.

**Comment by sharkykh** [comment]
@SunMar 
Try running Medusa with the `--quiet` (or `-q`) argument.

**Comment by SunMar** [comment]
@sharkykh from what I read ([source](https://stackoverflow.com/questions/24835155/pyw-and-pythonw-does-not-run-under-windows-7)), `print` throws an exception in Python 2.x (though the older Medusa version always ran fine under Python 2.7) but that was fixed in Python 3.x. In Python 3.x you don't get an exception anymore when you use `print()` while running in `pythonw`. I don't know about other functions.

As for `--quiet`, I'm actually already using that (probably because otherwise Medusa would fail to start under Python 2.7), my full startup line is:
```
"C:\Program Files\Python37\pythonw.exe" "X:\Medusa\Medusa\start.py" --nolaunch --quiet --datadir "X:\Medusa\Data" --config "X:\Medusa\Data\config.ini"
```

As mentioned before, when either I change `pythonw.exe` to `python.exe`, or if I add `sys.stderr = open('stderr.txt', 'a')` at the top of `start.py` then Medusa starts fine (but `stderr.txt` remains empty).

I have also tried encapsulating the call to `main()` in `start.py` in a `try:` / `except:` and then in the `except:` write something to a log file, but strangely enough it nothing was written to my log file suggesting it never got into the `except:` , so it doesn't look to be an exception, though as I've mentioned before, I'm not a Python developer so I could be doing something wrong there. Basically I've tried applying what's mentioned in [this SO answer](https://stackoverflow.com/questions/33844314/python-script-failing-under-pythonw) both with the logger that's mentioned there (in which case I did see some log lines end up in the file, but not the write from inside the `except:`) and with a simple `open('stderr.txt', 'w')`. I know the `open` is working because if I do something like `log = open('stderr.txt', 'w')` at the top followed by `log.write('starting...')`, I see the `starting...` appear in the file, but any `log.write(...)` inside the `except:` is not written to the file.

That's also why I'm kind of lost on what else I can try. Normally I'd just get out a step debugger and step through the code until I find the place where it's failing, but I don't have that setup for Python. If anyone knows of a quick and easy howto on how I could set that up for Python with minimal effort I don't mind giving that a shot to figure out the root cause.

**Comment by sharkykh** [comment]
After the initial application load, Medusa starts writing to log files. Have you checked `X:\Medusa\Data\Logs\application.log` for errors? (Or any other log entries)

**Comment by SunMar** [comment]
@sharkykh Yes, unfortunately nothing is written to `application.log` (unless I add my workaround and Medusa starts as normal). So the problem appears to be before Meduse writes its first entry to `application.log`.

**Comment by sharkykh** [comment]
Well, I changed `start.py` to the code below, and I got this error:
```
sys.stderr is None
```
Medusa still didn't start up. So that's probably the error you're getting.

```py
#!/usr/bin/env python
# -*- coding: utf-8 -*
"""Startup script."""
from __future__ import unicode_literals

import sys

try:
    from medusa.__main__ import main

    if __name__ == '__main__':
        if sys.version_info.major == 3 and sys.version_info.minor < 5:
            print('Medusa supports Python 2 from version 2.7.10 and Python 3 from version 3.5.0, exiting!')
            raise Exception('Incorrect Python version. Shutting down!')
        main()

except Exception as e:
    with open('stderr.txt', 'w') as fh:
        fh.write(str(e))
```

**Comment by sharkykh** [comment]
And FWIW, just fixing the exception above, allows Medusa to start up...
https://github.com/pymedusa/Medusa/blob/e01912a32739984ac683a846d30352a019665448/lib/unrar2/windows.py#L37-L39
```py
if sys.version_info > (3,3):
    import faulthandler
    with open(os.devnull, 'a+') as fh:
        faulthandler.enable(file=fh)
```

**I'm not 100% sure about this code.** This seems a bit hacky.

**Comment by medariox** [comment]
@sharkykh Wouldn't it make more sense to just remove the `faulthandler` import at this point?

**Comment by sharkykh** [comment]
I never used it and I don't understand its use case.
I just wanted to point out that this seems to be the only issue preventing it from working when using `pythonw`...

**Comment by SunMar** [comment]
@sharkykh I just ran `start.py` with the same try/except as you and I can confirm that I'm getting the same error as you.

Note that this issue is new in 0.3.0, the 0.2.x version worked fine with `pythonw.exe`.

**Comment by SunMar** [comment]
@medariox @sharkykh any idea if this can be solved?

I have to have automatic updates disabled right now, because it appears Meduse does a hard reset when updating, destroying my temporary fix. Then when I update I each time have to manually put the hotfix back to make it start up again.

**Comment by sharkykh** [comment]
@SunMar You can try the latest commit on `develop`.

**Comment by SunMar** [comment]
@sharkykh I've just switched to develop (after removing my local changes) and Medusa now starts up fine with `pythonw`. thank you! :)
