### ISSUE TITLE
Checkbox filter controls on displayShow page all have 0 except Skipped:

### ISSUE THREAD

**Issue by rotech** [pymedusa/Medusa#6372]
On the displayShow page the checkbox status filter controls all have 0 except Skipped:  This is the same on all show pages.  The boxes do work, and filter correctly - it's just the number is always 0.

![image](https://user-images.githubusercontent.com/610055/54484961-4d158280-48d5-11e9-85a9-95e2942da8f5.png)

 - OS: Archlinux
 - Branch: master
 - Commit: 94fae847b6e7e443d74c59cb11bdbd37c464b363
 - Tag: v0.3.0

Not sure if it's related or should be in another bug report, but if I select episodes using the checkboxes (i.e. filter to show only Allowed:) then use the "Select Episodes" button and change the status or quality, the change only happens on a seemingly random portion of the selected episodes.  There are no errors in the debug logs.

**Comment by rotech** [comment]
I just had a quick check (which I should have done before, sorry) this is also present in the "develop" branch.

**Comment by sharkykh** [comment]
Looks like an unintended change made to the way the numbers are calculated.
### Currently:
https://github.com/pymedusa/Medusa/blob/0e67cec293ec41146feb59f32b8fd1af0bbea869/themes-default/slim/src/components/show-header.vue#L401-L422
### Before #6189:
https://github.com/pymedusa/Medusa/blob/d7a3769128ef5a11e7fc1b067e2865733a31aaa0/medusa/server/web/home/handler.py#L903-L919

[The current JavaScript code results in these values.](https://user-images.githubusercontent.com/10238474/55171213-9b9e0900-5180-11e9-8685-1881a8f860fe.png)
Notice that the Python code used the `Overview` class and not `Quality`.
This matters because of what `Overview.QUAL` and `Overview.GOOD` mean...
https://github.com/pymedusa/Medusa/blob/0e67cec293ec41146feb59f32b8fd1af0bbea869/medusa/common.py#L776-L786

**Comment by p0psicles** [comment]
Tnx shark. I'll dive into that in the vue-good-table pr.

**Comment by eddywitkamp** [comment]
I also had non-zero numbers on the Skipped label, but I found out that the SPECIALS were hidden and guess what...those Specials had the Skipped label. Once I changed the label of the Specials, I had 0 Skipped again.

**Comment by medariox** [comment]
Should be fixed

**Comment by rotech** [comment]
Still not fixed for "Allowed" but working for others.

**Comment by p0psicles** [comment]
So allowed, always shows 0 for you?

**Comment by eddywitkamp** [comment]
For me, did a quick look at some shows, and Allowed is always at 0.

And the Archived ones are always shown, they should get a filter too.

**Comment by p0psicles** [comment]
You got a screenshot of where it's not properly displayed? Include the quality setting

**Comment by rotech** [comment]
Showing with all selected:
![Screenshot_Normal](https://user-images.githubusercontent.com/610055/76593506-5e7e8280-655b-11ea-900c-d03c95c2f961.png)

Here, you can see that the "Allowed" checkbox works as it should, but still shows 0
![Screenshot_Selected](https://user-images.githubusercontent.com/610055/76593519-64746380-655b-11ea-9adc-7624cc77f314.png)

**Comment by p0psicles** [comment]
Screenshot of the shows settings?

**Comment by rotech** [comment]
Show settings
![Settings](https://user-images.githubusercontent.com/610055/76607285-9942e380-6578-11ea-8df6-74210d2d7e0e.png)

**Comment by p0psicles** [comment]
I understand. But why would you change the episodes to "allowed"? If your using a preset like hd720p there is no distinction between preferred and allowed. And our current rules assume a downloaded episode as preferred.

**Comment by eddywitkamp** [comment]
Shouldn't the colors match the filters?
I see 2 yellow rows, in that screenshot, I assume that would mean Allowed = 2

**Comment by rotech** [comment]
> I understand. But why would you change the episodes to "allowed"? If your using a preset like hd720p there is no distinction between preferred and allowed. And our current rules assume a downloaded episode as preferred.

I was just saying that as a way to replicate the bug, and these filters do differentiate between preferred and allowed when you use them as in the example I gave.  In the original bug all the filters worked, they just all had 0 for the number of episodes they had "tagged"?.  That issue has been fixed for all the filters except allowed.

Yes, as eddywitkamp says above, in the example I gave "Allowed" should say 2.

**Comment by p0psicles** [comment]
Yeah I get the issue. We kinda fixed this issue with a workaround. And this is the result of what you get when using workaround.

**Comment by rotech** [comment]
I've been digging around with my very limited skills, and it (looks to me like) it is getting the numbers from episodeSummary() in show-header.vue

When it calls getOverviewStatus in consts.js, that function is returning an empty string for the allowed episodes, i.e. the structure below does not hit the return.

https://github.com/pymedusa/Medusa/blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/themes-default/slim/src/store/modules/consts.js#L97-L99

**Comment by rotech** [comment]
OK, I think I have at bit more info to add here. I think that if an episode status is downloaded, but the quality is not preferred or allowed, it falls into a bit of a hole, and gets lumped in with the allowed.

Just adding the following into the checkboxControls structure was enough to have the episodes counted correctly, and it all works.  The styling is wrong, I haven't dug into that yet - but the functionality works.

`
{
    id: 'downloaded',
   checked: true,
   name: 'Downloaded'
},
`

![Screenshot_20200322_125823](https://user-images.githubusercontent.com/610055/77239212-db38ed00-6c3c-11ea-9e90-54a588d17a91.png)
