### ISSUE TITLE
Recommended Show Issues

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#6388]
Hi Team

Since i updated docker to the latest version i am getting this when i try and look for Recommend Shows

**No module named ordered_dict**

Thanks

**Comment by medariox** [comment]
Delete `recommended.dbm` in your cache folder.

**Comment by HPMSGEN8** [comment]
Thanks Solved :)

**Comment by Tailslide** [comment]
I got the same error and tried removing this file then I got a different error: 

"need 'c' or 'n' flag to open new db"

**Comment by Tailslide** [comment]
Nevermind.. restarting medusa fixed it
