### ISSUE TITLE
Medusa stopped connecting to Deluge

### ISSUE THREAD

**Issue by homegreewn** [pymedusa/Medusa#6389]
It was working fine but now I get this error:

2019-03-20 12:54:57 WARNING  Thread_19 :: [94fae84] Error while testing deluged connection: cannot import name DelugeRPCClient

I can still connect to deluge daemon remotely without issues. Only Medusa cannot connect to it. 

Any help is greatly appreciated.

**Comment by p0psicles** [comment]
Search the issues here. Solutions are provised

**Comment by homegreewn** [comment]
I have been searching for about 5 hours with no success. Do you mind posting a link to the solution? The closest I have found but I am not sure if its the correct solution is updating to Python3.7 do you think this is the right path? Ty for your response.

**Comment by p0psicles** [comment]
Delete all *.pyc files recursive. Then start. That should fix it.

**Comment by medariox** [comment]
Or update to version 0.3.1, that should fix it as well.

**Comment by homegreewn** [comment]
thank you both for your replies, I just saw them and since I was troubleshooting by myself I decided to install python3.6. I succesfully installed it but now medusa won't start. I changed 2.7 to 3.6 in the medusa.service (only 1 line of code had to be changed). 

Now since I updated to python3 i thought i shouldnt delete *.pyc files. If I do need to please confirm (will that delete my deluge settings in my medusa, so i can back them up?)

@medariox How do I update to 0.3.1 without scerwing up my profile?

@p0psicles 

Again, ty for ur help

**Comment by homegreewn** [comment]
`pi@raspberrypi:/opt/medusa $ sudo systemctl start medusa
Job for medusa.service failed because the control process exited with error code.
See "systemctl status medusa.service" and "journalctl -xe" for details.
pi@raspberrypi:/opt/medusa $ systemctl status medusa.service
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-03-20 21:12:24 EDT; 11s ago
  Process: 10161 ExecStart=/usr/bin/python3.6 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa (code=exited,

Mar 20 21:12:24 raspberrypi systemd[1]: Starting Medusa Daemon...
Mar 20 21:12:24 raspberrypi systemd[1]: medusa.service: Control process exited, code=exited status=203
Mar 20 21:12:24 raspberrypi systemd[1]: Failed to start Medusa Daemon.
Mar 20 21:12:24 raspberrypi systemd[1]: medusa.service: Unit entered failed state.
Mar 20 21:12:24 raspberrypi systemd[1]: medusa.service: Failed with result 'exit-code'.
lines 1-10/10 (END)
`

**Comment by homegreewn** [comment]
`asdf`

**Comment by homegreewn** [comment]
`pi@raspberrypi:/opt/medusa $ sudo systemctl start medusa
Job for medusa.service failed because the control process exited with error code.
See "systemctl status medusa.service" and "journalctl -xe" for details.
pi@raspberrypi:/opt/medusa $ systemctl status medusa.service
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-03-20 21:12:24 EDT; 11s ago
  Process: 10161 ExecStart=/usr/bin/python3.6 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa (code=exited,

Mar 20 21:12:24 raspberrypi systemd[1]: Starting Medusa Daemon...
Mar 20 21:12:24 raspberrypi systemd[1]: medusa.service: Control process exited, code=exited status=203
Mar 20 21:12:24 raspberrypi systemd[1]: Failed to start Medusa Daemon.
Mar 20 21:12:24 raspberrypi systemd[1]: medusa.service: Unit entered failed state.
Mar 20 21:12:24 raspberrypi systemd[1]: medusa.service: Failed with result 'exit-code'.
lines 1-10/10 (END)
`

**Comment by homegreewn** [comment]
`test`

**Comment by homegreewn** [comment]
`pi@raspberrypi:/opt/medusa $ sudo systemctl start medusa
Job for medusa.service failed because the control process exited with error code.
See "systemctl status medusa.service" and "journalctl -xe" for details.
pi@raspberrypi:/opt/medusa $ systemctl status medusa.service
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-03-20 21:12:24 EDT; 11s ago
  Process: 10161 ExecStart=/usr/bin/python3.6 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa (code=exited,

Mar 20 21:12:24 raspberrypi systemd[1]: Starting Medusa Daemon...
Mar 20 21:12:24 raspberrypi systemd[1]: medusa.service: Control process exited, code=exited status=203
Mar 20 21:12:24 raspberrypi systemd[1]: Failed to start Medusa Daemon.
Mar 20 21:12:24 raspberrypi systemd[1]: medusa.service: Unit entered failed state.
Mar 20 21:12:24 raspberrypi systemd[1]: medusa.service: Failed with result 'exit-code'.
lines 1-10/10 (END)`

**Comment by homegreewn** [comment]
/usr/bin/python3.6 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa
bash: /usr/bin/python3.6: No such file or directory

**Comment by homegreewn** [comment]
pi@raspberrypi:~ $ python3.6 -V
Python 3.6.5

**Comment by papampi** [comment]
Hi,
New to Medusa, coming from sickchill

Sorry to bring up the old issue but cant solve this on fresh install on Qnap.
On fresh install after update, shut it down, removed all .pyc from Medusa folder, start it again and it still keeps giving the error and cant connect to deluge

Medusa Info: 

 ```
Branch: masterCommit: fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4bVersion: 0.3.7Database: 44.14
 Python Version:  2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]
 SSL Version:  OpenSSL 1.0.2k 26 Jan 2017
 OS:  Linux-4.14.24-qnap-x86_64-with-glibc2.2.5
 Locale:  en_US.UTF-8
```

**Comment by medariox** [comment]
Hey! That's a bit too generic to help. What is your setup? Any debug logs? Do you have the IP:Port starting with `scgi://` (if using the daemon)?

**Comment by papampi** [comment]
Medusa debug log only shows:
```
2019-11-26 19:07:58 WARNING	Thread-4 :: [fcb5a19] Error while testing deluged connection: cannot import name DelugeRPCClient
2019-11-26 19:06:40 WARNING	Thread :: [fcb5a19] Error while testing deluged connection: cannot import name DelugeRPCClient
2019-11-26 19:06:39 WARNING	Thread :: [fcb5a19] Error while testing deluged connection: cannot import name DelugeRPCClient
```

deluge 1.3.15, Connecting via daemon scgi://127.0.0.1:58846/ with same user/pass as sickchill connects to with no problem.

**Comment by papampi** [comment]
Also tried with stopped Sickchill and still same error.

**Comment by medariox** [comment]
You are missing files from Medusa. I'm not sure how you are installing Medusa, but it's not right.

**Comment by papampi** [comment]
Installed qpkg from qnapclub.eu
https://qnapclub.eu/en/qpkg/426

**Comment by medariox** [comment]
That package is over a year old. You will have to ask the maintainer to update it.
Otherwise, try to use sherpa.sh: https://forum.qnap.com/viewtopic.php?t=132373

**Comment by papampi** [comment]
Thanks mate.
Will check it later, when I get a bit of time.

**Comment by papampi** [comment]
Just an info for others whom got into this problem
Shutdown Medusa, Install QPython3.7 , remove all .pyc, edit python path in medusa.sh 
from:
`export PYTHON=$QPKG_ROOT/bin/python 
`
to:
`export PYTHON=/share/CACHEDEV1_DATA/.qpkg/QPython3/bin/python3`
