### ISSUE TITLE
I used windows installer to install 	Branch: master  v0.2.14 ..how do I upgrade to 0.3.0?

### ISSUE THREAD

**Issue by fire222** [pymedusa/Medusa#6410]
I thought the auto update was working but it looks like it didn't update to 0.3.0 it's still on v0.2.14..do I need to manually update that somehow?

**Comment by medariox** [comment]
Disable auto update and update manually.

**Comment by fire222** [comment]
ok thanks...do I copy over the old one or delete the old one..and will I lose all my settings?

**Comment by medariox** [comment]
When there is a new version available you get notified and can press a button to execute the update. Otherwise you can just overwrite the old files with the new ones. You won't loose any settings.

**Comment by fire222** [comment]
ok thanks for the help
