### ISSUE TITLE
After updating to python3 server status is showing all tasks inactive

### ISSUE THREAD

**Issue by Lulu300** [pymedusa/Medusa#6411]
**Describe the bug**
Since i've updated medusa to python3, when i go check server status tabs, it says that all tasks are inactive but they are working.
Here's my medusa.service : 
```SH
# Medusa systemd service unit file
#
# Configuration Notes
#
#    - Option names (e.g. ExecStart=, Type=) are case-sensitive)
#
#    - Adjust User= and Group= to the user/group you want Medusa to run as.
#
#    - Optional adjust EnvironmentFile= path to configuration file
#        Can ONLY be used for configuring extra options used in ExecStart.
#        Putting a minus (-) in front of file means no error warning if the file doesn't exist
#
#    - Adjust ExecStart= to point to your python and Medusa executables.
#       The FIRST token of the command line must be an ABSOLUTE FILE NAME,
#       then followed by arguments for the process.
#       If no --datadir is given, data is stored in same dir as start.py
#       Arguments can also be set in EnvironmentFile (except python)
#
#    - WantedBy= specifies which target (i.e. runlevel) to start Medusa for.
#        multi-user.target equates to runlevel 3 (multi-user text mode)
#        graphical.target  equates to runlevel 5 (multi-user X11 graphical mode)
#

### Example Using Medusa as daemon with pid file
# Type=forking
# PIDFile=/var/run/PyMedusa/Medusa.pid
# ExecStart=/usr/local/bin/python3.7 /opt/medusa/start.py -q --daemon --nolaunch --pidfile=/var/run/PyMedusa/Medusa.pid --datadir=/opt/medusa

## Example Using Medusa as daemon without pid file
# Type=forking
# GuessMainPID=no
# ExecStart=/usr/local/bin/python3.7 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa

### Example Using simple
# Type=simple
# ExecStart=/usr/local/bin/python3.7 /opt/medusa/start.py -q --nolaunch

### Example Using simple with EnvironmentFile where APP_DATA=/home/medusa/.medusa in /etc/medusa.conf
# Type=simple
# EnvironmentFile=/etc/medusa.conf
# ExecStart=/usr/local/bin/python3.7 /opt/medusa/start.py -q --nolaunch --datadir=${APP_DATA}

### Configuration

[Unit]
Description=Medusa Daemon
After=network.target

[Service]
User=medusa
Group=medusa

Type=forking
GuessMainPID=no
ExecStart=/usr/local/bin/python3.7 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa

[Install]
WantedBy=multi-user.target
```

**To Reproduce**
1. Go to 'Server Status'
2. See error

**Expected behavior**

**Screenshots**
![firefox_2019-03-24_10-25-57](https://user-images.githubusercontent.com/12187295/54877503-f3a2db80-4e1f-11e9-8d68-b3814f83c0dc.png)

**Medusa (please complete the following information):**
![firefox_2019-03-24_10-27-41](https://user-images.githubusercontent.com/12187295/54877497-dff77500-4e1f-11e9-9509-728ab2a191ce.png)

**Logs:**
<details>

```
<-- Please replace this whole line with your logs -->
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Change to type=simple

**Comment by medariox** [comment]
You have to use the new systemd https://github.com/pymedusa/Medusa/blob/master/runscripts/init.systemd

**Comment by jtwill** [comment]
Why does Medusa now require type=simple in systemd? It worked with type=forking previously. The example systemd file certainly makes it look like forking is an option. But the person reporting this bug was told that they must use type=simple. Either this is a real bug in Medusa, or else the example systemd file must be changed to make it clear that type-forking is not an option.

**Comment by p0psicles** [comment]
We changed the example systemd file to simple? We could add some comments to the file?

Regarding forking not working. We don't know why. So if some Linux guru can explain us, we would be very welcome.

I doubt it's a bug in Medusa though.
