### ISSUE TITLE
UNC Path support on Windows

### ISSUE THREAD

**Issue by canadria** [pymedusa/Medusa#6418]
It would be incredibly handy if Medusa (on Windows) supported UNC paths without drive mappings.

For example

"\\server\share\tvshows"

This is not a game changing feature, but would be a nice to have.

**Comment by xbette** [comment]
Just the problem i have also. Hope this will be added very soon!

**Comment by Rouzax** [comment]
Best way to solve this is not to add a network drive but a Symlink to the network location because that is available for all users that are logged in.

https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by canadria** [comment]
It doesn't work.

I actually use multiple Symlinks and Medusa will not follow the links.

**Comment by Rouzax** [comment]
I've been using symlinks on windows since the time of Sickbeard so it does work.
If it doesn't for you check the account under which Medusa runs has access to the network path.

**Comment by canadria** [comment]
So, I got it working. The permissions were OK, but it looks like the problem was on the share itself. I deleted the share on the NAS and recreated it and the symlinks and they work now.

Interestingly enough, UNC paths work now, so I guess this can just go to the archive pile.

**Comment by canadria** [comment]
Thank you for the help!

**Comment by xbette** [comment]
:/ No matter WHAT i do, nothing works for me. i've tried to create a new share on my private NAS server, doesn't work. 

I've tried between to windows servers (my local servers) Nothing works. :( 

no matter how i make the symlink then medusa can't see the stuff inside the folder

**Comment by Rouzax** [comment]
What is the account which is used to run Medusa?
Is it on Windows, Linux, NAS?

**Comment by xbette** [comment]
Meduser is runned on the Administrator account at my windows server 2008

**Comment by Rouzax** [comment]
As a service? 
If so please check your services.msc to see the actual user running it, by default it will often default to System.
If it is Administrator make sure that account has write access to your NAS.

**Comment by xbette** [comment]
When im in services.msc and do a properties on the "medusa" then its logged on as "local system account"

**Comment by Rouzax** [comment]
So you're not running as Administrator but a local System account which by design does not have rights to any network resources. Change the run as a count of the service to the desired user.

**Comment by xbette** [comment]
I just got it working by change the user account on the service to "Administrator"

THANKS!!!
