### ISSUE TITLE
Preferred Quality Not Displaying on Show Pages/Not DL'ing Preferred Quality

### ISSUE THREAD

**Issue by bobbydigital24** [pymedusa/Medusa#6420]
I'm not sure if I missed something, but my shows no longer show "Quality Preferred" under "Quality allowed".

I typically set allowed to SDTV, SDDVD, etc while setting preferred to all 720p.

I just added a new show and while the default quality settings were still in place and visible on the "add new show" page as well as the "edit show" page, they do not display on the show homepage and the settings do not seem to affect how the different episode qualities are displayed in terms of allowed or preferred. (See Screenshots below).
![image](https://user-images.githubusercontent.com/29279909/55111774-7ee6d000-50b1-11e9-93ac-c991268c1e44.png)
 

![Snipaste_2019-03-27_16-43-38](https://user-images.githubusercontent.com/29279909/55111371-9ec9c400-50b0-11e9-8e77-2271b9b4963e.jpg)

It is displaying SDTV downloads as 'green', or as preferred downloads in some cases. I've gone in and reselected the preferred qualities and reapplied and this does not change.

Even if I change it to a standard setting like HD720p all the way through, these SDTV episodes still show as preferred.
![image](https://user-images.githubusercontent.com/29279909/55113400-7c867500-50b5-11e9-8ba4-a5ca68b26d12.png)

Typically I'd expect to see all SDTV downloads as yellow/'allowed' until it replaced it with a green/'preferred' upgrade.

That no one else has reported anything like this yet makes me think it's something on my end. What am I missing?

The logs don't have much but some search result exclusions.

**Medusa (please complete the following information):**
 - OS: QNAP QTS 4.3.6.0883 x64
 - Branch: master
 - Commit: [b34f1df336e52cf0a690acbc393440ac9f8b3581 ](https://github.com/pymedusa/Medusa/commit/b34f1df336e52cf0a690acbc393440ac9f8b3581)

**Logs:**
[medusa_log_20190327.txt](https://github.com/pymedusa/Medusa/files/3015277/medusa_log_20190327.txt)

<details>

```
<-- Please replace this whole line with your logs -->
```
</details>

**Additional context**

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7415
