### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: TV2 (NZ)

### ISSUE THREAD

**Issue by creoden** [pymedusa/Medusa#6423]
### INFO
**Python Version**: `2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@b34f1df336e52cf0a690acbc393440ac9f8b3581
**Link to Log**: https://gist.github.com/f98f52a7fec71830d913a9cab2b10766
### ERROR
<pre>
2019-03-28 19:27:47 ERROR    Thread_10 :: [b34f1df] Missing time zone for network: TV2 (NZ)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/2e7e0b56e899224d44e91b634df4fc673753fdc3
