### ISSUE TITLE
Multi language when adding show

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#6429]
Hi,

**Is your feature request related to a problem? Please describe.**
When I had an episode who haven't french name, the field still empty...

**Describe the solution you'd like**
When the episode name doesn't exist in main language, Medusa should had a second language information like English

It's possible like other fork ?

Rgds
akhlan

**Comment by p0psicles** [comment]
Well, not without needing to do allot of extra api calls. The other fork is probably sickchill. And they still use the deprecated tvdb api v1

**Comment by medariox** [comment]
Yeah also don't really see the need for it. You can (and probably should) add the missing episode names to the indexers, so other people can benefit from it. Closing as it's not going to happen anyway.

**Comment by akhlan** [comment]
The french name doesn't exist, i can't do that....

**Comment by p0psicles** [comment]
You can't go to the tvdb site. Login. And change titles for episodes? It's crowd sourced right?

**Comment by akhlan** [comment]
No the title haven't been choose yet....
