### ISSUE TITLE
[APP SUBMITTED]: qbittorrent: Unable to set priority for Torrent

### ISSUE THREAD

**Issue by bmn001** [pymedusa/Medusa#6431]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:12) [GCC 4.6.4]`
**Operating System**: `Linux-2.6.32.12-armv5tel-with-glibc2.4`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@b34f1df336e52cf0a690acbc393440ac9f8b3581
**Link to Log**: https://gist.github.com/72e4a79d253074d26152391dbc3c4c03
### ERROR
<pre>
2019-03-30 01:05:12 ERROR    SNATCHQUEUE-SNATCH-268009 :: [b34f1df] qbittorrent: Unable to set priority for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
It's an error in qbittorrent. Torrent was already added?

**Comment by madtempest** [comment]
### INFO
**Python Version**: `2.7.16 (default, Apr 11 2019, 01:11:37) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/fad21e9df90789a989635ad45eb43686
### ERROR
<pre>
2019-05-20 17:33:04 ERROR    SNATCHQUEUE-SNATCH-121361 :: [f46bfac] qbittorrent: Unable to set priority for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by madtempest** [comment]
### INFO
**Python Version**: `2.7.16 (default, Apr 11 2019, 01:11:37) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/95f1583aae4aa88882153a06b47305eb
### ERROR
<pre>
2019-05-23 21:31:15 ERROR    SNATCHQUEUE-SNATCH-358211 :: [f46bfac] qbittorrent: Unable to set priority for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by madtempest** [comment]
### INFO
**Python Version**: `2.7.16 (default, Apr 11 2019, 01:11:37) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/9578bb7447d4db0bbc54c04653b8f645
### ERROR
<pre>
2019-05-25 04:54:30 ERROR    SNATCHQUEUE-SNATCH-360893 :: [f46bfac] qbittorrent: Unable to set priority for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by madtempest** [comment]
### INFO
**Python Version**: `2.7.16 (default, Apr 11 2019, 01:11:37) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/66ffcb365b165c8f20d91e922d264ac2
### ERROR
<pre>
2019-06-04 18:34:53 ERROR    SNATCHQUEUE-SNATCH-360893 :: [f46bfac] qbittorrent: Unable to set priority for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
