### ISSUE TITLE
quality preferred not displaying

### ISSUE THREAD

**Issue by jxer** [pymedusa/Medusa#6453]
quality preferred no longer displaying, 2 servers confirmed having same issue

https://i.imgur.com/b1EueoQ.png

Branch: master
Commit: b34f1df336e52cf0a690acbc393440ac9f8b3581
Version: 0.3.1

**Comment by sharkykh** [comment]
can confirm.
https://github.com/pymedusa/Medusa/blob/9e9fb070b7b38b522fb425624c9ee8eaa3fbcc80/themes-default/slim/src/components/show-header.vue#L147

I think
```diff
- combineQualities(show.config.qualities.preferred).length > 0
+ combineQualities(show.config.qualities.preferred) > 0
```
as `combineQualities` returns a number and not an array like `getPreset` does

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/6455
