### ISSUE TITLE
How know indexer use ?

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#6461]
Hi,

i would like know which indexer i have use for a TV Shown i check this information ?

Rgds
Akhlan

**Comment by p0psicles** [comment]
Try to formulate your question better. Maybe use Google translate.

**Comment by akhlan** [comment]
Hi,

I would like to know which indexer I used for a series.
Where to find this information, TVDB2, TVmaze or TMDB, I do not use all the time the same ....

Rgds
Akhlan

**Comment by p0psicles** [comment]
Mostly you should use tvdb. You can always Check the indexer yourself by checking the site. Anime only works with tvdb. Some shows that are not added to tvdb you can check tvmaze and tmdb. But there aren't many of those.

**Comment by medariox** [comment]
In the top side of a show page, there is the indexer logo, if I understand the question correctly:
![img](https://snapr.pw/i/72a4ce0507.png)

**Comment by PlaceboPRS** [comment]
You should always use TVDB because there's a bug whereby tvmaze and tmdb are providing incomplete dupe key information resulting in false positives of dupes, more information here: https://forum.nzbget.net/viewtopic.php?f=3&t=3447&p=21626#p21626
