### ISSUE TITLE
.@__thumb folder not being ignored AFTER PP

### ISSUE THREAD

**Issue by kcoyo** [pymedusa/Medusa#6467]
**Describe the bug**
I have a QNAP NAS that stores my media files. After PP, Medusa runs a file size check on the media folders. I get warnings saying "Unable to get size for file /Plex/TV Shows/.../Season X/.@__thumb/..." 

These checks are likely used to report folder size on the TV show for each season. They look like this: "Season contains 31 episodes with total filesize: 9.89 GB" under each season of the shows. 

**To Reproduce**
1. Have a QNAP NAS
2. Post-process a show
3. Wait for Medusa to report file size of TV season folders

**Expected behavior**
The .@__thumb folders should be ignored for the file size checks.

**Medusa (please complete the following information):**
 - OS: Linux-4.2.8-x86_64-with (Using Docker linuxserver.io)
 - Branch: master
 - Commit: https://github.com/pymedusa/Medusa/commit/b34f1df336e52cf0a690acbc393440ac9f8b3581

**Logs:**

```
> 2019-04-04 09:07:51 WARNING  APIv2-Thread_2 :: [] Unable to get size for file /Plex/Anime/One Piece/Season 19/.@__thumb/a100One Piece - S19E27 - 806 - Power of Fullness - New Gear Fourth Tankman!.mkv Error: OSError(2, 'No such file or directory')
> 2019-04-04 09:07:51 WARNING  APIv2-Thread_2 :: [] Unable to get size for file /Plex/Anime/One Piece/Season 19/.@__thumb/adefaultOne Piece - S19E26 - 805 - A Battle of Limits! Luffy and the Infinite Biscuits!.mkv Error: OSError(2, 'No such file or directory')
> 2019-04-04 09:07:51 WARNING  APIv2-Thread_2 :: [] Unable to get size for file /Plex/Anime/One Piece/Season 19/.@__thumb/a100One Piece - S19E27 - Power of Fullness - New Gear Fourth Tankman!.mkv Error: OSError(2, 'No such file or directory')
> 2019-04-04 09:07:51 WARNING  APIv2-Thread_2 :: [] Unable to get size for file /Plex/Anime/One Piece/Season 19/.@__thumb/a100One Piece - S19E24 - 803 - The Past That He Let Go Of! Vinsmoke Sanji!.mkv Error: OSError(2, 'No such file or directory')
> 2019-04-04 09:07:51 WARNING  APIv2-Thread_2 :: [] Unable to get size for file /Plex/Anime/One Piece/Season 19/.@__thumb/adefaultOne Piece - S19E16 - 795 - Great Ambition – Big Mom and Caesar.mkv Error: OSError(2, 'No such file or directory')
> 2019-04-04 09:07:51 WARNING  APIv2-Thread_2 :: [] Unable to get size for file /Plex/Anime/One Piece/Season 19/.@__thumb/adefaultOne Piece - S19E30 - 809 - A Storm of Revenge! An Enraged Army Comes to Attack!.mkv Error: OSError(2, 'No such file or directory')
> 2019-04-04 09:07:51 WARNING  APIv2-Thread_2 :: [] Unable to get size for file /Plex/Anime/One Piece/Season 19/.@__thumb/a100One Piece - S19E22 - 801 - The Benefactor's Life! Sanji and Owner Zeff!.mkv Error: OSError(2, 'No such file or directory')
> 2019-04-04 09:07:51 WARNING  APIv2-Thread_2 :: [] Unable to get size for file /Plex/Anime/One Piece/Season 19/.@__thumb/a100One Piece - S19E04 - 783 - Sanji Returns Home – To Big Mom's Territory!.mkv Error: OSError(2, 'No such file or directory')
> 2019-04-04 09:07:51 WARNING  APIv2-Thread_2 :: [] Unable to get size for file /Plex/Anime/One Piece/Season 19/.@__thumb/a100One Piece - S19E21 - 800 - 1 and 2 – Assemble! The Vinsmoke Family.mkv Error: OSError(2, 'No such file or directory')
> 2019-04-04 09:07:51 WARNING  APIv2-Thread_2 :: [] Unable to get size for file /Plex/Anime/One Piece/Season 19/.@__thumb/adefaultOne Piece - S19E24 - 803 - The Past That He Let Go Of! Vinsmoke Sanji!.mkv Error: OSError(2, 'No such file or directory')
> 2019-04-04 09:07:51 WARNING  APIv2-Thread_2 :: [] Unable to get size for file /Plex/Anime/One Piece/Season 19/.@__thumb/adefaultOne Piece - S19E03 - 782 - Fist of the Devil – Showdown! Luffy vs. Grant.mkv Error: OSError(2, 'No such file or directory')
```

**Additional context**
There's already a similar ignore but it's for DURING post-process: https://github.com/pymedusa/Medusa/pull/4392/commits/6506db4741afbee2c519b61ef82acf51f1462218#diff-dadc5be61152306286b08ec495901f62. Not sure if this is supposed to work regardless.

I notice that these errors come up when I load the TV show/Anime pages. There seems to be a script that runs file size checks on load.

**Comment by medariox** [comment]
Your system is creating these files. This has nothing to do with Medusa.

**Comment by onehans** [comment]
obviously system is creating thumbs but is there a option in Medusa to ignore hidden folders such any starting with "."
this folders are hidden for a reason, medusa does not need to dig them

**Comment by bitomule** [comment]
I’ve the same issue. I don’t understand why the ticket was closed. Is there a way to skip Medusa from post processing .@__thumb folders?
