### ISSUE TITLE
Medusa Web gui not working while postprocessing

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#6468]
Hello,

Just letting you know that I can not access medusa web gui while it is postprocessing some series.
At the moment this is a problem for me because I am currently uploading each file to the cloud, so postprocessing work can last a lot of time, even more if medusa needs to postprocess lots of files.
Is there any way to split the postprocessing process apart from the website gui?

Kind regards

**Comment by p0psicles** [comment]
You shouldn't let Medusa move it to cloud. Let Medusa stage and sync using rsync for example.

**Comment by elpedriyo** [comment]
Well, I have a folder that is mounted on my system that belongs to a cloud folder, so that is how medusa is doing it. I do not want to sync it, just move it. Also medusa needs to know in which folder are the files located.
At the moment there is no much trouble with it apart from not being able to access medusa while this process.

Kind regards

**Comment by medariox** [comment]
Fixed.
