### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Gaiam TV 

### ISSUE THREAD

**Issue by bassings** [pymedusa/Medusa#6470]
### INFO
**Python Version**: `3.6.7 (default, Dec  5 2018, 15:02:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]`
**Operating System**: `Linux-3.10.0-957.10.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@b34f1df336e52cf0a690acbc393440ac9f8b3581
**Link to Log**: https://gist.github.com/ef6129299ac3fab4433996ccc58fc911
### ERROR
<pre>
2019-04-06 06:12:50 ERROR    Thread_0 :: [b34f1df] Missing time zone for network: Gaiam TV 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
> Gaiam TV 

Already in the list  
https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L898
