### ISSUE TITLE
Latest raspbian/debian libssl upgrades breaks medusa 

### ISSUE THREAD

**Issue by alkalinelito** [pymedusa/Medusa#6472]
Hi first of all, this is my system info:
```
pi@raspberrypi3:~ $ cat /etc/debian_version 
9.8
pi@raspberrypi3:~ $ cat /etc/apt/sources.list
deb http://raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi
```

Today I noticed this errors on medusa : 

`Error requesting url https://cdn.pymedusa.com/news/news.md Error: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /news/news.md (Caused by SSLError(SSLError("bad handshake: Error([('', 'osrandom_rand_bytes', 'getrandom() initialization failed.')],)",),))`

Also all connections to trackers: 

`HTTPSConnectionPool(host='TRACKER_URL', port=443): Max retries exceeded with url: /user/account/login (Caused by SSLError(SSLError("bad handshake: Erro([('', 'osrandom_rand_bytes', 'getrandom() initialization failed.')],)",),))`

If figured it had something to do with ssl , so I searched latest upgrades (I upgraded my raspbian install 2 days ago):
```
$ sudo cat /var/log/dpkg.log.1 | grep upgrade | grep ssl
2019-04-03 21:27:36 upgrade libssl1.0.2:armhf 1.0.2q-1~deb9u1 1.0.2r-1~deb9u1
```

So I rolled back from 
`libssl1.0.2_1.0.2r-1~deb9u1_armhf.deb `
to 
`libssl1.0.2_1.0.2q-1~deb9u1_armhf.deb `

And everything works again .

Just to let you guys know , latest libssl debian upgrade (libssl1.0.2_1.0.2r-1~deb9u1_armhf.deb)  breaks something in medusa ssl.

**Comment by medariox** [comment]
This is likely not a Medusa issue, but rather something about the Python version you are using. We can't help you further as you didn't post your Python version (although it is explicitly requested in the issue template). You can possibly fix it by updating your Python version. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822431 If Raspbian doesn't support the fixed Python version you should build a new Python version from sources.
