### ISSUE TITLE
Fairy Tail - Strange bug

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#6477]
Hi,

when i add Fairy Tail series, i have a strange bug...

My episode aren't name like that

Fairy Tail_01x01_name.mkv
Fairy Tail_01x02_name.mkv
Fairy Tail_01x03_name.mkv
Fairy Tail_01x04_name.mkv...

Fairy Tail_02x01_name.mkv
Fairy Tail_02x02_name.mkv
Fairy Tail_02x03_name.mkv
Fairy Tail_02x04_name.mkv...

and when i had this serie in Medusa, the application transform season 2 in season 5... (Same issue with tvdb2 or TMDB)

Fairy Tail_02x01_Une rencontre marquée par le destin.nfo
```
<?xml version='1.0' encoding='UTF-8'?>
<episodedetails>
  <title>Le Roi des Dragons</title>
  <showtitle>Fairy Tail</showtitle>
  <season>5</season>
  <episode>1</episode>
  <uniqueid>4798440</uniqueid>
  <aired>2014-04-05</aired>
  <plot>Interrompant Natsu et Grey dans leur bagarre, Gajil demande au premier de le suivre, avec Wendy. Une marche souterraine mènera les trois Chasseurs de Dragons – accompagnés de quelques curieux – à un étrange cimetière.</plot>
  <runtime>25</runtime>
  <thumb>https://www.thetvdb.com/banners/episodes/114801/4798440.jpg</thumb>
  <rating>9.0</rating>
```

I haven't issue with season 1...

Why ?

Rgds
Akhlan

**Comment by medariox** [comment]
Enable absolute numbering for the show.
