### ISSUE TITLE
Required words (per show) listing global excluded list

### ISSUE THREAD

**Issue by a10kiloham** [pymedusa/Medusa#6481]
See screencap
https://i.imgur.com/sy6d1BP.png

List of required words same as global excluded words. I don't have any global required words.

**Comment by Olivier6767** [comment]
I notices the same issue, cannot use a global Required Words list... It's pulling the Excluded Words list instead.
This is in Show Detail / Advanced screen.

Any plan to fix this?
Thx.

**Comment by medariox** [comment]
It's just a visual bug.

**Comment by Olivier6767** [comment]
I4m not sure it's only visual. I had a Global Required Words list and for soem shows, I enabled the option: Exclude required words
I was hoping that my Global Required Words would be bi ignored for this show. However when forcing a search the log showed that is was still trying to match my Global Required Words for this show.

Or did I misunderstand this option?

**Comment by p0psicles** [comment]
Should be fixed with the vueify editshow pr.

**Comment by Olivier6767** [comment]
Thx!

**Comment by medariox** [comment]
Closing as fixed.
