### ISSUE TITLE
Multi language when adding show - Second post

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#6484]
Hi,

Is your feature request related to a problem? Please describe.
When I had an episode who haven't french name, the field still empty...

Describe the solution you'd like
When the episode name doesn't exist in main language, Medusa should had a second language information like English

It's possible like other fork ?

```
medariox said and close with that...
Yeah also don't really see the need for it. You can (and probably should) add the missing episode names to the indexers, so other people can benefit from it. Closing as it's not going to happen anyway
```
We can't because french name (or other langages...) don't exist when a TV show start en english langage...

Rgds
akhlan

**Comment by medariox** [comment]
You mean like a fallback language? @p0psicles already explain why it is not possible to add this in the closed issue. We have no intention to add add this functionality. Please avoid opening new requests about this.
