### ISSUE TITLE
Rescan missing files

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#6492]
Hello,

Can someone tell me how can I rescan a tv show without erasing it and adding it again?
I am clicking rescan files and force full update, but it still shows the deleted files as downloaded.

Please can someone give some feedback about this?

Kind regards

**Comment by medariox** [comment]
Rescan is what you need to use after you delete the file. If it doesn't work enable debug logging and open a new issue with the debug logs after you finish the rescan.
