### ISSUE TITLE
Not errasing when rescan is performed

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#6493]
Hello

I enabled the debug option as you told me and here is the log:
https://pastebin.com/XDRA5n9f

I can see on the log that the episode 1x01 no longer exists, but when I get into medusa it still appears as downloaded

![image](https://user-images.githubusercontent.com/3207791/55900410-6dc8b380-5bc7-11e9-8707-580a6e002ff9.png)

Kind regards

**Comment by p0psicles** [comment]
No, it appears as archived

**Comment by elpedriyo** [comment]
Hello,

Well it is not archived neither.
It doesn't matter how it is clasified, the rescan won't change the state of it

Kind regards

**Comment by p0psicles** [comment]
When an episode was downloaded and you remove the file. After rescan it changes its state to archived.
