### ISSUE TITLE
Latest Commit broke built Medusa Filters (JS issue)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#6497]
**Describe the bug**
as of commit: e9b9532aa2b90a459e790154c6eff04a9fa796ed
it seems that Filters such as Search & Filters such as by downloads, active etc are broken.
previous commit: 3a87b2bc19091ab6124461703f0c6f0461c8a770 seems to work fine.

**To Reproduce**
View image to see what i mean

**Screenshots**
![Screen Shot 2019-04-12 at 9 01 49 pm](https://user-images.githubusercontent.com/2242880/56033461-072ecb80-5d68-11e9-9c96-0c87e2e029de.jpg)

**Medusa (please complete the following information):**
 - OS: macOS 10.14.4
 - Branch: develop
 - Commit: e9b9532aa2b90a459e790154c6eff04a9fa796ed

**Logs:**
nothing in log, but here is js console output log from my browser:
https://gist.github.com/XxUnkn0wnxX/834964329d98bbb0d618d30a8ec24cfd

```
parsers.js?99729:1 Uncaught TypeError: Cannot read property 'addParser' of undefined
    at parsers.js?99729:1
(anonymous) @ parsers.js?99729:1
```

```
Uncaught TypeError: $(...).tablesorter is not a function
    at initializePage (home.vue?./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options:176)
```

seems i get these with latest commit, previous one i don't get these errors..

**Comment by medariox** [comment]
Will be fixed with https://github.com/pymedusa/Medusa/pull/6498
