### ISSUE TITLE
Find Proper job failing

### ISSUE THREAD

**Issue by flick1999** [pymedusa/Medusa#6500]
Whenever the Proper Job runs, it fails and goes red in the "Alive" status column. Medusa seems to run slowly afterwards until it is restarted. This happens every time it runs. I am unaware of making any configuration changes that would have triggered this.

I tried to do the debug log submission process but it seems to fail, not sure why. So, here's the error that's displayed when I View Errors:

2019-04-12 08:15:06 ERROR    FINDPROPERS :: [Torrenting] :: [94fae84] Exception generated: local variable 'torrent_rows' referenced before assignment
Traceback (most recent call last):
  File "/app/medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/app/medusa/medusa/search/proper.py", line 66, in run
    propers = self._get_proper_results()
  File "/app/medusa/medusa/search/proper.py", line 124, in _get_proper_results
    cur_propers = cur_provider.find_propers(recently_aired)
  File "/app/medusa/medusa/providers/generic_provider.py", line 207, in find_propers
    for item in self.search(search_strings[0], ep_obj=episode_obj):
  File "/app/medusa/medusa/providers/torrent/html/torrenting.py", line 86, in search
    results += self.parse(response.text, mode)
  File "/app/medusa/medusa/providers/torrent/html/torrenting.py", line 107, in parse
    if len(torrent_rows) < 2:
UnboundLocalError: local variable 'torrent_rows' referenced before assignment

**Comment by medariox** [comment]
Already fixed in develop: https://github.com/pymedusa/Medusa/pull/6430 
You should also update to the latest version.

**Comment by flick1999** [comment]
Hmm, I always run "check for updates" before submitting reports like this and I verified that I'm on 0.3.1, which github says is the latest version, 23 days old.  Guess I'll switch to the DEV build, since MASTER must lag behind, and hope that it doesn't introduce other issues. Thanks for the fast response; it is appreciated.

**Comment by medariox** [comment]
You seem to be running v0.3.0 currently. Master is not really much behind. It is one provider that has this bug (Torrenting). It's just not worth to push a release for that.

**Comment by flick1999** [comment]
Ah. Roger that, thanks for the clarification! I am curious about the v0.3.0
comment, though, as Info gives me this:


Branch: master
<http://dereferer.org/?https://github.com/pymedusa/Medusa/tree/master>
Commit: 94fae847b6e7e443d74c59cb11bdbd37c464b363
<http://dereferer.org/?https://github.com/pymedusa/Medusa/commit/94fae847b6e7e443d74c59cb11bdbd37c464b363>

Version: 0.3.1
<http://dereferer.org/?https://github.com/pymedusa/Medusa/releases/tag/0.3.1>

Database: 44.15
