### ISSUE TITLE
qBittorrent API v2

### ISSUE THREAD

**Issue by andystevens91** [pymedusa/Medusa#6505]
**Is your feature request related to a problem? Please describe.**
Using the latest qBittorrent builds from the unstable repo, Medusa cannot download torrents. I think the old APIs are now deprecated.

**Describe the solution you'd like**
Upgrade the qBittorrent client to use API v2. I did it on my local qbittorrent.py file (just changed the _add_torrent_uri and _add_torrent_file methods), but I'm not confident enough to submit a PR.

**Comment by p0psicles** [comment]
Youll have to add a method that will get the api version first. Then then based on that you can switch between apis.

**Comment by medariox** [comment]
Just submit your code. I'm sure it's going to be fine. We will help if needed.

**Comment by andystevens91** [comment]
I uploaded my code here https://gist.github.com/andystevens91/3067a6241a3e6c29ba140dad74e1af50
It's not fancy, there is no API version check, and I manually insert the 'tv' category because that's what I use on my server.

**Comment by sharkykh** [comment]
In case this helps, my attempt at this from a year ago:
https://github.com/pymedusa/Medusa/compare/develop...sharkykh:feature/qbittorrent-api-v2

While the authentication side of the code **isn't finished**,
I did put in some of the changes needed for API v2.

P.S.
I think that the new code should still support API v1 (only if API v2 isn't available).

**Comment by andystevens91** [comment]
Your code is mostly working, though I got 
`TypeError: a bytes-like object is required, not 'str'`
on line 47
`version = map(int, version.content.split('.'))`

i fixed it in this way, which is surely the worst way to do that, but works for me:

    try:
        version = map(int, version.content.split('.'))  
            if len(version) < 2:  
                version.append(0)  
                return tuple(version)  
    except TypeError:  
        return (2, 0, 0)

**Comment by p0psicles** [comment]
Can you post the stack trace of that? Also I assume you use python3?

**Comment by sharkykh** [comment]
Try just changing that line to: `version = map(int, version.text.split('.'))`

**Comment by andystevens91** [comment]
> Try just changing that line to: `version = map(int, version.text.split('.'))`

That works!

**Comment by medariox** [comment]
It would be great to have a PR with these changes for the next version.

**Comment by h2xtreme** [comment]
Hi all,

Any progress on this? qbittorrent 4.2.0 doesn't work with medusa right now

`2019-08-07 07:43:53 WARNING	SNATCHQUEUE-SNATCH-323420 :: [74c3f12] qbittorrent: Unable to send Torrent
2019-08-07 07:43:53 INFO	SNATCHQUEUE-SNATCH-323420 :: [74c3f12] qbittorrent: Not Found`

I tried both @sharkykh and @andystevens91 qbittorrent.py besides the default one present in medusa master branch. All return this error.

qbittorrent API version is 2.2

**Comment by p0psicles** [comment]
I'll try to finish it this week

**Comment by sharkykh** [comment]
Just FYI, qBittorrent version 4.2.0 is still in alpha, current (stable) version is 4.1.7 and it still fully supports the v1 API.
