### ISSUE TITLE
Post  Processing fails

### ISSUE THREAD

**Issue by FransAlmere** [pymedusa/Medusa#6513]
**Describe the bug**

After update from medusa this morning Post processing stops completely and does not work anymore after trying to postprocess TV shows.

1. Go to 'Post Processing'
4. See error: ERROR    POSTPROCESSOR :: [f46bfac] Exception generated: 'utf8' codec can't decode byte 0xfc in position 50: invalid start byte
Traceback (most recent call last):

**Expected behavior**

That shows with correct names are transferred to the right directory.

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/13037978/56132605-b34ffc80-5f8a-11e9-8229-4826e46bba26.png)

**Medusa (please complete the following information):**
 - OS: Synology DSM 6.2.1-23824 Update 6
 - Branch: master
 - Commit: : 46bfacf8763204fbde4f26a5916095371d494d1
Version: 0.3.1

**Logs:**
<details>

![afbeelding](https://user-images.githubusercontent.com/13037978/56132623-bf3bbe80-5f8a-11e9-8aff-17a676d0fc38.png)

```
</details>

**Comment by medariox** [comment]
The directory you are trying to process contains characters that are not supported by your OS localization (utf-8).

**Comment by FransAlmere** [comment]
Thats the easy part but untill now Medusa worked fine, tomorrow I updates as requested and the probleem occured. The only difference with yesterday is that the first episode of Game of Thrones was downloaden. So I am still stuck, I have a backup from a view days ago shall I try what happens if I restore that one? 




Kind regards 




Frans Lieshout


Banjostraat 49


1312 KB Almere


Deze mail is verzonden van mijn Motorola G6 via Outlook. 


De informatie in deze e-mail is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Wanneer u dit bericht per abuis ontvangt, verzoekt Frans Lieshout u contact op te nemen met de afzender. Bovendien verzoekt Frans Lieshout u in dat geval deze e-mail te vernietigen en de inhoud aan niemand openbaar te maken. Frans Lieshout aanvaardt geen aansprakelijkheid voor onjuiste, onvolledige dan wel ontijdige overbrenging van de inhoud van een verzonden e-mail, noch voor overgebrachte virussen.







On Mon, Apr 15, 2019 at 2:39 PM +0200, "Dario" <notifications@github.com> wrote:












The directory you are trying to process contains characters that are not supported by your OS localization (utf-8).

**Comment by medariox** [comment]
Nothing changed between version 0.3.0 and 0.3.1 that could have caused it. As I said, it must be a file that you are trying to post-process or a folder that you have added to to your media that is causing this. Most likely that file is part of the download you are talking about. Just delete it and try another download.

**Comment by FransAlmere** [comment]
Will try and let you know, thanks




Frans Lieshout


Banjostraat 49


1312 KB Almere


Deze mail is verzonden van mijn Motorola G6 via Outlook. 


De informatie in deze e-mail is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Wanneer u dit bericht per abuis ontvangt, verzoekt Frans Lieshout u contact op te nemen met de afzender. Bovendien verzoekt Frans Lieshout u in dat geval deze e-mail te vernietigen en de inhoud aan niemand openbaar te maken. Frans Lieshout aanvaardt geen aansprakelijkheid voor onjuiste, onvolledige dan wel ontijdige overbrenging van de inhoud van een verzonden e-mail, noch voor overgebrachte virussen.







On Mon, Apr 15, 2019 at 4:15 PM +0200, "Dario" <notifications@github.com> wrote:












Nothing changed between version 0.3.0 and 0.3.1 that could have caused it. As I said, it must be a file that you are trying to post-process or a folder that you have added to to your media that is causing this. Most likely that file is part of the download you are talking about. Just delete it and try another download.

**Comment by FransAlmere** [comment]
Today problem still exits. Downloaded Knightfall same problem, will not post process

![afbeelding](https://user-images.githubusercontent.com/13037978/56193266-85bd8e80-6030-11e9-955b-98030f47e61d.png)

Will restore backup from 14th of April, see if post procceing than works, if not I think we safeley can conclude that it is correct to assume that is has nothing to do with the update and there is something else going on.

Regards

**Comment by FransAlmere** [comment]
Restore did not solve the problem so what can I try next ?

**Comment by medariox** [comment]
Some folder in your Windows system is using non-ASCII chars (e.g.  ä, ö, ü, è, é,...). Do you have recently added such folder to your Show root directories or the folders you are trying to post-process? You need to remove it. Alternatively you should be able to fix it by upgrading to Python 3.5+.

**Comment by FransAlmere** [comment]
Problem Solved, after your remark I went with Putty on the comment line to the directory and there was a file with an ü in it, Was a German Title alltough I do not now why it was there replaced the file and evenything works again 😊
Thanks for the help

Regards
