### ISSUE TITLE
Popular Shows IMDB not working

### ISSUE THREAD

**Issue by rssfed23** [pymedusa/Medusa#6515]
**Describe the bug**
If you go to add recommended shows > Add from IMDB's Popular Shows you get the following error: 
_Fetching of Recommender Data failed. Exception:
db type could not be determined_

<img width="1408" alt="Screenshot 2019-04-15 at 16 21 35" src="https://user-images.githubusercontent.com/12484127/56144624-a2a78280-5f9a-11e9-839d-331cc836e899.png">

Medusa Info: | Branch: masterCommit: f46bfacf8763204fbde4f26a5916095371d494d1Version: 0.3.1Database: 44.14
-- | --
Python Version: | 3.7.2 (default, Mar 21 2019, 10:09:12) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
SSL Version: | OpenSSL 1.1.1b FIPS 26 Feb 2019
OS: | Linux-5.0.3-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
Locale: | en_GB.UTF-8

**Logs:**
<details>

```

2019-04-15 16:23:52 DEBUG    Thread_1 :: [f46bfac] GET URL: https://api.imdbws.com/chart/tvmeter [Status: 200]
2019-04-15 16:23:52 DEBUG    Thread_1 :: [f46bfac] User-Agent: IMDb/8.3.1 (iPhone9,4; iOS 11.2.1)

```
</details>

**Comment by medariox** [comment]
Delete the `recommended.dbm` file in your cache folder.

**Comment by rssfed23** [comment]
Problem Solved :)
