### ISSUE TITLE
Parse Error During Postprocessor Email Notification

### ISSUE THREAD

**Issue by gmusgrave** [pymedusa/Medusa#6526]
**Describe the bug**
Whenever I download "Jeopardy!" Medusa snatches the show and postprocesses it correctly EXCEPT that it always generates this warning:

> WARNING  POSTPROCESSOR :: [f46bfac] Unable to parse "Jeopardy! - 2019 04 15 - Returning Champion Vs. , show # 7971 - 720p HDTV" for email notification

I suspect there's something in the showname string that it doesn't like. This is an uncommon string, with several unusual characters (such as the exclamation mark, pound sign, period, and comma), and this doesn't happen with any other show.

Normally, this wouldn't be a big deal, but it's annoying because the show airs every weekday, so it happens five times a week, 46 weeks a year.

**Medusa (please complete the following information):**
 - OS: Windows-7-6.1.7601-SP1
 - Branch: master
 - Commit:  f46bfacf8763204fbde4f26a5916095371d494d1 
</details>

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/6527
