### ISSUE TITLE
[ FEATURE ] Option for delaying a provider snatch

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#653]
Hi,

Would it be possible to add a delay between nzb and torrent searches please?
Nzb is for me easier and safer whereas torrents is a lot more complicated.

I'd like to add nzb as prefered way and put something like 2 days of delay before searching via torrent.
Sonarr offers this feature

Cheers

**Comment by p0psicles** [comment]
I asume the delay should start from the moment of the first result, and not the first search.
As a user story: The user adds a show with multiple providers. Because the user prefers some providers over others, the user wants to give the preferred provider enough time time snatch a result, while after a specified period of time the less preferred provider get's a chance.

Is this kind of your story?

**Comment by NicoLeOca** [comment]
It seems so.
I narrowed it down only to nzb/torrent criteria but it could be generealized to any provider no matter nzb or torrent.

Also, it appears to be more important when an episode is searched right after it is aired. In that case the episode you are looking is likely to have never been on your prefered provider yet but you are willing to wait.
When you search for it later (weeks after, I mean), a delay may be disturbing and unnecessary. the order you sort your providers is enough to priotize.

Am I clear?

**Comment by labrys** [comment]
Imo it can be tied into an implementation of this feature request from feathub: [Timeout for snatched episodes. (Basic failed download function)](http://feathub.com/SickRage/SickRage/+25).  After a certain timeout, fail the snatch and failover to another priority-group.  Same failover groups and logic could be applied to searching.

**Comment by p0psicles** [comment]
I'd like to add a feature search profiles. Where these FR's can be put under. Thats something i was planning to work on for some time now. 

But i was thinking to get these user stories as clear as possible in the mean time.

**Comment by labrys** [comment]
I would say once a feature request has been added to the master feature request list, close the FR Issue (continue discussion in the closed issue ofc)

**Comment by NicoLeOca** [comment]
I vote to leave it opened as it's the default view when you arrive on the repository
you'll more likely have comments from users telling their story.
People never pay visits to closed issues

**Comment by p0psicles** [comment]
We'll we dont need allot of stories on one feature. Or at least i try to map them 1one1. Then if People look at the master feature list, they can use the to get to here.

Keeping them All open only clouds our overview. And keeps is from working on important stuff

**Comment by labrys** [comment]
Added to master feature request list - discussion for feature will continue here even though issue is closed.

**Comment by p0psicles** [comment]
#3360
