### ISSUE TITLE
Add provider - nCore

### ISSUE THREAD

**Issue by ExPeacer** [pymedusa/Medusa#6535]
Hy!
Could you add nCore to providers? It's the largest Hungarian tracker.
[https://ncore.cc/](https://ncore.cc/)

It's already added in other forks ;)

Thanks a lot for your help!

**Comment by medariox** [comment]
We need access to the provider to add it. We don't copy code from other forks as it's usually outdated/unmaintained and/or broken.

**Comment by ExPeacer** [comment]
I like this attitude 👍 

I can share my account in private, with a temporary password, if it's a possible solution.

**Comment by medariox** [comment]
Yes sure, join us on IRC or Discord.

**Comment by medariox** [comment]
Added with https://github.com/pymedusa/Medusa/pull/6537
