### ISSUE TITLE
Subtitles files (srt) aren't hard linked on post processing

### ISSUE THREAD

**Issue by sagilo** [pymedusa/Medusa#6542]
**Description**
I've downloaded an episode which includes an .srt file.
The .srt filename is the same exact as the MKV
'search for subtitles' is marked for the series.
I use 'hard copy' for the post-processing

It looks like the post processing find the srt file but ignores it

**Medusa env:**
 - OS: Ubuntu 16.04, running in Docker
 - Branch: master
 - Commit: 54da0c77d705a23f1ce67945ba4af3e1b978dcfc 
 - Version: 0.3.1 

**Logs:**
[medusa_logs.txt](https://github.com/pymedusa/Medusa/files/3101112/medusa_logs.txt)

**Comment by medariox** [comment]
Enable subtitles for the show.
