### ISSUE TITLE
Episode quality detected horribly wrong

### ISSUE THREAD

**Issue by dpedu** [pymedusa/Medusa#6552]
**Describe the bug**

My installation of medusa is detecting the quality of tv episodes wrong. For example:

```
Season 4/Black.Mirror.S04E04.Hang.the.DJ.720p.NF.WEBRip.DD5.1.x264-QOQ.mkv
Season 13/ancient.aliens.s13e03.720p.web.h264-tbs.mkv
```

Are both detected as "1080p WEB-DL" when they are clearly 720p.

And:

```
Season 8/Gold.Rush.S08E05.Son.Dethrones.Father.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv
```

Is detected as "720p Blu-Ray" when it is clearly 1080p WEB-DL.

**To Reproduce**
1. Scan a library with aforementioned files
2. See incorrect results

**Expected behavior**
The episodes are detect as the correct format.

**Screenshots**
<img width="1393" alt="Screen Shot 2019-04-23 at 9 28 33 PM" src="https://user-images.githubusercontent.com/1266188/56632476-c9a32b80-660e-11e9-9882-6a3c6da49d0a.png">

**Medusa (please complete the following information):**
 - OS: ubuntu 14.04
 - Branch: master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76 

**Logs:**
N/a, these were originally some time ago.

**Additional context**
It's possible these shows were added sometime in the past when there was a bug that is gone now. How do I correct this without manually inspecting and setting each episode? The "Rescan Files" and "Force Full Update" don't change anything.

**Comment by p0psicles** [comment]
There is a report_guessit.py file in the tests folder. Can you run that like, python report_guessit.py filename. And post results?

**Comment by p0psicles** [comment]
Also still need debug logs, from a rescan files.

**Comment by dpedu** [comment]
report_guessit.py is reporting correct information (which I won't bother to copy paste).

I don't see a "debug" log level available on the `/errorlogs/viewlog/` screen - only Info, Warning, and Error. So I assume "Info" is what you mean? 

When I rescanned "Gold Rush", what was logged was merely:

**Logs:**
<details>

```
2019-04-23 21:50:26 INFO     SHOWQUEUE-REFRESH :: [918cfe7] Cache check completed
2019-04-23 21:50:26 INFO     SHOWQUEUE-REFRESH :: [918cfe7] Trying to clean any empty folder under /tv/Gold Rush Alaska
2019-04-23 21:49:56 INFO     SHOWQUEUE-REFRESH :: [918cfe7] 208111: Performing refresh on Gold Rush
```
</details>

The season when viewed in the UI did not change from doing this:

<img width="1389" alt="Screen Shot 2019-04-23 at 9 50 56 PM" src="https://user-images.githubusercontent.com/1266188/56633169-e55c0100-6611-11e9-908b-b4337e9e1b22.png">

**Comment by dpedu** [comment]
I just saw your Discord message - here's the debug log for the same activity as above. It was too long for github so I put it on pastebin:

https://pastebin.com/raw/vnDxXJZx

**Comment by medariox** [comment]
Medusa won't rescan a file that hasn't changed. Since there is no bug you can just manually change the quality.

**Comment by p0psicles** [comment]
I made him move the folder, scan and put them back. The rescan also gave wrong qualities. So was curious to see a debug for that. Maybe his files are named wrong?

**Comment by medariox** [comment]
Where are the debug logs of that?

**Comment by dpedu** [comment]
Why was this closed? Is it not expected that Medusa labels files correctly?

**Comment by medariox** [comment]
If report_guessit reports the correct information there is nothing to do.

**Comment by dpedu** [comment]
> If report_guessit reports the correct information there is nothing to do.

Unless there is a bug in the plumbing that delivers the result of this script into the UI, of course. Looks like this is the case?

**Comment by medariox** [comment]
That is really unlikely.

Your 2nd screenshot shows the episodes tagged as 1080p and correctly detected as such quality. Are you even sure this is a real issue? I need you to rename ONE episode to a different quality and re-scan it. Then post the debug logs of that episode where the quality was not recognized correctly. Nothing else, not 10 pages worth of logs, just the one.

**Comment by dpedu** [comment]
With `report_guessit.py` showing correct info, I'm not sure what else the explanation could be.

> Your 2nd screenshot shows the episodes tagged as 1080p and correctly detected as such quality. Are you even sure this is a real issue?

Which episodes in the screenshot are you referring to? There are three tagged correctly, yes, but there are also 18 episodes detected as 720p, such as `Season 9/Gold.Rush.S09E11.The.Resurrection.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv`. Both the file name and output from the 3rd-party `mediainfo` command confirm that this file is 1080p and yet Medusa has for some reason decided otherwise. I just can't see how the bug I referenced is unlikely since the results of it are quite clear in the screenshot - the File Name column contains 1080p and the Status column says `Download 720p WEB-DL`. Am I missing something?

I renamed the episode to `Season 9/Gold.Rush.S09E11.The.Resurrection.2160p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv` and clicked Re-scan Files. Afterwards, the UI showed the correct (renamed) quality. Renaming it back to the original name even showed 1080p afterwards, which is great! I think this is the result you expected, so I won't bother with logs unless you disagree.

So, going back to the original question:

>How do I correct this without manually inspecting and setting each episode? 

Renaming counts as manual inspection/setting :-). It sounds like the least painful path forwards would be to remove each problematic show from Medusa entirely, and re-add it?

**Comment by medariox** [comment]
So why do you want to have this issue re-opened when you acknowledged yourself that this is bug is currently non-existent? I don't get it.

Anyway, as I first suggested, you can just change the quality from the drop-down to the quality you know is correct. As an alternative, you can also remove the shows and re-add them, but that's probably going to take longer.

**Comment by dpedu** [comment]
> So why do you want to have this issue re-opened when you acknowledged yourself that this is bug is currently non-existent?

I'm not sure what you mean by this. Are you disagreeing that many of the detected qualities in my screenshots are incorrect?

I'm just trying to understand how the incorrect labeling had come to be in the UI. "We don't know" is a perfectly acceptable answer, but sweeping this under the carpet is not.

Anyhow, I think I have the answers I was looking for. It sounds like there is currently no non-manual method to correct these. Appreciate the help!
