### ISSUE TITLE
Include subtitle (yes/no) on add new show

### ISSUE THREAD

**Issue by TMac7373** [pymedusa/Medusa#6607]
Subtitles should be an option when adding a new show.  The only way to do it now is to add the show, then go to mass update and select it there.

**Comment by p0psicles** [comment]
I'm pretty sure you have that option when you add the show

**Comment by TMac7373** [comment]
![Untitled](https://user-images.githubusercontent.com/26226170/56753149-eeef8100-6757-11e9-878a-03357c1dd2d6.jpg)

it should be here, right?

**Comment by p0psicles** [comment]
Then you have not configured your subtitles config. Need to enable that

**Comment by TMac7373** [comment]
thanks for your help!
