### ISSUE TITLE
Error while parsing filename

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#6614]
**Describe the bug**
Parsing BD as SD-DVD instead of BluRay

**To Reproduce**
Instead of BluRay, use BD to reproduce

Parsed [NeatBluRay] Hibike! Euphonium S02E09 VOSTFR (BD 1920x1080 8bits FLAC) into release_group: NeatBluRay, title: Hibike! Euphonium, season: 2, episode: [9], subtitle_language: fr, source: BDRip, screen_size: 1080p, aspect_ratio: 1.778, color_depth: 8-bit, audio_codec: FLAC, type: episode, parsing_time: 0.0323510169983, total_time: 0.0324549674988, absolute_episode: [], quality: SD DVD

**Expected behavior**
The parser should resolve the quality as BluRay instead of SD

**Medusa Latest dev commit**

**Additional context**
Don't know if I should post here or on guessit repository :(

Thanks a lot for your work !

**Comment by medariox** [comment]
Please open over at guessit.

**Comment by IDerr** [comment]
Opened : https://github.com/guessit-io/guessit/issues/601

**Comment by IDerr** [comment]
The issue has been closed, the error doesn't appear using last version of guessit.
https://github.com/guessit-io/guessit/issues/601

**Comment by medariox** [comment]
Are you sure the files is not actually a BDRip like our guessit version detected? It seems like anime releases that have BD in the name end up being rips (meaning: they don't have actually the full resolution (e.g. 1080p).

**Comment by IDerr** [comment]
The issue is not really for the BDRip part, more about the quality detected : SD DVD instead of 1080p.

To answer your question, it can be considered as a BDRip, since it's not the real BDMV file.

**Comment by medariox** [comment]
If it is a BDRip the `quality: SD DVD` is correct. It might be confusing, but it just means it is a BD/DVD Rip (we don't distinguish between the 2 in Medusa atm).

**Comment by IDerr** [comment]
ok ;) thanks for your work
