### ISSUE TITLE
Jeopardy!

### ISSUE THREAD

**Issue by rbhamilton** [pymedusa/Medusa#6615]
I've added Jeopardy! to Medusa.  Now that it's added, I can click on the show from the list but it either takes forever to open or simply fails to open.  Medusa has never downloaded a single Jeopardy! show but it works with all the other shows.

About the only thing I can think of is there are over 4500 episodes of Jeopardy?  Maybe it's exceeding some kind of limit?

**Comment by p0psicles** [comment]
Yes known bug. Is being worked on

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/5856
