### ISSUE TITLE
Problems with NZB on Python3

### ISSUE THREAD

**Issue by CeesKaas** [pymedusa/Medusa#6617]
**Describe the bug**
When using Blackhole for NZB an error (with stacktrace) is produced.
When using NZBget just an error is produced saying the nzb could not be sent to nzbget

To me this looks like a problem with how Python changed their API to output byte-like objects instead of strings from the standard_b64encode function. and no longer accepting byte[] on the write if you didn't open the file with the binary option

**To Reproduce**
Configure Blackhole for NZB and trigger a snatch
Configure NZBget and trigger a snatch

**Expected behavior**
the NZB to be downloaded and put in the right location

**Medusa (please complete the following information):**
 - OS: Ubuntu 19.04
 - Branch: master
 - Commit: f46bfacf8763204fbde4f26a5916095371d494d1
 - Python: 3.7.3

**Logs:**
Blackhole:
```
2019-04-27 19:09:02 INFO     SNATCHQUEUE-SNATCH-121361 :: [f46bfac] Saving NZB to ...
2019-04-27 19:09:02 ERROR    SNATCHQUEUE-SNATCH-121361 :: [f46bfac] Snatch failed! For result: ...
Traceback (most recent call last):
  File "/opt/medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/opt/medusa/medusa/search/core.py", line 142, in snatch_episode
    result_downloaded = _download_result(result)
  File "/opt/medusa/medusa/search/core.py", line 87, in _download_result
    file_out.write(result.extra_info[0])
TypeError: write() argument must be str, not bytes
```

NZBget:
```
2019-04-27 18:24:12 INFO     SNATCHQUEUE-SNATCH-121361 :: [f46bfac] Sending NZB to NZBget
2019-04-27 18:24:12 WARNING  SNATCHQUEUE-SNATCH-121361 :: [f46bfac] Connect Error to NZBget: could not add ... to the queue
```

**Additional context**
```
diff --git a/medusa/clients/nzb/nzbget.py b/medusa/clients/nzb/nzbget.py
index fdf869f0b..4e4672655 100644
--- a/medusa/clients/nzb/nzbget.py
+++ b/medusa/clients/nzb/nzbget.py
@@ -127,7 +127,7 @@ def sendNZB(nzb, proper=False):
     nzbcontent64 = None
     if nzb.result_type == 'nzbdata':
         data = nzb.extra_info[0]
-        nzbcontent64 = standard_b64encode(data)
+        nzbcontent64 = standard_b64encode(data).decode()

     log.info('Sending NZB to NZBget')
     log.debug('URL: {}', url)
diff --git a/medusa/search/core.py b/medusa/search/core.py
index ffe86cdd4..5a8f32a14 100644
--- a/medusa/search/core.py
+++ b/medusa/search/core.py
@@ -83,7 +83,7 @@ def _download_result(result):

         # save the data to disk
         try:
-            with open(file_name, u'w') as file_out:
+            with open(file_name, u'wb') as file_out:
                 file_out.write(result.extra_info[0])

             chmod_as_parent(file_name)
```
should fix these specific issues

**Comment by medariox** [comment]
Can you open a PR please?

**Comment by CeesKaas** [comment]
I've never done any commits to github yet, do you know a good guide that tells me how to do that?

**Comment by p0psicles** [comment]
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/6619
