### ISSUE TITLE
Add an anime button when using TMDB as provider 

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#6618]
**Is your feature request related to a problem? Please describe.**
When adding a show with TMDB as provider, there's not a anime button like with TVDB 
Example:
TMDB
![image](https://user-images.githubusercontent.com/7056621/56855825-959d7280-694e-11e9-824b-9f0b5663e8e5.png)

TVDB
![image](https://user-images.githubusercontent.com/7056621/56855832-acdc6000-694e-11e9-9ec5-498efdfad5cd.png)

**Describe the solution you'd like**
Add a button Anime when using TMDB if possible :D 

Thanks a lot for your work !

**Comment by p0psicles** [comment]
It's not possible, as anime shows depend heavily on thexem.de for mapping to scene numbering. And thexem only has mappings to tvdb.

**Comment by p0psicles** [comment]
So it's by design

**Comment by IDerr** [comment]
Ok thanks :D
