### ISSUE TITLE
Indexer country

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#6649]
Hello,

Just wanted to ask if I can set up the indexer to take airing time of an episode in another coutry like spain, instead of the original region of the show.

Kind regards

**Comment by p0psicles** [comment]
No, as 1 its not implemented. And 2 not all indexers have that info.

Why would you want it? What is Your use case?

**Comment by elpedriyo** [comment]
Hello,

Well, I want it because I have pending download in medusa list as wanted, because the original episode was aired but in VOSE and not in my country yet.

Kind regards

**Comment by p0psicles** [comment]
It Will download it as soon as available

**Comment by medariox** [comment]
Closing as not really doable and current behavior is acceptable.
