### ISSUE TITLE
[Feature Request] Add Keep link as post processing method

### ISSUE THREAD

**Issue by jee-r** [pymedusa/Medusa#6654]
**Is your feature request related to a problem? Please describe.**
Actually symbolic link processing method work fine but it's requires several actions to cleanup  data on torrent client's side and on Media directory, it's not very convenient.  

**Describe the solution you'd like**
Add an additional option for post processing method that make a symbolic link from source to destination directory like filebot do (https://www.filebot.net/cli.html >> "--action keeplink"). 

**Describe alternatives you've considered**
i don't know may be use filebot as post-process script but filebot need to setup a java env. 

**Additional context**
comparison of the 2 symlink methods

Symlink (actual)
Medusa copy the original file in the dest directory (Media) and make a symbolic link to source directory.

Keeplink (New)
Medusa make a symbolic link from the original file to the dest directory (Media). that's all :)

Regards
I hope my feature request is understandable, english is not my native language :)

**Comment by pax0707** [comment]
I would so much love the "Keeplink" option.
I've been using hardlink but I can't do that anymore since I moved my Medusa install to my new Pi to move some load off of my server that runs torrent/plex/etc.

**Comment by jee-r** [comment]
something similar to this https://github.com/barbequesauce/Watcher3/pull/139

**Comment by medariox** [comment]
Added.
