### ISSUE TITLE
X265 support

### ISSUE THREAD

**Issue by Sarcas666** [pymedusa/Medusa#6655]
More and more shows are available in x265/hvec. I tried a lot of settings but I never found a perfect solution. Either my x265 gets overwritten by a larger x264 version, or for some reason an episode never gets available on x265 and a x264 never gets choosen. 

**Describe the solution you'd like**
I know x265 support is a problem, but I hope it will be done anyway. The codec has been here for a while now. 

**Describe alternatives you've considered**
I tried combinations of preferred and required words, but it isn't perfect.

**Comment by medariox** [comment]
What doesn't work about the current solution with required words?

**Comment by Sarcas666** [comment]
There is no fallback to x264 in case a x265 doesn't show up. Also, sometime x265 versions become available only after a while. I'd love it if it was possible to automatically replace 'lesser' versions.  I realize it is all possible to do manually, but I prefer my computer to take care of these things...

**Comment by medariox** [comment]
That's what preferred and undesired words are for. If you think there is an issue with it you can open a bug report with attached debug logs.

**Comment by p0psicles** [comment]
Sarcas666 i'm aware of the issue. And the enhancement has been requested many Times before. If the preferred quality has been met, preferred words dont matter anymore.

Im not 100% sure. Haven't tried myself. But you could set your preferred quality really high. And use preferred words to set x265?

**Comment by p0psicles** [comment]
Like:
Allowed quality: 720/1080 webdl
Preferred quality: 8k blu-ray

Preferred words: x265
