### ISSUE TITLE
Post Processor Counting to Negative

### ISSUE THREAD

**Issue by Aethrios** [pymedusa/Medusa#6659]
On the latest version, happened in the last build, and still after updating/multiple restarts. 
The Post Processor will run once (10 mins after restart, as scheduled), but then just keeps counting down in the Next Run section. Server Status shows - HH:MM:SS. 
Changing the Cycle Time in the settings doesn't seem to be updating to the Server Status either.
Logs just show it wrapping up, then going silent.

To add: restarting within Medusa does jack; it just disables everything when it comes back up, killing but not restarting all the background processes (again, in Server Status). I have to restart the entire iocage.

**Comment by Aethrios** [comment]
To add a little more: 
This issue has persisted since opening the thread. Periodic restarts are still necessary. Changing the cycle time seems to hold the problem at bay for a few rounds of post processing, but it is still breaking.

**Comment by medariox** [comment]
Fixed ages ago.
