### ISSUE TITLE
downloading nfo's instead of nzb's

### ISSUE THREAD

**Issue by bjtukker** [pymedusa/Medusa#6672]
Receiving incorrect download locations from Medusa

First of all: I really like the looks of Medusa, but somehow Sabnzbd receives the nfo download location instead of the nzb from Medusa. Maybe I've misconfigured something; would like a good wiki for Medusa & Sabnzbd. 

Also, I've installed Python3 before installing Medusa, but 2.7 was used by Medusa. How can I change this?

**Comment by p0psicles** [comment]
You can start by not throwing away the issue template. Its there for a reason.
