### ISSUE TITLE
Typo - Failed downloads

### ISSUE THREAD

**Issue by metabaron** [pymedusa/Medusa#6686]
**Describe the bug**
When you list the "Failed downloads" through "Manage > Failed Downloads" (URL manage/failedDownloads/), there is a typo in the title.
Failed Downlaods
it should be
Failed Downloads

**To Reproduce**
1. Go to 'Manage'
2. Click on 'Failed Downloads'

**Expected behavior**
Proper wording

**Medusa (please complete the following information):**

Branch: master 
Commit: f46bfacf8763204fbde4f26a5916095371d494d1 
Version: 0.3.1

**Comment by sharkykh** [comment]
Fixed with #6720 (in develop branch)
