### ISSUE TITLE
Listed torrent in search

### ISSUE THREAD

**Issue by veranscoto** [pymedusa/Medusa#6689]
Sometimes I find a torrent that's from a particular source or group or something that Medusa doesn't find that I'd like to use.  It'd be nice if the Manual Search also searched torrents listed in the torrent client (assuming one's connected) and was able to be chosen/picked as a 'choice' that matches a show.

For instance, One Punch Man doesn't match One-Punch Man, but some groups don't include the "-", so if I pick up a torrent they used, the system won't 'find' it even though I have it downloaded or in queue as a downloading torrent.

This also of course brings up the fact that "-" items should also search " " and "." in filenames, but perhaps that's a different issue.

**Comment by p0psicles** [comment]
We use scene exceptions for the issue you described

**Comment by veranscoto** [comment]
I was thinking that too, but every time I was going to use it, it brings up a notice about numbering being off (i.e. Ep 305 rather than S08E12), rather than naming being different or being from a source I chose and picked up a magnet link for for myself.

Heck, even a place to put in a magnet link at the bottom of the list of torrents to choose from when doing Manual or Forced Search for individual episodes would solve the issue.

**Comment by medariox** [comment]
Post debug logs or a screenshot of the issue you are experiencing. What you describe doesn't make much sense to me.

**Comment by veranscoto** [comment]
It was more meant to be a feature request than an issue.  The simplest way I can think of to describe it is a place to put in a torrent link that medusa can handle as part of the search.  example picture below:

![image](https://user-images.githubusercontent.com/45440797/57944777-e25cd500-788c-11e9-9e78-dccd570f2332.png)

**Comment by p0psicles** [comment]
This is not really a feature that fits in our product vision. So therefor we have to kindly decline.

We can however try to help you out with Your issue with the tools already a available if you can explain your issue in more detail.

**Comment by veranscoto** [comment]
Ok, I get that.  I'll try to explain in more detail the issue I'm having.

Let's say I have a show that I've got 'watched' from Medusa.  For the example, I've got the show One-Punch Man.  Medusa may find torrents of said show, torrents 1, 2, 3, and 4 for me to choose from.  Great.  I have 4 choices to pick from when trying a 'manual search'.  However, I know a scene-group that is putting out this show.  They post torrents on their site, and I like their work because they have commentary I like.  Thus, the torrent I want is not in the list of 1-4, but instead another torrent that I manually found.  I want to be able to use this torrent and have Medusa register it.   Normaly, I could just use post-processing to do that, and it would be fine.  Unfortunately for me, the group making the show didn't name it quite the same; they named it as One Punch Man, instead of One-Punch Man.  Because there's a "-" missing, Medusa doesn't register it as the same thing in the post processing and now I've got to go manually do it.  Thus the impetus for asking to maybe drop a magnet link for a manual search.

**Comment by p0psicles** [comment]
Okay. So if you add the scene exception `one-punch man` and then run it through postprocessing, it should process fine. Which at the same time is less effort. As you dont even have to access Medusa.

For the other issue. How come Medusa cant access the torrent? Especially for anime every release group gets releases on open access providers.

**Comment by mugiwaranani** [comment]
Hey @p0psicles, just wanted to let you know that I added the scene exception "one punch man" and also tried "one-punch man" and still no results from YggTorrents (working in jackett), any ideas ?

Having the option to force search one or multiple providers with close results and add them like suggested would remove all issues..

**Comment by p0psicles** [comment]
Your not getting results from yggtorrents? That's a Total different issue. We have yggtorrents as a native provider. Have you tried that?

**Comment by p0psicles** [comment]
Im leaning to closing this issue. As its already oftopic. If you can provide debug log for a specific search on yggtorrents, ill give it a look. Pls try to get clear what Your issue is, and then het back to us

**Comment by veranscoto** [comment]
> Okay. So if you add the scene exception `one-punch man` and then run it through postprocessing, it should process fine. Which at the same time is less effort. As you dont even have to access Medusa.

I added scene exceptions for "One Punch Man" and One.Punch.Man and I'm still only getting the same results that I was getting before added those exceptions.

> For the other issue. How come Medusa cant access the torrent? Especially for anime every release group gets releases on open access providers.

I'm not sure why it can't; I can see [for example] horriblesubs on Nyaa, but it doesn't show up as a possible pick, even when I put basically every quality type as allowed. (in fact, no results from Nyaa show up).  I'm starting to wonder if it's because of the numbering/naming?  I.e. One Punch Man S2 - 05 [720p].mkv ?
