### ISSUE TITLE
Automated backup of DB and configuration to cloud service e.g. Google drive / Dropbox / etc...

### ISSUE THREAD

**Issue by c0dewhacker** [pymedusa/Medusa#6696]
**Is your feature request related to a problem? Please describe.**
A way to automatically backup the DB and configuration to an external source such as google drive would be perfect. Especially if your medusa instance is on different platforms... docker, qnap, OS install... etc....

Similar if not an addition to feature request 
http://feathub.com/SickRage/SickRage/+92 

**Describe the solution you'd like**
Probably something similar to this but built into Medusa 
https://www.instructables.com/id/Automated-Google-Drive-File-Backup-Python-Google-A/
Something like the mock up below that i've done

![backup1](https://user-images.githubusercontent.com/27728386/57965314-0c45f280-7986-11e9-9090-752972a85600.png)

**Describe alternatives you've considered**
As above, with python and a cron job you could copy the files out to a directory and just have google drive upload them in a normal sync. But this wouldn't take into account medusa's running state. something that pushes the backup files to a cloud service from within the app either on a scheduled basis or after an upgrade would be perfect and allow any platform or implementation of medusa to backup their DB and configuration to a cloud service.

**Comment by p0psicles** [comment]
That's a waste of effort. As all could be realized by a cronjob and simpele script. Have it stop Medusa. Copy db files and config.ini. start Medusa.
