### ISSUE TITLE
Yggtorrent results not in medusa but present in Jackett

### ISSUE THREAD

**Issue by mugiwaranani** [pymedusa/Medusa#6697]
Medusa doesn't show any YggTorrent results for 'One-Punch Man' and 'Shingeki no Kyojin' for example. Except those animes are all present when looking through Jackett. Even worse Yggtorrent results appear for 'One Piece'. There doesn't seem to be a name issue so I don't know what to look for

**Comment by medariox** [comment]
Closing because of missing issue template and related debug logs.
