### ISSUE TITLE
Failed to modify date of ... to series air date ...

### ISSUE THREAD

**Issue by TheHolyRoger** [pymedusa/Medusa#6700]
**Describe the bug**
When Medusa is running as a different user to the owner of the specific episode, it will fail to modify the airdate on linux systems. Filing logs with "Failed to modify date of ... to series air date ..."

**To Reproduce**
1. Enable "Set last modified filedate to the date that the episode aired?"
2. Post process a file which Medusa has access to but does not own
3. See error

**Expected behavior**
File dates are correctly modified without error:
"Changed modify date of 24 Legacy - S01E08 - 700 P.M. - 800 P.M.720p.HDTV.mkv to series air date Mar 20,2017 (20:00)"

**Medusa (please complete the following information):**
 - OS: Ubuntu 18.04.2
 - Branch: master
 - Commit: f46bfacf8763204fbde4f26a5916095371d494d1 

**Logs:**
<details>

```
Failed to modify date of 24 Legacy - S01E08 - 700 P.M. - 800 P.M.720p.HDTV.mkv to series air date Mar 20,2017 (20:00)
```
</details>

**Additional context**
Please see #6699 for fix when using systemd

**Comment by TheHolyRoger** [comment]
Same issue on Synology: #6021

**Comment by medariox** [comment]
Thanks for the PR! The change looks reasonable to me. Do you mind adding a [changelog entry](https://github.com/pymedusa/Medusa/blob/develop/CHANGELOG.md)?
