### ISSUE TITLE
Fresh Install on RPi and Auto Start does not work

### ISSUE THREAD

**Issue by allkindsofralph** [pymedusa/Medusa#6711]
After following the guide to install found here: https://github.com/pymedusa/Medusa/wiki/Medusa-installation-Debian-Ubuntu

I can run the program manually but i tried to use the SysVinit auto start method and the error i receive is:

> Failed to start medusa.service: Unit medusa.service not found.

**Comment by medariox** [comment]
That looks like a systemd error. Are you sure your system uses SysVinit and running `sudo service medusa start`?

**Comment by allkindsofralph** [comment]
I ended up fixing it by changing the runscript that was being copied. So instead I changed step 4 to

> sudo cp /opt/medusa/runscripts/init.debian /etc/init.d/medusa

**Comment by medariox** [comment]
Thank you. I've updated the guide to reflect that.
