### ISSUE TITLE
Evaluate strenght of episode name when multiple numerical strings are present

### ISSUE THREAD

**Issue by hvalev** [pymedusa/Medusa#6719]
**Is your feature request related to a problem? Please describe.**
Sometimes if an episode title features a numer (for example 5, 17) the parser interprets it as an episode name.

**Describe the solution you'd like**
I'd like to propose a hierarchy of labeling for episode names according to their strength. If multiple numerical strings are present, some such as E03 or S01E06 or Episode 23 would be evaluated and preferred to weak numbering such as a vague number 3 or 17 sitting somewhere in the episode name.

**Comment by medariox** [comment]
Without any concrete examples we can't do anything with this information. Anyway, the episode parsing in Medusa is handled by [guessit](https://github.com/guessit-io/guessit). Any suggestions should be posted over there.
