### ISSUE TITLE
Upcoming TV show doesn't get added

### ISSUE THREAD

**Issue by zaans2** [pymedusa/Medusa#6730]
**Describe the bug**
When adding a new, upcoming show I get a warning givin an `Error while loading while loading information from indexer TVDBv2` It does add a folder for the show, but it doesn't add it to the database, so it doesn't show up on the shows overview page.

**To Reproduce**
Go to `Shows` -> `Add shows` -> `Add new show`
Search for `The Unicorn` or `All Rise` (happens with both)
Select the `CBS` result
Click on `Add Show`
See warning

**Expected behavior**
I expect it to add the show.

**Medusa (please complete the following information):**
 - OS: ubuntu 18.04.2 LTS
 - Branch: master
 - Commit: [f46bfacf8763204fbde4f26a5916095371d494d1](https://github.com/pymedusa/Medusa/commit/f46bfacf8763204fbde4f26a5916095371d494d1)

**Logs:**
<details>

```
2019-05-27 09:36:42 WARNING  SHOWQUEUE-ADD :: [f46bfac] 361732: Error while loading information from indexer TVDBv2. Error: Show episode search exception, could not get any episodes. Did a full search. Exception: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/361732/episodes/query?page=1
```
</details>

**Comment by p0psicles** [comment]
The shows dont have any episodes. Medusa can't add those. But I agree we could return a more user friendly warning

**Comment by zaans2** [comment]
So if there was even a single episode it would add the show, but because it currently has no episodes it doesn't get added? This seems strange to me.

It is an upcoming show so it isn't strange that there are no episodes listen on the TVDB, but I still want to add it so when it does get episodes on the TVDB medusa does it's job.

Now I have to remember to add this show later when it has at least one episode on the indexer. Is it a technical limitation or a choice to do it this way?

**Comment by p0psicles** [comment]
It has been like this for a long time. So my guess a choice from way back

**Comment by zaans2** [comment]
Okay, first time I encountered it. I think it would be good idea to change it. Do I need to resubmit it as a feauture request?
