### ISSUE TITLE
Update YGG provider domain : https://www.yggtorrent.ch/

### ISSUE THREAD

**Issue by Sylanorr** [pymedusa/Medusa#6742]
Hello,

The YGG tracker is here now : https://www.yggtorrent.ch/

Please update the URL base at https://github.com/pymedusa/Medusa/blob/master/medusa/providers/torrent/html/yggtorrent.py#L39

Thanks

**Comment by medariox** [comment]
Already updated in develop: https://github.com/pymedusa/Medusa/commit/8a2c700b5863699e177b7b9a6aeaf05fd8768aa0

**Comment by yao89** [comment]
Hey, any news of this issue in master ?
master was updated yesterday, but nothing about this fix.
I'm missing my new episodes :'(

Thanks in advance.

**Comment by Sylanorr** [comment]
It works for me since the last update ! Try to manually launch a new search

Le jeu. 6 juin 2019 à 10:48, Adrien Labigne <notifications@github.com> a
écrit :

**Comment by yao89** [comment]
Oh, yeah today it work... Yesterday night I got errors "invalid password"...
Thanks ;)
