### ISSUE TITLE
Change or add alternate name to series

### ISSUE THREAD

**Issue by Beanux** [pymedusa/Medusa#6750]
Hello,

I've been adding some anime recently, and all of the episode were not already aired.
But they're not downloaded after aired.
They're on the tab Shedule, and processed on the search. Launching a manual search doesn't give result too.

So i found that the naming of the serie was the issue.
I've added it as the name of "The Rising of the Shield Hero", but it's also named "Tate no yuusha no nariagari" (it's only an example, i've a dozen of anime like this with dual naming, but it's one of the few currently airing).

And because i've added required word to the search vostfr/multi/french, to be sure to have it on the correct lang (subtitles search work great for series but not for anime according to my knowledge), it doesn't find it at all (name + required word).

So the options i found to solve this:
- A way to set an alternate name, like for episode
- A way to rename an existing Series
- A way to check different name based on the lang ([here](https://www.thetvdb.com/series/the-rising-of-the-shield-hero) title change according to the lang selected)
- Delete the existing serie and add it to the other name.
- Manualy (without medusa) search aired episode and add them.

I've excluded the 3rd option, (obviously the easiest to do), because it force reindexing episodes, and is not flexible to search also english name (when there is nothing found in french).

I aware that's a lazzy request, but i'm confident that it can be a good proposal anyway.

Thanks for reading, and btw thanks for all of the work you've done to Medusa:)

**Comment by medariox** [comment]
That's what scene exceptions are for.

**Comment by Beanux** [comment]
Ok, my bad, i've been misunderstanding it because of "This list appends to the original show name.". :(

I'm closing this ticket.

**Comment by nstephenh** [comment]
Came here searching for this solution. Maybe the comment should be changed to make it more clear what the field is for?
