### ISSUE TITLE
Add Beyond-HD as Torrent Search Provider

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#6766]
Please add https://beyond-hd.me as a Torrent Search Provider, unfortunately I don't have an invite.

**Comment by p0psicles** [comment]
The it's not possible. Or you give some of the devs temp access

**Comment by Rouzax** [comment]
It uses UNIT3D as backend. For now I've been able to add it using Jackett.
If I would give temp access, would you also need to initiate a lot of downloads from it?

**Comment by Rouzax** [comment]
The Jackett addition of Beyond-HD is giving me multiple duplicates of the same episode.
![image](https://user-images.githubusercontent.com/4103090/58976290-638df480-87c7-11e9-9469-14264ab60385.png)
Let me know what kind of access you would need to develop this?
If there is no need to initiate multiple downloads I'm willing to do that.

**Comment by p0psicles** [comment]
We only snatch a few torrents. But there only dropped in a folder and removed. Hit us up on discord

**Comment by medariox** [comment]
Added with https://github.com/pymedusa/Medusa/pull/6802
