### ISSUE TITLE
Post process : no nfo and thumbnails

### ISSUE THREAD

**Issue by cyan** [pymedusa/Medusa#6771]
hi,
when medusa auto post-process or when i manual post-process i'm missing more than half of the nfo and thumbnail from my episodes.
today i got 71 episodes from differents tv show and i had
71 video
34 nfo
16 thumbnails
only 15 complets sets (one episode had the thumbnail but not the nfo)

when i "Force full update" everything is generated

i just went through the issues (open and closed) and saw that i already happened 2 years ago exactly the same

thanks for your help and the great work you re doing on Medusa :)

**Comment by medariox** [comment]
Please follow the issue template to report issues. This is not because we don't want to help you (quite the contrary, actually), but because we just can't help you without the information that is required in the issue template.
