### ISSUE TITLE
Medusa stopped working 

### ISSUE THREAD

**Issue by MotleyC** [pymedusa/Medusa#6780]
Windows 10 x64. It stopped working this morning and the service won't start. It goes to paused. Was working fine until this morning. I have tried rebooting the PC which did not help. I see some file dates from today so I assume that it was updated and it broke.

**Comment by medariox** [comment]
We can't help without debug logs.

**Comment by MotleyC** [comment]
I restored a backup from this morning and did the git reset pull and it appears to be working again. Thanks
