### ISSUE TITLE
linuxserver/medusa doesn't save nzb api-keys?!

### ISSUE THREAD

**Issue by ratnose** [pymedusa/Medusa#6812]
I add a custom nzb provider, I got three, the first one works perfect, but not the other two - the api key doesn't gets saved and I can't delete made providers either.

Please help!

**Comment by medariox** [comment]
Which browser? Try a different one. This issue has never been reported, so I would assume it's something on your end (e.g. using an old browser).

**Comment by ratnose** [comment]
I had to give up on Medusa. Went to Sonarr v3 instead.
