### ISSUE TITLE
Episode title starting with number treated as multi-episode file/release

### ISSUE THREAD

**Issue by SunMar** [pymedusa/Medusa#6819]
Hi,

Recently I discovered that when an episode title starts with a number, Medusa thinks it's a multi-episode file.

For example Marvel's The Punisher season 1 episode 1 is titled "3 A.M.". When you search for this episode and grab a release with the title in it that is named "Marvels.The.Punisher.S01E01.3.A.M." it will think the file is for episode 1 and episode 3. As such it will then mark episode 3 as snatched as well (but not episode 2) and doesn't download it. Since I also have file renaming enabled this then trickles down to Plex since Meduse will rename the file to "S01E01-E03" and Plex then thinks it is episode 1 through 3 (and go straight to episode 4 after watching it).

Not a big issue, it's the first time I've come across it and I was able to manually correct it by removing the "3 A.M." from the filename after downloading but before processing, and then manually searching for and selecting a correct episode 3 release.

**Comment by p0psicles** [comment]
Can you report this at the guessit project?
