### ISSUE TITLE
[Question] ffmpeg still required?

### ISSUE THREAD

**Issue by MichaIng** [pymedusa/Medusa#6829]
I guess so since the prober is still in place + related warnings in log.

However why has it been removed from the Wiki install instructions https://github.com/pymedusa/Medusa/wiki/Medusa-installation-Debian-Ubuntu/_compare/2b46a047b9247b8d585863927bb3ebaa9e2183a4...dc2674e1aee670cf3f688b7f4567e04e82115334?

**Comment by medariox** [comment]
ffmpeg was never required. You can either install mediainfo (recommended) or ffmpeg or neither (not recommended).

**Comment by MichaIng** [comment]
@medariox
Ah okay, many thanks for clarification.
