### ISSUE TITLE
Medusa Returns Invalid Host for qBittorrent But Config Tests Successful 

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/Medusa#6830]
**Describe the bug**
2019-06-13 08:47:22 WARNING  SNATCHQUEUE-SNATCH-294492 :: [4d4a63c] qbittorrent: Invalid Host: Failed to parse: localhost:8082command
2019-06-13 08:47:22 WARNING  SNATCHQUEUE-SNATCH-294492 :: [4d4a63c] qbittorrent: Unable to send Torrent

**To Reproduce**
1. Go to 'Schedule>Search>Manual Search'
2. Click on 'any torrent'
4. See error Red X

**Expected behavior**
Torrents haven't been downloading for a bout a month now.  Fails to parse using ip localhost, 127.0.0.1, hos ip 192.168.2.24.  I use Jackett and categories populate for torrent providers.

**Medusa (please complete the following information):**

Branch:                 master 
Commit:                 4d4a63c850b583017e3cce56c819ac49d0ce5e35
 Version:                 0.3.3                  Database:                 44.14
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Windows-7-6.1.7601-SP1
Locale: | en_GB.cp1252

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by DrakeJones** [comment]
Got it. It was Issue #5838 fix: "Add an ending slash to your qBittorrent host:port, like: localhost:8080/".

You may want to change the example "URL to your qBittorrent client (e.g. http://localhost:8080)" under Search Settings>Torrent Search>qBittorrent host:port.

**Comment by p0psicles** [comment]
Can you create a screenshot of your search settings?
