### ISSUE TITLE
New TheTVDB status "Upcoming"

### ISSUE THREAD

**Issue by neoatomic** [pymedusa/Medusa#6832]
**Is your feature request related to a problem? Please describe.**
Yes. TheTVBD has a new status called " Upcoming" next to the traditional "Continuing" and "Ended". This status is currently showing as "Unknown" in Medusa.

**Describe the solution you'd like**
Adding support for this new Status. 

**Describe alternatives you've considered**

**Additional context**
Can be reproduced by adding a upcoming show like "The Mandalorian" ID:361753.
https://www.thetvdb.com/series/the-mandalorian

**Comment by sharkykh** [comment]
I believe the solution is to add it to the status map in:
https://github.com/pymedusa/Medusa/blob/8f79b736847b0a3b195b3250cd0d019137ee8fcf/medusa/indexers/indexer_config.py#L44-L64

**Comment by sharkykh** [comment]
Fixed with https://github.com/pymedusa/Medusa/commit/d5a84d39e1792c7498e96be87490d7568ec97679
