### ISSUE TITLE
[HDTorrents] Published dates swap months and days

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#6841]
**Describe the bug**
In the manual search the dates of HDTorrents swaps the Day and Month.

**Screenshots**
![image](https://user-images.githubusercontent.com/4103090/59507138-674a0700-8eaa-11e9-86a5-a2a8ffe1b4af.png)

On the site for this torrent
![image](https://user-images.githubusercontent.com/4103090/59548365-9619b900-8f4e-11e9-9692-435a2e404967.png)

Weird thing is that a different torrent is displayed correct
![image](https://user-images.githubusercontent.com/4103090/59548406-3079fc80-8f4f-11e9-8ee4-bba60fe0fabd.png)

On the site for this torrent
![image](https://user-images.githubusercontent.com/4103090/59548408-3b349180-8f4f-11e9-8c74-b8457f3ebafb.png)

**Medusa (please complete the following information):**

Medusa Info: | Branch: master Commit: 74c3f124fb599ad923e23f46fc320778b8b4217c Version: 0.3.4 Database: 44.14
-- | --
Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2o 27 Mar 2018
OS: | Windows-10-10.0.17763
Locale: | nl_NL.cp1252

**Comment by rafi-d** [comment]
Another semi-related issue in this picture:
"Updated" column does not obey the "Display fuzzy dates" setting...

**Comment by p0psicles** [comment]
Its using Europe style date format. Did you configure any localization? Or is that default for this provider?

**Comment by Rouzax** [comment]
> Its using Europe style date format. Did you configure any localization? Or is that default for this provider?

Not entirely sure, this is my profile
![image](https://user-images.githubusercontent.com/4103090/59549351-7ab5aa80-8f5c-11e9-90ac-f7f0f02f45ba.png)

It still wouldn't explain why some torrents are shown correct.

**Comment by p0psicles** [comment]
Try playing with the country / timezone settings. See if that changes the date format

**Comment by Rouzax** [comment]
Did a test
Torrents with location set to The Netherlands
![image](https://user-images.githubusercontent.com/4103090/59549402-455d8c80-8f5d-11e9-9fff-34f70e4492a9.png)

Torrents with Location set to US.
![image](https://user-images.githubusercontent.com/4103090/59549419-79d14880-8f5d-11e9-9369-611986868918.png)

**Comment by p0psicles** [comment]
If that's the default format well have to fix it

**Comment by Rouzax** [comment]
Do you need access to test it?

**Comment by rafi-d** [comment]
> 
> 
> Another semi-related issue in this picture:
> "Updated" column does not obey the "Display fuzzy dates" setting...

Added it a new issue. FYI...
