### ISSUE TITLE
Link to release uses wrong url

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#6853]
**Describe the bug**
The link for releases on the Help->Info page uses the wrong url (Field name is Version:)

the link in the app is ```http://dereferer.org/?https://github.com/pymedusa/Medusa/releases/tag/0.3.4```

the real link is (note the v in front of the number)
```http://dereferer.org/?https://github.com/pymedusa/Medusa/releases/tag/v0.3.4```

**To Reproduce**
click on the release link besides the version: label

**Expected behavior**
you are forwarded to the correct github page.

**Medusa (please complete the following information):**
all current versions

**Comment by sharkykh** [comment]
Nice catch!

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/6854
