### ISSUE TITLE
Snatch failed with xthor provider

### ISSUE THREAD

**Issue by TheCalcifer** [pymedusa/Medusa#6870]
**Describe the bug**
Hi,
I recently update Medusa, and since then, I didn't manage to snatch any torrent with my provider

**To Reproduce**
1. Go to an episode you want to snatch
2. Click on Snatch
3. See error

**Expected behavior**
The provider search works

**Medusa (please complete the following information):**
 - OS: Win 7
 - Branch: master
 - Commit: 74c3f124fb599ad923e23f46fc320778b8b4217c
 - Python version: 3.7.3
 - Database version: 44.14

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-06-24 12:36:35 ERROR    SEARCHQUEUE-FORCED-290853 :: [Xthor] :: [74c3f12] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\json\xthor.py", line 133, in parse
    if seeders < self.minseed:
TypeError: '<' not supported between instances of 'str' and 'int'
```
</details>

Thanks in advance

**Comment by medariox** [comment]
Thanks for the bug report. It will be fixed with https://github.com/pymedusa/Medusa/pull/7103
