### ISSUE TITLE
Add option to try and snatch 60FPS episodes

### ISSUE THREAD

**Issue by sammcj** [pymedusa/Medusa#6875]
**Describe the solution you'd like**

It would be great if I could select a box to ‘prefer 60fps’ (or other FPS), that would be awesome.

**Describe alternatives you've considered**

Likewise with 60FPS video, it would be neat to have this for HDR/DolbyVision episodes

—

I’m sorry if this has already been requested, I did a search and didn’t find the same request.

**Comment by medariox** [comment]
You can use preferred words to do that.
