### ISSUE TITLE
Power Loss.. all episode statuses changed from 'skipped' to 'wanted'

### ISSUE THREAD

**Issue by Tailslide** [pymedusa/Medusa#6884]
**Describe the bug**
My Synology box lost power and when it came back up all the shows that were previously marked 'skipped' became 'wanted' and medusa went on an all night downloading binge.  Now I have to go through every show and change them back to 'skipped'.

**To Reproduce**
N/A

**Expected behavior**
Stay in a consistent state after abrupt termination

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Synology
 - Branch: master
 - Commit: 74c3f124fb599ad923e23f46fc320778b8b4217c 
 - Python version: 2.7.14
 - Database version: 44.14

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
N/A
```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
How should we reproduce this?

**Comment by Tailslide** [comment]
Make a script to randomly kill and restart the process until the status changes?

**Comment by p0psicles** [comment]
I can garantee you that I can kill the process 100 times. And it won't reproduce. I could try to simulate what happened on your system at time of shutdown, but I would need debug logs for that.

**Comment by medariox** [comment]
That won't help. It likely happened because the DB was being updated when the system crashed.
You should post (debug) logs before the crash happened, so that we can investigate.

**Comment by Tailslide** [comment]
I didn't have the debug logs enabled at the time.  I was under the impression this section was for reporting bugs you can close this if you want.

**Comment by medariox** [comment]
You should post the normal logs in this case.

**Comment by Tailslide** [comment]
Well the good news is that I did have debug logs enabled at the time.  The bad news is that it happened yesterday morning and the logs only span 24 hours so it doesn't cover the power loss. Maybe because of all the download activity going on?  I can grab the logs immediately if I notice it quick enough next time.
