### ISSUE TITLE
Update init scripts to use Python 3

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#6892]
Update init scripts to use Python 3
### [`runscripts` folder](https://github.com/pymedusa/Medusa/tree/develop/runscripts)
- [ ] [`init.debian`](https://github.com/pymedusa/Medusa/blob/develop/runscripts/init.debian)
- [ ] [`init.fedora`](https://github.com/pymedusa/Medusa/blob/develop/runscripts/init.fedora)
- [ ] [`init.freebsd`](https://github.com/pymedusa/Medusa/blob/develop/runscripts/init.freebsd)
- [ ] [`init.gentoo`](https://github.com/pymedusa/Medusa/blob/develop/runscripts/init.gentoo)
- [ ] [`init.solaris11`](https://github.com/pymedusa/Medusa/blob/develop/runscripts/init.solaris11)
- [ ] [`init.systemd`](https://github.com/pymedusa/Medusa/blob/develop/runscripts/init.systemd)
- [ ] [`init.ubuntu`](https://github.com/pymedusa/Medusa/blob/develop/runscripts/init.ubuntu)
- [ ] [`init.upstart`](https://github.com/pymedusa/Medusa/blob/develop/runscripts/init.upstart)

**Comment by kerosyn** [comment]
One problem is the minimum version of python3 that Medusa supports is 3.5, but the wiki suggest 3.6. Not all distros are including (or have available) the same version. So I don't know if hardcoding a specific 3.x version would make sense.

Would just using the generic /usr/bin/python3 work? Are there other checks in place warning the user that they have a non-supported version of python3?

I have started a branch with just swapping python2.7 to python3, but not sure if that would break things. Seems like a simple enough change without much programming experience otherwise.

**Comment by sharkykh** [comment]
Thank you for taking the time.

> One problem is the minimum version of python3 that Medusa supports is 3.5, but the wiki suggest 3.6. Not all distros are including (or have available) the same version. So I don't know if hardcoding a specific 3.x version would make sense.
>
> Would just using the generic /usr/bin/python3 work? Are there other checks in place warning the user that they have a non-supported version of python3?

Minimum version is 3.5 (I should actually change this to 3.5.2 (see below).
`/usr/bin/python3` should be okay for most systems.
Yes, there is a check in place to make sure the correct Python version is used:
https://github.com/pymedusa/Medusa/blob/795e230e1ce742d833bdcdb7b736bfc0fcc7eba1/medusa/init/__init__.py#L43-L46

> I have started a branch with just swapping python2.7 to python3, but not sure if that would break things. Seems like a simple enough change without much programming experience otherwise.

Yes, the change itself is easy enough, but the reason I opened this issue instead of just blindly changing `python2.7` to `python3` is **because I don't know how this affects each distro**.

### Whether or not we should blindly merge #6905 and deal with the possible issues later, is up for discussion.

-----

**Why 3.5.2?**
Because the next version of `tornado` (v6.x) will only support 3.5.2 and above.
See "prerequisites" on https://www.tornadoweb.org/en/branch6.0/index.html#installation.
