### ISSUE TITLE
Wanted episode status is set very late compared to airing time delaying the episode download

### ISSUE THREAD

**Issue by mr-orange** [pymedusa/Medusa#6911]
**Describe the bug**
The wanted episode status is set very late , the episode air on 3AM and the wanted status is set to 10.00 AM.

Scene Example: The hand maid tale S03E07 will air in my Time zone at 3AM but the wanted status is set at 10AM

2019-07-03 10:10:28 INFO	DAILYSEARCHER :: [74c3f12] Setting status (Wanted) for show airing today: The Handmaid's Tale - S03E07 - Under His Eye 

**Expected behavior**
Set the wanted status at 3AM or 1 Hour after the episode is aired.

**Medusa (please complete the following information):**
 - OS:  Linux-4.9.134-armv7l-with-glibc2.4
 - Branch: master
 - Commit: 74c3f124fb599ad923e23f46fc320778b8b4217c
 - Python version: 3.7.2
 - Database version: 44.14

**Debug logs (at least 50 lines):**
Medusa is running 24H/24H

2019-07-03 10:10:28 INFO	DAILYSEARCHER :: [74c3f12] Setting status (Wanted) for show airing today: The Handmaid's Tale - S03E07 - Under His Eye 

**Additional context**
N/A

**Comment by p0psicles** [comment]
Just making sure. Did you configure a search delay for this show?

**Comment by mr-orange** [comment]
Nope...


________________________________
Da: p0ps <notifications@github.com>
Inviato: mercoledì, luglio 3, 2019 2:10 PM
A: pymedusa/Medusa
Cc: Mr_Orange; Author
Oggetto: Re: [pymedusa/Medusa] Wanted episode status is set very late compared to airing time delaying the episode download (#6911)


Just making sure. Did you configure a search delay for this show?

**Comment by p0psicles** [comment]
Still need some debug logs to troubleshoot this. Try to resolve that first.

Which timezone are you in?

**Comment by p0psicles** [comment]
The status is evaluated at each daily search. So it should never be later then airdate + Max daily search interval

**Comment by mr-orange** [comment]
The problem is the debug log is empty because the debug  option was not set.
I have only the log at info level and I think they areuseless.
I'm In italy The show aired in my time zone at 3AM.
The problem is for all show I think.

**Comment by mr-orange** [comment]
My next episode schedule is on Monday 8 is another show and I will check if the problem persist on other show and I will upload the debug log in the case.

**Comment by mr-orange** [comment]
Found something strange, The time of airing of the show is not correct.
My config are to show the airing time to local time zone
In my time zone the local time for Greys anatomy (a US show) is set to 8 PM and that is not possible.
The same show on the scheduled section has the correct time (02.00 AM)
Is it possible that the airing time routine get broken?

**Comment by medariox** [comment]
The airing time on the show page is always set to original time. You have to look for the single episodes air time.

**Comment by mr-orange** [comment]
Medariox you are right, after some air date time checking it seem the show air very late in the US and I got confused with the air time of others US show. I'm sorry.
I'll close the issue. Thanks for the support.

**Comment by p0psicles** [comment]
You can still use airdate offset to work around this
