### ISSUE TITLE
Unable to save changed Logging option in General Config

### ISSUE THREAD

**Issue by mr-orange** [pymedusa/Medusa#6912]
**Describe the bug**
Unable to save changed Logging option in General Config.
The saving button do not show the saving notification and the changed config is not saved.

**To Reproduce**
1. Go to General config - Logging option
2. Change a value and save
3. No saving notification is shown
4. The changed config is not saved

**Expected behavior**
The changed config is saved

**Screenshots**

**Medusa (please complete the following information):**

    OS: Linux-4.9.134-armv7l-with-glibc2.4
    Branch: master
    Commit: 74c3f12
    Python version: 3.7.2
    Database version: 44.14

**Debug logs (at least 50 lines):**
N/A

**Comment by p0psicles** [comment]
Just tested myself. Seems to work ok here. I unchecked debug logs. Refreshed page and it was still unchecked

**Comment by p0psicles** [comment]
You have to restart after checking it to make it have effect

**Comment by mr-orange** [comment]
yes I know but to me is not working, also no error and no debug log about saving the new config...

**Comment by sharkykh** [comment]
As for the notifications not showing up - #3956.
Not sure why the issue is closed.
As far as I know the effect of changing the debug option is immediate (you shouldn't need to restart).
Try checking the `config.ini` file after you click to save the configuration and look for `debug =`.
