### ISSUE TITLE
Notifications for >1 Plex Servers Fails

### ISSUE THREAD

**Issue by adamgoldberg** [pymedusa/Medusa#6921]
**Describe the bug**
Medusa cannot notify >1 Plex servers, it yields a parse error (theory described below)

If I put two valid Plex servers in this section, and click 'save', then 'test', I get this in the log:

`2019-07-06 11:38:46 WARNING	Thread-5 :: [74c3f12] PLEX: Error while trying to contact Plex Media Server: Failed to parse: 192.168.55.78:32400,192.168.55.248:32400`

**To Reproduce**
In Settings...Notifications...Home Theater/NAS, notifying a Plex Media Server (second item from the right after Kodi, Medusa will notify Plex that there's new content.   There seems to be UI provision for notifying >1 Plex servers, by entering each server on a different line.

If I put two valid Plex servers in this section, and click 'save', then 'test', I get this in the log:

`2019-07-06 11:38:46 WARNING	Thread-5 :: [74c3f12] PLEX: Error while trying to contact Plex Media Server: Failed to parse: 192.168.55.78:32400,192.168.55.248:32400`

Investigation:

It seems like 'hosts'  should be a list of hosts, and the loop  in medusa/notifiers/plex.py at around line 145, generates a notification for each (for cur_host in hosts), but the logged error seems to indicate that cur_host is "192.168.55.78:32400,192.168.55.248:32400" (i.e., not split into two as it should've been).
 
```
        for cur_host in hosts:
            url = '{schema}://{host}/library/sections'.format(
                schema=schema, host=cur_host
            )
[otherstuff]
            try:
                response.raise_for_status()
            except requests.RequestException as error:
                if response.status_code == 401:
                    log.warning(u'PLEX: Unauthorized. Please set TOKEN or USERNAME and PASSWORD in Plex settings')
                else:
                    log.warning(u'PLEX: Error while trying to contact Plex Media Server: {0}', ex(error))
                failed_hosts.add(cur_host)
                continue

```

**Expected behavior**
I'd expect that Medusa would notify each of the >1 Plex Servers.

**Screenshots**

**Medusa (please complete the following information):**
Medusa Info: | Branch: master Commit: 74c3f124fb599ad923e23f46fc320778b8b4217c Version: 0.3.4 Database: 44.14
-- | --
Python Version: | 2.7.13 (default, Apr 29 2017, 01:14:04) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]
SSL Version: | OpenSSL 1.0.1s-freebsd 1 Mar 2016
OS: | FreeBSD-10.3-RELEASE-amd64-64bit-ELF
Locale: | en_US.UTF-8

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
(not 50 lines, sorry, there's only one line generated during this whole process)
<details>

```
2019-07-06 11:38:46 WARNING	Thread-5 :: [74c3f12] PLEX: Error while trying to contact Plex Media Server: Failed to parse: 192.168.55.78:32400,192.168.55.248:32400
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Can you check config.ini and report on how the value is saved there?

**Comment by adamgoldberg** [comment]
Here's what it looks like:
`plex_server_host = 192.168.55.78:32400, 192.168.55.248:32400 `

**Comment by hyperletters** [comment]
I have noticed this same issue when trying to add 2 servers

**Comment by medariox** [comment]
Closing as fixed.
