### ISSUE TITLE
Anime - Medusa looking at wrong season folder for future episodes.

### ISSUE THREAD

**Issue by Grahamvs** [pymedusa/Medusa#6922]
I've got this strange issue with an anime (Fairy Tale) - it keeps thinking that it should look for season 8 episodes in the season 3 folder (eg: it thinks Season 8 Episode 39 is actually "Season 03/Fairy Tail S03 E39 (Footprints of the Myth).mp4"). It's also using the same file for Season 3.

I've recreated this with a new copy of Medusa (it's a clean database, I only copied in the config.ini), then after adding Fairy Tail as an existing show, I told it to do a "Force full update" as it had set the latest episode (which released the day before) to "unaired". That didn't seem to do anything, so I went to "Mass Update" and used the "update" command from there.

After refreshing, I noticed it had set all future episodes to the Season 3 folder, as well as setting them as archived (see image)

![image](https://user-images.githubusercontent.com/5189621/60775374-3d3adc00-a11a-11e9-8087-586febe8bfab.png)

**Comment by p0psicles** [comment]
Your using tvdb as indexer. There it uses smaller seasons then how it s released. So it will store and name the files using the indexer. That's how it's supposed to work

**Comment by Grahamvs** [comment]
Thanks, changing indexer solved my issue.
