### ISSUE TITLE
Failed to edit groups & required words

### ISSUE THREAD

**Issue by Lulu300** [pymedusa/Medusa#6928]
**Describe the bug**
When I try to edit groups or required words, nothing happen and I got an error 500.

**Screenshots**

![firefox_2019-07-09_14-13-02](https://user-images.githubusercontent.com/12187295/60894908-e8a37800-a263-11e9-8c69-79998dd22513.png)
![firefox_2019-07-09_14-13-31](https://user-images.githubusercontent.com/12187295/60894909-e93c0e80-a263-11e9-8025-9415126c326c.png)
![firefox_2019-07-09_16-05-24](https://user-images.githubusercontent.com/12187295/60894910-e93c0e80-a263-11e9-9af8-523b76d1a9de.png)

**Medusa (please complete the following information):**
 - OS: Linux-4.19.50-v7+-armv7l-with-debian-10.0
 - Branch: develop
 - Commit: b07e3b5d9d98e86c2499a17790f7d8d1c636fb6f
 - Python version: 3.7.3 (default, Apr  3 2019, 05:39:12)  [GCC 8.2.0]
 - Database version: 44.14

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/6929
