### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Network 10

### ISSUE THREAD

**Issue by solyxius** [pymedusa/Medusa#6934]
### INFO
**Python Version**: `2.7.14 (default, Mar 03 2018, 11:05:58) [GCC 7.3.0]`
**Operating System**: `Linux-4.2.8-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: https://gist.github.com/f0e143356075e04534a8a67b9bbebb04
### ERROR
<pre>
2019-07-11 07:17:59 ERROR    Thread_8 :: [74c3f12] Missing time zone for network: Network 10
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added: https://github.com/pymedusa/medusa.github.io/commit/321b516c09b1109c0ead6a5e34560edba95ce2b1
