### ISSUE TITLE
Mass Update Airdate offset

### ISSUE THREAD

**Issue by knowair** [pymedusa/Medusa#6939]
**Is your feature request related to a problem? Please describe.**
might be a bit niche, even I as the requester might only use it once or twice! 

Currently I can only change the option "Series > Edit > Advanced > Airdate Offset" individually via each show one at a time.

**Describe the solution you'd like**
Would be great to have an option under "Manage > Mass Update > Edit Selected" to set "Airdate Offset" in bulk in the same way as there is options already for i.e, root Directory or Quality 

**Describe alternatives you've considered**
I can only do in individually at the moment!

**Additional context**

**Comment by p0psicles** [comment]
To be honest, I highly doubt you have more then three shows in your library which need an offset

**Comment by knowair** [comment]
> To be honest, I highly doubt you have more then three shows in your library which need an offset

Until recently i would have thought the same, but i've been planning to get an hd home run over-the-air TV to Network box and it will record shows as well as allow live TV to be available via the home network. 

I thought, rather than remove these shows from Medusa I would just set them to be offset by a day. during which time the recording will be sorted. Then, should there ever be an issue with the recording and the episode isn't there within the day Medusa would then do it's thing and i'd not miss the episode.

I've got quite a few shows in the list so went to do a Mass Update and when the option wasn't there, figured it couldn't hurt to ask you guys the question! I knew it would be a niche request, and that it may not be worth your time, so if it doesn't happen i'm not going to be throwing my toys out of the pram!!

Cheers for all you do!

**Comment by medariox** [comment]
Not worth the work.
