### ISSUE TITLE
how to add show.rss to Medusa

### ISSUE THREAD

**Issue by SirusZex** [pymedusa/Medusa#6941]
l previously located this:

Config -> Search Providers -> Configure Custom Torrent Providers
Provider name: ShowRSS
RSS URL: https://showrss.info/other/all.rss
Search element: tv_raw_title
Add & save config.

however lm unable to get it to work.

however since the site has updated since that time l decided to try adding the RSS url as:
http://showrss.info/user/[userID].rss

and the search element as: tv:raw_title

but no episodes are showing up when searching manually for the RSS despite them being present in the RSS feed.

**Comment by medariox** [comment]
Manual and Backlog search is not supported with RSS feeds. Only daily search. This has always been the case. Think about using Jackett if you need more providers.
