### ISSUE TITLE
Warning when scheduler indicates not alive

### ISSUE THREAD

**Issue by bluelavalamp** [pymedusa/Medusa#6943]
Sometimes when I go into Server Status the Scheduler indicates that the Post Process is not alive.  To fix this I just restart Medusa and all is good.  But I get no indication of this fact unless I go in there to look.  It would be nice if some piece of the Scheduler is not alive to put a warning at the top of the screen like is done when an Update is available for download.  That way I will notice it quicker if something has died.

Thanks

**Comment by p0psicles** [comment]
You should have some log why it crashed. Turn on debug logging and wait for it to crash again.

Then please use the issue report template to provide required info.
