### ISSUE TITLE
Failed to start Medusa Daemon.

### ISSUE THREAD

**Issue by Kimbo256** [pymedusa/Medusa#6950]
Hello, I am running a back up of a Linux Centos server. I forgot mySQL database password so I am attempting to use Medusa to discover it.

I am following the instructions at this link to install and enable medusa:
https://github.com/pymedusa/Medusa/wiki/Medusa-installation-CentOS

Something keeps going wrong. When I reach step 7 of the instructions, I get the following error:
ul 16 18:31:50 ip-10-0-0-178 systemd[1]: Unit medusa.service entered failed state.
Jul 16 18:31:50 ip-10-0-0-178 systemd[1]: medusa.service failed.
Jul 16 18:31:50 ip-10-0-0-178 systemd[1]: medusa.service holdoff time over, scheduling restart.
Jul 16 18:31:50 ip-10-0-0-178 systemd[1]: Stopped Medusa Daemon.
Jul 16 18:31:50 ip-10-0-0-178 systemd[1]: start request repeated too quickly for medusa.service
Jul 16 18:31:50 ip-10-0-0-178 systemd[1]: Failed to start Medusa Daemon.
Jul 16 18:31:50 ip-10-0-0-178 systemd[1]: Unit medusa.service entered failed state.
Jul 16 18:31:50 ip-10-0-0-178 systemd[1]: medusa.service failed.

Troubleshooting I have already tried:
- I started from step two and tried to instal again. Same error. 
- I looked for the collection.py file and it was not present in my medusa file to delete.

Any advice on what could be going wrong?

**Comment by medariox** [comment]
Have you change the your systemd unit to Python 3? See https://github.com/pymedusa/Medusa/wiki/Switch-to-Python-3#systems-with-systemd
If yes, try to start Medusa manually, e.g.: `python3.6 /usr/share/medusa/start.py` and see what the issue is.
