### ISSUE TITLE
Cannot submit error to GitHub

### ISSUE THREAD

**Issue by SunMar** [pymedusa/Medusa#6952]
Hi,

When I try to submit an error directly from Medusa I get the following warning:

```
2019-07-17 10:07:35 WARNING  Thread_6 :: [74c3f12] GitHub returned an error "Not Found". If using a token, make sure the proper scopes are selected.
```

I am using a personal access token and already re-created it to make sure nothing was wrong there. Are there specific permissions required? If so what are they? And maybe they can be mentioned on the configuration page. It's also possible to add a clickable link that takes you directly to the GitHub page where you can create a token with the correct settings already checked. For example if you need `public_repo` and `read:user` you can add the link: https://github.com/settings/tokens/new?scopes=public_repo,read:user. That link can be changed using just the names you see on the page (the "header" level ones like `repo` are also possible to use).

**Comment by SunMar** [comment]
Side note, I just changed the configuration to use username/password which allowed me to submit the report, but it didn't give me any feedback about the issue it was submitted to. I had to go into the logs and find there that it had actually added the error as a comment on an existing issue. It would also be nice if after submitting you get some information about what happened (new issue created, existing issue commented) with a clickable link that can take you to the page on GitHub to for example add additional information.

**Comment by sharkykh** [comment]
> It's also possible to add a clickable link that takes you directly to the GitHub page where you can create a token with the correct settings already checked. For example if you need public_repo and read:user you can add the link: github.com/settings/tokens/new?scopes=public_repo,read:user. That link can be changed using just the names you see on the page (the "header" level ones like repo are also possible to use).

There is a link just like that next to the "GitHub personal access token" setting, when you don't have a personal key set (it is replaced by the "Manage tokens" button when you do have one set).
The link is: https://github.com/settings/tokens/new?description=Medusa&scopes=user,gist,public_repo
Although I'm not sure if all these scopes really needed.
Basically we need permission to:
1. Create gists on your behalf
2. Open issues and write comments on your behalf
3. Get your username
We need to look more into which scopes are needed, to limit the scopes as much as possible.

**Comment by sharkykh** [comment]
> Side note, I just changed the configuration to use username/password which allowed me to submit the report, but it didn't give me any feedback about the issue it was submitted to. I had to go into the logs and find there that it had actually added the error as a comment on an existing issue. It would also be nice if after submitting you get some information about what happened (new issue created, existing issue commented) with a clickable link that can take you to the page on GitHub to for example add additional information.

There is a notification, but notifications are currently only visible on HTTPS connections because of a change to the web standard (web notifications on insecure hosts are no longer allowed)
#3956

**Comment by SunMar** [comment]
thank you @sharkykh ! I'll keep the notifications in mind with regard to HTTPS, I indeed don't have HTTPS since it's only on my local LAN. so it doesn't have a public domain which means I can't use LetsEncrypt and I don't like self-signed certificates nor the hassle of having to rotate a proper certificate

as for the permissions, maybe it's an idea to add a small text where you can set the token that always shows, whether it's empty or filled, that you need to allow `gist`? I think I've had the token with no permissions at all for while now and it doesn't interfere with normal operations, this Submit Error was the first time I've had an issue with this

**Comment by medariox** [comment]
Use a new token with the correct permissions.
