### ISSUE TITLE
[APP SUBMITTED]: ValueError: 'Seeders' is not in list

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#6958]
### INFO
**Python Version**: `3.7.3rc1 (default, Mar 13 2019, 11:01:15) [GCC 8.2.0]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-buster-sid`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@0418408f642fdab010a45bba35544bd8b6a7924e
**Link to Log**: https://gist.github.com/d35518318cdb9f9d758f65cbd7388dc4
### ERROR
<pre>
2019-07-19 01:16:45 ERROR    SEARCHQUEUE-MANUAL-18347 :: [BJ-Share] :: [0418408] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/0418408f642fdab010a45bba35544bd8b6a7924e/medusa/providers/torrent/html/bjshare.py#L204">medusa/providers/torrent/html/bjshare.py</a>", line 204, in parse
    seeders = try_int(cells[labels.index('Seeders') + group_index].get_text(strip=True))
ValueError: 'Seeders' is not in list
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Incidental or structural / reproducible?

**Comment by marcio-ota** [comment]
BJ-Share changed the layout of tables, including DualAudio, Seasons, ...

**Comment by marcio-ota** [comment]
BJShare changed the layout. Until they find a final solution, change the file bjshare.py
from:
```
seeders = try_int(cells[labels.index('Seeders') + group_index].get_text(strip=True))
leechers = try_int(cells[labels.index('Leechers') + group_index].get_text(strip=True))
```
to:
```
seeders = 1
leechers = 1
```

**Comment by p0psicles** [comment]
@duramato mind sharing your creds with us?

**Comment by marcio-ota** [comment]
this is better:

seeders = try_int(cells[4].get_text(strip=True))
leechers = try_int(cells[5].get_text(strip=True))
...
torrent_size = cells[2].get_text(strip=True)

**Comment by p0psicles** [comment]
Did you test that?

**Comment by p0psicles** [comment]
I can add that fix to a PR I'm doing later today

**Comment by p0psicles** [comment]
@marcio-ota and others. The group_index was used as a more dynamic approach. As it's possible for a user of the site to enable/disabling some sort of grouping "columns?". So now this takes the fixed approach. I'll change it for now. But if anyone else has issues with this. They need to check this setting in theyre providers config panel.
