### ISSUE TITLE
Is it possible for Medusa to find obfuscated records from Usenet?

### ISSUE THREAD

**Issue by plato79** [pymedusa/Medusa#6968]
**Is your feature request related to a problem? Please describe.**
Medusa uses nzb indexers to find episodes, although some episodes are obfuscated so they're though to detect by copyright owners. Medusa obviously cannot detect them because they're mostly not indexed.

**Describe the solution you'd like**
Newsleecher ( usenet client ) uses a supersearch ( not sure if the api is open ) to search for episodes. Is it possible for Medusa to create its' own NZB files?

**Describe alternatives you've considered**
I'm using Newsleecher to manually export NZB to my usenet client ( sabnzbd plus ) and tag the nzb as tv episode so it's pushed to the process folder.

**Additional context**
Here is an example of obfuscated file description on Newsleecher:

`The.Handmaids.Tale.S03E09.Heroic.1080p.HULU.WEB-DL.AAC2.0.H.264-NTb | supersearch deobfuscated | b684865793d64fbf84f1952acd3c36c4 "b684865793d64fbf84f1952acd3c36c4"`

**Comment by medariox** [comment]
It's not possible.
