### ISSUE TITLE
[APP SUBMITTED]: qbittorrent: Unable to set the label for Torrent

### ISSUE THREAD

**Issue by Jamyz** [pymedusa/Medusa#6974]
### INFO
**Python Version**: `2.7.15 (default, May  4 2019, 18:38:15) [GCC 8.2.0]`
**Operating System**: `Linux-4.19.36-armv7l-with-glibc2.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: https://gist.github.com/7454095b4372d6e5b9afa3accfb8bdfd
### ERROR
<pre>
2019-07-23 22:28:16 ERROR    SNATCHQUEUE-SNATCH-273181 :: [74c3f12] qbittorrent: Unable to set the label for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Jamyz** [comment]
I found this tip. Create before the label in qbitorrent !!!!

**Comment by agpenton** [comment]
### INFO
**Python Version**: `2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]`
**Operating System**: `Linux-4.9.0-9-amd64-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/1cb36199df6a8234e38b4d8c83830200
### ERROR
<pre>
2019-09-01 14:32:28 ERROR    SNATCHQUEUE-SNATCH-210171 :: [f46bfac] qbittorrent: Unable to set the label for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by 318kbStudio** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18980-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-09-14 18:22:41 ERROR    SNATCHQUEUE-SNATCH-80117 :: [baad1e5] qbittorrent: Unable to set the label for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
With #7474, this error was replaced with a warning:

>qBittorrent: Unable to set torrent label. You need to create the label in qBittorrent first.

Thanks for the pointer, @Jamyz
