### ISSUE TITLE
[APP SUBMITTED]: sqlite3.OperationalError: table [nyaa] already exists

### ISSUE THREAD

**Issue by zaans2** [pymedusa/Medusa#6984]
### INFO
**Python Version**: `3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]`
**Operating System**: `Linux-4.18.0-24-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: https://gist.github.com/0a8012090c7b8e5871a15c483ccd38c0
### ERROR
<pre>
2019-07-27 10:57:29 ERROR    SEARCHQUEUE-BACKLOG-355567 :: [Nyaa] :: [74c3f12] DB error: table [nyaa] already exists
Traceback (most recent call last):
  File "/opt/**********/**********/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/**********/**********/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: table [nyaa] already exists
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Maybe best to delete csche.db In cache folder and restart

**Comment by p0psicles** [comment]
Cache.db
