### ISSUE TITLE
torrent friendly way of relocating files using qbittorrent (avoiding hard links)

### ISSUE THREAD

**Issue by wwikke** [pymedusa/Medusa#6987]
A random reddit user was so nice to share this code.

Code (medusa/clients/qbitorrent.py)
https://pastebin.com/0AMY2ben

Problem: "All my torrent downloads via Medusa go into an in_progress folder and stay there. I want them to end up in nice tidy show folders and I want to seed them, but I don't want to hardlink (seems messy) or copy them (uses more storage) in post processing."

The user reports it working:
"After adding the torrent it changes the location of it (moving the files) into the series folder."

It uses the qbittorent setLocation api - https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#set-torrent-location

Reddit thread:
https://www.reddit.com/r/PyMedusa/comments/bq68ba/how_to_run_setlocation_on_finished_torrents_via/

**Comment by medariox** [comment]
We don't provide support for custom code modifications.

**Comment by wwikke** [comment]
I understand. I don't need support. 
I wanted to raise your awareness and thought it might prove a useful change to the code.

**Comment by p0psicles** [comment]
We work through pull requests. It's not that difficult. Allot of beginner tutorials on using git and github
