### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: NOVA

### ISSUE THREAD

**Issue by clientxbg** [pymedusa/Medusa#6989]
### INFO
**Python Version**: `2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]`
**Operating System**: `Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-07-30 21:21:51 ERROR    Thread_0 :: [74c3f12] Missing time zone for network: NOVA
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
There are many networks with such name.
https://en.wikipedia.org/wiki/Nova_(TV)

I suppose in order to add a time zone, we need to find out which network

**Comment by clientxbg** [comment]
### INFO
**Python Version**: `2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]`
**Operating System**: `Linux-5.0.0-23-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: https://gist.github.com/76b9a469b9d299bf5d81c244a791f482
### ERROR
<pre>
2019-08-03 01:31:55 ERROR    Thread_9 :: [74c3f12] Missing time zone for network: NOVA
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
