### ISSUE TITLE
Add shows that have no S01 tag but rather date tag

### ISSUE THREAD

**Issue by homegreewn** [pymedusa/Medusa#7033]
I'm not sure if it's correct to post this here. I'm trying to download Conan and the show is labeled by date instead of season+ep i.e. "Conan 2019.07.27 Kevin Bacon", in torrent sites. 

Is this possible to configuer with medusa as is? If not, I guess this is indeed a feature request.

**Comment by p0psicles** [comment]
Check the air by date option for the show

**Comment by homegreewn** [comment]
> Check the air by date option for the show

where is it located?
