### ISSUE TITLE
Pages are not being automatically updated on status changes

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#7034]
Not sure if #3431 is referring  to this one:
Episodes status (main page, shows page etc) is not being "refreshed" when events occur. This cause wrong info to be shown on pages, until you manually refresh them.  
We can see this for a snatching event or just  time-related event (air date/wanted etc). 

I suggest an option to auto-refresh the currently displayed Medusa browser page *if* it is relevant to an event. So, for example main page - will be almost always refreshed, a specific show page will refresh only for events related to this show. 

Thanks

Rafi

**Comment by p0psicles** [comment]
Preparations have already been made for this. It will be implemented when the pages have been vueified.

**Comment by p0psicles** [comment]
Preparations have already been made for this. It will be implemented when the pages have been vueified.

**Comment by rafi-d** [comment]
Great, thanks! 

Any ETA?... :)

**Comment by p0psicles** [comment]
No it's allot of frondend work. And we don't have a pure frondend Dev. Could be 3 months. Or a year before everything has been converted
