### ISSUE TITLE
Medusa can't find anime episode(s)

### ISSUE THREAD

**Issue by BlayZin** [pymedusa/Medusa#7041]
**Describe the bug**
Medusa can't find any episodes of DanMachi season 2 on animebytes via jackett or built in AB provider even though the episode is out already. Weirdly enough the first 3 episodes were downloaded but not the 4th.
I added all kinds of scene exceptions and tried with absolute and scene numbering but it can't get any results in manual search.
I tested manually searching via Jackett and this is what I see https://ptpimg.me/90d3pz.png
so there is lots of stuff to be found I and all kinds of namings for this particular anime.
In the logs you can see some unicode error and it seems that it is already going to be fixed for 0.3.5 but I don't know if it has anything to do with it.
Is there some way to fix this?

**To Reproduce**
1. add AB as provider via jackett or inbuilt
2. Go to 'Shows'
3. Click on 'Is It Wrong to Try to Pick Up Girls in a Dungeon?'
4. Scroll down to 'episode 4 (maybe)'
5. Click on 'Manual search'
6. See nothing

**Expected behavior**
Finding latest episode and downloads/post processes it.

**Screenshots**
Jackett results: https://ptpimg.me/90d3pz.png
Medusa show page: https://ptpimg.me/qa5smj.png
Show important settings 1: https://ptpimg.me/x3caf5.png
Show important settings 2: https://ptpimg.me/1we6c2.png

**Medusa (please complete the following information):**
 - OS: ubuntu 18.04 x64
 - Branch: master
 - Commit: 74c3f124fb599ad923e23f46fc320778b8b4217c
 - Python version: 2.7.15+
 - Database version: 44.14

**Debug logs (at least 50 lines):**
Since the log is too long (it includes the whole manual search process): https://www.pastefs.com/pid/157768

**Comment by medariox** [comment]
The problem is that the torrent doesn't have a category in Jackett. The built in AB provider is probably broken, we don't have access to the site to verify if it's still working correctly.

**Comment by BlayZin** [comment]
But it has in the Jackett search result I see episode 4 with category TV/Anime

**Comment by BlayZin** [comment]
I looked a little through the logs and found those:
<details>
SEARCHQUEUE-BACKLOG-289882 :: [AnimeBytesJackett] :: [74c3f12] Error during parsing of release name: [HorribleSubs].Danmachi.S2.04.[Web][MKV][h264][1080p][AAC.2.0], with error: Discarding result. Multi-season detected for '[HorribleSubs].Danmachi.S2.04.[Web][MKV][h264][1080p][AAC.2.0]': MatchesDict([('release_group', u'HorribleSubs'), ('title', u'Danmachi'), ('season', [2, 4]), ('source', u'Web'), ('container', u'mkv'), ('video_codec', u'H.264'), ('screen_size', u'1080p'), ('audio_codec', u'AAC'), ('audio_channels', u'2.0'), ('type', u'episode'), (u'parsing_time', 0.029942989349365234)])
</details>
and
<details>
SEARCHQUEUE-MANUAL-289882 :: [AnimeBytesJackett] :: [74c3f12] We aren't interested in this result: [HorribleSubs].Danmachi.S2.04.[Web][MKV][h264][1080p][AAC.2.0] with url: http://localhost:9117/jackett/dl/animebytes/?jackett_apikey=**********&path=Q2ZESjhMXy1sOWtKT3R4T2ttY0VpbE9SUU1tRlEzSDByeTFNMkxxd1k3czdhQ2QzdzY0VUV1ZXpSTmFMV0xvanRXUWxkRWdJamNvMXM4MkdJU3N4RzRoQjkwOFZEQVVIMm1IcnhTWFlHYi1WZGdFcHBQbWkxYmp3XzJsQkM2S2E3S1BiM2N0Z3dHRFBYV1dDZU9wMVpRY2txUzU3QzdFR2hpVXFfdTJwWjNKUE5fZFhSRjRlSnNRcmdtRTdIRVlmd05ReTVyOXp6ejZScmNMNDVoUmJaMGxWYWlB&file=%5BHorribleSubs%5D+Danmachi+S2+04+%5BWeb%5D%5BMKV%5D%5Bh264%5D%5B1080p%5D%5BAAC+2.0%5D
</details>
or with indexer name:
<details>
SEARCHQUEUE-MANUAL-289882 :: [AnimeBytesJackett] :: [74c3f12] We aren't interested in this result: [HorribleSubs].Is.It.Wrong.to.Try.to.Pick.Up.Girls.in.a.Dungeon?.II.04.[Web][MKV][h264][1080p][AAC.2.0] with url: http://localhost:9117/jackett/dl/animebytes/?jackett_apikey=**********&path=Q2ZESjhMXy1sOWtKT3R4T2ttY0VpbE9SUU1tZUVqQVdzaG5yQ3pBOXJkWS1fWnY4bHdWMVc2UF90T2kzeDdGWDBUYnNoeXpsU0xhT0JOTFFyR2NkYWFpNjQ5Snd1YUlIblhZMi1aOHQ3eE5OaE5TeDhJdVd5U1ZlY2U0aFRROU1zUHBPZkF0SFRsQi1OMGZkY2VQd3prcUNhV1hSaWlOUjJyc09LaHFSbnluMzQtWmxyZUtKcXliRFVwaUR5WEdFVXdvdERiX0dGamRkRVVuM2tiSTZtM1VnVmtv&file=%5BHorribleSubs%5D+Is+It+Wrong+to+Try+to+Pick+Up+Girls+in+a+Dungeon%3F+II+04+%5BWeb%5D%5BMKV%5D%5Bh264%5D%5B1080p%5D%5BAAC+2.0%5D
SEARCHQUEUE-MANUAL-289882 :: [AnimeBytesJackett] :: [74c3f12] Error during parsing of release name: [HorribleSubs].Is.It.Wrong.to.Try.to.Pick.Up.Girls.in.a.Dungeon?.II.04.[Web][MKV][h264][1080p][AAC.2.0], with error: Unable to match [HorribleSubs].Is.It.Wrong.to.Try.to.Pick.Up.Girls.in.a.Dungeon?.II.04.[Web][MKV][h264][1080p][AAC.2.0] to a series in your database. Parser result: release_group: HorribleSubs, title: Is It Wrong to Try to Pick Up Girls in a Dungeon? II, episode: [], absolute_episode: [4], source: Web, container: mkv, video_codec: H.264, screen_size: 1080p, audio_codec: AAC, audio_channels: 2.0, type: episode, parsing_time: 0.0270080566406, total_time: 0.0274579524994, quality: 1080p WEB-DL, season: None
</details>

idk why medusa doesn't grab those even tho I set danmachi as scene exception.

**Comment by p0psicles** [comment]
The jacket result is detected by guessit as a multiseason result. So thats argueably an guessit issue.

Second one could be fixed if you could add `Is.It.Wrong.to.Try.to.Pick.Up.Girls.in.a.Dungeon?.II` as a `season` scene exception. But you can't add that in Medusa. Youl have to add to thexem.de.

http://thexem.de/xem/show/2000
@zoggy

**Comment by medariox** [comment]
It has been added and it should work now. In the future you can also add it to https://github.com/pymedusa/medusa.github.io/blob/master/scene_exceptions/scene_exceptions_tvdb.json
