### ISSUE TITLE
Manual scene numbering set but stills searching index

### ISSUE THREAD

**Issue by homegreewn** [pymedusa/Medusa#7051]
Manual scene numbering is set for a season of Impractical Jokers because a Episode Special screwed up the index. However when searching, Medusa still searches by index episode. More specifically:

S08E11 is the correct episode (added manually to scene as 8x11) and it shows in the Scene Column as manually added 8x11

S08E10 is the episode medusa is looking for in the logs, but of course it doesn't find it.

Any help is greatly appreciated.

**Comment by medariox** [comment]
Scene numbering means you want to use the numbering from XEM. Disable scene numbering and it will use your custom numbering.

**Comment by homegreewn** [comment]
@medariox if I disable it, when I change the number and click elswere it reverts back to the incorrect one. Any ideas?
