### ISSUE TITLE
[APP SUBMITTED]: AniDBPacketCorruptedError: Either decrypting, decompressing or parsing the packet failed

### ISSUE THREAD

**Issue by keese1295** [pymedusa/Medusa#7055]
### INFO
**Python Version**: `2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.19.0-0.bpo.4-amd64-x86_64-with-debian-9.9`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-08-14 02:28:16 ERROR    Thread-1522 :: [74c3f12] Avoiding flood by paranoidly panicing: Aborting link thread, killing connection, releasing waiters and quiting
Traceback (most recent call last):
  File "/home7/**********/.apps/medusa/medusa/ext/adba/aniDBlink.py", line 122, in run
    raise AniDBPacketCorruptedError("Either decrypting, decompressing or parsing the packet failed")
AniDBPacketCorruptedError: Either decrypting, decompressing or parsing the packet failed
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
You have been rate limited by AniDB.
