### ISSUE TITLE
Medusa cannot find episode

### ISSUE THREAD

**Issue by Starli0n** [pymedusa/Medusa#7057]
Hi,

I do not manage in configuring Medusa so that it downloads episode(s) of an anime.

When I search with Jackett:
**Query**: _Demon Slayer Kimetsu No Yaiba E04_
**Result**: _Demon Slayer Kimetsu No Yaiba E04 WEB x264-​URANiME_

But when I search with Medusa, it tries with this pattern (I saw it from the log)
_Demon Slayer Kimetsu No Yaiba 04_
but it missing the **E**
therefore I have no result

Indeed with Jackett, I have no result if I enter _Demon Slayer Kimetsu No Yaiba 04_ without the _E_.

Of course, I tried to add a scene exception like
_Demon Slayer Kimetsu No Yaiba E_
but Medusa add a space for the search
_Demon Slayer Kimetsu No Yaiba E 04_
which gives not result.

Is it possible to configure Medusa to search for a specific template ?
like _Demon Slayer Kimetsu No Yaiba Exx_

(or even better with a regex ?)

**Comment by p0psicles** [comment]
There has been a branch where this was in the works. But other changes have higher prio.
With provider are you using? Like nyaa, shanaproject and anidex work perfectly fine for this show.

**Comment by medariox** [comment]
I'm not sure Medusa is the problem here if `Demon Slayer Kimetsu No Yaiba 04` doesn't yield results because the E is missing. This is an extremely bad search engine that should be fixed by the provider. Anyway, searching as non-anime should search with the E.

**Comment by Starli0n** [comment]
I am using this following provide:
_KickAssTorrent (kat.li)_

Indeed, the search engine will search with the E for a non-anime but also with a S like
_Demon Slayer Kimetsu No Yaiba S01E04_
which yield no result as the naming does not have the season

I might try the provider you mentioned

**Comment by medariox** [comment]
Nyaa and Anidex are both pretty good and also inbuilt so you don't need to use Jackett.
