### ISSUE TITLE
Medusa seems to not retrieve all the categories of the provider

### ISSUE THREAD

**Issue by Starli0n** [pymedusa/Medusa#7058]
Hi,

I am using _KickAssTorrent (kat.li)_ as a provider and I tried to perform a search on _Saint Seiya - Saintia Shou_ which belongs to category **OTHER (7000)**.

But when I registered this provider, I do not see this category.
As a consequence, the result is always empty.

Is it normal ?

**Comment by medariox** [comment]
Yes, we only show categories related to TV. This is a provider issue and we can't fix it from our side. Honestly, kat.li is just a generic KAT clone, it has no special content. I suggest you just use one of the many better alternatives out there.

**Comment by Starli0n** [comment]
Ok noted, I will switch of provider
Actually, I am still a newbie on the topic

What do you suggest for anime, tv-show and eventually movies ?

**Comment by p0psicles** [comment]
For anime nyaa.si. maybe add shanaproject. That should get the most popular. If your really diehard. You could try getting into animebytes.

**Comment by Starli0n** [comment]
Thank you very much, it works much better with nyaa.si

I do not find shanaproject with Jackett and animebytes is private

**Comment by p0psicles** [comment]
Shanaproject is a native provider. I do not recommend using jacket of the provider is available in Medusa.
