### ISSUE TITLE
Quality file size for searching

### ISSUE THREAD

**Issue by coop73** [pymedusa/Medusa#7064]
Is there a way to change to the minimum and maximum file sizes for searching in a specific quality.
Example: I want to set 720p to search for files between 500MB and 1500MB.

**Comment by medariox** [comment]
It's not possible.

**Comment by coop73** [comment]
Is there a way to add that in future release?

**Comment by coop73** [comment]
Like This

**Comment by coop73** [comment]
Like is used in CouchPotato.
