### ISSUE TITLE
Right side of episode display cut off under certain conditions

### ISSUE THREAD

**Issue by Yellow1144** [pymedusa/Medusa#7084]
In episode lists where the episodes have long titles the right side of the display gets cut off along with the search buttons. 

See attached image
![Medusa Display Problem](https://user-images.githubusercontent.com/4110987/63612292-8ac4b880-c5a3-11e9-9e0b-60a87014521b.jpg)

Branch: develop 
Commit: cd6616a73fa5d6bc5caf48e39b485e2f330b2bcf 
Version: 0.3.4 
Database: 44.14
Python Version: | 3.7.4 (default, Jul 9 2019, 03:52:42) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.15.0-55-generic-x86_64-with-LinuxMint-18.3-sylvia

**Comment by medariox** [comment]
Possibly fixed.
