### ISSUE TITLE
need medusa to installed in brutesploit in termux platform

### ISSUE THREAD

**Issue by ReckonCrusat** [pymedusa/Medusa#7086]
As i am noob in this field,plz suggest me steps to install medusa inside directory of brutesploit after i clone it from github....
![photo_2019-08-25_21-15-36](https://user-images.githubusercontent.com/50946084/63652412-8fdd5f80-c77d-11e9-942d-1237af281d93.jpg)

**Comment by medariox** [comment]
This is not the Medusa you are looking for.

**Comment by ReckonCrusat** [comment]
It's asking for Medusa only dude,how can u say what I am looking for,that's
what the error say "need Medusa to be installed to make it work".
Plz suggest any code for it

**Comment by p0psicles** [comment]
https://github.com/Screetsec/BruteSploit/issues/5

**Comment by edwin-dua** [comment]
I can't install Medusa

**Comment by p0psicles** [comment]
You also want to manage your tvshow library with Medusa?

**Comment by Phone-Metal** [comment]
Since The Google Search Leads To This Page

![Screenshot_20210129_214921](https://user-images.githubusercontent.com/74254069/106296477-ed7fb080-627b-11eb-855d-48828110e8a6.jpg)

If Anyone Wants To Install Medusa For Brute forcing :
```
git clone https://github.com/jmk-foofus/medusa
cd medusa 
./configure
make && make install
```
P.s Just Use Thc-hydra instead :)

**Comment by mirx99** [comment]
Love it

**Comment by Gost6663** [comment]
Termux use madusa
