### ISSUE TITLE
Synology &  Locale:Unknown.Unknown

### ISSUE THREAD

**Issue by Jamyz** [pymedusa/Medusa#7088]
Can't change Locale

 - OS: [Linux-3.10.105-x86_64-with-glibc2.2.5]
 - Branch: [master]
 - Commit: [74c3f124fb599ad923e23f46fc320778b8b4217c ]
 - Python version: [2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]]
 - Database version: [44.14]

How i do on an Synology to change Locale : Unknown.Unknown to UFT-8 ?
Thanks

**Comment by medariox** [comment]
See https://www.chainsawonatireswing.com/2012/01/08/set-up-the-synology-diskstation-ds411j-to-support-utf-8/ or ask on the Synology support forums or use Google. We can't provide support for a third party OS.
