### ISSUE TITLE
Medusa Package with python3

### ISSUE THREAD

**Issue by Jamyz** [pymedusa/Medusa#7089]
You can try [here](https://mega.nz/#!XxYC3Ybb!cdKtWua9x51afjJDeUt1cHKzvy0FH3vlPIGTogk_nSI) Medusa package with python3.
Thans to @alexey-pimenov

**Comment by medariox** [comment]
We appreciate the efforts, but we can't allow sharing unofficial packages here. Please share it on reddit.com/r/pymedusa instead.
