### ISSUE TITLE
[TVDB] Year not being added to tvshows.nfo

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#7100]
**Describe the bug**
Not technically a medusa bug as it's TVDB having an issue with "First Aired" and "Year".

**To Reproduce**
Add a new show like "The Boys" from thetvdb scraper.

**Expected behavior**
It will not save <year>2019</year> in tvshows.nfo file from medusa, even tho medusa has the year scraped and saved and displayed in the show displaypage.

**Wanted behavior**
Fallback to something else to make sure <year> tag in tvshows.nfo is saved as long as medusa has the data even though thetvdb does not.

**Comment by Fietspomp86** [comment]
Yes this would be nice. Now when I've added the boys for example, Kodi shows show is from 1969... Only fix is to scan again and ignore local file.

**Comment by papampi** [comment]
+1
I always have to refresh new shows and ignore local in kodi to get the correct show date and not show it as 1969
