### ISSUE TITLE
Custom numbering search reverts back

### ISSUE THREAD

**Issue by homegreewn** [pymedusa/Medusa#7105]
I have this exact same issue, which was resolved apparently but for me it is still broken. Any advice is greatly appreciated. 

https://github.com/pymedusa/Medusa/issues/1451

When I add custom numbering it reverts back, and in the logs it is indeed searching for original numbering and not custom.

**Comment by medariox** [comment]
Are you sure you are not using scene numbering? That setting overwrites your custom numbering.

**Comment by homegreewn** [comment]
Yes
![image](https://user-images.githubusercontent.com/11887610/64117730-8d6d9d80-cd5b-11e9-88f5-6e677aa06417.png)

Unless there is a global scene numbering setting for ALL shows that I am unaware of.

**Comment by medariox** [comment]
When does it reset exactly? Does it reset in the UI?

**Comment by homegreewn** [comment]
Yes. After changing number as soon as I click elsewhere it reverts to original.

**Comment by medariox** [comment]
What you need to do is:
1. Enable Scene Numbering
2. Set the numbering (set it again if it is already set)

That should make it work correctly. This will be improved with: https://github.com/pymedusa/Medusa/pull/7106

**Comment by homegreewn** [comment]
Doesn't work either, I'll wait it out until #7106 and post then if it got fixed for me. Thank you.
