### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Apple TV+

### ISSUE THREAD

**Issue by pokyto** [pymedusa/Medusa#7130]
### INFO
**Python Version**: `2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-09-12 16:06:49 ERROR    Thread_15 :: [918cfe7] Missing time zone for network: Apple TV+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added
