### ISSUE TITLE
Can't update providers at all

### ISSUE THREAD

**Issue by horzadome** [pymedusa/Medusa#7135]
In UI, when trying to change provider order or add custom provider or do anything in the "search providers" tab, I get an error (in chrome console) saying"

```An invalid form control with name='provider_ratio' is not focusable.```
Note: provider_ratio from the log line is whichever provider is the first in the list at the moment of save. i.e. 'rarbg_ratio', 'limetorrents_ratio' ...

**To Reproduce**
1. Go to Search Providers -> Provider Priorities
1. Change provider order
1. Click any of the 2 "Save Changes" buttons
1. Notice that there's no "saved" popup and that there are js errors
1. Refreshing the page, we get the old provider order

**Expected behavior**
When saving changes, provider order should be saved

**Medusa:**
 - OS: ubuntu 18.04 x64
 - Branch: tried both master and develop
 - Commit: baad1e5af59d7f29606c1fed1c110af1424bb117
 - Python version: 3.6.8
 - Database version: ???

**Debug logs (at least 50 lines):**
Tere's nothing in server logs, appears to be UI error only
```
An invalid form control with name='provider_ratio' is not focusable.
```
</details>

**Additional context**
Reproduced in:
Chrome, Firefox, Brave, Vivaldi
both master and develop branch
both with and without reverse proxy in-between

**Comment by medariox** [comment]
Can't reproduce, works just fine here. What's your Chrome version? Is this a fresh install?

**Comment by p0psicles** [comment]
Probably has something to do with one of your configured providers. Did you add any custom?

**Comment by horzadome** [comment]
brave is at Version 0.72.13 Chromium: 77.0.3865.65 (Official Build) unknown (64-bit)
chrome is at Version 77.0.3865.75 (Official Build) (64-bit)
vivaldi at 2.7.1628.33 (Stable channel) (64-bit)
firefox at 69.0 (64-bit)

Installation of Medusa is fresh, though my main.db and config.ini have gone through years of Rage and Chill before finding their place in medusa.
I didn't add any custom providers.

**Comment by horzadome** [comment]
I just deleted all providers from my config.ini, restarted medusa and it works now :-/
It also nicely filled my config with providers.
Sorry for the false alarm.
