### ISSUE TITLE
latest docker image does not take the PUID/PGID parameter

### ISSUE THREAD

**Issue by hoefs** [pymedusa/Medusa#7136]
**Describe the bug**
latest docker build is creating folders as root/root and not als the desired PUID/PGID as before

**To Reproduce**
Steps to reproduce the behavior: Add new show and let it create folder

![Screenshot 2019-09-13 at 17 29 32](https://user-images.githubusercontent.com/7440522/64874834-20f07980-d64c-11e9-9d36-2454e0b924b6.png)

**Expected behavior**
it should create with PUID/PGID as configured in docker (should be admin/administrators but creates folder as root/root)

**Medusa (please complete the following information):**

- Branch: masterCommit: baad1e5af59d7f29606c1fed1c110af1424bb117
- Version: 0.3.5
- Database: 44.14
- Python Version: | 3.7.4 (default, Jul 13 2019, 14:44:04) [GCC 8.3.0]
- SSL Version: | OpenSSL 1.1.1b 26 Feb 2019
- OS: | Linux-3.10.105-x86_64-with
- Locale: | en_US.UTF-8

=> docker on synology

docker config:
![Screenshot 2019-09-13 at 17 29 06](https://user-images.githubusercontent.com/7440522/64874877-306fc280-d64c-11e9-89c0-cbdc17be7807.png)

**Comment by medariox** [comment]
We don't use the LinuxServer image anymore, but it's available as a separate docker image. 

Docker has that functionality built in since a long time. See https://docs.docker.com/engine/reference/run/#user

You can simply run the container with `-u 1024:100`.

**Comment by hoefs** [comment]
> We don't use the LinuxServer image anymore, but it's available as a separate docker image.
> 
> Docker has that functionality built in since a long time. See https://docs.docker.com/engine/reference/run/#user
> 
> You can simply run the container with `-u 1024:100`.

I am using the correct docker package:
![image](https://user-images.githubusercontent.com/7440522/64954407-c5113500-d885-11e9-9492-7c33675163c9.png)

In version 3.4 the PUID and PGID parameter did still work. After updating to 3.5 is stopped...

**Comment by p0psicles** [comment]
Maybe something Todo with the py3 switch?

**Comment by medariox** [comment]
The official image doesn't use PUID/PGID anymore!

You can use [this image instead](https://hub.docker.com/r/linuxserver/medusa/) if you can't run the container with the [(recommended)  `--user` option](https://docs.docker.com/engine/reference/run/#user).

**Comment by aightgenosse** [comment]
@hoefs were you to able to resolve the issue? I have the exact same baseline and problems. Any input would be greatly appreciated. 😁

**Comment by hoefs** [comment]
> @hoefs were you to able to resolve the issue? I have the exact same baseline and problems. Any input would be greatly appreciated. 😁

I switched to https://registry.hub.docker.com/r/linuxserver/medusa

They support easy user mappings (PGID, PUID) and everything works fine.

**Comment by aightgenosse** [comment]
Thank you for the quick reply! 😊 I was afraid that this would be the solution. How did you migrate the configuration? Exporting/importing the settings, or were you able to point the docker container to the same directories?

**Comment by hoefs** [comment]
> Thank you for the quick reply! 😊 I was afraid that this would be the solution. How did you migrate the configuration? Exporting/importing the settings, or were you able to point the docker container to the same directories?

indeed! linuxserver\medusa needs the same /config folder. Just download the new container, shut the old medusa, configure the new one with the correct pgid/puid and mappings (/config,/tv...). All should run fine

**Comment by aightgenosse** [comment]
Excellent, thanks again! 👍

**Comment by aightgenosse** [comment]
I can confirm that by switching to the https://registry.hub.docker.com/r/linuxserver/medusa image I've been able to resolve the issue. Migration has been fast and simple. 

@medariox: what has been the reason to disable support for PGID, PUID in your image? It seems to break compatibility with the Docker implementation running on Synology NAS. Or at least I've been unable to find out how to pass the --u:"pgid:puid" parameter via the web-interface.

**Comment by medariox** [comment]
@aightgenosse 
Our image never supported it AFAIK and we don't intend to support custom parameters, especially since there is an equally good image available.
