### ISSUE TITLE
How to eliminate "no upstream configured" warnings?

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#7160]
Hi,
V 0.3.5

How can I get rid of these constant warnings? -

2019-09-14 10:44:51 WARNING	CHECKVERSION :: [74c3f12] git rev-list --left-right "@{upstream}"...HEAD returned : fatal: no upstream configured for branch 'master'
2019-09-14 10:44:51 WARNING	CHECKVERSION :: [74c3f12] git rev-parse --verify --quiet "@{upstream}" returned : fatal: no upstream configured for branch 'master'
2019-09-14 10:44:47 INFO	CHECKVERSION :: [74c3f12] Checking for updates using GitHub Updater

Can it be related to this?: 
https://stackoverflow.com/questions/23401652/fatal-the-current-branch-master-has-no-upstream-branch

**Comment by medariox** [comment]
`git branch --set-upstream-to origin master`

**Comment by rafi-d** [comment]
D:\Program Files\Medusa\Medusa>git branch --set-upstream-to origin master
error: the requested upstream branch 'origin' does not exist
hint:
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint:
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.

D:\Program Files\Medusa\Medusa>

**Comment by medariox** [comment]
hint: run "git fetch" to retrieve it.

**Comment by rafi-d** [comment]
OK, looks like  this have fix the warnings:

git remote remove origin
git remote add origin https://github.com/pymedusa/Medusa.git

Maybe medusa should do that by itself if this type of error shows up?

**Comment by medariox** [comment]
Why? It's not like it normally happens. If you mess with git it can happen. Normal users are not supposed to do that.

**Comment by rafi-d** [comment]
Sorry. my mistake. warnings are still there :(

**Comment by medariox** [comment]
How is it set in your config.ini?

**Comment by rafi-d** [comment]
Already "fixed" it by resetting ( git reset --hard origin/master) 

config:
git_auth_type = 0
git_username = ""
git_password = ""
git_token = ""
git_reset = 1
git_reset_branches = develop, master
branch = master
git_remote = origin
git_remote_url = https://github.com/pymedusa/Medusa
