### ISSUE TITLE
Medusa will not start

### ISSUE THREAD

**Issue by EzraBlint** [pymedusa/Medusa#7169]
**Describe the bug**
Seems like whenever I try to start the service for Medusa (be it Master or Develop branch) the service just keeps restarting then fails

**To Reproduce**
use https://github.com/pymedusa/Medusa/blob/master/runscripts/init.systemd
clone either master or develop branch and start service

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Linux 3.10.0-957.27.2.el7.x86_64 CentOS Linux 7 (Core)
 - Branch: Either Master or Develop
 - Commit: baad1e5 or f20e140
 - Python version: Python 2.7.5
 - Database version: unknown

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
Sep 17 07:56:04 har-cent-03 python2.7[16066]: Traceback (most recent call last):
Sep 17 07:56:04 har-cent-03 python2.7[16066]: File "/apps/medusa/start.py", line 6, in <module>
Sep 17 07:56:04 har-cent-03 python2.7[16066]: from medusa.__main__ import main
Sep 17 07:56:04 har-cent-03 python2.7[16066]: File "/apps/medusa/medusa/__init__.py", line 24, in <module>
Sep 17 07:56:04 har-cent-03 python2.7[16066]: initialize()
Sep 17 07:56:04 har-cent-03 python2.7[16066]: File "/apps/medusa/medusa/init/__init__.py", line 37, in initialize
Sep 17 07:56:04 har-cent-03 python2.7[16066]: _monkey_patch_cfscrape()
Sep 17 07:56:04 har-cent-03 python2.7[16066]: File "/apps/medusa/medusa/init/__init__.py", line 184, in _monkey_patch_cfscrape
Sep 17 07:56:04 har-cent-03 python2.7[16066]: from medusa.init.cfscrape import patch_cfscrape
Sep 17 07:56:04 har-cent-03 python2.7[16066]: File "/apps/medusa/medusa/init/cfscrape.py", line 11, in <module>
Sep 17 07:56:04 har-cent-03 python2.7[16066]: import js2py
Sep 17 07:56:04 har-cent-03 python2.7[16066]: File "/apps/medusa/ext/js2py/__init__.py", line 73, in <module>
Sep 17 07:56:04 har-cent-03 python2.7[16066]: from .evaljs import *
Sep 17 07:56:04 har-cent-03 python2.7[16066]: File "/apps/medusa/ext/js2py/evaljs.py", line 155
Sep 17 07:56:04 har-cent-03 python2.7[16066]: exec (DEFAULT_HEADER, self._context)
Sep 17 07:56:04 har-cent-03 python2.7[16066]: SyntaxError: unqualified exec is not allowed in function '__init__' it contains a nested function with free variable
Sep 17 07:56:04 har-cent-03 systemd[1]: medusa.service: main process exited, code=exited, status=1/FAILURE
Sep 17 07:56:04 har-cent-03 systemd[1]: Unit medusa.service entered failed state.
Sep 17 07:56:04 har-cent-03 systemd[1]: medusa.service failed.

```
</details>

**Additional context**
I have ensured SELinux is not enforced and have ensured permissions and ownership are correct, infact when using Release 0.3.4 (74c3f12) Medusa seems to start up without issue i just cant seem to get in started on the latest release

**Comment by medariox** [comment]
Python 2.7.5 is not supported. Python > 2.7.10 is required. Also Python 2.7 support will be discontinued on the 01/01/2020.
