### ISSUE TITLE
Firefox Graphics (Homepage/Show lists)

### ISSUE THREAD

**Issue by EzraBlint** [pymedusa/Medusa#7170]
Unsure if this is a bug, general issue or feature request however:

When using medusa with firefox the columns do not have the sorting arrows, the downloads column does not have anything at all and when enabling tabs for anime and tv shows it does not seem to format properly and hide each shows behind the corresponding tab.

Firefox example
https://i.imgur.com/TrwvL0c.png

Firefox example on not separating TV and anime shows
https://i.imgur.com/wrQSkWY.png

chrome example (working example)
https://i.imgur.com/I4Ap1Yr.png

If it helps I am using the following:
Branch: master
Commit: baad1e5af59d7f29606c1fed1c110af1424bb117
Version: Unknown
Database: 44.14
Python: | 3.6.3 (default, May 31 2019, 13:05:43)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
OS: | Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-centos-7.6-Core
Firefox: 69.0 (64-bit)

I have tried rebuilding Medusa from fresh and the issue is still present which is why I think this is more something with how medusa is handled with Firefox as opposed to my specific Firefox browser (have tried with Firefox without any extensions [fresh install])

**Comment by p0psicles** [comment]
Ok. Well these pages are candidate to be transitioned to Vue components. I'll try to remember to test on ff when I get to it.

**Comment by EzraBlint** [comment]
oh awesome, thanks!, if you need me for testing or anything feel free to let me know

**Comment by EzraBlint** [comment]
Issue has been fixed, thankyou.
