### ISSUE TITLE
Option To Keep Show List Sort Order Default Alphabetical.  

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/Medusa#7184]
I'm always frustrated when...  I open Show List and see a non-alphabetical sort, by default.  Default by size seems very counter-intuitive, imho.  What is the rational for that?  It's also bit frustrating when the first click on the Show column header results in a reverse alphabetical sort.  

**Describe the solution you'd like**
I would at least like to have the option to define the default sort order.

**Describe alternatives you've considered**
I considered of jumping from the roof, but thought better of it.

**Additional context**
None, except kudos to the team for a great piece of software.

**Comment by medariox** [comment]
You can click on the Show column and it will sort by show name, the setting will stick. I'm not sure I understand the problem?

**Comment by DrakeJones** [comment]
I must have had a gremlin.  I reinstalled and it's sorting and sticking on restart.  Thanks.
