### ISSUE TITLE
Show list reverting to sort by size.

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/Medusa#7187]
This is driving me nuts! I can't be the only one!  The Show list sort order mysteriously reverts to sort by show folder size.

**To Reproduce**
All I have to do to reproduce the error is sort shows alphabetically, come back in later and shows are sorted by folder size.

**Expected behavior**
Sticky sort alphabetically.

**Comment by medariox** [comment]
Do you delete your browser cookies?

**Comment by DrakeJones** [comment]
Not for local server stuff like Medusa, SabNZBD, etc.

**Comment by medariox** [comment]
Actually the setting is saved in local storage, so make sure you don't delete that.

**Comment by DrakeJones** [comment]
No local data for Medusa 192.168.2.24, but some external websites do have local data stored.  I'll try to see why FF isn''t keeping data for local network addresses.  Could be one of my cookie/script managers.  Any other ideas?  Also, why is the default sort order size?  Or is that not the default sort order?  Lastly, can I put a line into my config.ini to force an alphabetical sort in Show List?

**Comment by medariox** [comment]
> Could be one of my cookie/script managers.

It's possible.

> Also, why is the default sort order size?

Because some people like it that way.

> Lastly, can I put a line into my config.ini to force an alphabetical sort in Show List?

No, that's not possible.

You should have something like this in your local storage (tablesorter-savesort):
![savesort](https://snapr.pw/i/7b24e53bfc.png)

**Comment by DrakeJones** [comment]
Pre-sort - Sorts by size
![image](https://user-images.githubusercontent.com/6259352/65832732-1c70c580-e2c8-11e9-8005-92f7affdc9ce.png)

Post-sort - Manual alphabetical sort
![image](https://user-images.githubusercontent.com/6259352/65832748-635ebb00-e2c8-11e9-8751-8af160a2c806.png)

Close window and reopen Medusa - Sorts by size again
![image](https://user-images.githubusercontent.com/6259352/65832888-7ecac580-e2ca-11e9-89cc-3dd44140ceb8.png)

Local storage is enabled for this site.  Strange.

And you prefer to sort your directories by size rather than alphabetically?  Interesting...

**Comment by medariox** [comment]
> And you prefer to sort your directories by size rather than alphabetically? Interesting...

It's not about what I prefer, I don't even use the list view. It's about what most people seem to like the most. At this point it seems obvious that the problem is on your side somewhere.

**Comment by DrakeJones** [comment]
Fair enough.  Thank you for your time.
