### ISSUE TITLE
Twitter auth token not saved

### ISSUE THREAD

**Issue by UNiXMIT** [pymedusa/Medusa#7196]
When trying to enable Twitter in the notification section I can get to the step that requests my auth token and I enter it into the entry field. I then test the notification and it works. I click save and refresh the page and it;s gone and the notification no longer works.

**To Reproduce**
Enable Twitter notifications and enter your auth key from Twitter.
Test the connection and it works.
Click save then refresh the page.
The auth key is not saved.

**Expected behavior**
I expteced the key to be saved.

**Medusa (please complete the following information):**
 - OS: DietPi
 - Branch: master
 - Commit: baad1e5af59d7f29606c1fed1c110af1424bb117
 - Python version: 	2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
 - Database version: 44.14

2019-09-30 22:29:21 ERROR	Thread-2 :: [baad1e5] Exception generated: {'message': 'Missing oAuth Consumer Key or Access Token'}

**Comment by p0psicles** [comment]
Should be fixed with #7194, although I couldn't verify it. Couldn't get it set up.
But as far as the requests go, everything should work now, python2 and 3.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7194
