### ISSUE TITLE
Episodes for paused shows being set to wanted

### ISSUE THREAD

**Issue by Yellow1144** [pymedusa/Medusa#7201]
I have a handful of shows in my database I have set to paused as I only want a few that air. 

I just noticed that sometime in the last few months, don't know when, new episodes are being set as wanted rather than Skipped. I have the default episode status set to Skipped.

Branch: develop
Commit: 28b1c7823e970a48ef71b7e5c224a105d095307e
Version: 0.3.4
Database: 44.14
--
Python Version: | 3.7.4 (default, Sep 2 2019, 20:44:09) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.15.0-64-generic-x86_64-with-LinuxMint-18.3-sylvia
Locale: | en_CA.UTF-8

I don't have any log data for this at the moment. I just noticed this

**Comment by medariox** [comment]
As always, we can't do anything without debug logs. Please open again when you have relevant logs.
