### ISSUE TITLE
NGINX Auth block support with Organizr via reverse proxy

### ISSUE THREAD

**Issue by Xenocell12** [pymedusa/Medusa#7204]
Shoutout to @OmgImAlexis ! This may be up your ally to have the skeleton key for the right configuration.

There is one thing @p0psicles and I are trying to figure out. We've been chatting on the Medusa discord on how to get this to work with Organizr. Currently I seem to be the only person trying to get Medusa to work with AUTH blocks in NGINX's reverse proxy using [Organizr](https://github.com/causefx/Organizr). I've run into closed or archived issues in Github with other forks of the sickbeard app that lead to dead ends. Maybe someone has the magic config???

So the issue we have is when trying to add a new or existing show and nothing seems to happen. This occurs when we have auth-0 block in the reverse proxy to take advantage of Organizr's secure login feature.

NGINX throws an error when trying to add a show: 2019/10/03 13:27:27 [error] 10020#1180: 1029 auth request unexpected status: 504 while sending to client, client: wanIP, server: mydomain/,** request: "POST /medusa/addShows/addNewShow HTTP/1.1", host: "mydomain", referrer: "https://mydomain/****/medusa/addShows/newShow/"

When we remove auth from the reverse proxy block all is well. But unfortunately we have Medusa exposed.

When I brought this issue to one of the devs of Organizr they said 

> "Medusa isn't liking the layer of Organizr Authentication being in place."
> 
> "There is either an endpoint/url for Medusa that needs to be additionally reverse proxied, or they need to do something else with the application to accept it.
> Similar to how, with Radarr and Sonarr, if you implement Organizr auth with a reverse proxy, IE: https://domain.com/sonarr, you will need to create another reverse proxy for http://domain.com/sonarr/api that REMOVES the auth.
> Like this:
> 
>     # Sonarr location block
>     location /sonarr/ {
>         auth_request /auth-1;
>         proxy_set_header Host $host;
>         proxy_set_header Accept-Encoding "";
>         proxy_pass http://192.168.1.103:9898/sonarr/;
>         # Sonarr API block
>         location /sonarr/api {
>             auth_request off;
>             proxy_intercept_errors off;
>             proxy_set_header X-Forwarded-Host $server_name;
>             proxy_set_header X-Forwarded-Ssl on;
>             proxy_pass http://192.168.1.103:9898/sonarr/api;
>         }
>     }
> 

Lastly I wanted to show you my current reverse proxy config for NGINX

> location /medusa {
>                 auth_request /auth-0;
>                 proxy_pass http://192.168.1.79:5050;
>                 proxy_set_header Host $host;
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header X-Forwarded-Host $host:443;
>                 proxy_set_header X-Forwarded-Server $host;
>                 proxy_set_header X-Forwarded-Port 443;
>                 proxy_set_header X-Forwarded-Proto $scheme;
> 
> # Websocket
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
> 		proxy_read_timeout 86400;
>  }

Please let me know if you guys have any questions on this. I'm wondering if there's just an API endpoint that needs to be excluded so nothing gets blocked out. I tried to make a basic reverse proxy that excludes /api/ but I'm sure I'm writing it wrong.

Anyway, thanks again for taking a look at this. I have many workarounds right now but this would be a nice feature to unlock. I can also contribute some documentation for Organizr preset reverse proxy configuration files.

Regards,
~XNO

**Comment by OmgImAlexis** [comment]
> This may be up your ally to have the skeleton key for the right configuration.

Confused by this line?

I should be able to get this working next week as I've got this kind of thing working in the past.

**Comment by Xenocell12** [comment]
Oh excellent! So about that first line, it refers to you having one key fix to all the problems with Medusa reverse proxy configurations. 

You helped another user with IIS reverse proxy and I had the exact issue as that person. 

The messy part was- I was piggy backing on Windows Server Essential 2012 R2 premade IIS so that make things more complicated.

I moved to NGINX for the Auth block feature that Organizr uses.

If you happen to find the right configuration would this be appropriate for Medusa wiki or Organizr wiki? Or perhaps both? I'd like to share a good preset with both projects.

I respond pretty quickly to Github emails so let me know if you have any questions any time!

Thanks again for all you help!

**Comment by Xenocell12** [comment]
Hello, any update on this? 👍
