### ISSUE TITLE
[APP SUBMITTED]: InvalidShowException: Unable to match [Erai-raws].Fairy.Gone.2nd.Season.-.01.[720p].mkv to a series in your database. Parser result: release_group: Erai-raws, title: Fairy Gone 2nd Season, episode: [], absolute_episode: [1], screen_size: 720p, container: mkv, mimetype: video/x-matroska, type: episode, parsing_time: 0.031298160553, total_time: 0.032341003418, quality: 720p HDTV, season: None

### ISSUE THREAD

**Issue by VexingHex** [pymedusa/Medusa#7237]
### INFO
**Python Version**: `2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]`
**Operating System**: `Linux-4.15.0-55-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-10-07 05:03:45 ERROR    SEARCHQUEUE-BACKLOG-359645 :: [Nyaa] :: [baad1e5] 359645: Multiple entries found in show: Fairy Gone 
Traceback (most recent call last):
  File "/opt/**********/**********/providers/generic_provider.py", line 339, in find_search_results
    search_result.name)
  File "/opt/**********/**********/name_parser/parser.py", line 390, in parse
    self.assert_supported(result)
  File "/opt/**********/**********/name_parser/parser.py", line 407, in assert_supported
    'Parser result: {result}'.format(result=result))
InvalidShowException: Unable to match [Erai-raws].Fairy.Gone.2nd.Season.-.01.[720p].mkv to a series in your database. Parser result: release_group: Erai-raws, title: Fairy Gone 2nd Season, episode: [], absolute_episode: [1], screen_size: 720p, container: mkv, mimetype: video/x-matroska, type: episode, parsing_time: 0.031298160553, total_time: 0.032341003418, quality: 720p HDTV, season: None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
You have multiple entries for an episode of the show Fairy Gone in your DB. Try a force update of the show. If it doesn't solve the issue, upload your DB to https://send.firefox.com/ and send me the link, I will fix it for you.

**Comment by VexingHex** [comment]
That seems to have resolved it. Thank you, do you know what could have caused that to be duplicated?
