### ISSUE TITLE
Bad formating of ReleaseGroup name while adding a new Anime

### ISSUE THREAD

**Issue by hergonoway** [pymedusa/Medusa#7238]
**Describe the bug**
While adding a new Anime show, every releasegroup added (manually or by selection) in whitelist section seems ok but once created, it results in bad formated releasegroup names in the main show page, which lead to nowhere during episode search.

**To Reproduce**
- While adding a new show, in format setting, chose any release group or manually fill in one
- Once show is created go to the main page of the show
- previously selected or manually filled releasegroup will be in the following format `b'ReleaseGroup'` ; Example Instead of `Horriblesubs` you'll get `b'Horriblesubs'`

If release group is removed/added once the show is created, the problem doesn't occur. It's only happening while adding a new show.

Screenshot : 
![image](https://user-images.githubusercontent.com/8405448/66350121-c1d80900-e95a-11e9-8bb7-15e8b3e3fd32.png)

**Comment by p0psicles** [comment]
Python 2 I presume?

**Comment by hergonoway** [comment]
using linuserver.io docker image (latest)

`root@MedusaV2:/# python3                                                                                              
Python 3.7.4 (default, Oct  2 2019, 14:13:54)                                                                         
[GCC 8.3.0] on linux                                                                                                  
Type "help", "copyright", "credits" or "license" for more information.                                                
>>>   `
