### ISSUE TITLE
I see a "FFmpeg (ffprobe) not found" warning. Can you comment?

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#7239]
Hi,
I am attaching a strange warning I see for the first time (I think). Can you comment? Is there a requirement to install and define ffmpeg location? if so, where to I set it up?

**To Reproduce**
No idea.. see attached log.

**Medusa (please complete the following information):**

Medusa Info: | Branch:                 master                  Commit:                 baad1e5af59d7f29606c1fed1c110af1424bb117                  Version:                 0.3.5                  Database:                 44.14
-- | --
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Windows-10-10.0.17763
Locale: | en_US.cp1255
  |  
  |  
User: | RAFI-PC$
Program Folder: | D:\Program Files\Medusa\Medusa
Config File: | D:\Program Files\Medusa\Data\config.ini
Database File: | D:\Program Files\Medusa\Data\main.db
Cache Folder: | D:\Program Files\Medusa\Data\cache
Log Folder: | D:\Program Files\Medusa\Data\Logs
Arguments: | --nolaunch --port=8081 --datadir=D:\Program Files\Medusa\Data

2019-10-08 14:33:48 WARNING  SHOWQUEUE-ADD :: [baad1e5] 
=========================================================================================
FFmpeg (ffprobe) not found on your system or could not be loaded.
Visit https://ffmpeg.org/download.html to download it.
If you still have problems, please check if the downloaded version matches your system.
To load FFmpeg (ffprobe) from a specific location, please define the location as follow:
  knowit --ffmpeg /usr/local/ffmpeg/bin <video_path>
  knowit --ffmpeg /usr/local/ffmpeg/bin/ffprobe <video_path>
  knowit --ffmpeg "C:\Program Files\FFmpeg" <video_path>
  knowit --ffmpeg C:\Software\ffprobe.exe <video_path>
=========================================================================================

2019-10-08 14:33:48 WARNING  SHOWQUEUE-ADD :: [baad1e5] An error occurred while parsing: E:\Downloads\Bittorrent\Mr. Robot\Mr. Robot - S04E01 - 401 Unauthorized.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
{
    "info": {
        "duration": "1:00:59", 
        "muxing_app": "Lavf58.29.100", 
        "writing_app": "Lavf58.29.100"
    }, 
    "video_tracks": [
        {
            "forced": false, 
            "language": "und", 
            "default": true, 
            "aspect_ratio_type": 0, 
            "enabled": true, 
            "number": 1, 
            "crop": {}, 
            "height": 1080, 
            "width": 1920, 
            "codec_id": "V_MPEG4/ISO/AVC", 
            "stereo_mode": 0, 
            "lacing": false, 
            "type": 1, 
            "interlaced": false
        }
    ], 
    "tags": [
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "MAJOR_BRAND", 
                    "language": "und", 
                    "string": "isom"
                }, 
                {
                    "default": true, 
                    "name": "MINOR_VERSION", 
                    "language": "und", 
                    "string": "512"
                }, 
                {
                    "default": true, 
                    "name": "COMPATIBLE_BRANDS", 
                    "language": "und", 
                    "string": "isomiso2avc1mp41"
                }, 
                {
                    "default": true, 
                    "name": "ENCODER", 
                    "language": "und", 
                    "string": "Lavf58.29.100"
                }
            ], 
            "targets": []
        }, 
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "HANDLER_NAME", 
                    "language": "und", 
                    "string": "VideoHandler"
                }
            ], 
            "targets": [
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 1, 
                    "position": 869, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 1
                }
            ]
        }, 
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "HANDLER_NAME", 
                    "language": "und", 
                    "string": "SoundHandler"
                }
            ], 
            "targets": [
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 2, 
                    "position": 933, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 1
                }
            ]
        }, 
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "BPS", 
                    "language": "eng", 
                    "string": "56"
                }, 
                {
                    "default": true, 
                    "name": "DURATION", 
                    "language": "eng", 
                    "string": "01:00:28.668000000"
                }, 
                {
                    "default": true, 
                    "name": "NUMBER_OF_FRAMES", 
                    "language": "eng", 
                    "string": "835"
                }, 
                {
                    "default": true, 
                    "name": "NUMBER_OF_BYTES", 
                    "language": "eng", 
                    "string": "25671"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_WRITING_APP", 
                    "language": "eng", 
                    "string": "mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_WRITING_DATE_UTC", 
                    "language": "eng", 
                    "string": "2019-10-07 08:03:59"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_TAGS", 
                    "language": "eng", 
                    "string": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
                }
            ], 
            "targets": [
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 3, 
                    "position": 997, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 1
                }
            ]
        }, 
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "BPS", 
                    "language": "eng", 
                    "string": "65"
                }, 
                {
                    "default": true, 
                    "name": "DURATION", 
                    "language": "eng", 
                    "string": "01:00:31.758000000"
                }, 
                {
                    "default": true, 
                    "name": "NUMBER_OF_FRAMES", 
                    "language": "eng", 
                    "string": "1143"
                }, 
                {
                    "default": true, 
                    "name": "NUMBER_OF_BYTES", 
                    "language": "eng", 
                    "string": "29577"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_WRITING_APP", 
                    "language": "eng", 
                    "string": "mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_WRITING_DATE_UTC", 
                    "language": "eng", 
                    "string": "2019-10-07 08:03:59"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_TAGS", 
                    "language": "eng", 
                    "string": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
                }
            ], 
            "targets": [
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 4, 
                    "position": 1438, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 1
                }
            ]
        }, 
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "DURATION", 
                    "language": "und", 
                    "string": "01:00:59.093000000\u0000\u0000"
                }
            ], 
            "targets": [
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 1, 
                    "position": 1880, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 1
                }
            ]
        }, 
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "DURATION", 
                    "language": "und", 
                    "string": "01:00:59.125000000\u0000\u0000"
                }
            ], 
            "targets": [
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 2, 
                    "position": 1948, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 1
                }
            ]
        }, 
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "DURATION", 
                    "language": "und", 
                    "string": "01:00:38.307000000\u0000\u0000"
                }
            ], 
            "targets": [
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 3, 
                    "position": 2016, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 1
                }
            ]
        }, 
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "DURATION", 
                    "language": "und", 
                    "string": "01:00:38.307000000\u0000\u0000"
                }
            ], 
            "targets": [
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 4, 
                    "position": 2084, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 1
                }
            ]
        }
    ], 
    "chapters": [], 
    "audio_tracks": [
        {
            "bit_depth": 32, 
            "forced": false, 
            "language": "und", 
            "default": true, 
            "output_sampling_frequency": 48000.0, 
            "enabled": true, 
            "number": 2, 
            "sampling_frequency": 48000.0, 
            "channels": 6, 
            "codec_id": "A_AAC", 
            "lacing": false, 
            "type": 2
        }
    ], 
    "recurse_seek_head": false, 
    "subtitle_tracks": [
        {
            "forced": false, 
            "language": "eng", 
            "default": false, 
            "enabled": true, 
            "number": 3, 
            "codec_id": "S_TEXT/UTF8", 
            "lacing": false, 
            "type": 17
        }, 
        {
            "forced": false, 
            "name": "SDH", 
            "language": "eng", 
            "default": false, 
            "enabled": true, 
            "number": 4, 
            "codec_id": "S_TEXT/UTF8", 
            "lacing": false, 
            "type": 17
        }
    ]
}
+-------------------------------------------------------+
Traceback (most recent call last):
  File "D:\Program Files\Medusa\Medusa\ext\knowit\api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "D:\Program Files\Medusa\Medusa\ext\knowit\providers\enzyme.py", line 135, in describe
    video_path=video_path, version=enzyme.__version__, data=json.dumps(data))
  File "D:\Program Files\Medusa\Python\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "D:\Program Files\Medusa\Python\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Program Files\Medusa\Python\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "D:\Program Files\Medusa\Python\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.timedelta(0, 3659, 125000) is not JSON serializable

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+

</details>

**Additional context**

**Comment by horacioj** [comment]
Try downloading the ZIP (https://ffmpeg.zeranoe.com/builds/), unzip somewhere, and add the unzipped   \bin to the path (see http://blog.gregzaal.com/how-to-install-ffmpeg-on-windows/)

HTH

**Comment by rafi-d** [comment]
Done. 
I think this should be part of Medusa settings if needed. Maybe even part if the ibstalation. Process.

**Comment by horacioj** [comment]
Actually, I just guess it will work. I found the same problem and googled for solutions. So far, I didn't get the error again.

**Comment by rafi-d** [comment]
What is it exactly used for in Medusa?

**Comment by horacioj** [comment]
This is what I could find https://github.com/pymedusa/Medusa/issues/3724

**Comment by medariox** [comment]
With ffmpeg/mediainfo it is possible to determine the file quality without it being in the file name. It is optional but recommended. If you don't want it, just ignore the warning.
