### ISSUE TITLE
Medusa is tracking but not snatching *special* episodes

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#7252]
Seems like we are showing in the home page special episodes (out of season), but do not  snatch them.

Attaching a good example of Star-Trek so you can test with (they had a couple of episodes in 2019, last was on 11-Oct next is next month.

**Expected behavior**
I expect Medusa to snatch all episodes, so also the specials in this case . Maybe an option to avoid that if the user do not want those. 

It seems like all those are marked with S00Exx , so it should be pretty easy to filter also all S00e* in your searches.  

**Screenshots**
attached

![1](https://user-images.githubusercontent.com/2458280/66696484-1ec61d00-ecd5-11e9-96d5-152b5f6a6610.png)

**Comment by p0psicles** [comment]
This is not possible. That's partly what we introduced manual search for

**Comment by rafi-d** [comment]
Why not? It seems those are being tracked, so all is needed to add this to the search, isn't it?

Also, I did try to search manually, and there is no way to so that since those are NOT listed in the show's page, only in the main page. At lease show them in the show page...

**Comment by p0psicles** [comment]
Not everyone is interested in them. I can say with some confidence more are not.

**Comment by rafi-d** [comment]
Maybe because not everyone is aware/exposed in time ?... Maybe if it was auto-snatched in time, more people would be aware? :)

**Comment by p0psicles** [comment]
Yeah could be added with an option. But then we'll get allot of users complaining that they're special eps are not found. As allot of there releases are far off scene standard. Are you going to respond to those users here and debug they're issues?

**Comment by rafi-d** [comment]
I am that expert to assess how many will / will not be found. 
Also, I expect this option to be disabled by default, so I can assess that only a few will try/test-drive  it at first. Those will not "complain", but will appreciate even partial finds. Learning from their  experience would be best... :) 

So, maybe as a simple first step, just add one new option, and enhance the search to pick those up if possible. GUI can be dealt with later on....  :)

**Comment by p0psicles** [comment]
You do know how to sell it.
@medariox thoughts?

**Comment by rafi-d** [comment]
Just the sound of reason... ;) Make a special branch, and I'll try test it for you... 

And two more points:
A. Unique feature(s) only in medusa will not be bad against the competition... (who, BTW, do have my file size filter, with GUI...)
B. You'll get me off your backs with this regards... ;)

**Comment by rafi-d** [comment]
1) Looking at the search code @ core.py, would't this be the only change needed to get also season 0 (S00) into the wanted list (optionally)? ->

def wanted_episodes(series_obj, from_date):
    """
    Get a list of episodes that we want to download.

    :param series_obj: Series these episodes are from
    :param from_date: Search from a certain date
    :return: list of wanted episodes
    """
    wanted = []
    allowed_qualities, preferred_qualities = series_obj.current_qualities
    all_qualities = list(set(allowed_qualities + preferred_qualities))

    log.debug(u'Seeing if we need anything from {0}', series_obj.name)
    con = db.DBConnection()
# rafi - add seasson 0 
    sql_results = con.select(
        'SELECT status, quality, season, episode, manually_searched '
        'FROM tv_episodes '
        'WHERE indexer = ? '
        ' AND showid = ?'
#        ' AND season > 0'   <------------------------------------------------
        ' AND season >= 0'  <------------------------------------------------
        ' AND airdate > ?',
        [series_obj.indexer, series_obj.series_id, from_date.toordinal()]
    )

2) I have quick tested after manually changing the status of couple of specials to "wanted", and they seem to have "behaved"/been snatched  normally ... I believe the "search" (magnifier glass button) is missing there , tho... 

So, I guess an *optional* one-line change might do the trick... (+ adding the missing search button)

FYI
![1](https://user-images.githubusercontent.com/2458280/66700778-65c80880-ecfd-11e9-8821-f5798e7c9bd9.png)

One note (to myself) would be to ignore the duration/play-time for those when I am calculating minimal file sizes in my own added size-filter-code, since it seems most specials have a very short play time (here 15m instead of 45m) , so files are also relatively small...

**Comment by medariox** [comment]
There is already an easy way to download specials (manual search). This feature request will be like the rest for me, if there are enough user who request it, it will be added without ETA. Otherwise it can stay in the wishlist. I'd like to remind that this is a FOSS project and we don't get a single $ from the work we put in this project **daily**. You can, however, open a PR with this feature. It will be reviewed   at some point and eventually merged if it meets our quality standards.

**Comment by rafi-d** [comment]
Unfortunately, my knowledge in your GUI/DB is very limited, so adding an option is not easy as it is for you.
I can do a PR if you think it can be the default, but I really think optional (global/per show) is better.

Regardless, I've changed my own code (as per the above), see how it goes...

**Comment by rafi-d** [comment]
> 
> Regardless, I've changed my own code (as per the above), see how it goes...

So far so good. Seems to snatch regular episodes as before.

when you decide to go forward, just do a code-wide search for "season > 0", since there are couple of stats related code that might needs tuning as well.  FYI.

**Comment by p0psicles** [comment]
If it's working you can do pr

**Comment by rafi-d** [comment]
For a character/one-line change? Already noted that I am not familiar with the  GUI/DB side for implementing that option we've discussed.

**Comment by Theli93** [comment]
Found this while looking into this particular issue.
I'm giving it my +1 and comment.

I agree that there are some shows that I will take all Specials on (i.e. _Star Trek_, _Mandalorian_, _Doctor Who_, etc.). I'd also add that there are some shows that no longer have regular season episodes, but still produce specials (particularly around the holidays) that, unless I'm paying particular attention, I may miss altogether. For this, shows that come to mind are _Mrs. Brown's Boys_ (they have done this for years now) and _Dreamworks Dragons_ appears to be following the pattern at present.

For **some** shows, it is much easier to delete/ignore unwanted episodes, than try to dig them up once you realize you've missed a critical special.

Thanks for the consideration.

**Comment by medariox** [comment]
Releases for specials are absolutely unreliable. An automated download for those episodes won't be added from us. Especially considering there is manual search available.
