### ISSUE TITLE
poster and show

### ISSUE THREAD

**Issue by bibi32** [pymedusa/Medusa#7262]
Hello, I have a problem with poster in some show in french, could somebody can help me ??

![Capture d’écran_2019-10-17_20-40-19](https://user-images.githubusercontent.com/26071810/67039750-43315780-f122-11e9-84fb-6e1a12ee2a0b.png)
![Capture d’écran_2019-10-17_21-10-37](https://user-images.githubusercontent.com/26071810/67039886-9c00f000-f122-11e9-8aac-8783834f9233.png)

**Comment by p0psicles** [comment]
There coming from thetvdb.com. fix them there

**Comment by bibi32** [comment]
There is not this poster from tvdb.
