### ISSUE TITLE
Home/Show List sorted by Download field misordered/misgrouped

### ISSUE THREAD

**Issue by shawnhicks** [pymedusa/Medusa#7263]
When sorting the show list by "Downloads", the sort order displayed is numerically nonsequential and the color coding status is not grouped together (correct color, wrong position). This normally happens for shows with hundreds of episodes that have one or a few wanted. Examples of shows with high episode counts include NCIS, SNL, SVU. I have not determined the specific count threshold for this condition.

Add a show with hundreds of episodes, populate all but one episode.
Click the "Downloads" field label to select ascending sort.

I expected the sort order and grouping to be maintained consistent with shows with smaller counts of episodes.

The image demonstrates SVU with one episode wanted in the incorrect sort/grouping position. "461/462" (1 wanted) is displayed between 218 (none wanted) and 276 (none wanted); "179/182" (next largest I have w/wanted) is positioned correctly with the same color grouping
![image](https://user-images.githubusercontent.com/26195502/67086533-d2a42e00-f155-11e9-9447-60dd98fd474c.png)

Medusa Info: 
Branch: master
Commit: baad1e5af59d7f29606c1fed1c110af1424bb117
Version: 0.3.5
Database: 44.14
Python Version: 2.7.16 (default, May 23 2019, 05:34:26) [GCC 7.4.0]
Google Chrome: Version 77.0.3865.90 (Official Build) (64-bit)

This issue does not produce error conditions, not including debug logs.

**Comment by p0psicles** [comment]
I will not give this much attention right now. But in a couple of weeks well start maintenance on all the home templates. Will look at it then

**Comment by shawnhicks** [comment]
This has been the behavior for years, probably goes back to sickbeard/sickrage code. I just got annoyed enough to document it.

**Comment by shawnhicks** [comment]
Today's observation:
Family Guy is positioned correctly 331/332
The Simpsons is not 665/666 (following SVU 462, preceding SNL 874)

**Comment by shawnhicks** [comment]
Today's observation:
Bering Sea Gold is positioned correctly 99/100
NCIS is not 382/383 (following Blindspot 89, preceding OITNB 91)

**Comment by p0psicles** [comment]
Reminder #5345

**Comment by shawnhicks** [comment]
Today's observation:
South Park is positioned correctly 301/302
SVU is not 463/464 (following X-Files 218, preceding American Dad! 276)

**Comment by shawnhicks** [comment]
Today's observation:
Cutthroat Kitchen is positioned correctly 179/182
SNL is not 866/867 (following The Simpsons 668, at end of list)

**Comment by p0psicles** [comment]
@shawnhicks would you be willing to test this out in the new home layouts?
