### ISSUE TITLE
Separate post processing directory for Anime?

### ISSUE THREAD

**Issue by LargeTalons** [pymedusa/Medusa#7267]
Hey Guys,

I was wondering if there are any plans to add the ability to have multiple post processing directories? I am using qbittorrent with separate labels for TV and Anime in Medusa, but I would like to keep these download directories separate while still maintaining the ability to post process either directory.

Is this possible?

Thank you for your work on this project, by the way.

**Comment by p0psicles** [comment]
Isn't there an option to run external scripts on download complete?

**Comment by LargeTalons** [comment]
I was wondering if there was a way to do this without having to figure out how to make a script.

Thanks for responding. I'll have to figure something out.

**Comment by p0psicles** [comment]
https://github.com/clinton-hall/nzbToMedia/wiki/qbittorrent

**Comment by medariox** [comment]
Why don't you use subfolders?
e.g. `processing/anime`
and `processing/tv`

**Comment by LargeTalons** [comment]
I did not think of using subfolders! Thanks for the advice.  This solves my problem.

**Comment by Ruffyop** [comment]
> 
> 
> Why don't you use subfolders?
> e.g. `processing/anime`
> and `processing/tv`

i know it is an old post, but can you explain it for me ? i have de Download directory in sab for 1.TV Shows 2.Anime Shows (anime Movies are also seperate, which also have seperate folders for plex). but in medusa i can only pick one Post-Processing Dir. is there any way i can change this ?
