### ISSUE TITLE
New address for xThor tracker

### ISSUE THREAD

**Issue by Tonycalves** [pymedusa/Medusa#7272]
The tracker xThor has a new address (and domain name), and suddenly a new address for the API, It is possible to update it to the next update? Thank you.. :)

**Comment by bourgouinadrien** [comment]
that should do the job `diff --git a/medusa/providers/torrent/json/xthor.py b/medusa/providers/torrent/json/xthor.py
index ef2549569..b1e316136 100644
--- a/medusa/providers/torrent/json/xthor.py
+++ b/medusa/providers/torrent/json/xthor.py
@@ -26,9 +26,9 @@ class XthorProvider(TorrentProvider):
         self.passkey = None

         # URLs
-        self.url = 'https://xthor.to'
+        self.url = 'https://xthor.tk'
         self.urls = {
-            'search': 'https://api.xthor.to',
+            'search': 'https://api.xthor.tk',
         }
`

**Comment by medariox** [comment]
This is an easy change. It will be available with the next release (PRs welcome!).

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7303
Will be available in the next release.
