### ISSUE TITLE
Choose new show folder name from scene exceptions

### ISSUE THREAD

**Issue by trisk** [pymedusa/Medusa#7277]
When adding a new show, I can choose the parent folder location but not the name of the new show folder. This causes problems for anime when the indexer (typically TVDBv2) show name doesn't match the scene name for the show.

I would like to be able to choose from the scene exceptions list for the folder name of the show. We should probably also allow free editing of the folder name.

My current workaround is to create empty show folders by hand and use "add existing shows", but locating them in the folder list is laborious when there are a large number of show folders present.

We should be able to expose an API endpoint for `get_scene_exceptions` or `get_scene_exceptions_by_name` to look up exceptions by indexer ID or name and list them in the UI. It looks like we can already pass a full show path to addNewShow so only the UI has to be updated.

**Comment by p0psicles** [comment]
You say this causes problems? But what's the problem?

**Comment by zorrax2b** [comment]
I have the same problem for Vinland saga
If I create with TVDB2 impossible to create (click on 'add show' but nothing happens. A second click gives you the possibility to create but with the folder direction)
If I create with other TVMAZE or TMDB, everything is ok but it did not recognize as an anime but as a normal serie

**Comment by medariox** [comment]
1. Use TheTVDB for Anime (other indexers don't work with XEM)
2. I just added the show from TVDBv2, it created the show folder `Vinland Saga` as expected

It would be really nice to understand the issue here.
