### ISSUE TITLE
Missing time zone for network: Fullscreen

### ISSUE THREAD

**Issue by moonbuggy** [pymedusa/Medusa#7278]
**Describe the bug**
2019-10-23 21:31:03 ERROR    Thread_0 :: [baad1e5] Missing time zone for network: Fullscreen

**To Reproduce**
1. Add [`The Deleted`](https://www.thetvdb.com/series/the-deleted)
2. View Errors

**Expected behavior**
I'm not sure what criteria are used to determine an appropriate time zone, especially when a 'network' that really just does web series is involved, but with nothing else to go on I'd assume their headquaters being in Los Angeles (according to [the Wiki](https://en.wikipedia.org/wiki/Fullscreen_(company))) would make `America/Los_Angeles` or `US/Pacific` as good a default as any.

**Medusa (please complete the following information):**
 - OS: CentOS 8
 - Branch: master
 - Commit: baad1e5
 - Python version: 3.7.5
 - Database version: 44.14

**Comment by YogSottot** [comment]
>  would make America/Los_Angeles or US/Pacific as good a default as any.

This time zone is already added as [fullscreen:US/Eastern](https://github.com/pymedusa/medusa.github.io/blob/ec9aefad601b6334b9f70cedf292e2f9151f4bb2/sb_network_timezones/network_timezones.txt#L2520), so I added copy as Fullscreen:US/Eastern as well.
