### ISSUE TITLE
Cannot add show

### ISSUE THREAD

**Issue by S3rrrjjj** [pymedusa/Medusa#7290]
Trying to add show: https://www.thetvdb.com/series/tour-de-force
TVID: `371399`

Does not show up in search. 
Tried to add it manually using this command: http://192.168.1.75:8081/api/v2/{Medusa-API-KEY}/?cmd=show.addnew&indexerid=371399&lang=fr

Result JSON: `error | "No authorization token."`

http://192.168.1.75:8081/api/v1/{Medusa-API-KEY}/?cmd=show.addnew&indexerid=371399&lang=fr

Result JSON: 

```
{
    "data": {},
    "message": "Empty results returned, check indexerid and try again",
    "result": "failure"
}

```
With API builder:
Response: 343ms
URL: /api/v1/MEDUSA-API/?cmd=show.addnew&tvdbid=371399&initial=hdtv&location=D:\Shared Videos\TV\Tour de force&season_folders=1&status=skipped&lang=fr&subtitles=0&anime=0&scene=0&future_status=wanted&flatten_folders=0

```
{
    "data": {},
    "message": "Empty results returned, check indexerid and try again",
    "result": "failure"
}

```
Medusa Info:
Branch: master
Commit: baad1e5af59d7f29606c1fed1c110af1424bb117
Version: 0.3.5
Database: 44.14

Python Version: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
SSL Version: OpenSSL 1.1.1c  28 May 2019
OS: Windows-10-10.0.17763-SP0
Locale: en_CA.cp1252

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/wiki/API-v2

or wait for the TVDB API to update.

**Comment by S3rrrjjj** [comment]
Thanks for the help. 

What the usual delay I should expect for the API to update? How come I'm able to add it with Sonarr? I prefer Medusa because unlike Sonarr, it gets episode description in the requested language instead of using only English..

**Comment by p0psicles** [comment]
What's the problem? I can add the show fine? just search for 'tour de france'

**Comment by S3rrrjjj** [comment]
Totally different show. The show I'm trying to add is called "Tour de force".  It can be added with TMDB but it doesn't get episode descriptions. I prefer thetvdb indexer.

**Comment by p0psicles** [comment]
Hmm yeah. That's really strange.
Will get back on this.

@medariox could be a bug on tvdb side. But non the less. Should we add search by id?

**Comment by medariox** [comment]
I don't see how it can be an issue on our side, as we just query their API with the searched words. Search by ID is a great idea to add as an alternative search method, but the issue is on TheTVDB's side and if it is not a caching issue (aka give it 48h after the "website change" to update the API), it should be reported to them directly.

**Comment by S3rrrjjj** [comment]
Why does it work with Sonarr? It doesn't work the same way? I can add it with the series name and no error in the log and .nfo is created 

```
Adding Series [371399][Tour de force] Path: [D:\Shared Videos\TV\Tour de force]
Starting episode info refresh for: [371399][Tour de force]
Downloading Fanart for [371399][Tour de force] https://www.thetvdb.com/banners/fanart/original/5db4409e459e1.jpg
Downloading Poster for [371399][Tour de force] https://www.thetvdb.com/banners/posters/5db44299f3e4c.jpg
```

```
<tvshow>
  <title>Tour de force</title>
  <plot />
  <episodeguide>
    <url>http://www.thetvdb.com/api/API-KEY/series/371399/all/en.zip</url>
  </episodeguide>
  <episodeguideurl>http://www.thetvdb.com/api/API-KEY/series/371399/all/en.zip</episodeguideurl>
  <mpaa />
  <id>371399</id>
  <uniqueid type="tvdb" default="true">371399</uniqueid>
  <genre>Documentary</genre>
  <premiered>2019-10-07</premiered>
  <studio>Canal D</studio>
</tvshow
```>

**Comment by medariox** [comment]
They probably still use the old API (v1) which should have been deprecated since 1 year or so.

**Comment by S3rrrjjj** [comment]
Ok thanks.

**Comment by S3rrrjjj** [comment]
Everything is working this morning. Even the already added shows got the latest updates. Problem had nothing to do with Medusa like you said. At least, I learned Medusa and Sonarr don't use the same API version.
