### ISSUE TITLE
Medusa errors out after updating, won't stay running

### ISSUE THREAD

**Issue by Dragonsys** [pymedusa/Medusa#7296]
**Describe the bug**
I get the following information and then Medusa exits

Traceback (most recent call last):
  File "C:\Tools\Medusa\Medusa\SickBeard.py", line 9, in <module>
    main()
  File "C:\Tools\Medusa\Medusa\medusa\__main__.py", line 2199, in main
    application.start(sys.argv[1:])
  File "C:\Tools\Medusa\Medusa\medusa\__main__.py", line 322, in start
    self.initialize(console_logging=self.console_logging)
  File "C:\Tools\Medusa\Medusa\medusa\__main__.py", line 1011, in initialize
    app.APP_VERSION = updater.current_version
  File "C:\Tools\Medusa\Medusa\medusa\updater\github_updater.py", line 53, in current_version
    return cur_version.lstrip('v')
AttributeError: 'NoneType' object has no attribute 'lstrip'

**To Reproduce**
1. Open CMD Prompt
2. run C:\Tools\Medusa\Python\python.exe "C:\Tools\Medusa\Medusa\SickBeard.py" --nolaunch --port=8081 --datadir="C:\Tools\Medusa\Data"

**Expected behavior**
I expect the script to stay running and listen on port 8081

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Windows 10 x64
 - Branch: master
 - Commit: baad1e5
 - Python version: 2.7.13
 - Database version: I don't know

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
Cannot get debug logs as I cannot start Medusa, what level would debug be if I edit the config.ini directly?
```
</details>

**Additional context**

I tried using the below cmds, but they did not help.
git fetch origin
git reset --hard origin/master

[HEAD is now at baad1e5 Merge pull request #7120 from pymedusa/release/release-0.3.5]

**Comment by medariox** [comment]
Is there any reason why you are not using the installer for Windows? The problem is that you need git installed and reachable.

**Comment by Dragonsys** [comment]
I did use the installer for Windows originally. And git is installed and reachable, hence I ran git to try and reset the install. It has been working fine up until just recently.

**Comment by medariox** [comment]
Uninstall the current version (make sure to make a DB backup) and install again with the installer.

**Comment by Dragonsys** [comment]
I just need to backup the main.db correct?

**Comment by Dragonsys** [comment]
Thanks, that looks to have worked. I see it updated the Python version as well.
