### ISSUE TITLE
DB error: OperationalError('table history has no column named size')

### ISSUE THREAD

**Issue by benpeart** [pymedusa/Medusa#7298]
I used the backup/restore feature to bring my settings over to a new instance of Medusa I'm now running in a docker.  The symptom I first noticed is that the list of shows wasn't restored.  I then manually recreated it.

Next, I noticed was that Medusa kept sending download requests to NZBGet for files that were already being downloaded.  I then noticed that those same episodes were not marked as 'snatched' even though they had been and were being downloaded. 

When I check the logs, I noticed the following sequence happening over and over (see attached logs for complete details) which makes me think the DB that was restored, doesn't match what the new code is expecting (versioning issue?):

"Snatch failed! For result: Marvels..."
.
.
.
2019-10-30 13:59:48 ERROR	SNATCHQUEUE-SNATCH-263365 :: [baad1e5] DB error: table history has no column named size

1. Go to '.Settings Backup/Restore'
2. Backup your main db file and config
3. Restore that db file in another instance of Medusa (running in Docker in my case)
4. Notice the shows aren't listed and missing episodes aren't getting marked as 'snatched'

**Expected behavior**
I expected 'restore' to restore my list of shows.  I also expected the new instanced of Medusa to properly track files that were 'snatched and being downloaded already.

**Medusa (please complete the following information):**
Branch: master
Commit: baad1e5af59d7f29606c1fed1c110af1424bb117
Version: 0.3.5
Database: 44.14
Python Version: | 3.7.5 (default, Oct 17 2019, 12:25:15) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-3.10.102-x86_64-with
Locale: | en_US.UTF-8
User: | abc
Program Folder: | /app/medusa
Config File: | /config/config.ini
Database File: | /config/main.db
Cache Folder: | /config/cache
Log Folder: | /config/Logs
Arguments: | --nolaunch --datadir /config
Runs in Docker: | Yes

**Debug logs (at least 50 lines):**
<details>
[Medusa DB Error.log](https://github.com/pymedusa/Medusa/files/3790724/Medusa.DB.Error.log)
</details>

**Comment by medariox** [comment]
The DB was not upgraded correctly, because the port is already in use:
```
2019-10-30 14:00:40 INFO	TORNADO :: [baad1e5] Could not start the web server on port 8081. Exception: [Errno 98] Address in use
2019-10-30 14:00:40 INFO	TORNADO :: [baad1e5] Starting Medusa on http://0.0.0.0:8081/
```

I suggest you start fresh making sure your port is actually free. At that point restore the backup and restart Medusa.

**Comment by benpeart** [comment]
The port is busy because that is the port Medusa is currently running on (otherwise successfully).  I picked that port because it didn't conflict with anything and it allowed my old copy of Medusa to run side by side so that I could do the backup/restore.

**Comment by medariox** [comment]
I'm not sure what you mean. You can't run two Medusa instances on the same port. You should either stop the old Medusa or choose a different port for the new Medusa install.

**Comment by medariox** [comment]
This is really strange. I suggest you shut down Medusa completely (please make sure all instances are terminated correctly) and open the `config.ini` settings file. In that file you will find the reference `web_port = 8081`. Try to change it to e.g. 8082 and start Medusa again, see if that helps.

**Comment by benpeart** [comment]
I worked around the problem by shutting down Medusa, deleting all the databases (I only left the config.ini file) and then started it back up and added back all my shows manually again.  I just thought I'd let you know there was a problem with the backup/restore feature.

A feature request - allow me to backup/restore my settings but not the DB.  Settings seems simpler and 'worked' while the DB had issues. :)

Thanks for all the work on Medusa!  I know this kind of work is largely thankless - you usually only hear from people when something isn't working correctly.

**Comment by medariox** [comment]
Glad to hear that!

The backup/restore function usually works just fine, I'm not sure what went wrong in your case. Maybe you switched from a (very) old Medusa version?

Most users don't want to manually re-add all the shows, that's why we also backup the DB. Starting with a "fresh" DB is usually a good idea, but can be also pretty annoying. We will think about the feature request for the future.
