### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Channel One

### ISSUE THREAD

**Issue by texacola** [pymedusa/Medusa#7300]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-10-28 13:01:09 ERROR    Thread_0 :: [baad1e5] Missing time zone for network: Channel One
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
Could you provide a log? What is the name of the show that caused this error?
With such a common name it is difficult to accurately determine from which country this tv-network.

**Comment by shawnhicks** [comment]
"channel one (UK):Europe/London" exists in network_timezones.txt, probably refers to BBC One aka BBC ONE.

**Comment by texacola** [comment]
I'm sorry everyone, I had no idea this got sent direct to GitHub from Medusa. I will pay more attention next time this happens!

Tex

**Comment by shawnhicks** [comment]
Missing timezone data is a common issue, could you answer YogSottot's questions?

**Comment by texacola** [comment]
The show is "Better Than Us"  made for the Russian state channel C1R (Channel One) according to Wikipedia and the latest of this error is from 4 days ago and my log file doesn't go back that far. I have a lot of shows in my list... 408 Shows (182 Active).

Thanks, Tex
