### ISSUE TITLE
Plex Alert

### ISSUE THREAD

**Issue by jchristisen** [pymedusa/Medusa#7320]
It would be awesome to also have Plex as a server that Medusa could notify after a update. I have it set to auto detect on plex side however sometimes it can take 5-10 minutes before it detects a change.

**Comment by p0psicles** [comment]
Wait, I don't use Plex. But dont we already have this in config - notifications?

**Comment by jchristisen** [comment]
We do however we don’t have it for plex server

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by p0psicles** [comment]
You mean you want to update your library on your Plex server after Medusa finishes a download? That's possible for server.
