### ISSUE TITLE
[APP SUBMITTED]: sqlite3.OperationalError: table [tokyotoshokan] already exists

### ISSUE THREAD

**Issue by zaans2** [pymedusa/Medusa#7330]
### INFO
**Python Version**: `3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]`
**Operating System**: `Linux-5.0.0-32-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/def72fbe75d3014d9db72678b04d6338
### ERROR
<pre>
2019-11-09 23:16:37 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TokyoToshokan] :: [baad1e5] DB error: table [tokyotoshokan] already exists
Traceback (most recent call last):
  File "/opt/**********/**********/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/**********/**********/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: table [tokyotoshokan] already exists
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Your getting all these issues because cache.db is locked. Maybe opened by sqlite3 editor. Or some other process. Reboot your machine. Or try to stop medusa,delete cache.db and start.
