### ISSUE TITLE
[APP SUBMITTED]: sqlite3.OperationalError: no such column: identifier

### ISSUE THREAD

**Issue by hergonoway** [pymedusa/Medusa#7337]
### INFO
**Python Version**: `3.7.5 (default, Oct 17 2019, 12:25:15) [GCC 8.3.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: https://gist.github.com/9ed9dad936197f2d1704b74f1d352eb9
### ERROR
<pre>
2019-11-12 02:23:09 ERROR    FORCEDSEARCHQUEUE-BACKLOG-262090 :: [Jackett - Nyaa] :: [918cfe7] DB error: OperationalError('no such column: identifier')
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/db.py#L113">medusa/db.py</a>", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: no such column: identifier
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Your db upgrade failed.
Enable debug logs.
Stop medusa.
Restore your main.db.v44.14 to main.db.
Start Medusa.
If still erroring. Post full debug logs

**Comment by hergonoway** [comment]
It's seems to works fine after this operation, thanks !

**Comment by maxcore** [comment]
@p0psicles thx man for this tricks !!
