### ISSUE TITLE
Medusa on Asustor NAS

### ISSUE THREAD

**Issue by aiiDaH** [pymedusa/Medusa#7342]
Hello

I can't find any guide or information on how to install medusa on Asustor 
can someone help me out here

**Comment by p0psicles** [comment]
Can you provide a link to the sickrage manual?

**Comment by aiiDaH** [comment]
> Can you provide a link to the sickrage manual?

not 100% sure of what you mean by that?

Im remembered from some years back that I could write in a repository but now I'm not allowed to do so

i have 3 kinds  I can download. sickchill,sickgear,sickbeard, thioose are one that are in my App Store

**Comment by p0psicles** [comment]
Hmm I'll see if I can hack one of the packages.

**Comment by p0psicles** [comment]
@clinton-hall hi, how much time would it cost you to create a Medusa package?

**Comment by aiiDaH** [comment]
> Hmm I'll see if I can hack one of the packages.

ive seen one post where the person wrote that he installed it but not saying in detail how he did it

**Comment by aiiDaH** [comment]
@Aesculapius how did you manage to do it?

**Comment by clinton-hall** [comment]
Give me a day or 2 and I should be able to package this...

**Comment by p0psicles** [comment]
If it's as easy as pointing to a python bin. Medusa is able to run on py 3.5 and higher. 2.7.13 will also work.

**Comment by clinton-hall** [comment]
@p0psicles 
I have an apkg that can be tested:
https://www.dropbox.com/s/igzilfk6h02fsaz/medusa_20191113_any.apk?dl=0

It works at this end (but I have so many other SickBeard forks installed it is sometimes difficult to verify if there are any requirments that are satisfied/installed by another App).
By default this requires "Python" App installed (which is 2.7), but if users install python3 and set python3 as the main "python" executable, this will pick that up. 

It could be edited to require python3 App and explicitly call python3 if required.

If any users can test and provide feedback, I'll try and update. Once verified all good I will submit to AppCentral.

**Comment by p0psicles** [comment]
@aiiDaH this is where you come in

**Comment by aiiDaH** [comment]
> @aiiDaH this is where you come in

Hello

Sorry for late answer I've been at work

Yes i managed to install it and it seems to work 

I got this message tho ii can't get rid of

WARNING  MAIN :: [80b323e] Your system is using an invalid encoding: ANSI_X3.4-1968. Please change your encoding as soon as possible or you could encounter unexpected issues.

and this is above my paygrade I dont know how to change encoding or what it is?

**Comment by p0psicles** [comment]
Default encoding should be utf-8. But I also don't know how to configure that on your nas

**Comment by p0psicles** [comment]
Well it would be less of an issue if you install python3. And make that default like @clinton-hall mentioned

**Comment by aiiDaH** [comment]
so the encoding has to do with the python ?

i have both installed as in picture, is that the issue for me ?
https://imgshare.io/image/UEIsu

**Comment by p0psicles** [comment]
If your starting Medusa now. Is it running on python3?

**Comment by aiiDaH** [comment]
I tried to uninstall pyton 2.7.10.r10 but it dont let me do it without uninstalling medusa and other apps, how to set  Pyton 3.7.0.r5 as the main is a clue for me

**Comment by p0psicles** [comment]
you shouldn't need to uninstall 2.7. Maybe @clinton-hall has some pointers for it.

**Comment by medariox** [comment]
This is some awesome work, thanks! It would really be great to support Python 3 by default, as we will end Python 2.7 soon, as it reaches its EOL.

**Comment by clinton-hall** [comment]
Ok, try this:
https://www.dropbox.com/s/2cc4vs1j595kunp/medusa_20191114_any.apk?dl=0

this now requires Python3 package to be installed, and then calls Python3...

Let me know if this fixes the encoding issue. I have not been able to test this here since I am working remotely (I have terminal access to edit and compile, but I can't hit any GUI...)

**Comment by aiiDaH** [comment]
Thx @clinton-hall  much appreciated...

@p0psicles  i have problem to get the snatched torrents to appear in Download Center in Asustor, im using black hole, any suggestions?

**Comment by p0psicles** [comment]
Sounds like an access rights issue. Maybe download center can't read them? Is there any user / group management possible in asustor?

**Comment by clinton-hall** [comment]
On Asustor, Medusa runs as admin:administrators, Download Centre runs as root.
Are the torrent files that Medusa saves still in the blackhole directory? 
Can you make Download Centre scan the directory manually?

**Comment by aiiDaH** [comment]
@p0psicles all has worked awesome and suddenly I it doesn't download any show for me and I get this


I get this on all downloads
[8b7f433] Failed to download any results for Supergirl.S05E09.1080p.WEB.h264-TRUMP[rartv]


2019-12-12 10:45:15 WARNING  Thread_9 :: [8b7f433] git fetch --prune origin returned : error: object file .git/objects/5e/5631ce7d1484da6433b9133fa57cb6df2504b1 is empty
fatal: loose object 5e5631ce7d1484da6433b9133fa57cb6df2504b1 (stored in .git/objects/5e/5631ce7d1484da6433b9133fa57cb6df2504b1) is corrupt
fatal: unpack-objects failed
2019-12-12 10:45:15 WARNING  Thread_9 :: [8b7f433] Unable to contact github, can't check for update

**Comment by aiiDaH** [comment]
> On Asustor, Medusa runs as admin:administrators, Download Centre runs as root.
> Are the torrent files that Medusa saves still in the blackhole directory?
> Can you make Download Centre scan the directory manually?

Hello @clinton-hall  I get alot errors now and they say that I need to update it , the maintainer they say need to do it, is it something you can do?

**Comment by aiiDaH** [comment]
> Give me a day or 2 and I should be able to package this...

Could u plz update it againi gladlynt pay for it

**Comment by clinton-hall** [comment]
What is it you want updated in the package? is anything not working?
The whole point of the package is that it uses git and allows you to update from the Medusa web UI.

**Comment by aiiDaH** [comment]
> What is it you want updated in the package? is anything not working?
> The whole point of the package is that it uses git and allows you to update from the Medusa web UI.

Hello @clinton-hall that was what I thought aswell but sudenly it doesn't work and another member told me that I can't update it myself and that I should contact the maintainer

im trying to press "Check for update" but nothing happens and when I check log I get this

2020-01-25 11:10:57 WARNING  Thread_5 :: [8b7f433] git fetch --prune origin returned : error: object file .git/objects/ad/3c38d6ecd1135865e079b4305630c534fd0005 is empty
fatal: cannot read existing object info ad3c38d6ecd1135865e079b4305630c534fd0005
fatal: index-pack failed

2020-01-25 11:10:57 WARNING  Thread_5 :: [8b7f433] Unable to contact github, can't check for update

How can I fix this ?

**Comment by clinton-hall** [comment]
the git install has become corrupt. Could have been the NAS stopped during an update?

To fix, log in via ssh and do the following.
```
/volume1/.@plugins/AppCentral/sickgear/CONTROL/start-stop.sh stop
rm -rf /volume1/.@plugins/AppCentral/sickgear/SickGear/.git
/volume1/.@plugins/AppCentral/sickgear/CONTROL/start-stop.sh restart
```
This will do a fresh install via git clone when it starts.

**Comment by clinton-hall** [comment]
I just updated the above... I originally had the wrong repo referenced, and this only removed the .git folder. The updated commands should remove the Medusa repo and re-clone this.
