### ISSUE TITLE
HTTPS Enabled nothing appears when i click on a poster 

### ISSUE THREAD

**Issue by cico971** [pymedusa/Medusa#7344]
After upgrade to the 0.3.6.
With HTTPS Enabled nothing appears when i click on a poster and try to edit a show.

1. upgrade to latest version
2. enable https with a let's encrypt certificate
3. restart and try to click on a show
4. Nothing appears, you can not see the list of episode or description of the show.

![image](https://user-images.githubusercontent.com/11680207/68722722-a9d95200-05b6-11ea-9d96-2539809dfdfe.png)
![image](https://user-images.githubusercontent.com/11680207/68722763-d0978880-05b6-11ea-8487-eace866f04fe.png)

**Expected behavior**
Before the upgrade when i clicked on a show i could see all the episode and the description

![image](https://user-images.githubusercontent.com/11680207/68722839-0dfc1600-05b7-11ea-8fa1-e451018476a6.png)
![image](https://user-images.githubusercontent.com/11680207/68722863-23714000-05b7-11ea-92bb-f0181912a5ff.png)

Branch: master
Commit: 80b323eefca7c8d3c233ded9f389b0af35725f17
Version: 0.3.6
Database: 44.14
Python Version: | 3.7.5 (default, Oct 19 2019, 00:50:49) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-4.4.59+-x86_64-with
Docker

**Comment by OmgImAlexis** [comment]
Try the page in a incognito window. I’m almost certain this is a caching issue. Had todo this myself.

**Comment by cico971** [comment]
Thanks works for me
