### ISSUE TITLE
Black-on-Black text with Light Theme Manual Search

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/Medusa#7351]
**Describe the bug**
Latest release gives black-on-black text with theme for SHOWS>SHOWLIST>YOUR SHOW>SEARCH 

**To Reproduce**
SHOWS>SHOWLIST>YOUR SHOW> Click on SEARCH icon 

**Expected behavior**
See options for search.

**Screenshots**
![Manual Show Search](https://user-images.githubusercontent.com/6259352/68852285-dd5fcd80-06d7-11ea-83fa-33f11dc8de66.JPG)

Medusa Info: | Branch:                 master                  Commit:                 80b323eefca7c8d3c233ded9f389b0af35725f17                  Version:                 0.3.6                  Database:                 44.14
-- | --
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Windows-7-6.1.7601-SP1
Locale: | en_US.cp1252

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Not a cache issue?

**Comment by DrakeJones** [comment]
Not a cache issue.  Deleted cache, restarted and the problem persists.  Other menus including Restart  also give "black-on-black" text with light theme.  Perhaps the page shade overlay pulled up when menus are invoked is in front of some text in light theme.

**Comment by p0psicles** [comment]
Ooh light theme. Sorry. I foobarred

**Comment by DrakeJones** [comment]
Foobs happen...

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7359

**Comment by DrakeJones** [comment]
Thank you for the fix.   As I mentioned above 
> Other menus including Restart also give "black-on-black" text with light theme. 

> 

The Restart warning and Shutdown warning text colors need to be fixed, too.  I should been more explicit.  Everything else seems fine. Looks like dark theme is more popular among the devs... ;-)
