### ISSUE TITLE
IMDB Add Popular show broken

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#7352]
Add Recommended from IMDb seems to be broken since the latest version
![image](https://user-images.githubusercontent.com/4103090/68857722-1144ee00-06ec-11ea-87c6-4c87c91469c3.png)

**Medusa (please complete the following information):**

Medusa Info: | Branch: masterCommit: 80b323eefca7c8d3c233ded9f389b0af35725f17Version: 0.3.6Database: 44.14
-- | --
Python Version: | 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.1c 28 May 2019
OS: | Windows-10-10.0.17763-SP0
Locale: | nl_NL.cp1252

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-11-14 13:36:11 DEBUG	Thread-7 :: [80b323e] User-Agent: IMDb/8.3.1 (iPhone9,4; iOS 11.2.1)
2019-11-14 13:36:11 DEBUG	Thread-7 :: [80b323e] GET URL: https://api.imdbws.com/chart/tvmeter [Status: 200]
```
</details>

**Comment by medariox** [comment]
Shut down Medusa. Remove the `recommended.dbm*` files in your `cache` folder and start again.

**Comment by Rouzax** [comment]
That seems to have solved it, thanks.
