### ISSUE TITLE
Tosh.0 - not enough information

### ISSUE THREAD

**Issue by annomatik** [pymedusa/Medusa#7358]
**Describe the bug**
Instead of processing my Tosh.0 episodes, Medusa gives me a lot of warnings that it cannot determine, what episode it is. Please help.

2019-11-16 01:29:28 WARNING	POSTPROCESSOR :: [80b323e] Processing failed for /medusa/Tosh.0.S03E02.1080p.BluRay.x264-YELLOWBiRD/Tosh.0.S0302.1080p.BluRay.x264-YELLOWBiRD.mkv: Not enough information to determine what episode this is
2019-11-16 01:29:28 INFO	POSTPROCESSOR :: [80b323e] Processing /medusa/Tosh.0.S03E02.1080p.BluRay.x264-YELLOWBiRD/Tosh.0.S0302.1080p.BluRay.x264-YELLOWBiRD.mkv

**Medusa (please complete the following information):**
 - OS: Raspbian Stretch on a Raspberry Pi 3B+
 - Branch: master
 - Commit: 80b323eefca7c8d3c233ded9f389b0af35725f17
 - Python version: 2.7.13
 - Database version: 44.14

**Comment by p0psicles** [comment]
In the tests folder there is a report_guessit.py script. Run that. `python report_guessit.py filetitle`

**Comment by p0psicles** [comment]
My guess is that guessit can t parse it

**Comment by annomatik** [comment]
Ha, I think I found a clue :-)

The *filename* is wrong, it has "S0302" in its file-name instead of "S03E02".  The *directory* name is right though (S03E02). The cool thing: If I only specify the filename in guess it, it detect Season 302. But if I specify a combination of directory and filename, it detects Season 3, episode 2.

$ python /opt/medusa/tests/report_guessit.py Tosh.0.S0302.1080p.BluRay.x264-YELLOWBiRD.mkv
# guessit: 3.1.0  rebulk: 2.0.0
? Tosh.0.S0302.1080p.BluRay.x264-YELLOWBiRD.mkv
: title: Tosh 0
  season: 302
  screen_size: 1080p
  source: Blu-ray
  video_codec: H.264
  video_encoder: x264
  release_group: YELLOWBiRD
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 0.439851999283
$


$ python /opt/medusa/tests/report_guessit.py Tosh.0.S03E02.1080p.BluRay.x264-YELLOWBiRD/Tosh.0.S0302.1080p.BluRay.x264-YELLOWBiRD.mkv
# guessit: 3.1.0  rebulk: 2.0.0
? Tosh.0.S03E02.1080p.BluRay.x264-YELLOWBiRD/Tosh.0.S0302.1080p.BluRay.x264-YELLOWBiRD.mkv
: title: Tosh 0
  season: 3
  episode: 2
  screen_size: 1080p
  source: Blu-ray
  video_codec: H.264
  video_encoder: x264
  release_group: YELLOWBiRD
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 1.04889297485
$

**Comment by p0psicles** [comment]
yes because there is a priority system for that. Filename precedes folder.
