### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Lifetime (UK)

### ISSUE THREAD

**Issue by shawnhicks** [pymedusa/Medusa#7363]
### INFO
**Python Version**: `2.7.16 (default, May 23 2019, 05:34:26) [GCC 7.4.0]`
**Operating System**: `Linux-4.2.8-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@80b323eefca7c8d3c233ded9f389b0af35725f17
**Link to Log**: https://gist.github.com/c6dc1423b6de40e151f1567351d65ee3
### ERROR
<pre>
2019-11-17 03:33:53 ERROR    Thread_1 :: [80b323e] Missing time zone for network: Lifetime (UK)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by shawnhicks** [comment]
The Joy of Sex Toys
displayShow?indexername=tvdb&seriesid=332959

**Comment by shawnhicks** [comment]
"Lifetime UK:Europe/London" exists in network_timezones.txt

**Comment by shawnhicks** [comment]
Suggestion, option a local file to concatenate with network_timezones.txt retrieval for oddities.

**Comment by medariox** [comment]
Lifetime UK != Lifetime (UK)

Allowing a personal list is also a bad idea, as the point is to share the timezones so that every user can benefit.

**Comment by shawnhicks** [comment]
I completely agree the the best practice is to have an authoritative list, the issue is that there's no obvious direction from the error and it's presented on every startup. If I had the option of creating local_timezones.txt, the error would be resolved until the network_timezones.txt is updated and parsed on next startup. 
For the first months I used sickrage, I had no idea how to correct the error or where it got the data. I even signed up on thetvdb just to amend the source data. As a contributor, one can't modify the core attributes, just episode data. The problem is that there's no authoritative equivalent network list within thetvdb when creating a new show, it's subject to the whim of the generator if the show entry.
The error message should identify the show name and tvdb id that caused the error, so you don't have to ask for it.

**Comment by shawnhicks** [comment]
What is the fastest way to get https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt updated?

**Comment by p0psicles** [comment]
Fork https://github.com/pymedusa/medusa.github.io
Create a branch of master.
Create a PR from your fork/branch.
Change: https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt
