### ISSUE TITLE
Updated to 0.3.6 with pagination, now specials not showing.

### ISSUE THREAD

**Issue by bluelavalamp** [pymedusa/Medusa#7364]
Is there some toggle to turn on so that specials will be shown in the show page now?  Before it would list the seasons and then the specials at the bottom, but after upgrading to 0.3.6 with pagination the specials aren't being shown at all.

**Comment by p0psicles** [comment]
And when you set pagination to all?

**Comment by medariox** [comment]
Upper right side on the show page:
![toggle](https://i.imgur.com/uq9d3Ea.png)

**Comment by shawnhicks** [comment]
Is there a way to default the old behavior (always show everything, including specials)?

**Comment by p0psicles** [comment]
Yes. Enable specials like medariox showed. And set pagination to "all"

**Comment by shawnhicks** [comment]
I mean for all shows, I don't want to have to remember to click show/hide for every individual show. Where can I set "all" and "show specials" for everything?

**Comment by shawnhicks** [comment]
[/share/Multimedia/tv shows] # find -name "Season 00"|wc -l
120
[/share/Multimedia/tv shows] # ls|wc -l
485

**Comment by p0psicles** [comment]
Both settings are for all shows

**Comment by shawnhicks** [comment]
It took a bit to jump through a few shows to verify. You are correct that setting once in any show remains for others (at least during that browser session).

**Comment by p0psicles** [comment]
The hide/show specials is a setting in the app. The pagination is a cookie. So that will be stored in your browser for the coming 10 years. Hope that's enough for you

**Comment by shawnhicks** [comment]
Have you tested pagination against SNL?

**Comment by p0psicles** [comment]
Yeah it's slow. But it loads

**Comment by shawnhicks** [comment]
Halts at S20E16 (500 records?)

**Comment by p0psicles** [comment]
Yes that's by design. Just choose all again if you want to see everything

**Comment by shawnhicks** [comment]
I always want to see everything.

**Comment by shawnhicks** [comment]
Season contains 5 episodes with total filesize: 3.42 GB, no, it doesn't.

![image](https://user-images.githubusercontent.com/26195502/69007757-cc40d780-08f6-11ea-98e1-8ff316e1976d.png)

**Comment by p0psicles** [comment]
It's cut of because of the pagination.

**Comment by p0psicles** [comment]
What I can change is, using the season + specials links at top right, to go to a specific season, also when pagination is limiting. I really don't see a use for always having to load everything.

**Comment by shawnhicks** [comment]
If the total filesize for the table is based on an incomplete display of the table, there should be a disclaimer that the entire table isn't being shown. 
I've been using the software for many years, this is a disruptive change to my use case.

**Comment by shawnhicks** [comment]
Jump to Season/Specials doesn't work unless you've gone to the end of the page and chosen "All".

**Comment by p0psicles** [comment]
I'll look at those issues

**Comment by p0psicles** [comment]
Maybe I'll add an option to disable pagination

**Comment by shawnhicks** [comment]
Why is the page draw so much slower now? I can witness the individual tables being loaded.

**Comment by p0psicles** [comment]
It's pulling per season. And building op the table as they come in. This gives you a much faster partially loaded table. In stead of having to look at a black screen. And then getting them all at once.

**Comment by shawnhicks** [comment]
Please consider adding field headings per season table as a display option.
