### ISSUE TITLE
Medusa never searches for an EP again once skipper

### ISSUE THREAD

**Issue by ozhound** [pymedusa/Medusa#7388]
**Describe the bug**
I have an issue, the issue is that there are several Episodes that are released by groups in specific languages. So i add the groups "tag" to the ignore list so that i only get the english version. however if that group is flagged as an ignored word it sets the Ep to skipped and never tries again.

**Expected behavior**
I expect it to skip that FILE not the entire episode, similar to the release quality

**Medusa (please complete the following information):**

Medusa Info: 
Branch: master
Commit:  94fae847b6e7e443d74c59cb11bdbd37c464b363 
Version:                 0.3.4
Database:                 44.15
Python Version: | 2.7.16 (default, May  6 2019, 19:28:45)  [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1c  28 May 2019
OS: | Linux-3.10.105-x86_64-with

**Comment by medariox** [comment]
Adding a word to the ignore list doesn't change the status of an episode. I'm not sure what you are experiencing.
