### ISSUE TITLE
Vueified showview - does not show season "0" any more [regression]

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#7390]
Version: 0.37
The "specials (season 0 ) is now not being displayed :( 
Example: star-terk discovery.

**Comment by medariox** [comment]
Enable it
![ddd](https://snapr.pw/i/f1506fc9ba.png)

**Comment by rafi-d** [comment]
I don't remember disabling anything  when updating form 0.35 to 0.37 . maybe some DB igration issue?

where is this setting  anyways? :)

**Comment by medariox** [comment]
Top right of the show page

**Comment by rafi-d** [comment]
Thanks! Any global/default  setting for it?

**Comment by p0psicles** [comment]
It is a global setting

**Comment by rafi-d** [comment]
Got it, thanks. 
If you ask me, any global setting should be in the global settings. As it is, there is no way to know it is global, and looks pretty much as shows''s-related ...
