### ISSUE TITLE
Keeps downloading shows that already exist

### ISSUE THREAD

**Issue by Germanicus1982** [pymedusa/Medusa#7395]
**Describe the bug**
In particular "Good Eats: Reloaded"

**To Reproduce**

**Expected behavior**
This show is already there and it keeps downloading a new version of the same quality.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Ubuntu Server 18.04
 - Branch: Master
 - Commit: fcb5a19 (I think)
 - Python version: 2.7.15
 - Database version: unsure

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
My debug logs, advanced, have absolutely nothing about Good Eats Reloaded in them. I'm not sure where to find complete logs other than the web interface.
```
</details>

**Additional context**
It just keeps downloading the season pack for this show even though it's already there. I have to continually delete it from my downloads and there doesn't appear to even be any post processing happening on it.

**Comment by medariox** [comment]
Logs are located in the Logs folder. Closing until they are posted.

**Comment by Germanicus1982** [comment]
Thanks for pointing out where they are located. If I couldn't find them before, you're closing the issue until I find them really helped.

**Comment by p0psicles** [comment]
We just got this posted allot like until a year ago. But nobody was able to post debug logs of this happening. And because we like to keep an overview as much as possible, where closing the issues that don't meet the issue template

**Comment by medariox** [comment]
@Germanicus1982 
I'm not exactly sure what you mean, but you are welcome.

**Comment by Germanicus1982** [comment]
@medariox 
I'm saying I don't know where the logs are stored. I use the front end in which there's no option to view past logs after so many lines. Tell me where they are stored on the file system and I'll post them.
