### ISSUE TITLE
Rating bar have to high value

### ISSUE THREAD

**Issue by sebeksd** [pymedusa/Medusa#7400]
**Describe the bug**
Stars on rating bar are set to to high value. Values over 7.5 are visible as almost 10/10.
All values seems to have at least one star to much.

**To Reproduce**
Add any show.

**Expected behavior**
Show with rating 8 should have 8 out of 10 stars in yellow, shows with rating 5 should have 5 out of 10 and so on.

**Screenshots**
![image](https://user-images.githubusercontent.com/18705953/69452992-4c39c800-0d63-11ea-923e-75b3558aef5f.png)
![image](https://user-images.githubusercontent.com/18705953/69453022-58258a00-0d63-11ea-92bc-12b60ec39ffb.png)
![image](https://user-images.githubusercontent.com/18705953/69453033-5d82d480-0d63-11ea-86fa-592aa9f9140c.png)
![image](https://user-images.githubusercontent.com/18705953/69453051-65db0f80-0d63-11ea-9675-0fcf2cc03855.png)
![image](https://user-images.githubusercontent.com/18705953/69453061-696e9680-0d63-11ea-8249-a9f4f1fceff4.png)

**Medusa (please complete the following information):**
Branch: master
Commit: 6bfdb2236003331e639a1845f765ee0462ae8a5d
Version: 0.3.7
Database: 44.14
Python Version: | 3.7.5 (default, Oct 17 2019, 12:25:15) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-4.14.24-qnap-x86_64-with
Locale: | en_US.UTF-8

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7401
