### ISSUE TITLE
Can't run a docker exec shell /bin/bash?

### ISSUE THREAD

**Issue by jaxjexjox** [pymedusa/Medusa#7402]
**Describe the bug**
Attempting to use a shell to diagnose issues, can't open said shell, can open shell for the other 20 containers on the host

**To Reproduce**
Sudo docker exec -i medusa /bin/bash
(container pymedusa/medusa)

Output =
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

Am I doing something wrong?

**Expected behavior**
Shell to open

**Screenshots**
Not needed really

**Medusa (please complete the following information):**
Ubuntu 18.04
Standard consumer branch
Pymedusa as of 23/11/2019

5.0.0-36-generic
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"

Docker version 18.09.7, build 2d0083d

**Debug logs (at least 50 lines):**

sudo docker run -d --name=medusa -v /dockerconfigs/medusa:/config -v /mnt/TVdownOnSSD:/downloads -v /mnt/TVonARRAY/:/tv -e PUID=0 -e PGID=0 -e TZ=Australia/Melbourne -p 8111:8081 pymedusa/medusa

(NOTE: Medusa itself is working fine - it was giving me trouble but it is infact fine after a reboot and more memory on my system)

I'm a newbie, this is PROBABLY my fault (sorry) ?

**Comment by sharkykh** [comment]
The image is based on Alpine Linux distro. Use `/bin/sh` instead.
