### ISSUE TITLE
Post-Processing not moving srt files

### ISSUE THREAD

**Issue by RazziaDK** [pymedusa/Medusa#7403]
**Describe the bug**
When post processing episodes with srt files, the srt files aren't moved and renamed with the episode.

I have "srt, nfo, sub, idx" in "Keep associated file extensions".
"Delete associated files" is not ticked.

I am a new user coming from Sick Chill (SC). In SC there is checkmark called "Move associated files", and I can't find anything similar in Medusa.

**Expected behavior**
When I add a tv show with subtitles in a srt file, I expect the video file and srt file to be moved to the root directory of the shows and renamed. It works for the video file, but the srt file along with nfo is left in the post processing directory.

**Medusa (please complete the following information):**
 - OS: Docker image pymedusa/medusa:latest

**Comment by medariox** [comment]
Have you enabled subtitles in Subtitles Search settings?

**Comment by RazziaDK** [comment]
I hadn't, and after playing with the settings for a while I got it working!
Thanks!
