### ISSUE TITLE
Save torrent magnet to blackhole folder

### ISSUE THREAD

**Issue by felixbrucker** [pymedusa/Medusa#7407]
I'm currently using sickchill with my own patches to add torrent magnet links to the torrent backhole folder as `xyz.magnet` which is basically a text file with the magnet link inside.

Could this feature be added to medusa as well?

The (pretty old) changes i made for reference: https://github.com/felixbrucker/SickRage/compare/master...felixbrucker:felixbrucker/magnet-blackhole

**Comment by p0psicles** [comment]
I don't see why not. @medariox?

**Comment by medariox** [comment]
I don't see the point of it. What application uses these .magnet files?

**Comment by felixbrucker** [comment]
The problem i solved with this is the following:
Torrent providers might provide .torrent files and/or magnet files. In the event that the torrent provider only provides a magnet link the blackhole torrent downloader needs a torrent tho, so a "converter" is used to "convert" the magnet to a torrent file, which doesnt work reliably/at all in my experience.
As for the torrent downloader im using, im using real-debrid (https://real-debrid.com/) which downloads .torrents or magnets and provides a http download of the finished torrent. I have written a small app that watches a folder for .torrent or .magnet files, adds them to the service, downloads the finished files, unpacks them and moves them into their destination where sickchill can find them.

If you want to support that service directly that would be an alternative of course, but very likely more work.

**Comment by medariox** [comment]
The problem I have with the 1. approach is that it will only serve it's purpose with your exact workflow and scripts. It will be code added for thousands of users that will literally benefit just one person.

I think that a proper implementation, even if initially more work intensive, would allow more users to benefit from it long term and result in a real alternative to the current methods.

**Comment by gersilex** [comment]
Using the exact same workflow with different software. I think adding a feature to "just save the magnet link in a file" instead of failing sounds reasonable. I see how not everybody has this use-case, but that's probably the case for many features.

Just wanted bump this to make clear that there really is interest in. I'm using sonarr just for this single feature and I really don't like it but have no choice.

**Comment by hurricane-dorian** [comment]
Since there is a bunch of debrider providers now, support for all of them can be provided via this feature and it would be very useful even if specific support for real-debrid is added.
