### ISSUE TITLE
Synology python3 upgrade

### ISSUE THREAD

**Issue by scott451** [pymedusa/Medusa#7411]
**Is your feature request related to a problem? Please describe.**
I do not know how to upgrade my Medusa to python3. I have installed python3.6.8 but the two methods for updating (systems or sysvinit) do not seem to apply.

**Describe the solution you'd like**
Any solution is acceptable.

**Describe alternatives you've considered**
I have looked at the sicker-custom synology package to see where python is mentioned, but its complexity surpasses me.

**Comment by p0psicles** [comment]
I think someone needs to create a new Synology package for this

**Comment by scott451** [comment]
hi,

there is a synology installer. i found a custom version for that [here](https://github.com/SynoCommunity/spksrc/issues/3710).

medusa seems to be working fine with python 3.5.8.    :-)


scott
