### ISSUE TITLE
[APP SUBMITTED]: DelugeD: Unable to set the label for Torrent

### ISSUE THREAD

**Issue by akosasante** [pymedusa/Medusa#7413]
### INFO
**Python Version**: `3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.19.55-6-osmc-armv7l-with-debian-9.11`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-11-22 02:41:12 ERROR    SNATCHQUEUE-SNATCH-41524 :: [fcb5a19] DelugeD: Unable to set the label for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
The torrent already exists.
