### ISSUE TITLE
Add new Page Selection feature at top of displayShow? too.

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/Medusa#7416]
**Is your feature request related to a problem? Please describe.**
Not a 'problem' just a bit of a hassle to have to scroll to the bottom of the page to advance.

**Describe the solution you'd like**
Add page selection feature to top of show/season table on displayShow?indexername=tvdb&seriesid=xxxxxx just to the left of select columns drop down.

**Comment by medariox** [comment]
Same as https://github.com/pymedusa/Medusa/issues/7433
Closing this one.
