### ISSUE TITLE
Archived episodes are not part of any displayShow show status filter groups

### ISSUE THREAD

**Issue by below9k** [pymedusa/Medusa#7419]
Archived is not part of the status filters in the displayShow page.

**To Reproduce**
1. Enter show page
2. Deselect all filters (Wanted, Allowed, Preferred, Skipped, Snatch)
3. Notice Archived episodes are still showing up

**Expected behavior**
Archived episodes to be part of the Preferred grouping filter or have another filter for Archived episodes.

**Screenshots**
![Screen Shot 2019-11-26 at 1 21 27 PM](https://user-images.githubusercontent.com/6232236/69665276-aa122c80-104f-11ea-9bcb-0a078b94bab4.png)

**Medusa Info:**
Branch: master
Commit: fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
Version: 0.3.7
Database: 44.14
Python Version: 2.7.12 (default, Oct 8 2019, 14:14:10) [GCC 5.4.0 20160609]
SSL Version: OpenSSL 1.0.2g 1 Mar 2016
OS: Linux-4.15.0-70-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: en_US.UTF-8

**Additional**
Also seeing: https://github.com/pymedusa/Medusa/issues/6372

**Comment by p0psicles** [comment]
@medariox should I just put them in preferred? Or create a new filter?

**Comment by eddywitkamp** [comment]
I started using Medusa (it's great!) and imidiately ran into this problem. Please make a new Archived filer.

**Comment by eddywitkamp** [comment]
Please add a new Archived filter, it would not be that difficult but would improve Medusa massivley.

**Comment by p0psicles** [comment]
Archived is part of the preferred group.
