### ISSUE TITLE
Backlog search not started because of running manual/forced search

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#7422]
**Describe the bug**
## issue
When a new show is added. After adding it, it will start a backlog search if there are any episodes wanted. Unfortunately we use a number of threadqueues for scheduled searches like daily, backlog and proper. As a separate queue for manual searches.

When a manual search is in progress it will skip out of the backlog search. Meaning it will have another go at the next scheduled backlog search.

Because adding a show and performing a manual search are both manual tasks. Chance is high the user is running a quick manual search, and adding a new show at the same time.

## Proposed solution 1
In stead of dropping out of the scheduled backlog, pause it. And continue when the manual search has finished.

## Proposed solution 2
In stead of starting a scheduled backlog search, start a manual backlog search. That will be queued after the running manual search. 
**To Reproduce**

1. Start manual search
2. Add show with default status "wanted"
3. Notice the warning in logs:
```
2019-11-26 23:01:08 INFO     SHOWQUEUE-ADD :: [90f59e4] Launching backlog for this show since its episodes are WANTED
2019-11-26 23:01:08 WARNING  SHOWQUEUE-ADD :: [90f59e4] Manual search is running. Unable to start Backlog Search
```

**Medusa (please complete the following information):**

Medusa Info: | 
Branch: develop
Commit: 90f59e47ddcae341d9af0560b2588ea775902735Version: 0.3.7Database: 44.15
-- | --
Python Version: | 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Linux-4.9.0-4-amd64-x86_64-with-debian-9.9
Locale: | en_US.UTF-8

**Comment by p0psicles** [comment]
@medariox fya

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7423
