### ISSUE TITLE
Docker image [latest] not up to date?

### ISSUE THREAD

**Issue by dirkr07** [pymedusa/Medusa#7431]
More of a question than a bug report I guess.
I recently moved from another fork to Medusa and am running it in Docker (on Synology) using the https://hub.docker.com/r/pymedusa/medusa/builds repository.

I pulled the "latest" image but this contains 3.6 while it keeps telling me there is a new release 3.7
Is the latest image autobuild with every release in master or is this a manual thing that somebody needs to do?

Just trying to get to the last version and otherwise I'll just move out of docker and install it normally.

Thanks!

**Comment by medariox** [comment]
You need to update the image manually when there is a new release available. In your case `docker pull pymedusa/medusa:latest` (or `:master`, it is the same) and restart the container. The images are built automatically when we merge new commits, yes. There is also `:develop` if you want to give the development builds a try.

**Comment by dirkr07** [comment]
@medariox I get that I need to manually pull the new image and rebuild my container. Thats not an issue.
The thing is that I noticed there was a release of 3.7 11days ago but the image doesn't seem to be updated to that yet? or can you confirm it is up to date?

I went from 3.5 to 3.6 by pulling the image and restarting my container.
For 3.7 I pulled the image, restarted the container and nothing happened.

If you can confirm that the current image (tag: latest) is 3.7 updated I can look towards fixing my setup :)

**Comment by medariox** [comment]
Sorry for the wait, I had to set up a virtual machine to install Docker. I can confirm that pulling `:latest` uses the correct version for me:
![img](https://snapr.pw/i/fe020e05ff.png)

**Comment by dirkr07** [comment]
@medariox Thanks for confirming.
For some reason my docker stays on 0.3.4 even though I repull the image, must be a synology docker thing.
I'll figure it out on my own further.
