### ISSUE TITLE
[Wiki] Debian 9 & 10 have Python3

### ISSUE THREAD

**Issue by Samillion** [pymedusa/Medusa#7435]
In the Wiki, the "[Switch to Python 3](https://github.com/pymedusa/Medusa/wiki/Switch-to-Python-3)" page, in Debian section, the only mention is to install it from source.

However, Debian 10 (Stable) already [includes Python 3.7 in its packages](https://packages.debian.org/buster/python3).

**Debian 10 (Buster):**
Steps to install and switch Medusa to Python 3 on Debian 10 (Buster):

1. Install Python 3

```
sudo apt update
sudo apt install python3
```

2. Open your systemd script located at:
```
/etc/systemd/system/medusa.service
```

3. Replace all mentions of python2.7 with python3.7 and save.

4. Reload systemd daemon:
```
sudo systemctl daemon-reload
```

5. Restart Medusa as you'd normally do:
```
sudo systemctl restart medusa
```

**Result:**
![Debian 10 Python 3](https://i.postimg.cc/CxRpBDnq/Annotation-2019-12-01-015231.jpg)

**Debian 9 (Stretch):**
Debian Stretch also includes [Python 3.5](https://packages.debian.org/stretch/python3) in the default available packages.

I haven't tried this on Stretch, but according to the Medusa team, Python 3.5 should work just fine.

So to install it on Debian Stretch, follow all the same steps above, except for the part on systemd script, do this instead:

Open your systemd script located at:
```
/etc/systemd/system/medusa.service
```

Replace all mentions of python2.7 with python3.5 and save.

Make sure to do the other steps after this as mentioned above.

**Comment by medariox** [comment]
Thanks for the feedback! I've updated the wiki entry accordingly.
