### ISSUE TITLE
In vue Show page - "Change status to:" does not seem to work/modify the  GUI

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#7436]
In 0.37/Win10 - Tries to change status to "Wanted" , it seems to add the show well to he backlog, but the episode line seems unchanged (not wanted nor snatched) . 

The test was done on old show, what was already aired, as well as on specials , that were NOT aired yet (Star-track: discovery)

Also, the page is not being auto-refreshed

**Comment by medariox** [comment]
Use the bug report template to report issues.
