### ISSUE TITLE
Search Settings page does not show up after most recent update

### ISSUE THREAD

**Issue by Yellow1144** [pymedusa/Medusa#7443]
After the latest update I can no longer access the Search Settings page. The result is just blank.

Branch: develop
Commit: f2be45a0d63ff07cfe8a0a6310027fc5b9accdf8
Version: 0.3.7
Database: 44.14
--
Python Version: | 3.7.5 (default, Oct 15 2019, 21:38:37) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.15.0-65-generic-x86_64-with-LinuxMint-18.3-sylvia
Locale: | en_CA.UTF-8

Nothing appears in the debug logs when I try to access the page.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7445
