### ISSUE TITLE
Some shows are not updating automatically

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#7450]
**Describe the bug**
Some "TVDB" shows are not updated over night, through the ShowUpdater.
This is happening because tvdb is still having a lot of issues with their api v3 switch.

Here is a list of all the issues:
https://forums.thetvdb.com/viewtopic.php?t=60239

And we suffer from the issue reported here:
https://forums.thetvdb.com/viewtopic.php?f=17&t=60229&start=10

So if you want to keep track of it's status you can check there.

Currently, there is nothing that we can do about it.
You can monitor your shows yourself. And once a week run a few forced updates.
If possible you can remove your show. But keep the data. And re-add it with tvmaze or tmdb, when possible. For example, this is not possible for anime shows.

Eventually, this will get resolved, and shows will start updating themselves.

**Comment by PinaColonic** [comment]
A friend and I both noticed today we are having this same issue with shows not updating - he did first and then I forced scan in mass update and found the same.   Got here and you already have a bug for it.  Just figured I would note we are seeing it too in case that helps with triage.

**Comment by rafi-d** [comment]
> Currently, there is nothing that we can do about it.
> You can monitor your shows yourself. And once a week run a few forced updates.
> If possible you can remove your show. But keep the data. And re-add it with tvmaze or tmdb, when possible. For example, this is not possible for anime shows.
>

I've noticed it too (with Vikings) :( Maybe you can add a hot-fix/possibility  in 'Edit show' to replace the indexer or to add another one? Or better yet - if the API fail is noticible - try another indexer?

Thanks

**Comment by p0psicles** [comment]
@rafi-d no that's really allot of work. Like a few weeks coding.

**Comment by rafi-d** [comment]
@p0psicles where can you see what exact indexer is being used for a show?

**Comment by p0psicles** [comment]
Different places. But for ex home - simple layout. You'll have icons for IMDb, trakt and the indexer

**Comment by rafi-d** [comment]
So, if I'd change manually  in main.db the indexer from 1 to 3 (tvMaze) and the indexer_id to whatever it is in tvMaze, it will be enough?

**Comment by p0psicles** [comment]
Yeah, but don't expect any support when shit hits the fan.

**Comment by medariox** [comment]
Should be fixed by now, closing.
