### ISSUE TITLE
Restore from Sickrage does not appear to work; no showlist, settings, on Synology NAS

### ISSUE THREAD

**Issue by Robert-SF** [pymedusa/Medusa#7453]
I backedup my sickrage install, and uninstalled on my Snology NAS.
Installed from the sickbeard-custom package with Medusa path.
Restore of backup file doens't show any restored show lists or config, with restart and no error messages.
Google-fu showed that I may want to rename the sickbeard.db to main.db, and re-zip and restore.
Did so, and no success.
But I am on a Mac and my ZIP file may contain a _Macos file in the ZIP....

SSH into the path to manually restore main.db, config.ini, etc, but got error messages. Did not capture those on start up and no success.
Unistalled and reinstalled several times.

Any help?

**Comment by p0psicles** [comment]
Stop medusa.
Only restore / overwrite files main.db and config.ini
Start
