### ISSUE TITLE
0.3.8 Regression: Episode title (i) mouseover no longer shows synopsis/summary

### ISSUE THREAD

**Issue by jtwill** [pymedusa/Medusa#7464]
**Describe the bug**
The episode title column shows a circle-i which in the past has been a mouseover (hover text) for a synopsis or summary of the episode. Immediately after upgrading to version 0.3.8, this mouseover stopped working. It does not display anything (cursor changes to a '?' cursor)

**To Reproduce**
Go to a show season list or a schedule of future downloads.
Find any circle (i) in the episode title and hover mouse over it
Note that no hover text is displayed

**Expected behavior**
An episode synopsis or summary should be displayed when hovering mouse over circle (i)

**Screenshots**

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64]
 - Branch: [e.g. master, develop]
 - Commit: [e.g. c65ca2]
 - Python version: [e.g. 3.6.8]
 - Database version: [e.g. 44.12]

Medusa Info: | Branch:                 master                  
Commit:                 8b7f433d4dce89058a8b9b62cc9bcd7a162a3344                  
Version:                 0.3.8                  
Database:                 44.14
Python Version: | 3.8.0 (default, Oct 23 2019, 18:51:26)  [GCC 9.2.0]
SSL Version: | OpenSSL 1.1.1d  10 Sep 2019
OS: | Linux-5.3.4-arch1-1-ARCH-x86_64-with-glibc2.2.5
Locale: | en_US.UTF-8

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**
This is a regression with Medusa version 0.3.8. The problem did not exist with prior version.

**Comment by OverlordQ** [comment]
Bisect gives you:

```
root@cc1d6c512025:/app/medusa# git bisect bad
198f5bf8ee9b665534e287d755974a239b0f15fc is the first bad commit
commit 198f5bf8ee9b665534e287d755974a239b0f15fc
Author: p0ps <p0psicles@users.noreply.github.com>
Date:   Wed Nov 27 22:58:29 2019 +0100

    Feature/vueify config main (#5617)
```

**Comment by medariox** [comment]
Fixed in develop with: https://github.com/pymedusa/Medusa/commit/3eb3cc4b1d9e685ed0a03c14a518acb919a3d19c
Will be available with the next release.
