### ISSUE TITLE
v0.3.8 Issues 

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#7468]
**Describe the bug**
Since upgrading from v0.3.7 to v0.3.8 nothing wants to show under Shows or scheduled etc... 

**To Reproduce**
1. Shutdown medusa
2. Update Docker
3. Clear Settings Of Container
4. Power Up Container

**Expected behavior**
Show all info

**Medusa (please complete the following information):**
 - OS: Synology DSM
 - Branch: Master / Showing Unknown
 - Commit: Unknown
 - Python version: Unknown
 - Database version: Unknown

Thanks

**Comment by HPMSGEN8** [comment]
@medariox & @p0psicles Have you seen this issue on Docker at all. as right now i am dead in the water cannot do anything. 

Any help on this please. 

Thanks in advanced.

**Comment by udochrist** [comment]
I had that issue. Needed to clean the Browser Cache so it’s working again

**Comment by HPMSGEN8** [comment]
@udochrist Awesome thanks for this :) 

Issue Resolved.
