### ISSUE TITLE
WARNING  APIv2-Thread_11 :: [8b7f433] Config patch ignored {'showDefaults': {'subtitles': False}}

### ISSUE THREAD

**Issue by pepitopajas** [pymedusa/Medusa#7475]
When you modify the program data in:

GENERAL / INDEXER

These parameters are not saved:

Default Indexer Language

Use initial indexer set to

Verified on linux and windows 7

And this message appears in logs

2019-12-12 02:01:11 WARNING  APIv2-Thread_11 :: [8b7f433] Config patch ignored {'showDefaults': {'subtitles': False}}

medusa 0.3.8
Python Version: | 3.7.3 
OS: | Windows-7

**Comment by p0psicles** [comment]
@medariox i'll fix these

**Comment by p0psicles** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7478
The showDefaults warning is unrelated and harmless. I'll look at that in the new year
