### ISSUE TITLE
Unable to connect to qbitorrent

### ISSUE THREAD

**Issue by pepitopajas** [pymedusa/Medusa#7476]
Unable to connect to qbitorrent

Medusa Info: | Branch: masterCommit: 8b7f433d4dce89058a8b9b62cc9bcd7a162a3344Version: 0.3.8Database: 44.14
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-7-6.1.7601-SP1
Locale: | es_ES.cp1252

**Comment by sharkykh** [comment]
You didn't provide logs so I don't know what's actually wrong,
but if you updated qBittorrent to version 4.2.0, take a look at https://github.com/pymedusa/Medusa/issues/3134#issuecomment-562262927

**Comment by medariox** [comment]
Improved further with: https://github.com/pymedusa/Medusa/pull/7474
