### ISSUE TITLE
Set yggtorrent url manually

### ISSUE THREAD

**Issue by Amonbofils** [pymedusa/Medusa#7479]
Hi there!

As Yggtorrent is always changing URL, and your developpers have more to do than change it every 2 month, i'd love to have a way to change manually this URL in settings .

Currently, i use docker for medusa, but i can't find a way to access permenently to providers/html folder to make it persistant. So for better use and easier way to change it than going into config files, i think it can be a good way to add a field in yggtorrent config file.

What do you think about it ?

Thanks

**Comment by medariox** [comment]
There is no need for it, as we simply redirect to the new domain. So there is no worry it will break.
