### ISSUE TITLE
get_iplayer support

### ISSUE THREAD

**Issue by ljmellor** [pymedusa/Medusa#7494]
**Is your feature request related to a problem? Please describe.**
Not exactly

**Describe the solution you'd like**
It would be nice to be able to use get_iplayer as a source for downloads

**Describe alternatives you've considered**
For the shows that aren't available through other sources I regularly have to manually use get_iplayer to obtain some shows, it would be fantastic if this could be included as an alternative to using torrents/nzbs

**Additional context**
https://github.com/get-iplayer/get_iplayer

**Comment by gmusgrave** [comment]
I upvote this feature request

**Comment by p0psicles** [comment]
Meh it's a perl script

**Comment by p0psicles** [comment]
Any python libs for it?

**Comment by medariox** [comment]
Won't happen, sorry.
