### ISSUE TITLE
[ FEATURE ] Omit show(s) from nightly scans

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#750]
it would be nice to have an option to flag a show as "do not update/scan/nightly" at all. call it a way to "archive" a show meaning no automated process will update show info etc that nightly scan does..

this would, for those who have quite a large collection, lessen the nightly workload since shows the user has manually tagged as "finished/archived show" to be omitted from the scan alltogether.

still it would be nice to be able to manually update a show from the DisplayShow page using "force full update".

For reference; I had a quick chat about this with Labrys on IRC.

**Comment by Thraxis** [comment]
When viewing the show, click on the "Pause" button on the top

**Comment by wimpyrbx** [comment]
@thraxis thanks, but no. This is a different option. if a show is PAUSED it will still go through all episodes of that show each night to update episode metadata etc. this feature request is to omit chosen shows for this nightly scan alltogether.

I.E. shows that you feel are as complete as you'd want them and still want them displayed in sickrage.. but there is no need or desire to have them included in the nightly scan.

**Comment by labrys** [comment]
Essentially an option to reduce processing of shows in a "frozen state" for performance concerns (among others).

**Comment by wimpyrbx** [comment]
http://weknowmemes.com/wp-content/uploads/2013/09/youre-goddamn-right-heisenberg-gif.png
:D

**Comment by fernandog** [comment]
Imo if all eps are download/archived (with desired quality) it shouldnt be updated

**Comment by Thraxis** [comment]
Sickrage should only be updating shows that actually had a change since the last time showUpdater ran, not looking through every show to see if it needs a change.  

When I wrote the code I didn't take into account not updating paused shows as other code in sickrage tended to block updates / downloads. etc.  

The code to change and what should fix it is noted below

https://github.com/pymedusa/SickRage/blob/d0c1d270f08bc1b84183d81a1ea5b1d70cacc426/sickbeard/showUpdater.py#L105-L108

```python
            try:
                if indexer_name == 'theTVDB':
                    if cur_show.indexerid in updated_shows:
                        pi_list.append(sickbeard.showQueueScheduler.action.updateShow(cur_show, True))
```


Should be changed to:
```python
           try:
                if indexer_name == 'theTVDB':
                    if cur_show.indexerid in updated_shows:
                        if not cur_show.paused:
                            pi_list.append(sickbeard.showQueueScheduler.action.updateShow(cur_show, True))`
```


NOTE:  This will only account for the TVDB indexer code.  The other code would need to be changed as below:

https://github.com/pymedusa/SickRage/blob/d0c1d270f08bc1b84183d81a1ea5b1d70cacc426/sickbeard/tv.py#L291-L295

```python
    def should_update(self, update_date=datetime.date.today()):

        # if show is not 'Ended' always update (status 'Continuing')
        if self.status == 'Continuing':
            return True
```

Change to:

```python
    def should_update(self, update_date=datetime.date.today()):

        # if show is not 'Ended' always update (status 'Continuing')
        if self.status == 'Continuing':
            return True
```

        # if the show is paused never update
        if self.paused:
            return False

**Comment by fernandog** [comment]
Yes. But why keep updating old episodes?
Is there a way to block it?

**Comment by Thraxis** [comment]
The code I posted above will block a show from being updated if it is in the pause state.

**Comment by Thraxis** [comment]
Just to revisit this issue a bit.  One current issue even with using the code to skip paused shows is that when a show is flagged to update checks every season and every episode.  TVDB provides the list of episodes that were updated, but the current system has no way to use this information reliably.

Nor is the current code very clean for multiple indexers as it isn't modular.

**Comment by fernandog** [comment]
@p0psicles is working on tvdb v2. maybe we can fix it by only updating episodes that got updated

**Comment by p0psicles** [comment]
As long as the tvdbv2 pr is open,  I'm open to suggestions or FR's.

**Comment by Thraxis** [comment]
Looks like the  tvdbv2 api only provides the updated series.  The updated episodes are only provided in the UPDATE XML files.

**Comment by fernandog** [comment]
so instead of get the updated series, we only get the updated episodes and from there we can know the update series. What do you think?

**Comment by p0psicles** [comment]
I think it's the other way around, but I think that's what you meant.

**Comment by labrys** [comment]
The way the api is intended is to get a list of series that are updated, and then submit an api request for each updated series you're interested in.

**Comment by Thraxis** [comment]
I'm documenting out what the current show Update process is right now which might help a bit on seeing where time has already been saved, and where time is being spent currently.

**Comment by Thraxis** [comment]
Below is the current process that the show Update goes through.  This does not account for the excluding of paused shows.

---

The show update process first sets an array named bad_indexer to contain any bad indexers,  currently only set to INDEXER_TVRAGE.  

Next it sets the update_datetime and update_date to now() update_datetime is then converted to update_timestamp using time.mktime.

One that is set it checks if there is a lastUpdate for theTVDB in the cache.db if there is it sets the last_update variable to that date if not it sets the last_update variable to update_timestamp  - 86400 (or 1 day previous)

Next we calculate the time delta between update_timestamp and the last_update

If it is 8 days (691200 seconds) or greater we download the updates_month.xml

If it is 25 hours (90000 seconds) or greater we download the updates_week.xml

If it is less than 25 hours we download the updates_week.xml

The path to the files to download are formatted as:

http://thetvdb.com/api/{API_KEY}/updates/{FILE_TO_DOWNLOAD}

The XML file contains lists of the Series ID’s that have been updated, Episode ID’s and Artwork ID’s

We parse the list and add all series ID’s into the updated_shows array 

Next we iterate through all shows, skipping any that have an indexer in the bad_indexer array.  

If the show indexer_name is ‘theTVDB’ we check if the cur_show.indexerid is  in the updated_shows array.  If it is we add the show to the showQueueScheduler to update the show.

If the show indexer_name is not ‘theTVDB’ a function from tv.py is called cur_show.should_update, passing the update_date variable.  

If the show status is ‘Continuing’ then the show is added to the showQueueScheduler.  If it is ‘Ended’ the show is checked to see if there is an episode air-date in the past 30 days or in the next 30 days.  If there is, it will be added to the showQueueScheduler.  During the first year of the show having ended it will be added to the showQueueScheduler once every 30 days.

The showQueueSchedular calls show_queue.py and calls QueueItemUpdate(ShowQueueItem)

This is where the actual work for update the show happens.

First it pulls information from the indexer for the show using show.loadFromIndexer (cache=not, self.force)

Next it loads information from IMDB using show.load_imdb_info()

This information is then saved to the database using show.saveToDB()

Next the updater loads all episodes from the database using show.loadEpisodesFromDB() into DBEpList.  Then loads all episodes from the Indexer using show.loadEpisodesFromIndexer(cache=not, self.force) into IndexerEpList. If there is no information in IndexerEpList the update is aborted.  If there is data it loops through each episode of each season and saves that information to the DB for each episode it saves it deletes that episode from the DBEpList.  If there are episodes in DBEpList after processing all episodes from theIndexer it deletes those episodes from the database.

After episodes have been processed it makes a new call to show.saveToDB.

**Comment by Thraxis** [comment]
tvdbapiv2 only provides a call to get updated series ID's using a call like:
https://api.thetvdb.com/updated/query?fromTime=1468861397

ideally if they continue to provide the XML files (which I have not heard that they would discontinue). They can be used to generate the list of episodes to update vs. just updating everything.  And when you have a show like Supernatural that currently has 12 seasons that is a significant chunk of time.

The caveat of this is that the list of updated episodes only contain the indexer ID of the episode not the season / episode number.  The functionality of removing episodes that do not exist on the indexer would no longer be functional either.
