### ISSUE TITLE
Adding new shows: use of season folders is forced (and can not be switched off or on)

### ISSUE THREAD

**Issue by ArieKindicator** [pymedusa/Medusa#7504]
**Describe the bug**
When adding new series the option "Group episodes by season folders?" is turned _on_ by default and can't be (manually) switched off (or on). Basically, this option is greyed out for user input.

**To Reproduce**
1. Go to 'Add new show, and add a (ramdom) new show'
2. Click on 'next' to go to page 3 or "Step 3, Customize options"
3. Try to toggle the button on and off for "Season Folders". You can't do this manually it is 'greyed out' for user input and on by default.

**Expected behavior**
This option "Season folders" should be turned on or off by user input.

**Screenshots**
Not necessary.

**Medusa (please complete the following information):**
 - OS: Linux-3.2.54-armv7l-with-glibc2.4 on Zyxel NAS520
- Branch: master
- Commit: fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
- Version: Unknown
- Database: 44.14
- Python Version: 2.7.16 (default, Oct 03 2019, 21:10:12)  [GCC 7.4.0]
- SSL: OpenSSL 1.1.1d 10 Sep 2019

Medusa is up-to-date, at every reboot the startup script of Medusa checks the github repository for updates. 

**Debug logs (at least 50 lines):**
Not necessary.
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

Edit:
![medusaseasonfolders](https://user-images.githubusercontent.com/4154128/70987009-5e3b2c00-20bf-11ea-8d42-2fcbdb653ab4.png)
The image shows that the toggle for season folders uses a different green color and I can not toggle it on or of. The toggle for Anime works as expected.

Maybe I can change it directly in the config.ini. `flatten_folders_default = 0` Changing it to 0 or 1 has no effect, but changing `anime_default = 0` to 0 or 1 toggle it on or off. Strange.

**Comment by p0psicles** [comment]
no problems here, toggling that.
![toggle_season_folders](https://user-images.githubusercontent.com/1331394/70985492-82493e00-20bc-11ea-9e91-68fde8bb1f51.gif)

**Comment by sharkykh** [comment]
AFAIK it's related to the "Name Pattern" on Post-Processing config.
I think if you don't have the season number in the filename you can't disable season folders.
And after changing the settings you need to restart Medusa...

**Comment by ArieKindicator** [comment]
> 
> 
> AFAIK it's related to the "Name Pattern" on Post-Processing config.
> I think if you don't have the season number in the filename you can't disable season folders.
> And after changing the settings you need to restart Medusa...

Yes, that was the problem. By mistake i had a season number in my name pattern, I removed it and now i can toggle the season button on the "Add Shows" page. Thanks.
I'm closing this issue.
