### ISSUE TITLE
Add EZTV as search provider need help

### ISSUE THREAD

**Issue by JorgMuskens** [pymedusa/Medusa#7506]
Hi Guys,
Most likely eztv is not everybodý favorite search provider but for me it is. 
So i started to check wether i was able to get the provider added by my self 
So i managed to retrieve the URL's which are needed to get a search on eztv

# URLs 
#SHOW search | https://eztv.io/search/?q1=game+of+thrones&q2=&search=Search
#EPISODE search | https://eztv.io/search/?q1=the+expanse+s04e01&q2=&search=Search 

So i tried to modify the zooqle.py file as eztv works similar as we need to scrap the page for the magnet link. The table section is not correct in the attached file and i want to test further

But i do not know how to test this. Can I just drop the file in de html folder? or do i need to make more changes to more files to add the provider.

I used to have a guide but i can not find it anymore

Hope someone is willing to help
[eztv.py.txt](https://github.com/pymedusa/Medusa/files/3975162/eztv.py.txt)
BR jorg

**Comment by medariox** [comment]
Please open a PR with your changes. It's by far the easiest way to show us your progress and for us to provide feedback and help.

**Comment by JorgMuskens** [comment]
Hi medariox,
I actually moved to json and got i woring perfectly. I am not fimiliar with github PR. I will try to open one with the code.

**Comment by JorgMuskens** [comment]
Added provider EZTV #7508
I created the PR hopefully correct otherwise let me know
