### ISSUE TITLE
[ FEATURE ] Add notes pr show/season

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#751]
it would be handy for those who really keep track of their shows status.. to add notes about the show or a specific season of a show.

example "this show/season needs to be replaced when a decent x265 release is out"
example "episode 8-10 are not possible to get a hold of due to BBC deleted them"

**Comment by OmgImAlexis** [comment]
@wimpyrbx isn't this the same as https://github.com/pymedusa/SickRage/issues/576?

**Comment by wimpyrbx** [comment]
https://github.com/pymedusa/Medusa/issues/576
