### ISSUE TITLE
Adding an Anime with release groups results in byte strings.

### ISSUE THREAD

**Issue by skarekrow** [pymedusa/Medusa#7510]
**Describe the bug**
Adding an anime show and putting in 2 release groups causes both groups to be a byte string in a list once finished. Adding just one group does not result in this behavior.

**To Reproduce**
1. Go to Add Shows
2. Add any Anime ([Bleach](http://dereferer.org/?https://www.thetvdb.com/dereferrer/series/74796) used in this example)
3. Add two groups like my picture

**Expected behavior**
The same groups being added as doing it via Edit - Format after the show is added

**Screenshots**
![Screen Shot 2019-12-18 at 4 22 06 PM](https://user-images.githubusercontent.com/1589047/71128392-be5eca80-21b2-11ea-8200-f1d617fac0eb.png)
![Screen Shot 2019-12-18 at 4 23 25 PM](https://user-images.githubusercontent.com/1589047/71128394-bf8ff780-21b2-11ea-8956-ae175593b67a.png)

**Medusa (please complete the following information):**
Medusa (please complete the following information):
OS: debian x64/docker
Branch: master on tag Version: 0.3.9
Commit: unknown
Python version: 3.7.5
Database version: 44.14

**Debug logs (at least 50 lines):**
Nothing shown in logs

**Comment by p0psicles** [comment]
Was just fixed in develop branch
