### ISSUE TITLE
Automatic periodic Backup

### ISSUE THREAD

**Issue by eddywitkamp** [pymedusa/Medusa#7513]
**Is your feature request related to a problem? Please describe.**
I have had numerous occasions when I Restart Medusa from the menu, it returns with 0 shows in the list. Meaning I have to restore from a backup.

**Describe the solution you'd like**
A setting to set a periodic backup automatically, so I always have an up to date backup available to restore.

**Describe alternatives you've considered**
Manual backup - but you can easily forget about that.

**Comment by dirkr07** [comment]
Would be great!

**Comment by gmusgrave** [comment]
I agree that this would be a great addition!

**Comment by p0psicles** [comment]
A simple batch / shell script could do the job. Copy main.db, failed.db and config.ini. and optionally your whole cache folder.

**Comment by medariox** [comment]
Backup is done on every update.
