### ISSUE TITLE
UI unusable on shows with large amount of episodes

### ISSUE THREAD

**Issue by mkarer** [pymedusa/Medusa#7520]
The UI gets unresponsible when it loads shows with a large amount of episodes in Firefox and Chrome (didn't test any other browsers).

[Detective Conan](https://www.thetvdb.com/series/detective-conan) for instance has ~1000 episodes, setting the amount of rows per page to 50 kinda works (although with ~3 seconds lag when clicking on a checkbox), but when I try to show 100 or more rows per page it's impossible to check all episodes of a season by using the checkbox next to the season (the episodes are checked shortly, but for some weird reason get unchecked again).

I'm using the linuxserver/medusa docker image but I've also already tried the develop branch which has the same issue. I guess it's a problem with Vue?

Medusa Info:
Branch: master
Commit: fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
Version: 0.3.9
Database: 44.14
Python Version: 3.7.5 (default, Oct 17 2019, 12:25:15) [GCC 8.3.0]
SSL Version: OpenSSL 1.1.1d 10 Sep 2019
OS: Linux-4.4.59+-x86_64-with
Locale: en_US.UTF-8

**Comment by skarekrow** [comment]
Unfortunately I ran into this issue too. Besides using 50 per page like you said, waiting quite a while works too. It continually paginates downwards until it’s done. All doesn’t mean all either, seems to cap at 500.

**Comment by p0psicles** [comment]
Try develop branch. We fixed a double loading bug there.
You can disable pagination if not satisfied with it.

**Comment by mkarer** [comment]
> 
> 
> Try develop branch. We fixed a double loading bug there.
> You can disable pagination if not satisfied with it.

I already did, same issue (disabling pagination made it worse for me). You can easily test it yourself, just add "Detective Conan" and try to check all episodes of one season.

**Comment by medariox** [comment]
I now understand what's going on here. This is not an issue of the UI being unresponsive. While episodes are being loaded in the background, if you select one or more episodes they are getting deselected as soon as more episodes load (in the background). It looks like the UI is unresponsive, but actually the selection is just getting removed every X seconds.

**Comment by mkarer** [comment]
> I now understand what's going on here. This is not an issue of the UI being unresponsive. While episodes are being loaded in the background, if you select one or more episodes they are getting deselected as soon as more episodes load (in the background). It looks like the UI is unresponsive, but actually the selection is just getting removed every X seconds.

You're right, waiting until all the episodes are loaded works (it just takes a very long time for 27 seasons, between 2 and 3 minutes).

**Comment by eddywitkamp** [comment]
I agree. I came over from Sickbeard and SB is much faster in loading a large show.

**Comment by rafi-d** [comment]
>  setting the amount of rows per page to 50 kinda works (although with ~3 seconds lag when clicking on a checkbox)

Same here. I have also noticed FF/Vue briefly refreshing itself during this load process. 

Not sure if I should raise it here, but one more "glitch" with this "paging" , is that the last in page (with only partial list of episodes) show, has a wrong summery line at the bottom, as if it was a complete show. 
![Medusa_episodes_in_page_2019-12-27_210348](https://user-images.githubusercontent.com/2458280/71540217-4fbb0300-2950-11ea-8d31-ad4a1fc5c681.png)

**Comment by medariox** [comment]
Use pagination if it's too slow.
