### ISSUE TITLE
[APP SUBMITTED]: qBittorrent: Unable to set priority for Torrent

### ISSUE THREAD

**Issue by angrywar** [pymedusa/Medusa#7539]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.18362-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@d0c136d7a528a471b51676140bd35d24d97f65c6
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-12-29 19:19:49 ERROR    SNATCHQUEUE-SNATCH-161511 :: [d0c136d] qBittorrent: Unable to set priority for Torrent
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
#4032 was reintroduced because qBittorrent API v2 respondes with 409 rather than 403.

@angrywar 
Torrent queueing is probably disabled, see #4032.
It should not be an error, #7541 should fix this.
