### ISSUE TITLE
Season packs not getting pulled over episodes

### ISSUE THREAD

**Issue by jxer** [pymedusa/Medusa#7542]
Branch: masterCommit: d0c136d7a528a471b51676140bd35d24d97f65c6Version: 0.3.9Database: 44.14
--
Python Version: | 2.7.9 (default, Sep 14 2019, 20:00:08) [GCC 4.9.2]
SSL Version: | OpenSSL 1.0.1t 3 May 2016
OS: | Linux-3.16.0-10-amd64-x86_64-with-debian-8.11
Locale: | en_US.UTF-8

line 1687 seems interesting.
[lost in time debug.txt](https://github.com/pymedusa/Medusa/files/4011417/lost.in.time.debug.txt)

**Comment by medariox** [comment]
Unsupported Python version. Ignored issue template. No issue description. Closing.
