### ISSUE TITLE
tvchaosuk update

### ISSUE THREAD

**Issue by kevwiener** [pymedusa/Medusa#7556]
hi guys ive been led to believe that the issue with the tvchaosuj torrent site is a medusa issue is there any chance that we can get it fixed, since they did a new site update it hasnt worked at all :(

thanks
kevin

**Comment by medariox** [comment]
We need access to the provider the fix it.

**Comment by kevwiener** [comment]
no dramas let me know where to send an invite to :) then we can get the ball rolling :)

**Comment by p0psicles** [comment]
You can pm us on discord

**Comment by kevwiener** [comment]
you got a discord link for me and ill join :)

**Comment by p0psicles** [comment]
In the readme.md

**Comment by medariox** [comment]
Fixed.
