### ISSUE TITLE
[APP SUBMITTED]: InvalidShowException: Unable to match [JJCA].[480p].JoJo's.Bizarre.Adventure.-.Thus.Spoke.Kishibe.Rohan.Chapter.1:.Episode.#05.Millionaire.Village.V2 to a series in your database. Parser result: release_group: JJCA, screen_size: 480p, title: JoJo's Bizarre Adventure, alias: JoJo's Bizarre Adventure - Thus Spoke Kishibe Rohan Chapter 1: Episode, alternative_title: Thus Spoke Kishibe Rohan Chapter 1: Episode, episode: [], absolute_episode: [5], episode_title: Millionaire Village, version: 2, type: episode, parsing_time: 0.131064891815, total_time: 0.142404079437, quality: SDTV, season: None

### ISSUE THREAD

**Issue by VexingHex** [pymedusa/Medusa#7559]
### INFO
**Python Version**: `2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]`
**Operating System**: `Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@d0c136d7a528a471b51676140bd35d24d97f65c6
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-01-06 21:42:01 ERROR    SEARCHQUEUE-BACKLOG-262954 :: [Nyaa] :: [d0c136d] 262954: Multiple entries found in show: JoJo's Bizarre Adventure (2012) 
Traceback (most recent call last):
  File "/opt/**********/**********/providers/generic_provider.py", line 282, in find_search_results
    search_result.name)
  File "/opt/**********/**********/name_parser/parser.py", line 392, in parse
    self.assert_supported(result)
  File "/opt/**********/**********/name_parser/parser.py", line 409, in assert_supported
    'Parser result: {result}'.format(result=result))
InvalidShowException: Unable to match [JJCA].[480p].JoJo's.Bizarre.Adventure.-.Thus.Spoke.Kishibe.Rohan.Chapter.1:.Episode.#05.Millionaire.Village.V2 to a series in your database. Parser result: release_group: JJCA, screen_size: 480p, title: JoJo's Bizarre Adventure, alias: JoJo's Bizarre Adventure - Thus Spoke Kishibe Rohan Chapter 1: Episode, alternative_title: Thus Spoke Kishibe Rohan Chapter 1: Episode, episode: [], absolute_episode: [5], episode_title: Millionaire Village, version: 2, type: episode, parsing_time: 0.131064891815, total_time: 0.142404079437, quality: SDTV, season: None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by LaChocola** [comment]
Is there not a fix to have this not appear as in error in my logs? Don't know what caused it or what I need to do to mitigate the issue

**Comment by VexingHex** [comment]
Can I ask why it was closed without comment, or what is causing this? I dont know what it is that needs to be done to resolve it, and havent seen the issue posted in the issues before, so if you know the fix, please let me know

**Comment by medariox** [comment]
Duplicate of https://github.com/pymedusa/Medusa/issues/7558

**Comment by VexingHex** [comment]
oh, didn't realize it uploaded them as 2 separate errors. I thought they came in as one. My bad. 😅
