### ISSUE TITLE
[Feature Request]  Option not to update ended shows every night.

### ISSUE THREAD

**Issue by papampi** [pymedusa/Medusa#7561]
I asked this when I was using sickchill, now I'm asking it for Medusa ...

Please add an option not to update ended shows every night.
Most of us have many ended shows in our libraries so checking and updating them every night is a waste of resource.

Please consider it.

**Comment by p0psicles** [comment]
Opposed to sickchill we only update when a show is reported changed by the indexer

**Comment by p0psicles** [comment]
So I don't it has updated old ended shows for you recently

**Comment by papampi** [comment]
Then its not needed, I thought its like sickchill that update all shows every night.
Then its not needed.

**Comment by p0psicles** [comment]
We're even more efficient then that. If only changes have been made to a specific season. Only that season is updated.

**Comment by papampi** [comment]
Thats amazing.
