### ISSUE TITLE
Searching for a show with all indexers fails when one indexer timesout

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#7567]
**Describe the bug**
Searching with "all indexers" fails if any of them timeout.

**To Reproduce**
Add a show while tvdb is having issues with "all indexers" selected.

**Expected behavior**
The indexers the didn't fail should have their results returned.

Related: https://github.com/pymedusa/Medusa/issues/7565

**Comment by eddywitkamp** [comment]
I reproduced it searching for the show "You".
When All Indexers is used, I get "Search timed out, try again or try another indexer"
If I just use TVDBv2, it works fine.

**Comment by medariox** [comment]
The timeout is a different issue.

This is fixed with https://github.com/pymedusa/Medusa/pull/7823
