### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Total Variety Network

### ISSUE THREAD

**Issue by IanKBrown** [pymedusa/Medusa#7587]
### INFO
**Python Version**: `2.7.10 (default, Aug 19 2015, 09:18:54) [GCC 4.6.3]`
**Operating System**: `Linux-4.14.x-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@942040af95311a71d9663236c7136434b6711ca5
**Link to Log**: https://gist.github.com/bedeed8e865b90bf9de5d60f825cfc28
### ERROR
<pre>
2020-01-14 22:03:07 ERROR    Thread_1 :: [942040a] Missing time zone for network: Total Variety Network
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
[Present in the list](https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L2397)
Issue can be closed.
