### ISSUE TITLE
UNABLE TO CONNECT your_ip:8081

### ISSUE THREAD

**Issue by ZMOT7S** [pymedusa/Medusa#7590]
I've recently went to linux (ubuntu 18.04) since windows 7 is ending. I had a full setup on Win7 including medusa, which I prefer to sonarr. I'm having trouble getting it setup on linux. Everything installed fine and "systemctl status medusa" shows loaded and no errors but I can't connect to myIP:8081 or localhost:8081. I even allowed 8081 in and out of the firewall. If I run "netstat -tulpn" I do NOT see medusa listed for any port. 

I'm also unsure of where the logs are for medusa, I'm new to linux and don't really know how to navigate the file system yet. I will post them if someone can point me in the right direction. Let me know if you need anymore info. 

Ubuntu 18.04 LTS
Python 3.6.9
Ran sudo apt update and upgrade

**Comment by etienne954** [comment]
Hi everyone,

Same issue here with a raspberry pi 2 running xbian. Yesterday I followed this procedure and everything went well : https://github.com/pymedusa/Medusa/wiki/Medusa-installation-Debian-Ubuntu.

Have a nice day

**Comment by medariox** [comment]
Does it work if you run Medusa directly?
`sudo -u medusa /usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa`
?

**Comment by etienne954** [comment]
Nop. This command gives me this : 

```
xbian@xbian ~ $ sudo -u medusa /usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa
Sorry, requires Python 2.7.x or Python 3.5 and above
```
But what is strange is that current version of Python is 2.7.9 

```
xbian@xbian ~ $ python -V
Python 2.7.9
```

**Comment by medariox** [comment]
We don't support such an old Python version, see: https://github.com/pymedusa/Medusa#dependencies
Although we do still support Python 2.7.10+ for now, I highly recommend to switch to Python 3.5.2+ as Python 2.7 is already EOL! In our Wiki you can find many guides on how to make the switch: https://github.com/pymedusa/Medusa/wiki

**Comment by ZMOT7S** [comment]
I did a full reinstall and the webui is available now.
