### ISSUE TITLE
Daily Search and Backlog Search page-bottom summary shows ??:??:??

### ISSUE THREAD

**Issue by mmhere** [pymedusa/Medusa#7602]
### Daily Search and Backlog Search page-bottom summary shows ??:??:??

**To Reproduce**
Simply load up the home page or in this case the Schedule page;  look at the status line at the bottom.

**Expected behavior**
Time remaining to next Daily and Backlog searches should be displayed.

**Screenshots**
Present..

**Medusa (please complete the following information):**
Medusa Info:	Branch: master 
Commit: 942040af95311a71d9663236c7136434b6711ca5 
Version: 0.3.10 
Database: 44.14
 Python Version:	2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
 SSL Version:	OpenSSL 1.0.2g 1 Mar 2016
 OS:	Linux-4.4.0-78-generic-x86_64-with-Ubuntu-16.04-xenial
 Locale:	en_US.UTF-8

**Debug logs (at least 50 lines):**
Cannot see anything relevant in the log;  debug is enabled.  I can search for something

Here is a tiny screen grab of the relevant line.  This happens to be in Vivaldi (browser):

![x](https://user-images.githubusercontent.com/16172883/72705344-18cfab80-3b10-11ea-90c7-f5af489784a2.png)

---

I hope this isn't a dupe.  I did search but it is a bit hard to search properly for `??:??:??`;  also the terms "Daily Search:" and "Backlog Search:" are quite generic within the issues present here.

**Comment by sharkykh** [comment]
Can you open up the Developer console (F12), refresh the page, and paste the logs from there?
If there are errors, then that's the issue.
If there aren't any errors, maybe the daily search and backlog search threads aren't running for some reason.

**Comment by mmhere** [comment]
This while the http://hostname/config/ route was displayed, opening Developer page, switching to Console tab, then F5 refreshing the /config/ page.  Is this the log you wanted?
```
TypeError: String(...).padStart is not a function
    at a (app-footer.vue:102)
    at a.formatTimeDuration (app-footer.vue:104)
    at a.schedulerNextRun (app-footer.vue:83)
    at a.<anonymous> (app-footer.vue?494d:1)
    at a.e._render (vue.esm.js:3551)
    at a.i (vue.esm.js:4069)
    at gn.get (vue.esm.js:4482)
    at gn.run (vue.esm.js:4557)
    at hn (vue.esm.js:4313)
    at Array.<anonymous> (vue.esm.js:1989)
Ge	@	vue.esm.js:1897
We	@	vue.esm.js:1888
qe	@	vue.esm.js:1848
e._render	@	vue.esm.js:3553
i	@	vue.esm.js:4069
gn.get	@	vue.esm.js:4482
gn.run	@	vue.esm.js:4557
hn	@	vue.esm.js:4313
(anonymous)	@	vue.esm.js:1989
Xe	@	vue.esm.js:1915
vue.esm.js:1897 TypeError: String(...).padStart is not a function
    at a (app-footer.vue:102)
    at a.formatTimeDuration (app-footer.vue:104)
    at a.schedulerNextRun (app-footer.vue:83)
    at a.<anonymous> (app-footer.vue?494d:1)
    at a.e._render (vue.esm.js:3551)
    at a.i (vue.esm.js:4069)
    at gn.get (vue.esm.js:4482)
    at gn.run (vue.esm.js:4557)
    at hn (vue.esm.js:4313)
    at Array.<anonymous> (vue.esm.js:1989)
Ge	@	vue.esm.js:1897
We	@	vue.esm.js:1888
qe	@	vue.esm.js:1848
e._render	@	vue.esm.js:3553
i	@	vue.esm.js:4069
gn.get	@	vue.esm.js:4482
gn.run	@	vue.esm.js:4557
hn	@	vue.esm.js:4313
(anonymous)	@	vue.esm.js:1989
Xe	@	vue.esm.js:1915
```

Also, here is the current configuration, as I switched to python3.5--

```
 Medusa Info:	Branch: master 
Commit: 942040af95311a71d9663236c7136434b6711ca5 
Version: 0.3.10 
Database: 44.14
 Python Version:	3.5.8 (default, Jan 20 2020, 17:29:22) [GCC 4.9.2]
 SSL Version:	OpenSSL 1.0.1k 8 Jan 2015
 OS:	Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
 Locale:	en_US.UTF-8
```

**Comment by mmhere** [comment]
Note that originally I was running on an Ubuntu 16.04 desktop (same issue), but the above is on the server I settled upon that runs it normally.  The server is old (Debian 8.2 Jessie), but otherwise has up to date(ish) Python 3.5(.8).

**Comment by sharkykh** [comment]
Yes, this is the log.
It's not related to the server running Medusa, it's actually Vivaldi.
Looks like it's using an outdated version of Chromium, and it's missing one of the newer (not THAT new, though) JavaScript features.
`TypeError: String(...).padStart is not a function`

IMHO, I think the Vivaldi devs should update their browser. I could replace `padStart` but it's just bound to happen again someplace else. Again, because it's not *that* new of a feature, and all the latest versions of the major browsers support it.

P.S. Medusa officially only supports the following browsers (and versions):
https://github.com/pymedusa/Medusa/blob/1d9be6339e8892bb07aed16082a9428cd9da5fba/themes-default/slim/babel.config.js#L6-L13

That doesn't mean that other browsers won't work at all, just that our support for them is limited.
And this issue is a prime example why...

**Comment by mmhere** [comment]
Thank you for inspecting the results.  I'm sure the latest Vivaldi uses a newer chromium;  I'm running an older version of Vivaldi.  No need to ping the Vivaldi devs or consider Vivaldi generally unsupported.

I can confirm that if I temporarily notch out the use of .padStart() things display, although minutes and seconds do not have the requisite leading zero when their value is a single digit.

A quick hack from this in `medusa-runtime.js`:
```
String(e).padStart(t, "0")
```
to this:
```
String(e)
```

proves the point.  (That was just an exercise to ensure that otherwise the timer values being dug up are actually correct, which they are.)

---

I would humbly request, however, that maybe the JS used be made more compatible?  Wouldn't one want to support as many browsers as possible?  Prefixing a minutes or hours value with a leading zero has been done for quite some time via means that predate .padStart().  Just my humble opinion.

On the same machine, I confirmed that a different browser (happens to be a more recent version of google-chrome, and this is on Linux/Ubuntu) does display things properly with the released `medusa-runtime.js`.

**Comment by mmhere** [comment]
I can also confirm that `http://medusahost:8081/home/status/` displays the correct info.  This confirms that at least the data is being propagated out to the GUI presentation layer.  Heh:  Maybe I'll write a compact little desktop widget to use the APIs to extract the relevant info.  This would save me from having to scroll to the bottom of whatever page I'm presently viewing.

Note as an aside that the Vue (<) (>) (^) floater arrows in the bottom right-hand corner present on most pages often obscure the Daily Search and Backlog Search text anyway...

**Comment by medariox** [comment]
The problem is where do we start and where do we stop? I'm sure an user wanting to use IE 10 could bring similar arguments. Is there a reason for not updating your browser? We just can't keep up with the amount of browsers/engines, I hope you understand.

**Comment by mmhere** [comment]
I would say go ahead and Close this issue.  Thanks for listening!
