### ISSUE TITLE
New show searches fail

### ISSUE THREAD

**Issue by HeroesDieYoung** [pymedusa/Medusa#7604]
Medusa has for some time now not been able to search for new shows.  In the UI it reports that a 500 error occurred, logs copied below.

I've made sure my copy is the latest available from GitHub, and I'm running Medusa with Python 2.7.17 on a CentOS 7.4 server.

> 2020-01-20 15:58:45 WARNING  APIv2-Thread_29 :: [942040a] could not connect to TheTvdb.com, with reason 'IndexerAuthFailed(u'Authentication failed, possible bad API key. Reason: HTTPError\n401 Client Error: Unauthorized for url: https://api.thetvdb.com/search/series?name=picard (401)',)'
> 2020-01-20 15:58:45 WARNING  APIv2-Thread_29 :: [942040a] Enabling Plex fallback as TheTvdb.com API is having some connectivity issues
> 2020-01-20 15:58:46 INFO     APIv2-Thread_29 :: [942040a] Error searching for show. term(s): [u'Picard'] indexer: tvdb error: Authentication failed, possible bad API key. Reason: HTTPError
> 401 Client Error: Unauthorized for url: https://tvdb2.plex.tv/search/series?name=picard (401)
> 2020-01-20 15:58:46 ERROR    APIv2-Thread_29 :: [942040a] Internal Error searching for show. term(s): [u'Picard'] indexer: tvmaze error: Expecting value: line 1 column 1 (char 0)
> Traceback (most recent call last):
>   File "/home/myuser/Medusa/medusa/server/api/v2/internal.py", line 202, in resource_search_indexers_for_show_name
>     indexer_results = indexer_api[search_term]
>   File "/home/myuser/Medusa/medusa/indexers/indexer_base.py", line 404, in __getitem__
>     selected_series = self._get_series(key)
>   File "/home/myuser/Medusa/medusa/indexers/indexer_base.py", line 158, in _get_series
>     all_series = self.search(series)
>   File "/home/myuser/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 189, in search
>     results = self._show_search(series, request_language=self.config['language'])
>   File "/home/myuser/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 166, in _show_search
>     results = self.tvmaze_api.get_show_list(show)
>   File "/home/myuser/Medusa/lib/pytvmaze/tvmaze.py", line 968, in get_show_list
>     shows = self.show_search(show_name)
>   File "/home/myuser/Medusa/lib/pytvmaze/tvmaze.py", line 985, in show_search
>     q = self._endpoint_standard_get(url)
>   File "/home/myuser/Medusa/lib/pytvmaze/tvmaze.py", line 548, in _endpoint_standard_get
>     results = r.json()
>   File "/home/myuser/Medusa/ext/requests/models.py", line 897, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/home/myuser/.local/lib/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
>     return _default_decoder.decode(s)
>   File "/home/myuser/.local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
>     obj, end = self.raw_decode(s)
>   File "/home/myuser/.local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2020-01-20 15:58:46 ERROR    TORNADO :: [942040a] Uncaught exception in APIv2: JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)
> Request: GET /api/v2/internal/searchIndexersForShowName?query=Picard&indexerId=0&language=en (47.206.93.59)
> Traceback (most recent call last):
>   File "/home/myuser/Medusa/ext/tornado/web.py", line 1592, in _execute
>     result = yield result
>   File "/home/myuser/Medusa/ext/tornado/gen.py", line 1133, in run
>     value = future.result()
>   File "/home/myuser/Medusa/ext/tornado/concurrent.py", line 261, in result
>     raise_exc_info(self._exc_info)
>   File "/home/myuser/Medusa/ext/tornado/gen.py", line 1141, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/home/myuser/Medusa/medusa/server/api/v2/base.py", line 79, in async_call
>     content = yield tornado_future
>   File "/home/myuser/Medusa/ext/tornado/gen.py", line 1133, in run
>     value = future.result()
>   File "/home/myuser/Medusa/ext/tornado/concurrent.py", line 261, in result
>     raise_exc_info(self._exc_info)
>   File "/home/myuser/Medusa/medusa/server/api/v2/base.py", line 70, in wrapper
>     result = method(*args, **kwargs)
>   File "/home/myuser/Medusa/medusa/server/api/v2/internal.py", line 55, in get
>     return resource_function()
>   File "/home/myuser/Medusa/medusa/server/api/v2/internal.py", line 192, in resource_search_indexers_for_show_name
>     indexer_api = indexer_instance.indexer(**custom_api_params)
>   File "/home/myuser/Medusa/medusa/indexers/tvdbv2/fallback.py", line 58, in __call__
>     return self.func(*args, **kwargs)
>   File "/home/myuser/Medusa/medusa/indexers/indexer_api.py", line 26, in indexer
>     indexer_obj = indexerConfig[self.indexer_id]['module'](*args, **kwargs)
>   File "/home/myuser/Medusa/medusa/indexers/tmdb/tmdb.py", line 46, in __init__
>     self.response = self.tmdb_configuration.info()
>   File "/home/myuser/Medusa/lib/tmdbsimple/configuration.py", line 39, in info
>     response = self._GET(path, kwargs)
>   File "/home/myuser/Medusa/lib/tmdbsimple/base.py", line 85, in _GET
>     return self._request('GET', path, params=params)
>   File "/home/myuser/Medusa/lib/tmdbsimple/base.py", line 82, in _request
>     return response.json()
>   File "/home/myuser/Medusa/ext/requests/models.py", line 897, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/home/myuser/.local/lib/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
>     return _default_decoder.decode(s)
>   File "/home/myuser/.local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
>     obj, end = self.raw_decode(s)
>   File "/home/myuser/.local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by medariox** [comment]
It's a temporary TheTVDB API issue, it will be fixed. There is nothing we can do about, just have to wait.

**Comment by HeroesDieYoung** [comment]
Seems like it's been several weeks at least already, do you happen to have a link to an issue they're tracking so I can follow it?  I could separate the different log outputs from the three different search providers if it would help, but when I go through each of TMDB, TVDBv2, and TVaaze individually all three result in different errors included in my log output above.  Surely all three of them aren't having simultaneous API bugs?

**Comment by medariox** [comment]
No, I don't have any any tracking issue. Apparently you have simplejson installed, try to uninstall it.

**Comment by HeroesDieYoung** [comment]
The docs claim medusa works for python 2.7.10+, so I had it running with 2.7.17 and expected it to work there.  Uninstalling the simplejson package would interfere with other python software I'm running, so instead I did a side-by-side installation of python 3.6.8 and ran Medusa with that version.  After that all three show searching engines are working fine.  I also have the simplejson package installed for python3 (it was installed by default with the main package), so it doesn't appear to cause any issue.
