### ISSUE TITLE
[APP SUBMITTED]: Unable to create the folder /media/plexdrive/Video/Series/El tiempo de la felicidad, can't add the show

### ISSUE THREAD

**Issue by pucelano7** [pymedusa/Medusa#7615]
### INFO
**Python Version**: `3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]`
**Operating System**: `Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@942040af95311a71d9663236c7136434b6711ca5
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-01-21 10:23:02 ERROR    Thread_15 :: [942040a] Unable to create the folder /media/plexdrive/Video/Series/El tiempo de la felicidad, can't add the show
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Connection or permission issue.
