### ISSUE TITLE
Show Root Directory (`#showRootDir`) selection does not populate on the home page sometimes

### ISSUE THREAD

**Issue by below9k** [pymedusa/Medusa#7621]
The show root directory selection does not populate sometimes.

**To Reproduce**
1. Navigate to home
2. Select a root directory from the selection
3. Repeat step2 until it doesn't load
4. Notice no selection is displayed (no options in the select element)

**Expected behavior**
Selection loads every time

**Screenshots**
Screenshot is after I have selected a root directory and can no longer see the selection
![Screen Shot 2020-01-23 at 12 16 18 PM](https://user-images.githubusercontent.com/6232236/73011912-da214600-3dda-11ea-90fb-cc0d9352dfda.png)

**Medusa Info:**
Branch: master
Commit: 942040af95311a71d9663236c7136434b6711ca5
Version: 0.3.10
Database: 44.14
Python Version: 2.7.12 (default, Oct 8 2019, 14:14:10) [GCC 5.4.0 20160609]
SSL Version: OpenSSL 1.0.2g 1 Mar 2016
OS: Linux-4.15.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: en_US.UTF-8

**Additional context**
The problem is intermittent; seems like a race condition. Changing routes and navigating back seems to be the best solution, but that isn't foolproof.

Edit 10/02/2020: The "All Folders" page always loads the selection for me

**Comment by below9k** [comment]
Got tired of refreshing 10mil times trying to get the drop down, so I dug through the code n found `window.api` is exposed.
Running:
```api.patch('config/main', {
    selectedRootIndex: -1
})``` in console gets me back to "All Folders"

**Comment by p0psicles** [comment]
I know. It will be fixed when I'm getting back at the home page vueify pr. So it's wip

**Comment by gitowok** [comment]
Another data point. For me the dropdown never populates, so I cant see nor select a folder. Its stuck on an invisible "All Folders" for me, with no dropdown at all exactly like below9k's screenshot. If I run the api.patch that below9k posted in the console (with any value of selectedRootIndex), I get:
Promise { <state>: "pending" }

**Comment by p0psicles** [comment]
I have it fixed. Will be merged once these days to develop

**Comment by gitowok** [comment]
confirmed 100% fixed for me in latest update.  Many thanks!
