### ISSUE TITLE
Server status shows all False

### ISSUE THREAD

**Issue by aiiDaH** [pymedusa/Medusa#7625]
Im running  NAS asustor AS5202T

with clinton-hall custom made Medusa
https://www.dropbox.com/s/2cc4vs1j595kunp/medusa_20191114_any.apk?dl=0

Here is how it looks for me 
https://imgur.com/8IWn0KQ

Medusa
Branch: master 
Commit: 8b7f433d4dce89058a8b9b62cc9bcd7a162a3344 
Version: 0.3.8 

@p0psicles any idea whats wrong?

**Comment by medariox** [comment]
I know what's wrong! You are running an old version, this is fixed in the newest release.

**Comment by aiiDaH** [comment]
> I know what's wrong! You are running an old version, this is fixed in the newest release.

@medariox how can I update it

im trying to press "Check for update" but nothing happens and when I check log I get this

2020-01-24 21:47:30 WARNING  CHECKVERSION :: [8b7f433] git fetch --prune origin returned : error: object file .git/objects/ad/3c38d6ecd1135865e079b4305630c534fd0005 is empty
fatal: cannot read existing object info ad3c38d6ecd1135865e079b4305630c534fd0005
fatal: index-pack failed

2020-01-24 21:47:30 WARNING  CHECKVERSION :: [8b7f433] Unable to contact github, can't check for update

How can I fix this ?

**Comment by medariox** [comment]
You probably need to ask the maintainer to update it.

**Comment by p0psicles** [comment]
It's the package of Clinton Hall. It should update through git. But for some reason that update failed

**Comment by aiiDaH** [comment]
> It's the package of Clinton Hall. It should update through git. But for some reason that update failed

yes, any idea how I can fix this @p0psicles
