### ISSUE TITLE
Medusa search torrents Fiance instead of Fiancé

### ISSUE THREAD

**Issue by txbut** [pymedusa/Medusa#7632]
90 Day Fiancé is what's grabbed by TBDB2, TMBD, TVMaze in Medusa. They don't pick up 90 Day Fiance.

How to I get Medusa to search torrents Fiance instead of Fiancé?
I tried ignored and required words a couple ways w/ no luck but got a Warning.

2020-01-27 23:06:44 WARNING  POSTPROCESSOR :: [942040a] D:\blablabla\finished-tv\90.Day.Fiance.S07E12.WEBRip.x264-TBS[rarbg]\90.day.fiance.s07e12.webrip.x264-tbs.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode

Thank you!

**Comment by medariox** [comment]
Add `Fiance` as scene exception for that show.

**Comment by wseedbox** [comment]
FWIW, I can't get this to work by adding "Fiance" to the scene exception.  I'm trying to add 90 day fiance pillow talk.  I've found the show on trackers, but it's not working in Medusa.

I'm not sure what i'm doing wrong....

**Comment by medariox** [comment]
Looks like the show is being released as `90 Day Fiance`, so that's what you should add as scene exception.

**Comment by wseedbox** [comment]
@medariox  Seriously, thank you so much for taking the time to figure this out and responding. 

I tested this out.  I was targeting the pillow talk version.  

By adding scene exception "90 day fiance" returned way too much.  It returned regular 90 day fiance, the before the 90 days version, and the pillow talk.

I added "90 day fiance pillow talk" and that worked.
