### ISSUE TITLE
[Support] push notifications (and SSL required?)

### ISSUE THREAD

**Issue by mmhere** [pymedusa/Medusa#7657]
(Please redirect me if there is a more appropriate location.)

What do I need to do to enable SSL on the Medusa side so later browsers will accept push notifications?  Perhaps there is a ReadMe somewhere?

My older version (of Vivaldi) is happy to receive push notifs from Medusa's http interface, but newer browsers (Firefox included) seem to require https access to the server.  I don't really need https because everything happily runs on my internal LAN.  From what I can research, however, it seems most current browsers just won't allow push notif from http pages, even if they are local.

I did pip3 install pyopenssl, which gets me part way there (no more log warning about that module not available), but Medusa refuses to start after I enabled the "Use https" toggle on the Configuration "Interface" page.

Do I have to go to some cert authority to generate key files?

Or, and this is really a browser question, can you tell the browser(s) to make exceptions for favoured http sites?

**Comment by medariox** [comment]
If you check your log files it should tell you more about why it's not starting. Eventually you can also enable the HTTP logging. Also, maybe related: https://github.com/pymedusa/Medusa/issues/7562
