### ISSUE TITLE
Network icons missing on main show list - Apple TV+ and Shudder

### ISSUE THREAD

**Issue by PinaColonic** [pymedusa/Medusa#7667]
**Describe the bug**

On the main Show List Medusa screen I have a show called Creepshow on the Shudder network, and also a show called Mythic Quest: Raven's Banquet which both have a ? icon showing instead of a normal network icon.

**To Reproduce**

Add those TV shows from TVDB2.

**Expected behavior**
Show the network icons normally on the Show List screen (main screen listing all the different shows that have been added to Medusa) - these icons probably haven't been created yet - but Apple TV+ is probably going to be pretty big as more and more shows are created so should be added, even if Shudder is more of a "fringe" network.

**Screenshots**
Can be provided if necessary.

**Medusa (please complete the following information):**
 Linux Mint 19.3
Branch: master
Commit: 942040af95311a71d9663236c7136434b6711ca5
Version: 0.3.10
Database: 44.14

Python Version: | 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
-- | --

SSL Version: | OpenSSL 1.1.1  11 Sep 2018
-- | --

OS: | Linux-4.15.0-76-generic-x86_64-with-LinuxMint-19.3-tricia
-- | --

**Comment by medariox** [comment]
Added with: https://github.com/pymedusa/Medusa/pull/7673
