### ISSUE TITLE
Medusa does not start after upgrade

### ISSUE THREAD

**Issue by jery19** [pymedusa/Medusa#7677]
pi@raspstor:/opt/medusa $ /usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa
Traceback (most recent call last):
  File "/opt/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/opt/medusa/medusa/providers/__init__.py", line 13, in <module>
    from medusa.providers.nzb import (
  File "/opt/medusa/medusa/providers/nzb/anizb.py", line 13, in <module>
    from medusa.providers.nzb.nzb_provider import NZBProvider
  File "/opt/medusa/medusa/providers/nzb/nzb_provider.py", line 9, in <module>
    from medusa.providers.generic_provider import GenericProvider
  File "/opt/medusa/medusa/providers/generic_provider.py", line 18, in <module>
    from medusa import (
  File "/opt/medusa/medusa/config.py", line 35, in <module>
    from medusa.updater.version_checker import CheckVersion
  File "/opt/medusa/medusa/updater/version_checker.py", line 17, in <module>
    from medusa.updater.docker_updater import DockerUpdateManager
  File "/opt/medusa/medusa/updater/docker_updater.py", line 9, in <module>
    from medusa.updater.source_updater import SourceUpdateManager
  File "/opt/medusa/medusa/updater/source_updater.py", line 11, in <module>
    from github import GithubException
ModuleNotFoundError: No module named 'github'

Do I miss a requirement ?

**Comment by medariox** [comment]
Kind of hard to help without any kind of needed information, but normally this is caused by updating manually and having `.pyc` files lying around. You can run this from Medusa's main dir (`opt/medusa`) and it should work again afterwards: `find . -name '*.pyc' -delete`

**Comment by jery19** [comment]
Just tried removing .pyc files with same result.  I am not a dev so I would need guidance on how to give you more debug information.  I posted what happens when I manually try to start Medusa.  When running the service the status is ok, but the page does not load.

pi@raspstor:/opt/medusa $ sudo service medusa status
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-01-31 11:28:13 EST; 497ms ago
 Main PID: 13291 (python3)
    Tasks: 1 (limit: 4915)
   Memory: 8.7M
   CGroup: /system.slice/medusa.service
           └─13291 /usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa

Jan 31 11:28:13 raspstor systemd[1]: Started Medusa Daemon.

That is where I tried running it manually and got error on initial post.

**Comment by medariox** [comment]
Stop the service.

Try to run with: 1/usr/bin/python3 /opt/medusa/start.py --datadir=/opt/medusa1
directly. See if that works.

Btw, it has nothing to do with being a dev, we have an [issue template](https://github.com/pymedusa/Medusa/issues/new?template=bug_report.md) and you chose to ignore it for some reason.

**Comment by jery19** [comment]
pi@raspstor:/opt/medusa $ /usr/bin/python3 /opt/medusa/start.py --datadir=/opt/medusa
Traceback (most recent call last):
  File "/opt/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/opt/medusa/medusa/providers/__init__.py", line 13, in <module>
    from medusa.providers.nzb import (
  File "/opt/medusa/medusa/providers/nzb/anizb.py", line 13, in <module>
    from medusa.providers.nzb.nzb_provider import NZBProvider
  File "/opt/medusa/medusa/providers/nzb/nzb_provider.py", line 9, in <module>
    from medusa.providers.generic_provider import GenericProvider
  File "/opt/medusa/medusa/providers/generic_provider.py", line 18, in <module>
    from medusa import (
  File "/opt/medusa/medusa/config.py", line 35, in <module>
    from medusa.updater.version_checker import CheckVersion
  File "/opt/medusa/medusa/updater/version_checker.py", line 17, in <module>
    from medusa.updater.docker_updater import DockerUpdateManager
  File "/opt/medusa/medusa/updater/docker_updater.py", line 9, in <module>
    from medusa.updater.source_updater import SourceUpdateManager
  File "/opt/medusa/medusa/updater/source_updater.py", line 11, in <module>
    from github import GithubException
ModuleNotFoundError: No module named 'github'

**Comment by jery19** [comment]
- OS: Raspbian Buster
 - Branch: master
 - Commit: Good question, but it installed about 30 min. ago.
 - Python version: Python 3.7.3
 - Database version: most update file in directory is 44.13

**Comment by medariox** [comment]
How did you update? Are you using git? Some files seem to be missing from your install.

**Comment by jery19** [comment]
I used the link inside Medusa to install.  And got the error.  This is where this all started.
After, I tried a git pull and got a result of "Already up to date".

**Comment by medariox** [comment]
That usually means that something broke during the update process:
Run:
```
git fetch origin
git reset --hard origin/master
```
From Medusa's main dir.

**Comment by jery19** [comment]
This is a fresh install I did last week when I upgraded my Pi3 to a Pi4.
I started brand new from a Raspbian Lite (my Pi3 was on the full build).
So that is why I first asked if I had a required component missing.

**Comment by medariox** [comment]
Medusa ships with all required libraries, it only needs Python.

**Comment by jery19** [comment]
Works now after git reset.

**Comment by jery19** [comment]
Can I help in any way to diagnose if the issue was my environment or if there was a problem with the update process ?

**Comment by medariox** [comment]
Great. Something broke during your update (e.g. RPi shut down, restarted, internet broke for a moment), it's not an issue with the update process.

**Comment by jery19** [comment]
Ok great.  thanks for your help.
