### ISSUE TITLE
Adding episodes to WANTED status, no backlog files are added.

### ISSUE THREAD

**Issue by kamshaft** [pymedusa/Medusa#7689]
When I select an episode to switch to the status to wanted and click go, Nothing happens.
If I click on manual search, and click the icon to grab it, it works.

**To Reproduce**
1. Find an episode to switch to WANTED status.
2. Click on the left checkbox.
3. Scroll to the top to switch the status to wanted
4. Click go.
5. Popup asked to add it to the backlog
6. Everything goes back the list and nothing changes and nothing is added to the backlog.

**Expected behavior**
I expect the file to be added to the back log and a download to start eventually if the file exists.

**Medusa (please complete the following information):**
 - OS: Linux-5.3.0-29-generic-x86_64-with (docker)
 - Branch: master
 - Commit: Unknown
 - Python version: 3.8.1
 - Database version: Database: 44.14

**Debug logs (at least 50 lines):**
Nothing shows up in the logs.

NOTE: IN the backlog Overview.  Where it says jump to show, nothing is there.

**Comment by medariox** [comment]
It won't start a backlog if you already have the desired quality, if that's what you mean.

**Comment by kamshaft** [comment]
I guess ya.  What I'm I supposed to do?  By default when I add a new that is already in progress.  They are all skipped.  If I want that particular episode, putting the checkbox and steps above does nothing.  Do I need to do this in a different way?  When I had Sick Beard that's I grabbed back episodes.

**Comment by medariox** [comment]
Hard to say. It obviously works fine here. What about debug logs? What browser are you using? Maybe post screenshots?

**Comment by kamshaft** [comment]
1. My Backlog Overview is completely empty, where it should have the episodes I've tagged wanted, should go in there right?
2. I tried Chrome and Firefox, same behavior.
3. Screenshots not much to post. lol
![image](https://user-images.githubusercontent.com/19599741/73700307-3a09cd80-46b4-11ea-8cbf-08e78c70a215.png)
![image](https://user-images.githubusercontent.com/19599741/73700333-4726bc80-46b4-11ea-9a60-b41bfe02a0fa.png)
Then nothing happens.

**Comment by medariox** [comment]
Can't really help without debug logs. Maybe you're using an old browser version? Anything block JavaScript in your browser?

**Comment by kamshaft** [comment]
Just tried all this on my iphone and ipad, and it works within Safari and Chrome!  Strange...  So, It's clearly a browser issue.  However, javascript is not disabled on there.  I'm do some closer investigations, and report back here to share my findings.

**Comment by kamshaft** [comment]
Well I have news.  Turns out it was the Web Filtering in my local anti-virus (Vipre).  Turned that off and voila, all is good.  What a weird isolated issue, remember kids check that darn anti-virus!
