### ISSUE TITLE
Unable to match episodes in one specific show

### ISSUE THREAD

**Issue by ygaeon** [pymedusa/Medusa#7710]
**Describe the bug**
Unable to match the episodes of the show "Around the world in 80 days" (tvdbid 84583).
The matcher seems to get confused with "80" in the name and match up "episode 80" even when the filename is "S01E05..."
I've tried renaming the files to include show name and without.
I've tried removing all meta data files and do a full update.
I've tried remove show and add it again.
Still, doesn't match up correctly.

Researching this further, it seems that it matches the "80" in the directory name and interpret that as "episode". A fix shouldn't be too hard :-)
(see debug log excerpt below)

**To Reproduce**
Show folder name "Michael Palin (1989) Around The World in 80 Days".
Season folder name "Season 01"
File names:
```
S01E01 - The Challenge.avi
S01E02 - Arabian Frights.avi
S01E03 - Ancient Mariners.avi
S01E04 - A Close Shave.avi
S01E05 - Oriental Express.avi
S01E06 - Far East and Farther East.avi
S01E07 - Dateline To Deadline.avi
```
Add show and see it not match the correct episodes.

**Expected behavior**
Correct matching of the episodes.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
 - Branch: master
 - Commit: 9a36461
 - Python version: Python 3.6.5
 - Database version: (not sure how to find database version)

**Debug logs (at least 50 lines):**
<details>
```
2020-02-08 11:03:18 DEBUG    SHOWQUEUE-REFRESH :: [9a36461] Parsed /.../Michael Palin (1989) Around The World in 80 Days/Season 01/S01E01 - The Challenge.avi into title: Michael Palin, year: 1989, episode: [80], episode_title: Days, season: 1, container: avi, mimetype: video/x-msvideo, type: episode, parsing_time: 0.31182408332824707, absolute_episode: [], quality: Unknown, total_time: 0.31302738189697266
```
</details>

**Additional context**

**Comment by medariox** [comment]
> Researching this further, it seems that it matches the "80" in the directory name and interpret that as "episode". A fix shouldn't be too hard :-)

Sounds like you have the fix ready, feel free to push the PR whenever you feel like!
