### ISSUE TITLE
wrong posters (banners are correct)

### ISSUE THREAD

**Issue by cheese1** [pymedusa/Medusa#7718]
**Describe the bug**
where does medusa search for posters? i sometimes get mixed results (wrong posters). the banner seems to be correct, though.

**To Reproduce**
create show 'OZ'
thats series:
http://dereferer.org/?https://www.thetvdb.com/dereferrer/series/70682
the poster is wrong
the banner is correct

**Screenshots**

**Medusa (please complete the following information):**
 - OS: fedora
 - Branch: master 0.3.11
 - Commit: 942040af95311a71d9663236c7136434b6711ca5
 - Python version: 3.7.6-2
 - Database version: 44.14

**Comment by cheese1** [comment]
![Screenshot from 2020-02-08 19-33-30](https://user-images.githubusercontent.com/6437726/74090407-42467c00-4aab-11ea-8ae4-dcd3a50f456a.png)

**Comment by p0psicles** [comment]
So you have any posters in you shows download folder?

**Comment by cheese1** [comment]
in fact i have two files:
Oz.jpg and fanart.jpg
both downloaded from an old sickbeard-installation
both files are of the same size/date and show the same correct content
![fanart](https://user-images.githubusercontent.com/6437726/74104116-01ee0900-4b52-11ea-80d6-a26ef4f695d4.jpg)
![Oz](https://user-images.githubusercontent.com/6437726/74104120-031f3600-4b52-11ea-93ef-1f1c6decf546.jpg)

**Comment by cheese1** [comment]
another example: The 100
![Screenshot from 2020-02-09 16-09-42](https://user-images.githubusercontent.com/6437726/74104618-b12cdf00-4b56-11ea-848e-49052f525f2d.png)
again twice the same file fanart.jpg and The_100.jpg

**Comment by p0psicles** [comment]
Medusa gets these from tvdb api. Only thing I can think of is that there was an issue at tvdbs side.

**Comment by p0psicles** [comment]
Maybe remove show but keep data. And add again?

**Comment by medariox** [comment]
Probably somehow related to the fact that the language is not english.

**Comment by cheese1** [comment]
removed the show, renamed the directory.
did a fresh search (german): same result
did a fresh search (english): same result
the language should not be a factor here, as this is just for episode summaries, i assume.

then i found, that there is a picture-cache, which i never deleted. after deleting the correct files i got fresh ones from tvdb. and voila those were the correct ones.

maybe we should delete cache-files, if we delete a show.
