### ISSUE TITLE
[docs] Release 0.3.12 not marked in CHANGELOG.md

### ISSUE THREAD

**Issue by mmhere** [pymedusa/Medusa#7734]
My running instance of Medusa advised me there was an update to main.  Cool

This shows release 0.3.12...

https://github.com/pymedusa/Medusa/releases

...and yet this doesn't quite have the complete story (shows 0.3.11 as the "latest" with an "Unreleased" section at the top):

https://github.com/pymedusa/Medusa/blob/develop/CHANGELOG.md

Thought someone might want to sync those.

**Comment by sharkykh** [comment]
#7732
