### ISSUE TITLE
config.ini is being changed (resetted?)  Also feature request: backup configuration

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#7745]
For some unknown reason , I found the config.ini file completely changed, meaning all my changes/additions were gone. 

**To Reproduce**
Unknown. The only thing I can think of that I was accessing using  two PCs one local one remote.

**Screenshots**
I uploaded here  the before and after files (since I had a backup, and saved a copy)
[Config.zip](https://github.com/pymedusa/Medusa/files/4185455/Config.zip)

**Medusa (please complete the following information):**
 - OS: win10 1903
 - Branch: Master 3.10 

**Additional context**
I like to request a feature: make a backup copy of config.ini (maybe also main.db) every time medusa service starts. 

Thank you

**Comment by medariox** [comment]
This can simply not happen. Medusa will only create a new config.ini if it can't find an existing one. That's the only way. Also we don't provide support for custom/modified versions, because we can't guarantee their proper function. Please open a new issue for the feature request.

**Comment by rafi-d** [comment]
Yet it seems it did happen. I opened a feature request ticket - #7746 , thanks

**Comment by below9k** [comment]
I may be mistaken, but I think medusa (sickbeard) stores the config in memory and writes it back out on shutdown/restart. So if you made manual changes to /config.ini and then restart medusa, those changes will be lost.
If I am not mistaken, the only way, I would assume, to circumvent this is to kill the process via task manager or whatever.

**Comment by rafi-d** [comment]
> I may be mistaken, but I think medusa (sickbeard) stores the config in memory and writes it back out on shutdown/restart.

I hope you are mistaken, since config changes should be written as soon as they are being made...

Regardless, in my case the complete config seems to have been reverted to default (2 years of changes - lost...) .

**Comment by medariox** [comment]
It is written directly on save and is never deleted/resetted on it's own.

**Comment by rafi-d** [comment]
Here is my susspesion: one PC thought  there is no file since it could not open it for writing since the other PC had it locked open already... so, next thing it decided to over-write it with default ... 

Just speculating...

**Comment by below9k** [comment]
I was not mistaken. I did a quick test:
- edited the prop `backlog_frequency` to another value (`1440`, was originally `1080`)
- restart of medusa using systemd
- medusa came back online the value was `1080` again

This however does not explain how it was reset to default, unless you had a copy of medusa running on the default config settings then restarted the process.

**Comment by rafi-d** [comment]
I think the more relevant test would be to do some config change using medusa, and just view the file after...

**Comment by below9k** [comment]
> I think another relevant test would be to do some config change using medusa, and just view the file after...

Done.
The same change (`1080`->`1440`) to "Backlog search interval" was written immediately when using the UI

**Comment by jee-r** [comment]
It happened to me, too. No particular reasons, i just updated the `pymedusa/medusa:latest` docker's image. Strange bug 🤷

**Comment by rafi-d** [comment]
A strange side-effect (leftover?) is that in rare cases, custom qualities-lists (preferred, allowed) are being cleared, resulting in never snatching a show. This is easy to see in the show page - the top like showing the qualities is not there...

**Comment by p0psicles** [comment]
You'll have to debug that yourself. Quality is in the db. Not config.

**Comment by rafi-d** [comment]
> 
> 
> You'll have to debug that yourself. Quality is in the db. Not config.

OK, I accept the challenge...  :)  

I've debugged some more, and here is a way to reproduce the issue (see test-clip attached). 

Apparently, it looks like the refresh/display of the qualities tab-page it unstable, and the highlight-markings on custom qualities are not "sticky"... There are times, they are gone, so, if you move over to another tab in there (like in my test - advanced->Ignored words tab) , and make any kind of change and save it - it also saves the black (now invisible) qualities, and they are gone . You need to remember what they were, and reconfigure every one of them... :(

https://drive.google.com/file/d/1_QvX9lzIzkARPsLIGnObM9e3sYj3Omsg/view?usp=sharing

FYI

Rafi

**Comment by medariox** [comment]
Can't reproduce it with Chrome, the qualities are always selected. If you add custom modifications and/or use additional browser plugins to purposely try to break the UI, we surely won't try to "fix" it. Also you said it is a side-effect of the removed `config.ini`, which obviously is not the case since the qualities are not saved to the config, as stated by p0psicles.

**Comment by rafi-d** [comment]
It's Firefox 73.0.1 / Win 10 1903 x64.

**Comment by medariox** [comment]
Okay, so it happens once every 10 refreshes with Firefox. Still, there is no reason to reopen this issue, it needs a new one and it will be Low Priority for obvious reasons.

**Comment by rafi-d** [comment]
>it needs a new one and it will be Low Priority for obvious reasons

Good, you reproduced it... No problem, I'll open another ticket and reference this one. 
BTW, I think that in FF it only happens if you use F5, and not contrl-F5 (so when using the cache...)

One more thing I've noticed:  FF has those lines  "selected" (dark blue), which Chrome - does not (light blue). 
![2020-03-01_151805](https://user-images.githubusercontent.com/2458280/75626412-0bf2ad00-5bd0-11ea-80e8-693ac317f26c.png)
