### ISSUE TITLE
strange bug 

### ISSUE THREAD

**Issue by Urbanshenkie** [pymedusa/Medusa#7755]
warrning about a torrent file that has notting to do with medusa.

Dario tol me to Properly set my locale 

this warning shows a UnicodeDecodeError for a file seeded in rutorrent 

this files has never been downloaded with medusa or any relations.

its a movie torrent  Saving Zoë 

WARNING  SNATCHQUEUE-SNATCH-21845 :: [ee1b898] Error while sending torrent: UnicodeDecodeError('ascii', 'lue>\r\n<value><i8>0</i8></value>\r\n<value><i8>1048576</i8></value>\r\n<value><i8>1</i8></value>\r\n<value><string>Saving Zo\xc3\xab (2019) NL Subs</string><

**Comment by medariox** [comment]
Medusa just processes the files that are in the post-processing folder you selected. So you or some software you are running must have put that file there... I'm not sure how to help.
