### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Sky Atlantic 

### ISSUE THREAD

**Issue by maciekb** [pymedusa/Medusa#7760]
### INFO
**Python Version**: `3.8.1 (default, Dec 30 2019, 15:43:37) [GCC 9.2.0]`
**Operating System**: `Linux-3.10.105-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/cf8ed949fc1eb0595cdcc093cd7df40f
### ERROR
<pre>
2020-02-16 22:37:20 ERROR    Thread_0 :: [] Missing time zone for network: Sky Atlantic 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
Already in the list: [Sky Atlantic:Europe/London](https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L1869)
