### ISSUE TITLE
Custom Edit-show -> allowed qualities list is not being displayed (w/o preferred)

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#7768]
**Describe the bug**
When setting custom Allowed  list of qualities but NOT specifying any Preferred one, the list is not being displayed anywhere, it it reverts to non-custom setting. Only when you add at least one preferred quality it is being displayed as the active setting.

**To Reproduce**
1. Go to 'Edit-show->Quality...'
2. Click on 'custom'
3. Select a few settings (see attached)
4. Save
5. Refresh

**Expected behavior**
The Custom list should be disabled with the selected items highlighted

**Screenshots**
See attached (before and after)

**Medusa (please complete the following information):**

Medusa Info: | Branch:                 master                  Commit:                 ee1b898d0f74750c4c265d077fcc0da73d17b41e                  Version:                 0.3.12                  Database:                 44.14
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j  20 Nov 2018
OS: | Windows-10-10.0.18362-SP0
Locale: | en_IL.cp1252
  |  
  |  
Arguments: | --nolaunch --datadir=D:\Program Files\Medusa\Data

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>  (of saving custom "Allowed" list only)

```
2020-02-20 15:08:01 DEBUG	APIv2-Thread-24 :: [ee1b898] 15315: Saving to database: Fauda
2020-02-20 15:08:01 DEBUG	APIv2-Thread-24 :: [ee1b898] TVmaze 15315: Setting location: E:\Downloads\Bittorrent\Fauda
2020-02-20 15:08:01 DEBUG	APIv2-Thread-24 :: [ee1b898] Internal name cache for fauda set to: fauda
2020-02-20 15:08:01 INFO	APIv2-Thread-24 :: [ee1b898] Building internal name cache for Fauda
2020-02-20 15:08:01 INFO	APIv2-Thread-24 :: [ee1b898] Finished processing 3144 scene exceptions.
2020-02-20 15:08:01 INFO	APIv2-Thread-24 :: [ee1b898] Updating exception_cache and exception_season_cache
2020-02-20 15:08:01 INFO	APIv2-Thread-24 :: [ee1b898] Updating scene exceptions for series Fauda and indexer 3 with id 15315

```
</details>

**Additional context**
Just to note: you can still see the selected items if you manually switch back to "custom"!

![image](https://user-images.githubusercontent.com/2458280/74937102-148afc80-53f4-11ea-84fb-da26b34f0c76.png)
![image](https://user-images.githubusercontent.com/2458280/74937115-1d7bce00-53f4-11ea-8349-1f97417818c8.png)

**Comment by medariox** [comment]
HD1080p is a predefined combined quality that includes the qualities you selected.

**Comment by rafi-d** [comment]
I see, thanks! 

If I may a semi-related question: 
I think I've noticed that the backlog still holds in it's list episodes which were downloaded/snatched already. I assume this is because they were not downloaded at the best quality out of the my selected/custom ones?  If so,  can this behavior be cotroled, I mean if to keep searching for the best quality for replacing (add to?) a previous download or not, or a timeout for that backlog-wait?

Thanks

Rafi

**Comment by medariox** [comment]
The whole point of the backlog search is to keep looking for an episode until you get the quality you want. In the backlog overview you can just press the "mail-box" icon to remove an entry from backlog. If this is something that you how to do often, you should consider tuning your quality preferences. An option to select an expire time for backlog is not available.

**Comment by rafi-d** [comment]
OK, understood. 

Since I can see a backlog full of old shows , which I have not waited for a better resolution to see them (and I do not want to option resolutions out) , I think it can be helpful to avoid the need to always press/archive manually shows. 
So, since there is a new feature now - "viewed" flag, which I hope will be somehow automated in the future to sync with Kodi/trackt/utorrent-labels (tho , I cannot imagine how... ) , Maybe I can suggest/request a new feature - to have an option to auto-skip backlog for watched episodes + set an expiration time? What so you think?
