### ISSUE TITLE
AC-3 not identified as AC3

### ISSUE THREAD

**Issue by rasmusbe** [pymedusa/Medusa#7778]
**Describe the bug**
When a file is named as AC-3 and not AC3 the post processing does not identify the episiode.

**To Reproduce**
1. Download a file containing AC-3 (for example `8.Out.Of.10.Cats.Does.Countdown.S19E06.1080p.HDTV.AC-3.x264.Subs-GTi.mkv` )
2. Run post processing
3. See error
    `8.Out.Of.10.Cats.Does.Countdown.S19E06.1080p.HDTV.AC-3.x264.Subs-GTi.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode`  

If I rename the file to change AC-3 to AC3 it works fine.

**Expected behavior**
Post processing success

**Medusa (please complete the following information):**
 - OS: Docker Linux
 - Branch: master
 - Commit: ee1b898d0f74750c4c265d077fcc0da73d17b41e
 - Version: 0.3.12
 - Python version: 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
 - Database version: 44.14

**Comment by medariox** [comment]
Please report it to guessit: https://github.com/guessit-io/guessit/issues
