### ISSUE TITLE
Newznab server not working

### ISSUE THREAD

**Issue by SparkyRih** [pymedusa/Medusa#7780]
I've been using Sickbeard for years, but it stopped working recently. So since it is not maintained anymore, I switched to Medusa... Everything is working fine, but I cannot connect to my own Spotweb Newznab server anymore, which worked fine in Sickbeard...

The error message I find in the log is the following:
2020-02-25 21:02:21 WARNING  Thread_9 :: [ee1b898] Error getting caps xml for: Spotweb

**Comment by medariox** [comment]
Medusa expects a caps XML from an Newznab provider. How does that look like for Sportweb? Please use the issue template and post debug logs, it's the only way we can help.
