### ISSUE TITLE
Error Parsing title with iggrtorrent

### ISSUE THREAD

**Issue by Dsimonnot69** [pymedusa/Medusa#7783]
Hello with  iggtorrent.se
The.Good.Doctor.S03E14.VOSTFR.720p.WEBRip.2CH.x265.HEVC
The.Flash.2014.S06E12.VOSTFR.720p.WEBRip.2CH.x265.HEVC
for exemple
do not go up in the manual search list
I guess it's related to the term webrip
However in terms of quality I accept everything
but 
The.Good.Doctor.S03E13.VOSTFR.720p.WEBRip.2CH.x265.HEVC
work 

An idea of the cause
thank you

**Comment by p0psicles** [comment]
You ignored the issue template.
 Please provide as much details as possible
Enable debug logs and run a manual search for an episode.

First take a look at the logs yourself. Maybe your answer is there. Else post debug logs.

**Comment by medariox** [comment]
Can't help without debug logs.
