### ISSUE TITLE
Apache Reverse Proxy WebSockets

### ISSUE THREAD

**Issue by Zyplonox** [pymedusa/Medusa#7788]
Hi,
im running Medusa in Docker (127.0.0.1:8082->8081/tcp) and proxy it through apache: 
```
<ifModule mod_ssl.c>
<VirtualHost 193.30.122.114:443>
    ServerName medusa.janvn.de
    ServerAdmin admin@janvn.de

    ErrorLog /var/log/apache2/medusa.janvn.de_error.log
    CustomLog /var/log/apache2/medusa.janvn.de_access.log combined

    <Location />
        AuthType Basic
        AuthName "Restricted Content"
        AuthUserFile /etc/apache2/.htpasswd
        Require valid-user
    </Location>

SSLProxyEngine On

    ProxyPass / http://127.0.0.1:8082/
    ProxyPassReverse / http://127.0.0.1:8082/

    ProxyPreserveHost On
    ProxyAddHeaders On

    # websockets
    ProxyPass /ws ws://127.0.0.1:8082/ws
    ProxyPassReverse /ws ws://127.0.0.1:8082/ws

SSLCertificateFile /etc/letsencrypt/live/janvn.de/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/janvn.de/privkey.pem

RequestHeader set X-Forwarded-Proto https
</VirtualHost>
</ifModule>
```

The site works just fine but firefox is telling me that he can't connect to wss://medusa.janvn.de/ws/ui several times if i open the page.
For me the websocktes proxy looks fine. Mod wstunnel is also enabled.

Reverse Proxy in config.ini is enabled, https is disabled.

Thanks a lot!

**Comment by Rouzax** [comment]
Maybe remove your domain.

Did you follow this guide?
https://github.com/pymedusa/Medusa/wiki/Reverse-Proxy-setup

**Comment by Zyplonox** [comment]
Thanks for your reply.

Yes i followed this guid. 
What do you mean remove your domain?

**Comment by Rouzax** [comment]
I would not put my domain publicly for the whole world to see on GitHub.

**Comment by Zyplonox** [comment]
There is a password authentication. So my domain is public anyway no reason for me to hide it ^^
