### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: FOX

### ISSUE THREAD

**Issue by scrotenz** [pymedusa/Medusa#7795]
### INFO
**Python Version**: `3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-03-01 20:22:41 ERROR    Thread_9 :: [ee1b898] Missing time zone for network: FOX
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
[Already in the list](https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L826)

**Comment by du5t1n55** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: https://gist.github.com/f27d66a1b032eb55dcc1727e45ebbf3a
### ERROR
<pre>
2020-04-22 21:18:39 ERROR    Thread_3 :: [8f6b666] Missing time zone for network: FOX
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by du5t1n55** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/9bab68ac0ea0d7435ba4e59ef249b77d
### ERROR
<pre>
2020-04-28 22:15:37 ERROR    Thread_19 :: [d9c31da] Missing time zone for network: FOX
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by du5t1n55** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/fbaa247497bc7bda61df004cf42feb78
### ERROR
<pre>
2020-05-21 23:16:08 ERROR    Thread_0 :: [d9c31da] Missing time zone for network: FOX
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by du5t1n55** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-07-27 23:11:39 ERROR    Thread_0 :: [d9c31da] Missing time zone for network: FOX
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
