### ISSUE TITLE
ical link

### ISSUE THREAD

**Issue by statik1983** [pymedusa/Medusa#7815]
**Is your feature request related to a problem? Please describe.**
NO
**Describe the solution you'd like**
I WOULD LIKE AN ICAL LINK FOR THE MEDUSA CALENDAR SO I CAN INTEGRATE IT INTO ORGANIZR
**Describe alternatives you've considered**
NONE. 
**Additional context**
RADARR PROVIDES AN ICAL LINK WHICH WORKS PERFECT.

**Comment by p0psicles** [comment]
Then use radarr or sonarr or whatever
