### ISSUE TITLE
Post procesing find by Folder name

### ISSUE THREAD

**Issue by MisaTurek** [pymedusa/Medusa#7834]
Hello,

Post procesing see only file with name - TV Show S0XE0X.avi

If I have Folder with name of TV Show and in folder File only name S01E01.avi, post procesing dont see him.

Old SickBear run perfectly, but new SiCkRage, SickChill, Medusa...nothing. 

Please help me!
Thanks

**Comment by p0psicles** [comment]
Can't you properly name your files. There are even open source tools for this.
