### ISSUE TITLE
Xthor Anti-Spam Protection: A.P.I limited to 1 request every 2 seconds

### ISSUE THREAD

**Issue by vlsoft** [pymedusa/Medusa#7845]
**Describe the bug**
A clear and concise description of what the bug is. problem when looking for episodes.

**To Reproduce**
1. Go to '...'   Automatic (SEARCHQUEUE-BACKLOG)

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64]
 - Branch: [e.g. master, develop] master
 - Commit: [e.g. c65ca2] ee1b898d0f74750c4c265d077fcc0da73d17b41e
 - Python version: [e.g. 3.6.8]  3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
 - Database version: [e.g. 44.12] Database: 44.14

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug

SEARCHQUEUE-BACKLOG-360898 :: [Xthor] :: [ee1b898] Protection Anti-Spam: A.P.I limitee a 1 requete toutes les 2 secondes.
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7846
