### ISSUE TITLE
Error on adding a show with same name and different country

### ISSUE THREAD

**Issue by SxS46** [pymedusa/Medusa#7853]
Hello, I'm trying to add both Lego Masters US and UK but after I add the first one I cannot add the second one because the system recognizes a folder called Lego Masters and sends me directly to the add existing show page. Any ideas?
To reproduce this just add Lego Masters US or UK and then try to add the other one.
Thank you

**Comment by medariox** [comment]
It works just fine for me. The one is called Lego Masters (US) and the other Lego Masters, so there is no conflict. This of course when added with the same indexer (TheTVDB in this case).

**Comment by SxS46** [comment]
I've tried and it keeps sending me to the add existing show when I try to add the second one, even with the same indexer

**Comment by SxS46** [comment]
I've manually renamed the folder Lego Masters to Lego Masters US and now I've successfully added the UK one. Thanks
