### ISSUE TITLE
[Feature] - Expand Search Filters | Anime/Other Language Dub Support

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#7861]
i've requested this b4 noted here #6238, but it seems it has slipped through the cracks..

If possible add new filters per show to allow for prefered language selection. as well as prefered words per show not just as a global option found in search settings
because as shows release on a weekly bases the dubbing releases usually come out 2-3 weeks later for each episode.

so how 
Quality settings work
```
Downloads any of these qualities: 1080p HDTV, 1080p WEB-DL, 1080p BluRay
But it will stop searching when one of these is downloaded: 1080p WEB-DL, 1080p BluRay
```

make it so based on prefered selected language it will search for allowed: any, Japanese & will stop at English.

if possible also add a Prefered Release Group other then just Whitelist & Blacklist.
like say i prefer HorribleSubs over Erai-raws, so if it finds both it will choose HorribleSubs instead.

**1st Option**:
make it so that we can edit the Language Filters. So say for **language: Jap**, we can list keywords like English, subs, eng subs etc... 
**language Eng**, keywords: Dub, Dubbed, Multi-Audio, Audio, Dual-Audio

**2nd Option**:
Each Language gets its own Release Groups Whitelist when anime is set. as certain release groups only do dubs, while others do both etc..

**3rd option**:
Combines 1st & 2nd options, user can specify per Language to either follow the set global release groups for that show, set custom release groups based on Language OR use word/keywords filters option per Language set.

EG Scenario:
Anime Show: Infinite Dendrogram
Language Allowed: Jap
Language Prefered: English
Medusa searches for the show only selecting results from the whitelisted release groups `HorribleSubs, Erai-raws` for the Jap Language. it will then further go through the list of selections and apply the prefered words filter for that show. Prefered Words: x265, 10Bit
if it doesn't find any prefered words it will just select one of them.

English Language: Medusa will search for results that contain keywords such as: Dubbed, Dub, Audio. Dual-Audio, Audio. if a preferred/allowed group is also present for English Language it will also apply that on top of the found results to further filter them.
English Language Release Groups: Golumpa, LostYears

Since English is prefered Medusa will continue searching for the English Language till it finds it & replaces it.

**Comment by medariox** [comment]
Don't open duplicate feature requests. You are free to add more information to the original feature request if you want. We don't have the resources to add niche functionality, so you will have to hope someone picks up your feature request and sends a PR.
