### ISSUE TITLE
Issuing setting up behind reverse proxy that is ssl 

### ISSUE THREAD

**Issue by AlexSamad** [pymedusa/Medusa#7873]
I have installed the latest version 

Medusa Info: | Branch: masterCommit: ee1b898d0f74750c4c265d077fcc0da73d17b41eVersion: 0.3.12Database: 44.14
-- | --
Python Version: | 3.6.9 (default, Nov 11 2019, 10:00:15) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
SSL Version: | OpenSSL 1.0.1e-fips 11 Feb 2013
OS: | Linux-2.6.32-696.10.3.el6.x86_64-x86_64-with-centos-6.9-Final
Locale: | en_US.UTF-8

i have httpd reverse proxy in front of it but it is setup for https only

when i attempt to connect chrome complains - all link are referenced as http not https

looks like you have coded the base url as https://

**Comment by medariox** [comment]
Have you followed the guide? https://github.com/pymedusa/Medusa/wiki/Reverse-Proxy-setup
We don't have https hard coded and can't help without knowing your actual setup.
