### ISSUE TITLE
Having issues chaning my show directory

### ISSUE THREAD

**Issue by Zladde1** [pymedusa/Medusa#7882]
Hi,

One of my drives is getting full and i'm trying to redirect the next episodes to another hard drive. I have changed in my settings where "Show root directories" is now a new drive as defualt. I even deleted the other root to remove any kind of problems. 

But even with this, my new episodes are Post Processing to the old hard drive that is almost full. I'm out of google searches on this one.

**Comment by p0psicles** [comment]
Did you chance l change the root folder for that show?

**Comment by Zladde1** [comment]
Thank you, i was about to pull my hair away last night. This is something i forgot to change..
