### ISSUE TITLE
Postprocessing frequency ignored

### ISSUE THREAD

**Issue by doodyd** [pymedusa/Medusa#7895]
I recently switched on automatic postprocessing. It doesn't seem to be processing my files in a timely manner.

When I look at the system status page, I notice that while the auto-postprocessing frequency is set to 10 minutes (as per the settings page and unchanged from the default, I believe), the time until next run is hours away.

![PostProcess](https://user-images.githubusercontent.com/29137584/77870107-0e582d80-7288-11ea-9d5c-1db264bf1f1b.png)

How can a 10 minute interval lead to a time between execution of many hours?

Manual postprocessing is working correctly, including the execution of my custom script.

OS: FreeNAS 11.2-U8; iocage jail
Branch: master
Commit: where do I find this?
Python version: 3.7.6
Database version: Where do I find this?

**Comment by doodyd** [comment]
Additional information:

Looking at the last run time and comparing that to the current time + time until next run, it seems the next run is exactly 24h 10m after the previous run.

**Comment by medariox** [comment]
Please try https://github.com/pymedusa/Medusa/pull/7898
Does it fix the issue?

**Comment by medariox** [comment]
Please update to the new release: https://github.com/pymedusa/Medusa/releases

**Comment by doodyd** [comment]
Thanks, I'll let you know how it goes.

Interestingly, after a manual postprocess last night, it ran every 10 minutes for 2 hours and then stopped. No files were processed during this period.  I did not check the 'next run' before applying the latest updates, so I don't know what it did after that 2 hour time frame.

**Comment by doodyd** [comment]
All good.  Running every 10 minutes, as required.
