### ISSUE TITLE
problem: this is taking too long, click here to show the page

### ISSUE THREAD

**Issue by BedoM** [pymedusa/Medusa#7896]
Hello,
I want to test for the first time "medusa"

so i have this docker-compose with the following nginx front end and i get this page from (chrome, firefox) (windows and linux)

![medusa](https://user-images.githubusercontent.com/25350431/77891675-9979f900-7271-11ea-9cc4-4c78c6d969a1.png)

   medusa:
    image: pymedusa/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /data/medusa/config:/config
      - /data/transmission/downloads:/downloads
      - /data/series:/tv
    networks:
       Stack_MediaCenter:
        ipv4_address: "172.20.0.10"
    restart: always

server {
    server_name medusa.mydomainname.fr;
    access_log /var/log/nginx/medusa.log;
    error_log /var/log/nginx/medusa.log;
    
location / {
    proxy_pass http://172.20.0.10:8081;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host:443;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-Port 443;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Websocket
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 86400;
}
}

35615ec8e172        pymedusa/medusa            "python start.py --n…"   8 minutes ago       Up 8 minutes        8081/tcp                                 medusa

**Comment by medariox** [comment]
Please update to the new release: https://github.com/pymedusa/Medusa/releases
