### ISSUE TITLE
Broken checkbox CSS

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#7902]
Looks like someone messed up the CSS recently. All checkboxes on that page are like that.

![Screen Shot 2020-03-31 at 8 30 19 am](https://user-images.githubusercontent.com/6525926/77966132-f9cc7180-7329-11ea-9cbf-225901161b5e.png)

**Comment by p0psicles** [comment]
page hasn't been toched in a while. Also which browser are you using? I'm having no issues on chrome.

**Comment by OmgImAlexis** [comment]
Same issue for chrome and safari for me. I’ll see if I can workout what’s causing this.

**Comment by medariox** [comment]
All good here with Chrome.
