### ISSUE TITLE
Banners on schedule page overlap on small width

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#7903]
Banners should fit to the surrounding div.

![Screen Shot 2020-03-31 at 9 03 21 am](https://user-images.githubusercontent.com/6525926/77968315-9729a480-732e-11ea-9125-87c80f79774d.png)

**Comment by p0psicles** [comment]
Not an issue here on chrome and ff on Windows or Android. Probably something wrong with your installation

**Comment by OmgImAlexis** [comment]
It's Safari. Just because you tested on Windows doesn't mean other OSs and/or browers are effected. You should know this.

**Comment by p0psicles** [comment]
Well unfortunately I can't dev and test on 20 different combinations of os/browsers. That's why projects like these depend on many devs who can dev/test against these combinations. So sorry not much we can do about this.
