### ISSUE TITLE
No daily searches 

### ISSUE THREAD

**Issue by sendas** [pymedusa/Medusa#7904]
**Describe the bug**
Searches are not performed automatically 

**Expected behavior**
Automatically episode search 

**Screenshots**

**Medusa (please complete the following information):**

Medusa Info: | Branch: master Commit: 4d1e78726dc94979cc7908651d13e40f199959a9 Version: 0.3.14 Database: 44.14
-- | --
Python Version: | 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-4.19.75-v7+-armv7l-with-debian-10.1
Locale: | en_GB.UTF-8
![45EFB545-70C7-4B39-9EAB-461E79D0B000](https://user-images.githubusercontent.com/10220908/78023058-e501d500-734d-11ea-8848-789d9f922c1a.jpeg)
![907A82B4-B9B2-421B-BD35-5B31D9E30B78](https://user-images.githubusercontent.com/10220908/78023064-e6330200-734d-11ea-9f0f-fd3bb8b30ba1.jpeg)

**Comment by sendas** [comment]
I have no debug logs

**Comment by medariox** [comment]
No debug log = no support.
Your status page shows that the daily searches are running just fine.
We can't verify anything without debug logs.

**Comment by sendas** [comment]
It’s says false on the active column ...

**Comment by sendas** [comment]
And “not in progress”

**Comment by medariox** [comment]
It is only active when it is actually running.
The important thing is that it is alive.
