### ISSUE TITLE
Post-Processing Extra script aren't working anymore since v0.3.14

### ISSUE THREAD

**Issue by lamplis** [pymedusa/Medusa#7905]
Hi,
I have a synology DS1515 and I had a post-processing script (in /config/postProcessing/) to execute Synology video indexer automatically after post processing.
Here is the script that worked for years :
`/volume1/@appstore/python/bin/python /volume1/@appstore/sickbeard-custom/var/IndexIt.py`

Since the last update it doesn't work anymore.
I have the following error : 
`Extra script python /volume1/@appstore/sickbeard-custom/var/IndexIt.py is not a file.`

I even tried with the direct python command but in vain:
`python /volume1/@appstore/sickbeard-custom/var/IndexIt.py`

When I list the files the rigths seem to have not changed :
`-rwxr-xr-x  1 sc-sickbeard-custom sickbeard-custom      1563 Mar 24  2019 IndexIt.py`

Medusa Info: 
- Branch:                 master
- Commit:               4d1e78726dc94979cc7908651d13e40f199959a9                  
- Version:                0.3.14

Could you help me?

**Comment by medariox** [comment]
There has been a little change for security reasons. Only use the script path, without the Python path. In your case just type `/volume1/@appstore/sickbeard-custom/var/IndexIt.py` in the extra script field.

**Comment by lamplis** [comment]
It's working perfectly !
Thank you very much !

Don't hesitate to update the wiki for this major change on post processing scripts : https://github.com/pymedusa/Medusa/wiki/Post-Processing

Regards

**Comment by medariox** [comment]
You're right. I've updated the wiki accordingly, thanks!

**Comment by lamplis** [comment]
It's working perfectly !
Thank you very much !

Don't hesitate to update the wiki for this major change on post processing scripts : https://github.com/pymedusa/Medusa/wiki/Post-Processing

Regards
