### ISSUE TITLE
Downloaded lower quality color is now Red?

### ISSUE THREAD

**Issue by eddywitkamp** [pymedusa/Medusa#7906]
**Describe the bug**
Downloaded episodes that are not the wanted quality used to show as Yellow.
They still show as Yellow in the backlog overview.
But in the Shows episode list they now show as Red?

**Expected behavior**
Downloaded episodes that are not the wanted quality show as Yellow.

**Screenshots**
![image](https://user-images.githubusercontent.com/6422683/78079757-13fb6380-73ad-11ea-9c9d-559cfa434d58.png)

![image](https://user-images.githubusercontent.com/6422683/78079827-39886d00-73ad-11ea-9d77-0d29a8d77973.png)

Medusa Info: Branch: master
Commit: 4d1e78726dc94979cc7908651d13e40f199959a9Version: 0.3.14
Database: 44.14
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-10-10.0.18362-SP0
Locale: | nl_NL.cp1252

**Comment by medariox** [comment]
It means they are neither in allowed nor preferred qualities aka a quality which is not desired. Add the "lower" qualities as allowed.

**Comment by medariox** [comment]
Yes, it was changed in 0.3.13
