### ISSUE TITLE
Displaying show with pagination off not showing all seasons/episodes

### ISSUE THREAD

**Issue by G33K** [pymedusa/Medusa#7907]
**Describe the bug**
Displaying show page with pagination off in the Interface settings is not showing all seasons/episodes. The list cuts off after a few seasons. Its as if it is paginating without the link to the pages.

**Medusa (please complete the following information):**
 - OS: Debian 9 x64
 - Branch: master
 - Commit: 4d1e78726dc94979cc7908651d13e40f199959a9
 - Python version: 3.5.3
 - Database version: 44.14

**Comment by medariox** [comment]
Now that the specials page is on a separate table there is no need to disable pagination. The option will be removed in the next version.

**Comment by eddywitkamp** [comment]
Before you remove that setting, will you fix the bug with Pagination that shows the wrong amount of episodes/size for a season that spans multiple pages?

**Comment by medariox** [comment]
It shows the size and episodes you can currently see on the page. It's meant to be like that and won't be changed. However, you can set to show up to 500 episodes at once, so you can decide how much of a season you want to display on a single page.

**Comment by Acrimonis** [comment]
If I may... 

I would love to be able to completely disable the pagination/lazy loading? It is very slow and not catching up with scrolling without delays and annoying scrolling jumps?

Or, is that something that needs be disabled at the code level? 
I assume vue.js, but I do not know that JS framework and short on time to dig it out?

Thanks much for your consideration.

**Comment by medariox** [comment]
@Acrimonis 
Are you suggesting that loading 5000 episodes at once is faster than loading 50 or 500? Because I don't see how your comment makes any sense from a technical or logical point of view.

**Comment by eddywitkamp** [comment]
Can you move the setting to select 50-100-etc rows per page to the top? 

If you select 500 (which I often do) you have to scroll all the way down to change it back to something else.

Also, the option ALL rows doesn't stick, it reverts to another number.

**Comment by p0psicles** [comment]
I'll see if I can store the "all" Better. 

As for the pagination, I'll look into it. But it's part if the component we use. So don't think we can change that. Maybe one can improve the jump arrow to the bottom.

**Comment by taoofshawn** [comment]
if pagination-off is going away, is there any way to jump to a season that is not on the currently displayed page? (the season links at top don't seem to work unless it is currently displayed)

**Comment by eddywitkamp** [comment]
> if pagination-off is going away, is there any way to jump to a season that is not on the currently displayed page? (the season links at top don't seem to work unless it is currently displayed)

Agree with this. If there is no way to turn pagination off, this bug is very important to fix first:

https://github.com/pymedusa/Medusa/issues/7552

**Comment by GldRush98** [comment]
> @Acrimonis
> Are you suggesting that loading 5000 episodes at once is faster than loading 50 or 500? Because I don't see how your comment makes any sense from a technical or logical point of view.

Of course 50 loads faster than 500.  However... and this is very important:
500 Loads MUCH faster than:
50, scroll down load
50, scroll down load
50, scroll down load
50, scroll down load
50, scroll down load
50, scroll down load
50, scroll down load
50, scroll down load
50, scroll down load
50, scroll down load
For those of us running Medusa on a fast server, using a fast computer, and all running at LAN speeds, loading all 500 episodes at once is MANY time faster than the constantly-scroll-and-load game. Please do not remove the option to disable pagination, as this will make Medusa nearly unusable for large shows. Medusa is useful to quickly check episodes even old ones that have been loaded in for a long time. Forcing pagination is going to be a very bad user experience.

**Comment by p0psicles** [comment]
I made some improvements in the episode Loading. Think that should be in the last release. It should ease the rendering while Loading Seasons. 

Also, when a vue-good-table PR gets merged, we can properly use the "all" For displaying all episodes, while using pagination

**Comment by GldRush98** [comment]
Will the All setting be universal across all shows, and remembered? If so then I think this should be a sufficient solution.  Any thing that avoids fighting the scroll-loading over and over and over :)

**Comment by p0psicles** [comment]
Yes it Will. 
But to be Clear. Your not forced to use 50 ep's. You can also set it to 500.

We'll also fix the jumping to season with pagination enabled.

**Comment by medariox** [comment]
Fixed in develop with https://github.com/pymedusa/Medusa/pull/8550
