### ISSUE TITLE
Do not found all "season packs" on non-English providers

### ISSUE THREAD

**Issue by Naworm** [pymedusa/Medusa#7919]
Hello everyone,
It is a really simple thing, but I'm pretty sure that every non-english users is impacted.

Obviously Season are called Season in English, so here I am using a French Provider (YggTorrent). In French, season is written "saison". When the uploaders name their torrent with Saison term for a Season Pack, Medusa will not see it.

Season (english) : OK
Saison (french) : NOK

Check attachements for a relevant example.

![2020-04-05 02_32_40-Recherche - Yggtorrent](https://user-images.githubusercontent.com/48997616/78464368-dff3ab80-76e8-11ea-8182-c31539cb7b80.png)

![2020-04-05 02_32_49-Years and Years _ Medusa](https://user-images.githubusercontent.com/48997616/78464367-df5b1500-76e8-11ea-9a72-22ea37ca477a.png)

So I tried to add "saison" in : Scene Exception => Same ; Required words => Same

Maybe other users will be able to confirm the issue and report other languages.

Regards,
Nawor

**Comment by p0psicles** [comment]
Is in the works #3732 
But that's per show. Maybe this needs to be added to a French provider? @medariox ?

**Comment by Naworm** [comment]
Nice, great work on the way ! 👍

Right, it may be a good idea to add a customizable Provider Options that permit to allow new prefixes to seasons and episodes.
like : S**, Season**,E**,Episode**,etc.

**Comment by p0psicles** [comment]
Currently we search for `S` + the season number. Like `S01`. Do you have an example of a `saison` season pack release name?

**Comment by Naworm** [comment]
What you mean ? There is a ton of different way to write `season` if considering all languages.
Do medusa can found a show that is written `Good.Show.Season.2` ?

**Comment by p0psicles** [comment]
I asumed that as this is a French indexer. Release names often have the keyword saison in it. Thats why is added it specific to the yygtorrents. But this only applies to performing manual and backlog searches. For example also season packs with different languages in them, will be processed through a daily (rss) search. 

So it's also a matter of having guessit (the tool that does the release name analysis) recognizing the non-english languages.

**Comment by p0psicles** [comment]
So that's why I asked for some release name examples. Cause maybe guessit also can't handle them

**Comment by p0psicles** [comment]
And last thing I'd like to add. There is like a officious standard for episode and season naming. That includes naming it in english. How are we to recognize a release name if season is written In Swahili?

**Comment by Naworm** [comment]
If you added the `saison` keyword to yggtorrent and to others french provider, it's all good for me.
I don't think that Swahili providers are supported by medusa, if so why not ^^

**Comment by p0psicles** [comment]
I checked and also guessit supports saison. So with this addition, a manual search should yield results now in develop branch

**Comment by Naworm** [comment]
Thanks a lot man !

**Comment by Naworm** [comment]
@p0psicles I've just checked your commit, do you think  that `'Saison {season}'` will permit to found 'Series.Name.Saison 3' and 'Series.Name.Saison.3'

**Comment by p0psicles** [comment]
Yes

**Comment by Naworm** [comment]
Hello @p0psicles ,
I am coming back to you after the update 0.3.15, I've tried another time and verify that the code was really up to date in my configuration.
But unfornately it do not foun any "Saison" season packs.
Here two example that do not found in manual search :

![2020-04-14 21_03_30-Window](https://user-images.githubusercontent.com/48997616/79263879-ed045d80-7e93-11ea-8e53-c1307f9c8da0.png)
![2020-04-14 21_02_39-Window](https://user-images.githubusercontent.com/48997616/79263892-efff4e00-7e93-11ea-9298-95bfb425d850.png)

Hope you can re-open the issue and see when you got time.

Regards,
Nawor

**Comment by Naworm** [comment]
@p0psicles please at least reopen the issue :)

**Comment by p0psicles** [comment]
Do you get any results now go yygtorrent? I heard that they use captcha now?

**Comment by Naworm** [comment]
Yes it work, but some time they add additionals security to prevent DDOS etc.

Ok now "Saison.3" is working
and "Saison 3" is working too but he is converting to "Saison.3".
It's all good now, duno why it do not worked on my early tests, I think i got baited by One Piece who do not work correctly.

![image](https://user-images.githubusercontent.com/48997616/79404805-03451300-7f93-11ea-81c9-3bb30058b3a8.png)

**Comment by Naworm** [comment]
Have you any clues ?

![2020-04-16 03_52_58-One Piece _ Medusa](https://user-images.githubusercontent.com/48997616/79405867-d21a1200-7f95-11ea-8952-f8fa4f0101f5.png)
![2020-04-16 03_52_34-Recherche - Yggtorrent](https://user-images.githubusercontent.com/48997616/79405872-d6dec600-7f95-11ea-8a84-0ae6c1aa1229.png)
![2020-04-16 03_52_16-Recherche - Yggtorrent](https://user-images.githubusercontent.com/48997616/79405875-d8a88980-7f95-11ea-8b7f-6ef13afe4b45.png)
