### ISSUE TITLE
Specials are not using filtering

### ISSUE THREAD

**Issue by eddywitkamp** [pymedusa/Medusa#7926]
**Describe the bug**
Now that Specials are in their own tab, they do not react to filtering anymore.
As you can see in the screenshot, "skipped" is off but all the skipped Specials still show up.

**Expected behavior**
Filtering is applied to the Specials too.

**Screenshots**
![image](https://user-images.githubusercontent.com/6422683/78511640-a2515a00-779e-11ea-9ef8-b2c6ba14a8a9.png)

**Medusa (please complete the following information):**
Branch: master
Commit: 4d1e78726dc94979cc7908651d13e40f199959a9
Version: 0.3.14
Database: 44.14
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-10-10.0.18362-SP0
Locale: | nl_NL.cp1252

**Comment by eddywitkamp** [comment]
Still an issue in 3.15

**Comment by medariox** [comment]
Specials don't have filtering and won't have filtering in the future, as it not useful in 99% of the shows.
