### ISSUE TITLE
Filtering is not working correctly on show home page using Pagination

### ISSUE THREAD

**Issue by eddywitkamp** [pymedusa/Medusa#7927]
**Describe the bug**
The amount of episodes in filters is only updated if that specific episode is in view, for example on page 3 of pagination. It does not show up on page 1.
This makes it hard to find episodes with a specific state.
I only found the episode I was missing looking at the backlog.

**To Reproduce**
1. Have a "wanted" episode on, for example, page 3 of a show
2. Open the show on the main page 1 and see "wanted" set to 0
3. Click though to page 3 and then suddenly, wanted is 1

**Expected behavior**
All episodes are counted against the filter on the starting page 1.

**Screenshots**
Page 1
![image](https://user-images.githubusercontent.com/6422683/78511758-69fe4b80-779f-11ea-9be6-ee053e6e18ff.png)

Page 3 (after disabling other filters, you have to be able to click through to page 3 first)
![image](https://user-images.githubusercontent.com/6422683/78511795-acc02380-779f-11ea-92ea-34cc1c33a629.png)

Backlog
![image](https://user-images.githubusercontent.com/6422683/78511725-4dfaaa00-779f-11ea-9b11-5ddbfd290591.png)

**Medusa (please complete the following information):**
Branch: master
Commit: 4d1e78726dc94979cc7908651d13e40f199959a9
Version: 0.3.14
Database: 44.14
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-10-10.0.18362-SP0
Locale: | nl_NL.cp1252

**Comment by eddywitkamp** [comment]
still an issue in 3.15

**Comment by medariox** [comment]
Filtering is always for the tables you are viewing. You can extend the episodes to 500 or look at the backlog overview.
