### ISSUE TITLE
[UI Bug] Unable to delete scene exceptions - auto added

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#7944]
**Describe the bug**
since the new scene exceptions has been added where you can now do season number as well, any show that auto adds scene exceptions i cannot delete via the web interface.

**Expected behavior**
to give me an option to delete it?

**Screenshots**
![Screen Shot 2020-04-10 at 1 23 30 pm](https://user-images.githubusercontent.com/2242880/78959902-b6df7a80-7b2f-11ea-8bbc-2e817f3dc190.jpg) - where is the X to remove?
![Screen Shot 2020-04-10 at 1 23 12 pm](https://user-images.githubusercontent.com/2242880/78959912-bd6df200-7b2f-11ea-90da-70ec8badf00f.jpg)

**Medusa**
 - OS: macOS Catalina 10.15.4
 - Branch: develop
 - Commit: 3fc2e3f212f3451810076198150796c8ef744b97
 - Python version: 3.7.7
 - Database version: 44.15

There are no logs as this is a interface issue..

**Comment by p0psicles** [comment]
You can't delete external exceptions. As it would just return after being synced again. Like the tool tip says

**Comment by p0psicles** [comment]
Add your own. You can delete those

**Comment by XxUnkn0wnxX** [comment]
well in case i have above the scene exception is wrong, i know adding my own will solve it but it will extending search time as it has to go through the auto added scene exception. which i don't want.

is there a way to turn of scene exceptions from being added automatically? i'd rather manage them myself manually.. @p0psicles

**Comment by p0psicles** [comment]
You'll have to wait for a new feature I'm developing. Search template. You'll have full control over which searches are done

**Comment by p0psicles** [comment]
Btw nothing changed regarding your issue. You could also not remove them before

**Comment by p0psicles** [comment]
#3732

**Comment by p0psicles** [comment]
@XxUnkn0wnxX maybe I gave the impression that I'm not grateful for your reported issue. But I really am. Tnx for using the develop branch and help make Medusa even more awesome!

**Comment by BeMacized** [comment]
@p0psicles I see this issue has been closed, but I'm running into a similar problem: The scene exceptions that were automatically added for one of the shows I am trying to download are simply incorrect. 

Yes, I can add my own scene exceptions, but it doesn't seem to prevent Medusa from finding episodes using the incorrect scene exceptions that were automatically added. The wrong episodes are downloaded because of it and there doesn't seem to be any way of turning it off. 

While I'd agree this is not a "bug" by definition, I would say it's a feature that prevents Medusa from working correctly. 
Is there any chance of this being reopened?

**Comment by medariox** [comment]
You can disable scene exceptions at any time from the show page settings.

**Comment by BeMacized** [comment]
> You can disable scene exceptions at any time from the show page settings.

That would be great! I however only see the option to disable scene exceptions you add yourself, not these automatically added scene exceptions like the ones shown in the screenshots. Would you mind showing where in the show settings this could be found?

**Comment by medariox** [comment]
It will disable all scene exceptions, not only the ones that were added manually.

**Comment by p0psicles** [comment]
@medariox don't think you can disable scene exceptions. You can disable scene numbering though. 

@BeMacized like mentioned before, it's a feature that's been worked on. No eta though. Check the linked PR above for more info.

**Comment by medariox** [comment]
Oh yeah, totally got me confused.

@BeMacized You can report faulty scene exceptions to thexem.de or to us and they will be removed https://github.com/pymedusa/medusa.github.io/tree/master/scene_exceptions
