### ISSUE TITLE
Post processor locks up manual search

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#7950]
**Describe the bug**
While the post processor thread is running manual search pages timeout. Once it’s finished the manual search pages works without an issue. 

Using the latest docker release. The issue seems to have been added in the last month or so. I do remember a change being added to the pp recently so I think it may have been what caused this.

**Comment by medariox** [comment]
Please use the issue template.

**Comment by OmgImAlexis** [comment]
@medariox I really don’t get you lately. 

Guess we’ll just leave this bug in since you can’t be fucked dealing with it. 💁‍♀️

**Comment by p0psicles** [comment]
No we have an issue template that users need to fill in. That way we have the minimum amount of info to start looking at an issue. 

We don't have allot of time to Invest into Medusa. So we Request users put some time into this as well. So if a user feels that he doesnt need to follow our rules, we also don't look at the issue.

**Comment by OmgImAlexis** [comment]
I know this... What else would you need? Come on. We've worked on this together I'm not just some random user.

If you let an auto PP start and then try and view a manual search page the page timesout.

**Comment by p0psicles** [comment]
Comon is it that much work to fill in the template? You ask what Else do I need, that info is in the template. From your installation to debug logs at time of a hang.

Do you know how much time a week we lose answering questions like this?

**Comment by OmgImAlexis** [comment]
There's nothing in the logs showing anything. If you just went and spent 3 seconds reproducing this you'd see the issue. You seeing this is going to help way more than me trying to do anything.

Funny how you talk about wasted time and then go on with all of this. @medariox could have easily just asked for the extra info but no...

**Comment by medariox** [comment]
I asked for the logs because I can't reproduce it. Manual search works perfectly fine for me while PP is running. That is because they run in different threads. So until you can provide reproducible proof we can't help and we also can't leave this as an open bug. Rules are the same for everyone: we need debug logs and a way to reproduce the issue, otherwise we just can't help.
