### ISSUE TITLE
ShowUpdater is no longer pulling updates. (Since 0.3.14 update)

### ISSUE THREAD

**Issue by darkzabat** [pymedusa/Medusa#7961]
The showupdater process is showing that it ran at its scheduled run time, but no shows are updating and there are no logs produced showing that the showupdater attempted to update any shows.

**To Reproduce**
1. Wait till the scheduled run of showupdater
2. Look for logs by filtering for showupdater logs and show queue (update) log. There are no logs for the last 24hr.
3. Run a full update on a show with new episodes or seasons.
4. New episodes and seasons for that show appear after running full update on show.

**Expected Behavior**
The showupdater should run daily and pull in all newly added episodes and seasons for all shows.

**Medusa (please complete the following information):**
 - OS: Fedora 31
 - Branch: master
 - Commit: 4d1e78726dc94979cc7908651d13e40f199959a9
 - Python version: 3.7.6
 - Database version: 44.14

**Comment by medariox** [comment]
The issue template requires debug logs.

**Comment by udochrist** [comment]
same here on the current docker image.
the automated update doesn't seem to  start. manual updates are working as expected.

![Schedule](https://user-images.githubusercontent.com/869637/79092676-ea99ea80-7d51-11ea-9c4c-377c56627008.png)

it should have run during the night, yet it doesn't run. the 14:37 was the time i last re-started medusa.

**Comment by medariox** [comment]
Fixed with the new release. Please update.

**Comment by darkzabat** [comment]
Confirmed, ShowUpdater now runs at the scheduled time. Thank you for implementing the fix so quickly.
