### ISSUE TITLE
[APP SUBMITTED]: sqlite3.OperationalError: no such table: scene_exceptions

### ISSUE THREAD

**Issue by hergonoway** [pymedusa/Medusa#7976]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: https://gist.github.com/dbecb686d677cc635f2cbabf8e745cd2
### ERROR
<pre>
2020-04-15 23:03:52 ERROR    FORCEDSEARCHQUEUE-BACKLOG-376729 :: [918cfe7] DB error: OperationalError('no such table: scene_exceptions')
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/db.py#L113">medusa/db.py</a>", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: no such table: scene_exceptions
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by hergonoway** [comment]
I should precise that I didn't alter the db in any way

**Comment by medariox** [comment]
Did you restart while the update was running? What are your setting regarding updates? Automatically update on or off?

There is no "quick fix". You need to upload your `main.db` and `cache.db` to https://send.firefox.com/ so we can fix it manually.

**Comment by hergonoway** [comment]
Thanks for your quick reply, "Did you restart while the update was running?" -> no, (from the UI) I almost never restart medusa (except when medusa doesn't react has expected, but it's always with an uptime beyond 24h, from what I can remember)

About updates : embedded updates are ON with check every hour (default) and auto-update is on. Also, every day at 3am I've got watchtower checking if there's any new image of medusa from  linuxserver.io, and if so, rebuild the docker by pulling the last image. But by experience a sigterm is sent during this operation. 

![image](https://user-images.githubusercontent.com/8405448/79395939-0fbd7180-7f7b-11ea-8a25-7ca75e25325d.png)

@medariox : I've shut down medusa and copied `cache.db` and `main.db`,  please find the requested link (thanks for your help !):  https://send.firefox.com/download/c189474ee0015b3b/#lTIHMmB86ctoLZ21ekBuCA

**Comment by medariox** [comment]
@hergonoway 
Download the new files from here: https://send.firefox.com/download/365a8751ca979682/#naIQbWJq1z097PdwcT-G8g
1. Make sure Medusa is shut down
2. Replace the new files with the existing ones
3. Start Medusa and let it finish the update (don't restart for any reason!)

This will allow a correct upgrade.

About your settings: you need to have either use auto updates or watchtower! Using both can cause this kind of issues! I suggest you disable the auto update and let watchtower handle it.

**Comment by hergonoway** [comment]
Thanks a lot for your time and help. New files seems to have fixed the issue. I've followed your advice and disable the buildin auto-udpate.

**Comment by syp1975** [comment]
Same issue as @hergonoway, except that I have "Automatically update" dissabled. Watchtower pulled a new image and recreated the container 1 day ago. I had restored main.db and config.ini to a backup made before the update, and the error appears again when I start the container.
https://send.firefox.com/download/e7370f0c8f88f2b2/#HAhjAqB41Cr0LEvuRemhTw
Archive contains the backup and the contents of the config folder

**Comment by hergonoway** [comment]
there was a new image built 2 days ago tagged as latest on dockerhub by linux server.io

`LABEL build_version=Linuxserver.io version:- v0.3.15-ls41 Build-date:- 2020-04-14T09:55:26+00:00`

**Comment by medariox** [comment]
@syp1975 
Here: https://send.firefox.com/download/4950f7c4afe1dc30/#cbWN-MLa_vEojfXHlNcaIw

@hergonoway 
No.

At this point there is probably something wrong with your Watchtower setup. Please make sure to fix it as we can't do this for every release with DB upgrade.

**Comment by syp1975** [comment]
The only missing thing was the scene_exceptions table. Thanx.

By default, watchtower sends a SIGTERM signal to stop the container, the same signal that docker stop command uses. May be medusa is taking too long to exit?

I will change default stop timeout of watchtower from 10s to 60s, just in case:
> Timeout before the container is forcefully stopped. When set, this option will change the default (10s) wait time to the given value. An example: --stop-timeout 30s will set the timeout to 30 seconds.
```
Argument: --stop-timeout
Environment Variable: WATCHTOWER_TIMEOUT
Type: Duration
Default: 10s
```

**Comment by medariox** [comment]
It depends what Medusa is doing at that time. If a backlog or show updater is running it will take longer to exit, because it needs to terminate before Medusa can shut down cleanly.

**Comment by reemplazable** [comment]
I have the same issue!
```
2020-04-17 01:36:20 ERROR    SEARCHQUEUE-BACKLOG-293088 :: [8f6b666] DB error: OperationalError('no such table: scene_exceptions')
Traceback (most recent call last):
sqlite3.OperationalError: no such table: scene_exceptions
2020-04-17 01:36:20 ERROR    SEARCHQUEUE-BACKLOG-293088 :: [8f6b666] DB error: no such table: scene_exceptions
Traceback (most recent call last):
sqlite3.OperationalError: no such table: scene_exceptions
```

**Comment by p0psicles** [comment]
@medariox check discord

**Comment by reemplazable** [comment]
help?

**Comment by wfulcher** [comment]
### INFO
**Python Version**: `3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]`
**Operating System**: `Linux-3.10.105-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/57de99b559233a2f24368f74458350ab
### ERROR
<pre>
2020-04-21 16:35:37 ERROR    FORCEDSEARCHQUEUE-MANUAL-279121 :: [baad1e5] DB error: OperationalError('no such table: scene_exceptions')
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/db.py#L113">medusa/db.py</a>", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: no such table: scene_exceptions
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by wfulcher** [comment]
### INFO
**Python Version**: `3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]`
**Operating System**: `Linux-3.10.105-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/30da9d50036537a12f95bf16651b985f
### ERROR
<pre>
2020-04-21 16:35:37 ERROR    FORCEDSEARCHQUEUE-MANUAL-279121 :: [baad1e5] DB error: no such table: scene_exceptions
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/db.py#L285">medusa/db.py</a>", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/db.py#L113">medusa/db.py</a>", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: no such table: scene_exceptions
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
https://github.com/pymedusa/Medusa/issues/7983#issuecomment-615194766
