### ISSUE TITLE
Show Update appears to not be running automatically

### ISSUE THREAD

**Issue by zodd721** [pymedusa/Medusa#7979]
**Describe the bug**
Under server status the "Show Update" hasn't run for 2 days.
The last run time was from the restart after applying the 0.3.15 update on 4/14

**To Reproduce**
1. Navigate to "Server Status".
2. Show Update status in False state
3. Show update hasn't run since 4/14/20
See screenshot

**Expected behavior**
Medusa automatically runs the show update and updates my show/episode info on a schedule.

**Screenshots**
![2020-04-16 09_04_35-Status_Medusa](https://user-images.githubusercontent.com/44557412/79465839-749bba80-7fc1-11ea-9346-5752cc3b4376.png)

**Medusa (please complete the following information):**
 - OS: Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic
 - Branch: master
 - Commit: 8f6b6665c778cb456899809877c3bc15a547abf6
 - Python version: 3.7.7 (default, Mar 10 2020, 17:25:08) [GCC 5.4.0 20160609]
 - Database version: 44.15

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**
I'm not sure what part of the debug logs you might want for this?
I can provide the entire log file if that would help?

**Comment by medariox** [comment]
Yeah well without debug logs we can't help you. I see you are having an error, so why not start by including that as the log? Otherwise restart and post the appropriate logs. There is really no point in opening an issue without logs.

**Comment by zodd721** [comment]
No disrespect but I wasn't sure which logs to upload for this. That's why I mentioned this in the additional context field. The last error I see in my error logs is from 4/15/20. I haven't seen any additional since. I wasn't sure if it was related to the failed status in my screenshot. So, is it ok for me to provide the entire: application.log.2 containing the error shown in Medusa when i resubmit this?

thank you
