### ISSUE TITLE
no such table: scene_exceptions

### ISSUE THREAD

**Issue by reemplazable** [pymedusa/Medusa#7983]
**Describe the bug**
It will not download anything

**To Reproduce**
1. Stop docker
2. Pull new version
3. Start docker

**Medusa (please complete the following information):**
- Branch:                 master                  
- Commit:                8f6b6665c778cb456899809877c3bc15a547abf6
- Version:                0.3.15
- Database:             44.15
- Python Version: | 3.7.6 (default, Dec 21 2019, 02:28:04)  [GCC 8.3.0]
- SSL Version: | OpenSSL 1.1.1d  10 Sep 2019
- OS: | Linux-5.6.3-arch1-1-x86_64-with
- Locale: | en_US.UTF-8

**Debug logs (at least 50 lines):**
```
2020-04-17 07:10:54 ERROR    FORCEDSEARCHQUEUE-MANUAL-364149 :: [8f6b666] DB error: OperationalError('no such table: scene_exceptions')
Traceback (most recent call last):
sqlite3.OperationalError: no such table: scene_exceptions
2020-04-17 07:10:54 ERROR    FORCEDSEARCHQUEUE-MANUAL-364149 :: [8f6b666] DB error: no such table: scene_exceptions
Traceback (most recent call last):
sqlite3.OperationalError: no such table: scene_exceptions
```

**Comment by medariox** [comment]
Read this: https://github.com/pymedusa/Medusa/issues/7976

**Comment by reemplazable** [comment]
@medariox but this is not a fix, How do I fix it? Send you the database file?

**Comment by p0psicles** [comment]
I'll give you instructions how to fix when I get home

**Comment by reemplazable** [comment]
@p0psicles thanks!

**Comment by p0psicles** [comment]
If you follow these instructions you can fix the issue your self.

1. Shutdown medusa
2. Make sure the process has completed stopped
3. Open a cmd prompt or bash, and navigate to the location where the `main.db` file resides
4. Run the following command: `python -c "exec(\"import sqlite3\ncurs=sqlite3.connect('main.db')\ncurs.execute('UPDATE db_version set db_minor_version = 14;')\ncurs.commit()\ncurs.close()\")"
5. Start medusa (wait until it has fully started)

The scene_exceptions table should have been recreated now

**Comment by reemplazable** [comment]
> If you follow these instructions you can fix the issue your self.
> 
>     1. Shutdown medusa
> 
>     2. Make sure the process has completed stopped
> 
>     3. Open a cmd prompt or bash, and navigate to the location where the `main.db` file resides
> 
>     4. Run the following command:
>        `python -c "exec(\"import sqlite3\ncurs=sqlite3.connect('main.db')\ncurs.execute('UPDATE db_version set db_minor_version = 14;')\ncurs.commit()\ncurs.close()\")"`
> 
>     5. Start medusa (wait until it has fully started)
> 
> 
> The scene_exceptions table should have been recreated now

IT is working!
THANKYOUUUU

**Comment by Jahislove** [comment]
same problem for me ,  fixing by Popsicles instructions work :)
