### ISSUE TITLE
Shazbat Provider - Increase duration parameter in rss url

### ISSUE THREAD

**Issue by dirkr07** [pymedusa/Medusa#8000]
**Is your feature request related to a problem? Please describe.**
The standard parameter in the rss url used is &fname=true&limit=100&duration=2+hours however the 2hrs is a bit short. i've often seen episodes appear on the tracker when it is not yet set as aired on the show in medusa. Therefor it doesn't get snatched.

**Describe the solution you'd like**
Either to increase the parameter to let's say 1 or 2 days or even better to make it configurable in the provider settings.

**Describe alternatives you've considered**
snatching manually always works ofcourse but not from within Medusa as it doesn't allow for backlog searches

**Comment by rafi-d** [comment]
I think this is available already, but per-show. Set show->edit->advanced->Air-Date Offset = -24 or -48 
Done...

**Comment by p0psicles** [comment]
Yes, as there are only a limited amount of shows that really are released early

**Comment by dirkr07** [comment]
Ok, get that. Only happens sometimes. 
But would be nice to search the provider in a longer timeframe in case the air date and real date are a bit close. 
Just increasing it a few hrs shouldn’t be an issue right? Just gives u more results to work with

**Comment by p0psicles** [comment]
Well it does. As most of the open providers also provide allot of "fake" Results. Waiting for a time where the chance of getting proper results reduces the risk on that

**Comment by p0psicles** [comment]
Also it limits the total load we put on those providers. So it's also a courtesy thing, we (sick*, sonar, etc) uphold.

**Comment by medariox** [comment]
Happens once in a lifetime and has a workaround, closing.
