### ISSUE TITLE
Medusa displays only some Seasons of a show

### ISSUE THREAD

**Issue by 3OW** [pymedusa/Medusa#8003]
**Describe the bug**
When clicking on a show, Medusa shows only some Seasons if the option "Use table pagination" is not activated. 

**To Reproduce**
1. If table pagination is active, turn it off and clear the browser cache or open a private instance.
2. Go to a show with many seasons like "The Simpsons"
3. Medusa will only display 3 out of 30 seasons.

**Expected behavior**
I would expect to see all 30 seasons.

**Screenshots**
![2020-04-23 02 02 27 localhost 83b1fbcb076d](https://user-images.githubusercontent.com/11493927/80045088-bf0fc080-8506-11ea-9aaf-cbf41b2205c3.png)

**Medusa**
Tested with under Windows:

- Branch: master
- Commit: 8f6b6665c778cb456899809877c3bc15a547abf6
- Version: 0.3.15
- Python Version 3.7.3
- Database: 44.15

I experience the same behaviour with the current version under Linux.

--
**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>
Medusa doesn't show related logs
</details>

**Additional context**
I used version 0.3.12 before and there it worked as expected.

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/7907
