### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Fox Channel (UK)

### ISSUE THREAD

**Issue by du5t1n55** [pymedusa/Medusa#8009]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: https://gist.github.com/b120949f0f714ed62e006a70c4c3fb45
### ERROR
<pre>
2020-04-22 22:49:10 ERROR    Thread_11 :: [8f6b666] Missing time zone for network: Fox Channel (UK)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
[Already in the list](https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L877)

**Comment by du5t1n55** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/0aa2d422627bbdfd4a3d9c18f1ffc263
### ERROR
<pre>
2020-04-28 22:15:37 ERROR    Thread_19 :: [d9c31da] Missing time zone for network: Fox Channel (UK)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by du5t1n55** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/2acd3d1389e612d4036b424fa93c9e7d
### ERROR
<pre>
2020-05-21 23:16:08 ERROR    Thread_0 :: [d9c31da] Missing time zone for network: Fox Channel (UK)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by du5t1n55** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-07-27 23:11:39 ERROR    Thread_0 :: [d9c31da] Missing time zone for network: Fox Channel (UK)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
