### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Bravo

### ISSUE THREAD

**Issue by du5t1n55** [pymedusa/Medusa#8013]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: https://gist.github.com/a19f12caa12642913c53e621efa29333
### ERROR
<pre>
2020-04-22 21:29:44 ERROR    Thread_15 :: [8f6b666] Missing time zone for network: Bravo
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
[Already in the list](https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L342)

**Comment by du5t1n55** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/728ec0c90108ee78a81fd1c8a87eff87
### ERROR
<pre>
2020-04-28 22:15:37 ERROR    Thread_19 :: [d9c31da] Missing time zone for network: Bravo
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by du5t1n55** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/7a3c5fdde25f70a3f9c1f0934e4ccf2b
### ERROR
<pre>
2020-05-21 23:16:08 ERROR    Thread_0 :: [d9c31da] Missing time zone for network: Bravo
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
