### ISSUE TITLE
Metadata files  being deleted unsure why

### ISSUE THREAD

**Issue by johnvick** [pymedusa/Medusa#8022]
Branch: masterCommit: d0c136d7a528a471b51676140bd35d24d97f65c6Version: 0.3.15Database: 44.15
--
Python Version: | 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-5.4.0-26-generic-x86_64-with
Locale: | en_US.UTF-8
  |  
  |  
User: | root
Program Folder: | /app/medusa
Config File: | /config/config.ini
Database File: | /config/main.db
Cache Folder: | /config/cache
Log Folder: | /config/Logs
Arguments: | --nolaunch --datadir /config
Web Root: | /medusa
Runs in Docker: | Yes

Metadata (.nfo, .jpg and .tbn) are being deleted - not sure why. What are "hanging associated files"?

Excerpt from log:

2020-04-25 04:42:40 INFO	SHOWQUEUE-REFRESH :: [d0c136d] 268356: Found hanging associated files for 'The Great British Sewing Bee' S01E05, deleting: '/mnt/Reality/The Great British Sewing Bee/Season 1/The Great British Sewing Bee - 1x05 - Episode 5-thumb.jpg, /mnt/Reality/The Great British Sewing Bee/Season 1/The Great British Sewing Bee - 1x05 - Episode 5.nfo'
2020-04-25 04:42:40 INFO	SHOWQUEUE-REFRESH :: [d0c136d] 268356: Looking for hanging associated files for: 'The Great British Sewing Bee' S01E05 in: /mnt/Reality/The Great British Sewing Bee/Season 1/The Great British Sewing Bee - 1x05 - Episode 5.avi

**Comment by medariox** [comment]
It is deleting files that were associated to episodes that don't exist anymore.

**Comment by johnvick** [comment]
But the episodes are still there...

**Comment by johnvick** [comment]
This just happened again with a different folder - all metadata files deleted video files intact. I am wondering if this may have something to do with MergerFS? All the files are stored on a different device to the one Medusa runs on, on an NFS share with MergerFS drive pooling. SnapRAID recovered all the files but I'm wondering what's going on.

**Comment by medariox** [comment]
Yes, this is because of the NSF mount. See https://stackoverflow.com/questions/21292365/python-os-path-exists-failing-for-nfs-mounted-directory-file-that-exists

You can try to enable the `Don't delete empty folders` option in post-processing settings.

**Comment by johnvick** [comment]
I've been using NFS shares in conjunction with Medusa for a few years and this has just started happening - the only thing I have changed in my setup is that I recently upgraded to OMV 5 from v 4. I'll try your suggestion - thanks for the help.

**Comment by johnvick** [comment]
I did your suggestion "Don't delete empty folders" and at same time fixed MergerFS file system as suggested in the Open Media Vault forum and problem has not recurred.
