### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Videoland

### ISSUE THREAD

**Issue by artificial-chaos** [pymedusa/Medusa#8023]
### INFO
**Python Version**: `3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: https://gist.github.com/780d4590c19509e420b6bdf1ff832171
### ERROR
<pre>
2020-04-26 11:23:02 ERROR    Thread_0 :: [8f6b666] Missing time zone for network: Videoland
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
[There are](https://en.wikipedia.org/wiki/Videoland) two tv-networks with a similar name: 
* [Videoland (Netherlands),](https://en.wikipedia.org/wiki/Videoland_(Netherlands)) a Dutch video on demand service owned by RTL Nederland  
* [Videoland Television Network](https://en.wikipedia.org/wiki/Videoland_Television_Network), a media company based in Taiwan  

What tv-show (tv-network) has made this error?  
What time zone should be chosen in this case?

**Comment by artificial-chaos** [comment]
It is Videoland (Netherlands), a Dutch video on demand service owned by RTL Nederland. Timezone UTC+2 hours.
