### ISSUE TITLE
Schedule page: only show a background image of a series with status "Continuing"

### ISSUE THREAD

**Issue by ArieKindicator** [pymedusa/Medusa#8031]
The schedule page displays a random show background image that changes at every refresh of this page.
It shows a background image of _all_ shows both with a "Continuing" and "Ended" status.
I would like to be able to set it to only to display background images of shows that have the status "Continuing". In other words it should nog display background images of "old" shows that already have been cancelled or ended years before and have the status "Ended" in Medusa.

**Comment by medariox** [comment]
I don't think this is ever going to happen, sorry.
