### ISSUE TITLE
Medusa deleting my failed downloads and then it complains...

### ISSUE THREAD

**Issue by vzografos** [pymedusa/Medusa#8041]
I am experiencing a strange behaviour with Medusa and I was trying to debug it, but I just cannot figure it out. Hope it is not something I have done wrong.
Here goes:
I have setup Medusa with nzbget and pos processes completed downloads just fine with NZBTOSICKBEARD script. 
However, when the download fails (due to incomplete etc) the postprocessing deletes the incomplete directories (from my NZBget InterDir) and then Medusa complains with a warning TORNADO :: [d9c31da] Post-processing attempted but directory doesn't exist: etc etc etc"

I have made sure that NZGget Parks the failed download dir and not delete it and that the NZBTOSICKBEARD sbdelete_failed option is set to 0. 

So something deletes the directories and I think it is the Medusa post processing 
If I disable the NZBTOSICKBEARD then the directories remain (but of course not post processed).

In Medusa I have enabled: Use Failed downloads and disabled: Delete failed in the Search Settings tab.

**Comment by medariox** [comment]
Please use the issue template.
