### ISSUE TITLE
Medusa deleted episode after 9 for "Dragon Ball Super"

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#8050]
Hello,

**Describe the bug**
Medusa deleted episode after 9 for "Dragon Ball Super" when i use scrapper tvdb (only for this serie)

**To Reproduce**
1. Go to 'Add shows'
2. Click on 'Add existing show', "Dragon Ball Super" for me
3. choose TVBD2'
4. Scan Files
5. For the season 1, all 14 episodes are found and rename and after episodes 10, 11, 12, 13 and 14 are deleted of my Synology Nas. Same issue for alle 5 seasons and reproduce two times

**Medusa 
 - OS: Synology
 - Branch: master
 - Commit: d9c31da063e6c4b4383749e19b27b13693a1b71e
 - Python version: 2.7.14
 - Database version: 44.15

**Debug logs (at least 50 lines):**
https://drive.google.com/file/d/1zt6sWWKTkEcCE6DaCWdG_7nNdMUwvbg_/view?usp=sharing

**Additional context**
Left : original files
Right : files after rename
https://zupimages.net/up/20/19/7sy5.png

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/wiki/Switch-to-Python-3

**Comment by akhlan** [comment]
I have Python 3.5.6-8 on my Synology for fews applications but Medusa use Python 2.7.14, it's not my choice...

**Comment by medariox** [comment]
Yes, you can use this package: https://github.com/SynoCommunity/spksrc/issues/3710#issuecomment-524808904
