### ISSUE TITLE
Medusa deleted episode after 9 for "Dragon Ball Super"

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#8051]
Hello,

**Describe the bug**
Medusa deleted episode after 9 for "Dragon Ball Super" when i use scrapper tvdb (only for this serie)

**To Reproduce**
1. Go to 'Add shows'
2. Click on 'Add existing show', "Dragon Ball Super" for me
3. choose TVBD2'
4. Scan Files
5. For the season 1, all 14 episodes are found and rename and after episodes 10, 11, 12, 13 and 14 are deleted of my Synology Nas. Same issue for alle 5 seasons and reproduce two times

**Medusa 
 - OS: Synology
 - Medusa Info:	Branch: master
 - Commit: d9c31da063e6c4b4383749e19b27b13693a1b71e
 - Version: 0.3.16
 - Database: 44.15
 - Python Version:	3.5.6 (default, Nov 25 2018, 14:24:15) [GCC 4.7.3 20130102 (prerelease)]
 - SSL Version:	OpenSSL 1.0.2n 7 Dec 2017
 - OS:	Linux-3.10.77-x86_64-with-glibc2.2.5
 - Locale:	en_US.UTF-8

**Debug logs (at least 50 lines):**
https://pastebin.com/1NE7eLVL

**Additional context**
Left : original files
Right : files after rename
https://zupimages.net/up/20/19/7sy5.png

**Comment by akhlan** [comment]
Who could help me ?

**Comment by p0psicles** [comment]
What's this folder Path? Renaming file from '/volume1/Videos/TV Series Animes/Dragon Ball Super/Saison 01/@eaDir/Dragon Ball Super_01x1.mkv@SynoResource' to '/volume1/Videos/TV Series Animes/Dragon Ball Super/Saison 01/@eaDir/Dragon Ball Super_01x01_Une récompense pour la paix. À qui reviennent les 100 millions de Zénis.mkv@SynoResource

Why is '@eaDir' in there? 
Please make sure your folder Structure is clean. `Show/Season 01/show.name.s01e01...mkv`

Then if still na issue. Enabled debug logs and send full logs.

**Comment by akhlan** [comment]
These folders are created by Synology himself but i don't know why and how? But, I don't think It's   the problem, I always see these hiddens folders and all work fine before (before what, i don't know ;) :D)

```
:/volume1/Videos/TV Series Animes/Dragon Ball Super$ cd \@eaDir/
:/volume1/Videos/TV Series Animes/Dragon Ball Super/@eaDir$ ls -al
total 32
drwxrwxrwx+ 2 root   root  4096 May 24 21:42 .
drwxrwxrwx+ 8 akhlan users 4096 May 24 21:31 ..
-rwxrwxrwx  1 root   root    82 May 23 18:25 Saison 01@SynoResource
-rwxrwxrwx  1 root   root    82 May 24 21:21 Saison 02@SynoResource
-rwxrwxrwx  1 root   root    82 May 24 21:25 Saison 03@SynoResource
-rwxrwxrwx  1 root   root    82 May 24 21:31 Saison 04@SynoResource
-rwxrwxrwx  1 root   root    82 May 24 21:42 Saison 05@SynoResource

:/volume1/Videos/TV Series Animes/Dragon Ball Super/@eaDir$ vi Saison\ 01\@SynoResource 

^@^E^V^G^@^B^@^@Mac OS X        ^@^B^@^@^@  ^@^@^@2^@^@^@ ^@^@^@^B^@^@^@R^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```

Some folder haven't these hidden folder but i don't know how they are create...

**Comment by akhlan** [comment]
so...

I have remake the error step by step and i put the debug log here
https://pastebin.com/GNtr5ZgL

Step by step in images

1 - https://zupimages.net/up/20/22/6sga.png
2 - https://zupimages.net/up/20/22/y39z.png
3 - https://zupimages.net/up/20/22/v1x3.png
4 - https://zupimages.net/up/20/22/br36.png
5 - https://zupimages.net/up/20/22/drj3.png
6 - https://zupimages.net/up/20/22/6f94.png

Who have an idea ?

**Comment by p0psicles** [comment]
That's not a debug log. That's info

**Comment by akhlan** [comment]
I don't see other log...

```
:/volume1/@appstore/medusa/var/Logs$ ls -al
total 504
drwxrwxrwx 2 sc-medusa medusa   4096 May 24 19:02 .
drwxr-xr-x 5 sc-medusa medusa   4096 May 28 10:07 ..
-rw-rw-rw- 1 sc-medusa medusa 501623 May 28 10:07 application.log
```

**Comment by p0psicles** [comment]
Youll have to enable debugging in config - general. And then restart

**Comment by akhlan** [comment]
I had see "Enable Debug" in General but I don't know we had need restart (should be write near Debug switch)

I can't put log in Pastebin, i haven't pro version to put more than 512Ko
https://www.transfernow.net/KirULi052020

Medusa deleted épisodes after 9 when i rename them

**Comment by medariox** [comment]
There is a bug with the associated files match logic. It will be fixed in the next release.

**Comment by akhlan** [comment]
It's not a simple "bug", i have lost all tv shown in all season after number 9...

**Comment by medariox** [comment]
Please contact @p0psicles for a full refund.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/8152
