### ISSUE TITLE
How activated https with a Synology and Medusa ?

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#8052]
Hello,

**Describe the bug**
It's not a bug but i would like activated https with my Medusa

**To Reproduce**
When I "Enable HTTPS", i have to field to need to be completed

HTTPS certificate : server.crt
file name or path to HTTPS certificate

HTTPS key : server.key
file name or path to HTTPS key

but i don't know what put in these fields... Who have activated https with Medusa on his Synology ?

**Medusa 
 - OS: Synology
 - Branch: master
 - Commit: d9c31da063e6c4b4383749e19b27b13693a1b71e
 - Python version: 3.5.6 (default, Nov 25 2018, 14:24:15) [GCC 4.7.3 20130102 (prerelease)]
 - Version: 0.3.16
 - Database version: 44.15

**Debug logs (at least 50 lines):**

**Additional context**

**Comment by Rouzax** [comment]
Easiest will be a reverse proxy with a Let's Encrypt certificate.
There a ton of setup guides for this.
For instance see https://www.google.com/search?q=synology+letsencrypt+behind+reverse+proxy

**Comment by akhlan** [comment]
I already use LetsEncrypt for my two Nas but I don't know how to set up SSL in Medusa, where is "server.crt" and "server.key"?

**Comment by p0psicles** [comment]
Use nginx with reverse proxy to medusa. The letsencrypt on nginx

**Comment by medariox** [comment]
server.crt and server.key can be in Medusa's main directory or you can also input a path.
