### ISSUE TITLE
[APP SUBMITTED]: Deluge: WebUI does not contain daemons

### ISSUE THREAD

**Issue by mitch71h** [pymedusa/Medusa#8086]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-05-11 03:07:27 ERROR    SNATCHQUEUE-SNATCH-134441 :: [d9c31da] Deluge: WebUI does not contain daemons
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
You've misconfigured your torrent client

**Comment by medariox** [comment]
Enable it in the Deluge settings.

**Comment by ssafhi** [comment]
### INFO
**Python Version**: `2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]`
**Operating System**: `Linux-4.15.0-101-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-05-31 02:43:58 ERROR    Thread_16 :: [d9c31da] Deluge: WebUI does not contain daemons
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
