### ISSUE TITLE
Search Providers - TorrentDay FreeLeech

### ISSUE THREAD

**Issue by skeelkat** [pymedusa/Medusa#8150]
The TorrentDay Provider already has a flag for "only download "FreeLeech" torrents." 
What would be great is a "**prefer** download of "FreeLeech" torrents.

Basically to allow the user the possibility to first check if a "FreeLeech" version is available, if not to fallback to a non-freeleech torrent.

**Comment by p0psicles** [comment]
Sounds Nice in theory. But in reality it won't help much. For backlog searches it could work. But 99÷ of your downloads come through daily searches. And then it will mostly get the non-freeleech first.

**Comment by skeelkat** [comment]
This is exactly what I was thinking.
I add an older show, Season 1 & 2 has freelech candidates, but Season 3 not. Download freechleech versions of 1&2 and use normal download for the rest.

simply changing the if statement in torrentday.py can accomplish this, but my python skill is non existent

**Comment by medariox** [comment]
Don't use the freeleech option, it will use both.
