### ISSUE TITLE
No bug, just to know

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#8154]
Hello,

it's just to know when the fix #8152 will be integrate ? one day, one week, one month ? it's just to know when I might have a fix I'm waiting for ;)

Rgds
akhlan

**Comment by play3rZA** [comment]
Hey akhlan,

It is merged to Develop, so if you really need it you can of course make use of the Develop branch until the next release.

From what I can see it's scheduled for the 0.3.17 release, but it doesn't have a due date yet, but 70% of the issues has already been closed, so it might not be too far off from a master release.

**Comment by akhlan** [comment]
How have you see that ?

**Comment by play3rZA** [comment]
In #8152 you can see at the top that it has been merged into the develop branch:
![image](https://user-images.githubusercontent.com/13823183/83265792-50d3b300-a1c2-11ea-8681-3d3b98da5758.png)

And on the right hand side you can see and click on the milestone which is the planned release version:
![image](https://user-images.githubusercontent.com/13823183/83265871-677a0a00-a1c2-11ea-9833-21798cea0b41.png)

**Comment by medariox** [comment]
As always, there isn't an exact ETA for the release. We are currently testing the new front end, so it might take some time.
