### ISSUE TITLE
Remove Show + delete files - does not delete the file(s) , access related issue?

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#8157]
Remove Show + delete files checked - does not delete the file(s). The show itself IS being removed correctly.
Following warnings is visible in the log (below).

**To Reproduce**
Just try it ? .. 

**Expected behavior**
Delete the file.
Since files are from torrents, and usually have other unrelated files "near" them (like subtitles etc) I like to propose an additional two choices:
1. Remove *all* related files too
2. Remove show folder

Unless all this is being done in the code already as default... 

**Screenshots**
No need

**Medusa (please complete the following information):**
 -

Medusa Info: | Branch:                 Unknown                  Commit:                 ee1b898d0f74750c4c265d077fcc0da73d17b41e                  Version:                 fatal: bad config line 1 in file .git/config                  Database:                 44.14

Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j  20 Nov 2018
OS: | Windows-10-10.0.18362-SP0

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2020-05-30 07:51:45 WARNING  SHOWQUEUE-REMOVE-SHOW :: [ee1b898] 353561: Unable to delete E:\Downloads\Bittorrent\The Enemy Within. Error: Error: 13: Access is denied
2020-05-30 07:49:54 WARNING  SHOWQUEUE-REMOVE-SHOW :: [ee1b898] 35017: Unable to delete E:\Downloads\Bittorrent\Devs. Error: Error: 13: Access is denied
2020-05-30 07:47:44 WARNING  SHOWQUEUE-REMOVE-SHOW :: [ee1b898] 270439: Show folder E:\Downloads\Bittorrent\The Affair does not exist. No need to delete


```
</details>

**Additional context**

**Comment by p0psicles** [comment]
That seems to really be a file access issue on those folders.

**Comment by rafi-d** [comment]
Do you mean only for me? or you can  reproduce it too?

**Comment by p0psicles** [comment]
This is 100% an issue only for you. Or anyone who doesn't have his access rights correctly setup. Else everyone would start complaining they can't remove shows

**Comment by rafi-d** [comment]
But I *CAN* remove shows, just not with the files (which is unchecked by default)... Maybe this is why people are not complain?... :)

**Comment by medariox** [comment]
It's just you.
