### ISSUE TITLE
Checkboxes in Search Providers is broken on Chrome on Android.

### ISSUE THREAD

**Issue by kerosyn** [pymedusa/Medusa#8159]
**Describe the bug**
Can't enable or disable checkboxes in Search Providers on Chrome on Android. Both in native view and while displaying as desktop site.

**To Reproduce**
1. Go to 'Search Providers'
2. Click on any of the provider checkboxes
3. See nothing happen

**Expected behavior**
Be able to select or unselect different providers.

**Medusa:**
 - OS: OSMC 2020.03-1
 - Branch: master
 - Commit: d9c31da063e6c4b4383749e19b27b13693a1b71e
 - Python version: 3.5.3
 - Database version: 44.15

**Additional context**
Reordering seems fine, so I am able to drag and drop the different providers into different orders. But completely unable to enable/disable new sources. Running latest (81.0.4044.138) version of Chrome on Android.

**Comment by p0psicles** [comment]
Can't reproduce. 
It's working on a non-mobile?

**Comment by kerosyn** [comment]
Don't have a PC to try with. Have Medusa installed on a raspberry Pi with no desktop mode. I will try to provide video later today once I'm back home. I know I've had this issue before, but don't remember if I found a work around or not.

**Comment by p0psicles** [comment]
Probably some provider added is bugged. Or making the page crash. You should try connecting from pc and run devtools (f12) and check for errors

**Comment by kerosyn** [comment]
No PC to use, so can't test that unfortunately.
