### ISSUE TITLE
add MEDUSA_COMMIT_HASH and MEDUSA_COMMIT_BRANCH to exported release

### ISSUE THREAD

**Issue by cheese1** [pymedusa/Medusa#8160]
**Is your feature request related to a problem? Please describe.**
it would be great to have MEDUSA_COMMIT_HASH and MEDUSA_COMMIT_BRANCH available in your released packages, too. i create rpm-packages for medusa and there is no trace for the correct MEDUSA_COMMIT_HASH/BRANCH in your released tar.gz without that information 
http://8081/config/
has no chance to display correct data.

**Describe the solution you'd like**
there is a VERSION-Variable in medusa/common.py
maybe one could set the said variables at the same time you set VERSION?

**Describe alternatives you've considered**
alternative is manually checking in github, which is errorprone and imho not the best solution

my packages are here (for fedora 32):
http://www.nosuchhost.net/~cheese/fedora/packages/32/x86_64/Medusa.html

**Comment by sharkykh** [comment]
`BRANCH` for [releases](https://github.com/pymedusa/medusa/releases) is always `master`.
As for `COMMIT_HASH`, the `tar.gz` on releases is auto-generated by GitHub.
I do know for a fact both the `tar.gz` and `zip` files generated by GitHub have a comment inside them containing the commit hash.

I can tell you that with Python, it can be read using:
For `tar.gz`:
```py
from tarfile import TarFile
with TarFile.open('/path/to/Medusa-0.3.16.tar.gz', 'r:gz') as tar:
    commit_hash = tar.pax_headers.get('comment')
```
And for `zip`:
```py
from zipfile import ZipFile
with ZipFile('/path/to/Medusa-0.3.16.zip', 'r') as zipf:
    if zipf.comment:
        commit_hash = zipf.comment.decode('utf-8')
```

**Comment by p0psicles** [comment]
Lol TIL

**Comment by sharkykh** [comment]
@p0psicles I needed to figure it out for `mvt` 😅 
https://github.com/sharkykh/medusa_vendor_tools/blob/a903b1bd87b7a0e1945f72c3d9fce4decee143eb/mvt/vendor.py#L265-L297

**Comment by cheese1** [comment]
Wow
Thanks for pointing that out. Branch is ok and clear now :)
The pax header is great to know. Thanks.
