### ISSUE TITLE
[support] Requesting a copy of .\.git\config

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#8175]
Hi,
Can you please attach/paste  for me a copy of the .git/config file? I believe mine was accidentally corrupted (getting a warning on a  "bad" 1st line). I can see indeed some Gibberish inside instead of text...

Thanks!

Rafi

**Comment by p0psicles** [comment]
Why not run a New clone? 
Then move over *.db, config.ini. and cache folder.

**Comment by rafi-d** [comment]
Well, I prefer not to replace the existing version, so not to spend much time now on  merging my modifications again. Sadly I am doing this every 2-4 new versions ... 
I thought pasting it here for me it quick/easy for you.

**Comment by OmgImAlexis** [comment]
Just clone into a temp directory and copy the file over.
