### ISSUE TITLE
Uninstall Medusa

### ISSUE THREAD

**Issue by ArcTuruzz** [pymedusa/Medusa#8176]
Hi
Since I could not find a previous topic regarding this, I assume it is really easy and I'm just a total noob.
I need to upgrade Medusa from version 0.2.13 to 0.3
However when trying to install the windows installer, I am told that Medusa is already installed on the system, and that I need to remove it before I install the new version.
However, I can't find a way to uninstall Medusa 0.2.13

Any assistance would be much appreciated.

**Comment by p0psicles** [comment]
Latest version is 0.3.16. It's not located in your software management?

**Comment by ArcTuruzz** [comment]
> Latest version is 0.3.16. It's not located in your software management?

I meant 0.3, it was a typo.
I forgot to mention I it is in Windows.
It is, however I get attached warning when trying to uninstall.
![Capture](https://user-images.githubusercontent.com/66487395/83910190-6456bf00-a76a-11ea-80ba-e4c785098fca.PNG)

**Comment by p0psicles** [comment]
It's normal to install in the onedrive? Sorry I don't have much experience with the window installer

**Comment by ArcTuruzz** [comment]
> It's normal to install in the onedrive? Sorry I don't have much experience with the window installer

I don't know. It has been working fine until the Python 2.7 (i think it was) is no longer supported and Medusa don't want to start anymore.
So I thought I would reinstall Medusa so that maybe it would work again.

I installed it on Onedrive, so that it would be availible if my C drive crashed or I have to format my C drive and reinstall windows.

**Comment by p0psicles** [comment]
Well I wouldn't do that. Medusa separates program and data. You can comfigure it to have the data (db, config.ini, logs, cache) in a separate folder. That could be in your onedrive. It looks like the uninstaller is removed from its original location?

**Comment by p0psicles** [comment]
Your using the latest installer? I can take a look tomorrow, in what's required to clean it up manually tomorrow

**Comment by ArcTuruzz** [comment]
> Your using the latest installer? I can take a look tomorrow, in what's required to clean it up manually tomorrow

Yes, seems somehow the installer folder is missing. Don't know why though :/
Would appreciate the assistance. Last option is to format C: and reinstall the whole server. Which is A LOT of work.
Would appreciate your guidance on how to manually remove medusa.
It has been working until Python 2.7 was no longer supported.

**Comment by p0psicles** [comment]
Py2.7 will be unsopporded from okt. Right night we only put a deprecation warning

**Comment by p0psicles** [comment]
step by step. you will need to remove some keys in regedit.
* Delete base program folder. C:\Medusa\Medusa.(you can save the Data and Python folder)
* open regedit (requires admin rights)
* Delete this key: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{991BED37-186A-5451-9E77-C3DCE91D56C7}_is1
* The key should include information used by Apps & Components (which you can use to uninstall apps).
* Delete this key: Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Medusa
* The key is used for the service
* Now restart your system and you should be able to install using medusa installer 0.6

**Comment by p0psicles** [comment]
I would also not recommend to install again in oneDrive. Just use your C:\ or D:\
Then after you can move your Data folder to your oneDrive if you want.

**Comment by p0psicles** [comment]
So my C:\Medusa\Medusa folder is equivalent of you C:\Users\Server\OneDrive\Medusa. So you should have a folder like C:\Users\Server\OneDrive\Data? But i'm not sure, as you used to install using an old installer.

**Comment by ArcTuruzz** [comment]
I think I will format my C: and install the whole server again. I have some other issues as well.
It's been a long time since I did this, so would appreciate some guidance.
Is there anything special I need to think about?
Do I still need to install Python seperatly?
Which files do I need to backup to keep my settings?

**Comment by ArcTuruzz** [comment]
> So my C:\Medusa\Medusa folder is equivalent of you C:\Users\Server\OneDrive\Medusa. So you should have a folder like C:\Users\Server\OneDrive\Data? But i'm not sure, as you used to install using an old installer.

I think I will format my C: and install the whole server again. I have some other issues as well.
It's been a long time since I did this, so would appreciate some guidance.
Is there anything special I need to think about?
Do I still need to install Python seperatly?
Which files do I need to backup to keep my settings?

**Comment by p0psicles** [comment]
Main.db, config.ini. maybe the other *.db files. The medusaInstaller will install all requirements.
