### ISSUE TITLE
eztv provider only fetches first 30 records

### ISSUE THREAD

**Issue by smalldog666** [pymedusa/Medusa#8182]
**Describe the bug**
The new EZTV provider only fetches first 30 records as the EZTV API defaults to a limit of 30 when no limit parameter is passed. Furthermore, the EZTV api has a upper fetch limit of 100 per page, hence to get more/all records, a page parameter needs to be passed as well (See https://eztv.io/api/)

**To Reproduce**

Go to https://eztv.io/api/get-torrents?imdb_id=2741602
This will fetch the list of torrents for The Blacklist. First rline will show number of torrents available (436 at this time), the limit of the number fetched (default to 30), and page number (default to 1)

Go to https://eztv.io/api/get-torrents?imdb_id=2741602&page=1&limit=30
This will produce the same result with explicit setting of limit and page number

Go to https://eztv.io/api/get-torrents?imdb_id=2741602&page=1&limit=100
This will produce a much larger result set (of 100)

https://eztv.io/api/get-torrents?imdb_id=2741602&page=5&limit=100
This will fetch page 5, with a result set of 36

https://eztv.io/api/get-torrents?imdb_id=2741602&page=6&limit=100
This will fetch page 6, with a result set of 0 (as there are not more than 500 results)

**Expected behavior**
More than 30 results should be returned. As some torrents may have a very large set of results, a reasonable cutoff may be 600 torrents (ie 6 pages)

**Screenshots**

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64] ubuntu 18.04.4 LTS
 - Branch: [e.g. master, develop] master
 - Commit: [e.g. c65ca2]
 - Python version: [e.g. 3.6.8] 3.6.9
 - Database version: [e.g. 44.12]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by smalldog666** [comment]
For reference, here is an alternative implementation I had written a few months back for my own use that iterates through 6 pages of results. Apologies for not contributing earlier as I had not realized there were others interested in using eztv.

[eztv.py.v1.3.zip](https://github.com/pymedusa/Medusa/files/4750547/eztv.py.v1.3.zip)

**Comment by p0psicles** [comment]
We very much Welcome pull requests

**Comment by medariox** [comment]
Waiting for PR.
