### ISSUE TITLE
Separate trakt watchlist from manual import

### ISSUE THREAD

**Issue by VilDegard** [pymedusa/Medusa#8196]
**Describe the bug**
First of all... massive thanks for this solid app! No really a bug, rather to check if that's feasible-- I want to separate the addition of shows I do manually (through Medusa) from the watchlist I keep on Trakt. I want the show I add in with the Trakt watchlist gets downloaded by Medusa, and the others manual additions get downloaded but not sync with my Trakt playlist. 

**To Reproduce**
See picture:
<img width="1090" alt="screen medusa trakt" src="https://user-images.githubusercontent.com/25377606/84842534-4d06b400-b03d-11ea-8e30-1366188e409f.png">

**Expected behavior**
I thought sync watchlist would only deal with shows in the watchlist, not add into the watchlist the shows I manualy select on Medusa.

**Screenshots**
See above

**Medusa (please complete the following information):**
 - OS: Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-16.04-xenial
- Branch: master 
- Commit: d9c31da063e6c4b4383749e19b27b13693a1b71e 
- Version: 0.3.16 
- Database: 44.15
- Python Version: 2.7.12 (default, Apr 15 2020, 17:07:12) [GCC 5.4.0 20160609]

**Debug logs (at least 50 lines):**
Not required unless necessary.

**Additional context**
I share my Plex server with friends, I want to separate the list of shows I download for them from the shows I follow. I used Sickchill to trakt my watchlist automatically.

**Comment by p0psicles** [comment]
I missed this One. Sorry

**Comment by VilDegard** [comment]
No worries at all
