### ISSUE TITLE
Reddit Follow Up - Search by TV ID

### ISSUE THREAD

**Issue by purevertigo** [pymedusa/Medusa#8210]
**Describe the bug**
Error - "No results found, try a different search."

**To Reproduce**
1. Add Show
2. enter tvdb show id in box

**Expected behavior**
find a certain show.

**Screenshots**
NA

**Medusa (please complete the following information):**
 - OS: windows 10
 - Branch: master
 - Commit: d9c31da063e6c4b4383749e19b27b13693a1b71e
 - Python version: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
- Database version: Version: 0.3.16

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>
2020-06-22 23:21:09 INFO	APIv2-Thread-21 :: [d9c31da] Error searching for show. term(s): ['266189'] indexer: tmdb error: Show search failed in getting a result with reason: Not found
2020-06-22 23:21:08 INFO	APIv2-Thread-21 :: [d9c31da] Error searching for show. term(s): ['266189'] indexer: tvmaze error: Show search failed in getting a result with reason: Show 266189 not found
2020-06-22 23:17:10 INFO	APIv2-Thread-24 :: [d9c31da] Broken providers found: ['']
2020-06-22 23:17:10 WARNING	APIv2-Thread-24 :: [d9c31da] Config patch ignored {'showDefaults': {'subtitles': False}}
</details>

**Additional context**

**Comment by medariox** [comment]
![search](https://i.imgur.com/fmw2PjB.png)

**Comment by p0psicles** [comment]
Did you try the search exactly as shown in the screenshot? I also tested it. Works fine

**Comment by purevertigo** [comment]
yes tested again, doesn't work still. This is really confusing as to why it is not working for me.

**Comment by p0psicles** [comment]
Enable debug logging and restart. 
Fill in the form as shown in the screenshot. But only select tvdb from the indexers select. 
Search and post relevant logs

**Comment by purevertigo** [comment]
here you go

https://gist.github.com/purevertigo/542b37ce1c316b8ea6c9d4bf86b7767e

**Comment by p0psicles** [comment]
Nope. That's not a debug log. Only has INFO log lines.
Enable debug in config -> general -> advanced tab -> logging
Then restart medusa.
Then search
Now go to your Log folder inside your medusa's data folder. Probably [Medusa install directory]/Logs. Open application.log and make sure to copy/paste everything starting from the timestamp of when you did the search to the end.
Post the log.

**Comment by purevertigo** [comment]
Sorry for the mistake. I have relinked to the actual log here.

https://gist.github.com/purevertigo/fcb5c46db4dddb18438837c49582bb48

thanks

**Comment by p0psicles** [comment]
Nope. Only a little piece of logs of the startup of the application. Nothing on the search itself

**Comment by purevertigo** [comment]
Sorry not sure what happened.

Here you go.

https://gist.github.com/purevertigo/eb49e591b32ea5b36c103b6f66d4e950

**Comment by p0psicles** [comment]
Hmm that looks okay.
Can you create a screenshot of your search with the error?

**Comment by purevertigo** [comment]
Here is the screenshot you asked for

![Annotation 2020-06-23 152125](https://user-images.githubusercontent.com/6506461/85363885-4e683d00-b565-11ea-8ce4-d66919360c25.jpg)

**Comment by p0psicles** [comment]
I just realized. We haven't released a new version in a while. The searching by id is currently only in develop branch. 

Checkout develop and this will work.

**Comment by purevertigo** [comment]
🤣 There goes all that troubleshooting. haha. Cheers, but I'll wait to add that show, and would rather not tempt fate with the other branch.

**Comment by medariox** [comment]
Why would you even need it? The show is easy to find by its name.

**Comment by purevertigo** [comment]
@medariox that wasn't actually the show I wanted, but a demo show because the other show was impossible to find with the current version  state of medusa search for me.

**Comment by p0psicles** [comment]
Also when you look for the show and only set iindexer to tvdb?

**Comment by purevertigo** [comment]
correct @p0psicles
