### ISSUE TITLE
Medusa has stopped showing any shows

### ISSUE THREAD

**Issue by slipshot2020** [pymedusa/Medusa#8225]
Hi - sorry, novice at this but learning- slowly!

Medusa had a list of shows.  All working fin for the past few months.  Now it has dropped them all, and is empty yet all data files remain in place.  Nothing else has been changed.  Log files when I restarted today show:

2020-07-01 10:14:35 WARNING  MAIN :: [] git rev-parse HEAD returned : fatal: unterminated line in .git/packed-refs: ...
2020-07-01 10:14:35 WARNING  MAIN :: [] git describe --tags --abbrev=0 None returned : fatal: unterminated line in .git/packed-refs: ...

Any idea what I can or should do?  I have tried to shutdown Medusa to reinstall a previous build.db, but Medusa just says it's shutting down and then never actually does - hours later it's still the same.

**Comment by medariox** [comment]
`build.db` doesn't exist in Medusa. What you can do is take a backup of your `main.db` and `config.ini`. Start over and restore these files.

**Comment by slipshot2020** [comment]
Thanks - should I uninstall from Windows and reinstall or just let the new installation overwrite?

and many thanks...

**Comment by p0psicles** [comment]
I would uninstall. Make sure your git config is valid

**Comment by slipshot2020** [comment]
Ok - uninstalled and reinstalled.  Did a check and the installer did not create a  build.db file.

I have reinstalled (copied over) both the main.db and config.ini files and yet still I don't get any shows visible.

**Comment by p0psicles** [comment]
can you get our discord? link in the Readme

**Comment by slipshot2020** [comment]
Sorry - cannot find the Readme part - in Medusa or on github?

**Comment by p0psicles** [comment]
https://discord.gg/zMdAdUK
