### ISSUE TITLE
Manage episodes....

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#8228]
First...  downloads don't always happen in the best resolution you want, so you settle for what you can get.
I like ti get 1080p when ever possible, for some reason unknown to me it seems like we like to download the same episodes over and over at that resolution.

What I have done in the past with SickChill is I go to managed and change the status from Downloaded 1080p to Archive 1080p
Here in Medusa I can't find a way to do that, All I can do is set all downloads to Archived and that's not what i want, I want the 480p still to be replaced by the 1080p download.
I looked at mass update but that doesn't deal with episodes..  
Only way I can seem to do it is go to each show and sort the downloaded and then change them,  That's a never ending struggle.

So I would like to see a Feature where you can also select the resolution,  
Example would be Downloaded and then 1080p or 720p etc..

I don't care about the media, (blueray, dvd, web, etc)... not sure why those are even options since most download are just Web Downloads, and Blue ray doesn't tell you anything other then what type of disk it may have come from, since anything can be put on a blue ray disk, even an old 240p movie.

**Additional context**

**Comment by medariox** [comment]
This is already possible and works as expected with allowed and preferred qualities. Eg. setting allowed to ANY and preferred to 1080p and 720p. Read: https://github.com/pymedusa/Medusa/wiki/Qualities-Changes#here-is-how-it-works
