### ISSUE TITLE
Multiple Post-Processing Dir

### ISSUE THREAD

**Issue by EzraBlint** [pymedusa/Medusa#8234]
**Is your feature request related to a problem? Please describe.**
I use rTorrent to manage and move completed downloads, this is done in association with Labels i.e Anime it moves to a folder called Anime, TV, Movies, Software etc... I am unable to fine tune these so Anime and TV are in a sub directory for Medusa to specifically hone in on, as such it checks all other directory necessarily and can throw warning/errors at files it does not like.

**Describe the solution you'd like**
Adding the option to specify multiple post processing directories (be it as a + icon where you can add multiple specification areas or even keep as is but separate via use of commas/other special character), I feel this would help greatly in the versatility of post processing with rTorrent to say the least and maybe other torrent clients but also just add to the fact that Medusa does a very good job at being able to keep TV and Anime separate throughout its life cycle, this is the only "bottleneck" in the whole process. 

**Describe alternatives you've considered**
I have considered external scripts to do this for me but this does not seem to be a straight forward process if at all possible, Medusa does not seem to recognize a soft symlink and hardlinks are also not an option. I have however stumbled upon "mount --bind dir1 dir2" which seems to be a solid work around in the mean time, however overall I just figure multiple post processing directories will be a lot cleaner as well as a nice additional feature to add to medusa's package/experience

**Additional context**
Unsure if I was clear in my explanation but by specification areas I meant the white field in the below screenshot:

![image](https://user-images.githubusercontent.com/8010518/87201076-c8364f80-c2f5-11ea-9698-99811f4c62c1.png)

Edited - Grammatical errors and updated to be more accurate with current testings

**Comment by OmgImAlexis** [comment]
If you’re running this in a container map just the subdirectories to the container and then point medusa to the parent of those.

For example passing though /downloads/tv and /downloads/anime then point it to /downloads it’ll then be able to skip the other directories as they’re not mapped in the container.

**Comment by EzraBlint** [comment]
@OmgImAlexis Awesome, thanks! that's done exactly as I needed, definitely need to get used to the extra dynamic that is docker, It just didn't enter my brain that container patch will create sub directories... nonetheless greatly appreciate the help. 

Not sure if the feature request would still be worthwhile though overall? for those that do not have/use docker but I can definitely say your solution works perfectly for the docker situation.

**Comment by medariox** [comment]
This works for all setups.
