### ISSUE TITLE
List sorting on Shows list page not preserving sorting on page reloads

### ISSUE THREAD

**Issue by Yellow1144** [pymedusa/Medusa#8235]
Hey all.. Thanks for the continued good work.

In this latest beta version I have, i noticed the changes to the shows page and while I kind of liked some things better before, I can get used to the new way they are. 

I have always primarily sorted my shows list using Banner layout, alphabetically and secondarily by status, which creates the condition where the shows are all sorted alphabetically with all the continuing shows at the top, followed by the ended shows that are listed alphabetically underneath. This still works, that is, until you reload the page, whereby the shows are still sorted alphabetically but the status column has reverted to the default such that the ended shows are mixed in with the continuing shows again. In prior versions this list sorting was always preserved.

The same thing happens in small poster layout but in the Simple layout it works properly and this sorting is preserved after page reloads.

Branch: develop
Commit: 8257200e73450509fe310b8a45c6780f47fc8716
Version: 0.3.16
Database: 44.15
--
Python Version: | 3.7.8 (default, Jun 29 2020, 05:46:05) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.15.0-106-generic-x86_64-with-LinuxMint-18.3-sylvia

Nothing in the logs..

**Comment by p0psicles** [comment]
I think it's already fixed in a new branch https://github.com/pymedusa/Medusa/tree/feature/vueify-snatch-selection.
At least sorting by two columns should now be saved in a cookie

**Comment by p0psicles** [comment]
@Yellow1144 if you can point out what you liked before, I can tell you if it's planned to be added. Or we can consider it.
In the branch it should be fixed. With the new tables. You can select multiple columns, by clicking on the first and holding shift key when clicking the second.

**Comment by Yellow1144** [comment]
Well I have a rather long show list and I find with the new list it loads them quite a bit slower. Also I really likes how the search field worked before. The interface just seems slower

**Comment by Yellow1144** [comment]
I just updated to the latest version. Aside from the update process seeming to go quite a bit slower than it used to, it is difficult to see if and when it has actually updated. The screen used to go black and indicate that it was in the process of updating before loading the show list once the update was complete. Now the screen never changes, it just keeps showing wherever I am, until the notifications pop up, I don't know that anything has happened. 

After the update the issue I mentioned above still exists. The list sort does not persist after a page reload. Also what you mentioned above I am not clear on, about selecting multiple columns in new tables. What tables are you speaking of? It doesn't work in the shows list (Banner layout)

Also, I noticed that I can no longer choose to have the articles A and THE excluded in the sort. The switch for this on the
 General > Interface tab does nothing. No matter how it is set. After 68 Whiskey in my list should be Absentia not A Discovery of Witches. I hate having to go way down the list to find titles hiding behind the word THE. 

Maybe I should open a different issue for the above.

**Comment by p0psicles** [comment]
Did you Check out the Branch I referenced to, or develop? 

I'll check for excluding the `A` and `The`.

Regarding the speed. Before we loaded every thing in the backend. So for large shows you had to wait a long time, before things started rendering. Now you get a page loaded much faster, after which the shows are pulled in.

For now I'm only making changes in the vueify-snatch-selection branch. So that branch is most up-to-date

**Comment by p0psicles** [comment]
The banner, simple and small poster layouts will be able to select by two columns

**Comment by Yellow1144** [comment]
No, sorry, didn't read properly. I am on develop. Is there a way I can change the git branch within Medusa to the one you specified (the Git options only allow for Master or Develop) or do I just clone it to another spot, disable my current, copy my config and database over and run that one? Please excuse my ignorance..

Would be nice if it was just as simple as switching branch on the Github section. 

One thing I learned from way back in the early Sickbeard days is to mirror my entire install folder to a backup location so if something goes bad after an update...... I keep 3 versions back

**Comment by p0psicles** [comment]
I would recommend getting familiar with the git commands. Like git checkout, git pull, git fetch.. Etc. If you don't want, no prob. Just wait for the changes to get into develop. But being on a feature branch will allow you to give us more feedback. So that helps us allot. 

If one Windows, you can install tortoiseGit. It's a UI for the git commands

**Comment by Yellow1144** [comment]
Yeah, I need to learn more about git. Have bigger priorities ATM, I'll just wait. Nope, ditched windows for Linux and never going back. I'll read man pages to start.

**Comment by p0psicles** [comment]
It's in develop now

**Comment by p0psicles** [comment]
I'll fix the sorting of `the` and `a` in a New PR sometime coming week

**Comment by Yellow1144** [comment]
Hey..
I just updated to the latest Develop version and the The/A problem persists. Changing the setting on General > Interface > The/A has no effect on my show list. No matter the setting The Alienist shows way down the list instead of at the top, A Million Little Things is near the top when it should be with the M shows. 

Still a problem..

**Comment by p0psicles** [comment]
Using the poster layout?

**Comment by Yellow1144** [comment]
Using the Banner layout..

But I discovered something. When changing the setting, I would just scroll down to the bottom of the page and click the last Save Changes button on the page. I just noticed that there was a Save Changes button at the bottom of the User Interface section. When I clicked that to save, the The/A sorting works properly on all layouts EXCEPT the Banner layout.

**Comment by p0psicles** [comment]
Ooh lll check that
