### ISSUE TITLE
Anime Checkbox visable depending on indexer

### ISSUE THREAD

**Issue by StijnDC** [pymedusa/Medusa#8240]
**Describe the bug**
When adding a show the "Anime" checkbox will be visible depending on which Indexer is used.
When an anime has not been picked up by certain indexers it is not possible to add the show to Medusa as the Anime option is not present.

**To Reproduce**
1. Add new show, for this example i'm using the new "Uzaki-chan Wants to Hang Out!" Anime
2. Go through the steps using "TVDBv2" and you will find the Anime check present
3.  Add the show using "TMDB" and you will find the Anime Check is missing

This is also the case for the "TVMaze" indexer

**Expected behavior**
If possible, the anime check should be available at all times, since now certain shows cannot be added as Anime.

**Screenshots**
![image](https://user-images.githubusercontent.com/5908942/87394652-59384f80-c5b0-11ea-8eae-a16ba4fd0275.png)
![image](https://user-images.githubusercontent.com/5908942/87394684-63f2e480-c5b0-11ea-99c6-ef58a940cc4b.png)
![image](https://user-images.githubusercontent.com/5908942/87394712-6ce3b600-c5b0-11ea-83a2-5433e96d7e94.png)
![image](https://user-images.githubusercontent.com/5908942/87394740-75d48780-c5b0-11ea-8738-150172d0b3c3.png)

**Medusa (please complete the following information):**
running on a Synology NAS

Medusa Info:
| Branch: master
Commit: d9c31da063e6c4b4383749e19b27b13693a1b71e
Version: 0.3.16
Database: 44.15
-- | --
Python Version: | 2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]
SSL Version: | OpenSSL 1.0.2n 7 Dec 2017
OS: | Linux-4.4.59+-x86_64-with-glibc2.2.5
Locale: | Unknown.Unknown

**Comment by p0psicles** [comment]
Anime listed on indexer and anime releases, often differ in season and episode numbering. 
For this we use thexem.de. they only map for the tvdb. 

So this is by design
