### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: AXN España

### ISSUE THREAD

**Issue by ledderi** [pymedusa/Medusa#8244]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1255`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-07-19 05:59:50 ERROR    Thread_0 :: [d9c31da] Missing time zone for network: AXN España
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by HPMSGEN8** [comment]
### INFO
**Python Version**: `3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]`
**Operating System**: `Linux-3.10.105-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-07-18 15:04:43 ERROR    APIv2-Thread_23 :: [fcb5a19] Missing time zone for network: AXN España
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
