### ISSUE TITLE
Medusa failing to grab new eps, with scene exception?

### ISSUE THREAD

**Issue by jaxjexjox** [pymedusa/Medusa#8253]
DOCKER Build:  latest tag, has been occurring for a long time, across multiple builds.
No error messages, just odd behaviour:
Can recreate, every week

My wife watches, unfortunately 90 day fiance series.

I have added the show to medusa and I have a valid search provider. My daily search interval is configured to 40 minutes.

The official name of the show is "90 Day Fiancé" and I've even configured a scene exception of "90 Day Fiance" (note the e!)

**most important part** clicking the 'manual search' button **always returns several results** by the time my wife asks "where is XYZ???!"

Yet every Tuesday (my time in Aus) the episode is not auto downloaded. _Medusa is fine grabbing multiple other shows without any issue_. The only difference is they don't have a scene exception configured for naming.

Is anyone else seeing this behaviour?

NOTE: when I did this, the torrents were already 6 hours old and I do not have "enable search delay" turned on either.

**Comment by medariox** [comment]
Are you sure the episodes you find with manual search match the requested quality?

**Comment by jaxjexjox** [comment]
It would be pretty embarassing if that's the case - I must admit one is set to 1080p (and I've already snatched it)
but this mornings screwup, I see this
"90 Day Fiance Happily Ever After S05E06 Ultimatums and Ugly Truths WEBRip x264-<REDACTED>"

Interesting, there's no resolution specified (annoying!) none the less, the file is ok.
I've change my pref to any, I'll see if it'll snatch it.

**Comment by medariox** [comment]
ANY does NOT include Unknown quality, you will need to use Custom and manually add Unknown.
