### ISSUE TITLE
Wrong Renaming for resolution lower than 480

### ISSUE THREAD

**Issue by segator** [pymedusa/Medusa#8263]
![image](https://user-images.githubusercontent.com/2348131/88428987-31d65380-cdf6-11ea-97bb-d9ba18b55429.png)

The left is detected as SDTV and right as N/A, can we change this to be detected as SDTV too? anything lower than 720 should be SDTV

**Comment by medariox** [comment]
It's sub SDTV quality, so no, it can't be detected as such.

**Comment by segator** [comment]
Can we at least put something not N/A?

**Comment by medariox** [comment]
You can already manually change it to whatever you'd like.

**Comment by segator** [comment]
can you be so kind to tell me where I could change this?

**Comment by medariox** [comment]
Select the episode and use the drop-down on the right (top) side of the show page:
![img](https://snapr.pw/i/ed7901e6af.png)

**Comment by segator** [comment]
ooh I see, but this is per episode i need something more global than i can chose depends of the resolution if is SDTV HDTV or whatever

**Comment by p0psicles** [comment]
We don't have the LDTV (lower definition tv) classified in medusa. Which is normally used to define resolutions below SDTV. So this is not possible.
