### ISSUE TITLE
ShowUpdater is no longer pulling updates. (Since 0.3.16 update)

### ISSUE THREAD

**Issue by darkzabat** [pymedusa/Medusa#8264]
The showupdater process is showing that it ran at its scheduled run time, but no shows are updating and there are no logs produced showing that the showupdater attempted to update any shows.

To Reproduce

Wait till the scheduled run of showupdater
Look for logs by filtering for showupdater logs and show queue (update) log. There are no logs for the last 24hr.
Run a full update on a show with new episodes or seasons.
New episodes and seasons for that show appear after running full update on show.
Expected Behavior
The showupdater should run daily and pull in all newly added episodes and seasons for all shows.

Medusa (please complete the following information):

OS: Linux-5.7.9-100.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
Branch: master
Commit: d9c31da063e6c4b4383749e19b27b13693a1b71e
Python version: 3.7.7
Database version: 44.15
Logs:
![Capture](https://user-images.githubusercontent.com/63563964/88441649-9974aa80-cdc6-11ea-969d-68591b4269e0.PNG)

**Comment by darkzabat** [comment]
Same behavior as  #7961 which was rooted in issue #7963

**Comment by medariox** [comment]
Post the relevant debugs logs as requested in the issue template and a screenshot of your server status.
