### ISSUE TITLE
Add Advanced Settings For Show - Preferred Words

### ISSUE THREAD

**Issue by LeeThompson** [pymedusa/Medusa#8266]
Medusa currently has some great advanced options for rejecting unwanted (or incorrect) releases with ignored words and weighting with even more detail with "required words" but this proposal is for "preferred" words which would not weight as heavily as required (and could be absent) but would help scoring which releases to grab.

This would work, UI wise, identically to required and ignored words.     The user could specify a particular group, but unlike required, if that group did _not_ release that particular episode, the program would proceed as normal.       The user could also list their favorite groups in the list, weighing those releases above others.     (Obviously if a preferred word release ends up being marked as failed, that would eliminate them from being picked.)

**Additional context**

Example:
_(Note, I'm not sure how this actually words in the backend, this is just for illustration purposes.   It may not be desirable or feasible to score items above 100.) _

Normal Usage:
```
Score  Release
100.00 SHOWNAME.S05E06.720p.BluRay.X264.1-GROUP_A-Obfuscated
100.00 SHOWNAME.S05E06.720p.BluRay.x264-GROUP_B
100.00 SHOWNAME.S05E06.720p.BluRay.x264-GROUP_C
100.00 SHOWNAME.S05E06.720p.BluRay.x264-GROUP_D
100.00 SHOWNAME.S05E06.720p.BluRay.x264-GROUP_C
```

Preferred Word Usage:   ( Preferred Words: GROUP_B,GROUP_C )
```
Score  Release
100.00 SHOWNAME.S05E06.720p.BluRay.X264.1-GROUP_A-Obfuscated
150.00 SHOWNAME.S05E06.720p.BluRay.x264-GROUP_B
100.00 SHOWNAME.S05E06.720p.BluRay.x264-GROUP_C
150.00 SHOWNAME.S05E06.720p.BluRay.x264-GROUP_D
100.00 SHOWNAME.S05E06.720p.BluRay.x264-GROUP_C
```

Where preferred words were simply not found or eliminated due to failure:
```
Score  Release
100.00 SHOWNAME.S05E06.720p.BluRay.X264.1-GROUP_A-Obfuscated
100.00 SHOWNAME.S05E06.720p.BluRay.x264-GROUP_D
```

**Comment by p0psicles** [comment]
We already have this feature implemented?

**Comment by LeeThompson** [comment]
Not that I've seen, there's ignored words and required words.

**Comment by p0psicles** [comment]
There currently isn't a per show option. It's in config - search settings - episode search

**Comment by LeeThompson** [comment]
Be _much_ more useful as a per show option.

**Comment by p0psicles** [comment]
Yeah but that's a nice to have. And that request has already been made. Low priority for me right now though.

**Comment by LeeThompson** [comment]
@p0psicles Fair enough!  Love Medusa!

**Comment by p0psicles** [comment]
Thing also is.. The preferred words aren't really that useful. As it will only attempt to check if a result is more preferred then the other, while here are no allowed and/or preferred matches at the time.

Like at 3pm first results come in. Early releases that are not preferred. Then it will pick those at the time. But with that the quality is satisfied, and it will no longer evaluate more preferred results.

So 2 hours later your preferred result comes in. It will not be snatched. 

You could work around this by configuring like a search delay of 4 hours. Hoping your preferred result comes in within that time span. 

That's the reason why I haven't extended the functionality of preferred words
