### ISSUE TITLE
Medusa won't start

### ISSUE THREAD

**Issue by jwsadler** [pymedusa/Medusa#8273]
New install on windows 2012 R2.  Medusa just sits at the Loading Page.  

Windows FW is off.

I have attempted to uninstall/reinstall multiple times.  Sometimes using admin.  Have also changed the service to use admin user / interact with desktop to no avail.  Please help.

[config.txt](https://github.com/pymedusa/Medusa/files/4988060/config.txt)

[application.log](https://github.com/pymedusa/Medusa/files/4988050/application.log)

**Comment by p0psicles** [comment]
Should be running on http://localhost:8081

**Comment by jwsadler** [comment]
It is running on localhost:8081.  Is there something in the config that suggests otherwise?

**Comment by p0psicles** [comment]
No, should be acceptable. Else prob something like firewall issue. Did you try different browsers?

**Comment by medariox** [comment]
How are you installing Medusa? How are you starting it? Have you tried starting Medusa from console with Python?

**Comment by jwsadler** [comment]
I just used the windows installer FF browser.

Interestingly enough it works when I use the develop branch.

**Comment by medariox** [comment]
We are going to release develop to master soon, so you will be able to use master again I guess.
