### ISSUE TITLE
Medusa won't start after fresh install

### ISSUE THREAD

**Issue by homegreewn** [pymedusa/Medusa#8274]
Running Debian 9+ installed medusa following this guide: https://github.com/pymedusa/Medusa/wiki/Medusa-installation-Debian-Ubuntu

After installation medusa opened and I restored backup.

After reboot medusa wont start. After running status update I get this:
```
pi@raspberrypi:/ $ sudo systemctl status medusa
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-07-29 19:14:01 -05; 1s ago
  Process: 6138 ExecStart=/usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medus
 Main PID: 6138 (code=exited, status=1/FAILURE)

Jul 29 19:14:01 raspberrypi systemd[1]: medusa.service: Service RestartSec=100ms expired, scheduli
Jul 29 19:14:01 raspberrypi systemd[1]: medusa.service: Scheduled restart job, restart counter is 
Jul 29 19:14:01 raspberrypi systemd[1]: Stopped Medusa Daemon.
Jul 29 19:14:01 raspberrypi systemd[1]: medusa.service: Start request repeated too quickly.
Jul 29 19:14:01 raspberrypi systemd[1]: medusa.service: Failed with result 'exit-code'.
Jul 29 19:14:01 raspberrypi systemd[1]: Failed to start Medusa Daemon.
```  
Any help is greatly appreciated.

**Comment by p0psicles** [comment]
Try to start manually. Use the same use and datadir

**Comment by homegreewn** [comment]
How do I start manually?

**Comment by p0psicles** [comment]
Can you post the content of your medusa.service file? 

And is this data dir correct? : /opt/medus
Else `/usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medus`

**Comment by homegreewn** [comment]
> Group=medusa
> 
> Type=simple
> ExecStart=/usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa
> TimeoutStopSec=25
> KillMode=process
> Restart=on-failure
> 
> [Install]
> WantedBy=multi-user.target

And yes it is the data dir. This are the contents. I deleted cache.db per another suggestion in a post but didn't do anything.

> pi@raspberrypi:/opt/medusa $ ls
> cache                           lib                          main.db.v44.9
> cache-20200729_173726           Logs                         MANIFEST.in
> cache.db.bak-20200729_173723    main.db                      medusa
> cache.db.v1.None                main.db.bak-20200729_173723  package.json
> cache.db.v2.None                main.db.v42                  readme.md
> CHANGELOG.md                    main.db.v43.1                renovate.json
> config.ini                      main.db.v44.1                requirements.txt
> config.ini.bak-20200729_173723  main.db.v44.10               runscripts
> CONTRIBUTING.md                 main.db.v44.11               setup.cfg
> COPYING.txt                     main.db.v44.12               setup.py
> Dockerfile                      main.db.v44.13               SickBeard.py
> dredd                           main.db.v44.14               start.py
> ext                             main.db.v44.2                tests
> ext2                            main.db.v44.3                themes
> ext3                            main.db.v44.4                themes-default
> failed.db                       main.db.v44.5                tox.ini
> failed.db.bak-20200729_173723   main.db.v44.6                yarn.lock
> failed.db.v2.None               main.db.v44.7
> hooks                           main.db.v44.8

This is what I get after I run `/usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa`

> pi@raspberrypi:/opt/medusa $ /usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa
> Traceback (most recent call last):
>   File "/opt/medusa/start.py", line 6, in <module>
>     from medusa.__main__ import main
>   File "/opt/medusa/medusa/__init__.py", line 24, in <module>
>     initialize()
>   File "/opt/medusa/medusa/init/__init__.py", line 34, in initialize
>     _urllib3_disable_warnings()
>   File "/opt/medusa/medusa/init/__init__.py", line 150, in _urllib3_disable_warnings
>     import requests
>   File "/opt/medusa/ext/requests/__init__.py", line 44, in <module>
>     import chardet
>   File "/opt/medusa/ext/chardet/__init__.py", line 19, in <module>
>     from .compat import PY2, PY3
> ModuleNotFoundError: No module named 'chardet.compat'

**Comment by p0psicles** [comment]
Can you try installing chardet? Like pip3 install chardet?

**Comment by homegreewn** [comment]
> pi@raspberrypi:~ $ pip3 install chardet
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (3.0.4)

Look like it's installed already?
I don't mind uninstalling and reinstalling medusa if that's an option because I have my backup, I'm just not sure how to do it. I tried to reinstall ontop of the installation but ofcourse that didn't do anything.

**Comment by medariox** [comment]
Uninstall it. Medusa already includes all required dependencies.

**Comment by medariox** [comment]
pip3 uninstall chardet

**Comment by homegreewn** [comment]
oh I thought you meant unisntall medusa. 

Strange, it says nothing to unisntall.

> pi@raspberrypi:~ $ pip3 uninstall chardet
> Not uninstalling chardet at /usr/lib/python3/dist-packages, outside environment /usr
> Can't uninstall 'chardet'. No files were found to uninstall.

**Comment by homegreewn** [comment]
Up

**Comment by medariox** [comment]
Try `pip3 uninstall chardet --user`.

**Comment by homegreewn** [comment]
That didn't do anything.

```
pi@raspberrypi:~ $ pip3 uninstall chardet --user

Usage:   
  pip3 uninstall [options] <package> ...
  pip3 uninstall [options] -r <requirements file> ...

no such option: --user
```

Also tried --medusa and --pi, just in case you meant to put a user in user and got the same result. So just to be clear it's NOT possible to uninstall/erase medusa and do a fresh install?

**Comment by medariox** [comment]
Of course, just delete the whole Medusa folder and download it again.

**Comment by homegreewn** [comment]
Couldn't delete folder, that's where the problem is.

> rm: cannot remove 'medusa/ext/oauthlib/oauth2/rfc6749/tokens.py': Structure needs cleaning

seem like I have file system corruption, any chance you know the next step to take? At least I know now it's not a medusa issue.

**Comment by p0psicles** [comment]
Plenty of advice if you google that. Probably need to unmount and run file system check
