### ISSUE TITLE
Download episodes releases for which subtitles in the selected language have been created

### ISSUE THREAD

**Issue by PrzemekSkw** [pymedusa/Medusa#8275]
**Is your feature request related to a problem? Please describe.**
It's not a problem but it will made my life easier

**Describe the solution you'd like**
It would be very helpful if Medusa will downloading episodes releases that have already been subtitled in my language. Sometimes when I download episode and then search for subtitles I see that subtitles don't match. So I must download another release for example episode.s01e01.web-rip.x264-XFL because only for that there're subtitles in polish language.

Regards,
Przemek

**Comment by p0psicles** [comment]
I don't know if we should want that. Then we need to start hammer the subtitle sites. Or at least search them before there is a release? 

Then we can just as well ask them now to start using captcha or the new cloudflare everywhere.

**Comment by PrzemekSkw** [comment]
Hi, thanks for answer. I know that will be problematic so don't bother. You make great work with Medusa. Can You tell me how can I  sync Medusa to my Trakt.tv account because I can't find any option for that?

**Comment by p0psicles** [comment]
In config - notifications, third tab

**Comment by PrzemekSkw** [comment]
Thank You very much.
