### ISSUE TITLE
Unable to connect to Medusa! message

### ISSUE THREAD

**Issue by etaardvark** [pymedusa/Medusa#8278]
**Describe the bug**
Intermittently my medusa instance generates the following message

Unable to connect to Medusa!

whenever trying to update or add a new show.

Originally i was running qmedusa on a qnap nas, but i have just switched to a Pi4 which seemed to make a difference for a while, but seems to have started happening again, as i've gone through and corrected the paths for the shows.

when this is happening, the python3 process is consuming 100% cpu of one core. Same problem occurs when trying to enable the debug log (without restarting medusa)

**To Reproduce**
1. Go to Add Show
2. The Add show page opens *partially* then receive a JS popup with the following message "Unable to connect to Medusa!"

**Expected behavior**
Not get the error message

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Raspbian / QNAP QTS
 - Branch: master
 - Commit: [e.g. c65ca2]
 - Python version: 3.7.3
 - Database version: [e.g. 44.12]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
This can happen when medusa is running multiple background tasks parallel. There are too many variables here. You could start with logging in to ssh and open the Logs/application.log with a tail -f application.log at the time when this happens. And see what's running. You might want to enable debug logging in config - general. (Restart  medusa). 

The thread that runs most often is daily search. But others can also run like the subtitle search or postprocessing thread.

**Comment by etaardvark** [comment]
watched the log when it locked up and got this 
Looks to have spawned 10 threads that fail to find the show when post processing
[debug.log](https://github.com/pymedusa/Medusa/files/5010980/debug.log)

**Comment by p0psicles** [comment]
Some weird things going on. Don't know where the Unable to find the show in database are coming from. But something looks fishy there. Probably locking up all the apiv2 threads. But that's not from postprocessing?

**Comment by p0psicles** [comment]
Also debugging is not enabled

**Comment by etaardvark** [comment]
yes - debugging is enabled in the UI now. When it generated that log it was before i had restarted, but thought it was interesting. 
I'm stripping the install back, deleted all my shows and gradually adding them back, just to see if that makes a difference

**Comment by p0psicles** [comment]
Also try to keep your postprocessing folder as clean as possible. Better to use nzbToMedia. As that won't scan the complete folser all the time

**Comment by etaardvark** [comment]
Seems to have been sorted by switching to Wired networking. Looks like whenever there were multiple threads going on accessing the network, everything got bound up in I/O Wait causing the timeouts. It was fine most of the time
