### ISSUE TITLE
Medusa snatch SD quality not 720p as it should

### ISSUE THREAD

**Issue by PrzemekSkw** [pymedusa/Medusa#8282]
**Describe the bug**
I have set Medusa to search 720p quality episodes and Medusa snatched SDTV quality.

![Zrzut ekranu z 2020-08-03 19-41-48](https://user-images.githubusercontent.com/25219988/89211749-80d47380-d5c2-11ea-9913-5cc5723847f0.png)
![Zrzut ekranu z 2020-08-03 19-42-36](https://user-images.githubusercontent.com/25219988/89211757-8631be00-d5c2-11ea-9875-a3af942af416.png)

Can somebody explain me what is wrong?
Regards,
Przemek

**Comment by medariox** [comment]
The problem is that quality is set using preferred and allowed qualities, not with preferred or ignored words. Read our Wiki beefore opening issues: https://github.com/pymedusa/Medusa/wiki/Show-settings-explained

**Comment by PrzemekSkw** [comment]
@medariox I set quality to HD720p like in Wiki but Medusa change to SDTV quality.

**Comment by medariox** [comment]
Please try to understand the difference between Quality settings and Word settings. You need to set the allowed quality of the Show to 720p.

**Comment by PrzemekSkw** [comment]
@medariox When I add my library I set every show to HD720p but now I see some shows are in SD. Is there a way to set all shows to 720p without manual editing every single show?

**Comment by medariox** [comment]
Yes, go in Manage > Mass Update 
Select the shows to edit

**Comment by PrzemekSkw** [comment]
Thank You.
