### ISSUE TITLE
Season folders are not created for newly added shows

### ISSUE THREAD

**Issue by ThrustVector** [pymedusa/Medusa#8288]
**Describe the bug**
Medusa is not creating season folders for new shows even though Season Folders is enabled in show settings.

**To Reproduce**
1. Add show with all episodes as skipped (for test purposes)
2. Select 1 Episode and set to wanted
3 After download and automatic post-processing find that episode is placed directly under show folder and not in a season folder (I had to force manual post-processing because I had tested before an automatic post-processing was then ignoring show)

**Expected behavior**
Automatic creating of Season folder and placement of episiode in apropriate folder.

**Screenshots**
N/A

**Medusa (please complete the following information):**
 - OS: Debian 10 (4.19.0-9-amd64)
 - Branch: master
 - Commit: d9c31da063e6c4b4383749e19b27b13693a1b71e
 - Python version: 3.7.3
 - Database version:  44.15

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
See attached file!
[Log_medusa_season_problem.txt](https://github.com/pymedusa/Medusa/files/5027701/Log_medusa_season_problem.txt)
```
</details>

**Additional context**

**Comment by ThrustVector** [comment]
Testing have been done with TV Show Yellowstone but this occurs for any newely added TV Show

**Comment by medariox** [comment]
Your episode naming pattern needs to include the season folder for it to work.

**Comment by ThrustVector** [comment]
Can not ever remeber to have changed that myself. So you meen instead of currently beeing %SN - S%0SE%0E - %EN I change that to Season %0S/%SN - S%0SE%0E - %EN ?

**Comment by medariox** [comment]
Yes, exactly.

**Comment by medariox** [comment]
The default naming patterns will always include season folders in the next release (see https://github.com/pymedusa/Medusa/pull/8289), so this won't happen anymore.
