### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Hallmark Movies & Mysteries

### ISSUE THREAD

**Issue by mrlt8** [pymedusa/Medusa#8303]
### INFO
**Python Version**: `3.7.4 (default, Oct  6 2019, 22:38:36) [GCC 8.3.0]`
**Operating System**: `Linux-4.4.227-1-ARCH-armv5tel-with-arch`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-08-07 05:16:40 ERROR    Thread_0 :: [d9c31da] Missing time zone for network: Hallmark Movies & Mysteries
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mrlt8** [comment]
Network logo for `Hallmark Movies & Mysteries` is also missing:
![61522](https://user-images.githubusercontent.com/67088095/89585662-794bdf00-d7fb-11ea-99cc-4cc1ae458855.png)

**Comment by medariox** [comment]
Added. Please open a new issue for the logo.
