### ISSUE TITLE
Sorting by "downloads" different in 0.4.0

### ISSUE THREAD

**Issue by rssfed23** [pymedusa/Medusa#8327]
**Describe the bug**
Not 100% sure if this is a bug or intended, but prior to 0.4.0, when clicking "downloads" to sort on the home screen, the list of shows would sort showing shows with missing episodes at the top, so it was easy to see any show missing some episodes.
Now, it's sorting quite differently, and shows with some eps set to wanted show halfway down the list and it's as if it's sorting by total episodes and showing missing eps at the top of that list depending on what the total number of eps should be (see screenshot). 

**To Reproduce**
1. Go to show list
2. Click on downloads column to sort

**Expected behavior**
That the show lists sorts as it was before in a logical order of shows with missing eps at the top (ordered by least no missing to most no missing) then by total number of episodes with all obtained.

**Screenshots**
Screenshot of how its sorting now:
<img width="188" alt="Screenshot 2020-08-15 at 17 21 27" src="https://user-images.githubusercontent.com/12484127/90316724-04c02100-df1c-11ea-87d6-f41f9c211d96.png">

**Comment by p0psicles** [comment]
I couldn't really get a mathematical formula in the old implementation, so I went with counting downloaded + snatched / total. But if you have ideas, I'd be happy to implement them

**Comment by p0psicles** [comment]
If we would order by missing eps. Meaning total - downloaded. Should we use a percentage or absolute value?
