### ISSUE TITLE
Sort by Next Ep/Prev Ep in Firefox

### ISSUE THREAD

**Issue by Twisted-** [pymedusa/Medusa#8329]
**Describe the bug**
Sorting by Next Ep/Prev Ep in firefox does not give the desired result. It seems to work fine in chrome. Results are never the same either.

**To Reproduce**
1. Go to 'Showlist' using Firefox
2. Click on 'the column header for Next Ep'
3. Look at the shows and the order they are in
4. Click on the column header for Next Ep again, to reverse the order, still not ok
5. Click on the column header a last time to get back to the order in step 3, find that it is yet another order it is put in.

**Expected behavior**
The list in the order of Next Ep

**Medusa (please complete the following information):**
 - OS: Server Ubuntu 20.04, client: both Ubuntu 20.04 and Windows 10 using Firefox 79.0 on both.
 - Branch: master
 - Commit: 471c8ed43f6125ebdcd471c260757d8c7cae2ad4
 - Python version: 3.8.2
 - Database version: 44.16

**Debug logs (at least 50 lines):**
Let me know if you need those, seems to be a front end problem, so I'm guessing no debug logs are needed?

**Additional context**
Works fine using chrome.

**Comment by mkleiman312** [comment]
Unexpected sorting behavior on Chrome (84.0.4147.125) as well, but only in the "Next Ep" column.

**Comment by spattersTatt** [comment]
Can confirm broken in Firefox... running nightly: 81.0a1 (2020-08-14) (64-bit)

![image](https://user-images.githubusercontent.com/44591802/90325694-f62a4600-dfbd-11ea-8fd1-9dbb1f63c5c7.png)

**Comment by p0psicles** [comment]
Should be fixed with a new release 0.4.1 (coming out today or tomorrow) #8337
