### ISSUE TITLE
Wasted screen space

### ISSUE THREAD

**Issue by eddywitkamp** [pymedusa/Medusa#8342]
**Describe the bug**
The latest version introduced a different layout with a lot of wasted screen space at the top.
Is that really necessary?

**To Reproduce**
Screenshot of Simple layout
![image](https://user-images.githubusercontent.com/6422683/90346245-bdbf5200-e027-11ea-956d-3d4ebefaf6c7.png)

**Medusa:**
Branch: master
Commit: 471c8ed43f6125ebdcd471c260757d8c7cae2ad4
Version: 0.4.0
Database: 44.16
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-10-10.0.18362-SP0
Locale: | nl_NL.cp1252

**Comment by eddywitkamp** [comment]
When removing the "Series" show list, it just show "uncategorized" instead of disappearing

**Comment by p0psicles** [comment]
No, your right. But you shouldn't remove the series shore list. I'll make a change to his the series show list title, if that's the only one
