### ISSUE TITLE
Home Page Not Sorting Correctly by "Next Ep." Column

### ISSUE THREAD

**Issue by gmusgrave** [pymedusa/Medusa#8347]
**Describe the bug**
The interface for the Home Page has changed, and the "_Next Ep._" column no longer sorts properly. Next episode ascending is my default sort so I can see upcoming shows, in order.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on the "_Next Ep._" column header to sort by this column
2. Click again to reverse the sort

**Expected behaviour**
The show list should sort by ascending next episode date, then change to descending on the next click.

**Screenshots**
Here is what my list looks like when I click on the "Next Ep." column (note that in spite of the ascending sort icon in the lower right corner of the column heading, the list is actually sorted by show name):

![Capture 1](https://user-images.githubusercontent.com/803620/90398260-bc5d4c00-e05e-11ea-8212-33386110e53e.JPG)

Here is what my list looks like when I click a second time on the "Next Ep." column (note that in spite of the descending sort icon in the upper left corner of the column heading, the list is actually sorted by show name, but starting lower down the list):

![Capture 2](https://user-images.githubusercontent.com/803620/90398496-270e8780-e05f-11ea-90ee-64fce553d037.JPG)

Here's a section of the same list much farther down the page:

![Capture 3](https://user-images.githubusercontent.com/803620/90398593-4dccbe00-e05f-11ea-98f0-14ce5205e9b6.JPG)

And even farther down the page:

![Capture 4](https://user-images.githubusercontent.com/803620/90398627-5de49d80-e05f-11ea-989f-1f026d4ee0cc.JPG)

This one's really odd... after testing the other columns to see if they sort properly (they all do except for "Quality"), I once again clicked on "Next Ep." and got this list – **almost** correct, **except** for the first two entries, and the next episode dates are out of order:

![Capture 5](https://user-images.githubusercontent.com/803620/90398779-92f0f000-e05f-11ea-9b08-6a4f7c817fee.JPG)

**Medusa (please complete the following information):**
 - OS: Windows-7-6.1.7601-SP1
 - Branch: master
 - Commit: 471c8ed43f6125ebdcd471c260757d8c7cae2ad4
 - Python version: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
 - Database version: 44.16

**Comment by p0psicles** [comment]
fixed in develop branch
