### ISSUE TITLE
Search dialog gone in Medusa Shows List

### ISSUE THREAD

**Issue by PrzemekSkw** [pymedusa/Medusa#8349]
**Describe the bug**
Yesterday I noticed that I cannot search in my TV Shows list. Search dialog is gone.

**To Reproduce**
1. Restart Medusa
2. Try to update

**Expected behavior**
Search in my saved shows list.

**Screenshots**
![Zrzut ekranu z 2020-08-17 17-21-10](https://user-images.githubusercontent.com/25219988/90414358-f86ccd00-e0af-11ea-978e-3e5a1ac63fd6.png)

**Medusa (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch: master,
 - Commit: 471c8ed43f6125ebdcd471c260757d8c7cae2ad4
 - Python version: 3.8.2
 - Database version: 44.16

Regards.

**Comment by p0psicles** [comment]
It's gone on purpose. It's still there if you use one of the table layouts.

It's a technical limitation of one of the used components. vue-isotope. I tried to get it to work. But it was very buggy.

I'll try to give it another go, after next release

**Comment by PrzemekSkw** [comment]
OK, thanks for info.
Regards.

**Comment by cheese1** [comment]
+1
would be great to get that back
i use the simple layout and filtered the list  alot in different columns.

**Comment by p0psicles** [comment]
That's a different issue

**Comment by stevensonnz** [comment]
+1 Would love that feature back for poster layout. Use it daily and updated recently and it disappeared.
