### ISSUE TITLE
Font color changed after 0.4.0 update

### ISSUE THREAD

**Issue by 1sourCream** [pymedusa/Medusa#8350]
**Describe the bug**
Font color changed after 0.4.0 update

**To Reproduce**
Happens after update of 0.4.0

**Expected behavior**
font color should be black

**Screenshots**
![Capture](https://user-images.githubusercontent.com/39070356/90431275-c3a04c00-e096-11ea-8eff-4c69f1c6302d.JPG)

**Medusa (please complete the following information):**
 - OS: [e.g. unraid 6.8.3 x64]
 - Branch:  master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76
 - Python version: 3.8.3
 - Database version: 44.16

**Comment by 1sourCream** [comment]
Yesterday this was closed with no response. Is it fixed or can someone help me please?

Thanks

**Comment by p0psicles** [comment]
It's fixes in developing. I'll release shortly

**Comment by 1sourCream** [comment]
> It's fixes in develop branch. I'll release shortly

Thank you for the update.
