### ISSUE TITLE
Sorting by downloads has changed

### ISSUE THREAD

**Issue by Simoofus** [pymedusa/Medusa#8357]
Issue:
I always like to sort my show list by downloads so I can see whats missing.
The sorting seems to have defaulted to a text sort now. It used to be (like a few days ago) numerical and all shows missing episodes would sit at the top like a to do list. 

If you click on dowloads it now sorts like this as an example:
0/10
1+5/6
10/10
103/103
12/12
186/199
22/28
23/23

So it looks like its reading the entire string and sorting as text. All other columns still working as they should.
Love the software thank you!

**Comment by p0psicles** [comment]
Fixed in develop
