### ISSUE TITLE
Cosmetic Bug - History Page Black Text?

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#8363]
**Describe the bug**
just noticed this, i know the text used to be white, but now its black & its barely readable (Dark Theme)

**Expected behavior**
used to be white text, not barely readable black

**Screenshots**
![Screen Shot 2020-08-20 at 2 20 26 am](https://user-images.githubusercontent.com/2242880/90662695-05deae80-e28c-11ea-99e4-3d850238701d.jpg)

**Medusa (please complete the following information):**
 - OS: macOS 10.15.6
 - Branch: develop
 - Commit: a7236eeb11bc7ad2b0ff053e37f6287c5ec69f07
 - Python version: 3.8.5
 - Database version: 44.16

**Comment by medariox** [comment]
Fixed in develop.
