### ISSUE TITLE
Restart of Medusa is not working on Synology NAS

### ISSUE THREAD

**Issue by ejc1967** [pymedusa/Medusa#8368]
**Describe the bug**
When you do an update or a manual restart of Medusa, Medusa shuts down but doesn't start up again. You have to manually start it.

**To Reproduce**
Perform a restart 😊

**Expected behavior**
For Medusa to automatically start up again after shutting down when performing a restart or update.

**Medusa:**
Branch: master
Commit: 20915b56d64dc7522e484f326d9cfe7449a73193
Version: 0.4.1
Database: 44.16

Python Version:	3.7.7 (default, Aug 18 2020, 20:42:48) [GCC 4.9.3 20150311 (prerelease)]
SSL Version:	OpenSSL 1.0.2n 7 Dec 2017
OS:	Linux-3.10.105-x86_64-with-glibc2.2.5
Locale:	en_US.UTF-8

**Additional context**
This is not relate to the latest change, it hasn't worked for me since I installed it, so for a couple of versions.

I did get it to work by doing the following:

If you change line 17: **if text_type(pid) != text_type(app.PID):** from **medusa/system/restart.py** back to from before change #4982, so to: **if str(pid) != str(app.PID):**   then the restart works just fine.

Side-note: same format is still used in current **medusa/system/shutdown.py**
17    def stop(pid):
18        if str(pid) != str(app.PID)

**Comment by dirkr07** [comment]
Same issue here but couldn't really be bothered with it as it's not like I (need to) restart medusa too often :)
Thanks for the workarround tho!

**Comment by p0psicles** [comment]
Cool. You can create a pull request. Well accept.

**Comment by ejc1967** [comment]
This issue can be closed for me, the latest update fixed it.

Thanks for all the good work !

**Comment by medariox** [comment]
Thanks for the update!
