### ISSUE TITLE
Home Sorting strange since update to vue.js (Poster view - sort by next episode)

### ISSUE THREAD

**Issue by dirkr07** [pymedusa/Medusa#8370]
**Describe the bug**
When the home screen is shown as Poster (could be others too) and the sorting is set to "Next Episode" the order used to be
1) Next episode that will be aired
2) Continueing
3) Ended

Now with the update to the new vue.js system it seems that the sorting is working differently.
I currently have (for example) several shows that are airing soon and they are shown on top. However it then becomes a mix of continueing/ended and also the random next episode.
e.g. I currently have "lucifer" with is set to air today all the way at the bottom in between some continueing shows.

The continueing/ended part is not a big deal but it does get tricky/annoying when the next episodes are just sorted in between.

FYI. I am using TVMaze for these as indexer

Perhaps linked to #8337 ?

**To Reproduce**
1. Show as Poster
2. Sort by Next Episode
3. Scroll and see what happens :)

**Expected behavior**
To have next episodes first, then Continueing and then Ended

**Screenshots**
![image](https://user-images.githubusercontent.com/10185229/90863019-9c939400-e38e-11ea-8f67-e3f3d4cfd230.png)

![image](https://user-images.githubusercontent.com/10185229/90862512-cf895800-e38d-11ea-9e12-c383e4183056.png)

**Medusa (please complete the following information):**
OS: Synology DSM
Medusa Info: |
Branch: master
Commit: 20915b56d64dc7522e484f326d9cfe7449a73193
Version: 0.4.1
Database: 44.16
-- | --
Python Version: | 3.5.6 (default, Nov 25 2018, 14:24:15) [GCC 4.7.3 20130102 (prerelease)]
SSL Version: | OpenSSL 1.0.2n 7 Dec 2017
OS: | Linux-4.4.59+-x86_64-with-glibc2.2.5
Locale: | en_US.UTF-8

Perhaps linked to feature/fix-save-shows-showlist ? (https://github.com/pymedusa/Medusa/pull/8337)

**Comment by p0psicles** [comment]
Now after episodes that have a next air date, it'll sort bij prev air date

**Comment by dirkr07** [comment]
Ah so meaning if it was a show that was on hiatus for a while it might get mixed in with Ended/Continuing shows that have prev eps that were aired after the last ep of the currently running show? (if that makes sense)

**Comment by p0psicles** [comment]
Yes

**Comment by dirkr07** [comment]
I assume then that once there is an airdate for the next episode it will move back in to the current listing.
Thanks!
