### ISSUE TITLE
Too Much Empty Space at Top

### ISSUE THREAD

**Issue by hernandito** [pymedusa/Medusa#8372]
Hi... this is not quite a bug...  but it's bugging. I really love my Medusa!

There is too much empty space at the top... There is too much vertical scrolling when using my iPad.  IMHO things could be a little more condensed and remain a fresh and modern UI.

The "_Filter Show Name_" worked much better before when it was directly above the list of shows table.

The words "_Show List_" can be moved up, and all the buttons and drop boxes can be put on the **same** line...

![Image 5](https://user-images.githubusercontent.com/787317/90934014-945b4900-e3ce-11ea-8a87-4d72d95f8fc3.png)

**The same is true on the show page:**

![med-1a](https://user-images.githubusercontent.com/787317/90935662-b609ff80-e3d1-11ea-8c4d-2fe74defe3e9.png)

Please consider reverting the episode search method from before.

Thank you.

H.

**Comment by hernandito** [comment]
Very nice... ! 

I did not know you could also tab the different lists... that makes sense. The way I am configured, I cant come up with a need for the different lists/folder.

**Comment by p0psicles** [comment]
Im separating running shows.

**Comment by hernandito** [comment]
You separate running shows from ones that have been canceled?  

On a side note:
I have made some additional css tweaks myself... I like this more compact/concise UI. I feel that I get a wide overview of my collection, appreciating the magnitude, while also being able to focus on details. I have only edited 3 css files (light theme) and the medusa-runtime.js

![_medusa2](https://user-images.githubusercontent.com/787317/90989747-2d729700-e56a-11ea-9bb2-4d5653a543b6.png)
![_medusa1](https://user-images.githubusercontent.com/787317/90989763-3e230d00-e56a-11ea-9d78-bd5413182e64.png)
![_medusa3](https://user-images.githubusercontent.com/787317/90989756-34010e80-e56a-11ea-9657-f6a3efc3f223.png)

If you want to test it, rename the files from .txt to .css and .js. I would love to hear your thoughts.

[medusa-runtime.js.txt](https://github.com/pymedusa/Medusa/files/5115087/medusa-runtime.js.txt)
[vendors.css.txt](https://github.com/pymedusa/Medusa/files/5115088/vendors.css.txt)
[style.css.txt](https://github.com/pymedusa/Medusa/files/5115089/style.css.txt)
[themed.css.txt](https://github.com/pymedusa/Medusa/files/5115090/themed.css.txt)

Thank you,

H.

**Comment by p0psicles** [comment]
Can you be more specific on the changes you made? Maybe use some highlights in the screenshots. Except for the column filters being wider I don't see much difference.

**Comment by hernandito** [comment]
Hi... the changes I have been making over time, they can be subtle... as a designer, my eye zeroes in on UI improvements. If you look at any of the css files, I have commented the parts that I changed... they look something like:

![_medusax](https://user-images.githubusercontent.com/787317/90990465-b213e400-e56f-11ea-8284-aaa4505e003a.png)

I have tightened margins, changed fonts, lightened border, reduced padding, etc. The images are bigger on the show page. Honestly they are quite numerous... 

For the _medusa-runtime.js,_ I have the following notes of what I changed:

> ===============================
    LATEST CHANGES
===============================

	change ALL word-breaks to word-break: normal; on line 1261
	change border-top: rgb(34, 34, 34) to border-top: rgb(149, 149, 149) line 939
	change border-left: rgb(34, 34, 34) to border-left: rgb(149, 149, 149) 	line 939
	change NEAR THE ABOVE: padding: 4px; to padding-left: 8px;
	change text-shadow:xxx   TO text-shadow: none
	change img.show-image width 180 to 220 on line 1261

And lastly, I think the **network logo** should make an appearance in the **Show Page.**.. here is a quick Photoshop. I did this fast... I will give some thought to size and location if you think this is worthwhile.

![_medusa3network](https://user-images.githubusercontent.com/787317/90990523-4b42fa80-e570-11ea-937d-8feffd736b87.png)

Thank you.

**Comment by p0psicles** [comment]
I think I'm going to leave it at this for now

**Comment by medariox** [comment]
I think everyone has different desires and preferences about design. We can't just make changes to please one or two people and upset the rest. The important thing is that the designs remains consistent throughout the application.

**Comment by cheese1** [comment]
@hernandito: as you seem to have a sense for it: maybe you could fix that "missing" shadows, too.  sorry for hijacking that thread, but i saw that missing shadow in your example, too.

just created a ticket under #8387 8387

**Comment by hernandito** [comment]
I was not exactly requesting my edits, I just wanted an opinion. I can keep customizing to my edits as I have been doing for a few years. I enjoy the process... like one would enjoy doing a crossword puzzle.

I think the original request and what p0psicles changed is terrific.

**Comment by p0psicles** [comment]
For me it's more important that I keep focus on a scope. Besides that I appreciate the help with the design.

**Comment by hernandito** [comment]
My pleasure to help...
