### ISSUE TITLE
Rename of files fails to rename existing 'episode'-thumb image.

### ISSUE THREAD

**Issue by QuickSwitchLK** [pymedusa/Medusa#8378]
**Describe the bug**
Rename of files feature fails to rename existing 'episode'-thumb image.
NFO and episode are renamed.

**To Reproduce**
1. Go to any show.
2. Click on 'Preview Rename'
3. Click 'Select all'
4. Click 'Rename Selected'

**Expected behavior**
All selected episodes are renamed, including matching thumbs and nfo files.

**Medusa (please complete the following information):**
 - OS: Synology

Medusa Info:
Branch:  master
Commit: 20915b56d64dc7522e484f326d9cfe7449a73193
Version: 0.4.1
Database: 44.16
Python Version: | 3.5.6 (default, Nov 25 2018, 14:24:15)  [GCC 4.7.3 20130102 (prerelease)]
SSL Version: | OpenSSL 1.0.2n  7 Dec 2017
OS: | Linux-4.4.59+-x86_64-with-glibc2.2.5
Locale: | en_US.UTF-8

User: | sc-medusa
Program Folder: | /volume1/@appstore/medusa/var/Medusa
Config File: | /volume1/@appstore/medusa/var/config.ini
Database File: | /volume1/@appstore/medusa/var/main.db
Cache Folder: | /volume1/@appstore/medusa/var/cache
Log Folder: | /volume1/@appstore/medusa/var/Logs
Arguments: | --daemon --pidfile /volume1/@appstore/medusa/var/medusa.pid --config /volume1/@appstore/medusa/var/config.ini --datadir /volume1/@appstore/medusa/var/

**Comment by QuickSwitchLK** [comment]
Hi Dave, yes I too have had issues in the past with very long file names and multiple nested directory's, but this is a new issue and with every thumb file matching the nfo and media file that is to be renamed. Cam anyone else confirm the problem? it should happen for any rename! No errors show in log either.

**Comment by nydave69** [comment]
Yes I see that issue weekly... I just figured it was a long file name problem because that what Ive seen in the past.
When it pops up again I'll actually do another count and see if it should have done the rename. I'll post when I have something.

**Comment by medariox** [comment]
It's not the file names. This happens when the image coming from the indexer is unavailable or corrupt.

**Comment by h3llrais3r** [comment]
@p0psicles 
Any fix for this? Trying to rename a lot of stuff, but the thumb files aren't taken into account. 
If I do a full update afterwards, new ones are being generated, but I end up with duplicate ones (linked to the old name).
Any suggestion as workaround?

**Comment by h3llrais3r** [comment]
@p0psicles 
I've just did some research myself and it seems to be related to: https://github.com/pymedusa/Medusa/blob/develop/medusa/post_processor.py#L213

If I remove the `+ '.'` at the end of this line, it takes all related files.
The extra `.` at the end was causing only files with different extensions to be taken... 

Not sure if removing this could have impact on something else. That's why it's probably why you should double check it. 😉
