### ISSUE TITLE
Show List blank after update

### ISSUE THREAD

**Issue by torleif** [pymedusa/Medusa#8383]
**Describe the bug**
None of the shows display on the show list page. this started happening after the last update.

**To Reproduce**
1. Go to http://medusa:8081/home/
2. ajax spinner spins for ages, then disappears 
3. nothing happens

**Expected behavior**
a list of shows will appear

**Screenshots**
![image](https://user-images.githubusercontent.com/67215/90976900-42185480-e595-11ea-91a9-75b858d56011.png)

**Medusa (please complete the following information):**
 - OS: [ubuntu Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:06 UTC 2020 i686 i686 i686 GNU/Linux]
 - Branch: master

Medusa Info: | Branch:                 master                  Commit:                 20915b56d64dc7522e484f326d9cfe7449a73193                  Version:                 0.4.1                  Database:                 44.16
-- | --
Python Version: | 2.7.17 (default, Jul 20 2020, 15:37:01)  [GCC 7.5.0]
SSL Version: | OpenSSL 1.1.1  11 Sep 2018
OS: | Linux-4.15.0-112-generic-i686-with-Ubuntu-18.04-bionic
Locale: | en_NZ.UTF-8

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2020-08-23 23:46:37 INFO	MAIN :: [20915b5] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2020-08-23 23:46:37 INFO	MAIN :: [20915b5] Building internal name cache for all shows
2020-08-23 23:46:37 INFO	MAIN :: [20915b5] Finished processing 3351 scene exceptions.
2020-08-23 23:46:36 INFO	MAIN :: [20915b5] Updating exception_cache and exception_season_cache
2020-08-23 23:46:36 INFO	TORNADO :: [20915b5] Starting Medusa on http://0.0.0.0:8081/
```
</details>

It looks like http://medusa:8081/api/v2/series?limit=1000&page=1 is timing out. is there a way to increase the time out or make it faster?

**Comment by torleif** [comment]
@p0psicles thanks for your feedback. I have about 30 or so shows. I did notice that if i use a cURL request from the terminal and lowered the limit it did seem to work faster, but I'm unsure how to get this in to medusa

**Comment by p0psicles** [comment]
Then the problem lies somewhere else. It should have no issues with 30 shows. 

What hardware are you running on. 
And start by upgrading python to 3.7. 2.7 is already run out of support. Soon we will not support py2 at all.

**Comment by nydave69** [comment]
I'm seeing that since the previous update......
If I wait a while it finally loads but every time I go back to that page I get the browser wait message.

**Comment by torleif** [comment]
it's running on an old dell, opiplex 360. it's got a Dual-Core  CPU E5300. not huge, but i thought it should handle it. it's got an ssd.

i'll try updating python

**Comment by torleif** [comment]
I updated to python3, though sadly i had to reinstall medusa in the process. the good news is it works now, though i had to re index all the shows
