### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: BNNVARA

### ISSUE THREAD

**Issue by IanKBrown** [pymedusa/Medusa#8388]
### INFO
**Python Version**: `2.7.10 (default, Aug 19 2015, 09:18:54) [GCC 4.6.3]`
**Operating System**: `Linux-4.14.x-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@20915b56d64dc7522e484f326d9cfe7449a73193
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-08-23 17:50:08 ERROR    APIv2-Thread_2 :: [20915b5] Missing time zone for network: BNNVARA
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
[Present in the list](https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L301)
Issue can be closed.
