### ISSUE TITLE
Dark text on dark background

### ISSUE THREAD

**Issue by Yellow1144** [pymedusa/Medusa#8390]
**Describe the bug**
On the History page, in  detailed view, while using the dark theme, All the history text for the Time, Action and Provider columns is white text on a dark grey background, but all the text under the Episode column is black on the same dark grey background. 
It is readable but it really should be white like the others

Also, while I'm here I thought I'd mention one things that has changed that is bugging me. If I am viewing the schedule, I usually use calendar layout, and I switch to another layout, the view does not change until I reload the page, it used to change immediately upon choosing a different layout. Can you change this back?

Thanx

Branch: develop
Commit: a7236eeb11bc7ad2b0ff053e37f6287c5ec69f07
Version: 0.4.0
Database: 44.16
--
Python Version: | 3.7.8 (default, Jun 29 2020, 05:46:05) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.15.0-112-generic-x86_64-with-LinuxMint-18.3-sylvia
Locale: | en_CA.UTF-8

**Comment by p0psicles** [comment]
Black text issue is fixed in develop. The other issue I know. Ik get to it when refactoring the schedule and history pages
