### ISSUE TITLE
Seconds are shown in show list

### ISSUE THREAD

**Issue by nbara** [pymedusa/Medusa#8408]
**Describe the bug**
Seconds should not be displayed in show list.

**To Reproduce**
1. Go home tab
2. See error

**Expected behavior**
Seconds should not be shown (cf settings: "**Note**: seconds are only shown on the History page")

**Screenshots**

<img width="385" alt="Screenshot 2020-08-28 at 13 21 35" src="https://user-images.githubusercontent.com/10333715/91555508-6d05fe00-e931-11ea-8ca5-6a7148ac6547.png">

**Medusa (please complete the following information):**
 - OS: macOS 10.15.5
 - Branch: master
 - Commit: 20915b56d64dc7522e484f326d9cfe7449a73193
 - Python version: 3.7.7
 - Database version: 44.16

**Comment by p0psicles** [comment]
What is your date/time setting? In config -> general

**Comment by p0psicles** [comment]
Never mind, I totally missed that. I'll hide seconds.
