### ISSUE TITLE
Unable to create folder although ownership/chmod is correct

### ISSUE THREAD

**Issue by digitalnaiveDE** [pymedusa/Medusa#8416]
Hey there,

 I am not a Linux professional and learned all the stuff myself through reading articles online. So please bare with me a bit.

So far Medusa was running kind of fine but i am struggling with those „unable to create folder“ issues. I did some research and checked my settings in the Medusa.service file where it is set to Medusa/Medusa (user/group). 

Than i checked my mounted folder /media where i have a subfolder called /media/Serien with the command ls -l and my system told me ownership is set to Medusa Medusa and chmod is set to 777. So what am i missing here?

I have another user i am using to connect via ssh to the system and executing all the commands, like mounting my external hdd. Can this be an issue?

Thanks for your help in advance

**Comment by medariox** [comment]
Fixed on discord.
