### ISSUE TITLE
Unnistall medusa on Ubuntu

### ISSUE THREAD

**Issue by Mascalerino** [pymedusa/Medusa#8417]
Hi,
I want to do a new install on Ubuntu beacause some of my files are corrupted. I delete all the files from /opt/medusa, but this doesn´t work. 
How i can purge all the instalation of Medusa? I use the version 0.3.16
Any assistance would be much appreciated.

**Comment by medariox** [comment]
What do you mean by it doesn't work? All Medusa files are stored there. Just follow the install instructions to install again.

**Comment by Mascalerino** [comment]
> What do you mean by it doesn't work? All Medusa files are stored there. Just follow the install instructions to install again.

I want to unninstall Medusa first and then do a new install. 
When i install Medusa again the home page is blank and the log returns a lot of errors. So the first thing i want, is to purge all data is stored in medusa and unnistalled it and do a fresh install.

**Comment by p0psicles** [comment]
Just delete te Medusa folder and Clone it again
