### ISSUE TITLE
show alphabetical ordering

### ISSUE THREAD

**Issue by bluelavalamp** [pymedusa/Medusa#8420]
Hi, 
I'm currently running:
Branch: master
Commit: 20915b56d64dc7522e484f326d9cfe7449a73193
Version: 0.4.1

And I noticed that the show ordering changed after updating to this version.  On the front page before when a show started with "The" it was ignored, so for example "The Amazing Race" would be placed in order for "Amazing Race".  Now it's in the "T" area because the "The" is being used for sorting order.

But when you are on a shows page and you click the pull-down menu of show titles at the top left, "The Amazing Race" would be in the "A" section because "The" is ignored.  

Is there anyway to make them consistent?

Thanks

**Comment by p0psicles** [comment]
Which layout? Can you create a screenshot?
