### ISSUE TITLE
Show page columns "Active" and "Status" are always the same.

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#8421]
**Describe the bug**
Show page columns "Active" and "Status" are always the same.

**To Reproduce**
Open the show listing page, check the two columns...

**Expected behavior**
That the Active would indicate if it's paused or not and the Status if the show is still running..
Would be my guess, why have two of the same?...

**Screenshots**
![image](https://user-images.githubusercontent.com/14140816/91780256-fd0fa600-ebc4-11ea-8ea0-afd429d9c138.png)

**Medusa (please complete the following information):**
Medusa Info: | Branch:                 master                  
Commit:                 20915b56d64dc7522e484f326d9cfe7449a73193                  
Version:                 0.4.1                  
Database:                 44.16
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j  20 Nov 2018
OS: | Windows-7-6.1.7601-SP1
Locale: | en_US.cp1252

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
NA
```
</details>

**Additional context**

**Comment by medariox** [comment]
They are not the same. An ended show is simply not active anymore. Just pause a continuing show to see the difference.

**Comment by nydave69** [comment]
pause doesn't change anything...
That's what I thought it did...

**Comment by medariox** [comment]
Yes, of you pause an ongoing show it will show the X.

**Comment by nydave69** [comment]
but it doesn't change...
