### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network:  - None

### ISSUE THREAD

**Issue by pax0707** [pymedusa/Medusa#8423]
### INFO
**Python Version**: `3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362-SP0`
**Locale**: `cp1250`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@20915b56d64dc7522e484f326d9cfe7449a73193
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-09-01 20:17:30 ERROR    APIv2-Thread_2 :: [20915b5] Missing time zone for network:  - None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
Can not find a network with such name. 
https://thetvdb.com/networks?page=18

**Comment by medariox** [comment]
https://thetvdb.com/networks?page=1
First name `- None`. I guess it's just a placeholder for series with unknown networks?

**Comment by pax0707** [comment]
OK, found it - https://www.thetvdb.com/series/final-space
Not a placeholder.

NETWORKS
- None from August 2020 to August 2020
Adult Swim from April 2016 to September 2019

**Comment by medariox** [comment]
I mean TheTVDB uses `- None` as a placeholder. That network doesn't exist.

**Comment by yrtria** [comment]
### INFO
**Python Version**: `3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.0-45-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@708c2e9351e61b3f96345ab013f52e83b5a474b5
**Link to Log**: https://gist.github.com/8759c479918b80d6d0356d944acf369b
### ERROR
<pre>
2020-09-06 16:35:04 ERROR    TORNADO :: [708c2e9] Missing time zone for network:  - None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by yrtria** [comment]
### INFO
**Python Version**: `3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.0-45-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-09-08 22:35:04 ERROR    TORNADO :: [b352bb6] Missing time zone for network:  - None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pct00** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/61086d234bb0d4da5627dc4d23f5f8ab
### ERROR
<pre>
2020-09-13 22:07:56 ERROR    APIv2-Thread_2 :: [b352bb6] Missing time zone for network:  - None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MotleyC** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-09-12 10:36:11 ERROR    APIv2-Thread_2 :: [b352bb6] Missing time zone for network:  - None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by wfulcher** [comment]
### INFO
**Python Version**: `3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]`
**Operating System**: `Linux-5.4.0-45-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-09-08 14:35:09 ERROR    TORNADO :: [d9c31da] Missing time zone for network:  - None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-09-20 08:54:27 ERROR    BACKLOG :: [b352bb6] Missing time zone for network:  - None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bootman2222** [comment]
### INFO
**Python Version**: `3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]`
**Operating System**: `Linux-4.19.107-Unraid-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/81ec5ae2af45ebdf6ab1e96ea342ecf2
### ERROR
<pre>
2020-09-24 20:00:46 ERROR    APIv2-Thread_2 :: [] Missing time zone for network:  - None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bootman2222** [comment]
### INFO
**Python Version**: `3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]`
**Operating System**: `Linux-4.19.107-Unraid-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/b3b2074d01149a547b0f605a1d426334
### ERROR
<pre>
2020-09-26 13:14:40 ERROR    APIv2-Thread_0 :: [] Missing time zone for network:  - None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bootman2222** [comment]
### INFO
**Python Version**: `3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]`
**Operating System**: `Linux-4.19.107-Unraid-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/33415078138c9eae06f58a88248f4133
### ERROR
<pre>
2020-09-27 21:32:57 ERROR    APIv2-Thread_0 :: [] Missing time zone for network:  - None
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
