### ISSUE TITLE
Can t start after python update

### ISSUE THREAD

**Issue by cyan** [pymedusa/Medusa#8424]
Heya,
i just came back on medusa after few weeks and realised that it was updated (while i still had an old python 2.X (don't remeber wich version)) few days later, i had a crash and had to restart the device, then the system couldn t start medusa, i saw that i needed to update python to 3 and followed the guide for my debian 8 on raspberry pi so i compiled the last python 3.8.4 and ended up with 

Traceback (most recent call last):
  File "/opt/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/opt/medusa/medusa/init/__init__.py", line 27, in initialize
    _ssl_configuration()
  File "/opt/medusa/medusa/init/__init__.py", line 110, in _ssl_configuration
    import ssl
  File "/Python-3.8.0/Lib/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

i tried to compile an older version such as 3.7.0 and now i just did with 3.8.0 (wich i used to get the log posted )

i also realised that there was a new script for SystemD so i used it instead of SysVinit
i tried the cmd directly but it still give me the same error
/Python-3.8.0/python /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa

thanks for your help

PS as i can't have access to the raspberry pi physically, i can't make a fresh OS install with debian9 and fresh medusa :(

**Comment by medariox** [comment]
The problem is that you are building Python without SSL. Follow this guide: https://jameskiefer.com/posts/installing-python-3.7-on-debian-8/

**Comment by cyan** [comment]
thanks a lot, i ll try that asap

**Comment by cyan** [comment]
i had to change few things but it s working now, thanks for your help
