### ISSUE TITLE
History Episodes Display Black on Black

### ISSUE THREAD

**Issue by alecmascot** [pymedusa/Medusa#8430]
After the latest update, 0.4.1, if using the Dark Display Scheme then on the History page the Episode Names are displayed Black on Black rendering then essentially invisible.
It is necessary to use the Light Display Scheme to see the Episode Names.

![Screenshot (16)](https://user-images.githubusercontent.com/70717540/92149884-85d15080-ee16-11ea-8832-56a4d1843748.png)

**Comment by p0psicles** [comment]
Is fixed In develop. Well release later this weekend.
