### ISSUE TITLE
Way to invoke custom Python code to search for shows

### ISSUE THREAD

**Issue by csm10495** [pymedusa/Medusa#8435]
**Is your feature request related to a problem? Please describe.**
There are some shows that I know aren't normally found on torrent websites, though I've whipped up some special python code that can download the show for me.

**Describe the solution you'd like**
An API system where I can have custom code called to see if a show is available via other means (and allow me to download it from there, then pass the downloaded location back to Medusa). Then Medusa can happily mark it as downloaded and not need to download it again if a torrent appears.

**Describe alternatives you've considered**
I thought about creating a custom RSS, but then I think right now I would still need a torrent which I don't really have at this point.

**Additional context**
I'm quite new to Medusa, so if this already exists please let me know. Thanks.

**Comment by p0psicles** [comment]
Medusa searches for nzb or torrents. And passes it on to a nzb or torrents client.

**Comment by csm10495** [comment]
So there is no way to have it invoke custom code to do a search (I guess without hacking it manually)?

**Comment by p0psicles** [comment]
I have no idea what your goal is. So I can't say if it's possible or not.
I can say, that we don't have some module or plugin system specifically for doing searches.
Your question is too vague. You can get on discord to discuss if you want. Link invite in our Readme.md

**Comment by csm10495** [comment]
Thanks for the help. I used the API to do this. Basically I have a python script that periodically checks for certain shows being wanted. Then it'll download them and mark them as snatched.
