### ISSUE TITLE
No longer starts

### ISSUE THREAD

**Issue by greentrancer** [pymedusa/Medusa#8457]
**Describe the bug**
Started the update process and the application no longer works now.

**To Reproduce**
1. Press 'update'
2. Wait

**Expected behavior**
Get the latest version.

**Screenshots**
[https://imgur.com/OMkRNAj](https://imgur.com/OMkRNAj)

**Medusa (please complete the following information):**
 - OS: QTS 4.4.3.1400
 - Branch: master

**Comment by medariox** [comment]
It's impossible to help without debug logs.

**Comment by greentrancer** [comment]
> 
> 
> It's impossible to help without debug logs.

How can I access those?

**Comment by medariox** [comment]
There should be a Logs folder in Medusa's main directory.

**Comment by p0psicles** [comment]
Else start manually from the command prompt. And see what errors.

**Comment by greentrancer** [comment]
> 
> 
> There should be a Logs folder in Medusa's main directory.

I believe this is the one:
[application.log](https://github.com/pymedusa/Medusa/files/5183880/application.log)

**Comment by p0psicles** [comment]
Can you shutdown from the ui? Has the process cleanly stopped? What's the logs of that. Please only copy/paste logs of the shutdown

**Comment by greentrancer** [comment]
> 
> 
> Can you shutdown from the ui? Has the process cleanly stopped? What's the logs of that. Please only copy/paste logs of the shutdown

I can 'stop' and 'start' from the QNAP UI, but I am not sure if or where are the logs containing that information.

**Comment by p0psicles** [comment]
No, not from qnap ui. From Medusa.

**Comment by greentrancer** [comment]
> 
> 
> No, not from qnap ui. From Medusa.

I attached a screenshot of Medusa in my first post - I cannot open it after the latest update; all I get is:

"Unable to connect
Firefox can't establish a connection to the server at 192.168.0.1:22121."

**Comment by imrman** [comment]
i am getting this after the recent update:
Traceback (most recent call last):
  File "app/SickBeard.py", line 6, in <module>
    from medusa.__main__ import main
  File "app/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "medusa/providers/__init__.py", line 41, in <module>
    provider_names = import_providers(__name__)
  File "app/medusa/providers/__init__.py", line 37, in import_providers
    import_submodules(package_name)
  File "app/medusa/providers/__init__.py", line 25, in import_submodules
    module = importlib.import_module(full_name)
  File "python2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "app/medusa/providers/torrent/__init__.py", line 29, in <module>
    import_submodules(__name__)
  File "app/medusa/providers/torrent/__init__.py", line 22, in import_submodules
    valid_pkg = import_submodules(full_name)
  File "app/medusa/providers/torrent/__init__.py", line 17, in import_submodules
    module = importlib.import_module(full_name)
  File "python2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "app/medusa/providers/torrent/html/thepiratebay.py", line 21, in <module>
    import validators
  File "app/ext/validators/__init__.py", line 23, in <module>
    from .url import url
  File "app/ext/validators/url.py", line 90, in <module>
    re.UNICODE | re.IGNORECASE
  File "python2/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "python2/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression

**Comment by medariox** [comment]
Seems to be an issue with the Python 2 version installed on QNAP. 
I strongly suggest you install the Python 3 version of Medusa with https://onecdonly.github.io/sherpa/
It's very straightforward. 

Take a backup
Install with sherpa
Restore backup

**Comment by greentrancer** [comment]
> 
> 
> Seems to be an issue with the Python 2 version installed on QNAP.
> I strongly suggest you install the Python 3 version of Medusa with https://onecdonly.github.io/sherpa/
> It's very straightforward.
> 
> Take a backup
> Install with sherpa
> Restore backup

I have to figure out how to install Python 3... I installed a version from QNAP App Centre, but all applications still use Python 2.

I posted on QNAP forum and currently waiting for any feedback. I have not found anything useful on Google.

**Comment by medariox** [comment]
What's wrong with sherpa? 😕

**Comment by greentrancer** [comment]
> 
> 
> What's wrong with sherpa? 😕

Are you talking to me? I cannot see any information that I can install Python 3 on QNAP with sherpa.

**Comment by medariox** [comment]
> > What's wrong with sherpa? 😕
> 
> Are you talking to me? I cannot see any information that I can install Python 3 on QNAP with sherpa.

Yes. Sherpa will install all necessary requirements (including Python 3) and Medusa.

**Comment by greentrancer** [comment]
> 
> 
> > > What's wrong with sherpa? 😕
> > 
> > 
> > Are you talking to me? I cannot see any information that I can install Python 3 on QNAP with sherpa.
> 
> Yes. Sherpa will install all necessary requirements (including Python 3) and Medusa.

That was brilliant and so easy - thank you for the recommendation!

![Uploading putty_2020-09-08_12-59-38.png…]()

It runs on:
Python Version: | 3.8.3 (default, Jun 12 2020, 20:24:48)  [GCC 8.4.0]
