### ISSUE TITLE
[APP SUBMITTED]: Unable to create the folder <show>, can't add the show

### ISSUE THREAD

**Issue by jfnz** [pymedusa/Medusa#8464]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@708c2e9351e61b3f96345ab013f52e83b5a474b5
**Link to Log**: **No Log available** (debug logging _was_ enabled)
### ERROR
<pre>
2020-09-08 15:14:40 ERROR    Thread_1 :: [708c2e9] Unable to create the folder S:\TV\blah, can't add the show
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

Issue is writing to a mapped drive. I can create folders/files on the mapped drive but Medusa cannot. I added "S:\TV" manually to the config file and restarted Medusa. Also tried symlink'ing "S:\TV" to "C:\tv" and still receive the same error.

I kinda feel like this is permissions related, but Medusa is running as "system" and this account has permissions to read/write this share.

Any ideas?

**Comment by p0psicles** [comment]
You should not run as system. Use a named user

**Comment by jfnz** [comment]
Running as "server01\user" (as an example) now -- no change. Still same error?

**Comment by jfnz** [comment]
To clarify, this only occurs on a mapped drive. I can create shows on a local disk no problems.

It's an issue for me as I need to read/write to my NAS and not localhost.

**Comment by p0psicles** [comment]
But then it's an issue with your permissions. Medusa works fine with mapped drives
