### ISSUE TITLE
Upgrading Medusa to Python 3 on Synology

### ISSUE THREAD

**Issue by Sandermand** [pymedusa/Medusa#8469]
I am beginning to see the following message in my Medusa log:

**2020-09-06 17:36:13 WARNING  MAIN :: [708c2e9] As of October 1st 2020 Medusa will not run on Python 2.x any longer.
Python 2.x has passed its sunset date as you can read here: https://tinyurl.com/y4zwbawq
Please upgrade your Python version to 3.6 or higher as soon as possible!**

How do i upgrade Medusa to run Python3 on my Synology NAS ? I have the regular v.1.4 package installed from Synocommunity in the Synology App store and have also had Python3 installed for months, without Medusa "pulling" itself over to the new version of Python. 

What do ?

Medusa Info: | Branch: master
Commit: 708c2e9351e61b3f96345ab013f52e83b5a474b5
Version: 0.4.2
Database: 44.16
-- | --
**Python Version: | 2.7.18** (default, Aug 3 2020, 17:35:43) [GCC 4.9.3 20150311 (prerelease)]
SSL Version: | OpenSSL 1.0.2n 7 Dec 2017
OS: | Linux-3.10.105-x86_64-with-glibc2.2.5
Locale: | Unknown.Unknown

**Comment by medariox** [comment]
There is a Synology package available with Python 3, see: https://github.com/SynoCommunity/spksrc/issues/3710#issuecomment-524808904

Just take a backup and restore.

**Comment by Sandermand** [comment]
> There is a Synology package available with Python 3, see: [SynoCommunity/spksrc#3710 (comment)](https://github.com/SynoCommunity/spksrc/issues/3710#issuecomment-524808904)
> 
> Just take a backup and restore.

Yeah i found that the other day but it does not seem like a very "official" solution. Will the regular Synocommunity package not get updated ? Or am i good to just run this Custom one for the forseeable future with updates and all coming in as normal ?

**Comment by p0psicles** [comment]
You don't need updates on the syno package. Medusa updates are separate from that. It's safe to use

**Comment by Sandermand** [comment]
> You don't need updates on the syno package. Medusa updates are separate from that. It's safe to use

Worked perfectly after installing Allans Python 3.7 package as well. Seems to be running alot faster on this new code as well. Thanks :)
