### ISSUE TITLE
No restart after todays update

### ISSUE THREAD

**Issue by sendas** [pymedusa/Medusa#8471]
I logged in to my rasppery pi and this happened:

/usr/bin/python3 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa

Traceback (most recent call last):
  File "/opt/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/opt/medusa/medusa/init/__init__.py", line 36, in initialize
    _monkey_patch_bdecode()
  File "/opt/medusa/medusa/init/__init__.py", line 166, in _monkey_patch_bdecode
    import bencodepy.compat
ModuleNotFoundError: No module named 'bencodepy.compat'

after a reboot everything works fine

debug log after reboot: [https://gist.github.com/sendas/a5932e7e6987c3b0950571d25f0f7a54](url)

Medusa Info: | Branch: masterCommit: 708c2e9351e61b3f96345ab013f52e83b5a474b5Version: 0.4.2Database: 44.16
-- | --
Python Version: | 3.7.3 (default, Apr 3 2019, 05:39:12) [GCC 8.2.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-4.19.75-v7+-armv7l-with-debian-10.1
Locale: | en_GB.UTF-8
  |  
  |  
User: | root
Program Folder: | /opt/medusa
Config File: | /opt/medusa/config.ini
Database File: | /opt/medusa/main.db
Cache Folder: | /opt/medusa/cache
Log Folder: | /opt/medusa/Logs
Arguments: | -q --daemon --nolaunch --datadir=/opt/medusa

**Comment by medariox** [comment]
For some reason you switched to Python 2.7 again. Stay on Python 3 like you are doing now and everything will be fine.

**Comment by sendas** [comment]
I haven't switch to anything .... it happened after the update.

If i go to the app and choose reboot everything works ...

**Comment by medariox** [comment]
So it only happens if you update? Does it happen if you reboot from within Medusa?

**Comment by medariox** [comment]
If it happens again it means that you are missing some files. In that case I suggest you checkout the `master` branch again from within the UI: General > Advanced Settings > GitHub > Branch version (select `master`) and press Checkout Branch.

**Comment by sendas** [comment]
> So it only happens if you update? Does it happen if you reboot from within Medusa?

Yes, only happens after the update. If I reboot within Medusa everything works fine.

**Comment by sendas** [comment]
> If it happens again it means that you are missing some files. In that case I suggest you checkout the `master` branch again from within the UI: General > Advanced Settings > GitHub > Branch version (select `master`) and press Checkout Branch.

It seems everything is ok

[https://gist.github.com/sendas/6d11111da3920c60da519654d85a1fed](https://gist.github.com/sendas/6d11111da3920c60da519654d85a1fed)
