### ISSUE TITLE
Tool to fix broken providers

### ISSUE THREAD

**Issue by Starbuck1991** [pymedusa/Medusa#8476]
**Is your feature request related to a problem? Please describe.**
Every time Medusa does a search, I get this message in its log:

Thread :: [b352bb6] Broken providers found: ['']

As I understand it, some provider/s are causing problems. I know this is not a major issue, still, it bugs me because the message is so unhelpful and I don't know how to "debug" the provider list.

**Describe the solution you'd like**
I'd like the ability to clean/delete all broken providers, or at least have them listed properly.

**Comment by medariox** [comment]
If there are broken providers, they will be listed between the brackets. In this case there aren't any.

**Comment by Starbuck1991** [comment]
OK, I understand now, not the most helpful log message I've ever got. :-P
It'll be better something like "No broken providers found", if the broken providers count is empty.
Still, I think it'll be a good thing to add the ability to quickly get rid of (or edit/repair) broken providers.
Thank you for your help!

**Comment by medariox** [comment]
I agree that the message should be better. If a provider is broken it will be automatically disabled.

**Comment by Starbuck1991** [comment]
Good to know! Thank you again for your support!

**Comment by p0psicles** [comment]
Well actually there are a number of providers that are currently broken and should be listed.
