### ISSUE TITLE
Synology Package for Python 3

### ISSUE THREAD

**Issue by BenjV** [pymedusa/Medusa#8479]
I have created a Synology package for Python3
You can find it on my github:

> https://github.com/BenjV/SYNO-packages

It will use the Python 3 of the SynoCommunity so be sure to install that first.
Add the owner of the folder where you downloader puts its files is to the group "sc-download".
Also if you use "move' files in the PostProcessing then the owner of the folder where you move to must be added to the "sc-download" group.

Let me know if there are problems.

**Comment by p0psicles** [comment]
We will also add this info in our readme.

**Comment by spock99** [comment]
Unloaded the prior sickchill loaded using sickbeard-custom and loaded this new build using manual package center so far work perfect. 
![image](https://user-images.githubusercontent.com/2895145/92825948-fcc19880-f384-11ea-9c37-8e5b23be8894.png)

**Comment by medariox** [comment]
Added to the wiki: https://github.com/pymedusa/Medusa/wiki

Thank you again!

**Comment by p0psicles** [comment]
@BenjV I see you removed the package. Sorry, didn't realize we had to host it

**Comment by BenjV** [comment]
No I will host it, I found a little annoying bug which I have to fix.
So I removed it from my github to prevent people installing it.
It will be back soon.

**Comment by p0psicles** [comment]
That's cool. I've also updated our own wiki. So i've decided to just link to your SYNO-packages link.
https://github.com/pymedusa/Medusa/wiki/Synology

**Comment by BenjV** [comment]
Ok the bug is fixed and the package is back online on my github
https://github.com/BenjV/SYNO-packages

**Comment by marflao** [comment]
Cool...many thanks for that, @BenjV, works like a charm ;-)
And I have the feeling the site is faster, more responsive.

Quick one: can i uninstall the "SickBeard Custom" package or shall I keep in on my NAS?

Thanks in advance.

**Comment by BenjV** [comment]
If you don't need it anymore you can remove it.
Two applications with the same functionality seems useless to me.

**Comment by marflao** [comment]
alright..thanks.
