### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by Oliveri88** [pymedusa/Medusa#8480]
I have been using Medusa for some time. Tried to open it today, takes me to the Medusa login screen Username & Password blank. I had is set to 'Remember me'. However, i'm now looking at two blank boxes. How can i reset the Username & Password. It appears i have no clue what the password was, only had to type it in once when this was setup (a long time ago). I found some info for linux systems but i'm running a windows 7 box. Please help.....

**Comment by p0psicles** [comment]
Stop Medusa. Edit config.ini and start

**Comment by Oliveri88** [comment]
OK, located where. I can't find it. I have 'unhidden' files and folders, but can somebody please tell me the directory path for windows?

**Comment by Oliveri88** [comment]
All Good, found it. Problem solved. Thank you.

**Comment by Oliveri88** [comment]
In case someone has the same query path is  \Medusa\Data\config.ini
