### ISSUE TITLE
Unable to send Torrent Error

### ISSUE THREAD

**Issue by Ropiper** [pymedusa/Medusa#8484]
Hello,

I'm trying to configure medusa+utorrent. I have both installed and running correctly and when I try the conection it says everything is correct.
![0x1lq8wc1mm51](https://user-images.githubusercontent.com/47742412/92983084-ccbbe780-f4a1-11ea-89d9-4f56969b2717.png)

But then I get the next Warning and it never gets any torrent
![no3vui581mm51](https://user-images.githubusercontent.com/47742412/92983095-d2b1c880-f4a1-11ea-8789-36f50920feb2.png)

Any idea?

**Comment by p0psicles** [comment]
Can you try removing the trailing slash in the url

**Comment by Ropiper** [comment]
> Can you try removing the trailing slash in the url

Same happening

**Comment by medariox** [comment]
Which uTorrent version?

**Comment by Ropiper** [comment]
> Which uTorrent version?
> Also try without label and see if that works.

Here is utorrent info
![image](https://user-images.githubusercontent.com/47742412/92994369-e2f59200-f4f9-11ea-8feb-6404b30a306a.png)

And same error without label

**Comment by medariox** [comment]
That's a really old version. We can't and won't support such old versions, sorry.

**Comment by Ropiper** [comment]
> That's a really old version. We can't and won't support such old versions, sorry.

Wich versions do you support? That's the last one I found in utorrent page

**Comment by medariox** [comment]
https://www.utorrent.com/intl/en/downloads/win

µTorrent Stable (3.5.5 build 45798)
For Windows (4.88 MB)
English (US) - August 28, 2020

**Comment by Ropiper** [comment]
> https://www.utorrent.com/intl/en/downloads/win
> 
> µTorrent Stable (3.5.5 build 45798)
> For Windows (4.88 MB)
> English (US) - August 28, 2020

That's for Windows, I'm on Ubuntu. I downloaded here https://www.utorrent.com/intl/es/downloads/linux

µTorrent Server for Ubuntu 13.04
Ubuntu 13.04 - 64-bit (2.16 MB)
English (US) - May 20, 2020

**Comment by medariox** [comment]
Ubuntu 13.04?

Yeah, not supported.

**Comment by p0psicles** [comment]
your better of using another torrent client that is actively developed and build for all Linux dists. 

Like rtorrent/rutorrent or qbittorrent

**Comment by Ropiper** [comment]
> your better of using another torrent client that is actively developed and build for all Linux dists.
> 
> Like rtorrent/rutorrent or qbittorrent

Working with qbittorrent, ty!

**Comment by Lightningblade** [comment]
Not working with qBitTorrent

**Comment by Lightningblade** [comment]
Not working with qbittorrent here.

Same scenario, test connection is a success but cant get torrents through.

qbittorrent: v4.2.5
Medusa: 
![image](https://user-images.githubusercontent.com/30607152/94366562-770a5080-00d9-11eb-888c-11bc4b0d26ae.png)


Running both in docker on the same Ubuntu 20 VM. 
qBitTorrent:
https://hub.docker.com/r/markusmcnugen/qbittorrentvpn/ (I can access the WebUI from my homenet, and the medusa connection states success as well, so I don't think the VPN is the problem.)

Medusa:
https://hub.docker.com/r/pymedusa/medusa

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/8527
