### ISSUE TITLE
Missing folder selection on show listing

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#8503]
Went to show listing page to see what shows completed. I Place all new shows in a temp folder type till at least the first shows have downloaded. This way I wont watch them till there in order. I select the folder to list just those shows to decide if they can be moved to their permanent place.

Went to do that this morning and the folder selection on the left isn't there.
Really need that back..

**Medusa (please complete the following information):**

Medusa Info: | Branch:                 master                  Commit:                 b352bb6924afcdfafce176a540d53ce405ca1312                  Version:                 0.4.3                  Database:                 44.16
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j  20 Nov 2018
OS: | Windows-7-6.1.7601-SP1
Locale: | en_US.cp1252

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Are you sure there are multiple folders? It will only shows with a minimum of 2 folders.

**Comment by nydave69** [comment]
It has moved to the other side over column selection...
