### ISSUE TITLE
New Quality: N/A

### ISSUE THREAD

**Issue by icaros401** [pymedusa/Medusa#8515]
**Describe the bug**
If the quality is not part of the file name, Medusa defaults to "N/A".

**To Reproduce**
1. Download American.Dad.S16E23.1080p.WEBRip.x264-BAE.mkv 
2. move .\American.Dad.S16E23.1080p.WEBRip.x264-BAE.mkv ..\American.Dad.S17E23.mkv' (Yes, I'm one of those who moved on to season 17)
3. Manual Post-Process

**Expected behavior**
Quality should be detected from the mkv container.

**Medusa (please complete the following information):**
 - OS: Linux-4.4.59+-x86_64-with
 - Branch: master
 - Commit: b352bb6924afcdfafce176a540d53ce405ca1312
 - Python version: 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
 - Database version: 44.16

**Additional context**
Using latest pymedusa/medusa docker image.

**Comment by medariox** [comment]
Report to knowit with detailed file information: https://github.com/ratoaq2/knowit
