### ISSUE TITLE
Add SpaceTorrent as new provider

### ISSUE THREAD

**Issue by neo62248** [pymedusa/Medusa#8534]
**Is your feature request related to a problem? Please describe.**
SpaceTorrent cannot work with Jackett (Cloudfare issue). Adding this provider directly to Medusa can be the solution.

**Describe the solution you'd like**
Adding SpaceTorrent like new provider.

**Comment by p0psicles** [comment]
If jacket can't get past the cloudflare protection, why do you think Medusa can?

**Comment by medariox** [comment]
Yeah, won't be possible for us either. Ask the provider to stop blocking with CF v2!
