### ISSUE TITLE
Missing one episode of a show.

### ISSUE THREAD

**Issue by Lightningblade** [pymedusa/Medusa#8544]
**Describe the bug**
I've added the show "Sword Art Online" to my fresh install of medusa and got it finally to work after using the development branch and configuring multiple things. It also automatically snatched all the episodes (even the first season which was not displayed on the show page until I added it in a scene exception for season 1 (Also a bug I suppose but not my issue right now). Except it didn't find a single episode: Season 3 Episoide 10. 
![image](https://user-images.githubusercontent.com/30607152/94477258-ed8a7980-01d1-11eb-9a39-f047cd1f2193.png)

I'm using nyaa as the only provider which has the episode just like any else 
![image](https://user-images.githubusercontent.com/30607152/94477372-14e14680-01d2-11eb-8daf-7c0dda133909.png)

Manual search doesn't result in anything either for the episode. Is there a way to manually say I downloaded it / add a magnet/torrent file?

**To Reproduce**
1. Add Sword Art Online while only having Nyaa as Search provider
2. Wait until or force the download of the show. 

**Expected behavior**
Download all episodes

**Medusa (please complete the following information):**
 - OS: [Ubuntu 20 as Docker host]
 - Branch: [develop] - After someone said I should edit the qbittorrent.py and saw it was already updated on the develop branch i just switched instead.
 - Commit: [https://github.com/pymedusa/Medusa/commit/f1e09802d7a875744a066cd2904a477fd05b31ef]
 - Python version: [3.7.6]
 - Database version: [44.16]

**Additional context**
![image](https://user-images.githubusercontent.com/30607152/94477442-33474200-01d2-11eb-8fe3-a38487989b0a.png)

**Comment by medariox** [comment]
The search query doesn't bring up the result: https://nyaa.si/?f=0&c=0_0&q=Sword+Art+Online+10
Anyway, closing because of missing debug logs.

**Comment by Lightningblade** [comment]
I'm sorry, here it is. Couldn't find anything relating to the episode 10 though. https://gist.github.com/Lightningblade/00eca71447c53253a969db260fb77021

And theoretically it is right here:
![image](https://user-images.githubusercontent.com/30607152/94538098-dedcaa80-0243-11eb-9c41-a2d9d59889bc.png)
https://nyaa.si/?f=0&c=1_2&q=Sword+Art+Online+-+Alicization+10&p=6
if you take the first of this list: 
![image](https://user-images.githubusercontent.com/30607152/94538144-edc35d00-0243-11eb-8821-723cb3eac1e1.png)

But page 6 (or result ~400) might be a bit to much. I think the problem is that the 10 also matches 1080p. 

But going back to my initial question, since this now happened, is there any way to tell medusa to directly use that link that I found myself? (Manual add)

**Comment by medariox** [comment]
Well yes, page 6 is a bit of a stretch. That's something Nyaa needs to fix.

There are multiple ways. You can manually change the status to Skipped or Ignored. You can download it and put it in the post-processing dir and wait for it to process. You can manually process the file from wherever. You can use black hole method and put the torrent file in the chosen folder.

There is no way to add a download link to Medusa directly though, you need to add it from the torrent client.

**Comment by Lightningblade** [comment]
Alright Thanks
