### ISSUE TITLE
Bug on Synology

### ISSUE THREAD

**Issue by sendas** [pymedusa/Medusa#8551]
Medusa Info:	Branch: master 
Commit: b352bb6924afcdfafce176a540d53ce405ca1312 
Version: 0.4.3 
Database: 44.16
 Python Version:	3.7.7 (default, Aug 18 2020, 20:43:27) [GCC 4.9.3 20150311 (prerelease)]
 SSL Version:	OpenSSL 1.0.2n 7 Dec 2017
 OS:	Linux-3.10.105-armv7l-with-glibc2.4
 Locale:	en_US.UTF-8
 	 
 	 
 User:	sc-medusa
Program Folder:	/volume1/@appstore/medusa/var/Medusa
 Config File:	/volume1/@appstore/medusa/var/config.ini
Database File:	/volume1/@appstore/medusa/var/main.db
 Cache Folder:	/volume1/@appstore/medusa/var/cache
 Log Folder:	/volume1/@appstore/medusa/var/Logs
Arguments:	
--daemon --pidfile /volume1/@appstore/medusa/var/medusa.pid --config /volume1/@appstore/medusa/var/config.ini --datadir /volume1/@appstore/medusa/var/ --nolaunch
 	 
 	 
Website:	http://github.com/pymedusa/medusa.github.io/
 Wiki:	https://github.com/pymedusa/Medusa/wiki
 Source:	https://github.com/pymedusa/Medusa
 IRC Chat:	#pymedusa on irc.freenode.net

[https://gist.github.com/sendas/e1c4baf23fa65d4e0d6efb90f59696d2](https://gist.github.com/sendas/e1c4baf23fa65d4e0d6efb90f59696d2)

**Comment by medariox** [comment]
Report to knowit: https://github.com/ratoaq2/knowit/issues
