### ISSUE TITLE
Seed ratio improperly working

### ISSUE THREAD

**Issue by neo-neo1** [pymedusa/Medusa#8555]
**Describe the bug**
For all torrent search providers, setting a 0 (or 0.0) seed ratio does not set anything at all as if the option was left blank on the torrent client (Deluge daemon). 0.1 to 0.9 works properly but not 0 (or 0.0)

I just transferred over from SickChill where this was not a problem.

**To Reproduce**
1. Go to 'Search Providers'
2. Click on 'Provider Options'
3. Scroll down to 'Seed Ration'
4. Set to 0 (or 0.0)

**Expected behavior**
A seed ratio of 0.0 to be set in the torrent client (Deluge daemon) when a torrent is snatched. With a 0.0 seed ratio the torrent client does not seed at all and stops the torrent after download is complete.

**Medusa**
 - OS: [Docker Container Alpine 3.12] on host [5:19.03.13~3-0~debian-buster]
 - Branch: master
 - Version: 0.4.3 (2020-09-08)
- Commit: Unknown 
- Database: 44.16
- Python: 3.8.5

</details>

**Comment by Entixs** [comment]
what are you trying to do with seed ratio 0.0? Do you want them to seed forever or not?

**Comment by neo-neo1** [comment]
> what are you trying to do with seed ratio 0.0? Do you want them to seed forever or not?

To seed forever you use -1. I need a seed ratio of 0.0 for a specific tracker, commonly known as "leech". Instead of Medusa setting the seed ratio as 0.0 it simply does not set anything at all as if the option was set blank. Works fine in SickChill.

In this manner the torrent client does not seed at all and stops the torrent after download is complete.

**Comment by Entixs** [comment]
I know this is probably a bug but can't you simply do that on your torrent client as well? Set a ratio setting for that specific tracker to stop seeding right after it's done downloading?

**Comment by neo-neo1** [comment]
> I know this is probably a bug but can't you simply do that on your torrent client as well? Set a ratio setting for that specific tracker to stop seeding right after it's done downloading?

I don't know of any torrent client that offers per-tracker seed ratio settings. Again, I used this feature in SickChill without issues and would love if Medusa was also able to properly parse 0.0

**Comment by p0psicles** [comment]
I can create a branch with a change, would you be willing testing this out?
