### ISSUE TITLE
Custom Newznab Providers get deleted

### ISSUE THREAD

**Issue by neo-neo1** [pymedusa/Medusa#8557]
**Describe the bug**
If you add 'Custom Newznab Providers' and later disable 'NZB Search' all the 'Custom Newznab Providers' you added get deleted. This is an unwanted behavior which does not occur with SickChill (and probably other forks).

**To Reproduce**
1. Go to 'Search Settings'
2. Click on 'NZB Search'
3. Enable 'Search NZBs' and configure respective settings.
4. Save.
5. Go to 'Search Providers'
6. Click on 'Custom Newznab Providers' and fill out respective settings to add a NZB provider.
7. Save
8. Go to 'Search Settings'
9. Click on 'NZB Search'
10. Disable 'Search NZBs' and Save.
11. Go to 'Custom Newznab Providers' or ''Provider Priorities' and any custom added providers are gone.

**Expected behavior**
After adding 'Custom Newznab Providers' they should not be automatically deleted if you disable 'NZB Search'

**Medusa**
 - OS: [Docker Container Alpine 3.12] on host [5:19.03.13~3-0~debian-buster]
 - Branch: master
 - Version: 0.4.3 (2020-09-08)
- Commit: Unknown 
- Database: 44.16
- Python: 3.8.5

</details>

**Comment by p0psicles** [comment]
Is this still an issue with the latest release?
I did made a change to this in de frontend a while ago.

**Comment by neo-neo1** [comment]
No longer an issue.
