### ISSUE TITLE
Disable proxy for torrent application

### ISSUE THREAD

**Issue by def324** [pymedusa/Medusa#8601]
**Describe the bug**
When configuring a proxy server it will be used for connections to the torrent progam, specifically qBittorrent in my case. Since the proxy is public facing and qBittorrent is internal, it will break the connection.

**To Reproduce**
1. Go to 'Configuration -> General -> Advanced Settings -> Proxy Host' and configure an external proxy, such as torproxy.
2. Go to 'Configuration -> Search Settings -> Torrent Search' and configure and internal qBittorrent client.
3. Try to download an episode, you'll see the following error:

<img width="1064" alt="Screen Shot 2020-10-11 at 5 35 46 PM" src="https://user-images.githubusercontent.com/184112/95690846-f2601c00-0c1a-11eb-8094-fbe2162b69f5.png">

**Expected behavior**
Medusa bypasses the external proxy for internal torrent applications. Ideally this could be configured.

**Screenshots**
See above.

**Medusa (please complete the following information):**
 - OS: Docker (linuxserver/medusa) / Linux-4.14.24-qnap-x86_64-with
 - Branch: master
 - Version: 0.4.3
 - Python version: 3.8.5
 - Database version: 44.16

**Debug logs (at least 50 lines):**
See screenshot above.

**Comment by p0psicles** [comment]
I'll make separate proxy settings for providers, indexers, clients and general

**Comment by p0psicles** [comment]
implemented
