### ISSUE TITLE
[APP SUBMITTED]: 289882: Multiple entries found in show: Danmachi: ¿Qué tiene de malo intentar ligar en una mazmorra? 

### ISSUE THREAD

**Issue by gilberth** [pymedusa/Medusa#8612]
### INFO
**Python Version**: `3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.0-48-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/2ad08492812469ca0af5d28c70d9dfd0
### ERROR
<pre>
2020-10-14 23:45:30 ERROR    SEARCHQUEUE-BACKLOG-289882 :: [nyan2] :: [b352bb6] 289882: Multiple entries found in show: Danmachi: ¿Qué tiene de malo intentar ligar en una mazmorra? 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Force update the show

**Comment by gilberth** [comment]
### INFO
**Python Version**: `3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.0-48-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-10-17 23:46:34 ERROR    SEARCHQUEUE-BACKLOG-289882 :: [nyan2] :: [b352bb6] 289882: Multiple entries found in show: Danmachi: ¿Qué tiene de malo intentar ligar en una mazmorra? 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
