### ISSUE TITLE
Episode appears as snatched

### ISSUE THREAD

**Issue by sendas** [pymedusa/Medusa#8625]
**Describe the bug**
Episode appears as snatched but it was downloaded and moved to the correct folder...

Medusa Info:	Branch: master 
Commit: b352bb6924afcdfafce176a540d53ce405ca1312 
Version: 0.4.3 
Database: 44.16
 Python Version:	3.7.7 (default, Sep 27 2020, 05:32:31) [GCC 4.9.3 20150311 (prerelease)]
 SSL Version:	OpenSSL 1.0.2u 20 Dec 2019
 OS:	Linux-3.10.105-armv7l-with-glibc2.4
 Locale:	en_US.UTF-8
 	 
 	 
 User:	sc-medusa
Program Folder:	/volume1/@appstore/medusa/var/Medusa
 Config File:	/volume1/@appstore/medusa/var/config.ini
Database File:	/volume1/@appstore/medusa/var/main.db
 Cache Folder:	/volume1/@appstore/medusa/var/cache
 Log Folder:	/volume1/@appstore/medusa/var/Logs
Arguments:	
--daemon --pidfile /volume1/@appstore/medusa/var/medusa.pid --config /volume1/@appstore/medusa/var/config.ini --datadir /volume1/@appstore/medusa/var/

![image](https://user-images.githubusercontent.com/10220908/96333312-0368bd00-1061-11eb-8b92-eb970ed164ec.jpeg)

![image](https://user-images.githubusercontent.com/10220908/96333319-0a8fcb00-1061-11eb-8534-864cf640fe8e.jpeg)

![image](https://user-images.githubusercontent.com/10220908/96333370-5e9aaf80-1061-11eb-945d-2b77143eaf5c.jpeg)

**Comment by medariox** [comment]
As you can see there are 2 snatches. That means that it was snatched and processed and after that another one was snatched. Obviously we will never understand why this happened without debug los, that's why this issues will be closed until the relevant debug logs are posted.

**Comment by sendas** [comment]
Which logs do you need ? I've only notice this after 24h so are the logs still there ? What do you need from me ? Thanks !

**Comment by sendas** [comment]
Also I don't understand why the topic is closed even though it's a pertinent matter. You just have to tell me what you neee. I'm not a developer ...

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/wiki/FAQ's-and-Fixes#how-do-i-enable-debug-logs-to-get-more-detailed-information-in-my-logs
https://github.com/pymedusa/Medusa/wiki/FAQ's-and-Fixes#where-are-the-log-files-located

**Comment by p0psicles** [comment]
@medariox we should add those links to the template.? What you think?

**Comment by medariox** [comment]
@p0psicles 
Sounds like a good idea.

**Comment by sendas** [comment]
I use Mac so I can't use WinSCP

Is there an alternative ? Thanks

**Comment by p0psicles** [comment]
Try fugu. https://sourceforge.net/projects/fugussh/files/
