### ISSUE TITLE
Adding Recommended Shows - db type could not be determined

### ISSUE THREAD

**Issue by MatthK** [pymedusa/Medusa#8628]
I am trying to add some recommended shows, but whenever I try to add IMDB or add from Trakt lists, I get an error message saying:

```
Fetching of Recommender Data failed. Exception:
db type could not be determined

```
I tried to check the logs, but there is no entry indicating what the problem could be.

1. Add Recommended Shows
2. Click either on "Add From Trakt Lists" or "Add From IMDB's Popular Shows"
3. See error message above

Medusa Info: 
Branch: master
Commit: b352bb6924afcdfafce176a540d53ce405ca1312Version: 0.4.3Database: 44.16
Python Version: 3.6.9 (default, Oct 8 2020, 12:12:24) [GCC 8.4.0]
SSL Version: OpenSSL 1.1.1 11 Sep 2018
OS: Linux-4.15.0-117-generic-x86_64-with-Ubuntu-18.04-bionic
Locale: en_US.UTF-8

**Debug logs (at least 50 lines):**
After enabling the debug log and a restart, it shows this in the log files.
```
2020-10-19 18:25:08 WARNING	Thread :: [b352bb6] Could not connect to Trakt service: Trakt may have some issues and it's unavailable. Try again later please
```

**Comment by p0psicles** [comment]
Probably need to remove the recommended.dbm file and start.

**Comment by MatthK** [comment]
Thanks. I renamed the file (just in case) and restarted Medusa. After that it first timed out, but after the file stopped increasing in size, I tried again, and it works again.
