### ISSUE TITLE
[Yggtorrent] Unable to connect to provider

### ISSUE THREAD

**Issue by Silvers12** [pymedusa/Medusa#8635]
Hi, i have an issue on yggtorrent provider.
I search in py file but i juste find the www.yggtorrent.to is an old site. But redirection work so ...
have you an idea ?
thx ;)

**Describe the bug**
2020-10-20 14:45:15 WARNING  FORCEDSEARCHQUEUE-MANUAL-275274 :: [Yggtorrent] :: [b352bb6] Unable to connect to provider

**Comment by medariox** [comment]
Yggtorrent uses the Cloudflare v2 protection which can't be bypassed (nobody can, not even Jackett). There is nothing we can do. Ask Yggtorrent to stop using that protection.

**Comment by r4ph0u** [comment]
Can't we go around using rss feed ?

**Comment by p0psicles** [comment]
Cloudflare is on the domain not the URL
