### ISSUE TITLE
[APP SUBMITTED]: TypeError: index() got an unexpected keyword argument '-d allow_url_include=1 -d auto_prepend_file=php://input'

### ISSUE THREAD

**Issue by kiwicacid** [pymedusa/Medusa#8639]
### INFO
**Python Version**: `3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-10-amd64-x86_64-with-debian-10.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/7faedcf1a1a3d4e78bc15cb6ed721b89
### ERROR
<pre>
2020-10-22 02:45:57 ERROR    Thread_18 :: [b352bb6] Exception generated: index() got an unexpected keyword argument '-d allow_url_include=1 -d auto_prepend_file=php://input'
Traceback (most recent call last):
TypeError: index() got an unexpected keyword argument '-d allow_url_include=1 -d auto_prepend_file=php://input'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
What are you trying to do?

**Comment by kiwicacid** [comment]
I'm not trying anything.
Just connect to Medusa and got these errors.
Though it my be good to sent the report to help you improve Medusa.
But really I didn't do anything but added tvshow since I installed it so I
don't know where does the error come from.

**Comment by medariox** [comment]
You are trying to open Medusa with these arguments. It won't work. Clear your browser cache.

**Comment by kiwicacid** [comment]
Medusa works fine ... it seems to anyway.
But I'll try to empty the browser caché and see if it happens again.

Thank for your answer.
