### ISSUE TITLE
Rarbg

### ISSUE THREAD

**Issue by sendas** [pymedusa/Medusa#8648]
It seems rarbg provider is not working, but I can access it on the web...

2020-10-23 04:20:35 WARNING  SEARCHQUEUE-BACKLOG-76203 :: [Rarbg] :: [b352bb6] Unable to connect to provider

Medusa Configuration
 Medusa Info:	Branch: master 
Commit: b352bb6924afcdfafce176a540d53ce405ca1312 
Version: 0.4.3 
Database: 44.16
 Python Version:	3.7.7 (default, Sep 27 2020, 05:32:31) [GCC 4.9.3 20150311 (prerelease)]
 SSL Version:	OpenSSL 1.0.2u 20 Dec 2019
 OS:	Linux-3.10.105-armv7l-with-glibc2.4
 Locale:	en_US.UTF-8
 	 
 	 
 User:	sc-medusa
Program Folder:	/volume1/@appstore/medusa/var/Medusa
 Config File:	/volume1/@appstore/medusa/var/config.ini
Database File:	/volume1/@appstore/medusa/var/main.db
 Cache Folder:	/volume1/@appstore/medusa/var/cache
 Log Folder:	/volume1/@appstore/medusa/var/Logs
Arguments:	
--daemon --pidfile /volume1/@appstore/medusa/var/medusa.pid --config /volume1/@appstore/medusa/var/config.ini --datadir /volume1/@appstore/medusa/var/

**Comment by medariox** [comment]
Rarbg's API URL is different from the website. Probably temp blocked for abuse or banned. Anyway, it is working fine here. We can't help.

**Comment by sendas** [comment]
Blocked ?! But I can access the website ! Who can help then?

**Comment by sendas** [comment]
Any idea how to fix it ?!
