### ISSUE TITLE
Request/Question 

### ISSUE THREAD

**Issue by Dhop84** [pymedusa/Medusa#8655]
Is there anyway of setting this up on either Android - Seagate  Cloud which needs Medusa to be in a RBW file format to be able to install it as an app or Cpanel server?

**Comment by p0psicles** [comment]
Isn't rbw Ruby? Medusa is written in python

**Comment by Dhop84** [comment]
> Isn't rbw Ruby? Medusa is written in python

Any idea how I would get it into the rbw file format?

**Comment by p0psicles** [comment]
Don't think it's possible. It's a totally different language

**Comment by Dhop84** [comment]
> Don't think it's possible. It's a totally different language

O OK, what about on Cpanel ?

**Comment by p0psicles** [comment]
Check our wiki on installation. You'll see all supported OS/platforms.

You'll always have to run it with python3
