### ISSUE TITLE
Distribute through Flathub

### ISSUE THREAD

**Issue by LongJohn-Silver** [pymedusa/Medusa#8656]
**Is your feature request related to a problem? Please describe.**
The absence of flatpak support.

**Describe the solution you'd like**
To add flatpak support.

**Describe alternatives you've considered**
None.

**Additional context**
One of the biggest advantages in contrast with snaps, is that flatpaks are sandboxed, and therefore this results in a more secure and private experience since it is harder for some kind of malware to attack the system, or for said application to retrieve user information without them knowing it. Another good point is that everything that's uploaded to Flathub (Flatpak's centralized repository) is compiled by the same developers, and cannot be done by some random person on the internet which could lead to outdated packages, piracy, and whatnot. Just like snaps, Flatpaks are compatible with every distribution that supports it, so you don't have to be uploading a million different releases, and also is becoming a more standardized option for non-based and Ubuntu based distributions alike, being adopted already by twenty five flavours of Linux, and some of them come with flatpak preinstalled out of the box (CentOS, ElementaryOS, EndlessOS, Fedora, Linux Mint, PureOS and ZorinOS).

More information:

https://flathub.org/
https://flatpak.org/
https://flatpak.org/setup/
https://docs.flatpak.org/en/latest/

**Comment by p0psicles** [comment]
I checked the docs. But flathub is more for desktop applications. Like they require a .desktop file. Medusa runs as a daemon.

Also there are some restrictions to file access. Making it a little bit hard to get it easily configured for everyone

**Comment by LongJohn-Silver** [comment]
> I checked the docs. But flathub is more for desktop applications. Like they require a .desktop file. Medusa runs as a daemon.
> 
> Also there are some restrictions to file access. Making it a little bit hard to get it easily configured for everyone

Well, I'm not an expert, but Sonarr also runs as a daemon but when you download it as a snap it has a .desktop file, also, on low computers like mine, it's not such a bad idea to run it as a desktop applications, because I only let them running to search something, then I kill the process so that it doesn't slow down my system.

And regarding to file access, yeah, I think that's related to isolation, but I'm not sure.

**Comment by p0psicles** [comment]
Meduasa is designed to run 24/7. If you don't, you can have issues. So that's not recommended.

I think sonar installs and then runs background. The desktop icon opens the local website in your browser.

If I'm really bored I might look into it

**Comment by LongJohn-Silver** [comment]
Ohh, I see, fair enough, then.

**Comment by medariox** [comment]
We also don't have resources to make something like this happen. This is an open source project, so you are more than welcome to contribute if you come up with something.
