### ISSUE TITLE
Customize the tracker request

### ISSUE THREAD

**Issue by blackmessor** [pymedusa/Medusa#8676]
An issue i got with some tracker. For a specific show for exemple "Black Clover" number 143, the request sent to the tracker is "Black clover 143". 
The problem is some(standard in the list, like "elite-tracker" required a "E" before the episode number, otherwise it found nothing. 

**Describe the solution you'd like**
Is this possible to have a function to custumize request sent to a tracker ?
For exemple, put a letter befor the episode number, or replace "Space" by ".". ???

Thx for all you work, you product is really cool

**Comment by medariox** [comment]
Provider issue, we won't add more search patterns to fix their buggy search engine.
