### ISSUE TITLE
[Feature Request] Use Medusa with NZBHydra2?

### ISSUE THREAD

**Issue by neo-neo1** [pymedusa/Medusa#8677]
Is Medusa linkable to NZBHydra/NZBHydra2? It's a nice Jackett alternative that I would love to see Medusa support.

**Comment by medariox** [comment]
It's already supported. Just add it as custom NZB provider.

**Comment by neo-neo1** [comment]
Thanks. A separate tab like there is for Jackett would be useful and clear things up.
