### ISSUE TITLE
 Failed parsing provider.

### ISSUE THREAD

**Issue by digitalgp** [pymedusa/Medusa#8682]
*2020-11-02 23:12:51 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [54da0c7] Failed parsing provider.
Traceback (most recent call last):
  File "/opt/medusa/medusa/providers/torrent/html/iptorrents.py", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/8674
