### ISSUE TITLE
Detect internal video parameters of file, instead of scraping from the name.

### ISSUE THREAD

**Issue by mglaske** [pymedusa/Medusa#8697]
**Is your feature request related to a problem? Please describe.**
Sometimes, when episodes are downloaded, the resolution isn't included, or is not formatted properly.  This results in medusa rejecting the file, even though it was proper.  

**Describe the solution you'd like**
Utilize libraries from various sources like pymediainfo to check the files internally.  Additional information about the video quality could also be useful in the episode metadata, such as, duration, actual resolution (yes it's 1080p, but it might be 1920x800 or 1920x1080, etc) Audio channels, bitrate, and more recently details around 4k video, including 8-bit or 10-bit, color encoding, etc.  Additionally, computing a md5 or simliar hash, could also help determine if newly downloaded video files are identical.

**Describe alternatives you've considered**
Creating my own "external" media information libraries, but it's not integrated.  I don't think anyone else does this afaik.

**Additional context**
Here is a json snippet of what my movie database tool stores per mkv file:
```
"8b2c2940c03e028e8ac9717d79f8c1d8": {"title": "Maze.Runnner.The.Death.Cure", "filetype": "mkv", "md5sum": "8b2c2940c03e028e8ac9717d79f8c1d8", "filename": "/d1/movies/Action/Maze.Runnner.The.Death.Cure.2018/Maze.Runner.The.Death.Cure.2018.BluRay.1080p.DTS-HDMA7.1.2Audio.x264.mkv", "valid": true, "filesize": "17.70GB", "year": "2018", "genre": "Action", "mkvinfo": {"duration": "2:23:52", "audio": [{"language": "en", "format": "DTS", "channels": "8 / 6", "bit_depth": 24, "codec": "DTS", "freq": 48000}, {"language": "zh", "format": "AC-3", "channels": 6, "bit_depth": 16, "codec": "AC3", "freq": 48000}], "video": [{"aspect_ratio": "2.40:1", "bit_depth": 8, "height": 802, "width": 1920, "bit_rate": "12.00Mb/s", "codec": "V_MPEG4/ISO/AVC", "resname": "1080p", "frame_rate": "23.976", "duration": null, "resolution": "1920x802"}], "chapters": null, "title": null}}
```

**Comment by p0psicles** [comment]
If the resolution is not included, we use the lib knowit to scan the file. 

Make sure you installed ffmpeg / fprobe. Or check knowit on GitHub page, for details

**Comment by medariox** [comment]
This is already being done if mediainfo or ffmpeg is installed.
