### ISSUE TITLE
Allow for multiple resolutions to be stored per episode.

### ISSUE THREAD

**Issue by mglaske** [pymedusa/Medusa#8698]
**Is your feature request related to a problem? Please describe.**
There are a few tv series that I would like to download in 4k.  However, I have multiple tv's that cannot support 4k that still would like to watch those episodes.  Currently, with medusa, it only supports (afaik) 1 file per episode.  I do not want to take the transcoding hit for these shows converting 4k down to 1080p, or even 720p.  Additionally 10bit video does not transcode easily to 8bit for non-HDR players.

**Describe the solution you'd like**
Allow a tv show to download and store multiple resolutions per episode.

**Describe alternatives you've considered**
Creating an entirely separate medusa instance for the 4k content, and some kind of external utility that symlinks the files together for my player (plex).  Very hacky.

**Comment by p0psicles** [comment]
This is to complex, to add any time soon. 
Better implement alternative if you really want this

**Comment by medariox** [comment]
This has been discussed multiple times already and won't be added by us (PRs welcome).
