### ISSUE TITLE
[ FEATURE ] keep looking for better quality after manual snatch

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#872]
Branch/Commit: last develop
OS: synology last DSM
What you did: 
quality settings of a show set to HD1080p
I forced a manual search of the episode s06E04, snatched a release with 720p HDTV quality.
it seems that Medusa considers this as allowed (as it appears in yellow)
![suits main](https://cloud.githubusercontent.com/assets/9487685/17583288/789772c6-5fb0-11e6-8a65-4e32bb3dc4ce.JPG)
a few days later, it has NOT been replaced by another release matching the quality setup. (HD1080p)
another manual search shows that releases are present, matching the quality settings.
![suits manual search](https://cloud.githubusercontent.com/assets/9487685/17583342/cd9805c4-5fb0-11e6-83da-b6e8cbc704c7.JPG)
What you expected:
I thought that Medusa would have replaced my manually snatched episode

is it an expected behaviour?

**Comment by NicoLeOca** [comment]
@fernandog 

![backlog suits](https://cloud.githubusercontent.com/assets/9487685/17635018/97996028-60d5-11e6-9646-fae6aead5e58.JPG)

**Comment by fernandog** [comment]
force backlog and send full logs of backlog thread

**Comment by NicoLeOca** [comment]
full logs, not filtered but last pieces are only about the backlog search
https://gist.github.com/NicoLeOca/332f27a3a7b5d66afc709840a4f7da56

One wierd message is:
Episode already exists with quality 720p HDTV and the found result has same/lower quality, ignoring found result for Suits S06E01 with quality 1080p WEB-DL

**Comment by NicoLeOca** [comment]
@fernandog 
1080p was just snatched automatically for the last episode of Suits

The "undesired behaviour is that manually snatching a lower quality makes Medusa consider this snatch as of allowed quality and doesn't replace then

**Comment by fernandog** [comment]
@NicoLeOca did you changed anything in quality settings? still on develop branch?

where did you got that sentence?

**Comment by NicoLeOca** [comment]
@fernandog 
still on dev yes
no I didn't change anything

that sentence is mine, it's my personal opinion

**Comment by fernandog** [comment]
@NicoLeOca by design any manual search episode turns off the auto search feature.

if you want to keep searching for better quality, just set it to wanted after you manuall searched it

**Comment by NicoLeOca** [comment]
@fernandog 
ok thanks for the advice
