### ISSUE TITLE
Enable backlog/manual searches with custom RSS torrent providers

### ISSUE THREAD

**Issue by wchan-ranelagh** [pymedusa/Medusa#8749]
**Is your feature request related to a problem? Please describe.**
After adding a custom RSS torrent provider, and updating its options to allow for daily searches, it is only using it for daily searches and when doing backlog/manual searches it doesn't seem to use these providers.  It would be great if they can be used in those other search types as well.

**Describe the solution you'd like**
Have backlog/manual (or another other search types) use the custom RSS torrent providers that are configured.

**Describe alternatives you've considered**
No alternative other than forcing daily searches and/or waiting for the next daily search every time I want to use the custom RSS providers.

**Comment by medariox** [comment]
Custom RSS providers only work for daily searches and that won't change for technical reasons.
