### ISSUE TITLE
Telegram notifications stopped working with latest update

### ISSUE THREAD

**Issue by johnvick** [pymedusa/Medusa#8771]
Branch: masterCommit: d0c136d7a528a471b51676140bd35d24d97f65c6Version: 0.4.6Database: 44.17
--
Python Version: | 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-5.7.0-050700-generic-x86_64-with
Locale: | en_US.UTF-8
  |  
  |  
User: | root
Program Folder: | /app/medusa
Config File: | /config/config.ini
Database File: | /config/main.db
Cache Folder: | /config/cache
Log Folder: | /config/Logs
Arguments: | --nolaunch --datadir /config
Web Root: | /medusa
Runs in Docker: | Yes

No messages and when I test get forbidden message. No changes made to config.

**Comment by medariox** [comment]
No logs, no support. Please fill the Bug report template as required.

**Comment by p0psicles** [comment]
Works fine here. Something wrong with your configuration
