### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: france.tv

### ISSUE THREAD

**Issue by Merrick28** [pymedusa/Medusa#8811]
### INFO
**Python Version**: `3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]`
**Operating System**: `Linux-4.19.0-12-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/6b04ad44adf47e74a41d121b29f18c28
### ERROR
<pre>
2020-12-01 15:28:44 ERROR    APIv2-Thread_2 :: [] Missing time zone for network: france.tv
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Added.
