### ISSUE TITLE
Medusa does not start any more after the latest update on my Synology

### ISSUE THREAD

**Issue by dr88dr88** [pymedusa/Medusa#8812]
Medusa does not start any more after the latest update on my Synology.

**Comment by medariox** [comment]
Install the correct package from https://github.com/pymedusa/Medusa/wiki/Synology
Other type of installs are not supported.

**Comment by dr88dr88** [comment]
Thanks this fixed the issue.
I had was using Sickbear Custom package.  
After installation I have restored successfully the backup that was created before the upgrade.
