### ISSUE TITLE
Medusa wont start after latest update

### ISSUE THREAD

**Issue by haroldboom** [pymedusa/Medusa#8817]
*Describe the bug**
Medusa wont start after latest update. Manually starting the medusa service fails, see logs below.

**To Reproduce**
service medusa start
service medusa status - shows a failure

**Expected behavior**
expected medusa to start

**Medusa (please complete the following information):**
 - OS: Debian 9.13
 - Branch: master
 - Commit: ce68da57b
 - Python version: Python 3.5.3
 - Database version: not sure how to find this

**Debug logs (at least 50 lines):**
Cant get medusa to start to enable debug

**Additional context**
 See logs below when commands are run;

**root@server:/opt/medusa# service medusa status**
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-12-02 15:49:37 AEDT; 6s ago
  Process: 13430 ExecStart=/usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa (code=exited, status=1/FAILURE)
 Main PID: 13430 (code=exited, status=1/FAILURE)

Dec 02 15:49:36 server systemd[1]: medusa.service: Main process exited, code=exited, status=1/FAILURE
Dec 02 15:49:36 server systemd[1]: medusa.service: Unit entered failed state.
Dec 02 15:49:36 server systemd[1]: medusa.service: Failed with result 'exit-code'.
Dec 02 15:49:37 server systemd[1]: medusa.service: Service hold-off time over, scheduling restart.
Dec 02 15:49:37 server systemd[1]: Stopped Medusa Daemon.
Dec 02 15:49:37 server systemd[1]: medusa.service: Start request repeated too quickly.
Dec 02 15:49:37 server systemd[1]: Failed to start Medusa Daemon.
Dec 02 15:49:37 server systemd[1]: medusa.service: Unit entered failed state.
Dec 02 15:49:37 server systemd[1]: medusa.service: Failed with result 'exit-code'.

**root@server:/opt/medusa# /usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa**
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.1.0l  10 Sep 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "/opt/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/opt/medusa/medusa/naming.py", line 27, in <module>
    from medusa.tv import Episode, Series
  File "/opt/medusa/medusa/tv/__init__.py", line 6, in <module>
    from medusa.tv.cache import Cache
  File "/opt/medusa/medusa/tv/cache.py", line 27, in <module>
    from medusa.rss_feeds import getFeed
  File "/opt/medusa/medusa/rss_feeds.py", line 7, in <module>
    from feedparser.api import parse
  File "/opt/medusa/ext/feedparser/__init__.py", line 28, in <module>
    from .api import parse
  File "/opt/medusa/ext/feedparser/api.py", line 37, in <module>
    from . import http
  File "/opt/medusa/ext/feedparser/http.py", line 146
    new_pieces[1] = f'{url_pieces.hostname}:{url_pieces.port}'
                                                             ^
SyntaxError: invalid syntax

**Comment by p0psicles** [comment]
Please fill out the issue template like requested

**Comment by haroldboom** [comment]
> Please fill out the issue template like requested

sorry about that, fixed now

**Comment by p0psicles** [comment]
Update python to at least 3.6. 3.5 is bugged
