### ISSUE TITLE
Restart impossible after update

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#8818]
**Describe the bug**
Yesterday, i have update my Medusa and since, unable to restart appli.

**To Reproduce**
1. Go to 'application center'
2. Click on 'medusa'
3. Scroll down to 'click on start'
4. " failure to start the repair of the package"

**Expected behavior**
The automatic restart failed as after all the other updates, but today the manual restart also failed, although it was working before.

**Screenshots**
![Capture d’écran 2020-12-02 à 10 34 10](https://user-images.githubusercontent.com/5829636/100854996-fd506380-3489-11eb-9880-ef33eb27499b.png)

**Medusa (please complete the following information):**
 - OS: Synology DSM 6.0.2
 - Branch: Master
 - Commit: The las t i think
 - Python version: 3.5.6.8
 - Database version: the last i think

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
Full log: /volume1/@appstore/medusa/var/medusa.log
Wed Dec  2 10:12:52 CET 2020
Starting medusa command /volume1/@appstore/medusa/env/bin/python /volume1/@appstore/medusa/var/Medusa/start.py --daemon --pidfile /volume1/@appstore/medusa/var/medusa.pid --config /volume1/@appstore/medusa/var/config.ini --datadir /volume1/@appstore/medusa/var/
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2n  7 Dec 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/Medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/volume1/@appstore/medusa/var/Medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/volume1/@appstore/medusa/var/Medusa/medusa/naming.py", line 27, in <module>
    from medusa.tv import Episode, Series
  File "/volume1/@appstore/medusa/var/Medusa/medusa/tv/__init__.py", line 6, in <module>
    from medusa.tv.cache import Cache
  File "/volume1/@appstore/medusa/var/Medusa/medusa/tv/cache.py", line 27, in <module>
    from medusa.rss_feeds import getFeed
  File "/volume1/@appstore/medusa/var/Medusa/medusa/rss_feeds.py", line 7, in <module>
    from feedparser.api import parse
  File "/volume1/@appstore/medusa/var/Medusa/ext/feedparser/__init__.py", line 28, in <module>
    from .api import parse
  File "/volume1/@appstore/medusa/var/Medusa/ext/feedparser/api.py", line 37, in <module>
    from . import http
  File "/volume1/@appstore/medusa/var/Medusa/ext/feedparser/http.py", line 146
    new_pieces[1] = f'{url_pieces.hostname}:{url_pieces.port}'
                                                             ^
SyntaxError: invalid syntax
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Check https://github.com/pymedusa/Medusa/issues/8812#issuecomment-736620121 for the fix

**Comment by FransAlmere** [comment]
Same here
![Sickbeard cannot start package](https://user-images.githubusercontent.com/13037978/100858760-b1ec8400-348e-11eb-9db8-83cb2faf1d8c.jpg)
![Sickbeard custom error log](https://user-images.githubusercontent.com/13037978/100858765-b2851a80-348e-11eb-96bb-a04c9c8f2d06.jpg)
