### ISSUE TITLE
How install python 3.8 on synology ?

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#8819]
Hy,

to resolve my restart issue after the last updat, i need to install an other Medusa package for synology but when i try to install "Medusa 1.1 Python 3 noarch.spk" Synology said me to install Python 3.7 or more...

It's possible to install directly the last Python 3.8.x on synology ?

Rgds
Akhlan

**Comment by medariox** [comment]
Just install Python 3.7 and after install Medusa: https://synocommunity.com/package/python3

**Comment by p0psicles** [comment]
https://github.com/pymedusa/Medusa/wiki/Synology
