### ISSUE TITLE
To use Medusa on synology, i need to instal pkg of Python3 v3.7.7-15

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#8820]
Hello,

I have a lot of pkg...

https://synocommunity.com/package/python3
> Python3 v3.7.7-15
> Python Programming Language.
> 
> Version 3.7.7-15
> Update openssl to 1.1
> Date
> 2020-10-13 21:04:54.183220
> Architectures
> 6.1 qoriq 6.1 apollolake 6.1 avoton 6.1 braswell 6.1 broadwell 6.1 broadwellnk 6.1 bromolow 6.1 cedarview 6.1 denverton 6.1 dockerx64 6.1 geminilake 6.1 grantley 6.1 purley 6.1 kvmx64 6.1 v1000 6.1 x86 6.1 x86_64 6.1 evansport 6.1 88f628x 6.1 armada370 6.1 armada375 6.1 armada38x 6.1 alpine 6.1 alpine4k 6.1 armadaxp 6.1 comcerto2k 6.1 monaco 6.1 rtd1296 6.1 armada37xx 6.1 aarch64 1.2 northstarplus 1.2 ipq806x 1.2 dakota 5.2 ppc853x 6.1 hi3535

How find my pkg ?

I have on Synology DS3615XS under Xpenology with an AMD processor if this information is necessary...

Who can help me ?

Rgds

**Comment by medariox** [comment]
https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model
Try 6.1 bromolow

**Comment by akhlan** [comment]
> https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model
> Try 6.1 bromolow

I can't, i have a 6.0.2-8451 DSM and I can't update to 6.1 or 6.2 because XPEnology isn't comptabible with AMD processor

**Comment by medariox** [comment]
Nobody forces you to use XPEnology. Honestly, it's not our problem. You need to e update DSM.
