### ISSUE TITLE
Require ALL the required words (i.e Logical AND vs OR)

### ISSUE THREAD

**Issue by caeci11ius** [pymedusa/Medusa#8824]
Would be good to have an option to require all of the required words (e.g. "hdr AND atmos" vs "hdr OR atmos"). Also, as it stands, the UI is confusing when it comes to the word lists (at least to me). I would have assumed that a list of required words would require all of the words before matching, rather than the existing match when any word is present. Even if there's not to be an option to set one or the other, it would be good for the UI to make it clear that a match will occur when any single word is present.

**Comment by p0psicles** [comment]
I can add some comments in the UI. But the functionality right now is sufficient for 99÷ of the use cases. Adding options would make it more confusing IMO.

**Comment by medariox** [comment]
You can just combine words like `hdtv.x264` and that should cover the remaining 1%.
