### ISSUE TITLE
Manual search "bypass filters" or "show results which your filters excluded"  

### ISSUE THREAD

**Issue by jaxjexjox** [pymedusa/Medusa#8826]
**Is your feature request related to a problem? Please describe.**
Shows not downloading despite being available.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

My system regularly 'misses' shows, which ARE available.
I suspect, this is due to aggressive filters (size requirements, resolution etc)

**Describe the solution you'd like**
Ability to perform a 'full hard search' regardless of filters and or tell or explain to me why it skipped X Y or Z release of a show

**Describe alternatives you've considered**
N/A

**Additional context**
Thanks for the hard work

**Comment by medariox** [comment]
Enable debug logging and run a manual search. That's exactly what it does.
