### ISSUE TITLE
Medusa won´t start on Synology after latest update

### ISSUE THREAD

**Issue by MrFearmanDK** [pymedusa/Medusa#8827]
Came home from work today, logged in to Medusa, it´s says your XX commits behind, i choose update and then Medusa won´t start anymore.
I get the following error on Synology: "Failed to run the Package service"
Tried uninstalling and then reinstall, but when installing it requires Python 2.7 or greater (already installed 3.7.7) but it still requires to have Python 2.7 to be installed?
Installing using "medusa_noarch-all_20181023.spk" on Synology, cannot find any newer spk for Synology
How to get Medusa working again, please advice!

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/wiki/Synology

**Comment by MrFearmanDK** [comment]
Super thx, the new installer (spk) was what i needed to get it running on Python 3.7.
