### ISSUE TITLE
Postprocessing a series with a year in the file name

### ISSUE THREAD

**Issue by seth586** [pymedusa/Medusa#8828]
Postprocessing doesn't recognize a TV show when the year is in the filename, example:
```
The Man in the High Castle (2015) - S04E01 - Hexagram 64.mkv
```
is not recognized, `2020-12-04 02:17:31 WARNING  POSTPROCESSOR :: [ce68da5] Missed file: /media/downloads/complete/The Man in the High Castle (2015) Season 4 S04/The Man in the High Castle (2015) - S04E01 - Hexagram 64.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode`

However this works:
```
The Man in the High Castle - S04E01 - Hexagram 64.mkv 
```

Plex differentiates same title movies and series by a year in (), so in my opinion this should be recognized.

**Comment by p0psicles** [comment]
Add The Man in the High Castle (2015) as a scene exception for that show
