### ISSUE TITLE
Medusa wont start after update

### ISSUE THREAD

**Issue by XSplinter** [pymedusa/Medusa#8831]
I just update Medusa from it's interface and now it wont start.

when trying to start it goes like this:

`sudo systemctl start medusa
Job for medusa.service failed because the control process exited with error code. See "systemctl status medusa.service" and "journalctl -xe" for details.
`

When I run systemctl status medusa.service it gives me this
```
● medusa.service - Medusa
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-12-04 12:42:19 UTC; 1min 17s ago
  Process: 15100 ExecStart=/opt/.venv/medusa/bin/python3 /opt/medusa/SickBeard.py -q --daemon --nolaunch --datadir=/opt/medusa (code=exited, status=1/FAILURE)

```
Any help will be appreciated

**Comment by medariox** [comment]
Python version?

**Comment by medariox** [comment]
Medusa needs Python 3 – 3.6.0 and newer to run. This has been announce many months ago. Update Python and it will work.

**Comment by XSplinter** [comment]
Thanks, I only had python 2.7 installed, after installing 3.6 and 3.7 Medusa works again
