### ISSUE TITLE
Permissions issue on postprocessed files on the docker version of Medusa

### ISSUE THREAD

**Issue by Anthodev** [pymedusa/Medusa#8838]
**Describe the bug**
Hello, i have a strange issue with Medusa on the postprocessed files.

I use Medusa on Docker (18.09.8) on a Synology NAS (DS218+, DSM 6.2.3) and so, the file download with SynoDS are downloaded just fine, the issue is that when the file is postprocessed (with a **Move** parameter), the file is losing all its permission (`000 root:root`) meaning the file is unreadable for Plex in the destination directory.

At the moment the only thing i can do is redo the permission through the web portal of my Syno, but it's a pain in the ass to not be able to completely automate the process.

Of course the destination folder has the correct permissions (for both Medusa and Plex) and the file is correctly moved to the destination folder, it is just unreadable for Plex since it lose all its permissions.

**To Reproduce**
1. Set the postprocess on Move
2. Let the postprocess kicked in
3. Check the permission on the file moved

**Expected behavior**
The file should keep its previous permissions.

**Medusa (please complete the following information):**
 - OS: Docker 18.09.8 (on a Synology NAS with DSM 6.2.3)
 - Branch: master
 - Python version: the one from the docker image
 - Database version: same as above

**Comment by BenjV** [comment]
Typical docker problem.
You would do better to us the native Synology Package for Medusa.
You can find it here.

https://github.com/BenjV/SYNO-packages

**Comment by medariox** [comment]
Are you also running Medusa as root? Does it also happen with copy?

**Comment by Anthodev** [comment]
I have used the package from @BenjV, it works correctly now, thanks.

But for your information @medariox, the container was running as root and i didn't test with copy.

**Comment by Freaksed** [comment]
I have this same issue and i do not want to use the synology package, i want to keep it in the docker container. Mine is set to copy not move.

**Comment by BenjV** [comment]
Still a permission problem of the docker container I guess.

Make sure the downloader creates files with a permission that medusa give access rights to read/write them.
Also make sure that on the target location the medusa user has read/write permissions.
