### ISSUE TITLE
Season Expansion Toggle

### ISSUE THREAD

**Issue by trumblejoe** [pymedusa/Medusa#8840]
**Is your feature request related to a problem? Please describe.**
Large shows have too many episodes and are slow to load. They can be buggy when slow resulting in medusa freezing as-well.

**Describe the solution you'd like**
For shows with more then 10 seasons (arbitrary number), load each Season 1, Season 2, etc only after they have been expanded by toggling an expansion button for that particular season. The amount of clicks this would add is minimal, the time saved enormous. See shows like Survivor and attempt to open Season 1. Even using the dropdown quick select, it freezes too much or doesn't work at all.

**Comment by medariox** [comment]
You can select how many episodes load x page. Just set it to the season size, e.g. 50 and it will load fast.
