### ISSUE TITLE
Download links missing, settings missing

### ISSUE THREAD

**Issue by GldRush98** [pymedusa/Medusa#8841]
**Describe the bug**
Download links are missing on the episode list for a show

**To Reproduce**
1. Go to a show's page
2. Make sure the download column is turned on
3. The column is blank, there should be http links based on configured setting for the web portal, but these settings are missing as well

**Expected behavior**
Download links available and settings for it.

**Screenshots**
https://i.imgur.com/AE7JVPF.png

**Medusa (please complete the following information):**
 - Docker: linuxserver/medusa:latest (0.5.0)
 - Branch: master

**Comment by p0psicles** [comment]
We've decided to remove them in the next release. In next release the download column will also be gone.

**Comment by GldRush98** [comment]
Well guess that answers that. I hate seeing features get removed but it is what it is.

**Comment by p0psicles** [comment]
It was broken for 1 year already. So nobody seemed to use it

**Comment by GldRush98** [comment]
Huh, always worked for me. Just had to have the URL set right. It's no biggie, I just thought it was a bug.

**Comment by p0psicles** [comment]
It was combining the URL with the absolute local path. Like http://../c:\\series\\...

**Comment by GldRush98** [comment]
Ah guess I got lucky with how I had my paths set up.
