### ISSUE TITLE
ImportError: _htmlparser

### ISSUE THREAD

**Issue by sioban** [pymedusa/Medusa#8842]
Hello,

I'm having a bug since several day that prevent me starting Medusa anymore:

When I try to run "systemctl start medusa.service", I'm getting the following error:

"déc. 07 08:53:36 shax python2.7[6304]: ERROR:stevedore.extension:Could not load 'legendastv': 'module' object has no attribute '_base'
déc. 07 08:53:37 shax python2.7[6304]: ERROR:stevedore.extension:Could not load 'shooter': cannot import name _htmlparser
déc. 07 08:53:37 shax python2.7[6304]: ERROR:stevedore.extension:Could not load 'podnapisi': cannot import name _htmlparser
déc. 07 08:53:37 shax python2.7[6304]: ERROR:stevedore.extension:Could not load 'tvsubtitles': cannot import name _htmlparser
déc. 07 08:53:37 shax python2.7[6304]: ERROR:stevedore.extension:Could not load 'opensubtitles': cannot import name _htmlparser
déc. 07 08:53:37 shax python2.7[6304]: ERROR:stevedore.extension:Could not load 'addic7ed': cannot import name _htmlparser
déc. 07 08:53:37 shax python2.7[6304]: ERROR:stevedore.extension:Could not load 'subscenter': cannot import name _htmlparser
déc. 07 08:53:37 shax python2.7[6304]: ERROR:stevedore.extension:Could not load 'thesubdb': cannot import name _htmlparser
déc. 07 08:53:37 shax python2.7[6304]: ERROR:stevedore.extension:Could not load 'argenteam': cannot import name _htmlparser
déc. 07 08:53:37 shax python2.7[6304]: ERROR:stevedore.extension:Could not load 'opensubtitlesvip': cannot import name _htmlparser
déc. 07 08:53:37 shax python2.7[6304]: Traceback (most recent call last):
déc. 07 08:53:37 shax python2.7[6304]:   File "/home/archives/downloads/nzb/extensions/Medusa/start.py", line 6, in <module>
déc. 07 08:53:37 shax python2.7[6304]:     from medusa.__main__ import main
déc. 07 08:53:37 shax python2.7[6304]:   File "/home/archives/downloads/nzb/extensions/Medusa/medusa/__init__.py", line 24, in <module>
déc. 07 08:53:37 shax python2.7[6304]:     initialize()
déc. 07 08:53:37 shax python2.7[6304]:   File "/home/archives/downloads/nzb/extensions/Medusa/medusa/init/__init__.py", line 38, in initialize
déc. 07 08:53:37 shax python2.7[6304]:     _configure_subliminal()
déc. 07 08:53:37 shax python2.7[6304]:   File "/home/archives/downloads/nzb/extensions/Medusa/medusa/init/__init__.py", line 210, in _configure_subliminal
déc. 07 08:53:37 shax python2.7[6304]:     from subliminal import provider_manager, refiner_manager
déc. 07 08:53:37 shax python2.7[6304]:   File "/home/archives/downloads/nzb/extensions/Medusa/ext/subliminal/__init__.py", line 16, in <module>
déc. 07 08:53:37 shax python2.7[6304]:     from .providers import Provider
déc. 07 08:53:37 shax python2.7[6304]:   File "/home/archives/downloads/nzb/extensions/Medusa/ext/subliminal/providers/__init__.py", line 4, in <module>
déc. 07 08:53:37 shax python2.7[6304]:     from bs4 import BeautifulSoup, FeatureNotFound
déc. 07 08:53:37 shax python2.7[6304]:   File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
déc. 07 08:53:37 shax python2.7[6304]:     from .builder import builder_registry, ParserRejectedMarkup
déc. 07 08:53:37 shax python2.7[6304]:   File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 311, in <module>
déc. 07 08:53:37 shax python2.7[6304]:     from . import _htmlparser
déc. 07 08:53:37 shax python2.7[6304]: ImportError: cannot import name _htmlparser
déc. 07 08:53:37 shax systemd[1]: medusa.service: Control process exited, code=exited, status=1/FAILURE
déc. 07 08:53:37 shax systemd[1]: medusa.service: Failed with result 'exit-code'.
déc. 07 08:53:37 shax systemd[1]: Failed to start Medusa Daemon.
"

I've tried to clone a completely fresh Medusa repo (while keeping my inis) and I'm getting the same error :/

**Medusa (please complete the following information):**
 - OS: Debian 10
 - Branch: master
 - Commit: ce68da57b3878591f77c21bb2acf28e6a58269fa
 - Python version: 2.7.16
 - Database version: <don't know how to get this one>

**Comment by medariox** [comment]
Python 2.7 is not supported anymore. Update to Python 3.6 or newer.
