### ISSUE TITLE
Fetching of Recommender Data failed

### ISSUE THREAD

**Issue by sioban** [pymedusa/Medusa#8850]
Hello,

When I try to go to Trakt Most Anticipated Shows, I'm getting this error:

```
Fetching of Recommender Data failed. Exception:
int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```

**To Reproduce**
1. Go to "Shows"
2. Click on "Add Recommended Shows"
3. Click on "Add from Trakt lists"

It start searching the throw the error "Fetching of Recommender Data failed. Exception:"

"Add From IMDB's Popular Shows" does not have this problem.

**Medusa (please complete the following information):**
- OS: Debian 10
- Branch: master
- Commit: ce68da5
- Python version: 3.7.3-2+deb10u2

**Debug logs (at least 50 lines):**
no logs even with debug mode activated

**Comment by p0psicles** [comment]
Fixed in develop branch
