### ISSUE TITLE
NZBGet generic dupe keys if show indexer is not TVDB

### ISSUE THREAD

**Issue by sunn0** [pymedusa/Medusa#8853]
**Describe the bug**
NZBGet dupe keys for shows that were added with TVDB are constructed like that: Medusa-{Show ID}-{Season}.{Episode}
NZBGet dupe keys for shows that were added with TVmaze or TMDB are constructed like that: -{Season}.{Episode}

The latter format is very prone to creating false duplicate releases.

**To Reproduce**
1. Add show 1 with TVmaze, search and grab season 1 (No need to download, queue should be enough)
2. Add show 2 with TVmaze, search and grab season 1. Episodes should be marked as dupes.

**Expected behavior**
Less generic dupe keys. Either the TVDB format for all, or in case of overlapping IDs between TVDB, TVmaze and TMDB something like Medusa-{Indexer ID}-{Show ID}-{Season}.{Episode} for TVmaze and TMDB (not for TVDB so the old dupe key system remains valid).

**Comment by medariox** [comment]
Duplicate. Post here: https://github.com/pymedusa/Medusa/issues/8735
