### ISSUE TITLE
Cannot login to medusa

### ISSUE THREAD

**Issue by Vince0511** [pymedusa/Medusa#8862]
**Describe the bug**
When I try to connect to my medusa it wont logon. After typing my user+pass it goes back to the login page (Asking for username + password. In the botom-right corner it said "Loading 0 of 0 shows"

New episodes are snatched and downloaded as normal by the way.

**Expected behavior**
It should login.

I've tried to change the password in config.ini. No luck. :-(
Can someome help me, please?

**Comment by medariox** [comment]
Stop Medusa, edit password in config.ini, start Medusa.

**Comment by Vince0511** [comment]
Thanks. It worked...
I did it several times yesterday, without any luck. I had a systemreboot pending. Thanks anyway
