### ISSUE TITLE
No GUI working

### ISSUE THREAD

**Issue by barukh27** [pymedusa/Medusa#8866]
Hi,

I've updated to the new version and I've found this issue. (I'm an OSMC raspberry user)

When I try to access the WebUI via myip:8081 it doesn´t work. I've reinstalled manually following the tutorial. The service is running. What could be the reason? Any hint?

Thanks in advance.

![image](https://user-images.githubusercontent.com/49249214/101938353-7adf4680-3be3-11eb-87f2-755c7391d9ff.png)

**Comment by p0psicles** [comment]
Correct port? Check your log in Logs/application.log. maybe port not available?

**Comment by barukh27** [comment]
Thank you for your answer.

I'm still quite a noob and I don't know how to get there. I've followed these paths so far:

/opt/medusa 
 /opt/medusa/medusa
/medusa/var/Logs/

But I'm not able to find the directory.

**Comment by p0psicles** [comment]
Probably /opt/medusa/Logs

**Comment by barukh27** [comment]
I've tried that too.
![image](https://user-images.githubusercontent.com/49249214/101941630-8bde8680-3be8-11eb-9ffd-0c5eed5545e1.png)
![image](https://user-images.githubusercontent.com/49249214/101941749-b92b3480-3be8-11eb-82af-2348be18e973.png)
![image](https://user-images.githubusercontent.com/49249214/101941809-cea05e80-3be8-11eb-927d-cc6553519d66.png)

I can't find it.

How should I continue?

**Comment by p0psicles** [comment]
Check your folder rights/ownership. Should be the same user as used in the systemd script

**Comment by barukh27** [comment]
It's the same: osmc.

**Comment by barukh27** [comment]
I'm trying to change the port manually (to 8083) but I'm not able to find the file config.ini

**Comment by p0psicles** [comment]
It's not able to create those files. Thus I think something wrong with file access

**Comment by p0psicles** [comment]
You can  also stop service. And run manually. Like sudo -u osmc /usr/bin/python3 /opt/medusa/start.py

**Comment by barukh27** [comment]
> sudo -u osmc /usr/bin/python3 /opt/medusa/start.py

It worked!

Thank you very much.
