### ISSUE TITLE
KeyError: (3, 9) when running post-processing in SABNZDB to Medusa

### ISSUE THREAD

**Issue by Kvothe1970** [pymedusa/Medusa#8869]
**Describe the bug**
I used to have the integration of Post Processing from SabNZDB to Medusa working. Suddenly this stopped working and I not sure if I broke something. 

When running the script, the following error is logged: 

Traceback (most recent call last): File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToSickBeard.py", line 270, in <module> import nzbToMedia File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/nzbToMedia.py", line 727, in <module> eol.check() File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/eol.py", line 99, in check warn_for_status(version, grace_period) File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/eol.py", line 140, in warn_for_status days_left = lifetime(version) File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/eol.py", line 70, in lifetime time_left = PYTHON_EOL[(major, minor)] - now

This is the config in autoProcessMedia.cfg

[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 1
        host = localhost
        port = 7073
        apikey = ""
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        process_method = ""
        # force processing of already processed content when running a manual scan.
        force = 0
        # tell SickRage/Medusa to delete all source files after processing.
        delete_on = 1
        # tell Medusa to ignore check for associated subtitle check when postponing release
        ignore_subs = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""
        ##### Set the recursive directory permissions to the following (0 to disable)
        chmodDirectory = 0

**Medusa (please complete the following information):**

Medusa Info: | 
Branch: master
Commit: ce68da57b3878591f77c21bb2acf28e6a58269faVersion: .0.5.0
Database: 44.17
-- | --
Python Version: | 3.9.0 (default, Nov 30 2020, 13:01:15) [GCC 8.4.0]
SSL Version: | OpenSSL 1.1.1h 22 Sep 2020
OS: | Linux-4.2.8-armv7l-with-glibc2.27
Locale: | en_US.UTF-8

I had a look at https://github.com/pymedusa/Medusa/wiki/NZBtoMedia but I am pretty sure that a) have not changed a thing, and b) the sections are as outlined there: but I would appreciate any help. I checked the logs for nzbtomedia and they are not being updated after a download is finished.

**Comment by p0psicles** [comment]
Looks like an nzbToMedia bug. 
Better report there.

**Comment by Kvothe1970** [comment]
Cheers! Will do, honestly working on narrowing things down here. I will mark this as done on here.
