### ISSUE TITLE
Add Recommended Show (Trakt) - fails - Fetching of Recommender Data failed. Exception:  int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by Avian-Flew** [pymedusa/Medusa#8873]
Show > Add recommended shows > Add from Trakt Lists

Error - 
Fetching of Recommender Data failed.
Exception:  int() argument must be a string, a bytes-like object or a number, not 'NoneType'

IMDB works - albeit slowly
AniDB works.

Deleted all .dbm files in Cache folder and restarted Medusa.

No effect.

No detail being captured in Logs (regardless of level).

![Trakt1](https://user-images.githubusercontent.com/59357800/102127035-e1fb3600-3e43-11eb-8043-57f72c511ea2.JPG)
![trakt2](https://user-images.githubusercontent.com/59357800/102127056-e9224400-3e43-11eb-9e51-59f49351577c.JPG)

**Comment by p0psicles** [comment]
already fixed in develop branch
