### ISSUE TITLE
Add New Parent Folder Unexpected Selection Behavior

### ISSUE THREAD

**Issue by trumblejoe** [pymedusa/Medusa#8874]
**Describe the bug**
Going to call this a bug, it's unexpected behavior which burned me pretty good at one point by placing shows in an unexpected directory. The parent folder selection does not automatically change to the newly added parent folder, it must be manually changed by the user, it will instead change to the default location. Obviously, if I'm adding a new parent folder, I must need or want that location and I expect the selection to change to that automatically.

**To Reproduce**
1. Add a new show, 
2. On Step 2 picking the parent folder, add a new parent folder
3. The selection will not automatically change to the newly added parent folder, it will stay on (or change to) the default selection.

**Expected behavior**
I expected the selection in the selection box to change to my newly added parent show location directory.

Medusa Info: | 
Branch: master
Commit: Unknown
Version: 0.5.0
Database: 44.17
Python Version: | 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
SSL Version: | OpenSSL 1.1.1g 21 Apr 2020
OS: | Linux-4.19.0-0.bpo.9-amd64-x86_64-with
Locale: | en_US.UTF-8

**Comment by medariox** [comment]
It's not surprising, it's the default behavior in most software. Just select it atfer you have created it.
