### ISSUE TITLE
Option to choose a root directory located on other NAS

### ISSUE THREAD

**Issue by mikeo999** [pymedusa/Medusa#8903]
I am using Medusa on Synology (NAS1). But my shows are moved to my second Synology (NAS2) for different reasons.
Bu now i have the problem I can't select the shows folder from NAS1 (Medusa) that are located on NAS2.

Would be great it there is/comes a solution to browse the network so you can choose on witch server the shows are.

**Comment by p0psicles** [comment]
Just mount it?

**Comment by medariox** [comment]
Why can't you select the shows on NAS2?

**Comment by mikeo999** [comment]
Because i can only see the folders from the nas where Medusa is running on. 

Thought is would be nice option it you can put in a path or IP-adres an choose other network devices the easy way.

**Comment by medariox** [comment]
The easy way is to mount the drive. Feature requests need to be posted here: https://github.com/pymedusa/Medusa/discussions/categories/ideas-feature-requests
