### ISSUE TITLE
User selectable date format for Format Settings - Air by date: YYYY MM DD and/or MM DD YYYY

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/Medusa#8904]
The problem is that the kind souls that post  **The Late Show With Stephen Colbert** now abbreviate the show name and use a reverse air date format (**YYYY MM DD** rather **MM DD YYYY**) that Medusa can't recognize; i.e., 
**Stephen Colbert 2020 12 14 Christopher Walken 1080p WEB H264-JEBAITED EZTV** _and_
**Stephen.Colbert.2020.12.14.Christopher.Walken.720p.WEB.H264-JEBAITED**
(Same poster is formatting with and without "**.**" separator).

Of course the abbreviated show name is easy to deal with as a Scene Exception, and date format does make for better sorting so it may catch on.   Never know...

The example above is the most prevalent format for this particular series, but other formats are or were used, too:    
**The Late Show With Stephen Colbert S02E015 2016 09 26 Rob Lowe, Kal Penn, Emma Willmann [UTR] mkv**

It would be very helpful to have user selectable date format for Format Settings - Air by date, analogous to the Scene Exception feature:  **YYYY MM DD** and/or **MM DD YYYY**.

Alternatives I've considered?  I see only one alternative: manual search of usenet and torrent indexers.

Thank you.

**Comment by medariox** [comment]
First format (YYYY MM DD) is recognized by Medusa without issues.
Second format also recognized, just don't use air by date.

**Comment by DrakeJones** [comment]
Doesn't work either way.  Even a forced manual search gives "No search results available" with Air by date on or off.  

**And if I go to an indexer, download and manual post process with Air by date _off_:**

Processing path: D:\ADMIN\comp\tv
Processing folder: D:\ADMIN\comp\tv
Post-processing files: ['stephen.colbert.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv']
Post-processing video files: ['stephen.colbert.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv']
Processing failed for D:\ADMIN\comp\tv\stephen.colbert.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv: Not enough information to determine what episode this is
Problem(s) during processing, failed for the following files/folders:
Missed file: D:\ADMIN\comp\tv\stephen.colbert.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv: Processing failed: Not enough information to determine what episode this is 

**If I go to an indexer, download and manual post process with with Air by date _on_:**

Post-processing results
Processing path: D:\ADMIN\comp\tv
Processing folder: D:\ADMIN\comp\tv
Post-processing files: ['stephen.colbert.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv']
Post-processing video files: ['stephen.colbert.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv']
Processing failed for D:\ADMIN\comp\tv\stephen.colbert.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv: Not enough information to determine what episode this is
Problem(s) during processing, failed for the following files/folders:
Missed file: D:\ADMIN\comp\tv\stephen.colbert.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv: Processing failed: Not enough information to determine what episode this is 

_If I change title to **stephen.colbert.12.16.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv** and manually postprocess SUCCESS!_

Processing path: D:\ADMIN\comp\tv
Processing folder: D:\ADMIN\comp\tv
Post-processing files: ['stephen.colbert.12.16.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv']
Post-processing video files: ['stephen.colbert.12.16.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv']
Processing D:\ADMIN\comp\tv\stephen.colbert.12.16.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv
Looks like this is an air-by-date or sports show, attempting to convert the date to season and episode
Show information parsed from file name
Retrieving episode object for The Late Show with Stephen Colbert S06E56
The episode file has a quality in it, using that: 720p WEB-DL
Snatch in history: False
Manually snatched: False
Info hash: None
NZB: False
Current quality: 1080p HDTV
New quality: 720p WEB-DL
Proper: False
This episode is a priority download: True
Old file: F:\TV Shows\Stephen Colbert\The Late Show with Stephen Colbert - 6x56 - Tom Hanks, Leslie Odom Jr.mkv
New file: D:\ADMIN\comp\tv\stephen.colbert.12.16.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv
Old size: 458.96 MB
New size: 906.73 MB
New file is 447.77 MB larger
This download is marked a priority download so I'm going to replace an existing file if I find one
No associated files were found for F:\TV Shows\Stephen Colbert\The Late Show with Stephen Colbert - 6x56 - Tom Hanks, Leslie Odom Jr.mkv
Deleting file: F:\TV Shows\Stephen Colbert\The Late Show with Stephen Colbert - 6x56 - Tom Hanks, Leslie Odom Jr.mkv
Found release name stephen.colbert.12.16.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re]
Destination folder for this episode: F:\TV Shows\Stephen Colbert
No associated files were found for D:\ADMIN\comp\tv\stephen.colbert.12.16.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv
Moving file from D:\ADMIN\comp\tv\stephen.colbert.12.16.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv to F:\TV Shows\Stephen Colbert\The Late Show with Stephen Colbert - 6x56 - Tom Hanks, Leslie Odom Jr.mkv
Processing succeeded for D:\ADMIN\comp\tv\stephen.colbert.12.16.2020.12.16.tom.hanks.720p.web.h264-jebaited[eztv.re].mkv
Post-processing completed.

**Comment by medariox** [comment]
It's just because you are changing name, which invalidates the cache. You have to keep air by on the first time. You can test that it works by just changing the group name.

**Comment by DrakeJones** [comment]
Thanks.  I'll test it in an hour or two...
