### ISSUE TITLE
Getting Error when clicking Subscribe button in Schedule

### ISSUE THREAD

**Issue by weekender23** [pymedusa/Medusa#8905]
Hi

I am running medusa on macOS 10.14.6 and when i click on the button Subcribe in the Schedule tab, I get a error in the Calendar app:

" There was an error subscribing to the calendar. The data downloaded from webcal://localhost:8081/calendar isn’t valid."

I tried changing the link from webcal://localhost:8081/calendar to http://localhost:8081/calendar and still get the same error.

**Comment by medariox** [comment]
There is already an issue about this. Closing as duplicate.
