### ISSUE TITLE
Unable to start Medusa Daemon

### ISSUE THREAD

**Issue by henmad** [pymedusa/Medusa#8908]
**Describe the bug**
Medusa Daemon does not start on reboot of raspbian, nor on manual restart with systemctl. The sytem reports failed to start and code=exited, status=1/Failure. 

Likely occured after a recent update. I have not touched the system except for updating Medusa.

See snip from terminal here:
<details>

pi@raspberrypi3:~ $ systemctl status medusa.service
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-12-22 10:13:45 CET; 1min 18s ago
  Process: 666 ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa (code=exited, status=1/FAILURE)
 Main PID: 666 (code=exited, status=1/FAILURE)

Dec 22 10:13:44 raspberrypi3 systemd[1]: medusa.service: Failed with result 'exit-code'.
Dec 22 10:13:45 raspberrypi3 systemd[1]: medusa.service: Service hold-off time over, scheduling restart.
Dec 22 10:13:45 raspberrypi3 systemd[1]: Stopped Medusa Daemon.
Dec 22 10:13:45 raspberrypi3 systemd[1]: medusa.service: Start request repeated too quickly.
Dec 22 10:13:45 raspberrypi3 systemd[1]: Failed to start Medusa Daemon.
Dec 22 10:13:45 raspberrypi3 systemd[1]: medusa.service: Unit entered failed state.
Dec 22 10:13:45 raspberrypi3 systemd[1]: medusa.service: Failed with result 'exit-code'.
pi@raspberrypi3:~ $ ^C
pi@raspberrypi3:~ $ /usr/bin/python2.7 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa
Traceback (most recent call last):
  File "/opt/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/opt/medusa/medusa/init/__init__.py", line 23, in initialize
    _monkey_patch_fs_functions()
  File "/opt/medusa/medusa/init/__init__.py", line 94, in _monkey_patch_fs_functions
    from medusa.init import filesystem
  File "/opt/medusa/medusa/init/filesystem.py", line 12, in <module>
    from builtins import map
ImportError: No module named builtins
pi@raspberrypi3:~ $

</details>

**Comment by medariox** [comment]
Python 2.7 is not supported anymore. Check the wiki for help on how to update to Python 3.

**Comment by thumDer** [comment]
Same issue here. I have both python and python3 installed on my synology, but medusa wants to use python 2.7 which is not supported anymore. how can I make medusa to use python 3 if its available?

**Comment by medariox** [comment]
There is a new Synology package linked in the wiki that uses Python 3.

**Comment by thumDer** [comment]
great, thank you!

**Comment by thumDer** [comment]
Since I cannot start medusa anymore, and can't make a backup I didn't want to uninstall the existing version and install a new package. After some googling I was able to make medusa use python3 with the following method, if anyone is interested:
https://www.reddit.com/r/synology/comments/ienn8l/replacing_python_package_for_medusa/
