### ISSUE TITLE
Show Specials in Schedule

### ISSUE THREAD

**Issue by dotsam** [pymedusa/Medusa#8910]
In a previous request #7252, it was made clear that Medusa will never attempt to search and download specials, and I agree with this, as it's not likely to be reliable.

What I would like to propose however is an option to show specials on the schedule, much like there is currently an option for showing/hiding paused shows.

Doing a quick test removing the `season != 0` condition from [medua/show/coming_episodes.py](https://github.com/pymedusa/Medusa/blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/show/coming_episodes.py#L88) seems to get the result I want. I think the only other thing I'd like to see is some additional attention drawn to them in the view, similar to the `[paused]` that shows for paused shows.

Thoughts? I can try submitting a pull request implementing this in pretty much the same way as "display paused" if you'd like.

**Comment by p0psicles** [comment]
I think it's a good idea. PR always welcome. Make sure to branch develop. 

Can, you give us access to your fork, so we can also make changes

**Comment by medariox** [comment]
Please use https://github.com/pymedusa/Medusa/discussions/categories/ideas-feature-requests
for feature requests. Issues if for bug reports only.
