### ISSUE TITLE
Sorting with article "The" even though option is disabled on main page

### ISSUE THREAD

**Issue by deusxanime** [pymedusa/Medusa#8911]
**Describe the bug**
This issue has persisted for quite a while and I believe it was marked fixed for v0.5.0, but I still see it. On the main page of Medusa (Show List), series titles that start with "The" are sorting on the article even though I have that option disabled under General > Interface > Sort with 'The' 'A', 'An'. Accessing page using Chrome v87.0.4280.88 (Official Build) (64-bit).

**To Reproduce**
While gathering info for this I remembered I sort by the Status column on the Show List page, so that "Ended" status series are not cluttering up active shows. Previously this would sort by Status and then secondarily by Show title column, and it still does so except the issue with titles that begin with an article like "The". If I sort directly by the Show title column instead, then it does work and ignores articles when alphabetizing. 

I also wanted to point out that initially it seems like it works. If I sort by "Show" title column it works and then if I go back and have it sort by the "Status" column it initially looks good and is ignoring articles when sorting. But as soon as I refresh the page (with it still set to sort by Status column), it is back to putting all the "The" series together with the T's.

**Expected behavior**
If I have the "Sort with 'The' 'A', 'An'" option disabled, it should never sort using "The" or other articles. I'd expect it to always honor that setting even if the Show title is a being used as a secondary sorting method, such as when sorting by Status column first.

**Screenshots**
![image](https://user-images.githubusercontent.com/11891866/103032735-67f33d00-4526-11eb-9b4c-dd96a943fd7e.png)

![image](https://user-images.githubusercontent.com/11891866/103032760-76415900-4526-11eb-956c-6c98280d89d2.png)

**Medusa (please complete the following information):**
 - OS: unRAID v6.8.3, using docker container by linuxserver.io
 - Branch: master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76
 - Version: 0.5.1
 - Python version: 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
 - Database version: 44.17

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug

I enabled debug log and tried changing the sort columns etc as described and nothing was logged. Don't think this goes into the logs so not sure how helpful they would be?

<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
If you want to sort by two columns, you have to use the shift key when clicking the second column.
Have you tried this?

**Comment by deusxanime** [comment]
> If you want to sort by two columns, you have to use the shift key when clicking the second column.
> Have you tried this?
> 
> ![image](https://user-images.githubusercontent.com/1331394/103132473-fab9e600-46a4-11eb-81f2-7fb4c4c823cf.png)

I had not tried that as I didn't know it was a thing! When I sorted by Status it still maintained alphabetical order on the Show column (other than articles of course), so I assumed that was defaulting to be the secondary sorting method. Clicking on Status to sort with that as the primary, and then shift-Clicking on Show to make it the secondary, does work. Articles are ignored and it is working as expected after using those steps.
