### ISSUE TITLE
Error pulling show image

### ISSUE THREAD

**Issue by Marthisdil** [pymedusa/Medusa#8919]
**Describe the bug**
Since the last update, anytime I pull a new show, Medusa has issues pulling the show's cover image.

**To Reproduce**
1) Add a new show
2) See warning log for message

**Expected behavior**
Show cover should be pulled

**Screenshots**
![image](https://user-images.githubusercontent.com/98221/103136408-c84cc080-4685-11eb-9526-9a5f0d8b05e5.png)

**Medusa (please complete the following information):**

Medusa Info: | Branch: masterCommit: UnknownVersion: UnknownDatabase: 44.17
-- | --
Python Version: | 3.9.0 (default, Oct 7 2020, 23:09:01) [GCC 10.2.0]
SSL Version: | OpenSSL 1.1.1h 22 Sep 2020
OS: | Linux-4.19.107-Unraid-x86_64-with-glibc2.32
Locale: | en_GB.UTF-8
  |  
  |  
User: | nobody
Program Folder: | /opt/medusa
Config File: | /config/config.ini
Database File: | /config/main.db
Cache Folder: | /config/cache
Log Folder: | /config/Logs
Arguments: | --config /config/config.ini --datadir /config
Runs in Docker: | Yes

**Comment by p0psicles** [comment]
no debug logs
no info on indexer used

**Comment by medariox** [comment]
Closing because of missing debug logs.
