### ISSUE TITLE
smtps support

### ISSUE THREAD

**Issue by faust64** [pymedusa/Medusa#8920]
**Is your feature request related to a problem? Please describe.**

Currently, Medusa may relay mail using SMTP or SMTP+STARTTLS: https://github.com/pymedusa/Medusa/blob/f39927ea6f0b3d18856dce32d86af43d57713720/medusa/notifiers/emailnotify.py#L357

It would be nice to add SMTPS support.

**Describe the solution you'd like**

Maybe something similiar to SABnzbd: https://github.com/sabnzbd/sabnzbd/blob/c38eac0e4606df429435885bb76d4da13798535e/sabnzbd/emailer.py#L84

First try connecting with smtplib.SMTP_SSL, and try again with smtplib.SMTP if the previous connection failed.

**Describe alternatives you've considered**

Using starttls works fine. or plain smtp as well.
Though I would rather avoid having to expose non-SSL ports

**Additional context**

Running on Kubernetes. Trying to prove Istio encryption is a poor excuse not to properly configure SSL everywhere.

**Comment by p0psicles** [comment]
you can always do a pull request

**Comment by medariox** [comment]
Please use https://github.com/pymedusa/Medusa/discussions/categories/ideas-feature-requests
for feature requests. Issues if for bug reports only.
