### ISSUE TITLE
[APP SUBMITTED]: 75941: Multiple entries found in show: Elfen Lied 

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#8923]
### INFO
**Python Version**: `3.8.6 (default, Nov 20 2020, 23:57:10) [Clang 12.0.0 (clang-1200.0.32.27)]`
**Operating System**: `macOS-11.1-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@bf1c47cbabc291d8a81ad03e396353a7b877c41e
**Link to Log**: https://gist.github.com/638b2beb76b11acbfa63d14ff5c210dc
### ERROR
<pre>
2020-12-27 18:50:37 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [NZBHydra] :: [ee727bb] 75941: Multiple entries found in show: Elfen Lied 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
not the 1st time I've had this. comes every now & then, not sure how this is supposed to be an error though?

**Comment by p0psicles** [comment]
Someone messes up the absolute numbering on tvdb. Often it's quickly fixed. But medusa then already has it cached. A force full update and restart should fix it

**Comment by medariox** [comment]
Force full update.
