### ISSUE TITLE
Does not download the episodes that have the year in the title

### ISSUE THREAD

**Issue by j0shii** [pymedusa/Medusa#8925]
**Is your feature request related to a problem? Please describe.**
There are some trackers who name the episodes with the year and Medusa for some reason does not take them. For example: Gangs of London (2020) T01E07 STARZ WEBDL 1080p ESP DDP 5.1 ING DDP 5.1 x264 - Eml HDTeam Series

**Describe the solution you'd like**
Some way that Medusa can ignore the year because it conflicts to find the episodes, if it helps, the year is always in parentheses.

**Comment by medariox** [comment]
You need to add a scene exception. Read the wiki.
