### ISSUE TITLE
Clicking on Show Title does no longer reload the page

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#8940]
**Describe the bug**
I think this has somehow been caused by the vue-ification of the show detail screen. In older versions of medusa you could click on the shows title and the screen would refresh/reload.

I have just reprocessed a d/l-ed item and it was still shown as "snatched" on the show. clicking on the title did not change things. reloading the page in the browser worked.
i use this feature usually to see how far the refreshing of filenames is when i copy a show with lots of eps to medusa vie the  filesystem and trigger refresh.

BTW: it would be cool to be able to copy the needed medusa infos for an issue report from the apps Info menu via a copy to clipboard button...

**To Reproduce**
1. Go to a shows 'detail' screen
2. Click on '<Show title>'

**Expected behavior**
The detail screen should be updated/reloaded to the latest data available in medusa (files, status,...)

**Screenshots**
- there is not really anything to see except that nothing changes...
- also: no error logs  as this is not producing any errors

**Medusa (please complete the following information):**
Branch: masterCommit: d45caa6b010ad704f4fa84ad120ef4e0b8402e30
Version: 0.5.1
Database: 44.17

Python Version: 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
SSL Version: OpenSSL 1.1.1d 10 Sep 2019
OS: Linux-3.10.105-x86_64-with
Locale: en_US.UTF-8

**Comment by p0psicles** [comment]
All actions should update the show for you. 
Please describe what you did in mist detail possible. I'll try to reproduce

**Comment by Rouzax** [comment]
Are you using a Reverse Proxy? 
Likely it is caching the page.

**Comment by udochrist** [comment]
ok. here you are. it's a test-case not a use case:

- open two tabs and got to the same show in both tabs.
- change status of one ep from "downloaded" to "archived"
- this changes on the active tab immediatly.
- on the other tab you could previously click on the title of the show to refresh. this is no longer working.

(and no. no proxies. internal network to a docker container)

**Comment by medariox** [comment]
Why are you opening 2 tabs in the first place? Once Medusa is out of beta it will be a SPA (like Plex, Kodi, etc.) and you won't be even able to open multiple tabs. You better start getting used to it.

**Comment by udochrist** [comment]
its a testcase not a use case as i have written....

**Comment by medariox** [comment]
Okay. So, it's an invalid testcase as it doesn't reflect how it is supposed to be used. You can refresh the tab to get around it for now, but as I wrote, it won't be allowed in the future.

**Comment by udochrist** [comment]
i find it a regression. especially as clicking on the show title in that screen has always reloaded the screens content.
but do as you please.

i don't understand what you mean with SPA and only one tab allowed to open/correctly.
How would you control that? I quite often have the same tabs on multiple computers as well as spaces and tables open.
i don't see how it is a progress/enhancement to limit the usage of a web-app to a single instance..

**Comment by medariox** [comment]
You can still have multiple tabs, you just have to refresh the browser tab.

**Comment by p0psicles** [comment]
It's currently working as designed. SPA means single page application. And refers to only having to load an HTML page once. And the rest is handles through xhttprequest calls. 

In the future we'll also make better use of the browsers localstorage. So then this will be less of an issue for you.
