### ISSUE TITLE
Update done, and I can no longer auth

### ISSUE THREAD

**Issue by draden05** [pymedusa/Medusa#8959]
**Describe the bug**
Hi Team,
I updated Medusa with the user interface, and when I log back in, it says that I have no more content and I fall back to the login page

**To Reproduce**
1. Update with UI
2. Reboot auto after updated
3. When connecting, reloads the page
4. See error/info at the bottom right "Loaded 0 out of 0 Shows"

**Screenshots**
![image](https://user-images.githubusercontent.com/19173109/103582269-ced90480-4edd-11eb-9da7-0e75ea4c7b3e.png)

**Medusa (please complete the following information):**
 - OS: Debian 9.13
 - Branch: master/develop (same error)
 - Commit: lasteds
 - Python version: 3.8
 - Database version: 44.16

**Comment by medariox** [comment]
Shut down Medusa.

Open config.ini and change web_username and web_password to:
```
web_username = ""
web_password = ""
```
Start Medusa. You won't be asked to login. Set a new user and pass from UI and save.

**Comment by draden05** [comment]
Ok thx, i tried :)
That "bypass" the login, but once I put a new login and want to log in it reproduces the bug again and I cannot log in again.

**Comment by medariox** [comment]
What commit are you exactly on? Do you use encyption?

**Comment by draden05** [comment]
Did you follow the exact steps I described (shut down, etc.)? 
- Yes stop medusa
- Change value in config.ini
- Restart medusa
- Save new user/pass with UI
- Logout
- Login with the new user/pass
- Bug

What commit are you on?
- Medusa Info: 
Branch: master                 
Commit: 1c1d3279ea1c3bb891b8581671e21543aea00c8c  
Version: 0.5.1
Database: 44.17
Python Version: 3.8.2 (default, Dec  5 2020, 11:27:07)  [GCC 6.3.0 20170516]

Do you use encryption?
I think yes ?
```
encryption_version = 1
encryption_secret = "b'nRcT0xh1[..........]"
```

_What amazes me is that I only updated via interface and reboot :(_

**Comment by medariox** [comment]
Do the same steps as above and set
```
encryption_version = 0
encryption_secret = ""
```

**Comment by draden05** [comment]
Ok it saved my pass in plain text, and the login work :)
How to reactivate the encryption properly to see if that the problem?

**Comment by medariox** [comment]
General > Advanced Settings > Encrypt passwords

**Comment by draden05** [comment]
Mmmh ok that saved :
```
encryption_version = 1
encryption_secret = ""
```
and
```
web_username = mylogin
web_password = ""
```

So I can't auth again xD

**Comment by medariox** [comment]
Do as above and remove
```
encryption_version
encryption_secret
web_cookie_secret
```
From config. It will generate new secrets. You will have to renew all passwords

**Comment by draden05** [comment]
Great ! It's finally good!
Thanks for taking your time to help me, everything is good :)
