### ISSUE TITLE
Restrict modification for some user

### ISSUE THREAD

**Issue by Beanux** [pymedusa/Medusa#8961]
**Describe the solution you'd like**
I am searching a way to share the access of medusa to friend, but preventing them from doing any modification.
So i'm searching ho to put medusa in read only for them, but allowing me (or any admin) to continue to add content.
That's means it's mainly have an admin password for all of the writing change requested.

**Describe alternatives you've considered**
I don't have any idea how to show existing content, with resume and episodes available. So i didn't though about an alternative except by doing it myself with a quick and dirty way (i'm more a sysadmin than a developer).

Because, medusa doesn't work with POST/GET method only after looking for the way it work, to implement this myself, the main way to do it would be to add some auth restriction on the API.
This restriction would be done by putting a proxy apache, and using it with authentification and forbid all writing API call.

The main issue about this is: i don't know medusa enough to know if all modification pass through the api.
So if you won't implement this, i would like some "little" help about how medusa handle modification (if there are some not documented on https://medusaapi.docs.apiary.io/#) and what are the one that doesn't use the api.

Thanks for reading and thanks you for providing medusa and working on it :)

**Comment by p0psicles** [comment]
Contact us on discord. I'll add you to developers group

**Comment by medariox** [comment]
Please use https://github.com/pymedusa/Medusa/discussions/categories/ideas-feature-requests
for feature requests. Issues if for bug reports only.
