### ISSUE TITLE
Authentication check - TypeError: expected bytes-like object, not str

### ISSUE THREAD

**Issue by twolaw** [pymedusa/Medusa#8962]
New bug since last update from **linuxserver/medusa** docker.

**Branch:**   master
**Commit:**  e6025de42a034b5887e5806fda210e30f5a1e150
**Version:**  0.5.1
Database:    44.17
**Python Version:**   3.8.5 (default, Jul 20 2020, 23:11:29)  [GCC 9.3.0]
**SSL Version:**  OpenSSL 1.1.1i  8 Dec 2020
**OS:**   Linux-3.14.29-aarch64-with
**Locale:**  fr_FR.UTF-8

ERROR:
```
2021-01-05 20:18:03 ERROR	TORNADO :: [e6025de] Uncaught exception in APIv2: TypeError("a bytes-like object is required, not 'str'")
Request: GET /medusa/api/v2/config (172.17.0.1)
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/app/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/app/medusa/ext/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/app/medusa/medusa/server/api/v2/base.py", line 57, in async_call
    content = self._check_authentication()
  File "/app/medusa/medusa/server/api/v2/base.py", line 131, in _check_authentication
    username, password = auth_decoded.split(':', 2)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by p0psicles** [comment]
@medariox this was something we fixed ages ago right?

**Comment by medariox** [comment]
I think so. Update Medusa.. your on version 0.4.6

**Comment by twolaw** [comment]
I exported/imported configuration from v0.4.6 to v0.5.1.
So I aleady use 0.5.1 :

 ![image](https://user-images.githubusercontent.com/10365746/103698994-8899a900-4fa2-11eb-9580-4dccf1a86b7c.png)

**Comment by twolaw** [comment]
My connection to medusa goes through a nginx reverse-proxy which have Basic authentication.
The bug shows up when the medusa API key is not correct, the medusa API server processes the Basic authentication of the reverse-proxy :
```
GET /medusa/api/v2/config HTTP/1.1
Host: zzero.duckdns.org
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://zzero.duckdns.org/
X-Api-Key: wrong_api_key
DNT: 1
Authorization: Basic c2ltb246UVlLZXNSREY=
Connection: keep-alive
```
which is unknown for medusa of course.

**Comment by twolaw** [comment]
My connection to medusa goes through a nginx reverse-proxy which have Basic authentication.
The bug shows up when the medusa API key is not correct, the medusa API server processes the Basic authentication of the reverse-proxy :
```
GET /medusa/api/v2/config HTTP/1.1
Host: host.duckdns.org
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://host.duckdns.org/
X-Api-Key: wrong_api_key
DNT: 1
Authorization: Basic c2ltb248UVlLZXNRSEY=
Connection: keep-alive
```
which is unknown for medusa of course.
