### ISSUE TITLE
Medusa fails to load - Loaded 0 out of 0 shows.

### ISSUE THREAD

**Issue by quacker1982** [pymedusa/Medusa#8964]
This error was only happening via my Android device but tonight it is now happening via PC.
Both systems are using Chrome.
Medusa is running on Qnap, upgraded via Sherpa.

Main log in screen loads, I enter the username and password, bottom right of screen shows loaded 0 out of 0 shows.
![image](https://user-images.githubusercontent.com/1976774/103765493-2c4f8b80-506d-11eb-8b81-b4e170bb6e42.png)

**Comment by medariox** [comment]
See https://github.com/pymedusa/Medusa/issues/8959#issuecomment-754241542

**Comment by p0psicles** [comment]
Password changed? Else reset password in config.ini.

**Comment by quacker1982** [comment]
@medariox champion, simple fix.  not sure what happened there but it is working again.
