### ISSUE TITLE
Filter non video file (.exe)

### ISSUE THREAD

**Issue by red4573** [pymedusa/Medusa#8969]
Recently i have seen torrent source posting file .exe and  medusa snatching them is there anywhere where to blacklist them?  pretty sure no body here want to download malware in their system.

**Comment by medariox** [comment]
That's not possible. Use trusted providers and verified uploaders.

**Comment by p0psicles** [comment]
I think that's the best advice you can get. Fix this at the source. Plenty of providers that don't show uploading of exe files
