### ISSUE TITLE
cannot search or add form trakt list

### ISSUE THREAD

**Issue by NunoHiggs** [pymedusa/Medusa#8972]
**Describe the bug**
If i try to go to add form trackt list, i get the error:

Fetching of Recommender Data failed. Exception:
int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**To Reproduce**
1. Go to Show, Add recommended show, add form trackt list 
2. Enter
3. The error appears

**Expected behavior**
It was expected to show the track lists

**Medusa (please complete the following information):**
 - OS: Fedora 31
 - Branch: Master
 - Commit: b352bb6924afcdfafce176a540d53ce405ca1312
 - Python version:  3.76
 - Database version:  44.16

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

No error is presented even with debug active

</details>

**Comment by p0psicles** [comment]
Should be fixed in develop branch
