### ISSUE TITLE
Skip subtitle search if episode match keywords

### ISSUE THREAD

**Issue by r4ph0u** [pymedusa/Medusa#8980]
**Is your feature request related to a problem? Please describe.**
When a show is set to download subtitles, it will search for them even if the video file already have them (especially if they are hardcoded). This can make the ep post-processing being post-ponned over and over.

This behaviour doesn't allow to easily mix both local torrent providers (where ep are always subbed) and international ones (where there is mostly no subtitles)

**Describe the solution you'd like**
Skipped subtitles search if given keywords are in the file name (like "vostfr")

**Describe alternatives you've considered**
An alternative would be to skip subtitle search based on the provider of the file (some local torrent provider being known to only release subbed episodes)

**Comment by medariox** [comment]
Medusa should already detect internal subs. If the internal subs language is not detected (which we can't do anything about, it means the releaser didn't add a language to the internal sub), you can enable "Unknown language" in subtitles settings.
"

**Comment by medariox** [comment]
Also please use Discussions for feature requests: https://github.com/pymedusa/Medusa/discussions/categories/ideas-feature-requests

**Comment by r4ph0u** [comment]
Sorry, I didn't knew Discussions where only a thing. However, you're not adressing the hardcoded subtitles part of my request, hardcoded sub being, obviously, not detected. Filtering with keywords doesn't seems to be such a bad idea, as it would work weither or not the releaser has done his job properly
