### ISSUE TITLE
Release groups in whitelist are not kept after adding a new show 

### ISSUE THREAD

**Issue by hergonoway** [pymedusa/Medusa#8989]
**Describe the bug**
Whatever release group I add in whitelist while adding a new show, there're not kept once the show is added.

**To Reproduce**
1. add a new show
2. add 1 or more group in whitelist then click "add show"
3. go to the detail page of the show, those groups don't appear, go edit the show, those groups are not in the whitelist box

**Expected behavior**
whitelisted release groups should be kept after adding the show

**Medusa (please complete the following information):**
Branch: master 
Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76 
Version: 0.5.2 
Python Version: | 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
SSL Version: | OpenSSL 1.1.1i 8 Dec 2020
OS: | Linux-4.4.59+-x86_64-with

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/9047
