### ISSUE TITLE
Syntax error starting medusa

### ISSUE THREAD

**Issue by maxdamage2122** [pymedusa/Medusa#9021]
I had a working install of medusa on Ubuntu and after doing an update it would no longer start. I backed up my /opt/medusa folder and started a fresh install but it still won't start. I get the following error when starting the systemd service:

DEPRECATION: The OpenSSL being used by this python install (OpenSSL
1.0.2g  1 Mar 2016) does not meet the minimum supported version (>=
OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, Y
ou may encounter an unexpected Captcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/opt/medusa/medusa/naming.py", line 27, in <module>
    from medusa.tv import Episode, Series
  File "/opt/medusa/medusa/tv/__init__.py", line 5, in <module>
    from medusa.tv.base import TV
  File "/opt/medusa/medusa/tv/base.py", line 57
    key_attr = f'_{key}'
                       ^
SyntaxError: invalid syntax

**Comment by medariox** [comment]
To run Medusa from source you will need one of these Python versions:

Python 3 – 3.6.0 and newer
