### ISSUE TITLE
Adding a new jackett provider is impossible

### ISSUE THREAD

**Issue by skAnkinVR** [pymedusa/Medusa#9034]
**Describe the bug**
Can't add a new jackett provider using the form.

**To Reproduce**
1. Go to 'Params.'
2. Click on 'Search Providers' and 'Configure Jackett Provider' tab
3. Fill the form with your jackett provider params.
4. At the end, nothing happens when clicking on 'Add'

**Screenshots**
![image](https://user-images.githubusercontent.com/77527809/104806972-925db080-57db-11eb-8cdd-5c2af426ed76.png)

**Medusa (please complete the following information):**
 - OS: Raspi OS 
 - Branch: Master
 - Commit: 698ca1db9903a9f716d9ed1910972cbf70ea50e8 
 - Python version: 3.7.3
 - Database version: 44.17

**Comment by medariox** [comment]
@p0psicles The save button is gone.

**Comment by medariox** [comment]
ping @sinnlosername

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/9037
