### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Amazon Prime Video

### ISSUE THREAD

**Issue by artificial-chaos** [pymedusa/Medusa#9036]
### INFO
**Python Version**: `3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@698ca1db9903a9f716d9ed1910972cbf70ea50e8
**Link to Log**: https://gist.github.com/19fa92365612324045bff4a31978b657
### ERROR
<pre>
2021-01-16 11:38:47 ERROR    APIv2-Thread_2 :: [698ca1d] Missing time zone for network: Amazon Prime Video
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dirkronsmans** [comment]
### INFO
**Python Version**: `3.7.7 (default, Oct 13 2020, 16:39:42) [GCC 4.9.3 20150311 (prerelease)]`
**Operating System**: `Linux-4.4.59+-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@698ca1db9903a9f716d9ed1910972cbf70ea50e8
**Link to Log**: https://gist.github.com/4c3bb1263446ff182b771b02718938c2
### ERROR
<pre>
2021-01-17 00:07:11 ERROR    EPISODEUPDATER :: [698ca1d] Missing time zone for network: Amazon Prime Video
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
