### ISSUE TITLE
Wrong Network Gets Picked U\p

### ISSUE THREAD

**Issue by purevertigo** [pymedusa/Medusa#9040]
This show 
https://www.thetvdb.com/series/departure
when added to Medusa shows the network of 'Universal Channel' and not 'Universal TV'

I have checked tvdb and also done a force full update.

![Screen Shot 2021-01-18 at 00 10 54](https://user-images.githubusercontent.com/6506461/104844126-66991280-5922-11eb-92f0-83aad23498d0.jpg)

![Screen Shot 2021-01-18 at 00 11 07](https://user-images.githubusercontent.com/6506461/104844130-6a2c9980-5922-11eb-98d6-3febb18f353e.jpg)

Windows
master branch
python 3.7.3
Database: 44.17
Commit: 698ca1db9903a9f716d9ed1910972cbf70ea50e8

Wasn't sure if debug logs needed for this.

**Comment by medariox** [comment]
No debug logs are needed for this.
This is an issue with TheTVDB, so you will need to contact them to get it fixed.
https://www.thetvdb.com/series/departure
https://www.thetvdb.com/companies/universal-channel
