### ISSUE TITLE
Active Filter is linked to Xem Filter

### ISSUE THREAD

**Issue by isignupovertor** [pymedusa/Medusa#9043]
**Describe the bug**
When trying to filter based on "Active" also filters on "Xem"

**To Reproduce**
1. Change layout to Simple
2. Ensure both Select Columns > Active & Xem 
3. Change filtering of Xem

**Expected behavior**
Filtering of Active is irrespective of Xem 

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/20748052/104886365-84d23300-5961-11eb-93dd-96ad6276a2d0.png)
After changing only "Active" to "yes"
![image](https://user-images.githubusercontent.com/20748052/104886410-9a475d00-5961-11eb-8231-1f7fd57aa408.png)

**Medusa (please complete the following information):**
 - OS: Linux 
 - Branch: v0.5.3
 - Commit: 698ca1d
 - Python version: 3.8.5
 - Database version: 44.17

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
Nothing showing on Debug log

**Additional context**

**Comment by p0psicles** [comment]
It's a bug in the used vue-good-table component. I'll issue a bugreport there.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/9066
