### ISSUE TITLE
Configuring subtitles is making a lot of unneccesary requests for getting country flags

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#906]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop/55acb3b352a4be3e293e46c91bea5f0a6791df53
OS: Windows (client) / Windows and Debian (server)
What you did: Starting typing country.
What happened: 404's
What you expected: To only see requests for country flags that are available, and no unneeded requests.
Logs:

```
PASTE LOGS HERE
Even better, an image.. ->
```

![image](https://cloud.githubusercontent.com/assets/1331394/17731205/acadcc98-646c-11e6-9453-5e5b4bae45d7.png)

**Comment by OmgImAlexis** [comment]
We could either just request the needed ones by using js to lazyload the flags from data-src -> src or we could load all the flags in a single spritesheet so there's only a single file to load. Either should work fine.
