### ISSUE TITLE
Episodes do not go in season folders

### ISSUE THREAD

**Issue by Bester31** [pymedusa/Medusa#9073]
When doing post processing the files go into the root folder not the season folder or create the season folder if needed.

The naming convention is: Season %S/%SN - S%0SE%0E - %EN

**Comment by p0psicles** [comment]
Check your show folder access rights. 
And you got season folders enabled for the show?

**Comment by Bester31** [comment]
No problem with access rights.  Just an external drive via usb to the computer Medusa is running on.
I've looked all over for enabling season folders.  Not sure where that is.

Btw if I posted in the wrong section I apologize.  Where do I post general questions about getting up and running.  I'm switching from Sickbeard so I know generally what I'm doing.

Thanks

**Comment by medariox** [comment]
When you add a show, there you can turn it on/off.
We have an issue template for a reason, please use it when opening an issue.
