### ISSUE TITLE
ModuleNotFoundError: No module named 'validators.btc_address' after update to 0.5.4 

### ISSUE THREAD

**Issue by pax0707** [pymedusa/Medusa#9077]
**Describe the bug**
After update to 0.5.4 Medussa won't start.

**Medusa (please complete the following information):**
 - OS: Windows 10
 - Branch: master
 - Python version: 3.8.6

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
Traceback (most recent call last):
  File "C:\Miki\Medusa\start.py", line 6, in <module>
    from medusa.__main__ import main
  File "C:\Miki\Medusa\medusa\__main__.py", line 67, in <module>
    from medusa import (
  File "C:\Miki\Medusa\medusa\providers\__init__.py", line 41, in <module>
    provider_names = import_providers(__name__)
  File "C:\Miki\Medusa\medusa\providers\__init__.py", line 37, in import_providers
    import_submodules(package_name)
  File "C:\Miki\Medusa\medusa\providers\__init__.py", line 25, in import_submodules
    module = importlib.import_module(full_name)
  File "C:\Users\noc\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Miki\Medusa\medusa\providers\torrent\__init__.py", line 29, in <module>
    import_submodules(__name__)
  File "C:\Miki\Medusa\medusa\providers\torrent\__init__.py", line 22, in import_submodules
    valid_pkg = import_submodules(full_name)
  File "C:\Miki\Medusa\medusa\providers\torrent\__init__.py", line 17, in import_submodules
    module = importlib.import_module(full_name)
  File "C:\Users\noc\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Miki\Medusa\medusa\providers\torrent\html\thepiratebay.py", line 21, in <module>
    import validators
  File "C:\Miki\Medusa\ext\validators\__init__.py", line 2, in <module>
    from .btc_address import btc_address
ModuleNotFoundError: No module named 'validators.btc_address'
```
</details>

**Comment by p0psicles** [comment]
https://github.com/pymedusa/Medusa/discussions/9072

**Comment by medariox** [comment]
1. Remove any conflicting validators versions:
`pip uninstall validators`
or
`pip3 uninstall validators`

2. Delete the `__pycache__` folder in `Medusa\ext\validators`.

If the above doesn't work your update went wrong:
3. Get a new copy of the latest version via `git` or manually.

**Comment by p0psicles** [comment]
Leaving open for visibility

**Comment by pax0707** [comment]
Guess something broke during the upgrade.
Only a fresh copy solved it.

**Comment by steveschow** [comment]
This seems to have happened to me also.  If I reinstall will I lose my DB info?  what is the proper way to reinstall it without losing my existing DB?

**Comment by pax0707** [comment]
Backup 1st, just in case.
Download zip of master.
From your install folder delete files and folder that exist in zip you downloaded.
Copy files from zip (within Medusa-master folder) to your install folder.
Profit.

**Comment by medariox** [comment]
Alternative: All important files are stored in the Data folder (e.g. Medusa/Data). Take a backup of that folder and use the Windows installer for a new install. Once done shut down Medusa, replace the new Data folder with the backup one and finally start again.

**Comment by steveschow** [comment]
Alright, thanks that seems to have me back.  I have disabled auto-update.  what is the proper way to update Medusa?

**Comment by steveschow** [comment]
After I get the notification, what is the best way to actually update it without screwing it up as happened here, and happened once before too?

**Comment by Rouzax** [comment]
Mine also did not come back after the prososed solution, needed to clone a new git instance and copy back
- cache.db
- main.db
- config.ini

**Comment by p0psicles** [comment]
> After I get the notification, what is the best way to actually update it without screwing it up as happened here, and happened once before too?

You'll get a notification that will bring you to the /update page. There you can also always try yo update if a new version is available

**Comment by steveschow** [comment]
How would that be different or any less problematic then auto update?

**Comment by medariox** [comment]
@steveschow We believe that the auto updater causes the issue.

**Comment by utajum** [comment]
run `git checkout -- ext/validators/btc_address.py` and possibly also `git checkout -- ext/tornado/py.typed`

worked for me

**Comment by ToinneGuust** [comment]
> run `git checkout -- ext/validators/btc_address.py` and possibly also `git checkout -- ext/tornado/py.typed`
> 
> worked for me

This resuscitated my instance

**Comment by klauf** [comment]
> run `git checkout -- ext/validators/btc_address.py` and possibly also `git checkout -- ext/tornado/py.typed`
> 
> worked for me

Thanks, the first line did the trick trick for me also! Glad for the help.
