### ISSUE TITLE
Synology

### ISSUE THREAD

**Issue by sendas** [pymedusa/Medusa#9079]
**Describe the bug**

Since last update I couldn't access Medusa.

I've tried re-installing using "sickbeard custom" and using the file github.com/pymedusa/Medusa.git but I get the error "failed to run the package service"

What should I do ?

**Comment by medariox** [comment]
Start by using the correct package https://github.com/pymedusa/Medusa/wiki/Synology

**Comment by sendas** [comment]
i've tried that. i get the same error....

**Comment by medariox** [comment]
We don't know the error you are getting so we can't help you.

**Comment by sendas** [comment]
when installing sickbeard custom i used the correct package and I get the error: "failed to run the package service"

**Comment by sendas** [comment]
<img width="802" alt="error" src="https://user-images.githubusercontent.com/10220908/105390640-2a5efe00-5c11-11eb-9cfb-d536e8da76cf.png">

**Comment by sendas** [comment]
<img width="636" alt="Captura de ecrã 2021-01-21, às 17 57 45" src="https://user-images.githubusercontent.com/10220908/105391695-4adb8800-5c12-11eb-87a9-ab489ecf93a0.png">

**Comment by medariox** [comment]
Download and install this package: https://github.com/BenjV/SYNO-packages/blob/master/Medusa%201.1%20Python%203%20noarch.spk

**Comment by p0psicles** [comment]
@sendas did you study the wiki instructions? https://github.com/pymedusa/Medusa/wiki/Synology

**Comment by sendas** [comment]
> Download and install this package: https://github.com/BenjV/SYNO-packages/raw/master/Medusa%201.1%20Python%203%20noarch.spk

that solved the problem ! thanks :) but for some reason the last update broke everything...

**Comment by sendas** [comment]
> @sendas did you study the wiki instructions? https://github.com/pymedusa/Medusa/wiki/Synology

Obviously
