### ISSUE TITLE
Root directory not used

### ISSUE THREAD

**Issue by MatthK** [pymedusa/Medusa#9097]
I have moved my library of TV shows to a new drive. I have then updated the General Configuration and deleted the old root directories and added the path to the new location. I defined that as the default.
Yet when Medusa downloads a new episode, it's copying it in the post processing to the old location, creating the directories there again. Also when rescanning a show, it changes all episodes to "Archived".

I have restarted Medusa and the whole server multiple times, but nothing helps. How can I get Medusa to use the new location?

Medusa Info: | Branch: masterCommit: 2b874c2c6a3c33d653eec6e50598a194627a6f76
                        Version: 0.5.4
                        Database: 44.17
Python Version: | 3.6.9 (default, Oct 8 2020, 12:12:24) [GCC 8.4.0]
SSL Version: | OpenSSL 1.1.1 11 Sep 2018
OS: | Linux-4.15.0-130-generic-x86_64-with-Ubuntu-18.04-bionic
Locale: | en_US.UTF-8

**Comment by MatthK** [comment]
I found the setting under Edit of the show. But is that the only way to update +100 shows? All doing it manually?

**Comment by p0psicles** [comment]
You can use manage -> massUpdate
