### ISSUE TITLE
Nippon TV logo displayed as ?

### ISSUE THREAD

**Issue by reconman** [pymedusa/Medusa#9098]
**Describe the bug**
I have already read https://github.com/pymedusa/Medusa/wiki/Network-logos and know that you can submit missing logos for networks.

The thing is, there are already some files for Nippon TV, but stored as "nippon-television.png" instead of "nippon-tv.png". I think that's why Medusa can't find any logo for the Nippon TV shows.

**To Reproduce**
1. Add `Wonder Egg Priority` to your shows
2. Refresh the shows page
3. A ? logo will be shown for the network

**Expected behavior**
The Nippon TV logo should be shown. I think it's fixed if you rename the nippon-television.png files to nippon-tv.png, since TVDB doesn't have any network called `Nippon Television` anymore.

**Medusa (please complete the following information):**
 - OS: Docker container
 - Branch: master
 - Commit: 2b874c2
 - Python version: Unknown
 - Database version: Unknown

**Comment by p0psicles** [comment]
Network could also be used by tvmaze or tmdb

**Comment by medariox** [comment]
Submit a PR with the logo if you want it added.

**Comment by reconman** [comment]
@medariox I told you it's already in there but I don't know if we can just rename it or have to copy it.

**Comment by medariox** [comment]
> Network could also be used by tvmaze or tmdb

It means you need to copy it.
