### ISSUE TITLE
Post-processing setting to "copy" behaves like "move"

### ISSUE THREAD

**Issue by jery19** [pymedusa/Medusa#9099]
Behaviour change since 0.5.3.
Post-processing setting is set to "Copy".

Expected behaviour :  New download is found in the Post-processing dir.  The file is copied and renamed and classified into the Show directory.  The original downloaded copy is kept and continues to be shared by tranmission. It will stay in the Post-processing dir until I manually delete it.  

Recent change in behaviour : New download is found in the Post-processing dir.  The file is moved and renamed and classified into the Show directory.  The original downloaded copy is no longer present in the Post-processing.  Transmission is updated to continue sharing the copy from the Show directory instead.

**To Reproduce**
1. Go to 'Post-processing'
2. Select Processing method 'Copy'
3. See the status of the torrent in Transmission

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Raspbian Buster Linux-5.4.79-v7l+-armv7l-with-debian-10.7
 - Branch: master
 - Commit: 2b874c2c6a3c33d653eec6e50598a194627a6f76
 - Python version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
 - Database version: 44.17

Detailed configuration 
- Transmission daemon 2.94
- Show directory and Post processing directory are located on a NAS, mounted thru the fstab as CIFS

![image](https://user-images.githubusercontent.com/24867713/105599765-9a30ce00-5d62-11eb-8d79-ae3770ecd788.png)

Unexpected behaviour in transmission (path) 
![image](https://user-images.githubusercontent.com/24867713/105600538-d7955b80-5d62-11eb-9901-c83fa5ce77aa.png)

Expected behaviour in transmission (original path)
![image](https://user-images.githubusercontent.com/24867713/105601164-014e8280-5d63-11eb-883e-9248c119feff.png)

**Comment by medariox** [comment]
Check your permissions. If the file can't be copied, it is moved instead.

**Comment by jery19** [comment]
I am not sure I am following you. 
I guess, this is the other way around, when the file can't be moved, it is copied instead.
I don't get how a file can be moved if it does not have the permission to copy.
Also, there were not changes in the permissions of the system before the behaviour change.

**Comment by medariox** [comment]
Remove the Downloaded files location from your client settings.

**Comment by jery19** [comment]
I just found something new.
Discovered the original files are moved to the root of my Show Directory, and also copied to the proper show sub-directory as expected by the rename process.  So I end up with 2 copies as I was expecting, but the original copy should not be moved to the Show directory, it should stay in the Post-processing dir.

**Comment by jery19** [comment]
I removed the setting in my client as discussed.  Lets see next time a show is downloaded if that fixed my issue.

**Comment by jery19** [comment]
This setting seems to be the issue.  Don't know why it changed.
![image](https://user-images.githubusercontent.com/24867713/105607061-c2242f80-5d6a-11eb-9dbe-70f988095b19.png)

**Comment by jery19** [comment]
I will confirm this was the issue as soon as the next download happens.  But it sound you found it.
