### ISSUE TITLE
[ FEATURE ] Media info is not sent to Trakt

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#910]
Branch/Commit: Latest Dev
OS: Ubuntu 14.04
What you did: Enable trakt notifications
What happened: Media info is not sent to trakt, becouse of the implementation is not up to date with the api http://docs.trakt.apiary.io/#reference/sync/add-to-collection
What you expected: Info to be sent to trakt like displayed here http://imgur.com/bm602De (the Ip Man 2 one)

**Comment by labrys** [comment]
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.
