### ISSUE TITLE
UNC path stopped working for post-processing

### ISSUE THREAD

**Issue by steveschow** [pymedusa/Medusa#9102]
I am using a windows machine to run medusa together with sabnzbd.  sabnzbd saves the shows to a different server.  Previously, Medusa was able to specify a UNC path name to that samba share....to do post processing.  For example

`\\webman\raid\extra\video\sabnzbd`

However, after updating Medusa recently, this no longer seems to work.  I can see that this share is mounted in windows, I can specify it in CMD terminal and see dir listing, for example.  I can see it through file explorer also.  And Medusa used to be able to use this path in post processing, but now it complains that dir does not exist.

What may have changed that would prevent medusa from being able to access that network share?  Is there another way to specify a network share that will work with. Medusa?

**Comment by medariox** [comment]
Nothing change to that part of the code. See if this helps: https://github.com/pymedusa/Medusa/wiki/Medusa-Windows-Installer#network-drive-mappings

**Comment by steveschow** [comment]
Yep, that fixed it, since I had to reinstall medusa I lost that aspect...was previously having it run as me.
