### ISSUE TITLE
Missing time zone for network: discovery+

### ISSUE THREAD

**Issue by Theonepudding** [pymedusa/Medusa#9105]
2021-01-24 14:11:53 ERROR    APIv2-Thread_2 :: [2b874c2] Missing time zone for network: discovery+

**Comment by artificial-chaos** [comment]
### INFO
**Python Version**: `3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@2b874c2c6a3c33d653eec6e50598a194627a6f76
**Link to Log**: https://gist.github.com/f8909e084a1609dcbdc9bcda81526083
### ERROR
<pre>
2021-01-24 17:50:36 ERROR    SHOWQUEUE-ADD :: [2b874c2] Missing time zone for network: discovery+
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
