### ISSUE TITLE
[Dev] Shows with 1-2 days away being set to wanted prematurely

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#9115]
**Describe the bug**
I'm not sure when the process runs to check/set airdates
however I have noticed all my upcoming shows that are 1-2 days away get set to wanted
offset for all shows are set to 0

**Screenshots**
![Screen Shot 2021-01-26 at 5 58 42 am](https://user-images.githubusercontent.com/2242880/105752639-a81d6380-5f9b-11eb-8512-951b601c9787.jpg) - all expanded are affected by this 1-2 days away till actual airdate
![Screen Shot 2021-01-26 at 5 58 54 am](https://user-images.githubusercontent.com/2242880/105752661-afdd0800-5f9b-11eb-9eaa-87bbae4a4081.jpg)
![Screen Shot 2021-01-26 at 5 59 03 am](https://user-images.githubusercontent.com/2242880/105752670-b3708f00-5f9b-11eb-8500-dadba1ec60e7.jpg)

**Medusa (please complete the following information):**
 - OS: macOS 11.1
 - Branch: feature/add-fdh (has dev branch merged)
 - Commit: 08be24d4e3ca98a7103311cb2c5eef9f585f2c64
 - Python version: 	3.8.7
 - Database version: 44.18

**Debug logs (at least 50 lines):**
[All Logs.zip](https://github.com/pymedusa/Medusa/files/5869019/All.Logs.zip)
not sure if its in here, as I'm not sure when it set those EP to wanted...

**Additional context**
just use episode status management every now & then & check for wanted..

**Comment by medariox** [comment]
There was a bug in develop that caused this. Just force full update the affected shows and it will be fixed.
