### ISSUE TITLE
Process downloads that are in its download folder..

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#9116]
**Describe the bug**
manually start a download and have when it's finished placed in the Medusa downloads folder

**To Reproduce**
1. Find an episode you need and have your downloader place the finished download in the Medusa folder..
2.  Example 

![image](https://user-images.githubusercontent.com/14140816/105764088-8208ac80-5f24-11eb-83ff-310911c7af54.png)

Season 2 Episode 2 of Batwoman 2019 is needed

![image](https://user-images.githubusercontent.com/14140816/105764446-f4798c80-5f24-11eb-9bff-54405cdbb7be.png)

Has been downloaded to the Medusa folder

`2021-01-25 15:42:52 WARNING  POSTPROCESSOR :: [2b874c2] Problem(s) during processing, failed for the following files/folders: 
2021-01-25 15:42:52 WARNING  POSTPROCESSOR :: [2b874c2] Missed file: O:\utorrent\completedDownload\MU\NCIS.S14E14.Nonstop.1080p.WEB-DL.DD5.1.H264-BTN[rarbg]\NCIS.S14E14.Nonstop.1080p.WEB-DL.DD5.1.H264-BTN.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2021-01-25 15:42:52 WARNING  POSTPROCESSOR :: [2b874c2] Missed file: O:\utorrent\completedDownload\MU\Batwoman.S02E02.1080p.WEB.H264-CAKES[rarbg]\batwoman.s02e02.1080p.web.h264-cakes.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2021-01-25 15:42:52 WARNING  POSTPROCESSOR :: [2b874c2] Missed file: O:\utorrent\completedDownload\MU\American.Gods.S03E03.1080p.WEB.H264-GGEZ[TGx]\american.gods.s03e03.1080p.web.h264-ggez.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2021-01-25 15:42:52 WARNING  POSTPROCESSOR :: [2b874c2] Missed file: O:\utorrent\completedDownload\MU\If.We.Built.It.Today.S02E01.Washington.DC.Reborn.720p.WEBRip.X264-KOMPOST[eztv.re].mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode`

As you can see it failed with 4 different shows, all need those episodes. This was with the normal post processing process.
If I do nothing Medusa will at some point find them and send them to the downloader, process the same files and update the shows. 

Manual
Post-processing results
Processing path: O:\utorrent\completedDownload\MU
Processing folder: O:\utorrent\completedDownload\MU
Post-processing files: ['If.We.Built.It.Today.S02E01.Washington.DC.Reborn.720p.WEBRip.X264-KOMPOST[eztv.re].mkv']
Post-processing video files: ['If.We.Built.It.Today.S02E01.Washington.DC.Reborn.720p.WEBRip.X264-KOMPOST[eztv.re].mkv']
Processing failed for O:\utorrent\completedDownload\MU\If.We.Built.It.Today.S02E01.Washington.DC.Reborn.720p.WEBRip.X264-KOMPOST[eztv.re].mkv: This show isn't in your list, you need to add it before post-processing an episode
Processing folder: O:\utorrent\completedDownload\MU\NCIS.S14E14.Nonstop.1080p.WEB-DL.DD5.1.H264-BTN[rarbg]
Post-processing files: ['NCIS.S14E14.Nonstop.1080p.WEB-DL.DD5.1.H264-BTN.mkv']
Post-processing video files: ['NCIS.S14E14.Nonstop.1080p.WEB-DL.DD5.1.H264-BTN.mkv']
Processing failed for O:\utorrent\completedDownload\MU\NCIS.S14E14.Nonstop.1080p.WEB-DL.DD5.1.H264-BTN[rarbg]\NCIS.S14E14.Nonstop.1080p.WEB-DL.DD5.1.H264-BTN.mkv: This show isn't in your list, you need to add it before post-processing an episode
Processing folder: O:\utorrent\completedDownload\MU\Batwoman.S02E02.1080p.WEB.H264-CAKES[rarbg]
Post-processing files: ['batwoman.s02e02.1080p.web.h264-cakes.mkv']
Post-processing video files: ['batwoman.s02e02.1080p.web.h264-cakes.mkv']
Processing failed for O:\utorrent\completedDownload\MU\Batwoman.S02E02.1080p.WEB.H264-CAKES[rarbg]\batwoman.s02e02.1080p.web.h264-cakes.mkv: This show isn't in your list, you need to add it before post-processing an episode
Processing folder: O:\utorrent\completedDownload\MU\American.Gods.S03E03.1080p.WEB.H264-GGEZ[TGx]
Post-processing files: ['american.gods.s03e03.1080p.web.h264-ggez.mkv']
Post-processing video files: ['american.gods.s03e03.1080p.web.h264-ggez.mkv']
Processing failed for O:\utorrent\completedDownload\MU\American.Gods.S03E03.1080p.WEB.H264-GGEZ[TGx]\american.gods.s03e03.1080p.web.h264-ggez.mkv: This show isn't in your list, you need to add it before post-processing an episode
Problem(s) during processing, failed for the following files/folders:
Missed file: O:\utorrent\completedDownload\MU\If.We.Built.It.Today.S02E01.Washington.DC.Reborn.720p.WEBRip.X264-KOMPOST[eztv.re].mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
Missed file: O:\utorrent\completedDownload\MU\NCIS.S14E14.Nonstop.1080p.WEB-DL.DD5.1.H264-BTN[rarbg]\NCIS.S14E14.Nonstop.1080p.WEB-DL.DD5.1.H264-BTN.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
Missed file: O:\utorrent\completedDownload\MU\Batwoman.S02E02.1080p.WEB.H264-CAKES[rarbg]\batwoman.s02e02.1080p.web.h264-cakes.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
Missed file: O:\utorrent\completedDownload\MU\American.Gods.S03E03.1080p.WEB.H264-GGEZ[TGx]\american.gods.s03e03.1080p.web.h264-ggez.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode

**Expected behavior**
That Medusa would process the needed files and update the show info.

**Medusa (please complete the following information):**

Medusa Info: | Branch: masterCommit: 2b874c2c6a3c33d653eec6e50598a194627a6f76Version: 0.5.4Database: 44.17
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-7-6.1.7601-SP1
Locale: | en_US.cp1252
  |  
  |  
User: | Plex
Program Folder: | C:\Medusa\Medusa
Config File: | C:\Medusa\Data\config.ini
Database File: | C:\Medusa\Data\main.db
Cache Folder: | C:\Medusa\Data\cache
Log Folder: | C:\Medusa\Data\Logs
Arguments: | --nolaunch --datadir=C:\Medusa\Data

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
see above
```
</details>

**Additional context**

**Comment by medariox** [comment]
Using add year without the exception. Add the scene exception (show name without year) or stop using ass year to show title.

**Comment by nydave69** [comment]
What?  don't understand, this has nothing to do with a year....
The exact same show will process correctly if snatch by Medusa...

**Comment by medariox** [comment]
Like I said, the snatch and post-process have no connection whatsoever. So what you are saying is not possible.
