### ISSUE TITLE
Medusa not starting after update on synology

### ISSUE THREAD

**Issue by MikeyMan83** [pymedusa/Medusa#9119]
**Describe the bug**
Medusa service wont start. I've been running it through sickbeard-custom app on synology. 
Running it through package center gives a message: "Could not start package service"
Trying to start trough CLI: 
root@NAS:~# synoservicecfg --hard-start pkgctl-sickbeard-custom
service [pkgctl-sickbeard-custom] start failed, synoerr=[0x0000]

**Medusa (please complete the following information):**
 - OS: DSM 6.2.3-25426 Update 3
 - Branch: master
 - Commit: Latest
 - Python version: 3.8.2-0150
 - Database version: ?

**Debug logs (at least 50 lines):**

[log.txt](https://github.com/pymedusa/Medusa/files/5873312/log.txt)

**Comment by medariox** [comment]
sickbeard-custom is not supported. Use the supported package: https://github.com/pymedusa/Medusa/wiki/Synology

**Comment by MikeyMan83** [comment]
Not supported? It's been running for years now?

**Comment by medariox** [comment]
The supported package is the one listed in the Wiki.

**Comment by MikeyMan83** [comment]
Very strange to be confronted with such a change in behvior...

**Comment by medariox** [comment]
What do you mean? You just need to install a different package.

**Comment by MikeyMan83** [comment]
Well, like i said; it has been running literally for years in this setup... After an update it stops working. Not the best way to go about it. I'll try the other package, but cannot access frontend now to make a backup of the database.

**Comment by MikeyMan83** [comment]
Trying to install the package mentioned, but i get an error that i need pyton 3 3.7 or higher. While i have 3.8.

**Comment by MikeyMan83** [comment]
Could very well be... 
And no i don't usually even use the frontend. 

Should be possible to block an upgrade if the dependencies are not met?

Tried installing python3 package; which is running:
root@NAS:/volume1/@appstore/sickbeard-custom/var/Logs# python3
Python 3.8.2 (tags/Contacts-1.0.0-0232-200617:57e5f51, Jun 29 2020, 09:36:37)
[GCC 4.9.3 20150311 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.


Medusa package install is not having it.

**Comment by medariox** [comment]
You need to remove whatever Python3 package you have installed and use the official one from the Syno repo.

**Comment by MikeyMan83** [comment]
I have. There is only 1 python3 package, and that's the syno one; at 3.8.2.

**Comment by medariox** [comment]
The latest Syno Python3 package is Version 3.7.7-15: https://synocommunity.com/package/python3
