### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Arte 

### ISSUE THREAD

**Issue by Merrick28** [pymedusa/Medusa#9129]
### INFO
**Python Version**: `3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]`
**Operating System**: `Linux-4.19.0-12-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/d376d14416207bfa1e946180ebd694a3
### ERROR
<pre>
2021-01-27 15:00:17 ERROR    SHOWQUEUE-ADD :: [] Missing time zone for network: Arte 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
Already present in the list  
https://github.com/pymedusa/medusa.github.io/blob/master/sb_network_timezones/network_timezones.txt#L222
