### ISSUE TITLE
Cached Results Store Old API Keys

### ISSUE THREAD

**Issue by LeeThompson** [pymedusa/Medusa#9132]
When Medusa caches search results, it stores them with the (at the time) API keys for the providers.
The problem is if the provider's API key is changed and the cache is used for a snatch, it fails because it's using an outdated and invalid key.

**To Reproduce**
1. Cache some search results
2. Change the API key on the search provider
3. Change the API key for that provider in medusa
4. Attempt snatch from the previously cached search results, it will fail

**Expected behavior**
The cache shouldn't include credentials, it should apply credentials when the snatch is sent to the download provider.

**Medusa (please complete the following information):**
Medusa Info: Branch: master
Commit: e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Version: Unknown
Database: 44.17
Python Version:| 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
SSL Version:  OpenSSL 1.1.1i 8 Dec 2020
OS:  Linux-3.10.105-x86_64-with (Docker)
Locale: en_US.UTF-8

**Debug logs (at least 50 lines):**
Not applicable since api keys are hidden.

**Possible Workaround:**
Stop Medusa, delete cache.db, Re-start Medusa

**Comment by LeeThompson** [comment]
NOTE: If you use "Refresh Results" any *new* results will work (since it will use the updated key) unfortunately prior results will still fail.

**Comment by p0psicles** [comment]
There is also the option of cache pruning. It will clean out cache results older then x days

**Comment by medariox** [comment]
Yep, just use auto prune after X days or manually delete `cache.db`.

**Comment by LeeThompson** [comment]
@medariox The better solution is not to store provider credentials in the cache at all.

**Comment by medariox** [comment]
Great idea! Waiting for your PR!

**Comment by LeeThompson** [comment]
> Great idea! Waiting for your PR!

Don't hold your breath, I need to learn Python3 first.

**Comment by p0psicles** [comment]
It's not that easy. The URL's your talking about have a token, userid or password included in them. We would need to recreate the URL per provider. Meaning that we only save bare minimum. And recreate the URL when needed.

**Comment by LeeThompson** [comment]
Obviously I can't speak specifically for Python3 (I keep meaning to learn and get into it, honest!) but the way I'd approach it would be to store the URL with a substitution token after the API key (i.e apikey={APIKEY}) which would be filled in if the cached URL was requested to be sent to the downloading service.

(NOTE: Actual API keys have been obfuscated for this example for obvious reasons)

For example: 

The cache "fetch" column would be stored in cache.db as
https://dognzb.cr/fetch/9b161db4e564df093b017c2fb2ba4d14/*APIKEY*

When medusa sends that catched fetch to the downloader it would, at that time, replace "*APIKEY* with the API key stored in the search provider profile for dognzb (in this case the fictional API key: '14496ab6b$70b3f12a245b139f4cf508').

Anyway that's my 2c on it.
