### ISSUE TITLE
Update cache.db after Search Provider gets updated

### ISSUE THREAD

**Issue by skalvaro** [pymedusa/Medusa#9135]
After updating a search provider api key Medusa is still grabbing releases using the old key, it seems to me these 'grabs' are taken from cache.db. The search provider in this case is nzbgeek but I guess that this would be true for all providers where the api key, or any other provider information, is stored in the cache results.

For new searches where the results are not in the cache the new key is used but if Medusa already had results in the cache it will use these with the old key.

Is there an easy way to update the information in the cache for that provider?
Shouldn't the cache be updated with the new provider information upon updating said provider?

I would rather not remove the complete cache because of this, I know it will work but it seems a bit overkill to me. Currently I'm using manual search for episodes that have this issue and making sure that I pick a result that is added after I updated the provider settings.

Medusa Info: 
Branch: master
Commit: 2ab9d450d31f554cd77a5477d69f5555cbec6156
Version: 0.5.6
Database: 44.17
Python Version: 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
SSL Version: OpenSSL 1.0.2k-fips 26 Jan 2017
OS: Linux-3.10.0-1160.11.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Locale: en_US.UTF-8

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/9132#issuecomment-768534248

**Comment by medariox** [comment]
Feature requests belong in Discussions as clearly stated in the template.
