### ISSUE TITLE
Episode quality not picked up correctly after re-import and changing indexers

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#9140]
**Describe the bug**
I recently deleted all my shows and left the files, after that I added existing shows and switched to TMDB.
Nothing else in my setup has changed, now when I go to `Preview Rename` it strips out a part of the file quality that I have setup in the rename options.

My naming scheme is like this:
`Season %0S/%SN - S%0SE%0E - [%SQN][%RG]`

When initiating `Preview Rename` this is the result.

Episode | Old Location | New Location
 -- | -- | --
7 | Season 03\A Series of Unfortunate Events - S03E07 - [1080p WEB-DL h264][MZABI].mkv | Season 03\A Series of Unfortunate Events - S03E07 - [1080p WEB][MZABI].mkv
6 | Season 03\A Series of Unfortunate Events - S03E06 - [1080p WEB-DL h264][MZABI].mkv | Season 03\A Series of Unfortunate Events - S03E06 - [1080p WEB][MZABI].mkv
5 | Season 03\A Series of Unfortunate Events - S03E05 - [1080p WEB-DL h264][MZABI].mkv | Season 03\A Series of Unfortunate Events - S03E05 - [1080p WEB][MZABI].mkv
4 | Season 03\A Series of Unfortunate Events - S03E04 - [1080p WEB-DL h264][MZABI].mkv | Season 03\A Series of Unfortunate Events - S03E04 - [1080p WEB][MZABI].mkv
3 | Season 03\A Series of Unfortunate Events - S03E03 - [1080p WEB-DL h264][MZABI].mkv | Season 03\A Series of Unfortunate Events - S03E03 - [1080p WEB][MZABI].mkv
2 | Season 03\A Series of Unfortunate Events - S03E02 - [1080p WEB-DL h264][MZABI].mkv | Season 03\A Series of Unfortunate Events - S03E02 - [1080p WEB][MZABI].mkv
1 | Season 03\A Series of Unfortunate Events - S03E01 - [1080p WEB-DL h264][MZABI].mkv | Season 03\A Series of Unfortunate Events - S03E01 - [1080p WEB][MZABI].mkv

As you can see it strips out the `h264` and it changes `WEB-DL` to `WEB`

Medusa Info: | Branch:                 master                  Commit:                 2ab9d450d31f554cd77a5477d69f5555cbec6156                  Version:                 0.5.6                  Database:                 44.17
-- | --
Python Version: | 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.1g  21 Apr 2020
OS: | Windows-10-10.0.17763-SP0
Locale: | nl_NL.cp1252

**Comment by medariox** [comment]
Works fine here. Is this only happening with TMDB? Any way to reproduce it?

**Comment by Rouzax** [comment]
Just to clarify, it is not happening on new snatches that come in and are processed.
Those are still named correct. This one was picked up today
![image](https://user-images.githubusercontent.com/4103090/106262706-b1b8fc80-6223-11eb-9be9-c0a7995bb8bf.png)

However when I go to the show page and hit the ![image](https://user-images.githubusercontent.com/4103090/106262802-cd240780-6223-11eb-825b-677dd4189cab.png)

Old episodes (from before the delete and re adding) will lose the info and the new one still retains it


Episode | Old Location | New Location
-- | -- | --
7 | Season 06\Superstore - S06E07 - [1080p WEB h264][STRONTiUM].mkv | Season 06\Superstore - S06E07 - [1080p WEB h264][STRONTiUM].mkv
6 | Season 06\Superstore - S06E06 - [1080p WEB-DL h264][NTb].mkv | Season 06\Superstore - S06E06 - [1080p WEB][NTb].mkv
5 | Season 06\Superstore - S06E05 - [1080p WEB h264][STRONTiUM].mkv | Season 06\Superstore - S06E05 - [1080p WEB][STRONTiUM].mkv

**Comment by medariox** [comment]
Okay, so it only happens for imported shows.

**Comment by Rouzax** [comment]
Depends on what you mean with imported.
Steps I did:
- Deleted all shows
- Left all physical files
- Imported all shows by doing `Add Existing Shows`
- Chose TMDB as default instead of TVDB
- All these episodes lose the quality information when doing a ![image](https://user-images.githubusercontent.com/4103090/106268883-01032b00-622c-11eb-8be0-6e9c93b34837.png)

All newly snatched shows will retain the info when doing a ![image](https://user-images.githubusercontent.com/4103090/106268883-01032b00-622c-11eb-8be0-6e9c93b34837.png)

This is why Superstore Episode 5 and 6 loose the info and Episode 7 does keep it, 7 was newly snatched after the switch to TMDB
Does that make sense?

I think it is because when I deleted the shows I also deleted all snatch information for them.

**Comment by medariox** [comment]
By imported I mean when using Add Existing Shows. I doubt anything else is of influence.

**Comment by p0psicles** [comment]
So you basically ran the rename twice? Renamed from original release to your template. Then renamed again from template to template? 

Also why would you want to do that?

**Comment by Rouzax** [comment]
Haven't run anything, just wanted to see.
Was just checking to see if there would be changes after going from TVDB to TMDB.

**Comment by p0psicles** [comment]
I isn't think the indexer has anything to do with it. I think you hit on a potential bug of re-renaming files.

**Comment by Rouzax** [comment]
That is my thinking as well, but wanted to make sure all info and history was there 😄 
It looks like it removes the codec info when you delete a show so when add them again it doesn't know when you hit rename and as a result will remove it.
Doesn't explain why it will retain the release group

**Comment by Rouzax** [comment]
It looks like the History is also deleted when deleting shows. 
The History page does not go any further then when I deleted my shows
![image](https://user-images.githubusercontent.com/4103090/106380188-d42c5080-63b0-11eb-8cfe-dc654e20dd9e.png)

**Comment by p0psicles** [comment]
Yeah, history is part of the relational db. So when deleting a show, we can't leave history rows, that don't relate anymore to a show

**Comment by Rouzax** [comment]
Make sense.

**Comment by medariox** [comment]
When you import shows you don't have the "original release name" from the downloads. That's why the preview couldn't determine the correct name. It will now use the file name as a fallback, this should fix the issue. See https://github.com/pymedusa/Medusa/pull/9147

**Comment by Rouzax** [comment]
Thanks, will give it a try when it is merged
