### ISSUE TITLE
Detection of Release Group is not reliable

### ISSUE THREAD

**Issue by lcdt22890158** [pymedusa/Medusa#9155]
**Describe the bug**
The functionality to determine the Group based on the Release Name doesn't reflect the conventions of the current anime RG scene.

![Screenshot](https://user-images.githubusercontent.com/43034492/106582834-88d49680-6598-11eb-8bd2-ff9022d7bcf8.png)

**Actual vs expected behaviour**

`[EMBER].Dr..Stone.S02E03.[1080p].[HEVC.WEBRip].(Dr..Stone:.Stone.Wars)` has its group detected as `Dr. Stone: Stone Wars `, expected result is `EMBER`.

`[Judas].Dr.Stone.-.S02E03.[1080p][HEVC.x265.10bit][Multi-Subs].(Weekly)` has its group detected as `Weekly`, expected result is `Judas`.

`[SSA].Dr..Stone.S2.-.03.[720p].mkv` and `[Naruto-Kun.Hu].Dr..Stone.S2.-.03.[1080p].mp4` both have no group detected. Expected results are `SSA` and `Naruto-Kun.Hu` respectively.

Similar results are seen for every other show I checked.

**To Reproduce**
1. Add an anime
2. Do a manual search on one of the episodes
3. Observe that many releases have incorrect or missing groups.

**Suggestion**
The majority of release groups at the moment put the group name in square brackets at the beginning of the release name. I believe that if something is within square brackets at the start of the release name, this should be used as the group name.

I've looked at a few currently airing shows, and I believe that this new rule will work in the vast majority of cases. Here are some extra cases worth considering:

`Tatoeba.Last.Dungeon.Mae.no.Mura.no.Shounen.ga.Joban.no.Machi.de.Kurasu.Youna.Monogatari..04.(1080p).[AF1FB9C1]` - New rule doesn't pick this up, but current rule doesn't either. So not a regression.

`DanMachi.S3.-.12.(AbemaTV.1080p).mkv` - New rule doesn't pick this up, but neither rule doesn't either. Would be fairly easy to handle this though, if there are no square brackets at the start of the release name we can fall back to looking for parens at the end of the release name.

`[豌豆字幕组&LoliHouse].进击的巨人./.Shingeki.no.Kyojin.-.67.[WebRip.1080p.HEVC-10bit.AAC][简繁内封字幕]` - Currently incorrectly detected as `豌豆字幕组`, should be `豌豆字幕组&LoliHouse`. I think we should try to include everything until we hit a matching closing bracket.

`[Sick-Fansubs].Shingeki.no.Kyojin.67.[720p][B1C62720].mp4` - Currently incorrectly detected as `Sick`, should be `Sick-Fansubs`. Probably the same issue as previous.

`[Sick.Fansubs].Shingeki.no.Kyojin.67.[720p][B1C62720] ` - Currently detected as `Sick`, should be `Sick Fansubs`. Not sure why this doesn't work, as `[Erai.raws]` does get correctly detected as `Erai raws`. Is it because Medusa already knows "Sick" as an RG?

I looked at a few older shows as well, but the Manual Search function isn't very useful there because most releases are batches, not single episode releases. It's possible that some older shows may be adversely affected by this change, but in my experience even for older shows the RG is usually at the start.

**Medusa (please complete the following information):**
 - OS: linuxserver.io Docker image - v0.5.6
 - Branch: master
 - Commit: Not sure
 - Python version: Not sure
 - Database version: Not sure

**Comment by medariox** [comment]
Same as https://github.com/pymedusa/Medusa/issues/9151#issuecomment-771159800
We can't keep up with made up rules that are changed every X months.
