### ISSUE TITLE
Change Episode Status in /manage fails 

### ISSUE THREAD

**Issue by jeffski10** [pymedusa/Medusa#9213]
Display snatched episodes (/manage/episodeStatuses?whichStatus=2) and try to change the status back to wanted/failed.   Submit and white screen.    Error in the log:

2021-02-12 16:28:50 ERROR    Thread_3 :: [b21beeb] Exception generated: 'Manage' object has no attribute 'setStatus'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/manage/handler.py", line 175, in changeEpisodeStatuses
    self.setStatus(
AttributeError: 'Manage' object has no attribute 'setStatus'

Status change works on the individual show pages. 

Medusa Info: | Branch: master
Commit: b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9

**Comment by LeeThompson** [comment]
Seeing this too.

**Comment by siconic** [comment]
I am experiencing this as well, tried to submit, but for some reason cannot.

**Comment by flick1999** [comment]
Seeing this as well. Also tried to submit.

**Comment by p0psicles** [comment]
Fixed with next release

**Comment by LeeThompson** [comment]
Just FYI seeing this in e094759640ca61c5c033bf1ff9d33bc7fc1ba857 (not sure if the fix for this has been released yet)

**Comment by p0psicles** [comment]
If that's on the master branch, no hasn't been released yet

**Comment by nydave69** [comment]
Why is this closed if it hasn't been solved for the users...

**Comment by p0psicles** [comment]
It has been solved in develop branch. 
That's how we work. We fix and merge to develop and close related issue. In the issue we link to the pr.

Saves me time as I don't have to go back to all the issues after I've release develop to master.
