### ISSUE TITLE
Post process via Terminal/API not recognising path

### ISSUE THREAD

**Issue by cinaedksm** [pymedusa/Medusa#9221]
I have been using a terminal command for manual post processing (remote via SSH) when necessary, and it's been working fine up until recently where it's giving me an error. 

Here's the command (API key and User substituted):

curl -s http://localhost:8081/api/v1/API-KEY/?cmd=postprocess&path=/home/USER/Downloads/tv_complete 

Which returns:

{"data": {}, "message": "You need to provide a path or set TV Download Dir", "result": "failure"}

Has there been a change to the API that I need to adapt to, or am I doing something wrong?

 - OS: Ubuntu 18.04 (Lubuntu)
 - Branch: master
 - Commit: b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
 - Python version: 3.6.7
 - Database version: 44.17

**Comment by p0psicles** [comment]
Not that I know of in the master branch. But in develop we've made changes that can impact you

**Comment by cinaedksm** [comment]
If you have the correct syntax for dev I can give that a try and see if it works?

**Comment by p0psicles** [comment]
You could use the UI. Config - general - advanced
Maybe have to fill in your git credentials

Or use git cli

git fetch origin
git checkout -t origin/develop

**Comment by reconman** [comment]
I use this:
`curl -X POST -d "proc_dir=/Data/Downloads/Torrents/Completed&process_method=hardlink&delete_on=on" http://192.168.0.2:8081/home/postprocess/processEpisode`

I used the format sent by the manual post-processing page, which I analyzed by using Chrome's developer console. (network tab)

**Comment by reconman** [comment]
For the code in the develop branch, I know have to use this:

`curl -X POST -d "proc_dir=/Data/Downloads/Torrents/Completed" -d "process_method=hardlink" -d "delete_on=false" -d "force=false" -d "is_priority=false" -d "failed=false" -d "proc_type=manual" -d "ignore_subs=false" -d "run_sync=true" http://192.168.0.2:8081/home/postprocess/processEpisode`

**Comment by cinaedksm** [comment]
Taken me ages to get around to trying it, but that worked perfectly. Thank you!
