### ISSUE TITLE
NZBGeek - Incorrect API key submitted for snatching

### ISSUE THREAD

**Issue by cinaedksm** [pymedusa/Medusa#9222]
Medusa is sending the wrong API key when fetching from NZBGeek. 
Searching works just fine, but fetching to SABnzbd returns Empty NZB. See attached screenshot, bottom is a manual fetch (I had problems with the API key that they resolved for me), top is the fetch from Medusa. As you can see the keys are wildly different. 

    OS: Ubuntu 18.04 (Lubuntu)
    Branch: master
    Commit: b21beeb
    Python version: 3.6.7
    Database version: 44.17

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/79052107/107883162-2eff9500-6ee5-11eb-8094-436560096e6a.png">

**Comment by p0psicles** [comment]
Prune your cache.
There is an option for that. In config - general
Or you delete your cache.db and restart

**Comment by cinaedksm** [comment]
That sorted it, thank you. Easy peasy!
