### ISSUE TITLE
Can't change scene #

### ISSUE THREAD

**Issue by bluelavalamp** [pymedusa/Medusa#9234]
I have a show where I need to modify the scene # on the show page.  When I change it the number always changes back to the original #,  So for example the number is 20x5 and I need to change to 22x5.  I can delete the 0 and change to 2 so its 22x5 , but after only a second or two it just changes back to 20x5.

Medusa Info: | Branch: masterCommit: b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9Version: 0.5.8Database: 44.17
-- | --
Python Version: | 3.9.1 (default, Jan 20 2021, 22:58:54) [GCC 10.2.0]
SSL Version: | OpenSSL 1.1.1i 8 Dec 2020
OS: | Linux-5.1.4-x86_64-Intel-R-_Core-TM-_i5-9600K_CPU_@_3.70GHz-with-glibc2.32
Locale: | en_US.UTF-8

**Comment by p0psicles** [comment]
It's not an anime show? 
Scene enabled? 
It has absolute numbering?

**Comment by bluelavalamp** [comment]
Not anime
Scene numbering is enabled
It has an absolute number but it's wrong too.  It's set to 3 and should be 66.  When I set to 66 the same thing happens.  After a couple seconds it changes back to 3

**Comment by bluelavalamp** [comment]
Just realized it's throwing an error when I try to change the number:

2021-02-16 18:23:19 ERROR    Thread_0 :: [b21beeb] Exception generated: setSceneNumbering() got an unexpected keyword argument 'indexername'
Traceback (most recent call last):
  File "/opt/Medusa-master/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
TypeError: setSceneNumbering() got an unexpected keyword argument 'indexername'

**Comment by bluelavalamp** [comment]
Should I use the Submit Error button?
Thanks

**Comment by p0psicles** [comment]
I'll fix it. No need

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/9356
