### ISSUE TITLE
 Cannot add new shows in Add Show tab (solution)

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/Medusa#9243]
So couldn't add any shows.  I tried the solution that @PrzemekSkw used in the now closed issue "Cannot add new shows in Add Show tab #9189" and it worked.

I tried to force a branch checkout to dev - just got a spinner.  (We can't switch branches from /config/general/, right?)  Restarted Medusa (had already tried that several times before trying to force dev branch) and am now able add shows again.  I suppose the issue is closed?

By the way, when the Add Show failed, there was no corresponding log entry.

**Comment by p0psicles** [comment]
You where probably on an old version. But good it's resolved for you
