### ISSUE TITLE
unable to add subsplease rss provider

### ISSUE THREAD

**Issue by ngamber** [pymedusa/Medusa#9250]
version: 0.5.8
to reproduce: 
add new custom torrent provider, use one of the subs please urls (https://subsplease.org/rss/?t&r=1080)
UI error appears: "Error when trying to load RSS: a bytes-like object is required, not 'Response'"
Nothing logged in medusa logs even with debug logs enabled.

**Comment by medariox** [comment]
Working fine here. Closing this issue as any info that could help identifying the issue is missing (not just debug logs).
