### ISSUE TITLE
Release group (fansub) is not correctly detected for some anime releases

### ISSUE THREAD

**Issue by roobre** [pymedusa/Medusa#9251]
**Describe the bug**

Some releases (specially anime) include spurious keywords in brackets in the name, e.g.:
`[Erai-raws].Hataraku.Saibou!!.-.04.[1080p][Multiple.Subtitle].mkv`

Here, despite the release group being `Erai-raws`, medusa will think it is `Multiple.Subtitle`:
![DeepinScreenshot_select-area_20210221142040](https://user-images.githubusercontent.com/969721/108626460-98852380-7450-11eb-839f-472a895fc6a4.png)

**To Reproduce**
1. Manually search for a show with releases from `Erai-Raws` (e.g. `tvdb346931`)
2. Observe the output of medusa (as in the screenshot above) 

**Expected behavior**
Medusa should pick the correct release group. In cases where it is ambiguous, perhaps all candidates should be matched against whitelist/blacklist.

**Medusa (please complete the following information):**

```

Medusa Info:
Branch:                 master
Commit:                 Unknown
Version:                 0.5.8
Database:                 44.17
Python Version:  3.8.5 (default, Jul 20 2020, 23:11:29)  [GCC 9.3.0]
SSL Version: OpenSSL 1.1.1i  8 Dec 2020
OS:  Linux-5.4.85-1-lts-x86_64-with
Locale:  en_US.UTF-8
```

**Comment by medariox** [comment]
Please report to guessit: https://github.com/guessit-io/guessit
