### ISSUE TITLE
Add Recommended Shows failing - Trakt and IMDB

### ISSUE THREAD

**Issue by Avian-Flew** [pymedusa/Medusa#9258]
**Describe the bug:**
When navigating to "Add Recommended Shows" function, upon selecting Trakt or IMDB am presented with an error - different for each provider. Anime option seems to be working.
Error: Trakt - "Fetching of Recommender Data failed. Exception: Forbidden - invalid API key or unapproved app"
Error - IMDB - "Fetching of Recommender Data failed. Exception: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte"
Changing List Option or Sort Options has no effect.
Trakt error shows in Log, IMDB error does not.

**To Reproduce:**
1. Go to "Add Recommended Shows"
2. Click on "Add from Trakt Lists" or "Add from IMDB's Popular Shows"
3. See error

**Expected behavior:**
Navigation to either should refresh the stored list(s) and present them in a list/graphical table for selection.

**Medusa:**
Branch: master
Commit: b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
Version: 0.5.8
Database: 44.17
Python Version: 3.9.0 (default, Dec 02 2020, 16:57:56) [GCC 8.4.0]
SSL Version: OpenSSL 1.1.1h 22 Sep 2020
OS: Linux-4.1.13-x86_64-with-glibc2.27
Locale: Unknown.Unknown
 	 
**Debug logs:**
2021-02-23 07:16:35 ERROR	Thread :: [b21beeb] Could not connect to Trakt service: Forbidden - invalid API key or unapproved app
Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/medusa/show/recommendations/trakt.py", line 113, in fetch_popular_shows
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/ext/trakt/core.py", line 548, in inner
    json_data = self._handle_request('get', url)
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/ext/trakt/core.py", line 525, in _handle_request
    raise self.error_map[response.status_code]()
trakt.errors.ForbiddenException: Forbidden - invalid API key or unapproved app

**Additional context:**
May be connected to Traktchecker not finding watchlist entries #9182 - similar error detail received.

**Comment by p0psicles** [comment]
For trakt, you need to authenticate in config - notifications. 
for the IMDb issue. Stop medusa
In cache folder. Delete all dbm files. 
Start
