### ISSUE TITLE
Unable to add new shows

### ISSUE THREAD

**Issue by Aethrios** [pymedusa/Medusa#9277]
No updates available, no permissions have changed on the dataset recently. Tried to add a couple news shows, they both throw the same error. Folders created, but adding them as "preexisting" shows fails too.

Running on freebsd in an iocage jail.

> 2021-02-27 18:53:58 ERROR	SHOWQUEUE-ADD :: [b21beeb] Error trying to configure show: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> Traceback (most recent call last):
>   File "/usr/local/medusa/medusa/queues/show_queue.py", line 414, in run
>     series.configure(self)
>   File "/usr/local/medusa/medusa/tv/series.py", line 1768, in configure
>     self.whitelist = options['whitelist']
>   File "/usr/local/medusa/medusa/tv/base.py", line 63, in __setattr__
>     super(TV, self).__setattr__(key, value)
>   File "/usr/local/medusa/medusa/tv/series.py", line 763, in whitelist
>     self.release_groups.set_white_keywords(short_group_names(group_names))
>   File "/usr/local/medusa/medusa/helpers/anidb.py", line 106, in short_group_names
>     short_group_list += get_short_group_name(group_name) or [group_name]
>   File "</usr/local/medusa/ext/decorator.py:decorator-gen-15>", line 2, in get_short_group_name
>   File "/usr/local/medusa/ext/dogpile/cache/region.py", line 1578, in get_or_create_for_user_func
>     key, user_func, timeout, should_cache_fn, (arg, kw)
>   File "/usr/local/medusa/ext/dogpile/cache/region.py", line 1047, in get_or_create
>     async_creator,
>   File "/usr/local/medusa/ext/dogpile/lock.py", line 185, in __enter__
>     return self._enter()
>   File "/usr/local/medusa/ext/dogpile/lock.py", line 87, in _enter
>     value = value_fn()
>   File "/usr/local/medusa/ext/dogpile/cache/region.py", line 977, in get_value
>     value = self._get_from_backend(key)
>   File "/usr/local/medusa/ext/dogpile/cache/region.py", line 1265, in _get_from_backend
>     self.backend.get_serialized(key)
>   File "/usr/local/medusa/ext/dogpile/cache/region.py", line 1221, in _parse_serialized_from_backend
>     metadata = json.loads(bytes_metadata)
>   File "/usr/local/lib/python3.7/json/__init__.py", line 343, in loads
>     s = s.decode(detect_encoding(s), 'surrogatepass')
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/9070#issuecomment-764062860
