### ISSUE TITLE
Trakt Most Anticipated Shows

### ISSUE THREAD

**Issue by ledderi** [pymedusa/Medusa#9307]
**Describe the bug**
Fetching of Recommender Data failed. Exception:

Forbidden - invalid API key or unapproved app
![Screenshot 2021-03-06 091009](https://user-images.githubusercontent.com/3157227/110198521-d3795500-7e5b-11eb-8fb9-9ce056af0a35.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Windows-10-10.0.19041-SP0
 - Branch: master
 - Commit:  55cecb9e821fb15f20efe75b0f59d13e896e1d87
 - Python version: 3.7.3
 - Database version: Database: 44.18

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Authenticate trakt in config - notifications

**Comment by ledderi** [comment]
sorry, but i don't understand what is config - notification

**Comment by medariox** [comment]
Gear ![gear](https://snapr.pw/i/86449dfc2d.png) > Notifications > Social > Trakt

**Comment by ledderi** [comment]
thanks, that helped.
