### ISSUE TITLE
Trakt Most Anticipated Shows

### ISSUE THREAD

**Issue by ledderi** [pymedusa/Medusa#9310]
**Describe the bug**
Fetching of Recommender Data failed. Exception:

'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**To Reproduce**

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64]
 - Branch: [e.g. master, develop]
 - Commit: [e.g. c65ca2]
 - Python version: [e.g. 3.6.8]
 - Database version: [e.g. 44.12]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**
![Screenshot 2021-03-06 155632](https://user-images.githubusercontent.com/3157227/110209354-c462c900-7e94-11eb-8767-90a631370fc5.png)

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/9094#issuecomment-766845722
