### ISSUE TITLE
Nebulance - Cached results for manual search get duplicated

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#9329]
**Describe the bug**
As described in #8787 
Provider Nebulance duplicates cache results.
![image](https://user-images.githubusercontent.com/4103090/110449268-53085d80-80c2-11eb-9345-5589220a2e42.png)

If you need access to the Provider reach out to me in DM on Discord.
I can also provide the cache.db if needed.

PS: Should rarbg already be deduplicated?
![image](https://user-images.githubusercontent.com/4103090/110449560-9793f900-80c2-11eb-980f-cfd0b0a12252.png)

**Comment by medariox** [comment]
Rarbg is fixed. You need to delete your old cache.

**Comment by p0psicles** [comment]
If there are other private providers I need to change. I'll only need an example of the download URL. You can  change any sensitive information in it.
