### ISSUE TITLE
Sending old apikey to nzbget

### ISSUE THREAD

**Issue by bitchkat** [pymedusa/Medusa#9334]
I changed my apikey for my custom newznab provider.  Medusa was searching perfectly.  However, when sending the nzb to nzbget, the url it sent still had the old api key. 

I had to open cache.db via sqlite3 and found the nzb_su (my custom provider is nzb.su) table.  Sure enough, the old key was in the url column.   I stopped medusa, cleared out this table, and restarted medusa.  I did a fresh search and manually snatched one of the episodes that was previously failing in nzbget.

Sure enough, it downloaded correctly this time.  I seems like an automatic cache clear should occur if we modify the custom newznab provider configuration.

**Comment by p0psicles** [comment]
This wil be improved for newznab providers in next version
