### ISSUE TITLE
Medusa service wont start after update

### ISSUE THREAD

**Issue by is33** [pymedusa/Medusa#9364]
**Describe the bug**
Medusa will not start after update. Appears to be a syntax error from .rebulk import

**To Reproduce**
sudo service start medusa 
Error

**Expected behavior**
Medusa web service starts

**Screenshots**
![image](https://user-images.githubusercontent.com/1373128/111719615-9be2b380-8832-11eb-8426-12777437f1f2.png)

**Medusa (please complete the following information):**
 - OS: 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

 - Branch: Master
 - Commit: Unsure
 - Python version: both 2.7.17 and 3.6.9
 - Database version: unknown, can provide zip file backup

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>
Cannot provide, app wont start
</details>

**Additional context**

**Comment by medariox** [comment]
It means you are trying to start with Python 2.7. use Python 3.6 and it will work.
