### ISSUE TITLE
ASync Post-Processing File Rename Incorrect on Single Season shows

### ISSUE THREAD

**Issue by trumblejoe** [pymedusa/Medusa#9370]
I upgraded the quality of Band of Brothers using the new Download Handler async postprocessor and it is renaming my files Band of Brothers - S2001E01 -.mkv

Nothing useful in the debug logs, the file names of episodes are.. 
Band.Of.Brothers.E03.2001.1080p.BluRay.DD5.1.x264.mkv

On the Display Show page it is recreating the Season listing as a new season as it processes episodes using the name Season 2001. The Season 1 listing (the old files) is still there, if that information is helpful.

Config - Post-Processing Naming Scheme
Season %0S/%SN - S%0SE%0E - %EN
Single-EP Sample:Season 02/Show Name - S02E03 - Ep Name.ext
Multi-EP sample:Season 02/Show Name - S02E03E04E05 - Ep Name.ext

Medusa Info: | Branch: masterCommit: UnknownVersion: 0.5.10Database: 44.18
-- | --
Python Version: | 3.8.5 (default, Feb 19 2021, 09:27:16) [GCC 9.3.0]
SSL Version: | OpenSSL 1.1.1j 16 Feb 2021
OS: | Linux-4.19.0-0.bpo.9-amd64-x86_64-with
Locale: | en_US.UTF-8

I am almost certain that immediate action I need to take is to rename the pre-post-process file to Band.Of.Brothers.2001.S01E03.1080p.BluRay.DD5.1.x264.mkv
However, I would still want to submit this as a bug to be on the safe side, because I don't believe the year date of the show should be being classified as the season number, especially with a single season tv show.

**Comment by p0psicles** [comment]
You should submit the issue at guessit repo. As that's what we use for release parsing.

**Comment by medariox** [comment]
Please report to guessit https://github.com/guessit-io/guessit/issues
