### ISSUE TITLE
Incorrect time in Schedule

### ISSUE THREAD

**Issue by ziogref** [pymedusa/Medusa#9388]
When Looking at the Schedule tab all the shows have the incorrect time. 

When looking in the Shows tab the show times are all correct.

The time and date and correct at the bottom of the page.

Time is set to "Local" and I live in UTC+11

Example
Station 19 in the shows tab says will be airing at Friday, 02/04/2021 11:00am (DD/MM/YYYY)

In the Schedule tab its says Friday 02/04/2021 12:00am (Midnight) 11 hours time difference. 

It appears to be using UTC+0 instead of UTC+11 even though the time is correct at the bottom of the page.

Server is Ubuntu Server 20.10

Clients accessing are Windows 10 laptop and Android phone. All set to the same time zone (UTC+11)

I have updated and rebooted the server
Running version 0.5.10 on the master branch.
I have run a mass update on the shows.
When looking at the show directly times are correct, issue is only in the schedule view.

I have cleared the cache on clients.

**Comment by reconman** [comment]
I used the version from `develop` for testing another bugfix and the timezone issue seems to be fixed there.

I'm living in CEST, so UTC+02:00 and the values are the same.

Can you test with the develop version?

**Comment by p0psicles** [comment]
Nothing changed to the code related to time zones in develop. I am working on the schedule page in PR #9403 though. So user might want to check out that branch, when it's ready for review

**Comment by p0psicles** [comment]
The branch is for 99÷ usable. Any testing and feedback on it would be very helpfull

**Comment by Tailslide** [comment]
Also having this issue.. wondering if it might be related to setting up a new docker image and restoring a config backup before setting the timezone. Sometimes I see ‘invalid date’ in the history page for every item but only certain times of the day.

**Comment by p0psicles** [comment]
Yeah that could be. The airdates are calculated with each show refresh. Maybe doing a force update after, fixes some?

**Comment by reconman** [comment]
@Tailslide Did you set the the TZ environment variable correctly?

For example, `-e TZ=Europe/Berlin`

**Comment by Tailslide** [comment]
@reconman I had it set to MST but I changed it to Canada/Mountain and the history page seems to be showing the dates and times correctly now, thanks.

I notice no matter what time the shows actually start at, the scheduled page shows all the shows as starting at 6pm which would be midnight UTC time.  If I go into the details of the show, the start time shows correctly under "Originally Airs:"

I tried running 'update' option for the show under mass update but still shows the same.

**Comment by Tailslide** [comment]
Actually found something interesting.. my iPhone under history on both chrome and safari shows 'invalid date' and chrome on my desktop shows the correct date and time

**Comment by ziogref** [comment]
> Yeah that could be. The airdates are calculated with each show refresh. Maybe doing a force update after, fixes some?

Ok so I figured out and got my medusa onto the develop branch (had to do it from the command line)

Issue still occurring. 

In the show Station 19 it says

Originally Airs: | Thursday 8:00 PM on ABC (US)
In the schedule is shows Friday 12am

Medusa Info:

Branch: develop
Commit: 5db9f63254814ba7e4f46f0ac12000ae988d496a
Version: 0.5.12
Database: 44.18
--

**Comment by p0psicles** [comment]
What's your setting for using local timezone or networks. In config - general - interface

**Comment by ziogref** [comment]
> What's your setting for using local timezone or networks. In config - general - interface

Local

and I just fixed it. My server time was set to UTC. sigh.

I will go back to master and see what happens there

**Comment by ziogref** [comment]
> What's your setting for using local timezone or networks. In config - general - interface

TIme is correct in master now that I have corrected the timezone on the server.

Its appears schedule uses Server time but the front page uses clients time

**Comment by p0psicles** [comment]
> Its appears schedule uses Server time but the front page uses clients time

Is that still an issue. Maybe I'm misunderstanding. Can you post some screenshots?

**Comment by ziogref** [comment]
When I switched to the devolop branch my issue still existed (as explained in my original post) but then I double checked my server time as I noticed and oddity when I logged in (login time being 4am instead of 2pm)

So I checked, server time was UTC. Updated it to UTC+10, rebooted server and issue resolved.

**Comment by p0psicles** [comment]
If everyone is working fine, all is good
