### ISSUE TITLE
Reloading the page is required when changing the Schedule layout

### ISSUE THREAD

**Issue by reconman** [pymedusa/Medusa#9415]
**Describe the bug**
Switching the Schedule Layout between the 4 modes (Calendar, Poster, Banner, List) has no immediate effect. Only after reloading the page, the layout is different.

**To Reproduce**
1. Go to Schedule
2. Switch the layout -> Nothing happens
3. Reload the page -> the layout changed

**Expected behavior**
The layout should change immediately like when changing the Shows layout.

**Medusa (please complete the following information):**
 - OS: Docker
 - Branch: develop
 - Commit: 68c257aaf2c7db37b6293011b3bcf607ef17e99b
 - Python version: Unknown
 - Database version: Unknown

**Comment by p0psicles** [comment]
I'm already In the working on vueify-ing schedule page. Will be fixed with PR #9403

**Comment by p0psicles** [comment]
should be fixed
