### ISSUE TITLE
A Feature Request - I Guess...  Add "5 Star" Network TZ

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/Medusa#9447]
Hi Folks - I'm getting an error: "2021-04-18 09:19:42 ERROR    BACKLOG :: [55cecb9] Missing time zone for network: 5Star"

"5Star (stylized as 5STAR) is a British free-to-air television channel owned by ViacomCBS Networks UK & Australia." (See Wikipedia [https://en.wikipedia.org/wiki/5Star](url)

Would it be problematic to add the tz for the network?

Thanks!

**Comment by medariox** [comment]
Added https://github.com/pymedusa/medusa.github.io/commit/5fd97747bf62aecd5d3c7d6393992924fcfd57ba

Next time just report the error from Medusa.
