### ISSUE TITLE
'utf-8' Error when trying to list of IMDB recommended shows

### ISSUE THREAD

**Issue by technic88** [pymedusa/Medusa#9455]
**Describe the bug**
Upon going to Shows --> Add Recommended Shows --> Add from IMDB's Popular Shows, get the following error:

_Fetching of Recommender Data failed. Exception:

'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte_

**To Reproduce**
1. Go to 'Shows' --> 'Add Recommended Shows'
2. Click on 'Add from IMDB's Popular Shows''
3. See error

**Expected behavior**
Should see list of recommended shows from IMDB.

**Medusa:**
OS: ubuntu 18.04 x64
Branch: master                  
Commit: 0286e89d15c86c8a9586e82f373d019f656f8b42                  
Version: 0.5.11
Database: 44.18                 
Python Version: | 3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0]
Locale: en_US.UTF-8

**Comment by medariox** [comment]
See https://github.com/pymedusa/Medusa/issues/9094#issuecomment-766845722
