### ISSUE TITLE
Manual Post-processing Method field empty

### ISSUE THREAD

**Issue by sebeksd** [pymedusa/Medusa#9457]
**Describe the bug**
Often after opening Manual Post-processing value for "Method" is empty, after refreshing page value is loaded correctly (not sure if this always works). This behavior started after "Process Async" was added. When "method" is empty processing is not working.

**To Reproduce**
1. Go to Main page
2. Select "Shows" -> "Manual post-processing"

**Expected behavior**
Value "Method" to be loaded every time

**Screenshots**
![image](https://user-images.githubusercontent.com/18705953/115356078-970b7980-a1bb-11eb-9acd-8bbbd158f766.png)

**Medusa (please complete the following information):**

Medusa Info: | 
Branch: master
Commit: 6bfdb2236003331e639a1845f765ee0462ae8a5dVersion: 0.5.11Database: 44.18
-- | --
Python Version: | 3.8.8 (default, Mar 15 2021, 13:12:20) [GCC 9.3.0]
SSL Version: | OpenSSL 1.1.1k 25 Mar 2021
OS: | Linux-5.10.0-0.bpo.5-amd64-x86_64-with
Locale: | en_US.UTF-8

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>
</details>

**Additional context**
Not sure if this is related but at same time this start to happen (i think so) something else start to happen, often after opening a show background image is loaded incorrectly (most of the time it is from previous show that was opened), refreshing page load correct background:
![image](https://user-images.githubusercontent.com/18705953/115356974-7263d180-a1bc-11eb-8694-ab0d5c4b9cbd.png)

**Comment by Yellow1144** [comment]
Yeah, I saw this discussed in a different issue. 
In the interim, after getting to the manual post-processing page, hitting F5 to reload the page makes it appear then manual post-processing will work

**Comment by p0psicles** [comment]
It's fixed in a branch.

**Comment by reconman** [comment]
See #9377, I think the bug is fixed in develop?

**Comment by p0psicles** [comment]
I think it's already in Master. But definitely develop.

**Comment by sebeksd** [comment]
Yes its working fine now, thanks for great work.
Quick question, I mentioned backgrounds not working correctly and now it seems that it is really a separate problem, should I report it as separate or are you already aware of it ?

**Comment by p0psicles** [comment]
Backgrounds are fixed in develop

**Comment by sebeksd** [comment]
Perfect :)
