### ISSUE TITLE
Remove series with file deletion deletes everything in root folder!

### ISSUE THREAD

**Issue by Arskin-Fertrubble** [pymedusa/Medusa#9465]
Thanks, devs. I was way overdue to sort out my TV series on the NAS device. This (as per title) took care of it nicely.

So I downloaded a few episodes again. And stupidly removed a single series with file delete.

Again, it deleted the lot in the root folder.

Not happy.

Medusa version 0.5.9 (28-02-2021)

**Comment by p0psicles** [comment]
That has probably something to do with your setup. Maybe folder ownership / permissions. As no other user reported about this in years

**Comment by medariox** [comment]
Please use and fill out the issue template when opening an issue, otherwise we can't help you (not happy).
