### ISSUE TITLE
Changing the location of torrent downloads need a restart of medusa before it is used.

### ISSUE THREAD

**Issue by BenjV** [pymedusa/Medusa#9480]
**Describe the bug**
When changing the location for downloaded torrent files that location is only used after a restart of Medusa.

**To Reproduce**
1. Go to 'Search Setting" and "TorrentSearch"
2. Change the "Downloaded files location" 
3. Click "Save Changes"
4. The changes are only being used after a restart of medusa.

**Expected behavior**
The change of the download location should be invoke without a restart.
And the when invoking the "Test Connection" that location should also be used not the old one.

**Cause**
The field "Downloaded files location" is saved to the config but not copied to the variable "app.TORRENT_PATH".
That is only being done at startup when the config is loaded.

That field should be copied to the variable "app.TORRENT_PATH" when clicked on "Save Changes". 
Also when clicked on "Test Connection" that field should be copied to "app.TORRENT_PATH" so a test can be made if the chosen folder is a correct share.

**Comment by Yellow1144** [comment]
Could this be related to the issue I have where Medusa doesn't remember the post processing location after a reboot. I have to re-enter the post-processing path every time after I reboot.


Branch: develop
Commit: bb4b9399992d8132d37f253b479841c9219bf21c
Version: 0.5.11
Database: 44.18
--
Python Version: | 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
SSL Version: | OpenSSL 1.1.1f 31 Mar 2020
OS: | Linux-5.8.0-50-generic-x86_64-with-glibc2.29
Locale: | en_CA.UTF-8

**Comment by p0psicles** [comment]
@BenjV when you save the config from the UI, it's always saving that to the python global AND the config.
I tested this using the search client `rtorrent`, but that's not that different.

![image](https://user-images.githubusercontent.com/1331394/116040902-e09d0e00-a66c-11eb-9dc7-d938a2efd765.png)

And when snatching an episode, the new value for app.TORRENT_PATH was available.

So i'm not sure what's going on.

**Comment by BenjV** [comment]
I will check again, maybe I made a mistake.
Let you know my findings.

**Comment by p0psicles** [comment]
I don't think thats the way for the torrent clients.
Best is to start here:
https://github.com/pymedusa/Medusa/blob/master/medusa/server/web/home/handler.py#L225
and extend that.

You'll also need to extend the api call of course. Here: https://github.com/pymedusa/Medusa/blob/master/themes-default/slim/src/components/config-search.vue#L578

Then if you want specific logic/checks in test_authentication. You might want to create a new test_authentication method in downloadstation.py, that overwrites the one in generic.py.

**Comment by BenjV** [comment]
I am not very familiar with .vue editing.

So can you tell met what I need to add to L578 of the config-search.vue so the testTorrent on L225 of the handler.py gets the location as an extra parameter?

**Comment by p0psicles** [comment]
I can create a pr. And give you access. That way I can take care of the frontend changes. If your okay with that?

**Comment by BenjV** [comment]
Sounds fine to me.
