### ISSUE TITLE
Cannot start Medusa

### ISSUE THREAD

**Issue by sdn3rd** [pymedusa/Medusa#9484]
When trying to start Medusa even after a fresh pull, i get a syntax error:
Apr 27 17:47:30 lx00 medusa[29488]:     from .rebulk import Rebulk
Apr 27 17:47:30 lx00 medusa[29488]:   File "/opt/medusa/ext/rebulk/rebulk.py", line 8, in <module>
Apr 27 17:47:30 lx00 medusa[29488]:     from .builder import Builder
Apr 27 17:47:30 lx00 medusa[29488]:   File "/opt/medusa/ext/rebulk/builder.py", line 16
Apr 27 17:47:30 lx00 medusa[29488]:     class Builder(metaclass=ABCMeta):
Apr 27 17:47:30 lx00 medusa[29488]:                            ^
Apr 27 17:47:30 lx00 medusa[29488]: SyntaxError: invalid syntax
Apr 27 17:47:30 lx00 systemd[1]: medusa.service: Control process exited, code=exited status=1
Apr 27 17:47:30 lx00 systemd[1]: medusa.service: Failed with result 'exit-code'.
Apr 27 17:47:30 lx00 systemd[1]: Failed to start LSB: starts instance of Medusa.

**Comment by medariox** [comment]
You are probably using an unsupported Python version. Medusa requires Python 3.6 or newer.

**Comment by sdn3rd** [comment]
Apr 27 17:47:30 lx00 medusa[29488]:     from .rebulk import Rebulk
Apr 27 17:47:30 lx00 medusa[29488]:   File "/opt/medusa/ext/rebulk/rebulk.py", line 8, in <module>
Apr 27 17:47:30 lx00 medusa[29488]:     from .builder import Builder
Apr 27 17:47:30 lx00 medusa[29488]:   File "/opt/medusa/ext/rebulk/builder.py", line 16
Apr 27 17:47:30 lx00 medusa[29488]:     class Builder(metaclass=ABCMeta):
Apr 27 17:47:30 lx00 medusa[29488]:                            ^
Apr 27 17:47:30 lx00 medusa[29488]: SyntaxError: invalid syntax
Apr 27 17:47:30 lx00 systemd[1]: medusa.service: Control process exited, code=exited status=1
Apr 27 17:47:30 lx00 systemd[1]: medusa.service: Failed with result 'exit-code'.
Apr 27 17:47:30 lx00 systemd[1]: Failed to start LSB: starts instance of Medusa.
root@lx00:/opt/medusa# env python
Python 3.6.9 (default, Jan 26 2021, 15:33:00)

**Comment by sdn3rd** [comment]
I am using 3.6.9 and ensured my python environment is pointing to it globally.

**Comment by medariox** [comment]
That is not possible.

The error you are seeing is caused by the fact that you are using a version of Python that doesn't support Abstract Base Classes (first introduced in Python 3.4).

**Comment by sdn3rd** [comment]
Thanks for the help, more helpful would have been the link to follow the ubuntu installation as updates broke it.

https://github.com/pymedusa/Medusa/wiki/Medusa-installation-Debian-Ubuntu

This fixed it, which would have been a lot more helpful to reply with.

**Comment by medariox** [comment]
I did the best I could, considering you completely ignored the issue template we ask you to fill before opening an issue. It would be pointless to point you to a system specific guide, without knowing your system.
