### ISSUE TITLE
Some Release Group's names not getting properly parsed during search.

### ISSUE THREAD

**Issue by JHBoricua** [pymedusa/Medusa#9495]
**Describe the bug**
When Medusa searches for Anime releases using Nyaa, the name of the Release Group is not parsed properly and as a result the download is not initiated. It's not all of them, but the ones affected are pretty consistent. For example:
Erai-raws releases are mis-identified as release group 'Multiple' or 'Multiple Subtitle'
Judas releases are mis-identified as release group 'Weekly'
etc....

Manually entering the mis-identified group name on the series settings works as a workaround to this issue, but it could probably lead to inconsistent results.

**Expected behavior**
Group Release parsed correctly so correct episode is snatched for download.

**Screenshots**
![image](https://user-images.githubusercontent.com/20731661/116820878-e6976100-ab3c-11eb-86d1-d1ec9eb2518e.png)

**Medusa (please complete the following information):**
 - OS: Medusa Docker on top of Debian Buster (Release 0.5.1.1)
 - Branch: Master
 - Commit: 0286e89
 - Python version: 3.8.8
 - Database version: 44.18

**Comment by p0psicles** [comment]
Parsing is handled by the package guessit. You could try to report these release names there. And maybe they'll fix it. 

But not a medusa issue.
