### ISSUE TITLE
Issues with default Schedule Sorting

### ISSUE THREAD

**Issue by avataroftime** [pymedusa/Medusa#9550]
Before the recent update, the Schedule page used to be sorted, by default, by Airdate (descending). Since the update, it seems to have changed to Later (descending) -> soon (descending) -> today (descending)… unsure about missed as I don't have any :)

Now I can sort it correctly by selecting Airdate, but it does not keep when I go off the page or reload. This does make the page weird to read now. Are we able to get this back to a more logical sorting (or be able to save the settings on how it should be sorted).

**Screenshots**
Broken:
![image](https://user-images.githubusercontent.com/14968565/118447576-4e040200-b734-11eb-8c5a-443b24e7e6e7.png)

Fixed:
![image](https://user-images.githubusercontent.com/14968565/118448090-e13d3780-b734-11eb-9827-993de8656d19.png)

**Medusa:**
 - OS: Linux-3.10.0-1160.6.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
 - Branch: master
 - Commit: d065c7
 - Python version: 3.6.8
 - Database version: 44.18

**Comment by p0psicles** [comment]
Fixed in develop branch
