### ISSUE TITLE
Page will hang in Firefox when clicking Wanted or other checkboxes on show page

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#9559]
**Describe the bug**
In the show page when I click on one of the labels `Wanted` etc, the page will just hang on Firefox 88.0.1 (64-bit)
![image](https://user-images.githubusercontent.com/4103090/118788213-d947d980-b893-11eb-9c91-acbf3454e486.png)

Medusa Configuration
Medusa Info: | Branch:                 master                  Commit:                 4d9c7927ebeb425e386b122a230c849163d065c7                  Version:                 0.5.12                  Database:                 44.18
-- | --
Python Version: | 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.1i  8 Dec 2020
OS: | Windows-10-10.0.17763-SP0
Locale: | nl_NL.cp1252

**Comment by p0psicles** [comment]
Does it show the same unresponsiveness as for smaller (new) shows. Like with a limited amount of episodes

**Comment by Rouzax** [comment]
Yes it does
![image](https://user-images.githubusercontent.com/4103090/118798386-df42b800-b89d-11eb-9c58-194955b49457.png)

**Comment by theunicellular** [comment]
Not sure if this is helpful but this happens for me on Chrome and Edge, regardless of show size.

**Comment by Akurosia** [comment]
![9ChC4hV3kG](https://user-images.githubusercontent.com/7465469/123226825-49213380-d4d4-11eb-82fc-2ca5a661422e.png)

this is the error i get whenever clicking any of the filter in firefox
