### ISSUE TITLE
Disk I/O error in SearchQueue

### ISSUE THREAD

**Issue by jameshope87** [pymedusa/Medusa#9574]
I have recently moved my Medusa Installation from one server to another and after a while getting it running, I am finally looking at my web interface with old database on the screen.

I just tried to add a new show and while it appeared in the show list, only 1 series showed up and this error was triggered:

2021-05-25 16:58:14 ERROR SHOWQUEUE-UPDATE :: [b21beeb] DB error: disk I/O error Traceback (most recent call last): File "/media/sdy1/**********/Medusa/medusa/db.py", line 286, in action self.connection.commit() sqlite3.OperationalError: disk I/O error

`2021-05-25 16:58:14 ERROR SHOWQUEUE-UPDATE :: [b21beeb] Traceback (most recent call last): File "/media/sdy1/**********/Medusa/medusa/queues/show_queue.py", line 670, in run self.show.save_to_db() File "/media/sdy1/**********/Medusa/medusa/tv/series.py", line 2191, in save_to_db main_db_con.upsert('tv_shows', new_value_dict, control_value_dict) File "/media/sdy1/**********/Medusa/medusa/db.py", line 355, in upsert self.action(query, list(itervalues(valueDict)) + list(itervalues(keyDict))) File "/media/sdy1/**********/Medusa/medusa/db.py", line 286, in action self.connection.commit() sqlite3.OperationalError: disk I/O error Traceback (most recent call last): File "/media/sdy1/**********/Medusa/medusa/queues/show_queue.py", line 670, in run self.show.save_to_db() File "/media/sdy1/**********/Medusa/medusa/tv/series.py", line 2191, in save_to_db main_db_con.upsert('tv_shows', new_value_dict, control_value_dict) File "/media/sdy1/**********/Medusa/medusa/db.py", line 355, in upsert self.action(query, list(itervalues(valueDict)) + list(itervalues(keyDict))) File "/media/sdy1/**********/Medusa/medusa/db.py", line 286, in action self.connection.commit() sqlite3.OperationalError: disk I/O error`

**Comment by p0psicles** [comment]
You have a disk IO error

**Comment by p0psicles** [comment]
Prob bad disk

**Comment by jameshope87** [comment]
It's a brand new disk, hence the migration into the new server. Could it be the database file that's corrupted instead?

**Comment by p0psicles** [comment]
Maybe. But that's really rare. You could always try starting with new db to test that out

**Comment by jameshope87** [comment]
Is it the "main.db" that I would have to backup and move to test that?

**Comment by p0psicles** [comment]
Yes

**Comment by medariox** [comment]
This could also be a symptom of wrong permissions on the DB files: e.g. if the file is read only.

**Comment by jameshope87** [comment]
So I tried moving all the main.db* files and the cache.db* files and the failed.db* files into a backup location and I get a disk I/O error when starting up now.

I will try a fresh install so I know permissions are correct, otherwise I guess I will submit a ticket about the disk failing!

**Comment by p0psicles** [comment]
Medariox has a point. You should also check file rights/ownership

**Comment by jameshope87** [comment]
I deleted all the dB files though, so surely they should have been created with the right permissions?

I check the Medusa folder and everything is owned by {my username}:{my username}

And the newly created files have rw for the owner but nothing else.

**Comment by BenjV** [comment]
Permission are inherited from the parent folder, so most likely the user which is running Medusa does not have the correct permissions from writing to that folder and so Medusa cannot create a database there nor modifying existing databases.

**Comment by jameshope87** [comment]
It wasn't that because database files were being made but the error was throwing when trying to modify them.

Anyway, I am not sure what solved this, but it seems to be working absolutely fine now...
