### ISSUE TITLE
Show Update Issues

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#9576]
**Describe the bug**
Over the last few days medusa does not seem to be updating the show status with new episodes or info.

**Medusa (please complete the following information):**
 - OS: Synology - Docker
 - Branch: master
 - Commit: fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
 - Python version: 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
 - Database version: 44.18

**Additional context**
When i do an Force Update them it pulls all the data but it does not seem to be doing this automatically anymore.

**Comment by HPMSGEN8** [comment]
Hi All,

Any update on this please as it is really causing me an lot of issues. 

Thanks

**Comment by p0psicles** [comment]
In server status. Does it show the showupdate queue alive?

**Comment by p0psicles** [comment]
If it's not an exception should have occurred in the logs.

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

Yes it is showing alive.

**Comment by MPvDam** [comment]
I have the same problems and I can't also not add shows.

- OS: Synology
- Branch: master
- Commit: 4d9c7927ebeb425e386b122a230c849163d065c7
- 3.7.10 (default, Mar 14 2021, 11:04:23) [GCC 4.9.3 20150311 (prerelease)]
- Database version: 44.18

**Comment by Frank071** [comment]
Could this be due to an issue with the indexer? I noticed that Medusa won't update a show if it has done that sometime during the last 12 weeks and it is not in the updated-list of the indexer. But that should/would mean that this issue is troubling a lot of people.

**Comment by MPvDam** [comment]
Hi @Frank071,

I have try'd all the indexers and they all give no updates or the possibility to add shows.

**Comment by p0psicles** [comment]
That's probably an issue with your connection. Maybe a proxy? All three indexes are working fine

**Comment by MPvDam** [comment]
Hi @p0psicles 
With a tcpdump i see that he want to connect to https://server-54-192-204-42.ham50.r.cloudfront.net but receive an 403 error there maybe to many traffic?

**Comment by p0psicles** [comment]
Yes could be. Your behind a vpn?

**Comment by MPvDam** [comment]
No i am not behind a vpn.

**Comment by MPvDam** [comment]
I see he use IPv6 to api.tvmaze.com is that maybe the problem.

**Comment by MPvDam** [comment]
api.tvmaze.com doesn't response not right at IPv6.

**Comment by MPvDam** [comment]
I have make a manual entry on the Synology in /etc/hosts so api.tvmaze.com resolve only IPv4. I can now add/update the shows.
I will send an e-mail to tvmaze to fixed the Ipv6 web access.

**Comment by HPMSGEN8** [comment]
So my issue is still not solved. I have to do a force update to get this to work.

Any thing I can do about this please ?

**Comment by p0psicles** [comment]
Is this for  a specific show. Or multiple?

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

It seems to be for all.

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

This is still happening on my Synology & Docker

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

This issue is staring to affect all my shows now after checking again. What can be done to solve this please.

**Comment by p0psicles** [comment]
I don't have this issue. So I don't know what to solve? You should look into some patterns your self. Like have some shows on tvdb, tvmaze and tmdb. And monitor that.

You could capture a debug log of a showupdater thread. And post that. We could see if it has issues getting the updated episodes.

**Comment by HPMSGEN8** [comment]
tvdb is the most of he ones i have issues with.

**Comment by p0psicles** [comment]
They will eventually become even less reliable. I would seriously consider switching to tvmaze. Unless you need thexem.de for a show

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

What you do say that ? and slow why the move as for the last x years tvdb was always the point ?

I will change that is not an issue just would like to know more and understand what or why the change please.

Thanks

**Comment by HPMSGEN8** [comment]
Also how would I change this for all the already added shows please ?

**Comment by p0psicles** [comment]
> Why you do say that ? I have been using it for years.
https://github.com/pymedusa/Medusa/discussions/8738

Nothing has changed in medusa in that part of the application in years. So when it's now failing for you, there are only a few reasons to why. From which the most obvious are. 1. tvdb api is not up2date. 2. you have issues with connecting to tvdb servers.

If this issue is not present with for ex tvmaze. I would suggest switching to tvmaze.

You can remove the show (do not remove the data). And then add it through the "Add existing show" feature.

In the near future i'll add a tool to migrate between indexers

**Comment by HPMSGEN8** [comment]
Thanks alot @p0psicles for this info.

I will start to move thigs over bit buy bit and see what happens.

Thanks for your time :)

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

What is the cost of the v4 API OR can you add an feature for users to add the new v4 API with there own PIN ? 

Thanks
