### ISSUE TITLE
Medusa can't communicate with Transmission

### ISSUE THREAD

**Issue by tcamargo** [pymedusa/Medusa#9619]
**Describe the bug**
Medusa can't RPC to transmission. I suspect it is something on Transmission 3.00 (CSRF protection). I get the same error if i try to connect to transmission rpc directly in a browser.
<details>
409: Conflict
Your request had an invalid session-id header.

To fix this, follow these steps:

When reading a response, get its X-Transmission-Session-Id header and remember it
Add the updated header to your outgoing requests
When you get this 409 error message, resend your request with the updated header
This requirement has been added to help prevent CSRF attacks.

X-Transmission-Session-Id: VZjCBODmHwSZifbrPg7d2XUnXO2TXzCNAcgcVcyIl2FKKXec
</details>

**To Reproduce**
1. Go to 'Torrent Search'
2. Add transmission details
3. Click on Test Connection

**Expected behavior**
"Success. Connected and authenticated"

**Screenshots**
<img width="1249" alt="2021-06-08_09-37-55" src="https://user-images.githubusercontent.com/52097/121186234-428c8e00-c83d-11eb-9c33-4e585d8f1ad5.png">

**Medusa (please complete the following information):**
 - OS: linuxserver.io docker image
 - Branch: master
 - Version: 0.5.12
 - Transmission: 3.00 (haugene/transmission-openvpn docker image)

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>
2021-06-08 09:32:37 DEBUG    Thread_0 :: [] GET URL: http://transmission.discworld:9091/transmission/rpc [Status: 409]
2021-06-08 09:32:37 DEBUG    Thread_0 :: [] User-Agent: Medusa/0.5.12 (Linux; 4.4.59+; 1607cb9e-c854-11eb-be8c-0242ac150002)
2021-06-08 09:32:37 DEBUG    Thread_0 :: [] The response returned a non-200 response while requesting url http://transmission.discworld:9091/transmission/rpc Error: HTTPError('409 Client Error: Conflict for url: http://transmission.discworld:9091/transmission/rpc')
</details>

**Additional context**
Migrating from Sickchill to Medusa. Same config works with Sickchill in a container.

**Comment by p0psicles** [comment]
Just verified with a docker version of transmission. We've fixed the issue in the develop branch.

**Comment by tcamargo** [comment]
Thx! Confirmed!

**Comment by teocasse** [comment]
Any plans on when this will be release to master?
