### ISSUE TITLE
Anime Search Results Hang-Up on the Word Season 

### ISSUE THREAD

**Issue by trumblejoe** [pymedusa/Medusa#9622]
**Describe the bug**
When searching for anime series (for example using Nyaa), the results are limited to results containing "Season" in the release name. For example, Aldnoah.Zero will only return [Kametsu].Aldnoah.Zero.Season.1.(BD.1080p.Hi10.FLAC).[Dual-Audio], and not [Lulu] Aldnoah Zero [BD 1080p Hi10 FLAC][Dual-Audio], [USS] Aldnoah.Zero (2014) (Dual Audio) [BD 1080p H264 AC3], etc.

This is probably a big cause of the ongoing anime search issues we have been seeing lately.

**Medusa (please complete the following information):**
 
Medusa Info: | Branch:&nbsp;masterCommit:&nbsp;UnknownVersion:&nbsp;0.5.10Database:&nbsp;44.18
-- | --
Python Version: | 3.8.5 (default, Feb 19 2021, 09:27:16) [GCC 9.3.0]
SSL Version: | OpenSSL 1.1.1j 16 Feb 2021
OS: | Linux-4.19.0-0.bpo.16-amd64-x86_64-with
Locale: | en_US.UTF-8

The only relevant search logs needed are here, it's only returning these two results because of the word "Season"
2021-06-10 00:26:40 INFO	FORCEDSEARCHQUEUE-MANUAL-279827 :: Nyaa :: Quality of [Kametsu].Aldnoah.Zero.Season.1.(BD.1080p.Hi10.FLAC).[Dual-Audio] is 1080p HDTV
2021-06-10 00:26:40 INFO	FORCEDSEARCHQUEUE-MANUAL-279827 :: Nyaa :: Quality of [Kametsu].Aldnoah.Zero.Season.2.(BD.1080p.Hi10.FLAC).[Dual-Audio] is 1080p HDTV
2021-06-10 00:26:39 INFO	FORCEDSEARCHQUEUE-MANUAL-279827 :: Nyaa :: Performing season pack search for Aldnoah.Zero

**Additional context**
Aldnoah.Zero is actually a great example, because it is often released under Aldnoah Zero, or Aldnoah.Zero other times, Season 1 & Season 2 are often combined into just a single season, and most releases don't have the word Season anywhere as it's released as just the show name. Scene exceptions are "Aldnoah Zero" by default, & I added one "Aldnoah" which as far as I can tell don't seem to be changing the search results (I almost wonder if it isn't being ignored...).

**Comment by p0psicles** [comment]
Medusa doesn't support multiseason or show packs.
