### ISSUE TITLE
Schedule page does not show the times (instead it shows 00:00 as time)

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#9624]
**Describe the bug**
The schedule page does not report the correct airdate for eps. all episodes that are listed are displayed with a time of 00:00 on the date they air. 
- TimeZone is set to "local" under general -> interface
- local Timzone is Europe/Berlin
- docker is started with  TZ=Europe/Berlin

This is not the case when I look at the shows. the airdates for the shows are displayed correct.
Attached you can see the same to EP's one time from the shows detail list compared to the schedule window.

Missed EP

![Screenshot 2021-06-10 at 08 20 07](https://user-images.githubusercontent.com/869637/121475137-5531cf00-c9c5-11eb-8b7b-207b6221d0df.png)
![Screenshot 2021-06-10 at 08 20 54](https://user-images.githubusercontent.com/869637/121475155-595dec80-c9c5-11eb-8cac-ef5782679857.png)

Today EP

![Screenshot 2021-06-10 at 08 45 25](https://user-images.githubusercontent.com/869637/121477562-4bf63180-c9c8-11eb-955f-2d92dc249e8c.png)
![Screenshot 2021-06-10 at 08 44 30](https://user-images.githubusercontent.com/869637/121477587-56183000-c9c8-11eb-9223-6ecdad55e686.png)

(EDIT: Added two samples) 

**To Reproduce**
1. Go to 'Schedule' and check the list

**Expected behavior**
The air dates displayed on the schedule list are displayed with matching time (in the selected timezone) and are used to trigger the search for new EPs.

**Screenshots**
See above

**Medusa (please complete the following information):**

Its the current docker image.

Medusa Info: | Branch:&nbsp;master&nbsp;Commit:&nbsp;4d9c7927ebeb425e386b122a230c849163d065c7&nbsp;Version:&nbsp;0.5.12&nbsp;Database:&nbsp;44.18
-- | --
Python Version: | 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-3.10.105-x86_64-with
Locale: | en_US.UTF-8

**Debug logs (at least 50 lines):**
There is no error / debug info to show

**Additional context**
N/A

**Comment by p0psicles** [comment]
Have those shows been added through tmdb?

**Comment by udochrist** [comment]
I'm unsure for these two shows. Can I check that somewhere on the show page?

FYI: I have only picked two examples. this issue applies to all my shows and there are definitely non-TMDB shows affected on that list. the schedule list (with all tick-marks) contains about 60 EPs that are all displayed with time 00:00

**Comment by p0psicles** [comment]
Tmdb doesn't have an airtime. So we default to 00.00. But the others should definitely show correct times. There is an issue open where times are for some users incorrect. But that should show different times

**Comment by p0psicles** [comment]
Also maybe it's already resolved in develop branch

**Comment by udochrist** [comment]
ok. as written all my times are 00:00
here is the screenshot of half the list

![Screenshot 2021-06-10 at 11 07 23](https://user-images.githubusercontent.com/869637/121497849-24a95f80-c9dc-11eb-860e-eef0c07047d3.png)

For the development branch: no idea how to use that with docker. can I use the tag "develop" (3days old acc. to docker-hub) to get that version and retry?

**Comment by medariox** [comment]
> For the development branch: no idea how to use that with docker. can I use the tag "develop" (3days old acc. to docker-hub) to get that version and retry?

Yes, exactly.

**Comment by udochrist** [comment]
Hmm. I switched to develop with my medusa container.

```
Container     Repository        Tag       Image Id      Size
-------------------------------------------------------------
medusa      pymedusa/medusa   develop   5c202470e9f6   176 MB
```

The info shows:

Medusa Info: | Branch:&nbsp;master&nbsp;Commit:&nbsp;a2683acb7fd77c51d2118722bdf76d947434fa85&nbsp;Version:&nbsp;0.5.12&nbsp;Database:&nbsp;44.18
-- | --
Python Version: | 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-3.10.105-x86_64-with
Locale: | en_US.UTF-8


There is no difference when It comes to the "Schedule". Still everything 00:00. Maybe the "develop" image is build on "master" branch?

**Comment by p0psicles** [comment]
Can you confirm that a tvdb show is showing 00.00?

**Comment by udochrist** [comment]
> Can you confirm that a tvdb show is showing 00.00?

tvdb show:
![Screenshot 2021-06-10 at 13 13 58](https://user-images.githubusercontent.com/869637/121515777-da30de80-c9ed-11eb-9808-9baea0e9be3b.png)
schedule:
![Screenshot 2021-06-10 at 13 14 30](https://user-images.githubusercontent.com/869637/121515820-e321b000-c9ed-11eb-8712-f2295ed75784.png)

I mean: the show is showing the dates and times for all eps and providers. it is only the "schedule" page that shows 00:00

**Comment by p0psicles** [comment]
What are your date/time settings in config / general?

**Comment by udochrist** [comment]
> What are your date/time and timezone settings in config / general?

provided in the issue template

https://github.com/pymedusa/Medusa/issues/9624#issue-916958674

**Comment by ukharley** [comment]
Same for me. All airtimes in schedule are 00:00 and also default sorting is wrong. Sorting I believe is fixed in develop.
Timezone set to local and half my shows are still using TVDB.

Started after update to version 0.5.12

**Comment by ddalben** [comment]
I have the same issue where all times are 00:00 on the schedule list page.  I have moved most of my shows over to TVMAZE but the issues is on all shows, TVMAZE and TVDB.   All images here are for the same show.
<img width="155" alt="time" src="https://user-images.githubusercontent.com/8142403/121633493-7e318d00-cab5-11eb-892a-70b7bdc08861.png">

Another quirk is that on the show page it shows IMDB and TVMAZE as the indexers.  On the Schedule page, it shows TVDB as well.  Not sure if it's related.
<img width="358" alt="page" src="https://user-images.githubusercontent.com/8142403/121633521-88538b80-cab5-11eb-8b31-a63e863cc46b.png">
<img width="102" alt="indexers" src="https://user-images.githubusercontent.com/8142403/121633527-8b4e7c00-cab5-11eb-9809-123cd07aaea1.png">

**Comment by ukharley** [comment]
To add to my observation earlier, when hovering over the tvdb indexer icon on the schedule page it says series undefined for all the shows, including those that use tvdb.
![medusa](https://user-images.githubusercontent.com/6772644/121638070-4826e580-ca82-11eb-990e-338f7982e4ca.png)

**Comment by udochrist** [comment]
This is some hell of a crazy issue.

I've just noticed that I see the date&time when I look at the schedule page using my iPad.
The dates are still 00:00 when I do the same from my MacBook Air (M1) and safari.

is it possible I need to clear some sort of cache on the MacBook browser before the switch to the development version picks up?

**Comment by p0psicles** [comment]
Can you try chrome? Maybe it's browser related?

**Comment by udochrist** [comment]
Seems to be browser related.

Chrome:
![Screenshot 2021-06-11 at 19 47 10](https://user-images.githubusercontent.com/869637/121728634-d4222700-caed-11eb-83cf-b7cce6fda54d.png)

Safari (M1 Mac)
![Screenshot 2021-06-11 at 19 47 37](https://user-images.githubusercontent.com/869637/121728682-e308d980-caed-11eb-86f1-b69cceca8218.png)

**Comment by p0psicles** [comment]
Ok good to know. I'll have a to borrow a Mac somewhere to debug this

**Comment by ukharley** [comment]
Still the same for me on the schedule page.
Tried three browsers, Firefox, Chrome and Edge.
Why does hovering over the tvdb icon say undefined when all the other show the correct link.
Clicking on the tvdb link gets a 404 error, all the others work.

**Comment by p0psicles** [comment]
> Why does hovering over the tvdb icon say undefined when all the other show the correct link.

That's probably I bug in the Vue template I need to address

**Comment by dotsam** [comment]
> Also maybe it's already resolved in develop branch

I can confirm that this is working fine in Safari on the develop branch.

**Comment by ddalben** [comment]
FWIW this occurs on Edge and Chrome for me on my PC. Also on my Android phone using Edge and Chrome

**Comment by p0psicles** [comment]
@ddalben your also running develop?

**Comment by ddalben** [comment]
> @ddalben your also running develop?

No, running 5.12.  I can't easily pull develop as I'm using the lsio docker

**Comment by ukharley** [comment]
I've moved to develop branch. Default schedule sorting is now fine as well as airdate. TVDB icon link is still wrong.
Thanks for your time and effort.

**Comment by udochrist** [comment]
So in summary:

- airtime in the schedule is shown on the development image but not if the browser is safari on macOS big sur.
- on the latest image no browser (tested safari&chrome) show the airtime on macOS big sur

**Comment by udochrist** [comment]
after the update to 0.5.13 this is working for me. I have tested the schedule pages on Big Sur x64 and m1 using safari.

**Comment by ddalben** [comment]
I still have the same issue on 5.13, is the preference to continue here or open another issue?

**Comment by udochrist** [comment]
> I still have the same issue on 5.13, is the preference to continue here or open another issue?

Could you test it using the private mode of your browser. I think this is a caching issue.

**Comment by ddalben** [comment]
> > I still have the same issue on 5.13, is the preference to continue here or open another issue?
> 
> Could you test it using the private mode of your browser. I think this is a caching issue.

Yes, apologies, I should have checked the basics before commenting.  All good for me too now.
