### ISSUE TITLE
Abnormal tracker - Search provider update

### ISSUE THREAD

**Issue by mysterfr** [pymedusa/Medusa#9627]
**Describe the bug**
The Abnormal tracker migrated to a new FQDN, pre-configured provider needs to be updated

**Additional context**
New base FQDN to be used : https://abn.lol

- Login page URL: https://abn.lol/Home/Login
- Search URL changed as well : https://abn.lol/Torrent

The search form, and subsequent URL have both changed as well.

Full search URL ("example") with no other params:
`https://abn.lol/Torrent?UserId=&YearOperator=%E2%89%A5&Year=&RatingOperator=%E2%89%A5&Rating=&SortOn=Created&SortOrder=desc&Search=example`

Full search URL, ("Mythic Quest S02E01") with "Series" category picked from the form:
`https://abn.lol/Torrent?UserId=&SelectedCats=1&AllGenres=false&YearOperator=%E2%89%A5&Year=&RatingOperator=%E2%89%A5&Rating=&SortOn=Created&SortOrder=desc&Search=Mythic+Quest+S02E01`

But the shortened version below works as well:
https://abn.lol/Torrent?Search=example

I look at the search form code, here's some variable value matching:
- "Series" main category: SelectedCats=1
- Qualities:
   * 2160p: SelectedQualities=1
   * 1080p: SelectedQualities=2
   * 720p: SelectedQualities=3
   * SD: SelectedQualities=4

When mutliple qualities are picked, the SelectedQualities parameter is repeated, for instance:
`SelectedQualities=2&SelectedQualities=3`

Results sorting:
`SortOn=Seeders&SortOrder=desc`

Thanks !

**Comment by mysterfr** [comment]
I had a bit of time so I tried to adapt the code of the below file:
`medusa/providers/torrent/html/abnormal.py`

Changes have to be made in the below functions:

**_init_**

```
def __init__(self):
        """Initialize the class."""
        super(ABNormalProvider, self).__init__('ABNormal')

        # Credentials
        self.username = None
        self.password = None

        # URLs
        self.url = 'https://abn.lol'
        self.urls = {
            'login': urljoin(self.url, 'Home/Login'),
            'search': urljoin(self.url, 'Torrent'),
        }

        # Proper Strings
        self.proper_strings = ['PROPER']

        # Miscellaneous Options

        # Cache
        self.cache = tv.Cache(self, min_time=30)
```

**search**

`    def search(self, search_strings, age=0, ep_obj=None, **kwargs):
        """
        Search a provider and parse the results.

        :param search_strings: A dict with mode (key) and the search value (value)
        :param age: Not used
        :param ep_obj: Not used
        :returns: A list of search results (structure)
        """
        results = []
        if not self.login():
            return results

        # Search Params
        search_params = {
            'SelectedCats': '1',   # "Series" category
            'SortOn': 'Created',  # Sorting: Available parameters: ReleaseName, Seeders, Leechers, Snatched, Size
            'SortOrder': 'DESC',  # Both ASC and DESC are available for sort direction
        }

        for mode in search_strings:
            log.debug('Search mode: {0}', mode)

            for search_string in search_strings[mode]:

                if mode != 'RSS':
                    log.debug('Search string: {search}',
                              {'search': search_string})
                    search_params['order'] = 'Seeders'

                search_params['search'] = re.sub(r'[()]', '', search_string)
                response = self.session.get(self.urls['search'], params=search_params)
                if not response or not response.text:
                    log.debug('No data returned from provider')
                    continue

                results += self.parse(response.text, mode)

        return results`


**parse**

The results table has changed.
Column labels are now in a proper TH instead of TD.
Different HTML class for the main table, and the rows element syntax has changed as well (no "tooltip" element of the dowload link TD, etc.

` def parse(self, data, mode):
        """
        Parse search results for items.

        :param data: The raw response from a search
        :param mode: The current mode used to search, e.g. RSS

        :return: A list of items found
        """
        # Units
        units = ['O', 'KO', 'MO', 'GO', 'TO', 'PO']

        items = []

        with BS4Parser(data, 'html5lib') as html:
            torrent_table = html.find(class_='table-rows')
            torrent_rows = torrent_table('tr') if torrent_table else []

            # Continue only if at least one release is found
            if len(torrent_rows) < 2:
                log.debug('Data returned from provider does not contain any torrents')
                return items

            # Catégorie, Release, Date, DL, Size, C, S, L
            labels = [label.get_text(strip=True) for label in torrent_rows[0]('th')]

            # Skip column headers
            for row in torrent_rows[1:]:
                cells = row('td')
                if len(cells) < len(labels):
                    continue

                try:
                    title = cells[labels.index('Release')].get_text(strip=True)
                    download = cells[labels.index('DL')].find('a')['href']
                    download_url = urljoin(self.url, download)
                    if not all([title, download_url]):
                        continue

                    seeders = try_int(cells[labels.index('S')].get_text(strip=True))
                    leechers = try_int(cells[labels.index('L')].get_text(strip=True))

                    # Filter unseeded torrent
                    if seeders < self.minseed:
                        if mode != 'RSS':
                            log.debug("Discarding torrent because it doesn't meet the"
                                      ' minimum seeders: {0}. Seeders: {1}',
                                      title, seeders)
                        continue

                    size_index = labels.index('Size') if 'Size' in labels else labels.index('Taille')
                    torrent_size = cells[size_index].get_text()
                    size = convert_size(torrent_size, units=units) or -1

                    item = {
                        'title': title,
                        'link': download_url,
                        'size': size,
                        'seeders': seeders,
                        'leechers': leechers,
                        'pubdate': None,
                    }
                    if mode != 'RSS':
                        log.debug('Found result: {0} with {1} seeders and {2} leechers',
                                  title, seeders, leechers)

                    items.append(item)
                except (AttributeError, TypeError, KeyError, ValueError, IndexError):
                    log.exception('Failed parsing provider.')

        return items`

**Comment by p0psicles** [comment]
When I get some time freed up I'll try to put these changes into a pull request

**Comment by p0psicles** [comment]
I'll need access to the provider. Can you contact me on our discord?
