### ISSUE TITLE
Torrentday asking for a non-existent? cookie value

### ISSUE THREAD

**Issue by dirkronsmans** [pymedusa/Medusa#9658]
**Describe the bug**
2021-06-21 08:31:21 WARNING  SEARCHQUEUE-PROPER-SEARCH :: [TorrentDay] :: [64df36d] You haven't configured the required cookies. Please login at TorrentDay, and make sure you have copied the following cookies: ('uid', 'pass', 'cf_clearance')

Since today all of the sudden I get a warning on Torrentday. the uid and pass cookie values are configured but cf_clearance seems to be a new one.
On the site itself tho there doesn't seem to be a cookie with that name either.

**Comment by dirkronsmans** [comment]
Seems a logout/login on the site got me the new cookie value on the site too so non-issue.

**Comment by AubreyKloppers** [comment]
tried to log out and back in - problem still there...

**Comment by dirkronsmans** [comment]
well you still need to add the cookie value in your configuration. For me the cookie was not present on the site till I logged out/logged back in

**Comment by AubreyKloppers** [comment]
I did get the new value and added it, but did not work...
`SNATCHQUEUE-SNATCH-82918 :: [0286e89] You haven't configured the required cookies. Please login at TorrentDay, and make sure you have copied the following cookies: ('uid', 'pass', 'cf_clearance')`

**Comment by AubreyKloppers** [comment]
Thank you
I had another look and switched to FireFox, deleted the cookies, logged back in and got the correct info.  It seems that Chrome has a problem, as the cookies just do not match.
Thanx again!
