### ISSUE TITLE
Add MagnetDL as torrent downloader

### ISSUE THREAD

**Issue by peervdb** [pymedusa/Medusa#9664]
Would it be possible to add MagnetDL to the list of torrent downloaders?

**Comment by p0psicles** [comment]
I'm not really a torrent user myself.
@duramato @medariox would this have any added value?

**Comment by medariox** [comment]
Seems like just another generic tracker. Not much value added IMO.

**Comment by peervdb** [comment]
It is for torrent downloaders who use public torrent sites

Op ma 28 jun. 2021 13:24 schreef Dario ***@***.***>:

**Comment by BenjV** [comment]
It is not a downloader nor a tracker.
It is a magnet torrent search engine, which add no extra value at all.

**Comment by peervdb** [comment]
It worked for me in SickChill :)

Op wo 30 jun. 2021 19:45 schreef BenjV ***@***.***>:

**Comment by medariox** [comment]
Use Zooqle or Rarbg. They also work just fine.
