### ISSUE TITLE
Schedule view all column content centered

### ISSUE THREAD

**Issue by mmhere** [pymedusa/Medusa#9692]
**Describe the bug**
The columns in the schedule view have all content centered.

**To Reproduce**
navigate to the schedule page.

**Expected behavior**
Some columns [may] make more sense to be left-justified as before.  Perhaps an setting/option could be provided.

**Medusa (please complete the following information):**
 - OS: Linux-4.19.0-17-amd64-x86_64-with-debian-10.10 
- Branch: master 64df36d92a354a89a69ac519911129a516b0c318
 - Medusa version:  0.5.13
 - Python version: 3.7
 - Database version: 44.18
 - Locale:	en_US.UTF-8

**Additional context**
I seem to recall this view (schedule) having most of the text heavy fields such as episode title, show name, being left justified in the past.  They presently appear centered within each field box for every row in the entire table, which makes things harder to read, IMHO.

**further blundering**

I grunged around in the schedule `.mako` files and did find table align=center in the HTML code, but perhaps the actual values are assembled in VUE during runtime.  [[...because... like a bad little hacker programmer, I tried to [temporarily] change those "center" values to "left" and restart everything, but could not see a change.  This was only a quick attempt and, of course, not a solution, and CLEARLY misguided.  ;-)  At any rate I probly don't understand how the caching works.  ...]]

Could we have an option to request left justification?

Or perhaps it is intended to be left justified anyway, and some combination of my server OS platform and browser viewer causes the centering?  Or is it in fact intended to be centered?

**Comment by p0psicles** [comment]
I'll check it out. If left aligned makes more sense, we can go for that

**Comment by p0psicles** [comment]
should be fixed with #9693
