### ISSUE TITLE
Synology DSM 7 package available on https://github.com/BenjV/SYNO-packages

### ISSUE THREAD

**Issue by BenjV** [pymedusa/Medusa#9723]
I have created a Synology package that can be installed on DSM 7.
Best way would be make a backup in medusa before you upgrade to DSM 7.
But the new package will try to recover the database and config from the old installation.
So first check if the config and database are  correctly loaded, if not restore the backup.

The package must be downloaded and manual installed.

It can be found here:
https://github.com/BenjV/SYNO-packages

**Comment by p0psicles** [comment]
Just to be clear. This package cannot be installed on dsm6?

**Comment by p0psicles** [comment]
I'll update our wiki

**Comment by BenjV** [comment]
No Synology change the package structure drastically.
So this package can only be installed on DSM 7.0-40000 or higher.
And older packages won't work on DSM 7.

**Comment by sendas** [comment]
I've installed it and now all show thumbnails disappeared...

**Comment by p0psicles** [comment]
Probably issue with the file rights on the cache folder

**Comment by BenjV** [comment]
No the cache location is owned by sc-medusa so that cannot be the issue.
More likely medusa has no permissions on the share where the video's are located.

As I wrote in the readme.md on my github:
Permissions to shares must be granted to the "system internal user" sc-medusa
If you have existing folders and files on that existing share, don't forget also to grand privs recursively with FileStation 
For details see: 
https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by sendas** [comment]
I had to restore my nas and now I can't install Medusa .... 

I've tried sickbeard custom but it doesn't let me because it says I don't have python. When I try to install python it fails ... 🤯 any idea ? Thanks

**Comment by BenjV** [comment]
If you have DSM 6, install Python 3 from the SynoCommunity and the my DSM 6 package of Medusa (download it to your PC and do a manual install).

If you have DSM 7 use my DSM 7 package of Medusa.
DSM 7 has standaard python 3 on board.
This package uses python 3 from the SynoCommunity if available, if not the stand python 3 from DSM 7.

Read the first post for the location of my packages.

Sickbeard custom does not work anymore for ages.

**Comment by sendas** [comment]
> If you have DSM 6, install Python 3 from the SynoCommunity and the my DSM 6 package of Medusa (download it to your PC and do a manual install).
> 
> If you have DSM 7 use my DSM 7 package of Medusa.
> DSM 7 has standaard python 3 on board.
> This package uses python 3 from the SynoCommunity if available, if not the stand python 3 from DSM 7.
> 
> Read the first post for the location of my packages.
> 
> Sickbeard custom does not work anymore for ages.

thanks! but I don't know how to install the medusa package in DSM 7... In Package Center do I choose manual install? It asks me for a file that I don't have... I have the zip file but that's not it... sorry i'm such a newbie :x

**Comment by p0psicles** [comment]
I think we can close this issue. People should still be able to find it if closed. And else i've made a small remark on DSM7 in the readme.
