### ISSUE TITLE
Wrong fanart size in Chrome/FF for android

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#973]
@p0psicles @Thraxis  @OmgImAlexis any idea?

Also 'release name' column is soooooo short and 'snatch' column so large when not needed:
@duramato 

![image](https://cloud.githubusercontent.com/assets/2620870/17945733/7b865a9a-6a1b-11e6-9d17-cac59b28fe57.png)

**Comment by OmgImAlexis** [comment]
This isn't a simple issue. Tagging as low priority for now.

**Comment by fernandog** [comment]
@OmgImAlexis how to make fanart image "start" below menu and not behind menu?

Now the first 50x of the fanart are "behind" the menu. Can't find a way to fix it

**Comment by OmgImAlexis** [comment]
It's because of the jQuery lib backstretch we use. There isn't a simple fix for this so there isn't much we can do right now.

https://github.com/srobbin/jquery-backstretch/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20viewport

**Comment by Thraxis** [comment]
@fernandog Were these all fixed?

I know I move the fanart down 50px or 90px depending on if the submenu is relative or fixed.

**Comment by fernandog** [comment]
Mobile view all good
