### ISSUE TITLE
NFO Export - TVMaze Indexer - Show ID

### ISSUE THREAD

**Issue by bzzbrr** [pymedusa/Medusa#9743]
Hello,

When exporting NFOs, medusa populates both the uniqueid and id fields with the id from the chosen indexer for a given show.  However, since multiple indexers can be used, the id field alone is not meaningful.  Some other software interprets the id field for a TV show as a TVDB id by default, so when a different indexer is used the metadata is interpreted incorrectly.

As far as I can tell, the ID field is deprecated in favor of the unique ID field for this reason, for example [on the Kodi wiki](https://kodi.wiki/view/NFO_files/TV_shows#nfo_Tags).

The relevant code is in [metadata/kodi_12plus.py, line 149](https://github.com/pymedusa/Medusa/blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/metadata/kodi_12plus.py#L149). 

**Would it be possible to either not include the id field in the NFO, only include it when TVDB is the indexer, or make it configurable?** 

Thanks for the great software.

**Comment by p0psicles** [comment]
i'll implement the uniqueid's in the next release.
example of how it will look:
```xml
<tvshow>
  <title>Space Force</title>
  <year>2020</year>
  <plot>On June 18, 2018 the federal government announced the creation of a 6th major division of the United States Armed Forces. The Goal of the new branch is "to defend satellites from attack" and "perform other space-related tasks." Or something. This is the story of the men and women who have to figure it out.</plot>
  <episodeguide>
    <url cache="auth.json" post="yes">https://api.thetvdb.com/login?{"apikey":"asdf","id":368667}|Content-Type=application/json</url>
  </episodeguide>
  <mpaa>TV-MA</mpaa>
  <uniqueid default="true" type="tvdb">368667</uniqueid>
  <uniqueid default="false" type="tmdb">85922</uniqueid>
  <uniqueid default="false" type="imdb">tt9612516</uniqueid>
  <uniqueid default="false" type="tvmaze">40445</uniqueid>
  <genre>Comedy</genre>
  <country>United States</country>
  <premiered>2020-05-29</premiered>
  <studio>Netflix</studio>
  <actor>
    <name>Steve Carell</name>
    <role>Mark R. Naird</role>
    <thumb>https://www.thetvdb.com/banners/person/296970/5ebc05b4a0e81.jpg</thumb>
  </actor>
  <actor>
    <name>John Malkovich</name>
    <role>Adrian Mallory</role>
    <thumb>https://www.thetvdb.com/banners/person/300400/5ebc0644c7253.jpg</thumb>
  </actor>
  <actor>
    <name>Tawny Newsome</name>
    <role>Angela Ali</role>
    <thumb>https://www.thetvdb.com/banners/person/505880/5ebc0677959a1.jpg</thumb>
  </actor>
  <actor>
    <name>Jimmy O. Yang</name>
    <role>Chan Kaifang</role>
    <thumb>https://www.thetvdb.com/banners/person/514361/5ebb1a2354368.jpg</thumb>
  </actor>
  <actor>
    <name>Ben Schwartz</name>
    <role>F. Tony Scarapiducci</role>
    <thumb>https://www.thetvdb.com/banners/person/285161/5ebc061e93933.jpg</thumb>
  </actor>
  <actor>
    <name>Diana Silvers</name>
    <role>Erin Naird</role>
    <thumb>https://www.thetvdb.com/banners/person/542843/5ebc059ec6789.jpg</thumb>
  </actor>
</tvshow>
```

**Comment by p0psicles** [comment]
@bzzbrr do you have any idea on how to use the episodeguide tag with indexers like tvmaze and tmdb? As for now, we only pass the tvdb's url.

**Comment by p0psicles** [comment]
implement in #9745

**Comment by bzzbrr** [comment]
> 
> 
> @bzzbrr do you have any idea on how to use the episodeguide tag with indexers like tvmaze and tmdb? As for now, we only pass the tvdb's url.

I do not, sorry.  Some research suggests that sonarr removed the tag entirely since it was buggy and dependent on APIs that are constantly in flux.

I greatly appreciate making the change so quickly.  Lastly, I noticed that the kodi legacy export uses the kodi 12+ code for setting ID.  Personally I think an ID with no indexer type has no value, so this is fine, but it could break someone's workflow if they only use TVDB with some software that doesn't support uniqueid.

Thanks again!

**Comment by bzzbrr** [comment]
Am I crazy, or do you need to both delete the existing NFOs and force a full show update in order to generate new NFOs?  Without deleting, I see updated file access, but the \<id\> tag remains and it's missing the 3 new \<uniqueid\> tags.

**Comment by p0psicles** [comment]
Yeah have to delete it
