### ISSUE TITLE
How to download 720p only if x265?

### ISSUE THREAD

**Issue by papampi** [pymedusa/Medusa#9751]
I want Medusa to download 720p only if x265 else download SD
I set custom quality as below:

```
Allowed Qualities: | SDTV, SD DVD, 720p HDTV
Preferred Qualities: | 720p HDTV
```

And Search Settings as below:

```
Undesired words: "720p x264" "720p h264"
Preferred words: "720P x265" "720P h265"
Require words: "720P x265" "720P h265" "x264" "h264"
```

Is it correct?

**Comment by papampi** [comment]
Why not accepting this:

`2021-07-24 14:43:42 INFO	FORCEDSEARCHQUEUE-BACKLOG-328577 :: Eztv :: [9b23c72] Ignoring Good.Girls.S04E15.720p.HEVC.x265-MeGusta.EZTV based on required words filter: ['x264', 'h264', '720p HEVC x265', '720p x265']
`

**Comment by p0psicles** [comment]
Because it needs to match `all` of those required words

**Comment by papampi** [comment]
Thanks for feedback.
But in "Require words" section its written:

> results must include at least one word from this list

So I removed Require words and changed settings to:

```
Undesired words: 720p x264, 720p h264
Preferred words: x265, 720p, HEVC, 720p x265, 720p HEVC x265
```

Looks like its working.

**Comment by p0psicles** [comment]
that also has it's downsides. Like for example. the first releases don't have x265 in it. Then it will will accept without x265. A day later an x265 release comes out. But it won't upgrade anymore, cause it's quality has been satisfied.

**Comment by papampi** [comment]
So its better to add "720p x264" to Ignore words instead of undesired?

**Comment by papampi** [comment]
And also set preferred to 720p?

**Comment by papampi** [comment]
I was reading Quality Settings wiki and noticed there is no x265/h265 profiles there.

It would be so good if we could have 720p-x265 and 1080p-x265 in default quality settings.

**Comment by papampi** [comment]
Most of older hardwares couldn't handle x265 compression but nowadays almost all can handle it pretty well and its becoming so popular.

**Comment by p0psicles** [comment]
Yeah I understand. But how Medusa's qualities are organised it's not that easy to fit in. As we already have qualities that are resolution + source. That would mean you now will get resolution + source + encoding

**Comment by papampi** [comment]
OK, Thanks.
So I tried multiple ignored and preferred words.
Is there anyway to add set of words in ignored or preferred? 

For example if I add "720p.WEB.H264" to ignored section it only ignore releases with the exact words but if I add "720p WEB H264" "720p H264"  "720p + H264" "720p & H264" ... it wont ignore.

There are so many release and releases provide different file names so we should keep checking and adding the new name formats all the time

**Comment by papampi** [comment]
Couchpotato (RIP) used to have the sets option too

> Required:
> Example: DTS, AC3 & English
> Release should contain at least one set of words. Sets are separated by "," and each word within a set must be separated with "&"
> 
> Ignored:
> Ignores releases that match any of these sets. (Works like explained above)

**Comment by BenjV** [comment]
x264 and x265 are not quality qualifiers but compression standards and adding combinations of quality and compression would be asking for endless combinations of qualifiers.

**Comment by medariox** [comment]
I think everything has been said.
