### ISSUE TITLE
Post Processing giving me constant warning due to hidden "/downloads/.medusa" folder

### ISSUE THREAD

**Issue by twiz-git** [pymedusa/Medusa#9752]
```
*	Transmission folder settings
Incomplete Downloads:	/media/downloads/.temp
Finished Downloads:	/media/downloads/
*	Medusa
Search Settings -> Torrent Search -> Downloaded files location:	/media/downloads/.medusa
Post-Processing -> Post-Processing -> Post-Processing Dir:	/media/downloads/.medusa
General -> Misc -> Show root directories:			/media/tv/
```

I understand normally there could be a problem with the Download Dir and Post-Processing Dir being the same location, but in my case there is none. Transmission downloads the files to `../.temp` and only moves them to `../.medusa` when they're completed, so there are no files for Medusa to post-process until the download is complete. But every time the post-processer runs, it gives the the warning:
`2021-07-25 23:31:02 WARNING	POSTPROCESSOR :: [xxxxx] Missed file: /media/downloads/.medusa: Hidden or ignored folder`

**Comment by medariox** [comment]
Using a hidden folder as post-processing dir is not allowed.

**Comment by twiz-git** [comment]
Is there any reason why?
It has been working, and without any noticeable problem, so it is possible...

**Comment by medariox** [comment]
No specific reason, we just think it makes no sense. You can submit a PR and we will consider changing it, but with any guarantees the change is going to be accepted.

**Comment by p0psicles** [comment]
Probably someone in the past made sure hidden folders where not considered. So that they could exclude them from being processed
