### ISSUE TITLE
Failed to start following power outage

### ISSUE THREAD

**Issue by PaloloWeather** [pymedusa/Medusa#9787]
**Describe the bug**
After a power outage caused my DS118 to reboot, the package cannot open with message "Failed to Start." Was working fine just a couple hours ago.

**To Reproduce**
1. Open Package Center
2. Scroll to Medusa
2. Click "Repair"
3. Error message - "Failed to run the package service. Package would not start! See: /var/log/packages/medusa.log"

**Expected behavior**
Medusa should launch.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Synology DSM 7 - rtd1296 (armv8) (aarch64?)
 - Branch: master
 - Commit: ?
 - Python version: 3.8
 - Database version: ?

**Debug logs (at least 50 lines):**
Can't access medusa logs without launching the package, correct?

**Additional context**
This is what the /var/log/packages/medusa.log shows:
2021/08/12 09:12:43 start medusa 2.0 Begin start-stop-status start
PID file: /volume1/@appdata/medusa/medusa.pid already exists. Exiting.
2021/08/12 09:12:58 start medusa 2.0 End start-stop-status start ret=[3]
2021/08/12 09:12:59 (system) trigger medusa 2.0 Begin start-stop-status stop
/var/packages/medusa/scripts/start-stop-status: line 66: kill: (2560) - No such process
2021/08/12 09:13:20 (system) trigger medusa 2.0 End start-stop-status stop ret=[0]

**Comment by p0psicles** [comment]
I think you should remove the pid file

**Comment by PaloloWeather** [comment]
Please forgive my ignorance, but how do I do that?

**Comment by p0psicles** [comment]
You'll have to login to your Nas using ssh. Then you'll have to navigate to the pid file location and remove it. rm /volume1/@appdata/medusa/medusa.pid

But maybe there is a better solution? I'm not a Synology user. 

@BenjV what would you do here?

**Comment by BenjV** [comment]
You are correct the pidfile has to be removed it is located here.

> /volume1/@appstore/medusa/var/medusa.pid

He has to login to the commandline and remove that file.
Enable terminal service and ssh in the control panel.
Install putty on your pc and login to the Nas on port 22 with your admin account
Give this command:

> rm /volume1/@appstore/medusa/var/medusa.pid

Thereafter you should be able to start medusa again.
The only alternative would be to remove medusa, reinstall medusa and rollback the latest backup of the database and config.

**Comment by PaloloWeather** [comment]
Thank you! Those instructions were super helpful. The only thing I had to adjust was to use "**sudo** rm /volume1/@appdata/medusa/medusa.pid" instead of just "rm" - even logged in as admin I still had "permission denied" initially. Back up and running now. Really appreciate the help!
