### ISSUE TITLE
Docker container not updated to 0.5.16

### ISSUE THREAD

**Issue by Tailslide** [pymedusa/Medusa#9798]
**Describe the bug**
Docker container not updated with release 0.5.16

**To Reproduce**
1. Go to https://registry.hub.docker.com/r/pymedusa/medusa/tags?page=1&ordering=last_updated
2. See last updated was 20 days ago.

**Expected behavior**
New docker container

**Comment by BenjV** [comment]
Why would you need an updated container?
Just update medusa from within medusa itself

**Comment by Tailslide** [comment]
Just following the instructions. Also picking update doesn’t seem to work on the docker version.

![7F8F5271-D8B2-4A2A-B9F7-461F94648BE5](https://user-images.githubusercontent.com/5757188/129493056-c0ea57b2-1d6a-46d9-96dd-ae34b2d29b37.jpeg)

**Comment by p0psicles** [comment]
No, you should always update your container. Updating from within container won't work, as there is no git availbale.

I'll push for a new release tomorrow. You can try that one.

**Comment by BenjV** [comment]
Would it not better to add git to the docker container?

**Comment by p0psicles** [comment]
No its really bad practice to manually change a docker state. You want the state of your container to be predictable for various reasons.

**Comment by Tailslide** [comment]
FYI container still not updated if you click the link at the top of this thread.

**Comment by medariox** [comment]
Should all be updated to latest version now.
