### ISSUE TITLE
Medusa not able to find episodes - have to manually import them

### ISSUE THREAD

**Issue by farffy** [pymedusa/Medusa#9832]
I've noticed that Medusa will not find new episodes, even when I manually search for them through Medusa.  If I log into my NZB site and do a search, I can find the episodes right away.  Why does Medusa fail to find the episodes when I can find them right away myself?

I've enabled debug logging and performed a manual search for an example tv show, log is here:
https://pastebin.com/PCT1mPJt

Medusa could not find any episodes, but if I log into my provider, they are readily available

**Comment by p0psicles** [comment]
You should enable debug logs and restart, then run a manual search and post logs. 
What's an example release name you expect to find? 
99÷ chance you need a scene exception

**Comment by farffy** [comment]
new pastebin:
https://pastebin.com/xgRmZegE

Quality is set to HD on Medusa, so it is finding the release, but not grabbing it?

**Comment by p0psicles** [comment]
So the show your looking for is `body cam`. Guessit is picking the word cam up as a source tag. 

Add scene exception `body` and try again
