### ISSUE TITLE
24h time format working in half of places

### ISSUE THREAD

**Issue by sebeksd** [pymedusa/Medusa#9833]
**Describe the bug**
When configured to use 24h time format there are many places that use 12h time format.

**To Reproduce**
Set time format to 24h (screen 1).
Also setting "Use system defaults" for time make date to appear twice in some places (screen 2):

**Expected behavior**
Time to be in 24h format everywhere.

**Screenshots**
Configuration:
![image](https://user-images.githubusercontent.com/18705953/131623429-0141b22b-0b8e-4020-8c98-3dfb5fd1bdd7.png)
After enabling system time format:
![image](https://user-images.githubusercontent.com/18705953/131623755-904502d0-345b-4d1b-9f95-882380312818.png)

Wrong time format, on show description:
![image](https://user-images.githubusercontent.com/18705953/131625066-76f6ece7-5b12-4d91-acd0-d11eacb33878.png)

Wrong time format, on schedule:
![image](https://user-images.githubusercontent.com/18705953/131625244-1d90fdd7-7e43-4640-b271-cb907156cc74.png)

**Medusa (please complete the following information):**
Medusa Info: 
Branch: master
Commit: 6bfdb2236003331e639a1845f765ee0462ae8a5d
Version: 0.5.19
Database: 44.18
Python Version:  3.8.10 (default, May 6 2021, 06:30:44) [GCC 9.3.0]
SSL Version: OpenSSL 1.1.1l 24 Aug 2021
OS: Linux-5.10.0-0.bpo.9-amd64-x86_64-with
Locale: en_US.UTF-8
Timezone: CET

**Debug logs (at least 50 lines):**
Not needed

**Additional context**
None

**Comment by sebeksd** [comment]
Bump

**Comment by p0psicles** [comment]
Just missed it

**Comment by sebeksd** [comment]
To refresh it a little, same issue happens on 0.5.22

**Comment by p0psicles** [comment]
I couldn't reproduce the double date on the `Air date` column. What is your configured date and time format?

**Comment by sebeksd** [comment]
Just tested,  "Use system defaults" now work correctly, it was probably fixed, maybe when this table was vuefied?

Main reason for this issue report was 24h not being used, and it is still true.
This are places that I found right now, not sure if there is more:
on show page, top header
![image](https://user-images.githubusercontent.com/18705953/170061405-b7e70c66-85c2-4ff3-990d-60512eeb6ae1.png)
release calendar
![image](https://user-images.githubusercontent.com/18705953/170061740-8a0c893d-4f59-4358-85dd-5fbc596645cf.png)

**Comment by p0psicles** [comment]
Fixed
