### ISSUE TITLE
Folder Permission Issues On Creation

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#9838]
**Describe the bug**
For some odd reason on my Synology when i add a new show the owner of the folder is root and not the User of the NAS.

**Medusa (please complete the following information):**
 - OS: DSM 6.2.3-25426 Update 3
 - Branch: Master
 - Commit: fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
 - Python version: 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
 - Database version: 44.18

medusa running in docker. 

I do not know why this not working and due to this the files that are getting processed are not taking the permissions as well.

**Comment by p0psicles** [comment]
What is the ownership of the shows root folder?

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

It is the user that i have setup. I do think this is the issue i have found. How do i change this in Docker please:

![image](https://user-images.githubusercontent.com/24679555/132029601-e24d74c9-5066-4b69-aebc-1514cd6d98cb.png)

**Comment by p0psicles** [comment]
Can you do a ls -al on the shows root folder?

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

drwxrwxrwx+ 218 User root 12288 Sep  2 20:14 Shows

And here is a show i added via medua

drwx------    2 root     root   4096 Sep  2 20:08 Gold Rush Winter's Fortune

**Comment by p0psicles** [comment]
If you change the ownership of your root dit to your medusa user, new folders beneath it should Enherit that

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

Where do i change this in medusa as the user in medusa is root from the screenshot i provided. I do have PID & UID Setup on my docker. I have not had this issue before it just started as i had to do an new install of docker etc...

**Comment by p0psicles** [comment]
Ow wait. I had to re-read your setup. 
Your setup is not something I've tested myself. 
I would Recommend using benjv Synology package. And not docker. Docker has its quirks. 

Else as a test you could ssh into your Synology. And use the cli to set ownership of that directory to your desired user. Like `chown user:user /folder/to/shows`

But this is really experimental.

**Comment by HPMSGEN8** [comment]
Thanks @p0psicles 

So it is better to use the Package on Synology then the Docker Install from you guys ?

**Comment by p0psicles** [comment]
Check our wiki for Synology. 
Yeah, I know that someone was looking running docker with user rights. But don't know the status of that. But you could still try the chown command. I even think you will need to run this anyway also with the syno pckage

**Comment by HPMSGEN8** [comment]
Thanks @p0psicles 

I do not know why docker does not want to work and inherit the rights once the folder is created via medusa. 

Thanks again will check the wiki :)

**Comment by p0psicles** [comment]
Well again. Don't think it's docker. But folder  ownership

**Comment by HPMSGEN8** [comment]
I have installed this now and the file rights are now:

drwxrwxrwx+   2 sc-medusa medusa  4096 Sep  4 10:57

![image](https://user-images.githubusercontent.com/24679555/132089002-eb897262-b97b-4742-8440-3bb1ce05d5cc.png)

So it is taking the user in medusa and adding it to the created folders. So now i need to find out how to get docker to change to the correct user and not use root.

**Comment by BenjV** [comment]
sc-medusa is the internal system user and cannot be used to grant permission to from the DSM gui.
So the package creates a group called sc-download and you must grant permission to the group sc-download to the show folder.

**Comment by HPMSGEN8** [comment]
Hi @BenjV 

Thanks but sc-download does have rights that is not the issue. When medusa creates the folder on the drive it is creating it as the medusa User. I.E in Docker for me ROOT and via the package sc-media.

If it is ROOT then the Permissions do not flow down to all the files. if sc-media then it seems this is working. 

so i am trying to see now how to get this fixed.

**Comment by BenjV** [comment]
I was talking about a normal installation of medusa on a Synology Nas with my Medusa package.
Most likely you are using a very old version of sickbeard-custom because that (if I remember correctly) used both the groups sc-download and sc-media and as user sc-sickbeard-custom.

Anything in a docker I cannot help you with, I would suggest to ask the creator of that docker.
Or just don't use docker and use my medusa package for DSM 6

**Comment by HPMSGEN8** [comment]
Hi @BenjV 

I am using your package will be moving over all my settings this weekend and will see if this solves the issue. So far from what i tested it is taking the rights on my Synology.

Keep you posted.

**Comment by HPMSGEN8** [comment]
Solved
