### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: NHK G	

### ISSUE THREAD

**Issue by RomainGoncalves** [pymedusa/Medusa#9846]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-5.10.52-v7l+-armv7l-with-debian-10.10`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@fbd43ad634662f2353739391127fc77e00454b78
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-08-26 15:52:03 ERROR    MAIN :: [fbd43ad] Missing time zone for network: NHK G	
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@f35a19da6bc4efcafff8facca6a4d5b9e3f3f501
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-12-09 16:51:55 ERROR    MAIN :: [f35a19d] Missing time zone for network: NHK G	
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@dd0b95038397b50db5d404a972f6202ddb932556
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-02-11 10:44:31 ERROR    MAIN :: [dd0b950] Missing time zone for network: NHK G	
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-05-03 17:40:38 ERROR    MAIN :: [e4870f8] Missing time zone for network: NHK G	
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-05-25 21:23:05 ERROR    MAIN :: [e4870f8] Missing time zone for network: NHK G	
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
