### ISSUE TITLE
Medusa not processing any special episodes

### ISSUE THREAD

**Issue by Psyfer9983** [pymedusa/Medusa#9864]
I cannot get Medusa to process any special episodes. I have renamed the files to match what they should be auto named to and other different combinations but nothing works to get them processed. I have tried every scraper that Medusa offers (delete show then re-add it with new scraper) and even put the files in the correct place and named and it will not find them when doing a file check. Medusa used to process special episodes. Has that feature been removed?

I have also looked at everything that I could find about this issue but still cannot get it work with special episodes.

**Comment by Psyfer9983** [comment]
Forgot to add what I have it running on.

System: Synology DS1813+ on DSM 6 (all packages up to date)

Medusa give the following for the episodes in questions: "Processing failed: This show isn't in your list, you need to add it before post-processing an episode"

**Comment by Psyfer9983** [comment]
Found the issue. The show in question had an episode number change for some of the special episodes. That is now working.

New question, does Medusa have the option of updating episode numbers if/when the scraper database gets updated?

**Comment by p0psicles** [comment]
Already fixed in the develop branch.

**Comment by Psyfer9983** [comment]
Ok, is there an easy way to change branches or is it an uninstall/reinstall. Also, if it is a reinstall, what's the branch url?

**Comment by p0psicles** [comment]
Easiest is to use git checkout.

**Comment by Psyfer9983** [comment]
Well, I used the Synology package installer. What's the correct url for the develop branch.

**Comment by p0psicles** [comment]
I'll release it. Don't know if the build in checkout works on the Synology package

**Comment by medariox** [comment]
I suggest to wait for the new release.

**Comment by Psyfer9983** [comment]
Yeah, I don't want to go through the hassle of a reinstall. I guess we don't have an ETA for the release? Been going through all my shows and doing updates to the ones that are missing episodes, art, etc...

**Comment by Psyfer9983** [comment]
Just letting you know the new update is working great with specials episodes. Thanks!
