### ISSUE TITLE
Euphoria (US) 2019 specials are not recognised by post- processing

### ISSUE THREAD

**Issue by refelian** [pymedusa/Medusa#9873]
I have been trying for the whole day to get the post processor to pick this up without success. All attempts end up in:

`Processing failed: This show isn't in your list, you need to add it before post-processing an episode`

It only happens to the specials. I have tried:
Euphoria.US.S00E01.mkv
Euphoria (US) S00E01.mkv
Euphoria (US) (2019) S00E01.mkv
Euphoria.S00E01.mkv
Euphoria US S00E01.mkv
Euphoria S00E01.mkv

Season 1 works when presented with Euphoria.US.S01E01.mkv etc

I am running 0.5.17 on Ubuntu (x86-64)

**Comment by medariox** [comment]
Fixed with the new release.
