### ISSUE TITLE
Docker container not updated to 0.5.18

### ISSUE THREAD

**Issue by Tailslide** [pymedusa/Medusa#9877]
Describe the bug
Docker container not updated with release 0.5.18

To Reproduce

Go to https://registry.hub.docker.com/r/pymedusa/medusa/tags?page=1&ordering=last_updated
See last updated was a month ago.
Expected behavior
New docker container

Not sure if the docker container is supposed to be released automatically when I get the "Pull the latest Docker image and rebuild your container to update" message or if I'm supposed to wait some period of time before trying.

**Comment by p0psicles** [comment]
Oow yeah that's broken.

**Comment by rasmusbe** [comment]
Might be worth looking into an github action that builds the image to the github container registry as well.

See https://codesalad.dev/blog/push-to-github-container-registry-using-github-actions-7 for reference.

**Comment by Tailslide** [comment]
FWIW, this docker image seems to update automatically maybe its easier to point people there instead.
https://github.com/linuxserver/docker-medusa/releases
https://hub.docker.com/r/linuxserver/medusa

**Comment by medariox** [comment]
Yes, we need to automate it since Docker Hub removed the possibility for free users.

**Comment by coops1967** [comment]
> FWIW, this docker image seems to update automatically maybe its easier to point people there instead.
> https://github.com/linuxserver/docker-medusa/releases
> https://hub.docker.com/r/linuxserver/medusa

That's the Pymedusa image I used before on my Synology.. worked fine. 
I changed over to the official Pymedusa githiub source anyway... because it's the official source.
@sigh@

I'll just wait around and see if it gets sorted... 0.5.17 is working ok after all.
;-)

**Comment by p0psicles** [comment]
Should be fixed now.
Docker builds are automated now.
There is one change though.
We don't use the tag `latest` anymore. We use `develop` in stead. So you'll have `master` for the releases and `develop` which will point to the develop branch.

We do recommend to use the `pymedusa/medusa` image as that has some additional checks build in to make sure you don't accidentally update from within the container.
