### ISSUE TITLE
Deprecation Warning Call set_torrent_stop_at_ratio to Deluge

### ISSUE THREAD

**Issue by neo-neo1** [pymedusa/Medusa#9896]
When Medusa snatches torrents to Deluge with any number besides `0` set in `Seed ratio` under `Provider Options & Feel` results in Deluge showing the below Depreciated warning call error (error taken from Deluge logs). My Deluge log file is polluted and overfilled with this same error anytime a torrent is snatched.

```
/usr/lib/python3/dist-packages/deluge/core/rpcserver.py:326: DeprecationWarning: Call to deprecated function set_torrent_stop_at_ratio.

  ret = self.factory.methods[method](*args, **kwargs)

/usr/lib/python3/dist-packages/deluge/core/rpcserver.py:326: DeprecationWarning: Call to deprecated function set_torrent_stop_ratio.

  ret = self.factory.methods[method](*args, **kwargs)
```

**Medusa**
- Docker: linuxserver/medusa:latest
- Branch: master
- Version: 0.5.18
- Database: 44.18
- OS: Armbian Linux-5.4.142-odroidxu4-armv7l-with
- Python Version: 3.8.10 (default, May  6 2021, 06:30:44)  [GCC 9.3.0]
- SSL Version: OpenSSL 1.1.1l  24 Aug 2021
- Locale: en_US.UTF-8
- Timezone: EDT

**Deluge**
- Docker: linuxserver/deluge:latest
- deluged 2.0.3-2-201906121747-ubuntu18.04.1
- OS: Armbian Linux-5.4.142-odroidxu4-armv7l-with
- libtorrent: 1.1.5.0
- Python: 3.6.9

**Comment by p0psicles** [comment]
Your right, the api command needs to be upgraded to: `set_torrent_options`. Only thing is that I can't see from wich version this can be used. As soon as I know that, i'll try to update it.

**Comment by p0psicles** [comment]
https://forum.deluge-torrent.org/viewtopic.php?f=8&t=56055
