### ISSUE TITLE
PID file: /volume1/@appdata/medusa/medusa.pid already exists. Exiting.

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#9902]
**Describe the bug**

**To Reproduce**
1. Shutdown synology
2. start synology
3. See error:
2021/09/22 02:08:06	start medusa 2.0 Begin start-stop-status start
PID file: /volume1/@appdata/medusa/medusa.pid already exists. Exiting.
2021/09/22 02:08:10	start medusa 2.0 End start-stop-status start ret=[3]
2021/09/22 02:08:10	(system) trigger medusa 2.0 Begin start-stop-status stop

<html>
<body>

Medusa Info: | Branch: masterCommit: 21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6Version: 0.5.18Database: 44.18
-- | --
Python Version: | 3.8.11 (default, Aug 31 2021, 16:12:39) [GCC 7.3.0]
SSL Version: | OpenSSL 1.1.1l 24 Aug 2021
OS: | Linux-4.4.180+-x86_64-with-glibc2.2.5
Locale: | en_US.UTF-8
Timezone: | PDT
  |  
  |  
User: | sc-medusa
Program Folder: | /volume1/@appstore/medusa/src
Config File: | /volume1/@appdata/medusa/config.ini
Database File: | /volume1/@appdata/medusa/main.db
Cache Folder: | /volume1/@appdata/medusa/cache
Log Folder: | /volume1/@appstore/medusa/var/Logs
Arguments: | -q --daemon --pidfile=/volume1/@appdata/medusa/medusa.pid --datadir=/volume1/@appdata/medusa --port=8897

</body>
</html>

**Debug logs (at least 50 lines):**
no log since Medusa can't start since PID file is present.

</details>

**Additional context**
Must be a right problem, but i can't fix it myself.
When i delete the PID file with winscp (root login), i can start Medusa

**Comment by BenjV** [comment]
If you running my DSM7 package then download an install the new version(1.4) of my Medusa package to fix this problem.
[](https://github.com/BenjV/SYNO-packages)

**Comment by ward0** [comment]
@BenjV i downloaded https://github.com/BenjV/SYNO-packages/blob/master/Medusa%201.4%20Python%203%20noarch.spk and tried to install, i get 'invalid file format, contact developer'.

**Comment by BenjV** [comment]
That is the version for DSM 6.
If you are running DSM 7 you need to download the DM 7 version.

**Comment by ward0** [comment]
@BenjV Thank you for your work! restarted DSM and Medusa is auto running again, thx!
