### ISSUE TITLE
can't access network drive

### ISSUE THREAD

**Issue by steveschow** [pymedusa/Medusa#9911]
I had this working before and I'm not really sure what I changed, but now suddenly Medusa is not seeing my windows network drive.  I had already previously configured the Medusa service to run as my normal windows account...and it had been working fine for quite a long time.

As of now I have Medusa running as service by me, I have a directory sym link created, which as me, I can enter and see the network drive, etc  But when I go to try to use the Manual Post Processing in Medusa and attempt to navigate into this symlinked network drive, it will not open up the folder in Medusa.  It used to.  

![Screen Shot 2021-09-26 at 2 53 02 PM](https://user-images.githubusercontent.com/9116800/134823830-3242eb10-f497-43a4-be46-d0fbab137614.jpg)

I've tried to type in the complete path name also, but doesn't matter I just get an error message when I try to run post processing manually...and so no post processing is happening now.

![Screen Shot 2021-09-26 at 2 53 39 PM](https://user-images.githubusercontent.com/9116800/134823834-e908aaa1-48cb-424a-ac95-11fdb1532ec0.jpg)

**Comment by p0psicles** [comment]
It's an issue with your directory rights.

**Comment by p0psicles** [comment]
Then it has something to do with the user the Medusa process is running with. 

Medusa hasn't changed.

**Comment by steveschow** [comment]
Medusa is running as me, same as sabnzbd

**Comment by medariox** [comment]
@steveschow Did you read this? https://github.com/pymedusa/Medusa/wiki/Medusa-Windows-Installer#network-drive-mappings

**Comment by steveschow** [comment]
Yes.  
Already tried that to ensure Medusa is running as me rather then admin
