### ISSUE TITLE
Scene Colomn Settings Not Saving?

### ISSUE THREAD

**Issue by neo-neo1** [pymedusa/Medusa#9921]
We're able to customize episode columns but no ability to save? I uncheck columns but it's only temporally. Leaving the page and coming back resets the settings.

[Screenshot of episode column settings which does not save](https://i.imgur.com/DRiXhfw.png)

_Yes,[ i've looked through settings](https://github.com/pymedusa/Medusa/wiki/Scene-exceptions-and-numbering) and see no mention of this? [All my anime, scene, and absolute options are disabled](https://i.imgur.com/rjM0oTH.png)_ 

**Use case:** Scene and absolute numbering is only useful for a small amount of shows. No reason to globally show it for everything as default.

**Comment by p0psicles** [comment]
I just tested it and it works fine here.
That should just store it in a cookie when you check/uncheck it.

Maybe clear your cookies for medusa?

**Comment by neo-neo1** [comment]
It being stored in a cookie would explain it not saving since I open Medusa inside of Organizr v2 which uses iFrame. Tested without and it works properly. 

Too bad it's not stored in the config file instead.

**Comment by medariox** [comment]
@neo-neo1  I've added you to the collaborators group. You should be able to edit the Wiki now. It was restricted because people tried to sneak affiliate links.

**Comment by neo-neo1** [comment]
> @neo-neo1 I've added you to the collaborators group. You should be able to edit the Wiki now. It was restricted because people tried to sneak affiliate links.

Thanks, the [respective page has been updated](https://github.com/pymedusa/Medusa/wiki/Scene-exceptions-and-numbering) regarding settings saved in cookies for others who encounter the same issue. Will also update the wiki in the future as I fine tune my configuration.
