### ISSUE TITLE
Dockerbased Medusa Shows dB-Backup question when checking for update

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#9935]
**Describe the bug**
As the docker image cannot update inside the container there should be no action other than possibly indicating whether a newer version/image is available. If I remember correct this used to be the way,
The latest version of the docker image however shows the question about a dB backup like the normal Medusa installation.
This looks like a regression in detecting whether the app is run in a container. 

**To Reproduce**
1. Go to 'tools-> check for update‘

**Expected behavior**
Info about possible update, no actions however. 

**Screenshots**
![2F5C6AE7-C723-4310-BF63-DFF7A94A34B3](https://user-images.githubusercontent.com/869637/136696979-dd34ac0d-dcf5-407b-8b4b-b23f38d14d95.jpeg)

**Medusa (please complete the following information):**
- Version: latest medusa:master docker

**Debug logs (at least 50 lines):**
N/A

**Additional context**
N/A

**Comment by p0psicles** [comment]
Which docker image are you using?

**Comment by udochrist** [comment]
pymedusa/medusa:master in the latest version.
