### ISSUE TITLE
Not enough quality settings

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#9942]
Hello,

I was just starting testing medusa, and I just discovered, that it has lack of some quality settings. Because of this some of my downloads are getting messed up.
At the moment medusa accepts:

![image](https://user-images.githubusercontent.com/3207791/137230095-2c08020d-693f-46d8-bd9a-deae4f2031c9.png)

And 4k-8k

However, some trackers use BREMUXs, which is not a RIP file in reality, although this won't be much of an issue.
On the other side, not having the quality BRDISK, or FULLBLURAY is killing myself. Some trackers upload directly the full disk, without MKV format, and naming the torrent with this standard. I do not really need FULL BLURAYS to be downloaded, but medusa is identifying them as Blurays 1080. Can we have a new quality category being created like BR-DISK as sonarr does? Once this category is created my jackett setup will replace whatever Full stuff of my trackers with that wording, so that medusa won't take it.

Kind regards

**Comment by medariox** [comment]
How are we going to distinguish them from regular Blu-ray 1080p releases?

**Comment by elpedriyo** [comment]
Fulls, will have in the name the word: full bluray:

![image](https://user-images.githubusercontent.com/3207791/137368674-d4667882-0466-4808-b65e-389df309730c.png)
